### ISSUE TITLE
Crashing miranda ng when using NVDA screenreader and opening/closing chatwindows.

### ISSUE THREAD

**Issue by grishakonzalaev** [miranda-ng/miranda-ng#1001]
### Expected behavior
I want to open and close chat windows normally without crashes.

### Actual behavior
if I quickly close chat window with contact or group chat room, I get crash.
It happens very seldom on stable versions.

### Does it work in stable version?
stable versions better than developers. Stable versions has more seldom crashes.

### Steps to reproduce that behavior
it's need windows10 to reproduce this.
if I quickly close chat window with contact or group chat room, I get crash.
It happens very seldom on stable versions.
I will attach crashreport with debugsymbols.
[mirandareport.txt](https://github.com/miranda-ng/miranda-ng/files/1388788/mirandareport.txt)

**Comment by georgehazan** [comment]
Yes, it's a known problem in NVDA. it embeds some code into Miranda, and after that normally working dialog crashes in some random places inside Windows. Perhaps a solution can be found at our forums, some people recommended a replacement.
