### ISSUE TITLE
MSN: 

### ISSUE THREAD

**Issue by theultramage** [miranda-ng/miranda-ng#1005]
> Your MSN account e-mail is unverified. Goto http://www.passport.com and verify the primary e-mail first.
> Yes / No

This pops up every now and then. Pressing Yes or No has no effect, it just closes the popup. The site www.passport.com is defunct. Logging into my microsoft (hotmail) account, everything seems to be in order.

**Comment by dartraiden** [comment]
Protocol is deprecated.
