### ISSUE TITLE
0.95.7 IRC / tabsrmm group chat colors regression

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#1010]
### Expected behavior
Text color and text background color in IRC should be displayed correctly, as in 0.95.6.

### Actual behavior
With the dev build, most colors and backgrounds were not correctly displayed. Leading to an IRC bot outputting white text on white background, etc.

### Does it work in stable version?
Yes. I compared 0.95.6 with 0.95.7 from around 10.10.2017.

### Steps to reproduce that behavior
Load 0.95.7 and make sure 'strip colors from messages in the log' is disabled. Join an IRC channel and have a separate account output various color and background combinations.

### Edit: Conclusion after testing
So where are we at? It looks like 0.95.6 can *receive* IRC color codes fine, but not send them. 0.95.7 can neither send nor receive them. When receiving colored text/background, 0.95.7 reverts to black-on-white or white-on-white, probably unrelated and to do with color settings elsewhere.

**Comment by georgehazan** [comment]
can you provide a concrete profile with a temporary IRC account for testing?

**Comment by Tharn** [comment]
0.95.7 stable still shows the same issue I was originally reporting. This fix made it into the latest release, right?

![untitled-1](https://user-images.githubusercontent.com/13466852/32528011-009f304c-c431-11e7-9818-779eda3af651.png)

**Comment by dartraiden** [comment]
OK, seems like 1d0b695 didn't help. Reopened.

**Comment by georgehazan** [comment]
@Tharn then you still need to provide a profile for testing

**Comment by Tharn** [comment]
@georgehazan I did. There's a link underneath the picture.

**Comment by georgehazan** [comment]
ouch.... sorry, I overlooked it... *SHAME*
thanks

**Comment by georgehazan** [comment]
@Tharn so can you join #miranda-bugs channel to demonstrate this problem? 
or which channel must I join to see it

**Comment by Tharn** [comment]
@georgehazan It works like this: https://en.wikichip.org/wiki/irc/colors

Ctrl-k number comma number text. No spaces. Number 1 is foreground, 2 is background.

**Comment by georgehazan** [comment]
that's not a problem. I easily create a colored message in HexChat, but it's not sent to server, all another clients in this room receive nothing but a text

**Comment by Tharn** [comment]
I tested all the color combinations. Looks like everything works. Feel free to close this!
