### ISSUE TITLE
libcurl doesn't have SSL support

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1018]
> [23:56:19]	ghazan: у нас кстати полная задница в libcurl
> [23:56:33]	ghazan: он почему-то собран без ssl
> [23:58:22]	ghazan: отчего его можно юзать только для ftp :)

**Comment by Goraf** [comment]
https://curl.haxx.se/docs/faq.html#curl_1_SSL_is_disabled_https
