### ISSUE TITLE
Add saving state of the opened tabs in TabSRMM to restore them after restart Miranda

### ISSUE THREAD

**Issue by ghsrcgh** [miranda-ng/miranda-ng#1019]
Please add saving state of the opened tabs in TabSRMM.

How it will work?
1) When you opening any tab, current state of the tabs (order, opened state) is saved to DB.
2) When you close any tab, current state of the tabs is saved to.
3) If Miranda is crashed or closed (during update or just manually by user, when you restart it, Miranda will load previous state of TabSRMM tabs from the DB.

So, you will not require to reopen favorite users for a common chatting.

**Comment by Mataes** [comment]
use plugin Sessions https://wiki.miranda-ng.org/index.php?title=Plugin:Sessions/en
