### ISSUE TITLE
statusmanager plugin can't work with windows xp (crash with exception)

### ISSUE THREAD

**Issue by BLF0x** [miranda-ng/miranda-ng#1020]
statusmanager plugin can't work with windows xp (crash with exception)

**Comment by georgehazan** [comment]
what about a crash log?

**Comment by BLF0x** [comment]
how i can see crash log ?

**Comment by georgehazan** [comment]
https://wiki.miranda-ng.org/Crash_reports

------ Original Message ------

**Comment by BLF0x** [comment]
Thanx ! But crashlog absent. When i open menu "Settings" i see error window: Entry point not found
exception Processing Message c0000138 Parameters 1d0 16cf48 75b3bf7c 75b3bf7c
when i press OK this window close...

**Comment by georgehazan** [comment]
first, you need the CrashDumper plugin

**Comment by BLF0x** [comment]
when open miranda i see that exception window. on the header window  is:
History++ MainWindow: miranda32.exe -- entry point not found

Crashdumper plugin isinstalled

**Comment by georgehazan** [comment]
you have the old h++ plugin from Miranda IM, remove it and replace with the proper one from our site via Plugin Updater -> Add missing components

**Comment by BLF0x** [comment]
Miranda Crash Report from 8 Nov 2017 15:37:26. Crash Dumper v.0.0.5.2

Likely cause of the crash plugin: Skype protocol (Web)

Exception: Access Violation at address 7C9109D8. Reading from address FFFFFFFF.

Stack Trace:
---------------------------------------------------------------
7C9109D8 (ntdll 7C900000): (filename not available) (0): wcsncpy
7C91080B (ntdll 7C900000): (filename not available) (0): wcsncpy
78AB016A (MSVCR100 78AA0000): (filename not available) (0): free
1262ADAF (mir_core 12620000): (filename not available) (0): mir_free
1700E12F (SkypeWeb 17000000): (filename not available) (0): (function-name not available)
1701CE34 (SkypeWeb 17000000): (filename not available) (0): (function-name not available)
12498C3B (mir_app 12480000): (filename not available) (0): Proto_ChainSend
1262A7FA (mir_core 12620000): (filename not available) (0): NotifyEventHooks
124A73FB (mir_app 12480000): (filename not available) (0): mir_main
8B5614EC ((module-name not available) 00000000): (filename not available) (0): (function-name not available)

CPU: Intel(R) Core(TM)2 CPU 4400 @ 2.00GHz [x86 Family 6 Model 15 Stepping 2] [2 CPUs]
Installed RAM: 3584 MBytes
Microsoft Windows XP Professional Service Pack 3 (build 2600)
Internet Explorer: 8.0.6001.18702 (build 86001)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian

Miranda NG Version: 0.95.6 build #18515 (f85295208e)
Build time: 1 Nov 2017 13:29:46
Profile: C:\QIP\Profiles\7573181\7573181.dat (dbx mmap driver)
Language pack: Russian (RU) [0419]
Service Mode: No

Active Plugins (23):
¤ AdvaImg.dll v.0.11.0.2 [1 Nov 2017 13:30:34] - Miranda image services 
¤ AVS.dll v.0.95.3.4 [1 Nov 2017 13:29:48] - Avatar service 
¤ Clist_modern.dll v.0.9.1.7 [1 Nov 2017 13:30:10] - Modern contact list 
¤ CrashDumper.dll v.0.0.5.2 [1 Nov 2017 13:30:10] - Crash dumper 
¤ DbEditorPP.dll v.4.0.1.1 [1 Nov 2017 13:30:12] - Database editor++ 
¤ Dbx_mmap.dll v.0.95.3.1 [1 Nov 2017 13:29:50] - Miranda NG mmap database driver 
¤ Facebook.dll v.0.3.3.2 [1 Nov 2017 13:30:10] - Facebook RM 
¤ HistoryPP.dll v.1.5.1.5 [24 Sep 2017 22:15:24] - History++ 
¤ ICQ.dll v.0.11.3.5 [1 Nov 2017 13:29:52] - IcqOscarJ protocol 
¤ IEView.dll v.1.5.0.1 [1 Nov 2017 13:29:58] - IEView 
¤ Import.dll v.0.95.4.3 [1 Nov 2017 13:29:48] - Import contacts and messages 
¤ MenuEx.dll v.1.3.0.10 [1 Nov 2017 13:29:58] - Menu item ext 
¤ MessageState.dll v.0.0.1.0 [1 Nov 2017 13:30:44] - Message state 
¤ MobileState.dll v.0.0.1.6 [1 Nov 2017 13:30:18] - Mobile state 
¤ MRA.dll v.2.1.1.1 [1 Nov 2017 13:30:04] - Mail.ru Agent 
¤ PluginUpdater.dll v.0.1.2.5 [1 Nov 2017 13:30:14] - Plugin updater 
¤ SeenPlugin.dll v.5.0.5.3 [1 Nov 2017 13:30:00] - Last seen 
¤ SkypeWeb.dll v.0.12.2.4 [1 Nov 2017 13:30:48] - Skype protocol (Web) 
¤ SmileyAdd.dll v.0.2.4.1 [1 Nov 2017 13:30:04] - SmileyAdd 
¤ TabSRMM.dll v.3.5.0.6 [1 Nov 2017 13:29:58] - TabSRMM 
¤ TopToolBar.dll v.0.8.0.4 [1 Nov 2017 13:30:06] - TopToolBar 
¤ UInfoEx.dll v.0.8.5.0 [1 Nov 2017 13:30:08] - User info ext 
¤ VKontakte.dll v.0.1.2.23 [1 Nov 2017 13:30:38] - VKontakte protocol 

Loaded Modules:
-------------------------------------------------------------------------------
C:\QIP\qip.exe  00400000 - 00409000 v.0.95.6.18515 [1 Nov 2017 13:29:46]
C:\WINXP\system32\ntdll.dll  7C900000 - 7C9B5000 v.5.1.2600.7013 [30 Jan 2016 6:22:18]
C:\WINXP\system32\kernel32.dll  7C800000 - 7C8F9000 v.5.1.2600.7013 [30 Jan 2016 6:22:18]
C:\WINXP\system32\USER32.dll  7E360000 - 7E3F1000 v.5.1.2600.5512 [26 Dec 2009 9:03:40]
C:\WINXP\system32\GDI32.dll  77F10000 - 77F5A000 v.5.1.2600.6973 [9 Dec 2015 2:13:42]
C:\QIP\MSVCR100.dll  78AA0000 - 78B5F000 v.10.0.40219.325 [6 Aug 2017 13:57:14]
C:\WINXP\system32\IMM32.DLL  76360000 - 7637D000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\ADVAPI32.dll  77DC0000 - 77E6C000 v.5.1.2600.6987 [17 Dec 2015 21:59:08]
C:\WINXP\system32\RPCRT4.dll  77E70000 - 77F03000 v.5.1.2600.6477 [7 Nov 2013 8:38:06]
C:\WINXP\system32\Secur32.dll  77FE0000 - 77FF1000 v.5.1.2600.5834 [26 Dec 2009 8:51:58]
C:\Program Files\Prio\prio.dll  10000000 - 10005000 v.1.9.8.1536 [31 Mar 2008 13:28:32]
C:\QIP\libs\mir_app.mir  12480000 - 12546000 v.0.95.6.18515 [1 Nov 2017 13:29:44]
C:\WINXP\system32\WINMM.dll  76B20000 - 76B4E000 v.5.1.2600.6160 [14 Oct 2011 17:47:28]
C:\WINXP\system32\SHLWAPI.dll  77F60000 - 77FD7000 v.6.0.2900.6540 [26 Mar 2014 6:17:50]
C:\WINXP\system32\msvcrt.dll  77C00000 - 77C58000 v.7.0.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\WinSxS\x86_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.2600.6028_x-ww_61e65202\COMCTL32.dll  773C0000 - 774C3000 v.6.0.2900.6028 [23 Aug 2010 19:12:36]
C:\WINXP\system32\WS2_32.dll  71A90000 - 71AA7000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\WS2HELP.dll  71A80000 - 71A88000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\UxTheme.dll  5B260000 - 5B298000 v.6.0.2900.5512 [26 Dec 2009 8:58:42]
C:\WINXP\system32\COMDLG32.dll  76380000 - 763C9000 v.6.0.2900.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\SHELL32.dll  7C9C0000 - 7D1DC000 v.6.0.2900.6880 [29 Jul 2015 19:17:50]
C:\WINXP\system32\ole32.dll  774D0000 - 7760E000 v.5.1.2600.7013 [30 Jan 2016 6:22:18]
C:\QIP\libs\zlib.mir  12740000 - 12758000 v.1.2.11.0 [1 Nov 2017 13:29:36]
C:\QIP\libs\mir_core.mir  12620000 - 12640000 [1 Nov 2017 13:29:38]
C:\WINXP\system32\VERSION.dll  77BF0000 - 77BF8000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\serwvdrv.dll  5D270000 - 5D277000 v.5.1.2600.0 [15 Apr 2008 13:00:00]
C:\WINXP\system32\umdmxfrm.dll  5B590000 - 5B597000 v.5.1.2600.0 [15 Apr 2008 13:00:00]
C:\Program Files\Punto Switcher\pshook.dll  08000000 - 08020000 v.4.3.6.1853 [1 Mar 2017 19:00:52]
C:\WINXP\system32\imagehlp.dll  76C80000 - 76CA9000 v.5.1.2600.6479 [13 Nov 2013 6:00:06]
C:\WINXP\system32\api-ms-win-core-synch-l1-2-0.dll  00A80000 - 00A83000 v.10.0.10586.15 [25 Aug 2016 23:13:16]
C:\WINXP\system32\MSCTF.dll  746E0000 - 7472C000 v.5.1.2600.6727 [22 Jan 2015 4:45:48]
C:\WINXP\system32\msctfime.ime  75310000 - 7533E000 v.5.1.2600.5768 [26 Dec 2009 8:51:22]
C:\QIP\Plugins\CrashDumper.dll  15060000 - 15070000 v.0.0.5.2 [1 Nov 2017 13:30:10]
C:\WINXP\system32\dbghelp.dll  59C60000 - 59D01000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\QIP\Plugins\Import.dll  15E00000 - 15E0D000 v.0.95.4.3 [1 Nov 2017 13:29:48]
C:\QIP\Plugins\Dbx_mmap.dll  15220000 - 15231000 v.0.95.3.1 [1 Nov 2017 13:29:50]
C:\QIP\Plugins\DbEditorPP.dll  151E0000 - 151FD000 v.4.0.1.1 [1 Nov 2017 13:30:12]
C:\QIP\Core\stdcrypt.dll  13080000 - 1308B000 v.0.95.6.18515 [1 Nov 2017 13:29:40]
C:\QIP\Core\stdssl.dll  13180000 - 13187000 v.0.95.6.18515 [1 Nov 2017 13:29:40]
C:\WINXP\system32\CRYPT32.dll  77A70000 - 77B08000 v.5.131.2600.6459 [7 Oct 2013 14:00:00]
C:\WINXP\system32\MSASN1.dll  77B10000 - 77B22000 v.5.1.2600.5875 [26 Dec 2009 8:51:20]
C:\WINXP\system32\WSOCK32.dll  71AB0000 - 71ABA000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\Msftedit.dll  4B460000 - 4B4E6000 v.5.41.15.1515 [15 Apr 2008 13:00:00]
C:\QIP\Plugins\AdvaImg.dll  14900000 - 14990000 v.0.11.0.2 [1 Nov 2017 13:30:34]
C:\QIP\MSVCP100.dll  78050000 - 780B9000 v.10.0.40219.325 [6 Aug 2017 13:57:14]
C:\QIP\Plugins\Clist_modern.dll  14D60000 - 14DD0000 v.0.9.1.7 [1 Nov 2017 13:30:10]
C:\WINXP\WinSxS\x86_Microsoft.Windows.Gdiplus_6595b64144ccf1df_1.0.6002.23846_x-ww_f7dfd05e\gdiplus.dll  4EBE0000 - 4ED8B000 v.5.2.6002.23846 [12 Nov 2015 1:51:02]
C:\WINXP\system32\MSIMG32.dll  76350000 - 76355000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\QIP\Plugins\AVS.dll  14B80000 - 14B92000 v.0.95.3.4 [1 Nov 2017 13:29:48]
C:\QIP\Plugins\Facebook.dll  15380000 - 153CF000 v.0.3.3.2 [1 Nov 2017 13:30:10]
C:\QIP\libs\libjson.mir  12460000 - 1246C000 [1 Nov 2017 13:29:48]
C:\QIP\Plugins\HistoryPP.dll  15780000 - 1596F000 v.1.5.1.5 [24 Sep 2017 22:15:24]
C:\WINXP\system32\oleaut32.dll  77110000 - 7719B000 v.5.1.2600.6688 [26 Nov 2014 18:16:52]
C:\WINXP\system32\winspool.drv  72FC0000 - 72FE6000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\RICHED20.DLL  74DF0000 - 74E5D000 v.5.30.23.1230 [15 Apr 2008 13:00:00]
C:\QIP\Plugins\ICQ.dll  15CA0000 - 15CF2000 v.0.11.3.5 [1 Nov 2017 13:29:52]
C:\QIP\Plugins\IEView.dll  15DA0000 - 15DBD000 v.1.5.0.1 [1 Nov 2017 13:29:58]
C:\QIP\Plugins\MenuEx.dll  16160000 - 1616E000 v.1.3.0.10 [1 Nov 2017 13:29:58]
C:\QIP\Plugins\MessageState.dll  16180000 - 16187000 v.0.0.1.0 [1 Nov 2017 13:30:44]
C:\QIP\Plugins\MobileState.dll  163E0000 - 163E6000 v.0.0.1.6 [1 Nov 2017 13:30:18]
C:\QIP\Plugins\MRA.dll  16400000 - 1645D000 v.2.1.1.1 [1 Nov 2017 13:30:04]
C:\QIP\Icons\xStatus_MRA.dll  13DE0000 - 13DF3000 [8 Nov 2017 0:06:48]
C:\QIP\Plugins\PluginUpdater.dll  16A20000 - 16A34000 v.0.1.2.5 [1 Nov 2017 13:30:14]
C:\QIP\Plugins\SeenPlugin.dll  16EC0000 - 16ECE000 v.5.0.5.3 [1 Nov 2017 13:30:00]
C:\QIP\Plugins\SkypeWeb.dll  17000000 - 17046000 v.0.12.2.4 [1 Nov 2017 13:30:48]
C:\QIP\Plugins\SmileyAdd.dll  170A0000 - 170BE000 v.0.2.4.1 [1 Nov 2017 13:30:04]
C:\QIP\Plugins\TabSRMM.dll  173A0000 - 17423000 v.3.5.0.6 [1 Nov 2017 13:29:58]
C:\QIP\Plugins\TopToolBar.dll  175E0000 - 175ED000 v.0.8.0.4 [1 Nov 2017 13:30:06]
C:\QIP\Plugins\UInfoEx.dll  176E0000 - 17732000 v.0.8.5.0 [1 Nov 2017 13:30:08]
C:\QIP\Plugins\VKontakte.dll  17800000 - 1783C000 v.0.1.2.23 [1 Nov 2017 13:30:38]
C:\QIP\Core\stdauth.dll  13000000 - 13007000 v.0.95.6.18515 [1 Nov 2017 13:29:40]
C:\QIP\Core\stdfile.dll  130C0000 - 130CF000 v.0.95.6.18515 [1 Nov 2017 13:29:42]
C:\QIP\Core\stdhelp.dll  130E0000 - 130E6000 v.0.95.6.18515 [1 Nov 2017 13:29:40]
C:\QIP\Core\stdidle.dll  13100000 - 13107000 v.0.95.6.18515 [1 Nov 2017 13:29:40]
C:\WINXP\system32\WTSAPI32.dll  76F40000 - 76F48000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\WINSTA.dll  76330000 - 76340000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\NETAPI32.dll  5BD50000 - 5BDA6000 v.5.1.2600.6260 [6 Jul 2012 16:58:22]
C:\QIP\Core\stdautoaway.dll  13020000 - 13026000 v.0.95.6.18515 [1 Nov 2017 13:29:40]
C:\QIP\Core\stduseronline.dll  131E0000 - 131E6000 v.0.95.6.18515 [1 Nov 2017 13:29:40]
C:\QIP\Core\stdaway.dll  13040000 - 13048000 v.0.95.6.18515 [1 Nov 2017 13:29:40]
C:\Program Files\Ruslat95\kbHook.dll  02D20000 - 02D33000 [8 Feb 2011 13:44:32]
C:\WINXP\system32\CLBCATQ.DLL  76FC0000 - 7703F000 v.2001.12.4414.700 [15 Apr 2008 16:00:00]
C:\WINXP\system32\COMRes.dll  037E0000 - 038B5000 v.2001.12.4414.700 [26 Dec 2009 9:01:40]
C:\WINXP\system32\oleacc.dll  61880000 - 618BA000 v.7.0.2600.6153 [26 Sep 2011 11:41:20]
C:\WINXP\system32\appHelp.dll  77B30000 - 77B52000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\shdocvw.dll  03B30000 - 03CF7000 v.6.0.2900.5512 [26 Dec 2009 9:02:52]
C:\WINXP\system32\CRYPTUI.dll  76650000 - 766E4000 v.5.131.2600.5512 [26 Dec 2009 9:01:42]
C:\WINXP\system32\WININET.dll  3F9E0000 - 3FAC7000 v.8.0.6001.23797 [21 Jan 2016 22:31:38]
C:\WINXP\system32\Normaliz.dll  03D10000 - 03D19000 v.6.0.5441.0 [7 Jan 2009 18:20:36]
C:\WINXP\system32\urlmon.dll  45020000 - 45155000 v.8.0.6001.23797 [21 Jan 2016 22:31:38]
C:\WINXP\system32\iertutil.dll  40080000 - 4026D000 v.8.0.6001.23797 [21 Jan 2016 22:31:36]
C:\WINXP\system32\WINTRUST.dll  76C20000 - 76C4E000 v.5.131.2600.6285 [24 Aug 2012 16:53:08]
C:\WINXP\system32\WLDAP32.dll  76F50000 - 76F7D000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\mydocs.dll  723F0000 - 7240B000 v.6.0.2900.5512 [26 Dec 2009 9:02:32]
C:\Program Files\ArcSoft\Software Suite\PhotoImpression 5\share\pihook.dll  03D40000 - 03D4E000 [4 Jul 2002 9:38:00]
C:\WINXP\system32\ntshrui.dll  76970000 - 76996000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\ATL.DLL  76B00000 - 76B11000 v.3.5.2284.2 [26 Dec 2009 8:51:00]
C:\WINXP\system32\USERENV.dll  769A0000 - 76A55000 v.5.1.2600.6689 [6 Dec 2014 10:29:08]
C:\Program Files\WinSCP\DragExt.dll  03DB0000 - 03DEA000 v.1.2.1.3970 [21 Jan 2014 13:18:30]
C:\WINXP\System32\mswsock.dll  71A30000 - 71A70000 v.5.1.2600.5625 [26 Dec 2009 8:51:38]
C:\WINXP\system32\DNSAPI.dll  76F10000 - 76F37000 v.5.1.2600.6089 [3 Mar 2011 9:53:36]
C:\WINXP\system32\iphlpapi.dll  76D50000 - 76D69000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\rasadhlp.dll  76FB0000 - 76FB6000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\hnetcfg.dll  698B0000 - 69908000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\System32\wshtcpip.dll  71A70000 - 71A78000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\schannel.dll  767D0000 - 767F9000 v.5.1.2600.6926 [24 Sep 2015 2:52:40]
C:\WINXP\system32\credssp.dll  59E00000 - 59E07000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\rsaenh.dll  68000000 - 68039000 v.5.1.2600.6924 [22 Sep 2015 0:55:04]
C:\WINXP\system32\dssenh.dll  68100000 - 68129000 v.5.1.2600.6924 [22 Sep 2015 0:55:04]
C:\WINXP\System32\winrnr.dll  76FA0000 - 76FA8000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\wshbth.dll  75000000 - 7501E000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\SETUPAPI.dll  77910000 - 77A04000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\MLANG.dll  75DA0000 - 75E31000 v.6.0.2900.5512 [15 Apr 2008 13:00:00]

**Comment by georgehazan** [comment]
yes, but h++ doesn't load anything from Miranda32.exe :-)

**Comment by BLF0x** [comment]
Когда ошибка происходит оно в краш не падает... Т.е. выскакивает окно с ошибкой, его можно закрыть и все дальше работает, но Statusmanager не подключен в плагинах (т.е. ошибка при загрузке статусменеджера, как я понимаю)
H++ отключал... не помогает... миранду обратно переименовывал в miranda32 -- не помогает...
Если удалить statusmanager -- ошибка пропадает.
Ошибка появляется при загрузке и при открытии настроек. (т.е. когда идет обращение к плагину)

**Comment by georgehazan** [comment]
а если проапдейтиться на вчерашний релиз?

**Comment by BLF0x** [comment]
вчерашний релиз миранды или плагина ? плагины я все релизы опробовал =)

**Comment by georgehazan** [comment]
миранду можно только целиком апдейтить, иначе оно начинает падать

**Comment by BLF0x** [comment]
это которая альфа ? сейчас попробую =)

**Comment by georgehazan** [comment]
нет, это которая стабля. вчера был очередной релиз
апдейтиться надо только через Plugin Updater

**Comment by BLF0x** [comment]
Да, спасибо -- помогло =)
Еще вопрос -- можно как то укрупнить кнопку отправки сообщений ? а то мышкой иногда если копипаст делаешь -- надо прицеливаться ? в идеале чтоб можно было просто свою картинку нужного размера под кнопку подставить (оно есть, но он уменьшает пиктограммы до нужного ему размера)

**Comment by georgehazan** [comment]
если только растянуть подвал вверх
