### ISSUE TITLE
TabSRMM: can't save template changes

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1023]
![2017-11-09_23h26_37](https://user-images.githubusercontent.com/5046855/32628032-866b3066-c5a5-11e7-81bf-8cc2dc414fcf.png)

changes can be saved (and I see changes in message log) only until restart
after restart all my changes are gone

**Comment by BLF0x** [comment]
Аналогичная проблема была... Исправил через "костыль" -- прописав нужные темплейты через database editor

**Comment by Tharn** [comment]
Can confirm that it does this. I found a workaround by exporting -> importing a theme.
