### ISSUE TITLE
Jabber does not auto-rejoin to groups after internet reconnection

### ISSUE THREAD

**Issue by ghsrcgh** [miranda-ng/miranda-ng#1026]
Jabber does not auto-rejoin to groups after internet reconnection

1) Channel (group) is not added to bookmarks
2) But channel is opened in TabSRMM window, i.e. it was an active channel (group)

Just after reconnection is staying offline and empty users/group.

**Comment by dartraiden** [comment]
Yes, we talked about this 2 days ago

> 
[15:31:17] <ghazan> я только не очень понимаю, что с ней делать, потому что все списки джойнов стираются при выходе

**Comment by georgehazan** [comment]
no chances, in Miranda that is technically impossible.
use bookmarks if you want to reconnect rooms automatically
