### ISSUE TITLE
History++ is enabling Conversations and Bookmarks sub-window every time you opening history

### ISSUE THREAD

**Issue by ghsrcgh** [miranda-ng/miranda-ng#1027]
History++ is enabling Conversations and Bookmarks sub-window every time you opening history.

It had started from a some version near aug-sep-oct 2017. This bug does not appear before.

Steps to reproduce:
Just open history for any user. You will see that Conversations and Bookmarks sub-windows are enabled (opened)... by default! Even if you will close them, then close a history of the user and re-open history of the user, they will be enabled (opened) again!

Two bugs:
1) They are enabled by default
2) You cannot save disabled state of them!

**Comment by georgehazan** [comment]
will be available in the development build tomorrow, the stable will receive this fix when it will be reuploaded next time
