### ISSUE TITLE
There is no any description of Sessions plugin in Miranda NG wiki (neither Russian nor English)

### ISSUE THREAD

**Issue by ghsrcgh** [miranda-ng/miranda-ng#1028]
There is no any description of Sessions plugin in Miranda NG wiki (neither Russian nor English):
https://wiki.miranda-ng.org/index.php?title=Plugin:Sessions/ru
https://wiki.miranda-ng.org/index.php?title=Plugin:Sessions/en

You just do not know **what** it is really doing. **How to find it and how to understand it purpose**, if you do not know anything about it and there is no any description?

See example in ticket #1019

**Comment by dartraiden** [comment]
Done.
