### ISSUE TITLE
[0.95.7 x64] Crash on router disconnect

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#1029]
My router disconnects regularly once a day. Just as it happened, Miranda crashed. The program is still on the stable channel, build no. `18770 (fe9623059e)`. Here's the log:

[crash.txt](https://github.com/miranda-ng/miranda-ng/files/1469577/crash.txt)

**Comment by dartraiden** [comment]
Create [log with debug symbols](https://wiki.miranda-ng.org/index.php?title=Crash_reports), please.

**Comment by Tharn** [comment]
Okay, now I'll just have to wait for it to happen again. In the meanwhile, would the .mdmp help?

**Comment by georgehazan** [comment]
no, it's useless. I need just .txt

**Comment by Tharn** [comment]
I found an easy way to reproduce this. When the network is available but the router has no successful internet connection, Miranda crashes instantly upon launching the program. This is with Status Manager set to auto-online several accounts.

**Comment by dartraiden** [comment]
I got different behavior:

- plug out Internet cable from router
"Network" icon in tray still OK
- launch Miranda, StartupStatus trying go to Online, all Miranda (and clist) clist hang up
- if Miranda launched after some time (when "Network" icon in tray have exclamation mark) - all OK

**Comment by georgehazan** [comment]
@Tharn so could you provide a crash log with symbols?

**Comment by Tharn** [comment]
I have symbols installed on both machines, it's just a waiting game now.

**Comment by Tharn** [comment]
It has not happened since. Maybe chalk this one up to Tox plugin issues. I will re-open if it happens again.
