### ISSUE TITLE
Irc Plugin Problem, /Peform donst works

### ISSUE THREAD

**Issue by Havokdan** [miranda-ng/miranda-ng#1032]
### Expected behavior
Formerly I used irc in miranda ng and the /Perform command worked, in the latest versions until the last one I tried (95.7) does not work any more as before

### Actual behavior
Does nothing

### Does it work in stable version?
No

### Steps to reproduce that behavior
 Used to give nickserv, ghost and recover commands in irc.

**Comment by georgehazan** [comment]
I use it to give /j commands, and they work pretty good
can you provide a network log for this problem?

**Comment by Havokdan** [comment]
I'm sorry, I used the google translator here, I mean the option that is inside the red rectangle of the image attached to this message. (I deleted my personal data, such as user, password and image channel)
![sem titulo](https://user-images.githubusercontent.com/6549729/32844288-c76d7970-ca00-11e7-821f-45ea223c5000.png)

**Comment by Havokdan** [comment]
Thanks, works.
