### ISSUE TITLE
[Enhancement] Ability to disable TabSRMM mouse wheel smooth scrolling

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#1035]
### Current Behaviour

One Miranda trademark is its speed. Dragging the scroll bar produces a very crisp and fast scrolling behaviour, while using the mouse wheel produces a slightly delayed kind of smooth scrolling. Especially when executing a long scroll this way, the UI will lag behind and finish up to a second after you're done moving the wheel.

### Proposed Enhancement

I would like to see a setting in TabSRMM that allows us to toggle this behaviour off. Smooth scrolling enabled would be the current default. With SS disabled, it should do fast, clean jumps. It should do this without any delay or lag, i.e. immediately as the mouse wheel input arrives.

**Comment by georgehazan** [comment]
this smooth scrolling is controlled by Windows, in Control Panel - System - Advanced Settings - Performance, it has nothing to do with Miranda, cause the tabSRMM window simply handles messages that are sent from Windows controls

**Comment by Tharn** [comment]
But here's the thing: 'smooth scroll list-boxes' seems to work only on the user list. It was *already turned off* for me, and I noticed a big difference in scrolling user list vs. scrolling chat log. I would like the chat log to behave like the user list, but it doesn't. Flipping this setting does not change how the chat log behaves, at least not for me.
