### ISSUE TITLE
Facebook does not work in the newest release of Miranda 0.95.7b18770 (booth 32b and 64b)

### ISSUE THREAD

**Issue by rheingold** [miranda-ng/miranda-ng#1036]
### Expected behavior
The program starting up

### Actual behavior
See screenshot - a lot of windows, never present in facebook, reported as "unknown contact" jumping up, with the error "Unexpected error" and then the plugin disables. If I leave the window up for a while, the plug-in is NOT being disabled.

### Does it work in stable version?
Yes, the actual behavior is exhibited in the stable version as well.

### Steps to reproduce that behavior
> Start Miranda
> Connect into "Online" state of facebook account

![obrazek](https://user-images.githubusercontent.com/10280242/32940138-205d0ec4-cb82-11e7-81f6-e838bba2c7a8.png)

**Comment by georgehazan** [comment]
1. Disable this option
![image](https://user-images.githubusercontent.com/4628541/32940326-615ba618-cb93-11e7-9c16-1aceeb980a7d.png)
2. Leave these three conversations

**Comment by rheingold** [comment]
Quite interesting workaround, however it solved the problem. Thanks

In such a case I hope somebody will be able to pinpoint the root-cause bug causing this.

**Comment by Robyer** [comment]
Cause would be that Facebook changed something related to group chats and plugin must be adapted to work correctly again.

**Comment by rheingold** [comment]
Thanks for your attendance to the problem.

**Comment by Robyer** [comment]
@rheingold I just tried my Miranda and it works. So it means that I can't fix it, until this update is widespread to my FB account too.

**Comment by georgehazan** [comment]
@rheingold my Miranda works too, can you open the Messenger in a browser and check these three group chats? what do you see there?

**Comment by rheingold** [comment]
@Robyer @georgehazan Besides my regular contact chats, there are also some chat-groups I have been attached to some time ago. These are probably the same ones as those causing the problem in Miranda, however while the facebok WWW-UI is showing them correctly, the API most probably does some filtering based on the age of the groups or some kind of status so Miranda cant retreive their meta-data. But in the WWW-UI I can wisit them and their contents is shown without trouble.

**Comment by ThosRTanner** [comment]
I have this too. It started last night for me. As I pretty much only use the multi user chats, and they are now called 'unknown contact' it renders the plugin useless for me :-(

**Comment by Robyer** [comment]
Now I have this issue too so I can look into it.

> I also noticed that if you get this issue it turns off chat in facebook and you have to switch it back on again
You mean on FB website? If you don't want to turn off chat when you turn off Miranda you can change that in Miranda's options.

**Comment by dartraiden** [comment]
@Robyer, also please see https://forum.miranda-ng.org/index.php?topic=192.msg20727#msg20727

**Comment by ThosRTanner** [comment]
@Robyer - yes. when miranda starts up and decides its going to go into a funny state, and closes all the group chat windows, it *also* turns off chat on the facebook website and you have to turn it back on.

Now I've done the workround above, it doesn't do that. but the switching off chat appears to be a side effect of this issue

**Comment by Robyer** [comment]
@dartraiden Yes that's same issue as this one.

I tried to fix it yesterday, but couldn't finish it. I know where the problem is and perhaps how to fix it, but I'm just too irritated and exhausted by the whole Visual Studio and C++ (I'm developing Android apps in Java) and for more than a year I don't even use Miranda at all anymore. I'll try to fix this once again (+ perhaps the duplicated steam messages), but then I'll probably leave Miranda NG completely...

**Comment by Robyer** [comment]
I won't finish this. I am leaving all Miranda NG development today.

If there is any potential contributor, it is good time to show up and take it here from me :-) I can try to help with start, how to understand the FB communication and it's inner working, etc.

I was already contacted by one guy who will try to fix it perhaps during next 1-2 weeks or so. But if there is anyone else, join the development too as more contributors means more good for whole Miranda.

Note: I pushed branch with my WIP changes to this issue to have slight idea where to start with fixing it - https://github.com/miranda-ng/miranda-ng/tree/fixFacebookMessages

**Comment by ThosRTanner** [comment]
I think this is also is causing miranda to grab the focus when I get a message. it only happens in facebook group chats and only since the group chats went funny.

**Comment by georgehazan** [comment]
@ThosRTanner @rheingold is the problem with stealing focus actual ?

**Comment by ThosRTanner** [comment]
Yes, And it's _extremely_ annoying.

**Comment by ThosRTanner** [comment]
Did someone jsut do something? I got the latest update today and my group names are back.

**Comment by peci1** [comment]
Seems like @georgehazan is working on this :) https://github.com/miranda-ng/miranda-ng/commit/4244ac9aff45e1e723b17f32b192ce4996ac52c0#diff-396cfa07d25a010cb44bbb5649311394 

The fix works for me, too.

**Comment by georgehazan** [comment]
all problems with chats should go away

**Comment by konto-andrzeja** [comment]
@georgehazan Group chats are fixed for me, thanks! But offline messages still don't work.

**Comment by georgehazan** [comment]
@konto-andrzeja offline messages to chats? or in the private threads?

**Comment by peci1** [comment]
For me, messages received when Miranda was not running do not appear at all after starting it. Maybe that is meant by "offline messages"?

**Comment by konto-andrzeja** [comment]
@georgehazan For me they don't work neither for private conversations nor for group chats. I.e. if somebody sends something to a group chat I'm in or writes to me directly while I'm offline, then after Miranda starts I don't see any messages.

**Comment by ThosRTanner** [comment]
The 'retrieve history' (experimental) setting still seems to be somewhat experimental

**Comment by peci1** [comment]
@ThosRTanner I think it's not what's in question here - the problem I describe (and probably also @konto-andrzeja ) is that I'm not notified when there are *unread* messages when I start Miranda.

**Comment by konto-andrzeja** [comment]
For me the messages that someone sent to me while Miranda was not connected to Facebook are nowhere to be found. There are no notifications, they are not visible in message windows, and not present in the history.

**Comment by zemiacsik** [comment]
Is there any issue left now?

**Comment by konto-andrzeja** [comment]
@zemiacsik I just checked and the offline messages work, I can start using Miranda for fb again! Thanks!

Now the only issue I'm facing is not handling attachments. When I go to Messenger and send some picture or share some link, in Miranda I see "User sent an unsupported attachment. Open your browser to see it.". When someone shares pictures/links with me, the same message appears.

**Comment by zemiacsik** [comment]
@konto-andrzeja Thanks for your feedback, yes there were some changes with attachments so I did some modifications yesterday, please wait for the next update and let me know.

**Comment by konto-andrzeja** [comment]
@zemiacsik Hi, I'm not sure if you're done with those changes you mentioned, but at this point if I go to messenger and attach file, in Miranda I see an empty message.

When somebody else sends me an attachment with some description, I only see the description. It's displayed as a normal message, so unless I go and check on messenger I can miss the fact that something was attached there.

Thanks for the good work! I'm not sure if this is the right place to ask, but is there `donate` button somewhere?

**Comment by konto-andrzeja** [comment]
@zemiacsik For some time there were no major problems with messages except for some attachments still not being displayed in Miranda, but now unfortunately some incoming messages are being omitted. How to reproduce:
1. Open Messenger in web browser.
2. Open chat window in Miranda.
3. Start conversation using chat window in Miranda.
4. Some incoming messages that appear in Messenger do not appear in Miranda. Sometimes they appear after some delay (even a minute or so), sometimes after reconnecting to fb, but some messages are dropped and not displayed at all.

**Comment by zemiacsik** [comment]
Thank you for reporting.
Yes, I have noticed some strange behaviour recently but I thought it is caused by Miranda in general because connection status is/was not showing properly (online when offline and vice versa) and sometimes the connection is lost at all so I was not sure if I am online or not but yes, I have experienced 4. too.
Unfotunately, I have some deadlines atm so I can not look at it now, maybe at the end of this month.

**Comment by konto-andrzeja** [comment]
@zemiacsik Ok, thanks! One more update, maybe it'll help. Yesterday I was talking with someone and his messages were appearing after significant delays (even 2-3 minutes), sometimes appearing multiple times, and then some of them had wrong author (my messages were displayed as his). Really weird stuff. :) Reconnecting to fb usually helps.

**Comment by dartraiden** [comment]
Non-actual, protocol was rewritten from scratch.
