### ISSUE TITLE
Miranda turns sound on again on reboot

### ISSUE THREAD

**Issue by TabajaraLabs** [miranda-ng/miranda-ng#1037]
### Expected behavior
What did you expect?
When I unselect "sounds" on options, I think it will be forever muted

### Actual behavior
What did you get instead?
When I reboot the computer on the next day, sound is activated again

### Does it work in stable version?
If you know in which dev build (or approximate date when) it was broken, it may be much easier to identify and fix the issue.
Version 0.95.8 alpha build #18795 x64

### Steps to reproduce that behavior
 * Provide step-by-step instructions so we can reproduce the issue (We can't fix what we can't reproduce).
 * Attach your VersionInfo.
 * Attach a crash report if you are experiencing crashes (It includes VersionInfo as well).
 * Attach a network log captured if you are experiencing connectivity issues.
 * If Miranda freezes, hangs up or consumes CPU, attach information obtained by Process Explorer tool.
- Open Miranda-NG
- Options, sounds, untick "enable sound events"
- Exit Miranda, open again
- "enable sound events" is ticked again

Greetings from Brazil!

**Comment by Goraf** [comment]
Can you show us your VersionInfo? I think I saw sth like that lately as a result of some plugin.

**Comment by georgehazan** [comment]
@TabajaraLabs you meant this checkbox?
it works pretty good for me
![image](https://user-images.githubusercontent.com/4628541/33026771-3ee0bd44-ce22-11e7-8353-45a87dbe693f.png)

**Comment by Goraf** [comment]
Now I remember. @georgehazan, it was ZeroNotification that was causing this (not sure if its a cause here). I don't remember the details but it was sth like when you have offline status (global status?) then it will force sounds to be turned on on restart no matter the settings.

**Comment by georgehazan** [comment]
@TabajaraLabs what about your VersionInfo ? can you post it here?

**Comment by TabajaraLabs** [comment]
Sorry for the delay, I was far away from my computer

[spoiler=VersionInfo][quote]CPU: Intel(R) Core(TM) i5 CPU 650 @ 3.20GHz 
[Intel64 Family 6 Model 37 Stepping 2] [DEP Enabled] [4 CPUs]
Installed RAM: 3960 MBytes
Microsoft Windows 7 Professional Edition, 64-bit Service Pack 1 (build 7601)
Internet Explorer: 9.11.9600.18837 (build 99600)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : Portuguese/Portuguese | 
Portuguese/Portuguese
Free disk space on Miranda partition: 186917 MBytes

Miranda NG Version: 0.95.8 alpha build #18807 (81d4a61fb7) x64
Build time: 21 Nov 2017 4:28:58
Profile: C:\Users\Alexandre\AppData\Roaming\Miranda 
NG\Labjara\Labjara.dat (dbx mmap driver)
Profile size: 589824 Bytes
Profile creation date: 26 Oct 2017 1:35:12
Language pack: No language pack installed
Service Mode: No

[b]Active Plugins (14):[/b]
¤ AdvaImg.dll v.[b]0.11.0.2[/b] [9 Nov 2017 4:32:42] - Miranda image 
services
¤ AVS.dll v.[b]0.95.3.4[/b] [16 Nov 2017 4:28:30] - Avatar service
¤ Clist_modern.dll v.[b]0.9.1.7[/b] [16 Nov 2017 4:32:30] - Modern 
contact list
¤ CrashDumper.dll v.[b]0.0.5.2[/b] [16 Nov 2017 4:33:00] - Crash dumper
¤ Dbx_mmap.dll v.[b]0.95.3.1[/b] [21 Nov 2017 4:29:32] - Miranda NG mmap 
database driver
¤ Facebook.dll v.[b]0.3.3.2[/b] [16 Nov 2017 4:31:36] - Facebook RM
¤ GG.dll v.[b]0.11.0.3[/b] [16 Nov 2017 4:28:54] - Gadu-Gadu protocol
¤ ICQ.dll v.[b]0.11.3.6[/b] [16 Nov 2017 4:29:12] - IcqOscarJ protocol
¤ Import.dll v.[b]0.95.4.3[/b] [25 Oct 2017 4:08:20] - Import contacts 
and messages
¤ IRC.dll v.[b]0.95.7.1[/b] [16 Nov 2017 4:29:00] - IRC protocol
¤ Jabber.dll v.[b]0.11.0.5[/b] [16 Nov 2017 4:32:20] - Jabber protocol
¤ PluginUpdater.dll v.[b]0.1.2.5[/b] [21 Nov 2017 4:35:38] - Plugin updater
¤ TabSRMM.dll v.[b]3.5.0.7[/b] [21 Nov 2017 4:30:02] - TabSRMM
¤ TopToolBar.dll v.[b]0.8.0.4[/b] [16 Nov 2017 4:32:00] - TopToolBar

[b]Unloadable Plugins (1):[/b]
¤ DbChecker.dll v.[b]0.0.0.0[/b] [21 Nov 2017 4:35:00] - <unknown>
     Plugin statically linked to missing module: mir_core.mir
     Plugin statically linked to missing module: mir_app.mir
     Plugin statically linked to missing module: VCRUNTIME140.dll


[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
Facebook                 0 - Enabled 0 - Disabled  Loaded
GG                       0 - Enabled 0 - Disabled  Loaded
ICQ                      1 - Enabled 0 - Disabled  Loaded
IRC                      0 - Enabled 0 - Disabled  Loaded
JABBER                   1 - Enabled 0 - Disabled  Loaded
MetaContacts             1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
  Proto_Facebook.dll [16 Nov 2017 4:46:26]
  Proto_GG.dll [16 Nov 2017 4:46:26]
  Proto_ICQ.dll [16 Nov 2017 4:46:26]
  Proto_IRC.dll [16 Nov 2017 4:46:26]
  Proto_Jabber.dll [16 Nov 2017 4:46:26]
  Proto_MetaContacts.dll [21 Nov 2017 4:44:46]
  TabSRMM_icons.dll [21 Nov 2017 4:44:42]
  Toolbar_icons.dll [16 Nov 2017 4:46:24]
  xStatus_ICQ.dll [16 Nov 2017 4:46:26]
  xStatus_Jabber.dll [16 Nov 2017 4:46:26]
[/quote][/spoiler]

Em 21/11/2017 17:28, George Hazan escreveu:

**Comment by georgehazan** [comment]
@TabajaraLabs is this problem still alive?
I can't imagine what might cause it now (previously it was new database format that might not work)
