### ISSUE TITLE
Problem with login into Facebook account

### ISSUE THREAD

**Issue by anetamm** [miranda-ng/miranda-ng#1039]
### Expected behavior
I would like to login into Facebook

### Actual behavior
Application login for second and then logut without any message.

### Does it work in stable version?
Problem occurs today. I use v. 0.95.7 build #18770

### Steps to reproduce that behavior
1. Turn Miranda
2. Try to connect to your facebook account
VersionInfo:
[spoiler=VersionInfo][quote]CPU: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz [Intel64 Family 6 Model 158 Stepping 9] [DEP Enabled] [4 CPUs]
Installed RAM: 8061 MBytes
Microsoft Windows 10 , 64-bit (build 15063)
Internet Explorer: 9.11.15063.0 (build 915063)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : Polish/Polish | Polish/Polish
Free disk space on Miranda partition: 24578 MBytes

Miranda NG Version: 0.95.7 build #18770 (fe9623059e) x64
Build time: 10 Nov 2017 22:01:52
Profile: C:\Users\jahba\AppData\Roaming\Miranda NG\Ja\Ja.dat (dbx mmap driver)
Profile size: 1179648 Bytes
Profile creation date: 28 Jul 2017 7:32:19
Language pack: Polish (PL) [0415]
Service Mode: No

[b]Active Plugins (22):[/b]
¤ AdvaImg.dll v.[b]0.11.0.2[/b] [9 Nov 2017 11:51:08] - Miranda image services 
¤ AIM.dll v.[b]0.11.0.1[/b] [9 Nov 2017 11:49:46] - AIM protocol 
¤ AVS.dll v.[b]0.95.3.4[/b] [9 Nov 2017 11:49:46] - Avatar service 
¤ Clist_modern.dll v.[b]0.9.1.7[/b] [9 Nov 2017 11:50:14] - Modern contact list 
¤ CrashDumper.dll v.[b]0.0.5.2[/b] [9 Nov 2017 11:50:18] - Crash dumper 
¤ Dbx_mmap.dll v.[b]0.95.3.1[/b] [10 Nov 2017 22:01:58] - Miranda NG mmap database driver 
¤ Facebook.dll v.[b]0.3.3.2[/b] [9 Nov 2017 11:50:18] - Facebook RM 
¤ GG.dll v.[b]0.11.0.3[/b] [9 Nov 2017 11:49:58] - Gadu-Gadu protocol 
¤ HistoryPP.dll v.[b]1.5.1.5[/b] [24 Sep 2017 21:15:30] - History++ 
¤ HistoryStats.dll v.[b]0.2.1.1[/b] [9 Nov 2017 11:51:16] - HistoryStats 
¤ ICQ.dll v.[b]0.11.3.5[/b] [9 Nov 2017 11:49:52] - IcqOscarJ protocol 
¤ Import.dll v.[b]0.95.4.3[/b] [9 Nov 2017 11:49:44] - Import contacts and messages 
¤ IRC.dll v.[b]0.11.0.3[/b] [9 Nov 2017 11:49:48] - IRC protocol 
¤ Jabber.dll v.[b]0.11.0.5[/b] [10 Nov 2017 22:02:44] - Jabber protocol 
¤ MSN.dll v.[b]0.14.0.1[/b] [9 Nov 2017 11:50:02] - MSN protocol 
¤ PluginUpdater.dll v.[b]0.1.2.5[/b] [9 Nov 2017 11:50:22] - Plugin updater 
¤ SkypeWeb.dll v.[b]0.12.2.5[/b] [9 Nov 2017 11:51:08] - Skype protocol (Web) 
¤ SmileyAdd.dll v.[b]0.2.4.2[/b] [9 Nov 2017 11:50:02] - SmileyAdd 
¤ StatusManager.dll v.[b]0.11.2.3[/b] [9 Nov 2017 11:51:06] - Status manager 
¤ TabSRMM.dll v.[b]3.5.0.7[/b] [10 Nov 2017 22:02:06] - TabSRMM 
¤ TopToolBar.dll v.[b]0.8.0.4[/b] [9 Nov 2017 11:50:06] - TopToolBar 
¤ WhatsApp.dll v.[b]0.1.3.3[/b] [9 Nov 2017 11:51:06] - WhatsApp protocol 

[b]Unloadable Plugins (1):[/b]
¤ DbChecker.dll v.[b]0.0.0.0[/b] [10 Nov 2017 22:02:30] - <unknown> 
    Plugin statically linked to missing module: mir_core.mir
    Plugin statically linked to missing module: mir_app.mir
    Plugin statically linked to missing module: api-ms-win-crt-string-l1-1-0.dll
    Plugin statically linked to missing module: api-ms-win-crt-runtime-l1-1-0.dll
    Plugin statically linked to missing module: api-ms-win-crt-filesystem-l1-1-0.dll
    Plugin statically linked to missing module: api-ms-win-crt-heap-l1-1-0.dll
    Plugin statically linked to missing module: api-ms-win-crt-time-l1-1-0.dll

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
AIM                      0 - Enabled 0 - Disabled  Loaded
Facebook                 1 - Enabled 0 - Disabled  Loaded
GG                       1 - Enabled 0 - Disabled  Loaded
ICQ                      0 - Enabled 0 - Disabled  Loaded
IRC                      0 - Enabled 0 - Disabled  Loaded
JABBER                   0 - Enabled 0 - Disabled  Loaded
MSN                      0 - Enabled 0 - Disabled  Loaded
SKYPE                    1 - Enabled 0 - Disabled  Loaded
WhatsApp                 0 - Enabled 1 - Disabled  Loaded
MetaContacts             1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 HistoryPP_icons.dll [9 Nov 2017 11:52:12]
 Proto_AIM.dll [9 Nov 2017 11:52:10]
 Proto_Facebook.dll [9 Nov 2017 11:52:10]
 Proto_GG.dll [9 Nov 2017 11:52:12]
 Proto_ICQ.dll [9 Nov 2017 11:52:10]
 Proto_IRC.dll [9 Nov 2017 11:52:10]
 Proto_Jabber.dll [10 Nov 2017 22:04:22]
 Proto_MetaContacts.dll [10 Nov 2017 22:04:22]
 Proto_MSN.dll [9 Nov 2017 11:52:12]
 Proto_Skype.dll [9 Nov 2017 11:52:12]
 Proto_WhatsApp.dll [9 Nov 2017 11:52:12]
 Proto_Yahoo.dll [27 Sep 2016 15:46:04]
 TabSRMM_icons.dll [10 Nov 2017 22:04:22]
 Toolbar_icons.dll [9 Nov 2017 11:52:12]
 xStatus_ICQ.dll [9 Nov 2017 11:52:12]
 xStatus_Jabber.dll [10 Nov 2017 22:04:22]
[/quote][/spoiler]

**Comment by Goraf** [comment]
@anetamm, check if you can login via web browser wihout problems

**Comment by LittleVulpix** [comment]
There was a big cloudflare outage today, many websites were affected and with them also many APIs and services, it's possible it was this - a temporary outage, nothing to do with miranda.

**Comment by anetamm** [comment]
@Goraf, I can login via web browser without problems (I tried with Opera, Vivaldi and Edge). Problem still occurs.

**Comment by Robyer** [comment]
1) Try to install Popup+ or Yapp plugin as there might be some error message in popup you don't see (because you don't have popup service plugin)
2) Capture and look at netlog (https://wiki.miranda-ng.org/index.php?title=Network_log). You can also send it privately to my e-mail (in case there is something private): <my nickname>@seznam.cz

**Comment by anetamm** [comment]
I found the couse of the error.
For few days I used a computer with internet from my cell that was a router (the old router broke down and I was waiting for a new one) and problem was still occurring. Today I am using a new router and the problem doesn't occur.
You can close the topic. Thank you all for the support.
