### ISSUE TITLE
SQLite

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1042]
Spamotron sources contains a very old SQLite (from 2009 year!).

Should we separate SQLite into .dll, update to newest version and use for importing Miranda IM profiles?
Currently Miranda IM users cannot simple upgrade to NG, because Miranda IM use SQLite as default  database driver.

**Comment by georgehazan** [comment]
yes, we should extract sqlite from Spamotron and reuse it in Import to import new format of Miranda IM's database
