### ISSUE TITLE
MySpace smileypack

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1047]
https://github.com/miranda-ng/miranda-ng/blob/master/plugins/SmileyAdd/smileys/nova/MYSPACE.msl
https://github.com/miranda-ng/miranda-ng/tree/master/plugins/SmileyAdd/smileys/nova/MySpace

are we really need this?
Miranda NG doesn't have MySpace support

same for 
https://github.com/miranda-ng/miranda-ng/blob/master/plugins/SmileyAdd/smileys/nova/YAHOO.msl
https://github.com/miranda-ng/miranda-ng/tree/master/plugins/SmileyAdd/smileys/nova/yahoo

**Comment by Goraf** [comment]
If they are on Addons then we could remove them from plugin. If not then we could upload them there and then remove :D

**Comment by georgehazan** [comment]
no, we don't need that
