### ISSUE TITLE
Button for pointing user to the addons.miranda-ng.org

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1048]
Users wants this button. "Get more skins" on _Skins -> Modern Contacts list_, _Skins -> Tipper_, etc.

Also, we can add link to addons.miranda-ng.org on Skins page instead of adding button to Modern, Nicer, Tipper, etc.

**Comment by georgehazan** [comment]
clist_nicer to go

**Comment by Mataes** [comment]
nicer also added in 0112d27
