### ISSUE TITLE
[Security]: memset cannot be used to scrub memory

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1049]
See http://en.cppreference.com/w/cpp/string/byte/memset
> memset may be optimized away (under the as-if rules) if the object modified by this function is not accessed again for the rest of its lifetime. For that reason, this function cannot be used to scrub memory (e.g. to fill an array that stored a password with zeroes). 

All major compilers (VS, GCC, Clang) just ignore memset in Release builds. We should use memset_s or [SecureZeroMemory](https://msdn.microsoft.com/ru-ru/library/windows/desktop/aa366877(v=vs.85).aspx).

Affected code (except 3-party libraries, we should update libraries instead of manual fixing old code):
https://github.com/miranda-ng/miranda-ng/blob/master/plugins/CryptoPP/src/GPGw/gpg_main.cpp#L253
https://github.com/miranda-ng/miranda-ng/blob/master/plugins/TabSRMM/src/sendqueue.cpp#L314
https://github.com/miranda-ng/miranda-ng/blob/master/plugins/Variables/src/parse_str.cpp#L490

**Comment by Goraf** [comment]
Tlen is going out #1050

**Comment by dartraiden** [comment]
Good, because Tlen also contains very old embedded PolarSSL, It's terrible.
