### ISSUE TITLE
Tlen protocol should be moved to deprecated.

### ISSUE THREAD

**Issue by wsx22** [miranda-ng/miranda-ng#1050]
Tlen (tlen.dll) is plugin designed for support Tlen IM protocol that was popular at Poland some years ago.

Now polish owner of tlen protocol - o2.pl company has closed it permanently.
Tlen protocol has been closed officially at May 2016.
Links: [en wiki](https://en.wikipedia.org/wiki/Tlen.pl), [pl](http://www.komputerswiat.pl/nowosci/programy/2016/20/tlen-to-juz-koniec-popularnego-komunikatora.aspx)
It works from miranda some time after that day, with limited functionality, but now it's permanently closed and offline.

So, please move tlen.dll to deprecated too.

**Comment by Mataes** [comment]
done in 6532896
