### ISSUE TITLE
What about "Upload to Dropbox" option in Db_autobackups and SendSS?

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1051]
Dropbox plugin is deprecated. Can CloudFile provide MS_DROPBOX_UPLOAD service?
Or we need temporary remove Dropbox functionality from this plugins?

@aunsane, @White-Tiger?

**Comment by lancev-moedelo** [comment]
I'll realize that service in CloudFile when I have some free time.

**Comment by aunsane** [comment]
@dartraiden, please check after 6d27acd0a57bc6a228f1b6dd2ce451c02cc7419c wil be build.

**Comment by dartraiden** [comment]
Tested on db_autobackups and SendSS. Plugin ask access to Dropbox, create Miranda NG folder inside Apps/Dropbox, but this folder is empty. No backups, no screenshots.

**Comment by aunsane** [comment]
@dartraiden db_autobackups is works on latest nightly https://i.imgur.com/QpyEeYK.png

**Comment by aunsane** [comment]
Db autobackup and Send ScreenShot+ were redesigned to use CloudFile.
