### ISSUE TITLE
Crash (Too large increment) & Database corruption

### ISSUE THREAD

**Issue by unitwobble** [miranda-ng/miranda-ng#1055]
Steps to reproduce:
1) Connecting Jabber to xmpp.jp (DNS timeout) will cause crash and error message (CrashDumper doesn't work):
"Database failure. Miranda will now shut down. (Too large increment)"
2) Database headers will be corrupted (from Miranda NG D... to offset 0x23) like:

example 1:
`4D 69 72 61 6E 64 61 20 4E 47 20 44 34 DD 74 00 01 08 00 00 57 DD 74 00 75 AF 05 00 35 00 00 00 70 33 74`

example 2:
`4D 69 72 61 6E 64 61 20 4E 47 20 44 80 80 74 00 01 08 00 00 A3 80 74 00 C1 62 05 00 34 00 00 00 BE FD 72`

3) Copy header from other profile, Miranda starts.

Update: I ran DBtool to clear history from database. Cannot reproduce the above after history is cleared.

---

CrashDumper Version Info:

CPU: Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz [Intel64 Family 6 Model 58 Stepping 9] [DEP Enabled] [4 CPUs]
Installed RAM: 8150 MBytes
Microsoft Windows 7 Professional Edition, 64-bit Service Pack 1 (build 7601)
Internet Explorer: 8.0.7601.17514 (build 87601)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : English/English | Japanese/Japanese
Free disk space on Miranda partition: 8607 MBytes

Miranda NG Version: 0.95.8 alpha build #18849 (500da0fe0a) [running inside WOW64]
Build time: 28 Nov 2017 11:36:24
Profile: C:\Miranda\Profiles\START2015-09-09\START2015-09-09.dat (dbx mmap driver)
Profile size: 7798784 Bytes
Profile creation date: 23 Feb 2016 9:57:27
Language pack: No language pack installed
Service Mode: No

[b]Active Plugins (12):[/b]
¤ AdvaImg.dll v.[b]0.11.0.2[/b] [25 Nov 2017 21:37:00] - Miranda image services 
¤ AVS.dll v.[b]0.95.3.4[/b] [25 Nov 2017 21:35:00] - Avatar service 
¤ CrashDumper.dll v.[b]0.0.5.2[/b] [25 Nov 2017 21:37:28] - Crash dumper 
¤ DbEditorPP.dll v.[b]4.0.1.2[/b] [25 Nov 2017 21:37:32] - Database editor++ 
¤ Dbx_mmap.dll v.[b]0.95.3.1[/b] [28 Nov 2017 11:36:38] - Miranda NG mmap database driver 
¤ HistoryPP.dll v.[b]1.5.1.5[/b] [28 Nov 2017 11:33:04] - History++ 
¤ Jabber.dll v.[b]0.11.0.5[/b] [28 Nov 2017 11:38:52] - Jabber protocol 
¤ MirOTR.dll v.[b]0.14.1.16[/b] [25 Nov 2017 21:38:46] - Miranda OTR 
¤ OpenSSL.dll v.[b]0.1.0.2[/b] [25 Nov 2017 21:40:00] - OpenSSL SSL API module 
¤ PluginUpdater.dll v.[b]0.1.2.5[/b] [25 Nov 2017 21:37:56] - Plugin updater 
¤ SeenPlugin.dll v.[b]5.0.5.3[/b] [25 Nov 2017 21:36:06] - Last seen 
¤ StatusManager.dll v.[b]0.11.2.3[/b] [25 Nov 2017 21:40:34] - Status manager 

[b]Unloadable Plugins (1):[/b]
¤ DbChecker.dll v.[b]0.0.0.0[/b] [28 Nov 2017 11:43:30] - <unknown> 
    Plugin statically linked to missing module: mir_core.mir
    Plugin statically linked to missing module: mir_app.mir
    Plugin statically linked to missing module: VCRUNTIME140.dll

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
JABBER                   5 - Enabled 1 - Disabled  Loaded
MetaContacts             1 - Enabled 0 - Disabled  Loaded
SKYPE                    0 - Enabled 1 - Disabled  Not Loaded
STEAM                    0 - Enabled 1 - Disabled  Not Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 AlphaMod_AIM_0.0.1.0.dll [16 Nov 2004 21:32:00]
 AlphaMod_ICQ_0.0.1.0.dll [16 Nov 2004 21:32:00]
 AlphaMod_Jabber_0.0.1.0.dll [16 Nov 2004 21:32:00]
 AlphaMod_Miranda_Man_0.0.1.0.dll [16 Nov 2004 21:32:00]
 AlphaMod_MSN_0.0.1.0.dll [16 Nov 2004 21:32:00]
 Global2(Bright Stroke).dll [25 Sep 2005 12:58:36]
 Global3.dll [27 Sep 2005 20:19:34]
 HistoryPP_icons.dll [23 Feb 2010 18:16:26]
 pinguins.dll [1 Oct 2007 14:37:22]
 proto_conn_IRC.dll [12 Sep 2005 20:21:00]
 proto_conn_msn.dll [4 Dec 2004 11:55:00]
 Proto_ICQ.dll [25 Oct 2012 8:01:24]
 Proto_IRC.dll [25 Oct 2012 8:01:25]
 Proto_Jabber.dll [25 Oct 2012 8:01:25]
 Proto_MetaContacts.dll [22 Oct 2017 19:26:30]
 Proto_MSN.dll [4 Mar 2010 15:34:26]
 Proto_Skype.dll [22 Oct 2017 19:26:30]
 Proto_Steam.dll [6 Apr 2015 5:55:20]
 PSI_Jabber.dll [5 Nov 2010 12:26:54]
 xStatus_ICQ.dll [4 Apr 2013 4:05:13]
 xStatus_Jabber.dll [4 Apr 2013 4:05:26]

**Comment by georgehazan** [comment]
That is the extremely rare bug (it happens about once a year), which cannot be reproduced normally. Too bad that you wiped a profile if you could reproduce it...
