### ISSUE TITLE
Gmail Multiple Notifier cannot read RSS

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1057]
[Reported by user](https://forum.miranda-ng.org/index.php?topic=5354)

Last working version is GmailNotifier.dll v.0.3.1.1 [24 Oct 2017 16:41:36].
Error message is "Can't get RSS feed!"

**Comment by georgehazan** [comment]
network log is needed

**Comment by imasuridondai** [comment]
Btw, why GmailMNotifier writes the unencrypted authorization credentials into the log file? I [REMOVED] them manually.

[20:18:58 0D08] [GmailMNotifier] Connection request to mail.google.com:443 (Flags 11)....
[20:18:58 0D08] [GmailMNotifier] (000000000274BA60) Connecting to server mail.google.com:443....
[20:18:58 0D08] [GmailMNotifier] (000000000274BA60) Connecting to ip 74.125.205.83:443 ....
[20:18:58 0D08] [GmailMNotifier] (820) Connected to mail.google.com:443
[20:18:58 0D08] [GmailMNotifier] (820 mail.google.com) Starting SSL negotiation
[20:19:00 0D08] [GmailMNotifier] (820 mail.google.com) SSL negotiation successful
[20:19:00 0D08] [GmailMNotifier] (000000000274BA60:820) Data sent
GET /mail/feed/atom HTTP/1.0
Authorization: Basic [REMOVED]
User-Agent: Miranda/0.95.8.18970 (x64)
Accept-Encoding: deflate, gzip
Host: mail.google.com
Connection: Keep-Alive
Proxy-Connection: Keep-Alive

[20:19:01 0D08] [GmailMNotifier] (000000000274BA60:820) Data received
HTTP/1.0 200 OK
Content-Type: text/xml; charset=UTF-8
Content-Security-Policy: script-src https://clients4.google.com/insights/consumersurveys/ https://www.google.com/js/bg/ 'self' 'unsafe-inline' 'unsafe-eval' https://mail.google.com/_/scs/mail-static/ https://hangouts.google.com/ https://talkgadget.google.com/ https://*.talkgadget.google.com/ https://www.googleapis.com/appsmarket/v2/installedApps/ https://www-gm-opensocial.googleusercontent.com/gadgets/js/ https://docs.google.com/static/doclist/client/js/ https://www.google.com/tools/feedback/ https://s.ytimg.com/yts/jsbin/ https://www.youtube.com/iframe_api https://ssl.google-analytics.com/ https://apis.google.com/_/scs/abc-static/ https://apis.google.com/js/ https://clients1.google.com/complete/ https://apis.google.com/_/scs/apps-static/_/js/ https://ssl.gstatic.com/inputtools/js/ https://ssl.gstatic.com/cloudsearch/static/o/js/ https://www.gstatic.com/feedback/js/ https://www.gstatic.com/common_sharing/static/client/js/ https://www.gstatic.com/og/_/js/;frame-src https://clients4.google.com/insights/consumersurveys/ https://calendar.google.com/accounts/ 'self' https://accounts.google.com/ https://apis.google.com/u/ https://apis.google.com/_/streamwidgets/ https://clients6.google.com/static/ https://content.googleapis.com/static/ https://mail-attachment.googleusercontent.com/ https://www.google.com/calendar/ https://calendar.google.com/calendar/ https://docs.google.com/ https://drive.google.com https://*.googleusercontent.com/docs/securesc/ https://feedback.googleusercontent.com/resources/ https://www.google.com/tools/feedback/ https://support.google.com/inapp/ https://*.googleusercontent.com/gadgets/ifr https://hangouts.google.com/ https://talkgadget.google.com/ https://*.talkgadget.google.com/ https://www-gm-opensocial.googleusercontent.com/gadgets/ https://plus.google.com/ https://wallet.google.com/gmail/ https://www.youtube.com/embed/ https://clients5.google.com/pagead/drt/dn/ https://clients5.google.com/ads/measurement/jn/ https://www.gstatic.com/mail/ww/ https://www.gstatic.com/mail/intl/ https://clients5.google.com/webstore/wall/ https://ci3.googleusercontent.com/ https://gsuite.google.com/u/ https://gsuite.google.com/marketplace/appfinder https://www.gstatic.com/mail/promo/ https://notifications.google.com/ https://tracedepot-pa.clients6.google.com/static/ https://mail-payments.google.com/mail/payments/ https://taskassist-pa.googleapis.com https://contacts.google.com/widget/hovercard;report-uri https://mail.google.com/mail/cspreport;object-src https://mail-attachment.googleusercontent.com/swfs/ https://mail-attachment.googleusercontent.com/attachment/ https://mail.gstatic.com/tpl/
Strict-Transport-Security: max-age=10886400; includeSubdomains
Content-Encoding: gzip
Date: Mon, 11 Dec 2017 16:19:01 GMT
Expires: Mon, 11 Dec 2017 16:19:01 GMT
Cache-Control: private, max-age=0
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: COMPASS=gmail=[REMOVED]; expires=Thu, 21-Dec-2017 16:19:02 GMT; path=/mail; Secure; HttpOnly
Alt-Svc: clear
Expect-CT: preload

[20:19:01 0D08] SSL failure recieving data (0, 5, 0)
[20:19:01 0D08] [GmailMNotifier] (000000000274BA60:820) Connection closed internal
[20:19:01 0D08] [GmailMNotifier] (000000000274BA60:4294967295) Connection closed

**Comment by georgehazan** [comment]
@imasuridondai eh... which OS do you use? XP?

**Comment by imasuridondai** [comment]
Haha. Windows 7 SP1 x64. And I have OpenSSL 1.0.2l  25 May 2017 installed.

**Comment by dartraiden** [comment]
Miranda don't use system OpenSSL.

**Comment by imasuridondai** [comment]
Okey, I removed OpenSSL.dll, and now it's works.

**Comment by imasuridondai** [comment]
Thank you.

**Comment by dartraiden** [comment]
Nice. OpenSSL.dll is only needed in 2 cases:
- on Windows XP (because Windows Crypto API in XP cannot SSL 3.2)
- on other OS if you are using MSN (if I'm not mistaken...)

in all other cases OpenSSL is only cause problems
