### ISSUE TITLE
TabSRMM group chat copy/paste weirdness

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#1062]
### Expected behavior
1. Marking text in a log with the mouse, then right-clicking should leave the text marked.
2. With the cursor/focus on the message log, Ctrl-A should select all.
3. 'Copy all' should do as advertised.

### Actual behavior
1. Right-click on the message log kills the selection. Right-click, then closing context menu by clicking on the scroll bar or other UI element restores the selection. -> The selection seems to be temporarily removed when right-click is invoked.
2. Ctrl-C works. Ctrl-A does not work reliably because it returns cursor/focus to the input box.
3. 'Copy all' in the context menu does not work. Neither with selected text nor with no text selected. 

### Does it work in stable version?
Using v. 0.95.8 nightly 18970. I think these are all fairly old problems though.

**Comment by georgehazan** [comment]
2) I cannot agree. Neither in Miranda IM nor in NG Ctrl+A does nothing
the current behaviour is normal, because any key press shall move focus to the entry field

**Comment by Tharn** [comment]
Sorry, should have specified. I'm talking about issues with the message log, not the entry field. 'Copy all' does not work for the message log.

If it's intended that any key press moves the focus, then why does Ctrl-C not move the focus, but Ctrl-A does? This is a bit unintuitive and by what you're saying, Ctrl-C should be fixed not to work either. Then we would need a working 'copy' as well as 'copy all' for the log.

**Comment by georgehazan** [comment]
1) Option of unhiding selection doesn't work for read-only controls
all another issues are fixed
