### ISSUE TITLE
LIBEAY32: crash at start on "lazy1"

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#1067]
Crashlog:
[20171213_LIBEAY32_lazy1.zip](https://github.com/miranda-ng/miranda-ng/files/1554694/20171213_LIBEAY32_lazy1.zip)

```
Exception: Access Violation at address 121C390C. Reading from address 12301000.

Stack Trace:
---------------------------------------------------------------
121C390C (LIBEAY32 121C0000): (filename not available) (0): lazy1
```

**Comment by georgehazan** [comment]
closed as duplicate of #1066

**Comment by Corak667** [comment]
разве дубликаты? Они в разное время вообще и при разных условиях. Этот чисто при старте системы видимо когда либы не успели инициализироваться, а миранда уже грузилась

**Comment by georgehazan** [comment]
переполнение стека и в том, и другом случае. просто тут упало немного в другом месте
