### ISSUE TITLE
TabSRMM: Input field resizes on its own

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#1074]
### Expected behavior
The input field should always remain consistent. It should stay the way it was initially set, and 'set and save for all sessions' should make a change similarly persistent.

### Actual behavior
1. When Miranda opens and displays long group chat logs, it will sometimes shrink the input field down to the point that it can disappear and only leave the divider to resize it back up. This does not always happen, but it does happen regularly.
2. When resizing by clicking and holding the divider in group chats, the divider will not move with the mouse pointer but always jump 1-2 lines below it. It's a minor issue, but maybe they are related.

### Does it work in stable version?
I haven't tried it, but seem to remember this to be another old issue.

### Steps to reproduce that behavior
0.95.8 19011 x64 nightly.
Have the group chat log limited to '0', which disables limits. (hope this is intended)
Have closing a tab only minimize the group chat, not close out of the channel.
Make a note of your input field size. Go to a busy IRC channel, close the tab and wait for a couple of hours. Open it again.

**Comment by georgehazan** [comment]
@Tharn still actual on #20712? sorry, I missed that ticket when I fixed resizer in tabSRMM, it shall work now

**Comment by Tharn** [comment]
I haven't noticed it happening lately.
