### ISSUE TITLE
SRMM fild messange error

### ISSUE THREAD

**Issue by Vitalley** [miranda-ng/miranda-ng#1075]
Miranda x86 build #18771, win10 x64 1709
In group chat normal wiev:
https://yadi.sk/i/CX8CDAHX3QnmyX
on chat:
https://yadi.sk/i/aj7_NMV73Qnn3K

**Comment by Vitalley** [comment]
Получилось огромное поле ввода сообщения, огромная кнопка отправить, слева аватар занял целую панель, а порою самих сообщений в чате не видно.

**Comment by georgehazan** [comment]
и его нельзя взять мышкой за перегородку и потащить вниз?

**Comment by georgehazan** [comment]
@Vitalley как повторить-то это?

**Comment by georgehazan** [comment]
там полностью переписан ресайзер в StdMsg, должно работать
