### ISSUE TITLE
Miranda #19028 hangs and sometimes crash too

### ISSUE THREAD

**Issue by facled** [miranda-ng/miranda-ng#1076]
I Update Miranda to Build #19028 today and now it hangs for a few minutes and sometimes Crash Miranda too.

I open Miranda and if a right click on systray icon or left click on protocol icon from main window it hangs.

[crash20171221173545.txt](https://github.com/miranda-ng/miranda-ng/files/1579987/crash20171221173545.txt)
[crash20171221174057.txt](https://github.com/miranda-ng/miranda-ng/files/1579988/crash20171221174057.txt)
[crash20171221180206.txt](https://github.com/miranda-ng/miranda-ng/files/1579989/crash20171221180206.txt)
[crash20171221181559.txt](https://github.com/miranda-ng/miranda-ng/files/1579990/crash20171221181559.txt)

**Comment by georgehazan** [comment]
well, I've fixed it, of course, but this problem means that you uses a broken image file or broken theme. perhaps you need to fix them
