### ISSUE TITLE
Facebook Notifications not working

### ISSUE THREAD

**Issue by newsjunkie247** [miranda-ng/miranda-ng#1077]
It no longer seems to recognize new Facebook notifications either as a pop-up or as logged to a chatroom since early this morning even though I changed nothing.

**Comment by georgehazan** [comment]
yes, Facebook dropped the page used to maintain message threads, including group chats
we're working on it

**Comment by georgehazan** [comment]
closed as duplicate of #1036

**Comment by newsjunkie247** [comment]
I think other group chats were mostly working for me though and this literally only stopped working December 19/20. It's not recognizing notifications at all (such as wall posts, comments, group posts) even just as a popup, in addition to not logging them.
