### ISSUE TITLE
History++ html export codepage  1251

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#109]
**Reported by v derckach on 23 Oct 2012 07:11 UTC**
 Сабж. Вся история экспортируется в 1251, хотя в заголовке html написано charset=utf-8, и только подпись «Создана модулем History++» в юникоде.

History++ export history in html with codepage 1251, while html header charset are set to utf-8. Only info message are stored as Unicode.

**Comment by georgehazan** [comment]
**Comment by BasiL on 11 Jan 2013 07:40 UTC**

Miranda NG Version: 0.94.1 alpha build #3043 x64

**Comment by georgehazan** [comment]
**Modified by BasiL on 11 Jan 2013 07:41 UTC**

**Comment by georgehazan** [comment]
**Modified by BasiL on 11 Jan 2013 07:42 UTC**

**Comment by georgehazan** [comment]
**Modified by BasiL on 15 Jan 2013 06:38 UTC**

**Comment by georgehazan** [comment]
**Modified by mataes on 27 May 2014 05:31 UTC**

**Comment by LittleVulpix** [comment]
This bug can be closed as a duplicate of #595 . I recommend closing this one and leaving #595 open because that one has a better description of the issue and is newer.

**Comment by dartraiden** [comment]
Duplicate of #595.
