### ISSUE TITLE
Discord: log path with date + edit messages from previous date

### ISSUE THREAD

**Issue by f2d** [miranda-ng/miranda-ng#1090]
### Expected behavior
1. Use the date of edit for log path variables.
2. Write strictly to the corresponding file path/name.

### Actual behavior
1. Original date of edited message is used in variables. This is not expected, but is mostly OK.
2. Following the edit, new messages are written after it into that old log file, until the current date changes or some other condition (I'm not yet sure how or when it's decided to rotate log filenames). This is bad, messages become scattered.

Although I'm only using logs for text search, so all is OK as long as all the text is saved somewhere, and it can be reformatted later by some script or tool.

### Steps to reproduce that behavior
 * Use Discord protocol (may be some other that allows editing messages, but keeps their original date).
 * Log path contains date variable.
 * Someone edits a message from previous date.

My log path in Message sessions → Group chats → Log formatting: `%miranda_logpath%\ChatRooms\%proto%\%yyyy%-%mm%\%nick%,%userid%_%yyyy%-%mm%-%dd%.log`

Resulting path looks like this: `D:\Programs\Miranda-NG\Profiles\UserName\Logs\ChatRooms\Discord_1\2018-01\Guild#Channel,LongNumberID_2018-01-01.log`

Miranda NG Version: 0.95.7 build #18771 (6defdc1294) x64.

**Comment by georgehazan** [comment]
well, Discord in this case generates a new message, with a timestamp = CURRENT_DATETIME, that refers to the original one. so there's no mistake, this event is new and written to the correct log file
