### ISSUE TITLE
Copy-pasting a file twice into a chat session crashes Miranda

### ISSUE THREAD

**Issue by sagamusix** [miranda-ng/miranda-ng#1091]
### Expected behavior
Nothing.

### Actual behavior
Pasting a file from Explorer once into a chat session shows the file transfer dialog. Pasting it another time crashes Miranda entirely.

### Does it work in stable version?
Using the latest stable version.

**Comment by dartraiden** [comment]
Crashlog? Version info?

Just move some files into TabSRMM window
![2018-01-06_01h29_05](https://user-images.githubusercontent.com/5046855/34631378-1cf5afae-f281-11e7-8f46-f16708efdffb.png)

**Comment by sagamusix** [comment]
Version info: https://pastebin.com/fC6F4a7C
I'm using a StdMsg chat window.

**Comment by sagamusix** [comment]
Also, as said in the description, you need to *copy&paste* the file, not move it.

**Comment by dartraiden** [comment]
Confirmed, my Miranda crashes too.

**Comment by dartraiden** [comment]
@georgehazan, stack from VS

![2018-01-06_02h15_17](https://user-images.githubusercontent.com/5046855/34632615-913e4c6c-f287-11e7-8e21-9b39d6438c83.png)
