### ISSUE TITLE
crash in tipper

### ISSUE THREAD

**Issue by Mataes** [miranda-ng/miranda-ng#1096]
call stack:
https://pastebin.com/vvUewrDi

variables:
https://pastebin.com/UFbuwZBA

**Comment by georgehazan** [comment]
полное хз, если честно... надо ловить это в студии и смотреть, что именно пошло не так
судя по тому, что это не постоянно так, то это не битая картинка, а что-то пропатчило память темы.

**Comment by georgehazan** [comment]
повторишь под студией - открой заново
