### ISSUE TITLE
[SteamWeb] Contact/auth requests do not work as intended

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#1114]
This tissue tracks the progress with friend/contact management issues for the SteamWeb protocol

- [x] Searching for a contact
- [x] Accepting a contact request
- [x] Sending a contact request
- [x] New contact requests show without the need to relogin
- [x] Deleting a contact

**Comment by georgehazan** [comment]
same as #1352 -  I need a network log on build #20712 or later, with Steam & Core only

**Comment by LittleVulpix** [comment]
@georgehazan will get you one tonight or tomorrow; I have a pending request at the moment so I can reproduce it easily.
