### ISSUE TITLE
TabSRMM: "enable sound effects" option bug

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1115]
![default](https://user-images.githubusercontent.com/5046855/35248479-4c813688-ffdf-11e7-89d6-78a20bc888f1.png)

Change state of this option -> Apply button not active

**Comment by futuarmo** [comment]
Как добраться до этих настроек?

**Comment by georgehazan** [comment]
@futuarmo пкм по заголовку окна табсов -> настройки контейнера

**Comment by georgehazan** [comment]
спасибо :)
