### ISSUE TITLE
[HistoryStats] Pressing "Apply" after modifying any settings causes a miranda crash

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#1118]
### Expected behavior
I expected changes to be applied normally.

### Actual behavior
Miranda crashes - however changes seem to be applied so they are in effect on subsequent miranda start.

### Does it work in stable version?
It worked in stable.

### Steps to reproduce that behavior
 * Have HistoryStats plugin
 * Latest Miranda
 * Go to HistoryStats plugin, change some options, press "Apply"
 * Miranda crashes.

Crashlog:

> Miranda Crash Report from 25 Jan 2018 19:36:41. Crash Dumper v.0.0.5.2
> 
> Likely cause of the crash plugin: HistoryStats
> 
> Exception: Access Violation at address 02E14B17. Reading from address 0000000C.
> 
> Stack Trace:
> ---------------------------------------------------------------
> 02E14B17 (HistoryStats 02DF0000): w:\miranda-build\plugins\historystats\src\optionsctrlimpl.cpp (1167): OptionsCtrlImpl::getItem
> 02E14F7F (HistoryStats 02DF0000): w:\miranda-build\plugins\historystats\src\optionsctrlimpl.cpp (901): OptionsCtrlImpl::onOCMGetRadioChecked
> 02E160BE (HistoryStats 02DF0000): w:\miranda-build\plugins\historystats\src\optionsctrlimpl.cpp (168): OptionsCtrlImpl::staticWndProc
> 7714342B (USER32 77110000): (filename not available) (0): AddClipboardFormatListener
> 77135893 (USER32 77110000): (filename not available) (0): DispatchMessageW
> 7712137C (USER32 77110000): (filename not available) (0): SendMessageW
> 7712109F (USER32 77110000): (filename not available) (0): SendMessageW
> 02E149A9 (HistoryStats 02DF0000): w:\miranda-build\plugins\historystats\src\optionsctrl.cpp (139): OptionsCtrl::getRadioChecked
> 02E0ECB8 (HistoryStats 02DF0000): w:\miranda-build\plugins\historystats\src\dlgoption_subcolumns.cpp (649): DlgOption::SubColumns::configHasConflicts
> 02E0D24F (HistoryStats 02DF0000): w:\miranda-build\plugins\historystats\src\dlgoption.cpp (326): DlgOption::updateProblemInfo
> 02E0E361 (HistoryStats 02DF0000): w:\miranda-build\plugins\historystats\src\dlgoption_subcolumns.cpp (363): DlgOption::SubColumns::onColSelChanging
> 02E0EA5C (HistoryStats 02DF0000): w:\miranda-build\plugins\historystats\src\dlgoption_subcolumns.cpp (118): DlgOption::SubColumns::handleMsg
> 02E0DA47 (HistoryStats 02DF0000): w:\miranda-build\plugins\historystats\src\dlgoption_subbase.cpp (30): DlgOption::SubBase::staticDlgProc
> 7714342B (USER32 77110000): (filename not available) (0): AddClipboardFormatListener
> 7711AB2C (USER32 77110000): (filename not available) (0): MapDialogRect
> 7711A2B7 (USER32 77110000): (filename not available) (0): MapDialogRect
> 7711A1D4 (USER32 77110000): (filename not available) (0): MapDialogRect
> 7714342B (USER32 77110000): (filename not available) (0): AddClipboardFormatListener
> 77135893 (USER32 77110000): (filename not available) (0): DispatchMessageW
> 7712137C (USER32 77110000): (filename not available) (0): SendMessageW
> 7712109F (USER32 77110000): (filename not available) (0): SendMessageW
> 02E1581C (HistoryStats 02DF0000): w:\miranda-build\plugins\historystats\src\optionsctrlimpl.cpp (581): OptionsCtrlImpl::onTVNSelChanging
> 02E15F55 (HistoryStats 02DF0000): w:\miranda-build\plugins\historystats\src\optionsctrlimpl.cpp (91): OptionsCtrlImpl::staticWndProc
> 7714342B (USER32 77110000): (filename not available) (0): AddClipboardFormatListener
> 77135893 (USER32 77110000): (filename not available) (0): DispatchMessageW
> 7712137C (USER32 77110000): (filename not available) (0): SendMessageW
> 7712109F (USER32 77110000): (filename not available) (0): SendMessageW
> 6707CBAC (COMCTL32 67010000): (filename not available) (0): CCSetScrollInfo
> 6703B0AF (COMCTL32 67010000): (filename not available) (0): Ordinal382
> 6703AEA4 (COMCTL32 67010000): (filename not available) (0): Ordinal382
> 67036B14 (COMCTL32 67010000): (filename not available) (0): ImageList_WriteEx
> 7714342B (USER32 77110000): (filename not available) (0): AddClipboardFormatListener
> 77135893 (USER32 77110000): (filename not available) (0): DispatchMessageW
> 7712B317 (USER32 77110000): (filename not available) (0): CallWindowProcW
> 02E15D17 (HistoryStats 02DF0000): w:\miranda-build\plugins\historystats\src\optionsctrlimpl.cpp (331): OptionsCtrlImpl::staticTreeProc
> 7714342B (USER32 77110000): (filename not available) (0): AddClipboardFormatListener
> 77135893 (USER32 77110000): (filename not available) (0): DispatchMessageW
> 7712137C (USER32 77110000): (filename not available) (0): SendMessageW
> 7712109F (USER32 77110000): (filename not available) (0): SendMessageW
> 02E14E30 (HistoryStats 02DF0000): w:\miranda-build\plugins\historystats\src\optionsctrlimpl.cpp (992): OptionsCtrlImpl::onOCMDeleteAllItems
> 02E16176 (HistoryStats 02DF0000): w:\miranda-build\plugins\historystats\src\optionsctrlimpl.cpp (205): OptionsCtrlImpl::staticWndProc
> 7714342B (USER32 77110000): (filename not available) (0): AddClipboardFormatListener
> 77135893 (USER32 77110000): (filename not available) (0): DispatchMessageW
> 7712137C (USER32 77110000): (filename not available) (0): SendMessageW
> 7712109F (USER32 77110000): (filename not available) (0): SendMessageW
> 02E14752 (HistoryStats 02DF0000): w:\miranda-build\plugins\historystats\src\optionsctrl.cpp (189): OptionsCtrl::deleteAllItems
> 02E0DA74 (HistoryStats 02DF0000): w:\miranda-build\plugins\historystats\src\dlgoption_subbase.cpp (25): DlgOption::SubBase::staticDlgProc
> 7714342B (USER32 77110000): (filename not available) (0): AddClipboardFormatListener
> 7711AB2C (USER32 77110000): (filename not available) (0): MapDialogRect
> 7711A2B7 (USER32 77110000): (filename not available) (0): MapDialogRect
> 7711A1D4 (USER32 77110000): (filename not available) (0): MapDialogRect
> 7714342B (USER32 77110000): (filename not available) (0): AddClipboardFormatListener
> 77135893 (USER32 77110000): (filename not available) (0): DispatchMessageW
> 771354EA (USER32 77110000): (filename not available) (0): DispatchMessageW
> 7713F4B9 (USER32 77110000): (filename not available) (0): GetWindowThreadProcessId
> 774C411D (ntdll 77450000): (filename not available) (0): KiUserCallbackDispatcher
> 73F4329C (win32u 73F40000): (filename not available) (0): NtUserDestroyWindow
> 126CA403 (mir_core 126C0000): w:\miranda-build\src\mir_core\src\cdlgbase.cpp (65): CDlgBase::~CDlgBase
> 125257E2 (mir_app 12520000): (filename not available) (0): COptionPageDialog::`scalar deleting destructor'
> 12526F44 (mir_app 12520000): (filename not available) (0): OptionsPageData::`scalar deleting destructor'
> 125267A1 (mir_app 12520000): w:\miranda-build\src\mir_app\src\options.cpp (807): COptionsDlg::OnDestroy
> 126CA162 (mir_core 126C0000): w:\miranda-build\src\mir_core\src\cdlgbase.cpp (264): CDlgBase::DlgProc
> 12526D4D (mir_app 12520000): w:\miranda-build\src\mir_app\src\options.cpp (1037): COptionsDlg::DlgProc
> 126C9EA2 (mir_core 126C0000): w:\miranda-build\src\mir_core\src\cdlgbase.cpp (297): CDlgBase::GlobalDlgProc
> 7714342B (USER32 77110000): (filename not available) (0): AddClipboardFormatListener
> 7711AB2C (USER32 77110000): (filename not available) (0): MapDialogRect
> 7711A2B7 (USER32 77110000): (filename not available) (0): MapDialogRect
> 7711A1D4 (USER32 77110000): (filename not available) (0): MapDialogRect
> 7714342B (USER32 77110000): (filename not available) (0): AddClipboardFormatListener
> 77135893 (USER32 77110000): (filename not available) (0): DispatchMessageW
> 771354EA (USER32 77110000): (filename not available) (0): DispatchMessageW
> 7713F4B9 (USER32 77110000): (filename not available) (0): GetWindowThreadProcessId
> 774C411D (ntdll 77450000): (filename not available) (0): KiUserCallbackDispatcher
> 126C9EA2 (mir_core 126C0000): w:\miranda-build\src\mir_core\src\cdlgbase.cpp (297): CDlgBase::GlobalDlgProc
> 7714342B (USER32 77110000): (filename not available) (0): AddClipboardFormatListener
> 7711AB2C (USER32 77110000): (filename not available) (0): MapDialogRect
> 7711A2B7 (USER32 77110000): (filename not available) (0): MapDialogRect
> 7711A1D4 (USER32 77110000): (filename not available) (0): MapDialogRect
> 7714342B (USER32 77110000): (filename not available) (0): AddClipboardFormatListener
> 77135893 (USER32 77110000): (filename not available) (0): DispatchMessageW
> 
> CPU: AMD Ryzen 7 1700 Eight-Core Processor  [AMD64 Family 23 Model 1 Stepping 1] [DEP Enabled] [16 CPUs]
> Installed RAM: 32697 MBytes
> Microsoft Windows 10 Professional Edition, 64-bit (build 15063)
> Internet Explorer: 9.11.15063.0 (build 915063)
> Administrator privileges: Yes
> OS Languages: (UI | Locale (User/System)) : English/English | English/English
> 
> Miranda NG Version: 0.95.8 alpha build #19217 (1ca493fc7a) [running inside WOW64]
> Build time: 25 Jan 2018 20:36:44

**Comment by Goraf** [comment]
Does it still crashes for you? I'm unable to reproduce it on my local debug build or with latest version from server.

**Comment by LittleVulpix** [comment]
Still crashes @ latest miranda. See recording.

Seems to now crash on pressing OK instead of apply though..

![Crash](https://i.imgur.com/Z7ccvpf.gif)

**Comment by Goraf** [comment]
Oh. Yep, it is crashing. I was trying changes in "Global" tab before and it doesn't crash there.

**Comment by Goraf** [comment]
Workaround is to use configure dialog that can be opened from main menu entry
