### ISSUE TITLE
New_GPG: doesn't work under XP

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1137]
> When Miranda is started with New_GPG plugin for the first time, a window pops up where you should point the plugin to gpg.exe and set home directory

Plugin cannot start and cannot show this window.

```
 New_GPG.dll v.0.0.0.0 [5 Feb 2018 4:01:28] - <unknown>
    Plugin statically linked to missing module: MSVCP140.dll
    Plugin statically linked to missing module: mir_core.mir
    Plugin statically linked to missing module: mir_app.mir
    Plugin statically linked to missing module: VCRUNTIME140.dll
    Plugin statically linked to missing module: api-ms-win-crt-heap-l1-1-0.dll
    Plugin statically linked to missing module: api-ms-win-crt-runtime-l1-1-0.dll
    Plugin statically linked to missing module: api-ms-win-crt-time-l1-1-0.dll
    Plugin statically linked to missing module: api-ms-win-crt-stdio-l1-1-0.dll
    Plugin statically linked to missing module: api-ms-win-crt-filesystem-l1-1-0.dll
    Plugin statically linked to missing module: api-ms-win-crt-environment-l1-1-0.dll
    Plugin statically linked to missing module: api-ms-win-crt-string-l1-1-0.dll
    Plugin statically linked to missing module: api-ms-win-crt-convert-l1-1-0.dll
```

**Comment by sss123next** [comment]
recently i have proted new_gpg to new ui api, it's not stable enough yet, so we see this kind of regressions from time to time.

**Comment by georgehazan** [comment]
the problem is that boost::process & boost::thread are not compatible with XP, and will never will.
they need to be removed

**Comment by sss123next** [comment]
unfortunately boost::process and boost::thread is key functionality of current implementation, so it's hard to eliminate it.
maybe in future i will redeisgin new_gpg so it no longer be gpg wrapper and have internal implementation of pgp features (maybe via some library), this will allow to eliminate most of threading and will make process wrapper unneeded.
but most probably it will not happen in near future.

**Comment by sss123next** [comment]
look at #1296
