### ISSUE TITLE
OpenSSL: Validating SSL certificates doesn't work

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1138]
> Проблема с SSL сертификатами, когда стоит галочка "проверять подпись сертификатов SSL" многие протоколы не конектятся.
> 
> [17:29:30 02E8] SSL established with ECDHE-RSA-AES128-GCM-SHA256
> [17:29:30 02E8] SSL connection failure(800b0109 299) :Цепочка сертификатов обработана, но
> обработка прервана на корневом сертификате, у которого отсутствует отношение доверия с пос
> тавщиком доверия.
> 
> Импорт сертификатов в "свойства обозревателя" в панели управления не решает данную проблему
> Microsoft Windows XP Professional Service Pack 3 (build 2600)
> Internet Explorer: 6.0.2900.5512 (build 62900.5512)
> 
> Пожалуйста добавьте возможность ручного разрешения и запоминания сертификатов, например если сертификат не проходит подлинность, миранда выдаёт окно запроса принять или отклонить данный сертификат, с возможностью просмотра информации о сертификате. 

https://forum.miranda-ng.org/index.php?topic=4756.msg21128;topicseen#msg21128

**Comment by georgehazan** [comment]
this certificate shall be imported in the "Trusted providers" folder, only then it will work.
