### ISSUE TITLE
KeepStatus: option "Reconnect on APM resume" don't work

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1139]

**Comment by Goraf** [comment]
Looks like `protoList` keeps wrong status of protocols (seems like they aren't updated)
After 
https://github.com/miranda-ng/miranda-ng/blob/18d362ad6c863d5cad9698b21d5995e8f3b945f5/plugins/StatusManager/src/KeepStatus/keepstatus.cpp#L1068
`ps[i]->m_status` is equal to `ID_STATUS_DISABLED` so when it comes to reestablish connection after APM resume
https://github.com/miranda-ng/miranda-ng/blob/18d362ad6c863d5cad9698b21d5995e8f3b945f5/plugins/StatusManager/src/KeepStatus/keepstatus.cpp#L1078-L1088
it fails to assign previous status, returning early 
https://github.com/miranda-ng/miranda-ng/blob/18d362ad6c863d5cad9698b21d5995e8f3b945f5/plugins/StatusManager/src/KeepStatus/keepstatus.cpp#L165-L168

**Comment by WalrusInAnus** [comment]
This really makes Miranda useless for me. My PC goes to sleep quite often, and it's permanent disconnected hell for me.

**Comment by Larusek** [comment]
Indeed it is. What's more disappointing, it has been 24 days and no one assigned to this bug. Is it being worked on at all?

**Comment by WalrusInAnus** [comment]
It's still bugged for me :(
What kind of log should I provide for you to be able to troubleshoot this further?

**Comment by Goraf** [comment]
> I haven't even put my PC to sleep, and I've just noticed I'm offline again.

@WalrusInAnus , but it's sth different than this ticket is about. Let all of us don't mix up things. Every option can be not working on its own. For general case of not reconnecting there was a separate ticket next to this one (#1150). If you have problem with basic feature go report there, or in both places if you also confirm that this is still not working.

First, make sure you updated Miranda to the latest development version. The next thing to check/provide are entries from KeepStatus in network log. You can create standalone report (link int the second ticket), or see them on the fly using Console plugin. And just in case recheck your options.

**Comment by WalrusInAnus** [comment]
Where do I find the network log though?

**Comment by Larusek** [comment]
Thank you for the fix. It's solved.

**Comment by hueldoeu** [comment]
dear users and developers, thank you very much for miranda ng. i had problems with plain miranda ng and reconnecting without plugin

i drag and dropped the statusmanager.dll (new name for keepstatus.dll) into miranda dg directory and changed the time under settings => keep status
https://www.bilder-upload.eu/upload/e49ba2-1570733099.png
[https://www.bilder-upload.eu/upload/e49ba2-1570733099.png](url)

click on the first link. IT's IMPORTANT TO RESTART MIRANDA!!!

now miranda ng is a masterpiece
