### ISSUE TITLE
CmdLine Plugin error when using Diacritics in message

### ISSUE THREAD

**Issue by trialsin** [miranda-ng/miranda-ng#1143]
Hello,

My english is poor so, look at gifs: [http://bit.ly/2shAbTF](http://bit.ly/2shAbTF)

**Comment by dartraiden** [comment]
Possibly related with https://github.com/miranda-ng/miranda-ng/issues/541

**Comment by georgehazan** [comment]
CmdLine works in ANSI, thus it can easily fail when a message contains symbol that cannot be converted into Unicode. @trialsin in which code page works your command line window?

**Comment by trialsin** [comment]
typing chcp in cmd returns 850. http://bit.ly/2ENdZFY

**Comment by georgehazan** [comment]
I've rewritten CmdLine to Unicode, so it should work now. 
give it a try

**Comment by trialsin** [comment]
I've got more problems in lastest version (0.95.8 alpha build 19462)
http://bit.ly/2HxbxBg

**Comment by georgehazan** [comment]
@trialsin thanks for pointing me out, fixed

**Comment by trialsin** [comment]
Everthing working now with that tricks:

if running in from a .cmd file need to 
set "chcp 1252" and save the file in latin1 encoding (don't work with UTF-8 files). 
With vim editor it is easy change file encoding

if running from cmd window, no tricks it is needed

thanks
