### ISSUE TITLE
CloudFile improvement

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#1144]
what do we need:

1. service that returns the list of available CloudFile services
2. settings modifications in SS+ & db_autobackup to select the appropriate cloud service
3, the ability to work with the account chosen
4. in the ideal variant - the usual accounts support in CloudFile to allow to maintain & use two Google Disk accounts, for example

**Comment by aunsane** [comment]
https://github.com/miranda-ng/miranda-ng/projects/6

**Comment by aunsane** [comment]
It seems all tasks are completed
