### ISSUE TITLE
StartupStatus: crash on closing CMDL dialog from 'General' options tab

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1145]
Crash on attempt close this dialog (via close button or OK)

![default](https://user-images.githubusercontent.com/5046855/36066103-3ffc320c-0eb5-11e8-9e91-d56eb0364b16.png)

**Comment by dartraiden** [comment]
Miranda Crash Report from 10 Feb 2018 22:54:03. Crash Dumper v.0.0.5.2

Likely cause of the crash plugin: Status manager

Exception: Access Violation at address 054910AE. Reading from address 00000000.

Stack Trace:
---------------------------------------------------------------
054910AE (StatusManager 05490000): w:\miranda-build\include\m_system_cpp.h (242): OBJLIST<SMProto>::destroy
054998AC (StatusManager 05490000): w:\miranda-build\plugins\statusmanager\src\startupstatus\ss_options.cpp (229): CmdlOptionsDlgProc
7562E0BB (USER32 75610000): (filename not available) (0): AddClipboardFormatListener
75638849 (USER32 75610000): (filename not available) (0): EndTask
7563ACD3 (USER32 75610000): (filename not available) (0): EndTask
7561BF65 (USER32 75610000): (filename not available) (0): GetKeyState
7561BE45 (USER32 75610000): (filename not available) (0): GetKeyState
7562E0BB (USER32 75610000): (filename not available) (0): AddClipboardFormatListener
75638849 (USER32 75610000): (filename not available) (0): EndTask
7563B145 (USER32 75610000): (filename not available) (0): EndTask
75628503 (USER32 75610000): (filename not available) (0): CallNextHookEx
75628AA0 (USER32 75610000): (filename not available) (0): IsWindow
77AB0BAD (ntdll 77A40000): (filename not available) (0): KiUserCallbackDispatcher
7562E0BB (USER32 75610000): (filename not available) (0): AddClipboardFormatListener
75638849 (USER32 75610000): (filename not available) (0): EndTask
7563ACD3 (USER32 75610000): (filename not available) (0): EndTask
7561BF65 (USER32 75610000): (filename not available) (0): GetKeyState
7561BE45 (USER32 75610000): (filename not available) (0): GetKeyState
7562E0BB (USER32 75610000): (filename not available) (0): AddClipboardFormatListener
75638849 (USER32 75610000): (filename not available) (0): EndTask
7563B145 (USER32 75610000): (filename not available) (0): EndTask
7563A89C (USER32 75610000): (filename not available) (0): EndTask
7561B95B (USER32 75610000): (filename not available) (0): SendMessageW
6CA06AA4 (COMCTL32 6C9C0000): (filename not available) (0): CreateMappedBitmap
6CA1C2BB (COMCTL32 6C9C0000): (filename not available) (0): ImageList_GetIconSize
7562E0BB (USER32 75610000): (filename not available) (0): AddClipboardFormatListener
75638849 (USER32 75610000): (filename not available) (0): EndTask
7563B145 (USER32 75610000): (filename not available) (0): EndTask
756290DC (USER32 75610000): (filename not available) (0): DispatchMessageW
7561B2EE (USER32 75610000): (filename not available) (0): IsDialogMessageW
126A4291 (mir_app 12660000): w:\miranda-build\src\mir_app\src\miranda.cpp (329): mir_main
0040B630 (Miranda32 00400000): w:\miranda-build\src\miranda32\src\miranda.cpp (85): wWinMain
004013C5 (Miranda32 00400000): f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl (283): __scrt_common_main_seh
750D8654 (KERNEL32 750C0000): (filename not available) (0): BaseThreadInitThunk
77AA4A47 (ntdll 77A40000): (filename not available) (0): RtlGetAppContainerNamedObjectPath
77AA4A17 (ntdll 77A40000): (filename not available) (0): RtlGetAppContainerNamedObjectPath

CPU: Genuine Intel(R) CPU 0000 @ 2.20GHz [Intel64 Family 6 Model 94 Stepping 0] [DEP Enabled] [8 CPUs]
Installed RAM: 16329 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 16299)
Internet Explorer: 9.11.16299.0 (build 916299)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian

Miranda NG Version: 0.95.8 alpha build #19273 (6ca25e9520) [running inside WOW64]
Build time: 9 Feb 2018 12:31:00
Profile: C:\Users\dr\AppData\Roaming\Miranda NG\home\home.dat (MDBX database driver)
Language pack: No language pack installed
Service Mode: No

Active Plugins (21):
¤ AdvaImg.dll v.0.11.0.2 [9 Feb 2018 12:32:24] - Miranda image services 
¤ AuthState.dll v.0.0.2.1 [9 Feb 2018 12:31:04] - Authorization state 
¤ AVS.dll v.0.95.3.4 [9 Feb 2018 12:31:50] - Avatar service 
¤ Clist_modern.dll v.0.9.1.7 [9 Feb 2018 12:31:30] - Modern contact list 
¤ CrashDumper.dll v.0.0.5.2 [9 Feb 2018 12:31:30] - Crash dumper 
¤ Db_autobackups.dll v.0.0.0.10 [9 Feb 2018 12:31:14] - Db autobackuper 
¤ DbEditorPP.dll v.4.0.1.2 [9 Feb 2018 12:31:32] - Database editor++ 
¤ Dbx_mdbx.dll v.0.95.8.3 [9 Feb 2018 12:32:28] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.0.95.3.1 [9 Feb 2018 12:31:08] - Miranda NG mmap database driver 
¤ historypp.dll v.1.5.1.5 [17 Jan 2018 18:45:20] - History++ 
¤ ICQ.dll v.0.95.8.1 [9 Feb 2018 12:31:14] - IcqOscarJ protocol 
¤ Jabber.dll v.0.11.0.5 [9 Feb 2018 12:32:18] - Jabber protocol 
¤ MenuEx.dll v.1.3.0.10 [9 Feb 2018 12:31:10] - Menu item ext 
¤ PluginUpdater.dll v.0.1.2.5 [9 Feb 2018 12:31:38] - Plugin updater 
¤ Popup.dll v.2.1.1.12 [9 Feb 2018 12:31:18] - Popup plus 
¤ SeenPlugin.dll v.5.0.5.3 [9 Feb 2018 12:31:16] - Last seen 
¤ StatusManager.dll v.1.1.0.2 [9 Feb 2018 12:32:24] - Status manager 
¤ TabSRMM.dll v.3.5.0.8 [9 Feb 2018 12:31:58] - TabSRMM 
¤ Tipper.dll v.2.1.0.7 [9 Feb 2018 12:31:52] - Tipper 
¤ Tox.dll v.0.11.3.1 [9 Feb 2018 12:32:44] - Tox protocol 
¤ Variables.dll v.0.2.3.11 [9 Feb 2018 12:31:26] - Variables 

Loaded Modules:
-------------------------------------------------------------------------------
C:\Program Files\Miranda NG\Miranda32.exe  00400000 - 00419000 v.0.95.8.19273 [9 Feb 2018 12:31:00]
C:\Windows\SYSTEM32\ntdll.dll  77A40000 - 77BCD000 v.10.0.16299.64 [25 Oct 2017 6:52:25]
C:\Windows\System32\KERNEL32.DLL  750C0000 - 75190000 v.10.0.16299.15 [29 Sep 2017 16:42:26]
C:\Windows\System32\KERNELBASE.dll  752D0000 - 754A7000 v.10.0.16299.15 [29 Sep 2017 16:41:43]
C:\Windows\System32\USER32.dll  75610000 - 75785000 v.10.0.16299.125 [8 Dec 2017 1:56:16]
C:\Windows\System32\win32u.dll  77820000 - 77836000 v.10.0.16299.15 [29 Sep 2017 16:42:09]
C:\Windows\System32\GDI32.dll  749F0000 - 74A12000 v.10.0.16299.15 [29 Sep 2017 16:42:10]
C:\Windows\System32\gdi32full.dll  776C0000 - 7781E000 v.10.0.16299.98 [26 Nov 2017 14:21:07]
C:\Windows\System32\msvcp_win.dll  75190000 - 7520C000 v.10.0.16299.15 [29 Sep 2017 16:42:14]
C:\Windows\System32\ucrtbase.dll  75930000 - 75A47000 v.10.0.16299.125 [8 Dec 2017 1:37:27]
C:\Windows\System32\SHELL32.dll  76170000 - 774A3000 v.10.0.16299.125 [8 Dec 2017 1:32:16]
C:\Windows\System32\msvcrt.dll  75A50000 - 75B0D000 v.7.0.16299.125 [8 Dec 2017 1:36:46]
C:\Windows\System32\cfgmgr32.dll  77620000 - 77658000 v.10.0.16299.15 [29 Sep 2017 16:42:16]
C:\Windows\System32\shcore.dll  74960000 - 749E8000 v.10.0.16299.15 [29 Sep 2017 16:42:13]
C:\Windows\System32\RPCRT4.dll  757A0000 - 7585E000 v.10.0.16299.15 [29 Sep 2017 16:42:27]
C:\Windows\System32\SspiCli.dll  74460000 - 74480000 v.10.0.16299.125 [8 Dec 2017 1:58:03]
C:\Windows\System32\CRYPTBASE.dll  74450000 - 7445A000 v.10.0.16299.15 [29 Sep 2017 16:42:27]
C:\Windows\System32\bcryptPrimitives.dll  77660000 - 776B7000 v.10.0.16299.98 [26 Nov 2017 14:00:39]
C:\Windows\System32\sechost.dll  74910000 - 74953000 v.10.0.16299.15 [29 Sep 2017 16:42:27]
C:\Windows\System32\combase.dll  744E0000 - 74726000 v.10.0.16299.15 [29 Sep 2017 16:42:14]
C:\Windows\System32\windows.storage.dll  75B10000 - 760D6000 v.10.0.16299.125 [8 Dec 2017 1:39:54]
C:\Windows\System32\advapi32.dll  775A0000 - 77618000 v.10.0.16299.15 [29 Sep 2017 16:42:27]
C:\Windows\System32\shlwapi.dll  77840000 - 77885000 v.10.0.16299.15 [29 Sep 2017 16:42:24]
C:\Windows\System32\kernel.appcore.dll  774B0000 - 774BE000 v.10.0.16299.15 [29 Sep 2017 16:42:11]
C:\Windows\System32\powrprof.dll  758E0000 - 75925000 v.10.0.16299.15 [29 Sep 2017 16:42:14]
C:\Windows\System32\profapi.dll  77890000 - 778A4000 v.10.0.16299.15 [29 Sep 2017 16:42:27]
C:\Windows\System32\IMM32.DLL  74790000 - 747B5000 v.10.0.16299.15 [29 Sep 2017 16:42:14]
C:\Program Files\Miranda NG\libs\ucrtbase.dll  65490000 - 65571000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\Program Files\Miranda NG\libs\mir_app.mir  12660000 - 12729000 v.0.95.8.19273 [9 Feb 2018 12:31:00]
C:\Windows\System32\WS2_32.dll  75860000 - 758C6000 v.10.0.16299.15 [29 Sep 2017 16:42:27]
C:\Windows\SYSTEM32\WINMM.dll  6D130000 - 6D154000 v.10.0.16299.15 [29 Sep 2017 16:42:08]
C:\Windows\System32\COMDLG32.dll  774C0000 - 77594000 v.10.0.16299.125 [8 Dec 2017 1:03:14]
C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.16299.125_none_5d79065fa7de350f\COMCTL32.dll  6C9C0000 - 6CBD1000 v.6.10.16299.125 [8 Dec 2017 1:31:19]
C:\Windows\System32\ole32.dll  74B90000 - 74C87000 v.10.0.16299.15 [29 Sep 2017 16:42:13]
C:\Windows\SYSTEM32\UxTheme.dll  6BF30000 - 6BFA9000 v.10.0.16299.15 [29 Sep 2017 16:42:25]
C:\Windows\SYSTEM32\winmmbase.dll  6BDA0000 - 6BDC3000 v.10.0.16299.15 [29 Sep 2017 16:42:08]
C:\Program Files\Miranda NG\libs\zlib.mir  12A40000 - 12A59000 v.1.2.11.0 [9 Feb 2018 12:30:50]
C:\Program Files\Miranda NG\libs\mir_core.mir  12800000 - 12822000 [9 Feb 2018 12:30:52]
C:\Windows\SYSTEM32\VERSION.dll  6D060000 - 6D068000 v.10.0.16299.15 [29 Sep 2017 16:42:24]
C:\Windows\SYSTEM32\Secur32.dll  6C3C0000 - 6C3CA000 v.10.0.16299.15 [29 Sep 2017 16:42:22]
C:\Program Files\Miranda NG\libs\VCRUNTIME140.dll  694F0000 - 69504000 v.14.11.25325.0 [25 May 2017 13:39:24]
C:\Windows\SYSTEM32\WTSAPI32.dll  71EC0000 - 71ECF000 v.10.0.16299.15 [29 Sep 2017 16:42:25]
C:\Windows\System32\MSCTF.dll  754B0000 - 755F4000 v.10.0.16299.19 [10 Oct 2017 9:31:30]
C:\Windows\System32\OLEAUT32.dll  74810000 - 748A3000 v.10.0.16299.15 [29 Sep 2017 16:42:14]
C:\Windows\SYSTEM32\dwmapi.dll  6D3F0000 - 6D413000 v.10.0.16299.15 [29 Sep 2017 16:42:16]
C:\Windows\System32\clbcatq.dll  75240000 - 752C2000 v.2001.12.10941.16384 [29 Sep 2017 16:42:14]
C:\Windows\system32\explorerframe.dll  62A60000 - 62E92000 v.10.0.16299.98 [26 Nov 2017 13:30:20]
C:\Program Files\Miranda NG\Plugins\CrashDumper.dll  177F0000 - 17801000 v.0.0.5.2 [9 Feb 2018 12:31:30]
C:\Windows\SYSTEM32\dbghelp.dll  6C830000 - 6C9B1000 v.10.0.16299.15 [29 Sep 2017 16:42:16]
C:\Windows\SYSTEM32\dbgcore.DLL  65590000 - 655B4000 v.10.0.16299.15 [29 Sep 2017 16:42:16]
C:\Program Files\Miranda NG\Plugins\DbEditorPP.dll  17970000 - 1798D000 v.4.0.1.2 [9 Feb 2018 12:31:32]
C:\Program Files\Miranda NG\Plugins\Dbx_mdbx.dll  179B0000 - 179D0000 v.0.95.8.3 [9 Feb 2018 12:32:28]
C:\Program Files\Miranda NG\libs\MSVCP140.dll  67F10000 - 67F7D000 v.14.11.25325.0 [25 May 2017 13:39:24]
C:\Program Files\Miranda NG\Plugins\Dbx_mmap.dll  179F0000 - 17A01000 v.0.95.3.1 [9 Feb 2018 12:31:08]
C:\Program Files\Miranda NG\Core\stdcrypt.dll  13060000 - 1306C000 v.0.95.8.19273 [9 Feb 2018 12:30:56]
C:\Program Files\Miranda NG\Core\stdssl.dll  13140000 - 13148000 v.0.95.8.19273 [9 Feb 2018 12:30:54]
C:\Windows\System32\CRYPT32.dll  778B0000 - 77A32000 v.10.0.16299.15 [29 Sep 2017 16:42:14]
C:\Windows\System32\MSASN1.dll  75600000 - 7560E000 v.10.0.16299.15 [29 Sep 2017 16:42:14]
C:\Windows\SYSTEM32\WSOCK32.dll  693A0000 - 693A8000 v.10.0.16299.15 [29 Sep 2017 16:42:19]
C:\Windows\SYSTEM32\Msftedit.dll  651E0000 - 65489000 v.10.0.16299.15 [29 Sep 2017 16:42:10]
C:\Program Files\Miranda NG\Plugins\AdvaImg.dll  171B0000 - 171B7000 v.0.11.0.2 [9 Feb 2018 12:32:24]
C:\Program Files\Miranda NG\libs\FreeImage.mir  12000000 - 12093000 [9 Feb 2018 12:31:40]
C:\Program Files\Miranda NG\Plugins\Clist_modern.dll  174D0000 - 17542000 v.0.9.1.7 [9 Feb 2018 12:31:30]
C:\Windows\SYSTEM32\MSIMG32.dll  6AA90000 - 6AA96000 v.10.0.16299.15 [29 Sep 2017 16:42:14]
C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.0.16299.125_none_9f128a60696ad536\gdiplus.dll  5D000000 - 5D16C000 v.10.0.16299.125 [8 Dec 2017 1:12:45]
C:\Program Files\Miranda NG\Plugins\AuthState.dll  17270000 - 17279000 v.0.0.2.1 [9 Feb 2018 12:31:04]
C:\Program Files\Miranda NG\Plugins\AVS.dll  172F0000 - 17302000 v.0.95.3.4 [9 Feb 2018 12:31:50]
C:\Program Files\Miranda NG\Plugins\Db_autobackups.dll  04E20000 - 04E2E000 v.0.0.0.10 [9 Feb 2018 12:31:14]
C:\Program Files\Miranda NG\Plugins\historypp.dll  04E30000 - 0501E000 v.1.5.1.5 [17 Jan 2018 18:45:20]
C:\Windows\SYSTEM32\winspool.drv  6C430000 - 6C49C000 v.10.0.16299.15 [29 Sep 2017 16:42:27]
C:\Windows\SYSTEM32\IPHLPAPI.DLL  74090000 - 740C0000 v.10.0.16299.15 [29 Sep 2017 16:42:14]
C:\Windows\SYSTEM32\bcrypt.dll  74110000 - 74129000 v.10.0.16299.125 [8 Dec 2017 1:55:44]
C:\Windows\SYSTEM32\RICHED20.DLL  65160000 - 651DE000 v.5.31.23.1231 [29 Sep 2017 16:42:23]
C:\Windows\SYSTEM32\USP10.dll  6D1C0000 - 6D1D7000 v.10.0.16299.15 [29 Sep 2017 16:42:16]
C:\Windows\SYSTEM32\msls31.dll  67ED0000 - 67F02000 v.3.10.349.0 [29 Sep 2017 16:42:24]
C:\Program Files\Miranda NG\Plugins\ICQ.dll  051A0000 - 051F3000 v.0.95.8.1 [9 Feb 2018 12:31:14]
C:\Program Files\Miranda NG\Plugins\Jabber.dll  05200000 - 052A1000 v.0.11.0.5 [9 Feb 2018 12:32:18]
C:\Program Files\Miranda NG\libs\LIBEAY32.mir  5CEB0000 - 5CFF1000 v.1.0.2.14 [3 Nov 2017 19:31:34]
C:\Program Files\Miranda NG\libs\libaxolotl.mir  12200000 - 12230000 [9 Feb 2018 12:31:10]
C:\Program Files\Miranda NG\libs\libjson.mir  125A0000 - 125AF000 [9 Feb 2018 12:31:06]
C:\Windows\SYSTEM32\DNSAPI.dll  73E10000 - 73EA4000 v.10.0.16299.19 [10 Oct 2017 9:11:03]
C:\Windows\System32\NSI.dll  758D0000 - 758D7000 v.10.0.16299.15 [29 Sep 2017 16:41:43]
C:\Program Files\Miranda NG\Plugins\MenuEx.dll  052D0000 - 052DE000 v.1.3.0.10 [9 Feb 2018 12:31:10]
C:\Program Files\Miranda NG\Plugins\PluginUpdater.dll  052E0000 - 052F5000 v.0.1.2.5 [9 Feb 2018 12:31:38]
C:\Program Files\Miranda NG\Plugins\Popup.dll  05300000 - 0533B000 v.2.1.1.12 [9 Feb 2018 12:31:18]
C:\Program Files\Miranda NG\Plugins\SeenPlugin.dll  05480000 - 0548F000 v.5.0.5.3 [9 Feb 2018 12:31:16]
C:\Program Files\Miranda NG\Plugins\StatusManager.dll  05490000 - 054AB000 v.1.1.0.2 [9 Feb 2018 12:32:24]
C:\Windows\SYSTEM32\WININET.dll  74180000 - 74444000 v.11.0.16299.98 [26 Nov 2017 13:29:14]
C:\Program Files\Miranda NG\Plugins\TabSRMM.dll  054B0000 - 05532000 v.3.5.0.8 [9 Feb 2018 12:31:58]
C:\Program Files\Miranda NG\Plugins\Tipper.dll  07100000 - 07125000 v.2.1.0.7 [9 Feb 2018 12:31:52]
C:\Program Files\Miranda NG\Plugins\Tox.dll  07270000 - 072AF000 v.0.11.3.1 [9 Feb 2018 12:32:44]
C:\Program Files\Miranda NG\libs\libsodium.mir  125C0000 - 12606000 [9 Feb 2018 12:32:32]
C:\Program Files\Miranda NG\libs\pthreads.mir  694E0000 - 694EC000 [9 Feb 2018 12:32:24]
C:\Program Files\Miranda NG\Plugins\Variables.dll  072B0000 - 072C8000 v.0.2.3.11 [9 Feb 2018 12:31:26]
C:\Program Files\Miranda NG\libs\Pcre16.mir  12860000 - 12878000 [9 Feb 2018 12:31:18]
C:\Windows\SYSTEM32\pdh.dll  65110000 - 65154000 v.10.0.16299.15 [29 Sep 2017 16:42:14]
C:\Program Files\Miranda NG\Core\stduserinfo.dll  13180000 - 1318D000 v.0.95.8.19273 [9 Feb 2018 12:30:54]
C:\Program Files\Miranda NG\Core\stdemail.dll  13080000 - 13086000 v.0.95.8.19273 [9 Feb 2018 12:30:56]
C:\Program Files\Miranda NG\Core\stdfile.dll  130A0000 - 130B0000 v.0.95.8.19273 [9 Feb 2018 12:30:56]
C:\Program Files\Miranda NG\Core\stdidle.dll  130C0000 - 130C8000 v.0.95.8.19273 [9 Feb 2018 12:30:56]
C:\Program Files\Miranda NG\Core\stdautoaway.dll  13000000 - 13006000 v.0.95.8.19273 [9 Feb 2018 12:30:54]
C:\Program Files\Miranda NG\Core\stduseronline.dll  131A0000 - 131A6000 v.0.95.8.19273 [9 Feb 2018 12:30:54]
C:\Program Files\Miranda NG\Core\stdaway.dll  13020000 - 13029000 v.0.95.8.19273 [9 Feb 2018 12:30:56]
C:\Windows\system32\dataexchange.dll  69300000 - 69348000 v.10.0.16299.15 [29 Sep 2017 16:42:09]
C:\Windows\system32\d3d11.dll  6BB60000 - 6BD9E000 v.10.0.16299.98 [26 Nov 2017 14:01:44]
C:\Windows\system32\dcomp.dll  69530000 - 6962E000 v.10.0.16299.15 [29 Sep 2017 16:42:16]
C:\Windows\system32\dxgi.dll  6C4A0000 - 6C533000 v.10.0.16299.98 [26 Nov 2017 14:01:41]
C:\Windows\system32\twinapi.appcore.dll  67CF0000 - 67E24000 v.10.0.16299.19 [10 Oct 2017 9:07:05]
C:\Windows\system32\RMCLIENT.dll  67CD0000 - 67CEA000 v.10.0.16299.15 [29 Sep 2017 16:42:11]
C:\Windows\System32\TextInputFramework.dll  67C50000 - 67CC7000 v.10.0.16299.15 [29 Sep 2017 16:42:10]
C:\Windows\System32\CoreUIComponents.dll  6B410000 - 6B644000 v.10.0.16299.15 [29 Sep 2017 16:42:10]
C:\Windows\System32\CoreMessaging.dll  6B8B0000 - 6B93C000 v.10.0.16299.15 [29 Sep 2017 16:42:14]
C:\Windows\SYSTEM32\ntmarta.dll  6B650000 - 6B678000 v.10.0.16299.15 [29 Sep 2017 16:42:14]
C:\Windows\SYSTEM32\wintypes.dll  6B7E0000 - 6B8AB000 v.10.0.16299.15 [29 Sep 2017 16:42:14]
C:\Windows\System32\oleacc.dll  6D2C0000 - 6D316000 v.7.2.16299.15 [29 Sep 2017 16:42:23]
C:\Windows\SYSTEM32\WindowsCodecs.dll  5CD40000 - 5CEAE000 v.10.0.16299.15 [29 Sep 2017 16:42:09]
C:\Windows\system32\mswsock.dll  73F70000 - 73FC5000 v.10.0.16299.15 [29 Sep 2017 16:42:14]
C:\Windows\System32\rasadhlp.dll  73E00000 - 73E08000 v.10.0.16299.15 [29 Sep 2017 16:42:23]
C:\Windows\System32\fwpuclnt.dll  73DB0000 - 73DFE000 v.10.0.16299.15 [29 Sep 2017 16:42:11]
C:\Windows\SYSTEM32\schannel.dll  67E30000 - 67E98000 v.10.0.16299.15 [29 Sep 2017 16:42:16]
C:\Windows\SYSTEM32\mskeyprotect.dll  692F0000 - 69300000 v.10.0.16299.15 [29 Sep 2017 16:42:09]
C:\Windows\SYSTEM32\ncrypt.dll  6D180000 - 6D1A0000 v.10.0.16299.15 [29 Sep 2017 16:42:14]
C:\Windows\SYSTEM32\NTASN1.dll  6BF00000 - 6BF2C000 v.10.0.16299.15 [29 Sep 2017 16:42:14]
C:\Windows\system32\ncryptsslp.dll  65C60000 - 65C7B000 v.10.0.16299.15 [29 Sep 2017 16:42:14]
C:\Windows\system32\napinsp.dll  64B00000 - 64B11000 v.10.0.16299.15 [29 Sep 2017 16:42:18]
C:\Windows\system32\pnrpnsp.dll  64AE0000 - 64AF6000 v.10.0.16299.15 [29 Sep 2017 16:41:23]
C:\Windows\system32\NLAapi.dll  6AC00000 - 6AC13000 v.10.0.16299.15 [29 Sep 2017 16:42:23]
C:\Windows\System32\winrnr.dll  64AD0000 - 64ADC000 v.10.0.16299.15 [29 Sep 2017 16:42:16]

**Comment by Goraf** [comment]
```
>	StatusManager.dll!SMProto::~SMProto() Line 51	C++	Symbols loaded.
 	StatusManager.dll!OBJLIST<SMProto>::destroy() Line 242	C++	Symbols loaded.
 	StatusManager.dll!CmdlOptionsDlgProc(HWND__ * hwndDlg, unsigned int msg, unsigned int wParam, long lParam) Line 229	C++	Symbols loaded.
 	[External Code]		Annotated Frame
 	[Frames below may be incorrect and/or missing, no symbols loaded for user32.dll]		Annotated Frame
 	mir_app.mir!mir_main(wchar_t * cmdLine) Line 329	C++	Symbols loaded.
 	Miranda32.exe!wWinMain(HINSTANCE__ * hInstance, HINSTANCE__ * __formal, wchar_t * cmdLine, int __formal) Line 85	C++	Symbols loaded.
 	[External Code]		Annotated Frame
```
`static TProtoSettings* optionsProtoSettings` shows wrong content on destruction. Somehow it is getting being invalid afer dialog initialization, because it is also wrong on `WM_COMMAND -> IDC_SHORTCUT`
