### ISSUE TITLE
Clist_modern: global padding for status bar does nothing

### ISSUE THREAD

**Issue by Goraf** [miranda-ng/miranda-ng#1148]
Setting global padding for status bar seems to have no effect. I'm not sure if it should, because it would do almost the same as `Space between` option is doing. If not, then those controls should be disabled for globals.

![image](https://user-images.githubusercontent.com/22941576/36067455-edbc3f88-0ebd-11e8-9540-dc16e30385f1.png)

**Comment by georgehazan** [comment]
it works only when "Set options per account" is set
