### ISSUE TITLE
XMPP/Jabber: Implement XEP-0313 ( mam / Message Archive Management )

### ISSUE THREAD

**Issue by damiankaczkowski** [miranda-ng/miranda-ng#1149]
Please consider implementing XEP-0313 for XMPP.
https://xmpp.org/extensions/xep-0313.html

It is one of the most desired feature according to miranda-ng feature request survey :
https://miranda-ng.uservoice.com/forums/250387-general/filters/top

It is one of the most useful features according to:
https://gultsch.de/xmpp_2016.html

Prosody recently got native XEP-0313 and XEP-0280 support:
https://blog.prosody.im/prosody-0-10-0-released/

More and more clients and servers also got support for this features:
https://www.zash.se/mam.html

XEP-0313 "combined with XEP-0280 (Message Carbons) provides a complete solution for "every message on every device", which is a key feature expected of modern communication platforms." XEP-0280 (Message Carbons) got implemented recently in miranda-ng which is great! Now only XEP-0313 is missing.

**Comment by dartraiden** [comment]
https://forum.miranda-ng.org/index.php?topic=6043.msg27082#msg27082

**Comment by georgehazan** [comment]
давай дальше баги по MAM в отдельные тикеты записывать, сюда не доплыть
