### ISSUE TITLE
Status Manager no longer reconnects when connection breaks

### ISSUE THREAD

**Issue by rkwk** [miranda-ng/miranda-ng#1150]
After I upgraded from stable (0.95.7) to development version recently, Status Manager stopped to reconnect after a broken Internet connection is reestablished.

**Comment by georgehazan** [comment]
network log that includes Core is appreciated
https://wiki.miranda-ng.org/index.php?title=Network_log

**Comment by rkawulak** [comment]
[Here it is](https://github.com/miranda-ng/miranda-ng/files/1722291/netlog.txt) (I've replaced the query parts of request URIs with "[...]" for privacy).

I've disabled the network card at line 5 and reenabled it in about a second, but there are no signs of any reconnection attempts in the log after the Internet connection came back.

I have Keep Status set-up as: check connection - yes, maximum retries - 0 (= infinite), delay - 10 s.

**Comment by georgehazan** [comment]
but there're no records from the Status Manager plugin, as well as any other lines from Core. 
have you enabled it? if you don't want to publish the full file, you can zip it and email it to me to ghazan at miranda point im. I guarantee the strict privacy of any data that might be included into this log

**Comment by rkawulak** [comment]
Yup, that's the complete file I got. I turned logging on a moment before disabling the connection and turned it off a few dozen seconds after enabling the connection. Here are the logging settings: 
![capture](https://user-images.githubusercontent.com/3124553/36282648-bf3837ae-1299-11e8-9ba5-ae1ddeae2098.PNG)

**Comment by georgehazan** [comment]
the problem is that I don't see any status change in that log... so KeepStatus has no chance to intrude and return the status back

**Comment by Goraf** [comment]
So it would be good to confirm that it is turned on. Show us your StatusManager/KeepStatus settings

**Comment by LoneBoco** [comment]
I have the exact same problem.  I have changed nothing with my configuration and one day my accounts just didn't reconnect anymore.

![image](https://user-images.githubusercontent.com/1922821/36356477-63b4052e-14a7-11e8-9704-8b20cff827e3.png)

![image](https://user-images.githubusercontent.com/1922821/36356481-6b45d92a-14a7-11e8-812d-ce431dbef1cf.png)

![image](https://user-images.githubusercontent.com/1922821/36356483-754384cc-14a7-11e8-9b37-d2804e8457df.png)

**Comment by Goraf** [comment]
@LoneBoco, do you also don't have entries from KeepStatus in netlog?

**Comment by dartraiden** [comment]
I know another user with the same problem. And yes, no KeepStatus entries in netlog.

**Comment by Goraf** [comment]
Maybe it has similar causes to #1139

**Comment by Larusek** [comment]
Same happens for me. Since about a month. No KeepStatus entries, nothing. First time such a problem with miranda-ng. Sadly it's a deal-breaker :/

**Comment by Goraf** [comment]
Try it with option "Continuously check for internet connection". Maybe it will force KeepStatus react on changes.

**Comment by Larusek** [comment]
It didn't help but I've got something in the log:

[00:24:26 1960] KeepStatus: suspend state detected: 00000004 00000000
[00:24:26 1960] KeepStatus: assigning status 41083 (41083, 0) to Dax@FB
[00:24:26 1960] KeepStatus: assigning status 40071 (41083, 0) to GG
[00:24:26 1960] KeepStatus: assigning status 40071 (41083, 0) to ICQ
[00:24:26 1960] KeepStatus: assigning status 40071 (41083, 0) to JABBER
[00:24:26 1960] KeepStatus: assigning status 40071 (41083, 0) to JABBER_2
[08:06:25 1960] KeepStatus: resume from suspend state
[09:44:27 2290] UPnP disabled. Internal Port: 50003
[10:09:00 1960] KeepStatus: suspend state detected: 00000004 00000000
[10:09:00 1960] KeepStatus: assigning status 41083 (41083, 0) to Dax@FB
[10:09:00 1960] KeepStatus: assigning status 40071 (41083, 0) to GG
[10:09:00 1960] KeepStatus: assigning status 40071 (41083, 0) to ICQ
[10:09:00 1960] KeepStatus: assigning status 40071 (41083, 0) to JABBER
[10:09:00 1960] KeepStatus: assigning status 40071 (41083, 0) to JABBER_2
[19:39:47 1960] KeepStatus: resume from suspend state

**Comment by dartraiden** [comment]
I obtain KeepStatus settings from user. And can confirm - KeepStatus don't work and no entries in netlog. @georgehazan will investigate this problem.

**Comment by WalrusInAnus** [comment]
I don't know whether it's related to this, but on my wife's PC with the latest (as of today) build I run into something I call "fake online" status. Her Miranda appeared online until she tried to send me a message, at which point it produced an error (timeout) and the status changed to offline.

**Comment by georgehazan** [comment]
@WalrusInAnus this behavior is typical for proxy connections or weak ip connections. TCP guarantees that missing replies to watchdog packets will close a socket after a certain timeout

**Comment by WalrusInAnus** [comment]
There's no proxy here though, and the connection we have is fairly stable. 
It's not like this is happening on regular basis, but it does happen.

**Comment by WalrusInAnus** [comment]
I even checked the "periodically check for connection" or something, and it still doesn't work.
It appears I am online, and in fact am not.
I just don't know.
[netlog.txt](https://github.com/miranda-ng/miranda-ng/files/1786785/netlog.txt)

**Comment by georgehazan** [comment]
@WalrusInAnus well, as we discovered it doesn't work precisely because you turned "periodically check for connection" on. Without this flag everything works ok for me.

**Comment by WalrusInAnus** [comment]
I don't have it on anymore and still keep finding myself offline.
What options do you suggest to enable and which ones to keep off? Just to make sure we're testing this under similar/same conditions.

**Comment by dartraiden** [comment]
All settings in Dial-up block

**Comment by WalrusInAnus** [comment]
You're confusing me.
Can you write what exactly should be enabled and what should be disabled?

**Comment by dartraiden** [comment]
For me KeepStatus  does not always work if these settings are enabled

![2222](https://user-images.githubusercontent.com/5046855/37396387-cd38e1e6-2789-11e8-95b9-0a70c120e17e.png)
