### ISSUE TITLE
[Tox] Skipping filetransfer (file exists) causes a stuck "pending" transfer which can crash miranda

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#1153]
### Expected behavior
When skipping a filetransfer (file dialog: file already exists), the file is either not shown in transfer list, or shown as "Skipped / cancelled"

### Actual behavior
After skipping a file, it shows up as if the transfer had started, but with no data being transferred. Clicking the red "X" to cancel the skipped transfer crashes miranda
![skipped](https://i.imgur.com/511p8ZW.png)

### Does it work in stable version?
I don't know...

### Steps to reproduce that behavior
1) latest miranda Miranda NG Version: 0.95.8 alpha build #19281 (e5abf09c15) [running inside WOW64]
2) be receiving a file that already exists
3) click "skip" on the file transfer promt
4) try to cancel the skipped file transfer from the file transfer list.

```
Crashlog:

Miranda Crash Report from 13 Feb 2018 11:57:30. Crash Dumper v.0.0.5.2

Likely cause of the crash plugin: Tox protocol

Exception: Access Violation at address 054D1CAE. Reading from address 00000000.

Stack Trace:
---------------------------------------------------------------
054D1CAE (Tox 054D0000): w:\miranda-build\protocols\tox\src\tox_transfer.h (57): FileTransferParam::~FileTransferParam
054D15F1 (Tox 054D0000): w:\miranda-build\protocols\tox\src\tox_transfer.h (117): CTransferList::Remove
054DF2F2 (Tox 054D0000): w:\miranda-build\protocols\tox\src\tox_transfer.cpp (308): CToxProto::CancelTransfer
054DDBFB (Tox 054D0000): w:\miranda-build\protocols\tox\src\tox_proto.cpp (111): CToxProto::FileCancel
126B3A05 (mir_app 12660000): w:\miranda-build\src\mir_app\src\protocols.cpp (355): CallProtoServiceInt
126B4A04 (mir_app 12660000): w:\miranda-build\src\mir_app\src\proto_chains.cpp (84): Proto_ChainSend
130A7113 (stdfile 130A0000): w:\miranda-build\src\core\stdfile\src\filexferdlg.cpp (745): FreeFileDlgData
130A5AAA (stdfile 130A0000): w:\miranda-build\src\core\stdfile\src\filexferdlg.cpp (732): DlgProcFileTransfer
75AC342B (USER32 75A90000): (filename not available) (0): AddClipboardFormatListener
75A9AB2C (USER32 75A90000): (filename not available) (0): MapDialogRect
75A9A2B7 (USER32 75A90000): (filename not available) (0): MapDialogRect
75A9A1D4 (USER32 75A90000): (filename not available) (0): MapDialogRect
75AC342B (USER32 75A90000): (filename not available) (0): AddClipboardFormatListener
75AB5893 (USER32 75A90000): (filename not available) (0): DispatchMessageW
75AB54EA (USER32 75A90000): (filename not available) (0): DispatchMessageW
75ABF4B9 (USER32 75A90000): (filename not available) (0): GetWindowThreadProcessId
7788411D (ntdll 77810000): (filename not available) (0): KiUserCallbackDispatcher
75AB58E9 (USER32 75A90000): (filename not available) (0): DispatchMessageW
75AA7502 (USER32 75A90000): (filename not available) (0): MonitorFromPoint
75A9AB2C (USER32 75A90000): (filename not available) (0): MapDialogRect
```

**Comment by gituser** [comment]
This bug presents not only in Tox, but in Jabber protocol as well.

**Comment by LittleVulpix** [comment]
@aunsane 

Just had another crash which happened due to a cancelled transfer.

> Miranda Crash Report from 14 Oct 2018 14:03:46. Crash Dumper v.0.1.0.2
> 
> Likely cause of the crash plugin: Tox protocol
> 
> Exception: Access Violation at address 0000000012ADAF07. Reading from address 0000000000000030.
> 
> Stack Trace:
> ---------------------------------------------------------------
> 0000000012ADAF07 (mir_core 0000000012AC0000): w:\miranda-build\src\mir_core\src\utils.cpp (37): replaceStrW
> 000000001A5C4359 (Tox 000000001A5B0000): w:\miranda-build\protocols\tox\src\tox_transfer.cpp (109): CToxProto::OnFileResume
> 000000001A5C2DFC (Tox 000000001A5B0000): w:\miranda-build\protocols\tox\src\tox_proto.cpp (133): CToxProto::FileResume
> 000000001294A061 (mir_app 00000000128E0000): w:\miranda-build\src\mir_app\src\protocols.cpp (412): CallProtoServiceInt
> 0000000012949DB9 (mir_app 00000000128E0000): w:\miranda-build\src\mir_app\src\protocols.cpp (390): CallProtoService
> 00000000130C739F (stdfile 00000000130C0000): w:\miranda-build\src\core\stdfile\src\filexferdlg.cpp (732): DlgProcFileTransfer
> 00007FFF8C67EB3E (USER32 00007FFF8C670000): (filename not available) (0): Ordinal2707
> 00007FFF8C67E2C1 (USER32 00007FFF8C670000): (filename not available) (0): Ordinal2573
> 00007FFF8C67E1D6 (USER32 00007FFF8C670000): (filename not available) (0): Ordinal2573
> 00007FFF8C67BC50 (USER32 00007FFF8C670000): (filename not available) (0): CallWindowProcW
> 00007FFF8C67B5CF (USER32 00007FFF8C670000): (filename not available) (0): DispatchMessageW
> 00007FFF8C676AEF (USER32 00007FFF8C670000): (filename not available) (0): IsDialogMessageW
> 0000000012937728 (mir_app 00000000128E0000): w:\miranda-build\src\mir_app\src\miranda.cpp (373): mir_main
> 0000000140002944 (Miranda64 0000000140000000): w:\miranda-build\src\miranda32\src\miranda.cpp (62): wWinMain
> 00000001400014BA (Miranda64 0000000140000000): f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl (288): __scrt_common_main_seh
> 00007FFF8A012784 (KERNEL32 00007FFF8A000000): (filename not available) (0): BaseThreadInitThunk
> 00007FFF8C840C31 (ntdll 00007FFF8C7F0000): (filename not available) (0): RtlUserThreadStart

**Comment by gituser** [comment]
It's a very annoying bug. Any chance of fixing it guys?

Thanks.
