### ISSUE TITLE
ICQ: "Invisible" status is broken

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1154]
When I set ICQ status to Invisible, I'm still Online for contacts (so I cannot hide).

**Comment by Larusek** [comment]
Exactly same problem.  As a workaround  you can set Online first and then change to Invisible - this way works.

**Comment by WalrusInAnus** [comment]
I can still see an invisible user as online. Not fixed as far as I can tell.

**Comment by georgehazan** [comment]
@WalrusInAnus yes, if he added you into the Visible list (Always Visible in terms of Miranda).
I've successfully tested that feature on iPhone

**Comment by WalrusInAnus** [comment]
I don't even see any visible list settings.
When I open the contact's details, it says online and not invisible.

**Comment by dartraiden** [comment]
"Invisible" working only if Miranda-side does not send any messages.

After first message sent from Miranda, Invisible not working.

**Comment by georgehazan** [comment]
Miranda IM behaves the same way, so that's smth that they changed at the server side
