### ISSUE TITLE
Doesn't display smileys in chat window

### ISSUE THREAD

**Issue by futuarmo** [miranda-ng/miranda-ng#1159]
### Expected behavior and actual
I'm using vk small smileys (it doesn't matter online or offline). When I send smiley, it displays in chat tab, but when my contact sends smiley to me, I got empty message.
I used app very long time, but bug appeared recently, the only change, that I made - turned on "Clean history older than 1 day" in HistorySweeperLight. HistorySweeperLight was installed and loaded with the app, but recently I turned on that option. Turning off HistorySweeperLight has no effect

### Does it work in stable version?
v.0.95.5 build 17337
0.95.7 build 18771 (6defdc1294) x64
0.95.8 alpha build #19301 (8227d51067) x64
Bug in stable and dev versions

### Steps to reproduce that behavior
Get smileys from other contact. I'm using vk protocol. I didn't test it with other protos.
[VersionInfoStable.txt](https://github.com/miranda-ng/miranda-ng/files/1739870/VersionInfoStable.txt)
[VersionInfoDebug.txt](https://github.com/miranda-ng/miranda-ng/files/1739871/VersionInfoDebug.txt)
[netlog.txt](https://github.com/miranda-ng/miranda-ng/files/1739876/netlog.txt)

**Comment by dartraiden** [comment]
Also
https://forum.miranda-ng.org/index.php?topic=28.msg21171#msg21171
