### ISSUE TITLE
CloudFile: auth doesn't work

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1171]
![default](https://user-images.githubusercontent.com/5046855/36757669-4110ee5a-1c23-11e8-88ed-c8d31021878e.png)

Click on the link leads zero results. Tested with Yandex and Dropbox. My default browser is Firefox.

**Comment by aunsane** [comment]
Click on link should open new IE window.

**Comment by dartraiden** [comment]
Can we use default browser instead IE?

**Comment by aunsane** [comment]
Of course. But if you have two account (of Dropbox e.g.) you should login and grant access for every account.
