### ISSUE TITLE
Add Support for Slack

### ISSUE THREAD

**Issue by sagamusix** [miranda-ng/miranda-ng#1178]
Slack is [phasing out](https://news.ycombinator.com/item?id=16539857) their XMPP and IRC integration in the next two months, making it impossible to connect to Slack through Miranda NG. There is a Slack plugin for Pidgin ([slack-libpurple](https://github.com/dylex/slack-libpurple)), so in theory it should be possible to have a native Slack plugin for Miranda NG.

**Comment by aunsane** [comment]
I started implementation of [Slack protocol](https://github.com/miranda-ng/deprecated/tree/master/NotWorkingStuff/Deprecated/Slack), but not found time and desire to continue. May be it would helpful for someone.

**Comment by dartraiden** [comment]
Slack prohibits any revers-engineering and threatens the developers who carry out these actions
https://g3rv4.com/2018/08/bye-bye-betterslack

**Comment by peci1** [comment]
Are there some miranda-libpurple bindings?

**Comment by dartraiden** [comment]
Does not exist unfortunately
