### ISSUE TITLE
Resurrect MagneticWindows plugin

### ISSUE THREAD

**Issue by sagamusix** [miranda-ng/miranda-ng#1179]
I used the MagneticWindows when still using Miranda IM, and it can still be found in the "deprecated" repository. Would it be possible to resurrect this plugin for Miranda NG to keep my desktop tidy?

**Comment by dartraiden** [comment]
We have [AsSingleWindow](https://www.youtube.com/watch?v=r73vpGrDXq8) plugin

**Comment by sagamusix** [comment]
I'm afraid that doesn't really do what I want; in particular I don't want my message windows to take up the same height as the contact list.

**Comment by georgehazan** [comment]
The problem is that we don't have the source code of recent MagneticWindows plugin. The version that was moved to /Deprecated can only dock windows one to another, but can't move them together

**Comment by sagamusix** [comment]
Quite honestly I wouldn't even mind that limitation.

**Comment by georgehazan** [comment]
so all you need is to dock windows together?.. but what is the point of it?

**Comment by georgehazan** [comment]
@sagamusix okay, returned it back

**Comment by sagamusix** [comment]
Thanks!

> but what is the point of it?

Mostly keeping them organized so that they don't float around on the desktop at random positions.
