### ISSUE TITLE
Unicode in file properties

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1182]
![666](https://user-images.githubusercontent.com/5046855/37233373-f2f95b24-2403-11e8-8c8e-bb103edc1046.png)

**Comment by georgehazan** [comment]
Windows don't support Utf-8 in version resource, so if you wanna see umlauts there, you need to return back to ANSI & codepage 1250 in the resource script

**Comment by dartraiden** [comment]
The year 2018, operating system still don't support UTF-8...
