### ISSUE TITLE
Discord: some special messages, events (stickers or deleted/edited) are never marked as read and make popup every logon

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#1193]
Sometimes i meet a problem with contact personal messages in Discord Miranda plugin - it's a smile or some sticker (or someone deletes/edits his message, or it's pinned event) - this message are forever unread - so every time you log-on Discord app in Miranda - it pop-ups again and again - can even happen 10 times a row... Only deleting contact log with problem event - helps.

**Comment by georgehazan** [comment]
I've tried to send smileys, delete/remove messages (from browser), pin/unpin event - everything is ok. reopen this bug if you have a network log

**Comment by LittleVulpix** [comment]
@georgehazan this issue is happening to me as well. For some reason it only "shows" if I use dbx_sqlite ... that said if I export the histories to json, I can see those events do not have the "r" flag.

**Comment by georgehazan** [comment]
@LittleVulpix yes, because mdbx stores this info on a different manner inside a contact...
dunno how to fix it during import, perhaps your idea about dbchecker & "Mark all events as read" was correct
