### ISSUE TITLE
Crash when applying changes to sound settings

### ISSUE THREAD

**Issue by imasuridondai** [miranda-ng/miranda-ng#1198]
### Expected behavior
Applying changes without a crash

### Actual behavior
A crash

### Does it work in stable version?
I dunno

### Steps to reproduce that behavior
Go to "Options..." > "Sounds"
Change any sound settings, f.e. check "Enable sound events" if unchecked or uncheck if checked
Click "OK" or "Apply"

[crash20180324111745.txt](https://github.com/miranda-ng/miranda-ng/files/1844133/crash20180324111745.txt)

**Comment by dartraiden** [comment]
Confirmed.

Crashlog with symbols
[crash20180324143944.txt](https://github.com/miranda-ng/miranda-ng/files/1844329/crash20180324143944.txt)
