### ISSUE TITLE
Database encryption mode

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1230]
- Change database encryption mode from Standard (default) to Total
- Press Apply button
- Checkbox returns to default mode

**Comment by leo-yuriev** [comment]
In general this is wrong approach. MDBX is strongly MVCC, therefore such "encryption" just creates a fresh encrypted copy of data, but previous unencrypted version still physically present and accessible (at least partial).

Properly implementation of encryption should be include the following steps/appointments:
1) create a new DB instance for encrypted data;
2) copy present record with encryption to new DB;
3) each record/item suitable for encryption should be prefixed with random salt (I recommend at least 8 bytes);
4) for check consistency of encrypted records/items the properly hash/checksum should be used:
   - but for security this checksum should not include the added salt-prefix from previos point,
   - instead it should include additional random salt-suffix (I recommend at least 8 bytes) and additional known string with length enougth to whitening of used hash/checksum
   - I recommend [t1ha2()](https://github.com/leo-yuriev/t1ha) and at least 64 bytes of known string;
5) close old DB without (!!!) deleting any data and then [DoD-erase](https://en.wikipedia.org/wiki/Data_erasure) the file on the disk.
6) User should be warned to decide to additional erasure of free-space on SSD/HDD.
