### ISSUE TITLE
Actman: Null pointer in mir_app.mir!CompareProtos

### ISSUE THREAD

**Issue by peci1** [miranda-ng/miranda-ng#1231]
After the last update (I'm on the unstable channel), Miranda crashes right after I start it and enter the decryption password.

Database migration was successful a week ago and I was able to use Miranda after it. This problem occured later.

Debugging in VS, I got this info:

```
>	mir_app.mir!CompareProtos(const MBaseProto * p1, const MBaseProto * p2) Line 28	C++	Symbols loaded.
 	mir_core.mir!List_GetIndex(SortedList * p_list, void * p_value, int * p_index) Line 139	C++	Symbols loaded.
 	mir_core.mir!List_Find(SortedList * p_list, void * p_value) Line 56	C++	Symbols loaded.
 	[Inline Frame] mir_app.mir!LIST<MBaseProto>::find(MBaseProto *) Line 228	C++	Symbols loaded.
 	mir_app.mir!Proto_GetUniqueId(const char * szModuleName) Line 179	C++	Symbols loaded.
 	Actman.dll!000000001710bc38()	Unknown	No symbols loaded.
```

`Exception thrown at 0x00000000128ED80D (mir_app.mir) in Miranda64.exe: 0xC0000005: Access violation reading location 0x0000000000000000. occurred
`

Unfortunately, the crash is before CrashReporter is initialized, so no useful dumps from it. I took a snapshot in VS, currently I'm uploading it, and I'll post a link when it's ready.

VersionInfo also unavailable due to the early crash. I'm using Win 10 64bit.

The Actman plugin was the problematic one - disabling it helped, Miranda starts normally. For me, it's a viable solution, since I think I didn't use this plugin at all...

**Comment by peci1** [comment]
Memory dump: https://drive.google.com/file/d/1cT8an4CdwRP8rnRdXKLDaK0Kk-EuAs4B/view?usp=sharing

**Comment by georgehazan** [comment]
@peci1 you better turn on option "Display parameter values in call stack" :) it's much more helpful than memory dumps. thanks for the good report

**Comment by peci1** [comment]
Oh, I haven't known about this option :) you learn something new every day, thanks.
