### ISSUE TITLE
Status menu doesn't change language until restart

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1241]

**Comment by georgehazan** [comment]
if you find any other menu items like these, list'em here & reopen the bug

**Comment by dartraiden** [comment]
Clist modern settings -> Extra icons
![extra](https://user-images.githubusercontent.com/5046855/38197888-0b7ea324-3693-11e8-9509-fbef5be5dedf.png)

**Comment by dartraiden** [comment]
Contacts -> Avatars
![avatars](https://user-images.githubusercontent.com/5046855/38197922-2fb15228-3693-11e8-8d1f-aec8a2bf6e68.png)

**Comment by dartraiden** [comment]
Icons -> Menu icons

![icons](https://user-images.githubusercontent.com/5046855/38198000-9952bc94-3693-11e8-86c5-dd6e8f882699.png)

**Comment by dartraiden** [comment]
Netlib log options

![netlib](https://user-images.githubusercontent.com/5046855/38198043-dc49a968-3693-11e8-90dc-348df81ab333.png)

**Comment by georgehazan** [comment]
Netlib options are translated in plugins, so the core can do nothing to it

**Comment by dartraiden** [comment]
Customize -> Hotkeys

![213213123](https://user-images.githubusercontent.com/5046855/38210743-f3678fb6-36c0-11e8-877b-c424d2e34abc.png)

**Comment by dartraiden** [comment]
Icons -> Menu icons still not fixed.
