### ISSUE TITLE
Cloudfile and Icolib

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1247]
А зачем подплагины Cloudfile регистрируют в иконлибе иконки статусов протокола? По старинке?

https://i.imgur.com/3Ofl6kc.png

**Comment by aunsane** [comment]
Судя по всему, эти иконки создаются автоматически при регистрации протокола.
@georgehazan, можно их не регистрировать, если протокол в капсах статусы никакие не декларирует?
