### ISSUE TITLE
Jabber stuck in offline

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1248]
> [Mataes] джаббер залипает в оффлайне и не идет в онлайн пока не тыкнешь сам руками офлайн и и онлайн :(
> [ghazan] ага. но только в случае ошибки

**Comment by Goraf** [comment]
Could be a duplicate. They were reports like that before. Sometimes the cause was a broken connection

**Comment by georgehazan** [comment]
closed as duplicate of #627
