### ISSUE TITLE
Sessions and avatars

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1249]
> [Mataes] ghazan: Гоша, а еще вот такая фигня: sessions поднимает вкладки видимо раньше чем успевают загрузиться аватары. и получается в окне у меня не показывается аватара контакта, хотя она у него есть
> [23:32:44] [Mataes] ghazan: и если закрыть вкладку и заново открыть, то аватара будет
> [23:33:22] [ghazan] ессно
> [23:33:27] [ghazan] странно вообще-то
> [23:33:35] [ghazan] а что, кэш аватаров пустой?
> [23:33:48] [Mataes] на диске аватара есть
> [23:33:57] [ghazan] совсем странно
> [23:34:12] [ghazan] тем более, что AVS грузится заведомо раньше Sessions
> [23:34:37] [Mataes] и ieview раньше
> [23:34:40] [Mataes] но факт)
> [23:35:51] [ghazan] вот у меня норм щас отработало
> [23:35:56] [ghazan] табсы же, да?
> [23:36:06] [Mataes] табсы+иевью
> [23:36:18] [ghazan] sessions поднял окно без аватара, потом оно прочихалось и аватара появилась
> [23:36:36] [Mataes] мож иевью не умеет так?
> [23:36:44] [ghazan] а он там никаким боком
> [23:36:54] [ghazan] он же только окно лога
> [23:36:58] [ghazan] и то через жопу
> [23:37:11] [Mataes] так в окне лога и рисуется аватара
> [23:37:43] [ghazan] и давно ? :)
> [23:37:44] [Mataes] ghazan: https://1drv.ms/u/s!AtyvHgNYmmo18UbQsm1ewxsU1Kv3
> [23:38:04] [Mataes] как бы скин такой всегда
> [23:38:05] [ghazan] а, слева
> [23:38:08] [Mataes] ага
> [23:38:16] [ghazan] вот это яхз... надо попробовать
> [23:39:17] [Mataes] похоже оно че вначале хватет, то и рисует всю дорогу
> [23:39:38] [ghazan] вероятно
> [23:39:55] [ghazan] надо посмотреть в Sessions... но это уже будет завтра

**Comment by dartraiden** [comment]
> ghazan: а раньше чтобы показать аватар в клисте оно сразу выгребалось
> ghazan: да и в табсы грузилось сразу

**Comment by georgehazan** [comment]
checked the clean profile - no problems at all with Jabber account.
it's smth related to IEView or the way how IE handles links to the local files

**Comment by georgehazan** [comment]
IEView shall hook ME_AV_AVATARCHANGED event to redraw avatars if needed
