### ISSUE TITLE
Дублирование контактов в чате Twitter при использовании сессий.

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#125]
**Reported by Radjah on 26 Jan 2013 10:07 UTC**
При использовании сессий и плагина twitter с включенным чатом наблюдается такой баг:
При загрузке миранды открываются все вкладки, в т.ч. чат Twitter. При этом Twitter еще offline, но в чате есть список участников с прошлого запуска.
Twitter подключается к сети, и чат заполняется дублями. Избавиться от дублей помогает выход и вход в учетной записи Twitter, при этом чат закрывается и открывается снова, но уже без дублей.
В качестве плагина чата используется Scriver.

**Comment by georgehazan** [comment]
**Comment by Rainman on 29 Jan 2013 20:00 UTC**
,   .

**Comment by dartraiden** [comment]
Seems like fixed.
