### ISSUE TITLE
omemo ui

### ISSUE THREAD

**Issue by sss123next** [miranda-ng/miranda-ng#1255]
ticked for tracking omemo ui implementation.

**Comment by DreamFlasher** [comment]
There were a couple of unadressed issues in the old thread -- shall we post bug reports here then?

With a new contact with who I have a Pidgin<->Conversations session, I get when I want to use Miranda: `Delivery failure: No valid OMEMO session exists`

Logs:
```
[10:38:54 0B2C] [JABBER_4] Jabber OMEMO: bug: omemo session does not have valid cipher
[10:38:54 0B2C] [JABBER_4] Jabber OMEMO: error: message does not encrypted for any sessions
```
The XML console only contains "message" entries, but no key exchange.

**Comment by Duke690** [comment]
Hi I'm trying to use MirandaNGs omemo encryption. At the moment I'm using a local ejabberd xmpp server. I tested omemo encryption on this server with different clients. It is working with pidgin-pidgin, gajim-gajim and conversion-gajim.
MirandaNG-MirandaNG is not working tho. Also MirandaNG omemo is not working with Gajim, Pidgin or Conversion.

MirandaNG-MirandaNG is showing this when trying to send a message:
[10:44:06 0710] [JABBER_2] Jabber OMEMO: error: message does not encrypted for any session
s

When trying to send omemo messages from MirandaNG to Gajim I get:
[11:01:02 1F48] [JABBER_1] Jabber OMEMO: bug: omemo session does not have valid cipher
[11:01:02 1F48] [JABBER_1] Jabber OMEMO: error: message does not encrypted for any session

On incoming Gajim omemo messages I get: 
[11:00:52 07D0] [JABBER_1] Jabber OMEMO: bug: omemo session does not exist or broken

I added complete MirandaNG console logs.
[miranda-miranda-user2.TXT](https://github.com/miranda-ng/miranda-ng/files/2034608/miranda-miranda-user2.TXT)
[miranda-miranda-user1.TXT](https://github.com/miranda-ng/miranda-ng/files/2034610/miranda-miranda-user1.TXT)
[gajim_miranda.TXT](https://github.com/miranda-ng/miranda-ng/files/2034609/gajim_miranda.TXT)

**Comment by sss123next** [comment]
also it's important to have miranda build with 31de2bbd767fee0c11ef1011d94d6ed14184e32d  fix

**Comment by sss123next** [comment]
@DreamFlasher, @Duke690  it's better to create separate tickets for bugs, this one for ui implementation tracking.

**Comment by vbprofi** [comment]
Hello experts,
if I try to send a Message from riseup.net with miranda-ng to xmpp.guru-account with conversations, I geht this error:
[12:58:23 25FC] [JABBER_1] Jabber OMEMO: error: message does not encrypted for any sessions.
Give an update of miranda-ng with 31de2bb-fix?

**Comment by sss123next** [comment]
this means what encrypted message does not encrypted for this device.
it's possible what remote does not received key for this device via jabber server event.
please open separate tickets for bugs, this ticket for ui,

**Comment by Neustradamus** [comment]
To follow this ticket.

**Comment by dartraiden** [comment]
I propose to add the following:

- [ ]  contact's userdetails tab with list of contac's devices with ids and fingerprints and ability to delete them individually (right click on id → Delete)
<img width="379" alt="Miranda64_gDbwhE6Uia" src="https://user-images.githubusercontent.com/5046855/170840391-f236bcd3-941c-43cf-9567-d24754c95dc6.png">
- [ ] same for my details (my ids and fingerprints of my devices), hightlghting of my current device (for example if I'm changed device and want to delete old device, but not accidentally delete current device)
<img width="379" alt="Miranda64_xi3Tkup6Ej" src="https://user-images.githubusercontent.com/5046855/170840602-8daecdda-21a4-4e4d-a959-f3e5935cd93e.png">
