### ISSUE TITLE
Cannot set chat message window text color

### ISSUE THREAD

**Issue by adlogic** [miranda-ng/miranda-ng#1270]
### Expected behavior
Possibility to change text color in message window

### Actual behavior
Always black

### Does it work in stable version?
Anywhere

### Steps to reproduce that behavior
I always use black and dark themes as always work in twilight or similar environment. Miranda always gave possibility to set background to be black and text to be white... But some years ago it seems broke and not possible to put white text in message window for chat only...

**Comment by georgehazan** [comment]
for which plugin? StdMsg, Scriver or tabSRMM?

**Comment by georgehazan** [comment]
![image](https://user-images.githubusercontent.com/4628541/38778596-a68d5d7a-40c4-11e8-8947-0b12e41412ef.png)
what am I doing wrong?

**Comment by adlogic** [comment]
In chat module (IRC for example). These are the settings I am speaking about:
https://i.imgur.com/okl5zyy.png

As you can see you can set message background, but you cannot set message text color here.

**Comment by dartraiden** [comment]
![default](https://user-images.githubusercontent.com/5046855/38959155-38063560-4368-11e8-826a-c4a7d8446649.png)

**Comment by dartraiden** [comment]
So it's StdMsg

**Comment by dartraiden** [comment]
Go to Message log and set up Message area text color.

**Comment by dartraiden** [comment]
@georgehazan, а почему так? Вот вид моего StdMsg:

![default](https://user-images.githubusercontent.com/5046855/38959523-ad60fb50-4369-11e8-8e00-0acc07f65f9c.png)

Все настройки, включая фон поля, куда я ввожу сообщения, настраивается через Chat module, но вот цвет текста настраивается через Message log, в котором настраиваются цвета для приватов:

![2](https://user-images.githubusercontent.com/5046855/38959620-fdd34732-4369-11e8-9e5e-88dedda1589b.png)

Я так понимаю, это последствия того, что чаты были в StdChat, а приваты в StdMsg? Может, сложить настройки цветов чатов/приватов в один раздел?

**Comment by dartraiden** [comment]
Another way: unify options for chats and private conversations

**Comment by dartraiden** [comment]
@adlogic,

> I will have white on white in all other message windows like Facebook/Jabber/etc.

You can set up white text and black background for all group chats and private conversations.

**Comment by adlogic** [comment]
@dartraiden yeah, right. I do not want to have all my private windows and everything else to be white on black, as you can imagine. So please do not unify them. Also it was working fine before, I think before that merge... So it should be just a matter of one setting, I do not think it is a huge issue, as all controls are already there.
