### ISSUE TITLE
При конвертации пропадают контакты News Aggregator и контакты протоколов, у которых отсутствует dll протокола

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1272]
Исходные данные: профиль mmap (сюда прикрепить не могу, вышлю по запросу). Содержит учётные записи ICQ, Jabber, Tox, 3 подписки в News Aggregator

Кладём профиль к стабле, скачанной с сайта. В стаблю добавляем плагин News Aggregator, но плагин Tox не добавляем.

Окно учётных записей:
![1](https://user-images.githubusercontent.com/5046855/38785205-b086a9ce-4125-11e8-9e4f-bd250451b5f2.png)

Список контактов (контакты Tox отображаются, можно посмотреть их историю, хоть протокол и не установлен). В редакторе базы они, само собой, отображаются с пометкой [UNLOADED]

![1](https://user-images.githubusercontent.com/5046855/38785241-25d1e626-4126-11e8-8b04-14c100d2d34d.png)

Обновляем до девелоперской версии, перезапуск, соглашаемся конвертировать профиль.
Из списка контактов пропадают контакты Tox и подписки News Aggregator. Из базы они тоже пропали. Вместо них появился один контакт `<UNKNOWN> [UNLOADED]`

**Comment by dartraiden** [comment]
Примечательно, что если до конвертации удалить любую учётную запись, то RSS-подписки сохраняются после конвертации.

**Comment by georgehazan** [comment]
можно запустить профиль мне на мыло?
