### ISSUE TITLE
Clist_blind, некоторые контакты не появляются в списке контактов после добавления учётной записи

### ISSUE THREAD

**Issue by jawhien** [miranda-ng/miranda-ng#1274]
При использовании clist_blind, после добавления учётной записи, некоторые контакты не отображаются. Решается проблема только после 1 - 2 переподключений. после чего всё отображается как надо.

**Comment by georgehazan** [comment]
@jawhien о каком именно протоколе идет речь? может быть, он просто не считывает все контакты с сервера?

**Comment by jawhien** [comment]
И с Jabber и с Vk. Ошибок никаких не появляется. Если включён clist_modern, все контакты сразу отображаются. CrashDumper установлен, но в лог ничего не пишет.
