### ISSUE TITLE
StdMsg: закрытие вкладки при двойном клике по контакту в списке контактов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1286]
Вкладка чата при двойном клике по чату в клисте закрывается. Но при двойном клике по контакту - нет.

**Comment by georgehazan** [comment]
duplicate of #1290: tab options were not applied to all subwindows

**Comment by dartraiden** [comment]
Надо привести поведение StdMsg, табсов и скривера к одному знаменателю:

StdMsg: при двойном клике по конфе в клисте вкладка конфы закрывается всегда.

TabSRMM: при двойном клике по конфе в клисте вкладка конфа закрывается, только если эта вкладка активна, иначе - делается активной.
