### ISSUE TITLE
Contacts from disabled accounts are displayed in certain conditions

### ISSUE THREAD

**Issue by Goraf** [miranda-ng/miranda-ng#1294]
If you enable disabled account, its contacts will be shown correctly, but if after that you disable it again, its contacts will not "disappear" but will be visible and displayed with Miranda icon (instead of protocol one) just like it was before. If you try to open history of such contact it will be shown as history of unknown contact but you will be able to see all its entries. The same will happen if you disable account that was enabled from the start. (Contacts from disabled accounts will be shown until restart.) If you try to go from [disabled -> ] enabled -> disabled -> enabled, then icons of contacts will stay incorrectly as Miranda one rather than those from protocols and will not reflect status of contact (tested with Clist Modern)

During tests with the above I encountered crash when trying to reopen options on "Ignore" page. Wasn't able to reproduce it.

[crash20180421174423.txt](https://github.com/miranda-ng/miranda-ng/files/1934779/crash20180421174423.txt)

**Comment by georgehazan** [comment]
they might be temporarily disabled, since their plugin gets unloaded, for example. after a plugin reappears, these accounts are automatically unblocked, as well as their contacts

**Comment by Goraf** [comment]
I don't see any changes on my side after last updates. Neither in AccMgr nor in clist (ClistModern).

I tried it with StdClist. Results are not exactly the same. If you start with disabled account and enable it then no contact will appear on clist after just that. But if you change account status to online then online contacts will appear, but only online. You wouldn't be able to force it to show offline contacts.

Crashlog from the tests. I was able to reproduce it only once while reseting Miranda with opened AccMgr window after eneabling/disabling jabber account for several times in a row.
```
>	mir_core.mir!WindowList_Remove(TWindowList * hList=0x0a9a4060, HWND__ * hwnd=0x00ed1c48) Line 70	C++
 	mir_app.mir!PROTO_INTERFACE::WindowUnsubscribe(HWND__ * hwnd=0x00ed1c48) Line 263	C++
 	mir_app.mir!CProtoIntDlgBase::DlgProc(unsigned int msg=2, unsigned int wParam=0, long lParam=0) Line 110	C++
 	Jabber.dll!CJabberDlgAccMgrUI::DlgProc(unsigned int msg=2, unsigned int wParam=0, long lParam=0) Line 1819	C++
 	mir_core.mir!CDlgBase::GlobalDlgProc(HWND__ * hwnd=0x00ed1c48, unsigned int msg=2, unsigned int wParam=0, long lParam=0) Line 345	C++
 	[External Code]	
 	[Frames below may be incorrect and/or missing, no symbols loaded for user32.dll]	
 	mir_core.mir!CDlgBase::GlobalDlgProc(HWND__ * hwnd, unsigned int msg, unsigned int wParam, long lParam=15539272) Line 345	C++
 	[External Code]	
 	mir_app.mir!mir_main(wchar_t * cmdLine) Line 337	C++
 	Miranda32.exe!wWinMain(HINSTANCE__ * hInstance=0x00400000, HINSTANCE__ * __formal=0x00000000, wchar_t * cmdLine=0x026c3e72, int __formal=10) Line 85	C++
 	[External Code]	
```
