### ISSUE TITLE
Add SendSS button to the TabSRMM toolbar

### ISSUE THREAD

**Issue by luckyrichpaulp** [miranda-ng/miranda-ng#1305]
1. Отображаются пункты плагина SendSS в меню контакта протокола Weather
Предлагает отправить скриншот. Думаю надо убрать. Зачем кому-либо контакту-погода отсылать скриншот? :)
2. Нет кнопки на панели TabSRMM. Хотелось бы добавить.

**Comment by dartraiden** [comment]
1. Не представляется возможным отключить этот пункт для виртуальных протоколов.
