### ISSUE TITLE
On first run after profile conversion some protocol plugins are loaded

### ISSUE THREAD

**Issue by Goraf** [miranda-ng/miranda-ng#1309]
On first run after profile conversion all protocol plugins (normal or virtual) are loaded even when still unchecked in plugins options.

**Comment by georgehazan** [comment]
no, they aren't loaded.
dlls are really loaded, but their Load() method is not executed, so there's no difference for user

**Comment by Goraf** [comment]
At least Weather and LotusNotify will show their dialogs
