### ISSUE TITLE
Adopt proxySwitch plugin

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1317]
https://addons.miranda-ng.org/ru/detail/1682?magic=1

requested via forum

**Comment by aunsane** [comment]
> This plugin requires modified Netlib. It is not possible to change the proxy settings run-time and it is not possible to determine which network interface is used by Miranda IM without this modification. It means that you need new modified miranda32.exe!
It seems that it's impossible to adopt to MNG.

**Comment by tweimer** [comment]
That statement is from 2005. It might be possible with the new netlib hooks.

**Comment by Mataes** [comment]
[diff.zip](https://github.com/miranda-ng/miranda-ng/files/2123009/diff.zip)
it is a patches for netlib for this plugin

**Comment by dartraiden** [comment]
Adopted.
