### ISSUE TITLE
Facebook: after using invisible status and back to online, online contacts don't instantly show up as online

### ISSUE THREAD

**Issue by Llamatron2112** [miranda-ng/miranda-ng#1319]
When setting the status to invisible on Facebook, all contacts show as offline, and the website's chat is turned off. That's the expected behaviour. But when setting the status back to online, the online contacts don't instantly show up, instead they seem to appear one by one, apparently as their status change.

**Comment by Goraf** [comment]
@zemiacsik it is a known, not from today, kind of limitation. I think that Robyer mentioned something about it on the forum.

**Comment by dartraiden** [comment]
Please test new Facebook protocol. It was rewritten from scratch and I cannot longer reproduce this bug.
