### ISSUE TITLE
Ordinal 116 not found in mir_app.mir

### ISSUE THREAD

**Issue by sagamusix** [miranda-ng/miranda-ng#1320]
### Expected behavior
No error message.

### Actual behavior
An error message saying something like "The ordinal 116 was not found in the dynamic link library mir_app.mir" is shown when opening the settings dialog in Miranda NG 0.95.8.

### Does it work in stable version?
This was experienced when upgrading to the latest stable.

### Steps to reproduce that behavior
 * Open settings dialog.

**Comment by dartraiden** [comment]
Yes, because some old files (deprecated plugins, etc) still in place and cannot be loaded with new core.

**Comment by dartraiden** [comment]
@georgehazan, try to update old stable with some of the deprecated protocols (AIM, Whatsapp, etc). Seems like core not banned them?

**Comment by georgehazan** [comment]
well, imho we added all deprecated dlls into that list
@sagamusix if you could detect which dll produces this message, we'd block it too

**Comment by sagamusix** [comment]
After using the update checker once more the problem disappeared, so I don't know exactly which plugin caused it. From what I remember, there were four plugins on the list... DbChecker was in there twice with two different extensoins though, maybe that was the problem? Other than that I remember there was AIM, but that shouldn't have been activated.

**Comment by georgehazan** [comment]
It's fixed anyway, this message is suppressed
