### ISSUE TITLE
When connecting to only some protocols, the notification area icon shows offline icon

### ISSUE THREAD

**Issue by sagamusix** [miranda-ng/miranda-ng#1321]
### Expected behavior
Suppose I use several instances of several protocols, but I only set half of them to online and the others to offline. Previously, the icon in the notification area would turn blue (online) if all the protocols that I set to online were connected. If they were disconnected temporarily, the icon would turn grey.

### Actual behavior
In Miranda 0.95.8, the icon stays grey even some protocols are not connected, and for some reason it turns blue while connecting to a protocol. It's as if the two icons are swapped.

### Does it work in stable version?
This is the stable version.

### Steps to reproduce that behavior
 * Connect and disconnect to various protocols.

**Comment by sagamusix** [comment]
I'm using clist_nicer. I cannot find Contact list - Tray though, or do you mean the first page of that branch which contains a couple of mentions of "Tray"?

**Comment by georgehazan** [comment]
caused by wrong fix of #1304
