### ISSUE TITLE
[0.95.8 x64] IRC accounts & random server names

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#1322]
### Expected behavior
After creating several IRC accounts with their own custom servers, Miranda NG should display the correct server, password etc. every time you visit them through Options -> Network.

### Actual behavior
The server settings in Options -> Network persist only until Miranda NG is restarted. Afterwards, the account settings may be (visually) replaced by other random servers. Passwords are still shown.

Even after erasing the whole IRC server list by hand and leaving only custom servers in the list, Miranda NG will still shuffle the servers around for the various accounts.

Note that the accounts still connect properly even when showing the wrong servers in Options -> Network. So there is a schism somewhere between what's displayed and what's saved.

### Does it work in stable version?
No, this is an old bug since Miranda IM days.

### Steps to reproduce that behavior
- Create several IRC accounts with custom servers.
- Restart Miranda NG.
- Open Options -> Network and visit the IRC accounts. Check if the server info is correct.

Miranda NG Version: 0.95.8 build 19942 (9db2e1eb71) x64
¤ IRC.dll v.0.95.7.2 [4 May 2018 2:03:54] - IRC protocol

**Comment by dartraiden** [comment]
Cannot reproduce. Can you provide exact names (Network name, description)?

**Comment by Tharn** [comment]
After a lot of time passed and I looked into the options, it happened again. The 'default network' shown for various IRC accounts are not the ones to which the accounts connect.

**Comment by Tharn** [comment]
I traced it down to the following:

Go into Contact List > Accounts. Hit 'Reset'. Restart Miranda NG.
Then go into Contact List > Accounts and change the order. Hit 'OK'.
Go into Settings and check the various IRC Networks. Now the server names & server info should be shuffled. IRC can still connect, but the data displayed is wrong.

**Comment by Tharn** [comment]
It happened again when I updated from stable to nightly.

In stable, I had deleted ALL servers and only used 6 IRC accounts with 6 servers that I added.
When I moved to nightly and the IRC plugin updated, it added back the hundreds of standard IRC servers that Miranda NG comes with. All 6 accounts had their account info changed to servers early in the alphabet, i.e. 4-irc, ABlinux, Accessirc and so on.

The accounts still connect, but the display of the server is wrong both in options and in the accounts list.

**Comment by georgehazan** [comment]
@Tharn simply remove servers.ini in the /Plugins subfolder, it will never happen again

**Comment by Tharn** [comment]
There is no servers.ini in my subfolder.

**Comment by Tharn** [comment]
Server Name STRINGs in the Database are correct, but options / accounts UI shows this:

![1](https://user-images.githubusercontent.com/13466852/111960038-81892e00-8aef-11eb-86e3-04f415c1a74a.png)
![2](https://user-images.githubusercontent.com/13466852/111960042-82ba5b00-8aef-11eb-9f84-6f154ab15e03.png)
![3](https://user-images.githubusercontent.com/13466852/111960044-83eb8800-8aef-11eb-960b-17772d75e37c.png)
![4](https://user-images.githubusercontent.com/13466852/111960046-851cb500-8aef-11eb-8bc8-2384adc35a87.png)
![5](https://user-images.githubusercontent.com/13466852/111960048-864de200-8aef-11eb-8338-7303ef1f34a2.png)

**Comment by dartraiden** [comment]
I suggest to just kill the list of all preset servers in the our repository

**Comment by dartraiden** [comment]
@Tharn please delete all these servers from db manually

**Comment by Tharn** [comment]
georgehazan, this fix removes all the pre-set servers,
it does not fix the issue of wrong servers being displayed in options after days? weeks? of use.

**Comment by georgehazan** [comment]
@Tharn you can use dbeditor++ to remove all unneeded server table entries from Settings / IRC_Servers

**Comment by Tharn** [comment]
Yes, I did that.
The issue 1322 is about wrong servers being shown in options & accounts lists. It mixes them up. It still does it even if there are only 6 servers in the list.
I'm pretty sure that's unrelated. But I'll poke you again if it happens again.

**Comment by dartraiden** [comment]
Maybe we should get rid of all these "Networks" and use a simple Jabber-like scheme "1 account = 1 server"?

**Comment by dartraiden** [comment]
Current vs proposal

![current](https://user-images.githubusercontent.com/5046855/112074546-9b764f80-8b87-11eb-95fc-fb70286b6e9d.png)

![image](https://user-images.githubusercontent.com/5046855/112074566-a5984e00-8b87-11eb-8967-b5b6cb138302.png)

**Comment by Tharn** [comment]
Yes, I don't see the point in this strange duplication either.
Could set each account with server URL, port etc. like hexchat and others do it.
