### ISSUE TITLE
Обновление с 0.94.9 до 0.95.8 приводит к невозможности конвертации профиля 

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1323]
Как известно, пользователи, переходящие с Miranda IM, сначала с помощью IM Updater обновляют IM до NG 0.94.9. Далее PluginUpdater находит и закачивает последнюю стаблю (0.95.8), перезапускает Миранду... и вместо предложения сконвертировать профиль получают сообщение, что их профиль в неизвестном формате.

Воспроизводится (у меня) так: взять свежую 64-битную [Miranda IM 0.10.80](https://sourceforge.net/projects/miranda/files/miranda-im/0.10.80.0/miranda-im-v0.10.80-x64.7z/download), создать MMAP-профиль (необязательно заводить в профиле учётки), закинуть IM Updater. Дальше он закачивает обновление до 0.94.9, перезапуск, закачивает обновление до 0.95.8, перезапуск - и опачки.

**Comment by BLF0x** [comment]
Такой же баг проявился. Вылечилось ручным обновлением в плагинах Dbx_mmap.dll при этом я еще заметил что плагин апдейтер когда обновлял не выставил галки на всех плагинах (ну вернее как я все галки не проверял, но точно помню что в момент когда шел апдейт -- несколько плагинов было проскипано,поскольку галки не стояли.. Сам я их не снимал). Либо это плагин апдейтер где то в настройках "вспомнил" (и было бы неплохо при апдейте до новой версии ядра принудительно апдейтить ВСЕ плагины, а не только отмеченные).
