### ISSUE TITLE
User reported: after database conversion WhatsApp history is lost

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1324]
Since WhatsApp plugin was removed, user installs Dummy and successfully recover WhatsApp contacts, but history is lost.

**Comment by Goraf** [comment]
Upgrade to Dummy was made before or after conversion?

**Comment by dartraiden** [comment]
After.

**Comment by Goraf** [comment]
Could Import plugin imports such history from old profile?

**Comment by dartraiden** [comment]
Yes, the user successfully imported WhatsApp history from the old profile.
