### ISSUE TITLE
Обновление с версии 095.7 до 0.95.8 - исчезла история

### ISSUE THREAD

**Issue by SergSuppa** [miranda-ng/miranda-ng#1328]
Обновление с версии 095.7 до 0.95.8 - исчезла история
Обновилась миранда, все плагины, вроде всё нормально. Перезапустил - появилось сообщение, что база в старом формате, надо конвертировать. Ок, конвертировал. И всё,  пропала вся история, остался только список контактов.

Вернулся на старую версию 095.7 , DbChecker прогнал - не помогло. Конвертация базы упорно приводит к тому, что в новом файле user.dat нет истории. 

Причём, её реально нет, сам файл user.dat в сотни раз меньше весит, чем до конвертации

**Comment by dartraiden** [comment]
История какого протокола?

**Comment by georgehazan** [comment]
контакты мигрируют, а история - нет?
размер профиля большой?

**Comment by lanmaster** [comment]
Тоже пропала история переписки.  Причем вновь написанные сообщения в истории появляются.

**Comment by georgehazan** [comment]
@lanmaster а можно прислать мне в мыло старый профиль с одним таким контактом хотя бы, на котором пропадает история? и без пароля на учетку. конфиденциальность данных 100% гарантируется

**Comment by lanmaster** [comment]
@georgehazan Возможно, не понадобится. Примерно понял в чем проблема. У меня миранда запускается из сетевой папки, прокинутой на Linux-сервер через SFTPNetDrive. Вероятно, ломается профиль, при конвертации в новый формат. Починил так: вытащил исправный профиль (от 10 мая) из бэкапа, перенес миранду на локальный диск, заменил профиль на исправный, запустил. Проблема не выявилась. Перенес всю папку миранды обратно на sftp-драйв, тоже полет нормальный. Возможно, профиль сломался при сетевом сбое и отвале sftp-диска. Хотя, на старом формате профиля все работало более полугода без сбоев.

**Comment by lanmaster** [comment]
Конвертация прошла успешно, история не потерялась. Что делал:
1. Все запуски миранды проводились с SFTP-драйва
2. Взял из бэкапа профиль от 6 мая
3. Запустил, запросилась конвертация, согласился. После конвертации история на месте.
4. Запросилось обновление, пока отказался. История на месте.
5. Перезапуск, обновление, история на месте.
Итого все работает, в чем была проблема - не понял.

**Comment by georgehazan** [comment]
>Итого все работает, в чем была проблема - не понял.

Проблема в нерабочей блокировке профиля на сетевом диске, как только ее отключили, всё стало нормально.

>Кстати, размер файла профиля не уменьшается в сотни раз, как в первом посте. История реально есть, но ее не видно в окне переписки и в окне истории.

а если этот профиль сжать?
