### ISSUE TITLE
StdMsg: rework "Send message on" settings

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1331]
"Send message on Enter" and "Send message on double enter" should be radio buttons, not check boxes. Because this is opposed settings. Also we should add third option "Send message on Ctrl+Enter".

**Comment by dartraiden** [comment]
Also, these options are broken. Even if "Send message on double enter" is enabled and "Send message on Enter" is disabled, message sends on Enter.

**Comment by georgehazan** [comment]
if you really want a new option to be created, extract it into the separate ticked with label 'enchancement'
