### ISSUE TITLE
StopSpamMod: unable to add accounts to "Filtered accounts" list

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1339]
![default](https://user-images.githubusercontent.com/5046855/39831730-0a2c2f0c-53ce-11e8-808c-4d86328727ef.png)

After moving accounts from left list to right and pressing OK, reopen settings => nothing is changed

**Comment by sss123next** [comment]
i will check it.

**Comment by sss123next** [comment]
probably fixed by 0d3c50e1d4280ab0622326cd77224f2ce6aa4e77 , reopen if problem still exists
