### ISSUE TITLE
Add 0.95.7 and 0.95.6 builds https://miranda-ng.org/distr/deprecated/

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1341]

**Comment by dartraiden** [comment]
https://miranda-ng.org/distr/deprecated/0.95.7/

Core: missing StdAuth and StdHelp
Core: Dummy shouldn't be in core package
H++ doesn't work
Missing Dropbox plugin
CloudFile should be removed from x32 and x64

**Comment by georgehazan** [comment]
I can't compile the real 0.95.7.3 build because its branch was removed from git

**Comment by dartraiden** [comment]
Please, add AdvaImg to core package

**Comment by georgehazan** [comment]
done
