### ISSUE TITLE
Scriver: remove "Use the contact's status icon as the window icon" option

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1347]
Same as StdMsg
https://github.com/miranda-ng/miranda-ng/commit/8f281c8de4a2b3c9cc000673cc63b015c6ce3d62

"Use the contact's status icon as the window icon"
IDC_STATUSWIN
SRMSGSET_STATUSICON
SRMSGDEFSET_STATUSICON

**Comment by jawhien** [comment]
and that's bad. now in the window titlebar no text information about the status of the contact, which I would love to have there :(

**Comment by dartraiden** [comment]
@jawhien, #1354
