### ISSUE TITLE
Add "with debug symbols" checkbox to PU

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1355]
Problem: user forgot to update debug symbols in stable version, because PU cannot update symbols for stable

Solution:
1) Pack stable Miranda with symbols on server (same as we already do for dev version)
2) Add checkbox "with debug symbols" to PU

So users can easily switch between stable<->nightly and between with_symbols<-> without_symbols

**Comment by AnrDaemon** [comment]
I suggest to always pack nightly with debug symbols.
I mean, there's very little reason not to.
