### ISSUE TITLE
StdMsg: "Send on Ctrl+Enter" setting is lost after upgrade

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1358]
Old stable:

![2](https://user-images.githubusercontent.com/5046855/39998496-ed92459c-578e-11e8-9a9f-4a049a70d194.png)

Both "Send message on" settings are disabled, so message sending on Ctrl+Enter

New stable:

![3](https://user-images.githubusercontent.com/5046855/39998522-03748d84-578f-11e8-9f59-e81c30367b1b.png)

sending on Ctrl+Enter should be enabled, but... no

**Comment by georgehazan** [comment]
в смысле lost, если его не было в профиле? :)
