### ISSUE TITLE
Не открывается окно беседы

### ISSUE THREAD

**Issue by daemvil** [miranda-ng/miranda-ng#1366]
После вчерашнего обновления Миранды (16.05.2018) перестали открываться окна бесед. Сообщения приходят, в истории сообщений появляются.

VersionInfo:
Miranda NG Version: 0.95.8 alpha build #20028 (56239fcddd) [running inside WOW64]
Build time: 17 May 2018 2:00:40
Profile: (MDBX database driver)
Profile size: 31457280 Bytes
Profile creation date: 12 Dec 2017 17:18:03
Language pack: Russian (RU) [0419]
Service Mode: No

Active Plugins (32):
¤ AVS.dll v.[b]0.98.1.1[/b] [17 May 2018 2:00:44] - Avatar service 
¤ Clist_nicer.dll v.[b]0.9.3.1[/b] [17 May 2018 2:00:46] - Clist nicer 
¤ Cln_skinedit.dll v.[b]0.0.0.4[/b] [17 May 2018 2:00:46] - Skin editor for Clist nicer 
¤ CrashDumper.dll v.[b]0.1.0.2[/b] [17 May 2018 2:01:16] - Crash dumper 
¤ DbEditorPP.dll v.[b]4.0.1.2[/b] [17 May 2018 2:01:16] - Database editor++ 
¤ Dbx_mdbx.dll v.[b]0.95.8.7[/b] [17 May 2018 2:02:04] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.[b]0.95.8.1[/b] [17 May 2018 2:00:44] - Miranda NG mmap database driver 
¤ Dummy.dll v.[b]0.2.0.0[/b] [17 May 2018 2:01:46] - Dummy protocol 
¤ historypp.dll v.[b]1.5.1.5[/b] [18 Apr 2018 22:19:56] - History++ 
¤ ICQ.dll v.[b]0.95.8.1[/b] [16 May 2018 2:00:50] - IcqOscarJ protocol 
¤ IEView.dll v.[b]1.5.0.1[/b] [8 May 2018 2:00:48] - IEView 
¤ Import.dll v.[b]0.95.8.6[/b] [17 May 2018 2:01:06] - Import contacts and messages 
¤ IRC.dll v.[b]0.95.8.1[/b] [16 May 2018 2:00:48] - IRC protocol 
¤ Jabber.dll v.[b]0.11.0.5[/b] [16 May 2018 2:01:28] - Jabber protocol 
¤ KeyboardNotify.dll v.[b]1.5.7.7[/b] [8 May 2018 2:00:56] - Keyboard notify ext. 
¤ MessageState.dll v.[b]0.0.1.0[/b] [8 May 2018 2:01:44] - Message state 
¤ MirOTR.dll v.[b]0.14.1.16[/b] [10 May 2018 2:01:58] - Miranda OTR 
¤ MRA.dll v.[b]2.1.1.1[/b] [16 May 2018 2:01:00] - Mail.ru Agent 
¤ PluginUpdater.dll v.[b]0.1.2.5[/b] [8 May 2018 2:01:14] - Plugin updater 
¤ Popup.dll v.[b]2.1.1.14[/b] [16 May 2018 2:00:58] - Popup plus 
¤ Restart.dll v.[b]0.0.6.0[/b] [8 May 2018 2:01:14] - Restart 
¤ SeenPlugin.dll v.[b]5.0.5.3[/b] [10 May 2018 2:00:46] - Last seen 
¤ SmileyAdd.dll v.[b]0.3.0.2[/b] [17 May 2018 2:01:14] - SmileyAdd 
¤ SpellChecker.dll v.[b]0.2.6.6[/b] [8 May 2018 2:01:48] - Spell checker 
¤ SplashScreen.dll v.[b]0.1.2.3[/b] [8 May 2018 2:00:56] - Splash screen 
¤ StopSpamMod.dll v.[b]0.0.2.3[/b] [8 May 2018 2:01:20] - StopSpam mod 
¤ TabSRMM.dll v.[b]3.5.0.9[/b] [17 May 2018 2:00:50] - TabSRMM 
¤ Tipper.dll v.[b]2.1.0.7[/b] [8 May 2018 2:00:54] - Tipper 
¤ TopToolBar.dll v.[b]0.8.0.5[/b] [10 May 2018 2:00:54] - TopToolBar 
¤ Tox.dll v.[b]0.11.3.2[/b] [16 May 2018 2:02:22] - Tox protocol 
¤ VKontakte.dll v.[b]0.1.4.5[/b] [16 May 2018 2:01:42] - VKontakte protocol 
¤ Weather.dll v.[b]0.4.0.3[/b] [16 May 2018 2:01:24] - Weather 

Weather ini files:
-------------------------------------------------------------------------------
 gismeteo.ini v.[b]2012.05.03[/b] [12 Aug 2017 11:23:46] - GisMeteo
 msn.ini v.[b]2014-11-08[/b] [12 Aug 2017 11:23:46] - MSN Weather (New Layout)
 weatherxml.ini v.[b]0.0.5.3 2009-07-16[/b] [12 Aug 2017 11:23:46] - WeatherXML
 wundergrnd_intl.ini v.[b]2011/02/13[/b] [12 Aug 2017 11:23:46] - Weather Underground Int'l
 wundergrnd_xml.ini v.[b]2011/02/13[/b] [12 Aug 2017 11:23:46] - Weather Underground XML

Protocols and Accounts:
-------------------------------------------------------------------------------
ICQ                      0 - Enabled 1 - Disabled  Loaded
JABBER                   2 - Enabled 2 - Disabled  Loaded
MRA                      2 - Enabled 1 - Disabled  Loaded
TOX                      0 - Enabled 1 - Disabled  Loaded
VKontakte                1 - Enabled 0 - Disabled  Loaded
WhatsApp                 0 - Enabled 1 - Disabled  Loaded

Icon Packs:
-------------------------------------------------------------------------------
 Flags_icons.dll [8 May 2018 2:02:12]
 HistoryPP_icons.dll [19 Apr 2018 2:02:08]
 Proto_AIM.dll [12 Dec 2017 4:06:28]
 Proto_Dummy.dll [17 May 2018 2:02:24]
 Proto_Facebook.dll [16 May 2018 2:02:26]
 Proto_GG.dll [16 May 2018 2:02:28]
 Proto_ICQ.dll [16 May 2018 2:02:26]
 Proto_IRC.dll [16 May 2018 2:02:26]
 Proto_Jabber.dll [16 May 2018 2:02:26]
 Proto_MetaContacts.dll [17 May 2018 2:02:24]
 Proto_MRA.dll [16 May 2018 2:02:26]
 Proto_MSN.dll [16 May 2018 2:02:28]
 Proto_Tox.dll [16 May 2018 2:02:28]
 Proto_VKontakte.dll [16 May 2018 2:02:28]
 Proto_Weather.dll [16 May 2018 2:02:28]
 TabSRMM_icons.dll [17 May 2018 2:02:24]
 Toolbar_icons.dll [17 May 2018 2:02:24]
 xStatus_ICQ.dll [16 May 2018 2:02:28]
 xStatus_Jabber.dll [16 May 2018 2:02:28]
 xStatus_MRA.dll [16 May 2018 2:02:28]

**Comment by georgehazan** [comment]
было исправлено сразу после выкладки, сейчас всё хорошо
