### ISSUE TITLE
Chat window icon changed in 0.95.8 update

### ISSUE THREAD

**Issue by sagamusix** [miranda-ng/miranda-ng#1369]
### Expected behavior
My icons should stay as they were configured.

### Actual behavior
One if the previous 0.95.8 updates (not the first 0.95.8 version) changed my chat window icons; previously I always saw the same icon for all contacts, no matter which protocol. Now I see protocol icons in the taskbar instead. 

### Does it work in stable version?
This is the latest 0.95.8 release.

**Comment by dartraiden** [comment]
Yes, because of we turn on "Use contact status icon as window icon" settings and remove this setting.

**Comment by sagamusix** [comment]
Yes, it's StdChat.

**Comment by georgehazan** [comment]
bug is fixed in the dev version
@sagamusix test it please there, if everything is ok, I'll port it back to the stable version

**Comment by sagamusix** [comment]
I can confirm it's fixed in testing.
