### ISSUE TITLE
StdMsg: курсор перестаёт мигать

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1372]
Открываем конфу, ставим курсор в поле ввода. Курсор (в виде вертикальной линии) мигает. Ждём секунд 10, не двигая мышью - курсор перестаёт мигать. Это какая-то нездоровая фигня, потому что он должен мигать и дальше.

**Comment by georgehazan** [comment]
это поведение винды теперь такое, к миранде отношения не имеет
для проверки нажимаем Win+R
