### ISSUE TITLE
Discord - Option to not display or log embedded link data.

### ISSUE THREAD

**Issue by RathaWynter** [miranda-ng/miranda-ng#1375]
Often when sending or receiving a link using the Discord protocol in Miranda, Discord will create embedded data which displays as a second message sent from you or your partner a few seconds later. According to [Vulpix](https://forum.miranda-ng.org/index.php?topic=4985.msg21706#msg21706) this may also result in this embed data being attributed to the wrong sender as well under certain conditions.

The embed text being shown and logged creates significant clutter in the chat log and history. Additionally, for every link posted 3 links are created; the original, the embedded one in a new message, and a third preview link for the embed. This is in addition to multiple lines of formatting and any text retrieved from the webserver for that embed.

For these reasons it would be nice to have the option for 'Do not display embedded data' and 'Do not log embed data' on the discord plugin. (Future plugins like IEView could possibly make use of this data, but TabSRMM and History++ do not.)

### Expected behavior
When you send or receive a link, no multi-message embedded data gets displayed or logged.
![problem_with_discord_embeds_fix](https://user-images.githubusercontent.com/35881801/40261655-192302b8-5abf-11e8-9b19-699ede4d7148.jpg)

### Actual behavior
Sending a link causes significant amounts of meta data clutter to be displayed and logged.
![problem_with_discord_embeds](https://user-images.githubusercontent.com/35881801/40261658-1d9e38f8-5abf-11e8-818e-3fbb18f7fa46.jpg)

[VersionInfo.txt](https://github.com/miranda-ng/miranda-ng/files/2018891/VersionInfo.txt)

**Comment by georgehazan** [comment]
no, it's not a separate message, that's an embedded url attached to the same message, so there's no risk of applying an url to another contact.

**Comment by RathaWynter** [comment]
Maybe theres a miscommunication here, but the embedded data seems to both display and be logged into history as a separate message with a different time stamp (as shown in the second image.) For example, a friend sends me a 648 character message with 4 links in it, and then ~3-10 seconds later another message entry with 2057 characters (More than 3 times the size of the original post) is displayed and logged as a new message.

I have also seen the embed data for a link arrive 8 seconds -before- the original message in the display window (and be logged into history with the embed first and the message after) as well, which is why I included a link to Vulpix's forum comment as it sounded plausible that the issue he mentioned was also legitimate.

My interest is simply in having an option to not display or log embed data at all, which would solve all my issues such as the embeds showing up out of order, the embeds creating duplicate links, and the embeds adding data that was not contained in the original message which increases the size of the database and clutters up the chat window and makes it confusing to read and scroll through. Additionally not displaying the embed data would possibly eliminate the problem Vulpix reported having as well.

**Comment by georgehazan** [comment]
yes, that's what I don't understand at all :)
at my side it looks like that
![image](https://user-images.githubusercontent.com/4628541/41614894-5f5404c4-7402-11e8-9a54-55afb33abd79.png)

would you mind please to add a network log that illustrates this problem?

**Comment by RathaWynter** [comment]
Thats different. Theres no embed data for pictures hosted on the discord server (attachments) as far as Im aware. Try sending or receiving the follow links through Discord, both should produce embedded text:
https://icq.com
https://www.youtube.com/watch?v=vy1iK17cnbU

Pasting the above links should recreate the problem, but will include a heavily sanitized netlog in case you're unable to reproduce the issue by simply pasting either of those links to someone. Typically links to websites (but not all websites) can cause the 'extra embeded text' problem. Happens quite often with Youtube videos for example. (But strangely not all of them.)

[Discord_Embedlink_Netlog.txt](https://github.com/miranda-ng/miranda-ng/files/2116626/Discord_Embedlink_Netlog.txt)

**Comment by RathaWynter** [comment]
@georgehazan No, it applies to both messages that are sent or received.

![sent_and_received](https://user-images.githubusercontent.com/35881801/41693719-cb2c2ffc-74c3-11e8-8831-6ba14e14105d.png)

**Comment by georgehazan** [comment]
I see... Discord protocol allows to update previously received message, Miranda simply doesn't support this mode right now

**Comment by RathaWynter** [comment]
Does that mean that its currently not possible to ignore/block/delete messages with the 'embed' info in them? Currently Miranda's implementation of the protocol does not display or log incoming voice chat requests, so I would have assumed that there was also a similar way to filter the embedded messages out as well, even if it was as simple as text matching: '----------------- Embed: http' and then ignoring / not logging / not displaying messages containing that string.

**Comment by georgehazan** [comment]
it's not reasonable to block or ignore messages with embedded links, because for people with IEView these messages are essential (IE automatically converts a link into preview). Also, if such an info is present in the first message, it shall not be lost anyway

this problem is slightly different: Discord sends the first message as a new message and the second message as an update for the first message. I can try to ignore these updates for now

**Comment by RathaWynter** [comment]
Ahh right, I was not aware that IEView actually supported the embedded message, so this should probably be implemented as an option in the protocol settings to give users the choice on whether or not to display that data. If it can be filtered anyway.

**Comment by georgehazan** [comment]
fixed, using server message id handling

**Comment by RathaWynter** [comment]
I just tested this and it does not appear to be fixed sadly. Version 0.95.11 #21092. 2018-12-28.

**Comment by RathaWynter** [comment]
I just tested this and it does not appear to be fixed sadly. Version 0.95.11 #21092. 2018-12-28.

**Comment by RathaWynter** [comment]
I just tested this and it does not appear to be fixed sadly. Version 0.95.11 #21092. 2018-12-28.
Am seemingly unable to edit posts or attach files in this issue anymore.

This is what should happen when i send a message:
https://i.imgur.com/vXCoq6H.png

This is what actually happens. Message is duplicated and embedded data is included.
https://i.imgur.com/33coipi.png

This is what gets logged in History++
https://i.imgur.com/1TuZpqk.png

Is there any way to stop this from happening when sending links? (Dont want any embed data to show in the chat window or the history.)

**Comment by RathaWynter** [comment]
To help clarify the issue if its not already understood:

I want to send / log only this message on Discord:
If you've ever played Diablo 1, this is kinda funny:
https://www.youtube.com/watch?v=Bhe-KD7fE_A

-

What actually gets sent / logged is this:
If you've ever played Diablo 1, this is kinda funny:
https://www.youtube.com/watch?v=Bhe-KD7fE_A
-----------------
Embed: https://www.youtube.com/watch?v=Bhe-KD7fE_A
	YouTube video
	Help Support the Cartoons: http://www.patreon.com/carbotanimations Shirts: https://www.teepublic.com/user/carbotanimations http://www.carbotanimations.com Fo...
Preview: https://i.ytimg.com/vi/Bhe-KD7fE_A/hqdefault.jpg

-

The original message contains 96 characters including 1 link.

Two messages show up in the local chat window after sending a message. Message #1 (original) contains 96 characters and 1 link. Message #2 (embed) contains 400 characters and 6 links for a total of ~500 characters and 7 links.)

The history++ log contains 400 characters and 6 links when it should only contain 96 characters and 1 link.

**Comment by RathaWynter** [comment]
To help clarify the issue if its not already understood:

I want to send / log only this message on Discord:
If you've ever played Diablo 1, this is kinda funny:
https://www.youtube.com/watch?v=Bhe-KD7fE_A

---

What actually gets sent / logged is this:
If you've ever played Diablo 1, this is kinda funny:
https://www.youtube.com/watch?v=Bhe-KD7fE_A

Embed: https://www.youtube.com/watch?v=Bhe-KD7fE_A
YouTube video
Help Support the Cartoons: http://www.patreon.com/carbotanimations Shirts: https://www.teepublic.com/user/carbotanimations http://www.carbotanimations.com Fo...
Preview: https://i.ytimg.com/vi/Bhe-KD7fE_A/hqdefault.jpg

---

The original message contains 96 characters including 1 link.

Two messages show up in the local chat window after sending a message. Message #1 (original) contains 96 characters and 1 link. Message #2 (embed) contains 400 characters and 6 links for a total of ~500 characters and 7 links.)

The history++ log contains 400 characters and 6 links when it should only contain 96 characters and 1 link.

**Comment by georgehazan** [comment]
@RathaWynter  in fact message #2 contain even more links, I display only a few of them to allow IEView to display video preview as a picture, for example

**Comment by RathaWynter** [comment]
I feel like we could use an option in the Discord settings for "Do not log or display embed data" that way people who want to use it with IEView can, and people who dont want inline preview wont get buried in unnecessary data and have their logs / windows / histories cluttered up with all that extra stuff which was not a part of the original message. (Hopefully this would function similarly to how the Steam protocol currently handles messages and does not include or log embedded data in the chat window or history.)

**Comment by RathaWynter** [comment]
Is there any chance we could have this issue re-opened? The ticket was for: "Discord - Option to not display or log embedded link data." and it was closed as "fixed, using server message id handling" but that seems like something completely different and did not actually address the issue of having an option to disable all display and logging of embedded data.

Discord display and history logging options:
Option 1 - Message text + Embedded link data (For use with IEView) - (How it currently works)

Option 2 - Original message text only. (For use with TabSRMM) - (Option reduces log and window clutter)

**Comment by RathaWynter** [comment]
Is it necessary to create a new ticket since this one has been closed even though the bug / request was not fulfilled?

Discord is the only protocol that I've used (out of ICQ, Skype, Steam, and Yahoo) which exhibits the display and logging of extra embedded data which was not part of the original message. This creates problems for those of us who do not use IEView as sent/received messages containing links will completely flood a chat window with text and multiple links.

Not only does it flood the chat window making you have to scroll the chat backward just to see what the original message was before all of the embedded stuff cluttered up the chat window, it also logs all of the embed data into the history which makes the history harder to read through and harder to search because large quantities of text and multiple links that were not part of the original message are now being added to the logs. This also artificially inflates the size of messages and the database with embeded content often being 3-5 times larger than the original message itself.

Thats why I believe that this ticket should remain open, its not just a display problem that creates a huge inconvenience for non-IEView users, it also creates a history problem too by cluttering logs significantly. The option to disable this undesirable behavior (especially because IEView is not a standard/default plugin as far as Im aware) seems pretty important for the protocol.
