### ISSUE TITLE
MRA: Перестал открываться сайт mail.ru по клику на уведомление о новой почте

### ISSUE THREAD

**Issue by ashum81** [miranda-ng/miranda-ng#1380]
21 мая 2018 перестал открываться сайт mail.ru по клику на уведомление о новой почте (значок с конвертом в трее).
Открывается адрес https://win.mail.ru/cgi-bin/start с title "start (1x1)".

[spoiler=VersionInfo][quote]CPU: Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz [Intel64 Family 6 Model 42 Stepping 7] [DEP Enabled] [4 CPUs]
Installed RAM: 8104 MBytes
Microsoft Windows 7 Enterprise Edition, 64-bit Service Pack 1 (build 7601)
Internet Explorer: 9.11.9600.19002 (build 99600)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian
Free disk space on Miranda partition: 12847 MBytes

Miranda NG Version: 0.95.8 build #19953 (09e90f29d4) x64
Build time: 22 May 2018 22:46:32
Profile: C:\Users\as\AppData\Roaming\Miranda NG\1\1.dat (MDBX database driver)
Profile size: 33554432 Bytes
Profile creation date: 3 Aug 2016 15:52:13
Language pack: Russian (RU) [0419]
Service Mode: No

[b]Active Plugins (18):[/b]
¤ AVS.dll v.[b]0.98.1.1[/b] [19 May 2018 14:14:48] - Avatar service 
¤ Clist_nicer.dll v.[b]0.9.3.1[/b] [19 May 2018 14:14:50] - Clist nicer 
¤ CrashDumper.dll v.[b]0.1.0.2[/b] [19 May 2018 14:15:16] - Crash dumper 
¤ Dbx_mdbx.dll v.[b]0.95.8.7[/b] [22 May 2018 22:47:56] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.[b]0.95.8.1[/b] [22 May 2018 22:46:40] - Miranda NG mmap database driver 
¤ Dummy.dll v.[b]0.2.0.0[/b] [22 May 2018 22:47:36] - Dummy protocol 
¤ Fingerprint.dll v.[b]0.1.0.0[/b] [19 May 2018 14:15:30] - Fingerprint NG 
¤ historypp.dll v.[b]1.5.1.5[/b] [22 May 2018 22:48:24] - History++ 
¤ ICQ.dll v.[b]0.95.8.1[/b] [19 May 2018 14:14:52] - IcqOscarJ protocol 
¤ Import.dll v.[b]0.95.8.6[/b] [22 May 2018 22:46:54] - Import contacts and messages 
¤ Jabber.dll v.[b]0.11.0.5[/b] [19 May 2018 14:15:20] - Jabber protocol 
¤ MRA.dll v.[b]2.1.1.1[/b] [19 May 2018 14:15:04] - Mail.ru Agent 
¤ PluginUpdater.dll v.[b]0.1.2.5[/b] [19 May 2018 14:15:26] - Plugin updater 
¤ SeenPlugin.dll v.[b]5.0.5.3[/b] [19 May 2018 14:15:00] - Last seen 
¤ SmileyAdd.dll v.[b]0.3.0.2[/b] [19 May 2018 14:15:36] - SmileyAdd 
¤ TabSRMM.dll v.[b]3.5.0.9[/b] [19 May 2018 14:14:54] - TabSRMM 
¤ Tipper.dll v.[b]2.1.0.7[/b] [19 May 2018 14:15:00] - Tipper 
¤ TopToolBar.dll v.[b]0.8.0.5[/b] [19 May 2018 14:15:08] - TopToolBar 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
ICQ                      1 - Enabled 0 - Disabled  Loaded
JABBER                   2 - Enabled 1 - Disabled  Loaded
MRA                      1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 Fp_icons.dll [19 May 2018 14:16:32]
 HistoryPP_icons.dll [22 May 2018 22:48:16]
 Proto_Dummy.dll [22 May 2018 22:48:16]
 Proto_ICQ.dll [19 May 2018 14:16:32]
 Proto_Jabber.dll [19 May 2018 14:16:32]
 Proto_MetaContacts.dll [22 May 2018 22:48:16]
 Proto_MRA.dll [19 May 2018 14:16:32]
 TabSRMM_icons.dll [19 May 2018 14:16:32]
 tabsrmm_icons_from_miranda_im.dll [11 Jul 2016 19:47:24]
 Toolbar_icons.dll [19 May 2018 14:16:32]
 toolbar_icons_from_miranda_im.dll [9 Sep 2014 22:24:06]
 xStatus_ICQ.dll [19 May 2018 14:16:32]
 xStatus_Jabber.dll [19 May 2018 14:16:32]
 xStatus_MRA.dll [19 May 2018 14:16:32]
[/quote][/spoiler]

**Comment by georgehazan** [comment]
у меня открывает норм. 
а если зайти в браузер на сайт и влогиниться - он ничего не скажет?
может ему надо что, или двухфакторная авторизация

**Comment by ashum81** [comment]
После очистки кэша браузера все заработало как раньше. Спасибо.
