### ISSUE TITLE
Клиент постоянно отваливается от Jabber сервера

### ISSUE THREAD

**Issue by SergeyKuznetsov1** [miranda-ng/miranda-ng#1381]
[netlog.txt](https://github.com/miranda-ng/miranda-ng/files/2038745/netlog.txt)

**Comment by georgehazan** [comment]
может включить keep alive? без него может легко отваливаться с таймаутом, а в логе кипалайва нет
PS: на будущее из лога лучше отключать аську, очень много мусора

**Comment by georgehazan** [comment]
>[10:45:07 3A90] SSL Server signaled SSL Shutdown
[10:45:07 3A90] [test] Connection closed gracefully
[10:45:07 3A90] [test] recvResult = 0

ну так видно, что сервер сам разорвал соединение, т.е. если не кипалайв, то клиент как бы не при чем
