### ISSUE TITLE
Закрыл Миранду -> открыл Миранду -> Миранда не может открыть профиль, он в неизвестном формате.

### ISSUE THREAD

**Issue by ArcherZett** [miranda-ng/miranda-ng#1384]
Тут даже и добавить-то нечего. Сегодня ее скачал, установил, настроил учетные записи. Раз 10 перезапускал, все было нормально. И тут вдруг сломался профиль. 
Единственное, что было изменено перед перезапуском - поставлены пометки (заблокировано) на учетные записи. Понятия не имею, что эти пометки делают. Вот опытным путем проверил - очевидно, они ломают профиль.
Повторять не буду, заново настраивать учетки долго, а тестером быть неохота.
![111](https://user-images.githubusercontent.com/39631936/40559950-23f83774-6061-11e8-936b-68d59fcc504f.JPG)

**Comment by dartraiden** [comment]
Учётная запись, которая заблокирована, не будет реагировать на изменения глобального статуса. На базу это вряд ли влияет.

**Comment by ArcherZett** [comment]
Миранда была установлена в Program Files по умолчанию, папка профиля - в %appdata%\roaming\miranda ng. После этого казуса установил не stable, а бету, бета хранит профиль в папке программы.
Сообщение вылезло один раз, процессы проверял, unlocker'ом папки тоже посмотрел, ничего профиль не использовало, для верности скопировал его, удалил и заменил. Профиль попросту испорчен, внутри. Hex-редактором заменил первые несколько разных смещений у профиля и свежесозданного, все равно не запустился. 
С ОЗУ и диском тоже все в порядке. Глючный профиль уже удален, старый драйвер удален из папки миранды, остался только новый, поставлен автобэкап на случай повторных казусов.

**Comment by ArcherZett** [comment]
> поставлен автобэкап на случай повторных казусов.
