### ISSUE TITLE
TabSRMM и StdMsg со Scriver по-разному мигают в панели задач при новом сообщении

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1385]
Исходные условия: контейнер открыт и свёрнут в панель задач. Приходит новое приватное сообщение.

TabSRMM: мигает в панели задач
StdMsg со Scriver: значок просто "горит", но не мигает.

**Comment by georgehazan** [comment]
вообще-то это три разных плагина.
соотв и поведение у них разное
