### ISSUE TITLE
Упал профиль

### ISSUE THREAD

**Issue by BLF0x** [miranda-ng/miranda-ng#1391]
Упал профиль после перезагрузки компа. Теперь при запуске выдает:

-------------
Тип события:	Уведомление
Источник события:	Application Popup
Категория события:	Отсутствует
Код события:	26
Дата:		26.05.2018
Время:		20:48:14
Пользователь:		Н/Д
Компьютер:	BLFOX
Описание:
Всплывающее окно приложения: Miranda32.exe - Ошибка приложения : Инструкция по адресу "0x1791b060" обратилась к памяти по адресу "0x000000ec". Требуемые данные в память не помещены из-за ошибки ввода/вывода "0x75b4b128".

ОК - завершение приложения
Отмена - отладка приложения

-------------

Вылечилось прибитием файла профиля. К сожалению битый файл не сохранил.
Отсюда вопрос: существует какое либо автономное средство для попытки отремонтировать подобный битый профиль, когда миранда "сама отремонтировать" его не в состоянии ? И возможно ли делать какой то бэкап профиля (после успешного запуска), если миранда, стала его использовать монопольно и в случае аварийного краха миранды возможны его повреждения ?

**Comment by georgehazan** [comment]
есть плагин, db_autobackup, рекомендую

**Comment by BLF0x** [comment]
Благодарю ! =) 
Еще вопрос: а что мешает не наращивать профиль за счет истории до гигантских размеров и тем самым увеличивать вероятность повреждения "всех яиц в одной корзине", а дробить ту же историю сообщений по месяцам и расталкивать эти месяцы в отдельные файлы ? в таком случае не придется монопольно держать все (достаточно будет только кусок) ? Или такая логика досталась по наследству и лучше пока работает -- ничего не трогать ?

**Comment by BLF0x** [comment]
Крашнулась после сегодняшнего обновления


Здравствуйте, George.

Miranda Crash Report from 7 Sep 2018 8:29:51. Crash Dumper v.0.1.0.2
Exception: Access Violation at address 125C5B33. Reading from address 01490D3D.

Stack Trace:
---------------------------------------------------------------
125C5B33 (libmdbx 125C0000): (filename not available) (0): mdbx_env_copy2fd
00080000 ((module-name not available) 00000000): (filename not available) (0): (function-name not available)

CPU: Intel(R) Core(TM)2 Duo CPU E7400 @ 2.80GHz [x86 Family 6 Model 23 Stepping 10] [2 CPUs]
Installed RAM: 5120 MBytes
Microsoft Windows XP Professional Service Pack 3 (build 2600)
Internet Explorer: 8.0.6001.18702 (build 86001)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian

Miranda NG Version: 0.95.9 build #20730 (ddf79e069e)
Build time: 6 Sep 2018 11:36:16
Profile: c:\icq\profiles\7573181\7573181.dat
Language pack: Russian (RU) [0419]
Service Mode: No

Active Plugins (31):
¤ AVS.dll v.0.95.9.0 [6 Sep 2018 11:36:20] - Avatar service 
¤ Clist_modern.dll v.0.95.9.0 [6 Sep 2018 11:36:48] - Modern contact list 
¤ CrashDumper.dll v.0.95.9.0 [6 Sep 2018 11:36:48] - Crash dumper 
¤ Db_autobackups.dll v.0.95.9.0 [6 Sep 2018 11:36:30] - Db autobackuper 
¤ DbEditorPP.dll v.0.95.9.0 [6 Sep 2018 11:36:48] - Database editor++ 
¤ Dbx_mdbx.dll v.0.95.9.0 [6 Sep 2018 11:37:38] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.0.95.9.0 [6 Sep 2018 11:36:22] - Miranda NG mmap database driver 
¤ Dummy.dll v.0.95.9.0 [6 Sep 2018 11:37:18] - Dummy protocol 
¤ Facebook.dll v.0.95.9.0 [6 Sep 2018 11:36:46] - Facebook 
¤ GG.dll v.0.95.9.0 [6 Sep 2018 11:36:44] - Gadu-Gadu protocol 
¤ historypp.dll v.1.5.1.5 [6 Sep 2018 11:37:56] - History++ 
¤ ICQ.dll v.0.95.9.0 [6 Sep 2018 11:36:28] - IcqOscarJ protocol 
¤ IEView.dll v.0.95.9.0 [6 Sep 2018 11:36:30] - IEView 
¤ Import.dll v.0.95.9.0 [6 Sep 2018 11:36:42] - Import contacts and messages 
¤ IRC.dll v.0.95.9.0 [6 Sep 2018 11:36:24] - IRC protocol 
¤ Jabber.dll v.0.95.9.0 [6 Sep 2018 11:37:00] - Jabber protocol 
¤ MenuEx.dll v.0.95.9.0 [6 Sep 2018 11:36:28] - Menu item ext 
¤ MessageState.dll v.0.95.9.0 [6 Sep 2018 11:37:22] - Message state 
¤ MobileState.dll v.0.95.9.0 [6 Sep 2018 11:36:54] - Mobile state 
¤ MRA.dll v.0.95.9.0 [6 Sep 2018 11:36:38] - Mail.ru Agent 
¤ MSN.dll v.0.95.9.0 [6 Sep 2018 11:36:46] - MSN protocol 
¤ PluginUpdater.dll v.0.95.9.0 [6 Sep 2018 11:36:52] - Plugin updater 
¤ SeenPlugin.dll v.0.95.9.0 [6 Sep 2018 11:36:32] - Last seen 
¤ SkypeWeb.dll v.0.95.9.0 [6 Sep 2018 11:37:30] - Skype protocol (Web) 
¤ SmileyAdd.dll v.0.95.9.0 [6 Sep 2018 11:36:54] - SmileyAdd 
¤ StatusManager.dll v.0.95.9.0 [6 Sep 2018 11:37:26] - Status manager 
¤ TabSRMM.dll v.0.95.9.0 [6 Sep 2018 11:36:28] - TabSRMM 
¤ TopToolBar.dll v.0.95.9.0 [6 Sep 2018 11:36:42] - TopToolBar 
¤ TranslitSwitcher.dll v.0.95.9.0 [6 Sep 2018 11:36:34] - Switch layout or transliterate 
¤ UInfoEx.dll v.0.95.9.0 [6 Sep 2018 11:36:40] - User info ext 
¤ VKontakte.dll v.0.95.9.0 [6 Sep 2018 11:37:16] - VKontakte protocol 

Loaded Modules:
-------------------------------------------------------------------------------
C:\icq\Miranda32.exe  00400000 - 0040B000 v.0.95.9.0 [6 Sep 2018 11:36:16]
C:\WINXP\system32\ntdll.dll  7C900000 - 7C9B5000 v.5.1.2600.7013 [30 Jan 2016 6:22:18]
C:\WINXP\system32\kernel32.dll  7C800000 - 7C8F9000 v.5.1.2600.7013 [30 Jan 2016 6:22:18]
C:\WINXP\system32\USER32.dll  7E360000 - 7E3F1000 v.5.1.2600.5512 [26 Dec 2009 9:03:40]
C:\WINXP\system32\GDI32.dll  77F10000 - 77F5A000 v.5.1.2600.6973 [9 Dec 2015 2:13:42]
C:\WINXP\system32\SHELL32.dll  7C9C0000 - 7D1DC000 v.6.0.2900.6880 [29 Jul 2015 19:17:50]
C:\WINXP\system32\ADVAPI32.dll  77DC0000 - 77E6C000 v.5.1.2600.6987 [17 Dec 2015 21:59:08]
C:\WINXP\system32\RPCRT4.dll  77E70000 - 77F03000 v.5.1.2600.6477 [7 Nov 2013 8:38:06]
C:\WINXP\system32\Secur32.dll  77FE0000 - 77FF1000 v.5.1.2600.5834 [26 Dec 2009 8:51:58]
C:\WINXP\system32\msvcrt.dll  77C00000 - 77C58000 v.7.0.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\SHLWAPI.dll  77F60000 - 77FD7000 v.6.0.2900.6540 [26 Mar 2014 6:17:50]
C:\WINXP\system32\IMM32.DLL  76360000 - 7637D000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\Program Files\Prio\prio.dll  10000000 - 10005000 v.1.9.8.1536 [31 Mar 2008 13:28:32]
C:\WINXP\WinSxS\x86_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.2600.6028_x-ww_61e65202\comctl32.dll  773C0000 - 774C3000 v.6.0.2900.6028 [23 Aug 2010 19:12:36]
C:\icq\libs\ucrtbase.dll  008F0000 - 009D1000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-string-l1-1-0.dll  003A0000 - 003A3000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-errorhandling-l1-1-0.dll  003C0000 - 003C3000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-timezone-l1-1-0.dll  003D0000 - 003D3000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-file-l1-1-0.dll  003E0000 - 003E4000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-namedpipe-l1-1-0.dll  003F0000 - 003F3000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-handle-l1-1-0.dll  009E0000 - 009E3000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-file-l2-1-0.dll  009F0000 - 009F3000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-heap-l1-1-0.dll  00A00000 - 00A03000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-libraryloader-l1-1-0.dll  00A10000 - 00A13000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-synch-l1-1-0.dll  00A20000 - 00A23000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-processthreads-l1-1-0.dll  00A30000 - 00A33000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-processenvironment-l1-1-0.dll  00A40000 - 00A43000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-datetime-l1-1-0.dll  00A50000 - 00A53000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-localization-l1-2-0.dll  00A60000 - 00A63000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-sysinfo-l1-1-0.dll  00A70000 - 00A73000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-synch-l1-2-0.dll  00A80000 - 00A83000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-console-l1-1-0.dll  00A90000 - 00A93000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-debug-l1-1-0.dll  00AA0000 - 00AA3000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-processthreads-l1-1-1.dll  00AB0000 - 00AB3000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-file-l1-2-0.dll  00AC0000 - 00AC3000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-profile-l1-1-0.dll  00AD0000 - 00AD3000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-memory-l1-1-0.dll  00AE0000 - 00AE3000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-util-l1-1-0.dll  00AF0000 - 00AF3000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-rtlsupport-l1-1-0.dll  00B00000 - 00B03000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-core-interlocked-l1-1-0.dll  00B10000 - 00B13000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-crt-runtime-l1-1-0.dll  00B20000 - 00B24000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-crt-stdio-l1-1-0.dll  00B30000 - 00B34000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-crt-locale-l1-1-0.dll  00B40000 - 00B43000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-crt-heap-l1-1-0.dll  00B50000 - 00B53000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\VCRUNTIME140.dll  00B60000 - 00B74000 v.14.11.25325.0 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-crt-string-l1-1-0.dll  00B80000 - 00B84000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-crt-convert-l1-1-0.dll  00B90000 - 00B94000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\mir_app.mir  126C0000 - 1278C000 v.0.95.9.20730 [6 Sep 2018 11:36:16]
C:\WINXP\system32\WINMM.dll  76B20000 - 76B4E000 v.5.1.2600.6160 [14 Oct 2011 17:47:28]
C:\WINXP\system32\WS2_32.dll  71A90000 - 71AA7000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\WS2HELP.dll  71A80000 - 71A88000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\UxTheme.dll  5B260000 - 5B298000 v.6.0.2900.5512 [26 Dec 2009 8:58:42]
C:\WINXP\system32\COMDLG32.dll  76380000 - 763C9000 v.6.0.2900.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\ole32.dll  774D0000 - 7760E000 v.5.1.2600.7013 [30 Jan 2016 6:22:18]
C:\icq\libs\FreeImage.mir  12000000 - 12092000 [6 Sep 2018 11:36:10]
C:\icq\libs\zlib.mir  12AA0000 - 12AB9000 v.1.2.11.0 [6 Sep 2018 11:35:56]
C:\icq\libs\api-ms-win-crt-utility-l1-1-0.dll  00BA0000 - 00BA3000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-crt-time-l1-1-0.dll  00BB0000 - 00BB3000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\MSVCP140.dll  00BC0000 - 00C2D000 v.14.11.25325.0 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-crt-math-l1-1-0.dll  00C30000 - 00C35000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-crt-multibyte-l1-1-0.dll  00C40000 - 00C45000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-crt-filesystem-l1-1-0.dll  00C50000 - 00C53000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\api-ms-win-crt-environment-l1-1-0.dll  00C60000 - 00C63000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\mir_core.mir  12860000 - 12883000 v.0.95.9.20730 [6 Sep 2018 11:35:56]
C:\WINXP\system32\WTSAPI32.dll  76F40000 - 76F48000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\WINSTA.dll  76330000 - 76340000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\NETAPI32.dll  5BD50000 - 5BDA6000 v.5.1.2600.6260 [6 Jul 2012 16:58:22]
C:\WINXP\system32\VERSION.dll  77BF0000 - 77BF8000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\serwvdrv.dll  5D270000 - 5D277000 v.5.1.2600.0 [15 Apr 2008 13:00:00]
C:\WINXP\system32\umdmxfrm.dll  5B590000 - 5B597000 v.5.1.2600.0 [15 Apr 2008 13:00:00]
C:\WINXP\system32\MSCTF.dll  746E0000 - 7472C000 v.5.1.2600.6727 [22 Jan 2015 4:45:48]
C:\WINXP\system32\msctfime.ime  75310000 - 7533E000 v.5.1.2600.5768 [26 Dec 2009 8:51:22]
C:\Program Files\Ruslat95\kbHook.dll  02CA0000 - 02CB3000 [8 Feb 2011 13:44:32]
C:\icq\Plugins\DbEditorPP.dll  17930000 - 1794D000 v.4.0.1.2 [6 Sep 2018 11:36:48]
C:\icq\Plugins\CrashDumper.dll  17750000 - 17761000 v.0.1.0.2 [6 Sep 2018 11:36:48]
C:\WINXP\system32\dbghelp.dll  59C60000 - 59D01000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\icq\Plugins\Dbx_mdbx.dll  17970000 - 17982000 v.0.95.9.1 [6 Sep 2018 11:37:38]
C:\icq\libs\libmdbx.mir  125C0000 - 125E4000 [6 Sep 2018 11:37:32]
C:\icq\Plugins\Dbx_mmap.dll  179B0000 - 179C0000 v.0.95.8.1 [6 Sep 2018 11:36:22]
C:\icq\Plugins\Import.dll  18530000 - 18542000 v.0.95.9.1 [6 Sep 2018 11:36:42]
C:\icq\libs\sqlite3.mir  12920000 - 12989000 [6 Sep 2018 11:36:30]
C:\icq\libs\libjson.mir  125A0000 - 125AC000 [6 Sep 2018 11:36:20]
C:\icq\Core\stdcrypt.dll  13060000 - 1306C000 v.0.95.9.20730 [6 Sep 2018 11:36:00]
C:\icq\Core\stdssl.dll  13120000 - 13128000 v.0.95.9.20730 [6 Sep 2018 11:35:58]
C:\WINXP\system32\CRYPT32.dll  77A70000 - 77B08000 v.5.131.2600.6459 [7 Oct 2013 14:00:00]
C:\WINXP\system32\MSASN1.dll  77B10000 - 77B22000 v.5.1.2600.5875 [26 Dec 2009 8:51:20]
C:\WINXP\system32\WSOCK32.dll  71AB0000 - 71ABA000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\Msftedit.dll  4B460000 - 4B4E6000 v.5.41.15.1515 [15 Apr 2008 13:00:00]
C:\icq\Plugins\Clist_modern.dll  17430000 - 174A2000 v.0.9.1.7 [6 Sep 2018 11:36:48]
C:\WINXP\WinSxS\x86_Microsoft.Windows.Gdiplus_6595b64144ccf1df_1.0.6002.23846_x-ww_f7dfd05e\gdiplus.dll  4EBE0000 - 4ED8B000 v.5.2.6002.23846 [12 Nov 2015 1:51:02]
C:\WINXP\system32\MSIMG32.dll  76350000 - 76355000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\icq\Plugins\AVS.dll  17250000 - 17261000 v.0.98.1.1 [6 Sep 2018 11:36:20]
C:\icq\Plugins\Db_autobackups.dll  179D0000 - 179DF000 v.0.1.0.1 [6 Sep 2018 11:36:30]
C:\icq\Plugins\Dummy.dll  17A30000 - 17A38000 v.0.2.0.0 [6 Sep 2018 11:37:18]
C:\icq\Plugins\Facebook.dll  17A90000 - 17AD9000 v.0.4.1.3 [6 Sep 2018 11:36:46]
C:\icq\Plugins\GG.dll  17DD0000 - 17E15000 v.0.11.0.4 [6 Sep 2018 11:36:44]
C:\icq\Plugins\historypp.dll  17E90000 - 1807E000 [6 Sep 2018 11:37:56]
C:\WINXP\system32\oleaut32.dll  77110000 - 7719B000 v.5.1.2600.6688 [26 Nov 2014 18:16:52]
C:\WINXP\system32\winspool.drv  72FC0000 - 72FE6000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\RICHED20.DLL  74DF0000 - 74E5D000 v.5.30.23.1230 [15 Apr 2008 13:00:00]
C:\icq\Plugins\ICQ.dll  183B0000 - 18403000 v.0.95.8.1 [6 Sep 2018 11:36:28]
C:\icq\Plugins\IEView.dll  184D0000 - 184ED000 v.1.5.0.1 [6 Sep 2018 11:36:30]
C:\icq\Plugins\IRC.dll  03580000 - 035CE000 v.0.95.8.1 [6 Sep 2018 11:36:24]
C:\icq\Plugins\Jabber.dll  035F0000 - 03691000 v.0.11.0.5 [6 Sep 2018 11:37:00]
C:\icq\libs\LIBEAY32.mir  12300000 - 12442000 v.1.0.2.16 [30 Mar 2018 13:51:28]
C:\icq\libs\api-ms-win-crt-conio-l1-1-0.dll  03090000 - 03093000 v.10.0.10586.15 [25 May 2017 13:39:24]
C:\icq\libs\libaxolotl.mir  12200000 - 1222F000 [6 Sep 2018 11:36:34]
C:\WINXP\system32\DNSAPI.dll  76F10000 - 76F37000 v.5.1.2600.6089 [3 Mar 2011 9:53:36]
C:\icq\Plugins\MenuEx.dll  036B0000 - 036BE000 v.1.3.0.10 [6 Sep 2018 11:36:28]
C:\icq\Plugins\MessageState.dll  036C0000 - 036C8000 v.0.0.1.0 [6 Sep 2018 11:37:22]
C:\icq\Plugins\MobileState.dll  036D0000 - 036D6000 v.0.0.1.6 [6 Sep 2018 11:36:54]
C:\icq\Plugins\MRA.dll  036E0000 - 03749000 v.2.1.1.1 [6 Sep 2018 11:36:38]
C:\icq\Icons\xStatus_MRA.dll  13CE0000 - 13CF3000 [6 Sep 2018 11:37:52]
C:\icq\Plugins\MSN.dll  03750000 - 0378D000 v.0.95.9.1 [6 Sep 2018 11:36:46]
C:\icq\Plugins\PluginUpdater.dll  03790000 - 037A5000 v.0.2.0.2 [6 Sep 2018 11:36:52]
C:\icq\Plugins\SeenPlugin.dll  037B0000 - 037BF000 v.5.0.5.3 [6 Sep 2018 11:36:32]
C:\icq\Plugins\SkypeWeb.dll  037C0000 - 03805000 v.0.12.2.5 [6 Sep 2018 11:37:30]
C:\icq\Plugins\SmileyAdd.dll  03810000 - 03828000 v.0.3.1.0 [6 Sep 2018 11:36:54]
C:\icq\libs\Pcre16.mir  128C0000 - 128D8000 [6 Sep 2018 11:36:40]
C:\icq\Plugins\StatusManager.dll  03830000 - 0384B000 v.1.2.0.4 [6 Sep 2018 11:37:26]
C:\WINXP\system32\WININET.dll  3F9E0000 - 3FAC7000 v.8.0.6001.23797 [21 Jan 2016 22:31:38]
C:\WINXP\system32\Normaliz.dll  03850000 - 03859000 v.6.0.5441.0 [7 Jan 2009 18:20:36]
C:\WINXP\system32\urlmon.dll  45020000 - 45155000 v.8.0.6001.23797 [21 Jan 2016 22:31:38]
C:\WINXP\system32\iertutil.dll  40080000 - 4026D000 v.8.0.6001.23797 [21 Jan 2016 22:31:36]
C:\WINXP\system32\IPHLPAPI.DLL  76D50000 - 76D69000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\icq\Plugins\TabSRMM.dll  03AB0000 - 03B30000 v.3.5.0.12 [6 Sep 2018 11:36:28]
C:\icq\Plugins\TopToolBar.dll  03B30000 - 03B3E000 v.0.8.0.5 [6 Sep 2018 11:36:42]
C:\icq\Plugins\TranslitSwitcher.dll  03B40000 - 03B4A000 v.0.1.0.1 [6 Sep 2018 11:36:34]
C:\icq\Plugins\UInfoEx.dll  03B50000 - 03BA1000 v.0.8.5.1 [6 Sep 2018 11:36:40]
C:\icq\Plugins\VKontakte.dll  03BB0000 - 03BEB000 v.0.1.5.2 [6 Sep 2018 11:37:16]
C:\icq\Core\stdfile.dll  130A0000 - 130B0000 v.0.95.9.20730 [6 Sep 2018 11:36:00]
C:\icq\Core\stduseronline.dll  13180000 - 13187000 v.0.95.9.20730 [6 Sep 2018 11:36:00]
C:\icq\Core\stdaway.dll  13020000 - 13029000 v.0.95.9.20730 [6 Sep 2018 11:35:58]
C:\WINXP\system32\CLBCATQ.DLL  76FC0000 - 7703F000 v.2001.12.4414.700 [15 Apr 2008 16:00:00]
C:\WINXP\system32\COMRes.dll  03F80000 - 04055000 v.2001.12.4414.700 [26 Dec 2009 9:01:40]
C:\WINXP\system32\oleacc.dll  61880000 - 618BA000 v.7.0.2600.6153 [26 Sep 2011 11:41:20]
C:\WINXP\System32\mswsock.dll  71A30000 - 71A70000 v.5.1.2600.5625 [26 Dec 2009 8:51:38]
C:\WINXP\system32\rasadhlp.dll  76FB0000 - 76FB6000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\hnetcfg.dll  698B0000 - 69908000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\System32\wshtcpip.dll  71A70000 - 71A78000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\schannel.dll  767D0000 - 767F9000 v.5.1.2600.6926 [24 Sep 2015 2:52:40]
C:\WINXP\system32\USERENV.dll  769A0000 - 76A55000 v.5.1.2600.6689 [6 Dec 2014 10:29:08]
C:\WINXP\system32\credssp.dll  59E00000 - 59E07000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\rsaenh.dll  68000000 - 68039000 v.5.1.2600.6924 [22 Sep 2015 0:55:04]
C:\WINXP\system32\dssenh.dll  68100000 - 68129000 v.5.1.2600.6924 [22 Sep 2015 0:55:04]
C:\WINXP\System32\winrnr.dll  76FA0000 - 76FA8000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\WLDAP32.dll  76F50000 - 76F7D000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\wshbth.dll  75000000 - 7501E000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\SETUPAPI.dll  77910000 - 77A04000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\USP10.dll  75540000 - 755AB000 v.1.420.2600.6557 [25 Apr 2014 12:54:46]
C:\WINXP\system32\msls31.dll  04F40000 - 04F69000 v.3.10.349.0 [8 Mar 2009 4:22:38]
C:\WINXP\system32\appHelp.dll  77B30000 - 77B52000 v.5.1.2600.5512 [15 Apr 2008 13:00:00]
C:\WINXP\system32\ieframe.dll  40270000 - 40D07000 v.8.0.6001.23797 [21 Jan 2016 22:31:36]


-- 
С уважением,
 Чан                          mailto:blfox@rambler.ru

**Comment by dartraiden** [comment]
Лог без отладочных символов, к сожалению, бесполезен.

Если и дальше падает, создайте чистый профиль и импортируйте туда всё добро со старого.
