### ISSUE TITLE
Починить Conversations в  Fingerprint

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1393]
> apollo2k4: Починить бы Conversation в  Fingerprint и добавить бы определение некоторых клиентов ВК, а то у нас только Kate.

**Comment by georgehazan** [comment]
@apollo2k4 
некоторых - например, каких?

**Comment by apollo2k4** [comment]
@georgehazan в первую очередь VK Messenger, по возможности можно Phoenix и Phoenix Lite.

Иконку Conversations так и не починили, Fingerprint до сих пор показывает иконку Conversations IRC MacOS клиента, сайт которого уже не открываться т.ч. может его совсем друпнуть…

**Comment by georgehazan** [comment]
Иконку Conversations как раз починили,

**Comment by apollo2k4** [comment]
В 216e1d2bd7924b8ae2c4ba3c9ee5c0b8cff57303 добавили [Phoenix](https://play.google.com/store/apps/details?id=biz.dealnote.phoenix) и [Phoenix Lite](https://play.google.com/store/apps/details?id=biz.dealnote.messenger) можно и их тоже добавить.

**Comment by dartraiden** [comment]
Done
271367ab3879f748ab3b5791042f2faeb238a7dd
