### ISSUE TITLE
Плагины сообщений: не все звуки работают

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1396]
Пример 1: стоит звук на highlighted message в групчате

StdMsg - звук при хайлайте есть
TabSRMM - звука нет

Пример 2: стоит звук на Outgoing в Instant messages (приватах)

StdMsg - звука нет
TabSRMM - звука нет

**Comment by georgehazan** [comment]
проверил у себя - всё ok

**Comment by georgehazan** [comment]
![image](https://user-images.githubusercontent.com/4628541/40837199-53366b32-65a2-11e8-879f-fc6834ddb0fe.png)
