### ISSUE TITLE
Remove libeay32 and ssleay from core package

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1399]
These libs only for OpenSSL, Jabber, and MSN plugins. And libcurl (only one plugin uses libcurl - FTPFile).

So we shouldn't pack them with [core package](https://github.com/miranda-ng/miranda-ng/blob/master/tools/build_scripts/z2_PackPluginUpdater.txt) (but should with installers and portable archive, because of Jabber and MSN).

**Comment by georgehazan** [comment]
it's used also in libcurl, libcrypt etc, so we better leave it in the core
