### ISSUE TITLE
Miranda 0.95.8.1 Scriver Log doesn't work anymore

### ISSUE THREAD

**Issue by Tragen** [miranda-ng/miranda-ng#1413]
I updated to the latest 0.95.8.1 and since this version, scriver isn't correctly working anymore.
When I write a message, it is shown in the upper log window.
When I write a second message, nothing is show. Also no answers are shown in the log.
When I check the history, all messages are there but not shown in scriver.
Only the first message is shown. Received or sent and then nothing more.

[spoiler=VersionInfo][quote]CPU: Intel(R) Core(TM) i7-2820QM CPU @ 2.30GHz [Intel64 Family 6 Model 42 Stepping 7] [DEP Enabled] [8 CPUs]
Installed RAM: 16264 MBytes
Microsoft Windows 10 , 64-bit (build 17134)
Internet Explorer: 9.11.17134.0 (build 917134)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | German/English
Free disk space on Miranda partition: 98752 MBytes

Miranda NG Version: 0.95.8.1 build #19974 (b9ae2ad226) x64
Build time: 8 Jun 2018 21:25:38
Profile: C:\USB\Software\Important\Miranda NG v0.95.8.1 x64\Profiles\Master of Dice\Master of Dice.dat (MDBX database driver)
Profile size: 123731968 Bytes
Profile creation date: 5 May 2018 20:24:37
Language pack: No language pack installed
Service Mode: No

[b]Active Plugins (29):[/b]
¤ AvatarHistory.dll v.[b]0.1.0.2[/b] [8 May 2018 21:59:50] - Avatar history 
¤ AVS.dll v.[b]0.98.1.1[/b] [8 May 2018 21:59:06] - Avatar service 
¤ BuddyExpectator.dll v.[b]0.1.2.3[/b] [8 May 2018 21:59:04] - Buddy expectator 
¤ CrashDumper.dll v.[b]0.1.0.2[/b] [16 May 2018 13:01:14] - Crash dumper 
¤ Db_autobackups.dll v.[b]0.0.0.11[/b] [8 May 2018 21:59:14] - Db autobackuper 
¤ DbEditorPP.dll v.[b]4.0.1.2[/b] [8 May 2018 21:59:36] - Database editor++ 
¤ Dbx_mdbx.dll v.[b]0.95.8.7[/b] [8 Jun 2018 21:27:00] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.[b]0.95.8.1[/b] [8 Jun 2018 21:25:44] - Miranda NG mmap database driver 
¤ Discord.dll v.[b]0.5.1.2[/b] [8 May 2018 22:00:14] - Discord protocol 
¤ Dummy.dll v.[b]0.2.0.0[/b] [8 Jun 2018 21:26:42] - Dummy protocol 
¤ Folders.dll v.[b]0.2.0.2[/b] [8 May 2018 21:59:12] - Custom profile folders 
¤ historypp.dll v.[b]1.5.1.5[/b] [5 Jun 2018 15:27:36] - History++ 
¤ HistoryStats.dll v.[b]0.2.1.1[/b] [8 May 2018 22:00:22] - HistoryStats 
¤ ICQ.dll v.[b]0.95.8.1[/b] [8 May 2018 21:59:12] - IcqOscarJ protocol 
¤ Import.dll v.[b]0.95.8.6[/b] [8 Jun 2018 21:25:54] - Import contacts and messages 
¤ IRC.dll v.[b]0.95.8.1[/b] [16 May 2018 13:00:42] - IRC protocol 
¤ Jabber.dll v.[b]0.11.0.5[/b] [8 May 2018 21:59:34] - Jabber protocol 
¤ LinkList.dll v.[b]0.0.0.2[/b] [8 May 2018 21:59:14] - History linklist plus 
¤ MenuEx.dll v.[b]1.3.0.10[/b] [8 May 2018 21:59:12] - Menu item ext 
¤ MirOTR.dll v.[b]0.14.1.16[/b] [8 May 2018 22:00:32] - Miranda OTR 
¤ MSN.dll v.[b]0.14.0.2[/b] [5 Jun 2018 15:26:22] - MSN protocol 
¤ PluginUpdater.dll v.[b]0.1.2.5[/b] [8 May 2018 21:59:38] - Plugin updater 
¤ PManagerEx.dll v.[b]0.0.0.5[/b] [8 May 2018 21:59:38] - Miranda NG profile changer 
¤ Scriver.dll v.[b]3.0.1.9[/b] [8 Jun 2018 21:25:44] - Scriver 
¤ SeenPlugin.dll v.[b]5.0.5.3[/b] [8 May 2018 21:59:18] - Last seen 
¤ SmileyAdd.dll v.[b]0.3.1.0[/b] [8 Jun 2018 21:26:10] - SmileyAdd 
¤ StatusManager.dll v.[b]1.2.0.1[/b] [5 Jun 2018 15:27:06] - Status manager 
¤ Tipper.dll v.[b]2.1.0.7[/b] [8 May 2018 21:59:18] - Tipper 
¤ Variables.dll v.[b]0.2.3.11[/b] [8 May 2018 21:59:44] - Variables 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
ICQ                      1 - Enabled 0 - Disabled  Loaded
JABBER                   1 - Enabled 3 - Disabled  Loaded
MSN                      1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 HistoryPP_icons.dll [5 Jun 2018 15:27:32]
 Proto_AIM.dll [9 Nov 2017 0:52:48]
 Proto_Discord.dll [8 May 2018 22:00:40]
 Proto_Dummy.dll [8 Jun 2018 21:27:12]
 Proto_Facebook.dll [5 Jun 2018 15:27:30]
 Proto_GG.dll [8 May 2018 22:00:40]
 Proto_ICQ.dll [8 May 2018 22:00:40]
 Proto_IRC.dll [16 May 2018 13:02:20]
 Proto_Jabber.dll [8 May 2018 22:00:40]
 Proto_MetaContacts.dll [8 Jun 2018 21:27:12]
 Proto_MSN.dll [5 Jun 2018 15:27:32]
 Proto_Yahoo.dll [17 Jun 2016 19:10:23]
 TabSRMM_icons.dll [5 Jun 2018 15:27:32]
 Toolbar_icons.dll [8 May 2018 22:00:40]
 xStatus_ICQ.dll [8 May 2018 22:00:40]
 xStatus_Jabber.dll [8 May 2018 22:00:40]
[/quote][/spoiler]

**Comment by Tragen** [comment]
![image](https://user-images.githubusercontent.com/1700241/41196822-46d163de-6c4a-11e8-9648-384e81042664.png)

**Comment by Tragen** [comment]
I had both windows open like in the screenshot and after 10 hours I got a new message which showed up in the log. My answer is missing again but everything is in the history.

**Comment by dartraiden** [comment]
Can you post screenshots with all Scriver settings?

**Comment by calabar77** [comment]
Oh, so it is not a common problem. I thought all the user with Scriver experienced the issue after the last update. 

[Here](http://www.mediafire.com/file/4il3jia8lg2b865/scriver.zip/file) is a zip file including screenshots for scriver settings. If something is missing, please tell me where I should find it.

**Comment by Tragen** [comment]
![image](https://user-images.githubusercontent.com/1700241/41259826-560f5c8e-6dd5-11e8-8226-c66c9978304e.png)

![image](https://user-images.githubusercontent.com/1700241/41259842-607b29fa-6dd5-11e8-84ac-1b93c1166772.png)

![image](https://user-images.githubusercontent.com/1700241/41259850-699fbfbe-6dd5-11e8-9b81-b4f9f57cb07c.png)

![image](https://user-images.githubusercontent.com/1700241/41259868-77b85390-6dd5-11e8-8921-30f7609e0f56.png)


Perhaps IEView? I haven't installed it

**Comment by Tragen** [comment]
![image](https://user-images.githubusercontent.com/1700241/41259928-b1a11880-6dd5-11e8-8a8c-f2e0235c364d.png)

![image](https://user-images.githubusercontent.com/1700241/41259931-b76bd5ac-6dd5-11e8-82b8-b41c0741c813.png)

![image](https://user-images.githubusercontent.com/1700241/41259943-bd0a0308-6dd5-11e8-8688-13929a290618.png)

![image](https://user-images.githubusercontent.com/1700241/41259951-c2834dbc-6dd5-11e8-8175-e1b16133b09b.png)

Perhaps IEView? I haven't installed it.

**Comment by Tragen** [comment]
I have installed IEView and toggled the IEView setting but it didn't help. I have no idea what could be the reason.

**Comment by georgehazan** [comment]
update to the stable version will be available in an hour

**Comment by dartraiden** [comment]
Still cannot reproduce even with these settings...

**Comment by dartraiden** [comment]
Please test again

**Comment by georgehazan** [comment]
finally reproduced & fixed completely.
bug was present only in the stable version, as the result of broken automatic merge from master

**Comment by Tragen** [comment]
It's working now. Thank you very much.
