### ISSUE TITLE
Database corrupted after sata controller failure

### ISSUE THREAD

**Issue by theultramage** [miranda-ng/miranda-ng#1418]
After a hardware failure, my profile is broken. The UI has the default theme, all the accounts and contacts are missing. Database Editor++ shows that the Settings tree seems to be intact, but it's unable to expand the Contacts tree.

The libmdbx page says that it guarantees data integrity even in this situation. The client has been sitting idle for over a day, so there should only be minimal write activity. Not sure if the library also compensates for OS write caching. Anyways, despite all this, it still broke. No error is displayed during startup, though.

**Comment by georgehazan** [comment]
yes, it's possible, if recent change was not applied 50 ms before a crash
so this event is possible, but is quite rare

**Comment by leo-yuriev** [comment]
libmdbx can provide data integrity, i.e. rollback to the last committed transaction.

However, currently the mdbx-driver intentionally opens the database in a [fragile](https://github.com/leo-yuriev/libmdbx/blob/60d668566533532ecc173337699ae14cdcd33d1c/mdbx.h#L310-L311) mode without [guarantee of data durability](https://github.com/leo-yuriev/libmdbx/tree/60d668566533532ecc173337699ae14cdcd33d1c#durability-in-asynchronous-writing-mode), and don't use API to explicitly create steady checkpoints (i.e [`mdbx_sync_env()`](https://github.com/leo-yuriev/libmdbx/blob/60d668566533532ecc173337699ae14cdcd33d1c/mdbx.h#L750-L768), [`mdbx_env_set_syncbytes()`](https://github.com/leo-yuriev/libmdbx/blob/60d668566533532ecc173337699ae14cdcd33d1c/mdbx.h#L1584-L1602) or [`mdbx_env_set_syncperiod()`](https://github.com/leo-yuriev/libmdbx/blob/60d668566533532ecc173337699ae14cdcd33d1c/mdbx.h#L1604-L1628)).

**Comment by dartraiden** [comment]
`guarantee of data durability`
the problem is that according to our tests it's very slow on profiles with hundreds of contacts

**Comment by georgehazan** [comment]
mdbx_env_sync(m_env, true) is executed 50 ms after any successful write commit (or a bunch of commits)

**Comment by dartraiden** [comment]
Perhaps it would be worth implementing as an option, but definitely not include the default.
