### ISSUE TITLE
Jabber password change

### ISSUE THREAD

**Issue by Alexey5112** [miranda-ng/miranda-ng#1422]
### Expected behavior
When changed password on server side, on client side can't logon without any message

### Actual behavior
Ask new password.

### Does it work in stable version?
Don't work.

### Steps to reproduce that behavior
1. Add Jabber account with "keep password" option.
2. Close "Miranda".
3. Change user password on server.
4. Run "Miranda" - jabber account can't connect silently.

**Comment by georgehazan** [comment]
if you installed a Popup+/YAPP plugin, you would get an error inside a popup

**Comment by Alexey5112** [comment]
Bad idea - many users too hard change password in "Perfererences" dialog. Only popup dialog - "Enter new password:".
