### ISSUE TITLE
IRC Highlight name matching

### ISSUE THREAD

**Issue by listerr** [miranda-ng/miranda-ng#1423]
I have enabled IRC highlight notification whenever my nick gets mentioned on a channel, however, it isn't matching the whole word, and therefore I get many false alarms if a word contains my nick.

My nick is set to `RobL`

I get an alert for something like the following:-

`<some_nick> I don't think there is a problem.`

Fix suggestion: Highlight only if: 
 - the nick has a leading or trailing space, or:
 - the line matches the nick exactly. (i.e. just contains the nick and nothing else.)

**Comment by georgehazan** [comment]
which plugin do you use? StdMsg / Scriver / tabSRMM?

**Comment by listerr** [comment]
I'll have to check but it's basically whatever is the default when installed.Rob On 14 Jun 2018 4:16 p.m., George Hazan <notifications@github.com> wrote:which plugin do you use? StdMsg / Scriver / tabSRMM?

**Comment by georgehazan** [comment]
tabSRMM has different highlighting rules based on regular expressions, while StdMsg uses simple string routines, so in tabSRMM you can embrace your nick with spaces

**Comment by listerr** [comment]
Okay - I've just done a new install on a new machine.

It seems tabSRMM is the default, but the behaviour is the same.

How do I put in the spaces for my nick?

Thanks,

Rob


On 2018-06-15 10:28, George Hazan wrote:
> tabSRMM has different highlighting rules based on regular expressions,
> while StdMsg uses simple string routines, so in tabSRMM you can
> embrace your nick with spaces


-- 
Rob Lister
rob@lonap.net
+44 20 3137 8330

**Comment by georgehazan** [comment]
\s%m\s, for example
