### ISSUE TITLE
issue with connection continues

### ISSUE THREAD

**Issue by slanovani** [miranda-ng/miranda-ng#1424]
### Expected behavior
What did you expect?
I expected that after restoring the old code, the program was going to handle facebook connection better
### Actual behavior
What did you get instead?
nothing happened. the program continues taking long periods of time to connect, and still goes to sleep mode or disconnects by itself. 
### Does it work in stable version?
If you know in which dev build (or approximate date when) it was broken, it may be much easier to identify and fix the issue.
in the latest version everything continues the same
### Steps to reproduce that behavior
 * Provide step-by-step instructions so we can reproduce the issue (We can't fix what we can't reproduce).
 * Attach your VersionInfo.
 * Attach a crash report if you are experiencing crashes (It includes VersionInfo as well).
 * Attach a network log captured if you are experiencing connectivity issues.
 * If Miranda freezes, hangs up or consumes CPU, attach information obtained by Process Explorer tool.
its version 0.95.8. i just open the program. the program is supposed to connect immediately to facebook protocols as soon as i open it, but it doesn't happen. it remains offline for long periods of time. and when it connects, it goes offline again by itself after a couple of minutes. please fix that, because it's not a problem of my internet. i have 20 mb broadband. 
[netlog.txt](https://github.com/miranda-ng/miranda-ng/files/2104734/netlog.txt)

**Comment by georgehazan** [comment]
well, as for me it takes 9 seconds to make FB online (on 150 mbit optical fiber), in your case the time is precisely the same, so it doesn't matter how fast your connection is. I've been looking at FB code for a couple of months, but still I don't know how to make it faster

**Comment by georgehazan** [comment]
also, as a matter of fact, consider that nothing was changed in FB code for about six months (I rolled back the change with persistent connections, because it practically stops the plugin on slow connections)

**Comment by slanovani** [comment]
Aaaah. So perhaps the problem is in facebook itself. Then if it’s like that. Tht, nothing much can be done.

De: George Hazan <notifications@github.com>
Enviado el: viernes, 15 de junio de 2018 4:36 a. m.
Para: miranda-ng/miranda-ng <miranda-ng@noreply.github.com>
CC: Slann Tonić <reydelasmaquinas@outlook.com>; Author <author@noreply.github.com>
Asunto: Re: [miranda-ng/miranda-ng] issue with connection continues (#1424)


well, as for me it takes 9 seconds to make FB online (on 150 mbit optical fiber), in your case the time is precisely the same, so it doesn't matter how fast your connection is. I've been looking at FB code for a couple of months, but still I don't know how to make it faster

**Comment by georgehazan** [comment]
> Aaaah. So perhaps the problem is in facebook itself. Then if it’s like that. Tht, nothing much can be done.

who knows... perhaps if all queries could be parallelized, we could save 2-3 seconds, but right now it's not possible
