### ISSUE TITLE
Correct archive names

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1426]
Currens stable is 0.9.8.1, but links are https://www.miranda-ng.org/distr/stable/miranda-ng-v0.95.8.7z

It's better to:
- name current release according to full version number (our wiki autogenerates links according to last version number, this leads to broken links)

- implement the auto-copying old release to https://miranda-ng.org/distr/deprecated/
It looks like they are copied manually, which led to the loss of several releases

**Comment by georgehazan** [comment]
does our site / wiki support these names?
or we can type in any names?

**Comment by Goraf** [comment]
Wiki right now uses release number for link text and as a part of the url too (typed manually in one place used in many). But I can adjust that and/or split to separate url/link text without a problem. I just need to know what will be the convention.

On the project page (from what I saw) is everything made manually, separately for every language

**Comment by georgehazan** [comment]
@Goraf evidently it would be smth like 
https://www.miranda-ng.org/distr/stable/miranda-ng-v0.95.8.1.7z

**Comment by Goraf** [comment]
So both (website and wiki) are ready out of the box. When new archives come out me or @dartraiden will be able to adjust everything in an instant.
