### ISSUE TITLE
Miranda doesn't set status back when returning from idle

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1427]
After removing StdIdle, my Miranda don't set status back when returning from idle.
I'm using StdAutoAway, not AAA.

![default](https://user-images.githubusercontent.com/5046855/41466461-089abd12-70ab-11e8-8b45-2afd8054947e.png)

**Comment by Phaere** [comment]
Same issue for me. "Become idle if computer is locked" sets status to idle when miranda starts. This option not working when computer locked\unlocked.
