### ISSUE TITLE
Ability to silently upgrade database

### ISSUE THREAD

**Issue by Phaere** [miranda-ng/miranda-ng#1429]
**Is your feature request related to a problem? Please describe.**
Cannot disable notification window about database upgrade. This is very major feature in corporate environments, because end users don't have such IT skills to understand what happens on screen.

**Describe the solution you'd like**
Some key in mirandaboot.ini or command line switch to disable upgrade notifications for end users

**Comment by georgehazan** [comment]
add the following setting into mirandaboot.ini:

[Database]
SilentUpgrade=1
