### ISSUE TITLE
MRA: show only one email notification

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1432]
> хотелось бы чтобы показывалось только одно оповещение о новой почте, а не на каждое письмо. Потому что постоянно происходит такая ситуация - пришло много новых писем в почту, о каждом письме пришло уведомление, на каждое уведомление открывается новое окно с mail.ru, и пока все уведомления не прокликаешь нельзя открыть контакт-лист.

https://forum.miranda-ng.org/index.php?topic=5361.msg21720#msg21720

**Comment by georgehazan** [comment]
- выключаем попапы о почте
- включаем показ количества почтовых сообщений в клисте
- профит

**Comment by georgehazan** [comment]
![image](https://user-images.githubusercontent.com/4628541/46734328-8b11d900-cc9b-11e8-8568-4b6e29d43149.png)

**Comment by ashum81** [comment]
У меня раздела Popups вообще нет.
![mir2](https://user-images.githubusercontent.com/2362198/46780193-ca403880-cd34-11e8-983b-dbee6af13a6a.PNG)
![mir1](https://user-images.githubusercontent.com/2362198/46780194-ca403880-cd34-11e8-85fb-76861046cbe0.PNG)

**Comment by georgehazan** [comment]
яннп, а где тогда показывается уведомление о почте?
