### ISSUE TITLE
HistoryStats plugin doesn't show any statistics

### ISSUE THREAD

**Issue by anetamm** [miranda-ng/miranda-ng#1433]
### Expected behavior
HistoryStats plugin should show stats

### Actual behavior
HistoryStats plugin doesn't show any stats.
Plugin generate "empty" HTML file - with no statistics, but header and footer is generated correctly.

### Version

> Miranda NG Version: 0.95.8.1 build #19977 (0d7a2e72d2) x64
> Build time: 14 Jun 2018 0:09:40
> Profile: C:\Users\jahba\AppData\Roaming\Miranda NG\Ja\Ja.dat (MDBX database driver)
> Profile size: 1048576 Bytes
> Profile creation date: 20 Jun 2018 17:47:58
> Language pack: No language pack installed
> Service Mode: No
> 
> [b]Active Plugins (20):[/b]
> ¤ AVS.dll v.[b]0.98.1.1[/b] [14 Jun 2018 0:09:44] - Avatar service 
> ¤ Clist_modern.dll v.[b]0.9.1.7[/b] [14 Jun 2018 0:10:18] - Modern contact list 
> ¤ CrashDumper.dll v.[b]0.1.0.2[/b] [14 Jun 2018 0:10:16] - Crash dumper 
> ¤ Dbx_mdbx.dll v.[b]0.95.8.7[/b] [14 Jun 2018 0:11:06] - Miranda NG MDBX database driver 
> ¤ Dbx_mmap.dll v.[b]0.95.8.1[/b] [14 Jun 2018 0:09:46] - Miranda NG mmap database driver 
> ¤ Facebook.dll v.[b]0.4.1.3[/b] [14 Jun 2018 0:10:12] - Facebook 
> ¤ GG.dll v.[b]0.11.0.4[/b] [14 Jun 2018 0:10:06] - Gadu-Gadu protocol 
> ¤ historypp.dll v.[b]1.5.1.5[/b] [14 Jun 2018 0:11:32] - History++ 
> ¤ HistoryStats.dll v.[b]0.2.1.1[/b] [14 Jun 2018 0:11:12] - HistoryStats 
> ¤ Import.dll v.[b]0.95.8.6[/b] [14 Jun 2018 0:10:12] - Import contacts and messages 
> ¤ mTextControl.dll v.[b]0.8.0.1[/b] [14 Jun 2018 0:09:56] - Miranda text control 
> ¤ NewEventNotify.dll v.[b]0.2.2.3[/b] [14 Jun 2018 0:10:14] - NewEventNotify 
> ¤ NewXstatusNotify.dll v.[b]1.4.0.11[/b] [14 Jun 2018 0:09:56] - xStatus notify 
> ¤ PluginUpdater.dll v.[b]0.1.2.5[/b] [14 Jun 2018 0:10:22] - Plugin updater 
> ¤ Popup.dll v.[b]2.1.1.14[/b] [14 Jun 2018 0:09:58] - Popup plus 
> ¤ Restart.dll v.[b]0.0.6.0[/b] [14 Jun 2018 0:10:24] - Restart 
> ¤ SkypeWeb.dll v.[b]0.12.2.5[/b] [14 Jun 2018 0:11:06] - Skype protocol (Web) 
> ¤ SmileyAdd.dll v.[b]0.3.1.0[/b] [14 Jun 2018 0:10:24] - SmileyAdd 
> ¤ TabSRMM.dll v.[b]3.5.0.9[/b] [14 Jun 2018 0:09:52] - TabSRMM 
> ¤ TopToolBar.dll v.[b]0.8.0.5[/b] [14 Jun 2018 0:10:16] - TopToolBar 
> 
> [b]Protocols and Accounts:[/b]
> -------------------------------------------------------------------------------
> Facebook                 1 - Enabled 0 - Disabled  Loaded
> GG                       1 - Enabled 0 - Disabled  Loaded
> SKYPE                    1 - Enabled 0 - Disabled  Loaded
> 
> [b]Icon Packs:[/b]
> -------------------------------------------------------------------------------
>  HistoryPP_icons.dll [14 Jun 2018 0:11:26]
>  Proto_Facebook.dll [14 Jun 2018 0:11:24]
>  Proto_GG.dll [14 Jun 2018 0:11:24]
>  Proto_MetaContacts.dll [14 Jun 2018 0:11:26]
>  Proto_Skype.dll [14 Jun 2018 0:11:28]
>  TabSRMM_icons.dll [14 Jun 2018 0:11:26]
>  Toolbar_icons.dll [14 Jun 2018 0:11:24]
> [/quote][/spoiler]

### Steps to reproduce that behavior
I just install plugin, and after several conversations, I tried to create statistics.

I noticed that on exclude tab I cannot change any option and I still have all protocol disabled. I tried to uninstall plugin and install one more time but problem still occurs.

**Comment by Goraf** [comment]
The only thing you can change on 'exclude' tab is a marker (icon) at the end of line of every contact/group. Do you mean that it doesn't change when you click it there? And options works mostly per contact. To disable all contacts from particular account there is option on 'input' tab, called "Ignore all contacts with protocol..". 

Check those two please and report back. 
I'm using Miranda 0.95.9 and it works for me out of the box.

**Comment by anetamm** [comment]
Hi, 

Thank you for answer.

On "input" tab I haven't marked any contacts in option "Ignore all contacts with protocol..". I would like to have all contacts in my stats.

On "exclude" tab options the marker is ON all the time. When I remove it and press OK to close Configure History Stats window and then open it again the marker is turned on again.
I think that's why statistics are not generated.

I haven't had such problems before. They appeared after the new installation of Windows.

**Comment by Goraf** [comment]
So I tried clean install of 0.95.8.1 x64 with new profile and it works. Hmm.. 

Hmm.. Lets try some tests then. Please download a new archive from site (https://www.miranda-ng.org/en/downloads/) and unpack it somewhere (like desktop, it is just for quick test only). Run it and create a new profile. You are using facebook so add only this account and after that turn it online for a moment to let plugin adds your contacts to the list (you can switch it to offline after that). Add HistoryStats plugin using the main menu "Available component list". Restart Miranda (just in case) and try to create stats without touching anything in options/configuration. It doesn't matter that you don't have messages in history of this new profile, it should show entires of contacts with 0 messages as well.

If that will work then your problems are most likely profile related

**Comment by georgehazan** [comment]
I don't have any problems with it too...
@anetamm would you please export your Settings/HistoryStats module into ini file and attach it to this ticket?

**Comment by anetamm** [comment]
@Goraf I did as you suggested and everything works ok. I will look for where the problem is with my profile.

@georgehazan ok, but I do not know how. Can  you write me how to do it?

**Comment by anetamm** [comment]
Guys, I found the cause of my problem. I did not pay attention to two options on "output" tab: 
- remove contacts with only incoming chats
- remove contacts with only outgoing chats
Both of them were selected.

Sorry for the fuss and thank you for your time.
