### ISSUE TITLE
Auto creating profile based on AutoExec_User.ini

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1434]
> Можно ли сделать, чтобы при запуске Миранды без профиля, автоматически создавался профиль на базе моего AutoExec_User.ini? Пока что я от всего вычистил редактором базы User.dat, при запуске Миранды в него все молча импортируется, но метод кривой, как для меня.

https://forum.ru-board.com/topic.cgi?forum=5&topic=39486&start=3280#13

**Comment by georgehazan** [comment]
решается через mirandaboot.ini:
- ставим AutoCreate=yes
- запускаем миранду с параметром /profile=kaboom 
- миранда автоматом всасывает в новый профиль инишку
- профит
