### ISSUE TITLE
Miranda Crashing at start

### ISSUE THREAD

**Issue by Servantik** [miranda-ng/miranda-ng#1447]
My Miranda is crashing at start(:
Сигнатура проблемы:
  Имя события проблемы:	APPCRASH
  Имя приложения:	Miranda64.exe
  Версия приложения:	0.95.8.19981
  Отметка времени приложения:	5b33f296
  Имя модуля с ошибкой:	Dbx_mdbx.dll
  Версия модуля с ошибкой:	0.95.8.7
  Отметка времени модуля с ошибкой:	5b35136e
  Код исключения:	c0000005
  Смещение исключения:	000000000001585c
  Версия ОС:	6.1.7601.2.1.0.256.1
  Код языка:	1049
  Дополнительные сведения 1:	c5d7
  Дополнительные сведения 2:	c5d7d40a9d388cad4b06153c5f948435
  Дополнительные сведения 3:	8d86
  Дополнительные сведения 4:	8d8627d7551029e6fce12803a5428e1d

**Comment by georgehazan** [comment]
можно попробовать восстановить профиль из бэкапа, если он есть.
лучше сделать нормальный краш-репорт (https://wiki.miranda-ng.org/index.php?title=Crash_reports)

**Comment by Servantik** [comment]
Получилось решить проблему.
Я переименовал базу профиля - дал файлам расширение sav. Создал заново профиль с тем же именем. А потом успешно импортировал базу из сохраненных файлов. И все заработало.

**Comment by georgehazan** [comment]
ok. сейчас в версии для разработки отрабатывается вариант с усиленной защитой, надеюсь, что в будущем таких проблем не будет
