### ISSUE TITLE
Реализация возможности обновления vcard при открытии контакта

### ISSUE THREAD

**Issue by Phaere** [miranda-ng/miranda-ng#1452]
В корпоративной среде - очень важно поддерживать vcard контакта в актуальном состоянии, люди очень активно пользуются этой информацией, а она актуальна только на стороне сервера.
До недавнего времени использовался сервис RefreshDetails плагина WhenWasIt, который запускался при старте клиента и за несколько часов обновлял всю информацию.
К сожалению после перехода на новую БД - данный сервис начал создавать значительную нагрузку на диски, создавая много изменений в БД миранды. Также, при количестве пользователей 1000+ он начинает ощутимо грузить сервер на протяжении долгого времени.
Один из возможных вариантов решения - опция "обновлять vcard при открытии контакта". 
Немного изучив поведение пользователей - чаще всего им требуется вкард людей, с которыми они общаются. Таким образом, если при открытии вкладки контакта будет запрашиваться его вкард с сервера - это снимет ненужную нагрузку с профиля и сервера.
Из возможностей, интегрированных в протокол, я находил только XEP, который хеширует аватар и посылает его хеш в каждом presence. Для обновления Vcard он не подходит, аватар не так часто меняется.

**Comment by dartraiden** [comment]
Реализовано автоматическое обновление вкардов
https://forum.miranda-ng.org/index.php?topic=5831.msg25044#msg25044
