### ISSUE TITLE
Remove "Show in menu" from all plugins

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1455]
Some plugins allow to show or hide their menu items.

ZeroNotify:
[Hide the "toggle sound" menu item (requires restart of Miranda)]

ProxySwitch:
[Display 'Show my IP' in menu]
[Display 'Proxy && IP' submenu]

I propose to make a list of such plugins and remove this feature. The user should use the menu editor for enable/disable menu items.

**Comment by Goraf** [comment]
Yes, they should, but when it comes to just simply show/hide, it is often a convenient shortcut and, what is more important, you can see just from looking at options page that plugin is adding some menu items. Right now there is a lack of such information in many cases. We often don't have it on wiki or anywhere else.

So with only remove of them I think that we would actually downgrade in UX and accessibility

**Comment by tweimer** [comment]
I agree with @dartraiden. Those options only clutter the options dialogs.

**Comment by dartraiden** [comment]
> you can see just from looking at options page that plugin is adding some menu items

We can just enable all menu items for installed plugins. If they are not needed, the user will turn them off. But if we do this, it will affect already existing users ...

**Comment by dartraiden** [comment]
Some plugins (SeenPlugin for example) have the ability to hide icon for menu item. We need to implement this functionality into core or drop such possibility.

**Comment by georgehazan** [comment]
there's no need to enable all these menu items, we can hide/show menu items according to existing options and then delete the settings

**Comment by Goraf** [comment]
SeenPlugin is a different story and I don't think it fits to this ticket as it uses customizable menu item so it needs options entries anyway

**Comment by georgehazan** [comment]
so, what we gotta do with all that stuff?
