### ISSUE TITLE
Tipper: variables with comma doesn't work

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1459]
`?translate(Give it up, I'm not in!)`

![default](https://user-images.githubusercontent.com/5046855/42396757-b5112a06-816b-11e8-8598-01c284345dec.png)

without a comma, i.e. `?translate(Give it up I'm not in!)`, works

**Comment by dartraiden** [comment]
Solution: `?translate(`Give it up, I'm not in!`)`

todo: add this hack to wiki

**Comment by tweimer** [comment]
Actually it is not a hack, and documented in the wiki: https://wiki.miranda-ng.org/index.php?title=Plugin:Variables/en#.60string.60
