### ISSUE TITLE
Language-specific group names

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1464]
"Group name" setting in message plugins. If I start Miranda on English, and then install and use Russian langpack, I want to add my contacts to "Контакты" and "Чаты", not to "Contacts" and "Chats".

**Comment by dartraiden** [comment]
Affected plugins:

StdMsg:

![default](https://user-images.githubusercontent.com/5046855/42559608-48a6e23a-84fd-11e8-8172-2a53e75c9507.png)

**Comment by georgehazan** [comment]
if a setting is already stored in the database, it shall not be translated again
