### ISSUE TITLE
StopSpam should update default phrases if langpack changed

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1479]
At this moment, StopSpam update this phrases only after Miranda restart

![default](https://user-images.githubusercontent.com/5046855/42591777-61566f28-8550-11e8-9489-4b64b16feab1.png)

I switch from English to Russian, but text still English.

**Comment by georgehazan** [comment]
as for me, these phrases are bilingual , so this ticket looks a bit strange
![image](https://user-images.githubusercontent.com/4628541/42598520-1bfc7c0a-8565-11e8-9cad-1ca200221846.png)
