### ISSUE TITLE
Jabber error presence logged repeatedly: "Unknown event type 2001, size 1"

### ISSUE THREAD

**Issue by theultramage** [miranda-ng/miranda-ng#1499]
On all my jabber contacts, even those that I haven't interacted with over a year, I keep getting these unknown entries in the logs. It just adds noise and bumps the last write time of the files.

in chat history - "sent error presence"
in msgexport - "Unknown event type 2001, size 1"

These show up erratically, once every few months and then multiple times a day. Oldest one I have is from 2010-04-09. I have been using the same jabber server since 2005. I don't know if it's a server misconfiguration, or an ancient Miranda glitch.

**Comment by georgehazan** [comment]
these options will help you
![image](https://user-images.githubusercontent.com/4628541/42772943-88a1ca86-8934-11e8-819c-4e0204492a7f.png)
