### ISSUE TITLE
mimcmd (command line)

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#150]
**Reported by vanishare on 19 Jan 2013 10:31 UTC**
       (   mimcmd.exe)  (       ,  )  .       ,         mimcmd.exe
        .

```
   ,               .
```

**Comment by georgehazan** [comment]
**Modified by mataes on 27 May 2014 07:59 UTC**

**Comment by dartraiden** [comment]
Duplicate of #119
