### ISSUE TITLE
AssocMgr: some protocols have icon only if checked

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1506]
Clean profile. No accounts. All unchecked. Icons for GG, MSN, Skype and DAT are missing, but other protocols icons are in place:

![default](https://user-images.githubusercontent.com/5046855/42739438-f8192ff2-889f-11e8-9fd4-08d3f647f4b1.png)

All checked:

![default](https://user-images.githubusercontent.com/5046855/42739441-19dddfde-88a0-11e8-8754-a4067662291e.png)

**Comment by georgehazan** [comment]
attach a profile, please. I cannot reproduce it
