### ISSUE TITLE
Sessions cannot open Jabber groupchats

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1515]
> ghazan, 23.07.2018 16:43:57:
> sessions срабатывает много раньше
> 
> ghazan, 16:44:09:
> ему ж не надо никуда ни коннектиться, ни логиниться

**Comment by georgehazan** [comment]
похоже, что без шансов. ну т.е. вызывается всё правильно, но нет никакой гарантии, что жабер будет влогинен, а поднять окно чата в пассивном протоколе никто не даст
