### ISSUE TITLE
Miranda in Twitter

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1516]
Connected Miranda app:

![default](https://user-images.githubusercontent.com/5046855/43080389-4ea28d70-8e98-11e8-8c60-64177e7d6af7.png)

We should:
- obtain control on this developer account
- change name
- change icon

**Comment by tweimer** [comment]
Is it some kind of Miranda custom pack? At least it doesn't claim to be official. Did anyone try to contact the authors?

**Comment by dartraiden** [comment]
No, it's our Twitter plugin

**Comment by tweimer** [comment]
What does that mean?

**Comment by dartraiden** [comment]
Our Twitter plugin use API key owned by this peoples.

**Comment by georgehazan** [comment]
I catched omniwolf at Facebook, he corrected the icon & app description
unfortunately it had broken the callback page that prints the code after app validation
any ideas how to fix it?

**Comment by georgehazan** [comment]
Twitter works again
