### ISSUE TITLE
Miranda NG stable install is in another language

### ISSUE THREAD

**Issue by Pauls83** [miranda-ng/miranda-ng#1519]
I'm on this page which seems to be correct for the English version but when I download and run the install, Miranda NG opens in some other language and I am not sure how to get it in English. What am I missing?

https://www.miranda-ng.org/en/downloads/

**Comment by dartraiden** [comment]
What is the language of your operating system?

**Comment by Goraf** [comment]
One of the quick solutions for you could be to delete all langapcks from `Languages` subfolder of your Miranda installation

**Comment by pstoric83** [comment]
Thanks! I'll try that next Monday when I'm back on-site.

**Comment by dartraiden** [comment]
Already fixed in 982c759948fd79f133180df85d96d24e72c431d1

@georgehazan, backport this to stable and rebuild installers, please

**Comment by pstoric83** [comment]
In the Languages folder it only has "langpack_polish" no English. How do I get it in English?

**Comment by Goraf** [comment]
@pstoric83 English is built-in. Just delete Polish one and it will work.

**Comment by pstoric83** [comment]
Thanks! that works
