### ISSUE TITLE
Options module in DB

### ISSUE THREAD

**Issue by FirstPacificator** [miranda-ng/miranda-ng#1524]
В базе есть секция Options, в которой хранятся ключики с настройками развернутости. В эти ключи лезут имена из лангпака. А вот в секцию SkinIconsUI, которая тоже хранит ключи с настройками развернутости, из лангпака ничего не лезет... Просьба сделать также и секцию Options.

**Comment by dartraiden** [comment]
![default](https://user-images.githubusercontent.com/5046855/43147720-58a32b16-8f6c-11e8-98fb-41d2f5fdcc0d.png)
