### ISSUE TITLE
Trojan.Win32.Cossta.alpb

### ISSUE THREAD

**Issue by JinruiTeki** [miranda-ng/miranda-ng#1531]
after update Miranda, Kaspersky free report:
31.07.2018 21.21.52	Поиск руткитов	Задача завершена	Время завершения: Сегодня, 31.07.2018 21:21
31.07.2018 21.20.05	Обнаруженный объект (файл) удален	D:\PROGRAMS\Miranda\Miranda32.exe	Файл: D:\PROGRAMS\Miranda\Miranda32.exe	Название объекта: Trojan.Win32.Cossta.alpb
31.07.2018 21.20.04	Обнаруженный объект (файл) помещен на карантин	D:\PROGRAMS\Miranda\Miranda32.exe	Файл: D:\PROGRAMS\Miranda\Miranda32.exe	Название объекта: Trojan.Win32.Cossta.alpb

**Comment by georgehazan** [comment]
уже выложили фикс, каспер заткнулся
ядро можно скачать руками с https://miranda-ng,org/distr/miranda32.zip
