### ISSUE TITLE
curupted DB from latest update

### ISSUE THREAD

**Issue by hypov8** [miranda-ng/miranda-ng#1537]
After and update and restarting Miranda it asked me if i want to import a database.
I don't have any to select so i click cancel.
Miranda loads, with no contacts or protocols found and the miranda window is invisible, just showing icons.
![mianda_contacts](https://user-images.githubusercontent.com/16630512/43785681-644215f0-9a56-11e8-973d-79962d004456.png)

**Comment by georgehazan** [comment]
- shut down Miranda;
- open your profile directory in a file manager or Explorer (by default - %APPDATA%\Miranda) and rename back a file of name <yourprofile>.DAT,BAK back to .DAT. if the new .DAT file exists, remove it;
- launch Miranda;
- when it would ask you about the upgrade, answer Yes;
- enjoy

**Comment by hypov8** [comment]
That helps.. File was about 2 months old. What caused the DB to get corrupted?
With loading the old DB file, my YAMN plugin was disabled. When I enable the plugin and click apply , Miranda crashes.
To replicate the crash, i have to enable/disable plugin and restart Miranda a few times.
Once I reload Miranda and plugin successfully loaded,  all my POP details have been wiped.
YAMN has always had issues in the past for me. Sometimes you need to restart Miranda for it to receive new emails.

---------------------------------------------------------------
Exception: Access Violation at address 56A64FE2. Writing to address 126B3FB7.

Stack Trace:
---------------------------------------------------------------
56A64FE2 (ucrtbase 56A40000): (filename not available) (0): _stdio_common_vswprintf
56A64DFF (ucrtbase 56A40000): (filename not available) (0): _stdio_common_vswprintf
1280EEB1 (mir_core 12800000): (filename not available) (0): mir_vsnwprintf

**Comment by georgehazan** [comment]
>That helps.. File was about 2 months old. What caused the DB to get corrupted?

Your database was not corrupted, it was in the old format, so the conversion was required to continue working.

YAMN is buggy, yes. Can you attach the whole crash report file?

**Comment by hypov8** [comment]
I added some images that show the data right before the crash. crash dump appears to be different here.
i am on win7 64 but using 32 bit Miranda. not sure what size size_t is on my system but its I suspect count it to large for _vsntprintf?
YAMN is not the only plugin that causes this crash to happen once it gets enabled and applied



[crash20180809233709.zip](https://github.com/miranda-ng/miranda-ng/files/2274385/crash20180809233709.zip)
![mir_yamn_crash_2](https://user-images.githubusercontent.com/16630512/43902646-233130b6-9bda-11e8-8874-40edd81aa268.png)
![mir_yamn_crash_1](https://user-images.githubusercontent.com/16630512/43902647-236a1656-9bda-11e8-8abb-95e6e5a6ab1a.png)

**Comment by georgehazan** [comment]
it seems that the core version differs from the version of plugins. try to do the following:
- download 32-bit core (https://miranda-ng.org/distr/stable/miranda-ng-v0.95.8.1.7z 
- unpack it to your folder;
- remove YAMN.dll (and all another dlls until crash persists);
- use Plugin Updater to update remaining modules;
- readd plugins using Plugin Updater;
- never add plugins manually in the future

**Comment by hypov8** [comment]
This is already a fresh install from the exact file you just sent.
I have only used the plugin updater tool for getting additional plugins.(the file dates are different but the updater gets crc match files if I delete any of the official plugins)

I think I know how to make it happen
with no additional plugins added, disable msn and irc protocols
close. open. enable irc protocol. crash..
I guess its still loading user accounts for inactive plugins

[crash20180810142013.zip](https://github.com/miranda-ng/miranda-ng/files/2276579/crash20180810142013.zip)

![mir_yamn_crash_3](https://user-images.githubusercontent.com/16630512/43938645-749c09f6-9c54-11e8-91e0-d2c0031027cc.png)
