### ISSUE TITLE
SkypeWeb+TabsRMM: если человек поставил статус "невидимка" или offline - сообщение доходит, но диалог зависает на 30 сек в ожидании ошибки.

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#1549]
Если человек поставил статус "невидимка" или offline - сообщение доходит (проходит в логе сервера и в ожидании доставке), но само диалоговое окно зависает и второе сообщение не отправить, не отменив предыдущее или дождавшись ошибки через секунд 30.

![uvin3d](https://user-images.githubusercontent.com/5046855/44629512-33244a80-a959-11e8-8ba5-3c6ccf1a7720.png)

Но ведь всё равно доходит в скайпвебе

![xrony3](https://user-images.githubusercontent.com/5046855/44629515-3c151c00-a959-11e8-980d-18992fe8a671.png)

Нужно чтобы не было такой задержки/ожидания, учитывая что там всё равно промежуточные микрософтовые серверы доставят потом сообщения, нету же полноценного p2p

**Comment by georgehazan** [comment]
не подтвердилось. может быть проблема с конкретным сервером скайп
