### ISSUE TITLE
Дублирование контактов в чате Twitter при использовании сессий.

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#156]
**Reported by Radjah on 26 Jan 2013 10:07 UTC**
     twitter      :
     ,  ..  Twitter.   Twitter  offline,         .
Twitter   ,    .           Twitter,       ,    .
     Scriver.

**Comment by georgehazan** [comment]
**Comment by Rainman on 29 Jan 2013 20:00 UTC**
,   .

**Comment by dartraiden** [comment]
Duplicate of #125
