### ISSUE TITLE
Em-LAN doen't work

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1568]
Running 2 Miranda on two separate machines in local network. Em-LAN doesn't automatically add another client into clist via broadcast. And cannot connect via IP specifying.

**Comment by georgehazan** [comment]
it means that you have blocked broadcasts between your hosts somehow

**Comment by l0oo** [comment]
Hello!
Have similar problem. NET VIEW \\ComputerName command works as should... :/
