### ISSUE TITLE
Dynamic un/loading bugs

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#157]
**Reported by robyer on 26 Jan 2013 12:32 UTC**
1) pasteit, packupdater, splashscreen - are crashing when dynamically un/loaded
2) ftp file ym - it cant be loaded at miranda start due to missing library (which is ok), but when try to load it dynamically, it loads without problem (which is wrong)

**Comment by Goraf** [comment]
#968 ListeningTo should be fixed
ad 3) shouldn't be a case anymore

**Comment by georgehazan** [comment]
PasteIt doesn't crash either

**Comment by georgehazan** [comment]
ftp file ym is also linked with all needed libraries, so it cannot give any error messages
