### ISSUE TITLE
EmLAN icons section name

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1572]
![4444444444444](https://user-images.githubusercontent.com/5046855/44946323-0b266280-ae03-11e8-97b5-a012f4be1f4d.png)

This should me EmLAN or E-mage LAN protocol, but don't EM_LAN_PROTO

![55555555555555](https://user-images.githubusercontent.com/5046855/44946337-3ad56a80-ae03-11e8-87a4-1991d1cb215a.png)

**Comment by georgehazan** [comment]
the problem is that old-style protocols like EMLan can't have display name for accounts... they share the database module name with interface, including icons & popups
