### ISSUE TITLE
Make Skype and Twiter sounds per-account instead of per-protocol

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1573]
![4](https://user-images.githubusercontent.com/5046855/44946359-aa4b5a00-ae03-11e8-998a-7d3f4c54201d.png)

Other accounts have per-account sound setup, but Skype and Twitter - per-protocol

**Comment by georgehazan** [comment]
almost all protocols (frankly speaking, all of them despite MSN & MRA) use global sound names (grep Skin_PlaySound for more info)
