### ISSUE TITLE
Fingerprint: change Conversations icon

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1575]
Conversation logo contains white "stripes" on the edge:

![splash_logo](https://user-images.githubusercontent.com/5046855/44957044-cc151180-aed5-11e8-8d03-f839314fba0a.png)

This looks ugly at 16x16. Current icon:

![1](https://user-images.githubusercontent.com/5046855/44957049-dcc58780-aed5-11e8-8e95-edaef3a414bf.png)

I suggest a new icon without stripes. There are 3 variants.

V1:
![2](https://user-images.githubusercontent.com/5046855/44957058-eea72a80-aed5-11e8-9340-8e088e491a76.png)

V2 (a bit darker):
![3](https://user-images.githubusercontent.com/5046855/44957060-f36bde80-aed5-11e8-8249-d58fb6f085f4.png)

V3 (brighter dots)
![4](https://user-images.githubusercontent.com/5046855/44957261-02a05b80-aed9-11e8-8266-6e2cf1897830.png)

**Comment by watcherhd** [comment]
voting for V3

**Comment by georgehazan** [comment]
same, simply commit this icon instead of the existing one
