### ISSUE TITLE
[TabSRMM] Message text highlighting based on keyword does not work correctly

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#1578]
### Expected behavior
I am able to add keywords to the "Highlight message text" window to be alerted for specific keywords that might show up in group chat message text

### Actual behavior
Nothing added to the highlight message text option is saved. The option to notify based on my own nickname works though...

### Does it work in stable version?
Not sure if this ever worked properly.

### Steps to reproduce that behavior
 * Install TabSRMM plugin
 * Go to Message Sessions->Group Chats and configure some keywords to be highlighted.
 * Save by presssing APPLY/OK
 * Go back to the same menu - the saved keyword is gone.

**Comment by dartraiden** [comment]
TabSRMM?

**Comment by dartraiden** [comment]
We fixed this bug a long time ago,,, maybe it's alive again :)

**Comment by LittleVulpix** [comment]
@dartraiden indeed, sorry; didn't realize this was a tabsrmm option but ofc it is.

**Comment by dartraiden** [comment]
Confirmed.
