### ISSUE TITLE
[SteamWeb] Support for the new invisible mode

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#1579]
**Is your feature request related to a problem? Please describe.**
Steam now supports invisible mode.

**Describe the solution you'd like**
Since miranda does too, it should be implemented for the steam web protocol

**Describe alternatives you've considered**
Not really

**Additional context**
The steam chat api and chat itself have changed recently, bringing some new features after years of stagnation; it'd be nice to have those implemented in Miranda.

**Comment by georgehazan** [comment]
Also fixed in the new protocol
