### ISSUE TITLE
ClistBlind: more items in the context menu of groups

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#158]
**Reported by Piciok on 29 Jan 2013 17:13 UTC**
Currently it's not possible to create a new group on the contact list. The only waty around it is to get into a situation where nothing's highlighted on the list and the option is available in the Context menu. It can be achieved right after Miranda starts, when nothing is selected on the list. My idea is to have a hotkey or an option in the main menu of Miranda NG to create a new group. This way we can avoid stickijng it in some weird place such as eg. the context menu of groups which is leaving those who don't have any groups created yet behind.

**Comment by georgehazan** [comment]
**Modified by watcher on 4 Feb 2014 16:25 UTC**

**Comment by georgehazan** [comment]
**Modified by mataes on 20 Jun 2014 04:02 UTC**

**Comment by LittleVulpix** [comment]
This is actually still the case with clist_modern as well. To make a new group, you need to call up context menu in a "free space" on the contact list, meaning you cannot right click any groups or contacts. In a situation where you have many groups and cannot expand the contact list vertically anymore, this becomes a problem.

**Comment by bdorer** [comment]
I don't know how the list in clist-blind is created but a standard keystroke is Ctrl+space to unfocus the entry.
Another way is to add the groups menu in to the menu bar. At the moment I'm not able to see the menu but it is configurable from settings > Customize.

**Comment by georgehazan** [comment]
now it's possible to use group's menu to create new group
