### ISSUE TITLE
[0.95.9 20729] Steam refusing connection, 401 Unauthorized

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#1583]
### Expected behavior
For Steam to be able to connect.

### Actual behavior
The Steam protocol broke. I keep getting 401 Unauthorized. This is probably due to an API change on Valve's end. 0.95.8 has not been able to connect either since a couple of days ago. Anyone else getting this?

**Comment by georgehazan** [comment]
works like a charm, just connected miranda to my Steam account

**Comment by Tharn** [comment]
After deleting and recreating the account, Miranda displayed the e-mail code prompt, I got an e-mail and it works again.

For some reason, the old account would simply refuse to connect. I still think this is worth a bug report, but for me personally the issue is gone.

**Comment by georgehazan** [comment]
yes, a network log with the problem will be appreciated

**Comment by Tharn** [comment]
This is the relevant piece. It just repeats.

```
access_token=**************************&ui_mode=web
[04:34:06 07B8] SSL Server signaled SSL Shutdown
[04:34:06 07B8] [STEAM_1] (0000000004AAA060:1716) Data received
HTTP/1.1 401 Unauthorized
Content-Length: 174
Content-Type: text/html; charset=UTF-8
Expires: Thu, 06 Sep 2018 02:34:05 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Thu, 06 Sep 2018 02:34:05 GMT
Connection: close

<html><head><title>Unauthorized</title></head><body><h1>Unauthorized</h1>Access is denied. Retrying will not help. Please verify your <pre>key=</pre> parameter.</body></html>
[04:34:06 07B8] [STEAM_1] (0000000004AAA060:1716) Connection closed internal
[04:34:06 07B8] [STEAM_1] (0000000004AAA060:4294967295) Connection closed
[04:34:06 07B8] [STEAM_1] CSteamProto::OnLoggedOn: unknown login error
[04:34:06 07B8] [STEAM_1] CSteamProto::SetStatus: changing status from 1 to 40071
[04:34:06 07B8] [STEAM_1] Connection request to api.steampowered.com:443 (Flags 11)....
[04:34:06 07B8] [STEAM_1] (0000000004AAA9E0) Connecting to server api.steampowered.com:443....
[04:34:06 07B8] [STEAM_1] (0000000004AAA9E0) Connecting to ip 172.227.98.69:443 ....
[04:34:06 07B8] [STEAM_1] (1720) Connected to api.steampowered.com:443
[04:34:06 07B8] [STEAM_1] (1720 api.steampowered.com) Starting SSL negotiation
[04:34:06 07B8] [STEAM_1] (1720 api.steampowered.com) SSL negotiation successful
[04:34:06 07B8] [STEAM_1] (0000000004AAA9E0:1720) Data sent
POST /ISteamWebUserPresenceOAuth/Logoff/v0001 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: Miranda/0.95.9.20729 (x64)
Accept-Encoding: deflate, gzip
Host: api.steampowered.com
Connection: Keep-Alive
Proxy-Connection: Keep-Alive
Content-Length: 71
```

**Comment by georgehazan** [comment]
well, the error doesn't say much, but at least after this error Steam shall not try to relogin.
unfortunately there's no info that a 'key' should be renewed :-(

**Comment by Tharn** [comment]
Since key =/= password, it might be a good idea to have an option in the Steam protocol to forget a key. I have found no option but to recreate the account, and simply querying Steam for a new key would be more elegant.

There could even be another input field under username and password with the key in it, so that the user can erase it and prompt a new key popup from Steam.

**Comment by LittleVulpix** [comment]
@Tharn miranda has a mechanism whereby it will delete the key after X unsuccessful logins. It has been working for me properly; I get prompted for a new token/key in case it expires or in case I fail to login multiple times.

**Comment by RathaWynter** [comment]
If you run into this again, you can manually remove the token with Database Editor++ without having to delete your account / history.
- Install the Database Editor++ addon and then launch it from Miranda's Main menu.
- Expand the Database Editor's "Settings" section in the left pane.
- Locate the correct Steam account (or search for "TokenSecret")
- Edit and clear the entry for "TokenSecret" on the correct Steam account.
- Attempt to login again. You should get the email/mobile code entry box to pop up.

There are occasionally times where you can login via friends, but not Miranda, however if the problem persists for more than a couple of hours its almost certainly a token issue. If you enter a new code into the popup and it still does not log you in, then its probably a Steam server issue and you'll likely have to wait an hour or two for a resolution.

**Comment by Tharn** [comment]
Thanks Ratha for the workaround. I guess what remains of this issue is that Miranda has a key deletion mechanism which did not work for me.

**Comment by Tharn** [comment]
It happened again. The protocol worked one day, stopped working the next.
Going into the log reveals 401 unauthorized.

This plugin needs a way to kill bad tokens, since apparently the automatic mode is not always reliable.

**Comment by RathaWynter** [comment]
It would be great to see an option on the account page, or on the Steam plugin to purge login tokens or force a new login session. I tend to have this issue every month or two. After hoping it will resolve itself and waiting 15-30 minutes, usually I'll restart Miranda, checking to make sure that I can login with the official Steam client. If i can then I'll go delete the token and try to login. If it fails (which often it will) I'll restart the client again. Then sometimes it will fail once or twice more before just magically working. Am not quite sure whats going on in those situations but deleting the TokenSecret usually solves it within about 3-5 minutes.

Miranda often feels very inconsistent with its Steam login behavior. Especially when you try to connect, it shows you online/connecting for a moment, and then it just stops and sets you back offline again without displaying any kind of error or anything to indicate what might be going on. Makes me wonder if theres something else internally that also needs to automatically expire before it allows logging in again. Or if too many login attempts with an invalid token cause Steam to block you from receiving a steamguard popup for a few minutes.
