### ISSUE TITLE
db_autobackups crash

### ISSUE THREAD

**Issue by BLF0x** [miranda-ng/miranda-ng#1588]
Падает с установленным db_autobackups в момент создания резервной копии. Если успеть отключить создание копии, перезапустить, включить создание копии и нажимать кнопку "сохранить сейчас" либо играться с параметрами в настройках -- копия не создается, программа не падает... Иногда при манипуляциях с полем "каждые:" или полем "количество резервных копий:" и последующим нажатием на "сохранить сейчас" в папке копий успевает появиться файл резервной копии, после чего самоуничтожиться =)
Т.е. копия создается только если при ЗАПУСКЕ программы было в настройках авторезервирование оно (авторезервирование) включено. При этом программа падает с ошибкой (в папке бэкапа остается не полностью записанный файл). Если при запуске авторезервирование отключено то программа не падает и копия при включении (без перезапуска программы) не создается...

   Miranda Crash Report from 7 Sep 2018 8:29:51. Crash Dumper v.0.1.0.2
Exception: Access Violation at address 125C5B33. Reading from address 01490D3D.

Stack Trace:
---------------------------------------------------------------
125C5B33 (libmdbx 125C0000): (filename not available) (0): mdbx_env_copy2fd
00080000 ((module-name not available) 00000000): (filename not available) (0): (function-name not available)

[crash20180908091559.txt](https://githu
[crash20180907082950.txt](https://github.com/miranda-ng/miranda-ng/files/2363089/crash20180907082950.txt)

b.com/miranda-ng/miranda-ng/files/2363088/crash20180908091559.txt)

**Comment by dartraiden** [comment]
База повреждена, попробуйте создать чистую базу и импортировать туда всё со старой.

**Comment by BLF0x** [comment]
какой ужас... а есть инструменты для экспорта импорта ? =)))))) а то как то некузяво опять всю историю грохать...

**Comment by dartraiden** [comment]
После создания новой базы всплывает предложение импортировать.

**Comment by BLF0x** [comment]
Да, спасибо, все "починилось". А все же, может стоит средство для "починки" подобных баз написать ??? Вроде раньше было... потом про новую базу говорили что она самопочинябельная. По факту -- вот грабельки родимые вылезли и опять ручками пимпы топтать -- некузяво =)

**Comment by dartraiden** [comment]
Это следствие того, что в прошлой стабле использовалась libmdbx 0.9, а в ней были кое-какие проблемы. В новой стабле используется libmdbx 1.0, которая намного "прочнее".
