### ISSUE TITLE
New type of contact list sorting: "Rate (ignore status)"

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#159]
**Reported by alien on 30 Jan 2013 16:05 UTC**
I discussed it long time ago with fry and we agree that there should be one more sorting method: "Rate(ignore status)"

Look at this:

![uwthldn](https://cloud.githubusercontent.com/assets/5046855/21083116/55940f28-bffa-11e6-8dcb-ffcd6c153439.jpg)

and focus on two contacts that have "Rate" set (no matter how strong)
since i have "Rate" as first sorting parameter, i want to have all contacts with any rate at the top of CList,no matter what other user data is.

If the contact don't have rate, then let the rest of the parameters will be applied. For now  "Wrocaw" contact is after all twitter contacts and twitter contacts don't have any "Rate" set. So as you see, Rate filter combined with Name and then status works not as in early 0.8 version.

So: i want that "Rate(ignore status)" works like that: put all contacts that have rate on on top of the list and then apply rest of the filter parameters. Then, below all contacts that have rate, put rest of the contacts and apply rest of the filter parameters.

**Comment by georgehazan** [comment]
**Comment by robyer on 31 Jan 2013 11:27 UTC**
This option is already here (in clist_modern), isn't it? Or what is wrong? It work as it should for me.

**Comment by georgehazan** [comment]
**Comment by alien on 13 Apr 2013 22:38 UTC**
Replying to [robyer](comment:1):
> This option is already here (in clist_modern), isn't it? Or what is wrong? It work as it should for me.
No it's not. The option what you think about is "Rate" and it works like that "Get all contacts that have rate, set them at the top of the clist and also sort them by second and third parameter." And you will get all contacts that have rate and "offline" status at the bottom, with is wrong. If i set "Rate" for any of the contacts, it's like "Favorite" from MSN: i want to see then at the top of the Clist, before any other contacts that don't have "Rate":

"Get all contacts that have rate, set them at the top of the clist , sort them by rate strength (yellow, red, green star) and if second or third parameter is "status", then ignore it."

This allows me to have very static list of "Other" contacts like Twitter, RSS, Weather and Radio.

**Comment by LittleVulpix** [comment]
This can be closed as **it has been implemented** via the "Don't place offline users to bottom" option right underneath the sorting listboxes in miranda options->contact list->general->contact list sorting-> "Don't place offline users to bottom."

**Comment by Robyer** [comment]
@LittleVulpix I don't think it has anything to do with "offline contacts". It is about sorting priorities (which is not limited to offline contacts).
I need to test it manually to validate this ticket again.

**Comment by LittleVulpix** [comment]
@Robyer I think it is; in the comment by alien from  13 Apr 2013 22:38 UTC , he says that the offline contacts (even those with rate) are below any (even unrated) contacts that are online. By enabling the "Don't place offline users to bottom." option, the sorting behaves exactly like requested - contacts with rate (regardless of status) are atop of all the other users with no rate. It would be best if the user could comment on this issue..

Previously sorting would always place offline users at the bottom of the list, regardless of their rates or other sorting parameters.

**Comment by Robyer** [comment]
Aha, allright then :)
