### ISSUE TITLE
Facebook Contacts are shown as Offline

### ISSUE THREAD

**Issue by winman3000** [miranda-ng/miranda-ng#1592]
If I connect to Facebook, all contacts are shown offline, although  there are online contacts. Status bar says that Facebook is online. After a while, Facebook gets offline and I nee to go online manualy. I don't have any problems with my internet connection. Any ideas?

**Comment by winman3000** [comment]
Here is the netlog.
[netlog.txt](https://github.com/miranda-ng/miranda-ng/files/2376631/netlog.txt)

**Comment by georgehazan** [comment]
Well, at least you can install StatusManager plugin to return FB back
online automatically. I'll dig the log later

**Comment by winman3000** [comment]
The StatusManager plugin would help me to stay online, but I don’t get Messages from the messenger anymore. And the Online and Offline status of the contacts are not reliably. If I connect to Facebook, Miranda tells me all news on my timeline and so on, but I canot see the contacts online status. Sometimes contacts coming online, but after a time, Facebook goes offline. Perhaps the log helps more to identify my problem. I have the same problem on my work place, another Computer, another Internet Connection.

**Comment by zemiacsik** [comment]
@winman3000 and do you have everything up to date? I'm just curious because I had (there was) a very same issue with this online/offline status changing but I think it should be ok with current version(s).

**Comment by slanovani** [comment]
I'm having the same problem, with the difference that now status online doesn't change. i mean. although I know that contacts are online because I'm getting messages, over miranda ng they always show as offline. so it's difficult for me to see who is online and who is not.

**Comment by dartraiden** [comment]
Is this actual for our new FB protocol? (0.95.11 and newer)

**Comment by slanovani** [comment]
No, it doesn't happen with the new protocol.


-------- Mensaje original --------
De: Alexander Gavrilov <notifications@github.com>
Fecha: 24/2/20 1:12 p. m. (GMT-05:00)
Para: miranda-ng/miranda-ng <miranda-ng@noreply.github.com>
Cc: Slann Tonić <reydelasmaquinas@outlook.com>, Comment <comment@noreply.github.com>
Asunto: Re: [miranda-ng/miranda-ng] Facebook Contacts are shown as Offline (#1592)


Is this actual for our new FB protocol? (0.95.11 and newer)
