### ISSUE TITLE
Вылетает при закрытии вкладок

### ISSUE THREAD

**Issue by ilio74** [miranda-ng/miranda-ng#1596]
При закрытии вкладок постоянно вылетает программа, что очень неприятно если чатишься с несколькими контактами. Переустанавливал несколько раз.
Спасибо.

[crash20180922012412.txt](https://github.com/miranda-ng/miranda-ng/files/2407208/crash20180922012412.txt)

**Comment by dartraiden** [comment]
В настройках апдейтера поставьте, пожалуйста, "стабильная версия с отладочными символами" и сделайте лог снова. Без символов он практически бесполезен.

**Comment by ilio74** [comment]
ой как оперативно ответили!
Я не очень сильно разбираюсь, Можете по ICQ 582420512 постучаться?
Спасибо.

**Comment by ilio74** [comment]
Miranda Crash Report from 22 Sep 2018 1:33:57. Crash Dumper v.0.1.0.2

Likely cause of the crash plugin: Miranda NG

Exception: Access Violation at address 0000000012AB2091. Reading from address 000010BC00000000.

Stack Trace:
---------------------------------------------------------------
0000000012AB2091 (mir_core 0000000012AA0000): w:\miranda-build\src\mir_core\src\lists.cpp (138): List_GetIndex
0000000012AB2287 (mir_core 0000000012AA0000): w:\miranda-build\src\mir_core\src\lists.cpp (56): List_Find
0000000012AAE126 (mir_core 0000000012AA0000): w:\miranda-build\src\mir_core\src\cdlgbase.cpp (425): CDlgBase::FindControl
0000000012AADF83 (mir_core 0000000012AA0000): w:\miranda-build\src\mir_core\src\cdlgbase.cpp (259): CDlgBase::DlgProc
00000000129315CE (mir_app 00000000128C0000): w:\miranda-build\src\mir_app\src\srmm_base.cpp (760): CSrmmBaseDialog::DlgProc
000000001A38D03F (TabSRMM 000000001A350000): w:\miranda-build\plugins\tabsrmm\src\msgs.cpp (242): CTabBaseDlg::DlgProc
000000001A37CD54 (TabSRMM 000000001A350000): w:\miranda-build\plugins\tabsrmm\src\msgdialog.cpp (3021): CSrmmWindow::DlgProc
0000000012AAD7B2 (mir_core 0000000012AA0000): w:\miranda-build\src\mir_core\src\cdlgbase.cpp (388): CDlgBase::GlobalDlgProc
00007FFB332B214C (USER32 00007FFB332A0000): (filename not available) (0): GetWindowRgnBox
00007FFB332B242D (USER32 00007FFB332A0000): (filename not available) (0): Ordinal2573
00007FFB332B2346 (USER32 00007FFB332A0000): (filename not available) (0): Ordinal2573
0000000012AB7BB2 (mir_core 0000000012AA0000): w:\miranda-build\src\mir_core\src\subclass.cpp (168): mir_callNextSubclass
000000001A054475 (SmileyAdd 000000001A050000): w:\miranda-build\plugins\smileyadd\src\dlgboxsubclass.cpp (88): MessageDlgSubclass
0000000012AB7B99 (mir_core 0000000012AA0000): w:\miranda-build\src\mir_core\src\subclass.cpp (164): mir_callNextSubclass
000000001A058F4B (SmileyAdd 000000001A050000): w:\miranda-build\plugins\smileyadd\src\richcall.cpp (366): RichEditOwnerSubclass
0000000012AB7AE1 (mir_core 0000000012AA0000): w:\miranda-build\src\mir_core\src\subclass.cpp (43): MSubclassWndProc
00007FFB332B6CC1 (USER32 00007FFB332A0000): (filename not available) (0): CallWindowProcW
00007FFB332B62CE (USER32 00007FFB332A0000): (filename not available) (0): SendMessageW
00007FFB332B6058 (USER32 00007FFB332A0000): (filename not available) (0): SendMessageW
00000000128D4CCA (mir_app 00000000128C0000): w:\miranda-build\src\mir_app\src\button.cpp (565): MButtonWndProc
00007FFB332B6CC1 (USER32 00007FFB332A0000): (filename not available) (0): CallWindowProcW
00007FFB332B688B (USER32 00007FFB332A0000): (filename not available) (0): CallWindowProcW
00007FFB255CD96B (COMCTL32 00007FFB255A0000): (filename not available) (0): DefSubclassProc
00007FFB255CDA88 (COMCTL32 00007FFB255A0000): (filename not available) (0): DefSubclassProc
00007FFB255CD802 (COMCTL32 00007FFB255A0000): (filename not available) (0): DefSubclassProc
0000000012AB7BB2 (mir_core 0000000012AA0000): w:\miranda-build\src\mir_core\src\subclass.cpp (168): mir_callNextSubclass
000000001A3A1A15 (TabSRMM 000000001A350000): w:\miranda-build\plugins\tabsrmm\src\tsbutton.cpp (496): TSButtonWndProc
0000000012AB7AE1 (mir_core 0000000012AA0000): w:\miranda-build\src\mir_core\src\subclass.cpp (43): MSubclassWndProc
00007FFB332B6CC1 (USER32 00007FFB332A0000): (filename not available) (0): CallWindowProcW
00007FFB332B6693 (USER32 00007FFB332A0000): (filename not available) (0): DispatchMessageW
00007FFB332B94CF (USER32 00007FFB332A0000): (filename not available) (0): IsDialogMessageW
0000000012917654 (mir_app 00000000128C0000): w:\miranda-build\src\mir_app\src\miranda.cpp (373): mir_main
0000000140002944 (Miranda64 0000000140000000): w:\miranda-build\src\miranda32\src\miranda.cpp (62): wWinMain
00000001400014BA (Miranda64 0000000140000000): f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl (288): __scrt_common_main_seh
00007FFB35373034 (KERNEL32 00007FFB35360000): (filename not available) (0): BaseThreadInitThunk
00007FFB35A01461 (ntdll 00007FFB35990000): (filename not available) (0): RtlUserThreadStart

CPU: Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz [Intel64 Family 6 Model 58 Stepping 9] [DEP Enabled] [4 CPUs]
Installed RAM: 16067 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 17134)
Internet Explorer: 9.11.17134.0 (build 917134)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian

Miranda NG Version: 0.95.9 build #20729 (b8830b8510) x64
Build time: 5 Sep 2018 18:35:28
Profile: C:\Users\ilio7\AppData\Roaming\Miranda NG\Рабочий\Рабочий.dat
Language pack: Russian (RU) [0419]
Service Mode: No

Active Plugins (28):
¤ AuthState.dll v.0.95.9.0 [5 Sep 2018 18:35:34] - Authorization state 
¤ AVS.dll v.0.95.9.0 [5 Sep 2018 18:35:36] - Avatar service 
¤ Clist_modern.dll v.0.95.9.0 [5 Sep 2018 18:36:00] - Modern contact list 
¤ CrashDumper.dll v.0.95.9.0 [5 Sep 2018 18:36:00] - Crash dumper 
¤ CryptoPP.dll v.0.95.9.0 [5 Sep 2018 18:36:56] - Crypto++ 
¤ Dbx_mdbx.dll v.0.95.9.0 [5 Sep 2018 18:36:56] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.0.95.9.0 [5 Sep 2018 18:35:34] - Miranda NG mmap database driver 
¤ Dummy.dll v.0.95.9.0 [5 Sep 2018 18:36:34] - Dummy protocol 
¤ Fingerprint.dll v.0.95.9.0 [5 Sep 2018 18:36:16] - Fingerprint NG 
¤ historypp.dll v.1.5.1.5 [5 Sep 2018 18:37:16] - History++ 
¤ HistorySweeperLight.dll v.0.95.9.0 [5 Sep 2018 18:35:40] - History sweeper light 
¤ ICQ.dll v.0.95.9.0 [5 Sep 2018 18:35:38] - IcqOscarJ protocol 
¤ Import.dll v.0.95.9.0 [5 Sep 2018 18:35:42] - Import contacts and messages 
¤ Jabber.dll v.0.95.9.0 [5 Sep 2018 18:36:04] - Jabber protocol 
¤ MirOTR.dll v.0.95.9.0 [5 Sep 2018 18:37:06] - Miranda OTR 
¤ MobileState.dll v.0.95.9.0 [5 Sep 2018 18:36:12] - Mobile state 
¤ mTextControl.dll v.0.95.9.0 [5 Sep 2018 18:35:42] - Miranda text control 
¤ NewEventNotify.dll v.0.95.9.0 [5 Sep 2018 18:35:58] - NewEventNotify 
¤ NewXstatusNotify.dll v.0.95.9.0 [5 Sep 2018 18:35:44] - xStatus notify 
¤ PluginUpdater.dll v.0.95.9.0 [5 Sep 2018 18:36:08] - Plugin updater 
¤ Popup.dll v.0.95.9.0 [5 Sep 2018 18:35:46] - Popup plus 
¤ Restart.dll v.0.95.9.0 [5 Sep 2018 18:36:08] - Restart 
¤ SecureIM.dll v.0.95.9.0 [5 Sep 2018 18:35:48] - SecureIM 
¤ SmileyAdd.dll v.0.95.9.0 [5 Sep 2018 18:36:12] - SmileyAdd 
¤ StatusManager.dll v.0.95.9.0 [5 Sep 2018 18:36:42] - Status manager 
¤ TabSRMM.dll v.0.95.9.0 [5 Sep 2018 18:35:40] - TabSRMM 
¤ Tipper.dll v.0.95.9.0 [5 Sep 2018 18:35:46] - Tipper 
¤ TopToolBar.dll v.0.95.9.0 [5 Sep 2018 18:35:54] - TopToolBar 

Loaded Modules:
-------------------------------------------------------------------------------
C:\Program Files\Miranda NG\Miranda64.exe  0000000140000000 - 000000014000C000 v.0.95.9.0 [5 Sep 2018 18:35:28]
C:\WINDOWS\SYSTEM32\ntdll.dll  00007FFB35990000 - 00007FFB35B71000 v.10.0.17134.254 [9 Aug 2018 7:53:50]
C:\WINDOWS\System32\KERNEL32.DLL  00007FFB35360000 - 00007FFB35412000 v.10.0.17134.1 [12 Apr 2018 2:34:40]
C:\WINDOWS\System32\KERNELBASE.dll  00007FFB31DE0000 - 00007FFB32053000 v.10.0.17134.165 [6 Jul 2018 10:25:54]
C:\WINDOWS\System32\USER32.dll  00007FFB332A0000 - 00007FFB33430000 v.10.0.17134.1 [12 Apr 2018 2:34:14]
C:\WINDOWS\System32\win32u.dll  00007FFB31DC0000 - 00007FFB31DE0000 v.10.0.17134.1 [12 Apr 2018 2:34:12]
C:\WINDOWS\System32\GDI32.dll  00007FFB34F10000 - 00007FFB34F38000 v.10.0.17134.285 [31 Aug 2018 6:42:27]
C:\WINDOWS\System32\gdi32full.dll  00007FFB32C80000 - 00007FFB32E12000 v.10.0.17134.285 [31 Aug 2018 10:42:49]
C:\WINDOWS\System32\msvcp_win.dll  00007FFB32160000 - 00007FFB321FF000 v.10.0.17134.137 [15 Jun 2018 8:08:14]
C:\WINDOWS\System32\ucrtbase.dll  00007FFB32060000 - 00007FFB3215A000 v.10.0.17134.254 [9 Aug 2018 7:54:11]
C:\WINDOWS\System32\SHELL32.dll  00007FFB33710000 - 00007FFB34B50000 v.10.0.17134.228 [3 Aug 2018 11:39:15]
C:\WINDOWS\System32\msvcrt.dll  00007FFB331F0000 - 00007FFB3328E000 v.7.0.17134.1 [12 Apr 2018 2:34:20]
C:\WINDOWS\System32\cfgmgr32.dll  00007FFB32200000 - 00007FFB32249000 v.10.0.17134.1 [12 Apr 2018 2:34:22]
C:\WINDOWS\System32\shcore.dll  00007FFB33430000 - 00007FFB334D9000 v.10.0.17134.112 [8 Jun 2018 12:29:20]
C:\WINDOWS\System32\RPCRT4.dll  00007FFB34B50000 - 00007FFB34C74000 v.10.0.17134.112 [8 Jun 2018 12:29:15]
C:\WINDOWS\System32\combase.dll  00007FFB34F60000 - 00007FFB35283000 v.10.0.17134.112 [8 Jun 2018 12:30:08]
C:\WINDOWS\System32\bcryptPrimitives.dll  00007FFB32300000 - 00007FFB3237A000 v.10.0.17134.285 [31 Aug 2018 6:42:44]
C:\WINDOWS\System32\windows.storage.dll  00007FFB32380000 - 00007FFB32A8D000 v.10.0.17134.285 [31 Aug 2018 6:42:51]
C:\WINDOWS\System32\advapi32.dll  00007FFB334E0000 - 00007FFB33581000 v.10.0.17134.1 [12 Apr 2018 2:34:44]
C:\WINDOWS\System32\sechost.dll  00007FFB34DC0000 - 00007FFB34E1B000 v.10.0.17134.1 [12 Apr 2018 2:34:22]
C:\WINDOWS\System32\shlwapi.dll  00007FFB32FC0000 - 00007FFB33011000 v.10.0.17134.1 [12 Apr 2018 2:34:33]
C:\WINDOWS\System32\kernel.appcore.dll  00007FFB31D40000 - 00007FFB31D51000 v.10.0.17134.112 [8 Jun 2018 12:29:20]
C:\WINDOWS\System32\profapi.dll  00007FFB31CA0000 - 00007FFB31CBF000 v.10.0.17134.1 [12 Apr 2018 2:34:22]
C:\WINDOWS\System32\powrprof.dll  00007FFB31CE0000 - 00007FFB31D2C000 v.10.0.17134.1 [12 Apr 2018 2:34:22]
C:\WINDOWS\System32\FLTLIB.DLL  00007FFB31D30000 - 00007FFB31D3A000 v.10.0.17134.1 [12 Apr 2018 2:34:22]
C:\WINDOWS\System32\IMM32.DLL  00007FFB35330000 - 00007FFB3535D000 v.10.0.17134.1 [12 Apr 2018 2:34:24]
C:\Program Files\Miranda NG\libs\ucrtbase.dll  00007FFAF4950000 - 00007FFAF4A44000 v.10.0.10586.15 [25 May 2017 13:43:38]
C:\Program Files\Miranda NG\libs\VCRUNTIME140.dll  00007FFB23890000 - 00007FFB238A6000 v.14.11.25325.0 [25 May 2017 13:43:38]
C:\Program Files\Miranda NG\libs\mir_app.mir  00000000128C0000 - 00000000129B0000 v.0.95.9.20729 [5 Sep 2018 18:35:28]
C:\WINDOWS\System32\WS2_32.dll  00007FFB33180000 - 00007FFB331EC000 v.10.0.17134.1 [12 Apr 2018 2:34:22]
C:\WINDOWS\System32\COMDLG32.dll  00007FFB34E20000 - 00007FFB34F0D000 v.10.0.17134.1 [12 Apr 2018 2:34:33]
C:\WINDOWS\System32\ole32.dll  00007FFB33020000 - 00007FFB33171000 v.10.0.17134.137 [15 Jun 2018 20:50:07]
C:\WINDOWS\SYSTEM32\WINMM.dll  00007FFB2FD30000 - 00007FFB2FD53000 v.10.0.17134.1 [12 Apr 2018 2:34:04]
C:\WINDOWS\SYSTEM32\UxTheme.dll  00007FFB301E0000 - 00007FFB30278000 v.10.0.17134.1 [12 Apr 2018 2:34:36]
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.17134.285_none_fb4297e330656775\COMCTL32.dll  00007FFB255A0000 - 00007FFB25809000 v.6.10.17134.285 [31 Aug 2018 10:42:04]
C:\Program Files\Miranda NG\libs\FreeImage.mir  0000000012000000 - 00000000120B7000 [5 Sep 2018 18:35:22]
C:\Program Files\Miranda NG\libs\mir_core.mir  0000000012AA0000 - 0000000012ACF000 v.0.95.9.20729 [5 Sep 2018 18:35:08]
C:\WINDOWS\SYSTEM32\WINMMBASE.dll  00007FFB2F9C0000 - 00007FFB2F9EA000 v.10.0.17134.1 [12 Apr 2018 2:34:04]
C:\WINDOWS\SYSTEM32\Secur32.dll  00007FFB23190000 - 00007FFB2319C000 v.10.0.17134.1 [12 Apr 2018 2:34:32]
C:\WINDOWS\SYSTEM32\VERSION.dll  00007FFB24860000 - 00007FFB2486A000 v.10.0.17134.1 [12 Apr 2018 2:34:34]
C:\Program Files\Miranda NG\libs\zlib.mir  0000000012D40000 - 0000000012D5D000 v.1.2.11.0 [5 Sep 2018 18:35:06]
C:\WINDOWS\SYSTEM32\WTSAPI32.dll  00007FFB2E960000 - 00007FFB2E973000 v.10.0.17134.1 [12 Apr 2018 2:34:37]
C:\Program Files\Miranda NG\libs\MSVCP140.dll  00007FFAF9B50000 - 00007FFAF9BEF000 v.14.11.25325.0 [25 May 2017 13:43:38]
C:\WINDOWS\SYSTEM32\SSPICLI.DLL  00007FFB31BA0000 - 00007FFB31BD0000 v.10.0.17134.1 [12 Apr 2018 2:34:23]
C:\WINDOWS\System32\MSCTF.dll  00007FFB33590000 - 00007FFB33705000 v.10.0.17134.285 [31 Aug 2018 10:43:10]
C:\WINDOWS\System32\OLEAUT32.dll  00007FFB35430000 - 00007FFB354F2000 v.10.0.17134.48 [28 Apr 2018 7:29:30]
C:\WINDOWS\SYSTEM32\dwmapi.dll  00007FFB30430000 - 00007FFB30459000 v.10.0.17134.1 [12 Apr 2018 2:34:20]
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL  00007FFB31690000 - 00007FFB3169B000 v.10.0.17134.1 [12 Apr 2018 2:34:20]
C:\WINDOWS\System32\clbcatq.dll  00007FFB35290000 - 00007FFB35330000 v.2001.12.10941.16384 [12 Apr 2018 2:34:20]
C:\WINDOWS\system32\explorerframe.dll  00007FFB15900000 - 00007FFB15D95000 v.10.0.17134.1 [12 Apr 2018 2:34:35]
C:\WINDOWS\System32\TextInputFramework.dll  00007FFB19D60000 - 00007FFB19DF7000 v.10.0.17134.191 [14 Jul 2018 7:18:18]
C:\WINDOWS\System32\CoreMessaging.dll  00007FFB2FD60000 - 00007FFB2FE3A000 v.10.0.17134.285 [31 Aug 2018 6:42:15]
C:\WINDOWS\System32\CoreUIComponents.dll  00007FFB2B0E0000 - 00007FFB2B3FE000 v.10.0.17134.112 [8 Jun 2018 12:29:15]
C:\WINDOWS\SYSTEM32\wintypes.dll  00007FFB2DD80000 - 00007FFB2DECD000 v.10.0.17134.112 [8 Jun 2018 12:30:06]
C:\WINDOWS\SYSTEM32\ntmarta.dll  00007FFB30D90000 - 00007FFB30DC1000 v.10.0.17134.1 [12 Apr 2018 2:34:23]
C:\Program Files\Miranda NG\Plugins\CrashDumper.dll  00000000178D0000 - 00000000178E4000 v.0.1.0.2 [5 Sep 2018 18:36:00]
C:\WINDOWS\SYSTEM32\dbghelp.dll  00007FFB24990000 - 00007FFB24B59000 v.10.0.17134.1 [12 Apr 2018 2:34:22]
C:\WINDOWS\SYSTEM32\dbgcore.DLL  00007FFB24720000 - 00007FFB24749000 v.10.0.17134.1 [12 Apr 2018 2:34:22]
C:\Program Files\Miranda NG\Plugins\Dbx_mdbx.dll  0000000017BD0000 - 0000000017BE6000 v.0.95.9.1 [5 Sep 2018 18:36:56]
C:\Program Files\Miranda NG\libs\libmdbx.mir  00000000127C0000 - 00000000127EB000 [5 Sep 2018 18:36:50]
C:\Program Files\Miranda NG\Plugins\Dbx_mmap.dll  0000000017C10000 - 0000000017C23000 v.0.95.8.1 [5 Sep 2018 18:35:34]
C:\Program Files\Miranda NG\Plugins\Import.dll  0000000018B30000 - 0000000018B47000 v.0.95.9.1 [5 Sep 2018 18:35:42]
C:\Program Files\Miranda NG\libs\libjson.mir  0000000012780000 - 0000000012796000 [5 Sep 2018 18:35:34]
C:\Program Files\Miranda NG\libs\sqlite3.mir  0000000012B60000 - 0000000012BE7000 [5 Sep 2018 18:35:36]
C:\Program Files\Miranda NG\Core\stdcrypt.dll  0000000013080000 - 000000001308D000 v.0.95.9.20729 [5 Sep 2018 18:35:12]
C:\Program Files\Miranda NG\Core\stdssl.dll  0000000013180000 - 000000001318A000 v.0.95.9.20729 [5 Sep 2018 18:35:10]
C:\WINDOWS\System32\CRYPT32.dll  00007FFB32A90000 - 00007FFB32C72000 v.10.0.17134.1 [12 Apr 2018 2:34:22]
C:\WINDOWS\System32\MSASN1.dll  00007FFB31CC0000 - 00007FFB31CD2000 v.10.0.17134.1 [12 Apr 2018 2:34:20]
C:\WINDOWS\SYSTEM32\WSOCK32.dll  00007FFB2E630000 - 00007FFB2E639000 v.10.0.17134.1 [12 Apr 2018 2:34:40]
C:\WINDOWS\SYSTEM32\Msftedit.dll  00007FFB0AD20000 - 00007FFB0B059000 v.10.0.17134.112 [8 Jun 2018 11:57:00]
C:\Program Files\Miranda NG\Plugins\Clist_modern.dll  0000000017570000 - 00000000175F3000 v.0.9.1.7 [5 Sep 2018 18:36:00]
C:\WINDOWS\SYSTEM32\MSIMG32.dll  00007FFB25C40000 - 00007FFB25C47000 v.10.0.17134.1 [12 Apr 2018 2:34:23]
C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.0.17134.285_none_3cdc1be3f1f2079c\gdiplus.dll  00007FFAE8490000 - 00007FFAE862A000 v.10.0.17134.285 [31 Aug 2018 10:22:19]
C:\Program Files\Miranda NG\Plugins\AuthState.dll  0000000017250000 - 000000001725A000 v.0.0.2.1 [5 Sep 2018 18:35:34]
C:\Program Files\Miranda NG\Plugins\AVS.dll  0000000017310000 - 0000000017327000 v.0.98.1.1 [5 Sep 2018 18:35:36]
C:\Program Files\Miranda NG\Plugins\CryptoPP.dll  0000000017910000 - 00000000179A6000 v.1.0.4.8 [5 Sep 2018 18:36:56]
C:\Program Files\Miranda NG\Plugins\Dummy.dll  0000000017CD0000 - 0000000017CDC000 v.0.2.0.0 [5 Sep 2018 18:36:34]
C:\Program Files\Miranda NG\Plugins\Fingerprint.dll  0000000017E70000 - 0000000017E8F000 v.0.2.0.1 [5 Sep 2018 18:36:16]
C:\Program Files\Miranda NG\Plugins\historypp.dll  00000000181B0000 - 00000000184BA000 [5 Sep 2018 18:37:16]
C:\WINDOWS\SYSTEM32\winspool.drv  00007FFB25B00000 - 00007FFB25B84000 v.10.0.17134.254 [9 Aug 2018 12:13:15]
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL  00007FFB31240000 - 00007FFB31278000 v.10.0.17134.1 [12 Apr 2018 2:34:23]
C:\WINDOWS\SYSTEM32\PROPSYS.dll  00007FFB2E770000 - 00007FFB2E924000 v.7.0.17134.112 [8 Jun 2018 12:29:34]
C:\WINDOWS\SYSTEM32\bcrypt.dll  00007FFB31800000 - 00007FFB31825000 v.10.0.17134.112 [8 Jun 2018 12:30:03]
C:\WINDOWS\SYSTEM32\RICHED20.DLL  00007FFB03950000 - 00007FFB039E5000 v.5.31.23.1231 [12 Apr 2018 2:34:35]
C:\WINDOWS\SYSTEM32\msls31.dll  00007FFB1A6A0000 - 00007FFB1A6D8000 v.3.10.349.0 [12 Apr 2018 2:34:34]
C:\WINDOWS\SYSTEM32\USP10.dll  00007FFB2D4B0000 - 00007FFB2D4C9000 v.10.0.17134.1 [12 Apr 2018 2:34:24]
C:\Program Files\Miranda NG\Plugins\HistorySweeperLight.dll  00000000188F0000 - 00000000188FB000 v.0.1.0.1 [5 Sep 2018 18:35:40]
C:\Program Files\Miranda NG\Plugins\ICQ.dll  0000000018970000 - 00000000189D9000 v.0.95.8.1 [5 Sep 2018 18:35:38]
C:\Program Files\Miranda NG\Plugins\Jabber.dll  0000000018C30000 - 0000000018CF2000 v.0.11.0.5 [5 Sep 2018 18:36:04]
C:\Program Files\Miranda NG\libs\libaxolotl.mir  0000000012260000 - 0000000012290000 [5 Sep 2018 18:35:46]
C:\Program Files\Miranda NG\libs\LIBEAY32.mir  0000000058750000 - 000000005895F000 v.1.0.2.16 [30 Mar 2018 13:58:20]
C:\WINDOWS\SYSTEM32\DNSAPI.dll  00007FFB31280000 - 00007FFB3133E000 v.10.0.17134.165 [6 Jul 2018 10:26:00]
C:\WINDOWS\System32\NSI.dll  00007FFB35420000 - 00007FFB35428000 v.10.0.17134.1 [12 Apr 2018 2:34:22]
C:\Program Files\Miranda NG\Plugins\MirOTR.dll  00000000190B0000 - 0000000019163000 v.0.14.1.17 [5 Sep 2018 18:37:06]
C:\Program Files\Miranda NG\Plugins\MobileState.dll  0000000019230000 - 0000000019239000 v.0.0.1.6 [5 Sep 2018 18:36:12]
C:\Program Files\Miranda NG\Plugins\mTextControl.dll  00000000194B0000 - 00000000194BC000 v.0.8.0.1 [5 Sep 2018 18:35:42]
C:\Program Files\Miranda NG\Plugins\NewEventNotify.dll  0000000019590000 - 000000001959C000 v.0.2.2.4 [5 Sep 2018 18:35:58]
C:\Program Files\Miranda NG\Plugins\NewXstatusNotify.dll  00000000195F0000 - 0000000019614000 v.1.4.0.12 [5 Sep 2018 18:35:44]
C:\Program Files\Miranda NG\Plugins\PluginUpdater.dll  00000000199B0000 - 00000000199CA000 v.0.2.0.2 [5 Sep 2018 18:36:08]
C:\Program Files\Miranda NG\Plugins\Popup.dll  0000000019A10000 - 0000000019A53000 v.2.1.1.15 [5 Sep 2018 18:35:46]
C:\Program Files\Miranda NG\Plugins\Restart.dll  0000000019C30000 - 0000000019C38000 v.0.0.6.0 [5 Sep 2018 18:36:08]
C:\Program Files\Miranda NG\Plugins\SecureIM.dll  0000000019DD0000 - 0000000019DEA000 v.1.0.12.4 [5 Sep 2018 18:35:48]
C:\Program Files\Miranda NG\Plugins\SmileyAdd.dll  000000001A050000 - 000000001A06E000 v.0.3.1.0 [5 Sep 2018 18:36:12]
C:\Program Files\Miranda NG\libs\Pcre16.mir  0000000012B00000 - 0000000012B1D000 [5 Sep 2018 18:36:02]
C:\Program Files\Miranda NG\Plugins\StatusManager.dll  000000001A1D0000 - 000000001A1F1000 v.1.2.0.4 [5 Sep 2018 18:36:42]
C:\WINDOWS\SYSTEM32\WININET.dll  00007FFB21C40000 - 00007FFB220AE000 v.11.0.17134.254 [9 Aug 2018 7:22:57]
C:\Program Files\Miranda NG\Plugins\TabSRMM.dll  000000001A350000 - 000000001A3E4000 v.3.5.0.12 [5 Sep 2018 18:35:40]
C:\Program Files\Miranda NG\Plugins\Tipper.dll  000000001A490000 - 000000001A4BA000 v.2.1.0.7 [5 Sep 2018 18:35:46]
C:\Program Files\Miranda NG\Plugins\TopToolBar.dll  000000001A570000 - 000000001A581000 v.0.8.0.5 [5 Sep 2018 18:35:54]
C:\Program Files\Miranda NG\Core\stduserinfo.dll  00000000131C0000 - 00000000131D0000 v.0.95.9.20729 [5 Sep 2018 18:35:12]
C:\Program Files\Miranda NG\Core\stdemail.dll  00000000130A0000 - 00000000130A9000 v.0.95.9.20729 [5 Sep 2018 18:35:12]
C:\Program Files\Miranda NG\Core\stdfile.dll  00000000130C0000 - 00000000130D4000 v.0.95.9.20729 [5 Sep 2018 18:35:12]
C:\Program Files\Miranda NG\Core\stdaway.dll  0000000013020000 - 000000001302B000 v.0.95.9.20729 [5 Sep 2018 18:35:12]
C:\WINDOWS\system32\dataexchange.dll  00007FFB15EF0000 - 00007FFB15F48000 v.10.0.17134.1 [12 Apr 2018 2:34:07]
C:\WINDOWS\system32\dcomp.dll  00007FFB2F820000 - 00007FFB2F9BC000 v.10.0.17134.1 [12 Apr 2018 2:34:20]
C:\WINDOWS\system32\d3d11.dll  00007FFB2EF40000 - 00007FFB2F24B000 v.10.0.17134.112 [8 Jun 2018 13:31:54]
C:\WINDOWS\system32\dxgi.dll  00007FFB30A60000 - 00007FFB30B1B000 v.10.0.17134.112 [8 Jun 2018 13:34:40]
C:\WINDOWS\system32\twinapi.appcore.dll  00007FFB30540000 - 00007FFB306F8000 v.10.0.17134.137 [15 Jun 2018 8:09:39]
C:\WINDOWS\system32\RMCLIENT.dll  00007FFB30510000 - 00007FFB30531000 v.10.0.17134.81 [20 May 2018 14:53:07]
C:\Windows\System32\oleacc.dll  00007FFB25A90000 - 00007FFB25AFB000 v.7.2.17134.1 [12 Apr 2018 2:34:32]
C:\Program Files\Miranda NG\icons\secureim_icons.dll  00000000136E0000 - 00000000136E8000 v.1.0.12.4 [5 Sep 2018 18:37:10]
C:\WINDOWS\SYSTEM32\WindowsCodecs.dll  00007FFB2B600000 - 00007FFB2B7AE000 v.10.0.17134.285 [31 Aug 2018 6:42:42]
C:\WINDOWS\system32\mswsock.dll  00007FFB314C0000 - 00007FFB31526000 v.10.0.17134.1 [12 Apr 2018 2:34:22]
C:\WINDOWS\system32\napinsp.dll  00007FFB0DEB0000 - 00007FFB0DEC6000 v.10.0.17134.1 [12 Apr 2018 2:34:40]
C:\WINDOWS\system32\pnrpnsp.dll  00007FFB0DE90000 - 00007FFB0DEAA000 v.10.0.17134.1 [12 Apr 2018 2:33:56]
C:\WINDOWS\system32\NLAapi.dll  00007FFB2E5F0000 - 00007FFB2E609000 v.10.0.17134.1 [12 Apr 2018 2:34:32]
C:\WINDOWS\System32\winrnr.dll  00007FFB20560000 - 00007FFB2056E000 v.10.0.17134.1 [12 Apr 2018 2:34:25]
C:\WINDOWS\System32\wshbth.dll  00007FFB0DE70000 - 00007FFB0DE85000 v.10.0.17134.1 [12 Apr 2018 2:34:12]
C:\Program Files\Bonjour\mdnsNSP.dll  00000000592A0000 - 00000000592C6000 v.3.0.0.10 [30 Aug 2011 23:05:32]
C:\WINDOWS\System32\fwpuclnt.dll  00007FFB284A0000 - 00007FFB28512000 v.10.0.17134.1 [12 Apr 2018 2:34:12]
C:\Windows\System32\rasadhlp.dll  00007FFB276F0000 - 00007FFB276FA000 v.10.0.17134.1 [12 Apr 2018 2:34:33]
C:\WINDOWS\SYSTEM32\schannel.dll  00007FFB30FE0000 - 00007FFB31059000 v.10.0.17134.165 [6 Jul 2018 9:57:47]
C:\WINDOWS\SYSTEM32\mskeyprotect.dll  00007FFB22690000 - 00007FFB226A4000 v.10.0.17134.1 [12 Apr 2018 2:34:06]
C:\WINDOWS\SYSTEM32\ncrypt.dll  00007FFB317D0000 - 00007FFB317F6000 v.10.0.17134.1 [12 Apr 2018 2:34:22]
C:\WINDOWS\SYSTEM32\NTASN1.dll  00007FFB31790000 - 00007FFB317C6000 v.10.0.17134.1 [12 Apr 2018 2:34:20]
C:\WINDOWS\system32\ncryptsslp.dll  00007FFB22CD0000 - 00007FFB22CF1000 v.10.0.17134.137 [15 Jun 2018 8:12:58]
C:\Windows\System32\Windows.Globalization.dll  00007FFB17130000 - 00007FFB172B9000 v.10.0.17134.254 [9 Aug 2018 7:28:56]
C:\Windows\System32\Bcp47Langs.dll  00007FFB19D10000 - 00007FFB19D60000 v.10.0.17134.1 [12 Apr 2018 2:34:10]
C:\Windows\System32\bcp47mrm.dll  00007FFB196D0000 - 00007FFB196F9000 v.10.0.17134.1 [12 Apr 2018 2:34:10]
C:\WINDOWS\SYSTEM32\globinputhost.dll  00007FFB1C680000 - 00007FFB1C6AA000 v.10.0.17134.1 [12 Apr 2018 2:34:12]
C:\WINDOWS\System32\coml2.dll  00007FFB34C80000 - 00007FFB34CF3000 v.10.0.17134.1 [12 Apr 2018 2:34:12]
C:\WINDOWS\SYSTEM32\sxs.dll  00007FFB31B00000 - 00007FFB31B9A000 v.10.0.17134.1 [12 Apr 2018 2:34:37]
C:\WINDOWS\SYSTEM32\uiautomationcore.dll  00007FFB0ED00000 - 00007FFB0EF00000 v.7.2.17134.112 [8 Jun 2018 11:55:00]
C:\Windows\System32\OneCoreCommonProxyStub.dll  00007FFB1E2F0000 - 00007FFB1E363000 v.10.0.17134.191 [14 Jul 2018 6:53:05]

**Comment by georgehazan** [comment]
вылетает при закрытии всех вкладок или при закрытии одной вкладки?

**Comment by ilio74** [comment]
В контейнере может быть несколько вкладок, может быт одна. Всегда по разному вылетает. Иногда когда закрываю несколько подряд, то не вылетает совсем.
