### ISSUE TITLE
CmdLine и MimCmd.exe - не срабатывает. (bug)

### ISSUE THREAD

**Issue by BlackSniperV** [miranda-ng/miranda-ng#1598]
Сломалось видимо, посмотрите пожалуйста.

**Comment by georgehazan** [comment]
а что именно не срабатывает?

**Comment by georgehazan** [comment]
вот запустил MimCmd.exe status, получил статусы протоколов.
что конкретно не работает?

**Comment by georgehazan** [comment]
проверил на XP без нифига - всё ok.

**Comment by BlackSniperV** [comment]
Прошу прощение. Команда quit не срабатывает. 
В одном случае появляется окно taskeng.exe и пропадает с информацией о выполненной команды "Выход" , на другом компьютере висит окно без какой либо информации пока его ручками не закроешь. А миранда как работала так и работает.

**Comment by georgehazan** [comment]
скажи планировщику запускать эту команду из-под того же пользователя, который запустил миранду, иначе у него не будет прав на доступ.

**Comment by BlackSniperV** [comment]
> Cкажи планировщику запускать эту команду из-под того же пользователя, который запустил миранду, иначе у него не будет прав на доступ. Cама по себе команда quit работает на ура, только что проверил

Действия
Запускаю миранду ручками по исполняемому файлу
Иду в пуск и запускаю CMD.exe
Ухожу из папки пользователя (C:\Users\dmitry>) cd..  и перехожу в папку миранды 
C:\>cd /d D:\miranda
D:\Miranda>
пишу mimcmd.exe version - вываливается список плагинов
пишу mimcmd.exe status - вываливается список статусов протоколов
пишу mimcmd.exe quit -  Выполнена команда "Выход". но миранда продолжает сидеть в процессах 

Что не так?

**Comment by BlackSniperV** [comment]
Ам... предполагаю, что я что-то не то делаю:
1.Двойной клик ПКМ по miranda32.exe
2.пуск, поиск cmd -> клик ПКМ по cmd
3.Переход из папки учёт.записи в папку миранды.
4.Набираю mimcmd.exe status - показывает.
5. mimcmd.exe version -  показывает.
6. mimcmd.exe help - показывает.
7. mimcmd.exe quit -  пишет, команда исполнена, но ничего не происходит.

Позже, сделал то же самое но миранду и cmd запустил с правами администратора. А результат один в один. 
![mim](https://user-images.githubusercontent.com/42166967/46302841-e9abc880-c5b2-11e8-871a-49f4799e01e5.gif)

**Comment by dartraiden** [comment]
У меня quit работает.

**Comment by georgehazan** [comment]
даже не знаю... там плагин открывает область шареной памяти, куда утилька из командной строки присасывается и посылает команду. может это терминальный сервер с кучкой запущенных миранд? :) и он посылает команду в первую попавшуюся? хотя нет, вроде статус распечатывается из твоей миранды, да? пока нет вариантов, может быть сделать нетворк лог и посмотреть, нет ли там чего?

**Comment by dartraiden** [comment]
@BlackSniperV 
Покажите выхлоп Главное мекню → Версии → Копировать в буфер обмена

**Comment by BlackSniperV** [comment]
[spoiler=VersionInfo][quote]CPU: Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz [Intel64 Family 6 Model 42 Stepping 7] [DEP Enabled] [8 CPUs]
Installed RAM: 16282 MBytes
Microsoft Windows 7 Enterprise Edition, 64-bit Service Pack 1 (build 7601)
Internet Explorer: 9.11.9600.19129 (build 99600)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian
Free disk space on Miranda partition: 90087 MBytes

Miranda NG Version: 0.95.10 alpha build #20792 (c85ac94a32) [running inside WOW64]
Build time: 1 Oct 2018 2:00:34
Profile: E:\Dropbox\Miranda\Profiles\BlackSniper\BlackSniper.dat
Profile size: 33783808 Bytes
Profile creation date: 15 May 2018 18:31:47
Language pack: Russian (RU) [0419]
Service Mode: No

[b]Active Plugins (70):[/b]
¤ Actman.dll v.[b]0.3.0.1[/b] [5 Sep 2018 19:10:48] - Action manager 
¤ AddContactPlus.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:36] - Add contact+ 
¤ Alarms.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:32] - Alarms 
¤ AssocMgr.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:56] - File association manager 
¤ AuthState.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:16] - Authorization state 
¤ AutoRun.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:56] - AutoRun 
¤ AutoShutdown.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:56] - Auto shutdown 
¤ AvatarHistory.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:58] - Avatar history 
¤ AVS.dll v.[b]0.95.10.0[/b] [22 Sep 2018 2:00:38] - Avatar service 
¤ BASS_interface.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:56] - BASS Interface 
¤ BuddyExpectator.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:18] - Buddy expectator 
¤ ChangeKeyboardLayout.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:36] - Change keyboard layout 
¤ ClientChangeNotify.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:40] - Client change notify 
¤ Clist_nicer.dll v.[b]0.95.10.0[/b] [22 Sep 2018 2:00:42] - Clist nicer 
¤ Cln_skinedit.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:16] - Skin editor for Clist nicer 
¤ CmdLine.dll v.[b]0.95.10.0[/b] [1 Oct 2018 2:01:00] - Command line 
¤ CrashDumper.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:46] - Crash dumper 
¤ CSList.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:22] - Custom status list 
¤ Db_autobackups.dll v.[b]0.95.10.0[/b] [1 Oct 2018 2:00:44] - Db autobackuper 
¤ DbEditorPP.dll v.[b]0.95.10.0[/b] [24 Sep 2018 2:01:40] - Database editor++ 
¤ Dbx_mdbx.dll v.[b]0.95.10.0[/b] [1 Oct 2018 2:01:56] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.[b]0.95.10.0[/b] [1 Oct 2018 2:00:38] - Miranda NG mmap database driver 
¤ Discord.dll v.[b]0.95.10.0[/b] [22 Sep 2018 2:01:46] - Discord protocol 
¤ Dummy.dll v.[b]0.95.10.0[/b] [1 Oct 2018 2:01:34] - Dummy protocol 
¤ Facebook.dll v.[b]0.95.10.0[/b] [22 Sep 2018 2:01:06] - Facebook 
¤ FavContacts.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:24] - Favorite contacts 
¤ FileAsMessage.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:10:24] - File as message 
¤ Fingerprint.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:54] - Fingerprint NG 
¤ Flags.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:18] - Country flags 
¤ FltContacts.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:28] - Floating contacts 
¤ Folders.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:24] - Custom profile folders 
¤ historypp.dll v.[b]1.5.1.5[/b] [5 Sep 2018 19:10:52] - History++ 
¤ ICQ.dll v.[b]0.95.10.0[/b] [22 Sep 2018 2:00:46] - IcqOscarJ protocol 
¤ IgnoreState.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:24] - Ignore state 
¤ Import.dll v.[b]0.95.10.0[/b] [1 Oct 2018 2:01:06] - Import contacts and messages 
¤ Jabber.dll v.[b]0.95.10.0[/b] [22 Sep 2018 2:01:20] - Jabber protocol 
¤ LinkList.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:28] - History linklist plus 
¤ MenuEx.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:26] - Menu item ext 
¤ MirandaG15.dll v.[b]0.95.10.0[/b] [22 Sep 2018 2:01:44] - MirandaG15 
¤ MirFox.dll v.[b]0.95.10.0[/b] [22 Sep 2018 2:01:40] - MirFox 
¤ MirOTR.dll v.[b]0.95.10.0[/b] [22 Sep 2018 2:02:16] - Miranda OTR 
¤ MRA.dll v.[b]0.95.10.0[/b] [22 Sep 2018 2:00:58] - Mail.ru Agent 
¤ Msg_Export.dll v.[b]0.95.10.0[/b] [22 Sep 2018 2:01:14] - Message export 
¤ MsgPopup.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:10:00] - Message popup 
¤ mTextControl.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:28] - Miranda text control 
¤ NewAwaySys.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:10:12] - New Away System Mod 
¤ NewEventNotify.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:42] - NewEventNotify 
¤ NewsAggregator.dll v.[b]0.95.10.0[/b] [22 Sep 2018 2:01:16] - News aggregator 
¤ NewXstatusNotify.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:26] - xStatus notify 
¤ Nudge.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:24] - Nudge 
¤ PluginUpdater.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:50] - Plugin updater 
¤ PManagerEx.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:48] - Miranda NG profile changer 
¤ Popup.dll v.[b]0.95.10.0[/b] [22 Sep 2018 2:00:52] - Popup plus 
¤ QuickMessages.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:26] - Quick messages 
¤ QuickSearch.dll v.[b]1.4.2.0[/b] [5 Sep 2018 19:10:50] - Quick Search 
¤ Scriver.dll v.[b]0.95.10.0[/b] [28 Sep 2018 2:00:48] - Scriver 
¤ SeenPlugin.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:28] - Last seen 
¤ SendSS.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:48] - Send ScreenShot+ 
¤ ShlExt.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:10:08] - Shell extension 
¤ SmileyAdd.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:48] - SmileyAdd 
¤ SpellChecker.dll v.[b]0.95.10.0[/b] [22 Sep 2018 2:01:40] - Spell checker 
¤ StatusManager.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:10:24] - Status manager 
¤ StopSpamMod.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:56] - StopSpam mod 
¤ Tipper.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:30] - Tipper 
¤ TopToolBar.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:38] - TopToolBar 
¤ UInfoEx.dll v.[b]0.95.10.0[/b] [22 Sep 2018 2:01:04] - User info ext 
¤ Variables.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:44] - Variables 
¤ VKontakte.dll v.[b]0.95.10.0[/b] [25 Sep 2018 2:01:50] - VKontakte protocol 
¤ Weather.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:54] - Weather 
¤ WhenWasIt.dll v.[b]0.95.10.0[/b] [5 Sep 2018 19:09:32] - Birthday reminder 

[b]Weather ini files:[/b]
-------------------------------------------------------------------------------
 Accu-Intl-XML.ini v.[b]0.0.6.0[/b] [6 Mar 2013 6:37:28] - AccuWeather Intl
 gismeteo.ini v.[b]2012.05.03[/b] [12 Aug 2017 11:23:46] - GisMeteo
 msn.ini v.[b]2014-11-08[/b] [12 Aug 2017 11:23:46] - MSN Weather (New Layout)
 weatherxml.ini v.[b]0.0.5.3 2009-07-16[/b] [12 Aug 2017 11:23:46] - WeatherXML
 wundergrnd_intl.ini v.[b]2011/02/13[/b] [12 Aug 2017 11:23:46] - Weather Underground Int'l
 wundergrnd_xml.ini v.[b]2011/02/13[/b] [12 Aug 2017 11:23:46] - Weather Underground XML

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
Discord                  0 - Enabled 1 - Disabled  Loaded
ICQ                      1 - Enabled 2 - Disabled  Loaded
JABBER                   0 - Enabled 7 - Disabled  Loaded
MRA                      2 - Enabled 0 - Disabled  Loaded
VKontakte                0 - Enabled 1 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 3DMata Jabber.dll [4 Feb 2005 14:10:34]
 colour_schemes.dll [6 Aug 2011 12:00:46]
 flags.dll [27 Oct 2007 21:33:00]
 Flags_icons.dll [22 Sep 2018 2:02:18]
 Fp_icons.dll [5 Sep 2018 19:10:48]
 HistoryPP_icons.dll [5 Sep 2018 19:10:46]
 Icons.7z [18 Jul 2012 10:48:50]
 jabber-smile.dll [10 Mar 2005 11:42:56]
 jabber_xstatus.dll [26 Mar 2008 22:22:36]
 Mra.dll [21 Jun 2012 9:10:28]
 mugzLESS_32bit.dll [27 May 2001 5:13:46]
 nudge.dll [21 Jun 2012 9:14:47]
 Proto_AIM.dll [12 Dec 2017 4:06:28]
 proto_conn.dll [3 Jul 2013 18:42:48]
 proto_conn_icq.dll [3 Jul 2013 18:42:48]
 proto_conn_jabber.dll [3 Jul 2013 18:42:48]
 proto_conn_MRA.dll [3 Jul 2013 18:42:48]
 proto_conn_ok.dll [3 Jul 2013 18:42:48]
 proto_conn_skype.dll [3 Jul 2013 18:42:48]
 proto_conn_yandex.dll [13 Jan 2014 9:50:55]
 Proto_CurrencyRates.dll [1 Aug 2018 11:04:02]
 Proto_Discord.dll [22 Sep 2018 2:02:20]
 Proto_Dropbox.dll [14 Nov 2017 4:20:56]
 Proto_Dummy.dll [1 Oct 2018 2:02:10]
 Proto_Facebook.dll [22 Sep 2018 2:02:18]
 Proto_GG.dll [12 Jul 2018 2:02:22]
 proto_GmailMNotifier.dll [8 Mar 2008 23:01:30]
 proto_gtalk.dll [12 Sep 2011 14:29:12]
 proto_icons_irc_smileys_xp.dll [3 Feb 2005 23:43:50]
 Proto_ICQ.dll [22 Sep 2018 2:02:18]
 Proto_IRC.dll [22 Sep 2018 2:02:18]
 Proto_Jabber.dll [22 Sep 2018 2:02:18]
 Proto_MetaContacts.dll [1 Oct 2018 2:02:10]
 Proto_MRA.dll [22 Sep 2018 2:02:18]
 Proto_mRadio.dll [24 Oct 2017 9:17:28]
 Proto_MSN.dll [22 Sep 2018 2:02:18]
 Proto_NewsAggregator.dll [22 Sep 2018 2:02:18]
 proto_odnoklassniki.dll [10 May 2010 20:56:06]
 Proto_Omegle.dll [24 Oct 2017 9:17:28]
 Proto_Sametime.dll [24 Oct 2017 9:17:30]
 Proto_Skype.dll [24 Oct 2017 9:17:30]
 Proto_Steam.dll [24 Oct 2017 9:17:30]
 Proto_Tlen.dll [24 Oct 2017 9:17:28]
 Proto_Tox.dll [24 Oct 2017 9:17:30]
 Proto_Twitter.dll [24 Oct 2017 9:17:28]
 Proto_VKontakte.dll [25 Sep 2018 2:02:28]
 Proto_Weather.dll [5 Sep 2018 19:10:46]
 Proto_Yahoo.dll [16 Jun 2015 12:01:58]
 Proto_YAMN.dll [24 Oct 2017 9:17:28]
 proto_yandex.dll [13 Jan 2014 9:57:39]
 randyicons_2k_set1.dll [9 Feb 2005 1:09:04]
 randyicons_XP_set2.dll [9 Feb 2005 1:09:30]
 SecureIM_icons.dll [17 Jan 2018 17:01:16]
 smileyadd.dll [26 Apr 2005 20:22:12]
 TabSRMM_icons.dll [25 Sep 2018 2:02:28]
 Toolbar_icons.dll [22 Sep 2018 2:02:18]
 tzers_icons.dll [21 Mar 2009 23:42:22]
 UInfoEx_icons.dll [22 Sep 2018 2:02:18]
 useactions_icons.dll [3 Jun 2010 23:44:20]
 Vista_Gtalk.dll [3 Dec 2008 0:44:28]
 Vista_IRC.dll [17 Dec 2008 22:47:36]
 Vista_Jabber.dll [3 Dec 2008 0:08:56]
 Vista_Weather.dll [17 Jan 2009 16:06:44]
 Watrack_buttons.dll [16 Jun 2015 12:07:46]
 Watrack_icons.dll [16 Jun 2015 12:07:46]
 weather.dll [27 Nov 2002 18:00:20]
 xstatus_icons.dll [10 Dec 2007 8:51:36]
 xStatus_ICQ.dll [22 Sep 2018 2:02:18]
 xStatus_Jabber.dll [22 Sep 2018 2:02:18]
 xStatus_MRA.dll [22 Sep 2018 2:02:18]
[/quote][/spoiler]

**Comment by dartraiden** [comment]
С clist_nicer эта команда почему-то не работает.

**Comment by BlackSniperV** [comment]
> С clist_nicer эта команда почему-то не работает.

Может имеет значение. но замечено было что пару раз после выполнения quit clist_nicer становится как бы не прорисовавшимся

**Comment by BlackSniperV** [comment]
> может быть сделать нетворк лог и посмотреть, нет ли там чего?
Если это не мысли в слух, то мне нужно знать что помечать в журнале.

**Comment by dartraiden** [comment]
Исправлено в https://github.com/miranda-ng/miranda-ng/commit/5f67ffc4042f36532474c8d8dbae9b65f736fb2a

**Comment by BlackSniperV** [comment]
Спасибо

**Comment by georgehazan** [comment]
запустил ночник строиться с этим фиксом, скоро будет
