### ISSUE TITLE
Crash: Simple Status Message

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#160]
**Reported by BasiL on 1 Feb 2013 07:16 UTC**
Simple Status Message crashed with unknown reason after startup of miranda32.exe

[Simple Status Message.ZIP](https://github.com/miranda-ng/miranda-ng/files/644765/Simple.Status.Message.ZIP)

**Comment by georgehazan** [comment]
**Comment by watcher on 30 Mar 2013 20:46 UTC**
Does it still crashes? Please reply.

**Comment by georgehazan** [comment]
**Modified by mataes on 27 May 2014 04:01 UTC**

**Comment by LittleVulpix** [comment]
This should be closed as no responses have been provided and the crash couldn't be reproduced + the bug is quite old. New ticket can be logged if it happens again.
