### ISSUE TITLE
IRC connecting but never online

### ISSUE THREAD

**Issue by XP-Fan** [miranda-ng/miranda-ng#1604]
When I am connecting to the IRC-Server of whappirc (an whatsapp web/IRC-Gateway), Miranda NG doesn't get that it is online. It always says connecting, thus it is possible to receive messages, but not to send anything, which sucks.

**Comment by georgehazan** [comment]
attach a network log, please
https://wiki.miranda-ng.org/index.php?title=Network_log

**Comment by XP-Fan** [comment]
Well yeah, this would contain my password wouldn't it?

**Comment by georgehazan** [comment]
> Well yeah, this would contain my password wouldn't it?

you can remove it from that file. Otherwise I cannot understand what's going on

**Comment by XP-Fan** [comment]
Allright, but I would then prefer to give you the file privately.

**Comment by georgehazan** [comment]
sure. email it to ghazan at miranda point im.

**Comment by dartraiden** [comment]
Duplicate of #719

**Comment by lieuwex** [comment]
FWIW the issue for connecting has been fixed at whapp-irc's side (I didn't send a MOTD, sorry). 

https://github.com/lieuwex/whapp-irc/issues/28 is the discussion on my side about whapp-irc <-> miranda-ng compatibility issues.
