### ISSUE TITLE
Scriver молча обрезает слишком длинные сообщений

### ISSUE THREAD

**Issue by Null-Kelvin** [miranda-ng/miranda-ng#1605]
Ожидаемое поведение:
1. Уведомление об ошибке "Текст слишком длинный"
2. Автоматическая нарезка на кусочки и отправка их отдельными сообщениями

Реальное поведение:
В историю попадает полное отправленное сообщение, другая сторона получает первые 4000 (зависит от протокола) символов этого сообщения

Идеально было бы если бы текст нарезался порциями, размер которых можно было бы указать в настройках Scriver.

**Comment by georgehazan** [comment]
для этого есть tabSRMM.
не обязательно любая функциональность будет включаться в тот или иной плагин

**Comment by sss123next** [comment]
Создайте новый тикет как feature-requiest а не как баг.

**Comment by Null-Kelvin** [comment]
Не-не-не, погодите! :)
Scriver никак не предупреждает о том, что сообщение длиннее чем допустимо для протокола, а отправляет то что сможет и на этом успокаивается.
Мечту о том, чтобы делить текст равными порциями как-то иначе, а не отдавать автоматике TabSRMM (которая еще в Miranda IM была помечена "экспериментально") можно рассматривать только как мечту, но отсутствие предупреждений от Scriver это же явно баг.

**Comment by dartraiden** [comment]
Думаю, что пометку "экспериментально" можно убрать, эксперимент несколько подзатянулся.

Таким образом, нужно выяснить, Scriver ли не умеет принимать от протокола "ой, у тебя слишком большое" или же протокол не передаёт SRMM-модулю нужную информацию. О каком протоколе идёт речь?

**Comment by apollo2k4** [comment]
> Таким образом, нужно выяснить, Scriver ли не умеет принимать от протокола "ой, у тебя слишком большое" или же протокол не передаёт SRMM-модулю нужную информацию.
Хорошо бы понимать умеют ли протоколы это.

**Comment by Null-Kelvin** [comment]
Как я понял, максимальный размер сообщения захардкожен где-то в самой миранде, а не запрашивается при отправке сообщения. Я тестил на Jabber и TOX - у первого TabSRMM показывает всплывающее окошко если сообщение больше 4000 символов, у второго - что-то в районе 1300 символов.
Scriver ни о чем не предупреждает, просто шлет что получится. У меня в хистори отображается сообщение целиком, а у принимающей стороны - сколько послалось.

**Comment by georgehazan** [comment]
протокол умеет информировать о максимальной длине сообщения, да
