### ISSUE TITLE
MRA отваливается по таймауту

### ISSUE THREAD

**Issue by BlackSniperV** [miranda-ng/miranda-ng#1609]
Два или три дня назад началось. Соединяется, а потом разъеденяется с сообщением 

[9:10:24 16B0] w:\miranda-build\src\mir_app\src\netlibopenconn.cpp 718: connect() failed (1460)
[9:10:24 16B0] Error happened: Can't connect to MRIM server, error 1460: Возврат из операции произошел из-за превышения времени ожидания.

https://forum.miranda-ng.org/index.php?topic=5361.msg22313#msg22313

**Comment by dartraiden** [comment]
> - Сегодня отказывается соединятся версия 6.2.7313,  кто пользуется у всех так ? 10 версия соединяется
> -- попробовал зайти десятой версией, все работает, пишут что они еще в августе предупреждали что закроют поддержку старых версий агента
> ---вычитал на просторах инета, что если зайти через любой anon-vpn то все работает на старых версиях, типа они для России прикрыли, а для других стран все работае

**Comment by georgehazan** [comment]
переставил порт на 443 - влетело на ура и работает. 
есть мнение, что проблемы начались только с портом 2402

**Comment by Dionis78** [comment]
Перепробовал все порты. Не работает.

**Comment by georgehazan** [comment]
см #1614
