### ISSUE TITLE
[0.95.9.1 x64] Caught a crash (Tox?)

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#1610]
I can't say what causes it, as it appears to be random. It also happens every time Tox tries to connect while internet connection is offline, as well as when I try to set Tox account to offline while it's still in the process of connecting.

This is a regression, as these crashes started happening only recently.

Here's the log with debug symbols. Version is 0.95.9.1 stable. The earliest version that crashed for me was Miranda NG Version: 0.95.9 build 20730 (ddf79e069e) x64

```
See next post for proper debug log.
```

**Comment by dartraiden** [comment]
> filename not available = no debug symbols

**Comment by Tharn** [comment]
Fff.. I had it set to 'stable version with debug symbols'. If this doesn't work, then the option doesn't work. I'm getting dev version and we'll see where we're at.
