### ISSUE TITLE
свалилась в  MRA.

### ISSUE THREAD

**Issue by BLF0x** [miranda-ng/miranda-ng#1613]
Упала сама по себе. Единожды при наборе и отправке текста в MRA.
Часть дампа прилагаю (полный нужен ?):
-------------
Miranda Crash Report from 9 Oct 2018 20:26:28. Crash Dumper v.0.1.0.2

Likely cause of the crash plugin: Miranda NG

Exception: Access Violation at address 00929500. Reading from address 0192B000.

Stack Trace:
---------------------------------------------------------------
00929500 (ucrtbase 008F0000): (filename not available) (0): wcsnlen
0091A5CF (ucrtbase 008F0000): (filename not available) (0): iswctype
0091AC8C (ucrtbase 008F0000): (filename not available) (0): iswctype
0091CF7D (ucrtbase 008F0000): (filename not available) (0): __lc_locale_name_func
0091ADAF (ucrtbase 008F0000): (filename not available) (0): _stdio_common_vsprintf
1270B065 (mir_app 126C0000): (filename not available) (0): Ordinal79
0547CA1F (MRA 05470000): (filename not available) (0): (function-name not available)

CPU: Intel(R) Core(TM)2 Duo CPU E7400 @ 2.80GHz [x86 Family 6 Model 23 Stepping 10] [2 CPUs]
Installed RAM: 5120 MBytes
Microsoft Windows XP Professional Service Pack 3 (build 2600)
Internet Explorer: 8.0.6001.18702 (build 86001)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian

Miranda NG Version: 0.95.9.1 build #20739 (567376b29d)
Build time: 8 Oct 2018 19:57:44
Profile: c:\icq\profiles\7573181\7573181.dat
Language pack: Russian (RU) [0419]
Service Mode: No

**Comment by dartraiden** [comment]
Нужен дамп с отладочными символами.

**Comment by dartraiden** [comment]
Так что, либо ждать, пока исправится https://github.com/miranda-ng/miranda-ng/issues/1611 и потом повторять падение, либо обновиться до девелоперской версии с символами и повторить падение.

**Comment by BLF0x** [comment]
файл .mdmp из crashlog подойдет ? =)

**Comment by dartraiden** [comment]
Нет, с установленными символами будет вместо 0547CA1F (MRA 05470000): (filename not available) (0): (function-name not available) указаны имена исходников и строки, где произошла ошибка. mdmp вообще не нужен.
