### ISSUE TITLE
MRA: Не может соединиться с сервером

### ISSUE THREAD

**Issue by Dionis78** [miranda-ng/miranda-ng#1614]
Проверил разные порты. Не соединяется.
[netlog.txt](https://github.com/miranda-ng/miranda-ng/files/2467321/netlog.txt)

**Comment by dartraiden** [comment]
Да, оно сдохло.

**Comment by dartraiden** [comment]
Назначил блокером, поскольку так или иначе перед следующей стаблей этот баг нужно закрыть: либо переписыванием протокола, либо его похоронами.

**Comment by dartraiden** [comment]
Sorry, but we cannot get MRA working. It requires complete protocol rewriting.
