### ISSUE TITLE
галка "Включить звуки событий" не сохраняет своего значения

### ISSUE THREAD

**Issue by alexeik** [miranda-ng/miranda-ng#1615]
![39e2d-clip-38kb](https://user-images.githubusercontent.com/5046855/46871697-c8f93380-ce3a-11e8-96d8-22761c5a6bd7.png)

Ребят, галка "Включить звуки событий" не сохраняет своего значения , если в окне звуков стоит где-нибудь галка.
Поэтому нельзя октлючить все звуки этой галкой.
ПРи перезагрузке миранды, галка снова там появится.
Глюк короче и туда и обратно.
На последней стабильной выплыло.

**Comment by dartraiden** [comment]
Попробуйте в редакторе базы пройти в раздел [Skin] и убить там настройку "UseSound".

**Comment by alexeik** [comment]
имелось ввиду, что если снять галку , то звуки останутся, те которые помечены своими галками.

**Comment by dartraiden** [comment]
Это так и задумано.

**Comment by dartraiden** [comment]
Создал #1617

**Comment by alexeik** [comment]
Так, послушайте.
Вроде если я снимаю галку "Включить звуки событий" то звуки должны отключится.
В данном же случае, при снятии звуки остаются.

**Comment by alexeik** [comment]
не понятно , что имелось ввиду под ночью и утром.

**Comment by georgehazan** [comment]
на ночь звуки выключаются, или на время работы. потом они включаются, а звуковая схема улетела?
