### ISSUE TITLE
Dynamically loaded not in plugin list

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#162]
**Reported by goraf on 3 Feb 2013 13:43 UTC**
Dynamically loaded plugins aren't in the plugin list until restart.

**Comment by georgehazan** [comment]
**Comment by wishmaster on 22 Jun 2013 09:34 UTC**
I can confirm the issue. The search box is not refreshes when a new plugin is dynamically loaded.

**Comment by Robyer** [comment]
I'm closing this as it has very confusing description and my "accidentally duplicit" issue better explains it #640
