### ISSUE TITLE
Add checkbox for service mode

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1624]
Current behavior: user should leave "Launch in service mode with" blank for normal mode.

![123232321321](https://user-images.githubusercontent.com/5046855/46922374-ec75d700-d010-11e8-9c04-6b6d8854f838.png)

This is confusing. I suggest remove this blank menu item and add checkbox instead for service mode launch

**Comment by georgehazan** [comment]
that's a usual practice both in Windows & Miranda, so I doubt that we need a checkbox.
![image](https://user-images.githubusercontent.com/4628541/47036866-1997c600-d186-11e8-9425-9f499e6ae75e.png)
