### ISSUE TITLE
tabsrmm-> Log status changes

### ISSUE THREAD

**Issue by alexeik** [miranda-ng/miranda-ng#1627]
поясните.
Если эта опция выбрана, то изменения статуса пишется в журнал открытого окна чата.
Чисто визуально подается , что запись о смене статуса ушла в историю. 
Как оказалось это фальшивка. 
Эти сообщения о смене статуса , чисто виртуальные.
А можно их сделать реальными, чтобы я мог посмотреть в истории эти сообщения.

**Comment by alexeik** [comment]
на последней сборке ночной.

**Comment by georgehazan** [comment]
никто и не планировал писать их в базу, они просто показываются в логе событий наряду с другими событиями. далеко не всё то, что пишется в окно лога, живет на самом деле в базе

**Comment by alexeik** [comment]
то есть, так вот, это отказ?
а как же быть то.
ктото умеет писать статусы в историю?
хоть помогли бы советом.

**Comment by georgehazan** [comment]
то есть как это вот? :-) afair никто и не обещал писать эту лабуду в базу, потому что это бессмысленно. воткнет человек себе listeningTo, и у него начнет меняться статус каждые 2 минуты с новой песней. в чем идея записывать всё это? изучить музыкальные пристрастия человека? а если он скрестит это с mRadio?

**Comment by alexeik** [comment]
вообще, просто возникли не понятки.
человек выходит в оффлайн с miranda ng
а потом появляется в онлайне через icq mobile. притом человек реаль ушел. можно писать в онлайн и ничего никуда не придет.
нужно посмотреть статусы , когда по времени меняются.

**Comment by georgehazan** [comment]
проще смотреть на иконку клиента, которая горит внизу справа. там четко будет видно, на миранде или на мобилке он сидит

**Comment by dartraiden** [comment]
Скажите человеку сделать вот так
https://wiki.miranda-ng.org/index.php?title=Plugin:ICQ/ru

**Comment by alexeik** [comment]
так дело в том, человек не заходит в icq mobile.
то есть он оффлайн.
а откуда то выходит его акк в онлайн.

**Comment by dartraiden** [comment]
Ну сервер его держит онлайн, как баунсер.

**Comment by alexeik** [comment]
вот и вопрос, как так. баунсер это что?

**Comment by dartraiden** [comment]
Как только человек хоть раз в жизни воспользовался мобильной аськой (пусть хоть год назад), отныне его сессия всегда висит онлайн, её поддерживает сервер, чтобы этому человеку могли писать другие люди, а он получал эти сообщения, как выйдет в реальности в онлайн. Но миранда эти сообщения сгружать с сервера не умеет.

Выше я написал, как разорвать эту сессию.

**Comment by alexeik** [comment]
ага понял.
увидел how to fix it.
