### ISSUE TITLE
ClistBlind: quick search on the Clist doesn't work

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#163]
**Reported by Piciok on 3 Feb 2013 21:09 UTC**
Currently the checkbox "Quick search in open groups only" seems not to take any effect. the letter navigation works only with items present on the contact list (I.e. groups and ungrouped contacts). It is not possible to navigate to contacts using first letter navigation if they are in groups and even what works is just the first letter navigation so it is not possible to navigate by entering a few first letters of the searched item's name.
I hope it can be fixed.

**Comment by georgehazan** [comment]
**Modified by watcher on 4 Feb 2014 16:25 UTC**

**Comment by georgehazan** [comment]
**Modified by mataes on 20 Jun 2014 04:04 UTC**

**Comment by bdorer** [comment]
I don't see any checkbox in clist-blind so I vote vor closing.
Furthermore I'm able to quicksearch a name by typing its first letters.
