### ISSUE TITLE
[CRASH] при закрытии, чтото пошло не так, либо флешку высунул рано, либо еще что.

### ISSUE THREAD

**Issue by alexeik** [miranda-ng/miranda-ng#1630]
ПРи загрузке получаю такие ошибки.
А потом CRASH.
Программа перестала загружаться.

---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: I:\ice.ng\libs\libmdbx.mir
File: pnl2bytes
Line: 628

Expression: size > 0 && size <= ((1u << 24) - 2 - (sizeof(void *) * 2u) / sizeof(pgno_t)) * 2

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
---------------------------
Abort   Retry   Ignore   
---------------------------

---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: I:\ice.ng\libs\libmdbx.mir
File: mdbx_pnl_check
Line: 774

Expression: ((scan[0]) > (scan[1]))

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
---------------------------
Abort   Retry   Ignore   
---------------------------

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Miranda32.exe
  Application Version:	0.95.9.0
  Application Timestamp:	5bbdd944
  Fault Module Name:	ucrtbase.dll

Чем помочь?

**Comment by alexeik** [comment]
Помогите.
А то миранда перестала грузиться.

**Comment by georgehazan** [comment]
там вместо заголовка у файла каша какая-то.
нужен бэкап от плагина db_autobackups

**Comment by alexeik** [comment]
а где они хранятся эти бэкапы?

**Comment by alexeik** [comment]
окей. нашел тут I:\ice.ng\Profiles\ngprofile\AutoBackups
сжал до 10 мб.
