### ISSUE TITLE
[Import] When importing an entire DB, it should not be checked for duplicates

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#1632]
When importing a database (from old profile into a blank profile, for example), duplicate checking should never be enabled. Because duplicate checking in miranda is only comparing timestamps, it can cause deletion of nonduplicate events.

**Comment by georgehazan** [comment]
added an option to check dups. enjoy :)

**Comment by LittleVulpix** [comment]
@georgehazan The funny thing is, even with the option it still deleted duplicates :D it doesn't say "xx duplicates skipped" in the import window, but they are still missing in the final db.

**Comment by LittleVulpix** [comment]
@dartraiden can you reopen this one please?

**Comment by LittleVulpix** [comment]
@datraiden this is now resolved (or rather, it is clear that after the duplicate skipping was removed, the remaining missing messages are caused by a problem win dbx_sqlite). Closing this issue.
@ghazan 's fix works for the skipping of import.dll which is what the case was initially about.

**Comment by soustruh** [comment]
Hi guys, I forgot to check the new „Check duplicates“ checkbox, so many of my messages got doubled. Is there any way I can fix it and remove the duplicates? Thanks!
