### ISSUE TITLE
[Discord] Group chats are very unreliable

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#1636]
### Expected behavior
Working group chats

### Actual behavior
These all happen randomly, intermittently

- [x] ~~nobody shows up in the chart participant list, as if the group was empty. But you can still see people talking, just not "who"~~ **Fixed in https://github.com/miranda-ng/miranda-ng/commit/8a57ca7afd4cce23a6a9112a64e3a2aeee7d96be**
- [x] sometimes the roles are properly shown, but usually the coloured "dots" next to group member list are missing
- [x] it is not possible to send media to group chat
- [x] ~~if a group chat window is opened and you reconnect to discord, group chat members will not reappear for some time. If you wait several minutes and then relogin, they will show.~~ **Fixed in https://github.com/miranda-ng/miranda-ng/commit/8a57ca7afd4cce23a6a9112a64e3a2aeee7d96be**

Probably more but these are the most problematic ones.

### Does it work in stable version?
No

### Steps to reproduce that behavior
Just use miranda with discord

**Comment by georgehazan** [comment]
2. Miranda supports only 8 roles, while Discord guilds potentially contain much more. In this case a contact might have no icon

**Comment by LittleVulpix** [comment]
Strangely, this works _sometimes_. Sometimes the chat has the colours, sometimes not... same chat.

**Comment by LittleVulpix** [comment]
Some updates, points 1 and 4 have been fixed.

**Comment by LittleVulpix** [comment]
Media sending to Discord guild chats now works. The "role" also shows up correctly. The "role dots" are showing wrongly or missing sometimes but eh.
