### ISSUE TITLE
[Discord] Direct messages from temporary contacts don't show until relogin

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#1637]
### Expected behavior
When someone messages me - even if they are not my contact - I should see the message.

### Actual behavior
A person messaged me via direct message, but I didn't know about this until I had to relog; then miranda retrieved all of the history.

### Does it work in stable version?
Probably not

### Steps to reproduce that behavior
* join some server
* have a contact who is not on your contact list message you directly
* no messages will arrive
* log out and log back into discord
* messages will show up

**Comment by georgehazan** [comment]
yes, they are ignored

**Comment by LittleVulpix** [comment]
The description of the issue shows that they appear when you log in

**Comment by georgehazan** [comment]
I need two network logs:
- one for receiving a message from unknown user in online mode;
- another for receiving such message during login (when it creates a user)

**Comment by LittleVulpix** [comment]
Looks like standard Discord behavior; even official client behaves this way.
