### ISSUE TITLE
dbx_sqlite: driver prevents main thread termination

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1642]
> Драйвер базы не даёт миранде закрыть основной поток из-за чего она остаётся висеть в памяти.

https://forum.miranda-ng.org/index.php?topic=5579.msg22547#msg22547

**Comment by sss123next** [comment]
всё еще актуально ?

**Comment by dartraiden** [comment]
Неактуально, исправлено.
