### ISSUE TITLE
Discord: add ability to hide guild subgroups and channels

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1652]
If "Use subgroups for guild's channels" option is enabled, every guild (server in Discord terminology) have own subgroups in contact's list.

My_cool_server
|_Common_channels
|____channel1
|____channel2
|_Privatr_channels
|____channel3
|____channel4

For example, I interesting only channel1. So, I want to hide all other channels from the contact list (some servers have tons of channels, but my contact list is not infinite :) )

I try to hide channels by ignoring them. This doesn't work: ignored channels appear in my contact list at next login. But subgroups cannot be ignored at all. My settings:

![2323232323](https://user-images.githubusercontent.com/5046855/49551272-ad248200-f8ff-11e8-8509-7debdd694aae.png)

Subgroups and channels are unchecked, channels are gone but these subgroups still in my contact list:

![3333](https://user-images.githubusercontent.com/5046855/49551207-70f12180-f8ff-11e8-8d9b-2faa8119f179.png)

**Comment by dartraiden** [comment]
I even cannot ignore "Server: <server name>" contact. For example, IRC protocol allow this.

**Comment by georgehazan** [comment]
what about "Hide empty groups" option in clist?

**Comment by dartraiden** [comment]
OK, for groups it works. But I still cannot hide useless Discord channels.

**Comment by georgehazan** [comment]
you can either move useful channels to the separate groups (if you use only a few of channels) or move useless channels to another group and close it using [+]
