### ISSUE TITLE
[Sticky Notes and Reminders] Slight change in behaviour of plugin settings

### ISSUE THREAD

**Issue by goonis** [miranda-ng/miranda-ng#1660]
Sticky Notes and Reminders plugin doesn’t have an ability to setup recurring events, so for example, for a weekly reminder, you have to re-set it weekly.

In the old version of the plugin that worked in Miranda IM, when you open a reminder by clicking on the icon from the tray and trying to select a new date and time for the reminder, the time of the future reminder was automatically substituted from the current reminder, but in the current plugin reminder time is setup from moment you click on icon in tray.

Example: reminder is set for example at January,1 9:00, at 9:00 it works and and shows the tray icon. If you click on the icon for example at 9:15, the window with the reminder will unfold and when you start to select a new date and time for the next reminder, the default time will be 9:15, I would like to inherit time from the current reminder and which was set to 9:00 .

Can this minor fix be made to the plugin?

**Comment by dartraiden** [comment]
Russian:

В старой версии плагина, которая работала еще в Miranda IM, при открытии ремайндера кликом по иконке из трея и при попытке выбрать новую дату для ремайндера время подставлялось автоматически из установленного для текущего ремайндера, а в нынешнем плагине подставляется текущее время.

Пример: ставлю reminder например на 1.04 9:00, он честно срабатывает в 9:00 и показывает иконку в трее. Если на иконку кликнуть например в 9:30, то окно с ремайндером развернется и при выборе новой даты и времени для следующего ремайндера по умолчанию время поставится 9:30, а хотелось бы чтобы оно наследовалось из текущего ремайндера и выставлялось по умолчанию на 9:00.

**Comment by goonis** [comment]
Получилось немного не то что хотелось бы.
В 08:30 ставим ремайндер на 08:45, в 08:45 он срабатывает в трее, в 09:00 открываем его из трея, всё ок, хотим повторить завтра в 08:45, выбираем дату и подставляется время 08:30 (то есть время создания ремайндера), а не 08:45, как задумывалось.

**Comment by georgehazan** [comment]
вот и мне показалось, что это что-то несуразное :) 
поправил, пнул билдик, через полчаса будет

**Comment by goonis** [comment]
Теперь стало правильно, но выплыл еще один косяк: если я в в сработавшем например в 9:00 ремайндере  выбираю для повторения любой день кроме сегодняшнего, то варианты выбора времени тоже только от 9:00 (точнее от 09:00 до 08:30) а должны быть от 0:00 до 23:30.

**Comment by georgehazan** [comment]
@goonis а какая разница? оно просто добавляет 24 часа в виде получасовых отрезков, так что всё равно можно выбрать любую временную отметку.

**Comment by goonis** [comment]
@georgehazan приниципиальной разницы наверное нет и должно сработать правильно, но если я переставляю ремайндер, который был назначен например на 1 апреля 9:00, на месяц вперед на 1 мая, но при этом на 7:00, то с учетом приписки у 7:00 (22:00 Hours) и главное переходом в выпадающем списке через 0:00 начинаешь сомневаться что выбрав дату 1 мая ставлю ли я ремайндер на 1 мая или уже на 2 мая.

**Comment by georgehazan** [comment]
вернул в точности к предыдущему виду, щас соберется

**Comment by goonis** [comment]
Обновился до 0.2.0.2
1. При создании и редактировании ремайндера всё стало ок, при переставлении на новую дату и время сработавшего ремайндера всё осталось по старому (с условных 14:00 до 13:30). Правда когда создается новый ремайндер то при выборе новой даты и потом возврате на текущую было бы логично выбор времени для текущей даты тоже возвращать к получасовкам от текущего времени, но это мелочи.
2. Пункт Edit Reminder стал просто недоступен для тех ремайндеров которые были созданы до запуска клиента, свежесозданный можно редактировать опять же только до перезапуска клиента.

**Comment by georgehazan** [comment]
>Пункт Edit Reminder стал просто недоступен для тех ремайндеров которые были созданы до запуска клиента, свежесозданный можно редактировать опять же только до перезапуска клиента.

ну там такая логика - если реминдер мигает в трее, то его нельзя исправлять в списке через меню

**Comment by goonis** [comment]
Мигание тут не причем, это вообще не связано с исходной темой тикета, недоступно редактирование для любого ремайндера, даже установленного на "через полгода", он же точно в момент редактирования не мигает. То есть создаем ремайндер на будущее время, перезапускаем клиента и всё, редактирование недоступно.

**Comment by georgehazan** [comment]
такого в принципе быть не может, если давить rclick не на пустом месте, а прямо на строчке с ремайндером

**Comment by goonis** [comment]
Вот пример, давил rclick на строке с первым ремайндером
![image](https://user-images.githubusercontent.com/8069033/54824031-c12b9e00-4cba-11e9-8402-68405e5da0e9.png)
Думаю на скрине видно что строка Edit Reminder неактивна.

**Comment by georgehazan** [comment]
поправил, сейчас соберется

**Comment by goonis** [comment]
А то что при переустановке на новые дату и время уже сработавшего ремайндера всё еще выбирается время от 10:00 до 09:30, а не от 00:00 до 23:30 как при создании нового, уже исправляться не будет?
![image](https://user-images.githubusercontent.com/8069033/54977750-4fe83580-4faf-11e9-91d2-f78569a4d6a1.png)
![image](https://user-images.githubusercontent.com/8069033/54977644-0ac40380-4faf-11e9-849d-2b1a0b3f9d34.png)

**Comment by georgehazan** [comment]
там логика простая - если число сегодняшнее, то идет относительное время (рис.2), если нет, то абсолютное (рис.1)

**Comment by goonis** [comment]
В случае с созданием ремайндера именно так и работает, а вот при переназначении времени ранее созданного и сработавшего - неправильно. Я же на втором скрине показал: число 2 апреля, а время предлагается относительное.

**Comment by goonis** [comment]
И вылез еще один баг видимо после последнего исправления: давным давно у меня выставлен еженедельный ремайндер на 07:00 среды, сегодня он сработал и при переустановке даты на следующую среду на те же 07:00 дата не не сохраняется и ремайндер тут же снова срабатывает, удалось это обойти только выставив его на "через 5 минут" и уже затем перейдя в список ремайндеров и, пока он не сработал, изменить его на следующую среду на 07:00, так дату удалось сохранить.

**Comment by georgehazan** [comment]
>при переустановке даты на следующую среду на те же 07:00 дата не не сохраняется и ремайндер тут же снова срабатывает

переустановил на 1 week после - сработало.

**Comment by goonis** [comment]
> переустановил на 1 week после - сработало.

А у меня нет. Записал небольшой скринкаст, на котором пытаюсь на сработавшем ремайндере дважды переставить время на неделю вперед и он тут же срабатывает снова.

[out.zip](https://github.com/miranda-ng/miranda-ng/files/3021207/out.zip)

**Comment by georgehazan** [comment]
> А у меня нет. Записал небольшой скринкаст, на котором пытаюсь на сработавшем ремайндере дважды переставить время на неделю вперед и он тут же срабатывает снова.

Ибо нефиг :) там в выпадашке надо выбрать 1 Week, работает железно :)
Щас посмотрим, что там с вводом даты не так.

**Comment by georgehazan** [comment]
ахаха :) не надо было править код, который делает относительные метки времени для всех выпадашек с датой, там сидел адский костыль, который позволял этому говнокоду работать...

**Comment by dartraiden** [comment]
Как только ты улучшаешь код, то вылезают баги из-за выбитых костылей. Miranda way: 19 лет на десктопе.

**Comment by georgehazan** [comment]
всё оказалось несколько проще. у обоих обосров одна и та же причина размером в 1 строчку

**Comment by goonis** [comment]
Обои исправились, но появился новый ) 
Создаем ремайндер на "через 1 минуту", он срабатывает, переставляем его на 7 дней вперед, заходим в список и видим вот такую картину:
![image](https://user-images.githubusercontent.com/8069033/55304438-22d6cf80-5454-11e9-95c7-600809b5dcaa.png)
1 и 6 ремайндеры этот как раз наш тестовый. Пытаемся удалить первый через правую кнопку мыши, получаем
![image](https://user-images.githubusercontent.com/8069033/55304504-76491d80-5454-11e9-957f-e90f22eabf6b.png)
Перезапускаемся, получаем 
![image](https://user-images.githubusercontent.com/8069033/55304593-c627e480-5454-11e9-8092-62f5f5bed5f3.png)
и уже успешно удаляем обе копии ремайндера переставленного ранее на 7 дней вперед.
Crash прикрепляю.
[crash.zip](https://github.com/miranda-ng/miranda-ng/files/3027828/crash.zip)

**Comment by C1eriC** [comment]
Можно ли сделать чекбоксы (или уже преобразовать это в комбобокс) для повторения напоминалки каждую неделю, каждый месяц, каждый год?

**Comment by C1eriC** [comment]
На сегодняшний день (2 апр) версия плагина 0.2.0.3 (на последней стабильной миранде) работает некорректно: уведомление, после всплытия и откладывания на какой-либо срок (через ввод вручную времени и даты) не откладывается, окно закрывается, но время остаётся прежним (которые было, а не которое вбили заного). И через пару секунд это же уведомление вылазит снова.

Так же, не запоминаются позиции колонок в окне Список напоминаний (где они все, в таблице). Колонки можно растянуть, как удобно, но их положение сбрасывается, после закрытия и открытия окна.

**Comment by C1eriC** [comment]
Miranda 95.10.2 #21681 релизная. Плагин 0.2.0.3. Win7x64.

При попытке отредактировать уже имеющуюся напоминалку — она дублируется (создаётся новая, с новым временем, но остаётся старая, со старым временем). При попытке удалить дубль — Миранда зависает, требует перезагрузки.

Так же не запоминает позиции колонок в окне Список напоминаний (см. предыдущий коммент).

**Comment by C1eriC** [comment]
Уведомления двоятся. Переставляешь время на одном — появляется второе точно такое же.
Уведомления, почему-то, перестали появляться. Иногда всплывают, иногда время проходит, но напоминалка не вылазит (в установленное время).
Удалял дубли, тут вообще чудо — сама собой появилось пустое напоминание (без текста) выставленное на 1601 год! → https://a.radikal.ru/a30/1904/3f/e68d1d60de90.png

**Comment by C1eriC** [comment]
Вот ещё какой баг: выставлена напоминалка (она есть в общем списке) на 12.04 12:00. Я её редактирую, выставляю ей другое время — 13.04 13:00. Создаётся её дубль!
https://c.radikal.ru/c39/1904/1d/ee46e9f67a4f.png
Появилась новая напоминалка, на скрине она выделена. А предыдущая, исправленная осталась где и была, но уже с новым временем.

**Comment by georgehazan** [comment]
@C1eriC запоминание ширины колонок нас покинуло, попробую восстановить

**Comment by C1eriC** [comment]
@georgehazan В текущей стабильной версии (95.10.2 #21687, плагин 2.0.4) ширина колонки запоминается некорректно. Выставляешь одну, а после закрытия окна она сбрасывается на другую (первая колонка получается шире в 3 раза чем выставил).

**Comment by georgehazan** [comment]
там винда пытается периодически выставить ширину колонки автоматически, пока не понял, как это предотвратить (тем более, что автоподбор ширины отключен)

**Comment by goonis** [comment]
А можно еще убрать прыганье фокуса со строки на строку когда водишь курс мыши по ремайндерам в списке их просмотра? Очень раздражает.

**Comment by C1eriC** [comment]
@georgehazan Сейчас, при открытии окна с полным списоком, выставляется какая-то определённая ширина. При новом открытии (даже если не менял ширину) — она изменяется! И так можно открывать/закрывать, и она прыгает туда-сюда, даже если сам ничего не шевелил.

**Comment by georgehazan** [comment]
@C1eriC ага, там бредовая конструкция полностью. выкинул нахрен, стало легче

**Comment by C1eriC** [comment]
Сегодня утром всплыли две напоминалки. Одну из них я отложил на 35 минут (через выпадающий список), а другая выглядела так (не было возможности изменить что-либо): https://d.radikal.ru/d35/1904/93/1e53daa13ce2.png
Нажал «Напомнить ещё раз». Потом, через окно со списоком всех напоминалок, я попытался изменить ей время (она и правда была отложена на сутки вперёд). Но у меня это не получилось! Она стоит на 21 апр. Я ставлю на 20 апр, но дата не меняется, остаётся так же 21 апр. Пробовал несколько раз, но она всё равно оставалась даты 21 апр (время даёт изменить).

**Comment by georgehazan** [comment]
@C1eriC это напоминалка, которая была создана в новом режиме "напоминать автоматически". У нее нельзя исправить время, она будет сама откручиваться на один день вперед

**Comment by C1eriC** [comment]
В плагине Notes and Reminders была бы очень полезна функция «Напоминать каждую неделю» и «Напоминать каждый год» (по аналогии с уже имеющейся «Напоминать каждый день»).
Достаточно ли об этом пожелании (понятно, что это не срочно и вообще, не факт что будет) написать здесь, или, лучше завести отдельное issue?

**Comment by dartraiden** [comment]
Если это не связано с этим тикетом, то, конечно, отдельный.

**Comment by C1eriC** [comment]
А вот, я нашёл [тикет на эту тему](https://github.com/miranda-ng/miranda-ng/issues/1746#issuecomment-489325100).

**Comment by C1eriC** [comment]
Что-то, всё-таки, в плагине не так (последняя релизная версия плагина и миранды).
Утром поставил напоминалку на 12:00. Она вылезла, я её отложил на час (когда она вылезла — выбрал «После» и из выпадающего списка «1 час»). Но она отложилась не на час, а на минуту и снова вылезла. Я удивился и снова отложил её на час. И снова она вылезла через минуту. Сейчас вот специально проверил — откладываю на час, но в общем списке напоминалок видно, что откладывается она только на 1 минуту вперёд.

Это явный баг.

**Comment by C1eriC** [comment]
@dartraiden, @georgehazan Баг описанный сообщением выше не даёт нормально пользоваться напоминалками. Может стоит открыть этот (закрытый) тикет? Ведь в процессе его исправления возник этот баг. Или, всё-таки, надо новый тикет для этих целей создавать?
