### ISSUE TITLE
ICQ10: переименованный контакт не обновляет своё имя на сервере

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1677]
1) логинимся в официальный клиент, добавляем контакт
2) логинимся в Миранду, она подтягивает этот контакт в клист
3) переименовываем контакт в официальном клиенте
4) Миранда при ближайшем переподключении тоже отобразит это изменение

Но если переименовать контакт в Миранде, то меняется имя в базе, но не /ICQ_1/Nick. Соответственно, то, что я переименовал контакт, не синхронизируется с сервером.

**Comment by georgehazan** [comment]
миранда никогда и не меняла ник на сервере, она при переименовании создает CList/MyHandle и сохраняет его локально

**Comment by georgehazan** [comment]
смысл в том, чтобы при переименовании на сервере не рушить собственный вариант. поэтому серверное имя - это ICQ/Nick, а в клисте мы видим CList/MyHandle

**Comment by MonsterNya** [comment]
[а это всё тогда зачем?](https://pp.userapi.com/c845417/v845417286/1669be/RFO-z_VYWP4.jpg)

**Comment by dartraiden** [comment]
Это настройки старого протокола, который не работает.

**Comment by MonsterNya** [comment]
ааа, сорян.
