### ISSUE TITLE
Tox: поиск по адресу Tox (76-значный адрес) предлагает сразу добавить контакт

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1681]
Вместо того, чтобы вывести результат поиска, нажатие на кнопку "Найти" сразу же предлагает добаить контакт.

**Comment by georgehazan** [comment]
а там нет поиска же. поэтому можно, конечно, тупо скопировать это в результат поиска и позволить нажать кнопку "Добавить", но смысла в этом немного
