### ISSUE TITLE
ICQ10 захватывает метаконтакт

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1684]
В метаконтакте у меня ghazan (Jabber) и goshismus (ICQ)
Дефолтным субконтактом указан Jabber в настройках меты. Мета называется _ghazan_.
Как только мне пишет _goshismus_, имя меты меняется на _goshismus_. И двойным кликом по мете открывается ICQ. Хотя, дефолт, напоминаю - Jabber.

И самое возмутительное - даже в настройках меты дефолт при этом становится ICQ.

**Comment by dartraiden** [comment]
Как только goshismus уходит в оффлайн, имя меты меняется обратно на ghazan. Но дефолтным сабом остаётся ICQ.

**Comment by georgehazan** [comment]
там такая мысль, что возникает временный default, но он не пишется в базу, в базе ничего не меняется, и на следующем заходе он снова станет по умолчанию

**Comment by georgehazan** [comment]
можно сделать так, чтобы дефолт не трогался, а выставлялся только для SRMM (впрочем, это и так происходит)

**Comment by dartraiden** [comment]
Ок, на стабле такое же поведение... не знаю, почему у меня чёткое ощущение, что все эти годы меты вели себя иначе
