### ISSUE TITLE
ICQ10: Миранда не помечает сообщения, как прочитанные?

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1693]
Добавил контакт в Миранду. Контакт мне пописал. Потом я его удалил. Потом снова добавил (тестировал соседний баг) и он мне снова пописал. В Миранде непрочитанных сообщений не было.

Затем я зашёл в свой UIN через официальный клиент, и все эти сообщения в нём висели, как новые, непрочитанные.

**Comment by georgehazan** [comment]
сто пудов
