### ISSUE TITLE
FTPFileYM broken filename / download link

### ISSUE THREAD

**Issue by MikeKnife** [miranda-ng/miranda-ng#1703]
### Expected behavior
Spaces in Filenames should be translated to "_" or similar 
Download-Link should be created accordingly

### Actual behavior
Spaces in Filenames are converted to 0xD1 (not nice, but still acceptable)
e.g.: "Test File.pdf" -> "ftp://ftp-server/TestÑFile.pdf" 

In the generated download link all spaces are just ommited.
The download link says: "ftp://ftp-server/TestFile.pdf" 
therefore the link does not work.

### Does it work in stable version?
Stable version is used (V 0.6.0.2)

**Comment by dartraiden** [comment]
Can you test on development version? FTPFile got some Unicode related fixes.

**Comment by MikeKnife** [comment]
I checked with the development version of ftpfileym.

It has the same issue.

Miek Knife

**Comment by MikeKnife** [comment]
I downloaded the version dated 01.02.2019-09:33. Unfortunately in a brand new miranda ng installation, it does not show up at all. Neither in 32bit nor in the 64bit Version.
I hope i got the right file. Can you please provide a download link.

Mike Knife

**Comment by dartraiden** [comment]
https://www.miranda-ng.org/distr/miranda-ng-alpha-latest.7z
https://www.miranda-ng.org/distr/miranda-ng-alpha-latest_x64.7z

and install plugin via PluginUpdater

**Comment by MikeKnife** [comment]
I am sorry to disappoint you. 
I tried the both versions (x64 and x86) that you provided above. I also installed the plugin both ways (insert in the respective folders and via plugin updater, as you recommended). In every configuration the miranda ng terminates immediately without any error msg, as soon as i click the upload-button. It just dies reproducable. 
I am using Windows7 HomePro x64.
I don't think it has anything to do with any other programm installed but if you think it might narrow things down, I can test it in a clean environment on a VM.

Mike Knife

**Comment by dartraiden** [comment]
Can you post versioninfo?
https://wiki.miranda-ng.org/index.php?title=Version_information

**Comment by MikeKnife** [comment]
Version-Info see file.
[MirandaNG-Versioninfo.txt](https://github.com/miranda-ng/miranda-ng/files/2847913/MirandaNG-Versioninfo.txt)

After the last update the error-msg reads. "unknown software exception" (0xc0150014) at 0x76e67b9b

Mike Knife

**Comment by dartraiden** [comment]
Seems like our CrashDumper is broken...

**Comment by dartraiden** [comment]
Please make another VersionInfo after the next update :)

**Comment by MikeKnife** [comment]
Hi,
Miranda NG  just offered a few more updates. After that everything seems to work correctly. (Sry I  did not pay attention, which components were updated.)

"Test - File.jpg"  converts to  "Test_-_File.jpg" with the correct file name in the link.
"ftp://userid:password@makroma.ddns.net/Test_-_File.jpg"

Perfect !!!

Here is the new version info, just in case.

[MirandaNG-Versioninfo_2.txt](https://github.com/miranda-ng/miranda-ng/files/2848331/MirandaNG-Versioninfo_2.txt)
 
Thank you for your effort. Great work.

Mike Knife
