### ISSUE TITLE
Jabber: implement XEP-0363 (HTTP File Upload)

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1710]
This allows just paste clipboard to message log and upload image on server. Like Telegram.

**Comment by DavisR-GitHub** [comment]
Yes, this feature seems to be very desirable.
Mobile clients and XMPP servers already supports it.

**Comment by ziceptor** [comment]
+

**Comment by OmlineEditor** [comment]
This is the desired function. it is not clear why it has not yet been done. without it, it is not possible to transfer files between different clients

**Comment by dartraiden** [comment]
Proto menu → Services... → Service Discovery → Right-click on service (for example upload.example.com) → Use for uploads.

**Comment by DavisR-GitHub** [comment]
Great! 
Thanks!
But could I ask one correction?
Sender sees in conversation window local address of file - like c:\filename.ext
Receiver sees correct http URL.
Could you change so both of them see http URL?

**Comment by OmlineEditor** [comment]
> Proto menu → Services... → Service Discovery → Right-click on service (for example upload.example.com) → Use for uploads.

only HTTP or HTTPS also supported?

**Comment by dartraiden** [comment]
> only HTTP or HTTPS also supported?
Both of course.

> Could you change so both of them see http URL?
[Done](https://github.com/miranda-ng/miranda-ng/issues/2098).

**Comment by DavisR-GitHub** [comment]
Confirmed
