### ISSUE TITLE
ICQ10: strange Online

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1713]
> Периодически те контакты кто используют миранду нг (2 чел + я сам, я сам у себя в контактах, да) начинают синхронно (все сразу) мигать, типа они только что перешли в онлайн, хотя они и так были онлайн. Где-то раз в 3-5 минут. Очень странная фигня.

https://forum.miranda-ng.org/index.php?topic=5619.msg23022#msg23022

**Comment by dartraiden** [comment]
> Me and my friend have the same version (last dev x32) and I got coming online status for him every 2-3 min and he see the same.

https://forum.miranda-ng.org/index.php?topic=5646.msg23043#msg23043

**Comment by dartraiden** [comment]
> ghazan
> 19:56:04	потому что сервак смену статуса присывлает

**Comment by dartraiden** [comment]
В качестве решения, например: обучить Миранлду не реагировать на смену статуса собеседником, если старый статус = прилетевшему новому. То есть, если собеседник Онлайн и он снова присылает инфу, что он Онлайн, игнорим это.

**Comment by dartraiden** [comment]
@georgehazan a это не Миранда ли keep-alive шлёт?

**Comment by georgehazan** [comment]
нет,Миранда не шлет кипалайв

**Comment by dartraiden** [comment]
То есть, немец неправду сказал?
https://forum.miranda-ng.org/index.php?topic=5623.msg23108#msg23108

**Comment by georgehazan** [comment]
ну он мыслит устаревшими понятиями. нет ни кипалайва, ни опций. всё мертво

**Comment by dartraiden** [comment]
Посмотрел лог, от сервера периодически прилетает ""state":"online"

**Comment by dartraiden** [comment]
@georgehazan can this helps?
https://forum.miranda-ng.org/index.php?topic=5619.msg23292#msg23292

**Comment by dartraiden** [comment]
Лог с клиента, который мигнул
[netlog — копия.txt](https://github.com/miranda-ng/miranda-ng/files/2734010/netlog.txt)
