### ISSUE TITLE
ICQ10 mirOTR doesn'T work with ICQ10

### ISSUE THREAD

**Issue by leecher1337** [miranda-ng/miranda-ng#1721]
### Expected behavior
Session setup of OTR session works fine.

### Actual behavior
mirOTR runs amok, both ICQ clients (Miranda NG -> Pidgin) bomb each other with OTR messages until ICQ server runs into a rate limit and kicks me off the network.
Maybe there is a message encoding issue, because both clients complain about malformed messages:

(13:24:08) 70908044 has sent a message intended for a different session. If you are logged in multiple times, another session may have received the message.
(13:24:11) Error setting up private conversation: Malformed message received
(13:24:12) Error setting up private conversation: Malformed message received
(13:24:14) Error setting up private conversation: Malformed message received
(13:24:16) 70908044 has sent a message intended for a different session. If you are logged in multiple times, another session may have received the message.
(13:24:19) Error setting up private conversation: Malformed message received
(13:24:20) Error setting up private conversation: Malformed message received
(13:24:21) Error setting up private conversation: Malformed message received
(13:24:27) 70908044 has sent a message intended for a different session. If you are logged in multiple times, another session may have received the message.

### Does it work in stable version?
N/A - no ICQ10 in stable.

### Steps to reproduce that behavior
One PIDGIN user and one Miranda NG user, both using ICQ accounts should try to establish a OTR session.

I can provide logs, but I don't know if this helps debugging the issue, as ouy just see the OTR-gibberish in the logs. I guess, it's not really useful.
For Versioninfo please see https://github.com/miranda-ng/miranda-ng/issues/1720

**Comment by dartraiden** [comment]
Please test after https://github.com/miranda-ng/miranda-ng/commit/f5980308df254aa17a9f5d94a980fb888b6c193f

**Comment by leecher1337** [comment]
Works fine, thank you
