### ISSUE TITLE
Facebook: option "Show wall posts (news feed)" does not work

### ISSUE THREAD

**Issue by newsjunkie247** [miranda-ng/miranda-ng#1722]
Having problems with the Facebook plugin. It seems to be get disconnected and I also keep getting the notification "Please try closing and reopening your browser window" even after restarting.

**Comment by dartraiden** [comment]
Create and post [Netlog](https://wiki.miranda-ng.org/Network_log) plaese

**Comment by dartraiden** [comment]
Try to disable news receoiving in protocol settings.

**Comment by dartraiden** [comment]
> [19:02]	ghazan: такая ошибка вылезает, когда аптайм миранды больше нескольких дней
> [19:05]	ghazan: я у матаеса уже глянул
> [19:06]	ghazan: там очень характерная ошибка
>

**Comment by newsjunkie247** [comment]
Actually, I think this may at least partially have been the result of having the option for getting the newsfeed checked - that hasn't worked in several months, though ideally it would be nice for it work again some day.

**Comment by dartraiden** [comment]
Old Facebook was deprecated, We should implement this for new Facebook.

https://github.com/miranda-ng/miranda-ng/issues/2162
