### ISSUE TITLE
ICQ10 crash in Netlib SSL transfer (according to stacktrace)

### ISSUE THREAD

**Issue by leecher1337** [miranda-ng/miranda-ng#1724]
### Expected behavior
No crash ;)

### Actual behavior
Crash in Netlib_Recv when calling SSLv3_client_method. See attached crashlog, I suspect a NULL pointer.

### Does it work in stable version?
N/A, no ICQ10 in stable

### Steps to reproduce that behavior
Cannot tell, suddenly crashed. Memory dump cannot be attached, as it contains sensitive information (password).

**Comment by dartraiden** [comment]
No crashlog attached. Can you upload it to Pastebin?

**Comment by dartraiden** [comment]
XP SP2 is not supported
Alsi log without debug symbols :(

**Comment by leecher1337** [comment]
Currently wasn't able to reproduce it again. 
Don't think it is related to SP-Level of OS, that would be odd... Miranda NG works on SP2, no missing dependencies on SP3 functions in it.

**Comment by dartraiden** [comment]
@georgehazan said that miranda should not even run under XP SP2, so it's funny :)

**Comment by leecher1337** [comment]
Might be related to https://github.com/miranda-ng/miranda-ng/issues/1728 because it also happened on token expiry. I guess if the mentioned issue has been fixed, this can also be closed and I will reopen it if it happens again.

**Comment by leecher1337** [comment]
Ok, not related, this bug still persists.
ICQ log before crash:
-----------
[01:04:06 0B50] [ICQ] Executing request e6e97f9f-d573-4f69-a533-041ea2b8d47f:
https://bos.icq.net/bos-k024c/aim/fetchEvents?aimsid=198.1508555343.2692582922:70908044&rnd=1546992246.447169&seqNum=94706&timeout=60000
[01:05:06 0B50] [ICQ] (05555260:2564) Data sent
GET /bos-k024c/aim/fetchEvents?aimsid=198.1508555343.2692582922:70908044&rnd=1546992246.447169&seqNum=94706&timeout=60000 HTTP/1.1
User-Agent: Miranda/0.95.11.21170
Accept-Encoding: deflate, gzip
Host: bos.icq.net
Connection: Keep-Alive
Proxy-Connection: Keep-Alive

[01:05:06 0950] [ICQ] (05555260:2564) Data received
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 09 Jan 2019 00:05:06 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 445
Connection: keep-alive
Keep-Alive: timeout=75
Content-Encoding: gzip
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

‹
[01:05:06 0B50] [ICQ] w:\miranda-build\src\mir_app\src\netlibhttp.cpp 522: HttpPeekFirstResponseLine Failed (11 10)
[01:05:06 0B50] [ICQ] (05555260:2564) Connection closed internal
[01:05:06 0B50] [ICQ] (05555260:4294967295) Connection closed
[01:05:06 0B50] [ICQ] Request e6e97f9f-d573-4f69-a533-041ea2b8d47f failed
[01:05:06 0B50] [ICQ] Executing request 9aa0348c-11f4-4ce9-afdc-857a2c0a99c9:
https://bos.icq.net/bos-k024c/aim/fetchEvents?aimsid=198.1508555343.2692582922:70908044&rnd=1546992246.447169&seqNum=94706&timeout=60000
[01:05:06 0B50] [ICQ] Connection request to bos.icq.net:443 (Flags 11)....
[01:05:06 0B50] [ICQ] (05555260) Connecting to server bos.icq.net:443....
[01:05:06 0950] [ICQ] (05555260:4294967295) Connection closed
[01:05:06 0950] [ICQ] Request a63dd37c-5899-4d9a-bb69-6742b8e74f0b failed
[01:05:06 0950] [ICQ] Executing request 3394c9a6-1921-4828-89f7-1efae2a977f1:
https://bos.icq.net/bos-k024c/aim/fetchEvents?aimsid=198.1508555343.2692582922:70908044&rnd=1546992246.447169&seqNum=94706&timeout=60000
[01:05:06 0950] [ICQ] Connection request to bos.icq.net:443 (Flags 11)....
[01:05:06 0B50] [ICQ] (05555260) Connecting to ip 178.237.20.79:443 ....
[01:05:06 0B50] [ICQ] (2692) Connected to bos.icq.net:443
[01:05:06 0B50] [ICQ] (2692 bos.icq.net) Starting SSL negotiation
[01:05:06 0950] [ICQ] (05555260) Connecting to server bos.icq.net:443....
[01:05:06 0950] [ICQ] (05555260) Connecting to ip 178.237.20.79:443 ....
[01:05:06 0950] [ICQ] (2536) Connected to bos.icq.net:443
[01:05:06 0950] [ICQ] (2536 bos.icq.net) Starting SSL negotiation
[01:05:07 0B50] [ICQ] (2536 bos.icq.net) SSL negotiation successful
[01:05:07 0B50] [ICQ] (05555260:2536) Data sent
GET /bos-k024c/aim/fetchEvents?aimsid=198.1508555343.2692582922:70908044&rnd=1546992246.447169&seqNum=94706&timeout=60000 HTTP/1.1
User-Agent: Miranda/0.95.11.21170
Accept-Encoding: deflate, gzip
Host: bos.icq.net
Connection: Keep-Alive
Proxy-Connection: Keep-Alive

[01:05:07 0950] [ICQ] (2536 bos.icq.net) SSL negotiation successful
[01:06:06 0B50] [ICQ] w:\miranda-build\src\mir_app\src\netlibhttp.cpp 522: HttpPeekFirstResponseLine Failed (38 10)
[01:06:06 0B50] [ICQ] (05555260:2536) Connection closed internal
[01:06:06 0B50] [ICQ] (05555260) Connecting to server bos.icq.net:443....
[01:06:07 0B50] [ICQ] (05555260) Connecting to ip 178.237.20.79:443 ....
[01:06:07 0B50] [ICQ] (2552) Connected to bos.icq.net:443
[01:06:07 0B50] [ICQ] (2552 bos.icq.net) Starting SSL negotiation
[01:06:08 0B50] [ICQ] (2552 bos.icq.net) SSL negotiation successful
[01:06:08 0B50] [ICQ] (05555260:2552) Data sent
GET /bos-k024c/aim/fetchEvents?aimsid=198.1508555343.2692582922:70908044&rnd=1546992246.447169&seqNum=94706&timeout=60000 HTTP/1.1
User-Agent: Miranda/0.95.11.21170
Accept-Encoding: deflate, gzip
Host: bos.icq.net
Connection: Keep-Alive
Proxy-Connection: Keep-Alive

[01:06:08 0950] [ICQ] (05555260:2552) Data sent
GET /bos-k024c/aim/fetchEvents?aimsid=198.1508555343.2692582922:70908044&rnd=1546992246.447169&seqNum=94706&timeout=60000 HTTP/1.1
User-Agent: Miranda/0.95.11.21170
Accept-Encoding: deflate, gzip
Host: bos.icq.net
Connection: Keep-Alive
Proxy-Connection: Keep-Alive

[01:06:08 0950] [ICQ] (05555260:2552) Data received
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 09 Jan 2019 00:06:08 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 437
Connection: keep-alive
Keep-Alive: timeout=75
Content-Encoding: gzip
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

‹
[01:06:08 0B50] [ICQ] (05555260:2552) Connection closed internal
-----------

Miranda Crash Report from 9 Jan 2019 1:06:17. Crash Dumper v.0.1.0.2

Likely cause of the crash plugin: Miranda NG

Exception: Access Violation at address 129EC693. Reading from address 000001A0.

Stack Trace:
---------------------------------------------------------------
129EC693 (SSLEAY32 129E0000): (filename not available) (0): SSLv3_client_method
126EFEC8 (mir_app 126A0000): (filename not available) (0): Netlib_Recv
126EA74C (mir_app 126A0000): (filename not available) (0): Netlib_SendHttpRequest
126EA9C1 (mir_app 126A0000): (filename not available) (0): Netlib_HttpTransaction
18202C1B (ICQ 18200000): (filename not available) (0): (function-name not available)
182046F9 (ICQ 18200000): (filename not available) (0): (function-name not available)
1285241C (mir_core 12840000): (filename not available) (0): mir_forkthreadex

CPU:  Intel(R) Pentium(R) M processor 1.86GHz [x86 Family 6 Model 13 Stepping 8]
Installed RAM: 2047 MBytes
Microsoft Windows XP Professional Service Pack 2 (build 2600)
Internet Explorer: 6.0.2900.2180 (build 62900.2180)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : German/German | German/German

Miranda NG Version: 0.95.11 alpha build #21170 (d7a89e57b6)
Build time: 8 Jan 2019 18:34:08
Profile: F:\Miranda IM\Profiles\leecher\leecher.dat
Language pack: No language pack installed
Service Mode: No

Active Plugins (18):
¤ AVS.dll v.0.95.11.0 [5 Jan 2019 2:00:38] - Avatar service 
¤ CrashDumper.dll v.0.95.11.0 [5 Jan 2019 2:01:04] - Crash dumper 
¤ Db_autobackups.dll v.0.95.11.0 [8 Jan 2019 18:34:18] - Db autobackuper 
¤ DbEditorPP.dll v.0.95.11.0 [5 Jan 2019 2:01:06] - Database editor++ 
¤ Dbx_mdbx.dll v.0.95.11.0 [8 Jan 2019 18:35:22] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.0.95.11.0 [8 Jan 2019 18:34:12] - Miranda NG mmap database driver 
¤ Dummy.dll v.0.95.11.0 [8 Jan 2019 18:35:06] - Dummy protocol 
¤ historypp.dll v.1.5.1.5 [4 Jan 2019 2:02:14] - History++ 
¤ ICQ.dll v.0.95.11.0 [8 Jan 2019 18:35:18] - ICQ/2018 protocol 
¤ Import.dll v.0.95.11.0 [8 Jan 2019 18:34:30] - Import contacts and messages 
¤ Jabber.dll v.0.95.11.0 [7 Jan 2019 2:01:12] - Jabber protocol 
¤ MirOTR.dll v.0.95.11.0 [4 Jan 2019 2:02:04] - Miranda OTR 
¤ MSN.dll v.0.95.11.0 [5 Jan 2019 2:01:00] - MSN protocol 
¤ OpenSSL.dll v.0.95.11.0 [5 Jan 2019 2:01:32] - OpenSSL SSL API module 
¤ PluginUpdater.dll v.0.95.11.0 [8 Jan 2019 18:34:44] - Plugin updater 
¤ Popup.dll v.0.95.11.0 [4 Jan 2019 2:00:50] - Popup plus 
¤ SeenPlugin.dll v.0.95.11.0 [4 Jan 2019 2:00:50] - Last seen 
¤ StopSpam.dll v.0.95.11.0 [4 Jan 2019 2:00:52] - StopSpam+ 

Loaded Modules:
-------------------------------------------------------------------------------
F:\Miranda IM\Miranda32.exe  00400000 - 0040B000 v.0.95.11.0 [8 Jan 2019 18:34:08]
C:\WINDOWS\system32\ntdll.dll  7C910000 - 7C9C7000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\kernel32.dll  7C800000 - 7C907000 v.5.1.2600.3119 [16 Apr 2007 16:53:05]
C:\WINDOWS\system32\USER32.dll  7E360000 - 7E3F1000 v.5.1.2600.3099 [8 Mar 2007 16:48:39]
C:\WINDOWS\system32\GDI32.dll  77EF0000 - 77F38000 v.5.1.2600.3466 [23 Oct 2008 13:51:07]
C:\WINDOWS\system32\SHELL32.dll  7E670000 - 7EE91000 v.6.0.2900.3402 [3 Jul 2008 14:02:44]
C:\WINDOWS\system32\ADVAPI32.dll  77DA0000 - 77E4A000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\RPCRT4.dll  77E50000 - 77EE2000 v.5.1.2600.3173 [9 Jul 2007 14:11:35]
C:\WINDOWS\system32\Secur32.dll  77FC0000 - 77FD1000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\msvcrt.dll  77BE0000 - 77C38000 v.7.0.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\SHLWAPI.dll  77F40000 - 77FB6000 v.6.0.2900.3429 [20 Aug 2008 6:33:09]
C:\WINDOWS\system32\hplun.dll  10000000 - 1000D000 v.1.0.0.1 [16 Feb 2004 12:28:04]
C:\WINDOWS\WinSxS\x86_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.2600.2982_x-ww_ac3f9c03\comctl32.dll  773A0000 - 774A3000 v.6.0.2900.2982 [25 Aug 2006 16:46:44]
F:\Miranda IM\libs\ucrtbase.dll  00D90000 - 00E70000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\api-ms-win-core-string-l1-1-0.dll  00D70000 - 00D73000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-core-errorhandling-l1-1-0.dll  00E70000 - 00E73000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-core-file-l1-1-0.dll  00E80000 - 00E84000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-core-timezone-l1-1-0.dll  00E90000 - 00E93000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\api-ms-win-core-namedpipe-l1-1-0.dll  00EA0000 - 00EA3000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-core-handle-l1-1-0.dll  00EB0000 - 00EB3000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-core-file-l2-1-0.dll  00EC0000 - 00EC3000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\api-ms-win-core-heap-l1-1-0.dll  00ED0000 - 00ED3000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-core-libraryloader-l1-1-0.dll  00EE0000 - 00EE3000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-core-synch-l1-1-0.dll  00EF0000 - 00EF3000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-core-processthreads-l1-1-0.dll  00F00000 - 00F03000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-core-processenvironment-l1-1-0.dll  00F10000 - 00F13000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-core-localization-l1-2-0.dll  00F20000 - 00F23000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\api-ms-win-core-datetime-l1-1-0.dll  00F30000 - 00F33000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-core-sysinfo-l1-1-0.dll  00F40000 - 00F43000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-core-synch-l1-2-0.dll  00F50000 - 00F53000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\api-ms-win-core-console-l1-1-0.dll  00F60000 - 00F63000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-core-debug-l1-1-0.dll  00F70000 - 00F73000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-core-processthreads-l1-1-1.dll  00F80000 - 00F83000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\api-ms-win-core-file-l1-2-0.dll  00F90000 - 00F93000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\api-ms-win-core-profile-l1-1-0.dll  00FA0000 - 00FA3000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-core-memory-l1-1-0.dll  00FB0000 - 00FB3000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-core-util-l1-1-0.dll  00FC0000 - 00FC3000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-core-rtlsupport-l1-1-0.dll  00FD0000 - 00FD3000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-core-interlocked-l1-1-0.dll  00FE0000 - 00FE3000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\api-ms-win-crt-runtime-l1-1-0.dll  00FF0000 - 00FF4000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\api-ms-win-crt-stdio-l1-1-0.dll  01000000 - 01004000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\api-ms-win-crt-locale-l1-1-0.dll  01010000 - 01013000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\api-ms-win-crt-heap-l1-1-0.dll  01020000 - 01023000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\VCRUNTIME140.dll  01030000 - 01043000 v.14.16.27012.6 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\api-ms-win-crt-string-l1-1-0.dll  01050000 - 01054000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\api-ms-win-crt-convert-l1-1-0.dll  01060000 - 01064000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\mir_app.mir  126A0000 - 1276C000 v.0.95.11.21170 [8 Jan 2019 18:34:08]
C:\WINDOWS\system32\WINMM.dll  76AF0000 - 76B1E000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\WS2_32.dll  71A10000 - 71A27000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\WS2HELP.dll  71A00000 - 71A08000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\UxTheme.dll  5B0F0000 - 5B128000 v.6.0.2900.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\COMDLG32.dll  76350000 - 7639A000 v.6.0.2900.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\ole32.dll  774B0000 - 775ED000 v.5.1.2600.2726 [26 Jul 2005 5:39:49]
F:\Miranda IM\libs\FreeImage.mir  12000000 - 12092000 [8 Jan 2019 18:34:00]
F:\Miranda IM\libs\zlib.mir  12A80000 - 12A99000 v.1.2.11.0 [8 Jan 2019 18:33:48]
F:\Miranda IM\libs\api-ms-win-crt-utility-l1-1-0.dll  01070000 - 01073000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\api-ms-win-crt-time-l1-1-0.dll  01080000 - 01083000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\MSVCP140.dll  01090000 - 010FF000 v.14.16.27012.6 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\api-ms-win-crt-math-l1-1-0.dll  01100000 - 01105000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\api-ms-win-crt-filesystem-l1-1-0.dll  01110000 - 01113000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\api-ms-win-crt-environment-l1-1-0.dll  01120000 - 01123000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
F:\Miranda IM\libs\mir_core.mir  12840000 - 12863000 v.0.95.11.21170 [8 Jan 2019 18:33:48]
C:\WINDOWS\system32\WTSAPI32.dll  76F10000 - 76F18000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\WINSTA.dll  76300000 - 76310000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\NETAPI32.dll  597D0000 - 59824000 v.5.1.2600.3462 [15 Oct 2008 17:57:39]
F:\Miranda IM\libs\api-ms-win-crt-multibyte-l1-1-0.dll  01130000 - 01135000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
C:\WINDOWS\system32\VERSION.dll  77BD0000 - 77BD8000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\rdpsnd.dll  5DE80000 - 5DE88000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\PSAPI.DLL  76BB0000 - 76BBB000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\PGPhk.dll  011D0000 - 011D9000 v.8.0.3.0 [27 Oct 2003 11:49:42]
C:\WINDOWS\system32\MSCTF.dll  746A0000 - 746EB000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\SynTPFcs.dll  63000000 - 63014000 v.7.5.17.18 [15 Sep 2005 12:57:36]
F:\Miranda IM\Plugins\DbEditorPP.dll  177A0000 - 177BD000 v.4.0.1.2 [5 Jan 2019 2:01:06]
F:\Miranda IM\Plugins\CrashDumper.dll  175C0000 - 175D1000 v.0.1.0.2 [5 Jan 2019 2:01:04]
C:\WINDOWS\system32\dbghelp.dll  59DD0000 - 59E71000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
F:\Miranda IM\Plugins\Dbx_mdbx.dll  177E0000 - 177F2000 v.0.95.9.1 [8 Jan 2019 18:35:22]
F:\Miranda IM\libs\libmdbx.mir  125A0000 - 125CB000 [8 Jan 2019 18:35:20]
F:\Miranda IM\Plugins\Dbx_mmap.dll  17820000 - 17830000 v.0.95.8.1 [8 Jan 2019 18:34:12]
F:\Miranda IM\Plugins\Import.dll  182E0000 - 182F2000 v.0.95.10.1 [8 Jan 2019 18:34:30]
F:\Miranda IM\libs\sqlite3.mir  12900000 - 12970000 [8 Jan 2019 18:34:20]
F:\Miranda IM\libs\libjson.mir  12580000 - 1258C000 [8 Jan 2019 18:34:12]
F:\Miranda IM\Core\stdcrypt.dll  13060000 - 1306C000 v.0.95.11.21170 [8 Jan 2019 18:33:52]
F:\Miranda IM\Plugins\OpenSSL.dll  01470000 - 01478000 v.0.1.0.2 [5 Jan 2019 2:01:32]
F:\Miranda IM\libs\LIBEAY32.mir  122E0000 - 12422000 v.1.0.2.18 [21 Nov 2018 14:46:18]
F:\Miranda IM\libs\api-ms-win-crt-conio-l1-1-0.dll  01480000 - 01483000 v.10.0.10586.15 [25 May 2017 13:39:24]
F:\Miranda IM\libs\SSLEAY32.mir  129E0000 - 12A29000 v.1.0.2.18 [21 Nov 2018 14:46:32]
C:\WINDOWS\system32\CRYPT32.dll  77A50000 - 77AE5000 v.5.131.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\MSASN1.dll  77AF0000 - 77B02000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\Msftedit.dll  4B4D0000 - 4B556000 v.5.41.15.1514 [27 Nov 2006 15:54:15]
F:\Miranda IM\Core\stdclist.dll  13040000 - 1304F000 v.0.95.11.21170 [8 Jan 2019 18:33:50]
F:\Miranda IM\Plugins\AVS.dll  170C0000 - 170D1000 v.0.98.1.1 [5 Jan 2019 2:00:38]
F:\Miranda IM\Plugins\Db_autobackups.dll  17860000 - 1786E000 v.0.1.0.2 [8 Jan 2019 18:34:18]
F:\Miranda IM\Plugins\Dummy.dll  178C0000 - 178C8000 v.0.2.0.0 [8 Jan 2019 18:35:06]
F:\Miranda IM\Plugins\historypp.dll  17D00000 - 17EEE000 [4 Jan 2019 2:02:14]
C:\WINDOWS\system32\oleaut32.dll  770F0000 - 7717B000 v.5.1.2600.3266 [4 Dec 2007 19:40:03]
C:\WINDOWS\system32\msimg32.dll  76320000 - 76325000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\winspool.drv  72F70000 - 72F96000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\imm32.dll  76330000 - 7634D000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\RICHED20.DLL  74DB0000 - 74E1C000 v.5.30.23.1228 [27 Nov 2006 15:54:15]
F:\Miranda IM\Plugins\ICQ.dll  18200000 - 1820E000 v.0.95.10.1 [8 Jan 2019 18:35:18]
F:\Miranda IM\Plugins\Jabber.dll  03BF0000 - 03C89000 v.0.11.0.5 [7 Jan 2019 2:01:12]
F:\Miranda IM\libs\libaxolotl.mir  121E0000 - 1220F000 [7 Jan 2019 2:00:48]
C:\WINDOWS\system32\DNSAPI.dll  76EE0000 - 76F07000 v.5.1.2600.3394 [20 Jun 2008 18:36:12]
F:\Miranda IM\Plugins\MirOTR.dll  03CB0000 - 03D48000 v.0.14.1.17 [4 Jan 2019 2:02:04]
F:\Miranda IM\Plugins\MSN.dll  03D50000 - 03D8A000 v.0.95.9.1 [5 Jan 2019 2:01:00]
F:\Miranda IM\Plugins\PluginUpdater.dll  03D90000 - 03DA6000 v.0.2.0.2 [8 Jan 2019 18:34:44]
F:\Miranda IM\Plugins\Popup.dll  03DB0000 - 03DEA000 v.2.1.1.15 [4 Jan 2019 2:00:50]
C:\WINDOWS\WinSxS\x86_Microsoft.Windows.Gdiplus_6595b64144ccf1df_1.0.2600.3352_x-ww_81af8e88\gdiplus.dll  4EBA0000 - 4ED46000 v.5.1.3102.3352 [15 Apr 2008 18:54:16]
F:\Miranda IM\Plugins\SeenPlugin.dll  04020000 - 04030000 v.5.0.5.3 [4 Jan 2019 2:00:50]
F:\Miranda IM\Plugins\StopSpam.dll  04030000 - 0403B000 v.0.1.0.2 [4 Jan 2019 2:00:52]
F:\Miranda IM\Core\stdmsg.dll  130C0000 - 130EB000 v.0.95.11.21170 [8 Jan 2019 18:33:50]
F:\Miranda IM\Core\stduserinfo.dll  13160000 - 1316D000 v.0.95.11.21170 [8 Jan 2019 18:33:50]
F:\Miranda IM\Core\stdemail.dll  13080000 - 13086000 v.0.95.11.21170 [8 Jan 2019 18:33:50]
F:\Miranda IM\Core\stdfile.dll  130A0000 - 130B0000 v.0.95.11.21170 [8 Jan 2019 18:33:50]
F:\Miranda IM\Core\stdautoaway.dll  13000000 - 13008000 v.0.95.11.21170 [8 Jan 2019 18:33:52]
F:\Miranda IM\Core\stduseronline.dll  13180000 - 13187000 v.0.95.11.21170 [8 Jan 2019 18:33:50]
F:\Miranda IM\Core\stdaway.dll  13020000 - 13029000 v.0.95.11.21170 [8 Jan 2019 18:33:50]
C:\WINDOWS\System32\mswsock.dll  719B0000 - 719F0000 v.5.1.2600.3394 [20 Jun 2008 18:36:12]
C:\WINDOWS\system32\rasadhlp.dll  76F80000 - 76F86000 v.5.1.2600.2938 [26 Jun 2006 18:40:34]
C:\WINDOWS\system32\hnetcfg.dll  66710000 - 66769000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\System32\wshtcpip.dll  719F0000 - 719F8000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\System32\winrnr.dll  76F70000 - 76F78000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\WLDAP32.dll  76F20000 - 76F4D000 v.5.1.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\rsaenh.dll  0FFD0000 - 0FFF8000 v.5.1.2600.2161 [4 Aug 2004 5:00:00]
C:\Programme\ThinkPad\Bluetooth Software\btkeyind.dll  05360000 - 0536F000 [1 Nov 2005 14:11:50]
C:\WINDOWS\system32\USP10.dll  75790000 - 757FB000 v.1.420.2600.2180 [4 Aug 2004 5:00:00]
C:\WINDOWS\system32\msls31.dll  74640000 - 74667000 v.3.10.349.0 [4 Aug 2004 5:00:00]

**Comment by dartraiden** [comment]
> this bug still persists

https://www.youtube.com/watch?v=Ov9ynOC4lPE

**Comment by leecher1337** [comment]
Next one, same stacktrace, here is ICQ log tail

[10:55:20 10B4] [ICQ] (3344 bos.icq.net) SSL negotiation successful
[10:56:02 10B4] [ICQ] (04348CE8:3344) Data sent
GET /bos-k024c/aim/fetchEvents?aimsid=198.1508555343.2692582922:70908044&rnd=1547114059.133057&seqNum=118201&timeout=60000 HTTP/1.1
User-Agent: Miranda/0.95.11.21170
Accept-Encoding: deflate, gzip
Host: bos.icq.net
Connection: Keep-Alive
Proxy-Connection: Keep-Alive

[10:56:02 13A8] [ICQ] (04348CE8:3344) Data received
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 10 Jan 2019 09:56:02 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 441
Connection: keep-alive
Keep-Alive: timeout=75
Content-Encoding: gzip

‹
[10:56:02 10B4] [ICQ] w:\miranda-build\src\mir_app\src\netlibhttp.cpp 522: HttpPeekFirstResponseLine Failed (11 10)
[10:56:02 10B4] [ICQ] (04348CE8:3344) Connection closed internal

**Comment by georgehazan** [comment]
yup, smth wrong with OpenSSL in multithreading mode...
