### ISSUE TITLE
SCRAM-SHA-1(-PLUS) + SCRAM-SHA-256(-PLUS) supports

### ISSUE THREAD

**Issue by Neustradamus** [miranda-ng/miranda-ng#1727]
"When using the SASL SCRAM mechanism, the SCRAM-SHA-256-PLUS variant SHOULD be preferred over the SCRAM-SHA-256 variant, and SHA-256 variants [RFC7677] SHOULD be preferred over SHA-1 variants [RFC5802]".

There is only SCRAM-SHA-1, there is not SCRAM-SHA-1-PLUS:
- https://tools.ietf.org/html/rfc5802
- https://tools.ietf.org/html/rfc6120

There is not SCRAM-SHA-256(-PLUS):
- https://tools.ietf.org/html/rfc7677 since 2015-11-02
- https://tools.ietf.org/html/rfc8600 since 2019-06-21: https://mailarchive.ietf.org/arch/msg/ietf-announce/suJMmeMhuAOmGn_PJYgX5Vm8lNA

I add SCRAM-SHA-512(-PLUS): https://xmpp.org/extensions/inbox/hash-recommendations.html

Linked to:
- https://github.com/scram-xmpp/info/issues/1

**Comment by georgehazan** [comment]
if possible, add the XMPP server address that supports these new standards, so we could test the code

**Comment by Neustradamus** [comment]
SCRAM-SHA-1 and SCRAM-SHA-256:
- Jackal: https://github.com/ortuman/jackal

SCRAM-SHA-1(-PLUS) and SCRAM-SHA-256(-PLUS):
- Tigase 8.0.0: https://docs.tigase.net/tigase-server/snapshot/Administration_Guide/html/

SCRAM-SHA-1(-PLUS), SCRAM-SHA-224(-PLUS), SCRAM-SHA-256(-PLUS), SCRAM-SHA-384(-PLUS), SCRAM-SHA-512(-PLUS):
- Metronome IM: https://metronome.im/

SCRAM-SHA-1(-PLUS):
- Prosody IM: https://prosody.im/doc/plain_or_hashed#authenticating

SCRAM-SHA-1:
- ejabberd: https://www.ejabberd.im/

**Comment by georgehazan** [comment]
@sss123next посмотри plz как время будет

**Comment by Neustradamus** [comment]
@georgehazan: Thanks a lot!

Can you add 512 and other too?

Some have 1/224/256/384/512 and -PLUS variants

Have you tested?

Servers:
- lightwitch.org (based on Metronome IM XMPP server; https://metronome.im/)
- jackal.im (https://github.com/ortuman/jackal/)

**Comment by Neustradamus** [comment]
@georgehazan: I have updated the main text with:
- SCRAM-SHA-512(-PLUS): https://tools.ietf.org/html/draft-melnikov-scram-sha-512
- SCRAM-SHA3-512(-PLUS): https://tools.ietf.org/html/draft-melnikov-scram-sha3-512
- Extensions to Salted Challenge Response (SCRAM) for 2 factor authentication: https://tools.ietf.org/html/draft-melnikov-scram-2fa

If you want to add SCRAM-SHA3-512 now, you can ^^

**Comment by Neustradamus** [comment]
@ all: It is official for TLS 1.3 Binding!
- RFC 9266: Channel Bindings for TLS 1.3: https://tools.ietf.org/html/rfc9266

Details:
- tls-unique for TLS =< 1.2
- tls-exporter for TLS = 1.3
