### ISSUE TITLE
ICQ10: протокол не обновляет ключ Nick в своей ветке

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1732]
Если изменить своё имя через сайт, то Nick не меняется в базе даже при переподключении протокола. Как следствие, в дальнейших сообщениях в журнале фигурирует старый ник.

Вероятно, имеет смысл запрашивать свой собственный ник при каждом подключении?

**Comment by georgehazan** [comment]
там не ник, там всю карточку надо запрашивать...
а ник все же меняется не так часто
