### ISSUE TITLE
ICQ10: протокол не меняет ключ Nick у контактов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1733]
Схоже с предыдущим тикетом. Если контакт сменил имя/ник (через сайт), то протокол самостоятельно никогда об этом не узнает. Имя в Миранде у контакта меняется лишь если вручную в user details нажать кнопку "Обновить".

Как вариант: запрашивать ник у всех контактов при каждом подключении протокола. Но не создаст ли это задержки, если контактов штук 200?

**Comment by georgehazan** [comment]
ну на самом деле так и есть: ник (в привычном для нас виде возвращается только при явном запросе UserInfo), а в списке пользователей на сервере его нет. поэтому по мере смены ника пользователем миранда не возбуждается ни разу...

**Comment by georgehazan** [comment]
да,  если всем раскидывать запросы, тормозить будет дико
