### ISSUE TITLE
Jabber: не анонсировать поддержку OTR, если не установлен MirOTR

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1734]
> С удалённого клиента в свойствах миранды можно заметить OTR. Причём OTR не работает если нет плагина MirOTR, но зачем-то анонсируется в свойствах

**Comment by georgehazan** [comment]
если речь идет об ext, то туда оно попадает только в случае наличия плагина.

if (bMirOTR)
	arrExtCaps.insert(JABBER_EXT_MIROTR);
