### ISSUE TITLE
Msg_Export: плагин всегда считает, что файл истории будет иметь на конце .txt, но при включённом экспорте в JSON файл кончается на .json

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1737]

**Comment by dartraiden** [comment]
Стало ещё хуже. До фикса было так:
- если включён экспорт в txt, то итоговый файл будет называться Mataes.txt
- если включён экспорт в JSON, то итоговый файл будет называться Mataes.txt.json

Плагин при вызове пункта меню "Открыть экспортированную историю" пытался открыть Mataes.txt и обламывался.

После фикса стало так:
- если включён экспорт в JSON, то итоговый файл будет называться Mataes.txt.json.json (добавился лишний json)

Плагин при вызове пункта меню "Открыть экспортированную историю" пытается по-прежнему открыть Mataes.txt и обламывается.

**Comment by dartraiden** [comment]
Кроме того, если выбран пункт "Экспорт в JSON" нужно менять txt на json в строке "Имя файла"

![3](https://user-images.githubusercontent.com/5046855/50938480-79ea8b00-1489-11e9-9445-e3922dc87cfb.png)

Я думаю, корень проблем растёт отсюда.

**Comment by georgehazan** [comment]
> Кроме того, если выбран пункт "Экспорт в JSON" нужно менять txt на json в строке "Имя файла"

не думаю. json просто добавляется по мере необходимости

**Comment by dartraiden** [comment]
Нет, мы возвращаемся к тому, что в заголовке тикета.
