### ISSUE TITLE
Scriver: notification of new messages in MUC

### ISSUE THREAD

**Issue by radjah** [miranda-ng/miranda-ng#1749]
### Expected behavior
Notification of a new message does not disappear when viewing a tab with a chat, if it has been selected.

### Actual behavior
The notification of a new message disappears when viewing a tab with a chat, if it has been selected.

### Steps to reproduce that behavior
* The window in the background. Active tab is tab with chat.
* New message comes to chat. A notification appears in the taskbar.
* I make the window an active click on its taskbar button.
* The notification that there are new messages in the chat does not disappear.

In order for the notification of new messages to disappear, you need to switch to another tab and return to the tab with chat.

**Comment by apollo2k4** [comment]
Duplicate #111
