### ISSUE TITLE
ICQ10: random crash

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1760]
[20:06]	f2065: Опять миранда упала, очевидно уже второй раз в этом месте падает. Что-то в последнем обновлении ICQ неправильно…

```
Likely cause of the crash plugin: ICQ/2018 protocol

Exception: Access Violation at address 18207892. Reading from address 00000000.

Stack Trace:
---------------------------------------------------------------
18207892 (ICQ 18200000): w:\miranda-build\protocols\icq10\src\server.cpp (64): CIcqProto::CheckOwnMessage
18207EBB (ICQ 18200000): w:\miranda-build\protocols\icq10\src\server.cpp (636): CIcqProto::OnSendMessage
18203A6F (ICQ 18200000): w:\miranda-build\protocols\icq10\src\http.cpp (195): CIcqProto::ExecuteRequest
18203C4A (ICQ 18200000): w:\miranda-build\protocols\icq10\src\http.cpp (40): CIcqProto::ServerThread
1285241C (mir_core 12840000): w:\miranda-build\src\mir_core\src\threads.cpp (161): forkthreadex_r
77717C04 (KERNEL32 77700000): (filename not available) (0): BaseThreadInitThunk
77D8AD8F (ntdll 77D30000): (filename not available) (0): RtlInitializeExceptionChain
77D8AD5A (ntdll 77D30000): (filename not available) (0): RtlInitializeExceptionChain

```

**Comment by dartraiden** [comment]
[20:56]	dartraiden: может, падает при определённых действиях?
[21:06]	f2065: Ну, входящее сообщение по ICQ. Вероятно, когда окно ICQ не открыто.
Утром это упало когда пришло новое ICQ-сообщение. Далее я весь день по ICQ обшался - не падало, а потом вдруг упало опять в момент сообщения (и вроде бы окно тоже было не открыто).
[21:07]	f2065: Раньше не падало, с последнего обновления - вот дважды упало
Вылезает только окно плагина о падении, с вопросом о копировании лога в буфер обмена.
И в пока я не нажму да/нет - миранда продолжает работать, даже в ICQ можно общатся. Утром когда упало - я ещё немного пообщался в ICQ, а потом на вопрос о копировании лога ответил - и тогда миранда закрылась.

**Comment by alexeik** [comment]
такие падения регулярные .
отправляешь , в тот момент когда к тебе приходит сообщение.
тайминги не всегда соблюсти можно для этого краша.
в tabsrmm получаю частенько. просто недавно скачал debug для отправки краша.

**Comment by georgehazan** [comment]
проблема в том, что оно по коду не может там падать :-)
как бы научиться повторять это под отладчиком?

**Comment by georgehazan** [comment]
понятно, что оно возникает в другом потоке, поэтому основной поток, который рисует окна, остается жить, так что весь интерфейс работает. вопрос в том, почему крашится рабочий поток

**Comment by alexeik** [comment]
может побольше try catch добавить.
рабочий поток этот тот ккоторый принимает, отправляет?

**Comment by georgehazan** [comment]
думаю, что всё проще
