### ISSUE TITLE
Глобальный выбор статусов неправильно сопоставлен с ICQ

### ISSUE THREAD

**Issue by f2065** [miranda-ng/miranda-ng#1765]
Miranda NG Version: 0.95.11 alpha build #21196
¤ ICQ.dll v.[b]0.95.11.0[/b] [12 Jan 2019 2:01:56] - ICQ/2018 protocol 
 Proto_ICQ.dll [12 Jan 2019 2:02:16]

В статусах ICQ:
Не в сети
В сети
Отсутствую
Недоступен
Занят
Не беспокоить
Невидимый

Баги:
- В глобальном статусе есть «Готов болтать», в статусе ICQ его нет. Однако при выборе глобально - он ставится и у ICQ. Не знаю виден ли он с другой стороны.

 - При глобальном выборе статуса не работает переход между статусом «В сети» и всеми прочими онлайн-статусами.
Например если глобальный статус выбрать «В сети», а затем «Отсутствую» - то ICQ становится в статусе «Не в сети»; Иногда надо пару раз повторить смену глобального статуса: «В сети», «Отсутствую», «В сети», «Отсутствую»… и ICQ уйдёт в оффлайн.
После этого бага можно несколько раз переключать глобальный статус между «Недоступен» и «Отсутствую» - ICQ так и остаётся в оффлайне… 

Так-же есть тут Jabber, он все глобальные статусы устанавливает правильно. А вот ICQ - статусы ставит неправильно.

**Comment by dartraiden** [comment]
Есть мнение, что пора выпилить все статусы, кроме "В сети" и "Не в сети".

**Comment by dartraiden** [comment]
Да, переключение между разными онлайн-статусами глючит. Например, у меня StatusManager автоматически уводит Миранду в Away при запуске полноэкранных приложений, а вот обратно вывести не может, сваливается в "Не в сети".

**Comment by dartraiden** [comment]
Проблему можно решить радикально, выпилив в ICQ все статусы, кроме "В сети" и "Не в сети".
Клиенты, работающие по протоколу WIM эти статусы от сервера всё равно не получают.
Но эти статусы ещё видят клиенты, работающие по протоколу OSCAR.

**Comment by f2065** [comment]
Ну сейчас надо как-то с глобальными статусами это состыковать…

**Comment by georgehazan** [comment]
>После этого бага можно несколько раз переключать глобальный статус между «Недоступен» и «Отсутствую» - ICQ так и остаётся в оффлайне…

потому что ловит rate limit на переключение статуса

**Comment by f2065** [comment]
rate limit - локально в самой миранде? Ведь получается что она вообще не выходит ни разу в онлайн при переключениях между отсутствую/недоступен.

**Comment by georgehazan** [comment]
нет, на сервере, разумеется. почему это не выходит?

**Comment by georgehazan** [comment]
@f2065 
>Например если глобальный статус выбрать «В сети», а затем «Отсутствую» - то ICQ становится в статусе «Не в сети»; 

а вот это совсем неправда
