### ISSUE TITLE
ICQ10: rework "Use friendly names" option

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1766]
We can obtain this info via protocol:

```
"friendly":John Smith"
...
"profile": {"displayId": "John Smith", "aimId": "firstName": "John", "lastName": "Smith", "friendlyName": "MegaDestroyer666"
```

please note: `friendly` and `friendlyName` are different fields. `friendly` = how to display user in my clist in official client. I can rename user and change `friendly`. But `friendlyName` is user nickname, I can not and should not change it.

Now see how it stored in db:
First Name = John
Last Name = Smith
Nick = John Smith

and userinfo:
![miranda64_wxgvq9q1kf](https://user-images.githubusercontent.com/5046855/51089940-caadfc80-1785-11e9-8e0a-4417e351d3df.png)

this is totally wrong, because user nick should be MegaDestroyer666, but Miranda just copy `friendly` content to db key `Nick` and lost friendlyName, because "Use friendly names" option is enabled.

Miranda historically use Nick db key as user name for clist. If we place `friendlyName` to Nick db key... well, userinfo will be fixed, but we lost ability to use `friendly` and will use MegaDestroyer666 as user name. Not good.

What can we do?
1) Place `friendly` to Nick db key, so we can load "renamed contacts" from server. Store `friendlyName`in a separate key and use this key as source for userinfo Nickname field. And remove "Use friendly names" option completely.
2) Smth else... @georgehazan suggests to use MyHandle for this.

**Comment by georgehazan** [comment]
no, the idea of using CList/MyHandle is bad, because in Miranda this setting always has priority over all another settings, so a 'friendly' field still will be used anyway

**Comment by georgehazan** [comment]
>this is totally wrong, because user nick should be MegaDestroyer666

if 'Use friendly names' option is disabled, this nick will be forcibly used instead of 'friendly' if you retrieve user info for this guy
