### ISSUE TITLE
ICQ10: прилетают старые ключи SecureIM при каждом логине

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1770]

**Comment by georgehazan** [comment]
непонятно, как фильтровать служебные сообщения, не помеченные как прочитанные

**Comment by uranus** [comment]
> непонятно, как фильтровать служебные сообщения, не помеченные как прочитанные
А можно сделать, чтоб они помечались прочитанными?

**Comment by dartraiden** [comment]
Они не пишутся в базу, в этом проблема. То есть, Миранда их получает, проверяет id - опа, такого в базе нет, значит, это что-то новенькое, непрочитанное.

**Comment by uranus** [comment]
Тогда придётся хотя бы id писать.
