### ISSUE TITLE
ICQ plugin isn't connecting to server.

### ISSUE THREAD

**Issue by anischenko-a** [miranda-ng/miranda-ng#1783]
Hi, ricently I recived email from ICQ suppurt, about new version of icq protocol. 
In one month my miranda stopped connecting to icq server.
Could you please update plugin for ICQ.
Thanks.

**Comment by anischenko-a** [comment]
Неожиданно для себя, заметил вопросы о проблемах на русском.
Продублирую мою проблему на русском.
--
Привет, недавно я получил от icq письмо с текстом, о том, что все сторонние клиенты перестанут подключаться. Потому, что они меняют протокол.
Не могли бы исправить плагин миранды для работы с icq.
Спасибо.

**Comment by rand256** [comment]
Этак вы можете еще заметить наличие списка [последних коммитов](https://github.com/miranda-ng/miranda-ng/commits/master), где за последние недели немалое количество оных относится к ICQ, что может натолкнуть на мысль.
