### ISSUE TITLE
Skype is not connecting

### ISSUE THREAD

**Issue by Ac314** [miranda-ng/miranda-ng#1784]
### Expected behavior
Miranda connects to Skype on start

### Actual behavior
Miranda does not connect to Skype on start

### Does it work in stable version?
Does not work with Miranda 0.95.11 alpha build #21233 (236dfc4581) x64, SkypeWeb.dll v.0.95.11.0 [19 Jan 2019 2:04:42]

### Steps to reproduce that behavior
See netlog attached. 
[netlog.txt](https://github.com/miranda-ng/miranda-ng/files/2778740/netlog.txt)

**Comment by Ac314** [comment]
Connects again after password change. I am closing the issue.

**Comment by f2d** [comment]
> Connects again after password change.
Same here.
Could not connect in Miranda-NG for several days with "login error", but official client worked.
Tried a password change and now Miranda-NG can connect.
