### ISSUE TITLE
После импорта истории сообщения остаются непрочитанными

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1785]
Если импортировать сообщения (конкретно - в формате mContacts) через Import, то они остаются непрочитанными, и TabSRMM при каждом открытии окна сообщений подгружает их все.

**Comment by dartraiden** [comment]
но только при загрузке по времени события
остальные так не глючат

**Comment by georgehazan** [comment]
вряд ли это имеет отношение к импорту. 
у меня залипло обычное сообщение без всякого импорта

**Comment by dartraiden** [comment]
> Тот же эффект обнаружился вне всякой связи с импортом истории.
> Есть метаконтакт, его история подгружается нормально, в соответствии с настройками - 20 предыдущих событий.
> Однако, если открыть в TabSRMM субконтакт (ICQ), где находится 99% истории этого метаконтакта, то грузится история за несколько месяцев.
> 
> Общего с предыдущим случаем разве что первый в прошлом субконтакт, а второй в настоящем.
https://forum.miranda-ng.org/index.php?topic=5681.msg23723#msg23723
