### ISSUE TITLE
Facebook protocol creates unusual activities in accounts

### ISSUE THREAD

**Issue by energizer01** [miranda-ng/miranda-ng#1790]
Last wednesday I created a new FB account which I wanted to user only for chatting using Miranda. All was working just for one day and than it logged me out of Miranda and on the site there was written that FB encountered an unusual activity in my account and wanted to verify it by adding a phone number and a photo. I did it, than it was veryfying it for a day and than the account was completely blocked. I created another account  which worked for two days and than again unusual activity. Fortunately this one has been unlocked after phone number verification, but now I'm afraid to use Miranda again. I hope it could be fixed. 
[VerInfo.txt](https://github.com/miranda-ng/miranda-ng/files/2787150/VerInfo.txt)

**Comment by georgehazan** [comment]
it's completely safe to use Facebook with Miranda. if you want just to chat with another people, disable Options - Network - Facebook - Events - Show wall posts

**Comment by energizer01** [comment]
Hi. Thanx for your reply. But how is it than possible that it created some unexpected activities on two brand new account and both were suspended? Thanx.

**Comment by dartraiden** [comment]
Server algorithms define this activity, we do not know the criteria.

**Comment by georgehazan** [comment]
nobody knows :-) that's a dark mystery of FB.
in the worst case you'd be asked to change a password

**Comment by energizer01** [comment]
OK, I'll try to use it again. I won't go to FB website, just chat. And if it will do it again i'll post here. Thanx a lot for your replies and if any developer here would find something which could cause these things please let me know. I really don't want to create another identity. :)

**Comment by energizer01** [comment]
Hi. nobody still found any miranda things which could cause FB to find it as an unsupported device or something? cause Now I was at the account for 3 days without Miranda and when I logged into Miranda it blew me away in half a day. :( So really this must be Miranda who causes it maybe just on newly created FB accountst.
