### ISSUE TITLE
No smiles in communication with web-ICQ

### ISSUE THREAD

**Issue by eugeny71** [miranda-ng/miranda-ng#1793]
I use Miranda NG version in development (0.95.11) with SmileAdd plugin. My buddy use web-ICQ interface in Firefox browser under Windows. We send to each other some messages with smiles. We see only own smiles but we don't see smiles from other side both. In Miranda NG I see empty squares only instead of graphical smiles from my buddy. In earlier versions of Miranda NG all smiles were displayed correctly.

**Comment by eugeny71** [comment]
(Versions 0.95.10 and earlier were normal. All builds of version 0.95.11 are working incorrect with smiles. Is new ICQ protocol fault in the absence of smiles? )

**Comment by dartraiden** [comment]
> In Miranda NG I see empty squares only instead of graphical smiles from my buddy.
We haven't implemented sticker support yet

**Comment by georgehazan** [comment]
>All builds of version 0.95.11 are working incorrect with smiles.

you might need a font that could display emoji correctly, Segoi UI, for example. Old fonts like Georgia have no such glyphs

**Comment by georgehazan** [comment]
that's how it should look like
![image](https://user-images.githubusercontent.com/4628541/51689102-073fea80-2007-11e9-8918-d7755a4c35b0.png)
