### ISSUE TITLE
ICQ10: add aboutMe content to user info

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1800]
`{"response":{"statusCode":200, "statusText":"Ok", "data":{"users":[{"aimId": "666412727", "displayId": "666412727", "friendly": "РРІР°РЅ РРІР°РЅРѕРІ", "state": "offline", "onlineTime": 989801, "userType": "icq", "buddyIcon": "http://api.icq.net/expressions/getAsset?f=native&t=666412727&id=0110dfe13783787b4d1ca437b55ced472dc7&type=buddyIcon", "iconId": "00010110dfe13783787b4d1ca437b55ced472dc7", "bigBuddyIcon": "http://api.icq.net/expressions/getAsset?f=native&t=666412727&id=011033a012f73cf8c62eaf38b2c26a20c400&type=bigBuddyIcon", "bigIconId": "000c011033a012f73cf8c62eaf38b2c26a20c400", "largeIconId": "03200110a0eaa8610cd9ea192fedc77bf723ac6e", "lastseen": 1548431054, "moodIcon": "http://api.icq.net/expressions/getAsset?f=native&t=666412727&id=0009306963716d6f6f6433&type=buddyIcon", "moodTitle": "QIP 2012 - РІСЃС‘ СЂР°Р±РѕС‚Р°РµС‚. РљР°С‡Р°Р№ РЅР° www.qip.", "profile": {"displayId": "Ivan Ivanov", "aimId": "666412727", "firstName": "Ivan", "lastName": "Ivanov", "friendlyName": "dr", "gender": "male", "homeAddress": [{"country": "RU", "state": "ABS", "city": "Zazhopins"}], "aboutMe": "Some text", "birthDate": 530755200}}]}}}`

![miranda64_poal6kafjf](https://user-images.githubusercontent.com/5046855/51756380-eee8d200-20d1-11e9-9f12-2f041aa133ea.png)

**Comment by dartraiden** [comment]
Also what about "moodTitle"?

**Comment by georgehazan** [comment]
Notes is editable field in which your can leave your own notes about this contact
