### ISSUE TITLE
Не обновляется штамп времени файла с базой данных.

### ISSUE THREAD

**Issue by wegabond** [miranda-ng/miranda-ng#1802]
Миранда стабильной ветки 0.95.10 #21022 x64
Из активных протоколов только jabber
Файл с базой профиля profile.dat не меняет метку времени, однако рядом лежащий profile.dat-lck меняет её исправно при каждом запуске программы.
В связи с этим имеется проблема при синхронизации профиля между двумя компьютерами.
Можно ли сделать, чтобы штамп времени profile.dat менялся при закрытии программы?

**Comment by georgehazan** [comment]
потому что не надо смотреть на File Creation Time, 
как Last Access Time, так Last Write Time прекрасно обновляются

**Comment by wegabond** [comment]
Если бы было именно так, то это обычное поведение и я не создавал бы тикет. Не обновляется именно время изменения. Вот видео: https://yadi.sk/i/SD-CeKfiIYKlIA

**Comment by georgehazan** [comment]
W:\miranda-ng\bin15\Debug64\Profiles\zzzzz>dir /TA *.dat
 Volume in drive W is ssd
 Volume Serial Number is E25B-8A7C

 Directory of W:\miranda-ng\bin15\Debug64\Profiles\zzzzz

28.01.2019  22:56         2 097 152 zzzzz.dat
               1 File(s)      2 097 152 bytes
               0 Dir(s)  179 815 878 656 bytes free

W:\miranda-ng\bin15\Debug64>Miranda64.exe

W:\miranda-ng\bin15\Debug64\Profiles\zzzzz>dir /TA *.dat
 Volume in drive W is ssd
 Volume Serial Number is E25B-8A7C

 Directory of W:\miranda-ng\bin15\Debug64\Profiles\zzzzz

29.01.2019  12:53         1 724 416 zzzzz.dat
               1 File(s)      1 724 416 bytes
               0 Dir(s)  179 816 251 392 bytes free

**Comment by georgehazan** [comment]
@wegabond ok, давай сделаем так. берем Миранду и засовываем под Process Monitor. делаем фильтр по имени процесса и пишем все файловые операции. При выходе должен отработать SetFileTime, который насильно ставит текущее время last access & last write - может он вылетает с каким-то кодом ошибки?

**Comment by wegabond** [comment]
Лог Procmon - https://yadi.sk/d/hezjaiO8yaLl-w

**Comment by georgehazan** [comment]
печалька... в логе ни одной ошибки. но ничего не происходит

**Comment by wegabond** [comment]
Обновился до текущей альфы. Проблема исправлена. Спасибо.
