### ISSUE TITLE
Регрес с stdurl

### ISSUE THREAD

**Issue by apollo2k4** [miranda-ng/miranda-ng#1805]
![image](https://i.imgur.com/weKiQGF.png)
Вместо красных квадратов был значок url т.к. видимо плагин не понимает, что это звонок и считал это url и после удаление stdurl иконок нет и поменять конкретно эту иконку в иконлибе нельзя

**Comment by georgehazan** [comment]
на последнем h++ у меня вот так
![image](https://user-images.githubusercontent.com/4628541/52051897-fd1d6f00-2565-11e9-8a9b-fb9965c95e5d.png)
