### ISSUE TITLE
ICQ10: client detection

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1809]
R&Q implemented this somehow
https://code.highspec.ru/Mikanoshi/RnQ/releases

- Определение клиентов (только несколько встроенных)
- Индикация того, что контакт имеет статус официального

**Comment by Mikanoshi** [comment]
Только по уникальным капсам клиентов, и если они их добавляют, больше никак уже не сделать.

**Comment by georgehazan** [comment]
индикация официального уже есть
