### ISSUE TITLE
ICQ10: server-side ignore list

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1810]
https://code.highspec.ru/Mikanoshi/RnQ/releases

возможно, имеет смысл потырить фичу?

**Comment by Mikanoshi** [comment]
Всенепременнейше :)

**Comment by georgehazan** [comment]
в смысле? игнорировать серверный список контактов? а зачем? для них ни статусы не приходят, ни обновления информации

**Comment by Mikanoshi** [comment]
"игнорировать серверный список контактов?"
Серверный список игнорируемых контактов. Там ещё есть список блокировки, непонятно чем отличаются. При добавлении в любой из них контакту перестают приходить обновления твоего статуса, а сообщения от него отбрасываются ещё на сервере.

**Comment by georgehazan** [comment]
ну это не блокировка, это то, что у них называется Mute / Unmute - девойс по-русски :)

**Comment by Mikanoshi** [comment]
Нет, это https://api.icq.net/buddylist/Mute, а списки игнора/блока это другая фича.
