### ISSUE TITLE
Move "Do not pop up the window when joining a chat room" from core to IRC

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1813]
https://github.com/miranda-ng/miranda-ng/blob/1e2a2a56c171067c1c02d1cbe14619e05c077a03/src/core/stdmsg/src/chat_options.cpp#L43

> sleepy_george, 31.01.2019 13:34:12:
> оно поехало прямо в настройки StdChat
> 
> sleepy_george, 13:34:24:
> потому что когда-то чаты были куском IRC :-)

**Comment by georgehazan** [comment]
in IRC chat windows are always hidden, this option is about smth different
