### ISSUE TITLE
Scriver: line delimiters glitch

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1824]
Miranda IM
![scriver-miranda-im](https://user-images.githubusercontent.com/5046855/52256381-839bcd00-2927-11e9-9689-229ae9324df5.png)

Miranda NG
![scriver-miranda-ng](https://user-images.githubusercontent.com/5046855/52256393-8e566200-2927-11e9-8bf9-dee4e46ceb54.png)

**Comment by georgehazan** [comment]
that's how RichEdit control 5.0 is drawn under Windows 8.x/10
Miranda IM uses old ANSI RichEdit 2.0 which is drawn with full frame
