### ISSUE TITLE
[dbx_sqlite] Importing data causes loss of events with identical timestamp.

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#1830]
### Expected behavior
When importing data into dbx_SQLite, all of my data is preserved.

### Actual behavior
Behavior identical to if you had "check for duplicates" checkbox enabled - all of the messages whose timestamp is the same are gone (only one of them survives)

### Does it work in stable version?
No.

### Steps to reproduce that behavior
 * Have some event that happened at the same time, for example message from 10:00:01 "hi" and "10:00:01" hey
 * try to import it
 * probably, only "hey" or only "hi" will make it into the database.

Issue is very reminiscent of #1632 and/or #1257 

Latest dev miranda as of 7.2.2019 was used.

**Comment by AnrDaemon** [comment]
Timestamp shouldn't be the only indication of a duplicated message.
If anything, it shouldn't be even considered as the indication of a duplicated message at all to begin with.

**Comment by LittleVulpix** [comment]
@AnrDaemon I agree. I never liked this feature and am happy it can be disabled. But for dbx_sqlite, disabling it does nothing.

We have duplicate message detection based on message ID for protocols that support it (discord?), but other than that, there isn't a simple way to detect duplicity.

I wanted it to work like this -> if timestamp matches, check text. If text matches, discard one of the messages. That seemed like a good idea. Yeah it would still get rid of some non-duplicate messages, like if a friend is spamming you and sends 3x the same thing within one second, but such cases are rare I reckon.

But just timestamp and NOT message text.... is wrong.

**Comment by jl452** [comment]
try import on current alpha (with or without "check duplicates", i think nothing different):
some examples (all ~3500, 29 or 31 diff (not remember)):

must be:

[13.01.2019 11:58:44] user1:
text1

[13.01.2019 11:58:44] user_me:
text2

[13.01.2019 11:58:56] user_me:
text3

imported:

[13.01.2019 11:58:44] user1:
text1

[13.01.2019 11:58:56] user_me:
text3

--------------------------------------------------

imported dublicates (1 range only):

[22.04.2019 0:30:08] user_me:
text4

[22.04.2019 0:30:30] user_me:
text5

...

[22.04.2019 0:42:58] user_me:
text6

[22.04.2019 0:30:30] user_me:
text5

...

[22.04.2019 0:42:58] user_me:
text6

[22.04.2019 0:43:20] user_me:
text7

--------------------------------------------------

must be:

[11.02.2019 23:17:49] user1:
text8

[11.02.2019 23:17:54] user_me:
text9

[11.02.2019 23:17:54] user1:
text10

imported:

[11.02.2019 23:17:49] user1:
text8

[11.02.2019 23:17:54] user1:
text10

--------------------------------------------------

manymanymany bugs events from user_not_from_this_history!!! (all equal and dublicates!! ~7500 items!!!):

[11.01.2019 23:11:28] user1:
Authorization request from (user_not_from_this_history): Please authorize my request and add me to your contact list.

**Comment by LittleVulpix** [comment]
Import into dbx_sqlite now does not filter out same-time events anymore.
