### ISSUE TITLE
Clist_modern: сделать вывод информации о последнем появлении отключаемым

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1831]
Насколько я понимаю, сейчас, если в модерне включена 2 или 3 строка, включён вывод статусного сообщения и стоит Seen Plugin, то нет возможности не выводить туда last seen.

**Comment by georgehazan** [comment]
![image](https://user-images.githubusercontent.com/4628541/53417292-5aca9d00-39e6-11e9-913d-9987d6a77783.png)
