### ISSUE TITLE
HistoryStats Crashes Miranda on report creation

### ISSUE THREAD

**Issue by 92U235** [miranda-ng/miranda-ng#1834]
Miranda (latest alpha and stable versions) crashes when creating the statistics via HistoryStats plugin. Roll-back to the latest stable version does not resolve the issue

Crash log attached.
[2019.02.09.zip](https://github.com/miranda-ng/miranda-ng/files/2847395/2019.02.09.zip)

**Comment by dartraiden** [comment]
Update to version with debug symbols and repeat crash log please

**Comment by 92U235** [comment]
Please find attached the updated crash log (based on a Miranda version with debug symbols)
[2019.02.09.zip](https://github.com/miranda-ng/miranda-ng/files/2847693/2019.02.09.zip)

**Comment by georgehazan** [comment]
@92U235 check the fix please in the dev version, if it succeeded, I'll merge it into the stable branch

**Comment by 92U235** [comment]
Thanks George. 
[2019.02.11.zip](https://github.com/miranda-ng/miranda-ng/files/2849414/2019.02.11.zip)
Updated Miranda - restarted - ran 'Create statistics' - crash.
Log attached

**Comment by 92U235** [comment]
Tried on another PC using the latest alpha w/ debug symbols (not sure if this is helpful, disregard if not) - crashes as well:
[2019.02.11_2.zip](https://github.com/miranda-ng/miranda-ng/files/2849504/2019.02.11_2.zip)

**Comment by georgehazan** [comment]
Nightly build gets compiled at 0100 GMT+0300, so that's simply old dll (the fact that a fix is committed doesn't mean that a build is compiled). Update it now and retry
