### ISSUE TITLE
Зависание миранды после выхода из спящего режима

### ISSUE THREAD

**Issue by Mataes** [miranda-ng/miranda-ng#1838]
ntdll.dll!_NtWaitForAlertByThreadId@8()	Unknown
 	ntdll.dll!RtlAcquireSRWLockExclusive()	Unknown
 	libmdbx.mir!mdbx_mapresize(MDBX_env * env=0x02740878, const unsigned int size_pgno=30720, const unsigned int limit_pgno=131072) Line 2245	C
 	libmdbx.mir!mdbx_page_alloc(MDBX_cursor * mc=0x0019dc00, unsigned int num=1, MDBX_page * * mp=0x0019d0d8, int flags=33554447) Line 2700	C
 	libmdbx.mir!mdbx_page_touch(MDBX_cursor * mc=0x0019dc00) Line 2877	C
 	libmdbx.mir!mdbx_cursor_touch(MDBX_cursor * mc=0x0019dc00) Line 8174	C
 	libmdbx.mir!mdbx_cursor_put(MDBX_cursor * mc=0x0019dc00, iovec * key=0x0019f068, iovec * data=0x0019f074, unsigned int flags=0) Line 8354	C
>	libmdbx.mir!mdbx_put(MDBX_txn * txn=0x00691ad0, unsigned int dbi=4, iovec * key=0x0019f068, iovec * data=0x0019f074, unsigned int flags=0) Line 11229	C
 	Dbx_mdbx.dll!CDbxMDBX::MarkEventRead(unsigned int contactID=65, unsigned int hDbEvent=125612) Line 400	C++
 	mir_core.mir!db_event_markRead(unsigned int hContact=65, unsigned int hDbEvent=125612) Line 406	C++
 	IEView.dll!HTMLBuilder::appendEventOld(IEView * view=0x02aefa80, IEVIEWEVENT * event=0x0019f1d4) Line 258	C++
 	IEView.dll!IEView::appendEventOld(IEVIEWEVENT * event=0x0019f1d4) Line 922	C++
 	IEView.dll!HandleIEEvent(unsigned int __formal=0, long lParam=1700308) Line 81	C++
 	mir_core.mir!CallService(const char * name=0x079af260, unsigned int wParam=0, long lParam=1700308) Line 595	C++
 	TabSRMM.dll!CTabBaseDlg::StreamInEvents(unsigned int hDbEventFirst=356052212, int count=1, int fAppend=1, DBEVENTINFO * dbei_s=0x00000000) Line 1246	C++
 	TabSRMM.dll!CTabBaseDlg::DM_EventAdded(unsigned int hContact=65, long lParam=125612) Line 1183	C++
 	TabSRMM.dll!CSrmmWindow::DlgProc(unsigned int uMsg=1336, unsigned int wParam=65, long lParam=125612) Line 2592	C++
 	mir_core.mir!CDlgBase::GlobalDlgProc(HWND__ * hwnd=0x0014037c, unsigned int msg=1336, unsigned int wParam=65, long lParam=125612) Line 387	C++
 	user32.dll!__InternalCallWinProc@20()	Unknown
 	user32.dll!UserCallDlgProcCheckWow()	Unknown
 	user32.dll!DefDlgProcWorker()	Unknown
 	user32.dll!_DefDlgProcW@16()	Unknown
 	mir_core.mir!mir_callNextSubclass(HWND__ * hWnd=0x0014037c, long(__stdcall*)(HWND__ *, unsigned int, unsigned int, long) wndProc=0x07603a4d, unsigned int uMsg=1336, unsigned int wParam=65, long lParam=125612) Line 168	C++
 	SmileyAdd.dll!MessageDlgSubclass(HWND__ * hwnd=0x0014037c, unsigned int uMsg=1336, unsigned int wParam=65, long lParam=125612) Line 90	C++
 	mir_core.mir!mir_callNextSubclass(HWND__ * hWnd=0x0014037c, long(__stdcall*)(HWND__ *, unsigned int, unsigned int, long) wndProc=0x076071c7, unsigned int uMsg=1336, unsigned int wParam=65, long lParam=125612) Line 164	C++
 	SmileyAdd.dll!RichEditOwnerSubclass(HWND__ * hwnd=0x0014037c, unsigned int uMsg=1336, unsigned int wParam=65, long lParam=125612) Line 368	C++
 	mir_core.mir!mir_callNextSubclass(HWND__ * hWnd=0x0014037c, long(__stdcall*)(HWND__ *, unsigned int, unsigned int, long) wndProc=0x07628fba, unsigned int uMsg=1336, unsigned int wParam=65, long lParam=125612) Line 164	C++
 	SpellChecker.dll!OwnerProc(HWND__ * hwnd=0x0014037c, unsigned int msg=1336, unsigned int wParam=65, long lParam=125612) Line 523	C++
 	mir_core.mir!MSubclassWndProc(HWND__ * hwnd=0x0014037c, unsigned int uMsg=1336, unsigned int wParam=65, long lParam=125612) Line 43	C++
 	user32.dll!__InternalCallWinProc@20()	Unknown
 	user32.dll!UserCallWinProcCheckWow()	Unknown
 	user32.dll!DispatchMessageWorker()	Unknown
 	user32.dll!_DispatchMessageW@4()	Unknown
 	mir_app.mir!mir_main(wchar_t * cmdLine) Line 381	C++
 	Miranda32.exe!wWinMain(HINSTANCE__ * __formal=0x00400000, HINSTANCE__ * __formal=0x00000000, wchar_t * cmdLine=0x006925f0, int __formal=1) Line 62	C++
 	[Inline Frame] Miranda32.exe!invoke_main() Line 118	C++
 	Miranda32.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!@BaseThreadInitThunk@12()	Unknown
 	ntdll.dll!__RtlUserThreadStart()	Unknown
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown

**Comment by georgehazan** [comment]
а держит-то его кто?

**Comment by Mataes** [comment]
а блин, не посмотрел. теперь уже и не узнаем(

**Comment by georgehazan** [comment]
ok, еще раз зависнет - посмотри, какой поток вцепился в базу.
