### ISSUE TITLE
ICQ: если у контакта на старом протоколе в базе был ключ "email", такой контакт при каждом логине будет выкидываться в NotInList (с потенциальным просёром истории), а вместо него создаётся MRA-контакт

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1847]
Можно просто ДО подключения проверять, есть ли у аськоконтактов (мы ведь можем отличить аськоконтакты от мрашников) этот проблемный ключ и стирать его.

**Comment by georgehazan** [comment]
для существующих акков придется сносить ключ e-mail руками
проще всего делать это с помощью dbeditor++
