### ISSUE TITLE
SkypeWeb duplicates some outgoing messages in history

### ISSUE THREAD

**Issue by rand256** [miranda-ng/miranda-ng#1849]
After #1777 was fixed there appeared new similar and a bit ironical issue: SkypeWeb now sometimes puts into history duplicated random _outgoing_ message.

It is happening only for a single message at a time and only when posting it. 
I.e.: you write message -> press enter -> you have your sent message appear twice in the log. 
Remote contact doesn't receive it, so it seems to be purely local issue: a duplicate actually doesn't getting sent, it only pollutes local history of the sender.

Duplicated outgoing message has the same timestamp and everything in the history.
It happens rarely, maybe once a week.

**Comment by georgehazan** [comment]
@rand256 I need a network log with the duplicated message

**Comment by rand256** [comment]
@georgehazan 

Here you go: https://pastebin.com/Fy076hz7
Message with text "test message 152" got duplicated.

Also: https://pastebin.com/zZG04F1c
Here message with text "test message 113" got duplicated, but the log looks a bit different from above.

Remote contact didn't receive duplicated messages, they are local only.
