### ISSUE TITLE
ICQ8+ adds second 0A char at each message's end which causes an empty line

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#185]
**Reported by Eagle on 2 Apr 2013 14:03 UTC**
As [already known](https://pidgin.im/pipermail/tracker/2013-February/078439.html) by the devs of Pidgin, the newest ICQ protocol version acts different when it comes to line endings:

Instead of a single UTF-8 character (0A), the newest version transmits two of these characters.

This results in MNG showing an empty line after _each_ message of _any_ ICQ contact.

Please fix this and additionally provide a solution for fixing older history-entries which suffered from this bug.

Thanks in advance & best regards,
 Martin

**Comment by georgehazan** [comment]
**Comment by eximido on 8 Apr 2014 09:18 UTC**
Ok, since #645 was closed as duplicate of this ticket, I suppose it should be noted here that this defect currently applies only to scriver messaging plugin, and tabSRMM is not affected by this now as well as history++ plugin too.

**Comment by dartraiden** [comment]
We implementing new protocol, so this ticket can be closed.
