### ISSUE TITLE
tox: краш при подключении

### ISSUE THREAD

**Issue by Mataes** [miranda-ng/miranda-ng#1850]
>	Tox.dll!dht_connect_after_load(DHT * dht=0x0c620020) Line 2914	C	Symbols loaded.
 	Tox.dll!do_dht(DHT * dht=0x0c620020) Line 2769	C	Symbols loaded.
 	Tox.dll!do_messenger(Messenger * m=0x36910eb0, void * userdata=0x07d7fdc4) Line 2618	C	Symbols loaded.
 	Tox.dll!tox_iterate(Tox * tox=0x09fb8640, void * user_data=0x02768588) Line 748	C	Symbols loaded.
 	Tox.dll!CToxProto::OnToxPoll(void * arg=0x02768588, unsigned char __formal='\x1') Line 84	C++	Symbols loaded.
 	ntdll.dll!_RtlpTpTimerCallback@12()	Unknown	Non-user code. Symbols loaded.
 	ntdll.dll!_TppTimerpExecuteCallback@8()	Unknown	Non-user code. Symbols loaded.
 	ntdll.dll!_TppWorkerThread@4()	Unknown	Non-user code. Symbols loaded.
 	kernel32.dll!@BaseThreadInitThunk@12()	Unknown	Non-user code. Symbols loaded.
 	ntdll.dll!___RtlUserThreadStart@8()	Unknown	Non-user code. Symbols loaded.
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown	Non-user code. Symbols loaded.

  | Name | Value | Type
-- | -- | -- | --
  | dht | 0x0c620020 {...} | DHT *
  | i | 2 | unsigned int
  | index | Variable is optimized away and not available. |

**Comment by georgehazan** [comment]
надо репортить это в libtox, потому что для того, чтобы это исправить, надо переписать половину, и я точно не буду этим заниматься
