### ISSUE TITLE
при изменении субконтакта в метаконтакте не меняется значок клиента в инфопанеле tabsrmm

### ISSUE THREAD

**Issue by Mataes** [miranda-ng/miranda-ng#1851]
![scr_tab](https://user-images.githubusercontent.com/3987390/53078574-8bea2f80-3505-11e9-8ce4-1f05721b1f78.png)

**Comment by georgehazan** [comment]
похоже, что в профиле засела с давних пор переменная MirVer в метаконтакте, надо ее просто прибить. если не поможет, переоткрой

**Comment by Mataes** [comment]
Mirver в базе для метаконтакта нет.
