### ISSUE TITLE
Skype plugin keeps going offline: The Skype plugin works pretty well but at least twice a day or more, it just goes offline and I need to reconnect manually. By comparison, the Facebook plugin seems to stay online.

### ISSUE THREAD

**Issue by Tekwizz** [miranda-ng/miranda-ng#1860]
### Expected behavior
What did you expect?

I expected the Skype plugin to stay connected, or to reconnect automatically if it disconnects.

### Actual behavior
What did you get instead?

I keep finding it is disconnected and I need to reconnect manually. This happens both here and on a remote PC. Windows 10 of different builds.

### Does it work in stable version?
If you know in which dev build (or approximate date when) it was broken, it may be much easier to identify and fix the issue.

The latest current one. The stable version. I just updated it a day ago through a web update.

I am pasting the version info below.

### Steps to reproduce that behavior
 * Provide step-by-step instructions so we can reproduce the issue (We can't fix what we can't reproduce).
 * Attach your VersionInfo.
 * Attach a crash report if you are experiencing crashes (It includes VersionInfo as well).
 * Attach a network log captured if you are experiencing connectivity issues.
 * If Miranda freezes, hangs up or consumes CPU, attach information obtained by Process Explorer tool.

I just stay on Skype all the time and it just drops it after varying amounts of time.

Here is the version info:

[spoiler=VersionInfo][quote]CPU: Intel(R) Pentium(R) CPU G2030 @ 3.00GHz [Intel64 Family 6 Model 58 Stepping 9] [DEP Enabled] [2 CPUs]
Installed RAM: 3968 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 16299)
Internet Explorer: 9.11.16299.0 (build 916299)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | English/English
Free disk space on Miranda partition: 245166 MBytes

Miranda NG Version: 0.95.10.1 build #21413 (1367e7c22f) x64
Build time: 15 Feb 2019 18:51:54
Profile: C:\Users\RABICA\AppData\Roaming\Miranda NG\Home\Home.dat
Profile size: 2097152 Bytes
Profile creation date: 16 Jan 2019 18:58:31
Language pack: No language pack installed
Service Mode: No

[b]Active Plugins (18):[/b]
¤ AVS.dll v.[b]0.98.1.1[/b] [15 Feb 2019 18:51:58] - Avatar service 
¤ Clist_modern.dll v.[b]0.9.1.8[/b] [15 Feb 2019 18:52:34] - Modern contact list 
¤ CrashDumper.dll v.[b]0.1.0.3[/b] [15 Feb 2019 18:52:28] - Crash dumper 
¤ Db_autobackups.dll v.[b]0.1.0.2[/b] [15 Feb 2019 18:52:10] - Db autobackuper 
¤ Dbx_mdbx.dll v.[b]0.95.9.1[/b] [15 Feb 2019 18:53:24] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.[b]0.95.8.1[/b] [15 Feb 2019 18:51:58] - Miranda NG mmap database driver 
¤ Dummy.dll v.[b]0.2.0.0[/b] [15 Feb 2019 18:53:00] - Dummy protocol 
¤ Facebook.dll v.[b]0.4.2.1[/b] [15 Feb 2019 18:52:30] - Facebook 
¤ GG.dll v.[b]0.95.11.1[/b] [15 Feb 2019 18:52:20] - Gadu-Gadu protocol 
¤ ICQ.dll v.[b]0.95.11.3[/b] [15 Feb 2019 18:53:18] - ICQ-WIM protocol 
¤ Import.dll v.[b]0.95.10.1[/b] [15 Feb 2019 18:52:10] - Import contacts and messages 
¤ IRC.dll v.[b]0.95.10.1[/b] [15 Feb 2019 18:52:02] - IRC protocol 
¤ Jabber.dll v.[b]0.11.0.5[/b] [15 Feb 2019 18:52:30] - Jabber protocol 
¤ MSN.dll v.[b]0.95.11.1[/b] [15 Feb 2019 18:52:16] - MSN protocol 
¤ PluginUpdater.dll v.[b]0.2.0.2[/b] [15 Feb 2019 18:52:32] - Plugin updater 
¤ SkypeWeb.dll v.[b]0.12.3.2[/b] [15 Feb 2019 18:53:10] - Skype protocol (Web) 
¤ TabSRMM.dll v.[b]3.5.0.12[/b] [15 Feb 2019 18:52:06] - TabSRMM 
¤ TopToolBar.dll v.[b]0.8.0.5[/b] [15 Feb 2019 18:52:20] - TopToolBar 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
Facebook                 1 - Enabled 0 - Disabled  Loaded
SKYPE                    1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 Proto_Dummy.dll [15 Feb 2019 18:53:36]
 Proto_Facebook.dll [15 Feb 2019 18:53:36]
 Proto_GG.dll [15 Feb 2019 18:53:36]
 Proto_ICQ.dll [15 Feb 2019 18:53:36]
 Proto_IRC.dll [15 Feb 2019 18:53:36]
 Proto_Jabber.dll [15 Feb 2019 18:53:36]
 Proto_MetaContacts.dll [15 Feb 2019 18:53:36]
 Proto_MRA.dll [15 Feb 2019 18:53:36]
 Proto_MSN.dll [15 Feb 2019 18:53:36]
 Proto_Skype.dll [15 Feb 2019 18:53:36]
 TabSRMM_icons.dll [15 Feb 2019 18:53:36]
 Toolbar_icons.dll [15 Feb 2019 18:53:36]
 xStatus_Jabber.dll [15 Feb 2019 18:53:36]
[/quote][/spoiler]

Thank you!

**Comment by Tekwizz** [comment]
The Skype plugin works pretty well but at least twice a day or more, it just goes offline and I need to reconnect manually. By comparison, the Facebook plugin never seems to go offline.

**Comment by georgehazan** [comment]
just install StatusManager plugin, it will reconnect your accounts automatically
