### ISSUE TITLE
непонятная иконка в tabsrmm

### ISSUE THREAD

**Issue by Mataes** [miranda-ng/miranda-ng#1861]
![image](https://user-images.githubusercontent.com/3987390/53286506-c6abcc00-3780-11e9-8734-1c14492177dc.png)
непонятно что это должно выводиться в этой иконке. периодически там бывают всякие разные значки

**Comment by georgehazan** [comment]
посмотри на оверлеи в фингере

**Comment by georgehazan** [comment]
по коду туда сбрасывается какой-то шлак, который не влезает в иконку статуса, например, typing notification, яхз, кем у тебя работает этот + , надо смотреть в опции иконок
