### ISSUE TITLE
SkypeWeb can't login new account (without skype username)

### ISSUE THREAD

**Issue by rand256** [miranda-ng/miranda-ng#1862]
Seems it's impossible to login to Skype with newly registered account. I guess I should use the e-mail address as username - so it just... starts connecting for a couple seconds and stops.

Here's network log: https://pastebin.com/MYdYeG3Z

I've also tried using live:username as a login, it also fails.
Logging the older account that has "classic" username without "live:" works fine for sure.

**Comment by georgehazan** [comment]
@leecher1337 would you please look at this problem with skype login?

**Comment by leecher1337** [comment]
@georgehazan User mentions this is a Skypeweb plugin problem, I wrote MSN plugin and I'm using it for my Skype connections, but I don't have the faintest idea about SkypeWeb plugin, I never used it. Please assign to SkypeWeb author.

**Comment by georgehazan** [comment]
that's a problem with Skype login. you applied it to MSN, remember?

**Comment by leecher1337** [comment]
I don't understand...

[16:24:59 2FBC] [SKYPE_1] CSkypeProto::SetStatus: changing status from 40071 to 40072

CSykpeProto is a class of SkypeWeb, not MSN protocol. I never worked on SkypeWeb protocol.

**Comment by georgehazan** [comment]
yes, but you grabbed a SkypeLogin library and applied it to MSN :) 
maybe you know something about Skype logins, because I know nothing about it

**Comment by leecher1337** [comment]
You mean the SkyLogin library that I wrote back in 2015?
https://github.com/msndevs/skylogin/
It implements the login method of the Skype Client, I don't think that it has any relationship with a pure web application like SkypeWeb whih uses other authentication schemes.

**Comment by rand256** [comment]
Is #554 related to this issue maybe? Although there was an old skype account linked to MS account while this issue is about logging in with entirely new MS account.

**Comment by leecher1337** [comment]
Why don't you use MSN plugin, if you have an MSN account to Skype anyway?

**Comment by rand256** [comment]
I didn't know it's possible.

However MSN plugin works not much better than SkypeWeb plugin in many cases. I see no way to add Skype contacts from there (a contact is added but never receices messages) and it doesn't receive auth requests as well (from both miranda and official web skype), a weird mess is happening in "MSN settings" -> "Server list" menu, typing notifications doesn't work, etc. However, if manage contact list beforehand in another client then simple chatting seems possible via MSN for new Skype accounts.

So, thanks for your advice.

**Comment by rand256** [comment]
FYI, logging into Skype via MSN plugin suddenly stopped working around 3 days ago.
Complains about bad credentials in the log.

**Comment by leecher1337** [comment]
Now also stopped working for me, login servers always return an error... 
Anyone there who knows how to fix it? 
I tried to bump client version ID string in login library, but to no avail, it still rejects login.

**Comment by leecher1337** [comment]
I checked the new Skype executables and cannot find any signs of MSNP24 protocol in them anymore. It's some ugly Electron web-based bloatware-client now. So I think Skype support is dead for now, unless someone will reverse-engineer the new protocol that they are using in Skype 8. Could be that it is some HTTPS-based crap now.

https://wink.messengergeek.com/t/microsoft-ending-support-for-classic-skype-version-7-n-o-v-e-m-b-e-r-1-january-8/6131

**Comment by leecher1337** [comment]
As I was asked by @georgehazan on the now authentication process, here are some hints:

1) Use OAUTH20 authentication like usual with service::lw.skype.com::MBI_SSL scope:
https://github.com/msndevs/protocol-docs/wiki/Authentication#authenticating-with-oauth

2) You receive an access_token. POST
```
{
    "access_token": "THE_ACCESS_TOKEN_YOU_RECEIVED",
    "clientVersion": "1433/8.42.0.60",
    "scopes": "client",
    "site_name": "lw"
}
```
to https://edge.skype.com/rps/v1/rps/skypetoken 
and you will receive a skypetoken in response:

```
{
    "expiresIn": 86398,
    "signinname": "user@hotmail.com",
    "skypeid": "user",
    "skypetoken": "eyJhb..."
}
```

3) Tell Skype that you logged in by POSTing
`skypetoken=THE_SKYPETOKEN_YOU_RECEIVED`
to https://api.asm.skype.com/v1/skypetokenauth

The nuse the X-Skypetoken like normal in Skypeweb.
Hope that helps.

**Comment by leecher1337** [comment]
Regarding the original problem of @rand256, it seems that one needs to login to the account via http://login.live.com, then go ot Security and click on check last activity.
You then will get redirected to a site where you need to verify your e-mail address via a code being sent to you. When done, SkypeWeb login worked for me again.
