### ISSUE TITLE
Иероглифы в jabber

### ISSUE THREAD

**Issue by apollo2k4** [miranda-ng/miranda-ng#1864]
![img](https://i.imgur.com/IMLBbaa.png)

**Comment by obs1dium** [comment]
Also affects displayed file names in file transfers.

**Comment by georgehazan** [comment]
@obs1dium what am I doing wrong?
https://i.imgur.com/XuYrzsi.png

**Comment by obs1dium** [comment]
It looked like this when I updated last Friday, had to perform a rollback to fix it:
![snap](https://user-images.githubusercontent.com/8465955/53364573-61520980-393f-11e9-8e6d-896a955ce0a9.png)
I just ran the update again and so far everything seems normal.

**Comment by georgehazan** [comment]
@obs1dium thanks, fixed
