### ISSUE TITLE
Joining Password Protected Jabber Conference is not working since last updates

### ISSUE THREAD

**Issue by pl4hh** [miranda-ng/miranda-ng#1865]
### Expected behavior
When joining a conference on a jabber server with password protection it should send the password.

### Actual behavior
Getting a 401 error, this conference is password protected.
`
<error code="401" type="auth">
<not-authorized xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" />
<text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">
A password is required to enter this room
</text>
</error>
`
### Does it work in stable version?
Shadowcopy-restored my miranda folder to a version 3 days ago. Then it works as usual.

### Steps to reproduce that behavior
XML Log with the Problem (no password is being sent)
`<presence xml:lang="en" to="XXXXX" from="XXXXXX" type="error">
<c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="http://miranda-ng.org/caps" ver="27XcWflg706F2HoE4+nr70eG1Qs=" ext="secureim mirotr x64 mood tune activity mir_notes" />
<x xmlns="vcard-temp:x:update">
<photo />
</x>
<error code="401" type="auth">
<not-authorized xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" />
<text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">
A password is required to enter this room
</text>
</error>
<priority>
1
</priority>
<show>
xa
</show>
<status>
Give it up, I'm not in!
</status>
</presence>`

XML output from working connect:

`<presence to="XXXX">
<priority>1</priority>
<x xmlns="http://jabber.org/protocol/muc">
<password>PASSWORD</password>
</x>
<c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="http://miranda-ng.org/caps" ver="/FXZ8ycWE0ln3YNM3mVN1/rgGZs=" ext="secureim mirotr x64 mood tune activity mir_notes" />
<x xmlns="vcard-temp:x:update">
<photo>XXXXX</photo>
</x>
<show>xa</show>
<status>Give it up, I'm not in!</status>
</presence>`

Version info from working jabber (i only restored plugins and icon, not the executable)
Miranda NG Version: 0.95.11 alpha build #21361 (bd864aa049) x64
¤ AVS.dll v.0.95.11.0 [8 Feb 2019 2:11:46] - Avatar service 
¤ Clist_nicer.dll v.0.95.11.0 [2 Feb 2019 2:03:24] - Clist nicer 
¤ CrashDumper.dll v.0.95.11.0 [8 Feb 2019 2:12:22] - Crash dumper 
¤ CryptoPP.dll v.0.95.11.0 [8 Feb 2019 2:14:20] - Crypto++ 
¤ Db_autobackups.dll v.0.95.11.0 [8 Feb 2019 2:11:54] - Db autobackuper 
¤ Dbx_mdbx.dll v.0.95.11.0 [8 Feb 2019 2:14:16] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.0.95.11.0 [8 Feb 2019 2:11:44] - Miranda NG mmap database driver 
¤ Dbx_sqlite.dll v.0.95.11.0 [2 Feb 2019 2:04:30] - Miranda NG SQLite database driver 
¤ Dummy.dll v.0.95.11.0 [8 Feb 2019 2:13:22] - Dummy protocol 
¤ historypp.dll v.1.5.1.5 [8 Feb 2019 2:26:16] - History++ 
¤ ICQ.dll v.0.95.11.0 [8 Feb 2019 2:13:46] - ICQ-WIM protocol 
¤ Import.dll v.0.95.11.0 [8 Feb 2019 2:11:58] - Import contacts and messages 
¤ IRC.dll v.0.95.11.0 [8 Feb 2019 2:11:48] - IRC protocol 
¤ Jabber.dll v.0.95.11.0 [8 Feb 2019 2:12:28] - Jabber protocol 
¤ MirOTR.dll v.0.95.11.0 [2 Feb 2019 2:04:48] - Miranda OTR 
¤ OpenSSL.dll v.0.95.11.0 [26 Jan 2019 2:04:18] - OpenSSL SSL API module 
¤ PluginUpdater.dll v.0.95.11.0 [8 Feb 2019 2:12:30] - Plugin updater 
¤ Scriver.dll v.0.95.11.0 [2 Feb 2019 2:03:20] - Scriver 
¤ SecureIM.dll v.0.95.11.0 [8 Feb 2019 2:12:00] - SecureIM 
¤ Sessions.dll v.0.95.11.0 [2 Feb 2019 2:03:30] - Sessions 
¤ SkypeWeb.dll v.0.95.11.0 [8 Feb 2019 2:13:34] - Skype protocol (Web) 
¤ TopToolBar.dll v.0.95.11.0 [2 Feb 2019 2:03:38] - TopToolBar 

Let me know if more info is needed.

**Comment by georgehazan** [comment]
thanks for the clear explanation, that was easy :)

**Comment by pl4hh** [comment]
Nice, thanks for all the effort, will test it tomorrow :)
