### ISSUE TITLE
при смене субконтакта не меняется аватарка в логе сообщений ieview и в таскбаре

### ISSUE THREAD

**Issue by Mataes** [miranda-ng/miranda-ng#1866]
![image](https://user-images.githubusercontent.com/3987390/53441175-42bf4180-3a17-11e9-8338-8017aa81b519.png)

**Comment by georgehazan** [comment]
в логе она и не должна меняться, она туда вписывается навечно из конкретного события, куда записан конкретный протокол саба, приславшего это сообщение
