### ISSUE TITLE
ICQ/Jabber: перестали синхронизироваться исходящие сообщения

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1870]
Если я общаюсь с телефона, то в Миранду не прилетают мои собственные исходящие реплики.

В ICQ такая же картина.

**Comment by georgehazan** [comment]
в жабере надо включить поддержку carbon copies, ибо достает несусветно
![image](https://user-images.githubusercontent.com/4628541/53560349-38a75b00-3b5d-11e9-926a-27121b817a57.png)
про аську надо смотреть

**Comment by dartraiden** [comment]
Она включена, но ничего не прилетает.
