### ISSUE TITLE
ICQ: режим невидимости

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1873]
"Можно даже сообщения отправлять не появляясь в сети, если не запрашивать fetchBaseURL."
https://forum.miranda-ng.org/index.php?topic=5619.msg24371#msg24371

> 
> dartraiden, 01.03.2019 17:37:16:
> ну типа ты отправляешь мессаги, но тебя не видят в онлайне
> 
> dartraiden, 17:37:33:
> можешь общаться с каким-то человм, а другие челы тебя не видят

**Comment by georgehazan** [comment]
тяжелый вопрос. на самом деле сейчас в Миранде корректно поддержан invisible для ICQ-WIM, надо попробовать задействовать его

**Comment by georgehazan** [comment]
это уже реализовано другим способом
