### ISSUE TITLE
SkypeWeb: disconnect error - "netlibopenconn.cpp 713: connect() failed (0)"

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#1874]
Disconnect error on:
" w:\miranda-build\src\mir_app\src\netlibopenconn.cpp 713: connect() failed (0)"
netlog:
[skype_error_netlog.txt](https://github.com/miranda-ng/miranda-ng/files/2922483/skype_error_netlog.txt)

**Comment by georgehazan** [comment]
да хрен его знает... оно попыталось зайти на сервер, попало на таймаут, а потом пытается закрыть это и пишет в лог какую-то ерунду
