### ISSUE TITLE
ICQ: защита от случайного стирания сессии

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1878]
Если пользователь сдуру при работающей Миранде убьёт все открытые сессии, то Миранда никогда не получит сообщения, которые были ей отправлены. При следующем логине Миранда, конечно, создаст новую сессию, но вот те сообщения, которые были посланы между стиранием сессий и созданием новой - пропали навсегда.

**Comment by georgehazan** [comment]
это почему они вдруг пропали, если они подсасываются теперь всегда?
