### ISSUE TITLE
Jabber: сломался редактор ростера

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1881]
Открываю редактор ростера. Жму Download, ростер скачивается.
Снимаю галку с кого-нибудь в серединке ростера. При каждом нажатии Upload галка снимается с очередного чувака, пока не снимется со всех.

Обратно галки не ставятся. Ставлю галку, жму Upliad - галка скидывается.

> [00:05]	dartraiden: снимаешь галку в редакторе ростера с кого-0нить
> [00:05]	dartraiden: делаешь много раз Upload
> [00:06]	dartraiden: и у твоих контактов по одному галки снимаются

**Comment by georgehazan** [comment]
а то, что он весь в квадратиках, тебя не взволновало? :)
