### ISSUE TITLE
Crash on PluginUpdater load

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1883]
- Disable PluginUpdater on Plugins settings page
- Hit Apply
- Enable PluginUpdater
- Hit Apply

Silent crash.

**Comment by dartraiden** [comment]
Same for CrashDumper/

**Comment by georgehazan** [comment]
не падает. нужен стек из студии

**Comment by dartraiden** [comment]
Перестало падать после рестарта винды.
