### ISSUE TITLE
Jabber: поддержка разделителя групп ::

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1884]
Чтобы создать дерево групп:
```
-Отдел 1
    +Сектор 1
    +Сектор 2
-Отдел 2
    +Сектор 1
    +Сектор 2
```

Необходимо использовать названия групп на сервере вида:
Отдел 1\Сектор 1
Отдел 1\Сектор 2
Отдел 2\Сектор 1
Отдел 2\Сектор 2

Как сделать чтобы миранда понимала разделитель :: ?
Отдел 1::Сектор 1
Отдел 1::Сектор 2
Отдел 2::Сектор 1
Отдел 2::Сектор 2

https://forum.miranda-ng.org/index.php?topic=5534

**Comment by georgehazan** [comment]
миранда это и так умеет
