### ISSUE TITLE
BossKey cannot close YAPP popups?

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1886]
https://github.com/miranda-ng/miranda-ng/blob/64723fbaae79b1bde53f9acfebe6eff1863141cb/plugins/BossKeyPlus/src/BossKey.cpp#L173

YAPPWinClass is not found in sources

**Comment by georgehazan** [comment]
а в чем проблема? имя класса окна не менялось, по понятным причинам

**Comment by dartraiden** [comment]
Проблема в том, что зажай поиском по коду YAPPWinClass - его нет вообще в исходниках Миранды.
