### ISSUE TITLE
Send Screenshot plugin no longer functional after most recent update

### ISSUE THREAD

**Issue by BlackCatte** [miranda-ng/miranda-ng#1890]
### Expected behavior
The Send Screenshot plugin (sendss.dll) should show a message window confirming if I would like to send the screenshot:

![image](https://user-images.githubusercontent.com/5046855/54038581-eeb01c00-41d1-11e9-8b2e-6ef9e1a6154a.png)

### Actual behavior
Now MsgPopup (msgpopup.dll) can't distinguish it as a pop up only having "Ok", so it hides the message window and converts it to a pop up:

![image](https://user-images.githubusercontent.com/5046855/54038620-04254600-41d2-11e9-9023-0b40a4acf3a8.png)

so I am no longer able to send screenshots. 

### Does it work in stable version?
Unsure. It was functioning as normal until the update on March 7th 2019.

### Steps to reproduce that behavior
1. Have sendss.dll enabled
2. Have msgpopup.dll enabled
3. Attempt to send screenshot
4. Instead of receiving normal confirmation message ( https://i.ibb.co/qCmFcyB/image.png ), a popup will be shown instead ( https://i.ibb.co/xzybKgc/image.png ), and the confirmation message is hidden from view.

-------------------------------------------------------------------------------

**### Version info:**
CPU: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz [Intel64 Family 6 Model 94 Stepping 3] [DEP Enabled] [4 CPUs]
Installed RAM: 8151 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 17134)
Internet Explorer: 9.11.17134.0 (build 917134)
OS Languages: (UI | Locale (User/System)) : English/English | English/English
Free disk space on Miranda partition: 919659 MBytes

**Miranda NG Version: 0.95.11 alpha build #21569 (9996211543) x64**
Build time: 8 Mar 2019 15:34:22
Profile: F:\Miranda NG\Profiles\Zack\Zack.dat
Profile size: 6692864 Bytes
Profile creation date: 6 Feb 2019 13:23:27
Language pack: No language pack installed
Service Mode: No

**Active Plugins (26):**
¤ AVS.dll v.[b]0.98.1.1[/b] [5 Mar 2019 18:48:36] - Avatar service 
¤ BasicHistory.dll v.[b]1.0.1.10[/b] [7 Mar 2019 2:04:06] - Basic history 
¤ Clist_modern.dll v.[b]0.9.1.8[/b] [5 Mar 2019 18:49:10] - Modern contact list 
¤ CrashDumper.dll v.[b]0.1.0.3[/b] [7 Mar 2019 2:03:48] - Crash dumper 
¤ Db_autobackups.dll v.[b]0.1.0.3[/b] [8 Mar 2019 15:34:34] - Db autobackuper 
¤ Dbx_mdbx.dll v.[b]0.95.9.1[/b] [8 Mar 2019 15:35:46] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.[b]0.95.8.1[/b] [8 Mar 2019 15:34:28] - Miranda NG mmap database driver 
¤ Discord.dll v.[b]0.6.1.4[/b] [8 Mar 2019 15:35:32] - Discord protocol 
¤ Facebook.dll v.[b]0.4.2.1[/b] [8 Mar 2019 15:34:54] - Facebook 
¤ Folders.dll v.[b]0.2.0.2[/b] [6 Feb 2019 2:05:12] - Custom profile folders 
¤ IEView.dll v.[b]1.6.0.2[/b] [1 Mar 2019 2:03:06] - IEView 
¤ Import.dll v.[b]0.95.10.1[/b] [8 Mar 2019 15:34:42] - Import contacts and messages 
¤ IRC.dll v.[b]0.95.10.1[/b] [27 Feb 2019 2:03:06] - IRC protocol 
¤ Jabber.dll v.[b]0.11.0.5[/b] [8 Mar 2019 15:35:02] - Jabber protocol 
¤ MenuEx.dll v.[b]1.3.2.0[/b] [7 Mar 2019 2:03:20] - Menu item ext 
¤ MirOTR.dll v.[b]0.14.2.1[/b] [8 Mar 2019 15:35:54] - Miranda OTR 
¤ MsgPopup.dll v.[b]0.1.2.1[/b] [7 Mar 2019 2:04:00] - Message popup 
¤ PluginUpdater.dll v.[b]0.2.0.3[/b] [7 Mar 2019 2:03:48] - Plugin updater 
¤ SendSS.dll v.[b]0.9.0.2[/b] [7 Mar 2019 2:03:50] - Send ScreenShot+ 
¤ SpellChecker.dll v.[b]0.2.6.6[/b] [8 Mar 2019 15:35:24] - Spell checker 
¤ TabSRMM.dll v.[b]3.5.0.13[/b] [8 Mar 2019 15:34:32] - TabSRMM 
¤ TopToolBar.dll v.[b]0.8.0.5[/b] [6 Feb 2019 2:05:22] - TopToolBar 
¤ Tox.dll v.[b]0.11.3.2[/b] [7 Mar 2019 2:04:44] - Tox protocol 
¤ Variables.dll v.[b]0.2.3.11[/b] [6 Feb 2019 2:05:38] - Variables 
¤ Watrack.dll v.[b]0.0.6.12[/b] [7 Mar 2019 2:04:58] - Winamp Track 
¤ Watrack_MPD.dll v.[b]0.0.0.4[/b] [8 Feb 2019 2:12:28] - Watrack MPD 

Protocols and Accounts:
Discord                  1 - Enabled 0 - Disabled  Loaded
JABBER                   1 - Enabled 0 - Disabled  Loaded

Icon Packs:
 Flags_icons.dll [8 Mar 2019 15:36:04]
 Proto_Discord.dll [8 Mar 2019 15:36:04]
 Proto_Dummy.dll [8 Mar 2019 15:36:04]
 Proto_Facebook.dll [8 Mar 2019 15:36:04]
 Proto_IRC.dll [27 Feb 2019 2:04:34]
 Proto_Jabber.dll [8 Mar 2019 15:36:04]
 Proto_MetaContacts.dll [8 Mar 2019 15:36:04]
 Proto_Tox.dll [7 Mar 2019 2:04:56]
 TabSRMM_icons.dll [8 Mar 2019 15:36:04]
 Toolbar_icons.dll [5 Mar 2019 18:50:20]
 Watrack_buttons.dll [7 Mar 2019 2:04:58]
 Watrack_icons.dll [7 Mar 2019 2:04:58]
 xStatus_Jabber.dll [8 Mar 2019 15:36:04]

**Comment by dartraiden** [comment]
Normal behaviour: left click on popup should send screenshot. Right click should dismiss.

**Comment by georgehazan** [comment]
@dartraiden nope, popup shall not be displayed for questions at all, that's my fault

**Comment by dartraiden** [comment]
ah I missed

> those having only OK button

in MsgPopup description
