### ISSUE TITLE
ICQ-WIM: Проблема с контактами UIN=*@mail.ru

### ISSUE THREAD

**Issue by mpioner** [miranda-ng/miranda-ng#1895]
После переезда на ICQ-WIM, контакты у которых вместо номера были прописана почта mail.ru (UIN=*@mail.ru):
1. за дублировались в базе, видимо конвертировались в chatgroup.
2. пропала история сообщений, в контекстном меню отсутствует пункт истории. 

Протокол MRA не использовался. 

версия на которой с историей всё нормально:
[VersionInfo.txt](https://github.com/miranda-ng/miranda-ng/files/2957895/VersionInfo.txt)

На последних стабильных и ночниках проблема.

**Comment by dartraiden** [comment]
Мы исправили эту проблему несколько недель назад/ Если вы переехали до исправления, то через редактор базы удалите у контктактов почту/

**Comment by dartraiden** [comment]
Кроме того, я буду очень благодарен если вы через редактор базы выгрузите любой из проблемных контактов в .ini и пришлёте нам, можно приватно на wowemuh@gmail.com

**Comment by mpioner** [comment]
если закинуть старый профиль и не запускать fixme.cmd, то при первом запуске и выходе в онлайн, появляются два контакта, при этом у одного из них история работает. После перезапуска, контакт с историей пропадает. 
[VersionInfo.txt](https://github.com/miranda-ng/miranda-ng/files/2958165/VersionInfo.txt)

**Comment by dartraiden** [comment]
Ну да, это как раз и есть тот самый баг.

Изначально у вас один контакт, у которого прописано мыло @mail.ru. Новый протокол думает, что это MRA-контакт. При выходе в сеть протокол подтягивает недостающие контакты с сервера (поскольку на сервере эти контакты ICQ, а в Миранде они уже MRA). История остаётся в MRA-контакта, а поскольку его на сервере нет, он стирается после перезапуска.

**Comment by dartraiden** [comment]
Ага, понятно.

Мы исправили ситуацию, когда у контакта ест ключ "e-mail" с почтой mail.ru

Оказывается, такой же эффект даёт ситуацию, когда вместо UIN мыло...

**Comment by georgehazan** [comment]
@mpioner надо проверить на девелоперской версии

**Comment by mpioner** [comment]
проверил.
закидываю старый профиль в новую ночную миранду, fixme.cmd не запускаю.
1. пропадает UIN в настройках.
2. все контакты ICQ дублируются, появляются прозрачные (c историей), обычные без истории. 
3. проблемные контакты *@mail.ru не дублируются.
4. Теперь появились много контактов [deleted], есть возможность не удалять оригинальный никнейм, а добавить [deleted] к нему?, так же хотелось бы что бы история таких контактов сохранялась!
5. После перезапуска миранды, программа не загружается, после запуска fixme.cmd запускается. 
6. Дубли контактов пропали, у нормальных контактов пропала вся история, история осталась только у тех у кого UIN  *@mail.ru

**Comment by dartraiden** [comment]
Тогда хотелось бы взглянуть на ini контакта до выхода в онлайн, а также на его ini, когда он "прозрачный" и на ini его дубликата, который без истории.

> 
Теперь появились много контактов [deleted], есть возможность не удалять оригинальный никнейм, а добавить [deleted] к нему?

Нет, мы показываем то, что пришло от сервера, а сервер вместо имени присылает "[deleted].

**Comment by mpioner** [comment]
INI отправил на почту.

>Нет, мы показываем то, что пришло от сервера, а сервер вместо имени присылает "[deleted]"
возможно  
Мой контакт лист настроен для отображение "My custom name" но после выхода онлайн он затирается и остаётся только поле IcqNick. Возможно не затирать custom и добавлять к нему [deleted]
На данный момент (Miranda NG Version: 0.95.11 alpha build #21604 (89c5b30b54) x64
) вся история контактов ICQ затирается после конвертации. 
Если нужно я могу создать отдельные кейсы по этим проблемам

**Comment by dartraiden** [comment]
Можно пример уина (чисто цифры), у которого имя [deleted]?

**Comment by mpioner** [comment]
414516955

**Comment by dartraiden** [comment]
Ну, вот, всё нормально, переименовал вручную (ПКМ по контакту → переименовать) и кастомное имя сохраняется.

![Miranda64_UmSkR0WhR8](https://user-images.githubusercontent.com/5046855/54344323-a4a3bc00-4651-11e9-811c-ec9d17e5f527.png)

Попробуйте конвертировать на сборке #21606  Если история перестанет пропадать и все контакты на месте и в нужном количестве, то можно переименовать [deleted] в желаемое имя.
