### ISSUE TITLE
Jabber/StdClist?: контакты не сохраняются в подгруппах

### ISSUE THREAD

**Issue by de77** [miranda-ng/miranda-ng#1896]
### Ожидаемое поведение
Ожидается, что после перезапуска Miranda-ng контакты, которые распределены по локально созданным подгруппам (subgroup) останутся в указанных подгруппах.

### Наблюдаемое поведение
После перезапуска Miranda-ng все контакты, остаются в локально созданных подгруппах, в которых они были распределены, но после подключения к серверу, контакты, которые находятся в онлайне, перемещаются в корневую группу, видимо созданную на сервере и после этого остаются в ней. Можно их опять переместить в подгруппы и до следующего перезапуска они будут находится в этих подгруппах.

### Работает ли это в стабильной версии?
Похоже подобное поведение присутствует ещё со времён miranda-im. Наблюдается в стабильной версии 0.95.10.1.

### Steps to reproduce that behavior
* подключаетесь к серверу
* создаёте подгруппу в группе
* переносите контакт, находящийся онлайн, из группы в созданную подгруппу
* выгружаете Miranda-ng
* запускаете Miranda-ng
* наблюдаете, что контакт, находящийся онлайн переместился из созданной подгруппы обратно в группу

### Сведения о версиях
[spoiler=VersionInfo][quote]CPU: Intel(R) Core(TM) i3 CPU 540 @ 3.07GHz [x86 Family 6 Model 37 Stepping 2] [DEP Enabled] [4 CPUs]
Installed RAM: 3582 MBytes
Microsoft Windows XP Professional Service Pack 3 (build 2600)
Internet Explorer: 6.0.2900.5512 (build 62900.5512)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian
Free disk space on Miranda partition: 23371 MBytes

Miranda NG Version: 0.95.10.1 build #21384 (c98ff02a2e)
Build time: 10 Feb 2019 18:27:56
Profile: D:\Program Files\Miranda NG\Profiles\profile\profile.dat
Profile size: 46137344 Bytes
Profile creation date: 16 Sep 2013 14:49:26
Language pack: No language pack installed
Service Mode: No

[b]Active Plugins (16):[/b]
¤ AVS.dll v.[b]0.98.1.1[/b] [10 Feb 2019 18:28:01] - Avatar service 
¤ CrashDumper.dll v.[b]0.1.0.3[/b] [10 Feb 2019 18:28:27] - Crash dumper 
¤ Db_autobackups.dll v.[b]0.1.0.2[/b] [10 Feb 2019 18:28:07] - Db autobackuper 
¤ DbEditorPP.dll v.[b]4.0.1.2[/b] [10 Feb 2019 18:28:28] - Database editor++ 
¤ Dbx_mdbx.dll v.[b]0.95.9.1[/b] [10 Feb 2019 18:29:16] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.[b]0.95.8.1[/b] [10 Feb 2019 18:28:01] - Miranda NG mmap database driver 
¤ Dummy.dll v.[b]0.2.0.0[/b] [10 Feb 2019 18:28:55] - Dummy protocol 
¤ HistoryPP.dll v.[b]1.5.1.5[/b] [10 Feb 2019 18:29:39] - History++ 
¤ ICQ.dll v.[b]0.95.11.2[/b] [10 Feb 2019 18:29:09] - ICQ-WIM protocol 
¤ Jabber.dll v.[b]0.11.0.5[/b] [10 Feb 2019 18:28:27] - Jabber protocol 
¤ OpenSSL.dll v.[b]0.1.0.2[/b] [10 Feb 2019 18:29:03] - OpenSSL SSL API module 
¤ PluginUpdater.dll v.[b]0.2.0.2[/b] [10 Feb 2019 18:28:32] - Plugin updater 
¤ SeenPlugin.dll v.[b]5.0.5.4[/b] [11 Feb 2019 14:05:25] - Last seen 
¤ SpellChecker.dll v.[b]0.2.6.6[/b] [10 Feb 2019 18:28:55] - Spell checker 
¤ TabSRMM.dll v.[b]3.5.0.12[/b] [10 Feb 2019 18:28:07] - TabSRMM 
¤ Tipper.dll v.[b]2.1.0.7[/b] [10 Feb 2019 18:28:14] - Tipper 

[b]Unloadable Plugins (1):[/b]
¤ DbChecker.dll v.[b]0.0.0.0[/b] [7 Nov 2017 23:04:51] - <unknown> 
    Plugin statically linked to missing module: mir_core.mir
    Plugin statically linked to missing module: mir_app.mir

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
ICQ                      1 - Enabled 0 - Disabled  Loaded
JABBER                   4 - Enabled 2 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 Flags_icons.dll [10 Feb 2019 18:29:31]
 HistoryPP_icons.dll [10 Feb 2019 18:29:31]
 Proto_AIM.dll [25 Aug 2017 18:14:46]
 Proto_Dummy.dll [10 Feb 2019 18:29:32]
 Proto_Facebook.dll [10 Feb 2019 18:29:31]
 Proto_GG.dll [10 Feb 2019 18:29:31]
 Proto_ICQ.dll [10 Feb 2019 18:29:32]
 Proto_IRC.dll [10 Feb 2019 18:29:31]
 Proto_Jabber.dll [10 Feb 2019 18:29:31]
 Proto_MetaContacts.dll [10 Feb 2019 18:29:32]
 Proto_MRA.dll [10 Feb 2019 18:29:32]
 Proto_MSN.dll [10 Feb 2019 18:29:31]
 TabSRMM_icons.dll [10 Feb 2019 18:29:32]
 Toolbar_icons.dll [10 Feb 2019 18:29:31]
 xStatus_ICQ.dll [13 Dec 2018 14:03:54]
 xStatus_Jabber.dll [10 Feb 2019 18:29:32]
[/quote][/spoiler]

**Comment by georgehazan** [comment]
Это скорее всего Google или еще какой-то сервер, который не поддерживает задание имени группы в ростере. Специально для таких случае в NG есть опция Options - Network - Jabber - Ignore roster groups
![image](https://user-images.githubusercontent.com/4628541/54431311-215c9600-4737-11e9-883a-e3f2c369a0fe.png)

**Comment by de77** [comment]
Спасибо большое, помогло.
