### ISSUE TITLE
XMPP/Jabber: Implement XEP-0352 (Client State Indication)

### ISSUE THREAD

**Issue by mrlioncub** [miranda-ng/miranda-ng#1898]
It is common for IM clients to be logged in and 'online' even while the user is not interacting with the application. This protocol allows the client to indicate to the server when the user is not actively using the client, allowing the server to optimise traffic to the client accordingly. This can save bandwidth and resources on both the client and server.
Protocol definition: https://xmpp.org/extensions/xep-0352.html

**Comment by georgehazan** [comment]
WARNING: This document has been automatically Deferred after 12 months of inactivity in its previous Experimental state. Implementation of the protocol described herein is not recommended for production systems. However, exploratory implementations are encouraged to resume the standards process.

Are you sure, that we shall implement it?

**Comment by georgehazan** [comment]
you can test the implementation in the development version
