### ISSUE TITLE
PluginUpdater + /profile, keep profile path while restarting

### ISSUE THREAD

**Issue by watergad** [miranda-ng/miranda-ng#1900]
Update with restart looses profile path defined with /profile cmd arg.
Обновление плагинапдейтером, требующее рестарта, теряет путь, указанный через /profile. Где-то путь должен сохраняться, чтобы после рестарта запуститься с тем же профилем.

Также, пользуясь случаем, выражу удивление отсутствием поддержки кавычек в /profile (хотя путь с пробелами всё равно **работает**).  Для винды, всё-таки, путь в кавычках, пожалуй, скорее, норма.

### Expected behavior
Restart with the same /profile
### Actual behavior
Restart with profile manager
### Does it work in stable version?
Yes
### Steps to reproduce that behavior
1. Start with /profile:D:\......
2. Update with restart

```
Miranda NG Version: 0.95.11 alpha build #21613 (e69e0ee825) [running inside WOW64]
Build time: 18 Mar 2019 2:00:40
Profile: D:\Users\Watergad\Miranda\watergad\watergad.dat
Profile size: 125001728 Bytes
Profile creation date: 17 Mar 2019 0:37:17
Language pack: No language pack installed
Service Mode: No

Active Plugins (20):
¤ Alarms.dll v.0.4.0.6 [16 Mar 2019 2:01:06] - Alarms 
¤ AVS.dll v.0.98.1.1 [16 Mar 2019 2:00:47] - Avatar service 
¤ Clist_modern.dll v.0.9.1.8 [16 Mar 2019 2:01:16] - Modern contact list 
¤ CrashDumper.dll v.0.1.0.3 [16 Mar 2019 2:01:14] - Crash dumper 
¤ DbEditorPP.dll v.4.0.1.2 [16 Mar 2019 2:01:16] - Database editor++ 
¤ Dbx_mdbx.dll v.0.95.9.1 [18 Mar 2019 2:02:04] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.0.95.8.1 [18 Mar 2019 2:00:44] - Miranda NG mmap database driver 
¤ Dbx_sqlite.dll v.0.95.10.2 [16 Mar 2019 2:01:58] - Miranda NG SQLite database driver 
¤ Dummy.dll v.0.2.0.0 [18 Mar 2019 2:01:38] - Dummy protocol 
¤ historypp.dll v.1.5.1.5 [16 Mar 2019 2:02:24] - History++ 
¤ ICQ.dll v.0.95.11.4 [16 Mar 2019 2:01:58] - ICQ-WIM protocol 
¤ Import.dll v.0.95.10.1 [18 Mar 2019 2:01:12] - Import contacts and messages 
¤ IRC.dll v.0.95.10.1 [16 Mar 2019 2:00:49] - IRC protocol 
¤ Jabber.dll v.0.11.0.5 [18 Mar 2019 2:01:08] - Jabber protocol 
¤ MSN.dll v.0.95.11.1 [16 Mar 2019 2:01:12] - MSN protocol 
¤ PluginUpdater.dll v.0.2.0.3 [16 Mar 2019 2:01:19] - Plugin updater 
¤ Scriver.dll v.3.0.1.10 [16 Mar 2019 2:00:50] - Scriver 
¤ SkypeWeb.dll v.0.12.3.3 [16 Mar 2019 2:01:54] - Skype protocol (Web) 
¤ StopSpam.dll v.0.1.0.2 [16 Mar 2019 2:01:02] - StopSpam+ 
¤ wbOSD.dll v.0.2.1.0 [16 Mar 2019 2:01:32] - WannaBe OSD 

Protocols and Accounts:
-------------------------------------------------------------------------------
ICQ                      1 - Enabled 0 - Disabled  Loaded
IRC                      1 - Enabled 0 - Disabled  Loaded
JABBER                   3 - Enabled 0 - Disabled  Loaded
MSN                      1 - Enabled 0 - Disabled  Loaded
SKYPE                    1 - Enabled 0 - Disabled  Loaded

Icon Packs:
-------------------------------------------------------------------------------
 HistoryPP_icons.dll [16 Mar 2019 2:02:20]
 Proto_Dummy.dll [18 Mar 2019 2:02:16]
 Proto_Facebook.dll [16 Mar 2019 2:02:18]
 Proto_GG.dll [16 Mar 2019 2:02:18]
 Proto_ICQ.dll [16 Mar 2019 2:02:19]
 Proto_IRC.dll [16 Mar 2019 2:02:18]
 Proto_Jabber.dll [18 Mar 2019 2:02:14]
 Proto_MetaContacts.dll [18 Mar 2019 2:02:16]
 Proto_MRA.dll [16 Mar 2019 2:02:19]
 Proto_MSN.dll [16 Mar 2019 2:02:18]
 Proto_Skype.dll [16 Mar 2019 2:02:20]
 TabSRMM_icons.dll [16 Mar 2019 2:02:19]
 Toolbar_icons.dll [16 Mar 2019 2:02:18]
 xStatus_Jabber.dll [18 Mar 2019 2:02:14]
```

**Comment by watergad** [comment]
> Does it work in stable version?

Кстати, интересный вопрос: из контекста не ясно, что здесь it: то ли работает ли этот функционал нормально в продакшне, то ли воспроизводится ли баг в продакшне )

**Comment by georgehazan** [comment]
> Кстати, интересный вопрос: из контекста не ясно, что здесь it: то ли работает ли этот функционал нормально в продакшне, то ли воспроизводится ли баг в продакшне )

Очевидно, что работает ли в стабильной версии или нет, т.е. имеет ли место регрессия в версии для разработки

**Comment by watergad** [comment]
Пока всё по-прежнему, рестарт теряет профиль, заданный в ярлыке запуска аргументом
[spoiler=VersionInfo][quote]
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian
Free disk space on Miranda partition: 115020 MBytes

Miranda NG Version: 0.95.10.2 build #21702 (50e8c748ff) [running inside WOW64]
Build time: 1 Jun 2019 22:55:48
Profile: D:\Users\Watergad\Miranda\watergad\watergad.dat
Profile size: 125001728 Bytes
Profile creation date: 17 Mar 2019 0:37:17
Language pack: No language pack installed
Service Mode: No

[b]Active Plugins (21):[/b]
¤ Alarms.dll v.[b]0.4.0.6[/b] [15 Apr 2019 21:34:34] - Alarms 
¤ AVS.dll v.[b]0.98.1.1[/b] [22 May 2019 19:27:02] - Avatar service 
¤ Clist_modern.dll v.[b]0.9.1.8[/b] [22 May 2019 19:27:26] - Modern contact list 
¤ CrashDumper.dll v.[b]0.1.0.3[/b] [17 May 2019 19:55:28] - Crash dumper 
¤ DbEditorPP.dll v.[b]4.0.1.2[/b] [17 May 2019 19:55:28] - Database editor++ 
¤ Dbx_mdbx.dll v.[b]0.95.9.1[/b] [1 Jun 2019 22:57:10] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.[b]0.95.8.1[/b] [1 Jun 2019 22:55:54] - Miranda NG mmap database driver 
¤ Dbx_sqlite.dll v.[b]0.95.10.2[/b] [15 Apr 2019 21:35:26] - Miranda NG SQLite database driver 
¤ Dummy.dll v.[b]0.2.0.0[/b] [1 Jun 2019 22:56:46] - Dummy protocol 
¤ historypp.dll v.[b]1.5.1.5[/b] [21 May 2019 11:56:36] - History++ 
¤ ICQ.dll v.[b]0.95.11.4[/b] [30 May 2019 13:59:40] - ICQ-WIM protocol 
¤ Import.dll v.[b]0.95.11.1[/b] [1 Jun 2019 22:56:18] - Import contacts and messages 
¤ IRC.dll v.[b]0.95.10.1[/b] [17 May 2019 19:55:04] - IRC protocol 
¤ Jabber.dll v.[b]0.11.0.5[/b] [30 May 2019 13:59:04] - Jabber protocol 
¤ MSN.dll v.[b]0.95.11.1[/b] [15 Apr 2019 21:34:46] - MSN protocol 
¤ PluginUpdater.dll v.[b]0.2.0.3[/b] [30 May 2019 13:58:52] - Plugin updater 
¤ Scriver.dll v.[b]3.0.1.10[/b] [30 May 2019 13:58:24] - Scriver 
¤ SkypeWeb.dll v.[b]0.12.3.3[/b] [30 May 2019 13:59:30] - Skype protocol (Web) 
¤ SpellChecker.dll v.[b]0.2.6.6[/b] [15 Apr 2019 21:35:16] - Spell checker 
¤ StopSpam.dll v.[b]0.1.0.2[/b] [17 May 2019 19:55:14] - StopSpam+ 
¤ wbOSD.dll v.[b]0.2.1.0[/b] [15 Apr 2019 21:35:00] - WannaBe OSD 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
ICQ                      1 - Enabled 0 - Disabled  Loaded
IRC                      1 - Enabled 0 - Disabled  Loaded
JABBER                   3 - Enabled 0 - Disabled  Loaded
MSN                      1 - Enabled 0 - Disabled  Loaded
SKYPE                    1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 Flags_icons.dll [15 Apr 2019 21:35:48]
 HistoryPP_icons.dll [21 May 2019 11:56:32]
 Proto_Dummy.dll [1 Jun 2019 22:57:26]
 Proto_Facebook.dll [30 May 2019 14:00:00]
 Proto_GG.dll [17 May 2019 19:56:30]
 Proto_ICQ.dll [30 May 2019 14:00:02]
 Proto_IRC.dll [17 May 2019 19:56:30]
 Proto_Jabber.dll [30 May 2019 14:00:00]
 Proto_MetaContacts.dll [1 Jun 2019 22:57:26]
 Proto_MRA.dll [30 May 2019 14:00:02]
 Proto_MSN.dll [15 Apr 2019 21:35:48]
 Proto_Skype.dll [30 May 2019 14:00:02]
 TabSRMM_icons.dll [30 May 2019 14:00:00]
 Toolbar_icons.dll [22 May 2019 19:28:32]
 xStatus_Jabber.dll [30 May 2019 14:00:00]
[/quote][/spoiler]

**Comment by georgehazan** [comment]
не подтверждаю. после рестарта миранды вижу в Process Explorer правильную комстроку
"W:\miranda-ng\bin16\Debug64\Miranda64.exe" /restart:9268 /profile=zzzzz

**Comment by watergad** [comment]
![image](https://user-images.githubusercontent.com/6408536/58818116-fbf46f80-8635-11e9-82f2-7a8028133720.png)

**Comment by georgehazan** [comment]
а рабочая папка так и должна быть? или она от фонаря указана? почему она отличается от пути на миранду? если что, то путь на профили надо программировать в mirandaboot.ini

**Comment by watergad** [comment]
С рабочей папкой мой косяк, спасибо! Извиняюсь, не доделал ярлык после перехода. Поправил, проверю, повлияло ли на апдейтер.
У меня мирандой пользуются несколько человек, а использовать APPDATA для личных данных я отучил :) В итоге профили лежат у кого где в usr под правами, и одной ProfileDir в mirandaboot.ini не обойтись - проще оказалось решить через ярлыки тогда.

**Comment by watergad** [comment]
Увы, не помогло, командная строка не изменилась при рестарте.
ProfileDir=
ShowProfileMgr=smart
DefaultProfile=
дефолтный инишник, в общем.

**Comment by georgehazan** [comment]
А зачем ей меняться, если она правильная? в комстроке видно, что профиль передался и должен работать. Отсчитываться он должен как раз от ProfileDir, который надо либо задать, либо закомментировать
