### ISSUE TITLE
Facebook label Miranda NG as malware

### ISSUE THREAD

**Issue by tealkami** [miranda-ng/miranda-ng#1902]
This is like 3-4 time that facebook wants me to change password because it thinks I was hacked

### Actual behavior
after some time facebook log me out and want to change password , because it thinks that Miranda NG is some malware who hacked my account , but the Facebook addon is just not updated with present facebook network code

### Steps to reproduce that behavior
Just be loged in with multiple facebook accounts , it happened to my both active facebook accounts. 

This happened before few times already , when the facebook addon is not updated with new facebook code, and it send old network communication which is not used by present facebook code

in network logs there should be some errors from server about “Not Authorized”

**Comment by georgehazan** [comment]
that's true, but Facebook support doesn't answer to my questions
also, there were absolutely no changes in FB proto, so I can only suppose what could result to this problem

**Comment by dartraiden** [comment]
We need to port plugin from website parsing to FB API.

**Comment by georgehazan** [comment]
> We need to port plugin from website parsing to FB API.

it will lead to feature loss. if things were so simple, there was no need to emulate a browser

**Comment by georgehazan** [comment]
@tealkami btw, I enabled two-phase authentication in Facebook, and since that time I've never seen this message, Would you try? Miranda supports 2-factor auth pretty good

**Comment by Rigello** [comment]
Same here. 'Suspicious activity', 'Change password' etc. Tried old trick with deleting DeviceID string, will report if it helps.

**Comment by johnykulik4025** [comment]
My opinion is that facebook is trying to prevent the user from subscribing to facebook if they have a permanently blocked account. If someone lives in Ireland, there is no problem finding the address and going there and discussing these facts. When no Onlyne communication is on the freezing point.

**Comment by winman3000** [comment]
I still have the problem. Today, I Need to reset my Password 3 times. I cannot say how many times I changed my Password.

Which feature loss we are talking About when switching to Facebook API? I only want to write with my contacts, see them going on or offline, when they are typing (currently not working) etc.

**Comment by georgehazan** [comment]
well, in fact after this commit FB doesn't treat Miranda as a malware (rather as a Firefox for Windows), so this concrete problem is solved. 

@dartraiden if a problem with account locking persisted, we'd need to open another bug
