### ISSUE TITLE
Service discovery is broken in v0.95.10.2

### ISSUE THREAD

**Issue by evle-zzz** [miranda-ng/miranda-ng#1910]
### Expected behavior
When I open Service discovery dialog for jabber protocol I expect to see a list of services

### Actual behavior
In v0.95.10.2 and in latest dev I see a single node with domain name and tooltip
"Info request error: Error 404: Not found
item-not-found"

### Does it work in stable version?
Works fine in v0.95.10.1

### Steps to reproduce that behavior
 * Have an jabber account. I used private XMPP server with Openfire 4.2.3.
 * Update to the latest version of Miranda-NG.
 * Open service discovery dialog.

[VersionInfo.txt](https://github.com/miranda-ng/miranda-ng/files/3037670/VersionInfo.txt)
![miranda_screen](https://user-images.githubusercontent.com/13830812/55465328-7b15f900-562f-11e9-8f15-64cc5a8550f0.png)

**Comment by georgehazan** [comment]
a network log would be appreciated
