### ISSUE TITLE
Поиск JABBER

### ISSUE THREAD

**Issue by Lavsky** [miranda-ng/miranda-ng#1911]
Добрый день!

После последних обновлений, что-то испортилось в поиске.

![2019-04-03_170725](https://user-images.githubusercontent.com/49240419/55485431-1ceb1500-5633-11e9-85ea-1e41c646c946.jpg)

**Comment by georgehazan** [comment]
и как это тестировать? на сервер можете дать доступ?

**Comment by georgehazan** [comment]
попробовал починить это вслепую. если будут вопросы - переоткройте тикет

**Comment by Lavsky** [comment]
Всё работает! Большое спасибо!
