### ISSUE TITLE
Jabber: после смены ника в никлисте конфы висят оба ника - старый и новый

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1913]
1) после смены моего ника в никлисте конфы остаётся висеть старый ник и появляется новый ник.
мне кажется, старый должен убираться

2) при этом, по-прежнему работает хайлайт по старому нику (то есть, я переименовался из dartraiden в Test, но если кто-то напишет "dartraiden", хайлайт сработает

**Comment by georgehazan** [comment]
duplicate of #1912

**Comment by dartraiden** [comment]
Тот баг исправился, этот остался.
