### ISSUE TITLE
ucrtbase.dll error broke install

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#1919]
Today's update, April 12th, broke my Miranda NG installation and made it unable to start. It was updated to 0.95.10.2 previously.

![Untitled](https://user-images.githubusercontent.com/13466852/56056680-2d9b3980-5d5d-11e9-9a78-67b7aacf3436.png)

**Comment by georgehazan** [comment]
@Tharn bad image error - dunno, maybe it's broken on your HDD?
https://ugetfix.com/ask/how-to-fix-error-code-0xc000012f-on-windows/

**Comment by dartraiden** [comment]
Maybe it's broken Microsoft updates?

**Comment by Tharn** [comment]
The update should not touch ucrtbase.dll in *miranda installation dir* however.

If it was broken on hdd, then it broke during the update process and something is fishy there.

**Comment by dartraiden** [comment]
Try to revert all files from \Plugin Updates\Backups

**Comment by Tharn** [comment]
Thanks guys, I have since simply reinstalled Miranda to fix it.

This does not solve the bug however. The only explanation I have is that the file download may have gotten corrupted.

**Comment by georgehazan** [comment]
well... it might be cached in a browser, for example
also you can try to download the installer, cause it checks the CRC of each file

**Comment by georgehazan** [comment]
well, in fact, both archives (32 & 64 bit) at the server contain the valid copy of UCRTBASE.dll, so it must be some local issue... the stable version was downloaded 470K times already

**Comment by dartraiden** [comment]
> The only explanation I have is that the file download may have gotten corrupted.
 Simply check digital certificate via file properties. If it still valid (dll is signed my Microsoft) = file is not corrupted.
