### ISSUE TITLE
ICQ Update server list (INVALID DATA)

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#192]
**Reported by SkOle on 9 Apr 2013 03:38 UTC**
При попытке сделать добавление контакта на сервер через меню в КЛ ничего не происходит, если делать синхронизацию через свойства протокола - ошибка INVALID DATA.

**Comment by georgehazan** [comment]
**Modified by watcher on 29 Jun 2014 15:46 UTC**

**Comment by dartraiden** [comment]
New protocol upload all data automatically.
