### ISSUE TITLE
scriver, при новом сообщении фокус скринридеров всегда перемещается на последнее сообщение

### ISSUE THREAD

**Issue by jawhien** [miranda-ng/miranda-ng#1920]
При использовании программ чтения с экрана, Jaws или NVDA, возникает следующая проблема:
Когда читаешь журнал сообщений, и приходит новое, фокус сразу перемещается к нему, не позволяя дочитать предыдущее сообщение, и при каждом новом сообщении приходится всегда искать последнее прочитанное сообщение. Таким образом, если сообщения приходят одно за одним, прочитать можно только последнее сообщение.

**Comment by georgehazan** [comment]
ну так в общем-то и задумано
пока не очень понятно, как сделать так, чтобы было нормально

**Comment by jawhien** [comment]
Я думаю было бы лучше, если было как в std msg. Там фокус остаётся на том сообщении, которое читаешь.

**Comment by lion891** [comment]
Всем доброго времени суток! Ребят, да, очень неудобна эта штука. Особенно когда переписываешься с несколькими людьми сразу и в каждом окне приходится постоянно отматывать стрелками, а когда люди ещё и пишут при этом... Дико неудобно. Буду премного благодарен, если этот маленький недочет удастся устранить. Заранее спасибо! :)
