### ISSUE TITLE
ShellExt в Win 7 x64 не работает

### ISSUE THREAD

**Issue by ziceptor** [miranda-ng/miranda-ng#1923]
```
Miranda NG Version: 0.95.11 alpha build #21746 (0b2ce9a3d3) x64
ShlExt.dll v.[b]2.2.0.3[/b] [16 Apr 2019 2:03:48] - Shell extension 
```

Не появляются пункты в контекстном меню Windows 7 x64 (на Win x32 работает). Никаких ошибок.

В настройках: Интеграция в оболочку произведена успешно (разрешено).

**Comment by apollo2k4** [comment]
Настройки UAC на компьютерах одинаковые? Возможно нужно запускать от Администратора, если стоит подтверждение действий.

**Comment by georgehazan** [comment]
@ziceptor можно начать с простого - находится ли ShellExt,dll в списке модулей процесса Explorer.exe. если нет, то выложен ли рантайм от студии в системные каталоги, потому что ShellExt не работает в контексте процесса миранды

**Comment by ziceptor** [comment]
@apollo2k4 UAC отключен.
@georgehazan ShellExt.dll в списке модулей процесса Explorer.exe отсутствует.
![](https://i.imgur.com/Q9HKqL1.png)

**Comment by georgehazan** [comment]
@ziceptor а как оно тогда должно работать, если его нет в explorer? надо тогда пробовать грузить эту dll руками, но смысл в том, что рантайм от VS2017 должен быть в системе (в миранде оно лежит в каталоге Libs)

**Comment by ziceptor** [comment]
Оно никак не должно работать, в этом и суть заголовка. Плагин сообщает, что всё хорошо, всё как надо зарегистрировано, и, как выясняется, бросает плагин на произвол судьбы, мол пользователь сам должен контролировать его работу (не важно, что он работает в контексте системы). Сообщайте тогда честно, проверки мол нет, подхватил его процесс explorer.exe или нет. Рантайм в системных каталогах есть. И 2017 и 2015 (в импорте у плагина он есть). Руками команда выполняется без каких бы то нибыло сообщений. Модуль не появляется.

**Comment by ziceptor** [comment]
Интересно, переустановка рантайм не изменила ситуацию, а вот добавление каталога Libs в системные переменные решило. В чём может быть проблема?

зы Если нажать на кнопку Удалить на странице настройки плагина, то после удаления настроек сообщение не меняется.. так и говорит, что интегрирован.

**Comment by georgehazan** [comment]
> Интересно, переустановка рантайм не изменила ситуацию, а вот добавление каталога Libs в системные переменные решило. В чём может быть проблема?

с очевидностью, ShellExt в 64 битах тянет напрямую какие-то библиотеки из Миранды, что очень странно. сейчас гляну

> Плагин сообщает, что всё хорошо, всё как надо зарегистрировано, и, как выясняется, бросает плагин на произвол судьбы, мол пользователь сам должен контролировать его работу (не важно, что он работает в контексте системы).

Только это плагин не для Миранды, а для Explorer... вот в чем проблема. Миранда о нем ни слухом, ни духом, когда его грузит совершенно посторонняя программа.

**Comment by georgehazan** [comment]
@ziceptor что-то у меня засовывание Libs в PATH не сильно помогло... но по крайней мере проблема повторяется
