### ISSUE TITLE
omemo compatibility tricks

### ISSUE THREAD

**Issue by sss123next** [miranda-ng/miranda-ng#1924]
implement aggressive **non xep compliant**  polling (like in gajim implementation) and other tricks for more rapid session negotiation and to avoid problems on servers with broken/misconfigured pep/

**Comment by sss123next** [comment]
related to #1417

**Comment by Neustradamus** [comment]
To follow this OMEMO ticket ^^

**Comment by sss123next** [comment]
this is seems resolved now.
