### ISSUE TITLE
The status of clients of the original ICQ is not displayed. (Не отображается статус клиентов оригинального ICQ)

### ISSUE THREAD

**Issue by MiceRus** [miranda-ng/miranda-ng#1926]
In the contact list, all clients using non-Miranda are almost always in the OFF state.
It is not convenient (В списке контактов все клиенты, использующие не Миранду почти всегда находятся в состоянии OFF. Крайне не удобно)

**Comment by dartraiden** [comment]
Таково поведение официального клиента, как мы можем на него повлиять? Адресуйте, пожалуйста, это к разработчику клиента - mail.ru
