### ISSUE TITLE
Hidden db option for hiding specified component from PU

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1927]
> А не могли бы вы сделать, пожалуйста, скрытую, не документированную возможность, чтобы прописав в базе, например, в разделе PluginUpdaterHide, какие компоненты/файлы скрыть в списке упдейтера? Либо в уже существующем разделе PluginUpdaterFiles, если ставишь значение '2', то оно снимает чекбокс с загрузки (как в случае с '0') и скрывает в списке.

**Comment by georgehazan** [comment]
done, if the appropriate line in PluginUpdaterFiles == 2

**Comment by dartraiden** [comment]
Значение "2" странно себя ведёт, если оно задано, допустим, элементу icons\tabsrmm_icons.dll

Воспроизводится так:
- меняем что-то (например, версию) редактором ресурсов в tabsrmm_icons.dll и в tabsrmm.dll. То есть, имитируем необходимость обновления значков и самого плагина.

- создаём в базе такую загогулину:
```
[PluginUpdaterFiles]
icons\tabsrmm_icons.dll=b0
plugins\tabsrmm.dll=b1
```

- дёргаем апдейтер, в апдейтере галка со значков снята (ибо у них b0), обновляемся

Результат: плагин обновился, а значки не обновились, как мы и указывали в базе (b0 значкам, b1 плагину).

Теперь тот же самый эксперимент, но в базе создаём:
```
[PluginUpdaterFiles]
icons\tabsrmm_icons.dll=b2
plugins\tabsrmm.dll=b1
```

Ожидаемое поведение: плагин должен обновиться, а значки нет, поскольку у них b2.
Реальное поведение: значки тоже обновляются, хотя при b2 они обновляться не должны.
