### ISSUE TITLE
pu_stub.exe has stopped working

### ISSUE THREAD

**Issue by dragonattack** [miranda-ng/miranda-ng#1930]
[![2019-04-25-194923.png](https://i.postimg.cc/Y2Q7zsHV/2019-04-25-194923.png)](https://postimg.cc/mhZKbVhN)

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	pu_stub.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5cc1deec
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.24354
  Fault Module Timestamp:	5c3565b8
  Exception Code:	c0000005
  Exception Offset:	00000000000fdde1
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1049
  Additional Information 1:	7b74
  Additional Information 2:	7b7495e388330aa28f5395591d8fb322
  Additional Information 3:	1d9d
  Additional Information 4:	1d9d06487ddcd879e8774190f42039d2

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```
### Steps to reproduce that behavior
 * start Miranda, it will check for updates on startup
 * updates found, press "Update"
 * pu_stub.exe has stopped working

### Run Miranda as Administrator
* it fixes the issue, but it was possible to have auto-updates without running Miranda as administrator before.

**Comment by georgehazan** [comment]
well... there is the certain workaround: you can move all that runtime stuff from MS (api-ms-win-crt*.dll, VCRUNTIME140.dll, ucrtbase.dll) to %SystemRoot%\System32, but yes, it should work anyway

**Comment by georgehazan** [comment]
@dragonattack dev build will be available soon, give it a try
