### ISSUE TITLE
ICQ: сессия поднимается даже при отсутствии доступа к сети

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1938]
- при запущенной миранде и выведенной в онлайн аське отключаю сетевой адаптер в винде
- увожу аську в оффлайн
- возвращаю её в онлайн

результат: аська сразу зеленеет, хотя сетевой адаптер отключён

**Comment by apollo2k4** [comment]
Со SkypeWeb тоже такие чудеса случаются.

**Comment by georgehazan** [comment]
это винда развлекается, пока таймаут на соединение держится, она пускать будет на запомненных credentials, а как только попытка startSession начнет ошибки давать, так и аська зеленеть перестанет
