### ISSUE TITLE
Should use CRLF instead of LF in ALL English langpack files.

### ISSUE THREAD

**Issue by ageback** [miranda-ng/miranda-ng#1944]
### Expected behavior
What did you expect?
All files in miranda-ng\langpacks\english should use CR+LF instead LF
### Actual behavior
What did you get instead?
Some of them use LF, like PopupPlus.txt and MagneticWindows.txt. That caused lost of translation after running Refresh.bat.  
### Does it work in stable version?
If you know in which dev build (or approximate date when) it was broken, it may be much easier to identify and fix the issue.
The latest version.
### Steps to reproduce that behavior
 * Provide step-by-step instructions so we can reproduce the issue (We can't fix what we can't reproduce).
 * Attach your VersionInfo.
 * Attach a crash report if you are experiencing crashes (It includes VersionInfo as well).
 * Attach a network log captured if you are experiencing connectivity issues.
 * If Miranda freezes, hangs up or consumes CPU, attach information obtained by Process Explorer tool.

**Comment by dartraiden** [comment]
What exactly files have LF?

**Comment by dartraiden** [comment]
Well, even after checkout under Linux all files have CR+LF

dr@xubuntu:~/miranda-ng/langpacks/english/Plugins$ file Contacts.txt
Contacts.txt: ASCII text, with CRLF line terminators

So it's your local problem...

**Comment by dartraiden** [comment]
Fixed in https://github.com/miranda-ng/miranda-ng/commit/15750b3ac9d8c76631cc43560b1cfa34460156c1

I suggest you to execute `git config --global core.autocrlf true`
https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration

**Comment by ageback** [comment]
I see. Thanks.
