### ISSUE TITLE
MSN is dead

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1945]
https://forum.miranda-ng.org/index.php?topic=5792.msg24815#msg24815

We should deprecate it or revive it.

**Comment by dartraiden** [comment]
> https://wink.messengergeek.com/t/microsoft-ending-support-for-classic-skype-version-7-n-o-v-e-m-b-e-r-1-january-8/6131
> 
> MSNP24 is dead now, plugin can be removed.
> Modify message
> 

https://forum.miranda-ng.org/index.php?topic=4163.msg24680#msg24680

**Comment by dartraiden** [comment]
Or we can adapt plugin for 3-party server
https://forum.miranda-ng.org/index.php?topic=5602.msg22507#msg22507

**Comment by c8c8** [comment]
I agree it's not working, but it was just updated yesterday... if it's dead, why is it being updated?

**Comment by dartraiden** [comment]
Plugin is not deprecated, so it MUST launch. If we made some changes in the core, all plugins will be updated respectively

**Comment by dartraiden** [comment]
Well. a year has passed, so the plugin movet to deprecated.

**Comment by mirddes** [comment]
https://escargot.chat/ indeed looks promising.

im not sure what the point is at this stage, but bravo to escargot.chat and would be of some use to someone.

https://nina.chat/ aims to do the same for AOL, AIM, ICQ, Yahoo, even Q-Link

has anyone tested any of it for compatibility with miranda?

collaboration could be fruitful for everyone.
