### ISSUE TITLE
Modify dbx_sqlite data schema

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#1949]
Right now the database schema of Dbx_Sqlite is wrong:
- it doesn't support metacontacts  & meta-history;
- it doesn't support server event ids

To solve that, several things should be done:
- add primary key of MEVENT to the **events** table;
- add another table, **events_srt** of three fields (all of them form its primary key): MCONTACT, timestamp, MEVENT;
- when any event is added, you need to insert 2 or 3 records: one into **events** + its primary key with the appropriate contact id & timestamp into **events_srt** + same thing for metacontact, if you insert an event into stub;
- event deletion shall remove records from **events_srt** too;
- methods for splitting / joining histories of subcontacts shall insert / remove references into / from **event_srt** too;
- FindFirstEvent / FindLastEvent / FindNextEvent / FindPrevEvent methods shall work with **events_srt** table exclusively, caching the timestamp of the previous event for correct cursor positioning (look at the implementation in Dbx_mdbx);
- EditEvent must be implemented (it's trivial);
- SetEventId / GetEventByID should be implemented using the additional key in **events**

**Comment by sss123next** [comment]
i am on it.
