### ISSUE TITLE
Remove notification engine from TabSRMM

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1950]
TabSRMM cѳntains its own NewEventNotify (older than our NewEventNotify).

**Comment by dartraiden** [comment]
> на самом деле в табсы тупо вставлена копия NewEventNotify, только более старая. проблема в том, что в обработке событий от NeN используется специфический для табсов код, поэтому вариант просто выкинуть его из табсов не прокатывает, нужна достаточно кропотливая работа

**Comment by MrMyth** [comment]
Можно ли просто временно добавить галочку "использовать NewEventNotify" для уведомлений?

**Comment by dartraiden** [comment]
Это равносильно выпиливанию, потому что в куче мест этот движок
используется принудительно. Научить использовать по выбору встроенный и
сторонний даже сложнее, чем выпилить.

**Comment by MrMyth** [comment]
Хотел попробовать вот такую правку. Но после сборки пошла ругань на нехватку библиотек.
Если это будет работать можно ли вставить как временное решение?
int tabSRMM_ShowPopup(MCONTACT hContact, MEVENT hDbEvent, WORD eventType, int windowOpen, TContainerData *pContainer, HWND hwndChild, const char *szProto)
{
	if (nen_options.iDisable || GetModuleHandle(L"NewXstatusNotify.dll")) // no popups at all. Period
		return 0;

	PU_CleanUp();

	if (nen_options.bDisableNonMessage && eventType != EVENTTYPE_MESSAGE)
		return 0;

	// check the status mode against the status mask
	if (nen_options.dwStatusMask != -1) {
		if (szProto != nullptr) {
			int dwStatus = Proto_GetStatus(szProto);
			if (!(dwStatus == 0 || dwStatus <= ID_STATUS_OFFLINE || ((1 << (dwStatus - ID_STATUS_ONLINE)) & nen_options.dwStatusMask)))           // should never happen, but...
				return 0;
		}
	}
	if (nen_options.bNoRSS && szProto != nullptr && !strncmp(szProto, "NewsAggregator", 3))
		return 0; // filter out RSS popups

	// message window is open, need to check the container config if we want to see a popup nonetheless
	if (windowOpen && pContainer != nullptr) { 
		if (nen_options.bWindowCheck && windowOpen) // no popups at all for open windows... no exceptions
			return 0;
	
		if (pContainer->m_flags.m_bDontReport && (IsIconic(pContainer->m_hwnd))) // in tray counts as "minimised"
			goto passed;

		if (pContainer->m_flags.m_bDontReportUnfocused)
			if (!IsIconic(pContainer->m_hwnd) && !pContainer->IsActive())
				goto passed;

		if (pContainer->m_flags.m_bAlwaysReportInactive) {
			if (pContainer->m_flags.m_bDontReportFocused)
				goto passed;

			if (pContainer->m_hwndActive != hwndChild)
				goto passed;
		}
		return 0;
	}
passed:
	if (PU_GetByContact(hContact) && nen_options.bMergePopup && eventType == EVENTTYPE_MESSAGE) {
		if (PopupUpdateT(hContact, hDbEvent) != 0)
			PopupShowT(&nen_options, hContact, hDbEvent, eventType, pContainer ? pContainer->m_hwnd : nullptr);
	}
	else PopupShowT(&nen_options, hContact, hDbEvent, eventType, pContainer ? pContainer->m_hwnd : nullptr);

	return 0;
}

Правил по аналогии с звуковой библиотекой bass.

**Comment by georgehazan** [comment]
> Но после сборки пошла ругань на нехватку библиотек.

Какая ругань? Что именно ты пробовал собирать?

> Если это будет работать можно ли вставить как временное решение.

Нет, это вряд ли можно вставить. Просто блокировать звук по наличию DLL - это очень плохая идея

**Comment by MrMyth** [comment]
> > Но после сборки пошла ругань на нехватку библиотек.
> 
> Какая ругань? Что именно ты пробовал собирать?
> 
> > Если это будет работать можно ли вставить как временное решение.
> 
> Нет, это вряд ли можно вставить. Просто блокировать звук по наличию DLL - это очень плохая идея

а почему звук? должно игнорировать потап. Из за того, что scriver багован, я сейчас не пользуюсь вашей программой. Вырезать старую версию потапов из Tabsrmm вы видимо не скоро будете. Мне нужен именно NewEventNotify. А в пару с Tabsrmm его нормально не поставить. Не уж то даже опционально нельзя сделать такую штуку. Не смог полноценно собрать libs ругалось на отсутствие библиотек.

**Comment by georgehazan** [comment]
> Из за того, что scriver багован, я сейчас не пользуюсь вашей программой

Что именно не так? До меня что-то долетало, но в точности я не вспомню.

> Вырезать старую версию потапов из Tabsrmm вы видимо не скоро будете.

Да, это непросто.


> Мне нужен именно NewEventNotify. А в пару с Tabsrmm его нормально не поставить. Не уж то даже опционально нельзя сделать такую штуку.

Угандошить функциональность табсов в зависимости от наличия другой DLL? Нет, такого даже опционально нельзя, потому что это главный редактор сообщений.

> Не смог полноценно собрать libs ругалось на отсутствие библиотек.

Интересует конкретное сообщение об ошибке

**Comment by MrMyth** [comment]
> > Из за того, что scriver багован, я сейчас не пользуюсь вашей программой
> 
> Что именно не так? До меня что-то долетало, но в точности я не вспомню.
> 
> > Вырезать старую версию потапов из Tabsrmm вы видимо не скоро будете.
> 
> Да, это непросто.
> 
> > Мне нужен именно NewEventNotify. А в пару с Tabsrmm его нормально не поставить. Не уж то даже опционально нельзя сделать такую штуку.
> 
> Угандошить функциональность табсов в зависимости от наличия другой DLL? Нет, такого даже опционально нельзя, потому что это главный редактор сообщений.
> 
> > Не смог полноценно собрать libs ругалось на отсутствие библиотек.
> 
> Интересует конкретное сообщение об ошибке

А в NewEventNotify тоже не хотите сделать возможность отключения Tabsrmm потапов? 

Что касается ошибки: vcruntime140.dll не было и программа не запускалась.

**Comment by georgehazan** [comment]
> А в NewEventNotify тоже не хотите сделать возможность отключения Tabsrmm потапов?

Разумеется. 

> Что касается ошибки: vcruntime140.dll не было и программа не запускалась.

Куда ж она из архива с ядром подевалась?

**Comment by MrMyth** [comment]
> > А в NewEventNotify тоже не хотите сделать возможность отключения Tabsrmm потапов?
> 
> Разумеется.
> 
> > Что касается ошибки: vcruntime140.dll не было и программа не запускалась.
> 
> Куда ж она из архива с ядром подевалась?

Тогда даже обсуждать нечего.

**Comment by MrMyth** [comment]
Я подумал вот о чем: фактически вся ваша программа построена на том, что одна dll убивает функционал другой. Например присутствие Tabsrmm убивает базовое окно переписки. Popup plus убивает базовые всплывающие уведомления. Здесь я предложил фактически тоже самое. Есть базовый функционал, но при наличии определенной dll он отключается и в дело вступает расширенный вариант. Так что причины отказа кажутся мне странными.

**Comment by georgehazan** [comment]
Для каждой функциональности, которую можно заместить, есть такое понятие, как MUID - по его наличию определяется функционал плагина. Соотв. если есть плагин с определенным MUID, то стандартный плагин, отвечающий за этот MUID, не грузится - никто никого не убивает
