### ISSUE TITLE
[Discord] Changing status post-sign-in doesn't work unless a normal client is also open

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#1953]
### Expected behavior
If I sign in as away and set myself to online, I should show up as online.

### Actual behavior
Everyone sees me as away. BUT if I open for example the web for discord alongside miranda, then all of the changes I do in miranda are properly propagated. Makes me think something must be done in addition to what miranda already does (because the web does pick up my change so something is certainly being done; but without the web, nobody sees my status actually change)

### Does it work in stable version?
No. It never worked.

### Steps to reproduce that behavior
 * Login as away (for example)
 * Switch to "online"
 * ask someone to verify your status - it's still away.
 * open your own account in web discord, don't change anything at all
 * immediately, you the status will work properly (when changed from miranda).

**Comment by georgehazan** [comment]
no, I don't confirm the fact the simultaneously opened account in a browser, for example, works as an amplifier for the same account in Miranda

**Comment by LittleVulpix** [comment]
So status doesn't change for you no matter what? For me, simultaneously opened account in the browser works.
