### ISSUE TITLE
Jabber: crash on "Owner: user detials" window 

### ISSUE THREAD

**Issue by modemo** [miranda-ng/miranda-ng#1955]
### Steps to reproduce that behavior
I was not able to reproduce it again, but I did something like this:
 * Create new Jabber account (friend's self-hosted server)
 * Login to account
 * Send/receive few messages to test functionality
 * Digging in "Owner: user details" window - AFAIR I was changing full name, first name, last name, clicking around, etc...

[crash20190518193650.txt](https://github.com/miranda-ng/miranda-ng/files/3196616/crash20190518193650.txt)

**Comment by georgehazan** [comment]
some strange memory corruption, maybe. 
normally this error cannot be reproduced
