### ISSUE TITLE
MRA: у свежесозданной учётки отсутствует пункт "Online" до рестарта Миранды

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1956]
![ehqgtCARrY](https://user-images.githubusercontent.com/5046855/58103552-d99d3380-7beb-11e9-9122-258fe56bc2cc.png)

**Comment by dartraiden** [comment]
А у ICQ есть. Протокол общий. Загадка.

**Comment by dartraiden** [comment]
Проблема чуть глубже: после перезапуска у MRA появляется Online, но пропадает Offline.

**Comment by georgehazan** [comment]
пока не воспроизводится, надо добиться появления (профиль или папка с мирандой)
