### ISSUE TITLE
Remove Free for Chat, On the Phone and Out of Lunch statuses completely

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1963]
> ghazan, 23.05.2019 17:47:10:
> надо вообще выпилить это
> 
> ghazan, 17:47:15:
> его нигде нет
> 

also remove icons

**Comment by dartraiden** [comment]
We do not need these statuses after ICQ-OSCAR death.

**Comment by dartraiden** [comment]
Ещё остались:

https://github.com/miranda-ng/miranda-ng/blob/622ef660a9e8c08bf24d4ae876cd58cdcb97f6f7/plugins/BASS_interface/res/Bass.rc#L66

https://github.com/miranda-ng/miranda-ng/blob/622ef660a9e8c08bf24d4ae876cd58cdcb97f6f7/plugins/BuddyPounce/src/dialog.cpp#L141

https://github.com/miranda-ng/miranda-ng/blob/622ef660a9e8c08bf24d4ae876cd58cdcb97f6f7/plugins/Clist_modern/src/modern_clcopts.cpp#L77

https://github.com/miranda-ng/miranda-ng/blob/622ef660a9e8c08bf24d4ae876cd58cdcb97f6f7/plugins/NewXstatusNotify/res/resource.rc#L127

https://github.com/miranda-ng/miranda-ng/blob/622ef660a9e8c08bf24d4ae876cd58cdcb97f6f7/plugins/Nudge/res/resource.rc#L94

https://github.com/miranda-ng/miranda-ng/blob/622ef660a9e8c08bf24d4ae876cd58cdcb97f6f7/plugins/SeenPlugin/src/utils.cpp#L427

https://github.com/miranda-ng/miranda-ng/blob/622ef660a9e8c08bf24d4ae876cd58cdcb97f6f7/protocols/IRCG/src/options.cpp#L933

https://github.com/miranda-ng/miranda-ng/blob/622ef660a9e8c08bf24d4ae876cd58cdcb97f6f7/protocols/IRCG/src/options.cpp#L933

https://github.com/miranda-ng/miranda-ng/blob/622ef660a9e8c08bf24d4ae876cd58cdcb97f6f7/protocols/YAMN/res/YAMN.rc#L241

**Comment by dartraiden** [comment]
Ешё:

https://github.com/miranda-ng/miranda-ng/blob/5840e0079961a5c164672908ba15368344db650d/include/delphi/m_protosvc.inc#L107

https://github.com/miranda-ng/miranda-ng/blob/5840e0079961a5c164672908ba15368344db650d/plugins/Clist_modern/src/modern_clcpaint.cpp#L57

https://github.com/miranda-ng/miranda-ng/blob/5840e0079961a5c164672908ba15368344db650d/plugins/Clist_modern/src/modern_clcpaint.h#L65

https://github.com/miranda-ng/miranda-ng/blob/5840e0079961a5c164672908ba15368344db650d/protocols/Gadu-Gadu/src/gg_proto.cpp#L115

https://github.com/miranda-ng/miranda-ng/blob/5840e0079961a5c164672908ba15368344db650d/protocols/Gadu-Gadu/src/gg_proto.h#L242

https://github.com/miranda-ng/miranda-ng/blob/5840e0079961a5c164672908ba15368344db650d/protocols/ICQCorp/src/protocol.cpp#L1801

https://github.com/miranda-ng/miranda-ng/blob/5840e0079961a5c164672908ba15368344db650d/protocols/ICQCorp/src/protocol.h#L101

https://github.com/miranda-ng/miranda-ng/blob/5840e0079961a5c164672908ba15368344db650d/protocols/JabberG/src/jabber_util.cpp#L200

https://github.com/miranda-ng/miranda-ng/blob/5840e0079961a5c164672908ba15368344db650d/protocols/YAMN/src/yamn.cpp#L163

**Comment by dartraiden** [comment]
https://github.com/miranda-ng/miranda-ng/blob/7334304717759df342b730cb676bd87dcf1e6200/plugins/NewAwaySysMod/src/stdafx.h#L94

https://github.com/miranda-ng/miranda-ng/blob/7334304717759df342b730cb676bd87dcf1e6200/plugins/NewAwaySysMod/src/stdafx.h#L96

https://github.com/miranda-ng/miranda-ng/blob/7334304717759df342b730cb676bd87dcf1e6200/plugins/NewAwaySysMod/src/stdafx.h#L97

**Comment by wsx22** [comment]
Status ID_STATUS_FREECHAT is still present and used in Gadu-Gadu protocol (GG).
(it is one of five online GG protocol statuses, and it worked correctly at MirandaNG too)
Removing it is unwanted limitation of Gadu-Gadu protocol functionality.

**Comment by georgehazan** [comment]
@wsx22 is that possible to simply map it to Online? like Facebook does (as well as ICQ Corp)

**Comment by georgehazan** [comment]
i.e. it will remain in libgadu, but not in Miranda

**Comment by wsx22** [comment]
@georgehazan 
Of course, map two statuses as one online status is technically posible and is the simplest way after last commits.
But, from my point of view as Gadu-Gadu protocol user, removing support of one from protocol statuses will be lost functionallity issue.
ID_STATUS_FREECHAT is one of five online GG protocol statuses. (GG protocol have: ONLINE, AWAY, DND, INVISIBLE and FREECHAT)
After change, GG protocol MirandaNG users will lost possibility to set theirs status to ID_STATUS_FREECHAT or view this status on theirs contacts.
Deduction "его нигде нет" that was couse of commits was wrong and, in my opinion, changes schould be reverted for ID_STATUS_FREECHAT.
Miranda always has been a program that bet on power users capabilities, not on overdone simplifications.

**Comment by tweimer** [comment]
@georgehazan I have to agree with @wsx22, if Gadu-Gadu supported FFC before, it should be kept/re-introduced. I do not use Gadu-Gadu, but from it's users point, removing it would be like a regression.
