### ISSUE TITLE
Import: wrong timestamps when import from QIP2012

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1966]
> В последних версиях Import появилась возможность импорта истории из qip 2012. Только почему-то при импорте время сообщений сдвигается на время часового пояса (у меня часовой пояс "+4", поэтому, например, 10:00 в qip 2012 превращается в 14:00 в miranda ng)

**Comment by georgehazan** [comment]
вот, я же говорил :-)

**Comment by dartraiden** [comment]
> теперь 10:00 в qip 2012 превращается в 18:00 в miranda ng, т.е. часовой пояс прибавляется дважды.
