### ISSUE TITLE
Scriver: значок на таскбаре начинает глючить, если есть непрочитанное сообщение и пользователь ушёл из сети

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1967]
Открываем в скривере окно беседы с контактом, который в онлайне.
Сворачиваем окно в таскбар.
От этого контакта прилетает сообщение.

Значок на таскбаре начинает мигать.

Контакт уходит в оффлайн.

Наблюдаемое поведение:
Значок либо перестаёт мигать, либо залипает в "зажжённом" состоянии.

Ожидаемое поведение:
Значок должен продолжать мигать.

![vh3RLUrEEX](https://user-images.githubusercontent.com/5046855/58374055-f87b2d00-7f3f-11e9-8704-d5d19beecce8.gif)

**Comment by georgehazan** [comment]
не подтверждаю. надо просто поставить настройку Settings / SRMM / FlashCount DWORD на значение типа 1000, и всё будет прекрасно. сейчас по умолчанию там стоит 3, т.е. иконка автоматически гаснет после 6 миганий, это никак не связано со сменой статуса
