### ISSUE TITLE
Не самый корректный вариант перевода на русский

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#1969]
Вот так на русском
![image](https://user-images.githubusercontent.com/4628541/58710712-9e59ec00-83c5-11e9-9cd5-7128a7996d68.png)

А вот так в оригинале
![image](https://user-images.githubusercontent.com/4628541/58710757-b7629d00-83c5-11e9-8a97-86e37d16257a.png)

**Comment by apollo2k4** [comment]
fix in 622ef66
