### ISSUE TITLE
Вебсервер: надо написать правило типа http://miranda-ng.org/* -> https://miranda-ng.org/*

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1970]
http://miranda-ng.org/distr/ -> 403

**Comment by dartraiden** [comment]
Пометил как блокер, потому что это ломает ссылки на загрузку HotCoffee.

**Comment by georgehazan** [comment]
там трудность в том, что хоткофе обслуживается отдельным набором правил
щас поправлю

**Comment by georgehazan** [comment]
done
