### ISSUE TITLE
Further on Facebook notification issue 

### ISSUE THREAD

**Issue by newsjunkie247** [miranda-ng/miranda-ng#1978]
It's definitely receiving them again, thank you, but the only issue is that now it seems to request all of them repeatedly (including when there isn't a new one) and as a result, when you have them logging into a chatroom as I do, it doesn't just add the individual new notification to the end like it used to but somehow adds new ones in the middle. I'm not sure how much of that is fixable.
But even though it flashes the popup for old and new notifications regularly, it only adds new ones to chatroom, (though in the middle, not at the end).
And it no longer seems to be "triggered" by individual notifications when there are several close after each other, like in a group. But again, I don't know how much of that is fixable

**Comment by georgehazan** [comment]
yes, in retrieves notifications once in a minute, but it should record only new notifications that weren't processed previously (you don't see repeatable popups for the same notifications, yes?)

**Comment by newsjunkie247** [comment]
I do see repeatable popups for the same notifications, though it only adds new ones to the "Facebook notifications chat log". (though like I said they are added in the middle and no longer at the end). I tried tweaking the unread/"seen on server" setting but that didin't seem to make a difference/I guess only applies to messages. And what  I'm also not sure is  fixable is that it no longer triggers individual notifications when there multiple posts right after each other like in a group in time frames under 1 minute (probably seconds).

**Comment by georgehazan** [comment]
okie, I'll look at it
I've never realized that it's possible to read fb notifs this way

**Comment by newsjunkie247** [comment]
Thanks. There is a setting under events to "log notifications into special chatroom."

**Comment by newsjunkie247** [comment]
I don't think this is fixed. I am still seeing duplicates, posts out of order in the chat log etc.

**Comment by newsjunkie247** [comment]
Actually, never mind, the duplication and order issue do seem to be fixed. I thought I was already using the new version but I wasn't.  I don't know yet about the issue of multiple notifications in a short period of time, perhaps that can be fixed with a short checking time? The contacts issue is still there though.
