### ISSUE TITLE
Aktualization from June 6, 2019  for x64 development version completely broken miranda's functionality.

### ISSUE THREAD

**Issue by huh02** [miranda-ng/miranda-ng#1979]
Aktualization from June 6, 2019  for x64 development version completely broken miranda's functionality.
I use SQL profile.
I can't see the text when I write a message.
I can't see the history in the message box.
I can't see the text of the incoming message.
There is no History option in miranda menu  for any user.
Returning a profile backup did not help.
I'm not at home now, so I don't have versioninfo. but it happened June 6, 2019, so it's the latest version after this update.

**Comment by georgehazan** [comment]
yes, SQL profiles might have some problems
I recommend you to migrate to stable, convert your profile into MDBX and live on it until sqlite will be rewritten to the working state
