### ISSUE TITLE
new_GPG incompatibility with other filters (otr, possible secureim)

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#198]
**Reported by mng on 25 Apr 2013 07:13 UTC**
 Hi

It seems it's broken in latest stable release

Message sent via New_GPG is encoded double times in UTF-8, so other contact receives bollocks, like:

`Text message: 䩔猹兄㝦瑂潗匱牍㕮瑫栲䵃䥵瀴㈊⭩啓汄洰癄兒儯瑡剘歉浉さ穑偱瘯獹慥慧硅卸扃橰䩅慰䡍ㅱ奭圶牃晑ぎ੨啍穫⽇橅㥌戯畏㉗䱢䜸噐乺䈳偸桑䬳 {0946134E-4C7F-11D1-8222-444553540000}`

It occurs only when sending messages, receiving messages over GnuPG encryption works fine.

Rolled back to the older release I had.

**Comment by georgehazan** [comment]
**Comment by mng on 25 Apr 2013 07:20 UTC**
note:

the version where all works fine is:

Miranda NG Version: 0.93.4 #2450 x64

version of new_gpg.dll is:

new_gpg.dll v.0.9.0.0 [Nov 2012 21:56:32](23) - GPG

**Comment by georgehazan** [comment]
**Comment by watcher on 25 Apr 2013 07:28 UTC**
what about 0.94.3?

**Comment by georgehazan** [comment]
**Comment by mng on 25 Apr 2013 08:15 UTC**
it seems to be related to UTF8 support in the ICQ protocol.

I did few tests on the latest alpha build (0.94.3) with SIM 0.9.5 client.

SIM 0.9.5 uses UTF-8 by default
Miranda-NG runs on Windows 7 thus using CP1251

russian text SIM->Miranda-NG without GnuPG doesnt work, english works
russian/english text Miranda-NG->SIM without GnuPG works
russian/english text SIM->Miranda-NG with GnuPG doesnt work (decryption failed)
russian/english text Miranda-NG->SIM with GnuPG works

If I switch SIM 0.9.5 to use CP1251 on specific contact here are the results:
russian/english text SIM->Miranda-NG without GnuPG works
russian/english text Miranda-NG->SIM without GnuPG works
russian/english text SIM->Miranda-NG with GnuPG doesnt work (decryption failed)
russian/english text Miranda-NG->SIM with GnuPG works

**Comment by georgehazan** [comment]
**Comment by sss_sss on 25 Apr 2013 16:50 UTC**
looks like this is encodings problem, and not gpg related ?

**Comment by georgehazan** [comment]
**Comment by mng on 26 Apr 2013 08:49 UTC**
@sss_sss:

maybe partly, because on the old version New_GPG was able to handle UTF-8 text.

**Comment by georgehazan** [comment]
**Comment by mng on 14 May 2013 13:54 UTC**
any update?

**Comment by georgehazan** [comment]
**Comment by sss_sss on 17 May 2013 21:24 UTC**
are you using metacontacts ?

**Comment by georgehazan** [comment]
**Comment by mng on 19 May 2013 15:43 UTC**
is it a plugin, right?

if so I don't.

**Comment by georgehazan** [comment]
**Comment by mng on 20 May 2013 23:25 UTC**
checked latest trunk with fresh new profile, GPG asks to specify homedir and GnuPG binary I typed relative paths into the dialog (because there is gnupg folder in the root of miranda dir):

http://trac.miranda-ng.org/ticket/371

**Comment by georgehazan** [comment]
**Comment by sss_sss on 22 May 2013 17:27 UTC**
first: please follow one simple rule, one problem =  one ticket
second: very interesting, it will be very helpful if you will provide miranda package on which i will easily reproduce this

**Comment by georgehazan** [comment]
**Comment by mng on 11 Jun 2013 20:24 UTC**
it's still happening in latest stable release 0.94.3

**Comment by georgehazan** [comment]
**Comment by mng on 12 Jun 2013 11:26 UTC**
and this bug is still in the latest trunk 

Miranda NG Version: 0.94.4 alpha build #4922 x64

**Comment by georgehazan** [comment]
**Comment by sss_sss on 12 Jun 2013 22:25 UTC**
looks like new_gpg conflicting with other filters, this is expected behaviour and very hard to fix, i leave this ticket for future, but it can be closed as invalid/wontfix anytime.

**Comment by georgehazan** [comment]
**Comment by mng on 15 Jun 2013 08:44 UTC**
the build from the site seems to be broken, whilst sss debug build is just working fine.

**Comment by georgehazan** [comment]
**Comment by mng on 8 Feb 2014 00:31 UTC**
checked latest stable miranda (0.94.8 x64) and this bug is still here (from site builds at least).

i will investigate more and report back.

**Comment by georgehazan** [comment]
**Comment by watcher on 8 Feb 2014 00:33 UTC**
latest stable miranda is 0.94.9

**Comment by georgehazan** [comment]
**Modified by mataes on 28 May 2014 04:34 UTC**

**Comment by georgehazan** [comment]
**Comment by mng on 12 Jul 2014 22:45 UTC**
Miranda NG Version: 0.95.2 alpha build #9766 x64 Build time: 12 Jul 2014 6:54:44

this bug reproduces on fresh latest ALPHA version.

**Comment by sss123next** [comment]
ancient bug.
reopen if still relevant.
