### ISSUE TITLE
Facebook not all contacts are showing as online

### ISSUE THREAD

**Issue by newsjunkie247** [miranda-ng/miranda-ng#1980]
Another problem since about sometime last night or so is that not all contacts are showing online, only about 2 or 3, even when the website shows between 10 to 20 or more online.

**Comment by newsjunkie247** [comment]
I think it might be users that the system designated as accessing Facebook from mobile/messenger etc. (even if those designations were not always correct)

**Comment by newsjunkie247** [comment]
And also I think it is no longer properly recognizing/handling when users are online yet away.

**Comment by georgehazan** [comment]
well, if you could make a network log from the very beginning, you can look for 
"ms":[{"overlay":{"
to watch all buddy list updates. if they happen in the log regularily, but you don't see status updates, zip this log and email it to me with the specification whose status is missing.

**Comment by newsjunkie247** [comment]
I have sent you the netlog, but I am not sure it is recognizing the missing statuses at all. I think those indicators might just be showing those it does show as online. At the moment for example it is only showing two people online and never showing anybody away at all the way it used to. It's very confusing.

**Comment by newsjunkie247** [comment]
For example now Miranda NG only shows four people online, but Facebook chat says there are 36 people online.

**Comment by winter2222** [comment]
today no online fb contacts are loaded for me, but messages are sent/ delivered but everyone is offline for me.

**Comment by newsjunkie247** [comment]
I don't know if it's related, but even though the notifications issue seems to be basically fixed, it seems to sometimes stop updating/showing new popups after a period of time.

**Comment by newsjunkie247** [comment]
And now I've somehow stopped getting pop notifications again entirely as well.

**Comment by ikeblaster** [comment]
@georgehazan I am afraid FB removed buddylist completely from `/pull` requests.

I loading presence of buddies using `/buddylist_update.php` endpoint. I must say it's really simple, it's just a list of online contacts (`{id: 1000013456, status: 0}`, status is always 0). It's possible to get another array containing all contacts (by appending `send_full_data=true` to POST data), but it's also crippled - everyone there has `status: -1` (if I remember correctly).

I am testing it locally, but I can create a pull request later. It would need some code review.

**Comment by georgehazan** [comment]
too bad that Facebook simply destroyed all old API calls that provided this information, so I had to rewrite this protocol completely to the new API... it will take time

**Comment by georgehazan** [comment]
@ikeblaster I think that all that stuff should be dropped and reimplemented using mqtt

**Comment by ikeblaster** [comment]
@georgehazan I just hope that mqtt would be fully usable. See this issue on project, which as far as I know uses mqtt. https://github.com/bitlbee/bitlbee-facebook/issues/185

Till that's ready here is promised PR. https://github.com/miranda-ng/miranda-ng/pull/1986

**Comment by georgehazan** [comment]
@ikeblaster thank you, this crutch seems to work, I merged you commit into master

**Comment by newsjunkie247** [comment]
I'm glad it's basically back. Is there anyway with a future update to bring back recognition of "away" status (when somebody is listed like away for x many minutes)?

**Comment by slanovani** [comment]
Ok, now it’s fixed. I’m getting status updates as well as online and offline contacts.
Good job!



De: newsjunkie247 <notifications@github.com>
Enviado el: domingo, 16 de junio de 2019 5:19 p. m.
Para: miranda-ng/miranda-ng <miranda-ng@noreply.github.com>
CC: Slann Tonić <reydelasmaquinas@outlook.com>; Manual <manual@noreply.github.com>
Asunto: Re: [miranda-ng/miranda-ng] Facebook not all contacts are showing as online (#1980)


I'm glad it's basically back. Is there anyway with a future update to bring back recognition of "away" status (when somebody is listed like away for x many minutes)?

**Comment by georgehazan** [comment]
@newsjunkie247 yes, when I'd implement MQTT, I'm working on it

@ikeblaster btw, have you skills in maintaining FB applications? I've got stuck :)

**Comment by ikeblaster** [comment]
@georgehazan What do you mean by FB applications? I am afraid I won't be able to help with that MQTT (actually never hear of it before this thread).

**Comment by newsjunkie247** [comment]
@georgeghazan Would that also help with getting back notifications for individual notifications? Like when multiple people post in groups within seconds? Used to be I could individual notifications for that.

**Comment by georgehazan** [comment]
@ikeblaster www.facebook,com - Manage applications 
I've already created a new application for Miranda NG, but there're numerous questions

**Comment by georgehazan** [comment]
@newsjunkie247 no, I don't think so

**Comment by newsjunkie247** [comment]
When I use the newest version of the Facebook protocol, the notifications chatroom doesn't seem to work properly, keeps going on and offline and on again.
