### ISSUE TITLE
Crash on import GPG-Key

### ISSUE THREAD

**Issue by vbprofi** [miranda-ng/miranda-ng#1983]
Miranda Crash Report from 13 Jun 2019 12:59:26. Crash Dumper v.0.1.0.3

Likely cause of the crash plugin: GPG

Exception: Unhandled C++ software exception at address 00007FF85C54A388.

Stack Trace:
---------------------------------------------------------------
00007FF85C54A388 (KERNELBASE 00007FF85C510000): (filename not available) (0): RaiseException
00007FF854F0486D (VCRUNTIME140 00007FF854F00000): (filename not available) (0): CxxThrowException
00007FF8390A64D2 (MSVCP140 00007FF839070000): (filename not available) (0): std::_Xout_of_range
00000000183C5555 (New_GPG 00000000183C0000): (filename not available) (0): (function-name not available)
00000000183FF70E (New_GPG 00000000183C0000): (filename not available) (0): (function-name not available)
0000000012B697FC (mir_core 0000000012B60000): (filename not available) (0): Ordinal920
0000000012B6FD2A (mir_core 0000000012B60000): (filename not available) (0): Ordinal737
0000000012B6F526 (mir_core 0000000012B60000): (filename not available) (0): Ordinal884
00007FF85DC321CC (USER32 00007FF85DC20000): (filename not available) (0): GetWindowRgnBox
00007FF85DC324AD (USER32 00007FF85DC20000): (filename not available) (0): Ordinal2573
00007FF85DC323C6 (USER32 00007FF85DC20000): (filename not available) (0): Ordinal2573
00007FF85DC36D41 (USER32 00007FF85DC20000): (filename not available) (0): CallWindowProcW
00007FF85DC36A1C (USER32 00007FF85DC20000): (filename not available) (0): CallWindowProcW
00007FF85DC404D3 (USER32 00007FF85DC20000): (filename not available) (0): IsWindowVisible
00007FF85FF3E6B4 (ntdll 00007FF85FEA0000): (filename not available) (0): KiUserCallbackDispatcher
00007FF85CB81164 (win32u 00007FF85CB80000): (filename not available) (0): NtUserMessageCall
00007FF85DC36256 (USER32 00007FF85DC20000): (filename not available) (0): SendMessageW
00007FF85DC360D8 (USER32 00007FF85DC20000): (filename not available) (0): SendMessageW
00007FF84760A755 (COMCTL32 00007FF8475E0000): (filename not available) (0): Ordinal235
00007FF84766A774 (COMCTL32 00007FF8475E0000): (filename not available) (0): Ordinal20
00007FF85DC36D41 (USER32 00007FF85DC20000): (filename not available) (0): CallWindowProcW
00007FF85DC36713 (USER32 00007FF85DC20000): (filename not available) (0): DispatchMessageW
00007FF85DC3954F (USER32 00007FF85DC20000): (filename not available) (0): IsDialogMessageW
00000000129D71F2 (mir_app 0000000012980000): (filename not available) (0): mir_main
0000000140002944 (Miranda64 0000000140000000): (filename not available) (0): (function-name not available)
00000001400014BA (Miranda64 0000000140000000): (filename not available) (0): (function-name not available)
00007FF85E304034 (KERNEL32 00007FF85E2F0000): (filename not available) (0): BaseThreadInitThunk
00007FF85FF13691 (ntdll 00007FF85FEA0000): (filename not available) (0): RtlUserThreadStart

CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz [Intel64 Family 6 Model 142 Stepping 10] [DEP Enabled] [8 CPUs]
Installed RAM: 8042 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 17134)
Internet Explorer: 9.11.17134.0 (build 917134)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : German/German | German/German

Miranda NG Version: 0.95.10.2 build #21709 (939edaf297) x64
Build time: 10 Jun 2019 15:16:52
Profile: E:\miranda-ng-v0.95.10.2_x64\Profiles\dbx\dbx.dat
Language pack: German (DE) [0407]
Service Mode: No

**Comment by apollo2k4** [comment]
Your crash log is not informative. If possible, please repeat the [creation of the crash log for this introduction](https://wiki.miranda-ng.org/index.php?title=Crash_reports).

**Comment by georgehazan** [comment]
I imported a key for a contact, it didn't crash
provide a log with symbols please

**Comment by georgehazan** [comment]
utilities.cpp, 1400:
		if (strstr(line, "-----END PGP PUBLIC KEY BLOCK-----")) {
			std::string::size_type p1 = 0, p2 = 0;
			p1 = key.find("Comment: login ");
			p1 += mir_strlen("Comment: login ");

если в файле нет этой строки, то импорт из главного меню падает.
из меню контакта импорт работает ok

**Comment by sss123next** [comment]
crash fixed in b34a90793af54c8b7a1e84846bfb73b47c9d8365
note: export/import from main menu used special file format, you can't import regular pubplic key this way because it must be attached to some contact, so additional fields is used during export, to import regular public key for specified contact please use contact menu instead

**Comment by sss123next** [comment]
> utilities.cpp, 1400:
> if (strstr(line, "-----END PGP PUBLIC KEY BLOCK-----")) {
> std::string::size_type p1 = 0, p2 = 0;
> p1 = key.find("Comment: login ");
> p1 += mir_strlen("Comment: login ");
> 
> если в файле нет этой строки, то импорт из главного меню падает.
> из меню контакта импорт работает ok

ну да, это не опциональное поле..., а вот проверки на его присутствие небыло, да.
