### ISSUE TITLE
[dbx_sqlite] Implement vacuumdb as a compaction method

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#1984]
**Is your feature request related to a problem? Please describe.**
mdbx (and even old mmap) had a compaction option which reduced db size

**Describe the solution you'd like**
A well-defined "vacuum" option exists for sqlite-type databases. It should be used.

**Describe alternatives you've considered**
I can manually open the miranda database file and run vacuum on it from a 3rd party application, but this is not ideal.

**Additional context**
For example after migration and various tasks, my database was 620MB. After vacuum, it shrank to 570MB.

**Comment by georgehazan** [comment]
implemented
