### ISSUE TITLE
After merging #1986, contact status change sound is played during each status update cycle

### ISSUE THREAD

**Issue by tyrylu** [miranda-ng/miranda-ng#1988]
### Expected behavior
The online/offline sounds will be played only for the changed statuses as they always did.

### Actual behavior
The offline sound is played for each contact (because of the bulk offline status assignment), afterwards, the online sound is played for the few who are online.

### Does it work in stable version?
It started when #1986 was merged and promoted to stable.

### Steps to reproduce that behavior
* Have the latest facebook plugin version with #1986.
* Setup a facebook account, some contacts would help.
* Set an offline and online sound.
* Observe the noise...

P. S.:, thanks for the fix, anyway.

**Comment by georgehazan** [comment]
it should be fixed in the nightly update
