### ISSUE TITLE
StdPopup: попап игнорирует настройку действий

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1990]
![image](https://user-images.githubusercontent.com/5046855/59765357-94c9f280-92a6-11e9-901c-52833ad61257.png)

Несмотря на то, что выбрано в этом меню, левый щелчок по тестовому попапу (кнопка Тест) вызывает окно с предложением перезапустить Миранду для обновления.

Нужно:
1) чтобы левый щелчок учитывал выбранное (закрывал попап, либо ничего не делал)
2) добавить в меню пункт "запросить перезапуск программы"

**Comment by georgehazan** [comment]
![image](https://user-images.githubusercontent.com/4628541/60359622-386f7d00-99e2-11e9-9594-08bbe4ba08bd.png)
дело в том, что реакция на кнопку и выдача сообщения зашита в программу попапа, поэтому от настроек она слабо зависит
