### ISSUE TITLE
Skype не получает списки контактов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1998]
В плагине skype не получают списки контактов. При запросе https://contacts.skype.com/contacts/v1/users/.../contacts - пишет код 401 Unauthorized

Может лучше использовать https://contacts.skype.com/contacts/v2/users/имя пользователя  Параметры url:
'delta' = '';
'reason'='default'

https://forum.ru-board.com/topic.cgi?forum=5&topic=50156&start=300#11

**Comment by georgehazan** [comment]
нет, там скайп глючит просто. у меня все ok
