### ISSUE TITLE
new_gpg force to use defective public keys option

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#200]
**Reported by sss sss on 18 May 2013 02:32 UTC**

**Comment by georgehazan** [comment]
**Modified by sss_sss on 12 Jun 2013 22:39 UTC**

**Comment by georgehazan** [comment]
**Modified by mataes on 28 May 2014 04:30 UTC**

**Comment by dartraiden** [comment]
Missing comments from Trac:

> Changed 4 years ago by mng:
> the version where all works fine is:
> 
> Miranda NG Version: 0.93.4 #2450 x64
> 
> version of new_gpg.dll is:
> 
> new_gpg.dll v.0.9.0.0 [23 Nov 2012 21:56:32] - GPG
> 
> 
> 
> Changed 4 years ago by mng:
> it seems to be related to UTF8 support in the ICQ protocol.
> 
> I did few tests on the latest alpha build (0.94.3) with SIM 0.9.5 client.
> 
> SIM 0.9.5 uses UTF-8 by default
> Miranda-NG runs on Windows 7 thus using CP1251
> 
> russian text SIM->Miranda-NG without GnuPG doesnt work, english works
> russian/english text Miranda-NG->SIM without GnuPG works
> russian/english text SIM->Miranda-NG with GnuPG doesnt work (decryption failed)
> russian/english text Miranda-NG->SIM with GnuPG works
> 
> If I switch SIM 0.9.5 to use CP1251 on specific contact here are the results:
> russian/english text SIM->Miranda-NG without GnuPG works
> russian/english text Miranda-NG->SIM without GnuPG works
> russian/english text SIM->Miranda-NG with GnuPG doesnt work (decryption failed)
> russian/english text Miranda-NG->SIM with GnuPG works
> 
> 
> 
> Changed 4 years ago by sss_sss
> looks like this is encodings problem, and not gpg related ?
> 
> 
> 
> Changed 4 years ago by mng:
> maybe partly, because on the old version New_GPG was able to handle UTF-8 text.
> 
> 
> 
> 
> Changed 4 years ago by sss_sss:
> are you using metacontacts ?
> 
> 
> 
> Changed 4 years ago by mng:
> is it a plugin, right?
> 
> if so I don't.
> 
> 
> 
> Changed 4 years ago by mng:
> checked latest trunk with fresh new profile, GPG asks to specify homedir and GnuPG binary I typed relative paths into the dialog (because there is gnupg folder in the root of miranda dir): #207
> 
> 
> 
> Changed 4 years ago by sss_sss:
> first: please follow one simple rule, one problem = one ticket
> second: very interesting, it will be very helpful if you will provide miranda package on which i will easily reproduce this
> 
> 
> 
> Changed 4 years ago by mng:
> and this bug is still in the latest trunk
> 
> Miranda NG Version: 0.94.4 alpha build #4922 x64
> 
> 
> 
> Changed 4 years ago by sss_sss:
> looks like new_gpg conflicting with other filters, this is expected behaviour and very hard to fix, i leave this ticket for future, but it can be closed as invalid/wontfix anytime.
> 
> 
> 
> Changed 3 years ago by mng:
> the build from the site seems to be broken, whilst sss debug build is just working fine.
> 
> 
> 
> Changed 2 years ago by mng:
> Miranda NG Version: 0.95.2 alpha build #9766 x64 Build time: 12 Jul 2014 6:54:44
> 
> this bug reproduces on fresh latest ALPHA version.
>

**Comment by sss123next** [comment]
ancient bug.
reopen if still relevant.
