### ISSUE TITLE
Miranda ng hanging my entire pc.

### ISSUE THREAD

**Issue by mr-cmd** [miranda-ng/miranda-ng#2021]
Hi developer i am Using 

Stable version (0.95.10.3) | 64 bits on laptop (Lenovo g50-45) 8Gb of ram, Windows 10 (1903).
I am using miranda ng from a long time, but from previous 1year its not working properly.
After installing miranda ng its Started hanging the entire pc, so we cant open any application.
If we uninstalled it from the machine everything started working perfectly.
Kindly fix this bug.
Thanks you in Advance

**Comment by dartraiden** [comment]
This is a well-known problem with clist_modern I think

See https://wiki.miranda-ng.org/index.php?title=Known_problems for solution

**Comment by mr-cmd** [comment]
Thanks you so much for the solution.
Now its working fine
