### ISSUE TITLE
Add AIM support

### ISSUE THREAD

**Issue by Nojus2001** [miranda-ng/miranda-ng#2029]
Since the Official Servers for AOL Instant Messenger shutdown 2 Years ago, there has been a revival server at http://iwarg.ddns.net/aim and it has gotten some popularity and I wonder if it's possible to add support to Miranda-NG?

**Comment by de77** [comment]
support of AIM was dropped in Miranda-NG version 0.95.7. See https://wiki.miranda-ng.org/index.php?title=Plugin:AIM

**Comment by dartraiden** [comment]
There is no reason to reanimate a corpse
Besides, it was ANSI and always brought a certain amount of madness
