### ISSUE TITLE
Фокус при переключении вкладок

### ISSUE THREAD

**Issue by Deadooshka** [miranda-ng/miranda-ng#2032]
При переключении вкладок фокус не переносится в поле ввода текста открываемого чата. Требуется дополнительно кликнуть в поле ввода, иначе текст будет набираться в предыдущей вкладке. Раньше такого не было. Плагин чата стоковый.

**Comment by georgehazan** [comment]
что есть "стоковый плагин чата"? StdMsg? tabSRMM?
