### ISSUE TITLE
ICQ плагин не показывает сохранённый пароль после перезапуска миранды.

### ISSUE THREAD

**Issue by apollo2k4** [miranda-ng/miranda-ng#2040]
Создаём аккаунт, вводим UIN и пароль, входим → всё ОК.
Перезапускаем миранду и получаем окно настроек в котором есть UIN и миранда подключается к сети ICQ, но при этом в поле «пароль» пусто, хотя в редакторе видно, что там сохранено значение.

**Comment by georgehazan** [comment]
в старом плагине так всегда и было. пароль не выводится в окне настроек из-за соображений безопасности, если его надо сменить, то можно вбить новый
