### ISSUE TITLE
Проблемы после переключения с TabSRMM на StdMsg

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2045]
1) в табсах было включено автоматическое копирование выделенного текста из лога
в StdMsg оно продолжает автокопироваться, но возможности отключить это нет

2) в табсах был отключён тулбар (панель кнопок)
в StdMsg тулбара нет в приватах, но есть в групчатах и нет возможности вернуть тулбар в приваты

**Comment by georgehazan** [comment]
>в StdMsg тулбара нет в приватах, но есть в групчатах и нет возможности вернуть тулбар в приваты

в смысле "нет возможности вернуть тулбар в приваты"?
![image](https://user-images.githubusercontent.com/4628541/64274543-409ce900-cf4c-11e9-9830-f3ab173ab1f5.png)

**Comment by georgehazan** [comment]
а в групчатах там отдельная настройка для тулбара. могу выпилить
