### ISSUE TITLE
Facebook treats miranda is suspicious activity and eventually blocks account

### ISSUE THREAD

**Issue by ThosRTanner** [miranda-ng/miranda-ng#2056]
### Expected behavior
I should be able to use miranda to view facebook messages without my account being blocked

### Actual behavior
My account gets blocked, eventually permanently

### Does it work in stable version?
Don't know if this works in stable. I doubt it

### Steps to reproduce that behavior
Connect, disconnect, reconnect to facebook and also use facebook and messenger in your browser
 * Attach your VersionInfo.
[spoiler=VersionInfo][quote]CPU: AMD Ryzen 7 1800X Eight-Core Processor  [AMD64 Family 23 Model 1 Stepping 1] [DEP Enabled] [16 CPUs]
Installed RAM: 16318 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 18362)
Internet Explorer: 9.11.18362.0 (build 918362)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | English/English
Free disk space on Miranda partition: 459819 MBytes

Miranda NG Version: 0.95.11 alpha build #22149 (10da002708) x64
Build time: 9 Sep 2019 20:40:48
Profile: C:\Users\Dad\AppData\Roaming\Miranda NG\HilaryQuerrien\HilaryQuerrien.dat
Profile size: 4194304 Bytes
Profile creation date: 18 Jun 2017 6:37:28
Language pack: No language pack installed
Service Mode: No

[b]Active Plugins (21):[/b]
¤ AVS.dll v.[b]0.98.1.2[/b] [23 Aug 2019 2:03:10] - Avatar service 
¤ Console.dll v.[b]0.0.7.4[/b] [27 Jul 2019 2:04:14] - Console 
¤ CrashDumper.dll v.[b]0.1.0.4[/b] [9 Sep 2019 20:41:26] - Crash dumper 
¤ Db_autobackups.dll v.[b]0.1.0.4[/b] [9 Sep 2019 20:41:04] - Db autobackuper 
¤ Dbx_mdbx.dll v.[b]0.95.9.1[/b] [9 Sep 2019 20:42:28] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.[b]0.95.8.1[/b] [27 Jul 2019 2:04:14] - Miranda NG mmap database driver 
¤ Dbx_sqlite.dll v.[b]0.95.10.2[/b] [21 Jul 2019 2:04:06] - Miranda NG SQLite database driver 
¤ Discord.dll v.[b]0.6.2.1[/b] [9 Sep 2019 20:42:08] - Discord protocol 
¤ Dummy.dll v.[b]0.2.0.0[/b] [9 Sep 2019 20:41:58] - Dummy protocol 
¤ Facebook.dll v.[b]0.4.2.4[/b] [9 Sep 2019 20:41:32] - Facebook 
¤ GG.dll v.[b]0.95.11.1[/b] [23 Aug 2019 2:03:32] - Gadu-Gadu protocol 
¤ ICQ.dll v.[b]0.95.11.6[/b] [9 Sep 2019 20:42:16] - ICQ-WIM protocol 
¤ Import.dll v.[b]0.95.11.1[/b] [9 Sep 2019 20:41:16] - Import contacts and messages 
¤ IRC.dll v.[b]0.95.10.1[/b] [9 Sep 2019 20:40:54] - IRC protocol 
¤ Jabber.dll v.[b]0.11.0.5[/b] [9 Sep 2019 20:41:22] - Jabber protocol 
¤ MSN.dll v.[b]0.95.11.1[/b] [27 Jul 2019 2:04:42] - MSN protocol 
¤ PluginUpdater.dll v.[b]0.2.0.3[/b] [9 Sep 2019 20:41:32] - Plugin updater 
¤ SkypeWeb.dll v.[b]0.12.3.4[/b] [27 Jul 2019 2:05:28] - Skype protocol (Web) 
¤ SmileyAdd.dll v.[b]0.3.1.2[/b] [27 Jul 2019 2:04:34] - SmileyAdd 
¤ TabSRMM.dll v.[b]3.5.0.14[/b] [9 Sep 2019 20:41:00] - TabSRMM 
¤ TopToolBar.dll v.[b]0.8.0.5[/b] [21 Jul 2019 2:03:18] - TopToolBar 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
Discord                  1 - Enabled 0 - Disabled  Loaded
Facebook                 1 - Enabled 0 - Disabled  Loaded
IRC                      1 - Enabled 0 - Disabled  Loaded
MSN                      1 - Enabled 0 - Disabled  Loaded
SKYPE                    1 - Enabled 0 - Disabled  Loaded
YAHOO                    0 - Enabled 1 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 Proto_AIM.dll [19 Dec 2017 5:14:40]
 Proto_Discord.dll [9 Sep 2019 20:42:36]
 Proto_Dummy.dll [9 Sep 2019 20:42:36]
 Proto_Facebook.dll [9 Sep 2019 20:42:36]
 Proto_GG.dll [23 Aug 2019 2:04:46]
 Proto_ICQ.dll [9 Sep 2019 20:42:36]
 Proto_IRC.dll [9 Sep 2019 20:42:36]
 Proto_Jabber.dll [9 Sep 2019 20:42:36]
 Proto_MetaContacts.dll [9 Sep 2019 20:42:36]
 Proto_MRA.dll [9 Sep 2019 20:42:36]
 Proto_MSN.dll [27 Jul 2019 2:06:00]
 Proto_Skype.dll [27 Jul 2019 2:06:02]
 TabSRMM_icons.dll [9 Sep 2019 20:42:36]
 Toolbar_icons.dll [23 Aug 2019 2:04:46]
 xStatus_Jabber.dll [9 Sep 2019 20:42:36]
[/quote][/spoiler]
 * Attach a crash report if you are experiencing crashes (It includes VersionInfo as well).
 * Attach a network log captured if you are experiencing connectivity issues.
 * If Miranda freezes, hangs up or consumes CPU, attach information obtained by Process Explorer tool.

**Comment by georgehazan** [comment]
No, that's not possible to prevent FB from blocking accounts that use Miranda. Your account can be recovered by usual procedure of entering SMS code or anything like that

**Comment by ThosRTanner** [comment]
I think you are missing the point. Facebook is blocking my account due to my use of miranda. Please reopen this.

**Comment by dartraiden** [comment]
Facebook cannot block account that use Miranda *permanently*
Sometimes Facebook blocks account that use Miranda, this is known bug

https://wiki.miranda-ng.org/index.php?title=Plugin:Facebook
