### ISSUE TITLE
Request: MQTT protocol for Facebook

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2058]
Sometimes FB is treated Miranda as malware, so we need to implement a new protocol for Facebook

https://en.wikipedia.org/wiki/MQTT
https://github.com/miranda-ng/miranda-ng/tree/master/protocols/Facebook (does not work)

**Comment by peci1** [comment]
For inspiration: pidgin plugin for Facebook works without a glitch.

https://bitbucket.org/pidgin/main/src/default/libpurple/protocols/facebook/
https://github.com/dequis/purple-facebook/tree/master/patches

The organization of the source code is a bit weird, but I hope it could help someone.

**Comment by ikeblaster** [comment]
Also this. https://github.com/7osCraft/facebook-chat-api/blob/master/src/listenMqtt.js

It uses 219994525426954 as `aid` (app id). It's the same value as messenger in browser uses.

**Comment by dartraiden** [comment]
Implemented. Further issues should be reported in new tickets.
