### ISSUE TITLE
Clist_modern: Добавить search box для поиска контакта и кнопку для его вызова

### ISSUE THREAD

**Issue by ziceptor** [miranda-ng/miranda-ng#2060]
На данный момент для поиска контакта необходимо активировать окно и начать набирать текст. Для рядового пользователя это не очевидно и не удобно.

Это могла бы быть кнопка на панели инструментов (TopToolBar), при нажатии на которую в верхней части контакт листа появлялось бы поле ввода.

**Comment by georgehazan** [comment]
- для доступа к toptoolbar тоже надо активировать окно;
- там могут быть только кнопки (это не ribbon control);
- Windows style - это именно поиск прямо по списку, как в Проводнике

**Comment by ziceptor** [comment]
Про активацию окна я написал в связке.. суть в том, что бы пользователю дать привычный инструмент поиска. Windows style, для абстрактной шестидесятилетней бабы Любы не знаком. Она понажимает кнопочек случайно и имеет в итоге не полный контакт лист и в ужасе кричит "пропали контакты" и т.д. и т.п.

У нас уже есть режимы вида, значит внедрить поле ввода не составит труда. Пользователь пишет текст в поле, а нажатия транслируются в список контактов, критически ничего не поменяется.

**Comment by 0x4E69676874466F78** [comment]
@georgehazan windows style не фильтрует список, а спускает фокус к совпадающему элементу.
