### ISSUE TITLE
Netlib_Recv() failed, error=10054

### ISSUE THREAD

**Issue by ziceptor** [miranda-ng/miranda-ng#2065]
лог https://pastebin.com/LsVb7dkD

Миранда отключилась от сервера. Сервер был доступен.. пинговался, но миранда не переподключалась к нему даже если руками изменить статус.

**Comment by georgehazan** [comment]
йес, наконец-то :) 
спасибо, щас мы это отловим

**Comment by apollo2k4** [comment]
Неужели это произошло!

**Comment by ziceptor** [comment]
Переподключение происходит без проблем, после такой бяки в логах.

**Comment by georgehazan** [comment]
> Переподключение происходит без проблем, после такой бяки в логах.

ну в ошибке нет ничего необычного, просто порвался сокет, так бывает. а вот то, что после этого жабер не коннектился - это, конечно, была жопа. большое спасибо за лог, глазами я бы в жизни это не нашел
