### ISSUE TITLE
Introduce a delay in IRC "Perform" sequence

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2067]
Is it possible to introduce a delay in the execution of commands performed on events in IRC networks? Specifically, I need to issue a NickServ GHOST command, and then to set my nick. But the GHOST needs some time to perform, and the command is returned immediately and is performed asynchronously, so /nick command issued immediately just fails.

I wanted my Perform sequence to look somewhat like this:
```
/msg NickServ GHOST <mynick>
<DELAYCOMMAND 500 ms>
/nick <mynick>
```

https://forum.miranda-ng.org/index.php?topic=5876

**Comment by georgehazan** [comment]
inside Perform /sleep [ms] does precisely that thing
