### ISSUE TITLE
Discord: поведение пунктов меню протокола Join guild и Copy my Discord ID

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2074]
Они появляются, когда включаешь опцию "Enable groupchats" и перезапускаешь миранду.

Тут сразу несколько багов:
- во-первых, непонятно, почему Copy my Discord ID зависит от наличия поддержки групчатов. По-моему, этот пункт должен быть всегда.
- во-вторых, после отключения "Enable groupchats" и перезапуска Миранды эти пункты не пропадают (что вообще нелогично - если они привязаны к этой настройке, они должны пропадать).
- в-третьих, юзер жалуется, что эти пункты не всегда и появляются после включения групчатов. Т.е., и пропадают они не всегда, и появляются не всегда.
- в-четвертых, эти пункты появляются в меню протокола лишь при перезапуске Миранды после включания поддержки групчатов в настройках протокола. Нельзя ли их добавлять/удалять на лету?

**Comment by dartraiden** [comment]
Фикс желательно портировать в стаблю.

**Comment by georgehazan** [comment]
> непонятно, почему Copy my Discord ID зависит от наличия поддержки групчатов. По-моему, этот пункт должен быть всегда.

пиздеж и провокация. этот пункт меню включен всегда

**Comment by georgehazan** [comment]
>  (что вообще нелогично - если они привязаны к этой настройке, они должны пропадать).

а он к нему и не привязан

**Comment by georgehazan** [comment]
>  юзер жалуется, что эти пункты не всегда и появляются после включения групчатов. Т.е., и пропадают они не всегда, и появляются не всегда.

Это меню протокола, его нельзя выключить или пропасть, его можно только перенести в главное меню с помощью галки в опциях

**Comment by dartraiden** [comment]
> его нельзя выключить или пропасть
а оно пропало
