### ISSUE TITLE
ICQ: small avatar in avatar management window

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2076]
<img width="359" alt="Miranda64_Pcpas7ZQCw" src="https://user-images.githubusercontent.com/5046855/65395494-1fd5ef80-dda4-11e9-8bee-834afe493ddb.png">

У других протоколов в этом диалоге показывается аватар большего размера. Насколько я помню, наш ICQ-WIM умеет работать с большими аватарами (старый протокол не осиливал больше, чем 80x80).

Т.е., я предлагаю не скукоживать аватар так сильно, места ещё полно.

**Comment by georgehazan** [comment]
сейчас в протоколе нет никаких ограничений на размер аватара, надо просто вместо мелкого брать аватар покрупнее, наверное

**Comment by georgehazan** [comment]
надо только стирать старый кэш аватаров, а то оно новые качать не будет
