### ISSUE TITLE
Plugin 'Import' cannot import history from text file exported by History++

### ISSUE THREAD

**Issue by mmadela** [miranda-ng/miranda-ng#2078]
### Expected behavior
The file is imported

### Actual behavior
The history is not imported, the wizard window displays:
'Cannot parse file header, skipping file'

### Does it work in stable version?
No

### Steps to reproduce that behavior
Export a contact history by:
navigate to a contact, 
open its history (Historypp plugin is active),
press book icon, 
select 'Export as text', 
save file, 
click on another user, 
select 'Import'
choose 'History++' as file type
select previously saved file
click OK
the above error is shown

current versions are used:

Miranda NG Version: 0.95.10.3 build #22079 (ac654ac11d) x64
Build time: 19 Sep 2019 20:24:32
Language pack: No language pack installed
Service Mode: No

[b]Active Plugins (14):[/b]
¤ AVS.dll v.[b]0.98.1.2[/b] [12 Aug 2019 19:58:56] - Avatar service 
¤ CrashDumper.dll v.[b]0.1.0.4[/b] [19 Sep 2019 20:25:06] - Crash dumper 
¤ Db_autobackups.dll v.[b]0.1.0.4[/b] [19 Sep 2019 20:24:46] - Db autobackuper 
¤ Dbx_mdbx.dll v.[b]0.95.9.1[/b] [19 Sep 2019 20:26:04] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.[b]0.95.8.1[/b] [1 Aug 2019 13:34:32] - Miranda NG mmap database driver 
¤ Dummy.dll v.[b]0.2.0.0[/b] [19 Sep 2019 20:25:34] - Dummy protocol 
¤ GG.dll v.[b]0.95.11.1[/b] [19 Aug 2019 20:54:52] - Gadu-Gadu protocol 
¤ historypp.dll v.[b]1.5.1.5[/b] [1 Aug 2019 13:36:18] - History++ 
¤ ICQ.dll v.[b]0.95.11.6[/b] [2 Sep 2019 16:16:36] - ICQ-WIM protocol 
¤ Import.dll v.[b]0.95.11.1[/b] [19 Sep 2019 20:24:56] - Import contacts and messages 
¤ Jabber.dll v.[b]0.11.0.5[/b] [19 Sep 2019 20:25:06] - Jabber protocol 
¤ PluginUpdater.dll v.[b]0.2.0.5[/b] [19 Sep 2019 20:25:08] - Plugin updater 
¤ SmileyAdd.dll v.[b]0.3.1.2[/b] [1 Aug 2019 13:34:50] - SmileyAdd 
¤ SpellChecker.dll v.[b]0.2.6.6[/b] [1 Aug 2019 13:35:48] - Spell checker

**Comment by dartraiden** [comment]
Works for me... (successfully import history from ICQ contact to Jabber contact)

Can you provide a header of exported file?

**Comment by mmadela** [comment]
###
### Full History Log
### Maaaa.Maaaa (JABBER_1: maaaa.maaaa@ssssss.com) - Maaaa Baaaa (mb) (JABBER_1: )
### (generated by history++ plugin)
###

[07.10.2015 09:35:00] Maaaa Baaaa (mb):

**Comment by dartraiden** [comment]
`¤ historypp.dll v.[b]1.5.1.5[/b] [1 Aug 2019 13:36:18] - History++`

outdated plugin?

**Comment by dartraiden** [comment]
Well, seems like this is a root of problem
`
### Maaaa.Maaaa (JABBER_1: maaaa.maaaa@ssssss.com) - Maaaa Baaaa (mb) (JABBER_1: )`

**Comment by mmadela** [comment]
thanks for correcting my post
my historypp.dll is dated 01.August, automatic update does not provide a newer one,
however a direct link on [page ](https://wiki.miranda-ng.org/index.php?title=Plugin:HistoryPP/en) contains a newer file

**Comment by dartraiden** [comment]
For some reason your contact have null Jabber ID (JID) in database. Install DbEditorPP plugin (via updater), go to contact menu → Open user tree in DBE++, locate "JABBER_1" section and delete "jid" key. Then reconnect the account to the network.

<img width="589" alt="Miranda64_MX0qVeyfT0" src="https://user-images.githubusercontent.com/5046855/65532523-9f7ad000-df04-11e9-9212-63bb2c0d4444.png">

**Comment by mmadela** [comment]
I cannot connect any more for this account, a server was changed and the old contacts are no longer working, there are the same contacts on the new server.
I want to import the history from the old contacts to the working ones.

**Comment by dartraiden** [comment]
Well, try to edit exported history and replace `Maaaa Baaaa (mb) (JABBER_1: )` by `Maaaa Baaaa (mb) (JABBER_1: example@example.com )`

**Comment by mmadela** [comment]
ok, manually patched file was correctly imported, thank you
