### ISSUE TITLE
gnupg version detection

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#208]
**Reported by mng on 12 Jun 2013 10:38 UTC**
on the first start of the fresh profile if i specify correct path to the gpg.exe and homedir just an empty dir it warns me out that version of GPG is incorrect:

![4fduoxq](https://cloud.githubusercontent.com/assets/5046855/21083926/9e5536c2-c00b-11e6-93fd-be3e45c4663c.png)

when I click OK it goes to the second menu warning me that there is no private key (thats actually right).

GPG version is correct:

gnupg\gnupg-bin>gpg --version
gpg (GnuPG) 1.4.7

Clearly, this is a bug in New_GPG in version detection.

Issue happens in the latest trunk version 
Miranda NG Version: 0.94.4 alpha build #4922 x64

**Comment by georgehazan** [comment]
**Modified by sss_sss on 12 Jun 2013 21:11 UTC**

**Comment by georgehazan** [comment]
**Modified by mataes on 28 May 2014 04:35 UTC**

**Comment by sss123next** [comment]
ancient bug.
reopen if still exists.
