### ISSUE TITLE
Настройки игнора метаконтакта не наследуются субконтактами

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2083]
Берем контакт, у которого НЕ стоит игнор Online notification
Суём его в существующую мету у которой СТОИТ игнор Online notification

Результат: при входе контакта в сеть будет событие Online notification. То есть, игнор Online notification, который стоит на мете, не наследуется её сабами.

Это очень неудобно, приходится матюгаться, вытаскивать этот саб из меты обратно, делая его полноценным контактом, ставить ему игнор Online notification и упихивать в мету.

**Comment by georgehazan** [comment]
суть немного не в этом. суть в том, что сабы при старте выставляются в состояние Hidden (чтобы они у клиста не путались под ногами), а для скрытых контактов уведомления не показываются. видимо, при засовывании контакта в мету Hidden не выставляется
