### ISSUE TITLE
SrmmLogContainer bugs

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2087]
- [x] <img width="482" alt="Miranda64_4KZAnLKnNU" src="https://user-images.githubusercontent.com/5046855/66002565-a6798380-e4ac-11e9-87fb-84c6cd202c58.png">

- [x] Jabber: меню конференции отсутствует

- [x] После отправки мной любого сообщения чат очищается

- [x] топик в конфе отображается словно обычное сообщение, отправленное мной, вероятно, как-то надо его иначе оформлять

- [x] копирование текста из конфы вызывает ошибку
<img width="291" alt="Miranda64_Tr6W8pTlha" src="https://user-images.githubusercontent.com/5046855/66003855-e4c47200-e4af-11e9-9a05-f5410b1f9559.png">

- [x] периодически в логе появляются совершенно пустые сообщения, при том, что участник, якобы отправивший их, молчал (презенсы?) если в h++ выставить фильтр на "сообщения", то эти пустышки не показываются, вероятно, это какие-то события, которые журнал не понимает

**Comment by georgehazan** [comment]
для топика в hpp честно передается флаг, что это топик, но h++ его игнорирует

**Comment by dartraiden** [comment]
Топик всё ещё отображается, как обычное сообщение

**Comment by georgehazan** [comment]
H++ вообще не сортирует события групчатов на типы, они для него все сообщения
