### ISSUE TITLE
miranda utf-8 support on incoming messages

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#209]
**Reported by mng on 12 Jun 2013 10:59 UTC**
 I'm using Miranda NG Version: 0.94.4 alpha build #4922 x64

there is an issue of receiving UTF-8 incoming messages from SIM-IM 0.9.5 client, I'm getting:

    14:57:33: С‚РµСЃС‚
    14:57:34: РµР±Р°РЅР°
    14:57:42: С‚РµРµРµРµСЃС‚

instead of the correct cyrillic messages

however, outgoing messages sent to the SIM are correctly displayed.

**Comment by georgehazan** [comment]
**Comment by ghazan on 12 Jun 2013 17:21 UTC**
it's a well known problem with the ICQ clients for Linux: they send messages in utf8 without specifying the encoding properly. you can set the default ANSI code page in ICQ options for all contacts, or set ICQ/CodePage=28666 in dbeditor for this concrete contact

**Comment by georgehazan** [comment]
**Comment by mng on 12 Jun 2013 20:11 UTC**
thanks for the tip i'll try this!

EDIT: can you point me where I should add this? I've added in both SRMM and ICQ_1 for this contact subvalues with type WORD (28666 in decimal, right)?

(screenshot would help a lot)

thanks a lot!

**Comment by georgehazan** [comment]
**Comment by mng on 12 Jun 2013 21:24 UTC**
 EDIT: can you point me where I should add this? I've added in both SRMM and ICQ_1 for this contact subvalues with type WORD (28666 in decimal, right)?

(screenshot would help a lot)

**Comment by georgehazan** [comment]
**Modified by mng on 13 Jun 2013 06:57 UTC**

**Comment by georgehazan** [comment]
**Comment by watcher on 13 Jun 2013 12:33 UTC**
ICQ_1/CodePage=w28666 - is for KOI8.

for UTF-8

In contact's database

ICQ_1/CodePage=w65001

**Comment by georgehazan** [comment]
**Comment by watcher on 13 Jun 2013 12:36 UTC**
[[Image(https://dl.dropboxusercontent.com/u/5359875/Snap/Snap%202013-06-13%20at%2015.35.02.png)]]

**Comment by georgehazan** [comment]
**Comment by mng on 14 Jun 2013 14:43 UTC**
like this:

[[Image(http://i.imgur.com/fK1VCxr.png)]] ?

EDIT: changed parameter to CodePage, still not working.

its not working.

**Comment by georgehazan** [comment]
**Comment by mng on 15 Jun 2013 17:56 UTC**
any update?

CodePage seems to be not working.

**Comment by georgehazan** [comment]
**Modified by mataes on 27 May 2014 06:18 UTC**

**Comment by georgehazan** [comment]
**Comment by mng on 12 Jul 2014 22:45 UTC**
this bug reproduces as well on fresh miranda-ng build from miranda-ng.org site:

Miranda NG Version: 0.95.2 alpha build #9766 x64 Build time: 12 Jul 2014 6:54:44

**Comment by georgehazan** [comment]
**Comment by ghazan on 17 Jul 2014 13:59 UTC**
attach a network log with this client, please

**Comment by dartraiden** [comment]
No netlog, ICQ was rewritten from scratch.
