### ISSUE TITLE
SkypeWeb: Неизвестное событие

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2096]
```Неизвестное событие, пожалуйста, отправьте этот текст разработчику: "<MediaAlbum albumId="a7033df4-3a25-4eb9-8473-6fc4198568de"></MediaAlbum>"```

https://forum.miranda-ng.org/index.php?topic=4705.msg25568#msg25568

**Comment by georgehazan** [comment]
запросил на форуме лог, если не пришлет, закрой тикет
никто это воспроизвести пока не может
