### ISSUE TITLE
Remove some obsolete shit

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2112]
- [x] 1) [MS_SYSTEM_SETIDLECALLBACK was replaced by Miranda_SetIdleCallback](https://github.com/miranda-ng/miranda-ng/commit/cb2efce1a4fe9c89c5fef63b3aca63f3e63983fc)

https://github.com/miranda-ng/miranda-ng/blob/8e8c80d9c99db7a0bf8272ad468fc7d5ea06dd8f/include/delphi/m_system.inc#L88

- [x] 2) [MS_SYSTEM_GETIDLE was replaced by Miranda_GetIdle](https://github.com/miranda-ng/miranda-ng/commit/cb2efce1a4fe9c89c5fef63b3aca63f3e63983fc)

https://github.com/miranda-ng/miranda-ng/blob/8e8c80d9c99db7a0bf8272ad468fc7d5ea06dd8f/include/delphi/m_system.inc#L97

- [x] 3) [MS_SYSTEM_GETBUILDSTRING was removed](https://github.com/miranda-ng/miranda-ng/commit/cb2efce1a4fe9c89c5fef63b3aca63f3e63983fc)

https://github.com/miranda-ng/miranda-ng/blob/8e8c80d9c99db7a0bf8272ad468fc7d5ea06dd8f/include/delphi/m_system.inc#L108

- [x] 4) [m_ieview.inc and hpp_external.pas were deleted](https://github.com/miranda-ng/miranda-ng/commit/48e0d2824f79489e28b027d3e7affcc218817bba) and [re-added](b4d51bb6ad3872b22d3ea52949d4cc5842c26da3). Is this a bug?

- [x] 5) [m_nMax was removed](835555b9555f43be50582c4be774d65fe69fbe4d), but still alive (search in sources)

- [x] 6) [MS_IGNORE_IGNORE was converted into function](226f2fceddb5b81d5ba7a16729b4f07e53cfafb4), but still exist in Actman services

https://github.com/miranda-ng/miranda-ng/blob/8e8c80d9c99db7a0bf8272ad468fc7d5ea06dd8f/plugins/Actman/services.ini#L184

- [x] 7) Same for MS_IGNORE_UNIGNORE

https://github.com/miranda-ng/miranda-ng/blob/8e8c80d9c99db7a0bf8272ad468fc7d5ea06dd8f/plugins/Actman/services.ini#L191

- [x] 8) [Manual experiments with CList/NotOnList was restricted](e441a31e9f912fc8e9244d16560565559b1924d2), but resurrected with WhatsApp (just search `hContact, "CList", "NotOnList"` in sources)

**Comment by georgehazan** [comment]
5) это был из другого класса m_nMax
8) это закомментированный код
