### ISSUE TITLE
[Discord] "Read X message" option is not working

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#2116]
### Expected behavior
Right-clicking a contact (whose online / away / etc message I can see and want to copy) and selecting "Read Online/Away/etc message" should let me see this message in a copy-able manner.

### Actual behavior
The window that pops up shows an empty message no matter what.

### Does it work in stable version?
No

### Steps to reproduce that behavior
 * Have someone on Discord with a status (be it game playing or music listening or just custom status)
 * try to get their status message by right-clicking and selecting "Read Online Message" (or whichever it is)

**Comment by georgehazan** [comment]
for Discord XStatusMsg is a game name ("game" attribute of one's presence)
if there's no XStatusMsg field inside his contact, you can't see it
