### ISSUE TITLE
[Discord] Support for the newly introduced Custom Status

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#2117]
**Is your feature request related to a problem? Please describe.**
https://support.discordapp.com/hc/en-us/articles/360035407531-Custom-Status
Discord now supports a custom status

**Describe the solution you'd like**
Since Miranda already has this feature, it would be nice if custom miranda status messages got propagated into Discord

**Describe alternatives you've considered**
None

**Additional context**
None.

**Comment by georgehazan** [comment]
I can't see it in the interface for another contacts (I can set mine but where can I view it?)

**Comment by LittleVulpix** [comment]
It shows up as status message for me. Settings shared in chat.
