### ISSUE TITLE
[Discord] "Group chats" (not guild chats) are not syncing offline messages

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#2118]
### Expected behavior
When someone says something in a group chat during my absence, it is synced next time I log in

### Actual behavior
When syncing, miranda tries to sync the group chat as id "0" and gets a NOT FOUND error, so no history is synced. Strangely enough however, the group history that is stored during regular chat time works just fine, and it is stored with the proper group chat ID file.

### Does it work in stable version?
No.

### Steps to reproduce that behavior
 * Have a group chat (at least 3 people)
 * Log off, and have someone send some messages in this group chat
 * Log back on, the messages are not retrieved

**Comment by dartraiden** [comment]
https://github.com/miranda-ng/miranda-ng/issues/2994

**Comment by georgehazan** [comment]
should be ok now
@LittleVulpix feel free to reopen it, if anything goes wrong with it
