### ISSUE TITLE
[dbx_sqlite] Event updates do not work properly

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#2121]
### Expected behavior
When someone modifies a message (for example in discord), I should be able to see the modified message.

### Actual behavior
In Ieview in my chat window, I see the same message repeated twice. In actual history, no change is reflected.

### Does it work in stable version?
It works with dbx_mdbx even in dev version.

### Steps to reproduce that behavior
 * use dbx_sqlite
 * send some link via discord
 * normally the link should get updated with the "embed" metadata, but it isn't.

**Comment by sss123next** [comment]
please check it in builds after b6216145513ed25b87a0f27f6554921b42adfea0

**Comment by LittleVulpix** [comment]
I wanted to try it, however, when I tried to import my mdbx profile into sqlite, it import said "Error loading source file, exiting".

**Comment by LittleVulpix** [comment]
@sss123next unfortunately the behavior is still the same. Embed data or "edits" are not stored in DB, and they also do not show in my chat window.

**Comment by sss123next** [comment]
understood.
how can i reproduce it without shitcord, they want mobile phone number and other private info, so it's not an option for me.

**Comment by LittleVulpix** [comment]
That is strange... My account is very old though so maybe that is why they let me go without personal info like phone and birthday and such.

I guess any protocol that lets you edit event content... I don't use any other protocolthat does though ( I guess webskype and facebook might, but I don'tuse them... )

@georgehazan has a discord account for testing, maybe you can borrow it?

**Comment by georgehazan** [comment]
@LittleVulpix easily

**Comment by sss123next** [comment]
@LittleVulpix can you please explain testing procedure, preferable step-by-step, i am not familiar to discord.

**Comment by LittleVulpix** [comment]
@sss123next , in your window, send a link to a friend (for example, youtube link). Discord servers will edit-replace your message with a sort of "embed" (thumbnail, preview, etc). This is normally reflected in miranda when not using sqlite. But when using sqlite, it is not reflected.

Similarly, when you use the Discord client or website and you edit your own message, the edited message content will show in your miranda now. But if you use SQLite, you will not see the modified message; instead you will see the same message posted again, sort of.

If you borrow Ghazan's account, he has me added as a friend I guess, I can chat with you to guide you there (maybe send a screenshot, etc).

Thanks!

**Comment by LittleVulpix** [comment]
Looks like this is working now.
