### ISSUE TITLE
ICQ: удалённый контакт зачем-то тут же вываливается в Not In List

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2122]
- добавляем контакт
- перезапускаем миранду для верности (можно и не перезапускать, это чтобы он стопудово улетел на сервер)
- удаляем контакт

Контакт удаляется из Миранды, Миранда удаляет его с сервера, но контакт тут же появляется Not In List. Зачем?

**Comment by georgehazan** [comment]
известно, зачем :) пакет от контакта пришел, значит, надо его в базу оформить :)

**Comment by apollo2k4** [comment]
Skype Web если что делает так же.
