### ISSUE TITLE
ICQ: контакт добавляется в неправильную группу

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2123]
У меня есть аськогруппа Contacts. Добавляю в неё человека. В моей Миранде он в клисте в группе Contacts.

Теперь завожу свою асю в чистую Миранду. И с сервера этот добавленный чувак подтягивается в General, а не в Contacts.

**Comment by georgehazan** [comment]
а в нетворк логе при входе оно в какой группе?

**Comment by georgehazan** [comment]
и еще хотелось бы лог добавления контакта

**Comment by dartraiden** [comment]
[netlog - Copy.txt](https://github.com/miranda-ng/miranda-ng/files/4908496/netlog.-.Copy.txt)
