### ISSUE TITLE
Notes & Reminders hotkeys

### ISSUE THREAD

**Issue by apollo2k4** [miranda-ng/miranda-ng#2126]
Т.к. функция вызова списка напоминалок часто вызывается, нельзя ли сделать для неё хоткей? А то приходится нажимать «Добавить напоминание» и уже оттуда заходить в «Список напоминаний», а потом ещё и закрывать окно «Добавить напоминание»..

[link](http://forum.ru-board.com/topic.cgi?forum=5&topic=50156&start=520#5)

**Comment by dartraiden** [comment]
хоткей какой-то одноразовый, получается

> вызвал по хоткею список напоминалок, закрыл. Снова нажал хоткей — всё, капут, никакой реакции (из меню список напоминалок тоже не вызывается).

**Comment by C1eriC** [comment]
Дело не в хоткее. Я потом пробовал открывать список напоминалок из меню. И тоже самое — раз открывается, в след. раз уже нет.

**Comment by georgehazan** [comment]
> Вероятно, это какая-то [общая большая ошибка](http://forum.ru-board.com/topic.cgi?forum=5&topic=50156&start=580#2).

Нет, это маленькая частная ошибка 😂😂 поправил

**Comment by C1eriC** [comment]
> поправил

Спасибо, обновился, сейчас список открывается. Но старые напоминалки так и не вылезли. При двойном щелчке по напоминалке из списка происходит открытие другой напоминалки.
