### ISSUE TITLE
Notes and Reminders: cannot import reminders from another db

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2132]
Пользователь прислал экспортированную ветку базы (там вместе хранятся настройки плагина и сами напоминания). После импорта ветки плагин не видит напоминания, а при перезапуске программы они вообще стираются из базы.

INI-шник предоставлю для тестов по запросу.

**Comment by georgehazan** [comment]
там всё состояние плагина грузится при входе в память, а при выходе выгружается в базу, затирая т.о. импортированные данные. чтобы всё работало, импорт надо вести в сервисном режиме
