### ISSUE TITLE
Likely cause of the crash plugin: Modern contact list

### ISSUE THREAD

**Issue by ziceptor** [miranda-ng/miranda-ng#2133]
При смене статуса на "не в сети", при помощи кнопки в заголовке контактлиста

![Скрин](https://i.imgur.com/YGtmaLI.png)

я получил [crash plugin](https://gist.github.com/ziceptor/840477d313868c2d3a526e9b5cf15783)

![Скрин настроек](https://i.imgur.com/l02jeZU.png)

**Comment by dartraiden** [comment]
Нужно обновиться до версии с отладочными символами и повторить лог.

**Comment by ziceptor** [comment]
[crash20191125112010.txt](https://github.com/miranda-ng/miranda-ng/files/3884891/crash20191125112010.txt)

**Comment by georgehazan** [comment]
сцуко... куда же оно девается. а часто это происходит?

**Comment by ziceptor** [comment]
Я баг поймал на стабильной версии, на версии в разработке его небыло. Поэтому проверять его там смысла нет.
