### ISSUE TITLE
TabSRMM missing "Set position for this session" menu

### ISSUE THREAD

**Issue by RathaWynter** [miranda-ng/miranda-ng#2134]
I just did a test-upgrade from:
Miranda NG 0.95.11.21135 (5a15c3af2e) - 2019-01-02 - Old client
Miranda NG 0.95.11.22337 (d98d238287) - 2019-11-24 - New client

The TABSRMM menu option to "Set position for this session" when resizing the input area seems to be missing from the current build of Miranda. The menu contained the following entries:
- Set position for this session
- Set and save for all sessions
- Set and save for this contact only
- Revert to old position

### Expected behavior
When resizing the message input area of the old client, a context menu would ask me whether i'd like to save this position for this session, for all sessions, for this contact, or revert accidental changes.

### Actual behavior
The new version of Miranda sets the position for the current window plus all currently open windows and all future chat windows. This change/bug removes the ability to have different sized input areas on a per-contact basis, or even just a temporarily changed input area size that does not affect all other windows.

-

Missing Feature:
![Set_Position_For_This_Session_Menu](https://user-images.githubusercontent.com/35881801/69499663-ba8ca080-0eb1-11ea-8276-59f2578b88ca.png)

[Versioninfo - 0.95.11.22337.txt](https://github.com/miranda-ng/miranda-ng/files/3884020/Versioninfo.-.0.95.11.22337.txt)

Below is the only reference to the missing function that I was able to find on Github using the search feature. But since I do not know how to use GitHub very well, someone else may be able to track down the actual commit that removed or broke this feature. The following file contained the text "Set position for this session" as well as the rest of the missing Menu settings.
https://github.com/miranda-ng/miranda-ng/blob/adddadb39220a5b135d9235140e3b63ffa374f7d/plugins/TabSRMM/res/resource.rc

**Comment by dartraiden** [comment]
This has been put behind "Use the same splitter height for all sessions" pref.
