### ISSUE TITLE
ICQ: мы не должны позволить добавлять [deleted]-контакты

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2136]
Сейчас при добавлении [deleted]-контакта протокол возвращает ошибку, но Миранда ничем не выдаёт это пользователю и спокойно добавляет контакт локально. Пользователь пребывает в уверенности, что всё прошло гладко, а контакт, разумеется, будет выкинут в NotInList и стёрт, ведь на сервере он не создался.

**Comment by georgehazan** [comment]
сервер их честно добавляет 
оставим пока как есть
