### ISSUE TITLE
ICQ: перестать стирать [deleted]-контакты

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2137]
Сейчас происходит следующее. Любой давно неактивный контакт рано или поздно удаляется Mail.ru и превращается в [deleted]. Этот процесс продолжается непрерывно. Например, человек в последний раз логинился год назад, пройдет ещё пара лет и его аккаунт уже будет удалён сервером по неактивности. Как только это произойдет, то все Миранды, у которых эта мертвая душа в контактах, выкинут его и сотрут. Это создаёт риск потери истории, если пользователь вовремя не заметит такую мертвую душу и не переведет её на Dummy.

**Comment by ziceptor** [comment]
+

**Comment by georgehazan** [comment]
никак. отменил стирание удаленных контактов, пусть болтаются, потому что на самом деле сервер позволяет их добавлять и никакого кода ошибки не возвращает

**Comment by dartraiden** [comment]
На сегодняшем билде такие контакты по-прежнему выкидываются в NotOnList и стираются затем.

**Comment by dartraiden** [comment]
Коммит https://github.com/miranda-ng/miranda-ng/commit/29e95647e80496938bf7bacc1afd352b687aed1f не помог.

Добавляем контакт 667709716. Лезем в базу, переименовываем его в ТЕСТ. Переподключаем аську. Контакт превращается в [deleted] и выкидывается в NotInList. Перезапускаем Миранду. Контакт стёрт.

**Comment by georgehazan** [comment]
не надо лезть в базу и переименовывать. надо нажать в клисте F2 и создать CList/MyHandle

**Comment by dartraiden** [comment]
какая ситуация:
в базе есть контакт Тест Тестович, которого на сервере уже нет, но миранда про это не знает

подключаемся к сети, с сервера прилетает инфа а) контакт переименовался в [deleted]; б) контакт стёрт с сервера

миранда переименовывает контакт, даёт ему ключ IcqDeleted И ДЕЛАЕТ NotInList=1

результат - контакт всё равно стирается

**Comment by dartraiden** [comment]
Скинул пример профиля, куда заведен контакт. Он выбрасывается в NotInList при подключении к сети.
