### ISSUE TITLE
SQLite, Scriver и количество последних сообщений.

### ISSUE THREAD

**Issue by apollo2k4** [miranda-ng/miranda-ng#2142]
При базе SQLite и Scriver если в "Показывать последних сообщений:" стоит какое-то количество, показывает только последнее сообщение, сброс настроек Scriver не помогает.

**Comment by alexeik** [comment]
также для tabsrmm 
![image](https://user-images.githubusercontent.com/318732/75622144-64b14e00-5bae-11ea-95e4-0a60c6e18c8f.png)

**Comment by sss123next** [comment]
fixed in 1198e47c25e12a4743b97674f254f13c6bc0bead

**Comment by alexeik** [comment]
Спасибо! Реал работает.
А то уж даже тормозило при открытии табов.
