### ISSUE TITLE
SkypeWeb: неудаляемый неизвестный контакт

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2149]
https://forum.miranda-ng.org/index.php?topic=4705.msg25908#msg25908

**Comment by georgehazan** [comment]
в этом логе нет добавления никакого контакта. надо его снести (можно удостовериться в этом в dbeditor++), перезапуститься и убедиться в том, что он создан
если в логе будут слова New contact created, этот лог я готов посмотреть
