### ISSUE TITLE
SkypeWeb зависает при синхронизации

### ISSUE THREAD

**Issue by BLF0x** [miranda-ng/miranda-ng#2150]
Если установить галку "Автоматическая синхронизация сообщений", то при загрузке миранды и подключения к скайпу, миранда зависает. При загрузке автоматически выходя в онлайн учетки ICQ, VK, SkypeWeb, MRA, MRA.
при этом skype зависает на анимации иконки статуса (вместе с ним зависает и все остальное, включая интерфейс миранды). Началось дня 2-3 назад после обновления... Если убрать Skypeweb.dll  то миранда включается, после если скачать плагин skypeweb не выключая работу миранды -- протокол (даже с галкой автосинхронизации) поднимается и работает... Если из миранды выйти, и запустить снова -- зависает.
Если убрать галку автосинхронизации -- все нормально работает

---------
CPU: Intel(R) Core(TM)2 Duo CPU E7400 @ 2.80GHz [x86 Family 6 Model 23 Stepping 10] [2 CPUs]
Installed RAM: 5120 MBytes
Microsoft Windows XP Professional Service Pack 3 (build 2600)
Internet Explorer: 8.0.6001.18702 (build 86001)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian
Free disk space on Miranda partition: 473 MBytes

**Comment by georgehazan** [comment]
Вопрос #1: используется ли плагин OpenSSL?

Вопрос #2: что надо сделать: зайти в нашу вики и прочитать пункт про использование Process Explorer (ну и скачать его, если он отсутствует) - https://wiki.miranda-ng.org/index.php?title=Using_Process_Explorer_as_the_debugging_tool. Также надо перейти на использование обновлений с отладочными символами.

Затем подвесить Миранду и приложить к ошибке стек главного потока (с _wWinMain)

**Comment by BLF0x** [comment]
OpenSSL используется... Выяснил вот что -- это не скайпвеб виноват... Когда идет подключение протоколов, если в кнопку главного меню миранды ткнуться  -- она повисает (при этом успевает сие меню отобразить)... 
При этом поскольку скайп автосинхронизацию делает - он подключается дольше других...
Поставил PE, но при зависании в закладке Threads -- пусто. Т.е. пока не зависает -- в окне Threads данные есть... При зависании оно пустое... 
Еще момент в нижнем окне PE при выборе Miranda32.exe много строчек <Pagefile backed> (Ошибка при чтении или записи в файл)

**Comment by BLF0x** [comment]
![miranda1](https://user-images.githubusercontent.com/33485944/71184591-0a7d3e00-228b-11ea-80d0-0510834ff0cd.jpg)

**Comment by BLF0x** [comment]
KRNL16.exe -- это пропатченный ntkrpamp.exe чтобы на 32-битной системе было доступно >4Г оперативки.

**Comment by BLF0x** [comment]
Без патченного ядра... картинка та же...
------- Start address 0x7C810CA1---------
ntoskrnl.exe+0x584d
ntoskrnl.exe+0x23e89
ntoskrnl.exe+0x1bc84
ntoskrnl.exe+0x96ff6
ntoskrnl.exe+0x69ab
ntdll.dll+0xe514
ntdll.dll+0x1046
0x00000000
-----------------------------------------------------

------- Start address ntdll.dll+0x54e6d---------
ntoskrnl.exe+0x584d
ntoskrnl.exe+0x23e89
ntoskrnl.exe+0x1bc84
ntoskrnl.exe+0x96ff6
ntoskrnl.exe+0x69ab
ntdll.dll+0xe514
ntdll.dll+0x1046
0x00000000
ntdll.dll+0x118a
ntdll.dll+0x19f95
ntdll.dll+0x19e0e
ntdll.dll+0xe457
-----------------------------------------------------

**Comment by dartraiden** [comment]
Problem still here

**Comment by dartraiden** [comment]
> George Hazan, [27.03.20 15:42]
> Я не знаю, как сказать Миранде, чтобы она не слала себя как user agent
> 
> George Hazan, [27.03.20 15:43]
> Есть подозрение, что Скайп это не любит
