### ISSUE TITLE
Notes and Reminders: date format & focus remove

### ISSUE THREAD

**Issue by goonis** [miranda-ng/miranda-ng#2152]
При выводе окна View Reminders предлагается использовать формат времени, установленный в системе, потому что дата выводится соотвественно настроек системы, а время странно видеть 1:40PM при формате времени в системе 13:40.

Еще предлагается убрать в этом же окне перемещение фокуса строки при перемещении мышки, которое делается с запаздыванием что часто приводит к непредсказуемым результатам при редактировании напоминалок, а перемещать его только при клике по конкретной строке.

**Comment by georgehazan** [comment]
в каком месте 1:40pm? 
![image](https://user-images.githubusercontent.com/4628541/71176476-03e6ca80-227b-11ea-8ff7-779abfb70c58.png)

**Comment by goonis** [comment]
Именно тут:
![f4d075b4 1](https://user-images.githubusercontent.com/8069033/71176833-bc147300-227b-11ea-8c94-cb5fd36288a1.png)
А это настройки Win10.
![4e1ceb8f 1](https://user-images.githubusercontent.com/8069033/71176857-c898cb80-227b-11ea-9400-5744be014657.png)

**Comment by goonis** [comment]
Кстати, вдогонку небольшая мелочь:
![image](https://user-images.githubusercontent.com/8069033/71177083-3b09ab80-227c-11ea-8a62-1a7e1de75906.png)
В самом низу ссылка на today заканчивается на 2 не захватывает 019 - это так задумано?

**Comment by georgehazan** [comment]
надо в Country or region поставить Russia, и всё пройдет

>В самом низу ссылка на today заканчивается на 2 не захватывает 019 - это так задумано?

это системная компонента, я ей никак не управляю

**Comment by goonis** [comment]
> надо в Country or region поставить Russia, и всё пройдет
> 

Если я правильно понимаю где, то так и стоит


![image](https://user-images.githubusercontent.com/8069033/71177318-cd11b400-227c-11ea-8961-f581049092b0.png)

**Comment by georgehazan** [comment]
Regional format -> Russian (Russia)

**Comment by goonis** [comment]
> Regional format -> Russian (Russia)

А если мне не нужна дата на русском? 
Формат времени же регулируется незавсисимо от того что стоит в Regional Format

**Comment by georgehazan** [comment]
если United States, то будет PM, 
рекомендую попробовать немецкий формат, он иногда выручает

**Comment by goonis** [comment]
То есть настройки Long time и Short time системы никак не влияют на форматы времени в приложениях?

**Comment by georgehazan** [comment]
я не знаю. я использую функцию винды, которая форматирует время и дату в соответствии с настройками из Control Panel

**Comment by goonis** [comment]
Ног ведь какая-то функция переключает формат отображения. например, часов в трее при смене формата Short time.
