### ISSUE TITLE
Latest dev update killed Miranda NG

### ISSUE THREAD

**Issue by PaderDesign** [miranda-ng/miranda-ng#2177]
### Expected behavior
What did you expect?
After updating, Miranda NG should launch as known.

### Actual behavior
What did you get instead?
When I launch Miranda NG it tells me, that the Profile MIRANDA.dat can not be opened, because it has the wrong format.

### Does it work in stable version?
If you know in which dev build (or approximate date when) it was broken, it may be much easier to identify and fix the issue.
unknown

### Steps to reproduce that behavior
 * Provide step-by-step instructions so we can reproduce the issue (We can't fix what we can't reproduce).
Just update to the dev version from 3.5 hours back and try to launch Miranda NG
 * Attach your VersionInfo.
latest dev version
 * Attach a crash report if you are experiencing crashes (It includes VersionInfo as well).
Miranda NG does not create a crash report. Instead I made this screenshot of the upcoming message: https://snipboard.io/6iP28y.jpg
 * Attach a network log captured if you are experiencing connectivity issues.
--
 * If Miranda freezes, hangs up or consumes CPU, attach information obtained by Process Explorer tool.
--

**Comment by georgehazan** [comment]
there was a short period of time when the broken db driver was present at the server (in 32-bit version)
now it's fixed, so any update after profile restoration will work ok

**Comment by georgehazan** [comment]
I've made an investigation, this is the problem with profiles created by the very first version of LMDB driver... so, to switch correctly to the newer format of it, you can try two following methods

1. after old MDBX driver restoration, enter your profile and click Database - Compact in the main menu. Then save this file and try to upgrade

2. If the first method fails, restore MDBX driver again and create a new empty profile and on the creation dialog check "Run in service mode" and choose Import. Then make a full import from the old profile using the topmost radio button in the Import wizard
