### ISSUE TITLE
Miranda NG can no longer read my existing profile

### ISSUE THREAD

**Issue by winman3000** [miranda-ng/miranda-ng#2178]
Today I installed the latest update from Miranda NG. Since then Miranda NG can no longer read my profile. It reports that it was created in an unknown format. I didn't change anything in my profile file.

**Comment by winman3000** [comment]
I was able to temporarily solve the problem by restoring my database backup. Of course, I don't know if the problem recurs after an update.

**Comment by georgehazan** [comment]
there was a short period of time when the broken db driver was present at the server (in 32-bit version)
now it's fixed

**Comment by georgehazan** [comment]
I've made an investigation, this is the problem with profiles created by the very first version of LMDB driver... so, to switch correctly to the newer format of it, you can try two following methods

1. after old MDBX driver restoration, enter your profile and click Database - Compact in the main menu. Then save this file and try to upgrade

2. If the first method fails, restore MDBX driver again and create a new empty profile and on the creation dialog check "Run in service mode" and choose Import. Then make a full import from the old profile using the topmost radio button in the Import wizard
