### ISSUE TITLE
Facebook: attachment sometimes doesn't load

### ISSUE THREAD

**Issue by ikeblaster** [miranda-ng/miranda-ng#2179]
```
{
	"error_code": 509,
	"error_msg": "Invalid attachment id (509)",
	"request_args": [
		{
			"key": "method",
			"value": "messaging.getAttachment"
		},
		{
			"key": "aid",
			"value": "2176195146023127"
		},
		{
			"key": "api_key",
			"value": "256002347743983"
		},
		{
			"key": "device_id",
			"value": "67523c32-da83-4415-857b-4e3c6f6cxxxx"
		},
		{
			"key": "fb_api_req_friendly_name",
			"value": "getAttachment"
		},
		{
			"key": "format",
			"value": "json"
		},
		{
			"key": "locale",
			"value": "en"
		},
		{
			"key": "mid",
			"value": "mid.$cAAAABwoJjQd1u-4Fs1viqi73x2UR"
		},
		{
			"key": "sig",
			"value": "ba9995d9fab2159973a40460e008xxxx"
		}
	]
}
```

When I tried it manually few minutes later, `messaging.getAttachment` returned expected data (no error). So maybe just delaying attachments loading for like 10-100 ms would be okay? Or trying it multiple times with delay in between (in new thread, not blocking other messages).

**Comment by georgehazan** [comment]
that means the current schema should be rewritten completely to async calls

**Comment by ikeblaster** [comment]
@georgehazan So far works perfect, great work.

I will have to send you some donate, you are insane. :) I am not able to keep up with all the improvements.

**Comment by georgehazan** [comment]
@ikeblaster paypal => @georgehazan 
you're welcome ❤🧐
