### ISSUE TITLE
"Miranda was unable to open <profile_name>, it's in an unknown format"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2181]
We need to implement crutch for this...

https://www.miranda-ng.org/en/news/unknown_profile_format

**Comment by peci1** [comment]
I tried to follow the suggested solution after running Miranda with the incompatible db. I didn't succeed fixing the screwed up db. I had to restore an older db from autobackups, and then it works.

**Comment by dartraiden** [comment]
[first256.zip](https://github.com/miranda-ng/miranda-ng/files/4049339/first256.zip)
for @georgehazan

**Comment by dartraiden** [comment]
Another one
[mir20190115.zip](https://github.com/miranda-ng/miranda-ng/files/4049503/mir20190115.zip)

**Comment by dartraiden** [comment]
+1
[newpiece.zip](https://github.com/miranda-ng/miranda-ng/files/4049573/newpiece.zip)

**Comment by georgehazan** [comment]
Ok, got it.
