### ISSUE TITLE
Facebook plugin "unauthorized access"

### ISSUE THREAD

**Issue by Wolfie0827** [miranda-ng/miranda-ng#2187]
The issue as reported in issue #1902 of facebook requiring password change due to "unauthorized access" when using Miranda to connect to chat seems to be still an issue, I run into it every time I try to use Miranda NG to log in to FB chat. I'm using Miranda NG version 0.95.10.3 Build #22095.

**Comment by georgehazan** [comment]
that is the old plugin, you need to upgrade your Miranda to the development version (0.95.11) using Plugin Updater and try again
