### ISSUE TITLE
Keyboard notify: не работает моргание в групчатах

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2190]
Ни на хайлайт, ни на простое сообщение.

**Comment by dartraiden** [comment]
> если у меня есть несколько групповых чатов, с непрочитанными сообщениями, достаточно открыть один, любой, чтобы индикация прекратилась.
> Можно-ли сделать так, чтобы индикация продолжалась пока хоть в одном из чатов есть новые сообщения?

**Comment by georgehazan** [comment]
неа, нельзя, потому что функция проверяет наличие нечитанных сообщений в базе, и пока они есть, оно моргает, а групчаты не создают события в базе, поэтому моргание прекращается сразу.
