### ISSUE TITLE
facebook protocol does not connect after updating

### ISSUE THREAD

**Issue by slanovani** [miranda-ng/miranda-ng#2192]
I've just updated to miranda ng 0.95.11, and i've found that the facebook protocol is now not connecting. I've updated all plugins including facebook protocol plugin, i've even removed and added the account for once again, and it just populates contact list but does not connect. no matter how many times I try to connect, it always keeps me offline.

**Comment by georgehazan** [comment]
A network log would be appreciated, core + Facebook. Refer to our Wiki how to make them: https://wiki.miranda-ng.org/Network_log.

You can attach a network log here or email it to ghazan at miranda.im

**Comment by slanovani** [comment]
here's a network log, hope it's helpful. 

regards,

slanovani
[netlog.txt](https://github.com/miranda-ng/miranda-ng/files/4149512/netlog.txt)
