### ISSUE TITLE
Twitter bug with Scriver or Tabsrmm

### ISSUE THREAD

**Issue by MrMyth** [miranda-ng/miranda-ng#2193]
Tabsrmm будто бы игнорирует настройку Twitter "Твиты как сообщения". Огромная просьба: раз не удается исправить Scriver, то поправьте хотя бы получение твитов как сообщений у Tabsrmm. Если я ставлю scriver - то твиты действительно приходят как сообщения. Если я ставлю Tabsrmm - твиты приходят как сообщения, но вот уведомлений об этом в трее и т.д нет. Новая вкладка в окне переписки не появляется также. Спасибо.
--------------------------------------------------------------------------------------------------------------
Tabsrmm seems to be ignoring Twitter tweets as messages. Huge request: since it is not possible to fix Scriver, then correct at least receiving tweets as messages from Tabsrmm. If I put a scriver, then the tweets really come as messages. If I put Tabsrmm - tweets come as messages, but there are no notifications about this in the tray, etc. A new tab in the chat window does not appear either. Thanks.

**Comment by georgehazan** [comment]
данные сообщения создаются с флагом "уже прочитанные", соотв. tabSRMM под них не зажигает контейнер (если не включена галка "Всегда поднимать контейнер на новые сообщения"). А уведомлений о прочитанных сообщениях реально не будет

**Comment by MrMyth** [comment]
> данные сообщения создаются с флагом "уже прочитанные", соотв. tabSRMM под них не зажигает контейнер (если не включена галка "Всегда поднимать контейнер на новые сообщения"). А уведомлений о прочитанных сообщениях реально не будет

А нельзя ли сделать настройку, которая сделает поведение сообщений одинаковым для обоих плагинов?

**Comment by georgehazan** [comment]
А в чем сейчас разница? Scriver точно так же не должен поднимать окно на уже прочитанные события.

Опция вот тут:
![image](https://user-images.githubusercontent.com/4628541/73686689-87e4fc80-46d9-11ea-8bac-60f9e6953f33.png)

**Comment by MrMyth** [comment]
> А в чем сейчас разница? Scriver точно так же не должен поднимать окно на уже прочитанные события.
> 
> Опция вот тут:
> ![image](https://user-images.githubusercontent.com/4628541/73686689-87e4fc80-46d9-11ea-8bac-60f9e6953f33.png)

Разница в том, что Scriver принимает твиты как сообщения. То есть создает вкладку в контейнере , играет звук и т.д. хотя вы говорите, что твит приходит прочитанным сообщением.

Если коротко объяснять: Scriver работает с твитами как с НЕ ПРОЧИТАННЫМИ сообщениями.
Tabsrmm обрабатывает твиты как ПРОЧИТАННЫЕ сообщения.

**Comment by MrMyth** [comment]
Упомянутая выше настройка включена, а Tabsrmm даже не создал вкладку для твита.

**Comment by MrMyth** [comment]
Я лучше вот так напишу. Сделайте пожалуйста так, чтобы если включено "Твиты как сообщения", то добавляет вкладку в контейнер. Хотел сам дописать, но не вышло.

**Comment by georgehazan** [comment]
ну там по факту достаточно убрать флаг "уже прочитано", и оно будет исправно мигать везде

**Comment by MrMyth** [comment]
Спасибо! Работает так как нужно, кроме одного. Нужно каждому пользователю для случая "Твиты как сообщения" отключать уведомления о смене статусного сообщения. Можно это в автомат добавить или по отдельной поднастройкой? Сейчас приходит уведомление о сообщении, а потом о новом статусном сообщении. Пока что вручную отключил для твитера уведомления о статусных сообщениях.
