### ISSUE TITLE
Update asks for permission twice

### ISSUE THREAD

**Issue by thany** [miranda-ng/miranda-ng#2195]
Whenever the program wants to update itself, it asks for permission to do so, twice. And that's even after clicking the "Update" button.

First, a UAC prompt comes up. I allow it. Second, another question pops up that asks me if I want to go ahead and do the update.

Assuming the UAC prompt is neccesary (there are ways to whitelist an application) after that it should just do the update right away. By that time, I have already clicked two buttons to make the update go ahead (first the "Update" button in the auto update popup, and secondly the UAC prompt).

I really think it's a bit overkill to expect the user to click three windows away in order to perform an update. And tbh, I usually hit Cancel because even though it takes less than 10 seconds, I just don't feel like it.

Best would be to just do it fully automatically, for example next time the program starts. Don't ask me, just do it.

I'm on Windows 10, and Miranda 0.95.11.

**Comment by georgehazan** [comment]
@thany 
> Best would be to just do it fully automatically, for example next time the program starts. Don't ask me, just do it.

That would be great, of course, but UAC requires the access rights each time Miranda launches pu_stub.exe to escalate permissions, only that scheme allows Miranda to write into %ProgramFiles%.

Alternatively you can install Miranda completely into your %APPDATA% directory, to which Miranda has full write access, so these messages won't bother you again

**Comment by thany** [comment]
I think CCleaner has a trick to whitelist itself, even though it modifies the registry... Maybe that helps too. But I suppose installing in Appdata works too.

As for the other messages before&after UAC. Any chance of getting rid of them?

**Comment by dartraiden** [comment]
Miranda, usually asks only three questions:

1) update is found on server, downliad it?
2) UAC prompt (to be able to record tp Program Files)
3) all files are replcaced, restart?

All these questions are necessary:
1) sometimes update is undesirable (for example, if I compiled a last commit and want to test it)
2) UAC request...
3) restart Miranda forcibly without user permission ... there will be a lot of angry users

So you can check "Silent mode" option in Updater settings and install Miranda to non-system folder.

**Comment by thany** [comment]
Oh there's a silent option! I didn't know that. Awesome 👍🏼
I'll check it out when I get home.

**Comment by georgehazan** [comment]
@thany a-and? :-)
