### ISSUE TITLE
[0.95.11 x64] IRC: Update broke input box shortcuts & Tab key

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#2197]
### Description
I don't know what happened, but ever since the new stable update, I am not able to use Ctrl-I, Ctrl-B, etc. to transform text to bold, italics, etc in the input field of TabSRMM when on IRC.

They still work when selecting transformations from the toolbar.

Edit: More text box oddness: Auto-completing an IRC nick with Tab removes the cursor from the text box and makes you unable to keep on typing.

### Does it work in stable version?
Nope, since this is now the new stable version.

### Steps to reproduce that behavior
CPU: Intel(R) Core(TM)2 Quad CPU Q9550 @ 2.83GHz [Intel64 Family 6 Model 23 Stepping 10] [DEP Enabled] [4 CPUs]
Installed RAM: 8192 MBytes
Microsoft Windows 8.1 Professional Edition, 64-bit (build 9600)
Internet Explorer: 9.11.9600.19597 (build 99600)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | German/German
Free disk space on Miranda partition: 36667 MBytes

Miranda NG Version: 0.95.11 build #22521 (0c55a1c040) x64
Build time: 3 Feb 2020 19:22:22
Profile: C:\Users\xxx\AppData\Roaming\Miranda NG\xxx\xxx.dat
Profile size: 2097152 Bytes
Profile creation date: 11 Jan 2020 22:25:40
Language pack: No language pack installed
Service Mode: No

Active Plugins (16):
¤ AVS.dll v.0.98.1.2 [3 Feb 2020 11:22:56] - Avatar service 
¤ Clist_modern.dll v.0.9.1.8 [3 Feb 2020 11:23:28] - Modern contact list 
¤ CrashDumper.dll v.0.1.0.4 [3 Feb 2020 11:23:24] - Crash dumper 
¤ Db_autobackups.dll v.0.1.0.4 [3 Feb 2020 19:22:34] - Db autobackuper 
¤ DbEditorPP.dll v.4.0.1.3 [3 Feb 2020 11:23:24] - Database editor++ 
¤ Dbx_mdbx.dll v.0.95.9.1 [3 Feb 2020 19:24:00] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.0.95.8.1 [3 Feb 2020 11:22:56] - Miranda NG mmap database driver 
¤ Dummy.dll v.0.2.0.0 [3 Feb 2020 19:23:28] - Dummy protocol 
¤ Import.dll v.0.95.11.1 [3 Feb 2020 19:22:56] - Import contacts and messages 
¤ IRC.dll v.0.95.10.1 [3 Feb 2020 11:22:58] - IRC protocol 
¤ MagneticWindows.dll v.0.0.3.2 [3 Feb 2020 11:24:10] - Magnetic Windows 
¤ PluginUpdater.dll v.0.2.0.5 [3 Feb 2020 11:23:28] - Plugin updater 
¤ StatusManager.dll v.1.2.0.6 [3 Feb 2020 11:24:04] - Status manager 
¤ Steam.dll v.0.11.6.6 [3 Feb 2020 11:23:56] - Steam protocol 
¤ TabSRMM.dll v.3.6.0.3 [3 Feb 2020 11:23:04] - TabSRMM 
¤ Tox.dll v.0.11.3.2 [3 Feb 2020 11:24:30] - Tox protocol 

Protocols and Accounts:
-------------------------------------------------------------------------------
IRC                      7 - Enabled 0 - Disabled  Loaded
STEAM                    1 - Enabled 0 - Disabled  Loaded

Icon Packs:
-------------------------------------------------------------------------------
 a0x_blue.dll [25 May 2007 13:34:20]
 a0x_bw.dll [25 May 2007 13:34:26]
 a0x_green.dll [25 May 2007 13:34:32]
 a0x_main.dll [25 May 2007 13:34:38]
 a0x_orange.dll [25 May 2007 13:34:46]
 a0x_purple.dll [25 May 2007 13:34:52]
 a0x_red.dll [25 May 2007 13:34:58]
 a0x_set1_grey.dll [25 May 2007 13:35:16]
 a0x_weather.dll [25 May 2007 13:35:04]
 a0x_yellow.dll [25 May 2007 13:35:08]
 Proto_Dummy.dll [3 Feb 2020 19:24:08]
 Proto_IRC.dll [3 Feb 2020 11:24:34]
 Proto_MetaContacts.dll [3 Feb 2020 19:24:08]
 Proto_Steam.dll [3 Feb 2020 11:24:36]
 Proto_Tox.dll [3 Feb 2020 11:24:36]
 TabSRMM_icons.dll [3 Feb 2020 11:24:34]
 Toolbar_icons.dll [3 Feb 2020 11:24:34]

**Comment by Tharn** [comment]
If this fix has landed in `Miranda NG Version: 0.95.12 alpha build #22526 (59667bf72b) x64`, then it has not solved the issue.

**Comment by georgehazan** [comment]
no, it's neither new nor unticking itself :-) 
it always worked this way

**Comment by Tharn** [comment]
Tab key still takes focus away from the text box.
