### ISSUE TITLE
ICQ: приходит невалидная ссылка на файл

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2201]
Отправляю из официального клиента в миранду Excel-файл. Прилетает ссылка вида https://ub.icq.net/files/api/v1.1/get/SPsoRy5HVb8av1qg0dAIYY0dAInm69QSfKij8SNJZdRi81y4L1OtUKjS2AgxEIZDzp8IOzKjJI8b2uBGv5upaSe1lLESG5CdzIyqZxe1nkAPN1czu5lG2JiTQSXpvNWiHkQBZGpU3Nk1RhT8IGk7Mj2Sh10dAI/111.xlsx

по которой файл не скачивается.

[netlog.txt](https://github.com/miranda-ng/miranda-ng/files/4159554/netlog.txt)

**Comment by dartraiden** [comment]
Сходу один недочёт: когда _из_ Миранды отправляешь, то в журнале Миранды остаётся невалиднвя ссылка

```
dartraiden, 06.02.2020 0:24:48:
C:\Users\dartraiden\Desktop\metal_heart.mid

dartraiden, 0:24:48:
https://files.icq.net/get/G0000hp0FndLcNS1q4RPHL5e3b32a01ag

```

**Comment by dartraiden** [comment]
Здесь будут форматы, отправку которых протестировал:

MIDI - ок в обе стороны

**Comment by dartraiden** [comment]
Ещё замечание: входящий файл принимается автоматически, а в журнале остаётся запись

Ivan Ivanov, 06.02.2020 0:22:21:
Incoming file transfer:

**Comment by georgehazan** [comment]
txt файлы улетают на ура, нужен лог.
мигать сообщение будет только в случае, если прием не автоматически
