### ISSUE TITLE
ICQ: входящие изображения не помечаются прочитанными

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2202]
- в Миранду прилетает входящее изображение (png), настроено автопринятие файлов, оно скачивается
- выключаем Миранду
- запускаем её -> открывается окно принятых файлов

**Comment by dartraiden** [comment]
первый нетлог - приём файла
второй нетлог - рестарт миранды

[1.txt](https://github.com/miranda-ng/miranda-ng/files/4172645/1.txt)
[2.txt](https://github.com/miranda-ng/miranda-ng/files/4172646/2.txt)

**Comment by dartraiden** [comment]
Такое ощущение, что эта зараза опять всплыла. Мне ICQ Official шлёт одну и ту же картинку.

**Comment by dartraiden** [comment]
Есть ощущение, что это NewStory гадил...
Мне вместо большого сообщения с перечислением фич новой аськи (и картинки) прилетала лишь картинка. Историей стоял NewStory, журналом привата стоял встроенный журнал табсов.

Вернул журналом H++, очистил историю беседы с ICQ Official и вгрузил всю историю с сервера. Вроде попустило.

**Comment by dartraiden** [comment]
[netlog - Copy.txt](https://github.com/miranda-ng/miranda-ng/files/4443685/netlog.-.Copy.txt)

**Comment by georgehazan** [comment]
посмотри, plz, это должно было пофикситься в конце мая
оно возникало, когда в истории файл был последним событием, и ссылка на него отдавалась в  "tail":{"messages": для соотв контакта. Сейчас содержимое tail не должно грузиться вообще, если в базе LastMsgId больше или равен тому, что прилетело с сервера

**Comment by dartraiden** [comment]
С одной стороны стало лучше: файл больше не прилетает бесконечно непрочитанным.

С другой стороны стало хуже:
- прилетает файл
- у меня отключено автопринятие, я не принимаю его руками, не смотрю вообще чего там моргает, выключаю миранду
- запускаю миранду - всё, файл проёбан, его уже нет
