### ISSUE TITLE
StdPopup bug 

### ISSUE THREAD

**Issue by MrMyth** [miranda-ng/miranda-ng#2204]
У StdPopup есть небольшой баг, смотрите приложенное изображение. В окне выбора, когда отключить уведомления два варианта не имею названия.
-------------------------------------------------------------------------------------------------------------
StdPopup has a small bug, see the attached image. In the selection window, when to turn off notifications, two options do not have a name.

![Безымянный](https://user-images.githubusercontent.com/20878728/74019197-4c338680-49a8-11ea-891d-67d90ce3c12e.jpg)

**Comment by georgehazan** [comment]
известное дело, это те статусы, которые мы выпилили
