### ISSUE TITLE
Twitter: автоматически отключать уведомления о смене статусного сообщения, если включена настройка "Твиты как сообщения"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2206]
после https://github.com/miranda-ng/miranda-ng/commit/cf4bff42f8a3dbf18623d8df599849399a6165a7 приходит уведомление о сообщении, а потом о новом статусном сообщении, что излишне.

**Comment by georgehazan** [comment]
уведомлениями о смене стамески ведает вовсе не Твиттер, а NEN
