### ISSUE TITLE
A correct support of OMEMO: 12 byte for initilization vector (IV)

### ISSUE THREAD

**Issue by Neustradamus** [miranda-ng/miranda-ng#2217]
There is a problem in the code:
- https://github.com/xsf/xeps/pull/894

**Comment by dartraiden** [comment]
@sss123next

**Comment by sss123next** [comment]
https://xmpp.org/extensions/xep-0384.html today omemo xep have a lot of changes compared to previous one, this is not so trivial changes.

**Comment by sss123next** [comment]
i hope i will have some time during this week to investigate further and implement necessary changes.

**Comment by Neustradamus** [comment]
@sss123next: In first, it is important to have compatibility with OMEMO 0.3.0 with 12 byte for initilization vector (IV).

**Comment by sss123next** [comment]
it's should be compatible now, currently 12bytes iv is used, with 16 bytes key and 16 bytes ad

**Comment by sss123next** [comment]
you can see for yourself, function called somethinencrypt, inside jabber_omemo.cpp

**Comment by Neustradamus** [comment]
@sss123next, can you confirm me, now Miranda NG:
- can received: 12 byte IV OMEMO messages?
- can received: 16 byte IV messages?
- sends only 12 byte IV messages?

**Comment by sss123next** [comment]
https://github.com/miranda-ng/miranda-ng/blob/master/protocols/JabberG/src/jabber_omemo.cpp#L2103

```
unsigned char key[16], iv[12], tag[16]
```

**Comment by sss123next** [comment]
same logic for decryption
https://github.com/miranda-ng/miranda-ng/blob/master/protocols/JabberG/src/jabber_omemo.cpp#L1645

```
unsigned char key[16], *tag;
		{
			size_t buf_len = signal_buffer_len(decrypted_key);
			unsigned char *tmp = (unsigned char*)mir_alloc(buf_len);
			memcpy(tmp, signal_buffer_data(decrypted_key), buf_len);
			memcpy(key, tmp, 16);
			unsigned char *ptr = tmp + 16;
			tag_len = (int)buf_len - 16;
			tag = (unsigned char*)mir_alloc(tag_len);
			memcpy(tag, ptr, tag_len);
			mir_free(tmp);
			signal_buffer_free(decrypted_key);
		}

		EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
		EVP_DecryptInit_ex(ctx, EVP_aes_128_gcm(), NULL, NULL, NULL);
		if (!EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_IVLEN, (int)iv_len, NULL)) {
			debugLogA("Jabber OMEMO: error: EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_IVLEN, (int)iv_len, NULL) failed");
			mir_free(tag);
			return true;
		}
		if (!EVP_DecryptInit_ex(ctx, NULL, NULL, key, iv)) {
			debugLogA("Jabber OMEMO: error: EVP_DecryptInit_ex(ctx, NULL, NULL, key, iv) failed");
			mir_free(tag);
			return true;
		}
		if (!EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_TAG, tag_len, tag)) {
			debugLogA("Jabber OMEMO: error: EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_TAG, tag_len, tag) failed");
			mir_free(tag);
			return true;
		}
		if (!EVP_DecryptUpdate(ctx, (unsigned char*)out, &outl, payload, int(payload_len))) {
			debugLogA("Jabber OMEMO: error: EVP_DecryptUpdate(ctx, (unsigned char*)out, &outl, payload, int(payload_len)) failed");
			mir_free(tag);
			return true;
		}
```

**Comment by sss123next** [comment]
> same logic for decryption
> https://github.com/miranda-ng/miranda-ng/blob/master/protocols/JabberG/src/jabber_omemo.cpp#L1645
> 
> ```
> unsigned char key[16], *tag;
> 		{
> 			size_t buf_len = signal_buffer_len(decrypted_key);
> 			unsigned char *tmp = (unsigned char*)mir_alloc(buf_len);
> 			memcpy(tmp, signal_buffer_data(decrypted_key), buf_len);
> 			memcpy(key, tmp, 16);
> 			unsigned char *ptr = tmp + 16;
> 			tag_len = (int)buf_len - 16;
> 			tag = (unsigned char*)mir_alloc(tag_len);
> 			memcpy(tag, ptr, tag_len);
> 			mir_free(tmp);
> 			signal_buffer_free(decrypted_key);
> 		}
> 
> 		EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
> 		EVP_DecryptInit_ex(ctx, EVP_aes_128_gcm(), NULL, NULL, NULL);
> 		if (!EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_IVLEN, (int)iv_len, NULL)) {
> 			debugLogA("Jabber OMEMO: error: EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_IVLEN, (int)iv_len, NULL) failed");
> 			mir_free(tag);
> 			return true;
> 		}
> 		if (!EVP_DecryptInit_ex(ctx, NULL, NULL, key, iv)) {
> 			debugLogA("Jabber OMEMO: error: EVP_DecryptInit_ex(ctx, NULL, NULL, key, iv) failed");
> 			mir_free(tag);
> 			return true;
> 		}
> 		if (!EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_TAG, tag_len, tag)) {
> 			debugLogA("Jabber OMEMO: error: EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_TAG, tag_len, tag) failed");
> 			mir_free(tag);
> 			return true;
> 		}
> 		if (!EVP_DecryptUpdate(ctx, (unsigned char*)out, &outl, payload, int(payload_len))) {
> 			debugLogA("Jabber OMEMO: error: EVP_DecryptUpdate(ctx, (unsigned char*)out, &outl, payload, int(payload_len)) failed");
> 			mir_free(tag);
> 			return true;
> 		}
> ```

for decryption any iv and tag lenngth should work (if this is supported by cipher)

**Comment by sss123next** [comment]
unfortunately i am currently overloaded with work, so most probably i will not have time to implement required changes during this week.

**Comment by Neustradamus** [comment]
@georgehazan, @sss123next: Any news?
Dino 0.2.0 has now "good" OMEMO.

**Comment by Neustradamus** [comment]
@sss123next: Miranda NG must to send with 12 by default.
It is possible to received with 12 but if you want 16 to keep compatibility with old...

**Comment by sss123next** [comment]
first we should clear this, miranda using this settings `unsigned char key[16], iv[12], tag[16]` from the beginning, as you can see in git history.

https://github.com/dino/dino/blob/master/plugins/omemo/src/jingle/jet_omemo.vala - looks same as ours for me, if problem exists, problem not in key/iv/tag size.
