### ISSUE TITLE
Twitter: add support for private messages

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2218]
This is not tweets and plugin does not support them.

https://forum.miranda-ng.org/index.php?topic=5985

**Comment by dartraiden** [comment]
https://help.twitter.com/ru/using-twitter/direct-messages

**Comment by georgehazan** [comment]
curl --request POST 
--url https://api.twitter.com/1.1/direct_messages/events/new.json 
--header 'authorization: OAuth oauth_consumer_key="YOUR_CONSUMER_KEY", oauth_nonce="AUTO_GENERATED_NONCE", oauth_signature="AUTO_GENERATED_SIGNATURE", oauth_signature_method="HMAC-SHA1", oauth_timestamp="AUTO_GENERATED_TIMESTAMP", oauth_token="USERS_ACCESS_TOKEN", oauth_version="1.0"' 
--header 'content-type: application/json' 
--data '{"event": {"type": "message_create", "message_create": {"target": {"recipient_id": "RECIPIENT_USER_ID"}, "message_data": {"text": "Hello World!"}}}}'
