### ISSUE TITLE
Отображение своего имени в учётных записях ok.ru

### ISSUE THREAD

**Issue by jinn81** [miranda-ng/miranda-ng#2220]
При общении в учётной записи Одноклассники в беседах вместо своего имени отображается id  пользователя.

Есть мысль проанализировать xml-поток xmpp-сервера Одноклассников для того, чтобы вставить имя своей учётной записи в беседы. В дальнейшем либо написать отдельный плагин для подключения Одноклассников, либо дописать соответствующий условный оператор для xmpp.odnoklassniki.ru

Пока не очень ясно, каким образом можно перехватить xml-поток для анализа передаваемых полей. Если кто-нибудь подскажет, как это сделать, идею реализую.

**Comment by dartraiden** [comment]
Можно через редактор базы зайти в секцию протокола /Настройки/протокол_порядковыйномер и создать там настройку MyHandle (тип Unicode), значение которой будет ником, отображаемым в истории. Это поддерживает TabSRMM.

**Comment by jinn81** [comment]
Спасибо! Поторопился с идеей, извините.

**Comment by georgehazan** [comment]
> При общении в учётной записи Одноклассники в беседах вместо своего имени отображается id пользователя.

где отображается?..

**Comment by dartraiden** [comment]
В журнале, подозреваю.

**Comment by jinn81** [comment]
> 
> 
> > При общении в учётной записи Одноклассники в беседах вместо своего имени отображается id пользователя.
> 
> где отображается?..

В беседе и истории.
![2020-02-17_22-03-30](https://user-images.githubusercontent.com/42745118/74680652-550b3000-51d2-11ea-855a-323965f891f0.png)

**Comment by jinn81** [comment]
> 
> 
> В качестве костыля можно через редактор базы зайти в секцию протокола /Настройки/протокол_порядковыйномер и создать там настройку MyHandle (тип Unicode), значение которой будет ником, отображаемым в истории. Это поддерживает TabSRMM.

Идея в том, чтобы заполнять ключ MyHandle значением соответствующего параметра из передаваемого XML в джаббер-сессии.

**Comment by dartraiden** [comment]
Может, через MirLUA это как-то делать. Но там, вероятно, нет средств для работы с входящим XML...

**Comment by jinn81** [comment]
А если сторонними методами разобрать? Нужно только понять структуру передаваемой Одноклассниками джаббер-сессии.

**Comment by jinn81** [comment]
Поясню немного, что имею в виду. Возможно, заблуждаюсь, поправьте. Я исхожу из того, что кроме стандартного presence from может передаваться некий presence okid, который возможно направить в беседу и журнал. Плагин же передаёт аналогичный presence okid собеседника. Мы его видим и в беседе и в журнале вместо message to.

**Comment by georgehazan** [comment]
не, просто ОК не отдает собственный вкард (личную карточку), он тупой, соотв Миранда не заполняет поле Jabber_1/Nick - единственный выход - заполнить его руками

**Comment by jinn81** [comment]
> 
> 
> не, просто ОК не отдает собственный вкард (личную карточку), он тупой, соотв Миранда не заполняет поле Jabber_1/Nick - единственный выход - заполнить его руками

Отдаёт-таки.
![2020-08-19_17-02-38](https://user-images.githubusercontent.com/42745118/90645694-f127f980-e23e-11ea-9f33-8430ca81385a.png)
На скрине видно, что MyHandle удалён, а xml загружает "свой" ник в каждом диалоге отдельно.

**Comment by georgehazan** [comment]
@jinn81 тысяча извинений, но какое отношение закладки на групчаты имеют отношение к всасыванию собственного вкард?

**Comment by jinn81** [comment]
@georgehazan чего не знаю, того не знаю. Просто увидел, что в xml-консоли, которая грузит инфу с сервера одноклассников, всё-таки присутствует моё имя, в смысле, ник. Если что-то не так понял, извините. Возможно, это какое-то нестандартное для чистого джаббера поле и оно не поддаётся обработке общепринятыми для джаббера методами. Но оно так или иначе присутствует в xml-потоке. Следовательно, его можно обрабатывать без костылей. Вот о чём речь. Ещё раз извините!

**Comment by dartraiden** [comment]
Jabber берёт ник из vCard, а это ник, с которым зашли в комнату.

**Comment by jinn81** [comment]
> 
> 
> Jabber берёт ник из vCard, а это ник, с которым зашли в комнату, с помощью закладки.

Согласен.

>
>
> Брать его оттуда - костыль.

Костыль, если делать его для всего джаббер-протокола. Индивидуально для ОКов это норма. Буду думать дальше. Жаль, опыта в программировании десктоп-приложений нет. Но крутить продолжу.

**Comment by jinn81** [comment]
> 
> 
> Jabber стандартно берёт ник из vCard, а это ник, с которым зашли в комнату с помощью закладки. Брать его оттуда - и есть костыль, потому что такое поведение (брать ник оттуда) не соответствует стандартам.
> 
> Лучше уж вписать руками MyHandle, чем костыль лепить.

MyHandle для ОКов и получается костыль.
