### ISSUE TITLE
Jabber: cannot invite user to conference

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2221]
Отправляю инвайт человек (в ростере или не в ростере - не важно), он его принимает и... всё, больше ничего не происходит. Кроме того, дальнейшие инвайты на "том конце" уже даже не показываются.

**Comment by dartraiden** [comment]
Теперь входящий инвайт вообще никак не виден (ну и принять его невозможно, его ж не видно). С включённым автопринятием тоже никакого эффекта.

**Comment by georgehazan** [comment]
@dartraiden а их на jabber.ru и нет - там теперь логика такая, что единожды приняв инвайт, ты будешь приниматься дальше автоматически. Поэтому я и просил тебя потестить инвайты, пока у тебя они показываются, ибо у меня давно на наших комнатах никаких инвайтов нет, а сервак тупо с ходу заряжает тебя в комнату
