### ISSUE TITLE
DNS Error: 3325978 DNS type 'mx' lookup of miranda.im responded with code SERVFAIL

### ISSUE THREAD

**Issue by erthink** [miranda-ng/miranda-ng#2229]
Проблема не с мирандой, а с доставкой почты для домена miranda.im.

**Comment by erthink** [comment]
Проблема не с мирандой, а с доставкой почты для домена miranda.im.

**Comment by dartraiden** [comment]
miranda.im, правда, принадлежит не нам, там почта у @georgehazan по историческим причинам

**Comment by erthink** [comment]
Вот к нему почта и не доходит уже сутки.
Моё последнее сообщение для него по теме запуска libmdbx под Wine:
>
>В логе много лишнего, т.е. запуск нескольких процессов...
>
>Тем не менее, видно что mdbx_chk шатно сообщает:
>002c:Call ucrtbase.__stdio_common_vfprintf(00000004,7f7fa3dd2800,140007158 "mdbx_env_open failed, error %d %s\n",00000000,0022fa18) ret=140005a28
> ! mdbx_env_open failed, error 120 Call not implemented.
>
>Причина снова в Wine, есть такая хрень:
>002c:Call KERNEL32.SetFileInformationByHandle(00000060,00000006,0022f890,00000008) ret=127dd1b2
>002c:fixme:file:SetFileInformationByHandle 0000000000000060, 6,
000000000022F890, 8
>002c:Ret  KERNEL32.SetFileInformationByHandle() retval=00000000 ret=127dd1b2
>
>Добавил еще один маленький костыль в ветку devel.

**Comment by dartraiden** [comment]
В качестве резервной можно использовать george.hazan собака гмыло

**Comment by dartraiden** [comment]
Думаю, тикет имеет смысл оставить и рассмотреть поднятие почты на miranda-ng.org

**Comment by apollo2k4** [comment]
> Думаю, тикет имеет смысл оставить и рассмотреть поднятие почты на miranda-ng.org, почта на домене, контролируемом бог знает кем, это ненадёжно...

![изображение](https://user-images.githubusercontent.com/133890/75114402-8e69f280-564d-11ea-81b8-9a09a68b6b95.png)
Там есть mail exchanger

**Comment by georgehazan** [comment]
сервак свалился, починили
