### ISSUE TITLE
Vietnamese Translation

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#223]
**Reported by ppanhh on 19 Jul 2013 19:34 UTC**
I would like to translate the product in to Vietnamese Localization but I dont know how to do that.
My email is: ppanhh@gmail.com
Please give me instructions.

**Comment by georgehazan** [comment]
**Comment by wishmaster on 19 Jul 2013 19:43 UTC**
What is your full email address?

Can you come to our jabber channel on xmpp://miranda-ng@conference.jabber.ru?join and discuss it there?

**Comment by georgehazan** [comment]
**Comment by robyer on 19 Oct 2013 14:20 UTC**
ppanhh: Look at http://wiki.miranda-ng.org/index.php?title=Langpacks/en#Creating_a_new_langpack

**Comment by georgehazan** [comment]
**Modified by mataes on 28 May 2014 04:31 UTC**

**Comment by dartraiden** [comment]
No reaction after 3 years, so we can close this bug.
