### ISSUE TITLE
AutoBackups Добавить возможность отключения всплывающих окон при выполнении бекапа

### ISSUE THREAD

**Issue by scutoff** [miranda-ng/miranda-ng#2231]
Добавить возможность отключения всплывающих окон плагина AutoBackups, т.к. очень раздражает, если бекап делать часто.

**Comment by georgehazan** [comment]
Главное меню - Всплывающие окна - убрать autobackups

**Comment by scutoff** [comment]
У нас просто отключен этот пункт меню был, поэтому не нашли)
спасибо
