### ISSUE TITLE
sqlite : options window and tabsrrm 

### ISSUE THREAD

**Issue by alexeik** [miranda-ng/miranda-ng#2237]
![image](https://user-images.githubusercontent.com/318732/75621958-05ead500-5bac-11ea-99a9-1cd24e8376b9.png)

**Comment by georgehazan** [comment]
Sqlite на текущий момент очень сырой, медленный и категорически не рекомендуется к использованию.  Баги в нем исправляться не будут до полного завершения работ по версии 0.95 (до августа, ориентировочно)

**Comment by alexeik** [comment]
А.тоткто поддерживает sqlite ну русском говорит?
Про sqlite я понимаю обстановку - ок.

**Comment by apollo2k4** [comment]
> А тот кто поддерживает sqlite ну русском говорит?
Да, но он сейчас занять в реале.

**Comment by dartraiden** [comment]
Всё меняется, нужно лишь переоткрыть окно табсов.

**Comment by dartraiden** [comment]
@georgehazan 
имеет смысл принудительно закрывать окно табсов при смене журнала?
