### ISSUE TITLE
mdbx_load не импортирует данные

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2239]
```
mdbx_dump.exe -n -a -f "%TEMP%\corrupted.tmp" "path\to\corrupted.dat"
mdbx_load.exe -n -f "%TEMP%\corrupted.tmp" "path\to\repaired.dat"
```

Проделав это на рабочем профиле получаем девственно чистый профиль без настроек, контактов, учёток и истории.

**Comment by erthink** [comment]
В миранде используются кастомные компараторы. Поэтому для загрузки данных `mdbx_load` следует запускать с опцией `-a` (append records in input order). Иначе данные будут пересортированы. В результате перестанет работать доступ к данным по ключам изнутри миранды, что видимо и наблюдается.

**Comment by erthink** [comment]
Предлагаю две вещи:
1. Сделать минимальную инструкцию оп использованию утилит `mdbx_chk`, `mdbx_dump`, `mdbx_load` с указанием нужных опций (-n, -i, -r, -a и т.п.).
2. В багах с тегом `dbx_mdbx` упоминать меня.

**Comment by georgehazan** [comment]
@erthink там батник есть, который всё это дергает на автомате. И проще меня дернуть, чем отвлекать тебя на странные вопросы не по теме, если что, я тебе напишу :-)

**Comment by dartraiden** [comment]
> Сделать минимальную инструкцию оп использованию утилит mdbx_chk, mdbx_dump, mdbx_load с указанием нужных опций (-n, -i, -r, -a и т.п.).

Она есть в вики, оттуда я команды и брал собственно. Только там про -a ничего не было.

**Comment by erthink** [comment]
https://t.me/libmdbx
