### ISSUE TITLE
plugin downloader

### ISSUE THREAD

**Issue by alexeik** [miranda-ng/miranda-ng#2241]
![image](https://user-images.githubusercontent.com/318732/75656559-43676500-5c75-11ea-99b0-e432d1825243.png)
afiter using filter and checking item, goes @Download@ click and UI are in not consistent state.
UI marks that i marked as skipped ... and so on

**Comment by georgehazan** [comment]
@alexeik объясни plz как повторить это. можно по-русски

**Comment by alexeik** [comment]
я использую фильтр, ввел "edi"
пометил потом галкой dbeditor
потом нажал Download и все изменилось, так как сейчас на скрине.
