### ISSUE TITLE
The change is required in icq new protocol deleted users renaming

### ISSUE THREAD

**Issue by lokapal** [miranda-ng/miranda-ng#2242]
It would be VERY helpful to save existing contact name in the local database if the contact is deleted by simply adding any additional sign/word to this contact as a warning that it is deleted by the server and should be moved to Dummy protocol to save all logs.
The logic should be very simple:
1. Miranda has contact name in the database (it's purely irrelevant is it custom or it is default name from the server).
2. If we obtain some mark/name/etc from the server that says that this contact is deleted, we simply ADD to the existing in the local database name something like [deleted] or .deleted or anything like it.

The need in this change is quite obvious. Let us imagine that we have a big miranda database with many years history. When we're importing the database from the old miranda/old protocol to the new one we will obtain a lot of almost anonymous users with the same name [deleted] who should be renamed/restored manually by searching in their histories - and it is not simple, if the last conversation with somebody took place 5-7 years ago!

**Comment by georgehazan** [comment]
@lokapal renaming to 'deleted' is strictly prohibited in ICQ-WIM protocol, this fact is specially checked. Perhaps you need to tune Optiions - Contact list - Contact names to visualize the correct string (LastName + FirstName, for example)

**Comment by lokapal** [comment]
I live at the stable builds only, and don't update builds automatically (only manually). Right now I have the following situation
![delcontacts](https://user-images.githubusercontent.com/6469161/75781353-1185f980-5d6e-11ea-92f1-87b43aab8717.png)
And the same situation in the other groups

**Comment by georgehazan** [comment]
yes, their nick is [deleted], but these contacts shall have also FirstName & LastName
if you set the higher priority of these fields, you will see their names again
