### ISSUE TITLE
TabSRMM cannot open \\server\share links

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2246]
Internal log just copy link to input field.
H++ ignores link

**Comment by tweimer** [comment]
@georgehazan @dartraiden Does it mean that those UNC links are displayed in the message log like regular HTTP links? Or what is "H++ ignores link" supposed to mean?

**Comment by dartraiden** [comment]
Click on the link did nothing

**Comment by tweimer** [comment]
Now it will open an UNC link when you click it? I'm not sure that is a good idea.

**Comment by dartraiden** [comment]
Yes, now Miranda should open this links (in Explorer I guess). Why is it bad?

**Comment by dartraiden** [comment]
There was a request from the user about this, so someone needs this

**Comment by tweimer** [comment]
Because opening it in the Explorer causes it to send your wondows login credentials (username and password) to the server that hosts that link. It could be abused for phishing links.

I have opened #2325 for more details.

**Comment by dartraiden** [comment]
Btw, you can easily test UNC support
try to open  \\dartraiden\c$ (replace dartraiden with your pc name)
