### ISSUE TITLE
Corrupted xStatus text for Steam

### ISSUE THREAD

**Issue by RozekPoland** [miranda-ng/miranda-ng#2251]
### Expected behavior
Displaying xStatus text for Steam properly.

### Actual behavior
![image](https://user-images.githubusercontent.com/37516069/76091587-235ddb80-5fbe-11ea-8cdb-f2f326ad74e8.png)
![image](https://user-images.githubusercontent.com/37516069/76093238-ee9f5380-5fc0-11ea-88f0-11cf743d6d18.png)

xStatus text is corrupted at displaying name of a server any Steam contact is playing on. There are (probably) Korean letters instead of name of a server. It refers to any game any Steam contact is playing.

### Does it work in stable version?
It occurs in both Stable and in the latest development version.

### Steps to reproduce that behavior
Plugins:
* Steam
* NewXstatusNotify
* Tipper (not obligatory)

**Comment by dartraiden** [comment]
Unfortunately, to add someone to your friends you need to have a “full” Steam account (spend at least $ 5 in Steam)

**Comment by dartraiden** [comment]
You can try adding @georgehazan  as a Steam friend so he can see these statuses

**Comment by georgehazan** [comment]
yup, add me, please. my nick in Steam is ghazan1
