### ISSUE TITLE
Facebook MQTT not receiving any messages

### ISSUE THREAD

**Issue by peci1** [miranda-ng/miranda-ng#2260]
### Expected behavior
When somebody sends me a message, Miranda shows it and logs it to history.

### Actual behavior
Nothing pops up, history is unchaged.

### Does it work in stable version?
Not relevant?

### Steps to reproduce that behavior
 * Setup a facebook connection via the new MQTT plugin.
 * connnect
 * Wait until somebody sends you a message.
 * Nothing happens.

I have a netlog capture of a typical problematic session. Is there a non-public way to share it?

[spoiler=VersionInfo][quote]CPU: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz [Intel64 Family 6 Model 60 Stepping 3] [DEP Enabled] [8 CPUs]
Installed RAM: 16074 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 18363)
Internet Explorer: 9.11.18362.0 (build 918362)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : Czech/Czech | Czech/Czech
Free disk space on Miranda partition: 14368 MBytes

Miranda NG Version: 0.95.12 alpha build #22647 (d3b2787774) x64
Build time: 13 Mar 2020 12:42:10
Profile: D:\miranda 0.5\Profiles\Peci\Peci.dat
Profile size: 28311552 Bytes
Profile creation date: 1 Aug 2014 17:01:10
Language pack: No language pack installed
Service Mode: No

[b]Active Plugins (35):[/b]
¤ AVS.dll v.[b]0.98.1.2[/b] [2 Mar 2020 2:03:08] - Avatar service 
¤ Clist_modern.dll v.[b]0.9.1.10[/b] [2 Mar 2020 2:03:36] - Modern contact list 
¤ Contacts.dll v.[b]1.6.0.0[/b] [3 Feb 2020 19:08:58] - Send/receive contacts 
¤ CrashDumper.dll v.[b]0.1.0.4[/b] [3 Feb 2020 19:09:26] - Crash dumper 
¤ Db_autobackups.dll v.[b]0.1.0.4[/b] [13 Mar 2020 12:42:22] - Db autobackuper 
¤ DbEditorPP.dll v.[b]4.0.1.3[/b] [3 Feb 2020 19:09:28] - Database editor++ 
¤ Dbx_mdbx.dll v.[b]0.95.9.1[/b] [13 Mar 2020 12:43:52] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.[b]0.95.8.1[/b] [3 Feb 2020 19:08:56] - Miranda NG mmap database driver 
¤ Dbx_sqlite.dll v.[b]0.95.10.2[/b] [3 Feb 2020 19:10:10] - Miranda NG SQLite database driver 
¤ Dummy.dll v.[b]0.2.0.0[/b] [13 Mar 2020 12:43:12] - Dummy protocol 
¤ Facebook.dll v.[b]0.1.0.4[/b] [12 Mar 2020 18:27:30] - Facebook 
¤ FTPFile.dll v.[b]0.6.0.5[/b] [3 Feb 2020 19:10:34] - FTP File YM 
¤ GG.dll v.[b]0.95.11.1[/b] [2 Mar 2020 2:03:40] - Gadu-Gadu protocol 
¤ historypp.dll v.[b]1.5.1.5[/b] [12 Mar 2020 18:28:02] - History++ 
¤ HTTPServer.dll v.[b]0.1.2.3[/b] [3 Feb 2020 19:09:40] - HTTPServer 
¤ ICQ.dll v.[b]0.95.11.8[/b] [2 Mar 2020 2:04:26] - ICQ-WIM protocol 
¤ IEView.dll v.[b]1.6.0.2[/b] [12 Mar 2020 18:26:16] - IEView 
¤ Import.dll v.[b]0.95.11.1[/b] [13 Mar 2020 12:42:42] - Import contacts and messages 
¤ IRC.dll v.[b]0.95.10.1[/b] [2 Mar 2020 2:03:12] - IRC protocol 
¤ Jabber.dll v.[b]0.95.11.1[/b] [13 Mar 2020 12:42:54] - Jabber protocol 
¤ KeyboardNotify.dll v.[b]1.6.0.1[/b] [3 Feb 2020 19:09:14] - Keyboard notify ext. 
¤ MenuEx.dll v.[b]1.3.2.0[/b] [3 Feb 2020 19:09:04] - Menu item ext 
¤ mTextControl.dll v.[b]0.8.0.1[/b] [3 Feb 2020 19:09:10] - Miranda text control 
¤ PluginUpdater.dll v.[b]0.2.0.6[/b] [12 Mar 2020 18:26:44] - Plugin updater 
¤ PopupPlus.dll v.[b]2.1.1.15[/b] [3 Feb 2020 19:09:10] - Popup plus 
¤ QuickSearch.dll v.[b]1.4.2.0[/b] [3 Feb 2020 19:10:40] - Quick Search 
¤ SeenPlugin.dll v.[b]5.0.5.5[/b] [3 Feb 2020 19:09:10] - Last seen 
¤ SkypeWeb.dll v.[b]0.12.3.5[/b] [2 Mar 2020 2:04:18] - Skype protocol (Web) 
¤ SmileyAdd.dll v.[b]0.3.1.2[/b] [3 Feb 2020 19:09:16] - SmileyAdd 
¤ StatusChange.dll v.[b]1.3.0.0[/b] [3 Feb 2020 19:09:40] - Status change 
¤ StatusManager.dll v.[b]1.2.0.6[/b] [3 Feb 2020 19:10:06] - Status manager 
¤ StopSpam.dll v.[b]0.1.0.2[/b] [3 Feb 2020 19:09:12] - StopSpam+ 
¤ TabSRMM.dll v.[b]3.6.1.2[/b] [12 Mar 2020 18:26:16] - TabSRMM 
¤ Tipper.dll v.[b]2.1.0.7[/b] [3 Feb 2020 19:09:12] - Tipper 
¤ UInfoEx.dll v.[b]0.9.0.1[/b] [3 Feb 2020 19:09:18] - User info ext 

[b]Unloadable Plugins (10):[/b]
¤ HotkeysPlus.dll v.[b]0.0.0.0[/b] [25 Oct 2009 8:53:58] - <unknown> 

¤ loadavatars.dll v.[b]0.0.0.0[/b] [25 Oct 2009 8:54:10] - <unknown> 

¤ mBirthday.dll v.[b]0.0.0.0[/b] [25 Oct 2009 8:54:12] - <unknown> 

¤ mtextcontrolA.dll v.[b]0.0.0.0[/b] [25 Oct 2009 8:54:14] - <unknown> 

¤ mToolTip.dll v.[b]0.0.0.0[/b] [25 Oct 2009 8:54:18] - <unknown> 

¤ PersonalizedSoundPlugin.dll v.[b]0.0.0.0[/b] [25 Oct 2009 8:54:20] - <unknown> 

¤ PhoneCostsCZE.dll v.[b]0.0.0.0[/b] [25 Oct 2009 8:54:46] - <unknown> 

¤ SOMWO.dll v.[b]0.0.0.0[/b] [25 Oct 2009 8:54:46] - <unknown> 

¤ updater.dll v.[b]0.0.0.0[/b] [25 Oct 2009 8:54:54] - <unknown> 

¤ xstatus_icons.dll v.[b]0.0.0.0[/b] [25 Oct 2009 8:54:56] - <unknown> 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
Facebook                 1 - Enabled 1 - Disabled  Loaded
ICQ                      1 - Enabled 0 - Disabled  Loaded
IRC                      2 - Enabled 1 - Disabled  Loaded
JABBER                   3 - Enabled 0 - Disabled  Loaded
SKYPE                    1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 clist_modern_icons.dll [15 Nov 2006 11:14:40]
 HistoryPP_icons.dll [12 Mar 2020 18:27:54]
 Proto_AIM.dll [21 Dec 2017 4:15:02]
 proto_conn_facebook.dll [5 Mar 2011 20:37:52]
 Proto_Dummy.dll [13 Mar 2020 12:44:00]
 Proto_Facebook.dll [12 Mar 2020 18:27:54]
 Proto_GG.dll [2 Mar 2020 2:04:48]
 Proto_ICQ.dll [2 Mar 2020 2:04:50]
 Proto_IRC.dll [2 Mar 2020 2:04:48]
 Proto_Jabber.dll [13 Mar 2020 12:44:00]
 Proto_MetaContacts.dll [13 Mar 2020 12:44:00]
 Proto_MRA.dll [2 Mar 2020 2:04:50]
 Proto_MSN.dll [2 Mar 2020 2:04:48]
 proto_PhoneCostsCZE.dll [25 Oct 2009 8:53:32]
 Proto_Skype.dll [2 Mar 2020 2:04:50]
 Proto_Yahoo.dll [23 Sep 2016 3:07:04]
 TabSRMM_icons.dll [12 Mar 2020 18:27:54]
 Toolbar_icons.dll [2 Mar 2020 2:04:48]
 UInfoEx_icons.dll [3 Feb 2020 19:10:36]
 w9x_icq.dll [25 Oct 2009 8:53:32]
 w9x_main.dll [25 Oct 2009 8:53:32]
 xstatus_icons.dll [25 Oct 2009 8:53:34]
 xStatus_Jabber.dll [13 Mar 2020 12:44:00]
[/quote][/spoiler]

**Comment by dartraiden** [comment]
> I have a netlog capture of a typical problematic session. Is there a non-public way to share it?

Send it to ghazan @ miranda.im and mention that the netlog is associated with this ticket

**Comment by peci1** [comment]
Thanks, netlog sent. This has been happening to me for a month or two. For some time, the new MQTT FB protocol worked for me, but then out of sudden it stopped.

**Comment by georgehazan** [comment]
yes, same error - ERROR_QUEUE_OVERFLOW, it happens when an inbox contains too many unread events. I'll try to dig this problem

**Comment by peci1** [comment]
What does "inbox" mean here? Messenger doesn't show me any unread messages...

**Comment by georgehazan** [comment]
@peci1 what do you see as Inbox at www.facebook.com

**Comment by peci1** [comment]
That one doesn't have any unread stuff.

**Comment by georgehazan** [comment]
hmm... according to the bitlbee changelog
> bitlbee-facebook-1.2.0 (2019-01-24):
  - Fix ERROR_QUEUE_OVERFLOW on login by bumping orca agent version

we need to do that again

**Comment by georgehazan** [comment]
@peci1 could you try the fix and reopen this bug if it didn't help

**Comment by peci1** [comment]
Hi, the fix did not help. I'm using the version I downloaded yesterday, so it should already contain the fix, yet still it doesn't show any messages.

Here's a part of the netlog:

```
[20:21:11 565C] [Facebook_1] UNZIP: <{"type":"inbox","seen_timestamp":0,"recent_unread":0,"unread":0,"unseen":0,"num_endpoints":2}>
[20:21:29 5798] [Facebook_1] (000000000A3BA000:2292) Data sent
00000000: C2 00                                            Â.
[20:21:29 565C] [Facebook_1] Received message of type=13, flags=0, body length=0
[20:21:29 565C] [Facebook_1] Received message of type=3, flags=0, body length=95
[20:21:29 565C] [Facebook_1] (000000000A3BA000:2292) Data received
[20:21:29 565C] [Facebook_1] UNZIP: <{"type":"inbox","seen_timestamp":0,"recent_unread":1,"unread":1,"unseen":1,"num_endpoints":2}>
[20:21:42 565C] [Facebook_1] Received message of type=3, flags=0, body length=53
[20:21:42 565C] [Facebook_1] (000000000A3BA000:2292) Data received
[20:21:42 565C] [Facebook_1] UNZIP: <>
[20:21:42 565C] [Facebook_1] Received list of presences: 1 records
[20:21:42 565C] [Facebook_1] Presence from user 100002993907238 => 2
[20:21:44 565C] [Facebook_1] Received message of type=3, flags=0, body length=95
[20:21:44 565C] [Facebook_1] (000000000A3BA000:2292) Data received
[20:21:44 565C] [Facebook_1] UNZIP: <{"type":"inbox","seen_timestamp":0,"recent_unread":0,"unread":0,"unseen":0,"num_endpoints":2}>
[20:21:44 565C] [Facebook_1] Received message of type=3, flags=0, body length=106
[20:21:44 565C] [Facebook_1] (000000000A3BA000:2292) Data received
[20:21:44 565C] [Facebook_1] UNZIP: <{"type":"inbox","seen_timestamp":1584732088982,"recent_unread":0,"unread":0,"unseen":0,"num_endpoints":2}>
```
If I understand it correctly, it saw there are some messages, but didn't show them to me.

**Comment by georgehazan** [comment]
@peci1 I've got some interesting info from one user that the same account works in one Miranda and doesn't work in another with the same error. Can you try to open Settings / Facebook_1 in dbeditor++ and remove all temporary data (token, stoken etc) from the database? Will it help?

**Comment by peci1** [comment]
Thanks. This seems to help. I was able to send and receive single-user chat messages. Group chat not tested yet. I'll reopen this if I face any problems.

**Comment by georgehazan** [comment]
@peci1 okay, another attempt to fix that problem automatically
dev build is available
