### ISSUE TITLE
New_GPG: вынести пункты плагина в подменю

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2266]
Иначе эти красавцы сильно раздувают ширину меню

![ClEuMZy](https://user-images.githubusercontent.com/5046855/76970813-7714e100-693d-11ea-945c-4a3f95868c94.png)

**Comment by georgehazan** [comment]
прямо вот очень? 🙄 тащемта на одну строку

**Comment by dartraiden** [comment]
Без них меню было бы шириной с "Выключить метаконтакты", что компактнее аж на треть.
