### ISSUE TITLE
XSoundNotify not working

### ISSUE THREAD

**Issue by MrMyth** [miranda-ng/miranda-ng#2269]
It's not working again. You can't hear the usual sound nor the unique. The plug-in doesn't do its job. Perhaps you should transfer the unique sound challenge to the plugins for dialog windows. And in the plug-in itself leave only a graphic shell for the purpose of sound.

**Comment by dartraiden** [comment]
Каждый плагин должен делать свою работу, иначе у нас получится, прости господи, квип.

**Comment by dartraiden** [comment]
Похоже, плагин не воспроизводит звук в принципе. Даже тест не проходит (кроме того, в заголовке окна какая-то лажа)

![image](https://user-images.githubusercontent.com/5046855/77175169-34850d00-6ad3-11ea-81b5-8e8b566e2951.png)

**Comment by MrMyth** [comment]
Тест лично у меня работает.

**Comment by georgehazan** [comment]
> Похоже, плагин не воспроизводит звук в принципе.

А ты звуки включи :-) начни с малого

**Comment by georgehazan** [comment]
показ какой-то ерунды в заголовке поправил, там какие-то древние ужасы были, а что касается самого плагина - пиликает исправно, будучи настроенным

**Comment by MrMyth** [comment]
> показ какой-то ерунды в заголовке поправил, там какие-то древние ужасы были, а что касается самого плагина - пиликает исправно, будучи настроенным

Неа, не пашет....

**Comment by georgehazan** [comment]
@MrMyth 
Давай тогда смотреть в dbeditor, что там творится в модуле XSoundNotify у контакта, который не работает. Должно быть XSNPlugin_ignore BYTE=0 и XSNPlugin_sound=<путь на звук>. При этом надо понимать, что без плагина BASS играть будут только вавки.

**Comment by MrMyth** [comment]
> @MrMyth
> Давай тогда смотреть в dbeditor, что там творится в модуле XSoundNotify у контакта, который не работает. Должно быть XSNPlugin_ignore BYTE=0 и XSNPlugin_sound=<путь на звук>. При этом надо понимать, что без плагина BASS играть будут только вавки. Кнопка Test в диалоге работает?

Ответ на этот вопрос есть выше, тест работает. Просто из настройки звуков все звуки тоже пашет. Дело вовсе не в формате звука. Я вешал их на псевдоконтакт ВК и на твитер. Не работает абсолютно у всех.

**Comment by georgehazan** [comment]
> Дело вовсе не в формате звука.

Так в  настройках-то что?

**Comment by MrMyth** [comment]
Проблема в том, что звук работает только для теста, при новом сообщении нет уникального звука.

**Comment by georgehazan** [comment]
вопрос остался прежним. нужно содержимое базы для этого контакта из модуля XSoundNotify

**Comment by dartraiden** [comment]
У меня вот так: ставим кастомный звук чувачку из ростера (ПКМ по контакту - set custom sound)

![image](https://user-images.githubusercontent.com/5046855/77328416-8d4fe200-6d2d-11ea-81a0-bb863231425d.png)

Теперь идём в настройки плагина и опа - у чувачка звук-то не назначен

![image](https://user-images.githubusercontent.com/5046855/77328492-a789c000-6d2d-11ea-86ff-f529b8cbfa78.png)

**Comment by dartraiden** [comment]
Короче, диалог с первого скриншота пишет в контакт. А диалог со второго скриншота пишет в Settings.

**Comment by dartraiden** [comment]
А звука так и нет вообще никакого, могу дать весь профиль.

**Comment by MrMyth** [comment]
Думаю я не смогу помочь отладить данный баг. Я понял, что чтобы настроить программу так как мне нужно, придется настраивать кучу костылей. Этот плагин как раз один из них. Нашел альтернативу: push уведомления от браузера + официальные "ВК сообщения". Если кому то интересно могу на форуме написать список проблем, мешающих мне.

**Comment by georgehazan** [comment]
поздно, уже починили ;-)
