### ISSUE TITLE
ICQ: на чистом профиле контакты с сервера подтягиваются и сразу выбрасываются в Not In List

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2273]
При каждом запуске Миранда, естественно, их стирает, а при каждом подключении протокола к сети они снова прилетают и выбрасываются в Not In List.

Логин и пароль от тестовой аси у @georgehazan

**Comment by dartraiden** [comment]
[netlog.txt](https://github.com/miranda-ng/miranda-ng/files/4363620/netlog.txt)

**Comment by georgehazan** [comment]
всё так и есть - их в списке нету. добавил всех перманентно в список, теперь они в списке нормально видны
