### ISSUE TITLE
Add option to not clear "NotOnList" group at start

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2281]
Всю жизнь в Миранде эта группа очищается автоматически при каждом запуске. А собственно, почему бы не сделать это отключаемым?

Это решит проблему некоторых ICQ-пользователей, которые, с одной стороны, опасаются, что прошляпят момент, когда сервер вдруг выкинет контакты из ростера и Миранда их сотрёт, а с другой, почему-то не желающих воспользоваться резервными копиями и подгрузкой истории с сервера.

**Comment by TaciturnShadow** [comment]
> почему-то не желающих воспользоваться резервными копиями и подгрузкой истории с сервера

Лично я храню резервные копии полтора года. Сколько хранится история на сервере я не знаю, но сомневаюсь, что она там есть вообще вся — например 15 летней давности. При этом старая история нужна достаточно редко, так что легко может оказаться, что резервных копий уже нет, а на сервере никогда и не было. Так что лучше бы история никогда самостоятельно не стиралась. Собственно в Miranda-IM так и было — у локального списка был приоритет перед серверным, сервер никак не мог удалить локальный контакт.

**Comment by apollo2k4** [comment]
> Всю жизнь в Миранде эта группа очищается автоматически при каждом запуске.

Раньше была галка не очищать эту группу при выходет, но это было оень давно.

> Собственно в Miranda-IM так и было — у локального списка был приоритет перед серверным, сервер никак не мог удалить локальный контакт.

Тогда протакол был реализован по другому, т.к. это был набор кастылей которых добились реверсэнженерингом, а сейчас это по сути обычный http post

**Comment by dartraiden** [comment]
То, что было раньше, следует забыть, потому что изменился сам протокол (не его реализация в Миранде, а то, как сервер общается с клиентом).
