### ISSUE TITLE
ICQ: add message deletion support

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2282]
Сейчас при удалении сообщения из истории Миранды, оно удаляется лишь из базы.

Насколько я понимаю, нетрудно реализовать удаление сообщений и с сервера, как это делает официальный клиент.

Предлагаю обсудить, как это лучше реализовать:

0) нужно ли это реализовывать вообще? во-первых, история сотрётся только у собеседников, использующих официальный клиент, поскольку Миранда входящие запросы на стирание истории игнорит и из базы не стирает. На сервере история всё равно останется, просто будет показываться как стертая, ведь (a) по российским законам её нужно хранить определенное время, (б) с точки зрения корпорации стирать пользовательские данные намертво - глупо

1) втупую при удалении из локальной истории удалять также и с сервера. В точности, как делает оф. клиент.

2) сделать опцию "при удалении сообщения из локальной истории, удалять его из серверной истории".

3) что-то ещё?

В зависимости от избранного решения продумать разные сценарии. Например, что будет, если пользователь решит удалить из Миранды всю историю, приведёт ли это к потере серверной историии (если да, то добавить некую защиту от дурака.).

**Comment by alexeik** [comment]
а можно спросить миранду @есть ли на сервере история на этот контакт раньше какой-то даты?@
чтобы принимать решение на как можно большем количестве данных.

**Comment by georgehazan** [comment]
@dartraiden сейчас при удалении с сервера в Миранде событие молча стирается, если чо

**Comment by dartraiden** [comment]
При удалении всей истории из Миранды нужно задавать следующие вопросы

1) ты уверен?
2) с сервера тоже или только локально?
3) у собеседника тоже или только с сервера у тебя?
