### ISSUE TITLE
Disappeared option to hide toolbar in chat rooms

### ISSUE THREAD

**Issue by anon17** [miranda-ng/miranda-ng#2289]
### Expected behavior
There should be an option to hide toolbar in chat rooms, it's ugly and nonfunctional.

### Actual behavior
One can hide buttons, but the empty toolbar stripe is still displayed.

### Does it work in stable version?
The option is missing in 0.95.12 alpha build #22737 (143bd800a6). The option was present in 0.95.9.

**Comment by dartraiden** [comment]
Please show [url=https://wiki.miranda-ng.org/index.php?title=Version_information]version info[/url], because there is three different message plugins: StdMsg, Scriver, TabSRMM.

**Comment by georgehazan** [comment]
in StdMsg you can disable toolbar only both for chats & group chats

**Comment by anon17** [comment]
[spoiler=VersionInfo][quote]Miranda NG Version: 0.95.12 alpha build #22737 (143bd800a6) x64
Build time: 2 Apr 2020 2:02:56
Profile: C:\Users\User\AppData\Local\MirandaNG\user\user.dat
Profile size: 3145728 Bytes
Profile creation date: 27 Sep 2018 14:54:45
Language pack: No language pack installed
Service Mode: No

[b]Active Plugins (7):[/b]
¤ AVS.dll v.[b]0.98.1.2[/b] [2 Apr 2020 2:03:00] - Avatar service 
¤ CrashDumper.dll v.[b]0.1.0.4[/b] [2 Apr 2020 2:03:29] - Crash dumper 
¤ Db_autobackups.dll v.[b]0.1.0.4[/b] [2 Apr 2020 2:03:10] - Db autobackuper 
¤ Dbx_mdbx.dll v.[b]0.95.9.1[/b] [2 Apr 2020 2:04:32] - Miranda NG MDBX database driver 
¤ IRC.dll v.[b]0.95.10.1[/b] [2 Apr 2020 2:03:02] - IRC protocol 
¤ Jabber.dll v.[b]0.95.11.1[/b] [2 Apr 2020 2:03:27] - Jabber protocol 
¤ SkypeWeb.dll v.[b]0.12.3.6[/b] [2 Apr 2020 2:04:06] - Skype protocol (Web) 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
SKYPE                    1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 Proto_Dummy.dll [2 Apr 2020 2:04:37]
 Proto_Facebook.dll [2 Apr 2020 2:04:37]
 Proto_GG.dll [2 Apr 2020 2:04:36]
 Proto_ICQ.dll [2 Apr 2020 2:04:37]
 Proto_IRC.dll [2 Apr 2020 2:04:36]
 Proto_Jabber.dll [2 Apr 2020 2:04:36]
 Proto_MetaContacts.dll [2 Apr 2020 2:04:37]
 Proto_MRA.dll [2 Apr 2020 2:04:37]
 Proto_MSN.dll [2 Apr 2020 2:04:36]
 Proto_Skype.dll [2 Apr 2020 2:04:38]
 TabSRMM_icons.dll [2 Apr 2020 2:04:37]
 Toolbar_icons.dll [2 Apr 2020 2:04:36]
 xStatus_Jabber.dll [2 Apr 2020 2:04:36]
[/quote][/spoiler]

It did work separately in 0.95.9.

**Comment by anon17** [comment]
> in StdMsg you can disable toolbar only both for chats & group chats

I don't know what plugin I use, but I can't disable toolbar for all chats either.

**Comment by anon17** [comment]
When I hide all buttons, toolbar still remains.

**Comment by dartraiden** [comment]
<img width="482" alt="Miranda64_7a1SoOSiKu" src="https://user-images.githubusercontent.com/5046855/78671023-58c05680-78e7-11ea-9903-38c98b3a58e0.png">
