### ISSUE TITLE
NewStory: кракозябры в окне предпросмотра

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2294]
В "Windows title" всё ок, а вот другие шаблоны выглядят странно

<img width="482" alt="Miranda64_Tp7RGguXLG" src="https://user-images.githubusercontent.com/5046855/78509676-83e86000-7798-11ea-8cfe-c167d773a2a0.png">

**Comment by Mataes** [comment]
fixed in 897d6fe
