### ISSUE TITLE
NewStory: в англоязычной ОС кириллица в истории отображается некорректно

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2297]
<img width="429" alt="Miranda64_7XgY5Xic6B" src="https://user-images.githubusercontent.com/5046855/78509885-0faebc00-779a-11ea-8989-0906188a15d2.png">

H++ в этих же условиях отображает всё корректно. Здесь явно не хватает юникода.

**Comment by georgehazan** [comment]
исправлено где-то в отстреле анси
