### ISSUE TITLE
AIM shows "undef" for my screen name

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#230]
**Reported by ltwally on 9 Sep 2013 16:09 UTC**
My chat log shows "undef" for my screenname when using AIM.  So far, other clients seem to work correctly.

This is only in the chat window.  When viewed from History++, my screenname appears as it should.

![screen_shot](https://cloud.githubusercontent.com/assets/5046855/21098668/62c12a10-c07b-11e6-8fa5-7ce4f0b58085.png)

**Comment by georgehazan** [comment]
**Comment by ltwally on 9 Sep 2013 16:12 UTC**
screen shot here:
http://postimg.org/image/6tfr3sf71/

**Comment by georgehazan** [comment]
**Comment by ltwally on 9 Sep 2013 16:14 UTC**
version info:
CPU: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz [Family 6 Model 58 Stepping 9](Intel64) [enabled](DEP) [CPUs](4)
Installed RAM: 32718 MBytes
Operating System: Microsoft Windows 7 Ultimate Edition, 64-bit Service Pack 1 (build 7601)
Shell: explorer.exe
Internet Explorer: 9.10.9200.16660 (build 99200)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | English/English
Free disk space on Miranda partition: 92281 MBytes

Miranda path: C:\SOFTWARE\NETWORK\miranda
Miranda NG version: 0.94.4 #5216 x64
Build time: 3 Jul 2013 0:46:42
Profile path: D:\Users\user\AppData\Roaming\Miranda NG\user\user.dat
Profile size: 10112.00 KBytes
Profile creation date: 4 Sep 2013 9:02:19
Language pack: No language pack installed
Service Mode: No

Active Plugins (24):
  AddContactPlus.dll v.[[3 Jul 2013 0:35:18](b]0.9.9.1[/b]) - Add contact+
  AdvaImg.dll v.[[30 May 2013 8:44:57](b]0.11.0.1[/b]) - Miranda image services
  AIM.dll v.[[3 Jul 2013 0:29:50](b]0.11.0.1[/b]) - AIM protocol
  AVS.dll v.[[3 Jul 2013 0:28:46](b]0.11.0.1[/b]) - Avatar service
  Clist_modern.dll v.[[3 Jul 2013 0:36:40](b]0.9.0.11[/b]) - Modern contact list
  DbEditorPP.dll v.[[3 Jul 2013 0:38:36](b]3.2.0.0[/b]) - Database editor++
  Dbx_3x.dll v.[[30 May 2013 8:41:44](b]0.11.0.1[/b]) - Miranda NG database driver
  Dbx_mmap.dll v.[[30 May 2013 8:41:50](b]0.11.0.1[/b]) - Miranda NG mmap database driver
  HistoryPP.dll v.[[30 Jun 2013 15:20:26](b]1.5.1.5[/b]) - History++
  ICQ.dll v.[[2 Jul 2013 14:30:56](b]0.11.0.1[/b]) - IcqOscarJ Protocol
  Import.dll v.[[30 May 2013 8:41:37](b]0.11.0.1[/b]) - Import contacts and messages
  IRC.dll v.[[3 Jul 2013 0:30:14](b]0.11.0.1[/b]) - IRC protocol
  Jabber.dll v.[[3 Jul 2013 0:31:20](b]0.11.0.2[/b]) - Jabber Protocol
  MirOTR.dll v.[[3 Jul 2013 0:46:48](b]0.11.0.4[/b]) - Miranda OTR
  MSN.dll v.[[3 Jul 2013 0:31:26](b]0.11.0.2[/b]) - MSN Protocol
  NewXstatusNotify.dll v.[[3 Jul 2013 0:33:08](b]1.4.0.9[/b]) - xStatus notify
  PluginUpdater.dll v.[[3 Jul 2013 0:39:28](b]0.1.1.4[/b]) - Plugin updater
  SmileyAdd.dll v.[[3 Jul 2013 0:33:52](b]0.2.3.17[/b]) - SmileyAdd
  SpellChecker.dll v.[[3 Jul 2013 0:35:08](b]0.2.6.0[/b]) - Spell checker
  StartupStatus.dll v.[[3 Jul 2013 0:34:00](b]0.8.0.45[/b]) - StartupStatus
  TabSRMM.dll v.[[3 Jul 2013 0:29:50](b]3.1.99.8[/b]) - TabSRMM
  Tipper.dll v.[[3 Jul 2013 0:34:14](b]2.1.0.4[/b]) - Tipper
  VersionInfo.dll v.[[3 Jul 2013 0:38:26](b]1.5.0.3[/b]) - Version information
  Yahoo.dll v.[[3 Jul 2013 0:30:30](b]0.11.0.1[/b]) - Yahoo Protocol

**Comment by georgehazan** [comment]
**Comment by ltwally on 26 Sep 2013 00:52 UTC**
I did some further research using the database editor.

I found that under Settings > AIM_1, there was no "Nick" string.  (Not an empty string -- no string named "Nick" whatsoever).

All the AOL contacts had this field, so I created a string called "Nick" in AIM_1 with my screenname as the contents.  Voila.  It worked.

Just to make sure I'm perfectly clear:  this was a brand new setup of Miranda NG 9.4.4.  Not an upgrade or import of Miranda IM (though I did later import Miranda IM stuff -- but this was after I'd noticed the issue).

I believe you have a bug in your account creation process for AIM accounts, though it might be some random plugin that killed the Nick string after the account was created.

**Comment by georgehazan** [comment]
**Comment by robertthomas on 28 Mar 2014 05:44 UTC**
The most up to date listing of coupons for  [snapdeals](http://www.couponsdeals.in/store/snapdeal-coupons/). Our editors check coupon codes to ensure validity every day.

**Comment by dartraiden** [comment]
AIM protocol is deprecated.
