### ISSUE TITLE
NewStory: после нажатия кнопки "Поиск..." следует автоматически поставить курсор в поле поиска

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2300]
<img width="429" alt="Miranda64_p9UU04P337" src="https://user-images.githubusercontent.com/5046855/78510146-dbd49600-779b-11ea-8501-36a896ac8b00.png">

сейчас курсор туда сам не ставится и приходится делать лишний клик в появившееся после нажатия кнопки поле поиска

**Comment by Mataes** [comment]
fixed in 6f41bab
