### ISSUE TITLE
NewStory: календарь в окне истории

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2302]
Во-первых, он не работает. Выбор какой-либо даты ничего не меняет

Во-вторых, кнопка вызова календаря не позволяет его скрыть повторным нажатием на нее.

В-третьих, если при открытом календаре альт-табнуться в другое окно, то по возвращении к окну  NewStory календарь пропадёт, а окно будет заблокировано намертво.

**Comment by Mataes** [comment]
fixed in 7c0f7e4
