### ISSUE TITLE
SkypeWeb: sometimes plugin does not show contacts statuses

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2306]
What do we know:
- the problem is not common, some people report that everything is ok
- the root of the problem is that the server response contains no **UserPresence** packets about these contacts

**Comment by dartraiden** [comment]
Perhaps the cause of the problems is authorization? Can someone check auth status of these contacts?

**Comment by dartraiden** [comment]
@georgehazan can you look at this?
https://github.com/EionRobb/skype4pidgin/issues/649#issuecomment-608198191

**Comment by ablazhov** [comment]
> Perhaps the cause of the problems is authorization? Can someone check auth status of these contacts?
How do I do that?

**Comment by ablazhov** [comment]
The problem is not always with the same contacts. Now two of the problematic contacts came back Online, but another one went Offline.

**Comment by Ac314** [comment]
All my contacts are always offline. In Skype 8 their status is shown correctly. I can post the log if you need.

**Comment by vorkot11** [comment]
All of my contacts are also always offline.

**Comment by ablazhov** [comment]
I confirm - fix is working!
