### ISSUE TITLE
????? вместо символов

### ISSUE THREAD

**Issue by alexeik** [miranda-ng/miranda-ng#2309]
![image](https://user-images.githubusercontent.com/318732/78667938-7ccd6900-78e2-11ea-85d2-fd960ecffeba.png)

при цитате такого рода ников появляется знаки вопросов.
протокол steam.

**Comment by dartraiden** [comment]
Это History++ ?

**Comment by alexeik** [comment]
я ж подписал 
протокол steam

**Comment by georgehazan** [comment]
логично. поддержки 32-битного уникода в паскале нет, не было и не будет

**Comment by alexeik** [comment]
это модуль из паскаля? ох.
очень классный плагин.

**Comment by dartraiden** [comment]
Мы все равно собираемся этот журнал в будущем заменить на NewStory, так что
добавлять поддержку Юникода туда явно никто не станет

**Comment by georgehazan** [comment]
если украсть дельфи поновее, то может быть там в рантайме и поправлено... но страшно лениво на это тратить время

**Comment by alexeik** [comment]
да может просто вставить привязку прям по коду символа?
коды русски в UTF известны, и известны их места в cp1251.

**Comment by georgehazan** [comment]
@alexeik это вообще не символы. это модификаторы уникода, с помощью которых можно наслаивать разную ̶г̶а̶д̶о̶с̶т̶ь̶ ̶на обычные буквы, типа такого
