### ISSUE TITLE
Invisible status doesn't work on Facebook

### ISSUE THREAD

**Issue by rkwk** [miranda-ng/miranda-ng#2310]
Setting 'Invisible' status on Facebook always causes being seen as 'Online' by others.

**Comment by dartraiden** [comment]
New protocol can only set Invisible status at login, not dynamically.

So solution will be:
step 1: implement "Always be invisible" option
step 2: remove Invisible status

**Comment by rkwk** [comment]
Thanks for tackling this! So does it mean that if I login with 'Invisible' status being active then I stay invisible until changing the status, but after the change I stay 'Online' even if I change back to 'Invisible'? Was it working like that so far? Will it still work like that with the new option, just without the possibility to switch back to 'Invisible'? If so, maybe a better approach would be to keep 'Invisible' status for the protocol, but simply re-login when it is set?

**Comment by dartraiden** [comment]
If you want to be invisible - enable corresponding option in protocol settings and reconnect.

**Comment by rkwk** [comment]
OK, thanks for the clarification.
