### ISSUE TITLE
Request: Clist Classic - Hotkey for toggling "Disable groups" on contact list.

### ISSUE THREAD

**Issue by RathaWynter** [miranda-ng/miranda-ng#2312]
**Request:**
Hotkey option to toggle "Disable groups" on contact list.

**The problem:**
I have over 200 contacts on my list, many of which are often hidden 2-3 groups deep. Rather than having to manually open all of those groups to search for someone, its often easier to just disable the groups and quick-type the person's name rather than have to spend 20 seconds scrolling through and opening groups trying to find the user I want to message, then closing them all when done.

Having a dedicated hotkey for this would be nice for those of us with large contact lists who need to swap back and forth often.

**Currently methods for doing this:**
- Open CList > Right click > Locate Disable groups. (Requires taking hand off the keys)
- Open CList > Grave Key (to undo user selection) > Context Menu Key > Arrow Keys > Enter [Enable/Disable groups] - (Requires multiple awkward key presses all over the keyboard.)

**Desired method:**
- Open CList > Context sensitive Hotkey (Only functions when contact list is active window.)

[VersionInfo.txt](https://github.com/miranda-ng/miranda-ng/files/4448413/VersionInfo.txt)

**Comment by georgehazan** [comment]
If you mean a search in Clist_blind. I just made it independent of groups

**Comment by georgehazan** [comment]
Perhaps all you need is just to uncheck the option "Search in opened groups only". The search in all Miranda clists is incremental and recursive, it doesn't locate items in the root folder only

**Comment by RathaWynter** [comment]
The perfect solution for me would be if "Disable groups" had specific sorting options and a hotkey. That would allow "Ignore status when sorting if groups are disabled" But I suspect that would be troublesome to add in options specifically for when "Disable groups" was active.

Ive tried the "Search in opened groups only" [disabled] option with Clist Classic and with Clist Modern, but whenever i use it, it opens every group that it comes into contact with as you're typing. If a user with the letters "EM" (Emma) is hidden in a group near the bottom of your list, it opens the first group and finds "Emily", and if thats not the person you are looking for and you continue to type "EMM" it opens a different group, which then requires manually closing of not only the final group the user is in, but all of the other groups (and nested groups) that it found users in along the way.

Sadly none of the current search options seem to do what I'm looking for (Mainly the ability to quick-search my contact list without disrupting the grouping in some way.) Most of the time i only want to search inside open groups, but still end up searching inside closed groups often enough that this has become quite a problem. Disabling groups is the best solution i've found at this point, and its still not perfect by itself.
