### ISSUE TITLE
Request: Clist Classic - Dont move offline users to bottom.

### ISSUE THREAD

**Issue by RathaWynter** [miranda-ng/miranda-ng#2313]
**Request:**
Option for Clist Classic: "Dont move offline users to bottom."
It would be ideal if this was on a per-group setting (similar to the 'hide offline users in here' option.)
Specifically, I would be to use this feature when **groups are disabled** to allow for purely alpha-numeric searching of the entire contact list without status interfering.

**The Problem:**
When using Clist Classic (or whatever the default (non-modern) list is called now), if the user selects: Options > Contact List > Contact list sorting > Sort contacts by name. There is no option to 'ignore offline status.' Large groups of users are always sorted online at the top and offline at the bottom.

This leads to a problem where if you have multiple people with similar names and you type the first few characters of their name, the contact list takes you to the person who is online, even when you want to get to the person that is offline. If the person has 10 or more letters in their name, like "Daniel Thomas (Discord)" [online] and you want to get to "Daniel Thomas (Steam)" [offline] this can get rather tedious.

**Ideal behavior:**
- Per-group setting for "Dont move offline users to bottom."
- Setting specifically available for when "Disable groups" is set.

[VersionInfo.txt](https://github.com/miranda-ng/miranda-ng/files/4448618/VersionInfo.txt)

**Comment by georgehazan** [comment]
that depends on your sorting order, no? if you enable Sort by status, Miranda behaves this way, if you'd chose "Sort by name", it won't

**Comment by RathaWynter** [comment]
In Clist Classic there are only 3 mutually exclusive options, with secondary and tertiary sorting options baked in.

![Clist_Classic_Sort_By_Name](https://user-images.githubusercontent.com/35881801/78827578-8917fb80-79a0-11ea-8e7b-b80a330daba6.png)

- In Clist Classic "Sort by Name" sorts first by Online/Offline, then by name. (Which is how I prefer it when groups are enabled.)
- "Sort by Status" groups by Online / Away / NA / Offline together, and then sorts by Name.

It would be nice to have additional sorting options specifically for when groups were disabled. As mentioned in my reply on the other feature request: "The perfect solution for me would be if "Disable groups" had specific sorting options and a hotkey. That would allow "Ignore status when sorting if groups are disabled" But I suspect that would be troublesome to add in options specifically for when "Disable groups" was active."

- Slightly offtopic commentary beyond this point.

I spent multiple hours last night testing Clist Modern to see if it would solve my issues, and while it implemented a solution for Issue #2311, it created additional problems that were not in Clist Classic. (Specifically, Extra icons dimming ~90% on mouse "Hot tracking" + altered default search behavior (After typing a few letters would cause up/down arrow presses to jump the contact list to group headers or matching usernames. But **unlike** the "Improved search behavior" this method did not indicate it was in search mode, or show what letters had been typed, or filter the contact list which easily led to frequent confusion if a letter was accidentally typed. To abort this search method so you could navigate with arrowkeys again required opening a message, or backspacing all of the invisibly searched letters.)

Example of Clist Modern causing Extra Icon Dimming
![Clist_Modern_Icon_Dimming](https://user-images.githubusercontent.com/35881801/78830159-c1213d80-79a4-11ea-9c6f-08c13f02fde6.png)
