### ISSUE TITLE
Stopped getting new message notifications

### ISSUE THREAD

**Issue by rkwk** [miranda-ng/miranda-ng#2318]
Using development version and FB protocol. I noticed that since ~1-2 days ago I don't see a pop-up or tray icon blinking when a new message arrives. Only when I open a chat window from the contact list I can see that there are some new messages. Also, the option to sort contacts by "Last message time" actually works (a contact moves up), so it's only a matter of notifications.

**Comment by rkwk** [comment]
Further observations: typing notifications via tray icon blinking work. When a chat window is already open, it flashes upon a new message and a pop-up shows too. It's only when the chat window is closed that there are no message notifications.

**Comment by georgehazan** [comment]
no problems here. could you attach your VersionInfo for beginning?

**Comment by rkwk** [comment]
Miranda NG Version: 0.95.12 alpha build #22793 (7b9996c68c) x64

**Comment by georgehazan** [comment]
@rkwk I meant a plugin list, frankly speaking.
that's a combination of some plugins that causes such effect

**Comment by rkwk** [comment]
¤ AddContactPlus.dll v.0.9.9.2 [3 Apr 2020 10:17:12] - Add contact+ 
¤ AuthState.dll v.0.0.2.1 [17 Mar 2020 20:52:36] - Authorization state 
¤ AvatarHistory.dll v.0.1.0.2 [17 Mar 2020 20:53:20] - Avatar history 
¤ AVS.dll v.0.98.1.2 [5 Apr 2020 14:29:00] - Avatar service 
¤ Clist_modern.dll v.0.9.1.10 [5 Apr 2020 14:29:30] - Modern contact list 
¤ CrashDumper.dll v.0.1.0.4 [17 Mar 2020 20:53:08] - Crash dumper 
¤ Db_autobackups.dll v.0.1.0.4 [10 Apr 2020 10:02:18] - Db autobackuper 
¤ DbEditorPP.dll v.4.0.1.3 [17 Mar 2020 20:53:06] - Database editor++ 
¤ Dbx_mdbx.dll v.0.95.9.1 [10 Apr 2020 10:03:40] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.0.95.8.1 [17 Mar 2020 20:52:40] - Miranda NG mmap database driver 
¤ Dbx_sqlite.dll v.0.95.10.2 [17 Mar 2020 20:53:54] - Miranda NG SQLite database driver 
¤ Dummy.dll v.0.2.0.0 [10 Apr 2020 10:03:08] - Dummy protocol 
¤ Facebook.dll v.0.1.0.4 [10 Apr 2020 10:03:32] - Facebook 
¤ Fingerprint.dll v.0.2.0.1 [9 Apr 2020 2:03:54] - Fingerprint NG 
¤ GG.dll v.0.95.11.1 [17 Mar 2020 20:53:00] - Gadu-Gadu protocol 
¤ historypp.dll v.1.5.1.5 [9 Apr 2020 2:04:54] - History++ 
¤ Import.dll v.0.95.11.1 [10 Apr 2020 10:02:34] - Import contacts and messages 
¤ Jabber.dll v.0.95.11.1 [9 Apr 2020 2:03:42] - Jabber protocol 
¤ MessageState.dll v.0.1.0.2 [17 Mar 2020 20:53:40] - Message state 
¤ PluginUpdater.dll v.0.2.0.6 [9 Apr 2020 2:03:44] - Plugin updater 
¤ Restart.dll v.0.0.6.0 [17 Mar 2020 20:53:08] - Restart 
¤ SeenPlugin.dll v.5.0.5.5 [9 Apr 2020 2:03:24] - Last seen 
¤ Sessions.dll v.0.1.4.0 [3 Apr 2020 10:17:06] - Sessions 
¤ SkypeWeb.dll v.0.12.3.6 [9 Apr 2020 2:04:20] - Skype protocol (Web) 
¤ SmileyAdd.dll v.0.3.1.2 [9 Apr 2020 2:03:30] - SmileyAdd 
¤ SpellChecker.dll v.0.2.6.6 [17 Mar 2020 20:53:54] - Spell checker 
¤ StatusManager.dll v.1.2.0.6 [17 Mar 2020 20:53:48] - Status manager 
¤ TabSRMM.dll v.3.6.1.2 [9 Apr 2020 2:03:16] - TabSRMM 
¤ Tipper.dll v.2.1.0.7 [9 Apr 2020 2:03:26] - Tipper 
¤ TopToolBar.dll v.0.8.0.5 [3 Apr 2020 10:17:16] - TopToolBar

**Comment by rkwk** [comment]
I can confirm that it works now - thanks!
