### ISSUE TITLE
ModernOpts window is empty when returning after pressing "Extra" button

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#232]
**Reported by robyer on 25 Sep 2013 10:17 UTC**
How to reproduce:

1. Open ModernOpts
2. Go to tab Contacts
3. Press "Extra" button on the bottom
4. Close newly opened window
5. You are back at ModernOpts but it is empty

This works correctly in Miranda IM.

**Comment by georgehazan** [comment]
**Modified by robyer on 2 Jan 2014 13:15 UTC**

**Comment by georgehazan** [comment]
**Modified by mataes on 27 May 2014 08:04 UTC**

**Comment by dartraiden** [comment]
ModernOpt is deprecated.
