### ISSUE TITLE
MessageState doesn't work with Facebook

### ISSUE THREAD

**Issue by rkwk** [miranda-ng/miranda-ng#2321]
After sending a message, the message state icon stays as "sending" indefinitely. If I reopen the message window, the icon is now "read", but the tooltip says the last message was read at 01:00:00 1970-01-01.

Miranda NG Version: 0.95.12 alpha build #22801 (6938f9a6fa) x64
¤ Facebook.dll v.0.1.0.5 [11 Apr 2020 2:05:00] - Facebook 
¤ MessageState.dll v.0.1.0.2 [17 Mar 2020 20:53:40] - Message state

**Comment by georgehazan** [comment]
confirmed

**Comment by georgehazan** [comment]
read delivery isn't supported in MQTT, I'm afraid, but you shall see one green checkmark
