### ISSUE TITLE
Do NOT make UNC links clickable in the message log

### ISSUE THREAD

**Issue by tweimer** [miranda-ng/miranda-ng#2325]
This is referring to https://github.com/miranda-ng/miranda-ng/commit/26521a465b9b24733459e73676bfa22dca1b5827 and #2246

I do not think that its is such a good idea to make those links clickable in the message log (or anywhere else). When you click one, Windows will send your login credentials over to the server. That may expose a certain security risk to steal your login credentials.

The same issue has been brought up for the Zoom Software.

So this should *not* be clickable by default in Miranda NG.

Source: https://www.bleepingcomputer.com/news/security/zoom-lets-attackers-steal-windows-credentials-run-programs-via-unc-links/

> As you can see from the chat messages above, a regular URL and the UNC path of \\evil.server.com\images\cat.jpg were both converted into a clickable link in the chat message.
> 
> You may be wondering what is so bad about that?
> 
> If a user clicks on a UNC path link, Windows will attempt to connect to the remote site using the SMB file-sharing protocol to open the remote cat.jpg file.
> 
> When doing this, by default Windows will send the user's login name and their NTLM password hash, which can be cracked using free tools like Hashcat to dehash, or reveal, the user's password.

**Comment by dartraiden** [comment]
> Windows will send your login credentials over to the server.

This is a normal Windows behaviour.

>  login credentials
Login and password's hash

**Comment by dartraiden** [comment]
It’s not a big deal that someone will know your account name and the password hash of your home computer (if this is not a targeted attack).

**Comment by tweimer** [comment]
> > Windows will send your login credentials over to the server.
> 
> This is a normal Windows behaviour.

Yes, but the users may not be aware of that behaviour. They might click it accidentally, not knowing what kind of syntax that is. I think that can be really dangerous when some attacker abuses it for phishing. It might even be a targeted attack, unlikely but still possible.

Maybe make it optional and disabled by default?
 
> > login credentials
> 
> Login and password's hash

Correct, but the hash can be de-hashed with a tool like Hashcat, as in the source I posted above:

> What makes this particularly problematic is that with the current power of our graphics cards and CPUs, a program like Hashcat can dehash passwords quickly. For example, the below hash for a fairly easy password was dehashed in just 16 seconds.

**Comment by dartraiden** [comment]
I'm not sure where we should implement this ... in all message plugins?

**Comment by tweimer** [comment]
> I'm not sure where we should implement this ... in all message plugins?

I was thinking it is only about TabSRMM. If other messaging plugins also have clickable UNC link, they should also get such option.

I do not see a place in the code to handle that. Not sure if H++ and IEView handle that internally. Message history would also be of concern.

**Comment by dartraiden** [comment]
Yes, UNC works in all message plugins with all logs

**Comment by georgehazan** [comment]
UNC links are processed by RichEdit control itself
the problem with tabSRMM was that EN_LINK event was preprocessed and UNC links were **blocked** explicitly

**Comment by dartraiden** [comment]
Can we restore this behaviour (preprocess EN_LINK) and put it behind option?

**Comment by tweimer** [comment]
@georgehazan My point is that there is a certain security risk with having that links clickable, as it might be abused by phishing attackers.
