### ISSUE TITLE
ChangeKeyboardLayout: problem if system have Birman Typography Layout instead of default

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2338]
https://ilyabirman.net/projects/typography-layout/

<img width="482" alt="Miranda64_yWQOm0Z6No" src="https://user-images.githubusercontent.com/5046855/79392677-72fbd380-7f7c-11ea-8b51-c3a43e717b72.png">

**Comment by georgehazan** [comment]
а в базе уникодное значение лежит?
ChangeKeyboardLayout/0419 и прочее

**Comment by dartraiden** [comment]
![image](https://user-images.githubusercontent.com/5046855/79478763-793d8e80-8014-11ea-96a3-1284f036bc2d.png)

там вообще его нет
