### ISSUE TITLE
SkypeWeb удаляет Mood Message, установленное через офиц. клиент

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2340]
>  SkypeWeb убирает запись в текстовом уведомлении статуса (в скайпе это называется "индикатор настроения", Mood Message) - делаю запись, применяю, подключаюсь Мирандой и запись исчезает. Если не подключаться Мирандой, запись на месте.

**Comment by georgehazan** [comment]
ну да, миранда замещает его на свою стамеску
проблема в том, что в скайпе она общая на все клиенты
