### ISSUE TITLE
NewStory , как бы нужно другое слово

### ISSUE THREAD

**Issue by alexeik** [miranda-ng/miranda-ng#2342]
Народ,
два слова @Новый@+ @История@ это странное объединение.
Кажись это взаимоисключающие слова.
может там HistoryBook
HistoryJournal
HistoryDump

Прикиньте, как плагин искать или в UI это будет?
Story это наверное к спаму в ВК и инсте имеет отношение. Все захотят написать новую историю как в вк или инсте? :)

**Comment by georgehazan** [comment]
это и есть новая история - принципиально новый плагин для просмотра истории, как в отдельном окне, так и внутри журналов
