### ISSUE TITLE
ICQ: при отсутствии постоянного пароля приходится вводить SMS-код при каждом логине

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2343]
Сейчас мы принудительно закрываем за собой сессию, поскольку иначе сторонний клиент Mandarin ICQ не может работать корректно. Это не проблема при использовании постоянного пароля, но при входе по SMS-коду это требует вводить новый код **при каждом подключении**, а постоянного пароля у свежесозданных учёток ICQ нет.

Пути решения проблемы:
1) не закрывать сессию. Я связался с разработчиком Mandarin ICQ, если проблема для него уже не актуальная, мы можем просто оставлять сессию висеть.

2) я нашёл пост Mikanoshi

>  Речь не про инвалидацию токена аутентификации же, логинится снова не надо, просто новую сессию потом создать используя сохранённый токен.

возможно, мы сможем из SMS-кода создать токен и использовать его для повторных созданий сессии при новых входах?

3) реализовать опцию, которая будет либо рвать сессию, либо не рвать

**Comment by georgehazan** [comment]
duplicate of #2341
