### ISSUE TITLE
[NewEventNotify] Пустой текст оповещений

### ISSUE THREAD

**Issue by goonis** [miranda-ng/miranda-ng#2348]
После последнего обновления (0.95.11 b22551)
NewEventNotify (0.2.2.4) перестал показывать текст оповещений
Настройки:
![image](https://user-images.githubusercontent.com/8069033/79737884-aa63da80-8304-11ea-8384-3eeec41ff960.png)
нажатие на Preview выглядит как 
![image](https://user-images.githubusercontent.com/8069033/79737974-cebfb700-8304-11ea-8574-e665fffd101f.png)

**Comment by georgehazan** [comment]
@goonis с каким редактором сообщений? StdMsg или скривер?

**Comment by goonis** [comment]
Думаю что StdMsg ибо Scriver никогда не ставил в плагины.

**Comment by georgehazan** [comment]
трудный вопрос, ибо у меня всё как часики, что с Popup+, что с обычным.
давай проверим перевод - может у тебя завалялся какой-то кривой лангпак?

**Comment by goonis** [comment]
дык у меня вроде на английском всё, никаких переводов.

**Comment by georgehazan** [comment]
давай тогда сделаем слепок настроек:
- выходишь из Миранды, копируешь профиль, заходишь в копию;
- убиваешь из копии все учетки, проверяешь, что все контакты и пароли исчезли
- сжимаешь профиль (Database -> Compact), чтобы убрать мусор, где могут быть пароли
- аттачишь этот слепок сюда или мне в мыло (ghazan собака miranda.im)

**Comment by goonis** [comment]
[user.zip](https://github.com/miranda-ng/miranda-ng/files/4504284/user.zip)

**Comment by georgehazan** [comment]
![image](https://user-images.githubusercontent.com/4628541/79772726-17916300-8339-11ea-9828-2db398695915.png)

**Comment by georgehazan** [comment]
@goonis давай усложним задачу - если у тебя на этом профиле ошибка воспроизводится, запакуй с профилем все dll и exe полностью, весь каталог Miranda, без PDB

**Comment by goonis** [comment]
> на этом профиле ошибка воспроизводится

А как выяснилось не воспроизводится, я и не запускал клиента после того как всё потер что касалось логинов и сжал базу, сейчас запустил с этим двухмегабайтным профилем без аккаунтов и проблемы нет.

**Comment by goonis** [comment]
Провел еще 2 эксперимента: подгрузил забекапленный профиль который был с утра и по которому был написан bugreport - баг есть, сделал ему Database Compact, перезапустил клиента - бага нет.
Странно всё это.
