### ISSUE TITLE
Jabber: the console is partially inaccessible

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#235]
**Reported by Piciok on 31 Oct 2013 15:01 UTC**
It is not possible to get to the edit field of the Jabber console.
Steps to reproduce:

1. Go to Menu -- Status -- Jabber -- Services -- XML Console

Expected behaviour: being able to move between the read-only edit box for reading output and the edit field for entering input.
Instead: one can only access the output reading part

**Comment by georgehazan** [comment]
**Modified by watcher on 29 Jun 2014 11:26 UTC**

**Comment by LittleVulpix** [comment]
This can be closed,

XML console's input and output boxes are both accessible.

**Comment by Robyer** [comment]
@LittleVulpix Just to be sure - did you try some software for blind people (I don't know how it's called) and if so, it worked as expected? Maybe it is problem of some specific software that can't access that inputs?

**Comment by LittleVulpix** [comment]
I turned on the screen reader in windows and it says: "XML console dialogue" when I open the XML console, and then for the output box, it says "rich edit control", for the input box it says "editing". I think that works?
