### ISSUE TITLE
NewStory: в настройках шаблонов нужна кнопка "Reset to default"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2350]
Там есть кнопка Cancel Edit, но она отменяет только несохранённые изменения. Т.е. это всё равно что нажать Cancel внизу окна.

Нужна кнопка "Reset to default", которая бы просто стирала соответствующий шаблон из базы, поскольку  в базу у нас как раз пишутся лишь изменённые шаблоны.

**Comment by dartraiden** [comment]
Одна проблема и одна хотелка:

1) кнопка действительно сбрасывает код шаблона и предпросмотр, но не зажигается кнопка Apply. Т.е. жмем кнопку, любуемся визуально на эффект и.. всё, в базе остаётся старый кастомизированный вариант. Нужно зажигать кнопку Apply, чтобы юзер мог применить изменения.

2) можно ли сделать, чтобы кнопка сбрасывала лишь текущий шаблон, а не все скопом?

**Comment by georgehazan** [comment]
2. делает ныне существующая кнопка Discard

**Comment by dartraiden** [comment]
Discard отменяет несохранённые изменения, сделанные в текущей сессии.
