### ISSUE TITLE
NewStory: не отображать полосу групчатах и белую рамку по периметру, правой стороной которой является скроллбар

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2355]
<img width="457" alt="Miranda64_WkHCSBVegP" src="https://user-images.githubusercontent.com/5046855/80286342-9587ac80-8733-11ea-886a-03343d0f9474.png">

**Comment by georgehazan** [comment]
а почему, собственно? а как его прокручивать?

**Comment by dartraiden** [comment]
В табсах её нет, и все прокручивается мышкой великолепно

**Comment by Mataes** [comment]
а у меня в табах есть скрол
![Скриншот 2020-04-26 00 34 12](https://user-images.githubusercontent.com/3987390/80291394-c678d900-8755-11ea-9eff-8d18a5e1fa25.png)

**Comment by georgehazan** [comment]
то же самое - есть скроллбар в чатах
возможно, где-то есть опция, которая это регулирует

**Comment by dartraiden** [comment]
Нету, в табсах это реализовывается чисто скином, ну а к стороннему журналу скин не применяется

**Comment by dartraiden** [comment]
Fixed by https://github.com/miranda-ng/miranda-ng/commit/01e2e633ef9c613464b84d8065d103d1112d4156 and https://github.com/miranda-ng/miranda-ng/commit/63c39e478f065ef664c7023e67391372ac859538
