### ISSUE TITLE
NewStory: add ability to customize incoming/outgoing names colors

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2358]

**Comment by georgehazan** [comment]
в каком смысле?

**Comment by dartraiden** [comment]
oops, fixed issue name :)

**Comment by georgehazan** [comment]
есть мнение, что не получится - там весь текст сливается воедино и рисуется залпом

**Comment by georgehazan** [comment]
так есть же в опциях Incoming name / Outgoing name - это не оно?
