### ISSUE TITLE
NewStory: некоторые переменные не работают

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2364]
`%p` - не работает совсем (заявлено, что это "AM/PM symbol")

`%a` - заявлено, что это "hour (12 hour format)", но на деле это сокращённый месяц ("янв", "окт")

`%H` - есть в предустановленных шаблонах, но про нее ни слова в справке и она не работает.

Нужно:
1) наладить `%p`
2) сделать так, чтобы `%a` давало заявленный результат ( "hour (12 hour format)"), а текущее поведение (сокращённое название месяца) повесить на какую-нибудь свободную переменную
3) понять, то ли мы потеряли поддержку `%H` при портировании плагина, то ли её тупо нужно выкинуть из шаблонов.

**Comment by georgehazan** [comment]
%H выкинуть, да, остальное всё пофикшено

**Comment by dartraiden** [comment]
`%p - не работает, если регион стоит с 24-часовым временем (например, Россия).
А в табсах работает...

![Uploading mstsc_b2iKl2DSXy.png…]()
