### ISSUE TITLE
Parallel messaging (via website and Miranda) do not show in Miranda

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2368]
> This netlog was captured while exchanging messages via the browser. Normally all messages would show up in Miranda too (expected and desired behavior). This time, Miranda only showed the messages I sent through Miranda itself.

https://forum.miranda-ng.org/index.php?topic=192.msg26830#msg26830

**Comment by georgehazan** [comment]
битый профиль
