### ISSUE TITLE
Jabber: если стоит игнор сообщений от незнакомцев и кто-то добавляет меня в ростер, то запрос авторизации не приходит

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2369]
Обычная ситуация, когда никакие игноры не стоят: кто-то добавляет меня в свой ростер и мне прилетает запрос авторизации при этом.

Но если поставить игнор сообщений (не авторизаций!) от неизвестных

<img width="482" alt="Miranda64_G4NUSLfGfB" src="https://user-images.githubusercontent.com/5046855/80628086-836e7c80-8a59-11ea-87c5-e2c93883e760.png">

то запрос авторизации при добавлении не прилетит

**Comment by dartraiden** [comment]
причем, если чувак отдельно потом сделает Request auth, то оно прилетит
а в момент добавления в ростер - хренушки, режется, хотя это же не сообщение

**Comment by georgehazan** [comment]
нет, всё приходит нормально. 
не приходит, когда есть такой скрытый контакт, и он не в списке.
