### ISSUE TITLE
NewStory: add option to customize separator color

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2380]
Я упарываюсь по тёмным темам. В H++ и табсах у меня просто текст на черном фоне. В NewStory  сепараторы создают эффект зебры.

<img width="571" alt="Miranda64_7t0tOrbu59" src="https://user-images.githubusercontent.com/5046855/80925855-f8182280-8d9b-11ea-95e9-1b22ff31d303.png">

**Comment by georgehazan** [comment]
Fonts & colors -> NewStory -> Selected items

**Comment by dartraiden** [comment]
Может, переименовать в Separators тогда?

**Comment by dartraiden** [comment]
Продолжим в #2389, проблема несколько шире.
