### ISSUE TITLE
NewStory: после отмены сообщения о неудавшейся доставке сообщения в логе остаётся неизвестное событие

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2385]
Unknown event

**Comment by dartraiden** [comment]
Это то же самое, что https://github.com/miranda-ng/miranda-ng/issues/2291
только там в родном журнале табсов это выглядит как добавление неудачноотправленного сообщения в лог

**Comment by georgehazan** [comment]
уже не считает неизвестным событием, там поправлено это. а то, что табсы срут этими записями в лог - это не проблема NewStory
duplicate of #2291
