### ISSUE TITLE
ICQ игнорирует настройки приёма файлов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2390]
![Screenshot_229](https://user-images.githubusercontent.com/5046855/81011040-ee57f300-8e5f-11ea-9322-bc6b75515ea1.jpg)

Эти настройки игнорируются и файл перезаписывается всегда.
Jabber, например, учитывает эти настройки...

**Comment by georgehazan** [comment]
Жабер крут, а осеку сынок перед ним :-)

**Comment by dartraiden** [comment]
Теперь копия файла тупо не принимается, если в настройках выставить "переименовывать".

![Screenshot_231](https://user-images.githubusercontent.com/5046855/81217404-3b190680-8fe5-11ea-9897-8ad024d13680.jpg)
