### ISSUE TITLE
Если у контакта нет истории (например, она удалена), NewStory показывает событие от неизвестного контакта

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2397]
<img width="429" alt="Miranda64_HVHleVS0rr" src="https://user-images.githubusercontent.com/5046855/81225462-f3e54280-8ff1-11ea-8f4e-8deb2f5891ce.png">

достаточно очистить историю и баг вылезает

**Comment by georgehazan** [comment]
это о другом... почему-то при удалении истории остается незачищенная запись в индексе, при том, что само событие удалилось. И вот оно пытается показать это событие, но не может

**Comment by georgehazan** [comment]
кстати, если профиль сжать перед очисткой истории, то этот баг будет?

**Comment by georgehazan** [comment]
это лечится прогоном main menu -> database - Check
