### ISSUE TITLE
ICQ Icons

### ISSUE THREAD

**Issue by filchef** [miranda-ng/miranda-ng#2402]
ICQ Icons missing - only online and offline Icons are ready.
In Settings you can see all icons but in Main window when you try to choice
**_Away
Not available 
Occupied 
Do not disturb 
Invisible_** 
There no such Icons.

**Comment by dartraiden** [comment]
Server does not support these statuses starting from Dec 2018. So they were removed.

**Comment by dartraiden** [comment]
Also see https://wiki.miranda-ng.org/index.php?title=Plugin:ICQ#Comparison_of_the_capabilities_of_the_old_and_the_new_protocol_in_Miranda_NG
