### ISSUE TITLE
Хочется легкую вставку файловой ссылки на файл вместо пересылки файла

### ISSUE THREAD

**Issue by DavisR-GitHub** [miranda-ng/miranda-ng#2408]
Предлагаю добавить в TabSRMM(хотя бы) такую фичу:
При дропанье файла или папки на окно чата с зажатым шифтом не запускать передачу файла, а вставлять URL на этот файл(папку). URL с преобразованными в %20 пробелами и протоколом file:/// с тремя слэшами.

Активно используется в локалке для обмена ссылками на файлы на сервере.

В свое время я добавил это сам, но так неудобно обновляться :)
Давайте добавим это в основную ветку

**Comment by DavisR-GitHub** [comment]
https://forum.miranda-ng.org/index.php?topic=6061.new#new

**Comment by georgehazan** [comment]
pull request сделаешь?

**Comment by DavisR-GitHub** [comment]
попытаюсь

**Comment by DavisR-GitHub** [comment]
Я нашел место, куда надо добавить "создать URL(список URL-ов) и вставить в окно ввода" при условии, если нажат Shift - это функция:
https://github.com/miranda-ng/miranda-ng/blob/373e78401f7ab116bc0c1787da125d5e46c901d5/src/mir_app/src/utils.cpp#L344

Прекрасно, что она используется всеми плагинами. Одна проблема, чтобы руками вставить тест в окно ввода, я должен иметь хэндл этого окна, а в этой функции у меня его нет.
Может быть есть какой-то другой способ отсюда отправить(добавить) текст в окно ввода?
Служба какая-нибудь универсальная.

**Comment by georgehazan** [comment]
> Прекрасно, что она используется всеми плагинами. Одна проблема, чтобы руками вставить текст в окно ввода, я должен иметь хэндл этого окна, а в этой функции у меня его нет.

Надо смотреть, откуда оно вызывается, там есть и хэндл диалога, и хэндл окна ввода, куда это всё падает

**Comment by DavisR-GitHub** [comment]
Ну как вариант - да, но это во всех плагинах вставлять надо. Я обрадовался, что можно в одном месте только добавить. Так нет функции типа SendMessage(hContact, String)?

**Comment by georgehazan** [comment]
@DavisR-GitHub сделал тебе затычку, общую для всех редакторов сообщений (см. коммит выше). Там внутри m_hwnd - это диалог, а m_message.GetHwnd() - соотв. окно ввода

**Comment by DavisR-GitHub** [comment]
#2412
