### ISSUE TITLE
Problems with (false) offline contacts in skype protocol

### ISSUE THREAD

**Issue by ivan1282ka** [miranda-ng/miranda-ng#2410]
Hi.
i noticed too few contacts online in miranda. i think this is problem. 

When i login using skype app at the same time with miranda NG , something strange happens:
in the skype app there are more contacts online than in miranda ng, A few seconds after login in skype app (windows) , in miranda suddenly appear  new contacts online , and then the cotacts online in skype app and in miranda is (almost) the same. 
And then if i logout of  skype app (windows) , after some period - few seconds to few minutes, some of contacts again go offline, and the number of contacts online in miranda is small again.
If i  login to skype app again , then in miranda ng contacts again come online. After i logout, contacts in miranda ng  go offline again - after some delay time period. 

I noticed that the same behavior happens when i use skype.web. But here the delay time period before contacts going offline is longer - minutes and more. 

Is it possible that MICROSOFT detects and prevents using of miranda ng?

Will  there be skype protocol in miranda ng in the future? 

Thanks for your help. 
Best regards.

**Comment by ivan1282ka** [comment]
I confirm! This bahavior happens! 
In the beginning , it seems nothing happens.
Just in skype app(windows) there are more contacts onlinine , than in miranda ng.
But when i scroll down recent contacts list  in skype app (windows) , then in miranda ng appear new contacts online. 
So it seems skype protocol in miranda ng shows false offline contacts. 
This is problem!
It seems that skype tends to hide online status of contacts. Perahps microsoft wants to close skype in favour of other their product? 
Thanks. Best regards.

**Comment by georgehazan** [comment]
Miranda displays online only those contacts that are online according to the data received from server. Later it analyzes presence packets and set online data according to them. What you can do is to provide me with a network log (core + Skype) from the very beginning to login, and mark contacts that are online in the application. Email this log (zipped) to ghazan at miranda point im.

**Comment by ivan1282ka** [comment]
Opsss. I wil try. But  it seems difficult. :(  But it seems that this is ratherm my problem with my skype account, then common problem? Nobody else sufer false offline contacts? 
Is it only me that see  contacts as offline,   that contacts are actually online? 
Every body that uses miranda ng sees the same contacts online and offline as in skype app and skype web? No difference in online presence of contacts in skype app and miranda ng? 
Am i only one that see more contacts online in skype app than in miranda? 
So my situation is hoples ... :(

**Comment by georgehazan** [comment]
> But it seems difficult.

No, network log creation doesn't seem difficult, we're receiving hundreds of them, At least that's not possible to solve the problem without it. You can read our wiki to learn how to prepare these logs: https://wiki.miranda-ng.org/index.php?title=Network_log

> Nobody else sufer false offline contacts?

As for me, I don't use standard Skype application at all, because it's an ugly bloatware :-) and I won't install it to solve this problem.

**Comment by ivan1282ka** [comment]
Ok i don't like skype too. I think , the original sкype developers  they just betrayed us and sold us as cattle. Аnd even that alone is enough to sh**it on skype and never look at it again.
But microsoft will immediately buy and destroy every single attempt to make decent alternative of skype. As microsoft bought skype, and wine , and so on... No matter if microsoft will buy the app or will buy the developers...  In this context: would you be so kind to tell me, what happens to audio video conversations in miranda ng? With SIP protocol? A? So that we will be able to completly forget for skype app?
Any way. 
Let stay on skype web. Skype web shows 13 contacts online. Miranda ng at the same time shows only 3 contacts online. Miranda ng shows skype for buisness contacts always offline. skype web shows skype buisness contacts online. 
What about this? 
Some time after connecting to skype web, miranda ng shows more online contacts (11! 2 still missing in miranda ng). And this happens sitematically. And no one of miranda developers noticed this? 
So there is at least two possibilityes: 
1. microsoft detects miranda ng and prevents it of proper working. 
2. Skype introduced some changes, which miranda ng did not reflect. 
3. there is a definit problem in my skype account. But i have reasons to think that itis not a problem only with my account. Perhaps is problem in my ip and my compuuter? Concerning only miranda ng and dissaperaing after loging in skype web? Yes !It is! It is so possible and so likeliy ...
Judging from your answer, i wll barely expect miranda ng reflection of this problem  soon. 
It's a pity. 
Perhaps it's a shame... 
Thanks. Best regards.

**Comment by ablazhov** [comment]
Unfortunately I have to confirm this problem.
Immediately after launch Miranda shows several online contacts (online + away that is) and then during the course of 20-30 minutes it slowly reduces them to just 1 online contact. After restart of Miranda all contacts are back online.
I am preparing netlog and a few screenshots for @georgehazan

**Comment by ivan1282ka** [comment]
Закрьили? Сразу, так и без объяснении? Надеюсь все будет хорошо.
Спасибо.

**Comment by dartraiden** [comment]
Как без объяснения? Вон же ссылка на коммит, в котором изменение.

**Comment by ivan1282ka** [comment]
Извините меня. А новичок здесь.  Плохо сориентировался.

**Comment by dartraiden** [comment]
Проблема исправилась? (проверяйте в версии в разработке 0.95.12)

**Comment by ablazhov** [comment]
Только частично по-моему:
https://forum.miranda-ng.org/index.php?topic=6060.msg27033#msg27033

**Comment by dartraiden** [comment]
Ждём нетлоги.
