### ISSUE TITLE
InlinePictures в Jabber не работают в Openfire. Почти

### ISSUE THREAD

**Issue by DavisR-GitHub** [miranda-ng/miranda-ng#2411]
Есть openfire 4.5.2 с плагином httpupload
Есть Miranda NG Version: 0.95.12 alpha build #23025 (6cd98af71a)
httpupload включен в миранде
При пересылке картинок(файлов изображений) отправка вроде как проходит, но вторая сторона не получает даже извещения. При этом сбрасывается соединение с сервером у отправителя.
На сервере - эксепшн: "Stopped parsing never ending stanza"
[Вычитал](https://discourse.igniterealtime.org/t/openfire-resetting-connections/48990/3), что при превышении станзой одного мегабайта опенфайр сбрасывает соединение, считая клиента подозрительным DoS-ником.
При этом другие файлы пересылаются через httpupload нормально.
В интерфейсе не нашел кнопки, а вот в базе нашел заветный параметр InlinePictures.
При 0 картинки тоже идут через httpupload и все хорошо.
Как-то стоит пофиксить такую ситуацию

**Comment by georgehazan** [comment]
это баг в openfire, 
лечится отключением зипования трафика в миранде
