### ISSUE TITLE
Список контактов не отображает группы с длинными наименованиями

### ISSUE THREAD

**Issue by alexkutuzov** [miranda-ng/miranda-ng#2421]
В  разделе CListGroup базы данных ограничена длина значения для элементов и как следствие вложенные группы с длинным наименованием не могут быть корректно отображены (имя группы обрезается после 125 символов).
Контакты  при этом имеют в разделе CList значение Group с полным (не обрезанным после 125 символов) наименованием группы и не попадают в группы с "обрезанным" названием

**Comment by georgehazan** [comment]
печалька 🙄 а сколько символов надо, чтобы давало вводить в имя группы?

**Comment by alexkutuzov** [comment]
Чем больше тем лучше, но думаю хотя бы 256 :-) 
 
У меня название группы имеет вид: служба\отдел\участок\подучасток\..\ и прочее…т.е. из-за вложенности получается очень длинное.
 
Как временное решение везде использовал сокращения… но кто знает какие группы появятся впоследствии, а отправка сообщений сразу всей группе очень удобная функция
