### ISSUE TITLE
NewStory: добавить экспорт в XML и Text

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2426]
Пользователь утверждает, что ему позарез нужен экспорт истории в эти форматы.

**Comment by georgehazan** [comment]
есть мнение, что в плагине истории этот функционал лишний
это всё надо переносить из BasicHistory в Import, чтобы форматы импорта и экспорта совпадали

**Comment by dartraiden** [comment]
https://github.com/miranda-ng/miranda-ng/issues/2435
