### ISSUE TITLE
SkypeWeb: не подгружает контакты с сервера на новом профиле

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2427]
> если создать чистый профиль с нуля и завести в нем только скайповебовскую учетку, то внезапно в него просто не загружаются никакие контакты с сервера, контакт-лист остается напрочь пуст. Сообщения при этом принимаются, отвечать на них можно. Если из старой учетки в Database Editor++ экспортировать контакты и импортировать их в новую - то с ними тоже все ок.
Т.е. просто пустая учетка неспособна сама загрузить с сервера имеющиеся контакты.
```

**Comment by georgehazan** [comment]
да нет, загружаются, всё нормально.
