### ISSUE TITLE
Contact status not displayed on the taskbar when Miranda launched from shortcut

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#244]
**Reported by dartraiden on 24 Nov 2013 13:19 UTC**
When taskbar button grouping is ON:

if Miranda launched from double clicking on .exe - status of contact displayed on the taskbar (see screenshot1)

if Miranda launched from shortcut - only Miranda icon displayed on the taskbar (see screenshot2)

![1](https://cloud.githubusercontent.com/assets/5046855/21099582/038ec700-c080-11e6-9195-7871462f521e.png)

![2](https://cloud.githubusercontent.com/assets/5046855/21099586/07a93348-c080-11e6-8981-9c2d9452155f.png)

[VersionInfo.txt](https://github.com/miranda-ng/miranda-ng/files/645913/VersionInfo.txt)

**Comment by georgehazan** [comment]
**Comment by robyer on 25 Nov 2013 11:05 UTC**
By shortcut you mean that icon which is attached to taskbar? Or any shortcut - e.g. on desktop?

**Comment by dartraiden** [comment]
Any shortcut (from Start menu in my case). But seems like it's not actual anymore (can't reproduce this on Windows 10)
