### ISSUE TITLE
New_GPG: can't export private key

### ISSUE THREAD

**Issue by jazzl0ver** [miranda-ng/miranda-ng#2444]
При экспорте приватного ключа, в дебаг-логе сообщение:
```
2020-Jun-11 02:58:12: : GPG executable not found
```
и результирующий файл пуст. При этом ключи нормально сгенерировались.
```
Miranda NG Version: 0.95.12 alpha build #23093 (1391158fa8) x64
¤ New_GPG.dll v.[b]0.2.0.3[/b] [11 Jun 2020 2:07:56] - GPG 
```

**Comment by georgehazan** [comment]
а путь на GPG настроен?

**Comment by jazzl0ver** [comment]
да, я ж говорю: все ключи нормально сгенерировались. проблема только с экспортом (ну, может с импортом тоже - пока не пробовал)

**Comment by georgehazan** [comment]
occasionally fixed by massive code cleaning in New_GPG
