### ISSUE TITLE
SeenPlugin: не работают всплывающие окна и запись изменения статуса в историю

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2446]
Всплывающие окна включены

<img width="482" alt="Miranda64_XZisgkhS1Y" src="https://user-images.githubusercontent.com/5046855/84441173-fb78b680-ac43-11ea-8596-2737727cd8d2.png">

В настройках выбрано слежение за всеми учётными записями и запись изменения статусов контактов в историю

<img width="482" alt="Miranda64_MLtBOMuTLw" src="https://user-images.githubusercontent.com/5046855/84442155-c1a8af80-ac45-11ea-8923-0e8b82969eed.png">

Результат: когда контакт меняет статус, ни всплывающего окна нет, ни в историю ничего не пишется.

**Comment by georgehazan** [comment]
что касается записи в историю - там имеется в виду собственная какая-то история, которая хранится как список строк в базе
