### ISSUE TITLE
Ошибочное определение транспорта Jabber2Jabber

### ISSUE THREAD

**Issue by DavisR-GitHub** [miranda-ng/miranda-ng#2447]
Я переименовал свой неправильно названный Jabber домен в xmpp.domain.com.
Все хорошо, кроме того, что изменились иконки статуса.
Выяснилось, что теперь используются иконки какого-то Jabber2Jabber.
Покопался в коде и нашел такое:
https://github.com/miranda-ng/miranda-ng/blob/5fb805622a3a3368ffb3de0c649074376e70256a/protocols/JabberG/src/jabber_icolib.cpp#L46-L71
Получается, что только лишь по имени моего домена миранда решила, что у меня какой-то транспорт используется. Но это не так :(
Как по мне xmpp - нормальный субдомен для сервера Jabber.

**Comment by georgehazan** [comment]
а у самого жабера какой домен? domain.com?

**Comment by DavisR-GitHub** [comment]
именно жаббер домен  xmpp.domain.com
и сервер так же зовется
