### ISSUE TITLE
Настройки Advanced Auto Away

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#245]
**Reported by Radjah on 28 Nov 2013 16:26 UTC**
При включении смены статуса на странице "Статус / Ожидание" в настройках AAA появляется предупреждение. При выключении смены предупреждение пропадает/появляется только после переоткрытии окна настроек.

**Comment by georgehazan** [comment]
**Modified by mataes on 27 May 2014 04:30 UTC**

**Comment by dartraiden** [comment]
Не получается воспроизвести. После выключения смены статуса в "Ожидании" и нажатия "Применить", предупреждение в настройках AAA корректно пропадает.

Возможно, починилось само при переписывании на классы и объединении в Status Manager.
