### ISSUE TITLE
Missing Miranda IM / Miranda NG .SVG logos

### ISSUE THREAD

**Issue by Neustradamus** [miranda-ng/miranda-ng#2454]
I do not found the Miranda IM / Miranda NG .SVG logos, where it is?

Can you add in website/code...

If it does not exist, can you create?

There are .PNG logos but it is not official place:
- https://wiki.miranda-ng.org/User:Dart_Raiden#Miranda_NG_logos

Thanks in advance.

**Comment by dartraiden** [comment]
SVG logos do not exist, I think.

I received [PNG logos](https://wiki.miranda-ng.org/User:Dart_Raiden#Miranda_NG_logos) from one of the former team members and decided to publish them.
