### ISSUE TITLE
JABBER: GSSAPI used even if user and password set for PLAIN authentication

### ISSUE THREAD

**Issue by DavisR-GitHub** [miranda-ng/miranda-ng#2457]
I have GSSAPI working on my setup. All fine.
But sometimes I need to test miranda under another account, so I run secondary instance of miranda with different from mine user/password set manually and UseDomainLogin=false
Instead of using these credentials miranda first tries to connect using GSSAPI and connects successfully.
But under my name. 
I think this is the place or wrong order:
https://github.com/miranda-ng/miranda-ng/blob/8f35d58ce9fa00dc940b616d5ac7ea1e5421612f/protocols/JabberG/src/jabber_thread.cpp#L605-L644
GSSAPI is before PLAIN

Interesting is following. For example my real account is admin@domain.com, test user account - user@domain.com.
After successful connect miranda still thinks my account is user@, but server thinks I'm admin@ because GSSAPI used.
Next step - miranda sends request to bind resource(computer name) - COMPUTER.
`<bind xmlns="urn:ietf:params:xml:ns:xmpp-bind">`

Server approves this and responses with full jid: admin@domain.com/COMPUTER
`<iq type="result" id="mir2aeb29e2179ddcc0_1" to="domain.com/3dnnlq7npx"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>admin@domain.com/COMPUTER</jid></bind></iq>`

Miranda starts using this jid silently!
`[JABBER_1] Result Bind: user@domain.com/COMPUTER changed to admin@@domain.com/COMPUTER`

In interface everywhere I'm USER, but, for example, I receive message history for ADMIN.
And miranda shows it as chat between USER and SOMEBODY when in reality it was chat between ADMIN and SOMEBODY.
So I receive very unpleasure mess up.

**Comment by georgehazan** [comment]
Согласно стандарту, PLAIN должен использоваться как последний ресурс, если сервер рапортует наличие более секурных способов авторизации (GSSAPI, OAUTH или SCRAM). Поэтому приоритет отдаётся NTLM, как и положено.

**Comment by DavisR-GitHub** [comment]
Но это же неправильно, то что я описал!
Я в миранде задал имя и пароль, выключил доменную авторизацию, а она мало того ,что авторизует меня, использую явно мной выключенный метод доменной авторизации, так еще и скрывает это!
Я только по неправильному архиву сообщений понял ,что есть проблема.

**Comment by georgehazan** [comment]
Выключить доменную авторизацию невозможно, можно отключить взятие логина и пароля из винды, это как бы вовсе не одно и то же, просто эта галка позволяет приступить к процедуре авторизации без ввода пароля (иначе оно туда даже не полезет)

**Comment by DavisR-GitHub** [comment]
Прости меня, но я еще раз спрошу:
Я на компьютере залогинился в WInbdows под учеткой USER1, запускаю миранду, в которой ставлю имя - USER2(он тоже доменный юзер, но это не важно), и миранда успешно молча  логинится на сервер используя GSSAPI и имя USER1. Это нормальное поведение с точки зрения пользователя, по-твоему?

**Comment by apollo2k4** [comment]
> Это нормальное поведение с точки зрения пользователя, по-твоему?

А почему вы считаете что оно не правильное. Доменная авторизация подразумевает, что используются данные из текущего доменного сеанса пользователя.

**Comment by DavisR-GitHub** [comment]
> Доменная авторизация

Но я же говорю, я в настройках Миранды ввожу руками имя и убираю галку "Доменный логин"
Как я еще могу сказать - используй PLAIN авторизацию?

**Comment by georgehazan** [comment]
> А почему вы считаете что оно не правильное. Доменная авторизация подразумевает, что используются данные из текущего доменного сеанса пользователя.

Имеется в виду, что если выключена галка "Domain login", то в сторону GSSAPI не коситься даже. Некая мысль, ее надо подумать, я не готов сейчас это утверждать на 100%

**Comment by georgehazan** [comment]
> > Доменная авторизация
> 
> Но я же говорю, я в настройках Миранды ввожу руками имя и убираю галку "Доменный логин"
> Как я еще могу сказать - используй PLAIN авторизацию?

Включить галку "Отключать аутентификацию SASL" - тогда всегда будет PLAIN , без вопросов

**Comment by DavisR-GitHub** [comment]
Честно говоря, совершенно не интуитивно-понятная связь...
Я понимаю, что лень, но ведь очевидно же, что если я задал имя и пароль руками, то я ожидаю авторизацию именно с этими параметрами. PLAIN она будет или еще какая, но с **ЭТИМИ** credentials

**Comment by dartraiden** [comment]
Так может просто при включении галки "SASL" делать поля логина/пароля неактивными?

**Comment by apollo2k4** [comment]
>Честно говоря, совершенно не интуитивно-понятная связь...

Вы админ в домене, вы раздали сборку с первоначально настроенным профилем где выбрано, использовать домена для авторизации. Правильно? Правильно! Или же вы потом хотите пробежать по всем и вбить их авторизацию.
А вариантов поведения отличных от стандарта может быть много и покрыть все варианты не получиться, а это местами сильно усложнит логику которая и так не всегда, может быть очевидна.

**Comment by DavisR-GitHub** [comment]
> пробежать по всем и вбить их авторизацию
Конечно я этого не собираюсь делать.
Я все описал. Речь не об улучшении моей жизни, а об улучшении Миранды.

**Comment by DavisR-GitHub** [comment]
> Включить галку "Отключать аутентификацию SASL"

Я попробовал. Перестало подключаться совсем. В логе openfire:
` TLS was required by the server and connection was never secured. Closing connection `
