### ISSUE TITLE
В из-за модуля jabber_archive в стабильной версии дублируются сообщения при получении истории

### ISSUE THREAD

**Issue by alexkutuzov** [miranda-ng/miranda-ng#2458]
В модуле jabber_archive следующий код

```
bool operator==(const DBEVENTINFO &ev1, const DBEVENTINFO &ev2)
{
	return ev1.timestamp == ev2.timestamp && ev1.eventType == ev2.eventType && ev1.cbBlob == ev2.cbBlob && (ev1.flags & DBEF_SENT) == (ev2.flags & DBEF_SENT);
}

```
проверяет идентичность отдельных сообщений ev1 и ev2, где ev1 - полученное из истории, а ev2 - уже имеющееся в базе данных. Но существует проблема в том что даже если время сервера и клиента совпадает, то передача данных не происходит мгновенно, а значит их метки времени гарантировано отличаются на время передачи. 

Откуда такой "чудесный" алгоритм взялся то.... у сервера запрашиваются беседы, а анализируются почему-то сообщения. Возможно следует принимать беседу целиком (раз уж её запросили) с заменой уже имеющихся записей в интервале от параметра "LastCollection". Вообще в чём сакральный смысл проверки на дублирование если история уже получена ? Стираем локальную, записываем пришедшую с сервера (естественно пользователя следует предупредить что локальная история  всегда заменяется на серверную, причём с метками времени сервера). А так шанс дублирования 50 на 50 получается. 

При значительном расхождении времени сервера с клиентом возможна потеря сообщений, но тут из-за XEP-0136 ничего не поделаешь, нужен MAM.... в Миранде реально ОЧЕНЬ нужен !!!

В корпоративной сети пользователь может зайти с любого компьютера, а история сообщений должна "мигрировать" вместе с ним. Попробовали унести профиль Миранды на общий ресурс, но как говорится "боливар не выдержал двоих" (вернее двух сотен) - дисковая подсистема не справилась с нагрузкой (постоянные изменения статусов приводят к излишней нагрузке на диск)

**Comment by dartraiden** [comment]
XEP-0136 мы уже удалили, MAM реализован, нужны тестеры

**Comment by alexkutuzov** [comment]
Да, в репозитории файл уже отсутствует. В ночной сборке про XEP-0313 есть изменения, но в какой момент клиент запрашивает полную историю я так и не понял. В нетлоге сейчас посмотрел фичи для MAM :0 и :1 действительно появились. У меня Openfire 4.5.2 и плагин Monitoring Service 1.7 - он вроде должен поддерживать XEP-0313.

**Comment by alexkutuzov** [comment]
А нужен "urn:xmpp:mam:2" в caps сервера? Видимо нужно обновить плагин ?

**Comment by dartraiden** [comment]
Сейчас мы имеем то, что описано, начиная [отсюда](https://forum.miranda-ng.org/index.php?topic=6043.msg27099#msg27099) и до конца
