### ISSUE TITLE
[SRAway] пишет статусы в базу не в Unicode

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2459]
В русскоязычной (из коробки) винде ставим статусы в Statuses → Status messages на кириллице.

Переносим базу в англоязычную винду без поддержки русского.

![photo_2020-06-17_17-19-40](https://user-images.githubusercontent.com/5046855/84910883-1c1b9300-b0c0-11ea-9756-99afcb5bd10a.jpg)

Всё это хранится в базе в модуле [SRAway]. Проблема в том, что хранится как String, а нужно хранить в Unicode.

**Comment by georgehazan** [comment]
пишет в Unicode, старые статусы в ANSI, да
