### ISSUE TITLE
Невозможность собрать отдельный проект из решения Miranda в Visual Studio 2019

### ISSUE THREAD

**Issue by alexkutuzov** [miranda-ng/miranda-ng#2462]
Знаю уже было "fix for broken project file compatibility in VS2019 16.6.0", но для ветви 0_95_11 тоже нужно (или хотя бы **ЖИРНОЕ** предупреждение)

**Comment by georgehazan** [comment]
ей осталось жить месяц, и тратить пару дней на 240 проектов не хотелось бы
