### ISSUE TITLE
В Jabber не работает MAM

### ISSUE THREAD

**Issue by alexkutuzov** [miranda-ng/miranda-ng#2463]
В модуле jabber_mam.cpp в методе:

```
void CJabberProto::MamRetrieveMissingMessages()
{
	CMStringA szLastId = getMStringA("LastMamId");
	if (szLastId.IsEmpty())
		return;

	XmlNodeIq iq("set", SerialNext());
	auto *set = iq << XCHILDNS("query", JABBER_FEAT_MAM) << XCHILDNS("set", "http://jabber.org/protocol/rsm");
	set << XCHILD("max", "100");
	set << XCHILD("after", szLastId);
	m_ThreadInfo->send(iq);
}
```
стоит проверка на запрос только при наличии уже имеющихся "MamId". 
Вопрос - откуда они должны появится то?
Не поймите меня неправильно, но в описании [https://xmpp.org/extensions/xep-0313.html](url) в пункте 3.5 написано:

When a message is archived, the server MUST add an <stanza-id/> element as defined in Unique and Stable Stanza IDs (XEP-0359) [2] to the message, which informs the recipient of where and under what ID the message is stored. When doing this the server MUST follow the business rules defined in XEP-0359. The 'by' attribute MUST be set to the address of the archive. For regular users that’s the bare JID of the account and for MUC that’s the bare JID of the room.

Servers MUST NOT include the <stanza-id/> element in messages addressed to JIDs that do not have permissions to access the archive, such as a users’s outgoing messages to their contacts. However servers SHOULD include the element as a child of the forwarded message when using Message Carbons (XEP-0280) [3]

```
Example 1. Client receives a message that has been archived
<message to='juliet@capulet.lit/balcony'
         from='romeo@montague.lit/orchard'
         type='chat'>
  <body>Call me but love, and I'll be new baptized; Henceforth I never will be Romeo.</body>
  <stanza-id xmlns='urn:xmpp:sid:0' by='juliet@capulet.lit' id='28482-98726-73623' />
</message>
```
Note: Previous versions of this protocol did not specify any interaction with stanza-id, and clients MUST NOT interpret XEP-0359 IDs in messages as archive IDs unless the server advertises support for 'urn:xmpp:mam:2' specifically.

Я даже специально в переводчик внес этот текст (мало ли вдруг я что-то не так перевёл)...

Серверы НЕ ДОЛЖНЫ включать элемент stanza-id в сообщения, адресованные JID, которые не имеют разрешений на доступ к архиву, например исходящие сообщения пользователей своим контактам.

В нетлоге у меня действительно нет элемента элемент stanza-id у обычных сообщений :

`<message type="chat" to="user1@mydomain/resource" id="mirb259a5a138fedfa8_42" from="user2@mydomain/resource"><body>test</body><active xmlns="http://jabber.org/protocol/chatstates"></active><request xmlns="urn:xmpp:receipts"></request><markable xmlns="urn:xmpp:chat-markers:0"></markable></message>`

Но в сообщениях из истории группового чата он присутствует:

`<message type="groupchat" id="10zp0ypf5s" from="billboard@conference.mydomain/resource" to="user1@mydomain/resource"><body>ВСЕМ ДОБРОЕ УТРО,СЕГОДНЯ В БУФЕТЕ:пирожки с творогом и изюмом. пирожки с морковкой.ВСЕМ ДОБРО ПОЖАЛОВАТЬ.</body><stanza-id xmlns="urn:xmpp:sid:0" id="2345e69e-448f-4a75-b141-4c588d9bed86" by="billboard@conference.mydomain"/><delay xmlns="urn:xmpp:delay" stamp="2020-06-17T03:23:20.551Z" from="bufet@mydomain/resource"/></message>`

Видимо сервер возвращает историю группового чата при входе, а для личных бесед опроса просто не происходит из-за выше указанной проверки.

Сервер  о поддержке mam сообщает : 
`<feature var="urn:xmpp:mam:0"/><feature var="urn:xmpp:mam:1"/><feature var="urn:xmpp:mam:2"/>`

Поясните пожалуйста принцип - вкратце как MAM должен был работать по вашей задумке.

**Comment by georgehazan** [comment]
> Вопрос - откуда они должны появится то?

Из <stanza-id/> внутри каждого заархивированного сервером сообщения.

> Servers MUST NOT include the element in messages addressed to JIDs that do not have permissions to access the archive, such as a users’s outgoing messages to their contacts.

Для всех входящих сообщений оно должно проставляться, для исходящих - нет
