### ISSUE TITLE
MDBX+Clist Modern: "libmdbx: core.c (4294): meta_txnid" and ClistModern:"modern_clcitems.cpp (402): CLVM_GetContactHiddenStatus"

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#2467]
CrashLog: http://coraksoft1.narod.ru/temp/miranda/MirandaCrashlog_20200623_meta_txnid_GetContactHiddenStatus.7z

Likely cause of the crash plugin: Miranda NG MDBX database driver

Exception: Access Violation at address 12026557. Reading from address 00000020.

Stack Trace:
---------------------------------------------------------------
12026557 (libmdbx 12000000): w:\miranda-build\libs\libmdbx\src\src\core.c (4294): meta_txnid
12025EA4 (libmdbx 12000000): w:\miranda-build\libs\libmdbx\src\src\core.c (4361): mdbx_meta_ot
12025C8A (libmdbx 12000000): w:\miranda-build\libs\libmdbx\src\src\core.c (4415): mdbx_meta_recent
12025BF3 (libmdbx 12000000): w:\miranda-build\libs\libmdbx\src\src\core.c (4431): mdbx_meta_mostrecent
12025B15 (libmdbx 12000000): w:\miranda-build\libs\libmdbx\src\src\core.c (4444): mdbx_meta_head
12022307 (libmdbx 12000000): w:\miranda-build\libs\libmdbx\src\src\core.c (5966): mdbx_txn_renew0
12021E88 (libmdbx 12000000): w:\miranda-build\libs\libmdbx\src\src\core.c (6196): mdbx_txn_renew
16907815 (Dbx_mdbx 16900000): w:\miranda-build\plugins\dbx_mdbx\src\dbutils.cpp (64): txn_ptr_ro::txn_ptr_ro
169072B4 (Dbx_mdbx 16900000): w:\miranda-build\plugins\dbx_mdbx\src\dbsettings.cpp (97): CDbxMDBX::GetContactSettingWorker
127BC286 (mir_app 12780000): w:\miranda-build\src\mir_app\src\mdatabasecommon.cpp (209): MDatabaseCommon::GetContactSetting
1292CA80 (mir_core 12920000): w:\miranda-build\src\mir_core\src\db.cpp (103): db_get_b
127A74EF (mir_app 12780000): w:\miranda-build\src\mir_app\src\contacts.cpp (286): Contact_IsHidden
163F2659 (Clist_modern 163E0000): w:\miranda-build\plugins\clist_modern\src\modern_clcitems.cpp (402): CLVM_GetContactHiddenStatus
163EEB55 (Clist_modern 163E0000): w:\miranda-build\plugins\clist_modern\src\modern_clc.cpp (1348): clcOnIntmIconChanged
163EE846 (Clist_modern 163E0000): w:\miranda-build\plugins\clist_modern\src\modern_clc.cpp (1536): clcOnIntmStatusChanged
163F1CEB (Clist_modern 163E0000): w:\miranda-build\plugins\clist_modern\src\modern_clc.cpp (1734): cli_ContactListControlWndProc
163F19D2 (Clist_modern 163E0000): w:\miranda-build\plugins\clist_modern\src\modern_clc.cpp (1716): cli_ContactListControlWndProc

**Comment by georgehazan** [comment]
базу сожми, там какие-то проблемы
main menu - database - compact
