### ISSUE TITLE
ICQ: последнее из входящих оффлайновых сообщений имеет некорректное время

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2470]
- я не в сети
- мне пишут 3 сообщения подряд (20:59)
- через некоторое время я выхожу в онлайн (21:34)
- эти 3 сообщения прилетают
- последнее из них имеет ТЕКУЩЕЕ время, а не время реальной отправки

```
   Татьяна Бреусова  Сегодня
 [20:59]  мидвееед
 [20:59]  выхади
­
   Татьяна Бреусова  Сегодня
 [21:34]  шаман пришел

```

**Comment by georgehazan** [comment]
не подтверждаю. давай нетворк лог делать

**Comment by dartraiden** [comment]
Вот что мне отправили в 1:37, пока Миранда была выключена

![image](https://user-images.githubusercontent.com/5046855/87210670-20ce1280-c31f-11ea-9cf6-62a0222ecaad.png)

В 2:34 я запустил Миранду и получил

```
Ivan Ivanov
 [01:37]  message1
 [01:37]  message2
­
 Ivan Ivanov  Today
 [02:34]  message3
```

[netlog](https://github.com/miranda-ng/miranda-ng/files/4905909/netlog.-.Copy.txt)
