### ISSUE TITLE
Блокировка настроек от изменения

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2473]
Фича востребована в корпоративной среде, чтобы пользователь по ошибке или злому умыслу не мог менять настройки.

Какие, вообще, у пользователя есть способы менять настройки:
- диалог настроек
- autoexec_.ini
- DbEditor

Мне видится всё это так:
- при раскатывании профиля сисадмин создаёт через autoexec_.ini необходимые ему настройки в базе, в том числе _настройку1_ которая блокирует вызов диалога настроек
- также, при раскатывании профиля через autoexec_.ini может быть создана _настройка2_, которая запрещает использование механизма autoexec при следующих запусках. Это защита от прошаренного пользователя. Но она одновременно лишает сисадмина возможности в дальнейшем что-то менять через autoexec, поэтому я её вынес в отдельную настройку
- DbEditor пользователям просто не надо раскатывать, а если пользователь пытается вручную подсунуть DbEditorPP.dll, это можно блокировать через политики Windows, это не наша забота.

Таким образом всё сводится к реализации двух настроек.

**Comment by georgehazan** [comment]
Загрузку dbeditor можно уничтожить через Settings/PluginDisable, это не вопрос, а вот с загрузкой ini не всё так однозначно, потому что оно реально убьет возможность обновлять настройки. Есть мнение, что если и делать настройку, то типа путь, из которого только и можно грузить инишки (хотя чем это отличается от Glob в mirandaboot.ini)

**Comment by dartraiden** [comment]
Тем, что Glob пользователь может поменять.

**Comment by georgehazan** [comment]
> Тем, что Glob пользователь может поменять.

Нет, если миранда лежит на сетевом диске с правами read-only.

> А вот если в базе сидит настройка "грузить инишки можно только с сетевого ресурса, который read-only для пользователя", то пользователь ее уже не поменяет при условии, что мы ему перекрыли возможность..

Проблема только в том, что база и настройки, в ней содержащиеся, недоступны до момента открытия профиля,, а нужны они по странному совпадению именно в момент запуска
