### ISSUE TITLE
ICQ: от людей, отсутствующих в ростере, приходит только последнее оффлайновое сообщение

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2477]
- выключаем Миранду
- нам начинает писать чувак, который не в списке контактов
- он пишет нам несколько сообщений
- включаем Миранду
- получаем только лишь последнее из этих сообщений

мне отправили вот такое

![image](https://user-images.githubusercontent.com/5046855/87178984-abdee680-c2e6-11ea-9509-d139579104be.png)

а при запуске Миранды я увидел только "сообщение 3", хотя в нетлоге видны все

[netlog - Copy.txt](https://github.com/miranda-ng/miranda-ng/files/4904399/netlog.-.Copy.txt)

**Comment by dartraiden** [comment]
Баг всё ещё жив.

Причем, если после выхода миранды у отправителя я виден как зелененький (хотя миранда должна была закрыть сессию), то всё доходит с правильным временем

Если же я у отправителя серенький, то доходит только последнее со сбитым временем.

**Comment by puffik2022** [comment]
Ошибка уже несколько месяцев эта

**Comment by georgehazan** [comment]
Если чувак не в ростере, то для него история автоматом запрашиваться не будет, потому что нет отметки о последнем прочитанном сообщении
