### ISSUE TITLE
StdMsg, TabSRMM, Scriver: изменённые настройки подгрузки истории применяются только после переоткрытия окна

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2478]
![image](https://user-images.githubusercontent.com/5046855/87210983-460f5080-c320-11ea-804f-863ea5c28a07.png)

Если поменять настройку в блоке "Load history events" (например, выключить подгрузку истории), то это применяется лишь после переоткрытия окна сообщений

**Comment by georgehazan** [comment]
эта настройка срабатывает только при открытии окна, соотв. в уже открытых окнах оно работать не будет
