### ISSUE TITLE
ICQ: не удаётся добавить контакт в серверный ростер

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2481]
Возможно, следствие https://github.com/miranda-ng/miranda-ng/issues/2123

Мне пишет чувак, который не в ростере. Я его добавляю в группу "Чуваки", но из-за https://github.com/miranda-ng/miranda-ng/issues/2123 в клисте создаётся пустая группа "General" (потому что на сервере он добавляется в группу "General", а не "Чуваки", что и есть суть бага https://github.com/miranda-ng/miranda-ng/issues/2123).

После перезапуска Миранды этот чувак становится бледным (то есть, на сервере его почему-то нет).

**Comment by georgehazan** [comment]
fixed with #2123
