### ISSUE TITLE
Jabber: SCRAM does not work under Windows 7

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2486]
Виртуалка для тестов есть.

**Comment by dartraiden** [comment]
Todo: проверить в XP?

**Comment by dartraiden** [comment]
[netlog-2020.07.13.txt](https://github.com/miranda-ng/miranda-ng/files/4919335/netlog-2020.07.13.txt)

нетлог от того, у кого падало

**Comment by dartraiden** [comment]
мой нетлог (через тор)

[netlog - копия.txt](https://github.com/miranda-ng/miranda-ng/files/4919336/netlog.-.txt)

**Comment by georgehazan** [comment]
на моей семерке работает, так что там проблемы с виндой какие0то
в любом случае падать оно больше не будет
