### ISSUE TITLE
Jabber: add ability to delete account

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2487]
Запрос на удаление выглядит посылкой такого вот сообщения в консоли:

```
<iq type='set' from='user@example.com/Resource' id='someid'>
  <query xmlns='jabber:iq:register'>
    <remove/>
  </query>
</iq>
```

Предлагаю добавить пункт в "меню протокола → службы", который бы отсылал это серверу (вероятно, предварительно выведя юзеру сообщение "вы уверены?"). И прикрутить обработку отрицательного ответа, если сервер не позволяет удалять таким образом.

**Comment by georgehazan** [comment]
а кнопка Unregister в настройках акка - это не оно?
