### ISSUE TITLE
Jabber: кнопка регистрации учётной записи неактивна при добавлении новой учётки

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2489]
- начинаем заводить в Миранду новую учётку
- кнопка регистрации неактивна

![image](https://user-images.githubusercontent.com/5046855/87775600-0d470e00-c82f-11ea-995d-d285293b9f77.png)

- нажимаем ОК, снова открываем менеджер учёток
- кнопка активна

**Comment by georgehazan** [comment]
неактивна, потому что учетка создается только после заполнения формы и нажатия Ok, а т.к. регистрация является методом учетки , то вызывать тупо нечего, и кнопка засерена до поры до времени.
