### ISSUE TITLE
Jabber: имя конференции не подтягивается

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2492]
Захожу в нашу конференцию с другого аккаунта (с другого сервера)

У конференции не видно имени. Вкладка с её названием пустая.

![image](https://user-images.githubusercontent.com/5046855/87877923-c6514800-c9e9-11ea-824d-e8f7c731b444.png)

В списке контактов она тоже не появляется.

**Comment by georgehazan** [comment]
вообще без проблем. давай нетворк лог делать

**Comment by dartraiden** [comment]
[netlog - Copy.txt](https://github.com/miranda-ng/miranda-ng/files/4944310/netlog.-.Copy.txt)

**Comment by georgehazan** [comment]
в логе нет слова Contact added, т.е. контакт с пустым ником уже существует, соотв понять, откуда берется дерьмо, не получилось. надо стереть этот контакт целиком, перезапустить миранду и войти в чат по новой

**Comment by dartraiden** [comment]
Стер

<img width="574" alt="Miranda64_TMmLGtqZNN" src="https://user-images.githubusercontent.com/5046855/87947166-9c605a00-caab-11ea-8c23-61eab5673b79.png">

Перезапустил и вошел

[netlog - Copy.txt](https://github.com/miranda-ng/miranda-ng/files/4948182/netlog.-.Copy.txt)

**Comment by dartraiden** [comment]
Нашёл закономерность:

1) запускаем миранду, присоединяемся к конфе (меню протокола - службы - создать/войти в чат), конфа появляется в клисте
2) покидаем конфу (пкм по конфе в клисте - выход)
3) конфа становится серенькой лампочкой в клисте
4) убиваем этот контакт-конфу через редактор базы или просто удаляем из клиста (пкм - удалить)
5) снова через меню протокола присоединяемся к конфе

результат: в клисте конфа не появляется, у табсов пустой заголовок вместо названия конфы
