### ISSUE TITLE
Clist+Core: crash at "Clist_SaveStateAndRebuildList" and "modern_clc.cpp (661): clcOnTimer"

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#2496]
Clist+Core: crash at "Clist_SaveStateAndRebuildList" and "modern_clc.cpp (661): clcOnTimer"

http://coraksoft1.narod.ru/temp/miranda/MirandaCrash_20200703_Clist_SaveStateAndRebuildList.7z

Likely cause of the crash plugin: Miranda NG

Exception: Access Violation at address 1279D794. Reading from address 00000000.

Stack Trace:
---------------------------------------------------------------
1279D794 (mir_app 12780000): (filename not available) (0): Clist_SaveStateAndRebuildList
1279A826 (mir_app 12780000): (filename not available) (0): Chat_GetGroup
163F06DA (Clist_modern 163E0000): w:\miranda-build\plugins\clist_modern\src\modern_clc.cpp (661): clcOnTimer
163F1B62 (Clist_modern 163E0000): w:\miranda-build\plugins\clist_modern\src\modern_clc.cpp (1745): cli_ContactListControlWndProc
163F19D2 (Clist_modern 163E0000): w:\miranda-build\plugins\clist_modern\src\modern_clc.cpp (1716): cli_ContactListControlWndProc
0012CD84 ((module-name not available) 00000000): (filename not available) (0): (function-name not available)

**Comment by georgehazan** [comment]
не попадает в символы. 
возможно, mir_app.dll не той версии
