### ISSUE TITLE
Discord: Error establishing WebSocket connection to gateway.discord.gg

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2499]
We got more and more complains about this problem

https://forum.miranda-ng.org/index.php?topic=4985.msg27251#msg27251

**Comment by f2d** [comment]
Discord's Documentation never mentions 404 errors, but googling around suggests that it may be some Cloudflare's thing, even if it worked without problems before.

As a wild guess, maybe using the Cookie value from the last seen `Set-Cookie: __cfduid=something` HTTP header on connect attemps will help? Even not storing them in the db, but only in memory, to see if it works first.

This page says it's related to rate limiting:
https://support.cloudflare.com/hc/en-us/articles/200170156-Understanding-the-Cloudflare-Cookies

**Comment by georgehazan** [comment]
@f2d 
no, standard client doesn't use cookies at all in WebSocket initialization query, but always succeeds.
Miranda sends that cookie, but often fails

**Comment by f2d** [comment]
@georgehazan
I checked Miranda's own netlog (not anywhere deeper), and cookies never appeared in sent headers, but there is a `Set-Cookie` in every HTTP response with a date set a month in future, which as a fact changes more often than once a month.
So I thought Miranda does not send it.

I don't know about standard client (I think it would not be easy to me to confirm whether it uses cookies or not), but while using Discord in a web-browser I have `__cfduid` set to expire in about a month, `__cfruid` to expire right now, and other things which are probably not related to the issue.

**Comment by georgehazan** [comment]
@f2d if you open Inspect->Network in Chrome & look at the query which browser sends to gateway.discord.gg, you can clearly see that it passes no cookies at all:

Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,ru;q=0.8
Cache-Control: no-cache
Connection: Upgrade
Host: gateway.discord.gg
Origin: https://discord.com
Pragma: no-cache
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Key: IehmjMjG60pyYUk238+OzA==
Sec-WebSocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

**Comment by f2d** [comment]
@georgehazan
You are right.

Even if I press Ctrl+F5, it sends the cookies to `Request URL: https://discord.com/channels/@me` and every js/css it downloads there, but does not include any cookies in `Request URL: wss://gateway.discord.gg/?encoding=json&v=8&compress=zlib-stream`, which is successful.

I didn't see any other useful info and have no more ideas on the issue.

**Comment by georgehazan** [comment]
> but does not include any cookies in

evidently, because those cookies are issued for discord.com domain :) while gateway resides at discord.gg

> I didn't see any other useful info and have no more ideas on the issue.

nevermind, thanks for your attempt to help.

**Comment by f2d** [comment]
Reporting: it seems not fixed.

Still randomly getting 404 from gateway with a v=8 request in Miranda, and reattempt a minute later works.
The only difference between failed and accepted requests that I can see is in `Sec-WebSocket-Key` header values.
I did not touch anything in between, including using web browser.

Miranda NG Version: 0.95.13 alpha build #23548 (b06220b86d) x64
Build time: 25 Dec 2020 21:53:26
