### ISSUE TITLE
Ability to disable incoming sounds in chats is lost

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2501]
After https://github.com/miranda-ng/miranda-ng/commit/de061b9f00ae2fac52c2400f27588d11e0397251
there is no ability to disable incoming chat sounds (but keep highlighted sounds) without disabling incoming private sounds

This must be fixed for TabSRMM, Scriver and StdMsg

**Comment by dartraiden** [comment]
1) вкладку с фильтрами в StdMsg перенести на третье место, как в других плагинах
![image](https://user-images.githubusercontent.com/5046855/88483505-02982180-cf71-11ea-8445-f78f9faddb44.png)

2) в Options → Sounds влепить ссылку на эти фильтры

**Comment by georgehazan** [comment]
1. она и будет на третьем месте, если не менять плагины динамически
2. в списке звуков никаких линков быть не может
