### ISSUE TITLE
[0.95.12 x64] Auto Resizing Window broke

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#2504]
### Expected behavior
Auto resize of the main window to work as it did in 0.95.11.

### Actual behavior
Having a minimum setting of 5% makes the main window almost invisible on startup. Setting it to 1% actually results in a bigger window that shows the protocol list correctly.
Also, when new contacts appear in the window, the whole window lets go of the desktop edges and jumps upward. 
Also, it will often show a scroll bar instead of sizing itself correctly. 

![miranda1](https://user-images.githubusercontent.com/13466852/89062655-2390b600-d367-11ea-8ec2-4961be060bca.png)
After a restart, the window has moved upward.
![miranda2](https://user-images.githubusercontent.com/13466852/89062657-24294c80-d367-11ea-84ae-4c7a2c3a36be.png)
Connecting to several accounts makes the window move up a lot. Scrollbar issue also shown.

### Does it work in stable version?
It worked in stable 0.95.11. This is a regression

### Steps to reproduce that behavior
CPU: Intel(R) Core(TM)2 Duo CPU P8700 @ 2.53GHz [Intel64 Family 6 Model 23 Stepping 10] [DEP Enabled] [2 CPUs]
Installed RAM: 3991 MBytes
Microsoft Windows 8.1 Professional Edition, 64-bit (build 9600)
Internet Explorer: 9.11.9600.19750 (build 99600)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | German/German
Free disk space on Miranda partition: 42706 MBytes

Miranda NG Version: 0.95.12 build #23261 (cf55aa3917) x64
Build time: 31 Jul 2020 15:41:52
Profile: C:\Users\xxx\AppData\Roaming\Miranda NG\xxx\xxx.dat
Profile size: 2097152 Bytes
Profile creation date: 28 Jul 2020 17:54:42
Language pack: No language pack installed
Service Mode: No

Active Plugins (16):
¤ AVS.dll v.0.98.1.2 [31 Jul 2020 15:41:54] - Avatar service 
¤ Clist_modern.dll v.0.9.1.10 [31 Jul 2020 15:42:24] - Modern contact list 
¤ CrashDumper.dll v.0.1.0.4 [31 Jul 2020 15:42:28] - Crash dumper 
¤ Db_autobackups.dll v.0.1.0.4 [31 Jul 2020 15:42:00] - Db autobackuper 
¤ DbEditorPP.dll v.4.0.1.3 [31 Jul 2020 15:42:26] - Database editor++ 
¤ Dbx_mdbx.dll v.0.95.9.1 [31 Jul 2020 15:43:30] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.0.95.8.1 [31 Jul 2020 15:41:54] - Miranda NG mmap database driver 
¤ Dummy.dll v.0.2.0.0 [31 Jul 2020 15:42:58] - Dummy protocol 
¤ Import.dll v.0.95.11.1 [31 Jul 2020 15:42:24] - Import contacts and messages 
¤ IRC.dll v.0.95.10.1 [31 Jul 2020 15:41:58] - IRC protocol 
¤ MagneticWindows.dll v.0.0.3.2 [31 Jul 2020 15:43:12] - Magnetic Windows 
¤ PluginUpdater.dll v.0.2.0.7 [31 Jul 2020 15:42:28] - Plugin updater 
¤ StatusManager.dll v.1.2.0.6 [31 Jul 2020 15:43:08] - Status manager 
¤ Steam.dll v.0.95.12.1 [31 Jul 2020 15:43:02] - Steam protocol 
¤ TabSRMM.dll v.3.6.1.3 [31 Jul 2020 15:42:06] - TabSRMM 
¤ Tox.dll v.0.11.3.2 [31 Jul 2020 15:43:36] - Tox protocol 

Protocols and Accounts:
-------------------------------------------------------------------------------
IRC                      5 - Enabled 0 - Disabled  Loaded
STEAM                    1 - Enabled 0 - Disabled  Loaded

Icon Packs:
-------------------------------------------------------------------------------
 a0x_blue.dll [25 May 2007 14:34:20]
 a0x_bw.dll [25 May 2007 14:34:26]
 a0x_green.dll [25 May 2007 14:34:32]
 a0x_main.dll [25 May 2007 14:34:38]
 a0x_orange.dll [25 May 2007 14:34:46]
 a0x_purple.dll [25 May 2007 14:34:52]
 a0x_red.dll [25 May 2007 14:34:58]
 a0x_set1_grey.dll [25 May 2007 14:35:16]
 a0x_weather.dll [25 May 2007 14:35:04]
 a0x_yellow.dll [25 May 2007 14:35:08]
 Proto_Dummy.dll [31 Jul 2020 15:43:38]
 Proto_IRC.dll [31 Jul 2020 15:43:38]
 Proto_MetaContacts.dll [31 Jul 2020 15:43:38]
 Proto_Steam.dll [31 Jul 2020 15:43:38]
 Proto_Tox.dll [31 Jul 2020 15:43:38]
 TabSRMM_icons.dll [31 Jul 2020 15:43:38]
 Toolbar_icons.dll [31 Jul 2020 15:43:38]

**Comment by dartraiden** [comment]
Regression after https://github.com/miranda-ng/miranda-ng/commit/da3db3e87f67f374861bc0eb6e89a75b7af61fbf

**Comment by dartraiden** [comment]
See also https://github.com/miranda-ng/miranda-ng/issues/2498#issuecomment-667431971

**Comment by Tharn** [comment]
Scroll bar issue still persists.

Also, I got a crash as I was activating and de-activating a couple of accounts at once, pointing to clist_modern. I think these may be related. https://pastebin.com/va4bCKt1

**Comment by dartraiden** [comment]
We reverted problem commit completely, so scroll bar issue is #2498

Crashlog is useless without debug symbols :(

**Comment by Tharn** [comment]
Yeah I know, sorry.
Maybe I'll catch it again with symbols.

**Comment by georgehazan** [comment]
> Scroll bar issue still persists. Set minimum very low to 0% or 1% to see this more consistently.

It only means that this bug existed for years :-) cause the bad change was rolled back completely
