### ISSUE TITLE
Cannot login to lightwitch.org after update to 0.95.12

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2507]
netlogs:
https://forum.miranda-ng.org/index.php?topic=6090.msg27324#msg27324

**Comment by georgehazan** [comment]
duplicate of #2506

**Comment by dartraiden** [comment]
Not duplicate because does not fixed

**Comment by georgehazan** [comment]
Missing sha-512 keys, please reset your password - там какая-то жопа с настройками на сервере
твой аккаунт логинится на ура
