### ISSUE TITLE
ICQ adds Discord_1 module to ALL new contacts

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2509]
В базе нет ни слова Discord
Добавляю в Jabber контакт
Он получает модуль Discord_1

Это очень странно.

Баг не проявляется, если отсутствует ICQ.dll

**Comment by georgehazan** [comment]
в базе полно шлака, в т.ч. настройки для несуществующих контактов (которые когда-то были, но убились)
с дописыванием dbchecker для mdbx оно уйдет
