### ISSUE TITLE
После обновления слетели настройки шрифтов и цвета чатов

### ISSUE THREAD

**Issue by Deadooshka** [miranda-ng/miranda-ng#2512]
0.95.12 win7 32. Без всяких цветомодулей и скинов.

**Comment by georgehazan** [comment]
а что именно слетело? и в каком плагине?

**Comment by Deadooshka** [comment]
Нарушилось отображение цвета и шрифтов в чатах (инверсная схема, сейчас цвет сливается с фоном). Цвет фона не пропал. В разделе опций customize все цвета и шрифты на месте. Плагин чатов встроенный.

**Comment by georgehazan** [comment]
> Нарушилось отображение цвета и шрифтов в чатах (инверсная схема, сейчас цвет сливается с фоном).

Честно - ничего не понял. Можно хотя бы картинку, как было раньше и как сейчас

**Comment by Deadooshka** [comment]
Какую картинку? Плагин стандартный. Настроены цвета шрифтов и фоновые цвета в окнах чата (фон тёмный, шрифт светлый). После обновления через меню цвет фона не изменился, но цвет шрифтов стал чёрный, то есть сливается с фоном. Настройки типа шрифта также игнорируются. Сделал откат на предыдущий релиз.

**Comment by dartraiden** [comment]
Экспортируйте, пожалуйста, через плагин DbEditorPP (Главное меню → База → Редактор базы) весь раздел [SRMM] (правой кнопкой по нему) и залейте полученный файл на какой-нибудь обменник типа upload.ee

**Comment by dartraiden** [comment]
@georgehazan 
-  берём 0.95.11, StdMsg, делаем в *групчатах* черный фон и белый текст
- обновляем до 0.95.12
- текст в настройках цветов/шрифтов остаётся белый, но в реальности он черный
