### ISSUE TITLE
TabSRMM: Possibility of renaming View Mode(s)

### ISSUE THREAD

**Issue by RozekPoland** [miranda-ng/miranda-ng#2513]
_Configuring View Modes_  window lacks **possibility of renaming existing view modes**. Currently it is possible to Add ( [+] button ) or Remove ( [-] button ) view mode only. There is enough space for another button for renaming (visualized in the picture).

![B2dhmww](https://user-images.githubusercontent.com/37516069/89352677-f3be1700-d6b4-11ea-99fd-f3996fadf815.jpg)

**Comment by dartraiden** [comment]
View modes exists in clist_modern and clist_nicer, not tabsrmm.
