### ISSUE TITLE
TabSRMM: Expansion of Multisend contact list functionalities

### ISSUE THREAD

**Issue by RozekPoland** [miranda-ng/miranda-ng#2514]
**Multisend contact list** lacks some of the functionalities of the main contact list, such as:
- Hide offline users
- Hide offline users out there
- Hide empty groups
- Disable groups

![multisend](https://user-images.githubusercontent.com/37516069/89354278-bd829680-d6b8-11ea-931a-30e3b12dec94.jpg)

Moreover, two other actions such as:
- Select All
- Select None

would be very useful for Multisend.

**Comment by georgehazan** [comment]
that's not possible. embedded contact lists have neither toolbars nor contact menus
