### ISSUE TITLE
У протокола EM-LAN отсутствует имя учётки

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2515]
Если у протокола нет учёток в принципе, может туда, в поиск выводить какое-то "красивое" имя, типа Em-LAN?

![adblock_update (12)](https://user-images.githubusercontent.com/5046855/89652086-99e46980-d8cd-11ea-94ea-8793c57ec9bc.png)

**Comment by georgehazan** [comment]
естественно, это старый протокол, и его именем является имя его DLL
