### ISSUE TITLE
Закладки: не открываются

### ISSUE THREAD

**Issue by DavisR-GitHub** [miranda-ng/miranda-ng#2518]
0.95.12 alpha build #23291

Всем привет

У нас в openfire созданы несколько закладок на корпоративные документы вида:
Телефония
\\Storage\Документы\Наша%20Телефония.pdf

Заладки исправно отображаются в миранде, но!
Раньше(ну в 0.95.11 точно) при клике на такую закладку она открывалась - вызывался ее обработчик и загружался PDF файл.
А теперь(и я не знаю с какой версии это началось) открывается диалог редактирования закладки.
Очень неудобно.
Хорошо бы вернуть обратно открытие закладки при клике

**Comment by dartraiden** [comment]
Прикол в том, что у меня на jabber.ru двойной клик по закладке не делал
ничего. Поэтому я и просил повесить на двойной клик редактирование.

**Comment by DavisR-GitHub** [comment]
Ну у нас два вида закладок используются - конференция с автовходом(работает) и документы с инфой.
Юзеру их редактировать вообще ни к чему(хотя кнопка же есть), а просто открыть теперь нечем :(

**Comment by dartraiden** [comment]
Началось это, понятное дело, с https://github.com/miranda-ng/miranda-ng/commit/39e19d52920d404fe6e6ff6bce8959657570a667

Вопрос сложный. Напоминает мне комикс, где исправили перегрев процессора и оказалось, что у кого-то на перегрев завязан сложный костыль.

**Comment by DavisR-GitHub** [comment]
Я пока не вник в реализацию, но там же две группы - конференции и ссылки, по даблклику первые должны входится и открываться, вторые просто открываться. Не вижу идеологической путаницы.
По мне - редактирование на даблклик - это совсем не очевидно. Закладки должна "открываться"

**Comment by dartraiden** [comment]
Я не возражаю, чтобы оно входило или открывалось. Но до этого оно вообще ничего не делало по даблклику, если не путаю.

**Comment by georgehazan** [comment]
там вообще был какой-то бред, когда закладка открывалась на активацию строки в списке
сделал, чтобы по двойному клику закладка запускалась (потому что редактировать надо не в пример реже)

**Comment by DavisR-GitHub** [comment]
Проверил.
1.  UNC ссылка на PDF - часики на курсоре мелькают и больше ничего не происходит
2. Конфа, в которую я уже автовошел и окно ее закрыто - ничего не происходит
3. Конфа ,в которую не зашел - захожу и окно конфы открывается

**Comment by georgehazan** [comment]
> 1. UNC ссылка на PDF - часики на курсоре мелькают и больше ничего не происходит

И это правильно. По канону там должен быть URL (закладка имеет тип URL или Groupchat), т.е. открывается браузером, соотв. там должно быть file://etc (и всю дорогу так было)

**Comment by DavisR-GitHub** [comment]
4. URL ссылка вида file:///\\server\path\file.ext - ничего не происходит
5. URL ссылка вида file://\\server\path\file.ext - ничего не происходит

**Comment by DavisR-GitHub** [comment]
> всю дорогу так было

Дык в свое время я долго подбирал формат, чтобы он открывался именно мирандой. В итоге остановился на UNC, но мне не сложно переделать. Просто сейчас никакой не срабатывает

**Comment by georgehazan** [comment]
я проверил - там и раньше стоял вызов Utils_OpenUrl, последние 6 лет точно

**Comment by DavisR-GitHub** [comment]
Не суть важно. сейчас у меня не работает даже с file:///
Копирую ссылку в Win+R - открывает акробат ридер

**Comment by DavisR-GitHub** [comment]
6. ссылка вида http://domain открывается

**Comment by georgehazan** [comment]
@DavisR-GitHub 
попробовал забить себе ссылку с простым UNC - отработало на ура. 
надо смотреть через procmon, наверное, что за фигня там происходит

**Comment by DavisR-GitHub** [comment]
Значит это у меня что-то сломалось...
Посмотрел прокмоном - ничего не увидел полезного

**Comment by dartraiden** [comment]
В Miranda IM при нажатии Enter на выделенной закладке конфы окно закладок остаётся на экране, происходит вход в конфу, открывается окно табсов

В ночнике окно закладок закрывается и ничего не происходит.

**Comment by DavisR-GitHub** [comment]
Перешел (начисто) на Win10.
Миранда 23422.
Из закладок не открываются ссылки на файлы вида:
\\server\path\file.ext
file:///\\server\path\file.ext
file://\\server\path\file.ext

Ссылка на локальный файл типа d:\folder\file.ext работает

**Comment by georgehazan** [comment]
@DavisR-GitHub должно открываться \\server\path\file.ext

**Comment by georgehazan** [comment]
@DavisR-GitHub только что проверил UNC в url  - работает

**Comment by DavisR-GitHub** [comment]
23429
не работают :(

**Comment by georgehazan** [comment]
а если в WinKey+R вбить этот же UNC - то работает?

**Comment by DavisR-GitHub** [comment]
да, но с уточнением. Если URL без пробелов, то Win+R работает:
`\\Storage\документы\InMedia.TXT`
Если с пробелами, то тоже, но это невалидный URL:
`\\Storage\документы\In Media.TXT`
Закодированные пробелы в Win+R не работают:
`\\Storage\документы\In%20Media.TXT`

В журнале TABSRMM работает и 
`\\Storage\документы\In%20Media.TXT`
и правильный
`file:///\\Storage\документы\In%20Media.TXT`

**Comment by georgehazan** [comment]
а в жабере не работает ничто из вышеперечисленного, включая \\Storage\документы\InMedia.TXT ?

**Comment by DavisR-GitHub** [comment]
да
А раньше работало

**Comment by DavisR-GitHub** [comment]
Фух, похоже наконец-то проблема решена!
