### ISSUE TITLE
MRA не приходят уведомления о уже пришедших письмах

### ISSUE THREAD

**Issue by apollo2k4** [miranda-ng/miranda-ng#2519]
Если письмо приходит во время работы Миранды, плагин включен — уведомление есть.
Если письмо пришло, пока Миранда была выключена или плагин MRA был оффлайн — уведомления не приходит (после запуска Миранды или перевода MRA в режим Online). 

http://forum.ru-board.com/topic.cgi?forum=5&topic=50156&start=1040#15

Скорее всего на сервере что-то изменилось.

**Comment by georgehazan** [comment]
А их больше нет с нами... вообще никакого упоминания о непрочитанных письмах при логине
