### ISSUE TITLE
Esc key behavior selection not work for jabber chat rooms in Miranda NG 0.95.12 build #23263

### ISSUE THREAD

**Issue by de77** [miranda-ng/miranda-ng#2521]
I'm using tabsrrm plugin. Miranda NG options "Message Sessions ->Tabs and Layout -> Miscellaneous options -> Esc Key behavior" sets to "Minimize window to the task bar".

### Expected behavior
When I'm pressing Esc key and jabber chat room window is active, I'm expecting that message session window will minimize to the task bar.

### Actual behavior
If there is only tab in message session window then message session window is closed. If there is two tabs e.g. jabber chat room and jabber contact, and active is jabber chat room then active jabber chat room is closed. If I'm pressing Esc again on active jabber contact then Esc worked as expected.

### Does it work in stable version?
It works on stable version 0.95.11 and not work on last stable.

### Steps to reproduce that behavior
 * open jabber chat room
 * press Esc key

 VersionInfo is:
[spoiler=VersionInfo][quote]CPU: Intel(R) Core(TM) i3 CPU 540 @ 3.07GHz [x86 Family 6 Model 37 Stepping 2] [DEP Enabled] [4 CPUs]
Installed RAM: 3582 MBytes
Microsoft Windows XP Professional Service Pack 3 (build 2600)
Internet Explorer: 8.0.6001.18702 (build 86001)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian
Free disk space on Miranda partition: 26364 MBytes

Miranda NG Version: 0.95.12 build #23263 (9e0133eefc)
Build time: 2 Aug 2020 11:44:13
Profile: D:\Program Files\Miranda NG\Profiles\profile\profile.dat
Profile size: 46137344 Bytes
Profile creation date: 16 Sep 2013 15:49:26
Language pack: No language pack installed
Service Mode: No

[b]Active Plugins (17):[/b]
¤ AVS.dll v.[b]0.98.1.2[/b] [2 Aug 2020 11:44:17] - Avatar service 
¤ CrashDumper.dll v.[b]0.1.0.4[/b] [2 Aug 2020 11:44:46] - Crash dumper 
¤ Db_autobackups.dll v.[b]0.1.0.4[/b] [2 Aug 2020 11:44:25] - Db autobackuper 
¤ DbEditorPP.dll v.[b]4.0.1.3[/b] [2 Aug 2020 11:44:49] - Database editor++ 
¤ Dbx_mdbx.dll v.[b]0.95.9.1[/b] [2 Aug 2020 11:45:54] - Miranda NG MDBX database driver 
¤ Dummy.dll v.[b]0.2.0.0[/b] [2 Aug 2020 11:45:15] - Dummy protocol 
¤ historypp.dll v.[b]1.5.1.5[/b] [2 Aug 2020 11:46:01] - History++ 
¤ ICQ.dll v.[b]0.95.12.1[/b] [2 Aug 2020 11:45:33] - ICQ-WIM protocol 
¤ Jabber.dll v.[b]0.95.11.1[/b] [2 Aug 2020 11:44:47] - Jabber protocol 
¤ OpenSSL.dll v.[b]0.1.0.2[/b] [2 Aug 2020 11:45:16] - OpenSSL SSL API module 
¤ PluginUpdater.dll v.[b]0.2.0.7[/b] [2 Aug 2020 11:44:52] - Plugin updater 
¤ PopupPlus.dll v.[b]2.1.1.17[/b] [2 Aug 2020 11:44:37] - Popup plus 
¤ SeenPlugin.dll v.[b]5.0.5.5[/b] [2 Aug 2020 11:44:29] - Last seen 
¤ SpellChecker.dll v.[b]0.2.6.6[/b] [2 Aug 2020 11:45:28] - Spell checker 
¤ TabSRMM.dll v.[b]3.6.1.3[/b] [2 Aug 2020 11:44:25] - TabSRMM 
¤ Tipper.dll v.[b]2.1.0.7[/b] [2 Aug 2020 11:44:31] - Tipper 
¤ WhoUsesMyFiles.dll v.[b]0.1.0.4[/b] [2 Aug 2020 11:44:40] - Who Use My Files 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
ICQ                      1 - Enabled 0 - Disabled  Loaded
JABBER                   4 - Enabled 2 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 Flags_icons.dll [2 Aug 2020 11:45:55]
 HistoryPP_icons.dll [2 Aug 2020 11:45:55]
 Proto_AIM.dll [25 Aug 2017 19:14:46]
 Proto_Dummy.dll [2 Aug 2020 11:45:55]
 Proto_Facebook.dll [2 Aug 2020 11:45:56]
 Proto_GG.dll [2 Aug 2020 11:45:55]
 Proto_ICQ.dll [2 Aug 2020 11:45:56]
 Proto_IRC.dll [2 Aug 2020 11:45:55]
 Proto_Jabber.dll [2 Aug 2020 11:45:55]
 Proto_MetaContacts.dll [2 Aug 2020 11:45:55]
 Proto_MRA.dll [2 Aug 2020 11:45:56]
 Proto_MSN.dll [3 Feb 2020 11:22:01]
 TabSRMM_icons.dll [2 Aug 2020 11:45:55]
 Toolbar_icons.dll [2 Aug 2020 11:45:55]
 xStatus_ICQ.dll [13 Dec 2018 15:03:54]
 xStatus_Jabber.dll [2 Aug 2020 11:45:55]
[/quote][/spoiler]

**Comment by georgehazan** [comment]
@de77 you're welcome to switch to the development version and test it
if everything is ok, I'll port this fix to the stable version
