### ISSUE TITLE
YAMN: add IMAP support

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2523]
Currently only POP3 is supported.

**Comment by georgehazan** [comment]
nope, that's not possible...
IMAP is quite complex and has multiple implementations (GMail, Outlook etc) which are not compatible
there's absolutely no time for that

**Comment by georgehazan** [comment]
можно сделать лабель для улучшений на далекое будущее и прилепить это сюда, чтобы не потерять
