### ISSUE TITLE
SSL-соединение для ICQ не устанавливается под Windows XP и под Windows Server 2003

### ISSUE THREAD

**Issue by RomanPekhov** [miranda-ng/miranda-ng#2536]
Версии:
ICQ.dll:   `0.95.12.1`
Miranda32.exe:   `0.95.12 build #23264 (e981b16d78) [0.95.12.0]`

Операционная система: `Windows Server 2003 Service Pack 2 (3790.srv03_sp2_rtm.070216-1710)`

Сетевой журнал Миранды: [netlog.txt](https://github.com/miranda-ng/miranda-ng/files/5080380/netlog.txt)

Требуются ли какие-нибудь ещё подробности?

Пожалуйста, исправьте!

**Comment by dartraiden** [comment]
Ваша операционная система не поддерживает протоколы шифрования, требуемые сервером.
Это не проблема Миранды.

https://wiki.miranda-ng.org/index.php?title=SSL/TLS_problems_under_legacy_operating_systems/ru

**Comment by RomanPekhov** [comment]
С плагином OpenSsl работает.  Спасибо!

Однако Миранда официально поддерживает XP и Svr2003.  Не помешало бы при запуске под этими ОС явно предлагать пользователю установить плагин OpenSsl.  Иначе какой смысл запускаться вообще?

**Comment by georgehazan** [comment]
@RomanPekhov 
Не все протоколы работают через https. Например, интранет-сервер может спокойно не иметь ограничений на длину cyphers вообще, или работать по SSL 3,0

**Comment by dartraiden** [comment]
В XP работает способ с заплаткой, который более предпочтителен. Предполагается, что пользователь сходит на страницу протокола в нашей вики и прочтёт.

**Comment by RomanPekhov** [comment]
Ну, вот страница протокола ICQ: wiki.miranda-ng.org/index.php?title=Plugin:ICQ

Слова «SSL» на этой странице нет.  Но даже если и было бы, странно ожидать, что пользователь станет искать решение проблемы на этой странице.  Годное приложение должно бы предлагать решение на блюдечке.

В общем, я просто докладываю, что происходит.  Протокол ICQ перестал работать сам по себе.  Я не делал никаких изменений в Миранде и в ОС.  Да, вероятно, сменился сертификат на сервере.  Но, на мой взгляд, стоило бы заподозрить, что проблема может выходить даже за пределы XP и Svr2003, изучить ситуацию и, быть может, сделать какие-то шаги навстречу пользователям — чтоб не растерять аудиторию.

**Comment by dartraiden** [comment]
И прямо в начале страницы там предупреждение пользователям устаревших ОС.

Более лучшего варианта нет. Ставить плагин XP-шникам принудительно нельзя -
взвоют те, у кого Миранда на рам-диске, уже были прецеденты.

Максимум, добавить однократное предупреждение при первом запуске в XP с
новым профилем...

**Comment by RomanPekhov** [comment]
Тогда, например, такой вариант: когда получаем ошибку, которая в журнале выглядит как

SSL connection failure (80090302 377): The function requested is not supported,

тогда проверяем версию ОС и, если это XP или Svr2003, предлагаем пользователю пройти на страницу «Проблемы, связанные с SSL/TLS, в устаревших операционных системах».   Всё.  Никаких инсталляторов не требуется.  Просто сообщение с URL'ом страницы.

На всякий случай ещё раз опишу, каковы ощущения пользователя: внезапно перестало соединяться.  Видимо, опять сервер поменял протокол.  Как обычно, обновлю Миранду и ICQ.dll.   Не помогло!  Как быть, куда бежать?  С какой стати вдруг установка ещё одного плагина (OpenSsl) должна помочь?  Прежде‑то работало же без него.  Не проще ли отказаться от Миранды вовсе?

То есть, маленький шаг навстречу пользователю здесь был бы кстати.

**Comment by dartraiden** [comment]
Это далеко не единственная ошибка, увы.

**Comment by dartraiden** [comment]
@georgehazan а теоретически можно отлавливать в нетлибе ошибки SSL?
