### ISSUE TITLE
Omegle: disconnection of both parties at the same time resulting in a neverending loop in the search for a new stranger

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#254]
**Reported by Piciok on 28 Dec 2013 11:51 UTC**
In an Omegle chat, when both parties come up with the idea of disconnecting at the same time and two disconnections clash, it then always happens that the next search for a new stranger gets stuck at the stage "Waiting for a new stranger..." disconnecting and connecting the Omegle protocol fixes it.
Steps to reproduce:
1. Connect to a stranger and chat or don't.
2. Disconnect at the same time as the other party (a hard situation to arrange I guess)
3. Both disconnections happen, an error message is printed to the message log.
Result: the new search begins but gets stuck.
Expected behaviour: the search begins and as a result a new stranger is eventually found.

**Comment by georgehazan** [comment]
**Comment by robyer on 29 Mar 2014 12:10 UTC**
I'll try to fix it in the future.

Btw situation could be easily reproducible, because you can force omegle to connect to "yourself" in another Miranda instance :-)

**Comment by georgehazan** [comment]
**Modified by mataes on 27 May 2014 08:06 UTC**

**Comment by tweimer** [comment]
Closing as Omegle is dead (#3917).
