### ISSUE TITLE
Унифицировать показ стикера при отсутствии SmileyAdd

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2541]
Если SmileyAdd не установлен и приходит стикер, то во всех трёх протоколах разное поведение:

Facebook: текстовое сообщение "SmileyAdd plugin required to support stickers"
VK (при включённой опции "стикеры как смайлы"): "Message link (https://vk.com/im?sel=610570501&msgid=11)"
ICQ: {STK:кодстикера}

**Comment by georgehazan** [comment]
а чем это плохо? где-то есть ссылка на стикер, где-то ее нету. соответственно и поведение разное

**Comment by dartraiden** [comment]
Как минимум, с аськой плохо тем, что у пользователя нет возможности ни стикер увидеть, ни узнать, что нужно плагин ставить.
