### ISSUE TITLE
ICQ: statusCode:401

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2544]
Нетлог - https://pastebin.com/6RC6PCH6

Юзер утверждает, что пароль перевводил в настройки для верности, и веб-версия  логинится с этим паролем.

https://forum.miranda-ng.org/index.php?topic=6100.0

**Comment by Mikanoshi** [comment]
В логе нет auth/clientLogin запроса, пароль вообще не передаётся)
