### ISSUE TITLE
SkypeWeb cannot connect

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2549]
netlog
https://forum.miranda-ng.org/index.php?topic=4705.msg27480#msg27480

**Comment by dartraiden** [comment]
```
   ghazan  Today
 [15:35]  не очень понятно
 [15:36]  похоже, что для логина надо выполнить этот JS, который  в html
­ [15:36]  потому что выполнить его надо в браузере в контексте вызовы
 [15:36]  с переданными куками и прочим
 [15:37]  странно, почему у меня работает
 [15:38]  стер токен у себя, тоже перестало
­

```

**Comment by ikeblaster** [comment]
Skype has one extra screen, where you need to choose whether you want to keep logged-in/remembered => one extra request before skype token can be obtained. Nothing else changed.

I just hope they won't change it again soon. It looks to me like one MS team doesn't know what the other one does. There is already a "remember me" checkbox at the login page.

**Comment by georgehazan** [comment]
@ikeblaster I can reset my password to smth else and send it to you, if you want

**Comment by georgehazan** [comment]
@ikeblaster everything is ok, when I visited the site and accepted new policy (though there's nothing about it in logs)
case closed
