### ISSUE TITLE
ImportTXT crashes while importing text file with empty event

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#255]
**Reported by andrzej aa on 19 Jan 2014 12:22 UTC**
 After exporting history from History++ as text I get a text file and everything works fine after importing. But I wanted to import history from another source, so I've done everyting like in exported files except that when ImportTXT finds empty line then Miranda crashes.

Example from attachments: Partial History [alpha] - [omega].txt
ImportTXT imports only 2 events (History++ pattern). It crashes at third one instead of throwing an error or skipping line. It doesn't work when I remove this event - 4th event (that empty one) crashes Miranda as well.

I have latest Miranda 0.94.7 installed with latest PDB files but CrashDump log file doesn't say much.

[Partial History [alpha] - [omega].txt](https://github.com/miranda-ng/miranda-ng/files/645944/Partial.History.alpha.-.omega.txt)

[crash20140119130712.txt](https://github.com/miranda-ng/miranda-ng/files/645945/crash20140119130712.txt)

**Comment by georgehazan** [comment]
**Comment by esim on 20 Mar 2014 13:39 UTC**
same problem here, if i export the history from a contact that looks how andrzej_aa example and import the same file as history++ pattern, i get only "Header not found" on import window

i use v0.95.1 alpha build 8664

**Comment by georgehazan** [comment]
**Modified by mataes on 27 May 2014 04:35 UTC**

**Comment by dartraiden** [comment]
ImportTXT is deprecated.
