### ISSUE TITLE
При очистке системной истории с помощью HistorySweeperLight остаётся неизвестное событие

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2553]
- ставим HistorySweeperLight и NewStory
- в HSL включаем очистку системной истории

![image](https://user-images.githubusercontent.com/5046855/90943650-53d9ea80-e423-11ea-94cf-9773a04d45e8.png)

- перезапускаем Миранду и смотрим системную историю

![image](https://user-images.githubusercontent.com/5046855/90943638-49b7ec00-e423-11ea-80b9-27efbd08e66d.png)

**Comment by dartraiden** [comment]
Не убирается, ни чекером (пробовал из запущенной миранды, а также из менеджера профилей), ни сжатием базы.

**Comment by georgehazan** [comment]
да и хрен с ним, по факту. mdbx как бы всё
