### ISSUE TITLE
Crash in Scriver?

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#256]
**Reported by Tragen on 28 Jan 2014 08:36 UTC**
I installed 0.94.7 and everything was ok.
This morning MNG started to crash.
1 of 10 starts succeed.

[crash20140128092125.txt](https://github.com/miranda-ng/miranda-ng/files/645949/crash20140128092125.txt)

[crash20140128092235.txt](https://github.com/miranda-ng/miranda-ng/files/645950/crash20140128092235.txt)

**Comment by georgehazan** [comment]
**Comment by Tragen on 28 Jan 2014 08:40 UTC**
I can add the crash dumps, but there are all my logins with passwords included. How should I handle this?

**Comment by georgehazan** [comment]
**Comment by watcher on 28 Jan 2014 08:58 UTC**
no need for passwords or crash dumps, but crash logs with symbols will help - http://wiki.miranda-ng.org/Crash_reports

**Comment by georgehazan** [comment]
**Comment by Tragen on 28 Jan 2014 21:02 UTC**
I will upload the crash log with symbols.

Here is how I can reproduce it the crash so far. I installed smileyadd plugin and the contacts and tipper pointed to a smiley pack which didn't exist. After changing it to the correct file, everything worked.

**Comment by LittleVulpix** [comment]
This can be closed. SmileyAdd plugin will complain upon startup that the defined smiley pack is missing, but will not crash; neither will scriver. Tested on 0.95.6 alpha build 17731
