### ISSUE TITLE
contact() and ccount() functions do not work as intended (Variables plugin)

### ISSUE THREAD

**Issue by Triskele69** [miranda-ng/miranda-ng#2561]
Например, если функцию contact написать с тремя параметрами, функция не выдаст никакого результата, хотя должна возвращать найденный контакт с номером, указанным в третьем параметре
Пробовал значения от -1 до 4 и r (r, судя по коду, должен возвращать случайный результат поиска)
В базе есть как минимум 4 контакта с email равным miranda@example.com (с учетом регистра)
?contact(miranda@example.com,email,2)

Если стереть третий параметр, то функция выдаст контакт, первый найденный.
?contact(miranda@example.com,email)

Если опять добавить третий параметр, то функция также возвращает первый найденный контакт (судя по всему берет из кэша)
?contact(miranda@example.com,email,2)

Функция ccount вернет 0, если до этого не вызывалась функция contact с теми же параметрами, и вернет 1, если вызывалась хоть один раз (опять же судя по всему берет из кэша)
?ccount(miranda@example.com,email)

Версия плагина 0.2.3.11

**Comment by Triskele69** [comment]
parse_miranda.cpp

**Comment by georgehazan** [comment]
@Triskele69 да, всё именно так и обстоит, спасибо. Влил

**Comment by Triskele69** [comment]
Пофиксился вызов функции contact с тремя аргументами, работает теперь почти как надо. Находятся различные контакты при Z=2+
Но стоит только вызвать эту функцию с двумя аргументами или Z=1, то она начинает возвращать один и тот же результат (из кэша)

т.е. как я понял, происходит вызов getContactFromString(), с nMatch = 0
дальше результат поиска кэшируется и при дальнейших вызовах выдаёт результат из кэша уже вне зависимости от значения nMatch

Вот этот кусок кода всему виной, возможно тут не хватает какого-то условия типа if
```
	// search the cache
	{
		CONTACTCE tmp = { dwFlags, (wchar_t*)tszContact, 0 };

		mir_cslock lck(csContactCache);
		CONTACTCE *p = arContactCache.find(&tmp);
		if (p != nullptr)
			return (bReturnCount) ? 1 : p->hContact; // found in cache
	}
```

Функция ccount тоже возвращает максимум 1

**Comment by Triskele69** [comment]
Добрался до дебаггера, пофиксил эти две функции.
Вот #2562

**Comment by georgehazan** [comment]
влито
