### ISSUE TITLE
Miranda NG 0.95.12 Update failed

### ISSUE THREAD

**Issue by mrkod32** [miranda-ng/miranda-ng#2563]
### Expected behavior
Updated version.

### Actual behavior
After restart it didn't recognized my profile and on "New profile" tab shows "Problem: Unable to find any database, this means you cannot create a new profile, you need to get dbx_mdbx.dll"
### Does it work in stable version?
I guess not.

### Steps to reproduce that behavior
1. Install Miranda NG
2. Launch Miranda NG
3. In Update dialogue click Update
4. Agree with restart

**Comment by dartraiden** [comment]
Is dbx_mdbx.dll is present in /Plugins?

**Comment by mrkod32** [comment]
> 
> 
> Is dbx_mdbx.dll is present in /Plugins?
> Is libmdbx.mir is present in Miranda root folder?

1. Yes
2. No

**Comment by georgehazan** [comment]
O_O
then download the appropriate core archive (https://miranda-ng.org/distr/stable/x32/miranda32.zip for 32-bit Miranda, https://miranda-ng.org/distr/stable/x64/miranda64.zip for 64-bit Miranda) and unpack it into the root
