### ISSUE TITLE
Ломается профиль после ребута компа. Miranda NG не может открыть '*', профиль в неизвестном формате.

### ISSUE THREAD

**Issue by scutoff** [miranda-ng/miranda-ng#2569]
Miranda натравлен на внутренний jabber с около 500 контактами c авторизацией через доменный логин.

Если после запуска Miranda64.exe дождаться начала подгрузки контактов и сразу отправить комп(или виртуалку) в **ребут** то после перезапуска 100% будет вот так
![image](https://user-images.githubusercontent.com/61544696/93328983-540cb080-f83e-11ea-8454-c2fc7f0a9fcc.png)
Тестил на win10 и на win7 без антивируса на голой винде.
Иногда просто ребут компа вызывает такую же проблему, без предварительного выхода из миранды. Если выйти из миранды то профиль не ломается (пока не удалось добиться чтобы сломался).

Чекнул сломанный профиль
![image](https://user-images.githubusercontent.com/61544696/93329693-64715b00-f83f-11ea-8ed4-a60721439311.png)

Если делать так даже во время загрузки контактов и сразу после запуска то профиль **не** ломается
![image](https://user-images.githubusercontent.com/61544696/93330412-920ad400-f840-11ea-95c4-ab9aa6c2d6e9.png)

Наблюдение - сразу после запуска, во время подгрузки контактов, миранда ест очень много CPU, но не выше 30% на CPU i5 4690 3.5Ghz
![image](https://user-images.githubusercontent.com/61544696/93330857-4278d800-f841-11ea-8f54-d6ac4315a91e.png)
Это на таком CPU
![image](https://user-images.githubusercontent.com/61544696/93331213-bc10c600-f841-11ea-8dff-2f62e138c571.png)

На более мощном CPU Xeon Gold 6248 с выделением на виртуалку только 16 ядер загрузка всего 6%
Как только контакты загрузились CPU больше не ест. Думаю это как-то связанно.

Сломанный профиль не получается сюда загрузить.
Помогите пожалуйста!

[spoiler=VersionInfo][quote]CPU: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz [Intel64 Family 6 Model 85 Stepping 7] [DEP Enabled] [16 CPUs]
Installed RAM: 16383 MBytes
Microsoft Windows 7 Professional Edition, 64-bit (build 7600)
Internet Explorer: 9.11.19041.0 (build 919041)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian
Free disk space on Miranda partition: 73555 MBytes

Miranda NG Version: 0.95.12 build #23272 (3b4a755614) x64
Build time: 14 Sep 2020 20:53:54
Profile: C:\Users\test.tb\AppData\Roaming\Miranda\*.dat
Profile size: 3145728 Bytes
Profile creation date: 16 Sep 2020 16:46:38
Language pack: Russian (RU) [0419]
Service Mode: No

[b]Active Plugins (21):[/b]
¤ Actman.dll v.[b]0.3.0.1[/b] [25 Aug 2020 19:06:24] - Action manager 
¤ AVS.dll v.[b]0.98.1.2[/b] [25 Aug 2020 19:04:32] - Avatar service 
¤ Clist_modern.dll v.[b]0.9.1.11[/b] [25 Aug 2020 19:05:04] - Modern contact list 
¤ CrashDumper.dll v.[b]0.1.0.4[/b] [17 Sep 2020 10:10:17] - Crash dumper 
¤ Db_autobackups.dll v.[b]0.1.0.4[/b] [14 Sep 2020 20:54:06] - Db autobackuper 
¤ DbChecker.dll v.[b]0.95.13.1[/b] [14 Sep 2020 20:55:22] - Database checker 
¤ DbEditorPP.dll v.[b]4.0.1.3[/b] [25 Aug 2020 19:05:02] - Database editor++ 
¤ Dbx_mdbx.dll v.[b]0.95.9.1[/b] [14 Sep 2020 20:55:30] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.[b]0.95.8.1[/b] [25 Aug 2020 19:04:32] - Miranda NG mmap database driver 
¤ historypp.dll v.[b]1.5.1.5[/b] [14 Sep 2020 20:55:48] - History++ 
¤ IEView.dll v.[b]1.6.0.4[/b] [25 Aug 2020 19:04:42] - IEView 
¤ Jabber.dll v.[b]0.95.11.1[/b] [14 Sep 2020 20:54:36] - Jabber protocol 
¤ MyDetails.dll v.[b]0.0.1.12[/b] [25 Aug 2020 19:05:06] - My details 
¤ PluginUpdater.dll v.[b]0.2.0.9[/b] [14 Sep 2020 20:54:30] - Plugin updater 
¤ PopupPlus.dll v.[b]2.1.1.17[/b] [25 Aug 2020 19:05:04] - Popup plus 
¤ QuickSearch.dll v.[b]1.4.2.0[/b] [25 Aug 2020 19:06:24] - Quick Search 
¤ SmileyAdd.dll v.[b]0.3.2.1[/b] [14 Sep 2020 20:54:18] - SmileyAdd 
¤ SpellChecker.dll v.[b]0.2.6.6[/b] [25 Aug 2020 19:05:52] - Spell checker 
¤ StatusManager.dll v.[b]1.2.0.6[/b] [14 Sep 2020 20:55:08] - Status manager 
¤ TabSRMM.dll v.[b]3.6.1.5[/b] [14 Sep 2020 20:54:08] - TabSRMM 
¤ Variables.dll v.[b]0.2.3.11[/b] [14 Sep 2020 20:54:18] - Variables 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
JABBER                   1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 Flags_icons.dll [25 Aug 2020 19:06:22]
 HistoryPP_icons.dll [14 Sep 2020 20:55:42]
 Proto_Dummy.dll [14 Sep 2020 20:55:42]
 Proto_Facebook.dll [5 Feb 2020 16:47:32]
 Proto_GG.dll [5 Feb 2020 16:47:30]
 Proto_ICQ.dll [5 Feb 2020 16:47:32]
 Proto_IRC.dll [5 Feb 2020 16:47:30]
 Proto_Jabber.dll [14 Sep 2020 20:55:42]
 Proto_MetaContacts.dll [14 Sep 2020 20:55:42]
 Proto_MRA.dll [5 Feb 2020 16:47:32]
 Proto_MSN.dll [5 Feb 2020 16:47:30]
 TabSRMM_icons.dll [14 Sep 2020 20:55:42]
 Toolbar_icons.dll [25 Aug 2020 19:06:22]
 xStatus_Jabber.dll [14 Sep 2020 20:55:42]
[/quote][/spoiler]

**Comment by scutoff** [comment]
Если выключить плагин Clist_modern.dll то контакты подгружаются на много быстрей и профиль перестает ломаться.

**Comment by georgehazan** [comment]
обычно в модерне достаточно выключить скин, без него всё гораздо быстрее

**Comment by DmDS** [comment]
такая же проблема. периодически ломается база после перезагрузки компьютеров (без предварительного выхода). что с Clist_modern.dll, что Clist.nicer.dll, что без них... независимо от железа, ОС и наличия антивируса.

**Comment by scutoff** [comment]
> обычно в модерне достаточно выключить скин, без него всё гораздо быстрее

И так пробывал, и без Clist_modern.dll тоже профиль ломается но чуть реже.
Вобщем проблема актуальна до сих пор. С Clist_modern.dll просто 100% ломается, если его выключить то 50/50 сломается.

**Comment by dartraiden** [comment]
`такая же проблема. периодически ломается база после перезагрузки компьютеров (без предварительного выхода)`
решение простое - перезагружать компьютер через штатные механизм перезагрузки, а не жестко рубить по питанию

**Comment by DmDS** [comment]
> ни один софт не даёт 100% гарантию, что после хардресета что-то не поломается

Спасибо за простое решение, но все перезагружается как надо))

**Comment by scutoff** [comment]
> > такая же проблема. периодически ломается база после перезагрузки компьютеров (без предварительного выхода)
> 
> решение простое - перезагружать компьютер через штатный механизм перезагрузки ОС, а не жестко рубить по питанию
> ни один софт не даёт 100% гарантию, что после хардресета что-то не поломается

Про хардресет речи не шло, проблема при штатном выключении либо штатной перезагрузки.

**Comment by DmDS** [comment]
На самом деле проблемы начались ещё в январе после перехода на новый формат БД.
https://www.miranda-ng.org/en/news/?important=1
После этого начались проблемы.
Если, спустя часа 2-3 после запуска Miranda, запустить проверку БД, скорее всего будут обнаружены ошибки. Ошибки все время одинаковые.
![7D70AB79-4E84-4194-A72D-699D8D3920AF](https://user-images.githubusercontent.com/1803032/95772409-5d662d00-0cc5-11eb-8a55-e079dc6aeb7d.jpeg)

**Comment by Deadooshka** [comment]
Как восстановить то? `mdbx_dump.exe -n -a -f ... ...` выдаёт ` mdbx_env_open() error -30796 MDBX_CORRUPTED: Database is corrupted`

**Comment by dartraiden** [comment]
Опция -t поддерживается в девелоперской версии, начиная с билд 23400

*.dat-lck - это лок-файл, база - .dat

**Comment by Deadooshka** [comment]
@dartraiden до какого-то момента .dat-lck имели размер 16кб и замена этого файла из бэкапа помогала решить проблему загрузки профиля. Последняя дата бэкапов февраль 2020. У меня просто копируются перед загрузкой Миранды.

**Comment by georgehazan** [comment]
@Deadooshka это временный говнофайл, который можно истреблять без малейшего урона для работы Миранды

**Comment by dartraiden** [comment]
> У меня просто копируются перед загрузкой Миранды.

Как видите, "просто" не всегда означает "правильно".

**Comment by dartraiden** [comment]
Всем, кто сталкивается с развалом базы, просьба обновиться до свежайшей 64-разрядной (важно) версии в разработке (важно) и подсунуть в каталог Миранды файлы и папки из приложенного архива (с заменой)
[Uploading Release64.zip…]()

**Comment by DmDS** [comment]
3 дня на последней разрабатываемой версии (и 32 и 64). пока ошибок в базе не наблюдается. 
закинул pdb на всякий случай)

**Comment by dartraiden** [comment]
В ночник влиты фиксы против развала базы.

**Comment by dartraiden** [comment]
Есть какой-то фидбек? Ломается по-прежнему или проблема решена?

**Comment by DavisR-GitHub** [comment]
Я у себя в сети развернул #23473
Пока тихо, но у меня редко бывали проблемы с профилем

**Comment by dartraiden** [comment]
Учтите, что откат с "версии в разработке" на "стабильную" не рекомендуется из-за крупных изменений в драйвере.

При необходимости всё же сделать откат, следует на "версии в разработке" сделать
```
mdbx_dump.exe -n -a -f "database.tmp" "путь\к\базе.dat"
```
а на стабильной сделать 
```mdbx_load.exe -n -a -f "database.tmp" "new.dat"```

**Comment by DmDS** [comment]
> Есть какой-то фидбек? Ломается по-прежнему или проблема решена?

вроде бы все в порядке. за 2 недели проблем не было
