### ISSUE TITLE
Setting Facebook Offline Sets Tray Icon Offline

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#257]
**Reported by muppet on 29 Jan 2014 19:00 UTC**
 Hi,

I'm using v0.94.8 build #7953 x64

I'm using clist_modern

In "Contact List-> Tray" I have the following selected:

System Tray Icon Mode: Show <Jabber Account>. "Only when statuses differ" is unticked.

The problem is, when I set my Facebook account offline, the System Tray Icon shows the Jabber Icon still, but the Offline version. If I then reselect my Jabber Account to Online, it then displays the correct (Online) Icon.

This is a very small bug, but would be nice to have fixed in the upcoming stable.

Thanks!

**Comment by georgehazan** [comment]
**Modified by watcher on 2 Feb 2014 17:39 UTC**

**Comment by georgehazan** [comment]
**Modified by mataes on 27 May 2014 04:36 UTC**

**Comment by georgehazan** [comment]
**Modified by mataes on 17 Jun 2014 04:28 UTC**

**Comment by georgehazan** [comment]
**Comment by robyer on 21 Jul 2014 10:29 UTC**
There were some changes to clist_modern's tray icon. Is this bug still actual?

**Comment by LittleVulpix** [comment]
This can be closed.

The option has been reworked and now has two separate lists in a section called "Icon mode" (for similar statuses and for different statuses). Tested it with similar status set to global and different set to one of the online accounts (jabber). Upon taking the second account offline, the global tray icon correctly switched to the jabber's online status.
