### ISSUE TITLE
"Mute chat" related issues

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2574]
[ ]  describe these feature it in the wiki
[ ] режимы мута работают не так, как задумано. Вот настройки фильтра событий:

<img width="482" alt="Miranda64_ydTrsMq7Qv" src="https://user-images.githubusercontent.com/5046855/99675996-f8061880-2a88-11eb-9bc1-9276f3cd7c23.png">

что я наблюдаю при различных режимах мута в действительности

Mute: default
хайлайты - длинные, звук есть
обычные сообщения - короткие, звук есть

Mute: always
хайлайты - короткие, звук есть
обычные сообщения - короткие, звука нет

Mute: never
хайлайты - длинные, звук есть
обычные сообщения - длинные, звук есть

**Comment by dartraiden** [comment]
Сравнение того, как муты задуманы и того, что мы имеем в реальности:

| Режим   | Задумка                                                                                 | Реальность                                                                  |
|---------|-----------------------------------------------------------------------------------------|-----------------------------------------------------------------------------|
| Default | длинное (бесконечное) мигание приватов и хайлайтов, короткое (6 миганий) для остального | длинное мигание и звук хайлайтов, короткое и звук для остального            |
| Never   | никакого мигания                                                                        | длинное мигание со звуком для всего                                         |
| Always  | короткое мигание для всего                                                              | короткое мигание со звуком для хайлайтов, короткое без звука для остального |

**Comment by dartraiden** [comment]
То есть:
Never неправильно работает по миганиям
И надо определиться, как должны работать звуки

**Comment by dartraiden** [comment]
== Default ==
- ✔️ приват: длинное со звуком и попапом
- ✔️ хайлайт: длинное со звуком и попапом
- ✔️ чат: короткое со звуком и попапом
настройки мигания, звука и попапа зависят от events and filters

**Comment by dartraiden** [comment]
StdMsg:
отсутствует попап на хайлайт (галка в events and filters взведена)

**Comment by dartraiden** [comment]
TabSRMM:
- стартуем с выключенными табсами (работает StdMsg)
- в жаббере настроен автовход в конфу
- вгружаем табсы
- нас кикают
- звук есть, мигания в трее и попапа нет

если табсы были активны с самого начала (стартовали вместе с мирандой), то всё ок
если перезайти в конфу после такого кика, то всё будет дальше ок

**Comment by dartraiden** [comment]
- [ ] StdMsg:
 
- стартуем с табсами
- в жаббере настроен автовход в конфу, мы сидим в конфе
- выгружаем табсы, в бой вступает StdMsg
- нас кикают или хайлайтят
- звук есть, попап есть, а в трее вместо мигающей иконки пустое пространство

**Comment by dartraiden** [comment]
- [ ] TabSRMM:

Never mute: иногда (не всегда воспроизводится), когда, например, были включены попапы, звуки и мигания для киков, а ты их выключил и после этого тебя кикнули, то мигание и попап всё равно есть
после рестарта баг уходит

**Comment by dartraiden** [comment]
StdMsg:

- [ ]  не работают звуки, мигания и попапы на status changes (либо я не понимаю, что это такое... когда кто-то меняет себе статус (away, dnd, etc) или роль (становится модератором) в конфе - тишина, когда мне меняют роль - тоже тишина)
- [ ]  если в истории чата есть несколько смен топика, то эти события подгружаются при входе в чат и вызывают несколько попапов... может, не стоит реагировать на прошлые события?

**Comment by georgehazan** [comment]
> StdMsg:
> 
> * [ ]   не работают звуки, мигания и попапы на status changes (либо я не понимаю, что это такое... когда кто-то меняет себе статус (away, dnd, etc) или роль (становится модератором) в конфе - тишина, когда мне меняют роль - тоже тишина)

это когда меняется статус онлайн - оффлайн
