### ISSUE TITLE
Discord: не скрываются чаты

### ISSUE THREAD

**Issue by sk8rthug** [miranda-ng/miranda-ng#2580]
Чаты дискорда не скрываются. Иду в настройки - игнорирование, убираю галки с чатов, перевожу протокол в оффлайн, включаю снова, и чаты возвращаются в список.

https://forum.miranda-ng.org/index.php?topic=6039.msg27652#msg27652

**Comment by dartraiden** [comment]
Fixed in https://github.com/miranda-ng/miranda-ng/commit/6876dbedc149f78702fee4ea60194a3b12eee2c7
