### ISSUE TITLE
Скрытые контакты обрабатываются ядром как неизвестные контакты

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2582]
- выставляем в настройках мирандовского игнора игнор авторизации от неизвестных контактов
- нам пишет некто (в Jabber), он появляется в клисте как временный контакт и в настройках игнора получает автоматом метку "игнор авторизации"
- добавляем его в ростер (авторизуем), он перестаёт быть неизвестным и метки игнора у него уже нет
- скрываем его (клист -> удалить -> только скрыть)

результат: контакт в ростере (мы его не удалили, а просто скрыли из клиста), но у него появилась метка "игнор авторизации", словно он неизвестный

**Comment by georgehazan** [comment]
нет. "неизвестным" контактом считается контакт, у которого стоит "Clist/NotOnList"
когда приходит авторизация хз от кого, делается временный контакт именно такого формата
