### ISSUE TITLE
Jabber: улучшение удобства работ со списками участников

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2584]
1) В окнах voice list, moderator list, member list и прочих есть внизу фильтр. Туда можно ввести текст, нажать рядом пиктограмму и фильтр применится.

Предлагаю сделать, чтобы фильтр применялся и по нажатию Enter (сейчас окно тупо закрывается)

2) Нужна возможность сортировки в этих окнах по алфавиту, потому что список участников в конфе велик, окно маленькое, просматривать запаришься

**Comment by georgehazan** [comment]
а еще список можно ресайзить...

**Comment by dartraiden** [comment]
<img width="245" alt="Miranda64_PuAknb2yhn" src="https://user-images.githubusercontent.com/5046855/99587508-3ef8fd00-29fa-11eb-8a6c-910f5f61e595.png">

**Comment by dartraiden** [comment]
Желательно крестик помещать в начало списка (потому что список длинный, и когда заходишь туда, чтобы зобанить очередного спамера, мотать вниз западло).
