### ISSUE TITLE
Остатки старого OpenSSL, с которыми нужно что-то делать

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2587]
- [ ] https://github.com/miranda-ng/miranda-ng/blob/be76bd932b0a8dada123311ab9a056a31fe8140f/libs/libmosquitto/libmosquitto.vcxproj#L33

возможно, вообще эту библиотеку пора убрать?

- [ ] https://github.com/miranda-ng/miranda-ng/blob/be76bd932b0a8dada123311ab9a056a31fe8140f/tools/installer_ng_stable/MirandaNG.iss#L71

не забыть убрать из инсталлятора стабли

- [ ] https://github.com/miranda-ng/miranda-ng/blob/be76bd932b0a8dada123311ab9a056a31fe8140f/src/mir_app/CMakeLists.txt#L10

не понял, какая из двух новых либ должна быть вместо libeay32

**Comment by georgehazan** [comment]
как стаблю потащим на новый openssl, оно применится автоматом
