### ISSUE TITLE
Инсталлятор: обрезается текст при нестандартном DPI в Windows (150%)

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2596]
![Untitled](https://user-images.githubusercontent.com/5046855/95689542-22f38600-0c1a-11eb-9bd1-8d3773b4fbb1.png)

**Comment by georgehazan** [comment]
ничего не знаю об инсталляторах :) 
попробуй покопать сам?

**Comment by dartraiden** [comment]
Проблема всё ещё жива

**Comment by dartraiden** [comment]
Todo:
1) проверить, сработал ли фикс
2) проверить, можно ли вообще удалить значение ширины
3) если фикс сработал, откатить InnoSetup на 5 версию, чтобы инсталляторы продолжали работать в XP
