### ISSUE TITLE
Quick filtering in contact list stopped working

### ISSUE THREAD

**Issue by ns6000** [miranda-ng/miranda-ng#2597]
### Expected behavior
Setting focus on contact list by clicking on it and started writing used to filter displayed contacts (online AND offline, all protocols and groups).

### Actual behavior
I'm writing and filtering isn't happening.

### Does it work in stable version?
Sorry, i've updated today, but i don't know from which version.
My version is 0.95.13 alpha build #23416 (4bb9749b21).

**Comment by dartraiden** [comment]
Post [version info](https://wiki.miranda-ng.org/index.php?title=Version_information), please

**Comment by georgehazan** [comment]
1. install Clist_Modern
2, turn on this option
https://i.imgur.com/9FE1vwe.png

**Comment by ns6000** [comment]
> Post [version info](https://wiki.miranda-ng.org/index.php?title=Version_information), please

[spoiler=VersionInfo][quote]CPU: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz [Intel64 Family 6 Model 58 Stepping 9] [DEP Enabled] [4 CPUs]
Installed RAM: 16327 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 19041)
Internet Explorer: 9.11.19041.0 (build 919041)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | Czech/Czech
Free disk space on Miranda partition: 59993 MBytes

Miranda NG Version: 0.95.13 alpha build #23417 (1aea5e768a) x64
Build time: 17 Oct 2020 2:03:28
Profile: C:\Apps\MirandaNG\Profiles\NonSuch\NonSuch.dat
Profile size: 138412032 Bytes
Profile creation date: 27 Aug 2016 15:31:58
Language pack: No language pack installed
Service Mode: No

[b]Active Plugins (21):[/b]
¤ AVS.dll v.[b]0.98.1.2[/b] [17 Oct 2020 21:24:40] - Avatar service 
¤ Clist_nicer.dll v.[b]0.9.3.2[/b] [12 Sep 2020 2:03:28] - Clist nicer 
¤ Cln_skinedit.dll v.[b]0.0.0.4[/b] [12 Sep 2020 2:03:24] - Skin editor for Clist nicer 
¤ CrashDumper.dll v.[b]0.1.0.4[/b] [17 Oct 2020 21:25:08] - Crash dumper 
¤ Db_autobackups.dll v.[b]0.1.0.4[/b] [17 Oct 2020 2:03:42] - Db autobackuper 
¤ DbChecker.dll v.[b]0.95.13.1[/b] [17 Oct 2020 2:05:10] - Database checker 
¤ Dbx_mdbx.dll v.[b]0.95.9.1[/b] [17 Oct 2020 2:05:12] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.[b]0.95.8.1[/b] [12 Sep 2020 2:03:26] - Miranda NG mmap database driver 
¤ Discord.dll v.[b]0.6.2.5[/b] [15 Oct 2020 19:47:38] - Discord protocol 
¤ Dummy.dll v.[b]0.2.0.0[/b] [17 Oct 2020 2:04:34] - Dummy protocol 
¤ historypp.dll v.[b]1.5.1.5[/b] [15 Oct 2020 19:48:26] - History++ 
¤ ICQ.dll v.[b]0.95.12.1[/b] [15 Oct 2020 19:47:48] - ICQ-WIM protocol 
¤ Import.dll v.[b]0.95.11.1[/b] [17 Oct 2020 2:03:56] - Import contacts and messages 
¤ Jabber.dll v.[b]0.95.11.1[/b] [15 Oct 2020 19:46:46] - Jabber protocol 
¤ New_GPG.dll v.[b]0.2.0.4[/b] [15 Oct 2020 19:47:46] - GPG 
¤ PluginUpdater.dll v.[b]0.2.0.9[/b] [15 Oct 2020 19:46:54] - Plugin updater 
¤ QuickSearch.dll v.[b]1.4.2.0[/b] [16 Oct 2020 14:38:56] - Quick Search 
¤ Scriver.dll v.[b]3.0.2.2[/b] [15 Oct 2020 19:46:20] - Scriver 
¤ SmileyAdd.dll v.[b]0.3.2.1[/b] [12 Sep 2020 2:03:42] - SmileyAdd 
¤ StatusManager.dll v.[b]1.2.0.6[/b] [12 Sep 2020 2:04:30] - Status manager 
¤ TopToolBar.dll v.[b]0.8.0.5[/b] [12 Sep 2020 2:03:46] - TopToolBar 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
Discord                  1 - Enabled 0 - Disabled  Loaded
ICQ                      1 - Enabled 0 - Disabled  Loaded
JABBER                   1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 HistoryPP_icons.dll [15 Oct 2020 19:48:16]
 Proto_AIM.dll [7 Jul 2016 20:50:30]
 Proto_Discord.dll [15 Oct 2020 19:48:16]
 Proto_Dummy.dll [17 Oct 2020 2:05:18]
 Proto_Facebook.dll [8 Sep 2019 2:04:50]
 Proto_GG.dll [13 Dec 2018 16:06:30]
 proto_GmailMNotifier.dll [16 Dec 2010 3:28:18]
 Proto_ICQ.dll [15 Oct 2020 19:48:16]
 Proto_IRC.dll [13 Dec 2018 16:06:30]
 Proto_Jabber.dll [15 Oct 2020 19:48:16]
 Proto_MetaContacts.dll [17 Oct 2020 2:05:18]
 Proto_MRA.dll [15 Oct 2020 19:48:16]
 Proto_MSN.dll [8 Sep 2019 2:04:50]
 Proto_Yahoo.dll [7 Jul 2016 20:50:31]
 raro-hexicubes.dll [7 Jun 2001 9:28:54]
 TabSRMM_icons.dll [15 Oct 2020 19:48:16]
 Toolbar_icons.dll [17 Oct 2020 21:26:32]
 xStatus_Jabber.dll [15 Oct 2020 19:48:16]
[/quote][/spoiler]

**Comment by dartraiden** [comment]
Database Editor → [CLC] → FilterSearch = 1

**Comment by ns6000** [comment]
ok, so i got rid of clist_nicer and switched to clist_modern, which helped, thanks

**Comment by georgehazan** [comment]
@ns6000 if you toggled that option, you can freely return back to clist_nicer :) 
it will work there too

**Comment by ns6000** [comment]
> @ns6000 if you toggled that option, you can freely return back to clist_nicer :)
> it will work there too

ha! really, nice! thank you!
