### ISSUE TITLE
Inaccessible plugin Dbx_mmap in new versions of Miranda NG

### ISSUE THREAD

**Issue by MichalSuchy** [miranda-ng/miranda-ng#2598]
Hello. I use Miranda NG 0.95.12 orr sometimes I try alpha versions of 0.9.13 and is not there accessible plugin Dbx_mmap. Can you open up this plugin, please? I had to create new profile with plugin Dbx_mdbx, there is fewer options for contacts in context menu and does not work there Seenplugin. Thanks, Michal.

**Comment by dartraiden** [comment]
Dbx_mmap is read only database driver for migrating old profiles to dbx_mdbx.
