### ISSUE TITLE
Em-LAN: binds to localhost

### ISSUE THREAD

**Issue by Deadooshka** [miranda-ng/miranda-ng#2599]
Иногда при загрузке выбирает не ту подсеть. Обычно при загрузке системы (Windows 7) с Мирандой в автозагрузке. В настройке `Network / E-mage LAN protocol` отображается только 127.0.0.1, при этом сохранённые контакты из подсети 192.168.* становятся вне сети. Сообщение отослать невозможно. Поиск контактов по IP работает.

**Comment by georgehazan** [comment]
эм... а эта сеть при загрузке вообще доступна? 
плагин просто перебирает доступные сетки средствами самой винды

**Comment by Deadooshka** [comment]
В этом то и проблема, что локальная сеть может быть недоступной на момент загрузки, и появиться при уже загруженной Миранде.

**Comment by georgehazan** [comment]
@Deadooshka 
тогда без шансов. свой внешний адрес Миранда определяет при старте, так что спасет только перезапуск.
в теории можно забиндить это на 0.0.0.0, чтобы плагин слушал на всех интерфейсах

**Comment by georgehazan** [comment]
@Deadooshka ну в смысле если надо сделать опцию биндить миранду на все интерфейсы, то отпиши, а нет, так просто закрой задачу

**Comment by Deadooshka** [comment]
Опция то никому не помешает в любом случае. Через `Keep status` тоже не работает.

**Comment by georgehazan** [comment]
> Через `Keep status` тоже не работает.

Оно и не должно работать через Keep status, потому что адрес сети вычисляется при загрузке плагина в самом начале
