### ISSUE TITLE
IRC logfile does not open

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#260]
**Reported by nosyfred on 1 Feb 2014 10:45 UTC**
Button 'Open Logfile (Ctrl-H)' does not open the chat logfile.

In last update logfile write path internally was changed from:
'%USERPROFILE%\Application Data\Miranda NG\default\Logs\Chat'
to:
'%USERPROFILE%\Application Data\Miranda NG\default\Logs\Chat\IRC'?

 [quote][size=1]CPU: Intel(R) Pentium(R) Dual CPU T3200 @ 2.00GHz [x86 Family 6 Model 15 Stepping 13] [DEP Enabled] [2 CPUs]
Installed RAM: 3006 MBytes
Operating System: Microsoft Windows XP Professional Service Pack 3 (build 2600)
Internet Explorer: 6.0.2900.5512 (build 62900.5512)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System?)) : German/German? | German/German?
Free disk space on Miranda partition: 1870 MBytes

Miranda NG Version: 0.94.9 final build #8010
Build time: 2 Feb 2014 14:48:30
Profile: C:\Dokumente und Einstellungen\Administrator\Anwendungsdaten\Miranda NG\default\default.dat
Profile size: 262144 Bytes
Profile creation date: 2 Feb 2014 16:31:35
Language pack: German (DE) [0407]
Service Mode: No

[b]Active Plugins (6):b

    AdvaImg?.dll v.[b]0.11.0.1b [2 Feb 2014 14:42:28] - Miranda image services
    CrashDumper.dll v.[b]0.0.4.22b [2 Feb 2014 14:45:10] - Crash dumper
    Dbx_mmap.dll v.[b]0.11.0.2b [2 Feb 2014 14:41:24] - Miranda NG mmap database driver
    Facebook.dll v.[b]0.2.2.1b [2 Feb 2014 14:43:38] - Facebook RM
    IRC.dll v.[b]0.11.0.2b [2 Feb 2014 14:41:52] - IRC protocol
    MirOTR.dll v.[b]0.11.0.4b [2 Feb 2014 14:48:46] - Miranda OTR

[b]Unloadable Plugins (1):b

    DbChecker?.dll v.[b]0.0.0.0b [2 Feb 2014 14:45:22] - <unknown>

[b]Protocols and Accounts:b

Facebook 1 - Enabled 0 - Disabled Loaded
IRC 2 - Enabled 0 - Disabled Loaded

[b]Icon Packs:b

    Proto_Facebook.dll [2 Feb 2014 14:43:54]
    Proto_IRC.dll [2 Feb 2014 14:43:58]
[/quote]

**Comment by georgehazan** [comment]
**Modified by nosyfred on 2 Feb 2014 17:37 UTC**

**Comment by georgehazan** [comment]
**Modified by watcher on 2 Feb 2014 17:40 UTC**

**Comment by dartraiden** [comment]
Fixed in 9fc484fbcb154f376584ad8814b816d4a733eb9e
Bug in StdChat, not IRC.
