### ISSUE TITLE
Seenplugin is not working

### ISSUE THREAD

**Issue by MichalSuchy** [miranda-ng/miranda-ng#2600]
Hello. I Installed Seenplugin to Miranda NG 0.95.12 or to some alpha version 0.95.13 and plugin is not working. When I enter to context menu on some contact, there is not date and time of last login of contact or Never seen. I have checked Last seen menu item and Show icon. Will plugin works in other versions of Miranda NG? Thanks, Michal.

**Comment by dartraiden** [comment]
Post [version info](https://wiki.miranda-ng.org/index.php?title=Version_information), please

**Comment by MichalSuchy** [comment]
[spoiler=VersionInfo][quote]CPU: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz [Intel64 Family 6 Model 158 Stepping 10] [DEP Enabled] [8 CPUs]
Installed RAM: 7928 MBytes
Microsoft Windows 10 , 64-bit (build 19041)
Internet Explorer: 9.11.19041.0 (build 919041)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Czech/Czech | Czech/Czech
Free disk space on Miranda partition: 48989 MBytes

Miranda NG Version: 0.95.12 build #23274 (5915066615) [running inside WOW64]
Build time: 7 Oct 2020 11:24:32
Profile: C:\Users\Michal Suchý\AppData\Roaming\Miranda NG\Michal\Michal.dat
Profile size: 2097152 Bytes
Profile creation date: 17 Oct 2020 23:01:36
Language pack: Czech (CZ) [0405]
Service Mode: No

[b]Active Plugins (10):[/b]
¤ AVS.dll v.[b]0.98.1.2[/b] [7 Oct 2020 11:24:36] - Avatar service 
¤ Clist_blind.dll v.[b]0.8.1.1[/b] [7 Oct 2020 11:25:22] - BClist 
¤ CrashDumper.dll v.[b]0.1.0.4[/b] [7 Oct 2020 11:25:08] - Crash dumper 
¤ DbChecker.dll v.[b]0.95.13.1[/b] [7 Oct 2020 11:25:56] - Database checker 
¤ Dbx_mdbx.dll v.[b]0.95.9.1[/b] [7 Oct 2020 11:26:14] - Miranda NG MDBX database driver 
¤ Dummy.dll v.[b]0.2.0.0[/b] [7 Oct 2020 11:25:36] - Dummy protocol 
¤ Facebook.dll v.[b]0.1.0.8[/b] [7 Oct 2020 11:25:58] - Facebook 
¤ Import.dll v.[b]0.95.11.1[/b] [7 Oct 2020 11:24:54] - Import contacts and messages 
¤ PluginUpdater.dll v.[b]0.2.0.9[/b] [7 Oct 2020 11:25:14] - Plugin updater 
¤ SeenPlugin.dll v.[b]5.0.5.5[/b] [7 Oct 2020 11:24:52] - Last seen 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
Facebook                 1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 Proto_Dummy.dll [7 Oct 2020 11:26:24]
 Proto_Facebook.dll [7 Oct 2020 11:26:24]
 Proto_MetaContacts.dll [7 Oct 2020 11:26:24]
[/quote][/spoiler]

**Comment by georgehazan** [comment]
@MichalSuchy mmm... perhaps you haven't marked an account in Options - Contacts - Last Seen?
could you drop a screenshot of those options?

**Comment by MichalSuchy** [comment]
I Am sending Screen. If is Facebook deactivated in tree list, how can I activate, when I am blind and I use Jaws or Nvda, please? Thanks, Michal.

**Comment by georgehazan** [comment]
> how can I activate, when I am blind and I use Jaws or Nvda, please?

@MichalSuchy as usual: enter the dialog, then click Tab until you run into that list, then use Space bar to toggle options, then press Ok

**Comment by MichalSuchy** [comment]
It's weird, but it doesn't work. I tryed several times to press space on account Facebook and press ok. I have at each contact in context menu these items:
Message
Convert to metacontact
Add to existing metacontact
Move to group
Import
User details
Delete

**Comment by georgehazan** [comment]
@MichalSuchy 
yes, you're right. that's a manually written old control... shame :) gotta fix it asap

**Comment by georgehazan** [comment]
@MichalSuchy pressing Space fixed in the development build, you can try now

**Comment by MichalSuchy** [comment]
Thanks, it is working.
