### ISSUE TITLE
История переписки не соответствует выбранной вкладке и сообщение отправляется пользователю история переписки которого отображается

### ISSUE THREAD

**Issue by ziceptor** [miranda-ng/miranda-ng#2602]
Переслали мне сообщение.

"Кстати, после обновления миранды поймал интересный глюк.  было открыто 4 или5 вкладок в течении нескольких дней. в итоге конгда выбираешь нужную из открытых и начинаешь набирать сообщение иногда история переписки не соответствует выбранной тобой вкладке и соответственно отправляется пользователю историю переписки с которым ты видешь."

Обновление было неделю назад. По версии не скажу, так как клиент сегодня получил новое обновление.

TabSRMM (TabSRMM internal log)
Hystory++
x32

**Comment by georgehazan** [comment]
и как это повторить?

**Comment by ziceptor** [comment]
Большой вопрос... по крайней мере на код более пристально посмотреть :)

**Comment by georgehazan** [comment]
За два месяца не столкнулся с этим. Давай сделаем точный рецепт повторения, и тогда переоткроем всё это
