### ISSUE TITLE
New GPG - Name and mail adress 

### ISSUE THREAD

**Issue by OmlineEditor** [miranda-ng/miranda-ng#2603]
i am using plugin New GPG (New_GPG.dll, author: sss)
creating a key, I need to specify a name and mail.

1) when specifying a name there is a problem, my name is 4 letters, but you need to specify a minimum of 5, other palagins do not have such restrictions.

2) I have my own hosting XMPP and the name for the account looks like this: name@localhost
but the program says it is invalid mail. This mailbox name is used to retrieve account information for encryption. I ask you to remove the restrictions and make it possible to use arbitrary types of mailbox.

**Comment by georgehazan** [comment]
@OmlineEditor есть мнение, что это ограничение утилиты GPG, которой вы пользуетесь.
Что можно сделать прямо сейчас: сгенерировать лог команд плагина New_GPG и проверить, что соответствующие ошибки выдаются не плагином, а GPG.exe. Если это так, то мы ничем не сможем помочь.

С ходу ограничений в теле самого плагина я не нашел.

**Comment by sss123next** [comment]
https://github.com/miranda-ng/miranda-ng/blob/f4adc7543085e13c526e166f5960ebe00a859c5d/plugins/New_GPG/src/ui.cpp#L223

не помню уже почему такое ограничение сделано.
но учитывая '2 I have my own hosting XMPP and the name for the account looks like this: name@localhost' - кейсерверы не примут такой ключ скорее всего, что касается xmpp и xep-0027, ни там ни там нет жесткого требования на соответствия ключа имени и/или адресу акаунта, тоесть можно вписать в эти поля что угодно.
