### ISSUE TITLE
First launch with new profile: missing clist window

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2605]
after https://github.com/miranda-ng/miranda-ng/commit/a949c9f2b090435ca63de525ee2cd1a79073f08a

<img width="137" alt="mstsc_mj3ARdwWVs" src="https://user-images.githubusercontent.com/5046855/97108453-aca55800-16de-11eb-9b4f-81f0e975143d.png">

**Comment by georgehazan** [comment]
это глюк с базе, откатили

**Comment by dartraiden** [comment]
Баг появился снова.
