### ISSUE TITLE
TabSRMM: ability to disable image pasting

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2609]
Если в буфере обмена находится растровое изображение (например, после нажатия принтскрина или после того, как в Paint выделить некую область картинки и нажать Ctrl+C), то Ctrl+V в области ввода табсов = отправка этого содержимого буфера как файлтрансфер.

Пользователь просит отключить это поведение или, хотя бы, сделать его отключаемым.

**Comment by georgehazan** [comment]
отказано. пользователю написано
