### ISSUE TITLE
Фрейм "status bar" странно себя ведет

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2612]
У меня статус-бар выглядит так

<img width="122" alt="Miranda64_kB9W2Xqusn" src="https://user-images.githubusercontent.com/5046855/98426347-881b8980-20a9-11eb-8cc3-e124b28056d4.png">

Если я сделаю Main menu - Frames - Status bar - Postition - Down, то статус-бар опустится к нижнему краю окна, как и полагается. Но если я сделаю Main menu - Frames - Status bar - Postition - Up после этого, то статус-бар так и остаётся у нижнего края и я не нахожу способа вернуть его в изначальную позицию.

Вероятно, это баг. Профиль дам по запросу.

**Comment by georgehazan** [comment]
Насколько я понимаю, фрейм статус-бара имеет флажок "Прижать книзу" (Frame.align = alBottom), отчего он наверх двигаться не может физически, да и пропускать кого-то мимо себя вниз тоже.
