### ISSUE TITLE
Кнопка фильтра событий ведёт себя по-разному в разных плагинах сообщений

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2617]
TabSRMM:
когда фильтр выключен, на кнопке красный крестик
при нажатии - вылезает настройка фильтра и фильтр включается (крестик пропадает)

StdMsg:
когда фильтр выключен - крестика нет
при нажатии вылезает настройка фильтра и фильтр включается (появляется крестик)

Scriver:
аналогично stdmsg

Таким образом, надо определиться, крестик означает включённый фильтр или выключенный?
И в соответствии с ответом поправить тот или иной плагин.
Потому что сейчас либо неверно в табсах, либо в двух оставшихся плагинах.

**Comment by georgehazan** [comment]
>Таким образом, надо определиться, крестик означает включённый фильтр или выключенный?

50/50. Например, у попапов в меню иконка обозначает текущее состояние, а группировка - состояние, в которое кнопка переводит
