### ISSUE TITLE
Intermittent disconnects on Jabber

### ISSUE THREAD

**Issue by thany** [miranda-ng/miranda-ng#2620]
### Expected behavior
No disconnects?

### Actual behavior
Jabber disconnects at random times.

### Does it work in stable version?
It has worked perfectly until 3 or 4 days ago and an update got installed. I didn't catch *what* exactly got installed, but `pu_stub.exe` wanted to run itself, updating "silently". I only know which version I'm on *now*, of course.

### Steps to reproduce that behavior
* Connect to Jabber
* Wait

### Relevant bit of log
This is the moment the connection is lost:
```
[00:45:42 18F8] [JABBER_1] Netlib_Recv() failed, error=10060
[00:45:42 18F8] [JABBER_1] recvResult = 0
[00:45:42 18F8] [JABBER_1] m_iDesiredStatus reset to (40072,40072) => 40071
[00:45:42 18F8] [JABBER_1] leaving worker thread
[00:45:42 18F8] [JABBER_1] Thread ended: type=0 server='my-server-here'
[00:45:42 18F8] [JABBER_1] (00000000005648C0:1596) Connection closed internal
[00:45:42 18F8] [JABBER_1] (00000000005648C0:4294967295) Connection closed
[00:45:42 18F8] [JABBER_1] Exiting ServerThread
```

### Version information
```
CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz [Intel64 Family 6 Model 94 Stepping 3] [DEP Enabled] [8 CPUs]
Installed RAM: 32699 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 19042)
Internet Explorer: 9.11.19041.0 (build 919041)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | Dutch/Dutch
Free disk space on Miranda partition: 103178 MBytes

Miranda NG Version: 0.95.12.1 build #23277 (98607f126c) x64
Build time: 18 Nov 2020 22:30:20
Profile: C:\Users\my-real-name-here\AppData\Roaming\Miranda NG\Thanatos\Thanatos.dat
Profile size: 12582912 Bytes
Profile creation date: 28 Mar 2020 16:43:25
Language pack: No language pack installed
Service Mode: No

Active Plugins (9):
¤ AutoRun.dll v.0.1.0.1 [5 Aug 2020 13:01:16] - AutoRun 
¤ AVS.dll v.0.98.1.2 [5 Aug 2020 13:00:38] - Avatar service 
¤ CrashDumper.dll v.0.1.0.4 [5 Aug 2020 13:01:06] - Crash dumper 
¤ Db_autobackups.dll v.0.1.0.4 [18 Nov 2020 22:30:32] - Db autobackuper 
¤ DbChecker.dll v.0.95.13.1 [18 Nov 2020 22:31:54] - Database checker 
¤ Dbx_mdbx.dll v.0.95.9.1 [18 Nov 2020 22:31:54] - Miranda NG MDBX database driver 
¤ Dummy.dll v.0.2.0.0 [18 Nov 2020 22:31:24] - Dummy protocol 
¤ Jabber.dll v.0.95.11.1 [18 Nov 2020 22:30:56] - Jabber protocol 
¤ PluginUpdater.dll v.0.2.0.9 [18 Nov 2020 22:30:56] - Plugin updater 

Protocols and Accounts:
-------------------------------------------------------------------------------
JABBER                   1 - Enabled 0 - Disabled  Loaded
MSN                      0 - Enabled 1 - Disabled  Loaded

Icon Packs:
-------------------------------------------------------------------------------
 Proto_Dummy.dll [18 Nov 2020 22:32:08]
 Proto_Jabber.dll [18 Nov 2020 22:32:06]
 Proto_MetaContacts.dll [18 Nov 2020 22:32:08]
 xStatus_Jabber.dll [18 Nov 2020 22:32:06]
```

**Comment by georgehazan** [comment]
>C:\>net helpmsg 10060
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

No, this problem (timeout) doesn't depend on Miranda anyhow

**Comment by dartraiden** [comment]
Install StatusManager plugin and set up KeepStatus function.

**Comment by thany** [comment]
@georgehazan Sorry, mate, but why did you close this issue?? It worked fine before a few days ago, and now it doesn;t. Isn't that a bug? And if not, could you elaborate on how/why it isn't a bug and how to get it fixed? Mind you, Miranda is the *only* program on my computer that can't keep a stable outbound connection.

@dartraiden That's a good workaround, I suppose, but shouldn't we want the problem actually fixed? I've never needed such a plugin, and now suddenly I do.

**Comment by georgehazan** [comment]
@thany because there're many cases when a simple wait fails with error 10060, for example, packet loss
also that could be a problem with firewall or antivirus, but Miranda does not affect all these things

**Comment by thany** [comment]
Okay, but that still doesn't help me, neither to solve the problem, nor to even diagnose it. What is it waiting for? How long does it wait?

Fact of the matter is that it worked fine before "some" version, don't remember, and now it's broken. And Miranda is the only software thing that changed since then. You're blaming external factors, I'm saying anything external hasn't changed.

So, how about Miranda just tries it again?

**Comment by dartraiden** [comment]
You can find previous version's binaries in /Miranda dir/Plugin Updates/
If you can confirm that the problem is not present in the previous version (it might just be a coincidence that the problems started after the update - "Post hoc, ergo propter hoc"), we need a full log

**Comment by thany** [comment]
Alright, but before that, I *still* don't know:

1. What is it waiting for that times out?
2. How long does it wait until it times out.

It's important to know these, in order to get closer to the root cause.

**Comment by georgehazan** [comment]
1. XMPP socket is eternally in the wait state - it does nothing but waiting
2. Forever, until server disconnects you with a timeout error

You can check if the Keepalive option is enabled in Options - Network - <JabberAcc>
