### ISSUE TITLE
Обновление с Miranda IM до NG приводит к непонятному каналу обновлений

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2623]
1) берём IM
2) обновляем через IM Updater
3) на первой итерации получаем 0.94.9 stable, смотрим канал обновлений в настройках апдейтера - stable
4) обновляемся далее, получаем 0.95.12.1 stable, смотрим канал обновлений в настройках апдейтера

ожидается: стабильный
в реальности имеем: кастомный
почему оно сползает со стабильного на кастомный?

![image](https://user-images.githubusercontent.com/5046855/99920903-be0e6e00-2d37-11eb-86dc-8292f52fbd8f.png)

**Comment by georgehazan** [comment]
потому что апдейтер IM рассчитан на попадание в XP, где нет https, а обновляться надо

**Comment by dartraiden** [comment]
Так 0.94.9 ещё обновляется нормально (там, видать, забит урл с http), а в актуальном апдейтере есть галка Use HTTPS, которая снимается автоматом в XP

**Comment by georgehazan** [comment]
это настройка, которая пишется в базу. 
нет, и в 0.94.9 она забивается в явном виде в профиль, чтобы работало всегда
