### ISSUE TITLE
Dbx_mdbx: cannot open or create profile with UNC path

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2627]
https://forum.miranda-ng.org/index.php?topic=6133.msg27941#msg27941

**Comment by erthink** [comment]
А как себя ведет `mdbx_chk` если задавать UNC path?

**Comment by derzai** [comment]
Вывод команды mdbx_chk.exe \\Server\F\Private\user\ICQ\user\user.dat
mdbx_chk v0.9.1-18-g1d31ebdc1c (2020-10-08T01:50:18+03:00, T-5cbfdfdc65b62937f7fc927e55cec6304bf04f7c)
Running for \\Server\F\Private\user\ICQ\user\user.dat in 'read-only' mode...
 ! mdbx_env_open failed, error 50 ╥ръющ чряЁюё эх яюффхЁцштрхЄё .

при монтировании сетевой шары (UNC путь) как диск, миранда так же говорит что профиль в неизвестном формате, то же самое происходит если сделать символическую ссылку на сетевую шару, этот же профиль прекрасно открывается локально. Новый профиль в этих случаях так же создается, но база имеет нулевой размер и при создании профиля появляется ошибка - "не могу создать профиль user.dat, ошибка 1".

**Comment by erthink** [comment]
`50` – это ошибка `ERROR_NOT_SUPPORTED` (The network request is not supported).
Какая у вас версия ОС на локальном компе и на сервере?

**Comment by derzai** [comment]
клиентская windows 7x64, XPx86 сервер windows server 2016, везде последние обновления, чуть позже на 10ке еще проверю

**Comment by erthink** [comment]
> клиентская windows 7x64, XPx86 сервер windows server 2016, везде последние обновления, чуть позже на 10ке еще проверю

@derzai, с большой вероятностью дело конечно в XP-ке и 7-ке, т.е. в том что не поддерживаются какие-то функции, используемые libmdbx для проверки размещения БД на сетевых дисках.
Вроде-бы это чинили и немного проверяли, но не для сетевых дисков.

У меня пока нет виртуалок чтобы по-отлаживать, поставил качаться (а потом еще нужно будет с инструментами/отладчиком разобраться).
@dartraiden, если у кого-то в команде есть отладочный комплект, то просьба помочь - нужно выяснить где именно внутри `mdbx_env_open()` возникает `ERROR_NOT_SUPPORTED`.

**Comment by derzai** [comment]
Проверил на 10x64 ошибки те же что и на windows 7 и на XP

**Comment by erthink** [comment]
> Проверил на 10x64 ошибки те же что и на windows 7 и на XP

О, это даже лучше. Постараюсь сегодня воспроизвести и пофиксить.

**Comment by erthink** [comment]
@derzai, в libmdbx баг поправлен.
Появление исправления в Миранде зависит от @georgehazan, видимо после того как мы с ним разберемся с https://github.com/erthink/libmdbx/issues/139.

**Comment by derzai** [comment]
отлично, будем ждать

**Comment by erthink** [comment]
Исправлено в текущем master-е

**Comment by georgehazan** [comment]
билд выехал на сервер, можно обновляться
