### ISSUE TITLE
Миранда зависает при попытке проверить базу

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2628]
Есть база mdbx. При попытке её проверить из запущенной Миранды - висяк.
Из менеджера профилей проверяется нормально и после этого больше не виснет.

Базу дам по запросу.

**Comment by apollo2k4** [comment]
> Есть база mdbx. При попытке её проверить из запущенной Миранды - висяк.
Имею аналогичную проблему.

**Comment by erthink** [comment]
Если я правильно понимаю, то сейчас Миранда почти постоянно держит открытую пишущую транзакцию и дело именно в этом.

**Comment by georgehazan** [comment]
@dartraiden @apollo2k4 стеки сделайте, хотя бы главного потока

**Comment by erthink** [comment]
Судя по показанным мне стекам:
- некий поток запускает пишущую транзакцию и эта транзакция работает (не закоммичена и не прервана).
- другой поток пытается запустить еще одну транзакцию и останавливается внутри libmdbx на ожидании завершения уже работающей транзакции (ибо пишущие транзакции строго сериализуются).
- третий поток пытается обратиться к БД и останавливается на критической секции внутри mir_core, которой защищено всё взаимодействие с БД и которая удерживается вторым потоком.

Соответственно, проблема в том, что вместо завершения или переиспользования уже запущенной пишущей транзакции делает попытка запустить еще одну = получается deadlock.

**Comment by georgehazan** [comment]
@erthink нет, мы обсуждали код, который не раздавался никому. В репозитарии принципиально другая схема
