### ISSUE TITLE
WhatsApp hangs on connection loss

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#263]
**Reported by watcher on 4 Feb 2014 10:48 UTC**
WhatsApp hangs on connection loss and consumes 98% of processor time.

**Comment by georgehazan** [comment]
**Comment by watcher on 4 Feb 2014 10:49 UTC**
stack from process explorer:

0	ntkrnlpa.exe!KeSetEvent+0x2a1
1	ntkrnlpa.exe!KeDelayExecutionThread+0x5cc
2	ntkrnlpa.exe!KeWaitForSingleObject+0x393
3	ntkrnlpa.exe!KiDeliverApc+0x664
4	halmacpi.dll!KfRaiseIrql+0xcb
5	halmacpi.dll!KeRaiseIrqlToSynchLevel+0x8f
6	halmacpi.dll!HalEndSystemInterrupt+0x67
7	halmacpi.dll!HalInitializeProcessor+0xae8
8	ntdll.dll!RtlGetCurrentProcessorNumberEx+0x6e3
9	ntdll.dll!TpDisassociateCallback+0x1c6
10	whatsapp.dll!WAConnection::sendPing+0x2ea
11	whatsapp.dll!WhatsAppProto::sentinelLoop+0xa7
12	mir_core.dll!forkthreadex_r+0x5a
13	MSVCR120.dll!_get_flsindex+0x6f
14	MSVCR120.dll!_get_flsindex+0x53
15	kernel32.dll!BaseThreadInitThunk+0x12
16	ntdll.dll!RtlInitializeExceptionChain+0xef
17	ntdll.dll!RtlInitializeExceptionChain+0xc2

**Comment by georgehazan** [comment]
**Modified by mataes on 27 May 2014 08:07 UTC**

**Comment by georgehazan** [comment]
**Comment by wishmaster on 5 Feb 2015 21:33 UTC**
Is it still a problem?

**Comment by dartraiden** [comment]
WhatsApp is deprecated.
