### ISSUE TITLE
Clist blind: странная работа быстрого поиска

### ISSUE THREAD

**Issue by jawhien** [miranda-ng/miranda-ng#2630]
### Expected behavior
1. Быстрый поиск должен осуществляться со следующей позиции за системным фокусом, т.е. если фокус установлен на контакте 18, то быстрый поиск осуществляется начиная с контакта 19, и только если это невозможно, переходит к началу списка и начинает уже с него.
2. Быстрый поиск не должен бесконечно ожидать ввода последующих символов, это делает поиск по первой букве невозможным. При наличии большого числа контактов, это может доставлять большие неудобства.
3. Быстрый поиск должен осуществлять поиск по нескольким буквам, если они вводятся последовательно с минимальным интервалом, но в соответствии со всем выше указанным.

 ### Actual behavior
Сейчас быстрый поиск работает очень странно, больше похоже на фильтр, а не на быстрый поиск, хоть и нет никаких признаков фильтрации. Найти нужный контакт с помощью него стало весьма неудобным.

### Does it work in stable version?
нет.

### Steps to reproduce that behavior
Открыть список контактов Clist Blind и воспользоваться быстрым поиском.

**Comment by georgehazan** [comment]
вынес ее в настройки, теперь переключение режима фильтра доступно в Options - Contact list - Common, Search works as filter

**Comment by jawhien** [comment]
@georgehazan
Пробовал и включать и отключать, но разницы так и не замечаю, быстрый поиск работает одинаково.

**Comment by georgehazan** [comment]
Если включить, то в списке контактов будут только контакты с этой подстрокой в имени. Если выключить, то оно будет прыгать на первый подходящий контакт, не изменяя список контактов

**Comment by jawhien** [comment]
@georgehazan
Что так, что так курсор просто прыгает на первый подходящий контакт в списке, что в принципе не соответствует быстрому поиску и очень неудобно. нужно к примеру найти контакт в середине списка, и либо писать целиком его приходится, либо листать весь список, а если контактов несколько десятков? а если много к тому же с похожими именами? более того большинство обычных пользователей вообще не будут понимать что происходит и почему быстрый поиск не работает. Мне кажется лучше уже вернуть старое поведение быстрого поиска, когда флаг снят, для clist blind по крайней мере.

**Comment by georgehazan** [comment]
@jawhien 
там есть нюанс, что именно clist_blind вообще не является традиционным мирандовским списком контактов, иначе бы он не читался вслух читалками, а является обычным виндовым контролом типа Listbox, а вот как сделать так, чтобы Listbox куда-то позиционировался - это отдельный вопрос вообще...

**Comment by jawhien** [comment]
@georgehazan
Я это знаю, только не понимаю куда и зачем он должен позиционироваться.

Я лишь говорю о том, чтобы одним из вариантов настройки вернуть поведение которое было раньше, например в версии 0.95.12 alpha build #22687, оно соответствует тому, как ведёт себя обычный ListBox.

**Comment by lion891** [comment]
@georgehazan Дополню обращение Jawhien. Если есть такая возможность, было бы здорово вернуть поиск, который был в более ранних версиях, так как работа нынешнего поиска совсем непонятна. В смысле, непонятно вообще, ищется что-то или нет...
И второй вопрос уже от меня. Сколько я не видел версий программы, при включении групп, т.е. снятие флага отключить группы, поиск как таковой перестаёт работать вообще. Вот эту штуку можно как-то поправить?
Заранее большое спасибо за ответ! :)

**Comment by georgehazan** [comment]
@lion891 парадокс в том, что в работе поиска уже многие годы никаких изменений не было. Что было - это неправильное умолчание режима работы с поиском, из-за чего криво работали настройки на чистом профиле. После изменения умолчания у всех поехал поиск, после чего настройку пришлось вынести в Common, чтобы каждый мог вернуться на предыдущий вариант.

> Сколько я не видел версий программы, при включении групп, т.е. снятие флага отключить группы, поиск как таковой перестаёт работать вообще. Вот эту штуку можно как-то поправить?

Поиск не зависит от режима групп, но, как я указывал выше, именно в clist_blind всё это накладывается на функционал винды, так что плющить его может как угодно.

**Comment by georgehazan** [comment]
@jawhien @lion891 я нашел коммит 8-месячной давности, который если откатить, получается в чистом виде виндовый поиск по первой букве, и да, он не работает в группах (только в первом слое).

**Comment by georgehazan** [comment]
ok, я слегка подправил работу списка, задействовав мирандовское ядро вместо виндового стандартного поиска. Теперь, если отключить режим фильтрации, то должно работать практически, как написано

**Comment by lion891** [comment]
@georgehazan Тогда здорово было бы вернуть хотя бы вариант, чтобы поиск работал как раньше, пусть даже в первом слое. Потому что когда у человека много контактов и все они начинаются мало того, что на одну букву, так ещё и на одно и то же слово, имя к примеру, новый поиск создаёт ну очень большие проблемы в навигации по контактам...

**Comment by jawhien** [comment]
@georgehazan 
Спасибо! Буду ждать обновления, чтобы попробовать.

**Comment by georgehazan** [comment]
@jawhien так уже можно

**Comment by jawhien** [comment]
@georgehazan 
В целом выходит так, что при отключённых группах работает только стандартный поиск, а при включённых только фильтр, что в принципе и правильно. Правда с фильтром есть один момент: при наличии групп, начинающихся с первой буквы контакта, вместо контакта находится только группа. Например: если есть группа "VKontakte"  контакт начинающийся на букву V не находится и тд.

**Comment by georgehazan** [comment]
@jawhien это при включенном фильтре в опциях или выключенном?

**Comment by jawhien** [comment]
@georgehazan в обоих случаях. Флаг "Search works as filter" ничего не изменяет, но я  пробовал и при отмеченном и не отмеченном состоянии.

**Comment by georgehazan** [comment]
> Правда с фильтром есть один момент: при наличии групп, начинающихся с первой буквы контакта, вместо контакта находится только группа. Например: если есть группа "VKontakte" контакт начинающийся на букву V не находится и тд.

Не подтверждаю. Включил группы, выключил фильтр, есть группа с именем Miranda и пользователь Mick - стоит набрать M, i, c, как курсор послушно прыгает на пользователя

**Comment by jawhien** [comment]
@georgehazan 
Да, спасибо, не знаю в чём было дело, но после создания чистого профиля эта проблема исчезла. :)

**Comment by jawhien** [comment]
@lion891 
> 
> 
> И второй вопрос уже от меня. Сколько я не видел версий программы, при включении групп, т.е. снятие флага отключить группы, поиск как таковой перестаёт работать вообще. Вот эту штуку можно как-то поправить?

Стандартный поиск работал бы в группах, если можно было бы отключить автоматические отступы для контактов. Я только сейчас понял ((. Для тех кто пользуется подглядом они визуально отделяют контакты от групп, те кто пользуется только скринридером их не замечает, только если на дисплее брайля возможно.

**Comment by jawhien** [comment]
@georgehazan
Нельзя ли сделать какой-нибудь флаг, который бы переключал между режимами поиска: стандартным поиском windows и фильтром? После последнего обновления стандартный поиск при отключённых группах работать перестал.

**Comment by georgehazan** [comment]
@jawhien я откатил то изменение, которое было, потому что с ним вообще чудеса начали происходить (типа двойного удаления контактов). Надо понять, как сделать так, чтобы оно не глючило, а мирандовский поиск работал

**Comment by Henry-White** [comment]
В сейбл-версии (Miranda NG Version: 0.95.12.1 build #23282 (276cb6f447) x64) быстрый поиск по контактам работает только если включить "показать отключенных".
При этом, чек-бокс "Поиск по списку контактов с фильтрацией режимов" отключен.

**Comment by georgehazan** [comment]
@Henry-White @jawhien 
ok, плагин переписан на другой тип контрола, изменений много и они сильные.
на текущий момент проверено, что:
- работает навигация + схлопывание/расхлопывание групп;
- работает Enter, F2, Del;
- поиск работает нормально как в режиме фильтра, так и в режиме поиска (по многим буквам)

Проверяйте, любые замечания welcome

**Comment by jawhien** [comment]
@georgehazan 
Спасибо! Теперь заработал и фильтр.
Есть только один момент, когда фильтр отключён, поиск осуществляется с начала имени контакта, а когда фильтрация включена, идёт по совпадению символов в самом названии. Нельзя ли сделать чтобы и при включённом фильтре поиск осуществлялся по совпадению с начала названия? Мне кажется это было бы логичнее.
В остальном проблем  каких-то не заметил. :)

**Comment by georgehazan** [comment]
@jawhien 
фильтр изначально и задумывался как подстрока, собственно оно так везде и работает (в поиске в браузере, например)

> В остальном проблем каких-то не заметил. :)

вот и славно

**Comment by jawhien** [comment]
@georgehazan 
да как-то не особо удобно выходит, ищешь одно, а находит всё что угодно.

**Comment by georgehazan** [comment]
оно изначально так и планировалось, я не виноват 
есть локатор, он работает с начала, а все фильтры во всех программах ищут подстроку. жизнь так устроена :)

**Comment by jawhien** [comment]
@georgehazan 
Да тут посути и фильтра то нету, если разобраться, это не поиск, нет поля ввода, что вводится вообще не очень ясно порой и что уже введено тоже непонятно, нигде не отображается и проверить невозможно, так что такая работа просто сбивает с толку, да и попросту неудобна.

**Comment by jawhien** [comment]
@georgehazan @georgehazan 
А вообще почему нельзя сделать выбор, искать подстроку или только совпадения с начала строки?
