### ISSUE TITLE
NewEventNotify: Crash on initsect.cpp (55): _RTC_Terminate

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#2631]
Crashlog: http://coraksoft1.narod.ru/temp/miranda/Miranda-ng-crash-NewEventNotify-RTC_Terminate_20200516.7z
"
Likely cause of the crash plugin: NewEventNotify

Exception: Access Violation at address 05CA1CE4. Reading from address FFFFFFFF.

Stack Trace:
---------------------------------------------------------------
05CA1CE4 (neweventnotify 05CA0000): d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\rtc\initsect.cpp (55): _RTC_Terminate
127D2ED4 (mir_app 12780000): w:\miranda-build\src\mir_app\src\pluginopts.cpp (234): LoadPluginDynamically
12789F64 (mir_app 12780000): w:\miranda-build\src\mir_app\src\pluginopts.cpp (325): CPluginOptDlg::OnInitDialog
1292B968 (mir_core 12920000): w:\miranda-build\src\mir_core\src\cdlgbase.cpp (211): CDlgBase::DlgProc
1292B25B (mir_core 12920000): w:\miranda-build\src\mir_core\src\cdlgbase.cpp (396): CDlgBase::GlobalDlgProc
7E368734 (USER32 7E360000): (filename not available) (0): GetDC
7E37413C (USER32 7E360000): (filename not available) (0): DefDlgProcW
7E373B30 (USER32 7E360000): (filename not available) (0): EnumDisplaySettingsA
7E373D5C (USER32 7E360000): (filename not available) (0): DefDlgProcW
7E368734 (USER32 7E360000): (filename not available) (0): GetDC
7E368816 (USER32 7E360000): (filename not available) (0): GetDC
7E37927B (USER32 7E360000): (filename not available) (0): GetParent
7E37651A (USER32 7E360000): (filename not available) (0): IsDlgButtonChecked
7E37683E (USER32 7E360000): (filename not available) (0): CreateDialogIndirectParamAorW
7E36EA84 (USER32 7E360000): (filename not available) (0): CreateDialogParamW
1292B522 (mir_core 12920000): w:\miranda-build\src\mir_core\src\cdlgbase.cpp (105): CDlgBase::Create
1292B1FF (mir_core 12920000): w:\miranda-build\src\mir_core\src\cdlgbase.cpp (385): CDlgBase::GlobalDlgProc
01D290F8 ((module-name not available) 00000000): (filename not available) (0): (function-name not available)
0300BA00 ((module-name not available) 00000000): (filename not available) (0): (function-name not available)
"

**Comment by georgehazan** [comment]
Левый плагин NewEventNotify, который крашится при попытке загрузиться в миранду
