### ISSUE TITLE
Core: crash on "stdio.h (1408): _vsnprintf" and "netlib_log.cpp (385): Netlib_Log"

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#2632]
Crashlog: http://coraksoft1.narod.ru/temp/miranda/Miranda-ng-crash-20200517-vsnprintf-Netlib_Logf.7z

"Likely cause of the crash plugin: Miranda NG

Exception: Access Violation at address 1003FC07. Reading from address 00740073.

Stack Trace:
---------------------------------------------------------------
1003FC07 (ucrtbase 10000000): (filename not available) (0): strnlen
100350AF (ucrtbase 10000000): (filename not available) (0): o_wcsncpy_s
1003577C (ucrtbase 10000000): (filename not available) (0): o_wcsncpy_s
10036DBF (ucrtbase 10000000): (filename not available) (0): _stdio_common_vsprintf
129233C5 (mir_core 12920000): c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\stdio.h (1408): _vsnprintf
1293003D (mir_core 12920000): w:\miranda-build\src\mir_core\src\memory.cpp (225): mir_vsnprintf
127CB860 (mir_app 12780000): w:\miranda-build\src\mir_app\src\netlib_log.cpp (385): Netlib_Logf
127CBAF9 (mir_app 12780000): w:\miranda-build\src\mir_app\src\netlib_openconn.cpp (650): my_connectIPv6
127CC816 (mir_app 12780000): w:\miranda-build\src\mir_app\src\netlib_openconn.cpp (689): NetlibDoConnect
127CCBC5 (mir_app 12780000): w:\miranda-build\src\mir_app\src\netlib_openconn.cpp (802): NetlibReconnect
127C905C (mir_app 12780000): w:\miranda-build\src\mir_app\src\netlib_http.cpp (424): Netlib_SendHttpRequest
127CA1DD (mir_app 12780000): w:\miranda-build\src\mir_app\src\netlib_http.cpp (862): Netlib_HttpTransaction
7C802455 (kernel32 7C800000): (filename not available) (0): Sleep"

**Comment by georgehazan** [comment]
нужно поновее, чем от 17.05 - там код поменялся полностью, вместе с номерами строк
