### ISSUE TITLE
Проблема выбора начертаний кастомного шрифта

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2633]
Предварительные действия:
- ставим кастомный шрифт в винду (PT Mono, PT Mono Bold)
- выставляем его в настройках Миранды, например в качестве шрифта для области ввода табсов

<img width="482" alt="Miranda64_D5wTrS4Ak4" src="https://user-images.githubusercontent.com/5046855/100525218-ebdc3280-31cf-11eb-9556-b12d6413ddc1.png">

Баг:
снова открываем настройку шрифта области ввода табсов
ожидаемый результат: возможность выбрать жирный, курсив и т.д.
наблюдаемый результат: доступно только обычное начертание (regular)

<img width="324" alt="Miranda64_NmVFINaNp5" src="https://user-images.githubusercontent.com/5046855/100525279-5c834f00-31d0-11eb-8d01-cf36daf69492.png">

если тыкнуть мышкой в любой шрифт, идущий в комплекте с виндой (допустим, следующий по списку - Roman), а потом обратно на PT Mono, то появляются все начертания

<img width="324" alt="Miranda64_ryxWKxVpma" src="https://user-images.githubusercontent.com/5046855/100525288-8a689380-31d0-11eb-80c5-d73fe29cae6a.png">

**Comment by georgehazan** [comment]
это стандартный виндовый диалог выбора шрифта, Миранда тут не при делах
