### ISSUE TITLE
check gpg.exe and gnupg_home in New_GPG

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#265]
**Reported by mng on 8 Feb 2014 11:37 UTC**
If user has wrong path to GPG.exe binary and/or to GnuPG home:

1) On start of miranda-ng there is a check so New_GPG alerts user it will not work
2) If you move these dirs in the process of miranda-ng

in both cases you'll get miranda-ng hanging if you try to communicate with GPG-enabled contact.

From user-perspective there should be some handler giving more info on the error, of course in first case it alerts user, but still breaks the miranda-ng.

**Comment by georgehazan** [comment]
**Modified by sss_sss on 8 Feb 2014 11:38 UTC**

**Comment by georgehazan** [comment]
**Modified by mataes on 27 May 2014 08:07 UTC**

**Comment by sss123next** [comment]
ancient bug.
reopen if still exist.
