### ISSUE TITLE
Message notification is not working properly

### ISSUE THREAD

**Issue by bol-van** [miranda-ng/miranda-ng#2651]
### Expected behavior
Должен мигать конверт в трее при наличии хотя бы одного непрочитанного сообщения
так было в ранних версиях

### Actual behavior
Если окно чата не открыто, конверт мигает
если открыто, окно не сфокусировано, то при последующем входящем сообщении 5 раз моргнет и затихает. при следующих нет вообще никакой реакции.
ты отлучился, пришел, и не видишь, что тебе написали. очень неудобно

### Does it work in stable version?
не работает в 0.95.12.1 и альфе 

### Steps to reproduce that behavior
отключить табы, tabsrm плагин
писать себе с другого аккаунта личные сообщения

**Comment by bol-van** [comment]
Если сделать так, то мигает неограниченно долго

msgdialog.cpp, stdmsg.dll
```
case WM_TIMER:
		if (wParam == TIMERID_FLASHWND) {
			FixTabIcons();
			if (!g_dat.nFlashMax || m_nFlash < 2 * g_dat.nFlashMax)
			{
				//FlashWindow(m_pOwner->GetHwnd(), TRUE);
				FLASHWINFO fw;
				fw.cbSize = sizeof(fw);
				fw.hwnd = m_pOwner->GetHwnd();
				fw.dwFlags = FLASHW_ALL;
				fw.uCount = 0x7FFFFFFF;
				fw.dwTimeout = TIMEOUT_FLASHWND;
				::FlashWindowEx(&fw);
			}
			m_nFlash++;
			break;
		}

```

**Comment by georgehazan** [comment]
![image](https://user-images.githubusercontent.com/4628541/104205617-a8681b80-543f-11eb-9fda-2c7a87eb700f.png)
куда стрелочка смотрит, надо поставить 0 - будет моргать всегда

**Comment by dartraiden** [comment]
Добавил уточение про 0 в текст.
