### ISSUE TITLE
После смены разрядности Миранды через настройки апдейтера, следующий запуск оказывается неудачным

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2652]
- имеем Миранду некоей разрядности (32 или 64)
- в настройках апдейтера выбираем "Перейти на <другую разрядность>"
- апдейтер закачивает бинарники выбранной разрядности, перезапускает Миранду
- но, т.к. мы перестали рантайм VS2017 паковать вместе с ядром, рантайм остаётся прежней разрядности

результат: запуск невозможен, вылезает окно "рантайма нет, скачайте его с интернета сами - с сайта MS"
причем, даже если юзер вручную скачает с сайта MS инсталлятор рантайма и поставит в систему, Миранда в первую очередь пытается использовать "неправильный" рантайм из Libs и всё равно фейлит

нужно вернуть эти несчастные пару мегабайт обратно в архив с ядром

**Comment by georgehazan** [comment]
а я начинаю думать, что изначальное решение со статической компиляцией Miranda32.exe и динамической загрузкой рантайма было правильным... и вообще тогда класть этот вонючий рантайм в дистрибутив не надо (может быть только в инсталлер, путем выкачивания из интернета в момент инсталляции)

**Comment by dartraiden** [comment]
А что делать с портативной версией, которая в разы популярнее инсталлятора?
