### ISSUE TITLE
TabSRMM: настройка цвета выделенного текста применяется только к никлисту, но не к логу групчатов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2654]
<img width="482" alt="Miranda64_4pu5jdys4W" src="https://user-images.githubusercontent.com/5046855/102724361-1711f780-4320-11eb-9581-3778efe1bb54.png">

делаем этот цвет любым... ну хоть зеленым и идём в групчат (с родным журналом табсов)

результат: в никлисте цвет выделенного текста стал зеленым, а вот в логе эта настройка проигнорировалась

<img width="390" alt="Miranda64_rHnZS6tcwL" src="https://user-images.githubusercontent.com/5046855/102724412-65bf9180-4320-11eb-9a61-6d38c82951e1.png">

**Comment by dartraiden** [comment]
Настройка фона выделенного (на скриншоте соседняя) ведёт себя аналогично (не применяется к логу)

**Comment by dartraiden** [comment]
А у приватов в табсах настроек фона и цвета выделенного текста вообще нет.  Вероятно, стоит их добавить.

**Comment by georgehazan** [comment]
у RTF control вообще нет такого понятия, как цвет фона выделенного текста, он формируется автоматически по виндовой теме

**Comment by dartraiden** [comment]
Тогда следует переименовать Selected text -> Selected nicklist text, а Selection background -> Nicklist selection background

**Comment by georgehazan** [comment]
там вообще нет ни одной настройки, которая применяется к логу вроде
