### ISSUE TITLE
Редактор меню: невозможно перетащить разделитель так, чтобы он встал между двумя раскрытыми разделами меню

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2656]
![b7cyGjPsO1](https://user-images.githubusercontent.com/5046855/103002338-c678e500-453f-11eb-8cd6-81a0d4e1c407.gif)

на видео я пытаюсь перетащить разделитель так, чтобы он встал между +Database и +VersionInfo
но Миранда не позволяет поместить его между, она норовит засунуть его либо в конец первого подменю, либо в начало второго, т.е. уровнем ниже, чем я хочу

**Comment by dartraiden** [comment]
Есть два обходных пути:
1) свернуть оба раскрытых подмню, тогда разделитель перетащится промеж них
2) убить этот разделитель и создать новый там, где надо (а не таскать имеющийся)

но как-то это всё же слегка костыльно

**Comment by georgehazan** [comment]
Вот так винда работает: отметку при движении вниз можно воткнуть только после верхнего, т.е. во второй уровень
