### ISSUE TITLE
Вынести настройку цвета попапов редактора базы в тонкие настройки

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2658]
<img width="482" alt="Miranda64_TqVOwzfPXP" src="https://user-images.githubusercontent.com/5046855/103037364-ba5f4880-457c-11eb-8f69-32600b6a69cc.png">

Разумно переместить настройку цвета в Customize -> Fonts and colors
И вместе с тем сделать настраиваемым цвет текста попапа (сейчас текст всегда чёрный)

**Comment by georgehazan** [comment]
настройки цвета попапов обычно живут в попапах
