### ISSUE TITLE
Проблемы с кастомизацией значка Mute chat

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2660]
Идём в настройку значков модерна и меняем показанный значок на любой иной

<img width="482" alt="Miranda64_6PJBpstTmV" src="https://user-images.githubusercontent.com/5046855/103142892-d00b7400-471c-11eb-9e4c-5120e48b7033.png">

перезапускаем Миранду для верности и выставляем чату Always mute или Never mute

ожидание: в клисте около чата должен сразу же появиться значок, причём такой, какой мы назначили
реальность: значок появляется лишь после рестарта, причём не кастомизированный, а стандартный

**Comment by georgehazan** [comment]
это не настройка вида значка, это то, как он будет виден в настройках экстра=иконок
