### ISSUE TITLE
Улучшение кастомизации значка Mute chat

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2661]
<img width="482" alt="Miranda64_6PJBpstTmV" src="https://user-images.githubusercontent.com/5046855/103142992-8ae84180-471e-11eb-8876-0a3f366f9784.png">

<img width="482" alt="Miranda64_9cYvYCcfw8" src="https://user-images.githubusercontent.com/5046855/103142989-87ed5100-471e-11eb-8c4b-0f9b5970b37f.png">

Как видно, есть два места, где настраивается этот значок:
- первый скрин это экстраиконка в клисте
- второй скрин это значок подменю в меню контакта

Может, их объединить? Какой смысл кому-то ставить разные значки? Я слабо представляю пользователя, которому на экстразначок нужен один значок, а на меню, которое управляет этой фичей нужен иной значок.

**Comment by georgehazan** [comment]
> Может, их объединить?

Не получится. Второй набор иконок генерируется genmenu просто по мере регистраций пунктов меню, где иконка берется из иколиба
