### ISSUE TITLE
Clist_modern: crash on "Chat_GetGroup" when moved group to the other subgroups

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#2662]
CrashLog: http://coraksoft1.narod.ru/temp/miranda/miranda-crash-20201226-Clist_modern-Chat_GetGroup.7z

Likely cause of the crash plugin: Miranda NG

Exception: Access Violation at address 12B9BA1A. Reading from address 00000001.

Stack Trace:
---------------------------------------------------------------
12B9BA1A (mir_app 12B80000): (filename not available) (0): Chat_GetGroup
163F12A6 (Clist_modern 163E0000): (filename not available) (0): (function-name not available)

**Comment by georgehazan** [comment]
а как это повторить?

**Comment by dartraiden** [comment]
Я потаскал группы в подгруппы и подгруппы в группы в разных сочетаниях - не упало.

**Comment by Corak667** [comment]
Ставил чистую миранду с нуля, чуток пытался перемещать категории-группы, просто хотел поместить некоторые категории в приоритете  и вложениии и субвложениях, но они мало того, что налезали одна на другую и подменяли-скрывали, так потом еще этот краш вылез когда разок переместил.

**Comment by georgehazan** [comment]
там просто по этому адресу другая функция совсем :( 
давай попробуем повторить это, я посмотрю более свежий краш
