### ISSUE TITLE
Редактор меню: сделать возможность скрытия сепараторов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2663]
После последнего коммита ситуация следующая:
- кастомные пункты меню можно скрыть (сняв с них галку), а можно удалить (кнопка Delete)
- сепараторы же снятием галки удаляются с концами

получается как-то неконсистентно

предлагаю сепараторы приравнять к кастомным менюхам, сделав им такое же поведение (галка - скрывать, Delete - удалять)

**Comment by georgehazan** [comment]
Тут проблема в том, что сепаратор не является самостоятельным элементом, как строка меню, соотв для него не определены понятия "скрыть" или "удалить".  Сепаратор - это просто разница в 100000 между position двух соседних строк меню, отсортированных по position, если его снять, то позиции пунктов меню пересчитываются без учета этой разницы, соотв. всякий след сепаратора пропадает
