### ISSUE TITLE
TabSRMM: дублируется настройка

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2666]
<img width="482" alt="Miranda64_bMWKLcC9Yi" src="https://user-images.githubusercontent.com/5046855/103418374-63bac580-4b9f-11eb-8167-2f0fabc132ec.png">

**Comment by georgehazan** [comment]
Они не дублируются, там же написано :) 
`{ LPGENW("* Symbols (incoming)"), RGB(50, 50, 50), L"Webdings", SYMBOL_CHARSET, 0, -12 },
{ LPGENW("* Symbols (outgoing)"), RGB(50, 50, 50), L"Webdings", SYMBOL_CHARSET, 0, -12 },`

**Comment by dartraiden** [comment]
Проблема в том, что этого не видно, там же Webdings
