### ISSUE TITLE
No typing notifications on Facebook

### ISSUE THREAD

**Issue by winman3000** [miranda-ng/miranda-ng#2668]
### Expected behavior
Miranda NG should notify the user when someone types a message.

### Actual behavior
Currently, no notification is displayed in the status bar or a sound is played when a contact types a message.

### Does it work in stable version?
I don't know. It worked a few days ago.

### Steps to reproduce that behavior
1. write a contact.
1. Wait for the contact to answer.

**Comment by georgehazan** [comment]
okay, it seems that some clients simply don't send them
