### ISSUE TITLE
Discord: crash on "gateway.cpp (137): CDiscordProto::GatewayThreadWorker" and "m_string.inl (552): CMStringT<char,ChTraitsCRT<char> >::CMStringT<char,ChTraitsCRT<char> >

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#2682]
<
Likely cause of the crash plugin: Discord protocol

Exception: Access Violation at address 00A7D3E0. Reading from address 0DBDF000.

Stack Trace:
---------------------------------------------------------------
00A7D3E0 (VCRUNTIME140 00A70000): (filename not available) (0): memcpy
12D231D4 (mir_core 12D20000): w:\miranda-build\include\m_string.inl (552): CMStringT<char,ChTraitsCRT<char> >::CMStringT<char,ChTraitsCRT<char> >
169C5778 (Discord 169C0000): w:\miranda-build\protocols\discord\src\gateway.cpp (137): CDiscordProto::GatewayThreadWorker
7C80A0C7 (kernel32 7C800000): (filename not available) (0): SetEvent
00150000 ((module-name not available) 00000000): (filename not available) (0): (function-name not available)
000360F7 ((module-name not available) 00000000): (filename not available) (0): (function-name not available)
>

**Comment by Corak667** [comment]
Crashlog+dump: http://coraksoft1.narod.ru/temp/miranda/MirandaNg-20210107-CDiscordProto-GatewayThreadWorker.7z

**Comment by georgehazan** [comment]
если повторится в этом месте, нужен нетворк лог дискорда + ядро
