### ISSUE TITLE
Popup plus: crash on "popup_wnd2.cpp (1246): WindowThread" and "threads.cpp (122): forkthread_r"

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#2683]
CrashLog; http://coraksoft1.narod.ru/temp/miranda/mirandang-20210101-popup_wnd2.cpp-WindowThread.7z

' Likely cause of the crash plugin: Popup plus

Exception: Access Violation at address 746FD59B. Reading from address 0000055C.

Stack Trace:
---------------------------------------------------------------
746FD59B (MSCTF 746E0000): (filename not available) (0): TF_CreateCicLoadMutex
746E8B2E (MSCTF 746E0000): (filename not available) (0): TF_CreateLangBarItemMgr
746FD8E3 (MSCTF 746E0000): (filename not available) (0): TF_CreateCicLoadMutex
746FDD0B (MSCTF 746E0000): (filename not available) (0): TF_CreateCicLoadMutex
747003AE (MSCTF 746E0000): (filename not available) (0): TF_CheckThreadInputIdle
7E368734 (USER32 7E360000): (filename not available) (0): GetDC
7E368816 (USER32 7E360000): (filename not available) (0): GetDC
7E3689CD (USER32 7E360000): (filename not available) (0): GetWindowLongW
7E368A10 (USER32 7E360000): (filename not available) (0): DispatchMessageW
057208F3 (PopupPlus 05710000): w:\miranda-build\plugins\popup\src\popup_wnd2.cpp (1246): WindowThread
12D33AEA (mir_core 12D20000): w:\miranda-build\src\mir_core\src\threads.cpp (122): forkthread_r
7C80B729 (kernel32 7C800000): (filename not available) (0): GetModuleFileNameA
'

**Comment by georgehazan** [comment]
это какая-то левая хрень у тебя в потрохах винды не справилась с созданием потока
