### ISSUE TITLE
Facebook: crash on "mqtt.cpp (74): MqttMessage::readStr" and "mqtt.cpp (130): FacebookProto::MqttParse"

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#2685]
CrashLog: http://coraksoft1.narod.ru/temp/miranda/mir-20201208-fb-MqttMessage-readStr.7z

Likely cause of the crash plugin: Facebook

Exception: Access Violation at address 16A643D2. Reading from address 00000000.

Stack Trace:
---------------------------------------------------------------
16A643D2 (Facebook 16A60000): w:\miranda-build\protocols\facebook\src\mqtt.cpp (74): MqttMessage::readStr
16A642B1 (Facebook 16A60000): w:\miranda-build\protocols\facebook\src\mqtt.cpp (130): FacebookProto::MqttParse
16A6787C (Facebook 16A60000): w:\miranda-build\protocols\facebook\src\server.cpp (404): FacebookProto::ServerThread
12D13A91 (mir_core 12D00000): (filename not available) (0): mir_forkthreadex

**Comment by georgehazan** [comment]
памяти надо добавить. когда память не выделяется, Миранда падает
