### ISSUE TITLE
TabSRMM+SkypeWeb: в инфопанель  стал добавляться префикс 8: после обновления от 6 января

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2688]
https://forum.miranda-ng.org/index.php?topic=4705.msg28170#msg28170

https://forum.miranda-ng.org/index.php?topic=4705.msg28191#msg28191

поскольку до обновления этого не было, это регрессия

**Comment by georgehazan** [comment]
- либо не надо показывать SkypeID на экране
- либо не удивляться наличию 8: в префиксе.

**Comment by dartraiden** [comment]
Надо что-то сделать с инфопанелью в табсах, хотя и очень не хочется.

**Comment by georgehazan** [comment]
а ничего с ней не сделать, она фиксированная
