### ISSUE TITLE
Scriver: падение при попытке зайти в настройки

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2697]
Втянул все настройки из mdbx в sqlite, поставил Scriver, поставил NeN. Запускаю Миранду, открываю настройки, жму Message sessions (настройки скривера) и молча падает без крашлога.

В студии:

`Вызвано исключение по адресу 0x00007FF9B913F8E0 (user32.dll) в Miranda64.exe: 0xC0000005: нарушение прав доступа при записи по адресу 0x0000000000050FE8.`

виртуалка готова, запущу по требованию

**Comment by georgehazan** [comment]
а стек-то есть?
