### ISSUE TITLE
Scriver + NewStory = Реверсивный скрол.

### ISSUE THREAD

**Issue by apollo2k4** [miranda-ng/miranda-ng#2706]
Если в Scriver использовать NewStory как журнал, то скролл прокрутки инвертирован, нажимая вниз прокрутка идёт вверх, наживая вверх прокручивает вниз.

**Comment by georgehazan** [comment]
что конкретно ты имеешь в виду? прокрутку клавиатурой, мышкой или скроллбаром? у меня пока всё ok

**Comment by dartraiden** [comment]
у меня тоже ок, прокручивал колесом мыши

возможно, будет быстрее стереть из профиля учётки и запулить сюда

**Comment by apollo2k4** [comment]
Мышей по стрелкам на скроле нажимаю.

**Comment by dartraiden** [comment]
Да, кнопки прокрутки (выше и ниже скроллбара) инверсированы.

**Comment by apollo2k4** [comment]
duplicate #2392
