### ISSUE TITLE
Scriver: контейнер не мигает

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2715]
Собственно сабж. Значки на вкладках мигают, а контейнер нет.

**Comment by georgehazan** [comment]
ну тут вопрос только в том, мигал ли он раньше
если поведение плагина осталось прежним, то и бог с ним

**Comment by dartraiden** [comment]
Не мигал и раньше.

**Comment by georgehazan** [comment]
прекрасно мигает контейнер и так. чяднт?

**Comment by georgehazan** [comment]
когда контейнер в фокусе, ни один из плагинов не мигает. если контейнер не в фокусе, он мигает
