### ISSUE TITLE
[Question] About a entry in solution files of this project

### ISSUE THREAD

**Issue by TobiasSekan** [miranda-ng/miranda-ng#2718]
Hello,

I currently working on a extension for vscode to easier work with Visual Studio solution files (*.sln)
https://github.com/TobiasSekan/SolutionExtension

And I have seen that you have a special entry in the solution files of this project.
like https://github.com/miranda-ng/miranda-ng/blob/master/bin15/mir_full.sln

```
	GlobalSection(DPCodeReviewSolutionGUID) = preSolution
		DPCodeReviewSolutionGUID = {00000000-0000-0000-0000-000000000000}
	EndGlobalSection
```

Can you explain to me what this is or what this is needed for?
Or is this for a Visual Studio extension?

best regards

**Comment by georgehazan** [comment]
that's a shit left by Visual Studio Code Review feature, you can simply ignore it

**Comment by TobiasSekan** [comment]
Thanks for the answer 👍
