### ISSUE TITLE
XEP-0384: OMEMO Encryption 0.3.0

### ISSUE THREAD

**Issue by Neustradamus** [miranda-ng/miranda-ng#2719]
Can you add the XEP-0384: OMEMO Encryption 0.3.0 support?

I have seen that it is only the 0.2.0 that it is supported:
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://conversations.im/omemo/xep-omemo.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.3.0.html

Thanks in advance.

Source:
- https://github.com/miranda-ng/miranda-ng/issues/2283#issuecomment-775628810

**Comment by sss123next** [comment]
4.2 - must work without any changes.

**Comment by sss123next** [comment]
4.3 done.

**Comment by sss123next** [comment]
i do not see any other changes, please test it.

**Comment by Neustradamus** [comment]
@sss123next: Thanks.

All details in "Appendix H: Revision History"

1/ Are you sure that "4.2" has not needed change?
- `<item>` -> `<item id='current'>`

2/ Ok for "4.3" change.

3/ Have you looked "10"?
- `<xs:attribute name="id" type="integer"/>` -> `<xs:attribute name="signedPreKeyId" type="integer"/>`
- `<xs:attribute name="id" type="integer" use="required"/>` -> `<xs:attribute name="preKeyId" type="integer" use="required"/>`

**Comment by sss123next** [comment]
1. we do not check attrs for this node, i do not see any reason to check it.
3. as i understand it's just corrected description, but xml dump from another client will be helpful, just to be sure

**Comment by sss123next** [comment]
unfortunately it's a bit harder than it should be to get xml logs...,
1. conversations does not provide any technical details fro end-user, to obtain something it's necessary to setup rebote debugger for android.
2. dino looks like trying to mimic conversation, especially in this part, does not provide any tech data and debugging facilities, does not provide xml logging
3. gajim currently does not work on my system for some reason.
4. psi - i probably can compile omemo plugin for psi, but it will require some time and investigation, looks like it depends on some  (still) exotic crypto libraries

so, it will be very helpful if someone will provide xml dumps of current omemo implementations, it will be fastest way.
alternatively i can look into code, but it may vary how long it will take depending on language and code complicity.

**Comment by Neustradamus** [comment]
Psi 1.5 has a problem of plugins (not up-to-date, look date here: https://github.com/psi-im/plugins/releases), please use directly Psi+ to have up-to-date plugins.
-> XML Console is here.

**Comment by sss123next** [comment]
i'll probably will ask rion directly about omemo in psi.
for now, yesterday changes can be tested, here is a little channce what it might fix incompatibility, but i guess most developers just ignore this attr just like we are, as it have no uses defined.
also xml log from miranda can be posted here in case of problems, and messages from miranda console (i have implemented very detailed log of omemo operations in miranda console (not xml console, miranda console located at network tab, require console plugin if i remember correctly))

**Comment by Neustradamus** [comment]
@Ri0n has not worked on OMEMO plugin, it is @Tehnick.
But you must to really full support OMEMO 0.3.0 instead of 0.2.0.

```
Version 0.3.0 (2018-07-31)
Make examples show items published to the id "current", as per XEP-0060 §12.20. (egp)
Version 0.2.2 (2018-11-03)
Fix a bunch of typos, batch-style. (pep)
Version 0.2.1 (2018-05-21)
Fix attribute names in schema (mb)
Version 0.2 (2017-06-02)
```

4.2 (item) / 4.3 / 10 (xs:attribute):
- https://github.com/miranda-ng/miranda-ng/issues/2719#issuecomment-778699457

**Comment by sss123next** [comment]
https://i.imgur.com/1WBODZO.png  - what am i doing wrong ?

**Comment by sss123next** [comment]
ah, hmm, dino sending it unencrypted, funny

**Comment by sss123next** [comment]
look at #2750

**Comment by sss123next** [comment]
this ticket closed because it's not precise enough, issue not related to any specific version of standard, instead general logic is broken in current code, my latest implementation was xep-0384 v0.3 compatible as you can see in new ticket about this regression.
