### ISSUE TITLE
32-разрядная Миранда не видит драйверы базы, будучи запущенной в 64-разрядном Linux

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2720]
- берем 64-разрядный линукс (убунту, например)
- берем wine-staging
- у 64-разрядной Миранды нет проблем, а вот 32-разрядная при старте не может создать базу, т.к. не видит ни одного драйвера базы (при этом обычные плагины типа Import или DbEditorPP видит)

**Comment by dartraiden** [comment]
@sss123next если будет минутка, посмотри, плиз

**Comment by sss123next** [comment]
если рассудить логически.
1. какой смысл запускать 32битную миранду в 64бит linux/wine ?
2. я так понимаю имеет смысл проверить 32битную миранду в 32бит linux/wine (такое с очень небольшой вероятностью еще может случиться в реальности)

к сожалению на доступных мне сейчас машинах не работает 32битный wine, выяснять почему сейчас нет времени.

**Comment by dartraiden** [comment]
1. Никакого, но если это не исправить, надо будет явно указать в вики, что разрядность должна совпадать с разрядностью дистрибутива
2. В 32-битном линуксе 32-битная Миранда работает нормально

**Comment by georgehazan** [comment]
> 1. Никакого, но если это не исправить, надо будет явно указать в вики, что разрядность должна совпадать с разрядностью дистрибутива

да ради бога, давай так и укажем, в чем проблема
