### ISSUE TITLE
[mdbx] First event of history is missing

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#2721]
### Expected behavior
My history is like it was before

### Actual behavior
First event of almost every chat is missing when exported via msgexport (or for example avatarhistory). Curiously, it is visible in history++ .

### Does it work in stable version?
No

### Steps to reproduce that behavior
Updated to miranda made post these commits:

https://github.com/miranda-ng/miranda-ng/commit/8976d32a2eda47013573c7e32132b19cf2949c15

I think they changed something that prevents the db from being read properly.

**Comment by dartraiden** [comment]
Try to compress the database

**Comment by erthink** [comment]
@georgehazan, на вскидку в https://github.com/miranda-ng/miranda-ng/commit/8976d32a2eda47013573c7e32132b19cf2949c15 там что-то не так с логикой перемещения курсора:
- после установки курсора всегда делается переход next/prev;
- реализация итерирования в обратном порядке выглядит не верной, советую повторить логику из [fpta](https://github.com/erthink/libfpta/blob/master/src/cursor.cxx#L238-L774) (проверенно тестами).

**Comment by LittleVulpix** [comment]
> 
> 
> Try to compress the database

I don't think anything is wrong with the DB. Nonetheless I tried, no difference.
