### ISSUE TITLE
Существующая учётка не активируется при установке соответствующего протокола

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2726]
В базе есть учётка твиттера, но протокол не установлен, учётка выглядит (совершенно справедливо) вот так

![image](https://user-images.githubusercontent.com/5046855/107760690-3be08500-6d3b-11eb-9f0e-b9bf9443b5b8.png)

Ставим протокол, вгружаем и... нету значка протокола ни в учетках, ни в панели статусов (см второй значок справа, там "дырка")
пока не рестартнёшь миранду

<img width="425" alt="mstsc_Gz3TLS7Tv7" src="https://user-images.githubusercontent.com/5046855/107760861-806c2080-6d3b-11eb-972e-8f858100ba5a.png">

**Comment by georgehazan** [comment]
всё активируется на ура, надо только опции открыть после загрузки плагина
