### ISSUE TITLE
NewGPG: не сохраняется ширина колонок

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2727]
![image](https://user-images.githubusercontent.com/5046855/107826414-ec7b7280-6d95-11eb-86e3-59346a1367d1.png)

заголовки колонок нечитаемы, колонки можно расширить мышью, но при переоткрытии окна их ширина сбрасывается к нечитаемо узкой

**Comment by gjf** [comment]
Дополнение: достаточно закрыть окно настроек, а затем открыть опять - ширина колонок опять становится узкой.
