### ISSUE TITLE
New_GPG: implement existing keys detection

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2728]
Psi+ и Gajim сразу увидели установленный GnuPG 2.2.27 в системе и все ключи из его связки.  New_GPG так не умеет.

**Comment by gjf** [comment]
Поправка: умеет. Просто мне нужно было грохнуть всю ветку настроек GPG в базе и при запуске настроить заново.
Но: сразу ругается, что вторая версия и грозится ошибками.
Предлагает поставить английскую локаль - но рекомендация от первой версии, во второй локали организованы в папках иначе.
Выбрать свой ключ стало возможно (хотя русские надписи на кнопках нечитаемы - слишком много букв для узких кнопок). Но в списке по-прежнему отсутствуют ключи собеседников (Psi+ и Gajim эти ключи видит).

**Comment by georgehazan** [comment]
@gjf а он второго клиента вообще на дух не переносит :) 
там поведение полностью непредсказуемо

**Comment by gjf** [comment]
@georgehazan Я понимаю, что обе ветки якобы развиваются одновременно, но первая не обновлялась уже два с половиной года.

> GnuPG 1.4 is the old, single binary version which still support the unsafe PGP-2 keys. This branch has no dependencies on the above listed libraries or the Pinentry. However, it lacks many modern features and will receive only important updates.

У меня на системе стоит вторая версия, все ключи - во второй версии. Первая не понимает формат второй.
То есть мне нужно держать две связки ключей - системную вторую и портативную первую, чтобы Миранда работала с PGP в джаббере? И переносить ключи туда-обратно вручную?

Ребята, ну несмешно же! По сути выходит, что шифрование в джаббере в настоящий момент не реализовано на базе Миранды.

**Comment by georgehazan** [comment]
да там этих шифрований, как грязи - что OMEMO, что OTR. GPG под виндой - это совсем не мейнстрим в силу своей уежищности реализации (запуск бинаря на каждое сообщение)

**Comment by gjf** [comment]
Ога, только ОМЕМО работает только с ОМЕМО самой Миранды (@dartraiden я верно ведь тебя понял?). К сожалению или к счастью, не у всех пользователей джаббера клиент - только Миранда.

**Comment by georgehazan** [comment]
@gjf нет, сейчас OMEMO работает со всеми клиентами, но противоречит стандарту. Если сделать его по стандарту, тогда загнется совместимость

**Comment by gjf** [comment]
Чёт я тогда не понял. То есть он у всех противоречит стандарту? Или как у всех тогда работает? А можно ткнуть носом в подробности?

**Comment by georgehazan** [comment]
@sss123next твой выход

**Comment by gjf** [comment]
Ну просто ситуация выходит такая: GPG старый и корявый, OMEMO нестандартный (?), ну в от OTR по сути все уже отказываются (во всяком случае - на мобильных платформах точно). Ну и всё, "шифрований как грязи" больше не осталось - во всяком случае таких, которые поддерживались бы глобально.

**Comment by georgehazan** [comment]
@gjf я бы для начала попробовал бы OMEMO, а уже потом выносил суждение о его совместимости и нестандартности. Автор утверждает, что последний раз,  когда он туда смотрел, всё работало как положено

**Comment by apollo2k4** [comment]
`Автор утверждает, что последний раз, когда он туда смотрел, всё работало как положено`
Нужно так же уточнить, что автор реализации у OMEMO и New_GPG один и тот же.

**Comment by gjf** [comment]
Ну зато пользователи утверждают обратное: https://github.com/miranda-ng/miranda-ng/issues/529
Лично я только что попробовал общение с Conversations - итог:
![Безымянный](https://user-images.githubusercontent.com/322186/107854174-3c584900-6e2b-11eb-8a54-438a25484a42.png)
Так что всё далеко не так радужно.

**Comment by gjf** [comment]
> автор реализации у OMEMO и New_GPG один и тот же.
... ну это понятно по реализации )))

**Comment by dartraiden** [comment]
Насколько я помню, наш OMEMO совместим только с нами же. Причины пока неизвестны (было предположение про длину вектора, оказалось ложным). Но это надо обсуждать не здесь, а сперва реализовать https://github.com/miranda-ng/miranda-ng/issues/2719 и https://github.com/miranda-ng/miranda-ng/issues/2283, после этого уже смотреть совместимость и курить логи в случае её отсутствия

**Comment by gjf** [comment]
Ну в итоге нашей дискуссии мы пришли к тому, что при обилии вариантов шифрования в протоколе XMPP Миранда не позволяет нормально использовать ни один из них со сторонними клиентами:

- ОТА устарел и не поддерживается ни одним современным мобильным решением
- ОМЕМО не совместим с другими клиентами
- PGP использует старую платформу и фактически не может использоваться на современных системах

Занавес. Тикет можно закрывать как бессмысленный.

**Comment by sss123next** [comment]
нафлудили....

omemo - фуфло
otr - фуфло
pgp (в виде чистого xep-0027) - тоже фуфло, и не очень безопасно (нет pfs)

по реализациям есть проблемы, но у вас тут просто срач получился.

**Comment by sss123next** [comment]
https://hubzilla.dark-alexandr.net/attach/bf0a68d1-6342-434a-985d-15dea4b7c853 (pdf)  - надо что то типа такого делать, но договориться о чем то с xmpp комитетом - проще застрелиться, я уже пытался.

а остальное всё фуфло.

omemo ? key-exchange через pep ? приколисты, не спасибо, я это фуфло делал за деньги, сам не пользуюсь, никому не рекомендую, до текущего стандарта доведу, будет совместимо, но не более, оно всё ранво никогда нигде нормально не будет работать.
