### ISSUE TITLE
ICQ plugin - Cannot unset X-status icon - always hotdog

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#273]
**Reported by jindrapetrik on 28 Feb 2014 19:48 UTC**
My X-status on ICQ protocol is always on. I cannot unset it with selecting "---" item. When I click on that item, I always get Hot dog icon. (I have myself in contact list so I can check it easily, and also other users see me like that)

**Comment by georgehazan** [comment]
**Comment by watcher on 28 Feb 2014 20:26 UTC**
Confirming - i have the same hot dog X-status for my own contact in contact list.

**Comment by dartraiden** [comment]
New protocol doesn't support xStatuses at all.
