### ISSUE TITLE
Facebook: group chat messages not saved in history

### ISSUE THREAD

**Issue by rkwk** [miranda-ng/miranda-ng#2731]
As in the title: chat history is empty for conversations with more than one person.

**Comment by georgehazan** [comment]
of course, they aren't saved, like in any other group chats in Miranda

**Comment by rkwk** [comment]
So couldn't this be fixed? From the user's point of view this doesn't make any sense that conversations with one contact are saved, but those with several contacts are not.

**Comment by dartraiden** [comment]
It cannot be fixed easily
