### ISSUE TITLE
[dbx_sqlite][regression] only the last of unread events is shown when multiple unread events arrive 

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#2734]
### Expected behavior
When someone sends me several messages, I expect to open and see all of them when I click the tray icon notification

### Actual behavior
When someone sends several messages, clicking on the unread notification in tray icon opens conversation where only the latest message they sent is shown. Moreover for each message, the tray icon will keep blinking. Though, if you click on the remaining "notifications", nothing else will be displayed.

### Does it work in stable version?
Nope.

### Steps to reproduce that behavior

Using latest miranda, i.e. a2e28bc1717d59ab8444fb5a1cf2872bcc59e8d8

Set your message lot to display only unread events.

Have someone send you multiple messages while the conversation window with them is closed. Then click on the "new message" tray icon to open the conversation.

Only the last message they sent will be displayed.

This is exactly the same behavior as in #1985 EXCEPT that one showed only the first unread event. Now this one shows only the last. And if you click on all the other "unread blinking tray icon notifications", nothing else is displayed.

**Comment by georgehazan** [comment]
well, I've send some messages through XMPP, and all of them are displayed correctly in tabSRMM
could you specify in details how could I reproduce this problem?

**Comment by LittleVulpix** [comment]
It happens for every single event for me.... (on discord and steam). Reproduction scenario is just to send more than one event.

You have to have setting to show only unread events enabled in your message log.
