### ISSUE TITLE
[dbx_sqlite][db_autobackups] db backups are intermittently created as 0-byte files

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#2735]
### Expected behavior
DB autobackups are created every configured interval

### Actual behavior
Sometimes, created db autobackups are 0-byte sized files...

### Does it work in stable version?
No. It works fine if mdbx is used though.

### Steps to reproduce that behavior
Miranda version: a2e28bc1717d59ab8444fb5a1cf2872bcc59e8d8
 * not sure if this matters, but my sqlite db is 600MB+
 * set up creation of autobackups every X minutes
 * _some_ of the backups are created as empty...

**Comment by LittleVulpix** [comment]
This is really bad. List of (generally hourly) backups:

![image](https://user-images.githubusercontent.com/8679333/108582465-f0e7f280-7376-11eb-8449-6cfd066950bf.png)

**Comment by georgehazan** [comment]
@LittleVulpix pay attention to a fix above, please
