### ISSUE TITLE
TabSRMM: при копировании текста из журнала копируются также разделители

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2740]
Открываем окно табсов со стандартным журналом, копируем кусок лога, вставляем в Notepad++

<img width="264" alt="notepad++_LbCYqyVUMY" src="https://user-images.githubusercontent.com/5046855/107992768-6efc7000-6fea-11eb-9f81-61ee09c2563c.png">

Результат: во вставленном присутствуют разделители (-), это здорово мешает. Хотелось бы чтобы их не было, или пустая строка, но не -

**Comment by dartraiden** [comment]
Что интересно, если вставлять не в редактор, а сюда, на гитхаб, то вместо "-" будут таки пустые строки

```
   ghazan  Yesterday
21:49	погоди, это StdPopup или где?
­
   dartraiden  Yesterday
21:49	да
21:49	он самвй
­
   ghazan  Yesterday
22:06	поправил
```

**Comment by georgehazan** [comment]
а почему бы им не копироваться? такой же текст, как и всё остальное

**Comment by georgehazan** [comment]
тем более, что разделители можно выключить
