### ISSUE TITLE
Статус на значке в трее

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2744]
Настройки такие

<img width="482" alt="Miranda64_hSjyuusFGS" src="https://user-images.githubusercontent.com/5046855/108001762-72015b80-6ffe-11eb-8b1a-b0308cc696cb.png">

У меня два протокола в онлайне: ICQ и Jabber. значок в трее выглядит так:
<img width="58" alt="oihJnEB9Hi" src="https://user-images.githubusercontent.com/5046855/108001797-8c3b3980-6ffe-11eb-808d-419f3311bd40.png">

Теперь, ICQ остаётся "в сети", а Jabber перевожу в "away", и значок в трее почему-то отражает состояние жаббера:

<img width="121" alt="NSgZPbBvAe" src="https://user-images.githubusercontent.com/5046855/108001843-b2f97000-6ffe-11eb-8d9e-d519fa250a5a.png">

Вопрос: это нормально? Почему оно реагирует на жаббер, чем он важнее аськи? И как мне сделать, чтобы значок в трее не менялся?

**Comment by georgehazan** [comment]
Потому что так изначально написан код в модерне. Чем больше код статуса (от Offlne до Invisible включительно), тем выше его вес, поэтому при вычислении глобального статуса и показывается жабир.
