### ISSUE TITLE
IRC: сделать сообщение о ошибке более понятным

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2751]
![108763711-b8a50780-7562-11eb-8087-a26440e4d8b6](https://user-images.githubusercontent.com/5046855/108764128-3f59e480-7563-11eb-8c87-5b1363deaff7.png)

это, если не заполнить ник, userid и имя

имя в сорцах плагина зовётся реально m_name, но в настройках-то это "Full name", так что в сообщении об ошибке не надо юзера заставлять гадать, что за m_name, это имя внутренней переменной...

**Comment by georgehazan** [comment]
это не имя внутренней переменной, это называется "массовый поиск и замена name на m_name" :)
