### ISSUE TITLE
SkypeWeb: Удалить скрытую настройку UseServerTime

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2757]
В скайпе уже есть скрытая настройка UseLocalTime, почему не задействовать её?

В коде протокола я вижу:
```
		if (bUseLocalTime)
			timestamp = iLocalTime;
```

Настройка была добавлена в GUI, но, видимо, позже удалена, а в коде осталась?
https://github.com/miranda-ng/miranda-ng/commit/b47d3f2a1fae41ac9c7438f4903692e417020db6

Таким образом:
- если эта настройка то, что надо, то лучше использовать UseLocalTime=1, а не реверсное UseServerTime=0
- если она предназначена для другого, то просьба объяснить её действие, потому что в вики про скрытые настройки скайпа вообще нет ни слова, надо всё это документировать

Также есть третий вариант: вынести эти скрытые настройки в GUI, потому что скрытые настройки это зло, а эти настройки, вроде бы, действуют на учётку, им самое место в настройках протокола.

**Comment by georgehazan** [comment]
это другое ©

это не настройка, а флаг, который передается в функцию извне
