### ISSUE TITLE
System area icon colours change

### ISSUE THREAD

**Issue by irwir** [miranda-ng/miranda-ng#2758]
Originally miranda's icon was in red colours.
There was a clear difference between connected (red) and disconnected (grey) states. Native ICQ green/grey icons also were doing good in this area.

The current pale blue icon is too similar to light grey, making it hard to tell connection state at a glance.
Would you please consider changes to make things visually more distinctive?

**Comment by georgehazan** [comment]
Options - Icons - Protocols - install any suitable icon set you want

**Comment by irwir** [comment]
Thanks for the hint.
I just guessed that minor changes in the current default icon might improve usability right "out of the box".
