### ISSUE TITLE
Jabber: комната в клисте горит желтым, даже когда с меня снимают membership

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2759]
Конфа, куда могут входить лишь те, кто занесен в список мемберов (Member list). Я есть в списке, нахожусь в конфе. Меня убирают из мемберов (ПКМ по мне -> Set affilation -> None). Я пропадаю из никлиста у всех, кто сидит в конфе и им пишут, что я покинул конфу

`[22:21]	dartraiden (dartraiden@blablabla.ru/Miranda) has left`

При этом:
- в окне сообщений я продолжаю видеть конфу и оставшихся участников, хотя я уже не могу ни писать в конфу, ни читать новые сообщения
- в клисте конфа горит желтым

Полагаю, что поведение при исключении из мемберов должно быть аналогично кику. При кике конфа в клисте сереет. и никлист становится пустым в окне сообщений

**Comment by georgehazan** [comment]
желтая иконка просто значит, что есть непрочитанные события
соотв сбрасывается она как только события будут прочитаны. this is the way
