### ISSUE TITLE
Бесконечный хайлайт при логине

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2762]
- тебя хайлайтят в полумертвой конфе, где лог почти не двигается
- теперь, при каждом логине с сервера подтягивается последние N сообщений конфы, и при каждом логине табсы оповещают тебя об этом хайлайте, пока он не уйдёт так далеко, что перестанет подгружаться при логине, что в полумертвой конфе может занять хз сколько дней

с этим надо что-то делать

проблема есть в StdMsg и табсах, скорее всего в скривере тоже

**Comment by dartraiden** [comment]
Такая же проблема у StdMsg, но уже со сменой топика: если в истории чата есть несколько смен топика, то эти события подгружаются при входе в чат и вызывают сигнализацию

**Comment by georgehazan** [comment]
Тут проблема в Jabber... он пропускает из комнаты всё до получения топика, а потом выкидывает все сообщения из истории на экран. И с этого момента нет никакой возможности сказать хайлайту, что он кусок истории, а не актуальная сущность

**Comment by georgehazan** [comment]
по факту это является дублем #2823 
т.е. без участия архива MAM с прописанными идентификаторами сообщений вылечить это не выйдет
