### ISSUE TITLE
Во всех плагинах сообщений не работают уведомления о смене статуса

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2764]
- в конфе сидят 2 человека, с разных миранд
- у первого выставлены в events and filters попапы, звуки и мигания на Status changes
- второй меняет свой статус (ставит себе Away или Offline, любое изменения статуса)
- в первой миранде нет ни попапа, ни звука, ни мигания

**Comment by dartraiden** [comment]
Поправка: Offline миранда расценивает как User leaving и реагирует на leaving.

**Comment by georgehazan** [comment]
эти уведомления о смене role / affiliation, я тебе соврал. всё работает

**Comment by dartraiden** [comment]
Я проверил, поменял role / affiliation - ноль реакции

**Comment by georgehazan** [comment]
![image](https://user-images.githubusercontent.com/4628541/111281301-d6d7c200-864d-11eb-8e53-366b8b7ad5db.png)
просто меняй ее не себе
