### ISSUE TITLE
Notes and Reminders: невозможно выставить существующей напоминалке более раннее время

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2773]
1) Создаем напоминалку на любое время в будущем

2) Пытаемся отредактировать её время на чуть более ранее

там в выпадающем списке более раннего времени просто нет

**Comment by georgehazan** [comment]
Напоминалки настроены на продвижение вперед, если надо отмотать назад, можно просто руками поправить время

**Comment by dartraiden** [comment]
Нет, увы, руками тоже нельзя подправить время назад.

Пример: сейчас 18:00,, создаём напоминалку на сегодня, на 22:00. Теперь пытаемся руками выставить ей 21:00. Оно выставляется на 21:00 завтрашнего дня.

**Comment by dartraiden** [comment]
Не помогло. Создаём напоминалку на сегодня, на 3 часа вперед. Затем руками редактируем её, вписывая время чуть более ранее (на час раньше, чем было). Она перескочит на завтра.

**Comment by C1eriC** [comment]
Возможно, описанную ошибку ( https://github.com/miranda-ng/miranda-ng/issues/2793#issuecomment-831768317 ), было более правильно отнести к этому issue. Скорее всего именно в результате этой правки возник новый баг.
