### ISSUE TITLE
Нужно менять статус после поднятия сессии, а не после прохождения авторизации

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2774]
> протоколы ICQ и MRA (возможно Skype иногда) при попытке переподключения (Keep status) ненадолго загораются онлайн, хотя физически интернета нет. Т.е. это сбивает с толку, смотрю — загорелись, наверное интернет появился?! Нет

```
   ghazan,  Today
[12:46]	оно проходит авторизацию об сайт и радостно зажигает статус
[12:46]	а потом при попытке натянуть сессию обламывается
```

**Comment by georgehazan** [comment]
не подтверждаю. при отсутствии Интернета выдается крутилочка, но никто в онлайн не лезет
надо уточнить, как настроены иконки подключения
