### ISSUE TITLE
Notes and Reminders: ресайз столбцов странно себя ведёт

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2779]
- создаём напоминалку, ставим в качестве текста ей пару абзацев Lorem ipsum
- делаем ширину столбца с текстом широкой, чтобы появилась горизонтальная прокрутка

Баги:
1) при достижении некоей ширины текст обрезается, хотя места ещё полно

![image](https://user-images.githubusercontent.com/5046855/111486256-6366ab00-8748-11eb-84b8-2b556662fd45.png)

2) если теперь поменять ширину столбца с датой (сделать его сначала шире, потом обратно уже), то изменяется ширина столбца с текстом

![image](https://user-images.githubusercontent.com/5046855/111486429-885b1e00-8748-11eb-86ae-17dd3e7fe8a6.png)

**Comment by georgehazan** [comment]
всё правильно.

1. в списке текст напоминалки ограничивается 80 символами, потому и режется (только не надо вот экстремизма с растягиванием этого в ширину до такой степени, чтобы текст влезал полностью)
2. при изменении ширины колонки с датой ширина колонки с текстом выбирается автоматом как разница между шириной окна и шириной даты
