### ISSUE TITLE
ICQ->авторизация - сбрасывается переключатель

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#278]
**Reported by dim565 on 9 Mar 2014 05:17 UTC**
Здравствуйте.
Эта проблема тянется уже не первый год.

То есть в настройках учетной записи ICQ меняю Приватность-Авторизация на **"Все пользователи могут добавить меня в список"**, сохраняю.
Стоит отключиться от сети и подключиться - сбрасывается на **"Требуется мое разрешение"**, что очень не правильно.
В других клиентах такого не замечал, значит бага не на стороне ICQ.

**Comment by georgehazan** [comment]
**Modified by dim565 on 9 Mar 2014 07:04 UTC**

**Comment by dartraiden** [comment]
Неактуально, новый протокол не имеет авторизации как таковой.
