### ISSUE TITLE
Сломался редактор меню контактов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2787]
Все подменю свернуты и не реагируют на крестик, который должен их разворачивать.

А вот в главном меню всё почему-то в норме...

<img width="482" alt="Miranda64_kndgyQu05d" src="https://user-images.githubusercontent.com/5046855/111715760-9bafdb80-8865-11eb-90ca-718ce12d8c80.png">

**Comment by dartraiden** [comment]
Причем, на чистом профиле всё ок, а на двух моих (боевом и тестовом) баг есть.

**Comment by dartraiden** [comment]
При этом, почему VK-шное подменю разворачивается, а прочие - нет.

**Comment by georgehazan** [comment]
не разворачиваются меню с флагом SYSTEM, которые динамически формируются плагином
