### ISSUE TITLE
HistoryStats: в заголовке таблицы Unknown contact

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2788]
Не уверен, что там должно быть, но явно не неизвестный контакт.

<img width="955" alt="mstsc_2hh6ZS4iBI" src="https://user-images.githubusercontent.com/5046855/111716531-47a5f680-8867-11eb-94b4-7e21a9123962.png">

**Comment by georgehazan** [comment]
![image](https://user-images.githubusercontent.com/4628541/111808184-d016ac80-88e4-11eb-8daf-e3c518816a90.png)
чяднт

**Comment by georgehazan** [comment]
видимо, нет ни одной учетки с прописанным ником

**Comment by georgehazan** [comment]
а не, надо просто в опциях заполнить, как тебя правильно именовать

![image](https://user-images.githubusercontent.com/4628541/111820177-3f46cd80-88f2-11eb-87ce-e96a9d4d6ce4.png)
