### ISSUE TITLE
0.95.12 build #23274: битая база

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2791]
Чекер ошибок не находит, но сжатие не удаётся. mdbx_dump выдаёт ошибки. После апгрейда до текущей стабли не прорисовывается даже окно модерна, все настройки и данные в базе теряются.

Базу и вообще все бинарники с этого билда, на которых всё происходит, дам по запросу.

**Comment by georgehazan** [comment]
в морг
