### ISSUE TITLE
[0.96.1 alpha] Plugin Updater does not respect "every X days" setting

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#2792]
### Expected behavior
When setting Plugin Updater to check every 5 days, I expect PU to check every 5 days.

### Actual behavior
Being on the Alpha channel, new versions are released almost every day. PU updates stuff every day / after nearly every program start instead of every 5 days.
Could it be that it resets the timer every time it downloads an update?

### Does it work in stable version?
Have not tried stable. (Pointless since stable updates are very rare)

### Steps to reproduce that behavior
Set PU to every 5 days, silent mode, backup database.

CPU: AMD Ryzen 7 3700X 8-Core Processor  [AMD64 Family 23 Model 113 Stepping 0] [DEP Enabled] [16 CPUs]
Installed RAM: 32694 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 19042)
Internet Explorer: 9.11.19041.0 (build 919041)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | English/English
Free disk space on Miranda partition: 50312 MBytes

Miranda NG Version: 0.96.1 alpha build #23814 (368611ceed) x64
Build time: 21 Mar 2021 13:32:10
Profile: C:\Users\XXX\AppData\Roaming\Miranda NG\XXX\XXX.dat
Database driver: SQLite database driver
Profile size: 376832 Bytes
Profile creation date: 17 Mar 2021 11:21:43
Language pack: No language pack installed
Service Mode: No

Active Plugins (16):
¤ AVS.dll v.0.98.1.2 [17 Mar 2021 2:05:20] - Avatar service 
¤ Clist_modern.dll v.0.9.1.11 [17 Mar 2021 2:06:06] - Modern contact list 
¤ CrashDumper.dll v.0.1.0.4 [17 Mar 2021 2:05:58] - Crash dumper 
¤ Db_autobackups.dll v.0.1.0.4 [21 Mar 2021 13:32:30] - Db autobackuper 
¤ DbChecker.dll v.0.95.13.2 [21 Mar 2021 13:34:06] - Database checker 
¤ DbEditorPP.dll v.4.0.2.1 [17 Mar 2021 2:05:58] - Database editor++ 
¤ Dbx_mdbx.dll v.0.95.9.1 [21 Mar 2021 13:34:24] - Miranda NG MDBX database driver 
¤ Dbx_sqlite.dll v.0.95.13.4 [21 Mar 2021 13:34:00] - Miranda NG SQLite database driver 
¤ Dummy.dll v.0.2.0.0 [21 Mar 2021 13:33:42] - Dummy protocol 
¤ Import.dll v.0.95.11.1 [21 Mar 2021 13:32:56] - Import contacts and messages 
¤ IRC.dll v.0.95.10.1 [17 Mar 2021 2:05:22] - IRC protocol 
¤ MagneticWindows.dll v.0.0.3.2 [17 Mar 2021 2:06:54] - Magnetic Windows 
¤ PluginUpdater.dll v.0.2.0.11 [17 Mar 2021 2:06:02] - Plugin updater 
¤ StatusManager.dll v.1.2.0.6 [17 Mar 2021 2:06:58] - Status manager 
¤ Steam.dll v.0.95.12.2 [7 Mar 2021 2:06:46] - Steam protocol 
¤ Steam.dll v.0.95.12.2 [17 Mar 2021 2:06:46] - Steam protocol 
¤ TabSRMM.dll v.3.6.1.5 [17 Mar 2021 2:05:34] - TabSRMM 

Protocols and Accounts:
-------------------------------------------------------------------------------
IRC                      6 - Enabled 0 - Disabled  Loaded
STEAM                    1 - Enabled 0 - Disabled  Loaded

Icon Packs:
-------------------------------------------------------------------------------
 a0x_blue.dll [25 May 2007 13:34:20]
 a0x_bw.dll [25 May 2007 13:34:26]
 a0x_green.dll [25 May 2007 13:34:32]
 a0x_main.dll [25 May 2007 13:34:38]
 a0x_orange.dll [25 May 2007 13:34:46]
 a0x_purple.dll [25 May 2007 13:34:52]
 a0x_red.dll [25 May 2007 13:34:58]
 a0x_set1_grey.dll [25 May 2007 13:35:16]
 a0x_weather.dll [25 May 2007 13:35:04]
 a0x_yellow.dll [25 May 2007 13:35:08]
 Proto_Dummy.dll [21 Mar 2021 13:34:36]
 Proto_IRC.dll [17 Mar 2021 2:07:28]
 Proto_MetaContacts.dll [21 Mar 2021 13:34:36]
 Proto_Steam.dll [17 Mar 2021 2:07:30]
 Proto_Tox.dll [17 Mar 2021 2:07:30]
 TabSRMM_icons.dll [17 Mar 2021 2:07:30]
 Toolbar_icons.dll [17 Mar 2021 2:07:28]

**Comment by georgehazan** [comment]
@Tharn well, Plugin Updater definitely updates the timer each time the checking process is launched, but timer interval can be overloaded only by the "Check updates at startup" option: you should unheck it, if you really wanna launch Updater once in 5 days and restart Miranda time to time

**Comment by Tharn** [comment]
I have disabled "Check at startup" and only left "check every 5 days" active, as well as silent mode.
It still polled for and installed updates nearly every time (=every day) I started Miranda.

**Comment by Tharn** [comment]
Still doesn't work. I get notified of updates once a day if not more.

**Comment by georgehazan** [comment]
@Tharn ensure that Settings -> PluginUpdater/PeriodMeasure = BYTE 1 in dbeditor++
previously options dialog had a bug which leaded to improper combobox behaviour, so you could get an interval of 5 hours instead of 5 days

**Comment by Tharn** [comment]
Thanks, it was set to 0.

**Comment by georgehazan** [comment]
Yes, sorted combo places "days" in front of "hours", so the setting receive the reversed meaning
