### ISSUE TITLE
Notes and Reminders: напоминалка, выставленная в начале суток, перескакивает на следующий день

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2793]
- выставляем в системе 2 часа ночи, X числа месяца
- создаём напоминалку, дату оставляем X, как предлагается (текущий день), а время выставляем через меню на 6 утра

напоминалка создаётся на 6 утра X+1

**Comment by georgehazan** [comment]
если выставлять через меню, там будет написано, через какое время оно рванет (и почему при этом оно перескочит на следующий день)

**Comment by C1eriC** [comment]
Сегодня утром обновился до последней стабильной версии (0.95.13.1 build #23799).
Нашёл баг в работе плагина Notes&Remiders.

Пример. Сейчас 13:00. Ставлю напоминалку на 21:00. Всё ок, время в общем списке указано верно. Открываю её на редактирование и вижу в поле Time не 21:00, а, почему-то, 16:00. Если вручную вписать туда какое-то своё время, например 20:00, оно установится и верно отобразится в общем списке. Но если нажать Update Reminder, то время изменится на 19:00! Т.е. изначально напоминалка была установлена на 21:00, при открытии показала 16:00, а если ничего не изменять и просто нажать Update, она вдруг стала 19:00. Явно что-то не так...
Старые напоминалки тоже показывают неправильное время при открытии окна с отдельной напоминалкой. -5 часов (была на 17:00, показывает 12:00). Возможно это как-то связано с моим часовым поясом, +5 GMT.

**Comment by C1eriC** [comment]
Да, старая ошибка была исправлена (теперь напоминалке можно установить более раннее время). Но возникла новая, которую я описал выше. Неправильно указывается время при открытии (не редактировании!) напоминалки.

**Comment by C1eriC** [comment]
Я не знаю в каком тикете писать.
Обнаружилась ещё одна серьёзна ошибка плагина Notes&Remiders.
Создаю напоминалку, время оставляю текущее, а дату выбираю следующую (сегодня 4-ое, я выбираю 5-ое).
Напоминалка создаётся на 2157 год...

**Comment by dartraiden** [comment]
Юмор в том, что N&R в 0.95.13 должен быть идентичен 0.95.13.1

**Comment by C1eriC** [comment]
Возможно дело не в N&R?
Я откатился на 0.95.13 и у меня нет тех ошибок, которые наблюдал утром в 0.95.13.1.

**Comment by georgehazan** [comment]
@C1eriC 
> Возможно дело не в N&R?

Разумеется :) если потыркать комбо туда-сюда, то всё сразу станет норм, а вот если не трогать, то будет плохо. Исправил, но пока только в дев билде, надо потестить еще.
