### ISSUE TITLE
Notes and Reminders &  меню контакта

### ISSUE THREAD

**Issue by goonis** [miranda-ng/miranda-ng#2796]
После сегодняшнего обновления Miranda64 и Notes and Reminders (только именно эти 2 компонента были обновлены) правый клик на контакте в контакт-листе кроме всего прочего теперь отображает еще и всё меню от Notes & Reminders кроме обычных своих пунктов.
![miranda-ng](https://user-images.githubusercontent.com/8069033/112157199-0bbcb980-8bf8-11eb-9b9e-7aa98c2e87d8.png)

**Comment by georgehazan** [comment]
Из настроек плагинов были истреблены опции по управлению пунктами меню, потому что они редактируются все в одном и том же месте: Options - Customize - Menus. Соотв. туда надо зайти и отключить всё ненужное
