### ISSUE TITLE
XSoundNotify: per account message sounds

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#280]
**Reported by Piciok on 15 Mar 2014 13:43 UTC**
Hello. Would it be possible to enhance this plugin with a feature of setting individual sounds for each account so that for example messages coming from Facebook contacts sound differently than those coming from Jabber?

**Comment by georgehazan** [comment]
**Modified by watcher on 22 Mar 2014 12:43 UTC**

**Comment by georgehazan** [comment]
**Modified by mataes on 28 May 2014 04:42 UTC**

**Comment by Mataes** [comment]
added  in 4f6145c
