### ISSUE TITLE
Перестали сохраняется изменения всех числовых настроек

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2804]
Например, кол-во подгружаемых сообщений в табсах.

Или число резервных копий в апдейтере.

Значения возвращаются к прежним после переоткрытия окна настроек

**Comment by dartraiden** [comment]
<img width="482" alt="Miranda64_bu4YsW8jPV" src="https://user-images.githubusercontent.com/5046855/112401978-b5956680-8d1c-11eb-963e-5347d451f493.png">
Пример: если выставить цифры руками, то изменения не сохранятся. Если цифры выставить стрелочками справа от полей, то сохранятся.

**Comment by georgehazan** [comment]
конфликтует с #2766
