### ISSUE TITLE
Disable TLS 1.0/1.1

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2806]
[TLS 1.0/1.1 is deprecated](https://habr.com/company/globalsign/blog/548832/)

In every file inside /etc/nginx/conf.d/

find
```
    ssl_certificate blabla
    ssl_certificate_key blabla
```
add
`    include /etc/letsencrypt/options-ssl-nginx.conf; `

**Comment by dartraiden** [comment]
TLS 1.0/1.1 used only for

- Android 4.3 and older
- IE 8-10 / Win 7  (IE 11 still work)

**Comment by georgehazan** [comment]
при этом Миранда под XP уйдет в тьму, т.е. обновления только по http, никакого https

**Comment by georgehazan** [comment]
done
