### ISSUE TITLE
Db_autobackups: при пропуске сутки отсчитываются заново

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2808]
- в бэкапере включена опция "бэкапить каждые 1 день" (интервал не важен, может быть и 2, и 3, для простоты возьмём 1)
- если на момент, когда прошёл день с прошлого бэкапа, и пора сделать бэкап, Миранда выключена, то плагин пропустит этот день

пример:
- бэкап произошёл вчера в 15 часов
- сегодня в 15 часов Миранда была выключена
- включаем Миранду в 17 часов
 
результат: бэкапер пропустит сегодняшний день и будет ждать 15 часов завтрашнего дня

сообщили тут
https://forum.ru-board.com/topic.cgi?forum=5&topic=50156&start=1300#3

**Comment by dartraiden** [comment]
Наверное, имеет смысл сделать опцию, как в виндовом планировщике задач, мол, если задача пропущена, то сразу её выполнять, как только мы прочухали, что она пропущена.

**Comment by georgehazan** [comment]
нет, не будет. таймер аккуратно отсчитывается от момента предыдущего запуска, никакие переходы с одного дня на другой не влияют
