### ISSUE TITLE
IRC Without Server-List, 'Perform on Event' broken

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#2809]
### Expected behavior
Perform on Event (Server) items have been transferred over to Perform on Event (Connect).
They should fire when the account connects.

### Actual behavior
The events don't work at all. Even when putting them into both 'Connect' and 'Available', they don't work.

### Does it work in stable version?
Nope, this is an issue with the change of IRC server lists.

### Steps to reproduce that behavior
CPU: AMD Ryzen 7 3700X 8-Core Processor  [AMD64 Family 23 Model 113 Stepping 0] [DEP Enabled] [16 CPUs]
Installed RAM: 32694 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 19042)
Internet Explorer: 9.11.19041.0 (build 919041)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | English/English
Free disk space on Miranda partition: 50322 MBytes

Miranda NG Version: 0.96.1 alpha build #23833 (25c72306da) x64
Build time: 26 Mar 2021 19:03:16
Profile: C:\Users\XXX\AppData\Roaming\Miranda NG\XXX\XXX.dat
Database driver: SQLite database driver
Profile size: 376832 Bytes
Profile creation date: 17 Mar 2021 11:21:43
Language pack: No language pack installed
Service Mode: No

Active Plugins (16):
¤ AVS.dll v.0.98.1.2 [25 Mar 2021 15:54:10] - Avatar service 
¤ Clist_modern.dll v.0.9.1.11 [25 Mar 2021 15:55:00] - Modern contact list 
¤ CrashDumper.dll v.0.1.0.4 [17 Mar 2021 2:05:58] - Crash dumper 
¤ Db_autobackups.dll v.0.1.0.4 [26 Mar 2021 19:03:34] - Db autobackuper 
¤ DbChecker.dll v.0.95.13.2 [26 Mar 2021 19:05:16] - Database checker 
¤ DbEditorPP.dll v.4.0.2.1 [17 Mar 2021 2:05:58] - Database editor++ 
¤ Dbx_mdbx.dll v.0.95.9.1 [26 Mar 2021 19:05:12] - Miranda NG MDBX database driver 
¤ Dbx_sqlite.dll v.0.95.13.4 [26 Mar 2021 19:05:14] - Miranda NG SQLite database driver 
¤ Dummy.dll v.0.2.0.0 [26 Mar 2021 19:04:44] - Dummy protocol 
¤ Import.dll v.0.95.11.1 [26 Mar 2021 19:03:52] - Import contacts and messages 
¤ IRC.dll v.0.96.1.1 [26 Mar 2021 19:03:24] - IRC protocol 
¤ MagneticWindows.dll v.0.0.3.2 [17 Mar 2021 2:06:54] - Magnetic Windows 
¤ PluginUpdater.dll v.0.2.0.11 [24 Mar 2021 2:05:54] - Plugin updater 
¤ StatusManager.dll v.1.2.0.6 [17 Mar 2021 2:06:58] - Status manager 
¤ Steam.dll v.0.95.12.2 [17 Mar 2021 2:06:46] - Steam protocol 
¤ TabSRMM.dll v.3.6.1.5 [17 Mar 2021 2:05:34] - TabSRMM 

Protocols and Accounts:
-------------------------------------------------------------------------------
IRC                      6 - Enabled 0 - Disabled  Loaded
STEAM                    1 - Enabled 0 - Disabled  Loaded

Icon Packs:
-------------------------------------------------------------------------------
 a0x_blue.dll [25 May 2007 13:34:20]
 a0x_bw.dll [25 May 2007 13:34:26]
 a0x_green.dll [25 May 2007 13:34:32]
 a0x_main.dll [25 May 2007 13:34:38]
 a0x_orange.dll [25 May 2007 13:34:46]
 a0x_purple.dll [25 May 2007 13:34:52]
 a0x_red.dll [25 May 2007 13:34:58]
 a0x_set1_grey.dll [25 May 2007 13:35:16]
 a0x_weather.dll [25 May 2007 13:35:04]
 a0x_yellow.dll [25 May 2007 13:35:08]
 Proto_Dummy.dll [26 Mar 2021 19:05:36]
 Proto_IRC.dll [26 Mar 2021 19:05:36]
 Proto_MetaContacts.dll [26 Mar 2021 19:05:36]
 Proto_Steam.dll [17 Mar 2021 2:07:30]
 Proto_Tox.dll [17 Mar 2021 2:07:30]
 TabSRMM_icons.dll [17 Mar 2021 2:07:30]
 Toolbar_icons.dll [25 Mar 2021 15:56:36]

**Comment by Tharn** [comment]
dartraiden, by the way, the new layout looks excellent. This should make things much simpler.

**Comment by dartraiden** [comment]
Simple = better :D
