### ISSUE TITLE
Auto-replacements features

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#282]
**Reported by grillox on 28 Mar 2014 18:59 UTC**
Auto-replacements doesn't import the old AutoReplacer MIM settings.

1) Where and how can I edit Message Sessions -> Auto-replacements entries? Or how can I import MIM AutoReplacer settings to the new one?

2) Auto-replacements doesn't have some cool features MIM AutoReplacer had: (i) captalize first sentence; (ii) correct two initial caps; (iii) a list of most used words or phrases to suggest.

**Comment by georgehazan** [comment]
**Comment by watcher on 28 Mar 2014 20:25 UTC**
There is no Auto-replacer in MNG - where did you find one?

**Comment by georgehazan** [comment]
**Comment by watcher on 28 Mar 2014 21:03 UTC**
There may be part of the spellchecker - but it wasn't changed in any way since Miranda IM. And it was never compatible in any way with AutoReplacer.

**Comment by georgehazan** [comment]
**Comment by grillox on 11 Apr 2014 22:04 UTC**
Where and how can I ask somebody to migrate AutoReplacer to NG?

http://addons.miranda-im.org/details.php?action=viewfile&id=593

**Comment by georgehazan** [comment]
**Comment by wishmaster on 13 May 2014 19:32 UTC**
Replying to [grillox](comment:3):
> Where and how can I ask somebody to migrate AutoReplacer to NG?
> 
> http://addons.miranda-im.org/details.php?action=viewfile&id=593
You could ask the author to send us the source code. Without it, it cannot be adopted.

**Comment by dartraiden** [comment]
We need the sources. So I close this.
