### ISSUE TITLE
dbx_sqlite: total encryption is broken

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2822]
- select total encryption
- apply
- standard encryption is returned

**Comment by dartraiden** [comment]
Todo for me:
- check total encryption after conversion (should be standard)
- check total encryption after manually set

**Comment by apollo2k4** [comment]
Оно не поломано, его нет в стандартной поставке.
Можно почитать https://habr.com/ru/post/470295/

**Comment by dartraiden** [comment]
Так у нас ядром это реализуется, поддердка со стороны либы не нужна.

**Comment by georgehazan** [comment]
@apollo2k4 шифрованием занимается StdCrypt и ядро

**Comment by apollo2k4** [comment]
@georgehazan хм… До сейчас был уверен, что оно занимается другим.
