### ISSUE TITLE
Thy shall not store password in memory

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2836]
![Untitled](https://user-images.githubusercontent.com/5046855/113728260-99bb9880-96fe-11eb-8e4b-34b353fb1ac7.png)

Red = db password

Yellow = some pattern that precedes the password and occurs in the database only 9 times 
thus it is quite easy to find the password in memory

**Comment by 0x4E69676874466F78** [comment]
+Use security desktop for password prompt.
