### ISSUE TITLE
Nicknames don't show up in group chats in Discord

### ISSUE THREAD

**Issue by y0shir** [miranda-ng/miranda-ng#2838]
![Снимок2](https://user-images.githubusercontent.com/26626790/113914049-81c74000-97f6-11eb-8f96-2ecf93feb0f5.PNG)

When I log in into group chat, it doesn't show nicknames next to the messages

CPU: Intel(R) Core(TM) i5-2310 CPU @ 2.90GHz [Intel64 Family 6 Model 42 Stepping 7] [DEP Enabled] [4 CPUs]
Installed RAM: 8176 MBytes
Microsoft Windows 7 Ultimate Edition, 64-bit Service Pack 1 (build 7601)
Internet Explorer: 9.11.9600.19129 (build 99600)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian
Free disk space on Miranda partition: 17573 MBytes

Miranda NG Version: 0.95.13 build #23795 (c7779b0542) x64
Build time: 6 Apr 2021 20:48:10
Profile: C:\Users\Home\AppData\Roaming\Miranda NG\yo1999\yo1999.dat
Database driver: MDBX database driver
Profile size: 2097152 Bytes
Profile creation date: 20 Sep 2019 20:40:17
Language pack: Russian (RU) [0419]
Service Mode: No

[b]Active Plugins (29):[/b]
¤ AddContactPlus.dll v.[b]0.9.9.2[/b] [6 Apr 2021 20:48:44] - Add contact+ 
¤ AsSingleWindow.dll v.[b]0.1.2.2[/b] [6 Apr 2021 20:49:50] - AsSingleWindow 
¤ AssocMgr.dll v.[b]0.2.1.1[/b] [6 Apr 2021 20:49:14] - File association manager 
¤ AVS.dll v.[b]0.98.1.2[/b] [6 Apr 2021 20:48:16] - Avatar service 
¤ Clist_modern.dll v.[b]0.9.1.11[/b] [6 Apr 2021 20:49:00] - Modern contact list 
¤ CrashDumper.dll v.[b]0.1.0.4[/b] [6 Apr 2021 20:48:56] - Crash dumper 
¤ CryptoPP.dll v.[b]1.0.4.8[/b] [6 Apr 2021 20:50:24] - Crypto++ 
¤ Db_autobackups.dll v.[b]0.1.0.5[/b] [6 Apr 2021 20:48:30] - Db autobackuper 
¤ DbChecker.dll v.[b]0.95.13.2[/b] [6 Apr 2021 20:50:04] - Database checker 
¤ Dbx_mdbx.dll v.[b]0.95.9.1[/b] [6 Apr 2021 20:50:12] - Miranda NG MDBX database driver 
¤ Dbx_sqlite.dll v.[b]0.96.1.1[/b] [6 Apr 2021 20:50:04] - Miranda NG SQLite database driver 
¤ Discord.dll v.[b]0.6.2.8[/b] [6 Apr 2021 20:49:54] - Discord protocol 
¤ Dummy.dll v.[b]0.2.0.0[/b] [6 Apr 2021 20:49:36] - Dummy protocol 
¤ FavContacts.dll v.[b]0.1.0.3[/b] [6 Apr 2021 20:48:24] - Favorite contacts 
¤ Fingerprint.dll v.[b]0.2.0.1[/b] [6 Apr 2021 20:49:12] - Fingerprint NG 
¤ Flags.dll v.[b]0.1.0.4[/b] [6 Apr 2021 20:48:20] - Country flags 
¤ Import.dll v.[b]0.95.11.1[/b] [6 Apr 2021 20:48:48] - Import contacts and messages 
¤ IRC.dll v.[b]0.96.1.1[/b] [6 Apr 2021 20:48:20] - IRC protocol 
¤ Jabber.dll v.[b]0.95.11.1[/b] [6 Apr 2021 20:49:12] - Jabber protocol 
¤ Omegle.dll v.[b]0.1.3.3[/b] [6 Apr 2021 20:48:48] - Omegle protocol 
¤ PluginUpdater.dll v.[b]0.2.0.11[/b] [6 Apr 2021 20:49:02] - Plugin updater 
¤ SecureIM.dll v.[b]1.0.12.6[/b] [6 Apr 2021 20:48:36] - SecureIM 
¤ SmileyAdd.dll v.[b]0.3.2.1[/b] [6 Apr 2021 20:48:48] - SmileyAdd 
¤ StatusManager.dll v.[b]1.2.0.6[/b] [6 Apr 2021 20:49:52] - Status manager 
¤ TabSRMM.dll v.[b]3.6.1.5[/b] [6 Apr 2021 20:48:28] - TabSRMM 
¤ TopToolBar.dll v.[b]0.8.0.5[/b] [6 Apr 2021 20:48:46] - TopToolBar 
¤ Tox.dll v.[b]0.11.3.2[/b] [6 Apr 2021 20:50:30] - Tox protocol 
¤ UserGuide.dll v.[b]0.0.0.1[/b] [6 Apr 2021 20:48:34] - User guide 
¤ VKontakte.dll v.[b]0.1.11.8[/b] [6 Apr 2021 20:49:36] - VKontakte protocol 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
Discord                  1 - Enabled 0 - Disabled  Loaded
IRC                      4 - Enabled 0 - Disabled  Loaded
JABBER                   1 - Enabled 0 - Disabled  Loaded
VKontakte                1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 Flags_icons.dll [6 Apr 2021 20:50:34]
 Fp_icons.dll [6 Apr 2021 20:50:34]
 Proto_Discord.dll [6 Apr 2021 20:50:34]
 Proto_Dummy.dll [6 Apr 2021 20:50:34]
 Proto_Facebook.dll [6 Apr 2021 20:50:34]
 Proto_GG.dll [6 Apr 2021 20:50:34]
 Proto_ICQ.dll [6 Apr 2021 20:50:34]
 Proto_IRC.dll [6 Apr 2021 20:50:34]
 Proto_Jabber.dll [6 Apr 2021 20:50:34]
 Proto_MetaContacts.dll [6 Apr 2021 20:50:34]
 Proto_MRA.dll [6 Apr 2021 20:50:34]
 Proto_MSN.dll [5 Feb 2020 13:47:30]
 Proto_Omegle.dll [6 Apr 2021 20:50:34]
 Proto_Steam.dll [6 Apr 2021 20:50:34]
 Proto_Tox.dll [6 Apr 2021 20:50:34]
 Proto_Twitter.dll [6 Apr 2021 20:50:34]
 Proto_VKontakte.dll [6 Apr 2021 20:50:34]
 SecureIM_icons.dll [6 Apr 2021 20:50:34]
 TabSRMM_icons.dll [6 Apr 2021 20:50:34]
 Toolbar_icons.dll [6 Apr 2021 20:50:34]
 xStatus_Jabber.dll [6 Apr 2021 20:50:34]

**Comment by georgehazan** [comment]
нужен нетворк лог Discord + core (можно в мыло на ghazan at miranda point im)

**Comment by dartraiden** [comment]
[url=https://wiki.miranda-ng.org/index.php?title=Network_log]netlog[/url]
