### ISSUE TITLE
Db_autobackups: сдвинуть надпись на пару-тройку пикселей

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2849]
<img width="292" alt="Miranda64_EruzYWCEoQ" src="https://user-images.githubusercontent.com/5046855/115113994-ae691d80-9f95-11eb-82d0-6ed9123131fb.png">

сейчас текст про дату следующего резервного копирования впритык к краю контрола, что некрасиво

**Comment by georgehazan** [comment]
куда сдвинуть?

**Comment by dartraiden** [comment]
Правее, чтобы первая буква не была впритык к границе

**Comment by georgehazan** [comment]
это не буква впритык к границе, это sunken edge так выглядит
