### ISSUE TITLE
Weather: some strings cannot be translated

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2852]
![image](https://user-images.githubusercontent.com/5046855/115474659-953ac800-a246-11eb-9465-1e67ec91c976.png)

Humidity, etc...

**Comment by georgehazan** [comment]
там, короче, должно переводиться полностью всё, что в INI берется в кавычки

[Forecast Day 1]
Set Data=[Forecast Day 1 WeekDay] & ", " & [Forecast Day 1 Day] & ": " & [Forecast Day 1 Condition] & " (" & [Forecast Day 1 Low] & "/" & [Forecast Day 1 High] & "), " & [Forecast Day 1 Precipitation] & " Rain, UV: " & [Forecast Day 1 UV Index] & ", Humidity: " & [Forecast Day 1 Humidity]

тут переводится всё, что взято в кавычки - " Rain, UV: " 
чтобы переводилось правильно, надо сделать из этого " " & "Rain, UV" & ": "
