### ISSUE TITLE
Weather: разобраться с переменными

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2853]
Сейчас форменная путаница.

Во-первых, есть расширенные настройки погоды, где названия переменных переводятся

![image](https://user-images.githubusercontent.com/5046855/115474855-0d08f280-a247-11eb-9797-749206df42dc.png)

Во-вторых, в настройках плагина есть список переменных в чертовски неудобном виде

![image](https://user-images.githubusercontent.com/5046855/115474899-2f9b0b80-a247-11eb-9957-7cb2caa4d2d1.png)

Предлагаю сделать следующее:  первый столбец переименовать в что-то типа "показатель" (и я допереведу его на русский), а вторым столбцом сделать именно "переменные", где будут названия переменных без локализации.

Т.е. будет

Dew point (локализуемое) | Dewpoint (название переменной) | Значение

**Comment by georgehazan** [comment]
короче, что надо сделать:
- берем все три INI файла, то, что внутри них в квадратных скобках - это имя переменной в базе данных, оно впоследствии и будет переводиться
- то, что попадает в краткую форму, находится в модуле weather_data.cpp, там надо синхронизировать эти изменения
- соотв что ты положишь в базу, то надо поместить в файл перевода, и оно будет переводиться на ура
