### ISSUE TITLE
Отключённый плагин сообщений по-прежнему доступен в качестве журнала

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2857]
- снимаем галку с табсов, перезапускаем миранду
- после перезапуска работает stdmsg, табсы должны быть полностью выгружены

но они видны в списке журналов и даже выбраны

<img width="482" alt="Miranda64_3eNIK8H9Ex" src="https://user-images.githubusercontent.com/5046855/115873572-c33d2980-a44b-11eb-8c9b-63cafa1351aa.png">

**Comment by georgehazan** [comment]
duplicate of #2856
