### ISSUE TITLE
Некорректно работает опция у кнопок "скрывать при нехватке места на тулбаре"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2858]
У кнопок форматирования текста на тулбаре (табсы, stdmsg) есть опция про их скрытие в случае нехватки места.

Но она работает как "всегда скрывать". Даже, если места в избытке.

**Comment by georgehazan** [comment]
не знаю, у меня всё прекрасно работает - по мере сжатия диалога по горизонтали эти кнопки пропадают
PS: работает только в табсах
