### ISSUE TITLE
Импорт: дублируются контакты ICQ и FaceBook

### ISSUE THREAD

**Issue by jawhien** [miranda-ng/miranda-ng#2859]
### Actual behavior
После импорта и того как протоколы подключатся к сети, контакты из ICQ и FaceBook дублируются. Если контакт в сети, то его дубликат отображается не в сети. База данных в формате sqlite, импортируемая база тоже. Версия v0.96.1 alpha build #23959 (8318809aa0) x64

**Comment by georgehazan** [comment]
В каком режиме происходит импорт - сервисном или нет?

**Comment by jawhien** [comment]
@georgehazan, судя по всему нет, в самом обычном.
