### ISSUE TITLE
"Run the following application when new hotmail arrives" Not working

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#287]
**Reported by madajs on 27 Apr 2014 01:14 UTC**
I've used this for years, its an option under Network -> msn -> account. You enable "Run the following application when new hotmail arrives" and select a file to run. It's no longer functioning for me and wondering if anyone is having trouble too. Maybe an issue with miranda not being able to tell that you've received new hotmail.

**Comment by georgehazan** [comment]
**Comment by robyer on 21 May 2014 08:09 UTC**
I saw on forum that tinfo about receiving new hotmail email is broken (probably on server-side).

**Comment by dartraiden** [comment]
Protocol is deprecated.
