### ISSUE TITLE
Tipper: при запуске Миранды под курсором возникает подсказка, словно курсор наведен на значок в трее

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2870]
У Миранды есть подсказка о статусе протоколов, всплывающая при наведении курсора на значок Миранды в трее. Типпер заменяет эту подсказку своей. И эта типперовская подсказка при каждом старте Миранды вылезает там, где в данный момент находится курсор. Даже, если курсор не в трее.

Если баг невозможно исправить, то можно, хотя бы, реализовать опцию в Типпере, которая бы отключала эту типперовскую подсказку, возвращаю стандартную мирандовскую? (она ведёт себя нормально)

**Comment by georgehazan** [comment]
Типпер меняет только содержание подсказки, по части же зажигания оной Миранда глючит самостоятельно, это никак от Типпера не зависит

**Comment by georgehazan** [comment]
![image](https://user-images.githubusercontent.com/4628541/117175969-0eeebc00-add8-11eb-96b2-1ab059103d49.png)
Попробуй выключить эту галку и попробовать

**Comment by dartraiden** [comment]
Enable tray tooltips - убирает подсказку совсем, соответственно баг не проявляется
Handle tray tooltips by Tipper - делает "большую" подсказку размером поменьше, но всё равно она "типперовская" и баг есть
