### ISSUE TITLE
Иконки  погоды в Weather.

### ISSUE THREAD

**Issue by Dimoks** [miranda-ng/miranda-ng#2872]
https://github.com/miranda-ng/miranda-ng/blob/45f973369d30ab01d92899d2ca6ca8371d284781/protocols/Weather/src/weather_conv.cpp#L330

Есть ещё условие «Местами солнечно» — "partly sunny". Нужно его добавить.

Из-за сокращения числа статусов для протокола теперь нет Rain Shower (Light Rain) и Snow Shower.

> How does weather assign status icons for each status?
>
>   Online    = Sunny
>   Away    = Partly Cloudy
>   NA    = Cloudy
>   Occupied    = Rain
>   DND   = Rain Shower
>   Free for Chat = Snow / Wintery Conditions
>   Invisible   = Lightning / Thunderstorm
>   On the Phone  = Snow Shower
>   Out to Lunch  = Fog / Haze
>   Offline   = No Data Available

Есть проблема с переопределением  иконок погоды в INI файлах погоды в секции [Icons].

Сейчас при **Условие_иконки**=текущее_условие показываются иконки:
_Condition_for_icon=[Condition]_
(текущее_условие получается из парсинга [Condition])

Выбранное **условие иконки** — показываемая иконка
_Condition_for_icon — icon_
(для _показываемых иконок_ (статусов протокола) задан список соответствий с _условиями иконок_, и он сейчас неверен)

Cloudy — контакт не в сети (Offline) ![image](https://user-images.githubusercontent.com/3314441/117284729-d26e9f00-ae6f-11eb-913d-94b8054dc111.png)

Fog — Snow ![image](https://user-images.githubusercontent.com/3314441/117284790-e6b29c00-ae6f-11eb-8c0c-9032e9b2868a.png)

Lightning — Lightning ![image](https://user-images.githubusercontent.com/3314441/117284855-f7fba880-ae6f-11eb-9c67-d65de0566b80.png)

Partly Cloudy — Sunny ![image](https://user-images.githubusercontent.com/3314441/117285172-63de1100-ae70-11eb-86f2-67fe30d1593c.png)

Rain — Cloudy ![image](https://user-images.githubusercontent.com/3314441/117285262-82440c80-ae70-11eb-879a-35fbaf47723d.png)

Rain Shower — Partly Cloudy ![image](https://user-images.githubusercontent.com/3314441/117285332-938d1900-ae70-11eb-9157-8196bfa02c2a.png)

Sunny — Иконка до загрузки информации (No Data Available) ![image](https://user-images.githubusercontent.com/3314441/117285431-af90ba80-ae70-11eb-99f0-7eb6fa084b86.png)  (во фрейме контакта пусто)

Snow — Rain ![image](https://user-images.githubusercontent.com/3314441/117285487-c0413080-ae70-11eb-8ce2-c23d76c1176b.png)

Snow Shower — Rain Shower ![image](https://user-images.githubusercontent.com/3314441/117285560-d64ef100-ae70-11eb-8cb4-108c35d6e061.png)

**Comment by georgehazan** [comment]
@Dimoks 
"partly sunny" вставил. всё, что ниже слов "Есть проблема с переопределением иконок погоды" вообще не понял, что надо сделать и зачем

**Comment by Dimoks** [comment]
На случай отсутствия статуса, передаваемого сайтом погоды, в том перечне, раньше использовалось прямое назначение иконки для него.
Слева перед = задавалось условие, соответствующее иконке (статусу протокола), справа условие, получаемое от сайта. И вот это в текущей версии работает неправильно.

**Comment by Dimoks** [comment]
Кажется мне всё-таки что я немного ошибся. Сейчас в значках для протокола погоды не показываются Fog и Snow Shower. После этих изменений там появится fog вместо Rain Shower?

**Comment by georgehazan** [comment]
аллах его знает, я просто синхронизировал два массива
завтра утром узнаем

**Comment by Dimoks** [comment]
А возможно ли сделать иконки погоды не статусом протокола, а чем-то другим? Аватаркой или чем-то ещё, не связанным со статусами?

**Comment by georgehazan** [comment]
@Dimoks давно пора сделать это экстраиконкой, а про маппинг в статусы забыть, как страшный сон

**Comment by Dimoks** [comment]
В настройках значков статусов протокола ничего не изменилось.

Остались неверные переопределения:

Fog — Snow ![image](https://user-images.githubusercontent.com/3314441/117284790-e6b29c00-ae6f-11eb-8c0c-9032e9b2868a.png)

Snow — Rain Shower ![image](https://user-images.githubusercontent.com/3314441/117285560-d64ef100-ae70-11eb-8cb4-108c35d6e061.png)

Rain Shower и Snow Shower вроде бы не меняют ничего, по крайней мере при текущем Sunny показывает Sunny.

**Comment by Dimoks** [comment]
А экстраиконку сложно вставить сюда? И как она будет показываться в контакте?

**Comment by georgehazan** [comment]
> А экстраиконки сложно вставить сюда?

Сюда - это куда?

> И как она будет показываться в контакте?

В контакт-листе справа, как обычно

**Comment by Dimoks** [comment]
В плагин, чтобы они вместо статуса протокола показывались.

**Comment by georgehazan** [comment]
тогда надо делать не экстраиконку, а расширенный статус, как в ICQ - типа "играю в футбол" или что-то в этом роде, плюс кастомную стамеску с описанием прогноза

**Comment by Dimoks** [comment]
Столько проблем из-за обычных картинок…

**Comment by Dimoks** [comment]
Может статус протокола и его иконки отключить,  и добавить экстра-иконки? Всё равно сейчас на все иконки не хватает статусов протокола.

**Comment by dartraiden** [comment]
Это уже обсуждается в https://github.com/miranda-ng/miranda-ng/issues/2886

**Comment by Dimoks** [comment]
Назначение иконки в секции [Icons] INI-файла так и не исправили:

Fog — Snow ![image](https://user-images.githubusercontent.com/3314441/117284790-e6b29c00-ae6f-11eb-8c0c-9032e9b2868a.png)

Snow — Rain Shower ![image](https://user-images.githubusercontent.com/3314441/117285560-d64ef100-ae70-11eb-8cb4-108c35d6e061.png)

_Rain Shower_ и _Snow Shower_ вырезаны.
