### ISSUE TITLE
ICQ: проблема со стикерами

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2873]
В какой-то момент мы унифицировали приём стикеров во всех протоколах. Стикеры отображаются как картинки в логе при установленном SmileyAdd, а в его отсутствии - как надпись о том, что нужно установить SmileyAdd.

Вчера мне прислали стикер. Вместо ожидаемой надписи он принялся как обычная передача файла, да ещё без расширения (файл "sticker").

**Comment by georgehazan** [comment]
есть мнение, что не стикер вовсе тебе послали. давай нетворк лог делать, ICQ + core
![image](https://user-images.githubusercontent.com/4628541/118301406-abf1d900-b4eb-11eb-8324-d7c1e83c4b0c.png)

**Comment by dartraiden** [comment]
скрин, файл, нетлог

<img width="326" alt="Miranda64_n1RSe8t3Zg" src="https://user-images.githubusercontent.com/5046855/118376769-ad4a0100-b5d2-11eb-8758-59ab0b91a7a2.png">

[sticker.zip](https://github.com/miranda-ng/miranda-ng/files/6488134/sticker.zip)

[netlog - Copy.txt](https://github.com/miranda-ng/miranda-ng/files/6488135/netlog.-.Copy.txt)

**Comment by georgehazan** [comment]
в логе обычный файл трансфер без намека на стикер
