### ISSUE TITLE
TabSRMM: встроенный журнал корёжит после отправки файла в групчат через HTTP File Upload

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2880]
Назначаем логом встроенный журнал табсов. Отправляем в конфу файл через HTTP File Upload. В конфу улетает ссылка, а предыдущая строчка в логе начинает выглядеть коряво.

**Comment by georgehazan** [comment]
баг самоликвидировался в процессе починки чатов с историей
