### ISSUE TITLE
QuickSearch: enhancements

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2881]
- [x] add columns header menu
- [x] add colorization
- [x] make right panel expanded by default (remove right panel at all and replace it with form)
- [x]  если выделить в окне QS несколько контактов и скопировать, то копируются все контакты, а не только выделенные
- [x] если выделить в окне QS несколько контактов и удалить через контекстное меню, то они остаются в окне QS, пока не нажмёшь кнопку Refresh
- [ ]  если выделить в окне QS несколько контактов и переместить их в группу через контекстное меню, то ничего не происходит
- [x] если нажать на галку в заголовке любой колонки, то выберутся все контакты (галка при этом не снимается, полагаю, что галки должны работать как-то иначе)
- [x] кнопку Close нужно убрать, т.к. рядом находится стандартный виндовый крестик в заголовке окна, который делает то же самое

**Comment by georgehazan** [comment]
p.3 никак - там все контролы на форме зависят от этого дерьма.

**Comment by dartraiden** [comment]
- [ ]  [если выделить в окне QS несколько контактов и скопировать, то копируются все контакты, а не только выделенные](https://github.com/miranda-ng/miranda-ng/issues/597)
- [ ] если выделить в окне QS несколько контактов и удалить через контекстное меню, то они остаются, пока не нажмёшь кнопку Refresh
- [ ]  если выделить в окне QS несколько контактов и переместить их в группу через контекстное меню, то ничего не происходит
