### ISSUE TITLE
Weather: display weather as extra-icon instead of status

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2886]

**Comment by georgehazan** [comment]
or as XStatusId/XStatusName?

**Comment by dartraiden** [comment]
or make an option

**Comment by georgehazan** [comment]
сделано через расширенный кастомный статус

**Comment by Dimoks** [comment]
А когда будет новая сборка? С последней почти месяц прошёл.

**Comment by georgehazan** [comment]
ночник собирается каждую ночь
в стаблю переносятся только оттестированные фиксы

**Comment by Dimoks** [comment]
Версия в разработке (0.96.1) уже включает этот фикс? Плагин уже собран? И что нужно настроить, если да. Возможно нужно выбрать версию в разработке с отладочными символами?

**Comment by dartraiden** [comment]
Версия в разработке это и есть ночник. Он собирается каждую ночь.

**Comment by Dimoks** [comment]
Расширенный кастомный статус как включить? Наверное я что-то не поставил. У меня контакты погоды с иконками слева, справа ничего нет.

**Comment by dartraiden** [comment]
Если я правильно помню, для этого нужен Clist_modern и включённая в нём поддержка экстра-значков

<img width="482" alt="Miranda64_yo0o41uBTx" src="https://user-images.githubusercontent.com/5046855/120346614-3451e580-c304-11eb-821a-672b250676c5.png">

**Comment by Dimoks** [comment]
Переопределения иконок неверные есть:

Rain — Snow ![image](https://user-images.githubusercontent.com/3314441/117284790-e6b29c00-ae6f-11eb-8c0c-9032e9b2868a.png)

Или там какая-то новая иконка дождя?

Иконки довольно мелкие. И где в настройках задаётся размер шрифта для контактов погоды? Размер для обычных контактов на них не влияет.

_Rain Shower_ и _Snow Shower_ не работают

Иконки во фреймах и в окне краткой информации о погоде и в окне информации о контакте как и раньше статусом протокола определяется. И там остались неверные переопределения:

Fog — Snow ![image](https://user-images.githubusercontent.com/3314441/117284790-e6b29c00-ae6f-11eb-8c0c-9032e9b2868a.png)

Snow — Rain Shower ![image](https://user-images.githubusercontent.com/3314441/117285560-d64ef100-ae70-11eb-8cb4-108c35d6e061.png)

Вот бы ещё иметь возможность задавать само [Condition] в ini, чтобы проверить реакцию. А так придётся станции с разными условиями искать.

**Comment by dartraiden** [comment]
> И где в настройках задаётся размер шрифта для контактов погоды? Размер для обычных контактов на них не влияет.

Очень даже влияет, у погодных контактов статус считается как Away, поэтому и шрифт надо менять у контактов, которые Away

**Comment by Dimoks** [comment]
Я всему подряд менял размер шрифта раньше, и не запомнил, когда он поменялся у этих контактов. В русской версии «Недоступен». Шрифт поменял размер, а вот иконка нет.

**Comment by dartraiden** [comment]
А разве должна?

**Comment by Dimoks** [comment]
Мелкая она в списке контактов. Во фрейме она побольше. Но это уже не x-статус.

**Comment by Dimoks** [comment]
На условия Rain Shower и на Rain выдаёт x-иконку дождя. Там всё-таки дождь, а не снег, как мне показалось раньше. Иконка реально очень маленькая. Интересно, можно ли это изменить.

**Comment by Dimoks** [comment]
А конкретно что и как изменилось в 4ddea20?

**Comment by Dimoks** [comment]
Переопределения Rain Shower и Snow Shower вернули уже для секции [Icons] ini-файла?

**Comment by georgehazan** [comment]
@Dimoks сборка уже лежит

**Comment by Dimoks** [comment]
Переопределения Rain Shower и Snow Shower не вернули для секции [Icons] ini-файла.
Они похоже и без переопределения не показывают нужные иконки.
При условии станции Rain Shower не показывает ![image](https://user-images.githubusercontent.com/3314441/117285560-d64ef100-ae70-11eb-8cb4-108c35d6e061.png), а показывает ![image](https://user-images.githubusercontent.com/3314441/117285487-c0413080-ae70-11eb-8ce2-c23d76c1176b.png).

**Comment by georgehazan** [comment]
> Переопределения Rain Shower и Snow Shower не вернули для секции [Icons] ini-файла.
> Они похоже и без переопределения не показывают нужные иконки.

Нету больше никаких переопределений, теперь показывается в точности та иконка, которая живет в Condition

> При условии станции Rain Shower не показывает

В каком месте?

**Comment by Dimoks** [comment]
> Нету больше никаких переопределений, теперь показывается в точности та иконка, которая живет в Condition

Говорите нет, а вот в что прописываю в INI в секции [Icons] таки работают т для x-иконки, и для статуса протокола.
При текущем Condition — Lightning работают все эти (без ; в начале), кроме Rain Shower и Snow Shower:

;Sunny=Lightning
;Cloudy=Lightning
;Partly Cloudy=Lightning
;Fog=Lightning
;Lightning=Lightning
;Rain=Lightning
;Rain Shower=Lightning
;Snow=Lightning
;Snow Shower=Lightning

> В каком месте?

X-иконки и статус протокола.

И всё-таки, иконки где-то увеличены? Так и не увидел.

**Comment by georgehazan** [comment]
> При текущем Condition — Lightning работают все эти (без ; в начале), кроме Rain Shower и Snow Shower:

Rain Shower и Snow Shower не имеют маппинга в статусы вообще. Они показываются только в UserInfo и xStatus.

> И всё-таки, иконки где-то увеличены? Так и не увидел.

32х32 - это максимум

**Comment by Dimoks** [comment]
Значки xStatus похоже 16×16 выводятся, как и статус протокола.

Не видел Rain Shower иконку ![image](https://user-images.githubusercontent.com/3314441/117285560-d64ef100-ae70-11eb-8cb4-108c35d6e061.png) в xStatus при Condition — Rain Shower. Была иконка Rain ![image](https://user-images.githubusercontent.com/3314441/117285487-c0413080-ae70-11eb-8ce2-c23d76c1176b.png).

**Comment by Dimoks** [comment]
Получается, что от статусов протокола не ушли полностью. Он остался во фрейме. Там вроде как аватаркой является, если верить настройкам протокола.
![изображение_2021-06-11_220234](https://user-images.githubusercontent.com/3314441/121736814-bb6f3c80-cb00-11eb-8470-11aaff82eb77.png)

**Comment by Dimoks** [comment]
И почему с
```
[Condition]
Set Data="Cloudy"
Unit=Cond
```
Текстом таки меняется условие, но иконка становится ![image](https://user-images.githubusercontent.com/3314441/117284729-d26e9f00-ae6f-11eb-913d-94b8054dc111.png) и статус протокола — отключён? И так с любым условием.

**Comment by Dimoks** [comment]
Не только у _Rain Shower_ иконка Rain ![image](https://user-images.githubusercontent.com/3314441/117285487-c0413080-ae70-11eb-8ce2-c23d76c1176b.png), но и _Light Rain_ тоже.

**Comment by georgehazan** [comment]
> Значки xStatus похоже 16×16 выводятся, как и статус протокола.

Разумеется. В списке контактов все иконки 16х16.

**Comment by Dimoks** [comment]
> > Не только у Rain Shower иконка Rain image, но и Light Rain тоже.
> 
> Во фрейме?

Не только. В списке контактов в виде x-иконки, и в других местах.

**Comment by Dimoks** [comment]
Раз x-иконки в списке контактов 16×16, может можно её в аватарку кинуть? Тогда и во фрейме возможно будет не статус протокола, а условие (condition).

**Comment by dartraiden** [comment]
А если у пользователя отключены аватарки?

**Comment by dartraiden** [comment]
Если только с сохранением x-иконок, т.к. у пользователя могут быть вообще отключён показ аватарок.

**Comment by Dimoks** [comment]
Почему бы и нет. Мешать не будет. С аватаркой лучше будет видно иконку.

**Comment by georgehazan** [comment]
не понял, зачем нужны какие-то condition.
аватары прекрасно работают и показывают все 10 картиночек, вне зависимости от.

**Comment by georgehazan** [comment]
> В статусе протокола (и во фрейме контакта) она на Snow ![image](https://user-images.githubusercontent.com/3314441/117284790-e6b29c00-ae6f-11eb-8c0c-9032e9b2868a.png) сейчас заменяется.

сейчас никакие иконки не заменяются на другие, показывается ровно то, что сидит в контакте

**Comment by Dimoks** [comment]
Почему-то у меня в контактах погоды не показываются аватары. Только x-иконка и текст. Во фрейме статус протокола. И на то, и на другое влияют переопределения иконок в секции [Icons] файла INI. Такое впечатление, что у нас совсем разные клиенты, или настроены настолько по-разному.

**Comment by georgehazan** [comment]
> Почему-то у меня в контактах погоды не показываются аватары. 

А почему они должны там показываться? Они в типпере показываются, как и положено.

> Во фрейме статус протокола.

А вот это совсем неправда. Там показывается Condition станции, назначенной по умолчанию,

> И на то, и на другое влияют переопределения иконок в секции [Icons] файла INI. 

Так выкинь эти переопределения к чертям? Тебе нужны правильные иконки или какие-то там переопределения, которые вроде как завязаны именно на статус, а не на Condition.

**Comment by Dimoks** [comment]
Ещё и tipper, которым не пользуюсь. По-умолчанию и он не показывает аватары у контактов погоды.

**Comment by georgehazan** [comment]
> По-умолчанию и он не показывает аватары у контактов погоды.

Вообще легко, прямо искаропки, надо только аватары залить в Plugins/Weather
![image](https://user-images.githubusercontent.com/4628541/121818376-85ac8e00-cc8f-11eb-8dd6-42f259f5be83.png)

**Comment by Dimoks** [comment]
Так. Откуда они берутся? И как называются? Из коробки не получается. Уже как минимум инструкция нужна.

**Comment by georgehazan** [comment]
> Так. Откуда они берутся? 

Забиваем в гугл "Miranda weather avatars", первая ссылка - https://addons.miranda-ng.org/ru/detail/3986

> И как называются? 

Их там куча разных. Любой набор из 10 картинок надо залить, как и написано выше, в Plugins/Weather, к инишкам.

> Из коробки не получается. Уже как минимум инструкция нужна.

На сайте аддонсов подробная инструкция

**Comment by Dimoks** [comment]
Разобрался. На аватары таки не влияет переопределение иконок.
На условие _Rain Shower_ показывает аватар _Rain_.
Удивило, что почти во всех наборах [Weather Avatars 1.1](https://addons.miranda-ng.org/ru/category/37) _Rain Shower_ и _Snow Shower_ показываются более интенсивными, чем _Rain_ и _Snow_.

**Comment by Dimoks** [comment]
Во время загрузки Миранды во фрейме контакта погоды показывается последний аватар. После загрузки он исчезает. После убирания контакта из фрейма и возвращения в него показывается нормально.

**Comment by Dimoks** [comment]
> > Во фрейме статус протокола.
> 
> А вот это совсем неправда. Там показывается Condition станции, назначенной по умолчанию,

Без добавленных аватаров там иконка статуса протокола отображается. И переопределения иконок таки влияют на неё. И пара показывает неправильные иконки:

Fog — Snow ![image](https://user-images.githubusercontent.com/3314441/117284790-e6b29c00-ae6f-11eb-8c0c-9032e9b2868a.png)

Snow — Rain Shower ![image](https://user-images.githubusercontent.com/3314441/117285560-d64ef100-ae70-11eb-8cb4-108c35d6e061.png)

А переопределения _Rain Shower_ и _Snow Shower_ просто никак не влияют сейчас на иконку.

**Comment by Dimoks** [comment]
Проверил переопределения иконок. И оказывается, они влияют на аватарки, добавленные в Plugins\Weather. Кроме _Rain Shower_ и _Snow Shower_.

**Comment by georgehazan** [comment]
> На условие _Rain Shower_ и _Light Rain_ показывает аватар _Rain_.

Поправил.

> Удивило, что почти во всех наборах [Weather Avatars 1.1](https://addons.miranda-ng.org/ru/detail/3986) _Rain Shower_ и _Snow Shower_ показываются более интенсивными, чем _Rain_ и _Snow_.

Если открыть Google Translate и забить туда Rain Shower, то удивление еще возрастет :-)

> Хотя есть и условия _Heavy Rain Shower_ и _Heavy Snow Shower_, судя по langpack_russian.txt

Это для каких-то старых инишек, их давно уже нет с нами.

> Без добавленных в Plugins\Weather аватаров там иконка статуса протокола отображается.

Угу. Тоже вычистил.

> И переопределения иконок влияют на неё.

Больше не будут :-)

> А переопределения _Rain Shower_ и _Snow Shower_ просто никак не влияют сейчас на иконку.

Это очевидно. Переопределять можно статусы, а статус сейчас оставлен только для показа станции по умолчанию в статус-баре, если это включено в настройках. Статусов же Rain Shower & Snow Shower не существует (с момента искоренения двух других статусов в Миранде)

**Comment by georgehazan** [comment]
> Если таки есть рабочий ini c русскоязычным сайтом, переопределения ему нужны.

Обычно в урл можно вбить что-то типа lang=en

**Comment by Dimoks** [comment]
Иконки на [msn ](https://www.msn.com/en-us/weather/today/)показывают, что Rain shower более интенсивный чем Light Rain, но менее интенсивный чем Rain. Там набор иконок очень богатый.

**Comment by Dimoks** [comment]
Похоже у gismeteo нет английского варианта. По крайней мере сразу не видно переключателей.

**Comment by Dimoks** [comment]
> > На условие _Rain Shower_ и _Light Rain_ показывает аватар _Rain_.
> 
> Поправил.

_Light Rain_ таки осталось _Rain_

**Comment by georgehazan** [comment]
> > > На условие _Rain Shower_ и _Light Rain_ показывает аватар _Rain_.
> > 
> > 
> > Поправил.
> 
> _Light Rain_ таки осталось _Rain_

Light Rain не бывает, оно просто срабатывает на слово Rain. В списке иконок Light - это молния, она же гроза

**Comment by Dimoks** [comment]
Можно наверное добавить сочетание "Light Rain" в условие для rshower.

**Comment by georgehazan** [comment]
> Можно наверное добавить сочетание "Light Rain" в условие для rshower.

Rain Shower - это ливень, проливной дождь (ты не посмотрел в Google Translate?)
Оно не имеет никакого отношения к Light Rain

**Comment by Dimoks** [comment]
Переводов несколько. Думаю не просто так на msn _Rain shower_ более интенсивный чем _Light Rain_, но менее интенсивный чем _Rain_. Им наверное лучше знать, что означают их условия.

**Comment by dartraiden** [comment]
Вероятно, они интенсивностью обозначают продолжительность.

Rain Shower короче по времени, чем Rain, но обильнее.

**Comment by Dimoks** [comment]
Ну сами смотрите. Иконка Light Rain: 
![image](https://user-images.githubusercontent.com/3314441/121969553-39d81280-cd7d-11eb-86ae-8be15e8c8c00.png)
Иконка Rain Shower: 
![image](https://user-images.githubusercontent.com/3314441/121969788-b0751000-cd7d-11eb-9888-a23216422774.png)
Иконка Rain: 
![image](https://user-images.githubusercontent.com/3314441/121969837-d39fbf80-cd7d-11eb-8ff4-e19c2cc1a67b.png)

**Comment by Dimoks** [comment]
Кстати при Rain Shower аватарка не показывается.

**Comment by Dimoks** [comment]
Там на msn карту смотрю в поисках станций с дождём. Либо осадков, либо радар. На радаре удобнее смотреть, при выборе города показывается информация с иконкой и интенсивностью осадков.

**Comment by Dimoks** [comment]
Пожалуй лучше оставить так, как есть сейчас в версии разработки.

**Comment by Dimoks** [comment]
И в msn.ini нужно почистить секцию [Icons]. Там сейчас куча ненужного. Приходится убирать при проверках.

**Comment by Dimoks** [comment]
Обнаружилась одна неприятная штука. При удалении контакта погоды, вместе с ним удаляется аватарка, отображаемая в нём.

**Comment by Dimoks** [comment]
Посмотрел последнюю ночную сборку. Переопределения Rain Shower и Snow Shower добавлены и работают.

**Comment by Dimoks** [comment]
Не знаю, важно ли это, но в статусах протокола (не xСтатусах) в ночной сборке иконки переопределяются так:

Sunny — Sunny 
Cloudy — Cloudy
Partly Cloudy — Partly Cloudy
Fog — Snow
Lightning — Lightning
Rain — Rain
Rain Shower — Rain
Snow — Rain Shower
Snow Shower — Rain Shower

Наверное это уже не изменить, и лучше не трогать.

**Comment by Dimoks** [comment]
С русскими **Condition** у протокола статус offline. И иконки не работают. Можно что-нибудь сделать?
