### ISSUE TITLE
Weather: строки нужно переводить до сборки, а не после

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2889]
![clp-20210522-1649510](https://user-images.githubusercontent.com/5046855/119228923-00194080-bb1e-11eb-8a44-02ab04de1fb9.jpg)

в противном случае переводится лишь начало строки, т.к. все мыслимые сочетания в ленгпак не впихнёшь

**Comment by Dimoks** [comment]
langpack_russian.txt пожалуй тоже нужно изменять. Получается например в прогнозе на следующий день:
91% Дождь, Описание УФ: 5 (moderate), Влажность: 75%.
С фазой луны msn что-то переделали. Вместо “New Moon” теперь просто “Moon” пишут. В переводе получается «Новый». Что дальше будет…

**Comment by Dimoks** [comment]
А зачем [Update] вернули к старому варианту? Он так не будет работать.

**Comment by dartraiden** [comment]
https://github.com/miranda-ng/miranda-ng/commits/master

Я сразу вернул его обратно.

**Comment by Dimoks** [comment]
В коммитах увидел. А “Moonphase” для чего разделено?

**Comment by Dimoks** [comment]
Ну так и подумал. Изменю тогда свою редакцию langpack_russian.txt. Кстати, кроме добавления этого, там ещё со скоростью ветра и его направления регистр первой буквы второго слова пришлось изменить ([Wind direction] и [Wind speed]), и добавить
[Precipitation]
Вероятность осадков.

**Comment by Dimoks** [comment]
Сейчас пара параметров встречаются в langpack_russian.txt несколько раз.

Строки 34709 — 34712, 35235 — 35238, 35814 — 35815 и 35818 — 35819, 36401 — 36402 и 36405 — 36406, и 36506 — 36509:

[Wind Direction]
Ветер: направление
[Wind Speed]
Ветер: скорость

и строки 34818 — 34821 для подстройки к изменениям в ini:

[Wind direction]
Ветер: направление
[Wind speed]
Ветер: скорость

**Comment by dartraiden** [comment]
Разные регистры = разные строки.

**Comment by Dimoks** [comment]
Нужно в msn.ini в [Forecast Day x] вместо "UV" указать "UV Index", тогда нормальная фраза получится.
