### ISSUE TITLE
Clist Nicer: moving through the list with pg-up and pg-down keys not possible anymore

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#289]
**Reported by Piciok on 16 May 2014 16:51 UTC**
As of a week or more it is not possible to move through the contacts in bigger amounts using the page up and page down keys.

**Comment by georgehazan** [comment]
**Modified by mataes on 17 Jun 2014 04:39 UTC**

**Comment by LittleVulpix** [comment]
This can be closed.

Pg-up and pg-down are working as intend in clist_nicer, 0.95.6 alpha build 17731
