### ISSUE TITLE
IRC command /nick in Network → Advanced → Perform

### ISSUE THREAD

**Issue by Dimoks** [miranda-ng/miranda-ng#2896]
### Expected behavior
`/nick %mnick` should quietly change nickname after `/msg NickServ GHOST` after reconnect.

### Actual behavior
Command `/nick %mnick` calls window “Change nickname” after reconnect with `%anick`.

### Steps to reproduce that behavior
In Options → Network → Advanced → Perform on Event: Connect:

```
/SERVERSHOW
/msg NickServ GHOST %mnick password
/nick %mnick
```
Connect to a IRQ server, and reconnect internet.

**Comment by dartraiden** [comment]
perhaps a delay is needed because NickServ does not have time to kill the old nickname

**Comment by Dimoks** [comment]
I put `/sleep 3000`, it did not help.

**Comment by Dimoks** [comment]
This server obviously takes a long time to do this.
```
/sleep 4000
/sleep 3000
```
Helps.

**Comment by Dimoks** [comment]
Need to add a delay command to https://wiki.miranda-ng.org/index.php?title=Plugin:IRC/en/Commands, I found it here in Issues.

**Comment by dartraiden** [comment]
Done

**Comment by Dimoks** [comment]
Is there a identifier with % for the password specified in Network → Account?

**Comment by dartraiden** [comment]
All identifiers are listed in https://github.com/miranda-ng/miranda-ng/blob/master/protocols/IRCG/src/input.cpp
