### ISSUE TITLE
ICQ: ошибка при добавлении контакта

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2899]
На 2 машинах стоят миранды, в каждую заведен один и тот же UIN.

В первой Миранде я удаляю контакт. Он стирается с сервера. Запускаю вторую Миранду. Контакт закономерно "бледный" (т.к. на сервере его нет, а в базе есть). Я его добавляю (зеленый плюсик) и получаю "ошибка при добавлении buddy). Но контакт, вроде как добавляется. Так что сообщение об ошибке чего-то врёт.

Дам профиль, на котором это воспроизводится.

**Comment by georgehazan** [comment]
лучше нетворк лог сделай

**Comment by dartraiden** [comment]
Fixed in https://github.com/miranda-ng/miranda-ng/commit/8e707034502d958e4a966a62367595c166ad0289
