### ISSUE TITLE
Icons are missing in IcoLib for Miranda32.exe/Miranda64.exe

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#290]
**Reported by dracosha on 17 May 2014 07:22 UTC**
Some icons are missing in IcoLib for Miranda32.exe/Miranda64.exe
Missing icons underlined with red color on screenshot.

![screenshot 2014-05-17 0014](https://cloud.githubusercontent.com/assets/5046855/21104664/7960b64c-c098-11e6-880b-382b832b6ba9.png)

**Comment by georgehazan** [comment]
**Modified by dracosha on 17 May 2014 07:25 UTC**

**Comment by georgehazan** [comment]
**Modified by dracosha on 17 May 2014 07:27 UTC**

**Comment by georgehazan** [comment]
**Modified by wishmaster on 17 May 2014 11:53 UTC**

**Comment by Mataes** [comment]
this first dialog before all modules. you can't change this icon
