### ISSUE TITLE
Форум умер, не выдержав обновления

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2902]
1) сделать бэкап всего каталога с форумом (возможно, сделать бэкап mysql-базы на всякий случай)

2) удалить всё, кроме
attachments
pm_attachments
favicon.ico
Settings.php

3) залить чистый движок последней версии
https://download.simplemachines.org/index.php?thanks;filename=smf_2-0-18_install.zip
(не перезаписывая favicon.ico и Settings.php, т.к. в них содержится специфическая для нашей инсталляции информация)

4) стереть все файлы install*

дальше я вдумчиво установлю только самые нужные моды (список сохранил) и языки, т.к. форум не выдержал именно большого числа модов, многие из которых не были жизненно необходимы
(и вообще у движка SMF моды это больное место, поэтому нужно подходить к ним очень скрупулёзно)

**Comment by georgehazan** [comment]
done

**Comment by dartraiden** [comment]
<img width="477" alt="WinSCP_9iQldlyDD0" src="https://user-images.githubusercontent.com/5046855/120098582-636b2a00-c13f-11eb-8f7b-43848a8bfd1a.png">

**Comment by georgehazan** [comment]
убил
