### ISSUE TITLE
ICQ: подгрузка отсутствующего в базе сообщения с сервера вызывает дублирование предыдущего сообщения

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2904]
берём любое сообщение в истории
удаляем его из истории Миранды
дёргаем подгрузку истории с сервера

результат: прилетает это отсутствующее в базе сообщение вместе с предыдущим
отчего получается дубль предыдущего, которое в базе уже есть, а тут прилетела его копия

**Comment by georgehazan** [comment]
разобрался. там в прошлом (вероятно, при работе с mdbx) отъедался первый символ серверного message id, отсюда и дубли. не страшно, можно просто косить историю и заменять ее серверной
