### ISSUE TITLE
User history dialog GUI

### ISSUE THREAD

**Issue by irwir** [miranda-ng/miranda-ng#2906]
**Is your feature request related to a problem? Please describe.**
1. Sometimes messages are big and multiline.
2. Find dialog has no history; it does not even restore the latest search line.

**Describe the solution you'd like**
1. Having a splitter between the message history list and text pane might be useful.
2. Storing search history on disk might be an overkill, though keeping history during the current session might be considered. At least restoring the latest search line when opening `Find` dialog might be simple and still useful.

**Comment by georgehazan** [comment]
>Having a splitter between the message history list and text pane might be useful.

Why the existing splitter doesn't do?..

>Storing search history on disk might be an overkill,

HDDs are large & cheap these days... I store the whole history since year 2001, and it takes only ~180 MB.

>At least restoring the latest search line when opening Find dialog might be simple and still useful.

You mean one in StdHistory? It should be small, fast & dumb, by design. There're a lot of another plugins for watching history, from little BasicHistory to monstrous History++, you can choose the most suitable one

**Comment by irwir** [comment]
> > Having a splitter between the message history list and text pane might be useful.
> 
> Why the existing splitter doesn't do?..

If there is a horizontal splitter, mouse pointer never changes to double-sided arrow - both in the latest stable and alpha builds. It should be a bug then.

> > Storing search history on disk might be an overkill,
> 
> HDDs are large & cheap these days... I store the whole history since year 2001, and it takes only ~180 MB.

In my practice, searches in User History are rare and random. Next day those saved strings most probably would be useless.

> > At least restoring the latest search line when opening Find dialog might be simple and still useful.
> 
> You mean one in StdHistory? It should be small, fast & dumb, by design. There're a lot of another plugins for watching history, from little BasicHistory to monstrous History++, you can choose the most suitable one

Yes, ll this is about stardard `User History` dialog, and its very basic finctions. It might be dumb, but does not have to go too far in this direction.
Is it difficult to keep the last search string while Miranda is running? Now every time when user clicked `Find...`, search string is empty.

**Comment by georgehazan** [comment]
okay, now we have saved search value, Del hotkey that deletes a message and F3 which repeats last search
if you desperately needs splitter, reopen this bug

**Comment by irwir** [comment]
Thanks for the implemented changes.
No, I am not desperate about adding a splitter; and have got no rights to reopen issues closed by someone else.
But it was very natural idea, and rather trivial, because vertical layout of `User History` very much resembles the standard message dialog.
