### ISSUE TITLE
Нарушена работа с мышью в плагине Quick Search

### ISSUE THREAD

**Issue by clayware-shard** [miranda-ng/miranda-ng#2908]
В окне плагина Quick Search (v1.5.0.3) для поиска и фильтрации контактов не работает действие двойного клика левой клавишей мыши по любой строке в таблице - не происходит открытие окна чата желаемого контакта. При этом переход к контакту через вызов контекстного меню кликом правой клавишей мыши или Shift+F10 и выбором пункта по умолчанию "Message" работает нормально.

Также после открытия окна Quick Search и наведения курсора мыши на любую строку таблицы всплывает tooltip с иероглифами.

![quicksearch_2021-06-05_15-35-32](https://user-images.githubusercontent.com/56484675/120891895-b9ded980-c613-11eb-9818-13c66031d95b.png)

Наблюдается в Miranda x86 0.96.1 alfa build 24086 под Windows 7 x64.

**Comment by georgehazan** [comment]
мышь поправил, откуда берется левый тултип - дьявол его знает, в плагин он не входит
