### ISSUE TITLE
Icons are missing in IcoLib for History++ plugin and HistoryPP_icons.dll

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#291]
**Reported by dracosha on 17 May 2014 08:31 UTC**
Some icons are missing in IcoLib for HistoryPP_icons.dll
Missing icons underlined with red color on screenshot.

![screenshot 2014-05-17 0015](https://cloud.githubusercontent.com/assets/5046855/21104688/8bcfe8de-c098-11e6-9c85-81bf5cd018f1.png)

**Comment by georgehazan** [comment]
**Comment by wishmaster on 17 May 2014 09:02 UTC**
Im not sure. Is that icon still used after password protection has been removed? If it is unused, it should be removed too.

**Comment by georgehazan** [comment]
**Comment by Awkward on 19 May 2014 06:41 UTC**
if that icon will be removed, isn't it break order of other icons in icon file?

**Comment by georgehazan** [comment]
**Modified by dracosha on 21 May 2014 12:03 UTC**

**Comment by georgehazan** [comment]
**Comment by wishmaster on 21 May 2014 12:10 UTC**
Replying to [Awkward](comment:2):
> if that icon will be removed, isn't it break order of other icons in icon file?
Yes, but I don't see a point in adding an icon to Icolib which isn't used anywhere.

**Comment by georgehazan** [comment]
**Modified by mataes on 27 May 2014 04:42 UTC**

**Comment by Mataes** [comment]
fixed in 8cce73a
