### ISSUE TITLE
Отваливается соединение с Jabber (XMPP) сервером. Миранда 0.95.13.1

### ISSUE THREAD

**Issue by OmlineEditor** [miranda-ng/miranda-ng#2910]
После обновления с версии 0.95.12 до версии 0.95.13.1 build 23808 начались глюки.
Связь с Jabber сервером переодически отваливается на ровном месте и это не только у меня но и у всех друзей кто тоже обновился до последней версии. Связь держится иногода по 2-3 часа иногда по 10 минут и отваливается, отвалилась отключилась и миранда сама потом переподключается. Для проверки я смотрела на потери ICMP пакетов с сервера ко мне и от меня к серверу, там проблем нет, пакеты не теряются канал связи хороший. Обновления были только миранды, свой сервер с Prosody я не трогала. Подскажите где мне смотреть дополнительную информацию и логи чтобы передать их вам?

**Comment by dartraiden** [comment]
[url=https://wiki.miranda-ng.org/index.php?title=Network_log]Нетлог[/url] включить для протокола и, скорее всего, ядра тоже. И ждать отвала, тогда в нетлоге будет что-то видно.

А проще поставить StatusManager и включить в нём KeepStatus, который будет переподключать при разрыве.

**Comment by OmlineEditor** [comment]
KeepStatus стоит и переподключается при разрыве. Проблема в том что при этом разрывается OTR серия и нужно занова начинать ее для чата, при этом еще не доходят сообщения если неустановленно новая OTR сессия. Я бы молчала если бы не было таких проблем. вот тут об этом писали подробнее: https://github.com/miranda-ng/miranda-ng/issues/2483

**Comment by OmlineEditor** [comment]
Отвалилось через 5 минут, вот что в логах, если нужно еще или больше скажите мне:

[2021-06-07 01:14:34 0A34] SSL failure recieving data (10054)
[2021-06-07 01:14:34 0A34] [JABBER_2] Netlib_Recv() failed, error=10054
[2021-06-07 01:14:34 0A34] [JABBER_2] recvResult = 0
[2021-06-07 01:14:34 0A34] [JABBER_2] m_iDesiredStatus reset to (40072,40072) => 40071
[2021-06-07 01:14:34 0A34] [JABBER_2] leaving worker thread
[2021-06-07 01:14:34 0A34] [JABBER_2] Thread ended: type=0 server='oracle'
[2021-06-07 01:14:34 0A34] [JABBER_2] (000000000EDA49D0:768) Connection closed internal
[2021-06-07 01:14:34 0A34] [JABBER_2] (000000000EDA49D0:4294967295) Connection closed
[2021-06-07 01:14:34 0A34] [JABBER_2] Exiting ServerThread
[2021-06-07 01:14:34 18AC] KeepStatus: connection lost! (JABBER_2)
[2021-06-07 01:14:34 18AC] KeepStatus: O

Далее потом пошли логи для установления нового соединения.

**Comment by dartraiden** [comment]
А операционка какая?

**Comment by OmlineEditor** [comment]
У меня Windows 7 x64. На сервере Ubuntu 20.04.2 LTS.
До обновления на версии 0.95.12 все работало целый день без единого разрыва, а что сейчас не пойму.
Кроме миранды ничего не поменялось.

**Comment by dartraiden** [comment]
Попробуйте установить плагин OpenSSL, вся работа с криптографией будет вестись с его помощью вместо WinCrypto
(мало ли, вдруг в семерке что-то протухло)

**Comment by OmlineEditor** [comment]
Этот плагин?
https://wiki.miranda-ng.org/index.php?title=Plugin:OpenSSL/ru

**Comment by dartraiden** [comment]
Он самый

**Comment by dartraiden** [comment]
Вот, кстати, пример (я ж помню, что недавно было что-то про SSL и семёрку), как на сервере параноидально рубанули часть алгоритмов, в результате все винды, кроме 10-ки отвалились
https://github.com/miranda-ng/miranda-ng/issues/2821

**Comment by OmlineEditor** [comment]
Установила, на вид плагин Миранда подхватила, хотя я не нашла для него никаких настроек. Будем надеятся что проблем не будет. Я понаблюдаю пару дней и отпишусь сюда по результату. Спасибо за оперативную помощь :)

**Comment by dartraiden** [comment]
А у него их нет. Это просто замена криптопровайдера.

**Comment by OmlineEditor** [comment]
Проблема не решена, в логах примерно следующее на момент проблемы:

[2021-06-07 15:16:04 1134] SSL failure recieving data (-1, 5, 10054)
[2021-06-07 15:16:04 1134] [JABBER_2] Netlib_Recv() failed, error=10054
[2021-06-07 15:16:04 1134] [JABBER_2] recvResult = 0
[2021-06-07 15:16:04 1134] [JABBER_2] m_iDesiredStatus reset to (40072,40072) => 40071
[2021-06-07 15:16:04 1134] [JABBER_2] leaving worker thread
[2021-06-07 15:16:04 1134] [JABBER_2] Thread ended: type=0 server='oracle'
[2021-06-07 15:16:04 1134] [JABBER_2] (0000000002A2D8C0:924) Connection closed internal
[2021-06-07 15:16:04 1134] [JABBER_2] (0000000002A2D8C0:4294967295) Connection closed
[2021-06-07 15:16:04 1134] [JABBER_2] Exiting ServerThread
[2021-06-07 15:16:04 10F4] KeepStatus: connection lost! (JABBER_2)
[2021-06-07 15:16:04 10F4] KeepStatus: O
[2021-06-07 15:16:12 10F4] KeepStatus: status for JABBER_2 differs: stored = 40072, real = 40071
[2021-06-07 15:16:12 10F4] KeepStatus: !1@>A 
[2021-06-07 15:16:12 10F4] [JABBER_2] PS_SETSTATUS(40071,40071) => 40072
[2021-06-07 15:16:12 0E64] [JABBER_2] Thread started: type=0
[2021-06-07 15:16:12 0E64] [JABBER_2] Connection request to 10.10.10.10:1234 (Flags 0)....
[2021-06-07 15:16:12 0E64] [JABBER_2] (0000000002A2D8C0) Connecting to server 10.10.10.10:1234....
[2021-06-07 15:16:12 0E64] [JABBER_2] (0000000002A2D8C0) Connecting to ip 10.10.10.10:1234 ....

**Comment by georgehazan** [comment]
>net helpmsg 10054
An existing connection was forcibly closed by the remote host.

Я бы всё же посмотрел логи на сервере, что там происходит. Вариант - соединение рубит какой-то промежуточный агент типа роутера или файрволла

**Comment by georgehazan** [comment]
Можно, конечно, забраться в https://miranda-ng.org/distr/deprecated, выкачать обратно 0.95.12.1, поставить и попробовать - будет ли его косить. Но если будет, то я буду очень сильно удивлен.

**Comment by OmlineEditor** [comment]
Поставила старую версию
В логах миранды таже ошибка, а в логах сервера сказано что виноват клиент т.к. долго не отвечает.
как быть куда копать? Все версии программ на сервере последние и свежие, канал обновления stable.

Вот логи сервера:

Jun 08 18:00:43 c2s55abc7f01530	debug	Received[c2s]: <r xmlns='urn:xmpp:sm:3'>
Jun 08 18:00:43 oracle:smacks	debug	Received ack request, acking for 13
Jun 08 18:00:43 c2s55abc7f01530	debug	mod_csi_battery_saver(ab53): Got outgoing stanza: <a>
Jun 08 18:00:43 c2s55abc7f01530	debug	mod_csi_battery_saver(ab53): Encountered important stanza, flushing buffer: <a>
Jun 08 18:00:43 c2s55abc7f01530	debug	Sending[c2s]: <presence from='anastasia@oracle/Home' to='maria@oracle'>
Jun 08 18:00:43 oracle:throttle_presence	debug	Buffering presence stanza from anastasia@oracle/Home to maria@oracle/Conversations.CftJ
Jun 08 18:00:43 c2s55abc7f01530	debug	Sending[c2s]: <a xmlns='urn:xmpp:sm:3' h='13'>
Jun 08 18:01:25 c2s55abc7e6db20	debug	Sending[c2s]: <iq from='oracle' id='idle-check' type='get'>
Jun 08 18:01:51 c2s55abc8114510	debug	Sending[c2s]: <iq from='oracle' id='idle-check' type='get'>
Jun 08 18:01:52 c2s55abc8114510	debug	Received[c2s]: <iq from='elena@oracle/Home' id='idle-check' to='oracle' type='result'>
Jun 08 18:01:52 stanzarouter	debug	Discarding iq from c2s of type: result
Jun 08 18:01:55 oracle:pinger	info	Client "anastasia@oracle/Home" silent for too long, closing...
Jun 08 18:01:55 c2s55abc7e6db20	debug	Disconnecting client, <stream:error> is: <stream:error><connection-timeout xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>
Jun 08 18:01:55 c2s55abc7e6db20	debug	Sending[c2s]: <stream:error>
Jun 08 18:01:55 c2s55abc7e6db20	debug	Sending[c2s]: </stream:stream>
Jun 08 18:01:55 c2s55abc7e6db20	debug	c2s stream for anastasia@oracle/Home closed: connection-timeout
Jun 08 18:01:55 c2s55abc7e6db20	debug	Destroying session for anastasia@oracle/Home (anastasia@oracle): connection-timeout
Jun 08 18:01:55 sessionmanager	debug	All resources of anastasia are now offline


--------

вот логи миранды:

[2021-06-08` 18:02:19 10E0] [JABBER_2] (0000000006DACFD0:2216) Data sent
[2021-06-08 18:02:19 10E0] [JABBER_2] (0000000006DACFD0:2216) Data sent
[2021-06-08 18:02:19 10E0] [JABBER_2] (0000000006DACFD0:2216) Data sent
[2021-06-08 18:02:19 10E0] [JABBER_2] (0000000006DACFD0:2216) Data sent
prodid="-//HandGen//NONSGML vGen v1.0//EN" version="2.0"/></iq>
[2021-06-08 18:02:19 1880] SSL failure recieving data (10054)
[2021-06-08 18:02:19 1880] [JABBER_2] Netlib_Recv() failed, error=10054
[2021-06-08 18:02:19 1880] [JABBER_2] recvResult = 0
[2021-06-08 18:02:19 1880] [JABBER_2] Expiring iq id 162, sent to tomara@oracle/Home
[2021-06-08 18:02:19 1880] [JABBER_2] Expiring iq id 163, sent to tomara@oracle
[2021-06-08 18:02:19 1880] [JABBER_2] <iq/> iqIdGetVcard
[2021-06-08 18:02:19 1880] [JABBER_2] Expiring iq id 161, sent to tomara@oracle
[2021-06-08 18:02:19 1880] [JABBER_2] Expiring iq id 160, sent to tomara@oracle
[2021-06-08 18:02:19 1880] [JABBER_2] m_iDesiredStatus reset to (40072,40072) => 40071
[2021-06-08 18:02:19 1880] [JABBER_2] leaving worker thread
[2021-06-08 18:02:19 10E0] KeepStatus: connection lost! (JABBER_2)
[2021-06-08 18:02:19 10E0] KeepStatus: O

**Comment by georgehazan** [comment]
выключенный keep connection alive?

**Comment by OmlineEditor** [comment]
нет, поддерживаю соединение, все должно работать. очень странно что не поддерживает. фаервол проверила, никто ничего не блокирует.
![123](https://user-images.githubusercontent.com/13348933/121214168-899f7100-c887-11eb-9881-0f898213112d.JPG)

**Comment by georgehazan** [comment]
а в нетворк логе пинги есть?
есть еще вариант - сервак не публикует urn:xmpp:ping в features, но почему-то его ждет

**Comment by OmlineEditor** [comment]
для сервера в настройках файла /etc/prosody/prosody.cfg.lua есть строка на счет пингования, и есть в логах что сервер ждет эти пинги (хотя я не смогла найти в документтации сколько он ждет пинга и какие настройки у него есть?):

modules_enabled = {
  "pinger";            -- нет документации на сайте:  https://modules.prosody.im/mod_pinger.html
  
-------
В логах что генерирует миранда я не вижу ничего по слову "ping" похожего на пингование сервера. Есть только запросы информации о других людях и там есть слово: < feature var="urn:xmpp:ping"/ > но это свойства другого клиента, а не мой пинг на сервер для поддержания соединения. Может в миранде глюк какой или может модуль другой на сервере использовать?

**Comment by OmlineEditor** [comment]
как в миранде получить полный список всего что может сервер? как проверить поддерживает ли сервер пингование?

**Comment by dartraiden** [comment]
XML-консоль, например (Статус -> Протокол -> Службы), там сырой XML

**Comment by dartraiden** [comment]
> Может в миранде глюк какой

Сомневаюсь, учитывая, что на jabber.ru ничего не отваливается, значит, пинги, когда они приходят, Миранда воспринимает.

**Comment by georgehazan** [comment]
> как в миранде получить полный список всего что может сервер? как проверить поддерживает ли сервер пингование?

в самом начале нетворк лога, сразу после успешного логина (challenge accepted) сервер высылает полный набор своих капсов (features)

**Comment by georgehazan** [comment]
> В логах что генерирует миранда я не вижу ничего по слову "ping" похожего на пингование сервера.

Есть вариант, когда сервер отдает хэш своих капсов вместо того, чтобы перечислять все капсы подряд. Тогда этот хэш можно найти в файле jabberCaps.json в профиле.

**Comment by OmlineEditor** [comment]
Там нет этого, нет ничего в начале, что имеет слова "ping"

Но я заметила что очень редко если долго ждать и не пользоваться мирандой в логах появляется:

[2021-06-08 19:00:10 039C] [JABBER_2] (0000000006C80D70:772) Data received
< iq type='get' from='oracle' id='idle-check'><ping xmlns='urn:xmpp:ping'/ >< /iq >
[2021-06-08 19:00:10 039C] [JABBER_2] recvResult = 79
[2021-06-08 19:00:10 039C] [JABBER_2] Handling iq id idle-check, type get, from oracle
[2021-06-08 19:00:10 039C] [JABBER_2] (0000000006C80D70:772) Data sent
< iq type="result" to="oracle" id="idle-check" from="anastasia@oracle/Home"/ >
[2021-06-08 19:00:10 039C] [JABBER_2] bytesParsed = 79
[2021-06-08 19:00:11 039C] [JABBER_2] (0000000006C80D70:772) Data received

----------

Иногна вот такое есть, но это не вначале и это не свойства сервера:
[2021-06-08 19:17:16 1B4C] [JABBER_2] (0000000006D20D70:776) Data sent
< iq type="get" id="mir9cac095dd4ebf0ce_10" from="anastasia@oracle/Home"><ping xmlns="urn:xmpp:ping"/ >< /iq >
[2021-06-08 19:17:16 1B4C] [JABBER_2] (0000000006D20D70:776) Data received
< iq type='result' to='anastasia@oracle/Home' id='mir9cac095dd4ebf0ce_10'/ >
[2021-06-08 19:17:16 1B4C] [JABBER_2] recvResult = 68
[2021-06-08 19:17:16 1B4C] [JABBER_2] bytesParsed = 68

----- 
recvResult немного разный в ответах

**Comment by OmlineEditor** [comment]
в файле jabberCaps.json нет ничего по слову "ping"

**Comment by georgehazan** [comment]
> Иногна вот такое есть, но это не вначале и это не свойства сервера:

Ну вот это и есть тот самый пинг. Миранда должна посылать его раз в минуту вроде бы (или после минуты неактивности)

**Comment by OmlineEditor** [comment]
ну там явно не минута проходит, я ждала минут 10-15 и ничего не трогала в ней и только тогда увидела этот "ping"

**Comment by georgehazan** [comment]
если включено сжатие трафика, отключи его (Options -> Advanced -> Enable stream compression)

**Comment by OmlineEditor** [comment]
Сжатие трафика выключено дывным давно. Еще я нашла странные модули в Prosody на сервере.
Есть модуль "ping", а есть модуль "pinger". У меня был включен модуль "pinger" (это тот для которого нет документации и нет описания почему-то). Я выключила модуль "pinger" и добавила модуль "ping". Посмотрим что будет, может там несовместимость модулей была или они не подходили для этих нужд. Через время отпишусь, что получилось после замены.

**Comment by georgehazan** [comment]
@OmlineEditor 
там был какой-то очень древний и очень странный код keepAlive, вычистил я его нахрен и заменил простым таймером - давай пробовать, билд собран на сервере

**Comment by georgehazan** [comment]
вне зависимости от погоды должно теперь каждые 60 секунд idle слать что-то на сервер

**Comment by OmlineEditor** [comment]
мне попоробовать установить Development version по этой ссылке?
 https://wiki.miranda-ng.org/index.php?title=Plugin:Jabber/en

**Comment by dartraiden** [comment]
Нет, нужно в настройках апдейтера переключиться на версию в разработке. И дождаться, пока прилетит свежий билд.

**Comment by OmlineEditor** [comment]
хорошо, я поробую пока ту версию что есть v0.95.13.1 с теми настройками что сделала на сервере (заменила pinger на ping)
Если не поможет, буду ждать вашу версию.

**Comment by dartraiden** [comment]
Ну, собственно, раз он собран, то он сразу и прилетит при смене канала обновлений на девелоперский.

**Comment by OmlineEditor** [comment]
для того чтобы понять кто был виноват сервер или плагин миранды я подожду хотябы 1 день.
С момента замены pinger на ping прошел 1 час и я не получила ни одного дисконекта и в логах стала чаще видеть сообщения < ping xmlns="urn:xmpp:ping"/ > они почти каждую минуту. Кажется модуль pinger для prosody кривой и его нужно заменить на ping модуль.

**Comment by OmlineEditor** [comment]
Подводим итог, проблема решена.
Было сделано следующее:
- на самом компьютере добавила плагин https://wiki.miranda-ng.org/index.php?title=Plugin:OpenSSL/ru
- на сервере для prosody поменяла модуль **pinger** на модуль **ping**
Вот и всё, больше настроек не меняла (включение логов не в счёт).
Кажется модуль быль реально кривой, а я из-за свое криворукости не смогла этого понять. Извините за доставленное неудобство, проблем в самой миранде v0.95.13.1 кажется нет.
