### ISSUE TITLE
Drop WinCrypto API support

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2912]
Во-первых, WinCrypto создаёт проблемы на старых ОСях, например в https://github.com/miranda-ng/miranda-ng/issues/2821 даже Windows 7/8.1 оказались в пролёте.
Во-вторых, в далёком светлом будущем мы станем кроссплатформенными, так что OpenSSL будет единственным вариантом.
В третьих, OpenSSL у нас уже не падает.

Вероятно, нужно дропнуть SSL-плагины (StdSSL и OpenSSL) как класс. OpenSSL-библиотеки у нас, вроде, в базовой поставке уже, так что просто надо сделать так, чтобы все плагины, которым нужно крипто, дёргали OpenSSL.

Либо малой кровью: превратить OpenSSL в StdSSL.

Сейчас же мы стоим враскоряку: используем StdSSL, но некоторые протоколы без libcrypto даже не вгружаются (аська, жаббер).

**Comment by georgehazan** [comment]
у нас в netlib еще до хрена мест, где используется crypt32.dll, и оттуда нам тоже прилетает регулярно, кстати, например из NTLM авторизации
