### ISSUE TITLE
[0.95.13.1 Update, June 11th] Steam can't connect

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#2916]
### Actual behavior
[11:05:48 1CAC] [STEAM_1] w:\miranda-build\src\mir_app\src\netlib_openconn.cpp 707: connect() failed (10060)

[11:05:58 1A1C] [STEAM_1] CSteamProto::SetStatus: changing status from 40071 to 40072
[11:05:58 0020] [STEAM_1] Connection request to api.steampowered.com:443 (Flags 11)....
[11:05:58 0020] [STEAM_1] (00000000047ED4D0) Connecting to server api.steampowered.com:443....
[11:05:58 0020] [STEAM_1] (00000000047ED4D0) Connecting to ip 95.100.80.141:443 ....

[11:06:19 0020] [STEAM_1] w:\miranda-build\src\mir_app\src\netlib_openconn.cpp 707: connect() failed (10060)
[11:06:19 0020] [STEAM_1] CSteamProto::OnLoggedOn: unknown login error
[11:06:19 0020] [STEAM_1] CSteamProto::SetStatus: changing status from 1 to 40071
[11:06:19 0020] [STEAM_1] Connection request to api.steampowered.com:443 (Flags 11)....
[11:06:19 0020] [STEAM_1] (00000000047EDDD0) Connecting to server api.steampowered.com:443....
[11:06:19 0020] [STEAM_1] (00000000047EDDD0) Connecting to ip 95.100.80.141:443 ....

Keeps repeating.

### Does it work in stable version?
This is the new stable version. It worked fine in stable version from a few days ago.
Looks like a regression. SSL Plugin deprecated? Maybe that's why.

### Steps to reproduce that behavior
CPU: AMD Ryzen 7 3700X 8-Core Processor  [AMD64 Family 23 Model 113 Stepping 0] [DEP Enabled] [16 CPUs]
Installed RAM: 32694 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 19043)
Internet Explorer: 9.11.19041.0 (build 919041)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | English/English
Free disk space on Miranda partition: 51413 MBytes

Miranda NG Version: 0.95.13.1 build #23810 (bce99692d0) x64
Build time: 11 Jun 2021 11:30:34
Profile: C:\Users\xxx\AppData\Roaming\Miranda NG\xxx\xxx.dat
Database driver: SQLite database driver
Profile size: 1155072 Bytes
Profile creation date: 21 Apr 2021 7:55:03
Language pack: No language pack installed
Service Mode: No

Active Plugins (16):
¤ AVS.dll v.0.98.1.3 [11 Jun 2021 11:30:38] - Avatar service 
¤ Clist_modern.dll v.0.9.1.11 [15 May 2021 23:17:36] - Modern contact list 
¤ CrashDumper.dll v.0.1.0.4 [3 May 2021 21:51:32] - Crash dumper 
¤ Db_autobackups.dll v.0.1.0.5 [11 Jun 2021 11:31:00] - Db autobackuper 
¤ DbChecker.dll v.0.95.13.2 [11 Jun 2021 11:32:42] - Database checker 
¤ DbEditorPP.dll v.4.1.0.2 [19 May 2021 12:05:50] - Database editor++ 
¤ Dbx_mdbx.dll v.0.95.9.1 [11 Jun 2021 11:32:58] - Miranda NG MDBX database driver 
¤ Dbx_sqlite.dll v.0.96.1.2 [11 Jun 2021 11:32:38] - Miranda NG SQLite database driver 
¤ Dummy.dll v.0.2.0.0 [11 Jun 2021 11:32:12] - Dummy protocol 
¤ Import.dll v.0.95.11.1 [11 Jun 2021 11:31:18] - Import contacts and messages 
¤ IRC.dll v.0.96.1.1 [11 Jun 2021 11:30:42] - IRC protocol 
¤ MagneticWindows.dll v.0.0.3.2 [3 May 2021 21:53:46] - Magnetic Windows 
¤ PluginUpdater.dll v.0.2.0.12 [11 Jun 2021 11:31:36] - Plugin updater 
¤ StatusManager.dll v.1.2.0.6 [14 May 2021 13:24:18] - Status manager 
¤ Steam.dll v.0.95.12.2 [11 Jun 2021 11:32:18] - Steam protocol 
¤ TabSRMM.dll v.3.6.1.5 [11 Jun 2021 11:30:52] - TabSRMM 

Protocols and Accounts:
-------------------------------------------------------------------------------
IRC                      6 - Enabled 0 - Disabled  Loaded
STEAM                    1 - Enabled 0 - Disabled  Loaded

Icon Packs:
-------------------------------------------------------------------------------
 a0x_blue.dll [25 May 2007 14:34:20]
 a0x_bw.dll [25 May 2007 14:34:26]
 a0x_green.dll [25 May 2007 14:34:32]
 a0x_main.dll [25 May 2007 14:34:38]
 a0x_orange.dll [25 May 2007 14:34:46]
 a0x_purple.dll [25 May 2007 14:34:52]
 a0x_red.dll [25 May 2007 14:34:58]
 a0x_set1_grey.dll [25 May 2007 14:35:16]
 a0x_weather.dll [25 May 2007 14:35:04]
 a0x_yellow.dll [25 May 2007 14:35:08]
 Proto_Dummy.dll [11 Jun 2021 11:33:16]
 Proto_IRC.dll [11 Jun 2021 11:33:14]
 Proto_MetaContacts.dll [11 Jun 2021 11:33:16]
 Proto_Steam.dll [11 Jun 2021 11:33:16]
 Proto_Tox.dll [25 Mar 2021 14:56:08]
 TabSRMM_icons.dll [11 Jun 2021 11:33:14]
 Toolbar_icons.dll [15 May 2021 23:19:42]

**Comment by Tharn** [comment]
Maybe it was a connectivity issue. Works now. Sorry.

**Comment by georgehazan** [comment]
That's an usual timeout

>net helpmsg 10060

A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by Tharn** [comment]
Yes, it was Steam being weird. It surprised me because it happened right after update.
