### ISSUE TITLE
X-статус в списке контактов

### ISSUE THREAD

**Issue by Dimoks** [miranda-ng/miranda-ng#2918]
После загрузки Миранды x-статус в списке контактов на второй строке показывается. Но через некоторое время он сменяется на статус контакта (В сети или другой).
Настройки такие:
![image](https://user-images.githubusercontent.com/3314441/121820560-3ae54300-cc9c-11eb-8a80-a7204ed44d71.png)

**Comment by georgehazan** [comment]
если стамески нет, то будет показываться статус, верхняя опция в правой колонке

**Comment by Dimoks** [comment]
Так дело в том, что x-staus сам не исчезает, отключается его показ. Без этой опции вторая строка просто убирается.

**Comment by georgehazan** [comment]
потому что у пользователя убирается стамеска. 
легко проверяется по наличию поля StatusMsg в базе у этого контакта

**Comment by Dimoks** [comment]
Да не убирается он у групп Вконтакте. Он всегда там висит. Редко меняют.

**Comment by Dimoks** [comment]
Кажется мне, что это «Начальный статус» барахлит. Или ещё что-то, отвечающее за установку состояния протоколов после запуска Миранды.

**Comment by Dimoks** [comment]
Впрочем у меня кроме ВК и нет особо контактов со статусами. Возможно это только к протоколу Вконтакте и относится.

**Comment by Dimoks** [comment]
Удаление статуса как-то можно отследить в логах?

**Comment by dartraiden** [comment]
ответ разработчика плагина

> в принципе вк может что угодно вдруг прислать - пустой контактлист при пользователях в онлайне, к примеру
> может быть и присылает иногда пустой статус
