### ISSUE TITLE
BuddyPounce: отсутствует чекбокс Default Settings

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2921]
Чекбокс  в ресурсе **настроек** плагина

https://github.com/miranda-ng/miranda-ng/blob/b59f0f79952056fadf809c676749eed052810b23/plugins/BuddyPounce/res/resource.rc#L107

и описан у нас в вики - если он взведен, то все настройки в диалоге настроек плагина считаются дефолтными
но в реальности его нет

![121826620-50b92f00-ccc1-11eb-8cb7-03b127900c60](https://user-images.githubusercontent.com/5046855/121826716-f2408080-ccc1-11eb-8b5d-b214b7659bdf.png)

**Comment by georgehazan** [comment]
это не чекбокс, это групбокс - текст сверху рамочки
