### ISSUE TITLE
Добавление TLS в протокол IRC

### ISSUE THREAD

**Issue by Dimoks** [miranda-ng/miranda-ng#2926]
Возможно ли добавить TLS в протокол IRC? Некоторые серверы используют защиту TLS, а SSL у них не поддерживается.
[Пример сервера](https://libera.chat/).

**Comment by apollo2k4** [comment]
А в чём собственно проблема? Набор алгоритмов которые включины в стандарт SSLv3 признаны устаревшими и обычно сервера запрашивают версию протокола больше. При включённой поддержке SSL всё отлично работает с TLS серверами (если конечно OpenSSL не 100 летний)

**Comment by georgehazan** [comment]
SSL и TLS - это одно и то же, только SSL исполняет отдельное подключение, а TLS работает на уже натянутом сокете, вот и вся разница.

**Comment by Dimoks** [comment]
+Zi означает защищённый режим? При включённом SSL на порт TLS. Если да, то таки работает.

У меня на трёх серверах SASL не срабатывает. 
> SASL authentication aborted
Включая указанный в примере.

**Comment by dartraiden** [comment]
![image](https://user-images.githubusercontent.com/5046855/123166731-688d7180-d47e-11eb-9fa6-e74e9a142ef8.png)

[23:54:05 04B0] [IRC_1] (2268) Connected to irc.libera.chat:6697
[23:54:05 04B0] [IRC_1] (2268 irc.libera.chat) Starting SSL negotiation
[23:54:05 04B0] [IRC_1] (2268 irc.libera.chat) SSL negotiation successful

**Comment by Dimoks** [comment]
В сочетании с идентификацией с настройками по-умолчанию даёт SASL authentication aborted. Без него таки срабатывает.

**Comment by dartraiden** [comment]
У меня с ident-ом всё тоже норм. При включении ident Миранда запросила открытие порта, мб ей это не разрешили или ещё что-то.

**Comment by Dimoks** [comment]
C ident тоже всё время SASL проходит? После первого раза таки сработала, но дальше снова SASL authentication aborted.

**Comment by Dimoks** [comment]
У другого сервера вообще не замечаю проблем с этим. А вот с другим, irc.freenode.net:6697 даже без ident SASL authentication failed. Возможно просто не поддерживается…

**Comment by dartraiden** [comment]
Да, где-то 1 раз из 10 SASL лажает. Но тут разве что с вайршарком сидеть и смотреть трафик, и то вряд ли что-то можно увидеть, т.к. вся логика авторизации на сервере. Удел клиента - хавать, что дают.
