### ISSUE TITLE
Повреждение истории контакта

### ISSUE THREAD

**Issue by alexkutuzov** [miranda-ng/miranda-ng#2927]
При открытии контакта отображается пустая переписка (даже при получении нового сообщения). В протоколе обмена сообщение фиксируется  - можно получить историю для контакта, но при повторном открытии окна - всё опять пусто. Удаление контакта и получение вновь его с Jabber сервера решает проблему, но ошибка в последствие повторяется вновь на других контактах.

Предположение что проблема с базой данных - во вложении dat файл с проблемой
[akutuzov.zip](https://github.com/miranda-ng/miranda-ng/files/6706980/akutuzov.zip)

Имя контакта - Нехорошева Л.Ю.

**Comment by georgehazan** [comment]
никто уже не будет ковыряться в MDBX формате, надо просто перейти на SQLITE - и всё будет хорошо

**Comment by alexkutuzov** [comment]
Да, я только ЗА! Вопрос в том как перейти?

**Comment by georgehazan** [comment]
проще всего перейти на версию в разработке, тогда конверсия произойдет автоматом
Options - Plugin Updater - development version

либо запустить импорт в сервисном режиме на свежесозданный профиль

**Comment by alexkutuzov** [comment]
А.... у меня профиль создается через mirandaboot.ini, опция AutoCreate... а сейчас действительно попробовал при создании нового профиля есть выбор из... формата SQLite... и больше ничего нет в списке :-)

**Comment by alexkutuzov** [comment]
Формат базы через mirandaboot.ini у меня задать ни как не получиться?

**Comment by georgehazan** [comment]
> Формат базы через mirandaboot.ini у меня задать ни как не получиться?

не получится

> есть выбор из... формата SQLite... и больше ничего нет в списке :-)

логично. хватит этих разборок в никуда

**Comment by alexkutuzov** [comment]
> > Формат базы через mirandaboot.ini у меня задать ни как не получиться?
> 
> не получится
> 
Получится! Если не ложить в папку с Мирандой плагин Dbx_mdbx.dll, и libmdbx.mir - формат вновь созданной базы будет SQLite !!!

**Comment by alexkutuzov** [comment]
Главное теперь чтобы ошибка была в базе данных, а не в поведении при открытии вкладки контакта... будем наблюдать.
