### ISSUE TITLE
Icons are missing in IcoLib for Modern contact list plugin

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#293]
**Reported by dracosha on 17 May 2014 21:00 UTC**
Some icons are missing in IcoLib for Modern contact list plugin.
Missing icons underlined with red color on screenshot.

![screenshot 2014-05-17 00112](https://cloud.githubusercontent.com/assets/5046855/21104743/ba5454a6-c098-11e6-83c6-7f8f95b311be.png)

**Comment by georgehazan** [comment]
**Modified by mataes on 27 May 2014 04:46 UTC**

**Comment by Mataes** [comment]
this icons you can change using proto_conn.dll
