### ISSUE TITLE
Weather: некорректно работает, если ini-шка в UTF

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2931]
> Скорее всего читает русский текст в другой кодировке и не находит соответствий. Например переопределения в секции [Icons] gismeteo_ru.ini не работают при файле в UTF-8, и у контакта протокол отключённым получается.

**Comment by dartraiden** [comment]
Файл для тестов
https://forum.miranda-ng.org/index.php?topic=5775.msg28710#msg28710

**Comment by georgehazan** [comment]
one needs to add Utf8=true line into the [Header] section of ini file
