### ISSUE TITLE
MRA: contact search does not work 

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2938]

**Comment by dartraiden** [comment]
Работает поиск контактов MRA через ICQ, но добавляет, разумеется, как ICQ. Вероятно, это плохая идея, надо всё-таки понять, как искать по MRA

**Comment by georgehazan** [comment]
давно уже все работает как надо

**Comment by dartraiden** [comment]
Не работает.

**Comment by dartraiden** [comment]
[netlog.txt](https://github.com/miranda-ng/miranda-ng/files/10851716/netlog.txt)

**Comment by dartraiden** [comment]
Теперь отломался логин по почте/паролю,
