### ISSUE TITLE
ICQ: при активной сессии Миранда не видит, что контакт вошёл в сеть

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2940]
У меня в контактах человек. Моя миранда запущена. Человек не в сети, его цветочек в моём клисте закономерно потухший.

Человек со своей миранды входит в сеть. Но в моём клисте он так и остаётся потухшим, пока я вручную не передерну протокол.

Т.е. словно бы при активной сессии миранда не видит, что собеседник появился в сети.

**Comment by uranus** [comment]
У меня и двух моих контактов аналогичная ситуация. Появление контактов в online не видно, хотя переход в offline видно.
Пока вручную не переключишь своё подключение offline-online.
