### ISSUE TITLE
After updating Miranda NG from version0.95.10.2 build #21708 (a010d93692) x64 to version 0.95.13.1 build #23819 (d487ea59c5) x64 all message history for contacts is gone.

### ISSUE THREAD

**Issue by huh02** [miranda-ng/miranda-ng#2941]
After updating Miranda NG from version0.95.10.2 build #21708 (a010d93692) x64 to version 0.95.13.1 build #23819 (d487ea59c5) x64 all message history for contacts is gone.
When I right-click on contact, I can only give Load server history and it does nothing. The "View History" option is missing. I think the problem is in the Dbx_sqlite.dll library.
I don't know what to do, can it be solved? I'm quite unhappy I would like to have my history in a new version. I have a backup of the original version of Miranda NG.
A list of the old and new versions is attached.
[version.txt](https://github.com/miranda-ng/miranda-ng/files/6872298/version.txt)
[version2.txt](https://github.com/miranda-ng/miranda-ng/files/6872299/version2.txt)

**Comment by georgehazan** [comment]
@huh02 well, I advice you to install the stable version to the separate folder, copy your backup to its Profiles folder and then compact your profile (main menu - Database - Compact). If it's finished without problems, try to upgrade it again

**Comment by huh02** [comment]
I don't know if I understood correctly, but I did this procedure. I unpacked the latest stable version of Miranda NG into a separate folder. I copied the Profiles folder from my backup to this folder. I put Database-Compact in the menu. Database was compacted succesfully.
Menu-Check for updates - nothing happened. I still have no history :-(

**Comment by dartraiden** [comment]
So you have no history in backup?

**Comment by dartraiden** [comment]
Ok, return to 0.95.10.2 (where history is in place). Try to compact db (i don't remember if this option was in 0.95.10.2)

**Comment by dartraiden** [comment]
Install [Msg_Export plugin](https://www.miranda-ng.org/distr/deprecated/0.95.10.2/x64/Plugins/), export all contacts history into JSON files.

Install Msg_Export into 0.95.13.1 (where history is missing), right click by contact -> Import and import corresponding JSON. Repeat for every contact.

**Comment by huh02** [comment]
> Ok, return to 0.95.10.2 (where history is in place). Try to compact db (i don't remember if this option was in 0.95.10.2)

There is no such choice here.
Only Back up profile and Save profile as (translated from my language).

> Install Msg_Export via PliginUpdater into 0.95.13.1

OK, I already had this plugin, but I think it was an older version. I copied the dll to the Plugins folder. I'm sorry, but I can't find any export all contacts history or anything like that.
Msg_export.dll is enabled in the settings. For each contact, I only see Open Exported History, but no mention of JSON.

Do I have a damaged database? That's scary...

**Comment by dartraiden** [comment]
Yes, Options -> History -> Message export -> Use JSON format -> Contacts -> Right-click -> Select All -> Export

**Comment by dartraiden** [comment]
> For each contact, I only see Open Exported History, but no mention of JSON.

Thanks for the suggestion! We should probably add this item to contact menu
https://github.com/miranda-ng/miranda-ng/issues/2942

**Comment by huh02** [comment]
The export all contacts was successful.
Import one contact status:

Contact has been imported.
Number of contacts in the database: 1
Skipping
Skip system history import.
Import history.
Import completed in 0 seconds.
Added 0 contacts, 0 groups and 10875 events.

I still don't see the View history option.
There is also no history in the chat window.
I'm already desperate for that.

**Comment by georgehazan** [comment]
@huh02 I still don't see the View history option.
Options - Customize - Menus - Contact menu.
Check that this menu item is enabled

**Comment by huh02** [comment]
Yes, this item is checked. It's litle different in my language, but I think that's it.

**Comment by huh02** [comment]
I can only import 2 histories of my contacts, one with size 301B and the other 581B. (Importing history. Failed to add message.) 
I can't believe my database is so badly damaged. I can't import history even with a size of 931B. When I look at the exported JSON files, I don't see any visible errors.
In version 0.95.10.2, the whole history works for all contacts who have it.

**Comment by huh02** [comment]
Finally, I was able to manually import all the histories one by one into version 0.95.13.1 using History ++. Unfortunately, all my Miranda NG settings are gone.
I will now examine if these settings can be exported from version 0.95.10.2.

**Comment by dartraiden** [comment]
> I will now examine if these settings can be exported from version 0.95.10.2.
Manually [install](https://www.miranda-ng.org/distr/deprecated/0.95.10.2/x64/Plugins/) dbeditorpp and export settings via database editor to ini

**Comment by dartraiden** [comment]
> Connection failed. Unknown error during sign on 430. Damn.

Fill the new ticket and attach [url=https://wiki.miranda-ng.org/index.php?title=Network_log]netlog[/url]

**Comment by huh02** [comment]
>Manually install dbeditorpp and export settings

Thanks I'll try it.

>Please fill the new ticket and attach netlog

It's okay now, I probably got a ban for too many logins.
