### ISSUE TITLE
ICQ: проблема с получением оффлайн-сообщений

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2945]
> Получение офф-лайн сообщений (заметил уже как несколько дней, сразу не обратил внимания) - на сервере 7(!) сообщений от одного контакта, все в рамках текущего дня: первое 17:43 последнее 18:47, miranda залогинилась, забрала сообщения -  в окне чата и в истории 1 последнее......
Вызываем  "загрузить историю сообщений с сервера" - приходят остальные 6 предыдущих

**Comment by puffik2022** [comment]
та же проблема несколько месяцев

**Comment by dartraiden** [comment]
Duplicate of #3534
