### ISSUE TITLE
Skype: cannot login

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2946]

**Comment by dartraiden** [comment]
https://github.com/EionRobb/skype4pidgin/issues/680#issuecomment-889640429

**Comment by lokapal** [comment]
I confirm: Skype4pidgin 1.7 in pidgin after browser login logins without any problem in account that was "pure Skype" 
https://github.com/EionRobb/skype4pidgin/releases

**Comment by georgehazan** [comment]
> I confirm: Skype4pidgin 1.7 in pidgin after browser login logins without any problem in account that was "pure Skype"
> https://github.com/EionRobb/skype4pidgin/releases

It doesn't for me, at least.

**Comment by rugabunda** [comment]
> 
> 
> > Failed getting Magic T value, please try logging in via browser first -- since July 30
> 
 doesn't work anymore

**Comment by georgehazan** [comment]
@ikeblaster excellent job, it works again

**Comment by rugabunda** [comment]
> 
> 
> @ikeblaster excellent job, it works again, thanks

how? it still does not work for me. @miranda-ng why did you delete my comment?

![Still Broken](https://user-images.githubusercontent.com/38260267/131306679-48aa67ea-5f56-4af0-808f-cff777a3ece9.png)

**Comment by dartraiden** [comment]
You screenshot is from Pidgin, not Miranda NG.

**Comment by rugabunda** [comment]
> 
> 
> You screenshot is from Pidgin, not Miranda NG.

oops, sorry :)
