### ISSUE TITLE
Miranda is hiding behind the sidebar 

### ISSUE THREAD

**Issue by MPerfurt** [miranda-ng/miranda-ng#2948]
At the beginning I had searched for a long time. When I found the hiding place it was easy.  Miranda is hiding behind the sidebar. The same procedure after today's update. Miranda minimizes and hides itself.

![grafik](https://user-images.githubusercontent.com/88318026/127840987-a3074257-26d3-4ef1-b58a-b8bd71b564bc.png)

**Comment by georgehazan** [comment]
eh... if you haven't locked the taskbar, that's a normal behaviour for any program.
what's wrong, on your opinion?

**Comment by MPerfurt** [comment]
Miranda Crash Report from 30 Nov 2022 17:39:52. Crash Dumper v.0.2.0.1
 
Likely cause of the crash plugin: TabSRMM
 
Exception: Access Violation at address 00000000130A18CD. Reading from address 0000000000000028.
 
Stack Trace:
---------------------------------------------------------------
00000000130A18CD (mir_core 00000000130A0000): (filename not available) (0): Ordinal508
00000000130A4D34 (mir_core 00000000130A0000): (filename not available) (0): Ordinal379
000000001935476F (TabSRMM 0000000019320000): (filename not available) (0): (function-name not available)
0000000019337E60 (TabSRMM 0000000019320000): (filename not available) (0): (function-name not available)
000000001935235B (TabSRMM 0000000019320000): (filename not available) (0): (function-name not available)
0000000019347850 (TabSRMM 0000000019320000): (filename not available) (0): (function-name not available)
00000000130BCDC8 (mir_core 00000000130A0000): (filename not available) (0): Ordinal884
00007FF9DA1A2920 (USER32 00007FF9DA190000): (filename not available) (0): ScreenToClient
00007FF9DA1A20C2 (USER32 00007FF9DA190000): (filename not available) (0): ScreenToClient
00007FF9DA1A1FD6 (USER32 00007FF9DA190000): (filename not available) (0): ScreenToClient
00007FF9DA19E858 (USER32 00007FF9DA190000): (filename not available) (0): CallWindowProcW
00007FF9DA19DE1B (USER32 00007FF9DA190000): (filename not available) (0): SendMessageW
00007FF9DA19D68A (USER32 00007FF9DA190000): (filename not available) (0): SendMessageW
0000000019334FDC (TabSRMM 0000000019320000): (filename not available) (0): (function-name not available)
00007FF9DA1A2920 (USER32 00007FF9DA190000): (filename not available) (0): ScreenToClient
00007FF9DA1A20C2 (USER32 00007FF9DA190000): (filename not available) (0): ScreenToClient
00007FF9DA1A1FD6 (USER32 00007FF9DA190000): (filename not available) (0): ScreenToClient
00000000130C22A7 (mir_core 00000000130A0000): (filename not available) (0): mir_callNextSubclass
000000001933594A (TabSRMM 0000000019320000): (filename not available) (0): (function-name not available)
00000000130C21C4 (mir_core 00000000130A0000): (filename not available) (0): mir_subclassWindowFull
00007FF9DA19E858 (USER32 00007FF9DA190000): (filename not available) (0): CallWindowProcW
00007FF9DA19E3DC (USER32 00007FF9DA190000): (filename not available) (0): DispatchMessageW
00007FF9DA1B0C03 (USER32 00007FF9DA190000): (filename not available) (0): SendMessageTimeoutW
00007FF9DBCB0EF4 (ntdll 00007FF9DBC10000): (filename not available) (0): KiUserCallbackDispatcher
00007FF9D9A91064 (win32u 00007FF9D9A90000): (filename not available) (0): NtUserPeekMessage
00007FF9DA19A5C3 (USER32 00007FF9DA190000): (filename not available) (0): PeekMessageW
00007FF9DA19A523 (USER32 00007FF9DA190000): (filename not available) (0): PeekMessageW
00000000130C0A14 (mir_core 00000000130A0000): (filename not available) (0): Ordinal3
0000000012EFB53C (mir_app 0000000012EA0000): (filename not available) (0): mir_main
0000000140002904 (Miranda64 0000000140000000): (filename not available) (0): (function-name not available)
00000001400014BA (Miranda64 0000000140000000): (filename not available) (0): (function-name not available)
00007FF9DBB274B4 (KERNEL32 00007FF9DBB10000): (filename not available) (0): BaseThreadInitThunk
00007FF9DBC626A1 (ntdll 00007FF9DBC10000): (filename not available) (0): RtlUserThreadStart
 
CPU: AMD Ryzen 5 3600 6-Core Processor  [AMD64 Family 23 Model 113 Stepping 0] [DEP Enabled] [12 CPUs]
Installed RAM: 8119 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 19045)
Internet Explorer: 9.11.19041.0 (build 919041)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : German/German | German/German
 
Miranda NG Version: 0.96.1 build #24554 (a8e37028d6) x64
Build time: 1 Nov 2022 19:25:48
Profile: C:\Users\User\AppData\Roaming\Miranda NG\THRmario\THRmario.dat
Database driver: SQLite database driver
Language pack: German (DE) [0407]
Service Mode: No
 
Active Plugins (16):
¤ AVS.dll v.0.98.1.6 [24 Sep 2022 11:34:12] - Avatar service
¤ Clist_modern.dll v.0.9.1.12 [24 Sep 2022 11:35:26] - Modern contact list
¤ CrashDumper.dll v.0.2.0.1 [4 Oct 2022 19:37:48] - Crash dumper
¤ Db_autobackups.dll v.0.1.0.7 [1 Nov 2022 19:26:30] - Db autobackuper
¤ DbChecker.dll v.0.95.13.3 [1 Nov 2022 19:30:00] - Database checker
¤ Dbx_mdbx.dll v.0.95.9.1 [5 Jun 2022 19:15:46] - Miranda NG MDBX database driver
¤ Dbx_sqlite.dll v.0.96.1.2 [1 Nov 2022 19:29:58] - Miranda NG SQLite database driver
¤ Dummy.dll v.0.2.0.1 [1 Nov 2022 19:29:10] - Dummy protocol
¤ Facebook.dll v.0.1.0.11 [24 Sep 2022 11:38:06] - Facebook
¤ ICQ.dll v.0.96.2.3 [23 Oct 2022 19:58:10] - ICQ-WIM protocol
¤ Import.dll v.0.95.11.1 [1 Nov 2022 19:26:18] - Import contacts and messages
¤ Jabber.dll v.0.95.11.1 [1 Nov 2022 19:26:44] - Jabber protocol
¤ NewEventNotify.dll v.0.2.2.5 [20 Oct 2022 21:50:24] - NewEventNotify
¤ PluginUpdater.dll v.0.2.1.3 [24 Sep 2022 11:36:06] - Plugin updater
¤ TabSRMM.dll v.3.6.2.6 [20 Oct 2022 21:48:44] - TabSRMM
¤ TopToolBar.dll v.0.8.0.5 [5 Jun 2022 19:13:22] - TopToolBar
 
Loaded Modules:
-------------------------------------------------------------------------------
C:\Program Files\Miranda NG\Miranda64.exe  0000000140000000 - 000000014000D000 v.0.96.1.0 [1 Nov 2022 19:25:48]
C:\Windows\SYSTEM32\ntdll.dll  00007FF9DBC10000 - 00007FF9DBE08000 v.10.0.19041.2130 [12 Oct 2022 10:29:03]
C:\Windows\System32\KERNEL32.DLL  00007FF9DBB10000 - 00007FF9DBBCF000 v.10.0.19041.2251 [9 Nov 2022 12:40:53]
C:\Windows\System32\KERNELBASE.dll  00007FF9D9760000 - 00007FF9D9A32000 v.10.0.19041.2193 [9 Nov 2022 12:40:50]
C:\Windows\System32\USER32.dll  00007FF9DA190000 - 00007FF9DA32D000 v.10.0.19041.2130 [12 Oct 2022 10:29:00]
C:\Windows\System32\win32u.dll  00007FF9D9A90000 - 00007FF9D9AB2000 v.10.0.19041.2251 [9 Nov 2022 12:40:46]
C:\Windows\System32\GDI32.dll  00007FF9DB5E0000 - 00007FF9DB60B000 v.10.0.19041.2130 [12 Oct 2022 10:28:58]
C:\Windows\System32\gdi32full.dll  00007FF9D9550000 - 00007FF9D965F000 v.10.0.19041.2130 [12 Oct 2022 10:29:06]
C:\Windows\System32\msvcp_win.dll  00007FF9D9B50000 - 00007FF9D9BED000 v.10.0.19041.789 [22 Feb 2021 13:58:47]
C:\Windows\System32\ucrtbase.dll  00007FF9D9660000 - 00007FF9D9760000 v.10.0.19041.789 [22 Feb 2021 13:58:47]
C:\Windows\System32\SHELL32.dll  00007FF9DA330000 - 00007FF9DAA73000 v.10.0.19041.2075 [12 Oct 2022 10:29:05]
C:\Windows\System32\IMM32.DLL  00007FF9DB7B0000 - 00007FF9DB7E2000 v.10.0.19041.2193 [9 Nov 2022 12:40:50]
C:\Program Files\Miranda NG\libs\ucrtbase.dll  00007FF9C98D0000 - 00007FF9C99C5000 v.10.0.14393.795 [14 May 2021 12:55:58]
C:\Program Files\Miranda NG\libs\VCRUNTIME140.dll  00007FF9D4A90000 - 00007FF9D4AA5000 v.14.16.27012.6 [14 May 2021 12:55:58]
C:\Program Files\Miranda NG\libs\mir_app.mir  0000000012EA0000 - 0000000012F99000 v.0.96.1.24554 [1 Nov 2022 19:25:46]
C:\Windows\System32\CRYPT32.dll  00007FF9D9340000 - 00007FF9D9496000 v.10.0.19041.1889 [10 Aug 2022 11:41:16]
C:\Windows\System32\SHLWAPI.dll  00007FF9DAC30000 - 00007FF9DAC85000 v.10.0.19041.2075 [12 Oct 2022 10:29:05]
C:\Windows\System32\msvcrt.dll  00007FF9DB030000 - 00007FF9DB0CE000 v.7.0.19041.546 [9 Oct 2020 21:47:54]
C:\Windows\System32\WS2_32.dll  00007FF9DAEB0000 - 00007FF9DAF1B000 v.10.0.19041.546 [9 Oct 2020 21:47:55]
C:\Windows\SYSTEM32\WINMM.dll  00007FF9D2AF0000 - 00007FF9D2B17000 v.10.0.19041.546 [9 Oct 2020 21:47:18]
C:\Windows\System32\RPCRT4.dll  00007FF9DAB00000 - 00007FF9DAC25000 v.10.0.19041.1806 [15 Jul 2022 11:04:26]
C:\Windows\System32\COMDLG32.dll  00007FF9DB620000 - 00007FF9DB6FA000 v.10.0.19041.1806 [15 Jul 2022 11:04:27]
C:\Windows\System32\combase.dll  00007FF9D9C60000 - 00007FF9D9FB4000 v.10.0.19041.2130 [12 Oct 2022 10:29:02]
C:\Windows\System32\shcore.dll  00007FF9DAF80000 - 00007FF9DB02D000 v.10.0.19041.1865 [10 Aug 2022 11:41:14]
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e\COMCTL32.dll  00007FF9B4460000 - 00007FF9B46FA000 v.6.10.19041.1110 [9 Jul 2021 13:18:06]
C:\Windows\System32\ADVAPI32.dll  00007FF9DB700000 - 00007FF9DB7AE000 v.10.0.19041.2130 [12 Oct 2022 10:28:55]
C:\Windows\System32\sechost.dll  00007FF9DB540000 - 00007FF9DB5DC000 v.10.0.19041.1865 [10 Aug 2022 11:41:17]
C:\Windows\System32\ole32.dll  00007FF9DB9E0000 - 00007FF9DBB0A000 v.10.0.19041.1202 [9 Sep 2021 17:54:52]
C:\Windows\SYSTEM32\UxTheme.dll  00007FF9D68E0000 - 00007FF9D697E000 v.10.0.19041.2193 [9 Nov 2022 12:40:52]
C:\Program Files\Miranda NG\libs\zlib.mir  0000000013300000 - 000000001331D000 v.1.2.12.0 [1 Nov 2022 19:24:58]
C:\Program Files\Miranda NG\libs\libssl-1_1.mir  0000000077090000 - 000000007713D000 v.1.1.1.18 [29 Oct 2022 21:06:38]
C:\Windows\SYSTEM32\VERSION.dll  00007FF9D37A0000 - 00007FF9D37AA000 v.10.0.19041.546 [9 Oct 2020 21:48:03]
C:\Windows\SYSTEM32\Secur32.dll  00007FF9CCCB0000 - 00007FF9CCCBC000 v.10.0.19041.546 [9 Oct 2020 21:48:01]
C:\Program Files\Miranda NG\libs\mir_core.mir  00000000130A0000 - 00000000130DD000 v.0.96.1.24554 [1 Nov 2022 19:25:00]
C:\Windows\SYSTEM32\WTSAPI32.dll  00007FF9D4A40000 - 00007FF9D4A54000 v.10.0.19041.546 [9 Oct 2020 21:47:23]
C:\Program Files\Miranda NG\libs\libcrypto-1_1.mir  00000000753C0000 - 000000007570D000 v.1.1.1.18 [29 Oct 2022 21:05:44]
C:\Windows\System32\bcrypt.dll  00007FF9D9310000 - 00007FF9D9337000 v.10.0.19041.1023 [10 Jun 2021 18:17:24]
C:\Program Files\Miranda NG\libs\FreeImage.mir  0000000012000000 - 0000000012126000 [1 Nov 2022 19:25:28]
C:\Windows\SYSTEM32\SSPICLI.DLL  00007FF9D91D0000 - 00007FF9D9202000 v.10.0.19041.2130 [12 Oct 2022 10:29:04]
C:\Program Files\Miranda NG\libs\MSVCP140.dll  00007FF9C8090000 - 00007FF9C812B000 v.14.16.27012.6 [14 May 2021 12:55:58]
C:\Windows\System32\MSCTF.dll  00007FF9DB8C0000 - 00007FF9DB9D5000 v.10.0.19041.2193 [9 Nov 2022 12:40:50]
C:\Windows\System32\OLEAUT32.dll  00007FF9D9FC0000 - 00007FF9DA08D000 v.10.0.19041.985 [14 May 2021 10:46:37]
C:\Windows\SYSTEM32\CRYPTBASE.DLL  00007FF9D8CE0000 - 00007FF9D8CEC000 v.10.0.19041.546 [9 Oct 2020 21:47:55]
C:\Windows\SYSTEM32\kernel.appcore.dll  00007FF9D7BB0000 - 00007FF9D7BC2000 v.10.0.19041.546 [9 Oct 2020 21:47:41]
C:\Windows\System32\bcryptPrimitives.dll  00007FF9D9AC0000 - 00007FF9D9B42000 v.10.0.19041.1415 [15 Dec 2021 11:16:26]
C:\Windows\SYSTEM32\textinputframework.dll  00007FF9ABB00000 - 00007FF9ABBF9000 v.10.0.19041.2075 [12 Oct 2022 10:28:58]
C:\Windows\System32\CoreUIComponents.dll  00007FF9D6080000 - 00007FF9D63DE000 v.10.0.19041.546 [9 Oct 2020 21:47:37]
C:\Windows\System32\CoreMessaging.dll  00007FF9D63E0000 - 00007FF9D64D2000 v.10.0.19041.2193 [9 Nov 2022 12:40:48]
C:\Windows\SYSTEM32\ntmarta.dll  00007FF9D84A0000 - 00007FF9D84D3000 v.10.0.19041.546 [9 Oct 2020 21:47:53]
C:\Windows\SYSTEM32\wintypes.dll  00007FF9D59B0000 - 00007FF9D5B04000 v.10.0.19041.2130 [12 Oct 2022 10:29:02]
C:\Windows\SYSTEM32\dwmapi.dll  00007FF9D6BA0000 - 00007FF9D6BCF000 v.10.0.19041.746 [19 Jan 2021 13:36:12]
C:\Program Files\Miranda NG\Plugins\CrashDumper.dll  00000000167E0000 - 00000000167F3000 v.0.2.0.1 [4 Oct 2022 19:37:48]
C:\Windows\SYSTEM32\dbghelp.dll  00007FF9D7050000 - 00007FF9D7234000 v.10.0.19041.867 [22 Mar 2021 17:17:47]
C:\Windows\SYSTEM32\dbgcore.DLL  00007FF9CC850000 - 00007FF9CC87C000 v.10.0.19041.789 [22 Feb 2021 13:58:54]
C:\Program Files\Miranda NG\Plugins\DbChecker.dll  0000000017020000 - 000000001702D000 v.0.95.13.3 [1 Nov 2022 19:30:00]
C:\Program Files\Miranda NG\Plugins\Dbx_mdbx.dll  0000000016AC0000 - 0000000016ACF000 v.0.95.9.1 [5 Jun 2022 19:15:46]
C:\Program Files\Miranda NG\libs\libmdbx.mir  0000000012B20000 - 0000000012B5C000 [5 Jun 2022 19:15:34]
C:\Program Files\Miranda NG\Plugins\Dbx_sqlite.dll  00000000170E0000 - 00000000170EF000 v.0.96.1.2 [1 Nov 2022 19:29:58]
C:\Program Files\Miranda NG\libs\sqlite3.mir  00000000131A0000 - 0000000013248000 [1 Nov 2022 19:25:56]
C:\Program Files\Miranda NG\Plugins\Import.dll  0000000017E40000 - 0000000017E5B000 v.0.95.11.1 [1 Nov 2022 19:26:18]
C:\Program Files\Miranda NG\libs\libjson.mir  0000000012AE0000 - 0000000012AF6000 [1 Nov 2022 19:25:56]
C:\Program Files\Miranda NG\libs\Pcre16.mir  0000000013120000 - 000000001313D000 [1 Nov 2022 19:26:00]
C:\Program Files\Miranda NG\Core\stdcrypt.dll  0000000013080000 - 000000001308D000 v.0.96.1.24554 [1 Nov 2022 19:25:08]
C:\Windows\SYSTEM32\Msftedit.dll  00007FF9AB7B0000 - 00007FF9ABAF8000 v.10.0.19041.1288 [14 Oct 2021 20:07:14]
C:\Program Files\Miranda NG\Plugins\Clist_modern.dll  00000000164A0000 - 000000001651F000 v.0.9.1.12 [24 Sep 2022 11:35:26]
C:\Windows\SYSTEM32\MSIMG32.dll  00007FF9CEF20000 - 00007FF9CEF27000 v.10.0.19041.1466 [12 Jan 2022 20:41:59]
C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.0.19041.2251_none_a252956433826d1a\gdiplus.dll  00007FF9BF030000 - 00007FF9BF1D5000 v.10.0.19041.2251 [4 Nov 2022 5:38:14]
C:\Windows\System32\clbcatq.dll  00007FF9DB7F0000 - 00007FF9DB89F000 v.2001.12.10941.16384 [12 Oct 2022 10:29:02]
C:\Windows\system32\explorerframe.dll  00007FF9A6D50000 - 00007FF9A6F70000 v.10.0.19041.1949 [14 Sep 2022 7:55:49]
C:\Program Files\Miranda NG\Plugins\AVS.dll  0000000016280000 - 0000000016297000 v.0.98.1.6 [24 Sep 2022 11:34:12]
C:\Program Files\Miranda NG\Plugins\Db_autobackups.dll  0000000017100000 - 0000000017115000 v.0.1.0.7 [1 Nov 2022 19:26:30]
C:\Program Files\Miranda NG\Plugins\Dummy.dll  0000000017140000 - 000000001714B000 v.0.2.0.1 [1 Nov 2022 19:29:10]
C:\Program Files\Miranda NG\Plugins\Facebook.dll  0000000016BC0000 - 0000000016BD6000 v.0.1.0.11 [24 Sep 2022 11:38:06]
C:\Program Files\Miranda NG\Plugins\ICQ.dll  0000000017D20000 - 0000000017D40000 v.0.96.2.3 [23 Oct 2022 19:58:10]
C:\Program Files\Miranda NG\Plugins\Jabber.dll  0000000017F20000 - 0000000017FD4000 v.0.95.11.1 [1 Nov 2022 19:26:44]
C:\Windows\SYSTEM32\DNSAPI.dll  00007FF9D87B0000 - 00007FF9D887A000 v.10.0.19041.1865 [10 Aug 2022 11:41:16]
C:\Program Files\Miranda NG\libs\libsignal.mir  0000000012BA0000 - 0000000012BD0000 [1 Nov 2022 19:26:20]
C:\Windows\SYSTEM32\IPHLPAPI.DLL  00007FF9D8770000 - 00007FF9D87AB000 v.10.0.19041.1865 [10 Aug 2022 11:41:16]
C:\Windows\System32\NSI.dll  00007FF9DA120000 - 00007FF9DA128000 v.10.0.19041.610 [19 Jan 2021 13:36:15]
C:\Program Files\Miranda NG\Plugins\NewEventNotify.dll  0000000018620000 - 000000001862E000 v.0.2.2.5 [20 Oct 2022 21:50:24]
C:\Program Files\Miranda NG\Plugins\PluginUpdater.dll  00000000184A0000 - 00000000184BA000 v.0.2.1.3 [24 Sep 2022 11:36:06]
C:\Program Files\Miranda NG\Plugins\TabSRMM.dll  0000000019320000 - 00000000193A4000 v.3.6.2.6 [20 Oct 2022 21:48:44]
C:\Windows\SYSTEM32\TextShaping.dll  00007FF9AD630000 - 00007FF9AD6DC000 [14 Oct 2021 20:07:14]
C:\Program Files\Miranda NG\Plugins\TopToolBar.dll  0000000018F80000 - 0000000018F91000 v.0.8.0.5 [5 Jun 2022 19:13:22]
C:\Program Files\Miranda NG\Core\stduserinfo.dll  0000000003870000 - 0000000003882000 v.0.96.1.24554 [1 Nov 2022 19:25:10]
C:\Program Files\Miranda NG\Core\stdemail.dll  0000000003890000 - 0000000003899000 v.0.96.1.24554 [1 Nov 2022 19:25:10]
C:\Program Files\Miranda NG\Core\stdfile.dll  00000000038A0000 - 00000000038B5000 v.0.96.1.24554 [1 Nov 2022 19:25:08]
C:\Program Files\Miranda NG\Core\stduihist.dll  00000000038C0000 - 00000000038C9000 v.0.96.1.24554 [1 Nov 2022 19:25:04]
C:\Program Files\Miranda NG\Core\stdautoaway.dll  0000000013000000 - 000000001300A000 v.0.96.1.24554 [1 Nov 2022 19:25:04]
C:\Program Files\Miranda NG\Core\stduseronline.dll  00000000038D0000 - 00000000038D9000 v.0.96.1.24554 [1 Nov 2022 19:25:08]
C:\Program Files\Miranda NG\Core\stdaway.dll  0000000013020000 - 000000001302C000 v.0.96.1.24554 [1 Nov 2022 19:25:06]
C:\Program Files\Miranda NG\Core\stdpopup.dll  0000000013160000 - 0000000013174000 v.0.96.1.24554 [1 Nov 2022 19:30:02]
C:\Windows\system32\dataexchange.dll  00007FF9A6F70000 - 00007FF9A6FAE000 v.10.0.19041.1387 [15 Dec 2021 11:16:16]
C:\Windows\system32\dcomp.dll  00007FF9D5B10000 - 00007FF9D5CF3000 v.10.0.19041.2075 [12 Oct 2022 10:29:02]
C:\Windows\system32\d3d11.dll  00007FF9D4BD0000 - 00007FF9D4E33000 v.10.0.19041.2075 [12 Oct 2022 10:28:57]
C:\Windows\system32\dxgi.dll  00007FF9D7BD0000 - 00007FF9D7CC3000 v.10.0.19041.2075 [12 Oct 2022 10:28:58]
C:\Windows\system32\twinapi.appcore.dll  00007FF9D35A0000 - 00007FF9D37A0000 v.10.0.19041.1865 [10 Aug 2022 11:41:11]
C:\Windows\SYSTEM32\WindowsCodecs.dll  00007FF9D1B00000 - 00007FF9D1CB4000 v.10.0.19041.1706 [12 May 2022 10:52:01]
C:\Windows\SYSTEM32\windows.storage.dll  00007FF9D73D0000 - 00007FF9D7B62000 v.10.0.19041.2251 [9 Nov 2022 12:40:46]
C:\Windows\SYSTEM32\Wldp.dll  00007FF9D8D70000 - 00007FF9D8DA0000 v.10.0.19041.2075 [12 Oct 2022 10:29:02]
C:\Windows\system32\mswsock.dll  00007FF9D8AD0000 - 00007FF9D8B3A000 v.10.0.19041.546 [9 Oct 2020 21:47:52]
C:\Windows\system32\napinsp.dll  00007FF9AD9F0000 - 00007FF9ADA07000 v.10.0.19041.546 [9 Oct 2020 21:47:47]
C:\Windows\system32\pnrpnsp.dll  00007FF9ADA10000 - 00007FF9ADA2B000 v.10.0.19041.546 [9 Oct 2020 21:48:31]
C:\Windows\system32\wshbth.dll  00007FF9C5380000 - 00007FF9C5395000 v.10.0.19041.546 [9 Oct 2020 21:47:43]
C:\Windows\system32\NLAapi.dll  00007FF9D4A60000 - 00007FF9D4A7D000 v.10.0.19041.2193 [9 Nov 2022 12:40:52]
C:\Windows\System32\winrnr.dll  00007FF9AE110000 - 00007FF9AE122000 v.10.0.19041.546 [9 Oct 2020 21:47:57]
C:\Windows\System32\fwpuclnt.dll  00007FF9B4C20000 - 00007FF9B4CA0000 v.10.0.19041.2006 [14 Sep 2022 7:55:45]
C:\Windows\System32\rasadhlp.dll  00007FF9CEF30000 - 00007FF9CEF3A000 v.10.0.19041.546 [9 Oct 2020 21:48:03]
C:\Windows\System32\Windows.Globalization.dll  00007FF9AAB40000 - 00007FF9AACE6000 v.10.0.19041.1865 [10 Aug 2022 11:41:11]
C:\Windows\System32\bcp47mrm.dll  00007FF9AA7E0000 - 00007FF9AA80D000 v.10.0.19041.1503 [11 Feb 2022 11:48:54]
C:\Windows\System32\Bcp47Langs.dll  00007FF9AB350000 - 00007FF9AB3AB000 v.10.0.19041.1566 [9 Mar 2022 0:04:57]
C:\Windows\SYSTEM32\globinputhost.dll  00007FF9AA770000 - 00007FF9AA795000 v.10.0.19041.1806 [15 Jul 2022 11:04:15]
C:\Windows\System32\coml2.dll  00007FF9DAA80000 - 00007FF9DAAF9000 v.10.0.19041.546 [9 Oct 2020 21:47:43]
C:\Windows\SYSTEM32\PROPSYS.dll  00007FF9D4800000 - 00007FF9D48F6000 v.7.0.19041.1741 [15 Jun 2022 0:48:33]
C:\Windows\System32\Windows.UI.dll  00007FF9AA020000 - 00007FF9AA161000 v.10.0.19041.746 [19 Jan 2021 13:36:09]
C:\Windows\System32\WindowManagementAPI.dll  00007FF9D1CC0000 - 00007FF9D1D61000 [10 Jun 2021 18:17:18]
C:\Windows\System32\InputHost.dll  00007FF9AAFD0000 - 00007FF9AB122000 v.10.0.19041.1741 [15 Jun 2022 0:48:33]
C:\Windows\SYSTEM32\edputil.dll  00007FF9A6B70000 - 00007FF9A6B94000 v.10.0.19041.546 [9 Oct 2020 21:47:58]
C:\Windows\SYSTEM32\urlmon.dll  00007FF9CA370000 - 00007FF9CA55D000 v.11.0.19041.2251 [9 Nov 2022 12:40:51]
C:\Windows\SYSTEM32\iertutil.dll  00007FF9CA0B0000 - 00007FF9CA361000 v.11.0.19041.2130 [12 Oct 2022 10:29:06]
C:\Windows\SYSTEM32\srvcli.dll  00007FF9CC750000 - 00007FF9CC778000 v.10.0.19041.1645 [13 Apr 2022 10:16:16]
C:\Windows\SYSTEM32\netutils.dll  00007FF9D8880000 - 00007FF9D888C000 v.10.0.19041.546 [9 Oct 2020 21:47:53]
C:\Windows\System32\Windows.Shell.ServiceHostBuilder.dll  00007FF9AE130000 - 00007FF9AE14D000 v.10.0.19041.746 [19 Jan 2021 13:36:04]
C:\Windows\System32\OneCoreUAPCommonProxyStub.dll  00007FF9CF100000 - 00007FF9CF8CB000 v.10.0.19041.2075 [12 Oct 2022 10:28:57]
C:\Windows\System32\USERENV.dll  00007FF9D9210000 - 00007FF9D923E000 v.10.0.19041.572 [9 Oct 2020 21:47:53]
C:\Windows\System32\Windows.StateRepositoryPS.dll  00007FF9B0D70000 - 00007FF9B0EB6000 v.10.0.19041.2193 [9 Nov 2022 12:40:46]
C:\Windows\SYSTEM32\MLANG.dll  00007FF9A48E0000 - 00007FF9A4922000 v.10.0.19041.746 [19 Jan 2021 13:36:19]
C:\Windows\SYSTEM32\WININET.dll  00007FF9B2B50000 - 00007FF9B3029000 v.11.0.19041.2193 [9 Nov 2022 12:40:51]
C:\Windows\SYSTEM32\profapi.dll  00007FF9D9250000 - 00007FF9D926F000 v.10.0.19041.844 [22 Mar 2021 17:17:48]
C:\Windows\System32\Windows.UI.AppDefaults.dll  00007FF9C9E60000 - 00007FF9C9EAC000 v.10.0.19041.1949 [14 Sep 2022 7:55:42]
C:\Windows\SYSTEM32\policymanager.dll  00007FF9D2B80000 - 00007FF9D2C20000 v.10.0.19041.2193 [9 Nov 2022 12:40:50]
C:\Windows\SYSTEM32\msvcp110_win.dll  00007FF9D8410000 - 00007FF9D849A000 v.10.0.19041.546 [9 Oct 2020 21:47:18]
C:\Windows\System32\CFGMGR32.dll  00007FF9D9A40000 - 00007FF9D9A8E000 v.10.0.19041.1620 [13 Apr 2022 10:16:17]
C:\Windows\System32\appresolver.dll  00007FF9AB180000 - 00007FF9AB210000 v.10.0.19041.1620 [13 Apr 2022 10:16:14]
C:\Windows\System32\SLC.dll  00007FF9D7E50000 - 00007FF9D7E79000 v.10.0.19041.1682 [12 May 2022 10:52:07]
C:\Windows\System32\sppc.dll  00007FF9D7E20000 - 00007FF9D7E45000 v.10.0.19041.1682 [12 May 2022 10:52:07]
C:\Windows\System32\OneCoreCommonProxyStub.dll  00007FF9AE7C0000 - 00007FF9AE83F000 v.10.0.19041.1949 [14 Sep 2022 7:55:41]


-- 
ATeO-Service Mario Pohle     phone: +49 361 241 43 0
Magdeburger Allee 140        fax  : +49 361 241 43 29
99086 Erfurt                 http://www.ateo.de/
USt./VAT-ID: DE 188394558
================================================================
WebDesign, Online-Shops, WebSpace & Domains, Internetzugänge
Sind Ihre Webseiten für Suchmaschinen optimiert? Steigern Sie
jetzt Ihre Besucherzahlen mit ausgefeiltem Internetmarketing:
http://www.ateo.de/suchmaschinenoptimierung.html

**Comment by georgehazan** [comment]
@MPerfurt please, install Miranda with debug symbols and provide another log with details
refer to our Wiki if needed: https://wiki.miranda-ng.org/index.php?title=Crash_reports

**Comment by MPerfurt** [comment]
Hello Georg,
 
i have found the dump fieles.
In the CrashLog.zip are all files.
 
Greatings
 
Mario
 
  
am Donnerstag, 1. Dezember 2022 um 10:22 schrieben Sie:

> @MPerfurt please, install Miranda with debug symbols and provide another log with details
> refer to our Wiki if needed: https://wiki.miranda-ng.org/index.php?title=Crash_reports
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.


-- 
ATeO-Service Mario Pohle     phone: +49 361 241 43 0
Magdeburger Allee 140        fax  : +49 361 241 43 29
99086 Erfurt                 http://www.ateo.de/
USt./VAT-ID: DE 188394558
================================================================
WebDesign, Online-Shops, WebSpace & Domains, Internetzugänge
Sind Ihre Webseiten für Suchmaschinen optimiert? Steigern Sie
jetzt Ihre Besucherzahlen mit ausgefeiltem Internetmarketing:
http://www.ateo.de/suchmaschinenoptimierung.html

**Comment by MPerfurt** [comment]
Now i have all Symbol-Files at the Plugin-Folder for the next crash ;-)
 
 
 
 

am Donnerstag, 1. Dezember 2022 um 16:15 schrieben Sie:

>> i have found the dump fieles. In the CrashLog.zip are all files.
> Yes, but txt file shall not contain lines like (filename not available)
> I need a new report with symbols
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.


-- 
ATeO-Service Mario Pohle     phone: +49 361 241 43 0
Magdeburger Allee 140        fax  : +49 361 241 43 29
99086 Erfurt                 http://www.ateo.de/
USt./VAT-ID: DE 188394558
================================================================
WebDesign, Online-Shops, WebSpace & Domains, Internetzugänge
Sind Ihre Webseiten für Suchmaschinen optimiert? Steigern Sie
jetzt Ihre Besucherzahlen mit ausgefeiltem Internetmarketing:
http://www.ateo.de/suchmaschinenoptimierung.html

**Comment by dartraiden** [comment]
It looks like Github doesn't get attachments when you reply via email client.

Attach attachment via browser to this ticket

**Comment by MPerfurt** [comment]
[crash20221207172613.txt](https://github.com/miranda-ng/miranda-ng/files/10194027/crash20221207172613.txt)
[crash20221207172613.zip](https://github.com/miranda-ng/miranda-ng/files/10194034/crash20221207172613.zip)

**Comment by georgehazan** [comment]
@MPerfurt that bug should have been fixed in the stable version too, try it please
