### ISSUE TITLE
[0.95.13.1] TabSRMM Group Chat Indent function broken

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#2949]
### Expected behavior
Both the first and subsequent lines of the group chat message should be more than a single space away from the timestamp. They should also be indented the same.

### Actual behavior
It looks like just one space separation after timestamp. And on those lines without timestamp, there is less.

When I de-select "Indent the second line", apply, then select it again and apply, the issue is fixed. (Until Miranda is restarted)

### Does it work in stable version?
No, this is the latest stable version. This issue is a regression after the updates from last week.

### Steps to reproduce that behavior
Check "Timestamp only when event time differs", "Prefix Messages with Timestamp", "Indent the second line of a message".

- - -

CPU: AMD Ryzen 7 3700X 8-Core Processor  [AMD64 Family 23 Model 113 Stepping 0] [DEP Enabled] [16 CPUs]
Installed RAM: 32694 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 19043)
Internet Explorer: 9.11.19041.0 (build 919041)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | English/English
Free disk space on Miranda partition: 50843 MBytes

Miranda NG Version: 0.95.13.1 build #23820 (2d52221a17) x64
Build time: 30 Jul 2021 20:43:12
Profile: C:\Users\XXX\AppData\Roaming\Miranda NG\XXX\XXX.dat
Database driver: SQLite database driver
Profile size: 1155072 Bytes
Profile creation date: 24 Jul 2021 19:51:08
Language pack: No language pack installed
Service Mode: No

Active Plugins (16):
¤ AVS.dll v.[b]0.98.1.3[/b] [12 Jun 2021 17:56:52] - Avatar service 
¤ Clist_modern.dll v.[b]0.9.1.11[/b] [12 Jun 2021 17:57:58] - Modern contact list 
¤ CrashDumper.dll v.[b]0.1.0.4[/b] [3 May 2021 21:51:32] - Crash dumper 
¤ Db_autobackups.dll v.[b]0.1.0.5[/b] [30 Jul 2021 20:43:28] - Db autobackuper 
¤ DbChecker.dll v.[b]0.95.13.2[/b] [30 Jul 2021 20:45:16] - Database checker 
¤ DbEditorPP.dll v.[b]4.1.0.2[/b] [19 May 2021 12:05:50] - Database editor++ 
¤ Dbx_mdbx.dll v.[b]0.95.9.1[/b] [21 Jun 2021 11:35:52] - Miranda NG MDBX database driver 
¤ Dbx_sqlite.dll v.[b]0.96.1.2[/b] [30 Jul 2021 20:45:12] - Miranda NG SQLite database driver 
¤ Dummy.dll v.[b]0.2.0.0[/b] [30 Jul 2021 20:44:50] - Dummy protocol 
¤ Import.dll v.[b]0.95.11.1[/b] [30 Jul 2021 20:43:58] - Import contacts and messages 
¤ IRC.dll v.[b]0.96.1.2[/b] [13 Jul 2021 10:55:50] - IRC protocol 
¤ MagneticWindows.dll v.[b]0.0.3.2[/b] [3 May 2021 21:53:46] - Magnetic Windows 
¤ PluginUpdater.dll v.[b]0.2.0.12[/b] [11 Jun 2021 11:31:36] - Plugin updater 
¤ StatusManager.dll v.[b]1.2.0.6[/b] [14 May 2021 13:24:18] - Status manager 
¤ Steam.dll v.[b]0.95.12.2[/b] [11 Jun 2021 11:32:18] - Steam protocol 
¤ TabSRMM.dll v.[b]3.6.1.5[/b] [30 Jul 2021 20:43:34] - TabSRMM 

Protocols and Accounts:
-------------------------------------------------------------------------------
IRC                      6 - Enabled 0 - Disabled  Loaded
STEAM                    1 - Enabled 0 - Disabled  Loaded

Icon Packs:
-------------------------------------------------------------------------------
 a0x_blue.dll [25 May 2007 14:34:20]
 a0x_bw.dll [25 May 2007 14:34:26]
 a0x_green.dll [25 May 2007 14:34:32]
 a0x_main.dll [25 May 2007 14:34:38]
 a0x_orange.dll [25 May 2007 14:34:46]
 a0x_purple.dll [25 May 2007 14:34:52]
 a0x_red.dll [25 May 2007 14:34:58]
 a0x_set1_grey.dll [25 May 2007 14:35:16]
 a0x_weather.dll [25 May 2007 14:35:04]
 a0x_yellow.dll [25 May 2007 14:35:08]
 Proto_Dummy.dll [30 Jul 2021 20:45:50]
 Proto_IRC.dll [13 Jul 2021 10:58:20]
 Proto_MetaContacts.dll [30 Jul 2021 20:45:50]
 Proto_Steam.dll [11 Jun 2021 11:33:16]
 Proto_Tox.dll [25 Mar 2021 14:56:08]
 TabSRMM_icons.dll [30 Jul 2021 20:45:48]
 Toolbar_icons.dll [12 Jun 2021 17:59:30]

**Comment by Tharn** [comment]
Also requires regular font, not monospace.

**Comment by georgehazan** [comment]
@Tharn investigation showed that timestamp is tab separated from the main text, so its length may vary from one chat to another, And that's how it's been working from the very beginning

**Comment by Tharn** [comment]
Yes, I also have to clarify this bug.

The variance did not happen from one window to the other. Variance happened as follows:

1. Open a group chat, see regular separation between time & text. Meaning tab distance or roughly 2 spacebar distance.
2. Something happened DURING the chat that made the window forget proper distance, it is now only 1 spacebar distance AND also not uniform anymore. Meaning it now varies with wider or more narrow letters displaying time, i.e. 11:11 vs 00:00.
3. Now, when I un-select "Prefix" and "Indent" options as indicated in the OP, and then re-enable and apply, the faulty window has correct distances once again.

This all happened after a certain update, and after I un-selected the 2 options and re-applied them, the bug did not occur anymore. However, people who do not do fresh installs and update regularly will run into this bug and unless they know the fix, it will keep happening until fixed.
