### ISSUE TITLE
Discord: Discord account disabled for suspicious activity

### ISSUE THREAD

**Issue by tealkami** [miranda-ng/miranda-ng#2959]
Definitely because of Miranda NG, need to change password, for now ...
So... Please update Discord plugin, bet it is some old code as was/is in Facebook plugin

I got this "change password" on 2 accounts, one is without any servers logged in chrome, other is logged on the windows app and on plenty servers. They got the "Discord account disabled for suspicious activity" e-mail on the same time.

**Comment by georgehazan** [comment]
@tealkami yes, and if you change password - does it work?

**Comment by tealkami** [comment]
Yes, after changing passwords, it works.
So... yea... this ticket should be more a "feature request" than a bug: "Please update the code for the future, don't let it hanging as the facebook plugin, thank you"
