### ISSUE TITLE
IRC перестал заходить на irc.libera.chat 

### ISSUE THREAD

**Issue by ArchyBaldd** [miranda-ng/miranda-ng#2960]
вчера 02.09.2021 миранда перестала подключаться к irc.libera.chat.
При попытке подключится в логах следующее:

в файле Server_ IRC.log:
[03 сен 21 10:15] ! Соединение с %bIRC%B (irc.libera.chat: 6697)
[03 сен 21 10:15] ! %i%b*Отключён*

в файле netlog.txt
[2021-09-03 10:15:02 1DB4] [IRC] Connection request to irc.libera.chat:6697 (Flags 0)....
[2021-09-03 10:15:02 1DB4] [IRC] (00000000036E2A80) Connecting to server irc.libera.chat:6697....
[2021-09-03 10:15:02 1DB4] [IRC] (00000000036E2A80) Connecting to ip 64.86.243.186:6697 ....
[2021-09-03 10:15:02 1DB4] [IRC] (1864) Connected to irc.libera.chat:6697
[2021-09-03 10:15:02 1DB4] [IRC] (1864 irc.libera.chat) Starting SSL/TLS negotiation
[2021-09-03 10:15:02 1DB4] SSL negotiation failure: error:00000005:lib(0):func(0):DH lib (5)
[2021-09-03 10:15:02 1DB4] [IRC] (1864 irc.libera.chat) Failure to negotiate SSL/TLS connection
[2021-09-03 10:15:02 1DB4] [IRC] (00000000036E2A80:1864) Data sent
CAP REQ :sasl
[2021-09-03 10:15:02 2C0C] [IRC] (00000000036E2A80:1864) Connection closed internal
[2021-09-03 10:15:02 2C0C] [IRC] (00000000036E2A80:4294967295) Connection closed

**Comment by georgehazan** [comment]
что-то перекрыло доступ извне на этот IP адрес, либо сервер заблочил этот IP сам

**Comment by ArchyBaldd** [comment]
но телнет показывает что порт доступен на этом IP:
telnet 64.86.243.186 6697
нет ответа что данный порт заблокирован как например если пробовать другой ( например, следующий по порядку порт) 6698 :
C:\>telnet 64.86.243.186 6698
Подключение к 64.86.243.186...Не удалось открыть подключение к этому узлу, на порт 6698: Сбой подключения

**Comment by dartraiden** [comment]
Чудес же не бывает, прямо сейчас прекрасно из Миранды сидим в #miranda-ng

https://wiki.miranda-ng.org/index.php?title=Version_information покажите

**Comment by ArchyBaldd** [comment]
я подключился с тем же инетом с другого клиента (irssi) - и на irc.libera.chat заходит там отлично:
 Irssi v1.1.3 - http://www.irssi.org
14:14 -!-  ___           _
14:14 -!- |_ _|_ _ _____(_)
14:14 -!-  | || '_(_-<_-< |
14:14 -!- |___|_| /__/__/_|
14:14 -!- Irssi v1.1.3 - http://www.irssi.org
14:16 -!- Irssi: Looking up irc.libera.chat
14:16 -!- Irssi: Connecting to irc.libera.chat [188.240.145.101] port 6697
14:16 -!- Irssi: Certificate Chain:
14:16 -!- Irssi:   Subject: CN: osmium.libera.chat
14:16 -!- Irssi:   Issuer:  C: US, O: Let's Encrypt, CN: R3
14:16 -!- Irssi:   Subject: C: US, O: Let's Encrypt, CN: R3
14:16 -!- Irssi:   Issuer:  C: US, O: Internet Security Research Group, CN: ISRG Root X1
14:16 -!- Irssi:   Subject: C: US, O: Internet Security Research Group, CN: ISRG Root X1
14:16 -!- Irssi:   Issuer:  O: Digital Signature Trust Co., CN: DST Root CA X3
14:16 -!- Irssi: Protocol: TLSv1.2 (256 bit, ECDHE-RSA-AES256-GCM-SHA384)
14:16 -!- Irssi: EDH Key: 521 bit ECDH: secp521r1
14:16 -!- Irssi: Public Key: 4096 bit RSA, valid from Aug  2 05:05:43 2021 GMT to Oct 31 05:05:41 2021 GMT
14:16 -!- Irssi: Public Key Fingerprint:
          EE:44:F3:2A:AE:B4:AB:60:1A:9F:A4:C3:EF:24:C7:0D:3C:96:14:7F:1A:3C:3D:34:C6:E1:D9:A1:98:1F:50:38 (SHA256)
14:16 -!- Irssi: Certificate Fingerprint:
          01:D3:86:34:78:4C:A8:0F:BD:67:63:26:FC:7B:96:EC:A3:6A:49:46:13:9E:06:F4:E4:F6:4C:43:03:60:26:37 (SHA256)
14:16 -!- Irssi: Connection to irc.libera.chat established
14:16 !osmium.libera.chat *** Checking Ident
14:16 !osmium.libera.chat *** Looking up your hostname...
------------------------------------
а у миранды опять:
[2021-09-03 15:15:06 1C50] [IRC] Connection request to irc.libera.chat:6697 (Flags 0)....
[2021-09-03 15:15:06 1C50] [IRC] (0000000003076710) Connecting to server irc.libera.chat:6697....
[2021-09-03 15:15:06 1C50] [IRC] (0000000003076710) Connecting to ip 188.240.145.102:6697 ....
[2021-09-03 15:15:06 1C50] [IRC] (3000) Connected to irc.libera.chat:6697
[2021-09-03 15:15:06 1C50] [IRC] (3000 irc.libera.chat) Starting SSL/TLS negotiation
[2021-09-03 15:15:06 1C50] SSL negotiation failure: error:00000005:lib(0):func(0):DH lib (5)
[2021-09-03 15:15:06 1C50] [IRC] (3000 irc.libera.chat) Failure to negotiate SSL/TLS connection
[2021-09-03 15:15:06 1C50] [IRC] (0000000003076710:3000) Data sent
CAP REQ :sasl
[2021-09-03 15:15:06 2FF8] [IRC] (0000000003076710:3000) Connection closed internal
[2021-09-03 15:15:06 2FF8] [IRC] (0000000003076710:4294967295) Connection closed

Он же пишет что "SSL negotiation failure: error:" - может там таймауты какие нить на SSL/TLS или какие нить цепочки сртификатов надо грузить?

**Comment by dartraiden** [comment]
Если Миранла старая, то там системное крипто используется, поэтому я и спрашивал про версию.

**Comment by ArchyBaldd** [comment]
Извините,  про версии не увидел (заработался видать). Вот:
--------------------------------------
CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz [Intel64 Family 6 Model 58 Stepping 9] [DEP Enabled] [8 CPUs]
Installed RAM: 16262 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 19043)
Internet Explorer: 9.11.19041.0 (build 919041)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian
Free disk space on Miranda partition: 204991 MBytes

Miranda NG Version: 0.95.13.1 build #23825 (0655388b2a) x64
Build time: 29 Aug 2021 17:49:14
Profile: D:\ArchyBald\docs\miranda_ArchyBald\Profiles\ArchyBald\ArchyBald.dat
Database driver: MDBX database driver
Profile size: 20971520 Bytes
Profile creation date: 3 Sep 2021 9:10:48
Language pack: Russian (RU) [0419]
Service Mode: No

Active Plugins (30):
¤ AVS.dll v.0.98.1.3 [13 Jun 2021 22:01:58] - Avatar service 
¤ Clist_modern.dll v.0.9.1.11 [13 Jun 2021 22:02:44] - Modern contact list 
¤ Contacts.dll v.1.6.0.0 [13 Jun 2021 22:02:00] - Send/receive contacts 
¤ CrashDumper.dll v.0.1.0.4 [3 May 2021 21:51:32] - Crash dumper 
¤ CryptoPP.dll v.1.0.4.8 [16 May 2021 19:21:14] - Crypto++ 
¤ Db_autobackups.dll v.0.1.0.5 [29 Aug 2021 17:49:32] - Db autobackuper 
¤ DbChecker.dll v.0.95.13.2 [29 Aug 2021 17:51:16] - Database checker 
¤ DbEditorPP.dll v.4.1.0.2 [19 May 2021 12:05:50] - Database editor++ 
¤ Dbx_mdbx.dll v.0.95.9.1 [21 Jun 2021 11:35:52] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.0.95.8.1 [13 Jun 2021 22:02:02] - Miranda NG mmap database driver 
¤ Dbx_sqlite.dll v.0.96.1.2 [29 Aug 2021 17:51:08] - Miranda NG SQLite database driver 
¤ Dummy.dll v.0.2.0.0 [29 Aug 2021 17:50:44] - Dummy protocol 
¤ Facebook.dll v.0.1.0.11 [13 Jun 2021 22:04:04] - Facebook 
¤ Fingerprint.dll v.0.2.0.1 [3 May 2021 21:51:48] - Fingerprint NG 
¤ GG.dll v.0.95.11.1 [13 Jun 2021 22:02:28] - Gadu-Gadu protocol 
¤ historypp.dll v.1.5.1.5 [15 Jun 2021 18:12:26] - History++ 
¤ ICQ.dll v.0.96.1.4 [12 Aug 2021 11:39:24] - ICQ-WIM protocol 
¤ IEView.dll v.1.6.0.4 [13 Jun 2021 22:02:12] - IEView 
¤ Import.dll v.0.95.11.1 [29 Aug 2021 17:50:00] - Import contacts and messages 
¤ IRC.dll v.0.96.1.2 [7 Aug 2021 10:34:02] - IRC protocol 
¤ Nudge.dll v.0.2.0.2 [6 Apr 2021 20:48:28] - Nudge 
¤ PluginUpdater.dll v.0.2.0.12 [13 Jun 2021 22:02:52] - Plugin updater 
¤ PopupPlus.dll v.2.1.1.17 [16 May 2021 19:20:04] - Popup plus 
¤ SecureIM.dll v.1.0.12.6 [6 Apr 2021 20:48:36] - SecureIM 
¤ SkypeWeb.dll v.0.95.13.3 [29 Aug 2021 17:51:02] - Skype protocol (Web) 
¤ SmileyAdd.dll v.0.3.2.1 [16 May 2021 19:19:34] - SmileyAdd 
¤ StatusManager.dll v.1.2.0.6 [16 May 2021 19:20:44] - Status manager 
¤ TabSRMM.dll v.3.6.1.5 [29 Aug 2021 17:49:30] - TabSRMM 
¤ Tipper.dll v.2.1.0.7 [13 Jun 2021 22:02:24] - Tipper 
¤ TopToolBar.dll v.0.8.0.5 [6 Apr 2021 20:48:46] - TopToolBar 

Unloadable Plugins (15):
¤ BattleShip.dll v.0.0.0.0 [4 Mar 2004 9:27:58] - <unknown> 

¤ changeinfo.dll v.0.0.0.0 [16 Jun 2005 13:39:02] - <unknown> 

¤ ContactsEx.dll v.0.0.0.0 [24 Nov 2002 19:16:50] - <unknown> 

¤ ContactVisibility.dll v.0.0.0.0 [12 May 2003 21:34:38] - <unknown> 

¤ DataAsMessage.dll v.0.0.0.0 [6 Oct 2007 17:52:12] - <unknown> 

¤ GoMoku.dll v.0.0.0.0 [13 Mar 2004 14:55:56] - <unknown> 

¤ imgdecoder.dll v.0.0.0.0 [11 Sep 2005 18:08:36] - <unknown> 

¤ loadavatars.dll v.0.0.0.0 [6 May 2007 14:10:20] - <unknown> 

¤ look-in.dll v.0.0.0.0 [24 Apr 2005 1:40:42] - <unknown> 

¤ mContacts.dll v.0.0.0.0 [21 Aug 2004 21:34:12] - <unknown> 

¤ png2dib.dll v.0.0.0.0 [6 May 2007 14:05:54] - <unknown> 
    Plugin statically linked to missing module: zlib.dll

¤ SMS (Unicode).dll v.0.0.0.0 [20 Jan 2009 23:00:04] - <unknown> 

¤ updater.dll v.0.0.0.0 [19 Mar 2011 22:31:02] - <unknown> 

¤ WhiteboardW.dll v.0.0.0.0 [6 Oct 2007 17:55:44] - <unknown> 

¤ XStatusNotify.dll v.0.0.0.0 [12 Jan 2008 20:10:52] - <unknown> 


Protocols and Accounts:
-------------------------------------------------------------------------------
ICQ                      1 - Enabled 0 - Disabled  Loaded
IRC                      1 - Enabled 0 - Disabled  Loaded

Icon Packs:
-------------------------------------------------------------------------------
 Fp_icons.dll [3 May 2021 21:56:04]
 HistoryPP_icons.dll [15 Jun 2021 18:12:16]
 jabber_xstatus.dll [11 Jul 2008 1:18:06]
 proto_AIM.dll [13 Dec 2011 20:13:20]
 proto_conn_MRA.dll [24 Feb 2010 9:28:01]
 Proto_Discord.dll [13 Jun 2021 22:04:38]
 Proto_Dummy.dll [29 Aug 2021 17:51:42]
 Proto_Facebook.dll [13 Jun 2021 22:04:40]
 Proto_GG.dll [13 Jun 2021 22:04:34]
 Proto_ICQ.dll [12 Aug 2021 11:40:10]
 Proto_IRC.dll [7 Aug 2021 10:36:28]
 Proto_Jabber.dll [21 Jun 2021 11:36:12]
 Proto_MetaContacts.dll [29 Aug 2021 17:51:42]
 Proto_MRA.dll [12 Aug 2021 11:40:10]
 Proto_MSN.dll [5 Jun 2019 2:02:42]
 Proto_Skype.dll [29 Aug 2021 17:51:42]
 proto_YAHOO.dll [13 Dec 2011 20:13:20]
 SecureIM_icons.dll [6 Apr 2021 20:50:34]
 TabSRMM_icons.dll [29 Aug 2021 17:51:40]
 tipper.dll [19 Nov 2009 15:54:10]
 Toolbar_icons.dll [13 Jun 2021 22:04:36]
 xStatus_Jabber.dll [21 Jun 2021 11:36:12]
 xstatus_MRA.dll [24 Feb 2010 9:28:10]

**Comment by ArchyBaldd** [comment]
Про ситуацию с крипто, если такие ситуации могут возникать значит в логах мне кажется и надо писать на такой случай: мол "сервер требует крипто-шифрование, которое поддерживается лишь в win10". Или например "для требуемого шифрования требуются следующие установленные программы/плагины/компоненты".

**Comment by ArchyBaldd** [comment]
А я кстати вспомнил что как раз 2го числа ставил обновления на винду - может это как раз и повлияло?
![2021-09-03_18-38-52](https://user-images.githubusercontent.com/61453667/132031953-627067ef-d5d4-46bf-a32f-a9c744c31f8a.png)

**Comment by dartraiden** [comment]
Нет, вряд ли влияет, т.к. в 0.95.13 уже используется OpenSSL вместо WinCrypto.

**Comment by dartraiden** [comment]
@georgehazan, у меня не заходит по TLS

```
[0:12:04 0E9C] [IRC_1] Connection request to irc.libera.chat:6697 (Flags 0)....
[0:12:04 0E9C] [IRC_1] (00000000055CBBE0) Connecting to server irc.libera.chat:6697....
[0:12:04 0E9C] [IRC_1] (00000000055CBBE0) Connecting to ip 64.86.243.186:6697 ....
[0:12:04 0E9C] [IRC_1] (1552) Connected to irc.libera.chat:6697
[0:12:04 0E9C] [IRC_1] (00000000055CBBE0:1552) Data sent
NICK dartraiden
[0:12:04 0E9C] [IRC_1] (00000000055CBBE0:1552) Data sent
USER Miranda DARTRAIDEN-PC server :a@a.ru
[0:12:05 22A0] [IRC_1] (00000000055CBBE0:1552) Connection closed internal
[0:12:05 22A0] [IRC_1] (00000000055CBBE0:4294967295) Connection closed
```

могу дать профиль

**Comment by ArchyBaldd** [comment]
с утра не заходилось, а прям щас нормально зашел на irc.libera.chat в миранде! Даже не знаю в какую сторону думать...

**Comment by georgehazan** [comment]
@ArchyBaldd 
если погуглить строку error:00000005:lib(0):func(0):DH lib (5), то вываливается куча ссылок на одну и ту же ошибку 10054  - remote host принудительно разорвал соединение. Обычно это проделки файрволла или админа корпоративной сетки, о чем я и написал в первом ответе, или потеря пакетов, которую SSL физически не переносит

**Comment by georgehazan** [comment]
> Может потому что я до этого только что поставил irssi на cygwin и зашел с него на irc.libera.chat... (может он прописал какие нибудь сертификаты?)

нет, openssl в Миранде никак на cygwin реагировать не может
