### ISSUE TITLE
Hidden contacts are added to the contact list multiple times

### ISSUE THREAD

**Issue by DayZTLD** [miranda-ng/miranda-ng#2962]
>>What did you expect?

I need to hide these users, they are not removed from the contact list, appears there again and again, every start Miranda!

>>What did you get instead?

With each new launch of Miranda and going online, some contacts appear again and again in the contact list, I block them, delete them, but they are visible again! the screenshot will say more ...

Why do these contacts appear in my list, how can they even be added there themselves? maybe I do not understand something and set it up wrong?

### Does it work in stable version?

New stable build released: 0.95.13.1 ...  in the expert the same thing!

### ![20210906_002](https://user-images.githubusercontent.com/45307969/132254075-654a5576-e371-4c2c-ace6-18693f412505.png)
![20210906_001](https://user-images.githubusercontent.com/45307969/132254082-bfd2285b-c84e-48f7-b310-52c8fda811c0.png)

[VersionInfo.txt](https://github.com/miranda-ng/miranda-ng/files/7120874/VersionInfo.txt)

2021.09.08 Update 1
[CrashLog_2021.09.08.zip](https://github.com/miranda-ng/miranda-ng/files/7124437/CrashLog_2021.09.08.zip)

2021.09.08 Update 2
I had a version that these are just the same nicknames, but here, see for yourself - this is the same messenger number:
![20210908_001](https://user-images.githubusercontent.com/45307969/132468357-8753c0aa-138e-4ec2-ab95-5d11d722eb06.png)

**Comment by georgehazan** [comment]
в ICQ когда-то был баг с размножением контактов, его давно уже нет с нами.

что надо сделать:
- запустить редактор базы в сервисном режиме (miranda32.exe /svc:dbeditorpp)
- зайти в список контактов так, чтобы видеть их идентификаторы справа
- убить задвоенные контакты с наибольшими идентификаторами
- enjoy

**Comment by DayZTLD** [comment]
georgehazan, я попробую конечно предложенный метод, но проблема в том, что база очень свежая, т.е. я взял и скачанную Миранду запустил, создав всё с нуля, в профиле uin + пароль, не тащил со старой базы контакты, историю и т.д., все контакты видимо хранятся на сервере icq (не особо шарю во всех этих тех.премудростях, пишу как понимаю)))

**Comment by dartraiden** [comment]
> все контакты видимо хранятся на сервере icq

Как раз те, что светло-серые (на скриншотах зачеркнутые) это контакты, которые почему-то есть в базе, но отсутствуют на сервере.

**Comment by DayZTLD** [comment]
> _Также, на правах бреда: к аське почта @mail.ru не привязана ли?_

dartraiden, гениально! думаете это от туда контакты? а как избавится теперь от них? уж не спрашиваю как они добавили мой номер к себе, не буду перегружать вас вопросами)))
**да, UIN привязан к mail.ru !!!**

**Comment by dartraiden** [comment]
Для начала, привязать к аське другую почту, не мейлрушную.

**Comment by DayZTLD** [comment]
> Так вы сами почту @mail.ru связали с аськой, указав почту в настройках аккаунта аськи на сайте. Поскольку ICQ и Mail.ru Agent это очень похожие сущности, Миранда, видимо, подтягивает и контакты агента.

ну вот, этот Agent видимо сам своей жизнью и жил... пока вы мне глаза не открыли! Наверняка я хоть один раз заходил в почту через браузер а там этот Agent... Но вообще то я пользуюсь почтовой программой. Ну это так, вдруг вы ещё кому-то будете помогать, просто для информации. Для будущих, так сказать версий происходящего, вполне реальных, как оказалось! ;)

> Для начала, [привязать](https://icq.com/login) к аське другую почту, не мейлрушную. Старую отвязать. Потом влогиниться в аську через Миранду и поудалять лишние контакты.

Благодарю, я попробую всё это проделать и отпишусь чем дело кончилось.
dartraiden , удачи тебе, добрый человек! Ну или умный. Умный и добрый. :)

**Comment by dartraiden** [comment]
Да, отпишитесь, если я прав, то это баг Миранды и его надо будет исправить.

**Comment by DayZTLD** [comment]
> Да, отпишитесь, если я прав, то это баг Миранды и его надо будет исправить.

увы, не понял как "отвязать" почту, но что интересно: зашел через web интерфейс и там НЕТ этих контактов! Там есть список "забаненых" контактов, я переписал от туда номера контактов: - да, они в Миранде есть и с ними никогда проблем не было - они жестко забанены и в контакт-лист никогда не "впрыгивают", всегда остаются "игнорируемыми".

**Comment by dartraiden** [comment]
Они убрали возможность изменить почту через личный кабинет :(

В поддержку: https://www.icq.com/support

>  и там НЕТ этих контактов

Потому что это  баг Миранды.
