### ISSUE TITLE
ICQ: если к аське привязана почта @mail.ru, то при логине прилетают контакты не только аськи, но и агента

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2964]
При каждом логине контакты от агента радостно влетают в аську, если к аське привязана почта @mail.ru
Удалить их не получится, они прилетят опять. Оф. клиент таким не страдает: он грузит только асечные контакты.

Отвязать почту затруднительно, т.к. для этого нужно теребить поддержку.

Воспроизвести легко:
- где-то добыть аську, к которой привязана почта @mail.ru
- залогиниться с этой почтой в официальный агент, добавить несколько контактов
- залогиниться с этой аськой в миранду

**Comment by JeanPaulLucien** [comment]
@dartraiden если заведешь аську для всех, то я проверю.

**Comment by dartraiden** [comment]
К аськам сейчас нельзя прикреплять почты.

**Comment by dartraiden** [comment]
Предлагаю сделать, как в официальном клиенте:
- если учётка протокола ICQ, то принимать в качестве логина лишь UIN или номер телефона
- если учётка MRA, то принимать в качестве логина лишь почту или номер телефона
