### ISSUE TITLE
VK: сообщения о действиях со страницей не работают в русской локале.

### ISSUE THREAD

**Issue by jawhien** [miranda-ng/miranda-ng#2965]
Некоторые сообщения, которые отправляются, когда пользователь совершает действия со своей страницей не переводятся правильно, хотя в файле локализации они присутствуют.

[User restored control over own page]
Пользователь восстановил контроль над своей страницей
[User was deactivated (deleted)]
Пользователь деактивирован (удалён)
[User was deactivated (banned)]
Пользователь деактивирован (забанен)

### Expected behavior
Отображение сообщений, как в файле локализации.

### Actual behavior
Отображаются несколько пробелов и скобки
   ()
примерно так.

### Does it work in stable version?
нет.

### Steps to reproduce that behavior
Необходимо чтобы пользователь совершил эти действия при включённой локализации.

**Comment by ElzorFox** [comment]
Не подтверждаю. Возможно какие-то специфичные условия воспроизведения нужны (журнал чатлога например).

![2021-10-16_17-37-10](https://user-images.githubusercontent.com/22792799/137587833-a9fd4ebf-2cce-4762-8b25-bdb0e9bc48c6.png)
.
