### ISSUE TITLE
Icons are missing in IcoLib for ModernOpt plugin

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#297]
**Reported by dracosha on 20 May 2014 18:07 UTC**
Some icons are missing in IcoLib for ModernOpt plugin.
Missing icons underlined with red color on screenshot.

![screenshot 2014-05-20 0012](https://cloud.githubusercontent.com/assets/5046855/21104807/feb1f626-c098-11e6-9d90-3d6b47756e17.png)

**Comment by georgehazan** [comment]
**Modified by mataes on 27 May 2014 04:48 UTC**

**Comment by Mataes** [comment]
plugin moved to deprecated
