### ISSUE TITLE
Facebook - Error 406

### ISSUE THREAD

**Issue by Dvorak-Stepan** [miranda-ng/miranda-ng#2970]
I changed my Facebook password today. Since then, I can't log in to Miranda via Facebook. It still reports error 406. Also tried a completely clean install of Miranda. I use 2FA on Facebook. Confirmation doesn't help and I have nowhere to write the control code.

**Comment by dartraiden** [comment]
Duplicate of https://github.com/miranda-ng/miranda-ng/issues/2163

**Comment by dartraiden** [comment]
Also see https://github.com/miranda-ng/miranda-ng/issues/2207#issuecomment-585791499

**Comment by Dvorak-Stepan** [comment]
Turn off 2FA? Good joke!
I'd rather wait and see if anything changes over time.
