### ISSUE TITLE
Discord: Could you please change how Miranda delete contacts from Discord server? instead deleting just hide the contact

### ISSUE THREAD

**Issue by tealkami** [miranda-ng/miranda-ng#2977]
When you unfriend/block someone in Discord or if the other person unfriend/block you, it will hide the contact (in official client/website), but if you search for the person or know the user#0000 name, it will show the whole history with that person.

But Miranda just delete the contact, all the history and notes, everything. So when in Discord you "unhide" the hidden contact, Miranda will add the contact back and load only the newest history.

**Comment by dartraiden** [comment]
Select contact -> Delete -> tick "Hide" checkbox.

**Comment by tealkami** [comment]
Did you even read what I did write ?

**Comment by dartraiden** [comment]
ah, I thought that you want to delete the contact, but not friend it

**Comment by dartraiden** [comment]
Miranda can download no more than a certain number of messages from the server, while the server has no limit for the official client.
