### ISSUE TITLE
Discord: Could you please change how Miranda HANDLE "delete contacts" from Discord server request ? instead deleting just hide the contact

### ISSUE THREAD

**Issue by tealkami** [miranda-ng/miranda-ng#2978]
When you unfriend/block someone **IN DISCORD OFFICIAL CLIENT/WEBSITE** or if the other person unfriend/block you(**IN DISCORD OFFICIAL CLIENT/WEBSITE**), it will **hide the contact** (in official client/website), but if you search for the person or know the user#1234 name, it will show the whole history with that person(IN DISCORD OFFICIAL CLIENT/WEBSITE).

But Miranda just delete the contact, all the history and notes, everything. So when in Discord you "unhide" the hidden contact, Miranda will add the contact back and load only the newest history.

**Comment by dartraiden** [comment]
If Miranda just hide contact, it will remain in roster, so it will be added to server roster on next login.

A possible solution would be the option "do not synchronize local roster with the server", but this will significantly complicate the simultaneous use of Miranda and the official client, since the official client will not know anything about adding / removing contacts in Miranda and vice versa

**Comment by tealkami** [comment]
what about "do not synchronize local roster with the server**, if contact is hidden**" ?

**Comment by dartraiden** [comment]
Can you try "Load server history" contact menu item?

It should load the whole history. If not, then this is Miranda's bug

**Comment by tealkami** [comment]
and how "load server history" will reload Miranda settings for that contact ? ...

It's very stupid that some command from server delete miranda contact with all the settings/notes/additional info
I don't want some automatic deletion of anything in MirandaNG, before you could set up Miranda how user like it, not as someone other "say so"

**Comment by dartraiden** [comment]
If this item downloads the entire history, then after re-adding (unfriend->friend) the contact, you can download the entire history from the server. Thus it solves the problem of deleted history.

We discussed this with @georgehazan, he is strictly against adding crutches with ignoring the roster

**Comment by tealkami** [comment]
Discord itself don't delete anything , history, personal notes, it just hide the contact, when you search for it, you can look all the history, see the personal notes, everything.

What about if... When Miranda **receive that request from server**, which delete contact in Miranda, **it would instead just do NOTHING** ? Like... it would ignore that one request, instead deleting the contact. That should not be that hard to do.
I do have contact which were hidden, find them, and I have in Miranda contact which should be "hidden" and everything works

**Comment by dartraiden** [comment]
>  it just hide the contact

Nope, it deletes contact locally and redownloads all from the server if necessary.

**Comment by tealkami** [comment]
> > it just hide the contact
> 
> Nope, it deletes contact locally (from local client db) and obtains all info from the server if necessary (if you perform a search, etc). The official client is heavily cloud-based, Miranda is not. Also, official client notes don't equal Miranda notes. Miranda notes (Contact menu → Info → Notes → My notes) are protocol independent, they are just entries in a local database and never sync with the server.
> 

In that first paragraph where you cut out that word, I wasn't talking about Miranda at all, it was about DISCORD the official app/website/server/database/handling ...  Are you even able to read whole text ? or it is your thing to read like "out of context" (this is not the first time, when you read only "parts"...) ? In that first paragraph I just did repeated my first paragraph in my first post ...

> When you unfriend/block someone **IN DISCORD OFFICIAL CLIENT/WEBSITE** or if the other person unfriend/block you(**IN DISCORD OFFICIAL CLIENT/WEBSITE**), it will **hide the contact** (in official client/website), but if you search for the person or know the user#1234 name, it will show the whole history with that person(IN DISCORD OFFICIAL CLIENT/WEBSITE).

--------------------

> You mentioned history and notes , what else is lost when you delete a contact?

seenplugin.dll - Last seen
Miranda Notes (you know that local one...)
and all other addons contact settings which I don't personaly use, but there are definitly more.

+ Problem is that the "Load History" doesn't load properly everything, and if it would load all the history, it would takes hours...

--------------------

**Where is the problem** to make it **ignore that command/request from server**, which make delete contact in Miranda ?
 
I use Miranda for archive and search (when I need to find something it is the fastest way), and when it delete stuff without my consent, what is the point to use Miranda... 

--------------------

Btw other thing which "blow my mind"(in very negative way) you did make Discord groups(those you see in app/website on official discord) as group contact in Miranda(those which are in Miranda NG localy in *.dat), but you didn't make it , that when you open the contact it would load the history, or anything ... was pretty much useless thing, it didn't load the group name, it looked like bug ...
but when I deleted the **Miranda NG group contact**... Miranda did send command to leave that group , which I was the owner ... without asking or anything ...

**Comment by tealkami** [comment]
What about make toggle for discord auto deleting : "Instead deleting the contact it will turn into metacontact" ?

and of course the "Load server History" doesn't load whole history , only last 100 messages ...

**Comment by dartraiden** [comment]
Discord has effectively deprived us of the ability to develop a protocol, see https://github.com/miranda-ng/miranda-ng/issues/2994

**Comment by dartraiden** [comment]
https://github.com/miranda-ng/miranda-ng/issues/2994

**Comment by tealkami** [comment]
So will this keep the contact, or make it into metacontact at least ?
