### ISSUE TITLE
Discord: privates containing multiple participants are partially broken

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2980]
Regression from https://github.com/miranda-ng/miranda-ng/commit/1a5dc583b048727752b8f72df676ec408908041f

1) missing name ('Unknown contact')
2) missing nicks (username#1234 instead of nick)
3) missing history in log (history is present in db)

**Comment by dartraiden** [comment]
https://github.com/miranda-ng/miranda-ng/issues/2994

**Comment by georgehazan** [comment]
All that is fixed
