### ISSUE TITLE
Icons are missing in IcoLib for xStatus notify plugin

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#299]
**Reported by dracosha on 20 May 2014 18:28 UTC**
Some icons are missing in IcoLib for xStatus notify plugin.
Missing icons underlined with red color on screenshot.

![screenshot 2014-05-20 0014](https://cloud.githubusercontent.com/assets/5046855/21104856/21310624-c099-11e6-9e76-2f7298425be5.png)

**Comment by georgehazan** [comment]
**Modified by mataes on 27 May 2014 04:49 UTC**

**Comment by Mataes** [comment]
fixed in f29a852
