### ISSUE TITLE
Смена языка "на лету" не поддерживается для названий подключений

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2996]
![изображение](https://user-images.githubusercontent.com/5046855/150210917-62b7e1cd-fc0c-4a4f-a592-ca32d4b631c7.png)

Запуск с русским ленгом → изменение языка на английский → открытие этого окна
"Miranda core logging" стало на английском, а вот у протоколов всё осталось на русском

**Comment by georgehazan** [comment]
разумеется. оно переводится один раз при старте плагина, и более не переводится. Переводиться оно перестает в тот момент, когда в середину подставляется имя протокола
