### ISSUE TITLE
Плагин ShlExt не может корректно получить повышенные права

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2998]
Плагин ShlExt при каждом запуске сообщает, что ему нужны права администратора, чтобы встроиться в оболочку. Затем он запрашивает права через UAC, но, получив одобрение, в оболочку не встраивается. Возможно, регрессия из-за последних изменений в Миранде, связанных с механизмом повышения прав.

Корректно встраивается, только если Миранда изначально запущена от админа. Если же запускать от обычного пользователя, случается описанный выше баг.

**Comment by georgehazan** [comment]
а как он может встроиться куда-то, если права эскалируются у pu_stub.exe, а вовсе не у ShlExt.dll
