### ISSUE TITLE
Icons are missing in IcoLib for StartupStatus plugin

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#300]
**Reported by dracosha on 20 May 2014 19:53 UTC**
Some icons are missing in IcoLib for StartupStatus plugin.
Missing icons underlined with red color on screenshot.

![screenshot 2014-05-20 0018](https://cloud.githubusercontent.com/assets/5046855/21104874/3368f70c-c099-11e6-86e0-95cacacad4d7.png)

**Comment by georgehazan** [comment]
**Modified by mataes on 27 May 2014 04:51 UTC**

**Comment by Mataes** [comment]
already fixed
