### ISSUE TITLE
WhenWasIt: remove mBirthday support

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3001]
![изображение](https://user-images.githubusercontent.com/5046855/150242451-d8258d10-e8d4-42f2-b092-97c3b2dcecb1.png)

if I'm not mistaken, we do not support the mBirthday plugin

**Comment by georgehazan** [comment]
трагедия в том, что UserInfoEx может хранить дни рождения в этом же формате, и если его убрать, то всё навернется

**Comment by dartraiden** [comment]
Тогда, может, просто переименовать mBirthdays в  UserInfoEx?
