### ISSUE TITLE
WhoUsesMyFiles: научить запрашивать поднятие прав

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3002]
![изображение](https://user-images.githubusercontent.com/5046855/150242757-232e20d4-d041-4ca6-a1cf-2e8403826ced.png)

Если Миранда запущена не от администратора, плагин выбрасывает сообщение о невозможности работы. Почему бы вместо этого не запрашивать поднятие прав через UAC? В случае, если пользователь отказал в поднятии прав, выводить это окно.

**Comment by georgehazan** [comment]
Потому что запрос прав там делается для перечисления каких-то сетевых фигней, а такое pu_stub в жизни не научится, поэтому запрашивать что-то бессмысленно.
