### ISSUE TITLE
Jabber: управление комнатой чата (Ctrl+O) не дает эффекта

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#3009]
### Expected behavior
???

### Actual behavior
Nothing

### Does it work in stable version?
0.95.13.1

### Steps to reproduce that behavior
User Jabber account, join to any chat and press Ctrl+O in chat window.

**Comment by dartraiden** [comment]
А в горячих клавишах что назначено на Crtl+O?

**Comment by JeanPaulLucien** [comment]
Речь об окне чата, где вкладки, списки пользователей, набор сообщения, сообщения. Там "История сообщений" и то, о чем речь.

**Comment by JeanPaulLucien** [comment]
Я не специалист в протоколе Jabber, поэтому, если отсутствие эффекта - это так и задумано, то желательно добавить уведомление либо неактивность.

**Comment by dartraiden** [comment]
Все горячие клавиши настраиваются тут

<img width="503" alt="Miranda64_aFsQjPyJHj" src="https://user-images.githubusercontent.com/5046855/151044119-6c7efe34-b1e0-4ff5-9f2e-5b46263832ad.png">

**Comment by dartraiden** [comment]
> Речь об окне чата, где вкладки, списки пользователей, набор сообщения, сообщения. Там "История сообщений" и то, о чем речь.

я не совсем понимаю, где написано, что именно по Crtl+O должно произойти то, что вы написали...

**Comment by dartraiden** [comment]
вопрос в том, что у вас тут
<img width="503" alt="Miranda64_UV2qp6eEer" src="https://user-images.githubusercontent.com/5046855/151045384-dd93db31-8a36-43e1-8e03-eafde350c453.png">

**Comment by georgehazan** [comment]
@JeanPaulLucien для начала можно попробовать нажать мышкой на шестеренку в тулбаре групчата. Если выедет окно опций комнаты, то проблема в хоткее. Если вылезет ошибка, то для вызова этого окна вы должны быть хотя бы модератором этого групчата

**Comment by JeanPaulLucien** [comment]
@georgehazan изначально ЛКМ. Уточнено.
