### ISSUE TITLE
Сохранять набранное по умолчанию

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#3010]
Существует возможность "Сохранить набранное и закрыть вкладку". Не знаю, как это работает. Как насчет того, чтобы сделать сохранение набранного по умолчанию, чтобы при открытии вкладки текст уже был?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by georgehazan** [comment]
Может быть я чего-то не понимаю, но это всегда было искаропки, по крайней мере в tabSRMM, это не отключаемо, в отличие от StdMsg

**Comment by dartraiden** [comment]
Вот так это выглядит в tabSRMM

![vmware_TRQy8zPhzA](https://user-images.githubusercontent.com/5046855/151185319-7270c60f-0c8e-4f2c-8ef4-295e80804f98.gif)

если это то, что нужно, то просто установите плагин tabSRMM и используйте его

**Comment by georgehazan** [comment]
@JeanPaulLucien и есть маленькая просьба: вопросы лучше задавать на форуме, он специально для этого
https://forum.miranda-ng.org
