### ISSUE TITLE
OMEMO между Мирандой и другими клиентами

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3013]
Server: xmpp.social

### Miranda vs Psi+
В Миранде включена поддержка OMEMO, в Psi+ "OMEMO всегда включено" (т.е. принудительно). Учётки успешно обменялись авторизациями, друг у друга в ростере, видят друг друга онлайн.

Отправка сообщения с Миранды: Не существует действительной сессии OMEMO
Полный нетлог из Миранды, начиная от добавления друг друга в ростер и кончая этой неудачной сессией:
[netlog.zip](https://github.com/miranda-ng/miranda-ng/files/7946226/netlog.zip)

Отправка с Psi:  [OMEMO] Не получилось начать сессию, сообщение не отправлено
Нетлог неудачной отправки
[netlog.zip](https://github.com/miranda-ng/miranda-ng/files/7946235/netlog.zip)

### Miranda vs Gajim
В Миранде включена поддержка OMEMO, в Gajim тоже. Учётки успешно обменялись авторизациями, друг у друга в ростере, видят друг друга онлайн.

Gajim увидел ключи Миранды, включено доверие им
![изображение](https://user-images.githubusercontent.com/5046855/151264285-b0e5e821-837c-47b2-b508-856c1458bb41.png)

но при попытке написать сообщение не доходит

[в миранду.txt](https://github.com/miranda-ng/miranda-ng/files/7946304/default.txt)

Из Миранды: Не существует действительной сессии OMEMO

[из миранды.txt](https://github.com/miranda-ng/miranda-ng/files/7946314/default.txt)

**Comment by sss123next** [comment]
эти логи бесполезные.
в первом [2:12:28 0668] [JABBER_2] Jabber OMEMO: error: message does not encrypted for any sessions - это значит что сообщение зашифровано не для нас (клиент который нам его послал не знает про наше устройство (миранду), почему так может быть описано ниже)
во втором вобще ничего нет касательно амемы

сесси создаются при получении pubsub-event, в зависимости от настроек сервера, эти события могут не прилетать, перелогин с обоих сторон может помочь (а может не помочь, опять же, в зависимости от настроек сервера), например в jeabberd с настройками по умолчанию раньше события в оффлайн не посылались (как сейчас не знаю, раньше это нужно было включать явно)

обсуждалось уже много раз.

**Comment by dartraiden** [comment]
Вот лог между Мирандой и Conversations (автор которого, как я понимаю, автор XEP-а)

Лог полный: логин Миранды на сервер, Conversations добавляет Миранду в контакты, они обмениваются авторизациями, затем Conversations запускает сообщение "привет" в Миранду

[netlog — копия.txt](https://github.com/miranda-ng/miranda-ng/files/7948034/netlog.txt)

**Comment by sss123next** [comment]
сервер не прислал эвент с ключами.

https://xmpp.org/extensions/xep-0384.html#usecases-discovering   5.2

**Comment by dartraiden** [comment]
На всякий случай, то же самое (пересоздал омемные ключи в Миранде с нуля, взаимные авторизации), но отправка "привет" из Миранды
[miranda-convers.txt](https://github.com/miranda-ng/miranda-ng/files/7948214/miranda-convers.txt)

Попробовал спарить Psi+ и Conversations - аналогично, в пси ничего не пришло...
[convers-psi.txt](https://github.com/miranda-ng/miranda-ng/files/7948245/convers-psi.txt)

**Comment by sss123next** [comment]
возможно мы не на то подписываемся, я проверю. сходу так не вспомню, но помоему теперь в стандарте  имя другое события.

**Comment by sss123next** [comment]
да, кстати еще 1 момент.
в стандарте прописано сейчас "urn:xmpp:omemo:2:devices" (они на моей памяти это уже раза 4 меняли), мы используем старое: "eu.siacs.conversations.axolotl" , изменить это тривиально, одно с другим очевидно несовместимо, но стоит обратить внимание на : 

```
Version 0.2 (2017-06-02)

Depend on SignalProtocol instead of Olm.

Changed to eu.siacs.conversations.axolotl Namespace which is currently used in the wild

```

потом оно менялось на "urn:xmpp:omemo:1" и на "urn:xmpp:omemo:2'"



всё это меняется тривиально за минуту, только вот все это несовместимо между собой, нам как делать ? )

**Comment by dartraiden** [comment]
Currently in nightly builds OMEMO is working between Miranda and Conversations/Gajim/Psi+ (probably other clients too), It still missing a lot of features (it seems that even multi-session support is missing), but at least clients can communicate somehow
