### ISSUE TITLE
Jabber: MirVer for Gajim contact is " " (space)

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3014]

**Comment by dartraiden** [comment]
[netlog.txt](https://github.com/miranda-ng/miranda-ng/files/7946397/netlog.txt)

**Comment by georgehazan** [comment]
надо смотреть, что сидит в файле jabberCaps.json на тему gajim c соотв хэшем версии

**Comment by dartraiden** [comment]
В общем, там сочетание двух факторов:
- в тот раз от Gajim не пришла инфа о клиенте
- Миранда в MirVer пишет примерно следующее "названиеклиента"+пробел+"версия"

Gajim, когда всё работает корректно, присылает только имя, но не версию.

В итоге, если приходит имя, то в мирвер пишется "имя ", а если имя не пришло, то одинокий пробел
