### ISSUE TITLE
UserInfoEx: сортировка по дате рождения ведёт себя странно

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3017]
Сортировка по возрастанию сортирует по неизвестному критерию:

![изображение](https://user-images.githubusercontent.com/5046855/151667007-868c4ad4-c094-4137-b7d0-eff3786da301.png)

начинается словно бы по году, но один контакт (4 снизу) особняком

Сортировка по убыванию, кажется, сортирует по месяцу, но на середине списка уже лажает

![изображение](https://user-images.githubusercontent.com/5046855/151667054-33cd38f1-aa1b-46cc-b496-65b4b0326b3f.png)

**Comment by georgehazan** [comment]
Прибилось вместе с #3018
