### ISSUE TITLE
UserInfoEx: проблемы с запоминанием сортировки

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3018]
1) ставим плагин
2) открываем список дней рождений
3) нажимаем на заголовок столбца "ETA"

баг №1: он сортируется по **убыванию** (должен по возрастанию)
баг №2: после этого при открытии окна сортировка всегда стоит по возрастанию ETA, даже если перед закрытием мы сортируем по какой-то другой колонке, т.е. он не запоминает

**Comment by georgehazan** [comment]
нет сортировки - нет проблемы
