### ISSUE TITLE
Добавить уведомление, если каталог для входящих файлов недоступен для записи

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3022]
Миранда установлена в Program Files, а каталог для принятых файлов, например, %miranda_path%/Inbox (как в HotCoffee). Входящий файл молча улетает в никуда, т.к. прав на запись нет. Пользователю об этой досадной ситуации никто не сообщает.

Хорошо бы добавить запрос прав в таком случае, или, хотя бы, какое-то уведомление, например, в виде попапа.

**Comment by georgehazan** [comment]
если кроме жабера еще кто-то будет так себя вести, открой баг заново
