### ISSUE TITLE
IEView: не отображаются подписи к файлтрансферам 

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3023]
После https://github.com/miranda-ng/miranda-ng/commit/35928eb9337176d80e7e2591ef0ceaccafda076d подписи появились во всех журналах, кроме IEView.

**Comment by dartraiden** [comment]
Баг снова ожил: когда через официальный клиент прилетает файл с подписью, то в IEView подпись не видна.

**Comment by dartraiden** [comment]
Мы воскресили этот баг в результате https://github.com/miranda-ng/miranda-ng/commit/927aa281dab3124d39f4e113ff96b62509e1114d

Теперь подписи не отображаются, потому что мы отключили их отображение.

Получается аксиома Эскобара:
- если подписи не показываются, то когда в Telegram или любом другом протоколе нам присылают событие, состоящее из файла + текста, текст в журнале отсутствует
- если подписи показываются, то этот текст приклеивается к имени файла

Предлагаю откатить коммит. Лучше уж невалидная ссылка на файл в журнале (файл всё ещё можно открыть из окна файлтрансферов), чем пропущенное сообщение

**Comment by sk8rthug** [comment]
А нельзя в коде прописать добавление пробела перед подписью, чтобы ссылка отделялась от текста?
