### ISSUE TITLE
Падение при выгрузке части плагинов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3025]
1) отключаю плагины, показанные на скриншоте (снимаю с них галочки)
![изображение](https://user-images.githubusercontent.com/5046855/153096083-2bfe68ec-1c2f-4008-8785-8675a40ca0ef.png)

2) жму "Применить"

3) падаю

<img width="356" alt="vmware_UzjKPx9dV0" src="https://user-images.githubusercontent.com/5046855/153096259-d9049fb4-29b2-4d51-aa78-7a6d1e429b44.png">

профиль дам

**Comment by georgehazan** [comment]
а символы - не? правый клик на функции в Стеке вызовов - загрузить символы - ткнуть в PDB
