### ISSUE TITLE
NewEventNotify: доработать окно настроек

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3027]
Не все настройки из раздела "Уведомления", который был уничтожен в табсах, доступны в настройках событий.

**Comment by dartraiden** [comment]
![Безымянный](https://user-images.githubusercontent.com/5046855/153267046-76f2f280-8f8f-4782-a47c-6f22152b69db.png)

![Безымянный2](https://user-images.githubusercontent.com/5046855/153267060-881d3621-1573-40e5-aaa5-81dd72fedd91.png)

**Comment by dartraiden** [comment]
<img width="374" alt="vmware_7ZLn4hT1zf" src="https://user-images.githubusercontent.com/5046855/153607710-4336b35d-cbfa-449b-ba19-c01a8e9e0f33.png">

три галки в блоке "По левому щелчку" сбрасываются в дефолт при переоткрытии настроек.

**Comment by georgehazan** [comment]
с той картинки 1, 2 и 5 сделал, 3, 4 и 6 не получится перенести в NEN
