### ISSUE TITLE
tabSRMM, Scriver: cannot toggle event filter by Ctrl+F

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3028]
Ctrl+F does nothing. It works only in StdMsg, but not in tabSRMM or Scriver.
Screenshot from Scriver:

![Безымянный](https://user-images.githubusercontent.com/5046855/153314728-6b54fab9-bcbc-4074-a0dc-c76d0793ddee.png)

**Comment by dartraiden** [comment]
Can we also make this hotkey customizable via Customize → Hotkeys?

**Comment by georgehazan** [comment]
табсы и так умеют вешаться на хоткей. в скривере пропущенный хоткей восстановил
