### ISSUE TITLE
Jabber: автоматически подставлять адрес текущего сервера при создании конференции

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3029]
Вот я пытаюсь создать комнату на jabber.ru

![изображение](https://user-images.githubusercontent.com/5046855/153315166-204e1399-40ac-4cf4-9096-9196a3ad5ad4.png)

Почему бы в поле "Сервер" по умолчанию сразу не подставлять адрес сервера? (conference.jabber.ru) Можно, конечно, ввести руками и после этого он будет доступен в выпадающем меню. Но это всё равно лишние клики (открыть меню и выбрать оттуда сервер).

Можно ли сразу автоматически подставлять?

**Comment by georgehazan** [comment]
А у нас по факту нет имени сервера конференций, для этого надо посылать на сервер запрос про service discovery и искать там сервис с type=conference

Так что реально проще один раз вбить руками, а потом оно запомнится
