### ISSUE TITLE
Miranda Settings: different view with different languages

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#3031]
### Expected behavior
Same 'Settings' menu view

### Actual behavior
It's different

### Steps to reproduce that behavior
1. Install Russian language pack or other
1.1. Go to Miranda Settings.
2. Switch to other language.

**Comment by dartraiden** [comment]
Какое конкретно меню? Например, главное меню выглядит идентично.

**Comment by JeanPaulLucien** [comment]
Upgrade: this bug there is because you sort menu by alphabet. 
Solution: remove sorting by alphabet, make it constant (static).

**Comment by georgehazan** [comment]
Without sorting by sections' name it's not possible to perform a lookup when you need to open concrete section
