### ISSUE TITLE
Miranda Settings: UX: "Toolbar" inside "Contact List" menu group

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#3032]
**Is your feature request related to a problem? Please describe.**
In Miranda Settings there is 'Toolbar' submenu. Titles of menu group do not provide enough information.

**Describe the solution you'd like**
Create menu 'Main Window' in Miranda settings. Put inside 'Toolbar' submenu.

**Comment by JeanPaulLucien** [comment]
This "Toolbar" inside "Contact List". Because I have seen that two "Toolbar" exist in English version. In this case "Contact List" rename as "Main Window". Or create new menu group "Main Window" and mover "Toolbar" from "Contact List" in "Main Window".

**Comment by georgehazan** [comment]
There is the only toolbar inside any contact list, implemented by TopToolbar plugin, no other toolbars are possible. 

SRMM toolbar's settings are located in "Message settings"
