### ISSUE TITLE
"Gap between buttons" option is broken

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3033]
![изображение](https://user-images.githubusercontent.com/5046855/153658699-f74d0a70-2e81-4e4b-bef4-a0ef528791ba.png)

Во-первых, опция "Gap between buttons" не делает ничего. Зазор между кнопками не меняется.

Во-вторых, при смене этого значения пропадает значок на кнопке "Фильтр событий". То есть, например: фильтр событий включён, на нём зеленая галка, или отключён - на нём крестик; меняем настройку про зазор между кнопками; зеленая галка или красный крестик с кнопки фильтра пропадают.

Это в tabSRMM.

В StdMsg и Scriver опция тоже не работает, но поведение кнопки фильтра чуток иное: при измении зазора на кнопке фильтра появляется крестик, даже если фильтр включен.

**Comment by JeanPaulLucien** [comment]
https://github.com/miranda-ng/miranda-ng/issues/3032

**Comment by JeanPaulLucien** [comment]
Mir 0.95.13.1 , tabSRMM 3.6.1.5
Confirm.

**Comment by JeanPaulLucien** [comment]
This option updates window. So, something it does.

**Comment by dartraiden** [comment]
StdMsg: баг частично остался. Когда фильтр событий включён, изменение зазора между кнопками меняет значок фильтра с "включён" на "выключен". Значок не должен меняться, ведь фильтр мы не выключали.

![Miranda64_NczACebpXo](https://user-images.githubusercontent.com/5046855/171497363-27c7af9d-4e62-42fe-8749-dd25c2d6a841.gif)

**Comment by dartraiden** [comment]
Короче, по значка осталось всё то же, что и в первом посте было описано.

**Comment by georgehazan** [comment]
там просто уничтожаются все кнопки и создаются заново
