### ISSUE TITLE
Miranda Settigs: UX: Texts: 2 "Toolbar" submenu

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#3034]
### Expected behavior
What did you expect?

### Actual behavior
There is 2 submenu with same title in English.

### Steps to reproduce that behavior
1. Select English.
2. Visit Miranda Settings.
3. Look for "Toolbal" titles in submenues.

**Comment by dartraiden** [comment]
All OK. Contact list toolbar and message window toolbar are different toolbars.

**Comment by dartraiden** [comment]
If you have 2x "Toolbar" in "contact list" node, please post your [url=https://wiki.miranda-ng.org/index.php?title=Version_information]version info[/url]. because I have only one "Contact list → Toolbar" section.
