### ISSUE TITLE
Chats Window: Visual: black text on dark blue

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#3036]
### Expected behavior
I can read a menu titles

### Actual behavior
I can't read a menu titles, because I can't see black text on dark blue background

### Does it work in stable version?
0/95/13/1

### Steps to reproduce that behavior
0. Join to any chat (room)
1. Open chat window
2. Press ALT, if menu bar (menu on top) is hidden
3. Click on any menu item to see a subitems
4. Move cursor on other menu item (cursor should not leave menu bar area, but not importat)
5. Success! When your cursor on menu item it's black text on dark blue

**Comment by georgehazan** [comment]
What about setting proper colors in Options / Customize / Fonts & colors?
And please, if you don't know how to tune Miranda, ask a question at the forum, don't post a bug

**Comment by JeanPaulLucien** [comment]
@dartraiden my Miranda with default settings as is needed by QA. Your image with other issue.

**Comment by JeanPaulLucien** [comment]
![bug001](https://user-images.githubusercontent.com/24779886/154196981-2163f108-3ce0-4cc6-8d88-f750d1bd9257.PNG)

**Comment by JeanPaulLucien** [comment]
@georgehazan all QA with default set.

**Comment by dartraiden** [comment]
Да, оно где-то в табсах выставляется. Мы несколько дней не можем понять, где.

Как-то связано со скином.

**Comment by georgehazan** [comment]
> ![bug001](https://user-images.githubusercontent.com/24779886/154196981-2163f108-3ce0-4cc6-8d88-f750d1bd9257.PNG)

Так получается, если увести курсор мыши с меню при работе с меню, тогда элемент становится неактивным, чтобы оно стало снова белым, надо просто вернуть курсор на место. При работе с клавиатуры такого эффекта не наблюдается.
