### ISSUE TITLE
Miranda Settings: "Use flat mode" does not wor

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#3037]
### Expected behavior
Don't know

### Actual behavior
Nothing

### Does it work in stable version?
0.95.13.1

### Steps to reproduce that behavior
Show Miranda.
Go to Miranda Settings, Contact list, Toolbar submenu. Change "Use flat mode".

**Comment by georgehazan** [comment]
Clist_Modern's skin engine doesn't support drawing flat button, so this option works only in Clist_Nicer or StdClist
