### ISSUE TITLE
Jabber: don't tell to server about Miranda version and OS by default

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#3038]
Miranda reports to server an information about Miranda and operational system by default. I suggest to not provide this information by default.

I don't know about other protocols, but don't tell them this information too.

**Comment by JeanPaulLucien** [comment]
I turned off to report Miranda's version. What wrong goes?

**Comment by dartraiden** [comment]
```
так версия Миранды нужна для выставления капсов

без нее никак

ну т.е. там половина фич отвалится сразу
```

**Comment by JeanPaulLucien** [comment]
Showing a different set of icons depending on the capabilities of other entities.
    Not sending [XHTML-IM (XEP-0071)](https://xmpp.org/extensions/xep-0071.html) [[1](https://xmpp.org/extensions/xep-0115.html#nt-idm46173955944224)] or other rich content to plaintext clients such as **cell phones**.
    Allowing the initiation of a **Voice over IP** (VoIP) session only to clients that support [Jingle (XEP-0166)](https://xmpp.org/extensions/xep-0166.html) [[2](https://xmpp.org/extensions/xep-0115.html#nt-idm46173955934032)] and [Jingle RTP Sessions (XEP-0167)](https://xmpp.org/extensions/xep-0167.html) [[3](https://xmpp.org/extensions/xep-0115.html#nt-idm46173955936304)].
    Not showing a "Send a File" button if another user's client does not support [SI File Transfer (XEP-0096)](https://xmpp.org/extensions/xep-0096.html) [[4](https://xmpp.org/extensions/xep-0115.html#nt-idm46173955928160)].
    Filtering [Publish-Subscribe (XEP-0060)](https://xmpp.org/extensions/xep-0060.html) [[5](https://xmpp.org/extensions/xep-0115.html#nt-idm46173955917952)] notifications based on advertised subscriber interests.
