### ISSUE TITLE
Jabber: Workaround for GTalk contact error message

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#304]
**Reported by Jojo on 22 May 2014 21:03 UTC**
As you might be aware, a large number of Jabber servers have switched to mandatory s2s encryption today, which makes contacting GTalk contacts through these servers impossible. One strange side effect is that the contacts still turn up in my contact list as being online (but they don't get my messages), and whenever they change their protocol status, I get the following message box:

*@gmail.com/MessagingA434a1408:
Fehler 404: nicht gefunden

remote-server-not-found

Generally it might be useful to get these kind of messages of course, but it's getting a bit annoying to get dozens of these, and I don't want to completely remove those GTalk contacts to be able to preserve their history etc.

**Comment by georgehazan** [comment]
**Modified by watcher on 29 Jun 2014 11:19 UTC**

**Comment by georgehazan** [comment]
**Comment by Jojo on 22 Jul 2014 22:14 UTC**
I'm not sure if something in Miranda has been changed or on the server I'm using (since they re-installed the server around the time I observed the change), but I'm not longer getting spammed with such error messages. So in case a relevant change was made in Miranda, this can be closed, otherwise I'm afraid I cannot verify if a future fix will fix the issue since I no longer get these messages.

**Comment by dartraiden** [comment]
GTalk is dead.
