### ISSUE TITLE
Удалить выпадающий список серверов Jabber

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3041]
Он не обновляется на xmpp.org и заброшен.

Я попытался удалить
IDC_LINK_PUBLIC_SERVER
m_lnkServers

но там ещё вылезают какие-то страшные штуки типа

OnDropdown
QueryServerListThread
RefreshServers

и без их выпиливания список всё равно выпадает

**Comment by georgehazan** [comment]
Это еще зачем? Оно прекрасно работает себе

**Comment by JeanPaulLucien** [comment]
@georgehazan 
Miranda gets servers from unmaintened list and will be moved soon. So it will stop to work and Miranda will get unexpected behavoir.
