### ISSUE TITLE
AVS: удалённые аватары не появляются при обновлении данных

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3043]
Открываем юзеринфо какого-нибудь контакта. Переходим в раздел "Аватар". Видим аватар.

<img width="379" alt="Miranda64_0KGCg3NbJ4" src="https://user-images.githubusercontent.com/5046855/154501090-980ab828-98eb-41a3-a43a-ff8824b2ec81.png">

Нажимаем Delete или Reset. Нас спрашивают "удалить ли файл аватара с диска".

<img width="330" alt="Miranda64_GOOim49D5m" src="https://user-images.githubusercontent.com/5046855/154501240-15371116-3bb4-4b23-8445-9a1eafa8b52c.png">

Выбираем любой ответ. Аватар пропадает. Нажимам "Update now".

Ожидание: аватар должен подгрузиться заново.
Реальность: аватар не появляется, пока не переоткроешь юзеринфо.

**Comment by JeanPaulLucien** [comment]
0.95.13.1
Confirm. TabsRmm
