### ISSUE TITLE
Dupicate messages in miranda + monal

### ISSUE THREAD

**Issue by myrrc** [miranda-ng/miranda-ng#3047]
### Expected behavior
Messages sent from Monal to Miranda through prosody are not duplicated

### Actual behavior
Messages delivered from Monal are delivered successfully, but then (after some time passes) are sent again.

### Does it work in stable version?
Yes

### Steps to reproduce that behavior

<details><summary> VersionInfo </summary>

```
Microsoft Windows 10 , 64-bit (build 19044)

Miranda NG Version: 0.95.13.1 build #23835 (9bdd68f90e) x64

Build time: 1 Mar 2022 15:48:52
Database driver: SQLite database driver
Profile size: 176128 Bytes
Profile creation date: 11 Mar 2022 21:12:20
Service Mode: No

[b]Active Plugins (14):[/b]
¤ AVS.dll v.[b]0.98.1.4[/b] [1 Mar 2022 15:48:58] - Avatar service 
¤ Clist_modern.dll v.[b]0.9.1.12[/b] [1 Mar 2022 15:50:38] - Modern contact list 
¤ CrashDumper.dll v.[b]0.2.0.1[/b] [1 Mar 2022 15:50:52] - Crash dumper 
¤ DbChecker.dll v.[b]0.95.13.3[/b] [1 Mar 2022 15:53:32] - Database checker 
¤ Dbx_sqlite.dll v.[b]0.96.1.2[/b] [1 Mar 2022 15:53:24] - Miranda NG SQLite database driver 
¤ Dummy.dll v.[b]0.2.0.0[/b] [1 Mar 2022 15:52:38] - Dummy protocol 
¤ historypp.dll v.[b]1.5.1.5[/b] [1 Mar 2022 15:54:16] - History++ 
¤ ICQ.dll v.[b]0.96.1.7[/b] [1 Mar 2022 15:53:28] - ICQ-WIM protocol 
¤ Import.dll v.[b]0.95.11.1[/b] [1 Mar 2022 15:49:50] - Import contacts and messages 
¤ IRC.dll v.[b]0.96.1.4[/b] [1 Mar 2022 15:49:08] - IRC protocol 
¤ Jabber.dll v.[b]0.95.11.1[/b] [1 Mar 2022 15:50:18] - Jabber protocol 
¤ PluginUpdater.dll v.[b]0.2.0.12[/b] [1 Mar 2022 15:51:14] - Plugin updater 
¤ TabSRMM.dll v.[b]3.6.2.1[/b] [1 Mar 2022 15:49:18] - TabSRMM 
¤ TopToolBar.dll v.[b]0.8.0.5[/b] [1 Mar 2022 15:50:22] - TopToolBar 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
JABBER                   1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 HistoryPP_icons.dll [1 Mar 2022 15:53:48]
 Proto_Dummy.dll [1 Mar 2022 15:53:54]
 Proto_ICQ.dll [1 Mar 2022 15:53:56]
 Proto_IRC.dll [1 Mar 2022 15:53:42]
 Proto_Jabber.dll [1 Mar 2022 15:53:46]
 Proto_MetaContacts.dll [1 Mar 2022 15:53:54]
 Proto_MRA.dll [1 Mar 2022 15:53:58]
 TabSRMM_icons.dll [1 Mar 2022 15:53:48]
 Toolbar_icons.dll [1 Mar 2022 15:53:42]
 xStatus_Jabber.dll [1 Mar 2022 15:53:46]
[/quote][/spoiler]
```

</details>

- Send a message from Monal
- Receive a message from Miranda
- Wait till Monal client disconnects
- See a duplicate connect->message log in Miranda. In Monal no messages are duplicated even after client re-install. In prosody logs there are no signs of duplicate messages. All messages sent in session are duplicated.

<details><summary>Prosody config</summary>

```
modules_enabled = {
    "roster"; "saslauth"; "tls"; "dialback"; "disco";
    "carbons"; "pep"; "private"; "blocklist"; "vcard4"; "vcard_legacy";
    "version"; "uptime"; "time"; "ping"; "admin_adhoc"; "posix";
    "mam"; "message"; "offline"; "smacks"; "csi_simple";
}

allow_registration = false
daemonize = true;
pidfile = "prosody.pid";

c2s_require_encryption = true
s2s_require_encryption = true
s2s_secure_auth = true

authentication = "internal_hashed"
archive_expires_after = "1y"

statistics = "internal"

certificates = "certs"
https_certificate = "..."

VirtualHost "..."

Include "conf.d/*.cfg.lua"
```
</summary>

Modules that could be the faulty ones: Message streaming (smacks) or archive (mam). However, disabling them didn't change anything.

**Comment by dartraiden** [comment]
Do you have simultaneously running miranda and another client (mobile Jabber client, etc)?

If yes, it's possible duplicate of https://github.com/miranda-ng/miranda-ng/issues/1314

**Comment by georgehazan** [comment]
@myrrc network log would be appreciated, Jabber + core
https://wiki.miranda-ng.org/index.php?title=Network_log describes how to create network logs

**Comment by myrrc** [comment]
> Do you have simultaneously running miranda and another client (mobile Jabber client, etc)?
> 
> If yes, it's possible duplicate of #1314 Some old message carbons related bug

Hi. Well, it's miranda and monal (mobile client for ios), no other clients.
And the message duplication happens when mobile client goes offline (and then, probably, online again, not sure).

**Comment by myrrc** [comment]
> @myrrc network log would be appreciated, Jabber + core https://wiki.miranda-ng.org/index.php?title=Network_log describes how to create network logs

Will investigate, strangely can't reproduce now. Closing until then.

Another note: OMEMO is off, sending a message with OMEMO from Monal to Miranda causes Miranda to crash. Will fire another Issue.
