### ISSUE TITLE
Jabber: Implement XEP-0198

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#305]
**Reported by Jojo on 22 May 2014 21:43 UTC**
XEP-0198 (Stream Management) can help on unstable networks (WiFi, UMTS) where disconnects (and thus message loss) are to be expected. While this is even more important for e.g. mobile phone clients, it would be nice to see Miranda supporting this as well. Currently many clients still lack this feature - see e.g. http://op-co.de/blog/posts/mobile_xmpp_in_2014/ - this article also mentions a few other XEPs that would be worth implementing for this scenario.

**Comment by georgehazan** [comment]
**Modified by watcher on 29 Jun 2014 11:25 UTC**

**Comment by sss123next** [comment]
doesn't it already done ?
