### ISSUE TITLE
OMEMO enhancement tricks

### ISSUE THREAD

**Issue by Null-Kelvin** [miranda-ng/miranda-ng#3053]
### Expected behavior
Работа OMEMO в Miranda NG

### Actual behavior
Работает только на одном сервере из проверенных, при условии что оба клиента - Miranda

### Steps to reproduce that behavior
Вариант 1: сервер ejabberd 21.12
Клиент Psi+ и Conversations работают без проблем. Лог Psi+ (профиль создан с нуля и на Psi+ и на Conversations) - сообщения просто ходят между устройствами. На Psi+ при первом ответе надо подтвердить ключ.
Лог:
[PsiPlus to Conversations.txt](https://github.com/miranda-ng/miranda-ng/files/8309660/PsiPlus.to.Conversations.txt)

Вариант1: тот же сервер, Psi+ и Miranda NG (версия 0.96.1.0)
Открываем Psi+ пишем сообщение. Он предлагает подтвердить ключи. Подтверждаем, сообщения уходят, в Miranda не появляются.
Сообщения из Miranda не уходят вовсе, вылетает ошибка.
Логи:
[PsiPlus.txt](https://github.com/miranda-ng/miranda-ng/files/8309663/PsiPlus.txt)
[MirandaNG.txt](https://github.com/miranda-ng/miranda-ng/files/8309664/MirandaNG.txt)

Вариант 2: сервер, на котором достоверно работает OMEMO между двумя Miranda NG
1 Открываем контакт в Psi+, пишем-отправляем, запрашивает подтверждение трех ключей, сообщение уходит, но не появляется в Miranda NG
2 Открываем контакт в Miranda, пишем-отправляем, запрашивает подтверждение ДВУХ ключей, сообщение уходит, в Psi+ появляется "OMEMO:Сообщение от недоверенного устройства"
Логи:
[Miranda Phase 1.txt](https://github.com/miranda-ng/miranda-ng/files/8309671/Miranda.Phase.1.txt)
[PsiPlus Phase 1.txt](https://github.com/miranda-ng/miranda-ng/files/8309673/PsiPlus.Phase.1.txt)

По совету из другого тикета, закрываем оба клиента, открываем их заново. Пытаемся отправить сообщения. Они ходят из Miranda в Psi+ но не наоборот. При этом Psi+ считает что сообщение ушло.
Логи:
[Miranda Phase 2.txt](https://github.com/miranda-ng/miranda-ng/files/8309674/Miranda.Phase.2.txt)
[PsiPlus Phase 2.txt](https://github.com/miranda-ng/miranda-ng/files/8309675/PsiPlus.Phase.2.txt)

**Comment by dartraiden** [comment]
Возможно, это связано с https://github.com/miranda-ng/miranda-ng/issues/1417

**Comment by sss123next** [comment]
уже обсудили, буду делать костыли как у всех, не по стандарту.
собственно уже сделал, надо отладить.

**Comment by OmlineEditor** [comment]
> порой со всякими странностями

А что за странности?

И самое главное работает ли шифрование на 100%? Нет ли проблем с отсылкой незашифрованных сообщений?

**Comment by dartraiden** [comment]
Например, настойчивая попытка поомемиться с мирандой, в которой OMEMO выключено, и отказ слать сообщения в незашифрованном виде...

**Comment by Neustradamus** [comment]
@Null-Kelvin: Your problem has been solved?

**Comment by Null-Kelvin** [comment]
> @Null-Kelvin: Your problem has been solved?
No, MirandaNG still have bugs in OMEMO, so I moved to Psi+

**Comment by sss123next** [comment]
сильно устаревший тикет
