### ISSUE TITLE
Ping: плавающий фрейм на стандартном скине модерна выглядит странно

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3054]
<img width="178" alt="mstsc_kU67JZp3cV" src="https://user-images.githubusercontent.com/5046855/159191379-7da87d1d-0f35-4ae7-9463-9b5b07503fe0.png">

У него рамка как-то сдвинута что ли...

**Comment by georgehazan** [comment]
это так border width работает в Windows 10/11, надо скачать WinAero Tweaks и выставить ее в ноль
