### ISSUE TITLE
No way to send message

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#3056]
### Expected behavior
Message is sent

### Actual behavior
Impossible to sent message

### Steps to reproduce that behavior
Go to Options, Message Sesstions and unselect all from Sending Messages. 
Now, you can't to send message using keyboard.

**Comment by dartraiden** [comment]
Достаточно настроить горячую клавишу для отправки сообщений

<img width="503" alt="Miranda64_s5ksqeqpSD" src="https://user-images.githubusercontent.com/5046855/159371615-3e032662-8af0-4a4c-8a56-aee6529ae86a.png">

**Comment by georgehazan** [comment]
It must have been fixed in the current dev build, because all those options were removed and replaced with the hotkey setting
