### ISSUE TITLE
Унифицировать настройку горячих клавиш для отправки сообщений

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3057]
Горячие клавиши для отправки сообщений сейчас у нас размазаны по двум местам

1) три хоткея (Enter, Shift+Enter, Enterx2) можно настроить тут

<img width="503" alt="Miranda64_wARRNm3Hs6" src="https://user-images.githubusercontent.com/5046855/159372067-ff96c6f3-a8c4-454b-8dc4-13343652947c.png">

2) и любой хоткей можно повесить тут

<img width="503" alt="Miranda64_Mlp0S2yC7i" src="https://user-images.githubusercontent.com/5046855/159372197-6c6e1d8b-f683-47d3-afc2-c0305ae5bdb3.png">

Предлагаю сделать более логично:
- опции про Enter и Shift+Enter удалить
- по умолчанию на втором скрине назначить Enter на отправку
-  если юзер хочет какой-то другой хоткей, то он идёт туда, куда показывает второй скрин и там добавляет себе хоть Shift+Enter, хоть любой другой хоткей

с двойным Enter сложнее, т.к. наша настройка хоткеев не позволяет добавить Enter+Enter, поэтому
- либо опцию про двойной Enter совсем выпилить, как извращение
- либо оставить её где и была
- либо научить наш настраиватель хоткеев добавлять такой хоткей

**Comment by georgehazan** [comment]
Суть в том, что сейчас табсы разделяют эти настройки со всеми другими клонами SRMM, в то время как настройки (и, главное, анализ) горячих клавиш присутствуют только в табсах. Т.о. отстрел этих опций в табсах приведет к разрыву в преемственности настроек

**Comment by dartraiden** [comment]
Табсы, было->стало

Enter -> Enter [✓]
Enterx2 -> Enter (т.к. двойной Enter выпилили) [✓]

**Comment by tamr** [comment]
Сегодня обнаружил, что отвалилась отправка сообщений. Ни по enter, ни по shift+enter, ни какая другая комбинация, заданная в горячих клавишах, сообщения не отправляет, а лишь переносит строку. Пункты на первом скрине в настройках отсутствуют. Что откатить, чтобы вновь стало хорошо?

**Comment by dartraiden** [comment]
Пункты мы выпилили.

Нужно сходить в настройку горячих клавиш и настроить желаемый хоткей.

**Comment by tamr** [comment]
Как это сделать? Кажется, уже всё перепробовал. Вижу в dbeditor ключ SendOnEnter в Tab_SRMsg? Относится ли он к TabSRMM? Может следует его удалить?

![2022-03-27_185506](https://user-images.githubusercontent.com/209513/160289868-ef72f5b9-227f-4449-9439-cb08fb19d956.png)

**Comment by georgehazan** [comment]
@tamr как обычно, ткнуть в хоткей, вылезет формочка, в которой нажать требуемую клавишу

**Comment by tamr** [comment]
Имеете ввиду, изменить хоткей? Пробовал разные комбинации, не работает. Пока откатился на стабильную версию.

**Comment by dartraiden** [comment]
Какой плагин сообщений используется? tabSRMM, StdMsg или Scriver?

**Comment by dartraiden** [comment]
> Пробовал разные комбинации, не работает

Возможно, комбинация уже назначена на какое-то другое действие.

**Comment by tamr** [comment]
TabSRMM, с версией 3.6.2.1 проблем не наблюдается, версия 3.6.2.2 от 26 числа из dev не работает. Хотя, в бэкапах вижу, что имеется  3.6.2.2 от 22 числа (417.5Kb). Делая апдейты ежедневно, в течении недели каких-то проблем не наблюдал.

**Comment by dartraiden** [comment]
Если не жалко, то сделайте резервную копию профиля, затем удалите из Миранды учётные записи и пришлите профиль нам. В профиле не останется каких-либо личных данных, они стираются вместе с аккаунтами.

**Comment by tamr** [comment]
После очистки, на самом деле, остаётся немало данных. Вижу в таблицах events, crypto, settings. Оказалось, недостаточно стереть или удалить таблицу events, пришлось уплотнить, чтобы окончательно удалить следы контактов и ключей. Не знаю, годится ли такая база, но вроде запускается без ошибок.

Копия профиля из неработающей версии.
Miranda NG Version: 0.96.1 alpha build #24440 (42c98b0aec) [running inside WOW64]
Active Plugins (21):
¤ Clist_modern.dll v.0.9.1.12 [27 Mar 2022 15:13:48] - Modern contact list 
¤ Console.dll v.0.0.7.4 [27 Mar 2022 15:12:40] - Console 
¤ CrashDumper.dll v.0.2.0.1 [27 Mar 2022 15:14:02] - Crash dumper 
¤ CryptoPP.dll v.1.0.4.8 [27 Mar 2022 15:14:44] - Crypto++ 
¤ Db_autobackups.dll v.0.1.0.6 [27 Mar 2022 15:12:52] - Db autobackuper 
¤ DbChecker.dll v.0.95.13.3 [27 Mar 2022 15:16:34] - Database checker 
¤ DbEditorPP.dll v.4.1.0.2 [27 Mar 2022 15:14:10] - Database editor++ 
¤ Dbx_mdbx.dll v.0.95.9.1 [27 Mar 2022 15:16:32] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.0.95.8.1 [27 Mar 2022 15:12:18] - Miranda NG mmap database driver 
¤ Dbx_sqlite.dll v.0.96.1.2 [27 Mar 2022 15:16:20] - Miranda NG SQLite database driver 
¤ Dummy.dll v.0.2.0.1 [27 Mar 2022 15:15:44] - Dummy protocol 
¤ historypp.dll v.1.5.1.5 [27 Mar 2022 15:17:18] - History++ 
¤ HistorySweeperLight.dll v.0.1.0.1 [27 Mar 2022 15:12:50] - History sweeper light 
¤ PluginUpdater.dll v.0.2.0.12 [27 Mar 2022 15:14:14] - Plugin updater 
¤ SecureIM.dll v.1.0.12.6 [27 Mar 2022 15:13:08] - SecureIM 
¤ SeenPlugin.dll v.5.0.5.6 [27 Mar 2022 15:13:12] - Last seen 
¤ SkypeWeb.dll v.0.95.13.3 [27 Mar 2022 15:15:56] - Skype protocol (Web) 
¤ SmileyAdd.dll v.0.3.2.1 [27 Mar 2022 15:13:14] - SmileyAdd 
¤ StatusManager.dll v.1.2.0.6 [27 Mar 2022 15:16:00] - Status manager 
¤ TabSRMM.dll v.3.6.2.2 [27 Mar 2022 15:12:26] - TabSRMM 
¤ TopToolBar.dll v.0.8.0.5 [27 Mar 2022 15:13:34] - TopToolBar 

[profile.zip](https://github.com/miranda-ng/miranda-ng/files/8358213/profile.zip)

**Comment by dartraiden** [comment]
Да, точно, в sqlite же удалённые данные не перезаписываются, а только помечаются как свободное место. Сжатие базы производит VACUUM, в результате чего свободное место перезаписывается.

**Comment by dartraiden** [comment]
Удалось воспроизвести, завтра будем разбираться...

**Comment by dartraiden** [comment]
Причина в ключе

[SRMM_Toolbar]
Tabsrmm_1=s10_0_0_0_1_0

**Comment by tamr** [comment]
Действительно, удалил и отправка сообщений заработала. Спасибо! Похоже, эта опция отвечает за отображение иконки "отправить", хотя галочка "по умолчанию" стоит.
![2022-03-28_004611](https://user-images.githubusercontent.com/209513/160302345-07a7b539-16a2-4a4e-ae6d-fe0498e19c6b.png)

ps: небольшой оффтоп в догонку. Кажется, когда-то уже задавал этот вопрос на форуме или руборде, касательно форматирования правок от скайпа в окне чата. Не планируется ли эти json как-то отформатировать для читабельности?
`{"original_message":{"time":1647246874,"text":"Original"},"edits":[{"time":1647246874,"text":"Changed"}]}`

**Comment by dartraiden** [comment]
Лучше открыть отдельный тикет и там описать как оно сейчас и как хочется, чтобы было.

**Comment by georgehazan** [comment]
@tamr поправил, можно переползать обратно

**Comment by Rubarius** [comment]
Ну лично мне и 200 сотрудникам двойной Enter в обще не мешал...А от ctrl+Enter все неделю плюются.

**Comment by Moumyio** [comment]
Ребят, верните пожалуйста настройку по двойному Enter.

**Comment by Rubarius** [comment]
Двойноё Enter уже 2 года не работет, уже 2 года все плюются на Ctrl+Enter, зачем убрали 2x Enter не понятно!
