### ISSUE TITLE
Центрировать кнопку "ОК" в окне подтверждения сжатия базы

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3060]
<img width="170" alt="Miranda64_7qf1OvdETf" src="https://user-images.githubusercontent.com/5046855/160260011-01fc9ad1-d75a-4efa-b83b-ca700212022d.png">

**Comment by georgehazan** [comment]
а на хуа, собственно? вообще-то в винде по стандарту кнопка Ok прижата вправо

**Comment by georgehazan** [comment]
MessageBoxW(nullptr, TranslateT("Database was compacted successfully"), L"Miranda NG", MB_OK | MB_ICONINFORMATION); - это стандартный виндовый вызов, там сама винда разбирается со всем этим
