### ISSUE TITLE
tabSRMM: hotkey "Send Message" does not work

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3062]
```
[SRMM_Toolbar]
SmileyAdd_0=s30_1_1_0_1_0
Tabmodplus_1=s120_0_0_0_0_0
Tabsrmm_1=s10_0_0_0_1_0
Tabsrmm_1016=s80_0_0_0_1_0
Tabsrmm_1020=s60_0_0_0_1_0
Tabsrmm_1022=s20_0_0_0_0_0
Tabsrmm_1025=s40_0_0_0_1_0
Tabsrmm_1104=s100_0_0_0_1_0
Tabsrmm_1113=s80_0_0_0_0_1
Tabsrmm_1140=s10_0_0_0_0_0
Tabsrmm_3001=s100_0_0_0_0_0
Tabsrmm_3002=s110_0_0_0_0_0
Tabsrmm_3003=s50_0_0_0_0_1
Tabsrmm_3004=s60_0_0_0_0_1
Tabsrmm_3005=s70_0_0_0_0_1
Tabsrmm_3006=s50_0_0_0_1_0
Tabsrmm_3007=s70_0_0_0_1_0
Tabsrmm_3008=s20_0_1_0_1_0
Tabsrmm_3009=s90_0_0_0_1_0
```

Экспериментальным путём установлено, что если в базе есть `Tabsrmm_1=s10_0_0_0_1_0`, то до работы над https://github.com/miranda-ng/miranda-ng/issues/3057 горячая клавиша, назначенная на действие Send Message, работает, а после - нет.

Возможно, остальные вышеперечисленные настройки тоже что-то ломают. Почему они вообще влияют на хоткей?

**Comment by georgehazan** [comment]
1 - это и есть Send button. какого дьявола оно делает в тулбаре = это второй вопрос
