### ISSUE TITLE
Plugin StatusManager

### ISSUE THREAD

**Issue by Razin004** [miranda-ng/miranda-ng#3063]
Здравствуйте, с новой версией MirandaNG, не работает plugin StatusManager 
Прошу вас разобраться с этой проблемой и если можно ответить мне на почту sasha.razin.99@bk.ru

**Comment by georgehazan** [comment]
а в чем конкретно это выражается?

**Comment by Razin004** [comment]
Скачал плагин с сайта StatusManager
Добавил его в папку Plugins
Перезапустил MirandaNG
А в настройках новые функции не добавились, например: что бы "в сети" запускалось автоматически

**Comment by georgehazan** [comment]
а в списке плагинов он есть? не надо ничего скачивать руками, надо использовать Plugin Updater и его сервис "установить дополнительный плагин"

**Comment by Razin004** [comment]
ну в папке я его добавляю и он есть, а где взять Plugin Updater?

**Comment by Razin004** [comment]
со старой версией всегда срабатывало

**Comment by Razin004** [comment]
вот я и добавляю файл тоже в ядро архива StatusManager.dll

**Comment by georgehazan** [comment]
значит не та dll, например, 32-битная dll не заработает в 64-битной миранде.
говорю же, для начала надо проверить, что сам плагин есть в списке плагинов и включен там

**Comment by Razin004** [comment]
подскажите как мне это сделать?

**Comment by georgehazan** [comment]
буквально, Options - Plugins, найти там StatusManager

**Comment by Razin004** [comment]
Тут его нет

**Comment by Razin004** [comment]
Версия 0.95.13.1 х64

**Comment by georgehazan** [comment]
Логично. Значит, надо скачать либо плагин нужной битности, либо от нужной версии (дев. билд под ядром стабли тоже грузиться не будет)

**Comment by dartraiden** [comment]
Если затрудняетесь определить версию и разрядность Миранды, смотрите [информацию о версиях](https://wiki.miranda-ng.org/index.php?title=Version_information).

**Comment by dartraiden** [comment]
Скорее всего, либо не совпадает разрядность, либо версия, как вам уже сказали.
