### ISSUE TITLE
Google Hangouts/Chat online/transition issue

### ISSUE THREAD

**Issue by newsjunkie247** [miranda-ng/miranda-ng#3067]
With the transition to Google Chat, chat messages from Gmail are still received in Miranda NG, but the other user appears offline if they are only using Google Chat. It would be great if this could be fixed/if there could be an updated Google Chat protocol sometime. thank you.

**Comment by georgehazan** [comment]
I doubt that the special plugin for Hangouts will ever be written, so we have what we could with XMPP connector

**Comment by newsjunkie247** [comment]
@georgehazan But Hangouts is likely shutting down soon and then the XMPP connector will likely stop working entirely, so couldn't one start thinking about some sort of solution?

**Comment by georgehazan** [comment]
@newsjunkie247 for now there's no open source library that implements Google Chat, if there was one, I could try to reimplement it for Miranda

**Comment by peci1** [comment]
libpurple already has an implementation: https://github.com/EionRobb/purple-googlechat .
