### ISSUE TITLE
IM Updater plugin

### ISSUE THREAD

**Issue by az-nvkz** [miranda-ng/miranda-ng#3070]
После обновления сайта перестал работать плагин обновления с Miranda IM. Он обращается за обновлением по адресу http://miranda-im.org/... а на новом сайте идет перенаправление на https://miranda-im.org, но плагин, видимо, не умеет обрабатывать это и сразу выдает ошибку обновления.

**Comment by georgehazan** [comment]
@az-nvkz поправил, спасибо. Должно работать

**Comment by az-nvkz** [comment]
Спасибо, заработало!
