### ISSUE TITLE
Scriver: окно сообщений закрывается при открытии настроек

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3083]
- ставим через апдейтер Scriver и соглашаемся на предложение апдейтера вгрузить его (это важно, баг воспроизводится лишь при вгружении плагина апдейтером, а не вручную)
- закрываем окно настроек
- открываем групчат
- открываем окно настроек

окно сообщений внезапно закрывается

если же перезапуститься и вгружать плагин вручную, то баг не воспроизводится

**Comment by georgehazan** [comment]
у меня ничего не закрывается.
