### ISSUE TITLE
Миранда отказывается обновиться с ночника на стабильную версию

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3085]
Каким-то образом у меня получилась ситуация: нахожусь на канале обновления "девелоперская версия без символов", если поменять канал обновлений на "девелоперская с символами" или "стабильная с символами", то апдейтер бросается закачивать требуемое, как и положено. Но если выбрать "стабильная без символов", то ничего не происходит, более того, при переоткрытии настроек чекбокс возвращается на "девелоперская".

Профиль дам по запросу, воспроизводится на нём 100%.

**Comment by georgehazan** [comment]
только хардкор :)
