### ISSUE TITLE
[0.96.1] [TabSRMM] Regression, Enter does not Send Message

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#3087]
### Expected behavior
**Enter key** should send message by default in single and group mode TabSRMM windows.

### Actual behavior
**Enter** does newline now. Shift-Enter, Alt-Enter, Ctrl-Enter don't send either. How to send???

Toolbar 'Sending Options' when enabled, does not react to click.

### Does it work in stable version?
Worked in last stable version, does not work in new 0.96.1.

**Comment by georgehazan** [comment]
SRMM send button settings migrated to Options - Customize - Hotkeys, enable Enter there

**Comment by dartraiden** [comment]
Also it is written at the beginning of our changelog.
