### ISSUE TITLE
В девелоперский канал вылилась 0.96.1

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3088]
Ещё вчера в девелоперском канале была 0.96.2, а в стабильном 0.96.1

Сегодня в девелоперском канале имеем какого-то мутанта - "альфа 0.96.1"

<img width="260" alt="Miranda64_Dym2Q1xKKK" src="https://user-images.githubusercontent.com/5046855/171857717-8c00a64a-02ac-4d24-90d1-0fde0e648b22.png">

**Comment by georgehazan** [comment]
да, гит сраный глючит после бранча, я забыл об этом
