### ISSUE TITLE
HotKeys not work for send message

### ISSUE THREAD

**Issue by sh-nick** [miranda-ng/miranda-ng#3093]
In new version (V0.96.1.24539) I can  not send message via [Ctr+Enter].

**Comment by sh-nick** [comment]
Checked old version V.95.13.1.23835 - no problem with this shortcut.

**Comment by georgehazan** [comment]
no problems here in 0.96.1 with Ctrl+Enter in all three plugins (Scriver, tabSRMM, StdMsg)
are you sure that you're using the latest version?

**Comment by georgehazan** [comment]
also check please that you have the correct hotkey for sending messages at Options -> Customize -> Hotkeys

**Comment by sh-nick** [comment]
[ru]
Разобрался.
В старой версии отправка сообщений по [Ctrl+Enter] работала даже если НЕ БЫЛО галочки около настройки «Горячие клавиши \ Окна сообщений - все \ Отправить».

В новой версии сегодня утром при первом обновлении в настройке «Горячие клавиши \ Окна сообщений - все \ Отправить сообщение» пропало значение шортката [Ctrl+Enter]. Первым делом я его восстановил, но вот галочку не выставил.

Сейчас заново накатил свежую версию. Значение шортката [Ctrl+Enter] на этот раз не пропало, но для того, чтобы он заработал пришлось выставить галочку около этого шортката.

Спасибо за оперативный ответ!
Задачу можно закрывать.

[en]
Solution: CheckBox ON in shortcut [Ctrl+Enter].
In old version [Ctrl+Enter] worked without [V], but for new version need to set CheckBox.

Thank you!
Problem solved, so you can close this task.
