### ISSUE TITLE
Групировка цифр и букв в ключе OMEMO

### ISSUE THREAD

**Issue by OmlineEditor** [miranda-ng/miranda-ng#3095]
Можно сделать более удобочитаемые ключи OMEMO?
Просто сгрупировав их по 8 символов можно добиться более удобочитаемого вида.

![omemo](https://user-images.githubusercontent.com/13348933/172186761-7e5a5e47-df7a-48c0-9a0b-9ed2fef928e9.png)

**Comment by OmlineEditor** [comment]
аналогично мешанина в отпечатке OMEMO при просмотре своего собственного отпечатка.
И еще там вкладки поломаны и они как-то налазят друг на друга, не получается их там в 2 ряда разместить.
![omemo2](https://user-images.githubusercontent.com/13348933/172188223-03bf909f-0522-463f-8b0c-709e570cba37.png)

**Comment by dartraiden** [comment]
Я бы ещё и в верхний регистр все эти ключи перевёл.

**Comment by OmlineEditor** [comment]
Вы сделали групировку в окне информации о владельце ключей, т.е. в личной карточке. А в окне где в самом начале когда идет вопрос об установке сессиии там по прежнему мешанина из букв и цифр. проверенно на версии 0.96.2.
Можно доделать и в этом самом первом окошке?

**Comment by georgehazan** [comment]
@OmlineEditor да есть там всё, отпечаток идет с разбивкой.
или надо приложить скриншот этого диалога
