### ISSUE TITLE
Миранда в самом начале при установлении OMEMO сесии падает

### ISSUE THREAD

**Issue by OmlineEditor** [miranda-ng/miranda-ng#3097]
Берем две одинаковые миранды 0.96.1 в них пока не уставновленных никакие OMEMO сессии и нет подтвержденных ключей
Начинаем писать сообщения друг другу, миранда начинает спрашивать о начале установки сессий OMEMO и требует подтверждение ключей. после начала этого действия то одна то другая миранда начинает падать, падает полностью что даже местами не дописывает в лог ошибки. Падает в момент отправки сообщений, то одна то другая миранда.
Потом, когда ключи установленны и подтверждены проблем нет, все работает как нужно.

В логах часто замечаю строки перед падением
`parsing error 6: Error=XML_ERROR_PARSING_ELEMENT ErrorID=6 (0x6) Line number=1: XMLElement name=preKeyPubl`
потом идет увеличение размера буфера для принятия данных и обычно при 16 килобайтах проблем нет. При этом буфер начинаетс с малых размеров, может его сразу большим поставить?

в момент падения миранды в логах такие строки:
`Jabber OMEMO: libsignal data backend impl: failed to load session (session does not exist)`

[netlog2_моя_миранда_упала_лог_с_нее_же.txt](https://github.com/miranda-ng/miranda-ng/files/8855258/netlog2_._._._._._._.txt)
[netlog2_чужая_миранда_упала_лог_с_моей_миранды_я_задосила.txt](https://github.com/miranda-ng/miranda-ng/files/8855259/netlog2_._._._._._._._._.txt)

**Comment by OmlineEditor** [comment]
Тоже самое при работе в последней тестовой версии 0.96.2
вот лог:
[v0.96.2.txt](https://github.com/miranda-ng/miranda-ng/files/8872536/v0.96.2.txt)

В логе видно что миранда говорит что OMEMO сессии нет, потом кажется пытается ее создать обмениваясь какими-то ключами и внезапно падает.

**Comment by georgehazan** [comment]
@OmlineEditor нужен не сетевой, а краш-лог (с установленным плагином CrashDumper)

**Comment by OmlineEditor** [comment]
в папке MirandaNG\Profiles\MyProfile\CrashLog\ пусто, есть только тот короткий лог что я привела.
CrashDumper плагин стоит, но он не работает т.к. миранда быстро падает и не успевает туда что-то записать.
Нужно CrashDumper запускать в отдельном потоке, в виде dll похоже не работает должным образом

**Comment by georgehazan** [comment]
@OmlineEditor а в настройках CrashDumper установлен именно этот путь?
А если скачать Windows Debugging Tools?

> Нужно CrashDumper запускать в отдельном потоке, в виде dll похоже не работает должным образом

CrashDumper запускается во всех потоках сразу.

**Comment by OmlineEditor** [comment]
> Windows Debugging Tools

Что это за зверь такой? может он уже у меня установлен только я незнаю об этом?
Это оно или нет? https://www.microsoft.com/en-us/download/details.aspx?id=8279

**Comment by OmlineEditor** [comment]
> нужен не сетевой, а краш-лог (с установленным плагином CrashDumper)

пробовала еще раз создать этот краш лог, но он не создается и ничего нет в папках. Может я что-то делаю не так?
Есть ПОДРОБНАЯ инструкция как правильно сделать этот лог?

**Comment by dartraiden** [comment]
Он либо создаётся, либо нет, повлиять на это пользователь не может.

**Comment by OmlineEditor** [comment]
> Он либо создаётся, либо нет, повлиять на это пользователь не может.

Ничего нет в моем случаи



> Можно прицепиться отладчиком к Миранде, в отладчике при падении будет видент стэк. Но для этого, разумеется, нужно ставить отладчик.

Могу попробовать поставить, если есть инструкция как это делать - я сделаю. Подскажите как это правильно сделать?

**Comment by dartraiden** [comment]
- поставить [VS Community](https://visualstudio.microsoft.com/ru/vs/community/), далее буду называть её "студией"
- запустить Миранду, убедиться, что в настройках обновлений выбран канал "Версия в разработке с отладочными символами"
- запустить студию
- Средства → Параметры → Отладка → Символы: добавить туда путь к папке, куда установлена Миранда

<img width="528" alt="devenv_eOG2RIEVp5" src="https://user-images.githubusercontent.com/5046855/192595353-8cf3eff9-5a7e-410c-9de9-81d4e428e7d7.png">

- Отладка → Присоединиться к процессу: выбрать в списке Миранду и присоединиться
- Повторить действия, приводящие к падению. Когда Миранда упадёт, щёлкнуть правой кнопкой в Стеке и включить "Показывать значения параметров". Скопировать всё содержимое Стека и вставить сюда

**Comment by OmlineEditor** [comment]
Critical error detected c0000374
Инструкция точки останова (оператор __debugbreak() или аналогичный вызов) выполнена в Miranda64.exe.

Необработанное исключение по адресу 0x00007FFDD2F8C9A9 (ntdll.dll) в Miranda64.exe: 0xC0000374: Куча была повреждена (параметры: 0x00007FFDD2FF7780).

[OMEMO.txt](https://github.com/miranda-ng/miranda-ng/files/9718464/OMEMO.txt)

**Comment by OmlineEditor** [comment]
> залил билд на сервер, можно пробовать

нужно в настройках обновления поменять на **_версию в разработке_** или глюк пофиксили в **_стабильной_** ветке?

**Comment by dartraiden** [comment]
Нужно, мы в стабильную не портируем непроверенные изменения.

**Comment by OmlineEditor** [comment]
Протестировала несколько раз кажется больше не падает, думаю проблема решена и тикет можно закрыть и добавить изменения в следующую стабильную ветку.
