### ISSUE TITLE
Miranda crashes randomly (null pointer dereference in NewEventNotify)

### ISSUE THREAD

**Issue by rkwk** [miranda-ng/miranda-ng#3103]
Crashes happen frequently (twice a day on average) on apparently random moments, without any user interaction. This keeps happening from at least 3rd of June.

The crash log (some parts removed for privacy):

	Miranda Crash Report from 15 Jun 2022 14:07:09. Crash Dumper v.0.2.0.1

	Likely cause of the crash plugin: NewEventNotify

	Exception: Access Violation at address 0000000018083F7E. Reading from address 0000000000000010.

	Stack Trace:
	---------------------------------------------------------------
	0000000018083F7E (NewEventNotify 0000000018080000): (filename not available) (0): (function-name not available)
	0000000018084D03 (NewEventNotify 0000000018080000): (filename not available) (0): (function-name not available)
	0000000018083522 (NewEventNotify 0000000018080000): (filename not available) (0): (function-name not available)
	00000000130AD93F (mir_core 00000000130A0000): (filename not available) (0): NotifyEventHooks
	00000000130AD76C (mir_core 00000000130A0000): (filename not available) (0): NotifyEventHooks
	0000000016B04A77 (Dbx_sqlite 0000000016B00000): (filename not available) (0): (function-name not available)
	00000000130A9B15 (mir_core 00000000130A0000): (filename not available) (0): db_event_add
	0000000016263D56 (AvatarHistory 0000000016260000): (filename not available) (0): (function-name not available)
	00000000130AD93F (mir_core 00000000130A0000): (filename not available) (0): NotifyEventHooks
	00000000130AD80D (mir_core 00000000130A0000): (filename not available) (0): NotifyEventHooks
	00000000130C0B48 (mir_core 00000000130A0000): (filename not available) (0): UnloadCoreModule
	00000000775D97A1 (USER32 00000000775C0000): (filename not available) (0): TranslateMessageEx
	00000000775D94C2 (USER32 00000000775C0000): (filename not available) (0): TranslateMessage
	00000000130C067A (mir_core 00000000130A0000): (filename not available) (0): Ordinal3
	0000000012EFB4B4 (mir_app 0000000012EA0000): (filename not available) (0): mir_main
	0000000140002904 (Miranda64 0000000140000000): (filename not available) (0): (function-name not available)
	00000001400014BA (Miranda64 0000000140000000): (filename not available) (0): (function-name not available)
	00000000776D55FD (kernel32 00000000776C0000): (filename not available) (0): BaseThreadInitThunk
	000000007783294D (ntdll 00000000777E0000): (filename not available) (0): RtlUserThreadStart

	[...]

	Miranda NG Version: 0.96.2 alpha build #24580 (3c1685dff7) x64
	Build time: 13 Jun 2022 22:07:26
	[...]
	Database driver: SQLite database driver
	Language pack: No language pack installed
	Service Mode: No

	Active Plugins (32):
	¤ AddContactPlus.dll v.0.9.9.2 [3 Jun 2022 16:20:50] - Add contact+ 
	¤ AuthState.dll v.0.0.2.2 [3 Jun 2022 16:20:14] - Authorization state 
	¤ AvatarHistory.dll v.0.1.0.2 [3 Jun 2022 17:44:54] - Avatar history 
	¤ AVS.dll v.0.98.1.4 [9 Jun 2022 22:31:22] - Avatar service 
	¤ Clist_modern.dll v.0.9.1.12 [3 Jun 2022 17:44:06] - Modern contact list 
	¤ CrashDumper.dll v.0.2.0.1 [3 Jun 2022 17:44:18] - Crash dumper 
	¤ Db_autobackups.dll v.0.1.0.6 [13 Jun 2022 22:07:56] - Db autobackuper 
	¤ DbChecker.dll v.0.95.13.3 [13 Jun 2022 22:10:38] - Database checker 
	¤ DbEditorPP.dll v.4.1.0.2 [3 Jun 2022 17:44:18] - Database editor++ 
	¤ Dbx_mdbx.dll v.0.95.9.1 [3 Jun 2022 17:46:24] - Miranda NG MDBX database driver 
	¤ Dbx_mmap.dll v.0.95.8.1 [3 Jun 2022 16:20:06] - Miranda NG mmap database driver 
	¤ Dbx_sqlite.dll v.0.96.1.2 [13 Jun 2022 22:10:38] - Miranda NG SQLite database driver 
	¤ Dummy.dll v.0.2.0.1 [13 Jun 2022 22:10:02] - Dummy protocol 
	¤ Facebook.dll v.0.1.0.11 [3 Jun 2022 17:46:18] - Facebook 
	¤ Fingerprint.dll v.0.2.0.1 [3 Jun 2022 17:44:44] - Fingerprint NG 
	¤ GG.dll v.0.95.11.1 [13 Jun 2022 22:07:52] - Gadu-Gadu protocol 
	¤ historypp.dll v.1.5.1.5 [3 Jun 2022 17:46:46] - History++ 
	¤ Import.dll v.0.95.11.1 [13 Jun 2022 22:08:04] - Import contacts and messages 
	¤ Jabber.dll v.0.95.11.1 [13 Jun 2022 22:08:28] - Jabber protocol 
	¤ MessageState.dll v.0.1.0.2 [3 Jun 2022 17:45:44] - Message state 
	¤ NewEventNotify.dll v.0.2.2.5 [12 Jun 2022 19:08:20] - NewEventNotify 
	¤ PluginUpdater.dll v.0.2.1.3 [3 Jun 2022 17:44:34] - Plugin updater 
	¤ Restart.dll v.0.0.6.0 [3 Jun 2022 17:44:36] - Restart 
	¤ SeenPlugin.dll v.5.0.5.6 [9 Jun 2022 22:31:56] - Last seen 
	¤ Sessions.dll v.0.2.0.1 [3 Jun 2022 16:20:42] - Sessions 
	¤ SkypeWeb.dll v.0.95.13.3 [13 Jun 2022 22:10:24] - Skype protocol (Web) 
	¤ SmileyAdd.dll v.0.3.2.1 [3 Jun 2022 16:20:48] - SmileyAdd 
	¤ SpellChecker.dll v.0.2.6.6 [9 Jun 2022 22:32:36] - Spell checker 
	¤ StatusManager.dll v.1.2.0.6 [3 Jun 2022 17:46:00] - Status manager 
	¤ TabSRMM.dll v.3.6.2.2 [12 Jun 2022 19:07:30] - TabSRMM 
	¤ Tipper.dll v.2.1.0.7 [3 Jun 2022 16:20:44] - Tipper 
	¤ TopToolBar.dll v.0.8.0.5 [3 Jun 2022 17:44:00] - TopToolBar

**Comment by dartraiden** [comment]
Crashlog without debug symbols is useless. Please download debug symbols and try again.
https://wiki.miranda-ng.org/index.php?title=Crash_reports

**Comment by rkwk** [comment]
I've got the stack trace with debug symbols, but I see that you've figured it out already. That's exactly the place you've fixed:

    w:\miranda-build\plugins\neweventnotify\src\popup.cpp (293): GetEventPreview

Thanks!
