### ISSUE TITLE
Steam plugin will not stay connected for more than 1-2 minutes.

### ISSUE THREAD

**Issue by RathaWynter** [miranda-ng/miranda-ng#3112]
Miranda's Steam plugin will not stay connected for more than 1-2 minutes at a time.
- Issues began June 23 or June 24, 2022 (either on the day the Steam sale started, or the day after, its not quite clear.)
- The Steam API was offline for close to 3 hours on June 23.
- The Netlog reports an HTTP 500 error.
- The issue of being disconnected every 1-2 minutes was highly noticeable for almost the entire day of the 24th.

Tested with multiple different versions:
- 0.96.2 #24623 (Used for Netlog)
- 0.96.1 #24180
- 0.95.13 #23733 (Edit: Added this netlog as well)

Tested on two different Steam accounts:
- One with ~160 contacts
- One with ~10 contacts (Test account used for netlog)

Miranda will make a successful login, download user statuses, and any messages that are on the server, but will typically lose connection 1-2 minutes after that. The netlog included was captured starting from ~30 seconds after logging in until disconnection.

Extra notes:
Its difficult to know when these problems start because Miranda does not often report the status of the Steam protocol correctly and will often say the protocol is online when it is not. (This is an old issue.)

Additionally it often takes logging in, going offline, and then setting status back to online again in order to establish a proper connection with the Steam plugin (on the account with 160 friends.) (This is also an old issue.)

https://help.steampowered.com/en/accountdata/SteamLoginHistory
![Steam_Test_Account_Logins](https://user-images.githubusercontent.com/35881801/175773373-4fea5f06-7ad8-4eec-a191-f084de2b6fbc.png)

Netlog specific to 'Miranda wont stay connected for more than 2 minutes':
[_Netlog_TestAccount_Sanitized.txt](https://github.com/miranda-ng/miranda-ng/files/8984676/_Netlog_TestAccount_Sanitized.txt) - 0.96.2 #24623
[_Netlog_TestAccount_Sanitized_95_13.txt](https://github.com/miranda-ng/miranda-ng/files/8984764/_Netlog_TestAccount_Sanitized_95_13.txt) - 0.95.13 #23733

[VersionInfo.txt](https://github.com/miranda-ng/miranda-ng/files/8984681/VersionInfo.txt)

**Comment by LittleVulpix** [comment]
I have the same issue. Won't stay connected at all, and it also started at the same time as @RathaWynter 's issue. So I guess it's something serverside, but not sure what or why it impacts just Miranda. The mobile client _seems_ fine.

**Comment by RathaWynter** [comment]
Neither the Steam Client, nor the [Webchat](https://steamcommunity.com/chat/) seem to be affected by this issue for what thats worth.

I do not know anyone who uses Pidgin / if that client even still has Steam protocol access. I wasn't able to find an issue tracker with current issues, nor their support forums, assuming they exist.

**Comment by georgehazan** [comment]
@RathaWynter and if you delete that access token from Miranda's profile, it will recalculate it?

**Comment by RathaWynter** [comment]
To clarify: You're talking about deleting the "TokenSecret" from the database for the Steam protocol?

I had not logged into the Test Account with Miranda in probably a year, and had to enter a new email authorization code in order to log in, so i assume that should have had a newly generated a new one. But i tested deleting it anyway:
- Deleted the "TokenSecret" from the database and closed Miranda.
- Re-opened Miranda, set Online status for Steam.
- Was prompted to re-enter my Email Auth code again, which i did.
- Miranda still only stays connected to Steam for less than 2 minutes.

**Comment by LittleVulpix** [comment]
Steam proto also deletes the token itself if the login is unsuccessful for a few times in succession; on my account this happened so I also have a new token, but I also can't stay connected for more than a few minutes.

**Comment by RathaWynter** [comment]
Still no change in connectivity or error since the 23rd. Can only stay logged in for 1-2 minutes.
Steam is still returning HTTP 500 errors for Miranda at essentially all hours of the day.

Are we dealing with a case of Miranda receiving a response it does not recognize, and therefore terminating connection, or are we being forcibly disconnected in some fashion like anti-bot or some kind of user-agent targeting given how reliably it happens? Its odd to me that Steam would allow a login, transmit message as well as user status info, then disconnect after about 60 seconds.

Heres one more log for comparison purposes. Like the first one this log was captured starting ~10 seconds after login (to avoid capturing too many private credentials and user info.)
[Netlog_Sanitized.txt](https://github.com/miranda-ng/miranda-ng/files/8998176/Netlog_Sanitized.txt)

**Comment by georgehazan** [comment]
@RathaWynter which request causes error 500? is that possible to print it?
or email the original variant of log to me privately

**Comment by RathaWynter** [comment]
@georgehazan Ive got a partially sanitized log that i could send you via email if you like, however the HTTP 500 appears 30 seconds after the next nearest thing. Heres (some of) the events immediately prior to the request, but there is a bit of other stuff that happens at this time stamp as well. You might want to see the full log instead, but i'd be surprised if the answer is in there.

```
[12:28:55 1AF4] [STEAM_1] (0000000003763670:744) Data received
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Vary: Accept-Encoding
Content-Encoding: gzip
Expires: Tue, 28 Jun 2022 18:28:54 GMT
Date: Tue, 28 Jun 2022 18:28:54 GMT
Content-Length: 588
Connection: close

‹ {"players":[{ ------------------- "players request here" --------------------------- }]}

[12:28:55 1AF4] [STEAM_1] (0000000003763670:744) Connection closed internal
[12:28:55 1AF4] [STEAM_1] (0000000003763670:4294967295) Connection closed
[12:28:55 0BD8] M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:schemas-upnp-org:service:WANIPConnection:1

[12:28:55 0BD8] M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:schemas-upnp-org:service:WANPPPConnection:1

[12:28:57 0BD8] UPnP Gateway detected 0, Control URL: 

---------------------30 seconds later---------------------------

[12:29:26 1B1C] [STEAM_1] (0000000003CEF310:736) Data received
HTTP/1.1 500 Internal Server Error
Content-Length: 141
Content-Type: text/html; charset=UTF-8
Expires: Tue, 28 Jun 2022 18:29:25 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 28 Jun 2022 18:29:25 GMT
Connection: close
X-N: S
```

**Comment by LittleVulpix** [comment]
I had a look; the web client uses a websocket so it's completely different from Miranda now.
I tried playing around with the timeout settings of the plugin but there was no real change.
There was one time where I stayed connected approx... 3 minutes. But after that I got the error again.
I don't think we are sending anything wrong, I think that whatever is happening is currently broken at Steam side or at Akamai somewhere (kind of like it was with Cloudflare).
It's weird because the first few polls are always successful.
Also it is always the poll request that fails - it stays "pending" / waiting, open towards the server, until the server responds back with error 500. But it responds back normally all the other times.
Unless someone can rewrite the steam proto to work over websocket, might be that we just have to wait for this to pass... not a fun prospect.

**Comment by georgehazan** [comment]
@LittleVulpix is that possible that you make a dump of Websocket packets? Maybe it would be simpler to switch to WS instead of writing brand new plugin for Steam

**Comment by georgehazan** [comment]
@LittleVulpix I have one, but I can't login since some time, it even doesn't pass SSL handshake. I even thought that it might be caused by all that shit that happens around Russia those times, I'll try to use the web client a bit later.

**Comment by georgehazan** [comment]
@LittleVulpix web chat succeeded
which nick is yours? Dajkamienia123?

**Comment by LittleVulpix** [comment]
@georgehazan I added you as friend but seems no accept.
@RathaWynter yeah I've been connected for a while as well now in fact. Didn't get booted (yet).

**Comment by RathaWynter** [comment]
@LittleVulpix Would you mind adding me on [Steam](https://steamcommunity.com/id/RathaWynter) as well? Im not sure how much more I can contribute toward solving the current problem if you two are looking into packet tracing, but for testing and future discussion of such issues it might be nice to have a direct line to someone to discuss them with.

I assume that you've returned to having constant connection issues as well after that short period on the 30th?

**Comment by LittleVulpix** [comment]
Just commenting that indeed the "restoration of functionality" was temporary and the issue is still ongoing.
@georgehazan if you need anything I did add you so feel free to contact me for whatever testing you might need.

Thanks.

**Comment by RathaWynter** [comment]
About 99% of the time the connectivity is 2 minutes for me, with a few rare exceptions. All of this began when the Steam sale started. The Steam sale ends in about 14 hours. I am really hoping that when the sale stops that things go back to normal, but if this is any indication of whats going to happen in future sales, we may be in some trouble. Im honestly surprised to have not gotten banned by steam for making so many login attempts over the last 2 weeks. I have to be in the thousands by now.

**Comment by LittleVulpix** [comment]
I basically only do a "retrieve chat messages once a day" reconnect for now, and I'm using the actual client for chatting (temporarily).

**Comment by RathaWynter** [comment]
Seems that whatever caused this during the start of the sale on the 23rd, has not resolved since the sale ended on the 7th. There was a 3-hour or so maintenance on the servers both at the start and end of the sale which i had hoped would maybe resolve whatever caused this connection problem, but no luck. Had assumed that a reduction in API calls, or active users on the platform after the sale ended might result in some better connectivity through the plugin, but theres been no real change since the issue started. Only the very rare 5-10 minute connection, extremely rare 1 hour connection, and the rest of the time disconnects after 1-2 minutes.

Activity on the connection such as typing notifications or messages being actively sent or received does not appear to have an impact on duration of connection.

**Comment by LittleVulpix** [comment]
@georgehazan , I put in these changes and I've been connected for a while now, too (when previously it would boot me off after a minute or two). I wonder what happened, why did they change the endpoint link/spec? :D In fact, most curious is why it worked this way previously and now it stopped working...

Anyway thank you for the fix, much appreciated.

**Comment by RathaWynter** [comment]
Thanks @georgehazan this update seems to have resolved the issue immediately. The disconnections every 1-2 minutes seem to have stopped. Thanks for looking into it!

How difficult was it to figure out what the problem was / was there any bit of data here that led you in the right direction toward figuring it out? Asking to help better understand what kind of info was useful and what was not for future reference, as well as wondering how you solved it or what tools were used.
