### ISSUE TITLE
tabSRMM: добавить в лог пункт контекстного меню "Копировать"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3114]
1) добавить в контекстное меню (пкм по журналу) пункт "копировать", копирующий выделенный текст
2) если включена настройка "копировать автоматически при выделении", то не показывать этот пункт (как бессмысленный)
3) если текст не выделен, то желательно тоже не показывать этот пункт

**Comment by dartraiden** [comment]
Попутно предлагаю рассмотреть нужность имеющегося пункта "Копировать всё".

**Comment by georgehazan** [comment]
может объединить их.... если есть выделение и не стоит автоматически копировать при выделении, то показывать текст "Копировать", иначе "Копировать всё",

**Comment by dartraiden** [comment]
В приватах появилось, в групчатах - нет.
