### ISSUE TITLE
PluginUpdater не стирает старую версию libmdbx.mir

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3125]
- берем 0.95.12.1
- создаём mdbx-профиль
- обновляемся до текущей стабильной версии

результат: апдейтер почему-то не стирает libmdbx.mir из корневого каталога, из-за этого dbx_mdbx не может стартануть и конвертации профиля не происходит

**Comment by georgehazan** [comment]
Он и не должен. libmdbx.mir стирает **новый** PU, а для этого ему надо запуститься, что будет только после рестарта
