### ISSUE TITLE
tabSRMM: "Colorize nickames in member list" chat option

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3126]
1) Does not work at all (it enabled on new profile by default but all nicks are not colored)
2) Disable/enable optiin -> nick list size will be reset to default width

**Comment by georgehazan** [comment]
1. Всё прекрасно работает, надо только задать цвета в опциях (Options - Customize - Fonts & colors - Group chats)
2. Поправил
