### ISSUE TITLE
WhenWasIt ведёт себя странно

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3130]
Пользовать в конференции сообщает

> [20:19]	RX-3200: напоминатор о днях рождениях снова игнорит сохранённые даты
> считалка количества лет отломилась

От себя могу добавить баг:
- пкм по пользователю в клисте → add/change users birthday → выставляем ему день рождения завтра
- около пользователя в клисте появляется воздушный шарик с цифрой 1 (остался один день)
- перезапускаем Миранду
- шарика нет

**Comment by georgehazan** [comment]
@dartraiden а о чем это?

[20:19] RX-3200: напоминатор о днях рождениях снова игнорит сохранённые даты
считалка количества лет отломилась

не наблюдаю вот этого

**Comment by dartraiden** [comment]
1) ставим UInfoEx и WWI
2) пкм по юзеру, у которого с сервера не приходит инфа о ДР (я тестировал на юзере протокола VK) -> Add/change user birthday -> открывается диалог WWI, где юзеру задаём дату рождения (допустим, 1 апреля 1990) с хранением её в модуле UserInfo

<img width="145" alt="mstsc_YP5QaNZ5lL" src="https://user-images.githubusercontent.com/5046855/181994898-265121b1-c27c-4c37-a56c-42fe4e005072.png">

3) открываем user info и переходим в Anniversaries

Результат: поскольку мы сохранили дату в модуль [UserInfo], а UInfoEx читает дату из модуля протокола, где даты рождения нет, он показывает сегодняшнюю дату

Окей, а если мы на скриншоте выше сохраним нашу вручную заданную дату в модуль протокола, а не в [UserInfo]? Тогда UInfoEx покажет корректную дату рождения, но при выходе в онлайн она сотрётся, т.к. с сервера прилетает пустота.

**Comment by dartraiden** [comment]
Тут возникает вопрос. Допустим, мы научим UInfoEx заглядывать не только в модуль протокола, но и в [UserInfo]. С сервера у контакта прилетает дата 1 мая 2000, а в [UserInfo] у нас хранится 1 апреля 1990.

Какую дату из двух мы должны показать в UinfoEx и StdUserInfo?
Какую из двух дат мы должны показать в WWI? (главное меню -> Дни рождения)

**Comment by georgehazan** [comment]
> Какую дату из двух мы должны показать в UinfoEx и StdUserInfo (не забываем и про него)?

C очевидностью, тот модуль, который стоит в настройках UInfoEx (там можно выбрать).

> Какую из двух дат мы должны показать в WWI?

Модуль, который стоит в настройках WWI, в свою очередь. Можно, конечно, грохнуть этот зоопарк и всегда писать в модуль протокола, так будет проще.

**Comment by dartraiden** [comment]
> C очевидностью, тот модуль, который стоит в настройках UInfoEx (там можно выбрать)
Что делать с StdUserInfo?

> Модуль, который стоит в настройках WWI, в свою очередь.
В WWI нет такой настройки "всегда писать туда-то". Там только при добавлении даты есть возможность выбрать, но оно индивидуально для каждого контакта. То есть, у одного контакта можно писнуть в UserInfo, а у другого в модуль протокола.

> Можно, конечно, грохнуть этот зоопарк и всегда писать в модуль протокола, так будет проще.
Тогда будет облом в случаях, когда у пользователя не указана дата на сервере. Наша кастомная дата в этом случае затирается протоколом каждый раз.

**Comment by dartraiden** [comment]
Есть вариант научить WWI и userinfo-плагины выводить обе даты.

**Comment by dartraiden** [comment]
Можно сделать так:

- из WWI мы удаляем возможность писать в модуль протокола, отныне он будет писать строго в модуль UserInfo
- WWI, StdUserInfo и UInfoEx мы переделываем таким образом, что они сначала ищут дату в UserInfo, а если там пусто, то в модуле протокола

**Comment by dartraiden** [comment]
Берем контакт, у которого по протоколу прилетают день и месяц, но не год (год он не указал). Смотрим список праздников через WWI:

![изображение](https://user-images.githubusercontent.com/5046855/182043802-5935bd1f-c17c-45fa-a61c-58bfbd24e380.png)

Всё корректно, год не указан - поэтому возраст неизвестен. Теперь через WWI добавляем в модуль [UserInfo] ему дату рождения 1 апреля 2000 года. Снова смотрим список праздников:

![изображение](https://user-images.githubusercontent.com/5046855/182043910-c55bb40c-2ed2-4aae-95e4-eadc27bfb4b7.png)

баг №1: у инфы из протокола тоже появился возраст, хотя там по-прежнему 0000 год и возраст должен быть неизвестен?
баг №2: пкм по первой строке (которая взята из UserInfo) → удалить. Вылезает запрос на удаление неизвестного контакта (если удалять, кликая по второй строке (где инфа из протокола), то всё корректно.

![изображение](https://user-images.githubusercontent.com/5046855/182043998-0ed9b49c-38f5-40cb-8077-9e90fb987148.png)

**Comment by georgehazan** [comment]
поправил всё кроме диалога из п.3, потому что он где-то еще, не в WWI. надо искать

**Comment by georgehazan** [comment]
убил диалог нахер. больше мы его не увидим

**Comment by dartraiden** [comment]
Что мы хотели сделать:
1) чтобы кастомная дата рождения улетала в UseInfo, а не в модуль протокола
2) не хранить возраст в годах, а вычислять его каждый раз

Что получилось:
1) кастомная дата пишется в модуль протокола
2) возраст (Age) пишется в UserInfo
