### ISSUE TITLE
StdUserInfo не добавляет пункт "User details" в меню контакта, когда вгружен на лету

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3132]
- запускаем миранду с UInfoEx
- выгружаем UInfoEx

ожидаемое поведение: в бой вступает StdUserInfo и в меню контакта появляется пункт для просмотра юзеринфо

реальное поведение: пункта нет, просмотреть юзеринфо невозможно

**Comment by georgehazan** [comment]
правда щастья всё равно не будет: этот пункт появится, но делать не будет ничего, и это пока никак не поправить
