### ISSUE TITLE
RFC 9266: Channel Bindings for TLS 1.3 support

### ISSUE THREAD

**Issue by Neustradamus** [miranda-ng/miranda-ng#3140]
Can you add the support of RFC 9266: Channel Bindings for TLS 1.3?
- https://datatracker.ietf.org/doc/html/rfc9266

Little details, to know easily:
- tls-unique for TLS =< 1.2
- tls-exporter for TLS = 1.3

Thanks in advance.

Linked to:
- https://github.com/miranda-ng/miranda-ng/issues/1727

**Comment by georgehazan** [comment]
@Neustradamus hi, is there a server where I could test this feature?

**Comment by georgehazan** [comment]
Aha, Prosody is ok, I'll upgrade my server

**Comment by georgehazan** [comment]
@Neustradamus I've added some code and tested that it really reports some data. Unfortunately, I hadn't verified it with the real server, because I still don't have the version of Prosody that supports it.

**Comment by Neustradamus** [comment]
@georgehazan: Thanks for your changes!

You can not try with Prosody trunk?

**Comment by Neustradamus** [comment]
@georgehazan: Have you looked for "tls-server-end-point"?

**Comment by Neustradamus** [comment]
@georgehazan: Have you looked for "tls-server-end-point" in more "tls-unique" and "tls-exporter"?

It is supported by:
- ejabberd (@prefiks): https://github.com/processone/xmpp/blob/ded8be8c169487688b11130eda566b1377ab3301/src/xmpp_stream_in.erl#L934
- Prosody IM: https://hg.prosody.im/trunk/log?rev=tls-server-end-point
- Tigase XMPP Server: https://github.com/search?q=org%3Atigase+tls-server-end-point&type=code

**Comment by georgehazan** [comment]
The problem is where to get Prosody Trunk... I have Ubuntu on my desktop, and it comes with the previous version, those SASL fixes were introduced only 8 weeks ago

**Comment by Neustradamus** [comment]
Here:
- https://hg.prosody.im/trunk/
- https://prosody.im/download/start
- https://prosody.im/download/start#nightly_builds

**Comment by Neustradamus** [comment]
@georgehazan: You can try the ejabberd master code with deps too...
- https://github.com/processone/ejabberd

For Prosody IM, it is here:
- https://hg.prosody.im/trunk/
- https://prosody.im/download/start
- https://prosody.im/download/start#nightly_builds

**Comment by Neustradamus** [comment]
@georgehazan: Have you tested?

**Comment by georgehazan** [comment]
> Have you tested on ejabberd test server?

Nope, only on Prosody, it works well
