### ISSUE TITLE
Add VoiceService to installer and portable package

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3153]
Сейчас у нас получилась странная ситуация, когда инсталлятор и портативная версия содержат только Jabber.dll, а вот если ставить Jabber через апдейтер, то с ним прилетит VoiceService.

Если в инсталляторе пользователь не выбрал Jabber для установки, то и не следует отгружать ему VoiceService.

**Comment by georgehazan** [comment]
@dartraiden вообще не умею в инсталлятор. посмотришь?

**Comment by dartraiden** [comment]
Нужно не забыть добавить ещё и в инсталлятор /архив / Jabber.zip стабильной версии, когда плагин станет стабильным.
