### ISSUE TITLE
TabSRMM: значок в окне предупреждения

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3158]
<img width="357" alt="Miranda64_5lnS2GYrha" src="https://user-images.githubusercontent.com/5046855/184408210-fc020620-5876-407c-8f25-6047f5932473.png">

у значка явно что-то не так с каёмкой

**Comment by georgehazan** [comment]
это какая-то особенность твоей винды...
на Windows 1- всё идеально
