### ISSUE TITLE
HistoryPP: проблемы с выгрузкой плагина

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3163]
- берем дистрибутив Миранды с сайта
- ставим H++, он вгружается на лету
- выбираем в табсах H++ как журнал для приватов и чатов
- ставим NewStory, он вгружается на лету, H++ выгружается соответственно, получаем такую (правильную) картину:

![4543е43е4е4е4](https://user-images.githubusercontent.com/5046855/184973983-83c687b3-c4de-4032-a40f-dfc2b3f155cf.png)

- закрываем настройки кнопкой ОК, открываем их снова и снова жмём ОК

Баг: в этот момент вгружается H++, хотя никто его об этом не просил

**Comment by georgehazan** [comment]
стало чуть иначе
стоит H++, он выбран как дефолтный лог в табсах
ставим и вгружаем NewStory
H++ выгружается при этом автоматом
табсы начинают юзать встроенный журнал, т.к. H++ уже нет
закрываем окно настроек ОК
снова открываем и снова ОК
H++вгрузился
