### ISSUE TITLE
Modern contact list: Не отображаются аватары в ростере.

### ISSUE THREAD

**Issue by radjah** [miranda-ng/miranda-ng#3164]
### Expected behavior
При включении опции Список контактов > Элементы строк > Вкладка "Аватары" > Показывать аватары должны выводиться в списке контактов.

### Actual behavior
При включении опции Список контактов > Элементы строк > Вкладка "Аватары" > Показывать аватары происходит только увеличение высоты строк контактов, но аватары не отображаются.

![изображение](https://user-images.githubusercontent.com/1141613/185004496-59c32f5e-bc99-48d3-9862-5894ed99ad4c.png)

### Does it work in stable version?
Не знаю.

### Steps to reproduce that behavior
Поставить флажок "Показывать аватары" на странице настроек "Список контактов > Элементы строк > Вкладка Аватары"
Нажать применить.

После перезапуска ничего не меняется.

version info https://pastebin.com/raw/Jcy7cFU5

![изображение](https://user-images.githubusercontent.com/1141613/185003802-adce8202-dae0-4817-a8b4-09827b4963da.png)
![изображение](https://user-images.githubusercontent.com/1141613/185003830-baf360f8-1541-4d9b-92a6-ca068a837885.png)

**Comment by georgehazan** [comment]
решается выключением компактного режима
