### ISSUE TITLE
importTXT and events

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#317]
**Reported by alaxa on 20 Jul 2014 20:27 UTC**
 HI there, I'm trying to import old histories using importTXT plugin+msg_export.dll and I ended up with some questions:

1) importing the TXT seems fine but I'm not sure if the dupes are correctly handled or removed. What is checking exactly? I mean:

```
alaxa 12/05/2010 14:56:22 hi
alaxa 12/05/2010 14:56:22 <space>
alaxa 12/05/2010 14:56:22 <return>
```

ok one has to be fast by i have such records, what the plugin is checking? only the date/time or also the message? beacuse it seems to me that only date/time is checkd.

2) I'm not sure but I think that "file events" are not well handled. After importing the history I see from history++ that such events are seen as standard messages (usually they are color marked or I can see an icon). Here I don;t know if it's a matter of msgExport.dll because exporting the history as mContact from history++ and importing as mContact from importTXT works and I see such events

**Comment by LittleVulpix** [comment]
1) yes, importTXT only uses timestamps. If you are certain your imported text contains no duplicates but not sure if it contains some duplicate timestamps (which it totally can), you should uncheck the option.

2) file events are not handled well for text exports.

As you noted/noticed, using the mContact export (and then import) option via history++/importTXT is the most reliable method, as it also copies avatar history etc. The importTXT module is fairly old and could use some sprucing up (as would the msg export).

**Comment by LittleVulpix** [comment]
@georgehazan 

You can close this.

Point 1 is now logged separately by #708 and point 2 has been logged as #682 previously, I just didn't realize it was the same issue.
