### ISSUE TITLE
VoiceService: drop autoaccept calls feature

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3170]
> [20:03]	deadsend: как должен выглядеть юзкейс автоматического приема звонков? Сидьши сидищь за копом и тут из колонок кто-то говорить начинает?
> [21:19]	deadsend: В связи с этим предлагаю выкинуть автоприем звонков, а вместе с ним и соотв страницу опций. А автосброс звонков перенести на общую страницу игнора событий

**Comment by georgehazan** [comment]
автоприем уже вылетел, а соотв. страницу в игнор не перенести никак, потому что он тупо о звонках не в курсе
