### ISSUE TITLE
VoiceService: add sounds into installer

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3177]
> С точки зрения нормального UX нам бы теперь нужно вместе с VoiceService звуки поставлять, по меньшей мере те которые вызов, занято и входящий звонок, и чтобы они по умолчанию были установлены

**Comment by dartraiden** [comment]
[274289__abernstein__rotary-phone-ring-medium.zip](https://github.com/miranda-ng/miranda-ng/files/9436766/274289__abernstein__rotary-phone-ring-medium.zip)

source: https://freesound.org/people/AberNStein/sounds/274289/

**Comment by dartraiden** [comment]
[ring.zip](https://github.com/miranda-ng/miranda-ng/files/9438124/ring.zip)

@georgehazan положи этот файл, пожалуйста, к другим файлам, перечисленным в https://github.com/miranda-ng/miranda-ng/blob/master/tools/installer_ng/Common/Files/Settings/autoexec_sounds.ini

**Comment by georgehazan** [comment]
положил
