### ISSUE TITLE
Wiki: невозможно редактировать вики через API

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3180]
Пытаюсь делать правки через AutoWikiBrowser. До обновления движка работало.

Сейчас от вики приходит "API returned the following error: 'You're not allowed to edit this wiki through the API.'"

**Comment by dartraiden** [comment]
1) прочитал https://www.mediawiki.org/wiki/API:Changing_wiki_content
там написано, что доступ к апи включен по умолчанию в движке

на всякий случай добавил в конфиг вики

```
$wgEnableAPI = true;
$wgEnableWriteAPI = true;
```

2) прочитал https://www.mediawiki.org/wiki/API:Restricting_API_usage

**Comment by dartraiden** [comment]
https://wiki.miranda-ng.org/api.php?action=query&meta=userinfo&uiprop=*

показывает, что право writeapi у меня есть

**Comment by georgehazan** [comment]
https://stackoverflow.com/questions/63136509/error-when-editing-wikimedia-page-in-a-protected-namespace-with-api

**Comment by dartraiden** [comment]
По какой-то причине, если для группы все (`*`) запрещен доступ к `writeapi`, то даже если для конкретной группы (например, `users`) этот доступ разрешён, то движок всё равно его запрещает.

Решение: я просто разрешил всем доступ к `writeapi`
