### ISSUE TITLE
Update hunspell to 1.7.1

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3183]
https://github.com/hunspell/hunspell/releases/tag/v1.7.1

наши изменения, которые, вероятно, нужно перенести в новую версию (особенно напрягает переименование файлов, зачем?)

https://github.com/miranda-ng/miranda-ng/commit/97a16a6e09df80ffa3429e23a0174bd8daaa29a1
https://github.com/miranda-ng/miranda-ng/commit/28bfc1633faded06c14308959796cc350878a896
https://github.com/miranda-ng/miranda-ng/commit/63bb7d10c06fd8747412e76572647577e74a4bb5
https://github.com/miranda-ng/miranda-ng/commit/bebafc42ab6199e86d4c2c901fac8d091bfffef0
https://github.com/miranda-ng/miranda-ng/commit/20c605478b56c89841adfc5ccb2d81758fda5745

**Comment by georgehazan** [comment]
файлы переименованы, потому что в наших шаблонах на расширение cxx повешено другое действие совсем - это stdafx.cxx
