### ISSUE TITLE
VoiceService: hide auto actions settings page if we do not have accounts with VOIP enabled

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3187]

**Comment by dartraiden** [comment]
А нельзя как-то более оперативно скрывать?

Сейчас у нас так: я выключаю поддержку VOIP в настройках протокола, а эти настройки пропадают из дерева настроек лишь после перезапуска миранды.

**Comment by georgehazan** [comment]
> Можно ли сделать так, чтобы они скрывались уже при переоткрытии окна настроек?

Формально нет, потому что список страниц опций уже считан и сидит в памяти в виде дерева. Жуткий костыль, который перехватывает смену лангпака на лету, лепить по такому поводу в опции жабера не хочется
