### ISSUE TITLE
Jabber: XEP-0198 не даёт перевести протокол в оффлайн, пока Миранда пытается переподключиться

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3189]
> [18:23]	deadsend: багрепорт: в жаббере при включенном xep-0198 отвалившееся соединение уходит в реконнект. В этом состоянии его нельзя перевести в оффлайн

**Comment by georgehazan** [comment]
XEP-0198 тут никаким боком. Просто пока идет подключение, жабер не дает сменить статус, пока сокет не отпотеет
