### ISSUE TITLE
Инвертированная логика отображения/скрытия групп в контакт-листе

### ISSUE THREAD

**Issue by goonis** [miranda-ng/miranda-ng#3195]
При включении опции группы исчезают из контакт-листа, 
![image](https://user-images.githubusercontent.com/8069033/190930014-786b6f02-8c48-401c-a4c3-f843d689e5d6.png)
![image](https://user-images.githubusercontent.com/8069033/190930024-ea230059-7416-41fe-b827-b4d765ed6918.png)

при отключении - появляются.
![image](https://user-images.githubusercontent.com/8069033/190930040-c555d0e4-9038-449e-8803-0adc6a6e8f4d.png)
![image](https://user-images.githubusercontent.com/8069033/190930060-b3eac526-e123-432d-b06d-666d3beebc1e.png)

версия 0.96.1 #24544 x64

**Comment by dartraiden** [comment]
Со всеми тремя (StdClist, Clist_modern, Clist_nicer) у меня всё ок: когда настройка включена, группы есть, когда отключена - групп нет.

**Comment by goonis** [comment]
У меня StdClist и да, перезапуск клиента проблему решил. 
Спишем на расположение звезд на небе, спасибо.
