### ISSUE TITLE
Нехватка места в диалоге общих настроек списка контактов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3198]
Текст одной настройки не помещается

<img width="503" alt="Miranda64_gqiZd9qlPQ" src="https://user-images.githubusercontent.com/5046855/191098161-2b14f17f-88d1-4ce6-afab-e13b124cab6b.png">

**Comment by georgehazan** [comment]
Просто перевод сделай нормальным. 
"Поиск в режиме фильтра"
