### ISSUE TITLE
Jabber: добавить редактирование в списки

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3205]
<img width="385" alt="Miranda64_RfZ7tmf6o3" src="https://user-images.githubusercontent.com/5046855/192147771-99cc57fa-78ac-4944-b508-aa6045b79eb1.png">

В этом окне и во всех подобных ему (списки участников, юзеров, забаненных) нет возможности скопировать JID или отредактировать запись

**Comment by georgehazan** [comment]
редактирования тут быть не может, потому что в XMPP определены только операции добавления и удаления из списка. Копирование в клипборд повесил
