### ISSUE TITLE
Jabber: incorrect presences

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3206]
deadsend: от миранды приходят пресенсы с 
```
<x xmlns="vcard-temp:x:update">
    <photo />
</x>
```

deadsend: там должен быть хеш от аватарки, например
```
<x xmlns="vcard-temp:x:update">
<photo>
a6f2aa4d0ad9ccd6d82caa0d52db883b1556881a
</photo>
</x>
```

**Comment by georgehazan** [comment]
у нас для групчатов и всего прочего летит точно такой же презенс, как и для всего остального
дальше дело сервера, как он это препарирует и выпиливает
