### ISSUE TITLE
tabSRMM: per contact message log

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3207]
From old tabSRMM documentation:

`to set the option for a single contact only, use the contacts user menu and select Messaging settings.... The Message log view mode option can be used to either choose the global setting or override this with one of the 3 options also available in the global setting.`

I cannot find "Message log view mode". Is it still actual?

**Comment by dartraiden** [comment]
Same question about https://wiki.miranda-ng.org/index.php?title=Plugin:TabSRMM/Keyboard_layout

**Comment by georgehazan** [comment]
и то, и то давно выпилено.
