### ISSUE TITLE
tabSRMM: настройка попапов о наборе текста не учитывает существования Toaster

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3209]
<img width="503" alt="Miranda64_U4lKhyaNQQ" src="https://user-images.githubusercontent.com/5046855/192166677-dd1ac729-4b91-4c47-ab8f-72eb64163a65.png">

В документации написано, что выделенная красным настройка неактивна, если отсутствует плагин всплывающих окон. Но она проверяет лишь существование StdPopup и Popup+. Если юзер использует Toaster и стёр ядерный плагин StdPopup, то настройка будет неактивна, хотя по факту плагин попапов (Toaster) есть.

**Comment by georgehazan** [comment]
Управляется эта хрень только с помощью Options - Popups - Events - Typing notifications
