### ISSUE TITLE
StdMsg: не работает двойной клик во встроенном журнале, а тройной клик ведёт себя по-разному в приватах и чатах

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3210]
1) Двойной клик в приватах и чатах ничего не делает (вместо выделения слова)
2) Тройной клик в привате выделяет строку. Тройной клик в чате выделяет строку И копирует её в буфер. Надо унифицировать поведение.

**Comment by georgehazan** [comment]
тройной клик сделал, с двойным там сам черт не разберет, почему по-разному обработка происходит...
