### ISSUE TITLE
Jabber: всплывающие окна об ошибках Jabber зачем-то ждут, пока сообщение, которое не удалось отправить, стоит в очереди

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3212]
В нашей конфе запрещено писать в приват.

В XML-консоли при попытке написать в приват сразу выдаётся:

```
<error code="403" type="auth">
<forbidden xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" />
<text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">
It is not allowed to send private messages
</text>
```

При этом табсы порождают попап о неудачной доставке и помещают неотправленное сообщение в очередь. Так вот, пока эта очередь не протухла, не будет попапа от протокола про "403 It is not allowed to send private messages". Только если закрыть окно табсов и согласиться с уничтожением очереди неотправленных, вылезет попап от протокола.

Полагаю, он должен сразу вылезать, отлуп от сервера же сразу получен.

**Comment by dartraiden** [comment]
В StdMsg картина похожая, но чуток иная. Там нет очереди отправки, поэтому

1) при отправке мы получаем отказ от сервера
2) StdMsg выплевывает окно
![изображение](https://user-images.githubusercontent.com/5046855/194181899-da0fb413-a40a-4195-8981-4a7c34f29c74.png)

3) и только после того, как юзер закроет окно, вылезает попап от протокола

**Comment by georgehazan** [comment]
ну в логе ясно видно, что происходит:
- ты посылаешь сообщение в приват, прилетает ошибка, которая отправляется в открытое окно, попап при этом не выдается
- закрывается окно, жабер посылает на тот конец провода <message chatstate=gone/> в честь закрытия окна, при этом окна уже нет, поэтому прилетевшая новая ошибка с тем же кодом выплевывается в попап
