### ISSUE TITLE
Miranda crashed when I have closed the Chat-Window

### ISSUE THREAD

**Issue by MPerfurt** [miranda-ng/miranda-ng#3214]
Miranda Crash Report from 12 Oct 2022 15:32:03. Crash Dumper v.0.2.0.1

Likely cause of the crash plugin: TabSRMM

Exception: Access Violation at address 00000000130A18CD. Reading from address 0000000000000028.

Stack Trace:
---------------------------------------------------------------
00000000130A18CD (mir_core 00000000130A0000): (filename not available) (0): Ordinal510
00000000130A4D34 (mir_core 00000000130A0000): (filename not available) (0): Ordinal379
0000000018D5476F (TabSRMM 0000000018D20000): (filename not available) (0): (function-name not available)
0000000018D37E60 (TabSRMM 0000000018D20000): (filename not available) (0): (function-name not available)
0000000018D5235B (TabSRMM 0000000018D20000): (filename not available) (0): (function-name not available)
0000000018D47850 (TabSRMM 0000000018D20000): (filename not available) (0): (function-name not available)
00000000130BCD60 (mir_core 00000000130A0000): (filename not available) (0): Ordinal884
00007FFA3CF82920 (USER32 00007FFA3CF70000): (filename not available) (0): ScreenToClient
00007FFA3CF820C2 (USER32 00007FFA3CF70000): (filename not available) (0): ScreenToClient
00007FFA3CF81FD6 (USER32 00007FFA3CF70000): (filename not available) (0): ScreenToClient
00007FFA3CF7E858 (USER32 00007FFA3CF70000): (filename not available) (0): CallWindowProcW
00007FFA3CF7DE1B (USER32 00007FFA3CF70000): (filename not available) (0): SendMessageW
00007FFA3CF7D68A (USER32 00007FFA3CF70000): (filename not available) (0): SendMessageW
0000000018D34FDC (TabSRMM 0000000018D20000): (filename not available) (0): (function-name not available)
00007FFA3CF82920 (USER32 00007FFA3CF70000): (filename not available) (0): ScreenToClient
00007FFA3CF820C2 (USER32 00007FFA3CF70000): (filename not available) (0): ScreenToClient
00007FFA3CF81FD6 (USER32 00007FFA3CF70000): (filename not available) (0): ScreenToClient
00000000130C223F (mir_core 00000000130A0000): (filename not available) (0): mir_callNextSubclass
0000000018D3594A (TabSRMM 0000000018D20000): (filename not available) (0): (function-name not available)
00000000130C215C (mir_core 00000000130A0000): (filename not available) (0): mir_subclassWindowFull
00007FFA3CF7E858 (USER32 00007FFA3CF70000): (filename not available) (0): CallWindowProcW
00007FFA3CF7E3DC (USER32 00007FFA3CF70000): (filename not available) (0): DispatchMessageW
00007FFA3CF90C03 (USER32 00007FFA3CF70000): (filename not available) (0): SendMessageTimeoutW
00007FFA3EFB0EF4 (ntdll 00007FFA3EF10000): (filename not available) (0): KiUserCallbackDispatcher
00007FFA3CAE1064 (win32u 00007FFA3CAE0000): (filename not available) (0): NtUserPeekMessage
00007FFA3CF7A5C3 (USER32 00007FFA3CF70000): (filename not available) (0): PeekMessageW
00007FFA3CF7A523 (USER32 00007FFA3CF70000): (filename not available) (0): PeekMessageW
00000000130C09AC (mir_core 00000000130A0000): (filename not available) (0): Ordinal3
0000000012EFB53C (mir_app 0000000012EA0000): (filename not available) (0): mir_main
0000000140002904 (Miranda64 0000000140000000): (filename not available) (0): (function-name not available)
00000001400014BA (Miranda64 0000000140000000): (filename not available) (0): (function-name not available)
00007FFA3D847034 (KERNEL32 00007FFA3D830000): (filename not available) (0): BaseThreadInitThunk
00007FFA3EF626A1 (ntdll 00007FFA3EF10000): (filename not available) (0): RtlUserThreadStart

CPU: AMD Ryzen 5 3600 6-Core Processor  [AMD64 Family 23 Model 113 Stepping 0] [DEP Enabled] [12 CPUs]
Installed RAM: 8119 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 19043)
Internet Explorer: 9.11.19041.0 (build 919041)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : German/German | German/German

Miranda NG Version: 0.96.1 build #24549 (66a773fc3b) x64
Build time: 4 Oct 2022 20:36:02
Profile: C:\Users\User\AppData\Roaming\Miranda NG\xxx\xxx.dat
Database driver: SQLite database driver
Language pack: German (DE) [0407]
Service Mode: No

Active Plugins (16):
¤ AVS.dll v.0.98.1.6 [24 Sep 2022 12:34:12] - Avatar service 
¤ Clist_modern.dll v.0.9.1.12 [24 Sep 2022 12:35:26] - Modern contact list 
¤ CrashDumper.dll v.0.2.0.1 [4 Oct 2022 20:37:48] - Crash dumper 
¤ Db_autobackups.dll v.0.1.0.7 [4 Oct 2022 20:36:44] - Db autobackuper 
¤ DbChecker.dll v.0.95.13.3 [4 Oct 2022 20:39:54] - Database checker 
¤ Dbx_mdbx.dll v.0.95.9.1 [5 Jun 2022 20:15:46] - Miranda NG MDBX database driver 
¤ Dbx_sqlite.dll v.0.96.1.2 [4 Oct 2022 20:39:56] - Miranda NG SQLite database driver 
¤ Dummy.dll v.0.2.0.1 [4 Oct 2022 20:39:12] - Dummy protocol 
¤ Facebook.dll v.0.1.0.11 [24 Sep 2022 12:38:06] - Facebook 
¤ ICQ.dll v.0.96.2.2 [4 Oct 2022 20:39:58] - ICQ-WIM protocol 
¤ Import.dll v.0.95.11.1 [4 Oct 2022 20:36:26] - Import contacts and messages 
¤ Jabber.dll v.0.95.11.1 [4 Oct 2022 20:36:40] - Jabber protocol 
¤ NewEventNotify.dll v.0.2.2.5 [4 Oct 2022 20:37:28] - NewEventNotify 
¤ PluginUpdater.dll v.0.2.1.3 [24 Sep 2022 12:36:06] - Plugin updater 
¤ TabSRMM.dll v.3.6.2.6 [4 Oct 2022 20:36:20] - TabSRMM 
¤ TopToolBar.dll v.0.8.0.5 [5 Jun 2022 20:13:22] - TopToolBar 

Loaded Modules:
-------------------------------------------------------------------------------
C:\Program Files\Miranda NG\Miranda64.exe  0000000140000000 - 000000014000D000 v.0.96.1.0 [4 Oct 2022 20:36:02]
C:\Windows\SYSTEM32\ntdll.dll  00007FFA3EF10000 - 00007FFA3F108000 v.10.0.19041.2130 [12 Oct 2022 11:29:03]
C:\Windows\System32\KERNEL32.DLL  00007FFA3D830000 - 00007FFA3D8ED000 v.10.0.19041.1889 [10 Aug 2022 12:41:20]
C:\Windows\System32\KERNELBASE.dll  00007FFA3CC20000 - 00007FFA3CEF2000 v.10.0.19041.2130 [12 Oct 2022 11:29:04]
C:\Windows\System32\USER32.dll  00007FFA3CF70000 - 00007FFA3D10D000 v.10.0.19041.2130 [12 Oct 2022 11:29:00]
C:\Windows\System32\win32u.dll  00007FFA3CAE0000 - 00007FFA3CB02000 v.10.0.19041.2130 [12 Oct 2022 11:29:00]
C:\Windows\System32\GDI32.dll  00007FFA3D110000 - 00007FFA3D13B000 v.10.0.19041.2130 [12 Oct 2022 11:28:58]
C:\Windows\System32\gdi32full.dll  00007FFA3CB10000 - 00007FFA3CC1F000 v.10.0.19041.2130 [12 Oct 2022 11:29:06]
C:\Windows\System32\msvcp_win.dll  00007FFA3C6D0000 - 00007FFA3C76D000 v.10.0.19041.789 [22 Feb 2021 14:58:47]
C:\Windows\System32\ucrtbase.dll  00007FFA3C9B0000 - 00007FFA3CAB0000 v.10.0.19041.789 [22 Feb 2021 14:58:47]
C:\Windows\System32\SHELL32.dll  00007FFA3E780000 - 00007FFA3EEC3000 v.10.0.19041.2075 [12 Oct 2022 11:29:05]
C:\Windows\System32\IMM32.DLL  00007FFA3E100000 - 00007FFA3E130000 v.10.0.19041.546 [9 Oct 2020 22:47:56]
C:\Program Files\Miranda NG\libs\ucrtbase.dll  00007FFA195D0000 - 00007FFA196C5000 v.10.0.14393.795 [14 May 2021 12:55:58]
C:\Program Files\Miranda NG\libs\VCRUNTIME140.dll  00007FFA34500000 - 00007FFA34515000 v.14.16.27012.6 [14 May 2021 12:55:58]
C:\Program Files\Miranda NG\libs\mir_app.mir  0000000012EA0000 - 0000000012F99000 v.0.96.1.24549 [4 Oct 2022 20:35:58]
C:\Windows\System32\CRYPT32.dll  00007FFA3C850000 - 00007FFA3C9A6000 v.10.0.19041.1889 [10 Aug 2022 12:41:16]
C:\Windows\System32\SHLWAPI.dll  00007FFA3D480000 - 00007FFA3D4D5000 v.10.0.19041.2075 [12 Oct 2022 11:29:05]
C:\Windows\System32\msvcrt.dll  00007FFA3E6E0000 - 00007FFA3E77E000 v.7.0.19041.546 [9 Oct 2020 22:47:54]
C:\Windows\System32\WS2_32.dll  00007FFA3DA70000 - 00007FFA3DADB000 v.10.0.19041.546 [9 Oct 2020 22:47:55]
C:\Windows\SYSTEM32\WINMM.dll  00007FFA36290000 - 00007FFA362B7000 v.10.0.19041.546 [9 Oct 2020 22:47:18]
C:\Windows\System32\RPCRT4.dll  00007FFA3E150000 - 00007FFA3E275000 v.10.0.19041.1806 [15 Jul 2022 12:04:26]
C:\Windows\System32\COMDLG32.dll  00007FFA3D140000 - 00007FFA3D21A000 v.10.0.19041.1806 [15 Jul 2022 12:04:27]
C:\Windows\System32\combase.dll  00007FFA3E280000 - 00007FFA3E5D4000 v.10.0.19041.2130 [12 Oct 2022 11:29:02]
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e\COMCTL32.dll  00007FFA1CFC0000 - 00007FFA1D25A000 v.6.10.19041.1110 [9 Jul 2021 14:18:06]
C:\Windows\System32\shcore.dll  00007FFA3DFC0000 - 00007FFA3E06D000 v.10.0.19041.1865 [10 Aug 2022 12:41:14]
C:\Program Files\Miranda NG\libs\libssl-1_1.mir  0000000075D80000 - 0000000075E2C000 v.1.1.1.17 [5 Sep 2022 20:59:56]
C:\Windows\System32\ADVAPI32.dll  00007FFA3D9C0000 - 00007FFA3DA6E000 v.10.0.19041.2130 [12 Oct 2022 11:28:55]
C:\Windows\System32\sechost.dll  00007FFA3D610000 - 00007FFA3D6AC000 v.10.0.19041.1865 [10 Aug 2022 12:41:17]
C:\Program Files\Miranda NG\libs\libcrypto-1_1.mir  0000000075E30000 - 000000007617D000 v.1.1.1.17 [5 Sep 2022 20:59:06]
C:\Windows\System32\ole32.dll  00007FFA3D4E0000 - 00007FFA3D60A000 v.10.0.19041.1202 [9 Sep 2021 18:54:52]
C:\Windows\SYSTEM32\UxTheme.dll  00007FFA39BE0000 - 00007FFA39C7E000 v.10.0.19041.2130 [12 Oct 2022 11:29:07]
C:\Windows\System32\bcrypt.dll  00007FFA3CAB0000 - 00007FFA3CAD7000 v.10.0.19041.1023 [10 Jun 2021 19:17:24]
C:\Windows\SYSTEM32\VERSION.dll  00007FFA37670000 - 00007FFA3767A000 v.10.0.19041.546 [9 Oct 2020 22:48:03]
C:\Windows\SYSTEM32\Secur32.dll  00007FFA2FE70000 - 00007FFA2FE7C000 v.10.0.19041.546 [9 Oct 2020 22:48:01]
C:\Program Files\Miranda NG\libs\FreeImage.mir  0000000012000000 - 0000000012126000 [4 Oct 2022 20:35:42]
C:\Program Files\Miranda NG\libs\zlib.mir  0000000013300000 - 000000001331D000 v.1.2.12.0 [4 Oct 2022 20:35:08]
C:\Program Files\Miranda NG\libs\mir_core.mir  00000000130A0000 - 00000000130DD000 v.0.96.1.24549 [4 Oct 2022 20:35:10]
C:\Windows\SYSTEM32\WTSAPI32.dll  00007FFA369C0000 - 00007FFA369D4000 v.10.0.19041.546 [9 Oct 2020 22:47:23]
C:\Windows\SYSTEM32\SSPICLI.DLL  00007FFA3C4E0000 - 00007FFA3C512000 v.10.0.19041.2130 [12 Oct 2022 11:29:04]
C:\Program Files\Miranda NG\libs\MSVCP140.dll  00007FFA2B480000 - 00007FFA2B51B000 v.14.16.27012.6 [14 May 2021 12:55:58]
C:\Windows\System32\MSCTF.dll  00007FFA3D710000 - 00007FFA3D825000 v.10.0.19041.2075 [12 Oct 2022 11:29:05]
C:\Windows\System32\OLEAUT32.dll  00007FFA3D8F0000 - 00007FFA3D9BD000 v.10.0.19041.985 [14 May 2021 11:46:37]
C:\Windows\SYSTEM32\CRYPTBASE.DLL  00007FFA3BFF0000 - 00007FFA3BFFC000 v.10.0.19041.546 [9 Oct 2020 22:47:55]
C:\Windows\SYSTEM32\kernel.appcore.dll  00007FFA3AE90000 - 00007FFA3AEA2000 v.10.0.19041.546 [9 Oct 2020 22:47:41]
C:\Windows\System32\bcryptPrimitives.dll  00007FFA3C770000 - 00007FFA3C7F2000 v.10.0.19041.1415 [15 Dec 2021 12:16:26]
C:\Windows\SYSTEM32\textinputframework.dll  00007FFA18D00000 - 00007FFA18DF9000 v.10.0.19041.2075 [12 Oct 2022 11:28:58]
C:\Windows\System32\CoreUIComponents.dll  00007FFA394F0000 - 00007FFA3984E000 v.10.0.19041.546 [9 Oct 2020 22:47:37]
C:\Windows\System32\CoreMessaging.dll  00007FFA39850000 - 00007FFA39942000 v.10.0.19041.746 [19 Jan 2021 14:36:13]
C:\Windows\SYSTEM32\ntmarta.dll  00007FFA3B720000 - 00007FFA3B753000 v.10.0.19041.546 [9 Oct 2020 22:47:53]
C:\Windows\SYSTEM32\wintypes.dll  00007FFA38DD0000 - 00007FFA38F24000 v.10.0.19041.2130 [12 Oct 2022 11:29:02]
C:\Windows\SYSTEM32\dwmapi.dll  00007FFA39FB0000 - 00007FFA39FDF000 v.10.0.19041.746 [19 Jan 2021 14:36:12]
C:\Program Files\Miranda NG\Plugins\CrashDumper.dll  00000000167E0000 - 00000000167F3000 v.0.2.0.1 [4 Oct 2022 20:37:48]
C:\Windows\SYSTEM32\dbghelp.dll  00007FFA3A360000 - 00007FFA3A544000 v.10.0.19041.867 [22 Mar 2021 18:17:47]
C:\Windows\SYSTEM32\dbgcore.DLL  00007FFA32880000 - 00007FFA328AC000 v.10.0.19041.789 [22 Feb 2021 14:58:54]
C:\Program Files\Miranda NG\Plugins\DbChecker.dll  0000000016A20000 - 0000000016A2D000 v.0.95.13.3 [4 Oct 2022 20:39:54]
C:\Program Files\Miranda NG\Plugins\Dbx_mdbx.dll  0000000016AC0000 - 0000000016ACF000 v.0.95.9.1 [5 Jun 2022 20:15:46]
C:\Program Files\Miranda NG\libs\libmdbx.mir  0000000012B20000 - 0000000012B5C000 [5 Jun 2022 20:15:34]
C:\Program Files\Miranda NG\Plugins\Dbx_sqlite.dll  0000000016AE0000 - 0000000016AEF000 v.0.96.1.2 [4 Oct 2022 20:39:56]
C:\Program Files\Miranda NG\libs\sqlite3.mir  00000000131A0000 - 0000000013248000 [4 Oct 2022 20:36:10]
C:\Program Files\Miranda NG\Plugins\Import.dll  0000000017840000 - 000000001785B000 v.0.95.11.1 [4 Oct 2022 20:36:26]
C:\Program Files\Miranda NG\libs\Pcre16.mir  0000000013120000 - 000000001313D000 [4 Oct 2022 20:36:14]
C:\Program Files\Miranda NG\libs\libjson.mir  0000000012AE0000 - 0000000012AF6000 [4 Oct 2022 20:36:10]
C:\Program Files\Miranda NG\Core\stdcrypt.dll  0000000013080000 - 000000001308D000 v.0.96.1.24549 [4 Oct 2022 20:35:18]
C:\Windows\SYSTEM32\Msftedit.dll  00007FFA094E0000 - 00007FFA09828000 v.10.0.19041.1288 [14 Oct 2021 21:07:14]
C:\Program Files\Miranda NG\Plugins\Clist_modern.dll  00000000164A0000 - 000000001651F000 v.0.9.1.12 [24 Sep 2022 12:35:26]
C:\Windows\SYSTEM32\MSIMG32.dll  00007FFA1B0F0000 - 00007FFA1B0F7000 v.10.0.19041.1466 [12 Jan 2022 21:41:59]
C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.0.19041.2130_none_a250abbc3384207a\gdiplus.dll  00007FFA19420000 - 00007FFA195C5000 v.10.0.19041.2130 [4 Oct 2022 10:33:20]
C:\Windows\System32\clbcatq.dll  00007FFA3D220000 - 00007FFA3D2CF000 v.2001.12.10941.16384 [12 Oct 2022 11:29:02]
C:\Windows\system32\explorerframe.dll  00007FFA08020000 - 00007FFA08240000 v.10.0.19041.1949 [14 Sep 2022 8:55:49]
C:\Program Files\Miranda NG\Plugins\AVS.dll  0000000016280000 - 0000000016297000 v.0.98.1.6 [24 Sep 2022 12:34:12]
C:\Program Files\Miranda NG\Plugins\Db_autobackups.dll  0000000016B00000 - 0000000016B15000 v.0.1.0.7 [4 Oct 2022 20:36:44]
C:\Program Files\Miranda NG\Plugins\Dummy.dll  0000000016B40000 - 0000000016B4B000 v.0.2.0.1 [4 Oct 2022 20:39:12]
C:\Program Files\Miranda NG\Plugins\Facebook.dll  0000000016BC0000 - 0000000016BD6000 v.0.1.0.11 [24 Sep 2022 12:38:06]
C:\Program Files\Miranda NG\Plugins\ICQ.dll  0000000017720000 - 0000000017740000 v.0.96.2.2 [4 Oct 2022 20:39:58]
C:\Program Files\Miranda NG\Plugins\Jabber.dll  0000000017920000 - 00000000179D4000 v.0.95.11.1 [4 Oct 2022 20:36:40]
C:\Windows\SYSTEM32\DNSAPI.dll  00007FFA3BAD0000 - 00007FFA3BB9A000 v.10.0.19041.1865 [10 Aug 2022 12:41:16]
C:\Program Files\Miranda NG\libs\libsignal.mir  0000000012BA0000 - 0000000012BD0000 [4 Oct 2022 20:36:24]
C:\Windows\SYSTEM32\IPHLPAPI.DLL  00007FFA3BA80000 - 00007FFA3BABB000 v.10.0.19041.1865 [10 Aug 2022 12:41:16]
C:\Windows\System32\NSI.dll  00007FFA3E6D0000 - 00007FFA3E6D8000 v.10.0.19041.610 [19 Jan 2021 14:36:15]
C:\Program Files\Miranda NG\Plugins\NewEventNotify.dll  0000000018020000 - 000000001802E000 v.0.2.2.5 [4 Oct 2022 20:37:28]
C:\Program Files\Miranda NG\Plugins\PluginUpdater.dll  00000000184A0000 - 00000000184BA000 v.0.2.1.3 [24 Sep 2022 12:36:06]
C:\Program Files\Miranda NG\Plugins\TabSRMM.dll  0000000018D20000 - 0000000018DA4000 v.3.6.2.6 [4 Oct 2022 20:36:20]
C:\Windows\SYSTEM32\TextShaping.dll  00007FFA110C0000 - 00007FFA1116C000 [14 Oct 2021 21:07:14]
C:\Program Files\Miranda NG\Plugins\TopToolBar.dll  0000000018F80000 - 0000000018F91000 v.0.8.0.5 [5 Jun 2022 20:13:22]
C:\Program Files\Miranda NG\Core\stduserinfo.dll  0000000003940000 - 0000000003952000 v.0.96.1.24549 [4 Oct 2022 20:35:20]
C:\Program Files\Miranda NG\Core\stdemail.dll  0000000003960000 - 0000000003969000 v.0.96.1.24549 [4 Oct 2022 20:35:18]
C:\Program Files\Miranda NG\Core\stdfile.dll  0000000003970000 - 0000000003985000 v.0.96.1.24549 [4 Oct 2022 20:35:20]
C:\Program Files\Miranda NG\Core\stduihist.dll  0000000003990000 - 0000000003999000 v.0.96.1.24549 [4 Oct 2022 20:35:16]
C:\Program Files\Miranda NG\Core\stdautoaway.dll  0000000013000000 - 000000001300A000 v.0.96.1.24549 [4 Oct 2022 20:35:16]
C:\Program Files\Miranda NG\Core\stduseronline.dll  00000000039A0000 - 00000000039A9000 v.0.96.1.24549 [4 Oct 2022 20:35:16]
C:\Program Files\Miranda NG\Core\stdaway.dll  0000000013020000 - 000000001302C000 v.0.96.1.24549 [4 Oct 2022 20:35:18]
C:\Program Files\Miranda NG\Core\stdpopup.dll  0000000013160000 - 0000000013174000 v.0.96.1.24549 [4 Oct 2022 20:39:50]
C:\Windows\system32\dataexchange.dll  00007FFA08240000 - 00007FFA0827E000 v.10.0.19041.1387 [15 Dec 2021 12:16:16]
C:\Windows\system32\d3d11.dll  00007FFA38100000 - 00007FFA38363000 v.10.0.19041.2075 [12 Oct 2022 11:28:57]
C:\Windows\system32\dcomp.dll  00007FFA38F30000 - 00007FFA39113000 v.10.0.19041.2075 [12 Oct 2022 11:29:02]
C:\Windows\system32\dxgi.dll  00007FFA3AEE0000 - 00007FFA3AFD3000 v.10.0.19041.2075 [12 Oct 2022 11:28:58]
C:\Windows\system32\twinapi.appcore.dll  00007FFA36F70000 - 00007FFA37170000 v.10.0.19041.1865 [10 Aug 2022 12:41:11]
C:\Windows\SYSTEM32\WindowsCodecs.dll  00007FFA19000000 - 00007FFA191B4000 v.10.0.19041.1706 [12 May 2022 11:52:01]
C:\Windows\SYSTEM32\windows.storage.dll  00007FFA3A6E0000 - 00007FFA3AE71000 v.10.0.19041.2130 [12 Oct 2022 11:28:59]
C:\Windows\SYSTEM32\Wldp.dll  00007FFA3C080000 - 00007FFA3C0B0000 v.10.0.19041.2075 [12 Oct 2022 11:29:02]
C:\Windows\system32\mswsock.dll  00007FFA3BDE0000 - 00007FFA3BE4A000 v.10.0.19041.546 [9 Oct 2020 22:47:52]
C:\Windows\system32\napinsp.dll  00007FFA1AF30000 - 00007FFA1AF47000 v.10.0.19041.546 [9 Oct 2020 22:47:47]
C:\Windows\system32\pnrpnsp.dll  00007FFA1AF10000 - 00007FFA1AF2B000 v.10.0.19041.546 [9 Oct 2020 22:48:31]
C:\Windows\system32\wshbth.dll  00007FFA378E0000 - 00007FFA378F5000 v.10.0.19041.546 [9 Oct 2020 22:47:43]
C:\Windows\system32\NLAapi.dll  00007FFA354C0000 - 00007FFA354DD000 v.10.0.19041.1151 [10 Aug 2021 23:59:45]
C:\Windows\System32\winrnr.dll  00007FFA1AD40000 - 00007FFA1AD52000 v.10.0.19041.546 [9 Oct 2020 22:47:57]
C:\Windows\System32\fwpuclnt.dll  00007FFA2FE80000 - 00007FFA2FF00000 v.10.0.19041.2006 [14 Sep 2022 8:55:45]
C:\Windows\System32\rasadhlp.dll  00007FFA2FE60000 - 00007FFA2FE6A000 v.10.0.19041.546 [9 Oct 2020 22:48:03]
C:\Windows\System32\Windows.Globalization.dll  00007FFA16400000 - 00007FFA165A6000 v.10.0.19041.1865 [10 Aug 2022 12:41:11]
C:\Windows\System32\Bcp47Langs.dll  00007FFA192C0000 - 00007FFA1931B000 v.10.0.19041.1566 [9 Mar 2022 1:04:57]
C:\Windows\System32\bcp47mrm.dll  00007FFA18940000 - 00007FFA1896D000 v.10.0.19041.1503 [11 Feb 2022 12:48:54]
C:\Windows\SYSTEM32\globinputhost.dll  00007FFA0D030000 - 00007FFA0D055000 v.10.0.19041.1806 [15 Jul 2022 12:04:15]
C:\Windows\System32\coml2.dll  00007FFA3E650000 - 00007FFA3E6C9000 v.10.0.19041.546 [9 Oct 2020 22:47:43]
C:\Windows\SYSTEM32\PROPSYS.dll  00007FFA37DA0000 - 00007FFA37E96000 v.7.0.19041.1741 [15 Jun 2022 1:48:33]
C:\Windows\System32\Windows.UI.dll  00007FFA18E20000 - 00007FFA18F61000 v.10.0.19041.746 [19 Jan 2021 14:36:09]
C:\Windows\System32\InputHost.dll  00007FFA18A70000 - 00007FFA18BC2000 v.10.0.19041.1741 [15 Jun 2022 1:48:33]
C:\Windows\System32\WindowManagementAPI.dll  00007FFA191C0000 - 00007FFA19261000 [10 Jun 2021 19:17:18]
C:\Windows\SYSTEM32\edputil.dll  00007FFA07F80000 - 00007FFA07FA4000 v.10.0.19041.546 [9 Oct 2020 22:47:58]

**Comment by dartraiden** [comment]
https://wiki.miranda-ng.org/index.php?title=Crash_reports
