### ISSUE TITLE
WhenWasIt: дни рождения контактов из отключённых учётных записей показываются как дни рождения "Неизвестного контакта"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3216]
Если у контакта отключенного протокола дата рождения прописана в модуле UserInfo, то он показывается в списке дней рождений как "Неизвестный контакт" даже при снятой галке "Показать все контакты". Это надо испрвить - контакты, принадлежащие отключенному протоколу, не должны показыватьcя при снятой галке "Показать все контакты".

![изображение](https://user-images.githubusercontent.com/5046855/220979569-752dbd8f-0b37-47e1-9355-49618be52aac.png)

Что интересно, если у контакта дата рождения прописана в модуле протокола, баг не воспроизводится. Именно дата в модуле UserInfo триггерит баг.

**Comment by dartraiden** [comment]
Не исправилось.

**Comment by dartraiden** [comment]
Исправилось, но я считаю, что мы НЕ должны показывать контакты отключённых протоколов, если не взведена галка "Показать все контакты".

**Comment by georgehazan** [comment]
А зачем вообще показывать все контакты? Даже там, где никаких дней рождения нету

**Comment by dartraiden** [comment]
Я не знаю зачем, но там в окошке есть такая галка.
