### ISSUE TITLE
PluginUpdater

### ISSUE THREAD

**Issue by FirstPacificator** [miranda-ng/miranda-ng#3231]
1. Когда-то давно вроде работало всё нормально при переезде с 32 бит на 64 и обратно. Т.е. после обновления ненужный экзешник удалялся автоматом, а миранда запускалась с нужного экзешника, а теперь и экзешник не удаляется и миранда пытается запуститься с уже ненужного экзешника, ну и естественно выскакивает ошибка с рантаймами.

2. https://i.imgur.com/Xibjet9.png
Если поставить галку (перейти на x-разрядную версию), то каждый раз при проверке обновлений находится обновление и обновляется с 64 на 32 и обратно, бесконечно.
Т.е. если поставить эту галку, то она остаётся всегда включенной.
По идее эта галка должна автоматом слетать при условии, если запустился реальный процесс обновления.

**Comment by dartraiden** [comment]
ОС какая?

**Comment by FirstPacificator** [comment]
Сейчас протестировал на 10-ке - проблем нет.
А на 7-ке обе проблемы существуют.

**Comment by dartraiden** [comment]
У меня всё ок на 7, видимо, какая-то локальная проблема.
