### ISSUE TITLE
NewAwaySys

### ISSUE THREAD

**Issue by FirstPacificator** [miranda-ng/miranda-ng#3246]
[скриншот](https://i.imgur.com/F7uauEW.png)

Удаляю статусное сообщение, перезагружаю миранду, а сообщение снова там.
Меняю сообщение на ?translate(``), перезагружаю миранду, а там снова: Yep, I'm here.
Дефолтное значение почему-то имеет жёсткую привязку.

**Comment by dartraiden** [comment]
Это какая-то особенность/проблема сборки HotCoffee, поэтому вопросы к её автору.
В чистой Миранде проблемы нет.
