### ISSUE TITLE
WhatsApp: при каждом выходе в онлайн чат мигает непрочитанным сообщением

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3249]
- групчат, все сообщения прочитаны
- уводим вацап в оффлайн и обратно в онлайн
- чат моргает непрочитанным сообщением, словно меня хайлайтнули

**Comment by georgehazan** [comment]
видимо, что-то поменялось (но что, я не знаю). теперь не мигает
