### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by FirstPacificator** [miranda-ng/miranda-ng#3253]
По умолчанию в настройках (в диалоге учётных записей) установлена одноимённая группа протокола для контактов, но контакты Twitter не попадают в эту группу, а остаются в корне.

**Comment by dartraiden** [comment]
Возможно, регрессия в результате https://github.com/miranda-ng/miranda-ng/commit/7d053a2f4a6c6b8ba7400fce490bab6418672191

**Comment by georgehazan** [comment]
@FirstPacificator не подтверждаю.
стер контакты из твиттера в сервисном режиме (чтобы они не стерлись с сервера), запустил Миранду - все контакты как миленькие отправились в группу Twitter.

Миранда не отправляет контакты в группу только в одном случае - если там уже проставлена какая-то другая группа (настройка CList/Group)
