### ISSUE TITLE
YAMN: не работает указание интервала проверки почты

### ISSUE THREAD

**Issue by FirstPacificator** [miranda-ng/miranda-ng#3256]
В настройках есть возможность указать интервал проверки почты (в минутах).
Какой бы интервал не указывал, проверка почты по этой настройке не работает.
А вот проверка из главного меню и из меню контакта работает отлично.
Но интервал это всё-таки важная настройка. Хотелось бы рабочую автоматическую проверку почты.

**Comment by georgehazan** [comment]
@FirstPacificator там все нормально с этим, просто есть довольно дебильная настройка check when и там надо выбрать статусы для проверки. Если статусы выбраны, то проверка стартует

**Comment by dartraiden** [comment]
Надо сделать их взведёнными по умолчанию.

**Comment by georgehazan** [comment]
готово
