### ISSUE TITLE
TabSRMM: не работает кнопка "Leave chat"

### ISSUE THREAD

**Issue by FirstPacificator** [miranda-ng/miranda-ng#3257]
В панели кнопок табса есть кнопка "Leave chat", и именно в этой панели кнопка "Leave chat" не работает, а вот из меню контакта "Leave chat" работает отлично.

**Comment by dartraiden** [comment]
Не вижу такой кнопки в "ванильной "Миранде.

Есть только Close session.

**Comment by FirstPacificator** [comment]
Саня, ты прав. Это луа-скрпит. Я прошу прощения. Закрываю тикет.
