### ISSUE TITLE
Accessibility: Can't determine states of checkboxes with a screen reader in the trees of Jabber options

### ISSUE THREAD

**Issue by marvellousmachine** [miranda-ng/miranda-ng#3268]
### Expected behavior
Approaching an option with up / down arrow should announce its name along with its state, pressing spacebar on a checkbox should announce change of its state (checked / unchecked).

### Actual behavior
Only option name is announced, no way to retrieve its state using a screen reader.

### Does it work in stable version?
No.

### Steps to reproduce that behavior
 * Open Options > Jabber > Advanced tab.
 * Navigate to the tree containing Miscellaneous options.
 * Browse through the items using up / down arrows with a screen reader. Note that only option name gets announced.
 * Additionally, press spacebar to check / uncheck any of the options, note that nothing gets announced, windows ding sound is played.
 * The same in the tree of Conferences tab.
 * For inspiration, the correct behavior can be observed e.g. in Scriver options Group chats > General > Options tree.

Tested with: NVDA 2022.4beta3, Miranda NG 0.96.2 alpha build #25093

**Comment by georgehazan** [comment]
@marvellousmachine,

Miranda draws custom checkbox icons in some trees, that's why your screen reader doesn't recognize them.
Perhaps it's time to remove all that trash, because it was created for Windows'95 & '98, since XP Windows could draw trees themselves.
