### ISSUE TITLE
Exception: Access Violation at address 00000000130A18CD. Reading from address 0000000000000028.

### ISSUE THREAD

**Issue by MPerfurt** [miranda-ng/miranda-ng#3270]
The crash was running when i have closed a message-window with 3 tabs.
The logs are at the attachment.
[CrashLog-2022.12.19.zip](https://github.com/miranda-ng/miranda-ng/files/10260917/CrashLog-2022.12.19.zip)

**Comment by dartraiden** [comment]
Same crashlog as https://github.com/miranda-ng/miranda-ng/issues/2948#issuecomment-1344151502

So we do not really fixed it...

**Comment by georgehazan** [comment]
@MPerfurt what do you have in Container Options - Title bar format ? I mean the format string contents. Also, this error happens, evidently, on some specific contact - is that protocol disabled?

**Comment by georgehazan** [comment]
@MPerfurt I've invented some crutch to fix this problem finally... hope it helps
stable build will be available soon for update
