### ISSUE TITLE
Clist_modern: добавить настройку отступа для подгрупп

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3274]
Есть настройка отступа для групп. Пользователь просит настройку для подгрупп.

<img width="503" alt="Miranda64_Y88UNuRfM7" src="https://user-images.githubusercontent.com/5046855/209221317-1e72fe3a-4a42-4375-b2d9-a18310f26621.png">

**Comment by dartraiden** [comment]
Уточнение: сейчас подгруппы жёстко имеют x2 от этой настройки. То есть, если отступ для групп указан 10 пикселей, то подгруппа корневой группы имеет 20 пикселей отступа.

**Comment by dartraiden** [comment]
![Безымянный](https://user-images.githubusercontent.com/5046855/209285612-613a9764-97cb-4d7a-8cc9-a0e9c225a494.png)

**Comment by georgehazan** [comment]
предлагаю просто сделать везде одинаковый отступ
