### ISSUE TITLE
NewEventNotify: get rid of inverted logic

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3275]
<img width="427" alt="mstsc_OXs6I0qDor" src="https://user-images.githubusercontent.com/5046855/209285682-14e22c3f-e029-4bdf-97f0-0bde4e2612d2.png">

**Comment by georgehazan** [comment]
для деревьев настроек не получается просто так заменить логику на обратную, только если вынести их наружу
