### ISSUE TITLE
NewEventNotify: настройка цветов всплывающих окон

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3280]
<img width="503" alt="Miranda64_pi21zSMfOU" src="https://user-images.githubusercontent.com/5046855/209441832-62666f7f-d786-42a2-96ff-a445e747456f.png">

Галки возле настроек цветов означают "использовать цвета по умолчанию" (не кастомные цвета, а цвета из настроек плагина всплывающих окон). При включении этих галок выбор цвета блокируется. Проблема в том, что чекбоксы никак не подписаны, да и места для этого мало.

Может быть, вынести настройки цветов и длительность в отдельную вкладку? Там уже есть вкладки "Основные настройки" и "Сообщения".

**Comment by georgehazan** [comment]
> Может быть, вынести настройки цветов и длительность в отдельную вкладку? Там уже есть вкладки "Основные настройки" и "Сообщения".

Вынести недолго, но места по ширине это явно не прибавит...
