### ISSUE TITLE
Telegram: отсутствует индикация того, что пароль 2FA введёт неверно

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3284]
Если пользователь неверно ввёл пароль 2FA, нужно ему об этом сообщить и снова запросить пароль.

Сейчас же, если в пароле ошибка, окно ввода пароля пропадёт и больше не появится, даже после переподключения

**Comment by georgehazan** [comment]
если пнуть регистрацию по новой, оно запросится, я починиль
