### ISSUE TITLE
Telegram: автозавершение сессии при удалении учётки

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3288]
Предлагаю сделать, как с WhatsApp: удаляется учётка из Миранды - сессию убиваем.

**Comment by dartraiden** [comment]
Перестало работать.

Учётка в онлайне. Я её удаляю из Миранды. Даже перезапускаю Миранду для верности. Смотрю в оф.клиенте - сессия не убита.

**Comment by georgehazan** [comment]
duplicate of #3417
