### ISSUE TITLE
Telegram: When adding an account, own user details are added as a "contact" instead of being stored into protocol settings

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#3289]
### Expected behavior
When adding Telegram account, I can send and receive messages and see my own username (and opposing side's username) when chatting.

### Actual behavior
Both sides show the target's username when chatting.

EDIT: seems the below is a feature.
~~Moreover the username of my account was also created as a "contact" which I think is a mistake.~~

### Does it work in stable version?
No

### Steps to reproduce that behavior
 * Fresh miranda
 * Add telegram acc
 * Have some contacts
 * Try sending one a message
 * it shows their username

By reading the code I was able to currently set up a workaround by adding the STRING "id" with my own account's ID + the UNICODE "Nick" with a nick in DBEditor in Settings->"Telegram proto name"->id (and Nick).

When linking with a telegram account, these values should be loaded into the above DB place

**Comment by dartraiden** [comment]
`Moreover the username of my account was also created as a "contact" which I think is a mistake.`

Not a bug: you can send messages to yourself. It is "Saved messages" in official TG client.

**Comment by LittleVulpix** [comment]
I see. Fair enough... still, the original issue stands.
