### ISSUE TITLE
Twitter: перестали прогружаться аватарки

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3291]

**Comment by georgehazan** [comment]
а почему они в России должны работать? оно же блокировано

**Comment by dartraiden** [comment]
через VPN, конечно же

**Comment by georgehazan** [comment]
А протокол никто и не блочил, только сам веб-сайт. Т.е. нельзя скачивать картинки, видосики и скрипты, а сам апи работает на ура.
