### ISSUE TITLE
SmileyAdd: глюк в подсказке к смайлу

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3295]
- устанавливаем этот набор: https://miranda-ng.org/distr/addons/Smileys/WhatsApp/whatsapp.zip
- нажимаем "Тест" в настройках плагина или же вызываем список смайлов из плагина сообщений

при наведении на смайл появляется не только описание смайла, но и какая-то точка

![211148973-3e07053b-cf5a-4808-87cc-700b9e52a4aa](https://user-images.githubusercontent.com/5046855/211149041-52aeaf3c-3a21-4a15-9852-824f9cf0c0e7.png)

**Comment by georgehazan** [comment]
так написан файл MSL, что там перед полной версией смайла торчит какая-то хрень
можно взять любой шрифт, где есть emoji
