### ISSUE TITLE
WhatsApp: при заведении учётки в Миранду некоторые контакты прилетают без имён

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3304]
- завожу учётку в Миранду
- некоторые контакты прилетают без имён, с номерами
- перезапуск не помогает, остаются с номерами

помогает пересоздание кэша

**Comment by georgehazan** [comment]
нужен лог, как и раньше, с указанием контактов. которые прилетели без имени

**Comment by dartraiden** [comment]
Некоторые контакты, вдобавок, прилетают с именами, которые установлены ими самими (в их профиле), а не с именами из моей адресной книги.

Есть лог с теми и другими, сюда аттачить опасаюсь.

**Comment by georgehazan** [comment]
> Есть лог с теми и другими, сюда аттачить опасаюсь.

ты знаешь мое мыло и телегу

**Comment by georgehazan** [comment]
приехал лог, ничего странного в нем не нашлось
