### ISSUE TITLE
Telegram: отсутствующие контакты имеют значок Миранды

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3306]
Я добавил значки для Away и Occupied согласно https://github.com/miranda-ng/miranda-ng/blob/master/protocols/Telegram/proto_telegram/src/resource.h#L7 (128 и 159).

Но у отсутствующих контактов по-прежнему значок Away в виде значка Миранды.

**Comment by georgehazan** [comment]
проще всего зайти в настройки значков в учетки и посмотреть коды - там все видно прямо
