### ISSUE TITLE
Telegram: контакты часто залипают в статусе Away

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3307]
Пример: человек был полчаса назад (согласно официальному клиенту), а в Миранде он висит Away. Если перезапустить Миранду, человек Offline.

**Comment by georgehazan** [comment]
там сейчас схема 10 минут online -> n/a, еще 10 минут - na -> offline

**Comment by dartraiden** [comment]
Вообще странная логика, Away должен идти первым, потом NA.

**Comment by dartraiden** [comment]
<img width="153" alt="JVR9QsArko" src="https://user-images.githubusercontent.com/5046855/212539986-e834c5b4-2260-4ccd-940f-152539f31bb1.png">

**Comment by dartraiden** [comment]
В аське, например, именно так: сначала контакт выкидывается в Away, потом в NA, потом в Offline

<img width="503" alt="Miranda64_9Rae26fqDE" src="https://user-images.githubusercontent.com/5046855/212540038-7ccfbf17-1438-465e-9b7e-2c55ec0c71e2.png">
