### ISSUE TITLE
Gadu-gadu protocol

### ISSUE THREAD

**Issue by Sagittarius68** [miranda-ng/miranda-ng#3310]
Hi
The gadu gadu protocol in miranda has not been working for several days

**Comment by dartraiden** [comment]
Fixed in build 25207

**Comment by Sagittarius68** [comment]
There is no gadu gadu protocol in this installation

**Comment by dartraiden** [comment]
![Безымянный2](https://user-images.githubusercontent.com/5046855/214795430-3e6231b4-d150-4c28-894e-ac8462b5c78f.png)

**Comment by Sagittarius68** [comment]
OK. I did that but it doesn't boot

**Comment by Sagittarius68** [comment]
no log in
