### ISSUE TITLE
Резкое увеличение размеры базы данных в версии 0.96.1 #24559

### ISSUE THREAD

**Issue by C1eriC** [miranda-ng/miranda-ng#3322]
В результате перехода со стабильной версии 0.96.1 #**24556** на 0.96.1 #**24559** ([коммит](https://github.com/miranda-ng/miranda-ng/commit/e5ade49900709039872a6403352447ac7f524f2f)) база данных (.dat) резко увеличивает свой размер. В моём случае с 73,3 Мб до 84,5 Мб (более 15%). Database - Compact сжимает только до 79,5 Мб. База зашифрована (Total).

Это происходит сразу же после запуска Miranda 0.96.1 #**24559**, до ввода пароля, до расшифровки базы, до получения сообщений. Версия 0.96.1 #**24556** размер базы не увеличивает, он остаётся прежним.

Check database ([[1]](https://hsto.org/webt/dk/cx/dp/dkcxdp1sj7h0uytyzzytp0xrm4e.png), [[2]](https://hsto.org/webt/60/fb/f8/60fbf8ewwd3p20vsasnbvsktysy.png)) со всеми галочками, по какой-то причине, ещё увеличивает размер базы. 79,5 → 87 Мб (далее, Compact сжимает её только до 85).

Что именно версия 0.96.1 #24559 может такое делать с базой?
Можно ли каким-либо образом удалить из базы лишнее (не удаляя историю переписки), уменьшив её размер?

<details>
  <summary>VersionInfo</summary>
CPU: AMD Ryzen 9 5900X 12-Core Processor  [AMD64 Family 25 Model 33 Stepping 0] [DEP Enabled] [24 CPUs]
Installed RAM: 32683 MBytes
Microsoft Windows 10 Home Single Language, 64-bit (build 19045)
Internet Explorer: 9.11.19041.0 (build 919041)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian
Free disk space on Miranda partition: 925100 MBytes

Miranda NG Version: 0.96.1 build #24559 (55950a018d) [running inside WOW64]
Build time: 9 Jan 2023 17:10:10
Profile: C:\YandexDisk\Flash\Prog\Miranda NG\Profiles\Mcl\Mcl.dat
Database driver: SQLite database driver
Profile size: 83587072 Bytes
Profile creation date: 17 Jan 2023 16:54:35
Language pack: No language pack installed
Service Mode: No

Active Plugins (17):
¤ AVS.dll v.0.98.1.6 [9 Jan 2023 17:10:14] - Avatar service 
¤ CrashDumper.dll v.0.2.0.1 [9 Jan 2023 17:11:30] - Crash dumper 
¤ Db_autobackups.dll v.0.1.0.7 [9 Jan 2023 17:10:40] - Db autobackuper 
¤ DbChecker.dll v.0.95.13.3 [9 Jan 2023 17:13:16] - Database checker 
¤ Dbx_mdbx.dll v.0.95.9.1 [9 Jan 2023 17:13:16] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.0.95.8.1 [9 Jan 2023 17:10:14] - Miranda NG mmap database driver 
¤ Dbx_sqlite.dll v.0.96.2.1 [9 Jan 2023 17:13:12] - Miranda NG SQLite database driver 
¤ Dummy.dll v.0.2.0.1 [9 Jan 2023 17:12:42] - Dummy protocol 
¤ historypp.dll v.1.5.1.5 [9 Jan 2023 17:13:34] - History++ 
¤ ICQ.dll v.0.96.2.3 [9 Jan 2023 17:13:16] - ICQ-WIM protocol 
¤ MessageState.dll v.0.1.0.2 [9 Jan 2023 17:12:52] - Message state 
¤ NotesReminders.dll v.0.2.2.2 [9 Jan 2023 17:13:14] - Sticky Notes & Reminders 
¤ PluginUpdater.dll v.0.2.1.4 [9 Jan 2023 17:11:42] - Plugin updater 
¤ Scriver.dll v.3.0.2.4 [9 Jan 2023 17:10:14] - Scriver 
¤ SkypeWeb.dll v.0.95.13.3 [9 Jan 2023 17:12:52] - Skype protocol (Web) 
¤ SmileyAdd.dll v.0.3.2.2 [9 Jan 2023 17:10:52] - SmileyAdd 
¤ StatusManager.dll v.1.2.0.6 [9 Jan 2023 17:13:10] - Status manager 

Protocols and Accounts:
-------------------------------------------------------------------------------
Dummy                    1 - Enabled 0 - Disabled  Loaded
ICQ                      1 - Enabled 0 - Disabled  Loaded
MRA                      1 - Enabled 0 - Disabled  Loaded
SKYPE                    1 - Enabled 0 - Disabled  Loaded
WhatsApp                 1 - Enabled 0 - Disabled  Loaded

Icon Packs:
-------------------------------------------------------------------------------
 HistoryPP_icons.dll [9 Jan 2023 17:13:24]
 Proto_Dummy.dll [9 Jan 2023 17:13:26]
 Proto_ICQ.dll [9 Jan 2023 17:13:26]
 Proto_MetaContacts.dll [9 Jan 2023 17:13:26]
 Proto_MRA.dll [9 Jan 2023 17:13:26]
 Proto_Skype.dll [9 Jan 2023 17:13:26]
 Proto_WhatsApp.dll [21 Apr 2015 23:55:34]  
</details>

**Comment by georgehazan** [comment]
добавился ключ в таблицу событий
