### ISSUE TITLE
Telegram: нужен способ оградить пользователей от ошибок при вводе номера телефона

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3324]
Сейчас номер телефона нужно вводить строго в формате <код страны><номер телефона>. Если ввести без кода страны, то логиниться не будет. Если перед кодом страны ввести "+", то исходящие сообщения будут отображаться как входящий от собеседника. Очень легко ошибиться.

Что нужно сделать: выкусывать плюс перед записью в базу. Когда пользователь заполняет данные и жмёт ОК. Это не поможет в борьбе с теми, кто пишет туда номер без кода страны вообще. Но сделать это всё равно стоит, хоть какая-то защита от ошибки.

Дальше идут разные варианты окончательного решения вопроса;
- тупо заменить текст перед полем. Сейчас там "Phone number:", а сделать "Phone number: +". Это одновременно намекает пользователю, что плюс вводить не нужно, а также то, что ожидается код страны
- разбить номер на два поля. Первое поле короткое на 4 (или сколько там максимум длина кантри-кода) символа, и чтобы там уже по дефолту стоял +
- сделать перед полем для номера дропдаун с кодами стран (+1, +7 и так далее для всех стран). Неясно, как этот список актуализировать, если вдруг у какой-то страны сменится код. Втаскивать какую-то либу для этого не хочется.

В официальном клиенте сделано всё это разом:

<img width="263" alt="Telegram_5P11TOCzfw" src="https://user-images.githubusercontent.com/5046855/216178777-cb9c05bd-f1a4-4dd8-867c-154e7ccd9afc.png">

как видим, есть и выпадающий список, из которого можно выбрать страну, чтобы кантри-код подставился сам, а также номер разбит на два поля: первое для кода (и там по дефолту уже стоит плюсик), а второе для номера.

<img width="260" alt="Telegram_Yo7XzTi3A4" src="https://user-images.githubusercontent.com/5046855/216178978-3644be08-7e17-4807-8432-0abf807c5a93.png">

**Comment by dartraiden** [comment]
Это практически не помогает юзеру не совершить ошибку

Юзер по-прежнему может ввести туда
+79000123456
89000123456
9000123456

**Comment by dartraiden** [comment]
Нужно сделать так:
1) чтобы после страны писался её код (+XX)
2) чтобы этот код автоматом прибавлялся к введенному номеру
3) чтобы страна не сбрасывалась при переоткрытии настроек

**Comment by georgehazan** [comment]
готово
