### ISSUE TITLE
удаление/редактирование уже отправленных сообщений

### ISSUE THREAD

**Issue by jazzl0ver** [miranda-ng/miranda-ng#3327]
Добрый день. Возможно ли реализовать сабж? Хотя бы для приватных сообщений

**Comment by georgehazan** [comment]
Да, например, NewStory это умеет

**Comment by dartraiden** [comment]
Нужно учитывать, что это затронет только вашу локальную базу. У собеседника ничего удалено/отредактировано не будет.

**Comment by jazzl0ver** [comment]
> Нужно учитывать, что это затронет только вашу локальную базу.
имхо тогда в этом нет никакого практического смысла

> для этого нужно реализовывать поддержку в соответствующем протоколе
в джаббере этой возможности нет?

**Comment by jazzl0ver** [comment]
> Да, например, NewStory это умеет

где можно почитать про возможности newstory? он умеет передавать картинки инлайн, например?

**Comment by georgehazan** [comment]
> он умеет передавать/показывать картинки инлайн, например?

инлайнить картинки, переданные через HTTP Upload в жабере, умеет емнип только ieview в режиме использования bbcodes, для этого они же должны быть включены в Jabber

**Comment by dartraiden** [comment]
> в джаббере этой возможности нет?

Этой возможности нет ни в каком протоколе по причине того, что до NewStory никакой журнал этого и не умел.

**Comment by jazzl0ver** [comment]
всем спасибо за ответы. жаль, что перспективы туманны.
