### ISSUE TITLE
WhatsApp nickname not Unicode

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#333]
**Reported by Chungalin on 6 Oct 2014 14:23 UTC**
In WhatsApp protocol plugin, nickname is not encoded in Unicode, so any attempt to include non ANSI characters ends up with a question mark. Its a fact that WhatsApp protocol supports Unicode in nickname, as many users using official app put even emojis in their nicks.

**Comment by georgehazan** [comment]
**Modified by watcher on 17 Dec 2014 23:26 UTC**

**Comment by georgehazan** [comment]
**Comment by wishmaster on 5 Feb 2015 21:34 UTC**
Is it still a problem?

**Comment by dartraiden** [comment]
WhatsApp is deprecated.
