### ISSUE TITLE
GStreamer libraries

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3336]
Нужно что-то решать с библиотеками GStreamer (необходимы для VOIP в Jabber). Сейчас с ними есть проблемы:

1) мы втащили в репу /include/gst, но непонятно, как их обновлять и есть ли там какие-то изменения относительно ванильных инклюдов (если они есть, их надо хотя бы задокументировать, иначе потом будет геморрой с обновлением)

2) сами библиотеки нужно качать на внешних сайтах и подкладывать. В идеале мы сами должны их поставлять вместе с VoiceService.

Это не срочная задача, т.к. пока VOIP умеет только Jabber (и то сильно экспериментально), но в будущем, вероятно, мы захотим это прикрутить к WhatsApp и Telegram, поэтому я делаю тикет, чтобы не забыть.

**Comment by georgehazan** [comment]
А сам звонок-то работает? Если да, то это надо, наверное, просто упаковать отдельно как-то... Включать их в VoiceService считаю неправильным, потому что этот плагин вообще не в курсе о реальной природе звонков, и для своего функционирования в этих библиотеках не нуждается. Возможно, надо сделать отдельный маленький плагинчик второго уровня для Jabber, который бы вместо опции автоматом бы включал нужные capabilities, и вот к нему уже упаковать эти библиотеки

**Comment by dartraiden** [comment]
А, может, плагин Jingle  потом сгодится для аудиозвонков в вацапе или телеге? И стоит как-то его более обще назвать.

И, может, нам VoiceService паковать вместе с этим Jingle, а не с Jabber? Зачем нужен VoiceService в Jabber при отсутствующем Jingle?
