### ISSUE TITLE
auto download files from whatsappserver

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#334]
**Reported by esim on 6 Oct 2014 15:36 UTC**
when somebody send a file, we get a link from a subdomain of whatsapp.net
how i know its every time ​`https://mm*.whatsapp.net/d/*.*`

and it would good if we set automatic get files from user of my contactlist that there files will too downloaded or see it how normally send files from contact

[VersionInfo.txt](https://github.com/miranda-ng/miranda-ng/files/646884/VersionInfo.txt)

**Comment by georgehazan** [comment]
**Modified by esim on 6 Oct 2014 15:37 UTC**

**Comment by dartraiden** [comment]
WhatsApp is deprecated.
