### ISSUE TITLE
ICQ: залипает статус собеседника

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3341]
```
[22.02.2023 22:02]
там где-то в ядре отломался таймаут

[22.02.2023 22:02]
поэтому висящий http-запрос не отваливается через 30 секунд, как положено

[22.02.2023 22:02]
и в Steam та же самая проблема
```

Проблема такая: когдл собеседник (ICQ) выключает Миранду, он продолжает у меня в клисте быть зелененьким.

<img width="106" alt="Telegram_F1IxQyH0WB" src="https://user-images.githubusercontent.com/5046855/220732739-234d9114-60eb-4718-b1be-0d3dfa780136.png">

И так он будет висеть хоть 10 часов кряду, пока я не переподключусь со своей стороны.

**Comment by georgehazan** [comment]
Залипает сессия, когда миранда падает и не подает на сервер команду об окончании сессии
