### ISSUE TITLE
Баг с отключением полей в настройках статусов ICQ/Telegram

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3342]
Открываем настройки и видим, что, хотя, в первом поле стоит 0, все поля активны

![изображение](https://user-images.githubusercontent.com/5046855/220767911-6ab8186c-9fca-47b6-8654-5b48782a6c8c.png)

И только если в первом поле поменять 0 на любое число, а потом вернуть обратно 0, все прочие поля становятся корректно недоступными

![изображение](https://user-images.githubusercontent.com/5046855/220768395-312253cd-06ae-4e90-b872-7da7c0111610.png)

Проще говоря, почему-то при открытии настроек оно не прочухивает, что тут 0 и надо все disable-ить.

**Comment by dartraiden** [comment]
В телеграме забыл поправить.

**Comment by georgehazan** [comment]
В смысле "забыл поправить"? Там полностью идентичный код

**Comment by georgehazan** [comment]
проверил, все в телеге ok
