### ISSUE TITLE
Protocol is not loaded

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3343]
Когда учётка отключена, пишется "protocol is not loaded"

![изображение](https://user-images.githubusercontent.com/5046855/220771891-f71d83e1-92b6-4dd5-a74d-b439242e4a61.png)

Когда-то давно в Miranda IM это было правдой, ведь каждая учётка соответствовала своей копии протокола (допустим, если было 2 учетки ICQ, то нужно было держать 2 копии dll протокола). Сейчас это не так, протокол вполне себе загружен (верхняя учётка же работает).

Предлагаю заменить "protocol is not loaded" на "account is disabled". А лучше вообще убрать эту надпись. Про то, что учётка отключена и так пишется правее, там где должен быть логин-пароль.

**Comment by georgehazan** [comment]
Вот смотри - берем и стираем ICQ.dll. Надпись будет точно такой же, именно потому, что весь протокол (а не один конкретный аккаунт) не загрузился, т.е. в прописанный в учетке BaseProto не существует. А вот почему в длинной цепочке мыслей что-то пошло не так, а соотв учетка не загрузилась, менеджер не знает, он просто вместо ссылки на учетку получил NULL.
