### ISSUE TITLE
Jingle: gst plugins not found

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3349]
Инициирую звонок.

Получаю сообщение о том, что плагины не найдены

![изображение](https://user-images.githubusercontent.com/5046855/221423221-7793c7c3-5ff6-401e-9bdf-a99a3a860d5c.png)

**Comment by dartraiden** [comment]
Ничего не изменилось, всё та же ошибка.

**Comment by georgehazan** [comment]
починилось
