### ISSUE TITLE
VoiceService: не переводятся строки в окне звонка

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3350]
![изображение](https://user-images.githubusercontent.com/5046855/221423290-bc6bbeeb-235a-4286-8cd9-7ab6db6bdc9d.png)

Call
Cancel
Close
Call is over

**Comment by georgehazan** [comment]
Даже не знаю, что сказать
mir_snwprintf(text, TranslateT("Call is over %s"), m_nsec ? m_lblStatus.GetText() : L"");

А этот плагин вообще в перевод включен?

**Comment by dartraiden** [comment]
Ready
Call
Cancel
Close
