### ISSUE TITLE
Telegram: невозможно открыть приватные групповые чаты

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3354]
У меня есть чаты, в которые доступ закрыт и пригласить может лишь администратор.

Эти чаты серые в списке контактов, их невозможно открыть. Но при этом оттуда исправно прилетают сообщения. Если умудриться зайти в такой чат через нажатие на попап с сообщением, то:
- у чата нет никлиста
- в логе не отображаются ники участников, только реплики

<img width="603" alt="Miranda64_vC7iONB4X2" src="https://user-images.githubusercontent.com/5046855/221702360-7757424f-91cf-4be3-858e-13359be07da1.png">

**Comment by georgehazan** [comment]
да, у меня тоже такое есть, надо разбираться
