### ISSUE TITLE
Telegram: поиск по нику работает неправильно

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3355]
Протокол почему-то считает, что "ник" это тупо объединение полей "Имя" и "Фамилия".

Пример: ник в телеграме у чувака Ivan550, т.е. https://t.me/Ivan550

Делаем поиск по нику
<img width="503" alt="Miranda64_uOtkjhHrjB" src="https://user-images.githubusercontent.com/5046855/221705292-bec6b0e0-7187-4eb2-a086-1ecb2df77cd1.png">

У всех найденных "Ник" представляет собой объединение "Имя"+"Фамилия".
Другими словами, у выделенного в списке на скриншоте чувака в столбце "Ник" должно быть `Ivan550`

**Comment by georgehazan** [comment]
а телеге пофиг, на самом деле, она не выделяет ник из общей массы
т.е. все три строки складываются и просто едут в таком виде на сервер
