### ISSUE TITLE
Telegram: сообщение про смс-код

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3357]
С целью экономии денег Паша больше не присылает проверочный код для любых десктопных и веб-клиентов в смс. Теперь код присылается только в уже существующую сессию.

Например, я завожу телеграм на телефоне, затем завожу официальный клиент на десктопе (код для входа прилетает в мобильный клиент), затем отключаю мобильный клиент и завожу телеграм в Миранду (код прилетает уже на десктопный клиент, т.к. он остался единственной сессией)

Когда пользователь заводит телеграм-учётку в Миранду, он получает сообщение "Enter secret code sent to your phone". Нужно как-то это переформулировать, что код будет прислан не на телефон, а в другую активную сессию (она может быть на каком угодно устройстве)

```
[Enter secret code sent to your phone"]
[Phone code expired]
[Invalid phone code]
```

Все эти сообщения нужно переформулировать. В смс Миранда уже никогда ничего не получит, т.к. Миранда десктопный клиент.

**Comment by georgehazan** [comment]
переделал сообщение, если будут мысли про улучшения, поправь прямо в коде
