### ISSUE TITLE
Не раскрываются подменю в редакторе меню контакта

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3359]
<img width="503" alt="Miranda64_k6BW6blQMX" src="https://user-images.githubusercontent.com/5046855/221854622-bd729ed7-11b6-4dde-a2a3-07d8f59b52b8.png">

Жму плюсик - подменю "Заглушать чат" должно раскрываться. А оно не реагирует.

Причем, в редакторе главного меню всё ок, баг именно в редакторе меню контакта.

**Comment by georgehazan** [comment]
некоторые подменю, помеченные как обслуживающиеся протоколом, не раскрываются и не редактируются
