### ISSUE TITLE
VoiceService: не работает "Удержать"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3362]
![photo_2023-02-28_15-47-46](https://user-images.githubusercontent.com/5046855/221858563-e0eccf15-00b0-4e95-b899-12306d342b62.jpg)

**Comment by georgehazan** [comment]
"Удержать" перебрасывает микрофон с одного звонка на другой, т.е. требуется, чтобы пришел второй звонок
