### ISSUE TITLE
Repository: set up credentials scanning

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3379]
https://habr.com/news/t/719660/

**Comment by georgehazan** [comment]
так репа-то не на гитхабе?

**Comment by dartraiden** [comment]
Это сканирование публичной репы, чтобы в нее не затесалось токенов. Публичная репа у нас на гитзабе

**Comment by georgehazan** [comment]
не, это бред полный. 
использование приватной репы полностью исключает попадание токенов в код и так
