### ISSUE TITLE
Telegram: не получается добавить бота, с которым уже было взаимодействие, но потом диалог был удален

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3390]
- добавляем в официальный клиенте бота https://t.me/u2ckbot
- нажимаем "Запустить"
- отправляем боту любой домен на проверку, допустим "github.com"
- удаляем диалог с ботом

**Эти шаги важны, ниже станет понятно, почему.**

Теперь, если выполнить поиск **u2ckbot** через официальный клиент, то мы видим, что этот бот почему-то нашёлся не в разделе "Общий поиск, а хз где он нашёлся. Это потому, что мы с ним уже общались. Хотя, повторюсь, диалога с ботом нет, мы удалили диалог.

<img width="181" alt="Telegram_yqyGaJ5CJu" src="https://user-images.githubusercontent.com/5046855/222852274-673b165c-1d4f-4313-b769-4ffb346bc25c.png">

(на скрине вверху искомый бот, а в разделе "Общий поиск" нашёлся только какой-то левый бот, нам не интересный)

- наконец, ищем **u2ckbot** через поиск Миранды

Наблюдаемое поведение: мы находим только того "не интересного нам бота". Похоже, что Миранда ищет только по "общему поиску" (в терминологии телеграма). В итоге, отсутствует возможность добавить через поиск Миранды бота, с которым мы уже однажды взаимодействовали, а потом удалили.

**Comment by dartraiden** [comment]
Кратко: если ты никогда не взаимодействовал с каким-либо ботом, то он поиском официального клиента найдется в разделе "Общий поиск", а также найдётся в Миранде. А вот если ты взаимодействовал с ботом и стёр диалог, то силами Миранды ты уже этого бота не вернешь и не напишешь ему, т.к. он тупо не найдётся.

**Comment by georgehazan** [comment]
Не подтверждаю. После стирания бота из офклиента из списка чатов оба бота ищутся в Global Search и соотв. попадают в /Миранду

**Comment by georgehazan** [comment]
@dartraiden есть идеи, как повторить? может лог сделаешь?
