### ISSUE TITLE
WhatsApp: после удаления учётки остаётся ключ в базе

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3391]
От WhatsApp остаётся один ключ:

```
[WhatsApp]
NLlog=d0
```

Причём, это не учётка, т.к. учётка в базе звалась WhatsApp_1
Предлагаю это вытирать за собой.

**Comment by georgehazan** [comment]
Это не учетка, да, непонятно, откуда оно берется... ща выясним

**Comment by georgehazan** [comment]
сделал, чтобы паразитные учетки не создавали модулей до тех пор. пока это реально не понадобится
