### ISSUE TITLE
[Telegram] Add support for file transfers (images etc) both incoming and outgoing

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#3392]
**Is your feature request related to a problem? Please describe.**
Add support for images/videos/etc file transfers in Telegram.

**Describe the solution you'd like**
Currently, Telegram has pretty good support for chat itself (missing secret chats but I'm not sure if those can be integrated due to their nature?)

**Describe alternatives you've considered**
No real alternatives right now to be honest...

**Additional context**
Maybe temporarily add support for incoming file to be at least mentioned in chat as an event or some... Maybe that could be really quick to implement as a workaround/stopgap until actual file transfers are ready. Right now I don't even know someone sent a picture unless they say so, and people often forget to say so and then wonder why I've not reacted to an image they shared...

**Comment by dartraiden** [comment]
Bug: Currently outgoing file transfers (me from official client -> some contact) received in Miranda as incoming.

**Comment by LittleVulpix** [comment]
I can confirm that receiving _binary_ files works. (I.e. not when someone sends an image or a video but when they send "a file" ). Nothing else works at the moment though, as far as files go.
