### ISSUE TITLE
Telegram: удаление сообщений по запросу собеседника

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3395]
Условия использования Telegram запрещают работу сторонних клиентов, которые не поддерживают удаление сообщений по запросу собеседника.

Это когда в официальном клиенте собеседник жмёт "удалить сообщение" в привате или "удалить чат" (приват целиком) и взводит галку "также удалить для собеседника". А также, когда удаляет в групповом чате сообщение.

Миранда просто игнорирует приход таких требований удалить сообщение из базы, как я понимаю.

Без этой фичи мы ходим под угрозой бана.

**Comment by dartraiden** [comment]
Рассмотрим все возможные случаи:
1) от собеседника прилетает запрос "сотри всю историю" - мы стираем из базы всю историю
2) от собеседника прилетает запрос "сотри конкретное сообщение(я)" - мы стираем запрошенные сообщения
3) я выбираю в Миранде "очистить историю" (в меню контакта) - из базы стирается вся история (как в жаббере, аське, да в чём угодно)
4) добавить в меню контакта пункт "очистить историю у собеседника" - собеседнику отправляется запрос на очистку всей его истории
5) я в журнале выбираю удаление конкретного сообщения - а вот тут неясно, что делать

**Comment by georgehazan** [comment]
Тут не все так просто. Пункт меню контакта "Empty history" экспортирует ядро, и оно просто стирает историю событие за событием - это будет дикий оверхед для телеги

**Comment by georgehazan** [comment]
> * от собеседника прилетает запрос "сотри всю историю" - мы стираем из базы всю историю.

это уже как бы реализовано

**Comment by georgehazan** [comment]
> 5\. я в журнале выбираю удаление конкретного сообщения - а вот тут неясно, что делать. Как узнать, хочу я удалить это сообщение чисто у себя, или у собеседника тоже?

есть мнение, что надо в учетке сделать настроечку - стирать только себе или всем

**Comment by dartraiden** [comment]
Не работает.

**Comment by georgehazan** [comment]
отлично стирается, только что проверил
