### ISSUE TITLE
tabSRMM: нежелательный сдвиг текста в журнале

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3396]
- берём tabSRMM со встроенным журналом
- берём тестовую конфу и заполняем видимую часть журнала сообщениями

<img width="528" alt="mstsc_RoWfQskL6w" src="https://user-images.githubusercontent.com/5046855/222929389-6da81833-c621-44e3-9b46-f2ccbbc2a82e.png">

- включаем фильтр событий, чтобы не показывались входы и выходы

<img width="200" alt="rwlvKRRCw0" src="https://user-images.githubusercontent.com/5046855/222929407-1df442fc-ebf3-4018-b674-8fada7e84406.png">

- заводим в конфу второй аккаунт и начинаем им входить и выходить из чата

после 89 входов/выходов журнал резко отскакивает вверх

![изображение](https://user-images.githubusercontent.com/5046855/222929442-939ae966-bd39-458c-bf18-ffc1eae0328d.png)

**Comment by dartraiden** [comment]
Т.е. первые 88 событий входа/выхода никак не повлияли, журнал был заполнен репликами сверху донизу, как на первом скриншоте. А вот 89 событие заставило журнал отскочить.

**Comment by SigmaTel71** [comment]
Скорее всего, влияет сколько не тип событий, сколько их общее количество. Сообщение же тоже как событие считается? Если прибавить к количеству сообщений количество событий входа-выхода до отскока журнала, сколько получается?

**Comment by dartraiden** [comment]
22 сообщения + 88 входов/выходов

**Comment by georgehazan** [comment]
в принципе логично - у групчата есть буфер на 100 событий, соотв 88 выходов и входов оставят там 12 событий, и верхние 10 событий должны стереться

**Comment by georgehazan** [comment]
ну т.е. идешь в Настройки - Беседы - Чаты и откручиваешь чиселко со 100 до 1000, например - и оно перестанет стираться
