### ISSUE TITLE
tabSRMM: поведение кнопок BBCode

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3397]
Настройки табсов дефолтные, создал новый профиль.

Открываем приват, смотрим глобальное состояние BBCode: они выключены

<img width="409" alt="bNCUoOGd0g" src="https://user-images.githubusercontent.com/5046855/222931673-b7f0769b-449f-442c-9dbf-693115593039.png">

На тулбаре в привате кнопок BBCode закономерно нет. Но в групчате они ЕСТЬ.

<img width="98" alt="mstsc_6hsJG5svII" src="https://user-images.githubusercontent.com/5046855/222931702-46d069ef-55f2-451a-9d95-d386cc8a342f.png">

И только если в том самом меню с первого скриншота глобально передёрнуть BBCode на вкл и потом на выкл, они пропадут из групчатов.

Таким образом, чаты почему-то считают, что по умолчанию BBCode включены, а приваты считают, что выключены. И только когда пользователь явно передернет опцию, приваты и чаты сойдутся во мнении.

**Comment by dartraiden** [comment]
Кроме того, вопрос, а почему кнопки BBCode в чатах неактивны?

**Comment by georgehazan** [comment]
> Но в групчате они ЕСТЬ.

Наличие кнопок управляется из настроек тулбара, им эти настройки по барабану

**Comment by georgehazan** [comment]
> Кроме того, вопрос, а почему кнопки BBCode в чатах неактивны?

Активность кнопок зависит от свойства протокола передавать bbcodes.
