### ISSUE TITLE
Telegram: не работает отправка события "прочитано"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3402]
У меня официальный клиент, у собеседника Миранда.

Он мои сообщения прочитал, но у меня не появилось двойной галочки

<img width="202" alt="Telegram_8ne3wL7DYY" src="https://user-images.githubusercontent.com/5046855/223165309-f54a5b12-37f5-498d-8370-dc55048206ab.png">

**Comment by dartraiden** [comment]
<img width="225" alt="Telegram_7NXp180gF1" src="https://user-images.githubusercontent.com/5046855/225038871-d7fd4e64-3e62-41b9-b268-59fc949717ce.png">

**Comment by georgehazan** [comment]
Немного не так: если окно с перепиской уже открыто, то уведомление о прочтении высылается на ура. Если окно не открыто, а появляется в результате нажатия на иконку в трее, то  уведомление о прочтении высылается, но не работает.
