### ISSUE TITLE
Telegram: добавление контакта по номеру телефона

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3405]
Официальный клмент позволяет искать (с помощью поля поиска) людей по имени, фамилии, @нику, но не по номеру телефона. 
Миранда тоже умеет искать по имени, фамилии и нику.

<img width="346" alt="Miranda64_cHRJYyVoVW" src="https://user-images.githubusercontent.com/5046855/223200829-b600d706-51af-4b2a-a88e-9f5fea74c380.png">

А вот добавлять контакты официальный клиент позволяет только по номеру телефона.

<img width="288" alt="Telegram_wRNguKAqgI" src="https://user-images.githubusercontent.com/5046855/223200898-ca5a4019-d35b-4a4b-8d64-c818a5fa7bc2.png">

В Миранде это не реализовано (например, я знаю номер телефона приятеля и хочу его добавить, но я знать не знаю, под каким ником он зареган в телеграме). Надо подумать, как это впихнуть. По идее, поиск и добавление контактов это же разные вещи.

**Comment by georgehazan** [comment]
сделал отдельную формочку в меню протокола
