### ISSUE TITLE
Telegram: не сихронизируется удаление контактов между официальным клиентом и Мирандой

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3406]
- завёл учётку Telegram в Миранду, в Миранду прилетел контакт @georgehazan 
- выключил Миранду
- в официальном клиенте удалил переписку с @georgehazan ("удалить чат"), а также удалил его из контактов Telegram

не осталось никаких следов в официальном клиенте

- запускаю Миранду, протокол подключается к сети

@georgehazan остаётся в клисте Миранды и не думает пропадать

В обратную сторону, при этом, всё синхронизируется. Т.е. если я удаляю контакт из Миранды, он стирается из контактов официального клиента.

**Comment by georgehazan** [comment]
Тут на самом деле вопрос на вопросе. Когда надо истреблять контакт в миранде? Когда стерта переписка (удален чат) или снесен контакт? В телеге это две разные сущности, а в миранде - одно и то же

**Comment by dartraiden** [comment]
Предлагаю так:
1) Реализовать приём сообщений от тех, кто не в адресной книге (я сделаю тикет про это). Допустим, какой-то незнакомец взял и писнул мне

таким образом, в Миранде у нас будет два типа контактов: из адресной книги и не из адресной

2) Если через официальный клиент я удаляю переписку с контактом, который НЕ в адресной книге, то истребляем его в Миранде

3) Если через официальный клиент я удаляю переписку с контактом, который остаётся В адресной книге, то в Миранде очищаем переписку, но контакт не удаляем. Если затем я удаляю его и из адресной книги, то истребляем в Миранде.

4) Если через официальный клиент я удаляю контакт из адресной книге, но не удаляю переписку, то в Миранде переводим его из статуса "в адресной книге" в статус "не в адресной". Если затем я удаляю переписку в официальном клиенте, то ситуация сводится к описанной в п.2
