### ISSUE TITLE
Telegram: в переписке с добавленными контактами я <undef>

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3407]
Добавляю контакт в Миранду. Пишу ему. Вместо моего имени - `<undef>`

<img width="578" alt="Miranda64_IqPk5PBeVV" src="https://user-images.githubusercontent.com/5046855/223204114-30f539e4-0ab5-4d9b-a1c1-89134392a0ed.png">

**Comment by georgehazan** [comment]
Надо смотреть, что у тебя выставлено показывать в списке контактов, по идее там должно быть пустое имя. У табсов <undef> выводится, когда миранда для контакта показывает пустой ник (в данном случае для контакта = 0, т.е. тебя)

**Comment by dartraiden** [comment]
<img width="283" alt="explorer_OIffP2PZ86" src="https://user-images.githubusercontent.com/5046855/223534449-ab6433b6-963e-4352-ab61-943b5f7af9ae.png">

В официальном клиенте у меня задано и FirstName, и Nick.

**Comment by georgehazan** [comment]
@dartraiden все еще нужен лог первого входа после регистрации в эту учетку
