### ISSUE TITLE
Telegram: окно ввода пароля странно себя ведёт

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3409]
Во-первых, текст заголовка не влезает по длине в дефолтную длину окна

<img width="294" alt="Miranda64_OVzGBdOMvV" src="https://user-images.githubusercontent.com/5046855/223206315-bd00173c-d800-4cae-a9c3-259679aecf4d.png">

Во-вторых, если я хочу таки прочитать этот текст и увеличиваю ширину окна, то строка ввода не расширяется вслед за окном

<img width="557" alt="Miranda64_G5D8i3QKUN" src="https://user-images.githubusercontent.com/5046855/223206498-e56c3ba7-444e-4a83-a064-7b9654a47fad.png">

**Comment by georgehazan** [comment]
Ресайзер поправил, а вот как менять ширину окна - бес его знает, просто сделал надпись покороче
