### ISSUE TITLE
Crash on import Miranda IM profile file

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#341]
**Reported by esim on 15 Nov 2014 15:27 UTC**
i imported a Miranda IM profile file and get a crashlogs.
after that i use dbchecker with aggressive mode, all events marked as read and convert unicode to utf8.
i started miranda ng but get every time a crashlog

Versionsinfo: http://pastebin.com/raw.php?i=YBzUeSxn

[crash20141115161816.txt](https://github.com/miranda-ng/miranda-ng/files/646895/crash20141115161816.txt)

[crash20141115161909.txt](https://github.com/miranda-ng/miranda-ng/files/646896/crash20141115161909.txt)

[crash20141115161952.txt](https://github.com/miranda-ng/miranda-ng/files/646897/crash20141115161952.txt)

[crash20141115162254.txt](https://github.com/miranda-ng/miranda-ng/files/646899/crash20141115162254.txt)

**Comment by georgehazan** [comment]
**Comment by wishmaster on 15 Nov 2014 16:03 UTC**
Could you delete ImportTXT plugin from plugin directory and try again?

**Comment by georgehazan** [comment]
**Comment by esim on 16 Nov 2014 09:18 UTC**
without importtxt it works normally

**Comment by georgehazan** [comment]
**Comment by wishmaster on 16 Nov 2014 09:23 UTC**
I thought so. Could you now open Main menu->Accounts and see if there are any new created accounts? If so, please double click them and post a screenshot here. Import plugin was recently changed to recreate missing accounts.

**Comment by georgehazan** [comment]
**Comment by esim on 16 Nov 2014 15:22 UTC**
yes there are new accounts and works great since i removed importTXT.dll file.
i upgrade msn accounts to dummies but if i download latest importTXT plugin and restart i get a crashlog on start up.

**Comment by georgehazan** [comment]
**Comment by wishmaster on 16 Nov 2014 15:27 UTC**
Replying to [esim](comment:4):
> yes there are new accounts and works great since i removed importTXT.dll file.
Like I said: "If so, please double click them and post a screenshot here."

**Comment by georgehazan** [comment]
**Comment by esim on 16 Nov 2014 17:45 UTC**
oh sorry i didnt read that.
on first try i get a crashlog but this time with other result.
if i double click on a account i can change account name.
it need only one click to get account information.

**Comment by georgehazan** [comment]
**Comment by wishmaster on 16 Nov 2014 18:03 UTC**
Replying to [esim](comment:6):
> oh sorry i didnt read that.
> on first try i get a crashlog but this time with other result.
> if i double click on a account i can change account name.
> it need only one click to get account information.
Yes, and it will keep crashing because the account created by import plugin is corrupted. Delete it and it won't crash anymore.

**Comment by georgehazan** [comment]
**Comment by esim on 17 Nov 2014 09:12 UTC**
i used miranda im with trillian import plugin and dann export it with menuex plugin.
after that i import it with menuex on miranda ng.
there are many possibles where it get corrupted

**Comment by georgehazan** [comment]
**Comment by wishmaster on 17 Nov 2014 09:23 UTC**
I don't understand? It seems you use Miranda NG Import plugin, it's the only plugin that can create accounts. Could you open a thread in the german forum about it? It's hard to understand you.

**Comment by georgehazan** [comment]
**Modified by esim on 17 Nov 2014 19:47 UTC**

**Comment by georgehazan** [comment]
**Modified by esim on 26 Dec 2014 12:37 UTC**

**Comment by georgehazan** [comment]
**Comment by esim on 26 Dec 2014 12:41 UTC**
Importing a Miranda IM profile it works now fine but if i want import a Miranda NG profile than i get a crashlog and after this on every start of Miranda NG too.
http://pastebin.com/raw.php?i=9Crjxtd6

if i deactivate ImportTXT than importing works too but than when i activate ImportTXT than i get crash on every start.
http://pastebin.com/raw.php?i=cVMmqzts

**Comment by dartraiden** [comment]
ImportTXT is deprecated.
