### ISSUE TITLE
Jabber: If no nick for room in Bookmarks Miranda uses user ID as nick.

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#3412]
### Expected behavior
Miranda asks for nick.

### Actual behavior
Miranda reveals user ID.

### Does it work in stable version?
0.96.3

### Steps to reproduce that behavior
1. Open Bookmarks and delete nick (make it empty) for conference;
2. Double click on this bookmark to join.

**Comment by dartraiden** [comment]
[uni_nick.patch](https://github.com/miranda-ng/miranda-ng/files/10922298/uni_nick.patch)

**Comment by georgehazan** [comment]
поправил патч и залил
