### ISSUE TITLE
ICQ: групчат залетает в клист с неверной группой

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3420]
- нас добавляют в групчат
- в клисте Миранды он отображается в группе, которая задана в настройках табсов

<img width="252" alt="Miranda64_8Nc21CS10M" src="https://user-images.githubusercontent.com/5046855/224472288-15dbe04a-6f65-4fa2-8425-135e0e922ea1.png">

- открываем чата в редакторе базы и видим, что на самом деле он в группе Conferences, а клист врёт
- и только когда мы руками чат в клисте переносим из группы Чаты в группу Чаты же, в базе у него прописывается правильная группа

**Comment by georgehazan** [comment]
Потому что у тебя в лангпаке Conferences переводится как Чаты?
