### ISSUE TITLE
Sessions: опция "только если доступна последняя сессия" ведёт себя странно

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3421]
Настройки по умолчанию:

![изображение](https://user-images.githubusercontent.com/5046855/224560136-3d71e80c-2cbd-444a-bff2-3aa27517fb26.png)

Теперь переключаем на "Восстановить предыдущую сессию", нажимаем ОК и снова открываем настройки

![изображение](https://user-images.githubusercontent.com/5046855/224560171-b79651a8-0a0e-435b-a2bb-8cb9761c5000.png)

Результат:
1) галка "только если доступна последняя" снялась (не должна была, мы ж её не трогали)
2) если снова выбрать "Открыть менеджер" и взвести галку "только если доступна последняя", нажать ОК и переоткрыть настройки, галка будет снаята. Т.е. галку взвести обратно невозможно

**Comment by georgehazan** [comment]
Просто тип контрола выбран криво, по факту это такой же радиобатон, как и остальные три
