### ISSUE TITLE
Yahoo: contacts that i want to add see a wrong name of me

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#343]
**Reported by FredAC on 24 Nov 2014 20:28 UTC**
Hi there,

when I add a new yahoo-contact, the person I want to add doesn't get shown MY name as the person who wants to contact him, but the name of the last contact i added to my own list.
So to make an example: I add person X. After adding Person X I want to add Person Y. Person Y get's shown a request from Person X (but it was me who wants to add Y).
So something seems to be mixed up in the code...

Can somebody help please?

This issue is not new (since one year approx.), but this way I want to make a new try to get it fixed...

Frederik

**Comment by georgehazan** [comment]
**Modified by FredAC on 24 Nov 2014 21:06 UTC**

**Comment by georgehazan** [comment]
**Modified by FredAC on 24 Nov 2014 22:38 UTC**

**Comment by georgehazan** [comment]
**Comment by wishmaster on 3 May 2015 10:53 UTC**
Could you please attatch a [network log](http://wiki.miranda-ng.org/index.php?title=Netzwerklog) when you try to add a contact?

**Comment by georgehazan** [comment]
**Comment by FredAC on 8 May 2015 10:03 UTC**
Hi, i added a logfile as requestet.

The Problem is, we are many users of Miranda, and not all of us have the descripted bug all the time. The logfile attached now is "bug-free".

I hope i can add another logfile of a different user within the next days, who is having the bug.

**Comment by georgehazan** [comment]
**Comment by FredAC on 15 May 2015 15:24 UTC**
Hi, anbei das andere versprochene Log-File, welches zu einem Fehler fhrte. Der Empfnger (b.winhall) sah in diesem Fall einen ganz anderen User als den, der den Request abgesendet hatte (horn_michael85).

**Comment by aunsane** [comment]
Yahoo protocol was depricated b0f3e30460fc26ef4fe59bc161b0fddd8eeb9a08.
