### ISSUE TITLE
While Miranda is launched some hotkeys in other programs do not work

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#3435]
### Expected behavior
Hotkeys in other programs work.

### Actual behavior
While Miranda is launched some hotkeys in other programs do not work.

### Does it work in stable version?
0.96.3 64-bit

### Steps to reproduce that behavior
1. Launch Chromium or Electron based software.
2. Launch Miranda.
3. Go to Chromium based software and press hotkeys.

**Comment by dartraiden** [comment]
Ctrl+Shift+N работает нормально.
