### ISSUE TITLE
Как работают фильтры событий?

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3440]
Вот настройки фильтра событий по умолчанию. Плагин сообщений роли не играет, поведение везде одинаковое.

![изображение](https://user-images.githubusercontent.com/5046855/226145313-b2352c6c-f9e9-4176-b94b-4a023a37b8d6.png)

Там ясно написано, что галки влияют на то, что показывать, **когда фильтр событий активен**.

Открываем групчат. Видим, что фильтр событий **не активен** (воронка с красным крестиком).

<img width="328" alt="mstsc_ni1tgzzoXx" src="https://user-images.githubusercontent.com/5046855/226145425-792987e3-c4eb-47cc-899b-74be3258d962.png">

Но почему-то попапы при неактивном фильтре ведут себя именно так, как настроено в настройках выше. Т.е. если включить в настройках попапы при смене ника, то будут вылезать попапы при смене ника. Вопрос: почему же настройки, которые гласят "вот это показывать при активном фильтре" действуют при неактивном фильтре?

Либо тут какая-то ошибка, либо текст "Show when filter is active" врёт, потому что эти галки учитываются и тогда, когда фильтр inactive.

**Comment by georgehazan** [comment]
На всех кнопках в миранде нарисовано то действие, которое произойдет, если на кнопку нажать. Т.е. кнопка с красным крестиком - это выключение фильтра

**Comment by dartraiden** [comment]
> Т.е. кнопка с красным крестиком - это выключение фильтра

Табсы считают иначе. См. заголовок окна. Значок на кнопке отражает текущее состояние, а не будущее.

![изображение](https://user-images.githubusercontent.com/5046855/226389754-5f38aba1-8955-4efe-9926-f8e71f16487e.png)

**Comment by dartraiden** [comment]
В табсах иконка теперь отражает то, что произойдёт при нажатии.

А вот в скривере она по-старому отражает текущее состояние фильтра.
