### ISSUE TITLE
tabSRMM: не работает фильтр событий для комнаты

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3441]
Этот баг следует обсудить только после разбирательств с https://github.com/miranda-ng/miranda-ng/issues/3440

Вот настройки фильтра событий табсов по умолчанию:

![изображение](https://user-images.githubusercontent.com/5046855/226145749-0839c0ee-6c5c-40fe-9cba-0d207bb6c8d5.png)

Т.е. показывать попапы, звуки, мигание в трее только для хайлайтов. Для остальных событий ничего не показывать.

Открываем чат и включаем фильтр событий в чате. Получаем такое.

![изображение](https://user-images.githubusercontent.com/5046855/226145780-4648f46d-b5a1-403e-8d93-767be4069dbd.png)

Я полагаю, что квадратики означают "как в глобальных настройках". Окей. Явным образом для этого чата включаем попапы и моргания трея на простые сообщения.

![изображение](https://user-images.githubusercontent.com/5046855/226146028-ae427142-13f3-41ef-9c7e-8931d185574d.png)

Ещё раз обращаю внимание, в фильтре событий в комнате написано "Показывать элементы" и стоят галки возле всего, что связано с обычными сообщениями. Я понимаю это так, что когда кто-то писнет в эту комнату, в трее будет моргание и вылезет попап.

Результат: а нет никаких попапов и моргания. Действуют глобальные настройки, где всё отключено. А кастомные для этой комнаты - не действуют.

**Comment by georgehazan** [comment]
Все работает как положено, и настройки сохраняются как надо.
Просто при открытом окне комнаты не работают попапы и трей

**Comment by dartraiden** [comment]
Но ведь не работает как надо.

Вот настройки фильтра для конкретной комнаты

<img width="185" alt="mstsc_buUffVnr5g" src="https://user-images.githubusercontent.com/5046855/226348114-4d139f01-1d7b-4537-bbff-52eef6199352.png">

Вот глобальные настройки

<img width="256" alt="mstsc_b1tUnW7dd4" src="https://user-images.githubusercontent.com/5046855/226348333-8fb0d918-a706-4eb6-af97-8276a218a7c4.png">

Согласно этому, если фильтр в комнате выключен, то действуют глобальные настройки: нет попапов и моргания треем про обычные сообщения в комнате. Если фильтр включён, то должны быть попапы и моргание в трее.

А в реальности всё иначе. Вот фильтр включён:
<img width="21" alt="mstsc_SAmagTKxm1" src="https://user-images.githubusercontent.com/5046855/226348786-d4df314b-7bc9-49bf-8c9b-7d7da8305995.png">

И у нас есть попапы и моргание, как и полагается.

А если фильтр выключен:
<img width="17" alt="mstsc_QL06RbqHlq" src="https://user-images.githubusercontent.com/5046855/226349287-d65ec69b-1313-49b2-860f-947e301e7b80.png">

То у нас опять есть моргания и попапы.
