### ISSUE TITLE
Фильтр событий: убрать лишнюю колонку

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3442]
Вот с такими настройками есть попапы и моргание в трее при смене темы

![226146264-ae40e36d-2263-4bcf-84dc-f4d5bdb809d6](https://user-images.githubusercontent.com/5046855/226146311-30fdbdd0-1aed-4b42-88b5-e835a1c69b05.png)

И с вот такими они тоже есть.

![226146266-2c99f232-f292-4af1-88e4-4e899b2e03c8](https://user-images.githubusercontent.com/5046855/226146324-3b1b2e07-e3d1-41b7-9d9f-28b2bc992c12.png)

Вопрос: а зачем тогда этот вертикальный столбец левый, если он ни на что не влияет? Выпилить его. Текстовые метки оставить, а чекбоксы долой.

**Comment by georgehazan** [comment]
Левая колонка управляет опциями фильтра в групчате по умолчанию для всех чатов, если нажать на иконку фильтра, то там будут отмечены именно эти строки
