### ISSUE TITLE
ICQ: застревают сообщения группового чата

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3447]
- создаём групчат через офиц. клиент
- выключаем офиц. клиент и заходим через Миранду
- пишем в чат "1"
- пишем в чат "2"
- пишем в чат "3"
- пишем в чат "4"

на какой-то итерации происходит следующее:
- сообщение, допустим, "3" уходит, собеседники видят его в чате, но в журнал на нашей стороне оно не попадает
- после отправки "4" в наш журнал влетают сразу "3" и "4"

грубо говоря, словно сообщение где-то застревает, а следующее его проталкивает

при этом, собеседники с других миранд видят всё сразу, как полагается, т.е. баг чисто визуальный на нашей стороне

**Comment by georgehazan** [comment]
не факт. аськин сервер пакетирует сообщения, чтобы они попадали в один long poll, надо смотреть в нетворк лог, в одном они пакете приходят или в разных

**Comment by dartraiden** [comment]
Переоткрою, т.к. в официальном клиенте проблемы нет.
