### ISSUE TITLE
Telegram: дефолтное значение таймаутов для фейковых статусов должно быть 0

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3453]
В ICQ дефолтные настройки такие

<img width="503" alt="Miranda64_6OEV7PZvW6" src="https://user-images.githubusercontent.com/5046855/227647687-7e874558-33f7-4955-8ab1-7b13a4f18b60.png">

В Telegram дефолтное значение у первого статуса - 600. Предлагаю сделать 0. Если кому-то нужны эти фейковые статусы, тот их себе и включит.

**Comment by georgehazan** [comment]
В телеге это дефолтное поведение мобильного клиента, поэтому и включено так, иначе вообще никого в онлайне не будет
