### ISSUE TITLE
Telegram: в чате используется фамилия имя, а в приватах ник

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3455]
Я в групповом чате с чуваком, у которого ник "@ник" и имя "Иван Иванов".

Когда чувак пишет в чате, в логе он показывается, как Иван Иванов. Если я нажму в логе на его имя и выберу "Сообщение", то откроется приват, где на вкладке привата будет "ник".

Как-то нелогично.

Я так понимаю, что в привате это определяется настройками клиста? В клисте ник имеет приоритет выше Фамилии Имени.

<img width="503" alt="Miranda64_yqhUT8X4j6" src="https://user-images.githubusercontent.com/5046855/227652938-66060371-0300-422a-8646-e5d57c711d11.png">

Окей, но может мы тогда и в чатах сделаем так, чтобы уважались эти настройки? А то получается, что в клисте и привате мы это настроить можем (скриншот выше), а вот в логе чата всегда Фамилия Имя без вариантов.

**Comment by georgehazan** [comment]
В привате это определяется шаблоном табсов, что именно показывать
