### ISSUE TITLE
Telegram: при первом входе прилетает только один чат

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3457]
У меня в официальном клиенте один чат помещён в архив. Я завожу учётку в Миранду, логинюсь. Результат: в клист и в базу влетает ровно этот самый один чат. И только когда передернешь протокол в оффлайн-онлайн, прилетят все остальные каналы и чаты.

**Comment by georgehazan** [comment]
Лог нужен

**Comment by dartraiden** [comment]
Выслал лог.

Уточнкение, сейчас это выглядит так:
- я логинюсь, ввожу код и 2FA-пароль
- в клист и в базу чаты/каналы не влетают, влетают только контакты
- как только в каком-то чате что-то пишут, то он влетает в базу и клист

после передёргивания протокола влетают все чаты
