### ISSUE TITLE
tabSRMM: двоятся сообщения

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3458]
Завожу учётку телеги в Миранду.

В официальном клиенте пишу "ыыы" в наш тестовый чат.

Результат:
- в базу Миранды попадает одно "ыыы"
- во встроенном журнале табсов отображается два "ыыы"

<img width="596" alt="explorer_30BHIjgIAk" src="https://user-images.githubusercontent.com/5046855/227654487-0bcc06a9-8fe7-4270-9259-f7ea2491b64a.png">

**Comment by georgehazan** [comment]
не могу повторить. нужен профиль

**Comment by dartraiden** [comment]
Удалось повторить в аське. Сетап: официальный клиент с одним уином, Миранда с другим уином.

1) создаю в официальном клиенте группу, куда добавляю Мирандовский уин
2) пишу 3 сообщения в официальном клиенте

<img width="134" alt="explorer_9MlLCloA2b" src="https://user-images.githubusercontent.com/5046855/230512000-920f8578-18bb-4491-9043-158d87edd7fd.png">

3) открываю этот чат в Миранде

<img width="446" alt="Miranda64_4Q8TYhA7oD" src="https://user-images.githubusercontent.com/5046855/230512045-dbdb1ae5-8b6d-4608-95bc-7fc68d16e1f6.png">
