### ISSUE TITLE
Telegram: история чатов не вгружается корректно при открытии окна

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3460]
Я сижу в супергруппе

- пишу через официальный клиент в групчат
- моё сообщение появляется и в миранде
- после меня туда пишут другие юзеры, в журнале всё появляется
- перезапускаю Миранду

результат: в базе все сообщения исправно сохранились, они видны через просмотрщик истории. А вот при открытии чата в журнале табсов те самые мои сообшения... и всё, того, что нафлудили после меня - нет

**Comment by georgehazan** [comment]
Сейчас это зависит от того, как настроен журнал - на показ сообщений за N минут, последних N сообщений или фиксированного числа сообщений

**Comment by dartraiden** [comment]
У меня настроено "Показывать 15 последних сообщений"
