### ISSUE TITLE
tabSRMM: показ имен в журнале групчата ломается

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3461]
- поменял приоритет имен в настройках клиста (не знаю, важно ли это, но вдруг)

<img width="503" alt="Miranda64_eSUDAcH49q" src="https://user-images.githubusercontent.com/5046855/227663041-8abe2ce9-dc45-4ba6-bd33-86bc1164cd61.png">

- через какое-то время открываю групчат телеграма, а там некоторые имена пропали

<img width="433" alt="Miranda64_LqZWzcLYQu" src="https://user-images.githubusercontent.com/5046855/227663168-3c1cd875-1c43-4f7b-836e-1331763867ab.png">

На скриншоте вместо имен некоторых юзеров в логе пустота

**Comment by georgehazan** [comment]
@dartraiden второй день этого нету, может быть оно как-то починилось вследствие наложения критической секции на изменение некоторых данных
