### ISSUE TITLE
Miranda's hideout

### ISSUE THREAD

**Issue by MPerfurt** [miranda-ng/miranda-ng#3468]
When restarting Windows & Miranda, Miranda hides outside of the display. Default Display Setting: 3840x2160 + Zoom: 175% - If I switch the zoom to 125%, then Miranda appears somewhere on the display.
![miranda-ng-display-hideout](https://user-images.githubusercontent.com/88318026/228208683-4b382853-0131-4235-a84e-8506ed2b1a18.PNG)
![miranda-ng-display-setting](https://user-images.githubusercontent.com/88318026/228208692-b133835c-c77b-4daf-8439-6141cfe788ba.PNG)

**Comment by georgehazan** [comment]
@MPerfurt which contact list do you use? Modern, Nicer or StdClist?

**Comment by MPerfurt** [comment]
Hi George,
 
the modern clist is selected:
 
 
  
am Dienstag, 28. März 2023 um 13:16 schrieben Sie:

> @MPerfurt which contact list do you use? Modern, Nicer or StdClist?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.


-- 
ATeO-Service Mario Pohle     phone: +49 361 241 43 0
Magdeburger Allee 140        fax  : +49 361 241 43 29
99086 Erfurt                 http://www.ateo.de/
USt./VAT-ID: DE 188394558
================================================================
WebDesign, Online-Shops, WebSpace & Domains, Internetzugänge
Sind Ihre Webseiten für Suchmaschinen optimiert? Steigern Sie
jetzt Ihre Besucherzahlen mit ausgefeiltem Internetmarketing:
http://www.ateo.de/suchmaschinenoptimierung.html

**Comment by georgehazan** [comment]
@MPerfurt 
check please Options - Contact list - Window - Pin to desktop. If this option is checked, Miranda would bind the main window's coordinates to the desktop borders, and if you chose the larger scale, most of the contact list will be hidden. In this case you need to disable this option and move contact list once manually, Miranda will remember its location

**Comment by dartraiden** [comment]
In addition, there are ways to get to the application window that is off the screen
https://t.me/sterkin_ru/1467
