### ISSUE TITLE
The warning about smiles set stays forever.

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#3473]
### Expected behavior
What did you expect?
### Actual behavior
Warning about smiles set stays forever.

### Does it work in stable version?
0.96.3

### Steps to reproduce that behavior
1. Install SmileyAdd
2. You should be warned that no smiles sets.
3. This warning stays forever.

**Comment by georgehazan** [comment]
Options -> Popups -> Set timeout

**Comment by JeanPaulLucien** [comment]
Timeout was. The warning from SmileyAdd was visible much more than in settings.

**Comment by dartraiden** [comment]
Да, всплывающее окно о том, что смайлов нет, не имеет таймаута.
