### ISSUE TITLE
ICQ: отправленные мной в групчат файлы Миранда расценивает как новое сообщение

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3478]
- меня приглашают в групчат
- я кидаю в групчат картинку

Несмотря на то, что окно сообщений открыто (я туда кинул картинку только что), в клисте около групчата появляется значок непрочитанного сообщения.

**Comment by georgehazan** [comment]
Логично: если фокус не на текущем контейнере, то будет зажигаться значок
фокус сбивает окно пересылки файлов
