### ISSUE TITLE
ICQ crashes on receiving long message

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#348]
**Reported by dennorth on 9 Dec 2014 09:17 UTC**
падение протокола icq при получение большого текста

**Comment by georgehazan** [comment]
**Comment by watcher on 9 Dec 2014 10:40 UTC**
Please use english for ticket name and bug description, please attach crashlogs.

**Comment by georgehazan** [comment]
**Comment by watcher on 9 Dec 2014 10:40 UTC**
http://wiki.miranda-ng.org/index.php?title=Crash_reports

**Comment by georgehazan** [comment]
**Modified by watcher on 9 Dec 2014 10:43 UTC**

**Comment by dartraiden** [comment]
No crashlog, no old ICQ.
New protocol tested with 4500 symbols. All OK.
