### ISSUE TITLE
ICQ: сессия не закрывается при уходе ноутбука в гибернацию

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3480]
Сообщил пользователь, проверить пока не на чем.

**Comment by georgehazan** [comment]
а почему сессия должна закрываться? там надо отсылать специальный пакет, а миранду прибивают, не спрашивая

**Comment by dartraiden** [comment]
Не удаётся воспроизвести: через минуту после ухода в сон сессия на моём ноутбуке закрывается.
