### ISSUE TITLE
History++: не следует переводить название плагина в списке журналов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3484]
В локализации H++ есть строчка

```
[History++]
История
```

Она предназначена для того, чтобы переводить пункт настроек H++ (выделен красным)

<img width="395" alt="5kupbzc10L" src="https://user-images.githubusercontent.com/5046855/231706504-73271bd6-22a4-4a3f-a125-6a3c3e1ca7e7.png">

Однако при этом переводится и имя журнала в списке журналов. В итоге, у нас там есть журнал с названием "История" (выделен синим).

Там, где выделено синим, не следует переводить строку "History++"

**Comment by georgehazan** [comment]
Тогда и мысль про "встроенный журнал" переводиться не будет
