### ISSUE TITLE
Tox: seems toxme.io is not actual

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#3490]
In window Contact search there is some text for Tox with toxme.io domain. Seems toxme.io is not actual.

Steps to reproduce:
1. Find/add contacts window
2. Select Tox
3. The text with "toxme.io" domain is visible

**Comment by dartraiden** [comment]
Точнее: если при поиске контактов введён не адрес Tox, а что-то иное, то Миранда попытается поискать на toxme.io, который больше не работает.

Следует выпилить эту логику.

**Comment by JeanPaulLucien** [comment]
https://github.com/miranda-ng/miranda-ng/issues/3333
