### ISSUE TITLE
History++: ошибка при удалении сообщения из журнала

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3491]
![изображение](https://user-images.githubusercontent.com/5046855/232584387-411b4266-39e2-46ed-8910-4039002b2cf9.png)

Ошибка возникает только в 32-разрядной версии.

**Comment by georgehazan** [comment]
у меня не падает в 32-битном варианте
к сожалению, больше я ничего по данному вопросу предложить не могу, по понятным причинам
