### ISSUE TITLE
Import: not possible to import mContats files

### ISSUE THREAD

**Issue by Mitch037** [miranda-ng/miranda-ng#3494]
1. export contact's history (TXT or mContacts)
2. clear contact's history (and delete it in case of importing mContacts)
3. import contact's history back
3.1. right-click on a contact, select Import and then select History++ from the list (for TXT) or Miranda NG database (for mContacts)
4. Log:

when importing TXT
> Number of contacts in database: 1
> Skipping new contacts import.
> Skipping system history import.
> Importing history.
> Loading file 'ContactHistory.txt'...
> Import completed in 0 seconds.
> Added 0 contacts and 0 groups.

when importing mContacts
> Number of contacts in database: 1
> Importing groups.
> Importing contacts.
> Skipping contact with no protocol
> Importing system history.
> Importing history.
> Import completed in 0 seconds.
> Added 0 contacts and 0 groups.
> Skipped 1 contacts.

**Comment by georgehazan** [comment]
@Mitch037 for which protocol, Steam?
cause the text file import works ok for Jabber

**Comment by dartraiden** [comment]
Cannot reproduce TXT with Jabber and Facebook. Works fo me.

mContacts import is broken

**Comment by georgehazan** [comment]
@Mitch037 well, it's not a broken import, it's a broken export :-) you need to export files to mContacts format again

**Comment by dartraiden** [comment]
> Any idea how can I isolate the issue

Please provide example of txt file.

**Comment by dartraiden** [comment]
Tested: 32 and 64-bit generates identical files. Import works on both 32 and 64 bit under Windows 10.

**Comment by dartraiden** [comment]
You history:
`[2023-04-21 12:01:27]`

My history
`[21.06.2022 2:10:36] `

**Comment by dartraiden** [comment]
Well, it depends on Windows date settings...

Russian: 21.06.2022
USA: 4/27/2023

What region is set on your system?

**Comment by dartraiden** [comment]
History++ written on Pascal. Pascal uses Windows date format.

Moreover, it uses the format from the LANGUAGE settings.

**Comment by dartraiden** [comment]
The problem is that the History++, when exporting, uses the date format from the Windows settings, but Import uses default format for current region

Example: Russian default date format is dd.mm.yyyy. If I change the format here

![photo_2023-04-27_17-38-57](https://user-images.githubusercontent.com/5046855/234897397-e1a774a9-64af-4b82-abad-e457e1199b0a.jpg)

to yyyy-mm-dd, then in the exported history i will get yyyy-mm-dd, but Import expexts dd.mm.yyyy

**Comment by dartraiden** [comment]
Then the bug is more simply: "Import does not like the yyyy-MM-dd format"

**Comment by dartraiden** [comment]
https://github.com/miranda-ng/miranda-ng/issues/3514

**Comment by dartraiden** [comment]
Starting from build 25606 History++ forces the format dd.mm.yyyy
