### ISSUE TITLE
Import: not possible to import MsgExport file

### ISSUE THREAD

**Issue by Mitch037** [miranda-ng/miranda-ng#3495]
1. export contact's history
2. clear contact's history
3. import contact's history
3.1. right-click on a contact, select Import, then select History++
4. Log:

> Number of contacts in database: 1
> Skipping new contacts import.
> Skipping system history import.
> Importing history.
> Loading file '...\miranda-ng\Profiles\MyProfile\MsgExport\ContactHistory.txt'...
> Cannot parse file header, skipping file
> Import completed in 0 seconds.
> Added 0 contacts and 0 groups.

**Comment by dartraiden** [comment]
Msg_Export text format is not equivalent History++ text format.
