### ISSUE TITLE
Steam: Cannot Login - 'ISteamWebUserPresenceOAuth' not found

### ISSUE THREAD

**Issue by RathaWynter** [miranda-ng/miranda-ng#3498]
Steam had a service disruption a couple of hours ago but since coming back online, Miranda has been unable to log in.

This behavior happens with an old install of Miranda (0.96.1 24180) and a freshly updated one (0.96.3 25537), tested with two different Steam accounts.

Preview of error log:
`<html><head><title>Not Found</title></head><body><h1>Not Found</h1>Interface 'ISteamWebUserPresenceOAuth' not found</body></html>`

[_Netlog_TestAccount_Sanitized.txt](https://github.com/miranda-ng/miranda-ng/files/11279027/_Netlog_TestAccount_Sanitized.txt)
[VersionInfo.txt](https://github.com/miranda-ng/miranda-ng/files/11279045/VersionInfo.txt)

**Comment by georgehazan** [comment]
Hi, it seems that they have finally dropped HTTP API... too bad, if the websocket API is the only choice now, it's a completely different protocol

**Comment by Tharn** [comment]
So the steam plugin is effectively gone for now? Bummer.

**Comment by dartraiden** [comment]
Looks like it. @georgehazan, as far as I remember, it doesn't make sense to convert the protocol to websockets? (require keeping the steam client running)

**Comment by RathaWynter** [comment]
I'm just throwing this out there for informational purposes in case anyone is unaware: Steam chat is accessible from a standard web browser. Not sure whether future Miranda/Steam plugin changes could take advantage of the same data stream or API that allows the web chat to function, but that seems like it could be a path for future protocols to avoid requiring the Steam Client to be running.

https://steamcommunity.com/chat/

**Comment by LittleVulpix** [comment]
Hi!
I believe there is reasonably functional websocket implementation in Miranda (which I think was used for Discord, formerly...), so maybe it should be possible to re-implement Steam without inventing websocket implementation itself.

that said obviously everything else is different about Steam so... I do see why you said it will be like a whole new protocol.

I would very much like for it to be implemented though...!

**Comment by Tharn** [comment]
Yeah, it would be nice to keep Steam functional by any means... that protocol is the last hold-out for me using Miranda vs. a purely IRC client. No pressure, though. ;)

**Comment by georgehazan** [comment]
> I believe there is reasonably functional websocket implementation in Miranda (which I think was used for Discord, formerly...), so maybe it should be possible to re-implement Steam without inventing websocket implementation itself.

But that obviously means writing new protocol from scratch (despite drawing status icons, of course). If somebody knows the existing open source library which already implements Steam via WS, point me to it, it will significantly speed up the process. Right now I know only libraries which use either the running instance of the official Steam client, or old good HTTP API which just failed.

**Comment by georgehazan** [comment]
> Steam chat is accessible from a standard web browser.

Yes, and it definitely uses websockets, according to my packet analyzer. The problem is that I have no spare time at all to reverse engineer that protocol (read the above comment about library)

**Comment by RathaWynter** [comment]
@georgehazan In addition to Pidgin's Steam implementation [having an issue](https://github.com/EionRobb/pidgin-opensteamworks/issues/206), there appears to also be some kind of GOG Galaxy implementation, however it sounds like their version could have been using the same protocol too. Could be some useful info or people over here to get in touch with, sounds a little like someone might be working on something:
https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/159#issuecomment-1513717833

Recently someone else i talked to mentioned this Matrix Steam bridge project. I believe that their implementation is working, but I know literally nothing about it in any capacity. Linking it here just in case it can be of use.
https://github.com/icewind1991/mx-puppet-steam
https://github.com/icewind1991/mx-puppet-steam/issues/41 - May or may not be related / have useful links.

**Comment by georgehazan** [comment]
@RathaWynter good that we ain't alone, it became to rise my suspicions.
mx-puppet-steam looks more promising, at least it has some implementation on JS
I'll try to log in using this library, if it works, I can adapt it to Miranda

**Comment by ABaumher** [comment]
Coming from the GOG Galaxy page. Galaxy's implementation has uses websockets for communication, but the latest protocol broke us as well, albeit for a different reason. Our code expected a callback confirming login; it's no longer being sent. I'm attempting a fix now, but if you need a look at a websocket implementation, feel free to use whatever you can. Just a warning, I didn't write it so far, so if it looks like gibberish to you, you are not alone.

**Comment by RathaWynter** [comment]
@georgehazan It sounds like the folks at FriendsOfGalaxy managed to get their Steam implementations working. Im not sure if you can use anything they were working on to fix the logins, or if you had made any progress with the way MX Puppet Steam does it.

Just thought I'd let you know that they had made some progress and check in to see if there had been any behind the scenes happenings since we've not heard anything in about a month. There have not been any updates to the Pidgin issue regarding their Steam implementation as far as I can tell either. (Judging solely by looking at the issue / commit trackers.)

**Comment by RathaWynter** [comment]
Just checking in, have not heard anything since April, and was wondering if there'd been any background progress being made or discussion that can be followed as to the current state of the plugin, rewrite, or if anything is in the works. Thanks!

**Comment by Tharn** [comment]
I think the Steam plugin is dead at this point. Time to remove it from the list.

**Comment by wxx1764753522** [comment]
<html><head><title>Not Found</title></head><body><h1>Not Found</h1>Interface 'ISteamWebUserPresenceOAuth' not found</body></html>

**Comment by RathaWynter** [comment]
https://github.com/SteamRE/SteamKit
https://github.com/SteamRE/

Is there anything in here that would lead toward a future revival of the Steam plugin for Miranda? I'm not really sure what its full capabilities are exactly, but it seems as if its got some development within the last year, and some fairly well known players in the 'steam development' community seem to be following, contributing, using, or are otherwise involved with the project in some way.

It seems as if some projects such as Archi's ASF may have been affected by the types of changes to the Steam Authentication / Login that eventually brought Miranda and Pidgin's plugins offline as well. (Although Miranda's Steam protocol went offline April 19, 2023. while they were forced to make changes ~March 19, 2023 as seen here: https://github.com/JustArchiNET/ArchiSteamFarm/issues/2788 )

**Comment by Tharn** [comment]
SteamKit version 3.0.0 just released.

**Comment by georgehazan** [comment]
The protocol revived up to the state when the only thing that doesn't work is sending / receiving messages
