### ISSUE TITLE
StopSpamMod: удалить настройку "удалять все временные контакты после перезапуска"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3499]
В StopSpamMod есть две настройки:
- удалять временно добавленные контакты при перезапуске
- удалять все временные контакты при перезапуске

Как минимум вторую настройку ("удалять все временные контакты") надо удалить, т.к. такая же настройка есть во всех клистах. Из обычного StopSpam мы её уже удалили.

Насчёт первой настройки не уверен. Они, видимо, чем-то отличаются?

![изображение](https://user-images.githubusercontent.com/5046855/233510521-8fd21ab0-f3f3-4fd3-bca1-e8b045b8e7e4.png)

**Comment by georgehazan** [comment]
У первой настройки ориентация на контакты, имеющие флаг Excluded (бес его знает, что это такое).
Вторую настройку убрал
