### ISSUE TITLE
Deleting temporary contacts on exit

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#35]
**Reported by anonymous on 5 Sep 2012 15:24 UTC**
Hello
Please make this optional, some option to turn this on/off in configuration or mirandaboot.ini
I do not want such contacts were deleted on exit and i think not only me
Sometimes we can forget to add some contact and exit Miranda, after this contact is lost

clistmod.cpp:
```
550         //remove transitory contacts 
551         HANDLE hContact = (HANDLE) CallService(MS_DB_CONTACT_FINDFIRST, 0, 0); 
552         while (hContact != NULL) { 
553                 HANDLE hNext = (HANDLE) CallService(MS_DB_CONTACT_FINDNEXT, (WPARAM) hContact, 0); 
554                 if (DBGetContactSettingByte(hContact, "CList", "NotOnList", 0)) 
555                         CallService(MS_DB_CONTACT_DELETE, (WPARAM) hContact, 0); 
556                 hContact = hNext; 
557         }
```

**Comment by georgehazan** [comment]
**Modified by BasiL on 15 Jan 2013 06:35 UTC**

**Comment by dartraiden** [comment]
Fixed in https://github.com/miranda-ng/miranda-ng/issues/2281
