### ISSUE TITLE
Yahoo group chat (conference): groups are lost after switching status offline / online or restart of the program

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#350]
**Reported by FredAC on 13 Dec 2014 12:38 UTC**
Hi there,

with some friends i am using the Yahoo group chat.

Unfortunately, every time one of us (Users or Groups Admin) has once gone offline with Yahoo in Miranda (or has restarted his Miranda application), we have to set up the group new, because otherwise that person no longer "sees" the group (the remaining people can talk, but just without the one person who was away / was offline).

Is there a solution for this?
It should be possible, as in SKYPE (classic) groups it is possible to remain permanently connected, so the group is set up only once and then the people in the group permanently see each other, without having the group always to be new set if somebody was offline.

Would be great if you had a solution.

Frederik

**Comment by georgehazan** [comment]
**Modified by FredAC on 13 Dec 2014 18:29 UTC**

**Comment by aunsane** [comment]
Yahoo group chat was depricated b0f3e30460fc26ef4fe59bc161b0fddd8eeb9a08.
