### ISSUE TITLE
Tipper: Smiley displayed in Skypename

### ISSUE THREAD

**Issue by Mitch037** [miranda-ng/miranda-ng#3505]
If mouse cursor hovers over a Skype contact, it displays a tooltip with contact's data including Skypename. Some skypenames start with: 8:live:d... - as a result ":d" part is 'translated' into :D icon smiley. The only fix for this is to disable "Enable SmileyAdd support" in "Settings\Customize\Tooltips\Extra (TAB)".

**Comment by georgehazan** [comment]
Check the Options - Customize - Smileys - General - Replace only smileys surrounded by spaces
