### ISSUE TITLE
ICQ: при создании групчата не видны ники

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3507]
- я создаю групчат через оф. клиент и затаскиваю в чат 2 своих аккаунта
- затем запускаю две Миранды с этими 2 аккаунтами

результат: в одной из Миранд (каждый раз в разной) в чате отсутствует никлист, а все реплики в чате без ников. После переподключения к сети проблемв уходит.

**Comment by georgehazan** [comment]
лог бы, аська + ядро, в том случае, если ники обкакались

**Comment by georgehazan** [comment]
{"status": {"code": 20000}, "method": "getUserInfo", "reqId": "1a824698-5fc2-43ad-a0b7-50c1d0a7d2aa", "results": {}}

Сервак при запросе структуры чата прислал пустой result, отсюда и пустые ники
