### ISSUE TITLE
Clist: "Toggle fold groups" menu item in Groups menu

### ISSUE THREAD

**Issue by Mitch037** [miranda-ng/miranda-ng#3509]
It would be useful to have a menu item(s) as "Fold/Unfold" or "Toggle fold" groups in Group menu.
Additionally, it would also be useful to have it in "Setup view modes" as "Show groups folded/unfolded", somewhere close to the "Show contacts in groups" option as it would have to be enabled in the first place.

**Comment by georgehazan** [comment]
no, I don't think so. You can click on a button leftwards to the group's name, or use Right/Left arrows to Unfold/fold groups.

**Comment by georgehazan** [comment]
> The same could be said about "Show contacts in groups" in "Setup view modes" :-)

Well, it's a template, group menu isn't.

**Comment by georgehazan** [comment]
A view mode is a template, which can be applied many times. Group menu is smth that exists outside any template, it's a separate entity.

> So maybe Fold/Unfold groups for view modes at least?

Why not? But it should be discussed in another context
