### ISSUE TITLE
Clist_modern: окно приклеивается к краю экрана с зазором

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3510]
Окно приклеено в правом нижнем углу. Как видно, есть зазор сбоку и снизу.

<img width="138" alt="dqxiTf9kpd" src="https://user-images.githubusercontent.com/5046855/234273137-90988b3e-ea16-43bd-9bd2-9f838e3504fe.png">

**Comment by georgehazan** [comment]
Величина этого зазора регулируется, например, в Windows Tweaker -> Window Borders
Это просто прозрачная граница окна, по умолчанию шириной 4 dialog units.

**Comment by dartraiden** [comment]
Поставил 0, перезагрузился, проблема осталась.

**Comment by dartraiden** [comment]
На первом скрине 0, на втором - 4 (значение по умолчанию). Никакой разницы.

<img width="127" alt="0" src="https://user-images.githubusercontent.com/5046855/236909112-7102a9a9-1798-4908-9aca-22c85c4e33f9.png">
<img width="131" alt="4" src="https://user-images.githubusercontent.com/5046855/236909127-0ab7da28-8103-499e-89ba-7d677517273d.png">

**Comment by georgehazan** [comment]
![image](https://github.com/miranda-ng/miranda-ng/assets/4628541/a8218cd7-c78a-41f9-b41c-25d6374e1dd2)
Это как=то от твоего скина зависит, с ним есть зазор, да, а  в Aero Dark нет
Больше ничего не менял, только скин
