### ISSUE TITLE
Import cannot import H++ txt history with yyyy-mm-dd date format

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3514]
Независимо от языка и региона. Если мы берем, скажем, польскую винду, где формат даты по умолчанию yyyy-mm-dd, то Import не может импортировать историю.

**Comment by georgehazan** [comment]
ok, сделал пока, чтобы h++ всегда выливал в формате dd.mm.yyy hh:nn:ss
