### ISSUE TITLE
Plugin Updater: Ability to remove plugin

### ISSUE THREAD

**Issue by Mitch037** [miranda-ng/miranda-ng#3515]
Currently, it is only possible to enable/disable plugin(s) in Plugin Updater. It would be very useful to be able to remove plugin(s) directly from Plugin Updater window, instead of doing it manually from Miranda directory.

**Comment by dartraiden** [comment]
It is not clear what to do with the libraries. If the plugin comes with a library, should I delete it too? What if two plugins share a library?

**Comment by georgehazan** [comment]
> 2\. plugin is tied to library which is also used by other plugin(s)

We don't have this info, that's not a package manager like DEB/RPM with the usage counter for libraries...
