### ISSUE TITLE
Проблема при вгружении NewStory после History++

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3516]
- создаём чистый профиль, History++ и NewStory не установлены
- в меню контакта есть пункт История со стандартным значком, который вызывает StdUIHistory
- ставим апдейтером History++ и соглашаемся его вгрузить
- в меню контакта пункт просмотра истории теперь имеет значок History++
- ставим апдейтером NewStory и соглашаемся его вгрузить

Результат: в меню контакта появляются ДВА пункта просмотра истории. У первого значок StdUIHistory, у второго значок NewStory. При этом оба пункта открывают StdUIHistory. Хотя вгружен NewStory.

**Comment by georgehazan** [comment]
Да, есть такое
