### ISSUE TITLE
Telegram: add to stable

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3526]
1. https://github.com/miranda-ng/miranda-ng/issues/3309
2. https://github.com/miranda-ng/miranda-ng/issues/3390
3. https://github.com/miranda-ng/miranda-ng/issues/3395
4. https://github.com/miranda-ng/miranda-ng/issues/3546
5. https://github.com/miranda-ng/miranda-ng/issues/3392
6. https://github.com/miranda-ng/miranda-ng/issues/3288

**Comment by georgehazan** [comment]
я так понимаю, что под XP телеги не будет вовсе, а с ботом не повторяется
@dartraiden можно закрывать?

**Comment by de77** [comment]
Жаль, если не будет поддержки Telegram в Windows XP.

**Comment by georgehazan** [comment]
@de77 ну вот как в XP прикрутят работу с потоковыми переменными, так сразу
или надо садиться и по-взрослому переписывать TDLIB

**Comment by de77** [comment]
Это которые Thread Local Storage (TLS)?

TlsAlloc()/TlsGetValue()/TlsSetValue() и TlsFree()?
так они ещё с Windows 95 поддерживаются, или это какие-то другие?

**Comment by de77** [comment]
Если я правильно понимаю, то это тоже самое, что и __declspec(thread). Единственно с ним есть проблема:
[Thread Local Storage (TLS)](https://learn.microsoft.com/en-us/cpp/parallel/thread-local-storage-tls?view=msvc-170/)

В частности:
> On Windows operating systems before Windows Vista, __declspec( thread ) has some limitations. If a DLL declares any data or object as __declspec( thread ), it can cause a protection fault if dynamically loaded. After the DLL is loaded with LoadLibrary, it causes system failure whenever the code references the __declspec( thread ) data.

У меня получилось на базе функций Tls*() и шаблона C++ сделать нечто похожее thread_local. На небольших тестовых примерах в Windows XP SP3 это работает.
```
// detls.h - thread_storage implementation by de77
#pragma once

#include <windows.h>

template <typename T>
class detls
{
  public:
   detls(const T& value):init_(0)
   {
     detls_();
     if (id_ != TLS_OUT_OF_INDEXES)
     {
       T* ptr = new T(value);
       TlsSetValue(id_, static_cast<void*>(ptr));
     }
   }

   ~detls()
   {
     if (id_ != TLS_OUT_OF_INDEXES)
     {
       T* ptr = static_cast<T*>(TlsGetValue(id_));
       if (ptr != NULL)
         delete ptr;
     }
   }

   detls():init_(0)
   {
     detls_();
   }

   operator T() const
   {
     T* ptr = static_cast<T*>(TlsGetValue(id_));
     return (ptr != NULL) ? *ptr : NULL;
   }

   operator= (const T& value)
   {
     if (id_ != TLS_OUT_OF_INDEXES)
     {
       T* ptr = static_cast<T*>(TlsGetValue(id_));
       if (ptr != NULL)
         delete(ptr);

       ptr = new T(value);
       TlsSetValue(id_, static_cast<void*>(ptr));
     }
   }

 private:
   DWORD id_;
   LONG init_;

   void detls_(void)
   {
     if (InterlockedCompareExchange((void**)&init_, (void*)1L, (void*)0L) == 0L)
     {
       id_ = TlsAlloc();
       init_ = 1;
     }
     else
     {
       while (!init_)
         Sleep(1);
     }
   }
};
```
К сожалению C++ не совсем моя специализация, так-что там возможно чего-то не хватать и явно можно было сделать гораздо лучше. Во вложениях тестовые примеры, сценарий сборки и протоколы работы тестовых примеров. 
[tester.zip](https://github.com/miranda-ng/miranda-ng/files/11707081/tester.zip)
Если есть возможность, не могли-бы Вы посмотреть, можно-ли будет это как-то применить. 

В любом случае спасибо за Ваш с @dartraiden труд и замечательную программу.

**Comment by dartraiden** [comment]
> В любом случае спасибо за Ваш с @dartraiden труд и замечательную программу.

![Без имени](https://github.com/miranda-ng/miranda-ng/assets/5046855/fc97c9e5-5341-4cd6-8565-fb6d1ca1dab3)
