### ISSUE TITLE
Aero Glass transparency is missing on v0.96.2 build #25339

### ISSUE THREAD

**Issue by MP36ctrl** [miranda-ng/miranda-ng#3528]
### Expected behavior
What did you expect?
Aero transparency on standard miranda windows such as settings or find contact
### Actual behavior
What did you get instead?
No transparency (as if im on basic or classic themes from windows 7) (This excludes Tab SRMM)
### Does it work in stable version?
This is the latest update on the date of this issue
If you know in which dev build (or approximate date when) it was broken, it may be much easier to identify and fix the issue.
v0.96.2 build #25339
### Steps to reproduce that behavior
 * Provide step-by-step instructions so we can reproduce the issue (We can't fix what we can't reproduce).
Simply update to build 25339
[spoiler=VersionInfo][quote]CPU: AMD FX(tm)-6300 Six-Core Processor  [AMD64 Family 21 Model 2 Stepping 0] [DEP Enabled] [6 CPUs]
Installed RAM: 32750 MBytes
Microsoft Windows 7 Ultimate Edition, 64-bit Service Pack 1 (build 7601)
Internet Explorer: 8.0.7601.17514 (build 87601)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | English/English
Free disk space on Miranda partition: 75812 MBytes

Miranda NG Version: 0.96.2 build #25339 (4591857045) x64
Build time: 25 May 2023 22:05:06
Profile: G:\Users\PC of 2015\Documents\Programs\Miranda NG - Copy\Profiles\MSCPCCheckup\MSCPCCheckup.dat
Database driver: SQLite database driver
Profile size: 9248768 Bytes
Profile creation date: 27 May 2023 0:46:27
Language pack: No language pack installed
Service Mode: No
SRMM Log Viewer: hpp

[b]Active Plugins (49):[/b]
¤ AVS.dll v.[b]0.98.1.6[/b] [5 Mar 2023 13:47:18] - Avatar service 
¤ BuddyExpectator.dll v.[b]0.1.2.3[/b] [25 May 2023 22:05:24] - Buddy expectator 
¤ Clist_nicer.dll v.[b]0.9.3.2[/b] [25 May 2023 22:05:20] - Clist nicer 
¤ Cln_skinedit.dll v.[b]0.0.0.4[/b] [5 Mar 2023 13:47:22] - Skin editor for Clist nicer 
¤ CloudFile.dll v.[b]0.11.0.6[/b] [19 May 2023 18:11:42] - CloudFile 
¤ CrashDumper.dll v.[b]0.2.0.1[/b] [19 May 2023 18:09:56] - Crash dumper 
¤ CryptoPP.dll v.[b]1.0.4.8[/b] [5 Mar 2023 13:49:12] - Crypto++ 
¤ Db_autobackups.dll v.[b]0.1.0.7[/b] [25 May 2023 22:05:26] - Db autobackuper 
¤ DbChecker.dll v.[b]0.96.3.1[/b] [25 May 2023 22:08:12] - Database checker 
¤ Dbx_sqlite.dll v.[b]0.96.2.4[/b] [25 May 2023 22:08:04] - Miranda NG SQLite database driver 
¤ Dummy.dll v.[b]0.2.0.1[/b] [25 May 2023 22:07:24] - Dummy protocol 
¤ EmLanProto.dll v.[b]0.1.0.3[/b] [19 May 2023 18:11:36] - E-mage LAN protocol 
¤ Facebook.dll v.[b]0.1.0.11[/b] [19 May 2023 18:11:56] - Facebook 
¤ GmailNotifier.dll v.[b]1.0.1.2[/b] [25 May 2023 22:07:18] - Gmail Multiple Notifier 
¤ historypp.dll v.[b]1.5.1.5[/b] [25 May 2023 22:08:42] - History++ 
¤ HistoryStats.dll v.[b]0.2.1.2[/b] [5 Mar 2023 13:49:54] - HistoryStats 
¤ ICQ.dll v.[b]0.96.3.2[/b] [25 May 2023 22:08:08] - ICQ-WIM protocol 
¤ IEView.dll v.[b]1.6.0.5[/b] [25 May 2023 22:05:34] - IEView 
¤ Import.dll v.[b]0.96.3.1[/b] [25 May 2023 22:06:04] - Import contacts and messages 
¤ IRC.dll v.[b]0.96.1.4[/b] [25 May 2023 22:05:14] - IRC protocol 
¤ Jabber.dll v.[b]0.95.11.1[/b] [25 May 2023 22:06:16] - Jabber protocol 
¤ MinecraftDynmap.dll v.[b]0.1.0.1[/b] [19 May 2023 18:11:12] - Minecraft Dynmap protocol 
¤ mRadio.dll v.[b]0.0.2.4[/b] [5 Mar 2023 13:50:34] - mRadio Mod 
¤ MsgPopup.dll v.[b]0.1.2.2[/b] [5 Mar 2023 13:49:14] - Message popup 
¤ NewEventNotify.dll v.[b]0.2.2.7[/b] [25 May 2023 22:06:02] - NewEventNotify 
¤ NotesReminders.dll v.[b]0.2.2.2[/b] [25 May 2023 22:08:08] - Sticky Notes & Reminders 
¤ Omegle.dll v.[b]0.1.3.4[/b] [19 May 2023 18:09:50] - Omegle protocol 
¤ PluginUpdater.dll v.[b]0.2.1.5[/b] [21 Mar 2023 10:04:32] - Plugin updater 
¤ PopupPlus.dll v.[b]2.1.2.0[/b] [5 Mar 2023 13:47:56] - Popup plus 
¤ QuickSearch.dll v.[b]1.5.0.4[/b] [31 Mar 2023 12:29:02] - Quick Search 
¤ SecureIM.dll v.[b]1.0.12.6[/b] [5 Mar 2023 13:47:46] - SecureIM 
¤ SeenPlugin.dll v.[b]5.0.5.6[/b] [19 May 2023 18:09:26] - Last seen 
¤ SendSS.dll v.[b]0.9.0.2[/b] [5 Mar 2023 13:48:22] - Send ScreenShot+ 
¤ SmileyAdd.dll v.[b]0.3.2.2[/b] [19 May 2023 18:09:36] - SmileyAdd 
¤ SplashScreen.dll v.[b]0.1.2.3[/b] [5 Mar 2023 13:47:46] - Splash screen 
¤ StatusChange.dll v.[b]1.3.0.0[/b] [5 Mar 2023 13:49:08] - Status change 
¤ StatusManager.dll v.[b]1.2.0.6[/b] [5 Mar 2023 13:50:02] - Status manager 
¤ Steam.dll v.[b]0.96.1.1[/b] [19 May 2023 18:11:22] - Steam protocol 
¤ TabSRMM.dll v.[b]3.6.2.6[/b] [25 May 2023 22:05:32] - TabSRMM 
¤ Tipper.dll v.[b]2.1.0.7[/b] [5 Mar 2023 13:47:52] - Tipper 
¤ TooltipNotify.dll v.[b]0.7.0.1[/b] [5 Mar 2023 13:47:50] - Tooltip notify 
¤ TopToolBar.dll v.[b]0.8.0.5[/b] [5 Mar 2023 13:48:04] - TopToolBar 
¤ Tox.dll v.[b]0.11.3.2[/b] [19 May 2023 18:12:12] - Tox protocol 
¤ TrafficCounter.dll v.[b]0.1.1.9[/b] [5 Mar 2023 13:48:40] - Traffic counter 
¤ Twitter.dll v.[b]1.3.1.7[/b] [19 May 2023 18:10:00] - Twitter protocol 
¤ UserGuide.dll v.[b]0.0.0.1[/b] [5 Mar 2023 13:47:52] - User guide 
¤ VoiceService.dll v.[b]0.1.3.1[/b] [25 May 2023 22:08:18] - Voice Service 
¤ wbOSD.dll v.[b]0.2.1.0[/b] [19 May 2023 18:10:42] - WannaBe OSD 
¤ WebView.dll v.[b]0.1.3.3[/b] [5 Mar 2023 13:49:28] - Webview 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
CloudFile/GDrive         1 - Enabled 0 - Disabled  Loaded
Discord                  2 - Enabled 0 - Disabled  Loaded
Dummy                    1 - Enabled 0 - Disabled  Loaded
EM_LAN_PROTO             1 - Enabled 0 - Disabled  Loaded
Facebook                 2 - Enabled 0 - Disabled  Loaded
ICQ                      1 - Enabled 0 - Disabled  Loaded
JABBER                   1 - Enabled 0 - Disabled  Loaded
Omegle                   1 - Enabled 0 - Disabled  Loaded
STEAM                    1 - Enabled 0 - Disabled  Loaded
TOX                      1 - Enabled 0 - Disabled  Loaded
Twitter                  1 - Enabled 0 - Disabled  Loaded
WebView                  1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 HistoryPP_icons.dll [25 May 2023 22:08:34]
 Proto_Discord.dll [1 Mar 2022 15:53:57]
 Proto_Dummy.dll [25 May 2023 22:08:36]
 Proto_Facebook.dll [19 May 2023 18:12:16]
 Proto_ICQ.dll [25 May 2023 22:08:38]
 Proto_IRC.dll [25 May 2023 22:08:34]
 Proto_Jabber.dll [25 May 2023 22:08:34]
 Proto_MetaContacts.dll [25 May 2023 22:08:36]
 Proto_MinecraftDynmap.dll [19 May 2023 18:12:16]
 Proto_MRA.dll [25 May 2023 22:08:38]
 Proto_mRadio.dll [5 Mar 2023 13:50:28]
 Proto_Omegle.dll [19 May 2023 18:12:14]
 Proto_Steam.dll [19 May 2023 18:12:16]
 Proto_Tox.dll [19 May 2023 18:12:16]
 Proto_Twitter.dll [19 May 2023 18:12:14]
 SecureIM_icons.dll [5 Mar 2023 13:50:26]
 TabSRMM_icons.dll [25 May 2023 22:08:36]
 Toolbar_icons.dll [1 Nov 2022 20:30:12]
 xStatus_Jabber.dll [25 May 2023 22:08:34]
[/quote][/spoiler]
 * Attach a crash report if you are experiencing crashes (It includes VersionInfo as well).
 * Attach a network log captured if you are experiencing connectivity issues.
 * If Miranda freezes, hangs up or consumes CPU, attach information obtained by Process Explorer tool.

**Comment by dartraiden** [comment]
Probably regression after https://github.com/miranda-ng/miranda-ng/commit/23f21ae625b736b640d9258b2660111e38e21145

**Comment by MP36ctrl** [comment]
Ah i see, can you add an option to restore it if possible? as i am on windows 7 and it looks odd
