### ISSUE TITLE
Clist_modern: прозрачность применяется принудительно

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3532]
В настройках модерна отключена всякая прозрачность

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/b1475382-d1e7-49f8-8dc1-243a08d225e1)

Когда окно модерна поверх обычного приложения, оно действительно не прозрачно. Но если оно поверх 3D-приложения, например, поверх эмулятора Android, оно имеет прозрачность

**Comment by georgehazan** [comment]
а если включить галку "Режим без скина"?

**Comment by dartraiden** [comment]
Тогда норм, но клист выглядит довольно пугающе.

**Comment by georgehazan** [comment]
Тогда это к GDI+... он используется для виртуального рисования на поверхности при включенном layered mode
