### ISSUE TITLE
Перенос приватного репозитория с BitBucket на GitHub

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3536]
В связи с тем, что [Роскомнадзор решил, что россиянам не нужен BitBucket](https://ntc.party/t/bitbucket-org/4624), предлагаю перенести приватный репозиторий с секретами на GitHub.

Требуется:
- создать здесь приватный репозиторий
- залить туда файлы вместе с историей коммитов
- раздать доступ к репозиторию тем, у кого он был на BitBucket

**Comment by georgehazan** [comment]
предлагаю поднять гит у нас на сервере и не мучаться

**Comment by apollo2k4** [comment]
> предлагаю поднять гит у нас на сервере и не мучаться

Поддерживаю.

**Comment by georgehazan** [comment]
Сейчас проверил - доступ и через веб, и через консоль гита работает без перебоев и ВПН
