### ISSUE TITLE
Jabber: перенести опцию об использовании HTTP FIle Upload в настройки протокола

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3538]
Если сервер криво настроен и декларирует поддержку HTTP File Upload, но не реализует её, то у пользователя нет возможности отключить сабж, т.к. Миранда включает это по умолчанию, а галки для отключения в Service Discovery тупо нет.

**Comment by georgehazan** [comment]
Отказать. Так уже было, и в итоге всё похерилось, потому что сложность немыслимая всё это организовывать

**Comment by dartraiden** [comment]
В конференции выяснили, что такого не было.

**Comment by georgehazan** [comment]
ghazan: c http upload конечно полная чушь получается
ghazan: т.к. это не фича и не публикуется в самом начале, то надо при каждом логине выслать диско, считать список нод и на каждую ноду заслать запрос деталей, и это только для того, чтобы считать имя ноды для аплоада
ghazan: давайте оставим настройку и все
ghazan: не будем ничего никуда переносить
