### ISSUE TITLE
Telegram: не работает загрузка истории для Saved messages

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3544]
Для обычный контактов работает. Для Saved messages - нет.

**Comment by dartraiden** [comment]
После обновления загрузилось автоматически (почему-то) одно сообщение. Ручная загрузка положения не исправила - по-прежнему это одно сообщение в истории и торчит.

**Comment by georgehazan** [comment]
Потому что первая попытка отправила все сообщения в системную историю, и они больше не грузятся, т.к. такие идентификаторы в базе уже есть. Надо стереть из системной истории
