### ISSUE TITLE
Не сохранять настройки нетлога для удалённых учётных записей

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3547]
На примере Telegram:

- создаю учётку с именем "Telegram"
- ставлю на неё галку в настройках нетлога, само ведение нетлога (файл и прочее) можно не включать

<img width="375" alt="Miranda64_hoY4gLTo2j" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/bad887c3-c402-4d3f-91c5-40c952769bc5">

- удаляю учётку
- перезапускаю Миранду
- снова завожу учётку с именем "Telegram"

Результат: в настройках нетлога галка на этой учётке уже стоит. Хотя учётка свеженькая. Галка осталась от прошлой учётки.

**Comment by georgehazan** [comment]
Настройки логирования хранятся внутри модуля и учетки и стираются вместе с ним, разумеется
Просто логирование автоматом включается для всех новых учеток

**Comment by dartraiden** [comment]
У меня новые учётки никогда не включают логирование автоматически.
