### ISSUE TITLE
StdMsg: настраиваемый стиль кликабельной http-ссылки внутри чата

### ISSUE THREAD

**Issue by Deadooshka** [miranda-ng/miranda-ng#3554]
На данный момент стиль ссылки зависит от системной темы. Хотелось бы иметь цветовую настройку шрифта ссылки, как это есть для остальных текстовых элементов чата.

**Comment by georgehazan** [comment]
Миранда никак не участвует в рисовании ссылок, поэтому задать цветв для них нереально

**Comment by Deadooshka** [comment]
@georgehazan, тогда как тогда убрать кликабельность ссылки? Такой настройки нет. Настройки темы и шрифтов независимы от системной темы, поэтому цвет ссылок в каком-то случае будет неотличимым от фона, то есть невидимым.

**Comment by dartraiden** [comment]
Например, использовать History++, он на паскале и поэтому рисует ссылки сам, а также умеет настраивать их цвет.
