### ISSUE TITLE
Псевдоредактирование

### ISSUE THREAD

**Issue by apollo2k4** [miranda-ng/miranda-ng#3559]
Пока ждем доработок NewStory.
Было бы неплохо временно отключить псевдоредактирование т.к. оно активируется одиночным кликом когда NewStory выступает журналом чата в Scriver.

**Comment by dartraiden** [comment]
Или добить это до полноценного редактирования с одновременным обучением протоколов отправлять правку на сервер.

**Comment by georgehazan** [comment]
> Или добить это до полноценного редактирования с одновременным обучением протоколов (Telegram, ICQ, Jabber) отправлять правку на сервер.

Оно и есть полноценное редактирование с отправкой результата на сервер. Работает пока только в Discord

**Comment by apollo2k4** [comment]
> Работает пока только в Discord

Который дропнут ввиду их борьбы с нами.

**Comment by georgehazan** [comment]
теперь оно активируется двойным кликом
