### ISSUE TITLE
Telegram: удалённый канал остаётся в Миранде

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3563]
- создаём в официальном клиенте канал (не групчат, а именно анонимный канал, куда постить может только владелец)
- делаем там пост
- заводим учётку в Миранду
- при логине этот канал влетает в Миранду
- выключаем Миранду
- удаляем канал через официальный клиент
- запускаем Миранду

Результат: канал в клисте есть, только серый и зайти туда нельзя.

**Comment by georgehazan** [comment]
В логе видно, что канал приходит со статусом Banned. Идея на получение такого статуса была в том, чтобы сохранить канал как контакт для того, чтобы осталась история, ну т.е. очень не хочется стирать канал, если тебя там забанили - вдруг что-то полезное останется
