### ISSUE TITLE
Центрировать кнопку в диалогах, которые предусматривают лишь одну кнопку

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3565]
Есть предложение её центрировать в таких случаях.

<img width="170" alt="Miranda64_Bs81Dxq8Wd" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/fc97b910-fcaa-4858-8aee-e37aa20fb9be">

**Comment by georgehazan** [comment]
Это как бы стандартный MessageBoxW, там такой опции не предусмотрено
