### ISSUE TITLE
ICQ: статус "Не в сети"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3566]
Проблемы:
- миранду выключаем - остальные клиенты (например, другая Миранда) видят её по-прежнему в онлайне
- десктопный клиент сворачиваем - Миранда видит его в онлайне бесконечно, пока сама Миранда не переподключится
- десктопный клиент разлогиниваем - Миранда видит его в онлайне бесконечно, пока сама Миранда не переподключится
- мобильный клиент сворачиваем - через минуту Миранда видит его оффлайн. Это как и должно быть.

Таким образом, есть какие-то проблемы при взаимодействии Миранда-Миранда и Миранда-десктопный клиент.

Сюда я буду складывать результаты своих наблюдений и дампы трафика.

**Comment by dartraiden** [comment]
Как ведёт себя официальный декстопный клиент при неактивности:

https://forum.miranda-ng.org/index.php?topic=118.msg30448#msg30448

```
событие такое:
Код: [[Выделить]](javascript:void(0);)

{
          "type" : "presence",
          "eventData" : {
            "nick" : "Crackerz",
            "aimId" : "694631417",
            "displayId" : "694631417",
            "friendly" : "Номер Асечков",
            "onlineTime" : 0,
            "userType" : "icq",
            "iconId" : "000101103cdcb279dc09ceaaa1b97d3b38f677de",
            "lastseen" : 0
          },
          "seqNum" : 163250
        }

Точно такое же приходит при разлогинивании, так что номер всегда в сети.
Если запросить статус номера или перелогиниться, то у такого номера не будет приходить onlineTime в данных, так его можно приписать к офлайновым.
```

**Comment by dartraiden** [comment]
В качестве первого шага давай

[ ] запрашивать инфу о пользователе после каждого изменения статуса

**Comment by Mikanoshi** [comment]
Запрашивать бесполезно, пока не переподключишься приходят неверные данные.
Также у меня есть примеры номеров, которые закрыли сессию в крысе и никакие переподключения не меняют их данные, всегда lastseen = 0, а onlineTime остутствует. Я добавил проверку, чтобы кидать такие в офлайн, вроде пашет)
Но так и непонятно как выйти в офлайн в любом клиенте, включая все официальные, чтобы альтернативные увидели это без всяких переподключений и мгновенно.

**Comment by georgehazan** [comment]
@Mikanoshi 
> Я добавил проверку, чтобы кидать такие в офлайн, вроде пашет)

какую проверку?

**Comment by Mikanoshi** [comment]
> какую проверку?

> lastseen = 0, а onlineTime отcутствует

2 рабочих способа как определить реально ли номер в офлайне:
- запросить getUserInfo или getUserLastseen (второе удобнее, можно задать список номеров), там приходит правильный lastseen и всё ок
- запросить давно устаревший wim/presence/get, там приходит lastseen = 0 для таких контактов, при этом в запросе отсутствует onlineTime

Просто в R&Q при получении КЛ с сервера при создании сессии и при выходе контактов онлайн автоматом запрашиваются капсы, а это wim/presence/get, так что чтобы не добавлять новых запросов я использую 2ой способ.
Оф клиенты в любом случае отправляют события с lastseen=0 onlineTime=0 постоянно, когда юзер фокус на окно делает, так что и 1ым способом потом проверяется статус, когда контакт уже онлайн.

**Comment by georgehazan** [comment]
> * (второе удобнее, можно задать список номеров), там приходит правильный lastseen и всё ок

Чот не работает, вывожу миранду в оффлайн, делаю запрос getUserLastseen, получаю в lastseen всё тот же 0.

**Comment by Mikanoshi** [comment]
Хз, у меня работает) Сейчас вообще при закрытии сессии в Миранде и оф клиенте через короткое время после события с нулями приходит событие с правильным lastseen>0, что-то на сервере аси поправили похоже.

**Comment by dartraiden** [comment]
У меня ничего не уходит.

**Comment by Mikanoshi** [comment]
Так эта фигня и не работает надёжно. При закрытии клиента или разлогиновании приходит событие с lastseen=0 onlineTime=0, после этого через 10-20 сек может придти ещё одно с правильным lastseen>0, а может и ничего не придти. Мало того, даже если запросить getUserLastseen через пару секунд после этого события, то там может быть всё ещё 0, т.е. тоже с задержкой меняется.
Короче я сделал проверку getUserLastseen через 5 сек после прихода нулей и каждые 15 минут проверку ВСЕХ онлайн контактов.
