### ISSUE TITLE
Jingle: опция "Использовать VOIP" отсутствует, если вгрузить плагин на лету

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3573]
Если вгрузить Jingle на лету, опция "Использовать VOIP" отсутствует в настройках учётки Jabber. Появляется только после перезапуска.

**Comment by georgehazan** [comment]
видимо, пофиксилось вместе с #3572

**Comment by dartraiden** [comment]
Нет, https://github.com/miranda-ng/miranda-ng/issues/3572 исправился, а этот жив.
