### ISSUE TITLE
Folders: add support for offline files path

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3574]
Currently, offline files are downloaded to /<profile/dlFiles folder

Let's make it customizable.

**Comment by dartraiden** [comment]
Нужно подумать, возможно, логично будет как-то связать путь к offline files с уже имеющейся настройкой пути сохранения старых файлотрансферов, чем выносить настройку в Folders.

**Comment by SM-Sergey** [comment]
Могу сказать, что после сегодняшнего коммита и обновления - эта проблема решена - файлы попадают туда, куда указано в опциях файлтрансферов.
