### ISSUE TITLE
NewStory: add offline files support

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3576]
При прилёте такого файла NewStory честно рисует ссылку вида `file://.../dlFiles/id/filename`, но файл не принимается.

**Comment by SM-Sergey** [comment]
Не знаю, сюда ли это относится, но...

После сегодняшнего коммита (7fae2fb) в ньюстори сломались ссылки на все старые, давно скачанные, файлы (включая и те, которые были скачаны задолго до образования сервера ICQ, хранящего файлы), на их месте остались просто "file://"
