### ISSUE TITLE
Оффлайновые файлы: доработка журналов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3578]
Сюда будем складывать конкретные претензии к отображению оффлайновых файлов в журналах

**Comment by SM-Sergey** [comment]
Можно добавить? 
Открывать файл, наверное, стоит не по второму клику, когда файл уже скачался, а для определенного списка расширений  файлов (картинки, видео) просто по факту скачивания. Ведь если кликнул на такой файл, то ожидается, что он откроется. И в контекстном меню иметь выбор - Download, Download and open и Open (который засерен пока файл не скачан)

**Comment by SM-Sergey** [comment]
Ну вроде не так сложно - в опциях (файлтрансверов?) добавить список расширений для автооткрытия с ручным вводом, и по умолчанию там держать самое распространенное. А в систему совсем не лезть. Если не установлен просмотрщик чего-то, система сама спросит "чем открыть"

**Comment by SM-Sergey** [comment]
И вообще - было бы неплохо, чтобы по клику на оффлайн файл инициировался бы "старый" полноценный файлтрансфер со всеми его опциями, включая путь и автопереименование файлов, кроме уже лишнего подтверждения. А не простая загрузка в dlFiles.

**Comment by georgehazan** [comment]
> И вообще - было бы неплохо, чтобы по клику на оффлайн файл инициировался бы "старый" полноценный файлтрансфер со всеми его опциями, включая путь и автопереименование файлов

Автопереименование - это устаревший бред, протокол гарантирует размещение файлов под уникальными именами. Человеческое имя файла показывается, но нигде не используется

**Comment by SM-Sergey** [comment]
Ничего протокол не гарантирует! Мы через ICQ пересылаем по 100 версий одного файла (прошивки для микроконтроллеров и ПЛИС в процессе отладки) в день, и именно автопереименование обеспечивало сохранение их всех локально под разными номерами. Теперь это сломалось.

**Comment by georgehazan** [comment]
Всё там хорошо, с сервера приходит вполне себе уникальное имя файла, видимо в плагине остался старый код, который сохраняет не под тем именем

**Comment by SM-Sergey** [comment]
Ну уж извините. Если еще и файлы начнут менять имена не на те, что оригинальные, это вообще полная задница будет, особенно когда речь идет о документах, прошивках, исходника.

**Comment by georgehazan** [comment]
Есть такая программа - браузер, которая хранит в кэше файлы хрен знает под какими именами. При попытке открыть файл он открывается с правильным именем. Какая разница пользователю, как оно хранится?

**Comment by SM-Sergey** [comment]
Причем тут кэш? Тут речь о передаче файлов от меня (разработчика) к товарищу (тестировщику). Или наоборот - например счета на оплату от клиента ко мне. Надо чтобы он в результате попал в папку, связанную с его контактом и сохранил там свое родное имя, и если надо автопереименовался в (1) (2) и т.д. Чтобы я через пять или десять лет зашел в эту папку и нашел этот файл по его имени, не копаясь в глубинах истории. Это прекрасно работало с 2003 года, когда я поставил миранду, и до вчера. А что и как там будет в журнале смотреться - это само по себе, конечно там должно быть и имя файла и локальная ссылка на него для открытия, это само собой и отдельно. Но локальное сохранение всех файлов "as is" в папках для отдельных контактов - для меня первично.

**Comment by georgehazan** [comment]
> Причем тут кэш?

При том, что сейчас обсуждается хранение файлов в кэше миранды? Это даже не кэш протокола, это общий кэш для всех оффлайновых файлов в Миранде, вне зависимости от протокола. Как оттуда будут браться файлы при нажатии на клик - это вообще не проблема пользователя.

**Comment by SM-Sergey** [comment]
Хорошо. Пусть это новое будет "кеш". И пусть он будет работать как угодно, если нельзя его оставить в удобном "старом формате" файлтрансфера с его опциями. Я просто думал, что это проще в реализации. Если нет, то нет.

Тогда жизненно необходимо оставить возможность старых файлтрансферов, чтобы имелась возможность автозагрузки всех приходящих файлов в автомате по папкам по контактам без изменения их оригинальных имен и с автопереименованием. Пускай параллельно с "кешем" - просто если в опциях файлтрансферов стоит "авто акцепт". Чтобы не следить за всеми файлами, и не кликать по ним, чтобы потом "где-то в тундре" не оказалось, что этот файл отсутствует в локальном хранилище.

Или какой тогда есть быстрый способ найти нужный файл, если я знаю, что мне было прислано за сегодня 20 файлов "image.hex" и мне нужен третий с конца?

**Comment by georgehazan** [comment]
> Или какой тогда есть быстрый способ найти нужный файл, если я знаю, что мне было прислано за сегодня 20 файлов "image.hex" и мне нужен третий с конца?

Ткнуть на нем в истории? Имхо это самое логичное, вместо того, чтобы ковыряться в файловой системе. В истории может и комментарий быть к этому файлу

**Comment by SM-Sergey** [comment]
Я вообще то с этими файлами в консоли работаю, нередко в wsl, но чаще в Far Manager.
Это получается, что мне придется еще и комментировать их всех по мере прихода?

**Comment by georgehazan** [comment]
Вообще не проблема - просто настроить винду, чтобы файлы открывались с помощью ФАР

**Comment by SM-Sergey** [comment]
Ну это костыли все. Фар всегда открыт на одном мониторе, незачем его переоткрывать, на то он и фар, чтобы просто в нем работать. А wsl? Чтобы открыть это что-то чем-то wsl-линуксовым?

Речь в целом о другом - оно до вчера прекрасно работало, можно сказать идеально, ну кроме зависаний некоторых трансферов. А теперь сломалось, причем до такой степени, что пока видится только один вариант - оставаться на версии до вчерашнего коммита.

**Comment by SM-Sergey** [comment]
В общем, в сухом остатке, нужно вот что:
1) Иметь возможность включить старую систему файлтрансферов вместо новой системы с кешем (лучше всего для отдельных контактов, но можно и глобально для протокола, или вообщее глобально).
2) Желательно (не обязательно) иметь в журнале/истории в контекстном меню на записи с файлом "Perform File transfer" для того, чтобы его руками скачать по правилам файлтрансферов. Не важно, из кеша или из онлайна, важно чтобы он получил оригинальное имя и попал в папку согласно опциям файлтрансфера.
3) Если файл загружен файлтрансфером, то клик в журнале/истории должен открывать файл из файлтрансфера, так как ему кеш уже точно не нужен. Иначе из системы с офлайном и кешем.

Вот, как то так... Причем именно жизненно необходимо!

**Comment by georgehazan** [comment]
> Вот, как то так...

Это как бы одна из точек зрения, не нужно делать из нее культа. Например, если сделать так, то при форварде картинки в телеге на N контактов она будет скачана N раз и аккуратно разложена в их папки. Офигительный функционал, да?

**Comment by SM-Sergey** [comment]
А это почему она будет разложена? При форварде это же исходящий файл, а не входящий. А скачиваются только входящие.

Просто речь о том, что файлтрансферы уже давно хорошо работают, и местами очень удобны и нужны, и я прошу сделать лишь выбор для пользователя, где он хочет использовать старую систему, а где новую. И как писал на форуме, могу даже обсудить какую нибудь сумму за это, так как из-за этого (при условии не отката на старые версии) у меня рабочие процессы сильно замедлились и стали зело нервными.

**Comment by georgehazan** [comment]
> А это почему она будет разложена? При форварде это же исходящий файл, а не входящий. А скачиваются только входящие.

Т.е. свои файлы в логе показывать не надо? Это как? А если авто скачивание включено, оно всё всосет, не разбираясь

**Comment by SM-Sergey** [comment]
> Т.е. свои файлы в логе показывать не надо? Это как? А если авто скачивание включено, оно всё всосет, не разбираясь
По логике - показывать надо. Вдруг я его потерял, этот файл, и хочу обратно скачать. А вот автоскачивать незачем совершенно, т.е. разбираться в этом все таки стоит.

**Comment by SM-Sergey** [comment]
Даже более того - ведь известен путь, откуда этот файл был отправлен, и если его надо "открыть" здесь и сейчас, можно сначала посмотреть, есть ли он там, откуда его отправляли, и только если его нет, то скачать.

**Comment by georgehazan** [comment]
насколько я понимаю, в сухом остатке по этому тикету получается задание вопроса на открытие исполняемого файла и отображение отосланных файлов как оффлайновых?

**Comment by georgehazan** [comment]
> автопереименования не будет по политическим причинам,

оно уже есть, примерно с неделю.

> исполняемые файлы тоже разные бывают

исполняемые файлы - это те, чьи расширения перечислены в PATHEXT. 
можно при их загрузке ставить им бит, чтобы при открытии винда задавала вопрос

главный вопрос остался прежним - больше идей нет? всё, что написано выше, уже сделано

**Comment by SM-Sergey** [comment]
> оно уже есть, примерно с неделю.

Простите. Я видимо не обновился еще на это, а коммит такой пропустил. Сейчас обновил, проверим!

>  больше идей нет?

Ну вот "Save As" с диалоговым окном "куда и под каким именем", рядом с "Copy URL" и "Download" в контекстном меню оффлайн-файла. С функциональностью -  скачать файл минуя кеш прямо туда, если он еще не был скачан "в кеш", или скопировать из "кеша", если он там есть. Ну это как бы "запрос фичи". Было бы в некоторых случаях удобнее, чем делать "Download" и потом копировать его руками из папки контакта.

Для любителей подрыгать и поплюхать, можно тоже самое сделать и по дрыгплюху.
