### ISSUE TITLE
ICQ: устаревают ссылки на оффлайновые файлы

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#3579]
В протоколе ICQ через небольшое время устаревают ссылки на оффлайн-файлы, и если не успел их скачать, а миранда была в онлайне, то всё, с концами.

**Comment by SM-Sergey** [comment]
Проблема оказалась более серьезная - время очень небольшое. Файл пришел в 11:36, я отходил от компа. В 11:42 ссылка уже протухла, вместо файла прилетает 404. То есть 6 минут уже хватило для устаревания.

**Comment by SM-Sergey** [comment]
Ничего не исправлено. Сегодня ночью приехал файл, я его не скачал, и версия была еще без автозагрузки. Обновился. Кликаю на файл, результат как и раньше - 404. Кусок нетлога выложен на форуме.

**Comment by georgehazan** [comment]
> Сегодня ночью приехал файл, я его не скачал, и версия была еще без автозагрузки. Обновился. Кликаю на файл, результат как и раньше - 404.

Если висела версия без автозагрузки, как она могла скачать файл ночью? Тестить надо после обновления

**Comment by SM-Sergey** [comment]
Этот баг - совсем не про автозагрузку. 
А про то, если она выключена пользователем, либо по какой то причине не сработала (перебои с интернетом, например) - то оффлайн-файл через некоторое время нельзя открыть. При этом в оф. клиенте таких проблем нет.

**Comment by dartraiden** [comment]
> При этом в оф. клиенте таких проблем нет.

Оф. клиент работает по совсем иному принципу.

**Comment by dartraiden** [comment]
TODO: как-то выяснить, как официальный клиент препарирует файлы, чтобы они не протухали.

**Comment by SM-Sergey** [comment]
Вот-вот, именно про это "TODO" и вся issue создана. У оф. клиента (имею в виду web-icq который) и ссылки на файлы устроены чуток иначе, идут через через "api/v92/files/get/", он же их как-то получает свежие всегда, по-видимому каждый раз с их сервера заново берет, ведь он локальную базу не держит. Хотя это пока лишь предположение.  
А у миранды ссылки идут через /api/v1.1/files/get/

**Comment by SM-Sergey** [comment]
Если быть точнее, то запросить новое инфо о файле (из /files/api/v1.1/info/....) , а уже оттуда выцепить новый "dlink"

**Comment by SM-Sergey** [comment]
Вот. Пока что первое исследование показало следующее:

1. В самом эвенте на сервере хранится "фейковая ссылка c кучей букв" - например "https://files.icq.net/get/kQPaYSegJPOe0NCP0eNJPk64b82c9e1bb"
2. Чтобы получить актуальную ссылку, надо запросить другой сервер с инфой о файле - через ту же "кучу букв" - u.icq.net/files/api/v1.1/info/kQPaYSegJPOe0NCP0eNJPk64b82c9e1bb
3. И вот только в ответ на этот запрос придет текущая действующая ссылка на этот файл - в данном случае "dlink":"https://ub.icq.net/api/v1.1/files/get/kQPaY22Nr3Uw31c0ocD1AcacD1A0vrj14yFiuSqOLg9itSfOpIhWEYsGq27Y01MBf4QImbLubGS4vbnioQd1niHwBX0IboBXQSirSYKG5o89OsCxN2VIIt8h3IzWSkxIKQeX2G4u0NpGzTJcOsOnYcs1nrocD1/Microwave_Coaxial_Conn_Cat030E.pdf"

Всякие там запчасти ссылок с идами сессий и пр. я опускаю, чтобы не засорять, смысл и без них ясен. 

И вот эта последняя ссылка, она недолго живущая, ее нигде хранить смысла нет.  На сколько я понял (могу ошибаться), миранда именно эту, неживущую ссылку в базе сохраняет, а надо не забывать и первую, "фейковую", и при каждом новом обращении к оффлайн файлу заново проходить через п.2., а не лишь один раз, когда евент пришел впервые.

Заодно та же проблема видна и при "Load server history". По ней прилетают на месте оффлайн файлов "фейковые ссылки" типа как в п.1 (так и должно быть!), но алгоритм "Load server history" не декодирует их как файлы, не запрашивает инфо о файле, и соответствуенно ведет себя некорректно, загаживая историю этими фейковыми ссылками.

**Comment by SM-Sergey** [comment]
Дальнейшая окончательная проверка всё это четко подтвердила.

Взял файл 2021 года - это по лоад сервер хистори когда-то давно прилетело, тоже где-то в 2021 еще:

xxxxx, 20.05.2021, 19:55:
https://files.icq.net/get/0ggcc000i2dMjPo713udGh60a694781bb

Запросил вот прям щас руками (не закрывая оф клиент, чтобы его сессия была жива, а кучу букв-цифр подставил из того, что выше, руками. Ну тут апи чуть другое, "v92" вместо "v1.1" - но уверен, что и с "v1.1" как в миранде сейчас, всё сработает.

https://u.icq.net/api/v92/files/info/0ggcc000i2dMjPo713udGh60a694781bb/?aimsid=005.0312840321.1563482791:300659245&previews=192,600,800,xlarge

Получил ответ - вуаля, вот и живая временная ссылка и на сам файл, и на его превьюшки, и мд5, и размер, и имя файла настоящее:

{

      "result": {
            "info": {
                  "has_previews": true,
                  "file_size": 97678,
                  "file_name": "20210520_195458.jpg",
                  "md5": "1c872cfcb4dcf329d70a3aa13e1950d3",
                  "dlink": ["https://ub.icq.net/api/v92/files/get/0ggcc000EXOdPGfrm9cFEWX9mOEWXNd11fCQhkZTiYsH4WmQWalbmMGjsHCGQLkxX41Znpmymxq7mI0yvai8HiKvm9af2omGZmfUisJV1TCEOCNQXhrbjwCoWyCfmVTb7imF3TiGX5iHrLXzYtvLmvWFHvtJzFEWX/20210520_195458.jpg"](https://ub.icq.net/api/v92/files/get/0ggcc000EXOdPGfrm9cFEWX9mOEWXNd11fCQhkZTiYsH4WmQWalbmMGjsHCGQLkxX41Znpmymxq7mI0yvai8HiKvm9af2omGZmfUisJV1TCEOCNQXhrbjwCoWyCfmVTb7imF3TiGX5iHrLXzYtvLmvWFHvtJzFEWX/20210520_195458.jpg),
                  "mime": "image/jpeg",
                  "trustRequired": false,
                  "antivirus": {
                        "check_mode": "async",
                        "check_result": "safe"
                  }
            },
            "extra": {
                  "file_type": "image"
            },
            "previews": {
                  "192": ["https://ub.icq.net/api/v92/files/preview/ttl/192/0ggcc000EXOdPGfrm9cFEWX9mOEWXNd11fCQhkZTiYsH4WmQWalbmMGjsHCGQLkxX41Znpmymxq7mI0yvai8HiKvm9af2omGZmfUisJV1TCEOCNQXhrbjwCoWyCfmVTb7imF3TiGX5iHrLXzYtvLmvWFHvtJzFEWX/"](https://ub.icq.net/api/v92/files/preview/ttl/192/0ggcc000EXOdPGfrm9cFEWX9mOEWXNd11fCQhkZTiYsH4WmQWalbmMGjsHCGQLkxX41Znpmymxq7mI0yvai8HiKvm9af2omGZmfUisJV1TCEOCNQXhrbjwCoWyCfmVTb7imF3TiGX5iHrLXzYtvLmvWFHvtJzFEWX/),
                  "600": ["https://ub.icq.net/api/v92/files/preview/ttl/600/0ggcc000EXOdPGfrm9cFEWX9mOEWXNd11fCQhkZTiYsH4WmQWalbmMGjsHCGQLkxX41Znpmymxq7mI0yvai8HiKvm9af2omGZmfUisJV1TCEOCNQXhrbjwCoWyCfmVTb7imF3TiGX5iHrLXzYtvLmvWFHvtJzFEWX/"](https://ub.icq.net/api/v92/files/preview/ttl/600/0ggcc000EXOdPGfrm9cFEWX9mOEWXNd11fCQhkZTiYsH4WmQWalbmMGjsHCGQLkxX41Znpmymxq7mI0yvai8HiKvm9af2omGZmfUisJV1TCEOCNQXhrbjwCoWyCfmVTb7imF3TiGX5iHrLXzYtvLmvWFHvtJzFEWX/),
                  "800": ["https://ub.icq.net/api/v92/files/preview/ttl/800/0ggcc000EXOdPGfrm9cFEWX9mOEWXNd11fCQhkZTiYsH4WmQWalbmMGjsHCGQLkxX41Znpmymxq7mI0yvai8HiKvm9af2omGZmfUisJV1TCEOCNQXhrbjwCoWyCfmVTb7imF3TiGX5iHrLXzYtvLmvWFHvtJzFEWX/"](https://ub.icq.net/api/v92/files/preview/ttl/800/0ggcc000EXOdPGfrm9cFEWX9mOEWXNd11fCQhkZTiYsH4WmQWalbmMGjsHCGQLkxX41Znpmymxq7mI0yvai8HiKvm9af2omGZmfUisJV1TCEOCNQXhrbjwCoWyCfmVTb7imF3TiGX5iHrLXzYtvLmvWFHvtJzFEWX/),
                  "xlarge": ["https://ub.icq.net/api/v92/files/preview/ttl/xlarge/0ggcc000EXOdPGfrm9cFEWX9mOEWXNd11fCQhkZTiYsH4WmQWalbmMGjsHCGQLkxX41Znpmymxq7mI0yvai8HiKvm9af2omGZmfUisJV1TCEOCNQXhrbjwCoWyCfmVTb7imF3TiGX5iHrLXzYtvLmvWFHvtJzFEWX/"](https://ub.icq.net/api/v92/files/preview/ttl/xlarge/0ggcc000EXOdPGfrm9cFEWX9mOEWXNd11fCQhkZTiYsH4WmQWalbmMGjsHCGQLkxX41Znpmymxq7mI0yvai8HiKvm9af2omGZmfUisJV1TCEOCNQXhrbjwCoWyCfmVTb7imF3TiGX5iHrLXzYtvLmvWFHvtJzFEWX/)
            }
      },
      "status": {
            "code": 20000
      }

}

**Comment by dartraiden** [comment]
Для уже загруженных событий не сработает, нужно перезагрузить историю с сервера и в ней всё будет.

**Comment by SM-Sergey** [comment]
>> нужно перезагрузить историю с сервера и в ней всё будет.

Не будет - там живет свой баг, о котором я уже много раз упоминал - приходящие по загрузки истории оффлайн файлы не декодируются как файлы, а трактуются как "фейковая ссылка" - то есть удаление евента с оффлайн файлом из истории, и затем загрузка истории с сервера, приводит к появлению в истории сообщения с текстовой фейковой ссылкой, а не с оффлайн файлом.

Вообще по хорошему для этого надо отдельный "issue" сделать.
