### ISSUE TITLE
Jabber: HTTP File Upload всё ещё не работает как оффлайновые файлы

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3582]
Мне приходит файл через HTTP File Upload.

Ожидание: для меня это будет оффлайновый файл со скачиванием по клику.

Реальность: файл скачивается сам в  JabberTmp и в лог вставляется конструкция `[img]C:\Users\dartraiden\AppData\Roaming\Miranda NG\home\JabberTmp\dcbde0d09f9cc779cb41d6e97a6face9bc2b9669.png[/img]`

**Comment by dartraiden** [comment]
Вдогонку вопрос: откуда вообще вылез JabberTmp? Может, это изничтожить?

**Comment by georgehazan** [comment]
> Вдогонку вопрос: откуда вообще вылез JabberTmp? Может, это изничтожить?

Это для CID: инлайнинг картинок. Дебильная фича для фанатов вставить картиночку в текст сообщения

> Мне приходит файл через HTTP File Upload.

С ними всё в порядке

**Comment by dartraiden** [comment]
Угу, это был не File Upload, это на том конце чувак включил грёбаный инлайн.
