### ISSUE TITLE
Оффлайновые файлы: не открывать скачанный файл автоматически

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3584]
Сейчас при нажатии на оффлайновый файл он будет скачан и тут же запущен.

Соответственно, если нам прислали исполняемый файл, пакетный файл или скрипт, это может закончится нехорошо.

Предлагаю сделать следующее:
- при клике по файлу он скачивается
- тут же рисуется галочка о том, что файл скачан (сейчас она рисуется при переоткрытии окна, но её нужно рисовать сразу, далее станет понятно почему)
- при клике по файлы с галочкой он открывается

Таким образом, пользователь может в любой момент понять, стоит ли кликать или не стоит.

**Comment by dartraiden** [comment]
Да, а ещё туда же py и кучу всего прочего. А потом мы переедем под линукс, где ещё sh, zsh и тьма всего.

**Comment by mikekaganski** [comment]
Стоит реализовать MOTW.

https://nolongerset.com/mark-of-the-web-details/
https://textslashplain.com/2016/04/04/downloads-and-the-mark-of-the-web/
