### ISSUE TITLE
Оффлайновые файлы: исходящие файлы должны выглядеть как и входящие

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3585]
Для примера см. официальный клиент Telegram. Что входящий, что исходящий файл, механизм одинаков - в журнале виден файл, на него можно нажать.

У нас в Jabber полный разнобой и бардак:
- входящий файл выглядит как оффлайновый файл
- исходящий выглядит как URL

Давай приведём это к единому знаменателю.

**Comment by georgehazan** [comment]
Сделано это для всё той же связки с IEView - тогда в журнал вставляется [img] ссылка [/img], и в журнале инлайнится переданная картинка
