### ISSUE TITLE
Не открываются сетевые ссылки

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3586]
Мне приходит сетевая ссылка вида `\\server\folder\file.txt`
Ссылка кликабельна, но ни по клику, ни при "пкм по ссылке -> открыть ссылку" ничего не происходит.

Можно тестировать у себя так:
- взять 2 машины с виндой
- с одной машины подключиться к другой по RDP (mstsc.exe) в настройках подключения выполнить расшаривание локального диска
- на удалённой машине (к которой подключились) можно открыть диск с локальной машины в Проводнике по ссылке вида `\\tsclient\буквадиска\папка`, например `\\tsclient\D\dev`
- но если в Миранду на удалённой машине кинуть эту ссылку, то ничего не открывается

**Comment by georgehazan** [comment]
Вообще без проблем запускается (в табсах). Надо смотреть, что там с правами
