### ISSUE TITLE
Добавить кнопку отправки файла на тулбар плагинов сообщений

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3588]
Идея с форума.

**Comment by georgehazan** [comment]
а смысл? есть меню протокола, там можно выбрать файл

**Comment by SM-Sergey** [comment]
А это где такое меню? Возможно я просто не знаю каких-то возможностей... 
На данный момент я знаю лишь один способ отправить файл - кликнуть правой кнопкой на контакте в контакт-листе, и там выбрать "File". Но когда в клисте семь экранов контактов, то докрутить до нужного контакта, чтобы найти его среди оффлайновых, не так и просто... А в рабочих моментах надо слать много файлов разным контактам. В добрые старые времена, когда статус оффлайн-онлайн-т.д. работал корректно и управлялся пользователем - было еще более менее, все контакты, с которыми идет общение, были в нужное время онлайн и вверху (при соотв. опции сортировки), и тыкнуть в нужный контакт было без проблем. А в современных реалиях, напрочь испорченных владельцами протоколов - статус онлайна не значит ничего вообще, и контакт прыгает как хочет туда сюда. И даже если отключить сортировку "оффлайны внизу" - все равно сплошная путаница при большом клисте.
Вот поэтому хотелось бы иметь возможность послать файл в текущей открытой сессии сообщений одним тыком, и не в клист, а не отходя от окна сообщений.

**Comment by apollo2k4** [comment]
> а смысл? есть меню протокола, там можно выбрать файл

Не интуитивно для пользователя, в мессенжерах она вообще в окне ввода живёт. При том, что CloudFile добавляет свою иконку, что мешает стандартной отправки файла так делать.

> На данный момент я знаю лишь один способ отправить файл - кликнуть правой кнопкой на контакте в контакт-листе, и там выбрать "File".

Можно кликнут по статусной строке контакта в окне чата и получить такое же меню. Ели если у вас включен тулбар, там есть иконка «Контакт» которая вызовет это же меню.

**Comment by SM-Sergey** [comment]
>  Ели если у вас включен тулбар, там есть иконка «Контакт» которая вызовет это же меню.
О, спасибо. Именно незнание. Я туда всегда пытался только правой кнопкой тыкать. Так да, вполне достаточно в общем.

Но, я бы сказал, что это неявно, так как отправка файла это заурядная задача, зачастую почти наравне с отправкой сообщений по надобности.

**Comment by georgehazan** [comment]
> Не интуитивно для пользователя, в мессенжерах она вообще в окне ввода живёт.

В Миранде пока господствует идеология дрыг-н-плюх файла в окно ввода, которое инициирует трансфер

**Comment by SM-Sergey** [comment]
Но с другой стороны - кнопка вызова истории же есть, например. Она также дублирует меню протокола. При этом, это гораздо более редко нужная вещь, чем отправка файла.
дрыг-н-дроп далеко не все используют, для этого надо еще открыть что-то лишнее, откуда этот файл брать. Например из Far Manager нельзя дрыгнуть файл наружу.

А кстати - есть возможность как-то снаружи достать из миранды контакт лист и пнуть ее на отправку файла контакту? Интересуюсь с целью написать плагин для фара по отправке файла контакту.

**Comment by georgehazan** [comment]
> Но с другой стороны - кнопка вызова истории же есть, например. Она также дублирует меню протокола.

Кнопку истории кладет на тулбар плагин истории.

> дрыг-н-дроп далеко не все используют, для этого надо еще открыть что-то лишнее, откуда этот файл брать. Например из Far Manager нельзя дрыгнуть файл наружу.

При всем уважении к Рошалу и его творению это как бы проблема FAR. Есть стандартный виндовый способ таскания файлов, он в Миранде реализован.

> А кстати - есть возможность как-то снаружи достать из миранды контакт лист и пнуть ее на отправку файла контакту? Интересуюсь с целью написать плагин для фара по отправке файла контакту.

Есть плагин MimCmd, который позволяет из комстроки дернуть несколько команд, в т.ч. получить список контактов

**Comment by SM-Sergey** [comment]
>  Есть стандартный виндовый способ таскания файлов, он в Миранде реализован.

Это хорошо, но не всем удобно, ибо это "один из стандартных" виндовых способов, а не "единственный стандартный", и многие пользователи вообще этим способом не пользуются. Но это риторика.

> Кнопку истории кладет на тулбар плагин истории.

Ну как бы для пользователя это не важно, кто ее туда положил, главное что она там есть. А, собственно, это сложно, туда кнопку положить? Из-за чего весь сыр-бор? Может тогда эту тему закрыть для "ядра", а сделать плагин, который ее туда положит (если так можно), и желающие видеть там кнопку будут спокойны?

**Comment by georgehazan** [comment]
> Это хорошо, но не всем удобно, ибо это "один из стандартных" виндовых способов, а не "единственный стандартный", и многие пользователи вообще этим способом не пользуются.

Могу посоветовать второй стандартный способ - в FAR нажать на файле AppKey -> Copy, а в Миранде - Ctrl+V

> А, собственно, это сложно, туда кнопку положить?

Не очень просто, да, надо в куче мест покопаться.

> а сделать плагин, который ее туда положит (если так можно), и желающие видеть там кнопку будут спокойны?

Мы как раз только что убили StdFile, и восстанавливать его очень не хочется

**Comment by SM-Sergey** [comment]
Ну и аминь.... Ctrl-V это хорошо.  Тоже не знал.
