### ISSUE TITLE
Find/add contacts... Bug with Yahoo-Plugin: finds any name/account, existing or not

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#359]
**Reported by FredAC on 11 Jan 2015 15:48 UTC**
"Wishmaster" told me to put it into the bug tracker, so here we are:

Hi there,

the "Find/add contacts"-Function in Miranda NG has a bug using the yahoo protocol: no matter which Yahoo-ID (existing or not) you type in the search, Miranda shows you an existing account.

This behaviour is not new, in NG it was like this from the first day on, probably even in last versions of Miranda IM (not sure at the moment). But i know, in former times in older versions of Miranda IM, this was working properly.

If you do the same (adding/searching contacts) in other protocols like skypeclassic, facebook,... Miranda seems to "work"/search for a second and then shows you an result (or not, if the ID is not existing). In Yahoo protocol it seems like there is just no search executed, as the account (which is often not existing) is always shown as available within 1 milli-second :-)

Would be fine if you could solve that.

More information and some screenshots you will find at:
http://forum.miranda-ng.org/index.php?topic=3801.msg9774#msg9774

Fred

[Pentium(R) Dual-Core CPU E5800 @ 3.20GHz [x86 Family 6 Model 23 Stepping 10](spoiler=VersionInfo][quote]CPU:) [Enabled](DEP) [CPUs](2)
Installed RAM: 3328 MBytes
Operating System: Microsoft Windows 7 Professional Edition, 32-bit Service Pack 1 (build 7601)
Internet Explorer: 9.11.9600.17501 (build 99600)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : German/German | German/German
Free disk space on Miranda partition: 15259 MBytes

Miranda NG Version: 0.95.3 build #11706
Build time: 1 Jan 2015 1:05:10
Profile: D:\Miranda_Fred\Profiles\Fred\Fred.dat
Profile size: 6356992 Bytes
Profile creation date: 11 Dec 2014 23:03:48
Language pack: No language pack installed
Service Mode: No

[Plugins (27):[/b](b]Active)
  AdvaImg.dll v.[[1 Jan 2015 0:55:24](b]0.11.0.1[/b]) - Miranda image services 
  AIM.dll v.[[1 Jan 2015 0:54:52](b]0.11.0.1[/b]) - AIM protocol 
  AutoRun.dll v.[[1 Jan 2015 1:01:34](b]0.1.0.1[/b]) - AutoRun 
  AVS.dll v.[[1 Jan 2015 0:54:08](b]0.95.3.4[/b]) - Avatar service 
  Contacts.dll v.[[1 Jan 2015 0:55:48](b]1.6.0.0[/b]) - Send/receive contacts 
  CrashDumper.dll v.[[1 Jan 2015 0:59:20](b]0.0.5.2[/b]) - Crash dumper 
  DbChecker.dll v.[[1 Jan 2015 1:00:00](b]0.95.3.1[/b]) - Database checker 
  Dbx_mmap.dll v.[[1 Jan 2015 0:54:16](b]0.95.3.1[/b]) - Miranda NG mmap database driver 
  Facebook.dll v.[[1 Jan 2015 0:57:24](b]0.2.9.9[/b]) - Facebook RM 
  GG.dll v.[[1 Jan 2015 0:54:38](b]0.11.0.3[/b]) - Gadu-Gadu protocol 
  ICQ.dll v.[[1 Jan 2015 0:55:10](b]0.11.2.6[/b]) - IcqOscarJ protocol 
  IEHistory.dll v.[[21 Dec 2014 5:37:58](b]0.0.1.7[/b]) - IEView history viewer 
  IEView.dll v.[[1 Jan 2015 0:56:10](b]1.4.0.2[/b]) - IEView 
  Import.dll v.[[1 Jan 2015 0:54:08](b]0.95.3.4[/b]) - Import contacts and messages 
  IRC.dll v.[[1 Jan 2015 0:54:50](b]0.11.0.2[/b]) - IRC protocol 
  Jabber.dll v.[[1 Jan 2015 0:55:16](b]0.11.0.4[/b]) - Jabber protocol 
  MSN.dll v.[[1 Jan 2015 0:55:24](b]0.11.1.2[/b]) - MSN protocol 
  PluginUpdater.dll v.[[1 Jan 2015 1:00:10](b]0.1.2.4[/b]) - Plugin updater 
  SimpleStatusMsg.dll v.[[1 Jan 2015 0:57:42](b]1.9.0.4[/b]) - Simple status message 
  SkypeClassic.dll v.[[1 Jan 2015 1:03:46](b]0.0.0.55[/b]) - Skype protocol (Classic) 
  SmileyAdd.dll v.[[1 Jan 2015 0:56:42](b]0.2.3.17[/b]) - SmileyAdd 
  StartupStatus.dll v.[[1 Jan 2015 0:56:56](b]0.8.0.47[/b]) - StartupStatus 
  TabSRMM.dll v.[[1 Jan 2015 0:54:36](b]3.4.0.7[/b]) - TabSRMM 
  TopToolBar.dll v.[[1 Jan 2015 0:57:56](b]0.8.0.4[/b]) - TopToolBar 
  Twitter.dll v.[[1 Jan 2015 0:58:26](b]1.1.0.3[/b]) - Twitter protocol 
  WhatsApp.dll v.[[21 Dec 2014 5:38:20](b]0.1.0.5[/b]) - WhatsApp Protocol 
  Yahoo.dll v.[[1 Jan 2015 0:54:56](b]0.11.0.1[/b]) - Yahoo protocol 

[and Accounts:[/b](b]Protocols)
-------------------------------------------------------------------------------
AIM                      0 - Enabled 0 - Disabled  Loaded
Facebook                 1 - Enabled 0 - Disabled  Loaded
GG                       0 - Enabled 0 - Disabled  Loaded
ICQ                      1 - Enabled 0 - Disabled  Loaded
IRC                      0 - Enabled 0 - Disabled  Loaded
JABBER                   0 - Enabled 0 - Disabled  Loaded
MSN                      0 - Enabled 0 - Disabled  Loaded
SkypeClassic             1 - Enabled 0 - Disabled  Loaded
Twitter                  0 - Enabled 0 - Disabled  Loaded
WhatsApp                 1 - Enabled 0 - Disabled  Loaded
YAHOO                    1 - Enabled 0 - Disabled  Loaded
MetaContacts             1 - Enabled 0 - Disabled  Loaded

[Packs:[/b](b]Icon)
-------------------------------------------------------------------------------
 HistoryPP_icons.dll [Jan 2015 1:00:28](1)
 Proto_AIM.dll [Jan 2015 0:57:58](1)
 Proto_Facebook.dll [Jan 2015 0:57:54](1)
 Proto_GG.dll [Jan 2015 0:57:58](1)
 Proto_ICQ.dll [Jan 2015 0:57:58](1)
 Proto_IRC.dll [Jan 2015 0:57:58](1)
 Proto_Jabber.dll [Jan 2015 0:58:00](1)
 Proto_MetaContacts.dll [Jan 2015 1:04:08](1)
 Proto_MSN.dll [Jan 2015 0:58:00](1)
 Proto_Skype.dll [Jul 2014 19:56:58](6)
 Proto_Twitter.dll [Jan 2015 0:57:58](1)
 Proto_WhatsApp.dll [Dec 2014 5:38:08](21)
 Proto_Yahoo.dll [Jan 2015 0:58:00](1)
 TabSRMM_icons.dll [Jan 2015 1:00:28](1)
 Toolbar_icons.dll [Jan 2015 0:58:02](1)
 xstatus_icons.dll [Jul 2006 0:09:06](18)
 xStatus_ICQ.dll [Jan 2015 0:55:26](1)
 xStatus_Jabber.dll [Jan 2015 0:55:26](1)
[/quote][/spoiler]

**Comment by aunsane** [comment]
Yahoo protocol was depricated b0f3e30460fc26ef4fe59bc161b0fddd8eeb9a08.
