### ISSUE TITLE
Clist_nicer: не работает кнопка "Убрать скин"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3590]
Кнопка ничего не делает

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/251cd600-7f71-4694-91ed-e1b5915496d9)

**Comment by georgehazan** [comment]
на самом деле, если присмотреться к уголкам групп, видно, что иконки из скина исчезают, также меняется заливка. Беда в том, что все настройки цветов и шрифтов из скина переписываются в профиль, поэтому внешне изменения при убирании скина малозаметны
