### ISSUE TITLE
ICQ: если ссылка на файл протухла, но файл был скачан, его нельзя открыть

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3592]
`в icq ссылка на оффлайн файл на следующий день уже "404"..... но не смотря на то, что файл был скачан и лежит в  %miranda_userdata%\dlFiles\%uid%\ по клику ничего не происходит, так как не проверяется его локальноеналичие, а ссылка на файл на сервере уже протухла`

**Comment by georgehazan** [comment]
конечно же проверяется. если файл есть в кэше и его длина совпадает с заданной, то он открывается сразу

**Comment by SM-Sergey** [comment]
Это не работает. Сейчас проверил - аж четыре раза кликнул на один и тот же тестово пришедший файл (ICQ) - по нетлогу он каждый раз грузится заново, да и по времени открытия понятно, что это не открытие из места, куда он был раньше загружен.

**Comment by SM-Sergey** [comment]
Но на самом деле сформулировано тут не совсем корректно. 
Во первых, ссылки вчера протухать перестали, и новые "приходы" файлов теперь долгоиграющие - вроде это работает, по нетлогу каждый раз миранда лезет за свежим file/info. Но есть старые пришедшие нескачанные файлы, они как были протухшими, так и остались. Видимо в базе для них ссылка не той системы хранится, не первичная "фейковая", а временная (это догадка) - при обращении к ним миранда лезет за file/info по какой-то кривейшей ссылке и получает законные 404. Но это и ладно, таких немного, и, надеюсь, их можно будет обновить, если Load Server History заработает.

Во вторых, непосредственно по этой теме:
 - при клике во встроенном журнале табсрмм - файл всегда грузится, проверка наличия файла не работает. И это не зависит от того, протухшая там ссылка, или новая - просто проверка наличия файла не работает, файл, если ссылка протухла, но он был раньше скачан - не открывается, а если ссылка не протухла - грузится заново и открывается.
- при клике в ньюхистори - строго наоборот - все уже загруженное отлично открывается из локального хранилища, но зато не грузится не загруженное.

то есть эта бага зависит от того, что испольуется в качестве журнала/истории.

**Comment by georgehazan** [comment]
Про NewStrory есть отдельный тикет

**Comment by SM-Sergey** [comment]
Ну про ньюстори это ладно. Я просто упомянул, что она стала юзабельна с автозагрузкой, и при этом ведет себя красиво и хорошо. Фиг с ней, с ньюстори.

А вот табсрмм так и не заработал. По прежнему каждый клик на оффлайн файл делает его новую загрузку (по нетлогу), несмотря на то, что он уже лежит в положенном месте. При этом Load Server History вроде заработал.
