### ISSUE TITLE
ICQ: Load Server History: оффлайн файлы трактуются как сообщения

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#3594]
Если удалить из истории запись с оффлайн-файлом, и сделать "Load Server History", то появится сообщение с "фейковой ссылкой", но не оффлайн файл. Если из истории запись с файлом не удалять, то такое сообщение добавится сразу после записи с файлом.

**Comment by georgehazan** [comment]
они и есть сообщения. ссылку поправил
