### ISSUE TITLE
Странное поведение при редактировании профиля в XMPP

### ISSUE THREAD

**Issue by apollo2k4** [miranda-ng/miranda-ng#3595]
Если попробовать отредактировать несколько пунктов в своих данных в «Личные данные…» → jabbername → «Общее», при нажатии на ОК применяется только последнее редактированное поле.

**Comment by georgehazan** [comment]
Не подтверждаю. Давай делать нетворк лог + скриншот, на котором было бы указано, какие поля изменились. Плюс еще вопрос - UInfoEx стоит?

**Comment by apollo2k4** [comment]
Пока не могу повторить.
