### ISSUE TITLE
ICQ: "Copy URL" в контекстном меню журнала/истории на оффлайн файле отдает бессмысленную ссылку

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#3596]
Это нельзя назвать багом - по "Copy URL" (как минимум - журнал tabsrmm) копируется "фейковая ссылка" на файл, как она пришла с сервера, и это в общем-то понятно и честно. Только вот обычному пользователю от нее толку ноль.
Логично было бы запросить file/info с сервера по факту клика на такое меню, и в клипборд поместить свежую живую ссылку.

**Comment by SM-Sergey** [comment]
Интересно, когда? Прямо сейчас подтянул все апдейты, сделал Copy URL на файле, и получил https://files.icq.net/get/0fukE000n21dwJFFW3S7Go6542b9801bb

**Comment by SM-Sergey** [comment]
Насколько я понимаю, это не тривиальная задача - запрос на копирование ссылки надо отправлять в протокол, а уже он должен решать, как это делать.

**Comment by georgehazan** [comment]
Оно немного выкосилось в процессе оптимизации. Вернул
