### ISSUE TITLE
Непоятным образом выскакивают проблемы отправки сообщений, даже если ничего не отправлять (tabsrmm?).

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#3600]
Точно описать баг не могу, но случайным образом в tabsrmm появляются ошибки отправки сообщений с Retry/Cancel/Send later. При этом бывает достаточно просто открыть окно и начать писать новое сообщение. Или если окно откроется само по приему входящего сообщения. Если нажать Cancel, то всё равно потом при закрытии окна сообщений будет диалоговое окно с уведомлением, что есть неотправленное сообщение, и оно может быть потеряно. Если окно закрыть, потом выскочит и уведомление об ошибке отправки.
Баг непонятен и нестабилен, четких критериев для его повтора мне пока не удалось выявить. Но очень часто это происходит. У меня это на протоколе ICQ, но с форума есть данные о VK и Skype, то есть от протокола это вряд ли зависит. Появилось буквально на днях, но точно на каком обновлении, не могу сказать.

**Comment by dartraiden** [comment]
Jabber у меня тоже.

**Comment by dartraiden** [comment]
Для начала надо пробовать отключить в табсах отправку событий о наборе текста и посмотреть, пропадёт ли баг.

**Comment by SM-Sergey** [comment]
>  отключить в табсах отправку событий 

попробовал, но я не знаю как ее отключить в табсах, я ее отключил в Options->Message sessions -> Typing notify для контакта "ICQ official", сняв там галку на этом контакте. Затем даже перезапстил мир. Не помогло - при открытии окна сообщений для "ICQ official" и наборе там текста без отправки выскочило.

**Comment by SM-Sergey** [comment]
Упс. Одновременно вышло с исправлением :)
