### ISSUE TITLE
Русский языковой пакет: не хватает одной строки

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3609]
https://github.com/miranda-ng/miranda-ng/commit/a6137a56ef842f439e1c1a2a26bb6caec1ab69d7#diff-1cc9a2a0491bb1a71562398feb5c882807736994fae2a7f881795d776a61f674

Эта строка по какой-то причине не попадает в langpack_russian.txt

**Comment by georgehazan** [comment]
готово
