### ISSUE TITLE
NewStory: зациклить поиск

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3610]
Сейчас при достижении конца истории Enter не делает ничего.

Предлагаю сделать поиск зацикленным. Или, хотя бы, сделать опцию.

**Comment by apollo2k4** [comment]
Немного не так, поведение по умолчанию – открываешь историю (по умолчанию последнее сообщение на экране) → Поиск → Запрос → Энтер (в молоко), и только потом вспоминаешь, что нужно жать «поиск вверх»

**Comment by georgehazan** [comment]
Он и есть зацикленный, прямо здесь и сейчас
