### ISSUE TITLE
NewStory: сделать дефолтные настройки шрифта идентичными H++

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3615]
Например, у H++ везде используется Tahoma 8, где-то обычная, где-то полужирная.

NewStory использует Segoe UI 9.

**Comment by georgehazan** [comment]
И это хорошо, что используется новый шрифт, где есть эмодзи, например.
В трахоме мало того, что нет эмодзи, так там еще и только европейские языки

**Comment by apollo2k4** [comment]
Так может таскать с собой какой нибудь FiraCode или Roboto чтобы было всё в комплекте или сделать возможность выбора не только зарегистрированных в системе шрифтов, а допустим смотреть ещё в папку fonts в папке профиля или корня миранды
