### ISSUE TITLE
NewStory: выделенный текст имеет какой-то фон, который не настраивается

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3617]
<img width="503" alt="Miranda64_6bpUzcoRaF" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/4d1a17bd-cc92-4425-8d22-d8fe03b78a32">

<img width="438" alt="Miranda64_JcjOGCum1R" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/4a885d49-1e8e-421a-a0a9-65e41823cafd">

Мы имеем:
- выделенный текст: красный = ок
- фон выделения: синий = ок (это вот эта вся синяя строка от края до края)
- граница выделения: белая = ок (трудно заметить, это такая белая полоска понизу синего фона)

Баг: отсутствует настройка вон того светло-голубого фона позади букв. Это не фон выделения (он синий).

**Comment by dartraiden** [comment]
Кроме того, если поставить фон сетки зеленым, то при открытии привата на миллисекунду весь журнал заливает зеленым.

**Comment by georgehazan** [comment]
винда сама выбирает фон активного контрола для ввода текста, исходя из текущей темы винды.
мы нигде не рисуем этот фон самостоятельно
