### ISSUE TITLE
NewStory: прокрутка скроллбаром переходит от сообщения к сообщению вместо прокручивания содержимого окна

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3618]
Не знаю, как это сформулировать, покажу на примере.

Вот так работает прокрутка во всех журналах, когда хватаешь мышью скроллбар и двигаешь его - сразу прокручивается ВСЁ содержимое окна. Причём, если на момент начала прокрутки не выделено ни одно сообщения, то выделение и не появляется:

![mstsc_6ySmhsoKGi](https://github.com/miranda-ng/miranda-ng/assets/5046855/13c8da8b-b207-477d-907b-bef05c437df1)

А вот так работает прокрутка скроллбаром в NewStory - во-первых, сразу возникает выделение где-то посередине, во-вторых, выделение перескакивает с сообщения на сообщение, и только когда оно дойдёт до края окна, журнал соизволит прокручиваться

![Miranda64_MrZESRP4ar](https://github.com/miranda-ng/miranda-ng/assets/5046855/d4cb44b3-8f83-4914-9897-60606e746892)

**Comment by SM-Sergey** [comment]
И еще в третьих - нажатием стрелочки вверх при нахождении выделения вверху все работает как надо - по одному сообщению крутит. Нормально. А нажатием стрелочки вниз, когда выделение внизу - как PgDn - сразу на пачку.
И в четвертых, стрелочкой если крутить вниз, пока выделение не "уперлось" - выделение может уйти вниз за пределы окна, если там находится не целое сообщение, даже хотя-бы лишь пара пикселей видна в окне.
ИМХО: При заходе вниз на нецелое сообщение оно должно выходить вверх так, чтобы стало целым; И далее работать также, как и при стрелочке вверх.
