### ISSUE TITLE
NewStory: размер значков в журнале

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3619]
Какие-то они милипиздрические...
Я бы, может, и пользовался ими, не переназначая их, но они реально крохотные.

Речь про значки перед сообшениями (сообщение, файл, входящее, исходящее)

Кроме того, попробуй поставить закладку в журнале (пкм по сообщению - toggle bookmark) появляется звездочка, которая практически наползает на ник

**Comment by georgehazan** [comment]
а зачем их делать большими? на них нажимать не надо, они чисто для украшения
