### ISSUE TITLE
Скрывать настройки шрифтов и цветов встроенного журнала плагина сообщений, если в качестве журнала выбран сторонний журнал

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3625]
На примере: стоят табсы. Пользователь ставит NewStory и выбирает его журналом для приватов и чатов. Соответственно, встроенный журнал табсов уже не используется.

В настройке шрифтов и цветов получается форменная путаница:

<img width="503" alt="Miranda64_I9JLwdUWyP" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/13b130e5-391e-4473-b389-0be271508c0a">

У нас по-прежнему доступна настройка цветов Single Messaging и Group chats. Но это настройки встроенного журнала, о чём пользователю никто не сообщает. Настраивать теперь надо в разделе NewStory.

Будь я новичком, то рассуждал бы так: вон, написано "Message sesions" -> "Single Messaging" и "Group chats", наверное там и надо настраивать цвета, а не в соверщенно отдельном разделе NewStory.

Предлагаю сделать следующее:
1) "Messaging sesions", возможно, переименовать в "Message plugin" (необязательно)
2) Если установлен **И** выбран в качестве журнала сторонний журнал, скрывать опции, относящиеся к цветам встроенного журнала в приватах. Например, в табсах это раздел  цветов "Single Messaging"
3) Если вдобавок ещё сторонний журнал выбран не только для приватов, но также и для чатов, то скрывать опции, относящиеся к цветам встроенного журнала в групчатах. апример, в табсах это раздел  цветов Group chats

Аналогично сделать в скривере и stdmsg.

**Comment by georgehazan** [comment]
в табсах используется сквозной массив цветов и шрифтов для всех элементов, в том числе для раскрашивания контейнера и инфопанели, поэтому выкинуты только настройки собственно журнала
