### ISSUE TITLE
NewStory: автопрокрутка журнала при открытии новой вкладки в фоне

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3628]
- открыто окно табсов, диалог с контактом, журнал прокручен до самой актуальной реплики
- мне пишет другой контакт, табсы создают в этом же окне фоновую вкладку для этого другого контакта
- в активной вкладке журнал автоматически прокручивается на 1 реплику вверх

**Comment by georgehazan** [comment]
не совсем так, точнее, совсем не так. при появлении второй вкладки врубается заголовок табов и откусывает одну строчку от размера окна лога, оно и ресайзится, отрезая кусочек снизу ( показ ведется от первого находящегося на странице сообщения).

**Comment by dartraiden** [comment]
Я понимаю, но нужно возвращать фокус обратно. Например, встроенный журнал табсов в такой ситуации дёргается, но откручивается взад.

![Miranda64_BYkemccvJc](https://github.com/miranda-ng/miranda-ng/assets/5046855/270a9267-9eb7-4e8c-ba08-71b9067a0c68)

**Comment by dartraiden** [comment]
Предлагаю подумать над убиранием этого дёрганья. Например, встроенный журнал табсов вообще не двигается в такой ситуации.

**Comment by georgehazan** [comment]
блин, не перерисовывается - плохо, перерисовывается при изменении размера - тоже плохо 
надо определиться, что хуже
