### ISSUE TITLE
Настройки уведомлений о наборе текста

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3635]
<img width="503" alt="Miranda64_C3SI7mR4Sq" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/9f934be3-e630-48e2-b0b4-6d29ebde5bb9">

Выделенные галки определяют то, показывать соответствующий попап или нет. А поля правее (фон / текст) определяют цвет.

Но галки-то находятся в блоке "Цвета". Это не очень логично.

Предлагаю сделать так:
1) галки отсюда убрать
2) ...и перенести их в "События"

<img width="503" alt="Miranda64_FCl1BGV5o4" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/1207f571-184f-4fbe-8835-5f1812b43ed8">

Т.е. заменить галку "уведомления о наборе текста" на две галки "уведомления о начале набора" и "уведомления о конце набора".

Это логичнее и проще, чем текущая схема, когда сначала нужно в событиях включить уведомления о наборе, а затем в Цветах ещё и включить уведомления о начале / конце набора.

**Comment by georgehazan** [comment]
Если бы не настройка "один попап на контакт", я бы согласился.
А так имхо проще назвать групбокс Popups (всплываюшие окна)
