### ISSUE TITLE
NewStory: удаление самого нового сообщения оставляет дырку

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3637]
Удаляем самое новое (крайнее в списке) сообщение. Вместо него остаётся пустота. Если теперь нажать стрелку вверх или стрелку вниз, то журнал подкрутится и заполнит пустоту.

Предлагаю делать это автоматически, ведь природа не терпит пустоты.

**Comment by georgehazan** [comment]
на самом деле удаление любого сообщения оставляло дырку
