### ISSUE TITLE
Имя метаконтакта не обновляется

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3639]
Пока не особо понимаю, как воспроизводить баг, но он иногда проявляется.

Есть метаконтакт, состоящий из аськи `George Hazan` и жаббера `ghazan`. Жаббер в мете назначен главным. Вывожу жаббер в оффлайн и выключаю миранду,

Запускаю Миранду, Status Manager восстанавливает статусы, бывшие при выходе. Соответственно субконтакт `George Hazan` онлайн, а `ghazan` не в онлайне. Имя меты получается по имени аськи, т.к. жаббер хоть и главный, но не в сети.

Затем минут через 10-15 руками вывожу жаббер в онлайн.

Ожидаемое поведение: имя меты должно поменяться на имя жаббера, т.к. он главный и он теперь в онлайне.
Реальность: у меты остаётся имя аськи до тех пор, пока субконтакт жаббера что-то мне не напишет.

**Comment by georgehazan** [comment]
Я это в личке комментировал, перенесу сюда. Есть такое понятие - текущий саб в сессии, который использует в основном SRMM, чтобы отсылать сообщение в самый активный саб. Переключается он входящим или исходящим сообщением, и настройки самого метаконтакта на это никак не влияют. При этом в клисте, видимо, используется именно он
