### ISSUE TITLE
Message window pops up when somebody is messaging me

### ISSUE THREAD

**Issue by OvalMedia** [miranda-ng/miranda-ng#3640]
A couple of versions ago there was a new feature that when somebody is writing me the message window just pops up and steals the focus. This is very annoying when I am doing stuff like entering a password somewhere for instance.
How can I turn this attention grabber off? 

Thank you

**Comment by dartraiden** [comment]
Post [url=https://wiki.miranda-ng.org/index.php?title=Version_information]version info[/url] please.

**Comment by OvalMedia** [comment]
v0.96.3 build #25684 (e313c689e1) x64

**Comment by OvalMedia** [comment]
[spoiler=VersionInfo][quote]CPU: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz [Intel64 Family 6 Model 158 Stepping 9] [DEP Enabled] [4 CPUs]
Installed RAM: 16344 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 19045)
Internet Explorer: 9.11.19041.0 (build 919041)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : German/German | German/German
Free disk space on Miranda partition: 40412 MBytes

Miranda NG Version: 0.96.3 build #25684 (e313c689e1) x64
Build time: 13 Jun 2023 18:24:12
Profile: C:\Users\{USERNAME}\AppData\Roaming\Miranda NG\x\x.dat
Database driver: SQLite database driver
Profile size: 3907584 Bytes
Profile creation date: 28 Dec 2018 15:56:54
Language pack: German (DE) [0407]
Service Mode: No
SRMM Log Viewer: built-in

[b]Active Plugins (16):[/b]
¤ AVS.dll v.[b]0.98.1.6[/b] [10 Jun 2023 13:58:06] - Avatar service 
¤ Clist_modern.dll v.[b]0.9.1.12[/b] [10 Jun 2023 13:59:08] - Modern contact list 
¤ CrashDumper.dll v.[b]0.2.0.1[/b] [10 Jun 2023 13:58:58] - Crash dumper 
¤ Db_autobackups.dll v.[b]0.1.0.7[/b] [13 Jun 2023 18:24:30] - Db autobackuper 
¤ DbChecker.dll v.[b]0.96.3.1[/b] [13 Jun 2023 18:27:08] - Database checker 
¤ Dbx_mdbx.dll v.[b]0.95.9.1[/b] [10 Jun 2023 14:05:10] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.[b]0.95.8.1[/b] [10 Jun 2023 13:58:00] - Miranda NG mmap database driver 
¤ Dbx_sqlite.dll v.[b]0.96.2.4[/b] [13 Jun 2023 18:27:02] - Miranda NG SQLite database driver 
¤ Dummy.dll v.[b]0.2.0.1[/b] [13 Jun 2023 18:26:26] - Dummy protocol 
¤ Import.dll v.[b]0.96.3.1[/b] [13 Jun 2023 18:24:58] - Import contacts and messages 
¤ Jabber.dll v.[b]0.95.11.1[/b] [13 Jun 2023 18:25:16] - Jabber protocol 
¤ NewEventNotify.dll v.[b]0.2.2.7[/b] [10 Jun 2023 13:58:52] - NewEventNotify 
¤ PluginUpdater.dll v.[b]0.2.1.5[/b] [10 Jun 2023 13:59:12] - Plugin updater 
¤ TabSRMM.dll v.[b]3.6.2.6[/b] [10 Jun 2023 13:58:18] - TabSRMM 
¤ TopToolBar.dll v.[b]0.8.0.5[/b] [10 Jun 2023 13:58:44] - TopToolBar 
¤ VoiceService.dll v.[b]0.1.3.1[/b] [13 Jun 2023 18:27:14] - Voice Service 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
JABBER                   1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 Proto_Dummy.dll [13 Jun 2023 18:31:00]
 Proto_Jabber.dll [13 Jun 2023 18:30:58]
 Proto_MetaContacts.dll [13 Jun 2023 18:31:00]
 TabSRMM_icons.dll [10 Jun 2023 14:05:14]
 Toolbar_icons.dll [10 Jun 2023 14:05:12]
 xStatus_Jabber.dll [13 Jun 2023 18:30:58]
[/quote][/spoiler]

**Comment by georgehazan** [comment]
that's not a new feature, it existed in tabSRMM from the very beginning
options - message sessions - tabs & layout - automatically create window blablabla

**Comment by dartraiden** [comment]
> TabSRMM

Options → Message sessions → Tabs and Layout → How to create tabs and windows for incoming messages

**Comment by OvalMedia** [comment]
Thank you. It might have been there from the beginning but it automatically (or accidentally?) activated after some update in the past.
