### ISSUE TITLE
Facebook protocol can't login

### ISSUE THREAD

**Issue by tyrylu** [miranda-ng/miranda-ng#3648]
### Expected behavior
The Facebook protocol works

### Actual behavior
The protocol login procedure fails, without any visible error.

### Does it work in stable version?
Nope, almost seems as a Facebook side change.

### Steps to reproduce that behavior
Just try to login to Facebook.
Relevant versions: Miranda NG Version: 0.96.3, Facebook.dll v.0.1.0.11.
Attached is a Facebook netlog where it happens. It is weird that the connection just closes after TLS negotiation and even data logging is of course enabled, nothing is logged. If it'd help, I can try to do a packet capture.
[netlog.txt](https://github.com/miranda-ng/miranda-ng/files/12387664/netlog.txt)

**Comment by georgehazan** [comment]
@tyrylu  Miranda simply cannot establish SSL connection with Facebook. It might be caused by several reasons:
- your admin blocked access to Facebook
- time on your PC is wrong, so SSL certificate became invalid etc

**Comment by tyrylu** [comment]
Alright, it was just a case of a weird cange or not of a Facebook password, e. g. I got a suspicious activity warning last week or so, but a password change was not required, but the old password was getting a 401 from the API, but no error dialogs from Miranda, and a manual password change fixed it, we'll see for how long.

**Comment by dartraiden** [comment]
This is a known issue when Facebook, upon noticing suspicious activity, stops working via API with an old password.

**Comment by tyrylu** [comment]
Well, this one was different, it did not require a password change for me, but the password did not work on, for example, messenger.com, so it was somewhat weird.
