### ISSUE TITLE
Impossibility to use EM-LAN contact as part of metacontact

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#365]
**Reported by Servantik on 23 Jan 2015 08:31 UTC**
While adding EM-LAN contact to metacontact I receive the message
"Не могу получить уникальный ID контакта".

**Comment by georgehazan** [comment]
**Comment by wishmaster on 23 Jan 2015 22:14 UTC**
Should be fixed in [11896], please test

**Comment by georgehazan** [comment]
**Comment by Servantik on 26 Jan 2015 14:56 UTC**
Replying to [wishmaster](comment:1):
> Should be fixed in [11896], please test


Ok. First time, before I create metacontacts with EM-LAN, all was OK. But after I create ICQ+EM-LAN metacontacts and restart Miranda - it crashes at startup (:. I use x64-bit Miranda NG. And try to use 0.95.3 and 0.95.4 versions.

**Comment by georgehazan** [comment]
**Comment by wishmaster on 26 Jan 2015 16:57 UTC**
Strange, I even fixed a possible crash with x64 builds. Could you post a crash report as described [here](http://wiki.miranda-ng.org/index.php?title=Crash_reports)?

**Comment by georgehazan** [comment]
**Comment by Servantik on 27 Jan 2015 07:05 UTC**
Replying to [wishmaster](comment:3):
> Strange, I even fixed a possible crash with x64 builds. Could you post a crash report as described [here](http://wiki.miranda-ng.org/index.php?title=Crash_reports)?

OK. I add 2 attachments - crash20150127100044.txt, crash20150127100044.mdmp

**Comment by georgehazan** [comment]
**Comment by wishmaster on 27 Jan 2015 09:10 UTC**
This is not useful. Please read the article again, especially this:
>If you have PluginUpdater installed you can download the latest development version of plugins and the appropriate debug symbols automatically.
>Go to Options  Services  Plugin Updater  "Files source"
>Select Development version with debug symbols option and click OK.
>Choose Check for updates from the Main menu, click Update and wait till Miranda asks for restart.

**Comment by georgehazan** [comment]
**Comment by Servantik on 27 Jan 2015 11:58 UTC**
Sorry. I had understood this instruction incorrectly at first time. What will be now?

crash20150127145237.txt
crash20150127145237.mdmp

**Comment by georgehazan** [comment]
**Comment by wishmaster on 27 Jan 2015 20:38 UTC**
I tried to fix it in [11931], let me know if it helped.

**Comment by georgehazan** [comment]
**Comment by Servantik on 28 Jan 2015 08:01 UTC**
It seems, that it helped ). Thank You!!!

**Comment by georgehazan** [comment]
**Comment by Servantik on 2 Feb 2015 09:26 UTC**
But now other EM-LAN users don't see Cyrillic letters in my messages.

**Comment by dartraiden** [comment]
**Changed 2 years ago by wishmaster**
Do you mean in general or only when you send messages to a metacontact?

**comment:11 follow-up: ↓ 12 Changed 2 years ago by Servantik**
Only when I send messages to metacontact (I had grouped all my EM-LAN users to metacontacts, so I didn't notice this before).
