### ISSUE TITLE
NewStory: упоротая прокрутка

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3651]
> deadsend, 22.08.2023, 17:30:
> - Упоротая прокрутка. Не плавлая по пикселям, а по сообщениям, которые все разной высоты. UX ужасен

**Comment by georgehazan** [comment]
ну мы в общем=то так и планировали, чтобы не переписывать вообще всё

**Comment by dartraiden** [comment]
Надо, хотя бы, сделать, чтобы прокрутка вела себя во всех аспектах как в H++

**Comment by georgehazan** [comment]
в H++ прокрутка колесом идет по пикселям, у нас это невозможно
