### ISSUE TITLE
NewStory: копирование сгруппированных сообщений

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3654]
Вот так сгруппированные выглядят во **встроенном журнале табсов**

<img width="296" alt="Miranda64_1ZMFNIMRfM" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/d9ecf494-d7d4-4322-b5c8-76a5e78264eb">

И вот так они копируются

```
   ghazan,  Сегодня
[17:46]	в чатах не пашет совсем
[17:46]	потому что группирует по контакту, а там никаких контактов нет
[17:46]	не знаю пока, что с этим делать
```

Т.е. WYSIWYG - как видишь глазами в журнале, так и будет скопировано (дата лишь у первого в группе, у остальных время)

NewStory: сгруппированные выглядят как и в табсах - дата у первого, у остальных только время

<img width="307" alt="Miranda64_eJ088MMcj8" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/486add4e-2b01-4b4b-ade8-950e2005aea2">

Но при копировании получается дата у каждого

```
ghazan, 22.08.2023, 17:46:
в чатах не пашет совсем
ghazan, 22.08.2023, 17:46:
потому что группирует по контакту, а там никаких контактов нет
ghazan, 22.08.2023, 17:46:
не знаю пока, что с этим делать

```

**Comment by georgehazan** [comment]
А это как шаблон для копирования настроишь - так и будет
