### ISSUE TITLE
NewStory: снятие выделения

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3657]
Пора решить, когда у нас будет сниматься выделение с выделенных сообщений.

Сейчас оно не снимается в приватах никак, а в групчатах снимается при отправке сообщения.

**Comment by georgehazan** [comment]
Пора. Что будем делать?

**Comment by dartraiden** [comment]
Предлагаю снимать выделение при клике в поле ввода. Как в History++

**Comment by dartraiden** [comment]
Насчёт "в истории выделение не снимать". Надо придумать какой-то способ.

Кейс: я кликнул по сообщению в истории, а затем решил, что хочу экспортировать её всю целиком. Сейчас для этого придётся переоткрывать окно, т.к. иначе экспортируется лишь то, что выделено, а способа снять выделение нет.
