### ISSUE TITLE
NewStory: цвет ссылок

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3660]
Я сделал фон выделения в настройках таким же, какой у выделения в Windows во всех приложениях. Синий такой.

<img width="503" alt="Miranda64_2PCcij1CSX" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/355f61ed-3228-4458-a50e-8022559d84e5">

Теперь выделяю сообщение со ссылкой:

<img width="329" alt="Miranda64_xx7ta6mtXb" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/ce3a7e3b-4770-4f75-aae4-bb5a5ef9745e">

Получается фигня: синяя ссылка на синем фоне. Её едва можно разглядеть.

При этом, если начать редактирование сообщение, винда умная, винда делает ссылку белой.

**Предлагаю реализовать такую же опцию, как в History++: настройка цвета ссылки.** Тогда я смог бы сделать ссылки не голубыми, и они при выделении смотрелись бы лучше.

**Comment by georgehazan** [comment]
даже в обычном richedit управление цветом ссылок - это нереально сложно, а тут, когда нет контрола richedit, и вовсе непонятно, как это контролировать.

**Comment by dartraiden** [comment]
После перехода на litehtml можно вернуться к этому вопросу.
