### ISSUE TITLE
tabSRMM: всплывающие уведомления о наборе текста при получении оффлайнового сообщения

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3661]
В миранде включены всплывающие окна о наборе контактом текста и об окончании набора.

Я включаю Миранду и мне в жаббер прилетает сообщение, которое мне прислали, пока я был оффлайн.

Вылезают два попапа: "контакт закончил набирать текст" и "сообщение". Первый попап, мне кажется, ошибочен. Сообщение контакт отправил несколько часов назад, он уже ничего не набирает.

**Comment by georgehazan** [comment]
сделай нетворк лог, если сможешь
