### ISSUE TITLE
NewStory: сломано редактирование

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3664]
После недавнего коммита про снятие выделения в журнале сломалось редактирование.

Раньше: двойной клик в журнале и истории приводил ко входу в режим редактирования

Теперь: двойной клик в журнале выделяет и тут же снимает выделение, а в истории вообще ничего не делает.

**Comment by dartraiden** [comment]
Теперь в режим редактирования по двойному клику входит. Но редактировать текст нельзя, нет реакции на нажатия клавши.

**Comment by georgehazan** [comment]
Потому что три года назад было сделано так, что двойной клик открывает мемо-поле в режиме только для чтения, а F2 и нажатие Edit в контекстном меню - полностью
