### ISSUE TITLE
NewStory: ссылка вставляется некликабельной

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3665]
1) Очищаем историю нашей тестовой Jabber-конфы в базе (от файлтрансферов, другие события в базе не хранятся, т.к. сервер не поддерживает MAM).

2) Перезапускаем Мираду и открываем конфу. В журнале пусто. Пишем в поле ввода "testtesttest", **но не отправляем**. Теперь туда же в поле ввода кидаем мышкой картинку и отправляем картинку. Следом тут же жмём Enter и отправляем наше сообщение "testtesttest".

Результат: ссылка на картинку не кликабельна в журнале.

<img width="506" alt="Miranda64_5LhwrdMzlh" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/61cd6799-a9c7-4354-8c70-1123c9503dda">

**Comment by dartraiden** [comment]
Если просто кинуть картинку, то ссылка будет кликабельна. Баг проявляется лишь если вот таким вот образом вслед за картинкой улетает сообщение.

**Comment by dartraiden** [comment]
Иногда даже просто при отправке простой ссылки в чат она некликабельна, и все ссылки в этом сеансе тоже становятся некликабельными.

**Comment by tamr** [comment]
Можно сюда вдогонку зарепортить небольшой баг с ссылками в NewStory, может из той же области.
При наличии нескольких ссылок в сообщении, при клике открывается последняя.

**Comment by dartraiden** [comment]
Неактуально после перехода на litehtml.
