### ISSUE TITLE
StopSpamMod не поддерживает учётные записи с внутренними именами на кириллице

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3668]
- создаём учётку, даём ей ВНУТРЕННЕЕ имя на кириллице (не обычное, а внутреннее)
- ставим StopSpamMod

результат: StopSpamMod в своих настройках показывает учётки по внутренним именам, учётку с кириллицей не видит

у StopSpam такой проблемы нет, возможно, потому что он показывает обычные имена, а не внутренние

**Comment by georgehazan** [comment]
а никто и не говорил, что внутренние имена могут нести кириллицу
там специально нет никакого уникода, поэтому ни сравнение, ни сортировка таких учеток нормально производиться не будет, что мы и видим в данном случае.

**Comment by dartraiden** [comment]
В таком случае следует при создании учётки либо ограничить допустимые символы в поле "внутреннее имя", либо вообще убрать это поле.
