### ISSUE TITLE
Long and incorrect loading of messaging window

### ISSUE THREAD

**Issue by Mitch037** [miranda-ng/miranda-ng#3670]
### Expected behavior
1. Instant load of messaging window.
2. Applying setting of number of previous events that are displayed in messaging window.
3. Displaying messages chronologically.

### Actual behavior
1. Loading of messaging window takes a while.
2. Setting of number of previous events that are supposed to be displayed by messaging window is not applied.
3. One message that is displayed at the top of messaging window is non-chronological.

### Does it work in stable version?
It applies to both stable and dev version.

### Steps to reproduce that behavior
Once I load history of one of my VK contacts (3000 events) from the server, it takes a few good seconds to load and display messaging window for that contact. The issue doesn't occur when I use "View history" by History++ or NewStory. What's important, my previous events limit is set to 10, while messaging window for that specific problematic contact displays THE WHOLE HISTORY. It works correctly (displays only 10 events) for other VK contacts who don't have so many events in their history.
Once history events of that contact get reduced to 100 (manually deleted by me) messaging window loads instantly and displays only the last 10 events, not the whole history - so it works properly as intended.
What's also weird: before the manual removal of history events, at the top of messaging window of that problematic contact, there was a message which was not chronologically correct, and right below it, the oldest message which was in fact the first event in the whole contact's history. That non-chronological event disappeared from the top of the list once history events of that contact got reduced to 100. I thought it might be worth noting as it also suggests there's a problem with Miranda handling those events. 
I can reproduce the issue with a brand new Miranda profile. Tried with StdMsg, TabSRMM and History++ as log viewers. Each of them displays the whole contact history in messaging window instead of last 10 events. The only difference is loading time of messaging window (TabSRMM and History++ seem to work faster than StdMsg). Also, each of them displays that non-chronological message at the top of messaging window.
Lastly, I gave NewStory a try. It also displays the whole contact history in messaging window. However, it doesn't display that non-chronological message at the top of messaging window + it works the fastest from all the log viewers I have tested.

**Comment by georgehazan** [comment]
run Main menu - Database - Check and enable the "Mark all events as read" checkbox in options

**Comment by georgehazan** [comment]
Which SRMM plugin do you use? StdMsg, Scriver, tabSRMM?
