### ISSUE TITLE
Сортировка учётных записей в списке контактов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3672]
В менеджере учёток учётки сортируются по алфавиту

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/1496e17d-7a4c-4faf-97ce-a4701ed6d9d5)

А вот в настройках клиста учётки (после нажатия "Сброс"), сортируются как-то странно, Tox идёт перед Telegram.

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/7305a032-c4b0-437c-9e5a-f30c99524070)

Я в курсе, что можно перетаскиванием поменять позицию, но вопрос не в этом, вопрос в том, почему клист сортирует учётки нелогично?

**Comment by dartraiden** [comment]
Может быть, потому что у Tox имя модуля TOX (капсом)? Но это же шиза.

**Comment by georgehazan** [comment]
> Может быть, потому что у Tox имя модуля в сорцах - TOX (капсом)? 

Несомненно
