### ISSUE TITLE
Плагины сообщений: не ждать таймаут, если протокол отключён

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3673]
За последние месяцы тему подняли уже два юзера:

1)
> Бывают такие ситуации, когда из-за каких-то локальных перебоев с инетом отправка сообщения подвисает. Через долгое время - будут копки "retry" и т.д. Но! Если в это время принудительно уйти в оффлайн, и вернуться в онлайн - этот таймаут никак не меняется. Выглядит не логично - если я сам ушел в оффлайн, то какой смысл дальше ждать отсылки? В моей логике - если я ушел в офлайн, то предложение отправить сообщение заново должно появиться тут же, чтобы вернувшить в онлайн я мог не ждать этого огромного таймаута, а отправить тут же.

2)
> Если протокол оффлайн и в это время я пытаюсь отправить собеседнику сообщение, миранда долго пытается это сделать (даже если сообразить, в чём дело, и срочно перевести протокол в онлайн), после чего в табсрмм высвечивается, что отправка сообщения не удалась, ещё раз, отмена, отправить позже.
Нельзя ли сразу проверять, а онлайн ли протокол, и если оффлайн, то высветить, мол, протокол оффлайн, отправить ещё раз, позже, отмена, или даже сразу если протокол оффлайн, то сделать кнопку отправки неактивной?

Суммируя:
* первый пользователь хочет, чтобы при уводе протокола в оффлайн плагин сообщений узнавал об этом и переставал ждать истечения таймаута, сразу выплёвывая "отправка не удалась, повторим?"
* второй пользователь хочет:
** чтобы попытка отправки сообщения в протокол, находящийся в офлайне, сразу кончалась неудачей, без ожидания таймаута (но у нас есть, как минимум, Dummy с опцией "разрешить отправку сообщений", который by design шлёт сообщения в оффлайн, не будет ли это с ним конфликтовать?)
** чтобы удавалась отправка сообщения в протокол, который был в офлайне в момент отправки, но переключился в онлайн, пока не кончился таймаут плагина сообщений

**Comment by georgehazan** [comment]
> чтобы попытка отправки сообщения в протокол, находящийся в офлайне, сразу кончалась неудачей

у нас каждый протокол знает, умеет ли он отправлять сообщения в оффлайн. Те, которые не умеют, сразу орут об этом.
