### ISSUE TITLE
NewStory: добавить в шаблоны переменную, которая бы сдвигала всё, что дальше после нее, к правому краю

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3676]
Пример: есть шаблон `%N %d.%o.%y`

Это даёт  на выходе `Имя день.месяц.год`, выровненные по левому краю

<img width="167" alt="Miranda64_xErg2s9fBL" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/e2ab330b-0d60-48c9-a886-5f0199587a62">

Запрос от пользователя с форума: хотелось бы переменную, которую можно было бы вставить между именем и датой, и чтобы в результате дата была бы прижата к правому краю. То есть, эта переменная как бы указывает, что дальше форматирование идёт "по правому краю", а не по левому как по умолчанию.

<img width="171" alt="Miranda64_g9gcQRKqxm" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/3694d915-9076-42f8-b859-39f0dc2e44a6">

**Comment by georgehazan** [comment]
Если кто-то сможет нарисовать код в RTF, который это делает, тогда можно задачу вернуть на меня, я сделаю, ибо генератор RTF наконец-то заработал. На самом деле RTF умеет смещать вправо до упора только всю строку целиком
