### ISSUE TITLE
Fingerprint: значки корёжит

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3682]
Запускаю миранду, включаю опцию "показывать значок клиента в строке состояния окна сообщений"

Некоторые значки меняются на какую-то фигню (см. значок Gajim у контакта ValdikSS, значок превратился в какую-то зеленую соплю)

Если опцию отключить, то значки так и остаются фигнёй, исправляются лишь рестартом Миранды.

![photo_2023-09-21_19-10-27](https://github.com/miranda-ng/miranda-ng/assets/5046855/f956b76a-023d-411d-9713-7aa5711444b3)
![photo_2023-09-21_19-10-36](https://github.com/miranda-ng/miranda-ng/assets/5046855/3a852ac0-393c-46cd-89ab-021071ddeabc)

**Comment by georgehazan** [comment]
duplicate of #3680
