### ISSUE TITLE
tabSRMM: унифицировать оверлей включенной функции в строке состояния

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3683]
Выключены всплывающие окна (Popup+), звуки и уведомления о наборе: на значках в строке состояния окна сообщений отображаются красные крестики

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/a945c95d-ea6b-43c8-8e71-80c0c5ba6838)

А теперь щелчком по ним включим всё это

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/6630925e-94fd-4b4b-8a33-e536f07e8938)

На звуках и уведомлениях о наборе текста появились зеленые галочки, а на попапах не появилась.

Предлагаю как-то унифицировать это всё, есть два пути:
1) если функция включена, то не выводить зеленую галочку
2) если функция включена то выводить зеленую галочку у попап+, чтобы он не выбивался из общего ряда

**Comment by dartraiden** [comment]
Мне больше нравится вариант 1. Если включено, то рисуем просто значок без оверлея. Если отключено - лепим сверху оверлей в виде крестика. Зеленая галка нафиг не нужна.

**Comment by georgehazan** [comment]
Это не оверлей, это просто разные иконки. Вот так они нарисованы, панимаиш... 
Надо просто нарисовать соотв. иконку для попапов и вдуть ее в DLL
