### ISSUE TITLE
ICQ: некоторые файлы всё ещё приходят в виде битых ссылок

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3684]
https://forum.miranda-ng.org/index.php?topic=6559.msg30813#msg30813

**Comment by Mikanoshi** [comment]
Все ссылки на стикеры и закачанные файлы из оф клиента давно присылаются именно так, получить все данные файла и ссылку на скачивание можно по запросу:
https://files.icq.com/getinfo?file_id=[FILE_ID]
или с токеном сессии, где можно также запросить разные размеры превью для изображений:
https://u.icq.net/api/v92/files/info/[FILE_ID]?aimsid=[AIMSID]&previews=mdpi,hdpi,xhdpi,xxhdpi,small,medium,large,xlarge

**Comment by georgehazan** [comment]
@Mikanoshi там смысл проблемы немного не в этом
кидать запрос оно умеет автоматом, вопрос в том, что сервак иногда скидывает ссылки не в тот домен, на который я кидаю запрос, тогда начинаются проблемы

**Comment by SM-Sergey** [comment]
Тут смысл совсем в другом - миранда не расценивает такие ссылки как файлы, если они приходят в тексте сообщения, а не с самого его начала. То есть надо парсить все сообщение целиком на наличие таких ссылок и преобразовывать в оффлайн файлы все такие находки.
