### ISSUE TITLE
PluginUpdater: transit from CRC32 to SHA-256

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3687]
Since we just encountered crc32 collision, we need to switch to a better hash function.

**Comment by apollo2k4** [comment]
Какова вероятность того что пользователь с определённым билдом будет обновляться на свежую версию и между ними будут коллизия? Думаю, это на уровне погрешности.

**Comment by georgehazan** [comment]
Ну вот вчера мы в первый раз наступили на эти грабли, хорошо еще плагин не ключевой, а то бы Миранда начала бы крашиться сразу после старта
