### ISSUE TITLE
whatsapp registration code

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#369]
**Reported by vvvaaagggaaa on 17 Feb 2015 15:28 UTC**
hi guys , thanks for the correct messages history reordering and whatsapp avatar.

miranda latest version 95.4x windows 7 and xp 

i have a problem for registering a new user in whatsapp.
i open the miranda ng and receive a paste password.
hit the request code 1 time and he send a code but many times ,
request code dont send.
i paste a code and register failed or connection failed.
i try the register user in my miranda win xp and i receive failed.
request code box is grayed if insert old codes .
the send request code works before updates and stop.
example: turn on miranda, request code grayed and dont send a code
update, resquest code works only 1 time and dont work never ( next update )
thanks a miranda team for the option use a whatsapp
in my pc windows xp sp3 works better.

**Comment by dartraiden** [comment]
WhatsApp is deprecated.
