### ISSUE TITLE
NewStory: по щелчку ПКМ на сообщении выделять его

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3693]
Сейчас мы имеем что:

- открываем NewStory, не выделено ни одного сообщения. Жмём ПКМ по сообщению → Копировать. Результат: ничего не скопировано, т.к. сообщение не выбрано.

- выделяем сообщение ЛКМ. Жмём ПКМ по другому сообщеню, копируем текст. Результат: в буфер скопировалось не то, по которому щелкали, а то, которое было выделено

Это неудобно, например, мне человек написал, я хочу скопировать его сообщение. Во встроенном журнале табсов для этого надо просто пкм-нуть по сообщению и выбрать копирование. А в NewStory сначала надо выделить ЛКМ, а потом уже копировать. Выходит на один клик больше.

**Comment by georgehazan** [comment]
тогда выделение будет слетать, если оно есть
