### ISSUE TITLE
Folders: добавить возможность указания путей для наборов значков

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3697]
> Свои иконпаки держу в "Customize\Icons", хотелось бы туда перенести остальные свои иконпаки из "Icons" (Proto_Conn.dll, TabSRMM_icons.dll и ToolBar_icons.dll). Например, в Folders есть поддержка переноса скинов, в том числе и для TabSRMM, почему бы не завести раздел "Иконки"?

https://forum.ru-board.com/topic.cgi?forum=5&topic=50156&start=1980#9

**Comment by georgehazan** [comment]
не вижу пока смысла править кучу мест, пока пусть ответит на форуме
