### ISSUE TITLE
Tipper: Не показывает текст в подсказках контактного листа.

### ISSUE THREAD

**Issue by opiums9** [miranda-ng/miranda-ng#3698]
### Ожидаемое поведение
При наведении указателя мыши на контакт - всплывающая подсказка с информацией и аватаркой

### Реальное поведение
При наведении указателя мыши на контакт - всплывающая подсказка с аватаркой, но без текста

### Используемая версия
Miranda NG Version: 0.96.3 build #25684 (e313c689e1) x64
Build time: 28 Sep 2023 18:49:24

### Дополнительная информация и скриншоты
Был произведены различные манипуляции, а именно:
* Проверено, что цвет шрифта текста и фона не совпадают
* Смена скина не помогает
* Проверено на версии из коробки (официальной версии с сайта + плагин Tipper)
* Попытки включения / отключения множества настроек плагина не привели к ожидаемому поведению
![image](https://github.com/miranda-ng/miranda-ng/assets/25082773/23d4cf76-07ff-4de3-8e96-57a126127d7b)
![image](https://github.com/miranda-ng/miranda-ng/assets/25082773/753138ea-e8d5-4da1-b73d-0d9d0e5ce0b6)
![image](https://github.com/miranda-ng/miranda-ng/assets/25082773/4f37b9e9-90ec-4f6b-9cc1-92dc277c1188)

**Comment by georgehazan** [comment]
@opiums9 сделай plz вот что:
- копируем профиль и открываем копию в миранде
- истребляем оттуда все учетки
- сжимаем профиль, чтобы лишние данные точно стерлись
- архивируем его и кидаем мне в личку в форум

**Comment by opiums9** [comment]
Готово

**Comment by georgehazan** [comment]
Там если дважды кликнуть на строке типпера, раскроется формочка, в ней есть второй снизу комбик (для всех контактов / для приватов / для групчатов) - он должен быть заполнен. Если он не заполнен, то он почему-то не показывается никогда
