### ISSUE TITLE
Tabsrmm hangs

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#370]
**Reported by esim on 22 Feb 2015 21:39 UTC**
if i write only "*100%" on Tabsrmm into irc group chat than this window hangs and must aggressive closing Miranda NG

http://pastebin.com/UMhbFyxU

**Comment by LittleVulpix** [comment]
This can be closed. Tried with tabsrmm and irc group chat, typing "*100%" or *100% didn't cause any issues. 0.95.6 alpha build 17731
