### ISSUE TITLE
YAMN: настройка "уведомления: значок в трее"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3703]
В настройках YAMN можно выбрать вид уведомлений. Среди них есть "значок в трее". Оно реализовано очень странно.

- если настройка выключена, то при прилете письма значок миранды в трее меняется на мигающий конверт
- если настройка включена, то значок миранды в трее меняется на мигающее конверт, а рядом появляется второй значок в виде переливающегося конверта

Предлагаю, что-то придумать. Например, чтобы эта настройка определяла, превращать значок миранды в мигающий конверт или нет. А второй значок вообще убрать.

Потому что два почти одинаковых значка это бред, кому это нужно?

**Comment by georgehazan** [comment]
Там всё сложнее - эта опция управляет еще показом ошибок, которые прилетают с сервера, и показываются они только в отдельной иконке в трее в этом случае. Пока выпилить это нет возможности
