### ISSUE TITLE
YAMN: Миранда зависает если изменить настройки YAMN во время прилёта письма

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3704]
- заводим в YAMN почтовый аккаунт, не закрываем настройки
- засылаем в эту почту письмо
- дёргаем на топтулбаре проверку почты

результат: значок Миранды в трее превращается в мигающий конверт

- включаем в настройках YAMN настройку "значок в трее"

Миранда зависает и перестаёт отвечать.

**Comment by dartraiden** [comment]
Уточнение: зависает при изменении любой настройки YAMN пока в трее мигает конвертик о новом письме.

Конвертик мигает → дёргаем любую галку в настройках YAMN → применяем → висяк

**Comment by georgehazan** [comment]
Стек надо сделать, где зависает главный поток
Process Explorer / Process Hacker, с символами
