### ISSUE TITLE
GmailNotifier: вместо пароля в базу пишется логин

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3707]
- ставим плагин
- вбиваем в его настройках имя почты gmail и пароль
- смотрим в базу

результат: в базе в ключе Nick содержится имя почты, а в ключе Password вместо пароля тоже имя почты. Пароль в базу не попал.

**Comment by georgehazan** [comment]
он и не должен туда попадать, потому что гугл работает через токен
один раз вычислили токен, дальше пароль не нужен

**Comment by dartraiden** [comment]
Плагин из коробки не работает.
