### ISSUE TITLE
Documentation about OTR plugin recommendations

### ISSUE THREAD

**Issue by saelic** [miranda-ng/miranda-ng#3712]
Miranda NG provides plugins to use OTR encryption to protect user's messages from eavesdropping.
For the moment, basing on project's Wiki entries, the available plugins are:
1. GPG
2. Miranda OTR
3. SecureIM
4. StdCrypt

There is no enough information about which one should be used and Wiki entries consist of very few information.

I have a case where the OTR encryption is a must, but, even that I have same knowledge about computer security, I don't know which plugin should I choose.

As the OTR messaging becomes more and more important every day, I believe that there should be a documentation entry which explains in detail:
1. Which OTR plugins are generally recommended.
2. Which OTR plugins are in active development, supported and have regular updates.
3. What is the level of security provided by each of the plugins.
4. How each plugin is compatible with each other and with external OTR systems.

It would be great if such information would be provided here (or put directly to Wiki entries), so people will have an idea what to choose. For now I'm stuck because of lack of the above information.

Thank you
saelic

**Comment by georgehazan** [comment]
Evidently, only one plugin provides OTR support - Miranda OTR
all another plugins implement various encryption protocols according to their names

**Comment by georgehazan** [comment]
PS: if you have a question, you better use the forum, not a bug tracker

**Comment by saelic** [comment]
> PS: if you have a question, you better use the forum, not a bug tracker

Well, I count documentation problems as a bug, that's why I posted it here.
It is really not clear what-is-what in terms of those plugins.
