### ISSUE TITLE
Jabber: авторизованный, но не добавленный в ростер контакт сам собой добавляется в ростер

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3714]
Чувак не из моего ростера засылает мне запрос авторизации. Снимаю галку "добавить в ростер" и принимаю авторизацию.

Результат: контакт добавляется с ключом NotOnList, он временный, это логично, т.к. в ростер я его не добавлял.

Но после перезапуска Миранды этот контакт уже оказывается сам собой в ростере.

**Comment by dartraiden** [comment]
Мне кажется, тут должно быть одно из двух:

1) Либо авторизация автоматически добавляет контакт в ростер. Тогда галку "не добавлять в ростер" следует засерить, чтобы её нельзя было снять.

2) Либо контакт и вправду добавляется как временный, тогда он должен стираться при перезапуске, т.к. у меня в клисте включено стирание временных контактов при запуске

**Comment by georgehazan** [comment]
Тут получается как: если ты присланный запрос одобрил, а свой не послал, то этот контакт таки заедет тебе в ростер с авторизацией to. Сейчас на все такие контакты, у которых авторизация не none, Миранда создает вполне нормальный такой контакт.

Если делать этот контакт временным, то будет I like to move it, move it, т.е. на каждый запуск он создается, а в конце разваливается, при этом т.е. контакт будет новый, для него будет каждый раз дергаться запрос вкард, например.
