### ISSUE TITLE
YAMN: проблемы с переводом

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3719]
<img width="432" alt="mstsc_NJ3Efb3Kap" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/6c1cd654-a5c5-475e-84a6-f75b3ae94e27">

"kB" (размер письма) вообще в ленгпак не попадает и всегда остаётся на английском, наверное, нужно сделать переводимым

При смене языка на лету с русского на английский в этом окне со списком писем "Отключён" осталось на русском

**Comment by georgehazan** [comment]
1. не вижу проблемы с kB.
2. статус хранится как уже переведенная строка, если проверить акк, то оно переведется по-новому

**Comment by dartraiden** [comment]
> не вижу проблемы с kB


<img width="408" alt="mstsc_WARbsTHs8C" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/bb4b4144-633a-433b-95d9-06c2a9cdd313">

**Comment by georgehazan** [comment]
в торрентах тоже везде пишут KiB, и что?
