### ISSUE TITLE
MirandaG15 plugin crashes when Logitech Gaming Software exits

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#372]
**Reported by Llewen on 9 Mar 2015 11:22 UTC**
Just that, this didn't use to happen with the original Miranda plugin.  Crash logs attached.

[crash20150309081438.zip](https://github.com/miranda-ng/miranda-ng/files/646952/crash20150309081438.zip)

**Comment by dartraiden** [comment]
Ещё крашлог
https://forum.miranda-ng.org/index.php?topic=4029.msg24623#msg24623
