### ISSUE TITLE
YAMN: лишние пробелы в заголовке письма

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3724]
![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/fa7baace-5523-492b-bf2a-c88246198b7a)

Если тема письма достаточно длинная (например, тема "Лишние пробелы в заголовке письма"), то в заголовок вкрадываются лишние пробелы.

**Comment by dartraiden** [comment]
Проблема ушла в списке писем, но если открыть это письмо, то всё ещё жива

![Безымянный](https://github.com/miranda-ng/miranda-ng/assets/5046855/3073cd0b-03f8-4f7d-8a8d-b78a01f9c8d2)

**Comment by georgehazan** [comment]
а в чем проблема? почтовый клиент может дробить строки как хочет, стандарт MIME это позволяет

**Comment by dartraiden** [comment]
Проблема в том, что дробить не нужно, справа места полно.

**Comment by dartraiden** [comment]
Есть ещё одно соображение в пользу того, что это баг. У юзера с руборды этот перенос строки показывается как пробел. У меня - как перенос. Это явный баг.

**Comment by georgehazan** [comment]
> Проблема в том, что дробить не нужно, справа места полно. Остальные строки не дробятся - прокрути вниз, увидишь там заголовки письма, которые не дробятся, а использую свободное место справа.

Это вообще не проблема этого окна: оно показывает raw data, как они приехали с сервера, а там почтовый клиент отправителя абсолютно имеет право разбивать строки так, как ему это удобно. Ничего править в самих данных это окно права не имеет, оно только расшифровывает quoted printable и base64, чтобы не мучать юзера головной болью

> У юзера с руборды этот перенос строки показывается как пробел. У меня - как перенос.

В списке писем теперь всё это выкашивается целиком, их больше нет там, а в большом окне показывается как приехало
