### ISSUE TITLE
YAMN: по умолчанию всплывающие окна отключены, но они есть

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3726]
Настройки попапов YAMN по умолчанию

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/d77b1895-463e-4b0c-8bb8-8bb460e64966)

Но если дёрнуть проверку почты через топтулбар и новой почты нет, то вылезает попап "новых писем нет". Хотя, он отключен, как видно из настроек.

**Comment by georgehazan** [comment]
всё так: при дергании руками кнопки или пункта в меню контакта попап врубается для этой конкретной задачи насильно

if (CheckFlags & YAMN_FORCECHECK)
	Param.nnflags |= YAMN_ACC_POP;  // if force check, show popup anyway and if mailbrowser was opened, do not close

**Comment by dartraiden** [comment]
Странно, может, выкосим это? Это не логично, только путает пользователей.

**Comment by dartraiden** [comment]
Смотри сам: пользователь явно указывает, что ему не нужны, допустим, попапы "новой почты нет". Почему же мы его желание должны игнорировать, если проверка дёрнута руками, но уважать, если проверка дёрнута автоматически?

**Comment by georgehazan** [comment]
А как узнать результат операции, если ты жмакнул на кнопку? Типа если мыло пришло, то мы это увидим в трее?
