### ISSUE TITLE
NewStory: если сообщение не влезает в окно, то оно не докручивается до конца

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3736]
Выбираем Scriver плагином сообщений и NewStory журналом.
Делаем окно размером поменьше и закрываем.
Заводим в RSS-плагин фид https://www.linux.org.ru/section-rss.jsp?section=1
Дёргаем проверку, кликаем на попап.

Открывается скривер, а в нём сообщение, но не докрученное до конца. Вручную его можно докрутить.

![mstsc_cxNySYFZic](https://github.com/miranda-ng/miranda-ng/assets/5046855/a1da45d1-16c3-4b86-8b23-81f14ab5dde5)

**Comment by dartraiden** [comment]
Сообщил @apollo2k4 

Я не уверен, что это надо чинить. Ведь удобнее читать сообщение с начала.

**Comment by georgehazan** [comment]
всё так: если последнее сообщение не влезает по высоте в текущее окно лога, то оно будет показано с начала
