### ISSUE TITLE
YAMN: показывать/скрывать контакт в клисте на лету

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3740]
<img width="159" alt="mstsc_lHS2U94WPj" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/53ece23b-f295-45d7-844f-1f408214b109">

Эта настройка в YAMN управляет тем, показывать или не показывать контакт в клисте. Т.е. если её взвести, контакт будет виден. Если выключить её, контакту пишется Hidden=1

Но контакт появляется или пропадает в клисте только после рестарта. Мы можем сразу обновлять клист при изменении этой настройки?

**Comment by georgehazan** [comment]
Неправильно. Наличие контакта в профиле управляется двумя галками: этой и которая повыше (Check mail)
Всё прекрасно исчезает на лету
