### ISSUE TITLE
YAMN: настройка показа/непоказа контакта в клисте не синхронизируется со скрытием контакта руками

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3741]
<img width="159" alt="275358937-53ece23b-f295-45d7-844f-1f408214b109" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/198e84ae-6341-4013-8f63-61a223c3e158">

Эта настройка в YAMN управляет тем, показывать или не показывать контакт в клисте. Т.е. если её взвести, контакт будет виден. Если выключить её, контакту пишется Hidden=1

- Включам эту настройку, чтобы контакт был виден
- А теперь удаляем контакт из клиста, но оставляем его в базе. То бишь, скрываем его

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/d0c133cd-8a39-4fc1-b0af-3825cfc36607)

Ожидание: вместе с таким ручным скрытием контакта снимется и галка в YAMN.
Реальность: ничего подобного, галка остаётся взведена, а раз она взведена, то при ближайшем рестарте у контакта удаляется Hidden=1 и контакт снова виден.

Предлагаю синхронизировать это. Если мы руками скрываем контакт, то и галка в YAMN должна сама собой сняться.

**Comment by georgehazan** [comment]
Настройка сохраняется в профиле, и плагин находится в своем полном праве.
Отслеживать в профиле изменение скрытности контакта никакой возможности нету
