### ISSUE TITLE
[IRC/TabSRMM] Improvement: Option to keep log/scrollback in RAM

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#3743]
**Is your feature request related to a problem? Please describe.**
When opening a tab for a (previously joined but not opened as active tab) group chat room, and the scrollback is very long, the tab will lag and stall as it reads the log and writes it into the tab - I assume it does this from disk.

**Describe the solution you'd like**
Keeping the whole session scrollback in RAM. It would be nice to have this as an option toggle, since scrollback can blow up memory use and Miranda-NG is known for low memory footprint.

Also of note that it does this every time, even if repeatedly closing and opening the tab, the delay occurs every time.

In the event that it already does keep the active log in memory, it should not lag TabSRMM this hard, or at all, to display it.

**Comment by georgehazan** [comment]
all IRC events are stored exclusively in memory
I recommend you to try NewStore plugin, it works way faster in these cases

**Comment by Tharn** [comment]
I'm talking about the group chat message window, normal IRC scrollback, not history. Isn't this TabSRMM?

**Comment by georgehazan** [comment]
IRC has no history, it displays only messages retrieved from the server

tabSRMM is just a container for a log window, it might be its native log viewer or NewStory/IEView/h++/whatever. The problem of the native log viewer is that it gathers all events into one monolite piece of text, and perhaps it becomes quite heavy. NewStory creates a virtual array of events, and simply scrolls over it, so it has no problems of displaying large amount of events. Try it
