### ISSUE TITLE
ICQ: приём файла блокирует отправку сообщений

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3748]
> Во время приема файлов встает отправка сообщений этому контакту, вылетает по таймауту, как ошибка отправки. Если приходит файл на полгига например, остаешься без связи надолго... Однако прием продолжает работать при этом, как и отправка сообщений другим контактам.

**Comment by georgehazan** [comment]
Блокироваться там нечему, потому что прием файла идет в отдельном потоке, вопрос в том, что для скачивания файлов в полгига Миранда реально плохо подходит, потому что весь файл сначала будет помещен в память, а потом слит на диск. В процессе выделения полгига памяти может встать раком вся винда, не то что отправка сообщений.

В качестве решения можно порекомендовать кликать на таких файлах Copy URL и засовывать его во что-то типа wget

**Comment by SM-Sergey** [comment]
И тем не менее, блокируется же. Сообщения-то не отправляются, пока идет прием файла, даже если файл на мегабайты, выделение которых ничего не занимает, а канал медлительный. Так что, все же, блокироваться там видимо есть чему.

**Comment by georgehazan** [comment]
Блокируется выделение памяти, которая пытается найти кусок пожирнее. Да, схема не самая оптимальная, но превращать Миранду в менеджер закачек пока не планируется

**Comment by SM-Sergey** [comment]
Да быть того не может. Там что, для каждого контакта свой менеджер памяти что ли? Другому контакту в это же время сообщения отправляются без проблем. Ну какой кусок "пожирнее", если это например 10 мбайт. В современной жизни это не о чем.
