### ISSUE TITLE
ICQ: неясно, как докачать оборванный облачный файл

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3749]
> Если передача файла оборвалась, то непонятно, как его докачать.

**Comment by georgehazan** [comment]
Никак, разумеется.
Можно кликнуть Copy URL и вставить файл в download manager, который умеет resume

**Comment by SM-Sergey** [comment]
Низзя. См. #3596

**Comment by SM-Sergey** [comment]
По хорошему, если закачка оборвалась раньше, чем файл весь получен, надо просто его заново поставить в очередь на закачку. Ладно, пусть он не будет докачиваться с места обрыва, но пусть хоть закачается за N попыток.

**Comment by georgehazan** [comment]
уже можно
