### ISSUE TITLE
YAMN: опция принудительного показа вспл. окон не всегда работает

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3750]
Включаем вспл. окна и принудительные вспл. окна при ручной проверке почты

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/98456583-d589-4007-92d3-d67cb928d8f3)

В настройках Popup+ отключаем вспл. окна при глобальном статусе "Отсутствую"

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/62222d4b-f43d-426d-896b-49c8e716e484)

Берём профиль, в котором ровно одна учётка протокола (Jabber, например)

Выставляем ей статус "Отсутствую" или глобальный статус "Отсутствую" (что одно и то же, т.к. учётка одна)

Дёргаем руками проверку почты.

Наблюдаемое поведение: попапов нет.
Ожидаемое поведение: попапы должны быть, мы для этого и придумали опцию в YAMN "Всегда показывать попапы при ручной проверке почты".

**Comment by dartraiden** [comment]
Так и не работает.

**Comment by georgehazan** [comment]
и не будет, потому что на уровне движка попапов отключает любые попапы
