### ISSUE TITLE
NewStory: входящие эмодзи видны при редактировании, но не при просмотре

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3752]
SmileyAdd не стоит.

В NewStory шрифт Calibri.

Мне присылают `😜`. В журнале он отображается квадратиком, а при редактировании уже черно-белым смайлом из шрифта.

<img width="366" alt="Miranda64_yqAf7Jlz2r" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/df2c163b-1176-4eb5-ab76-f1a38a6192ff">

**Comment by georgehazan** [comment]
а где написано, что в этом шрифте есть emoji? 
при редактировании контрол меняется на обычный Edit, туда подставляется системный шрифт

**Comment by dartraiden** [comment]
Встроенный журнал табсов, Calibri 26 пунктов, синий

![photo_2023-10-27_15-24-06](https://github.com/miranda-ng/miranda-ng/assets/5046855/08834f02-558f-4391-bcd1-b4824200a5c2)
