### ISSUE TITLE
PopupPlus: добавить отключение всплывающих окон при неактивности

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3756]
![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/9220ad72-6c40-4338-b8f8-426ed83f6190)

Сейчас Popup+ умеет выключать попапы в полноэкранном режиме, а также при определённых статусах.

Пользователь просит добавить туда (в настройки отключения попапов) опцию "Через N минут неактивности". Чтобы через N минут неактивности попапы гасились (разумеется, когда активность возвращается, попапы должны начинать показываться).

**Comment by georgehazan** [comment]
Есть мнение, что это лишнее. Есть плагин StatusManager, он умеет детектить неактивность и впадать в спящий режим. Вот на это событие и надо делать опцию. Спроси его

**Comment by dartraiden** [comment]
Тогда это надо добавлять в настройки idle после того, как сделаем https://github.com/miranda-ng/miranda-ng/issues/3766

**Comment by georgehazan** [comment]
Пока просто повесил на idle
