### ISSUE TITLE
ICQ: Миранда не может определить, что собеседник использует Миранду

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3757]
У меня Миранда, у собеседника тоже. Но MirVer в базе не создаётся.

TODO: проверить, работает ли детект мандарина и крысы.

**Comment by georgehazan** [comment]
Всё, капсов больше нет с нами, когда запрашиваешь инфу о контакте.
Следовательно, версию на новом протоколе ICQ больше не определить

**Comment by georgehazan** [comment]
А вот и капсы
