### ISSUE TITLE
ICQ: реализовать поддержку "Избранного"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3758]
Оф. клиент ICQ поддерживает псевдоконтакт "Избранное". Как в Telegram.

**Comment by georgehazan** [comment]
У меня в ICQ нет такого контакта, возможно, потому что я ни разу не запускал оф. клиент
Нужен нетворк лог с ним

**Comment by dartraiden** [comment]
[izbrannoe_icq.zip](https://github.com/miranda-ng/miranda-ng/files/13226652/izbrannoe_icq.zip)

понаписывал себе в избранное в официальном клиенте

**Comment by SM-Sergey** [comment]
Это не псевдоконтакт, это отправка сообщения самому себе на свой UIN

**Comment by SM-Sergey** [comment]
А, не! Я сам себя все таки вижу. Вот отправил в избранное, и вижу в миранде. Так что, формально можно закрыть этот вопрос.

![2023-11-04 20_22_02-ICQ — Mozilla Firefox](https://github.com/miranda-ng/miranda-ng/assets/34127439/134730fa-c64f-4be2-9261-7500920b4784)
![2023-11-04 20_22_26-Sergey Markov (Online)](https://github.com/miranda-ng/miranda-ng/assets/34127439/4c009ba9-2728-4be8-951d-bdfbc9319d30)

**Comment by SM-Sergey** [comment]
И наоборот, если я себе отправляю сообщение в миранде, то и в оф. клиенте тоже вижу в избранном.
Так что, всё работает!

**Comment by SM-Sergey** [comment]
Но есть и странность.... Если уйти в оффлайн в миранде, и вернуться в онлайн - то я у себя оказываюсь в оффлайне...
