### ISSUE TITLE
dont work option "strip all tags in outgoing actions"

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#376]
**Reported by John Dow on 16 Apr 2015 16:53 UTC**
Dont work option "strip all tags in outgoing actions" in GPG settings.
With uncheck this checkbox tags stripped whatever.
With incoming messages tags worked normal, outgoing - no.
Bug appeared after update to last version of Miranda and all components.

[versions_before_update.txt](https://github.com/miranda-ng/miranda-ng/files/646962/versions_before_update.txt)

[versions_after_update.txt](https://github.com/miranda-ng/miranda-ng/files/646963/versions_after_update.txt)

**Comment by georgehazan** [comment]
**Modified by John_Dow on 16 Apr 2015 16:56 UTC**

**Comment by sss123next** [comment]
ancient bug.
reopen if still relevant.
