### ISSUE TITLE
FileAsMessage: если прервать передачу файла, пункт меню отправки файла пропадает

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3763]
- отправляем файл через пкм по контакту  - "файл как сообщение"
- на той стороне возникает заминка, например, миранда падает
- на нашей стороне отменяем передачу

результат: в контекстном меню контактов пропадает пункт отправки FileAsMessage

**Comment by georgehazan** [comment]
естественно, пропадает, он показыватся только для онлайновых клиентов
если на том конце провода миранда свалилась, то пункт меню автоматически исчезнет
