### ISSUE TITLE
Сделать имена в [PluginUpdaterFiles] регистронезависимыми

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3764]
Сейчас пути и имена файлов допускаются лишь в нижнем регистре:

```
[PluginUpdaterFiles]
plugins\dummy.dll=b2
```

При этом, сами файлы и папки у нас вполне себе в разном регистре, допустим, Plugins или TopToolBar.dll

Если написать в базе Dummy вместо dummy или Plugins вместо plugins, то не срабатывает. Почему-то оно хочет строго нижний регистр. Нужно избавиться от этого неудобного ограничения.

**Comment by georgehazan** [comment]
все настройки плагинов идут исключительно в нижнем регистре
не вижу в этом никаких проблем
