### ISSUE TITLE
NewStory: добавить опцию сдвига выделения при прокрутке стрелками

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3768]
В History++ прокрутка стрелками клавиатуры сдвигает выделение, а прокрутка скроллбаром или колесом мыши не сдвигает.

Пользователи просят сделать в NewStory такое же поведение (сейчас стрелки не двигают выделение).

Предлагаю сделать опцию.

**Comment by georgehazan** [comment]
пока без опции, клава всегда бегает по событиям

**Comment by dartraiden** [comment]
Давай, всё же, опцией. А то неудобно.

**Comment by georgehazan** [comment]
Назвал опцию "H++ compatibility mode", может еще что-то пригодится
