### ISSUE TITLE
Telegram: добавление ботов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3771]
"Вот есть у меня в телеге некий бот. Открываю миранду, открываю телегу, пишу в бота команду — в миранде открывается окошко с этим ботом и подписью «контакт не в списке, вы можете его добавить». Добавляю, не включая галочку «запросить авторизацию». Перезапускаю миранду — бота нету.

Опять пишу боту в телеге, опять в миранде открывается окошко, и тоже с этим «контакт не в списке». Добавляю, на этот раз не снимая галочку «запрос авторизации». Перезапускаю…
Контакт есть в клисте, хотя и с чёрной каймой, которая у меня настроена на контакты не в списке. В общем, открываю окошко общения с этим ботом и опять вижу «контакт не в списке». Не жму добавление. Перезапускаю миранду. Контакта в контакт-листе нет."

```
ghazan, 01.11.2023
[21:42] а его в списке контактов нету

ghazan, 01.11.2023
[21:42] телега его потом присылает, а он опять не в списке
[21:42] и идет себе, солнцем палимый

```

**Comment by georgehazan** [comment]
вопрос - а не исправился ли этот тикет?
там проблема-то была в том, что миранда не слала на сервер запрос на френжение
а теперь всё шлется на ура
как это проверить?

**Comment by Deadooshka** [comment]
После обновления в контакт-листе появляется куча ботов, которые в официальных клиентах не видны.  Наверное, это боты связанные с подписанными каналами. После удаления из контакт-листа они опять могут подгружаться. В основном это боты-модераторы каналов.

**Comment by georgehazan** [comment]
@Deadooshka их можно один раз истребить, и больше они никогда не появятся.
видимо, их как-то использует официальный клиент, но они никогда не выходят в онлайн

**Comment by Deadooshka** [comment]
@georgehazan они всё равно лезут десятками. Есть повторяющиеся, а есть новые непонятного назначения. В официальном клиенте их нет, но когда пишешь в бот, то чат с ним уже отображается везде. Главное неудобство - эти боты смешиваются с живыми контактами, и надо как-то их отделить и положить в другое место или запретить добавляться в контакты.
