### ISSUE TITLE
mir_app.mir cannot be loaded

### ISSUE THREAD

**Issue by kzkin** [miranda-ng/miranda-ng#3773]
После успешной сборки проекта bin16/miranda32.sln в Microsoft Visual Studio 2019 при запуске отладки появляется сообщение об ошибке "mir_app.mir cannot be loaded" в папке libs имеется файл mir_app.mir. В чём проблема не пойму, как исправить ?

**Comment by georgehazan** [comment]
подсунуть туда из архива с ядром недостающие библиотеки, например, openssl

**Comment by kzkin** [comment]
а как понять каких библиотек не хватает ?
