### ISSUE TITLE
Newstory: Problems with scrolling, and crash.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#3781]
Дано: история контакта с 2003 года, в которой >200000 сообщений.
Открываем историю (для журнала я еще ньюстори не поставил). Начинаем таскать бегунок туда-сюда, в конец, в начало, и как угодно по-разному.

Для начала сообщения из "по-русски" начинают плавно преобразовываться в "по-RTF-ному". Чем дальше, тем больше.

![2023-11-02 20_20_13-ElectroVoicer - history  204833 messages total](https://github.com/miranda-ng/miranda-ng/assets/34127439/e7fbd453-cae0-432a-ad0a-dc6dc8c4173b)

Ну и потом, вишенкой на торте, краш. Когда безумно растущее кол-во GDI Objects дойдет до 10000.

[crash20231102201326.txt](https://github.com/miranda-ng/miranda-ng/files/13242687/crash20231102201326.txt)

Я уже писал про это давно , но что-то не найду тикет. Наверное на форуме писал. Как минимум, не должны GDI объекты накапливаться и не освобождаться.

**Comment by georgehazan** [comment]
как это не должны? а смайлики? это же вполне отдельная такая картинка
больше текста, больше смайликов, больше GDI

на себя контрол показа истории расходует что-то около 20 handles, и их число не зависит от количества строк

**Comment by SM-Sergey** [comment]
> как это не должны? а смайлики?

У меня ни разу не было ситуации, чтобы для видимой на экране части, и +- вокруг этой видимой части, было 10000 объектов GDI

То есть, Вы считаете нормальным, что Newstory сначала глючит, а потом падает в тех же условиях, когда все другие истории работают без проблем? И это как бы не баг?

**Comment by georgehazan** [comment]
Ну как, h++ валится в корку на длине истории в 16К, например, но это же нормально, да?
Если отключить смайлы, то GDI handles расходоваться не будут.

**Comment by SM-Sergey** [comment]
Вот ни разу не замечал за h++ такого падения, я много раз именно в ней, пока на ней сидел, бегунком искал в этой длинной истории нужный кусок на нужные даты лет на 15-20 назад.

**Comment by SM-Sergey** [comment]
Вот прям щас на нее переключился, на h++ - GDI объекты крутятся вокруг 1000-1100 - таскай бегунок сколько хочешь, ничего не случается, и кол-во объектов не растет.

**Comment by SM-Sergey** [comment]
Я обновил до текущего состояния. И проверил еще раз пять-шесть. В h++ этой проблемы нет, можно "гулять" по всей громадной истории как хочется. Newstory ведет себя стабильно, как тут описано, портит вывод, крашится.
Я не понимаю, почему этот баг закрыли. Он есть в полном объеме. Переход на h++ можно рассматривать только как временное решение, чтобы листать историю, в те моменты, когда надо лезть глубоко в нее. Но на "постоянку" перейти на h++ - не выход! Проблему надо лечить.

**Comment by georgehazan** [comment]
Можно отстрелить смайлы, она вылечится. Для h++ в SmileyAdd есть специальная жопная затычка, чтобы не вставлять картинки через COM, а как-то посредством отправки сообщений в Дельфи, вот только в NewStory нет дельфи...

**Comment by SM-Sergey** [comment]
Причем тут дельфи? Раз в h++ все нормально, значит в винде можно сделать так, чтобы оно работало нормально, и не важно, на С или на паскале. Баг он и есть баг.

Отключать смайлы это вариант, но как это сделать для ньюстори, но не для встроенных журналов?


PS. Вот еще краш словил, просто тыкнув в Options->Smileys->Categories tab. Правда повторить потом больше не смог.
[crash20231103224333.txt](https://github.com/miranda-ng/miranda-ng/files/13254062/crash20231103224333.txt)

**Comment by SM-Sergey** [comment]
И, вообще, чтобы это перестало быть багом, надо тогда просто насмерть отключить смайлы в ньюстори в просмотре истории, до лучших времен.

**Comment by georgehazan** [comment]
> Причем тут дельфи?

При том, что в h++ используется специальный режим показа смайликов, который поддерживается не системным контролом, а специальной компонентой дельфи. Как она это делает - никому не ведомо.

> Раз в h++ все нормально, значит в винде можно сделать так, чтобы оно работало нормально,

Но для этого в С++ и винду надо втащить весь рантайм от дельфи и все её компоненты.

> И, вообще, чтобы это перестало быть багом, надо тогда просто насмерть отключить смайлы в ньюстори в просмотре истории, до лучших времен.

Может быть, посмотрим

**Comment by SM-Sergey** [comment]
Ну, допустим, не надо весь рантайм втаскивать, а надо разобраться, как это делает дельфи на уровне общения с контролом - посниферить сообщения, и т.п. Да, сложно это, но можно.

Как вариант, предложу попробовать перевести SmileyAdd для виндей с 8-ой с COM на EM_INSERTIMAGE - должно помочь, все таки сам контрол начнет  картинки отображать. А для виндей до 8-го принудительно ограничить количество вставляемых смайлов - переставать это делать, если кол-во гди объектов превысило какое-то там.

**Comment by georgehazan** [comment]
> Ну, допустим, не надо весь рантайм втаскивать, а надо разобраться, как это делает дельфи на уровне общения с контролом - посниферить сообщения, и т.п.

Каким "контролом"? В дельфи есть компонента, которая рендерит текст и иконки поверх canvas, никаких "контролов" там нету, есть грид, каждой ячейкой которого является компонента Дельфи.

> Как вариант, предложу попробовать перевести SmileyAdd для виндей с 8-ой с COM на EM_INSERTIMAGE - должно помочь, все таки сам контрол начнет картинки отображать.

Вот это точно будет создание копии картинки на каждый чих.

> И это все не отменяет бага с отображением RTF в виде исходника, это появляется гораздо раньше, чем кол-во гди объектов приблизится к концу.

Там перестает вообще работать GDI подсистема, и не рендерится ни фига поэтому.

**Comment by SM-Sergey** [comment]
> Вот это точно будет создание копии картинки на каждый чих.
Ну и ладно, памяти не жалко, её много. Значительно больше, чем объектов GDI. Сейчас не конец 90-х, когда память была на вес золота. Зато есть надежда, что GDI объекты будут созданы только для картинок, попавших на экран сейчас, а для не попавших - нет. И, если не создавать для каждой одинаковой иконки новый IStream, то есть некий шанс, что и копий не насоздается.

PS
А это нормально, что после снятия галки с плагина SmileyAdd в опциях миранда закрылась без создания краш-инфо?

**Comment by georgehazan** [comment]
> Ну и ладно, памяти не жалко, её много.

Каждая картинка - это 3 GDI handle. Дальше рассказывать?

**Comment by SM-Sergey** [comment]
А кто сказал, что при вставлении картинки через EM_INSERTIMAGE она сразу создается в виде GDI объекта? Такого быть не должно по определению. Она должна храниться просто в виде массива данных. А GDI объекты - создаваться только тогда, когда эта картинка требует отображения на экране.

**Comment by SM-Sergey** [comment]
И вообще, а зачем делать на каждый экземпляр одинаковой иконки свой HBITMAP ? Если я правильно понимаю суть имеющейся проблемы. Иконок не так и много, хватило бы одного объекта-картинки на одну иконку, а не на каждый ее экземпляр.

**Comment by georgehazan** [comment]
> И вообще, а зачем делать на каждый экземпляр одинаковой картинки свой HBITMAP ?

Именно поэтому в Миранде сделано умнее, чем пользовать EM_INSERTIMAGE, там расходуется только один GDI handle на каждый смайлик. Но все равно расходуется

**Comment by SM-Sergey** [comment]
Вот именно, что на каждый смайлик. А зачем на каждый экземпляр одинакового смайлика в тексте то?

И, все таки, это вряд ли умнее, чем EM_INSERTIMAGE, который передает поток с картинкой, и вообще не использует ни одного GDI handle. Скорее, в миранде так со времен до Win 8, когда еще не было EM_INSERTIMAGE

**Comment by georgehazan** [comment]
> Вот именно, что на каждый смайлик. А зачем на каждый экземпляр одинакового смайлика в тексте то?

Потому что в RTF вставляется не картинка, а EMF, который на нее ссылается, но выделение EMF - это тоже один GDI handle.

> И, все таки, это вряд ли умнее, чем EM_INSERTIMAGE, который передает поток с картинкой

Угу, и внутри создает отдельный битмап из этого потока. Спасибо, не интересно

**Comment by SM-Sergey** [comment]
> Угу, и внутри создает отдельный битмап из этого потока.

Да, но только для тех, **которые в данный момент отображаются на экране**! Разница огромна.

**Comment by georgehazan** [comment]
Вкратце - нет. Попробуй сам, что мы тут воду толчем в ступе

**Comment by georgehazan** [comment]
> Да, но только для тех, **которые в данный момент отображаются на экране**! Разница огромна.

Вкратце - нет. Попробуй сам, что мы тут воду толчем в ступе

**Comment by SM-Sergey** [comment]
Мне пока не удалось научиться собирать миранду, я все таки программист по встраиваемым системам и по драйверам ядра виндовс. Видимо у меня чего-то не хватает на рабочей станции для нее. Так бы и попробовал наверное.

**Comment by georgehazan** [comment]
Не надо собирать миранду, надо сделать rtf control и заслать туда по нажатию кнопки EM_INSERTIMAGE. На каждое нажатие кнопки засечь показания GDI handles

**Comment by SM-Sergey** [comment]
И, самое главное, что как ни крути, это баг, и мощный баг, несмотря на то, что пока непонятно, как его устранить!

**Comment by SM-Sergey** [comment]
>Не надо собирать миранду, надо сделать rtf control и заслать туда по нажатию кнопки EM_INSERTIMAGE. 

Вот это для меня как раз сложно - писать всю обвязку UIшную, чтобы окно создалось с нужными контролами и кнопками, не мой профиль от слова совсем. В миранде было бы проще, так как там уже все окна созданы, а вот всякие алгоритмические части, это как раз моя тема.

**Comment by SM-Sergey** [comment]
Хорошо. Тогда еще вот так.
Я же правильно понимаю, что в контрол не грузится сразу вся история с картинками? А подгружается по мере скроллинга? Иначе бы  объекты GDI сразу зашкалили, и оно бы рухнуло при еще открытии. А можно по мере скроллинга удалять из контрола лишние "далёкие" куски текста вместе с картинками в них? Или, хотя бы, только картинки из них? С освобождением соответстувующих им объектов GDI?

**Comment by SM-Sergey** [comment]
И снова здрасте. SmileyAdd отключил, а глюк на месте. GDI объекты растут точно так же, и тот же краш. И те же проблемы с отображением RTF в виде исходника.

 Кучу ресурса клавиатуры израсходовали не в тему.

**Comment by SM-Sergey** [comment]
А вот истории в 8300 сообщений хватило, чтобы уронить.

**Comment by SM-Sergey** [comment]
Далее.  Для сравнения. 

1) Беру как образец журнал табсов, в который грузится 100 последних сообщений по настройке в опциях. Открываю. Кол-во объектов возрастает с 783 до 809. Пролистываю их все до верха - кол-во объектов крутится вокруг этих 809 +- незначительно, но не растет.

2) открываю ту же историю, но в ньюстори. Кол-во объектов возрастает с 783 до 913. Ну ладно, побольше, но нормально. Докручиваю вверх ровно до того же 100-го назад сообщения - кол-во объектов возрастает до 1249 и обратно не падает.

В чем принципиальная разница? Если в такой же контрол выводится примерно такая же информация?

**Comment by SM-Sergey** [comment]
Так что с этим? Без смайлов все тоже самое и с той же скоростью. То есть, виноваты не смайлы.
Верните пожалуйста тикет в "open"

**Comment by dartraiden** [comment]
https://forum.miranda-ng.org/index.php?topic=6033.msg30902#msg30902

**Comment by SM-Sergey** [comment]
Ну что можно сказать еще про вашу лень.
Проверил через GDIView, и через Bear. Утечка идет как минимум объектов типа "DC", причем не MF/EMF-DC, а просто DC, и вовсе не картинок. Количество битмапов стоит как вкопанное. А это вообще ни в какие ворота не лезет, зачем держать сотни постоянно открытых объектов этого типа??? Они же - открыл, порисовал, закрыл!

Кроме этого, утекает еще что-то, что GDIView не показывает (All GDI утекает ровно вдвое быстрее, чем DC, ну и сумма не сходится, и Bear также показывает). Возможно, один объект DC физически занимает два объекта GDI, второй какой-то скрытый. В общем, устраните уже наконец утечку объектов, хотя бы DC.

Вот два скриншота, между которых было несколько "PgUp"

![2023-11-18 14_08_46-GDIView](https://github.com/miranda-ng/miranda-ng/assets/34127439/4273116f-af5a-4ab8-b773-eaa786163851)
![2023-11-18 14_11_52-GDIView](https://github.com/miranda-ng/miranda-ng/assets/34127439/124f8327-3569-4fde-a67e-d4e8c6b7feb2)

**Comment by dartraiden** [comment]
> Мне пока не удалось научиться собирать миранду

https://wiki.miranda-ng.org/index.php?title=Building_Miranda/ru

**Comment by SM-Sergey** [comment]
> https://wiki.miranda-ng.org/index.php?title=Building_Miranda/ru

Да я это все читал, но, увы, я работаю в VS2008 - собираю драйверы для железа, совместимые от XP до 11. Так что мне пока не судьба. Хотя я уже предполагаю, как исправить этот глюк в корне.
