### ISSUE TITLE
Jabber: запрос авторизации не отправляется при добавлении контакта

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3790]
<img width="280" alt="Miranda64_wIwBOfhLOz" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/b4e133cc-67a1-464e-b5ed-8ea179ed3461">

Добавляю контакт через поиск. Взведена и почему-то засерена галка про запрос авторизации. Поле с текстом запроса авторизации тоже засерено. Контакт добавляется, но никакого запроса авторизации на том конце не возникает. Только если руками из меню контакта запросить авторизацию, тогда на том конце вылезает запрос.

Вижу тут 3 бага:
1) почему опция запроса авторизации засерена? А если я вдруг хочу добавить контакт, но не запрашивать авторизацию?
2) запрос авторизации принудительно включён, но ничего не приходит
3) почему засерена возможность вписать текст в запрос авторизации?

**Comment by georgehazan** [comment]
1. Потому что он направляется принудительно. А как можно добавить кого-то куда-то, не направляя запрос? Вариантов упихать контакт в ростер без запроса авторизации в XMPP не поддерживается.
2. Что именно куда не приходит? А на сервер запрос уходит? Почему он не приходит - это дело десятое может быть, и целиком зависеть от сервера (например, тот юзер тебя забанил в приваси листс)
3. Потому что никакого текста запроса в XMPP не существует, в отличие от ICQ

**Comment by dartraiden** [comment]
[send.txt](https://github.com/miranda-ng/miranda-ng/files/13261056/send.txt)
[received.txt](https://github.com/miranda-ng/miranda-ng/files/13261057/received.txt)

**Comment by dartraiden** [comment]
Тут в любом случае есть баг:
1) Если запрос авторизации НЕ отправился, то баг в том, что Миранда не отправляет его, несмотря на взведенную принудительно галку "запросить авторизацию"
2) Если запрос авторизации отправился, то баг в том, что Миранда на том конце никак не отреагировала
