### ISSUE TITLE
SmileyAdd - Crash #2

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#3791]
Если снять галку с плагина в Options->Plugins, и нажать Apply, миранда крашится без создания Crash Info. После перезапуска галка на плагине остается не снятой. Три раза попробовал - стабильно.

**Comment by georgehazan** [comment]
а если к миранде отладчик подвесить?

**Comment by dartraiden** [comment]
> После перезапуска галка на плагине остается не снятой.

Логично, оно же упало и в базу изменение не сохранилось.

**Comment by SM-Sergey** [comment]
>а если к миранде отладчик подвесить?

то вот так. А в миранде где-то pdb-шки лежат? Откуда крашдамипер символы берет?
![2023-11-04 17_36_36-PID_ 26884 - WinDbg 1 2308 2002 0](https://github.com/miranda-ng/miranda-ng/assets/34127439/38d6dae8-534b-4490-a3c2-442d83ddf628)

**Comment by SM-Sergey** [comment]
pdb сам нашел. ща.

**Comment by SM-Sergey** [comment]
вот
![2023-11-04 17_46_57-PID_ 26884 - WinDbg 1 2308 2002 0](https://github.com/miranda-ng/miranda-ng/assets/34127439/cc38ca86-cccb-413f-a981-2a9419ff282c)

**Comment by SM-Sergey** [comment]
И вот еще, поглядев на стек... Если галку снимать при закрытых окнах сообщений, то все ОК.
