### ISSUE TITLE
XEP-0440: SASL Channel-Binding Type Capability support

### ISSUE THREAD

**Issue by Neustradamus** [miranda-ng/miranda-ng#3793]
Dear @miranda-ng team, 

After jabber.ru MITM, can you add the support of "XEP-0440: SASL Channel-Binding Type Capability" for more security?
- https://xmpp.org/extensions/xep-0440.html

Thanks in advance.

Linked to:
- https://github.com/miranda-ng/miranda-ng/issues/3140
- https://github.com/miranda-ng/miranda-ng/issues/3792
- https://github.com/miranda-ng/miranda-ng/issues/3793
- https://github.com/miranda-ng/miranda-ng/issues/3794
- https://github.com/miranda-ng/miranda-ng/issues/4074
- https://notes.valdikss.org.ru/jabber.ru-mitm/
- https://snikket.org/blog/on-the-jabber-ru-mitm/
- https://www.devever.net/~hl/xmpp-incident
- https://blog.jmp.chat/b/certwatch

**Comment by Neustradamus** [comment]
@georgehazan: ejabberd has the support:
- https://github.com/processone/xmpp/blob/ded8be8c169487688b11130eda566b1377ab3301/xmpp.doap#L732
- https://github.com/processone/ejabberd/issues/3972

Prosody IM (trunk) has too:
- https://hg.prosody.im/trunk/log?rev=xep-0440

The XEP-0440 supports is already in:
- Monal IM: https://github.com/monal-im/Monal/blob/9e189f448b8677533b2b832fa48e08cabc5d7b27/monal.doap#L663
- nbxmpp used by Gajim: https://github.com/gajim/python-nbxmpp/blob/6e6ffb7b2427cae8d1200008ad0542cce81db29c/python-nbxmpp.doap#L420
- Tigase XMPP Server: https://github.com/tigase/tigase-server/blob/65787881da84d7f790bb86177cdc1e78d194d380/src/main/restructured/Tigase_Administration/Release_Notes/Tigase_v8.3.0.inc#L10 + https://github.com/tigase/tigase-server/blob/65787881da84d7f790bb86177cdc1e78d194d380/src/main/restructured/Tigase_Administration/Release_Notes/Tigase_v8.3.0.inc#L45

cc: @tmolitor-stud-tu, @prefiks.

**Comment by georgehazan** [comment]
@Neustradamus Prosody has no reference to tls-server-endpoint in its sources, neither ejabberd does.
seems that this task would be postponed until I have a server for tests

**Comment by Neustradamus** [comment]
@georgehazan: You have forgotten the "-":
- https://hg.prosody.im/trunk/log?rev=tls-server-end-point

**Comment by Neustradamus** [comment]
@georgehazan, @dartraiden: XEP-0440 is missing in .doap file, can you look if the support of the latest version is good?
- https://github.com/miranda-ng/miranda-ng/blob/master/docs/miranda.doap#L357

At this time, it is XEP-0440 0.4.2 (2024-07-02):
https://xmpp.org/extensions/xep-0440.html

@georgehazan: I suppose you have added 0.4.0 (2022-09-21), your commit has been done 2023-12-23:
- https://github.com/miranda-ng/miranda-ng/commit/cbdf4e985f31329a131e2b5cd1ba10051373bf2a

Change between 0.4.0 (2022-09-21) and 0.4.2 (2024-07-02):
- https://services.w3.org/htmldiff?doc1=https://xmpp.org/extensions/attic/xep-0440-0.4.0.html&doc2=https://xmpp.org/extensions/attic/xep-0440-0.4.2.html

**Comment by dartraiden** [comment]
Added XEP-0440 v0.4.0

btw smth wrong with https://xmpp.org/software/miranda-ng/ - it shows Miranda as mobile client

**Comment by georgehazan** [comment]
> Change between 0.4.0 (2022-09-21) and 0.4.2 (2024-07-02):

@Neustradamus  but there's no difference at all, they simply replaced square brackets with angle ones
