### ISSUE TITLE
XEP-0474: SASL SCRAM Downgrade Protection support

### ISSUE THREAD

**Issue by Neustradamus** [miranda-ng/miranda-ng#3794]
Dear @miranda-ng team, 

After jabber.ru MITM, can you add the support of "XEP-0474: SASL SCRAM Downgrade Protection" for more security?
- https://xmpp.org/extensions/xep-0474.html

Thanks in advance.

Linked to:
- https://github.com/miranda-ng/miranda-ng/issues/3140
- https://github.com/miranda-ng/miranda-ng/issues/3792
- https://github.com/miranda-ng/miranda-ng/issues/3793
- https://github.com/miranda-ng/miranda-ng/issues/3794
- https://github.com/miranda-ng/miranda-ng/issues/4074
- https://notes.valdikss.org.ru/jabber.ru-mitm/
- https://snikket.org/blog/on-the-jabber-ru-mitm/
- https://www.devever.net/~hl/xmpp-incident
- https://blog.jmp.chat/b/certwatch

**Comment by Neustradamus** [comment]
@georgehazan: ejabberd has the support:
- https://github.com/processone/xmpp/issues/79

The XEP-0474 supports is already in:
- Monal IM: https://github.com/monal-im/Monal/blob/9e189f448b8677533b2b832fa48e08cabc5d7b27/monal.doap#L695

cc: @tmolitor-stud-tu, @prefiks.

**Comment by tmolitor-stud-tu** [comment]
prosody has support, too: https://modules.prosody.im/mod_sasl_ssdp.html

**Comment by Neustradamus** [comment]
@georgehazan: Thanks for this new and important support! :)
