### ISSUE TITLE
Telegram: не находит меня по нику

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3796]
В Миранду заведен мой второй аккаунт. Выполняю через Миранду поиск моего основного аккаунта @dartraiden 

Результат: находится какая-то фигня без ника, имени и фамилии. При попытке её добавить в клист, ничего не происходит.

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/30aee006-302e-4f33-8bcb-8912b7d9fb28)

[search.txt](https://github.com/miranda-ng/miranda-ng/files/13257824/search.txt)

[add.txt](https://github.com/miranda-ng/miranda-ng/files/13257825/add.txt)

При этом, например, @georgehazan находится поиском вполне нормально...

**Comment by georgehazan** [comment]
Ну да, телега пишет при добавлении, что имя пустое, и с таким именем оно никого добавлять не будет. При этом в результатах поиска оно никакого имени не возвращает... Проверь, нет ли у тебя в профиле уже этого контакта

**Comment by georgehazan** [comment]
@dartraiden надо сделать нетворк лог от самого начала до того момента, когда в результатах поиска покажется пустая запись

**Comment by dartraiden** [comment]
Больше не воспроизводится :(
Даже пробовал удалить аккаунт с серверов TG и пересоздать.
