### ISSUE TITLE
Telegram: не удаётся добавить контакт в ростер

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3798]
Мне пишет человек не из ростера.
В Миранде образуется временный бледный контакт телеграма (NotOnList)
Жму "плюсик" в окне сообщений, добавляю контакт. Он становится полноценно синеньким.
Перевожу протокол в оффлайн и обратно в онлайн. 

Результат: контакт вышибается обратно в NotOnList. И в официальном клиенте в контактах никто не появляется. Такое ощущение, что Миранда его в серверный ростер не в состоянии добавить.

**Comment by georgehazan** [comment]
В логе добавления контакта ошибка есть?
