### ISSUE TITLE
YAMN: статус псевдоконтакта YAMN почему-то зависит от глобального статуса миранды

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3799]
- в YAMN включена опция про уведомления в клисте, соответственно в клисте есть псевдоконтакт YAMN
- пока у миранды глобальный статус "не в сети", конвертик YAMN красный
- когда любой протокол выходит в сеть и глобальный статус меняется на "в сети", конвертик YAMN становится зеленым и в трее мигает человечек ("контакт вышел в сеть")

Это довольно странно и неудобно. YAMN ведь проверяет почту вне зависимости от глобального статуса Миранды. У него есть опции "проверять при запуске" и "интервал". Согласно им он и проверяет. Понятия "онлайн" и "оффлайн" ему совсем не нужны. Он соединился, проверил, закрыл соединение. Зачем статус этого псевдоконтакта прибит гвоздями к глобальному статусу?

**Comment by georgehazan** [comment]
Потому что YAMN отрабатывает функцию PS_SETSTATUS, которую дергает ядро и клист. Если все протоколы уведены в оффлайн, то проверка почты также осуществляться не будет, и все контакты протокола YAMN дружно едут в оффлайн
