### ISSUE TITLE
IRC: кракозябры в логе сервера

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3800]
irc.irc.com
6697-6697
SSL

> Global, 05.11.2023, 01:30:
> Уведомление от Global [Random News - Oct 27 04:08:42 2023 UTC] рџЋ‰ Join us in #trivia for a thrilling trivia showdown! Test your knowledge and have a blast with us! рџ§ рџ’Ў

`рџЋ‰` и `рџ§ рџ’Ў`

**Comment by georgehazan** [comment]
выставить для сервера кодировку utf8 не помогает?

**Comment by dartraiden** [comment]
Помогло.
