### ISSUE TITLE
ICQ: Статус контакта "я сам" не соответствует моему статусу в миранде, и подобные проблемы со статусами других контактов.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#3802]
Контакт "я сам", то есть контакт с моим же UIN (= Favorites в оф. клиенте), будучи добавленным в БД, почему-то имеет статус, не соответствующий текущему статусу миранды. Других клиентов для этого UIN нигде не запущено. Этот контакт непонятным образом может становиться онлайн, уходить в оффлайн, в общем, живет своей жизнью. Если аську в миранде увести в оффлайн, и вернуть в онлайн, то "я сам" остаюсь в оффлайне, даже если до этого был в онлайне. Если запустить миранду, когда она не была запущена, то тоже "я сам" в оффлайне. Но "я сам" бываю и в онлайне тоже! Правда, не могу понять, когда именно. Запустив оф. клиент вебаську, я тоже не выхожу в онлайн. В общем весь мозг сломал, но понимания вопроса нет.

**Comment by SM-Sergey** [comment]
Добавка... Когда я перевожу аську в онлайн, с сервера в контакт листе в явном виде прилетает для меня "status":"online". Но я в клисте всё равно в оффлайне. Вырезка из нетлога:
![2023-11-05 15_12_58-view netlog3 txt - Far 3 0 6060 0 x64](https://github.com/miranda-ng/miranda-ng/assets/34127439/2e3ff217-15e5-4c38-9023-4519fecb696c)

**Comment by SM-Sergey** [comment]
И в еще одной записи там же - я тоже онлайн.

![2023-11-05 15_24_08-view netlog3 txt - Far 3 0 6060 0 x64](https://github.com/miranda-ng/miranda-ng/assets/34127439/248520ac-b598-4b16-97c5-1bbc6813c5ac)

Та же проблема для клиента "ICQ Official" - он всегда в онлайне, но не в миранде, где он скачет непонятным образом.

**Comment by SM-Sergey** [comment]
В общем, эта проблема распространяется на все контакты. Если можно, переименуйте пожалуйста ее, выходит, что я неверно сформулировал название тикета.

**Comment by SM-Sergey** [comment]
Чтобы я у себя стал онлайн - надо зайти в оф. клиент, и там разлогиниться! Фигня какая то.
В общем, нет никакой корреляции между статусами в оф. клиенте и статусами в миранде. Из тех, кто в оф. клиенте онлайн, почти все в миранде оффлайн.

**Comment by SM-Sergey** [comment]
В общем, долго наблюдая за нетлогом, и сниферя оф. вебаську... Имеется какая-то неадекватная завязка не lastseen.

Оф. клиент работает чётко и просто:
 - Изначально, при открывании оф. клиента, статусы ("state") и lastseen берутся из приходящего контакт листа (список buddylist").  
 - потом по мере изменения состояний приходят евенты "presence" - статусы обновляются оттуда, lastseen тоже.

Если контакт имеет "state":"online", то "lastseen" не имеет смысла и игнорируется. Собственно, в этом случае он нулевой или вообще отсутствует. Если контакт "offline" - то показывается, когда клиент ушел в оффлайн из "lastseen". Тут всё ясно и прозрачно.

В миранде же ничего не ясно и мутно.
- При переходе из оффлайна в онлайн "state" из буддилиста никак не влияют на состояния контактов в клисте.  
- При приходе евента "presence" - зачем-то делается дополнительный GetUserLastSeen, который, понятное дело, всегда выдает ровно тот же lastseen, что пришел в крайнем евенте "presence". Хотя lastseen не имеет смысла при "state":"online, да и в миранде вообще нет такого понятия, как "Last seen" (хотя было бы полезно иметь для оффлайн контактов).

В результате - после выхода миранды в онлайн, все контакты поголовно в оффлайне, несмотря на информацию из буддилиста, где все текущие статусы пришли, до тех пор, пока не придет евент типа "presence". ИМХО - излечить более чем просто - сделать ровно тот же алгоритм, что в оф. клиенте, который явно проще, чем какая-то мутность миранды.

**Comment by SM-Sergey** [comment]
ИМХО, пофиксилось. Не знаю, в каком коммите, но все статусы появились какими положено.

**Comment by georgehazan** [comment]
> Не знаю, в каком коммите, но все статусы появились какими положено.

я пририсовал, в каком конкретно. просто завелась кучка тикетов почти одинаковых, я об этом забыл уже
