### ISSUE TITLE
ICQ: Нет уведомлений о новых сообщениях, если я пишу с другого клиента самому себе.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#3803]
Не знаю, связано ли это с предыдущим, то есть со странным поведением статуса, но подозреваю, что да. Если я пишу с другого клиента "себе" на свой UIN (в Favorites в оф. клиенте), то сообщение приходит, появляется в журнале-истории (если оно было открыто для контакта "я сам" заранее), но нет никаких уведомлений нигде об этом, если журнал не в фокусе. И закладка журнала не самосоздается, если она не была открыта, хотя это включено. Но ведь по сути, это "контакт как контакт", такой же, как и остальные, сообщение пришло - всплывай-уведомляй.

Хотя... Подумав... А с другой стороны, а оно надо??? Если я сам себе написал, то вроде и уведомлять самого себя нет смысла :) Интересный вопрос... Просто непонятно, почему уведомления не работают, вряд ли же это задумывалось заранее.

**Comment by georgehazan** [comment]
Разумеется, не работает. Собственный UIN плагином переводится в контакт №0, т.е. собственно учетную запись. Поэтому никакие механизмы работать не будут, это надо теперь специально прописывать в коде

**Comment by SM-Sergey** [comment]
>Собственный UIN плагином переводится в контакт №0, т.е. собственно учетную запись

Каким плагином? В БД номер моего контакта 301 (через дбедитор вижу), в нетлоге тоже 301, все сообщения тоже привязаны к контакту с моим UIN и номер 301. Или я не о том?

**Comment by georgehazan** [comment]
Любым плагином. В данном случае ICQ.

**Comment by SM-Sergey** [comment]
А это тогда что? И почему в истории у этого контакта все нормально, все сообщения на месте? То есть всё работает внешне как надо? 

![2023-11-05 13_36_53-Database Editor++](https://github.com/miranda-ng/miranda-ng/assets/34127439/b43519bd-91c4-4ab3-8d62-a95442a9caae)
![2023-11-05 13_37_13-Database Editor++](https://github.com/miranda-ng/miranda-ng/assets/34127439/a1c48c15-2cc1-4f97-a339-3549994e464e)

**Comment by georgehazan** [comment]
Мы всё еще об уведомлениях? Или уже о сообщениях?

**Comment by SM-Sergey** [comment]
А это разное? Простите, не знал. Я был уверен, что запись сообщения в базу = причина для уведомления.

**Comment by georgehazan** [comment]
Уведомления не пишутся в базу, в отличие от сообщений.

**Comment by georgehazan** [comment]
Typing notification для фаворитесов не передается ни стандартным, ни веб-клиентом
Всё остальное вроде заработало

**Comment by dartraiden** [comment]
Как-то я пропустил этот момент. Если я что-то на одной машине сохраняю в Избранное, то зачем на другой машине мне должно приходить уведомление об этом?

**Comment by SM-Sergey** [comment]
> Если я что-то на одной машине сохраняю в Избранное, то зачем на другой машине мне должно приходить уведомление об этом?

Е:сли это именно я - то да. А вот если это "кто-то на той машине что-то сохраняет", то очень даже интересно быть об этом уведомленным.

**Comment by georgehazan** [comment]
> Если я что-то на одной машине сохраняю в Избранное, то зачем на другой машине мне должно приходить уведомление об этом?

Оно и не приходит. Проблема была в том, что в ICQ неправильно высчитывался контакт для Избранного, в результате чего не работала логика входящих сообщений (автосоздание окна, например). Коммит вообще не про уведомления, я в описании сразу написал, что уведомления не работают для себя
