### ISSUE TITLE
Если я меняю в опциях настройку, каким плагином показывать журнал, то кнопка OK срабатывает как "Apply"

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#3805]
Если я меняю в опциях настройку, каким плагином показывать журнал, то кнопка OK срабатывает как "Apply" - не закрывает окно опций.

**Comment by georgehazan** [comment]
Вкратце - нет. При этом перестраивается дерево опций, потому что часть страниц прячется или показывается, поэтому выполняется повторный вход в опции

**Comment by SM-Sergey** [comment]
Но это же неправильно - при OK окно всегда должно закрываться. При Apply - перестраиваться и открываться заново.

**Comment by georgehazan** [comment]
Согласен, что-то тут неправильно. Починил
