### ISSUE TITLE
ICQ: неверно работает Last seen в user details.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#3810]
Должно быть:
Если контакт в онлайне ("state":"online"), то "Last seen" - это "текущее время" - мы его видим прямо сейчас (при этом в протоколе "lastseen":0 или его нет вообще, совсем)
Если контакт в оффлайне  ("state":"offline"), то "Last seen" - берется из "lastseen", при этом если он "1388520000", ноль, либо его нет вообще, то это "Long time ago", а иначе это корректное время, когда был последний раз.

Сейчас: 
Для контактов со "state":"online" показывается какое-то непонятное старое время, либо вообще не показывается ничего. (и они не обязательно еще и в онлайне, но это другой тикет - #3802)
Для контактов со "state":"offline" и полным отсутствием "lastseen" - показывается какое то непонятное время откуда-то, хотя его не должно быть, это "Long time ago".

**Comment by georgehazan** [comment]
Все значительно запутаннее - ICQ всегда возвращает 0 для любого статуса, да еще и статусы путает
Автор R&Q говорит, что это можно выяснить специальным запросом через 2-3 секунды, но это пока не реализовано

**Comment by SM-Sergey** [comment]
> Все значительно запутаннее - ICQ всегда возвращает 0 для любого статуса,

Нет. Я уже второй день сниферю это, все отдается четко и без ошибок. И этот "второй запрос" строго всегда повторяет то, что было отдано сразу в "presence".  И информация в буддилисте тоже верная. Если не верите - могу накидать вырезок из нетлога по самое не балуй.

**Comment by SM-Sergey** [comment]
Вот последний приход контакта в онлайн:
{"response":{"statusCode":200, "statusText":"OK", "data":{"pollTime":1687, "ts":1699203178, "fetchBaseURL":"https://u.icq.net/bos/nbos-b002i/aim/fetchEvents?aimsid=024.0702289970.0750251579:300659245&rnd=1699203178.287745&seqNum=380666", "fetchTimeout":60, "timeToNextFetch":1, "events":[{"type":"presence", "eventData":{"aimId":"747814602", "displayId":"747814602", "friendly":"Eva Markova", **"state":"online"**, "userType":"icq", **"lastseen":0**}, "seqNum":380665}]}}}


Вот последний уход одного из контактов в оффлайн:

{"response":{"statusCode":200, "statusText":"OK", "data":{"pollTime":9852, "ts":1699202938, "fetchBaseURL":"https://u.icq.net/bos/nbos-b002i/aim/fetchEvents?aimsid=024.0702289970.0750251579:300659245&rnd=1699202938.132276&seqNum=380641", "fetchTimeout":60, "timeToNextFetch":1, "events":[{"type":"presence", "eventData":{"aimId":"747814602", "displayId":"747814602", "friendly":"Eva Markova", **"state":"offline"**, "userType":"icq", **"lastseen":1699202878**}, "seqNum":380640}]}}}

Я просмотрел больше сотни таких евентов и в логе миранды, и в снифферении оф. клиента, ни одного косяка пока не видел.

**Comment by georgehazan** [comment]
> Нет. Я уже второй день сниферю это, все отдается четко и без ошибок.

Тут люди третий год сидят и снифферят, и всё никак понять не могут. А тут раз - и победа :-)

**Comment by georgehazan** [comment]
> Я просмотрел больше сотни таких евентов и в логе миранды, и в снифферении оф. клиента, ни одного косяка пока не видел.

Если сессия разрывается, приходит offline. Если сессия не разрывается, то на оффлайн приходит онлайн, с lastseen:0, и понять это можно только некоторое время спустя

**Comment by SM-Sergey** [comment]
> Если сессия не разрывается, то на оффлайн приходит онлайн, с lastseen:0, и понять это можно только некоторое время спустя

Так это правильно - сейчас именно так и есть, пока сессия не разорвана - это онлайн. Чтобы увести контакт в оффлайн, надо чтобы все подключенные клиенты закрыли сессии. Таков текущий алгоритм работы аськи.

**Comment by georgehazan** [comment]
> Так это правильно - сейчас именно так и есть, пока сессия не разорвана - это онлайн.

Вот только ни веб, ни мобильные клиенты об этом не знают. Отсюда и проблемы

**Comment by SM-Sergey** [comment]
мобильный оф. клиент знает. За время наблюдения все уходы моб. клиента в оффлайн всегда вызывают приход "presence" с "state":"offline" и валидным "lastseen" в миранду. Ни разу еще не пришло "online". А у веб клиента я  не знаю способа уйти в оффлайн, кроме как его закрыть.

**Comment by SM-Sergey** [comment]
С моб. клиентом вообще хитро. Он бросает основное соединение, уходя в как бы оффлайн, который не оффлайн на самом деле, а полуспячка. И уйдя в это подполье держит некий другой коннект, по которому, не выходя из состояния оффлайна, получает уведомления о новых сообщениях. Но я пока не осилил его отсниферить с расшифровкой трафика.

**Comment by georgehazan** [comment]
> мобильный оф. клиент знает.

вкратце - нет. там сессия разрывается, если ручками выставить статус Offline, но так, понятное дело, ни один юзер делать не будет. Юзер просто смахивает гуй с экрана, а фоновый сервис продолжает работать в фоне, не разрывая сессии

**Comment by SM-Sergey** [comment]
> а фоновый сервис продолжает работать в фоне, не разрывая сессии

разрывая ту, в которой работал, пока был на экране. Но создавая некую другую, куда получает уведомления о новых сообщениях. Только прошедшей ночью это разбирал на текущей версии.

Но дело не в этом. Дело в том, что на эти переходы на сегодня всегда приходит "presence" с честными "offline" / "online", и с честным lastseen, ни одного исключения не поймано пока.

**Comment by SM-Sergey** [comment]
Вообще - это все не по теме. Это другой вопрос. Проблема, описанная в тикете, заключается в двух вещах:

1) надо инициализировать все статусы в клисте согласно "online" / "offline" из прихода буддилиста с сервера при переводе миранды из оффлайна в онлайн - это сразу излечит #3802, и половину этого тикета. Потому, что нет особо претензий к переходам из онлайна в оффлайн и наоборот по ходу дела, а все проблемы растут из отсутствия начальной инициализации из буддилиста.

2) Для онлайн контактов (и не суть важно почему он онлайн) Last Seen в юзер-деталях должен быть "прямо сейчас", т.е. текущее время - мы же его видим в онлайне.

3). Определенные значения из Lastseen надо интерпретировать не как время-дату, а как "Long time ago".

**Comment by dartraiden** [comment]
Следует добавить несколько проверок:

1) если прилетело 1388520000, то в юзеринфо не выводить дату последнего захода
https://forum.ru-board.com/topic.cgi?forum=5&topic=50156&start=2060#8

2) если прилетело 0 и контакт не в сети, то тоже не выводить

3) если прилетело 0 и контакт в сети, вывести текущие дату и время, как сейчас делает "в сети с"

**Comment by dartraiden** [comment]
> а миранда чем хуже?

мы не можем в значение типа LONG записать строку "Long time ago"

**Comment by SM-Sergey** [comment]
Ну можно наверное и всегда строку сделать. Просто придется аське дату форматировать... В общем, наверное, варианты то есть, если подумать. Ну это, ясное дело, ваша прерогатива, делать как удобно. Я просто сказал, как оно есть алгоритмически сейчас.

**Comment by SM-Sergey** [comment]
... или сделать два разных свойства (поля в БД, ну или как там оно, я не знаю) - если есть новое, то отображать современным способом, если нету, то старым.
