### ISSUE TITLE
Yahoo file transfer fails to start if connected to Yahoo for too long.

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#382]
**Reported by Ratha on 9 May 2015 09:47 UTC**
Bug: Yahoo file transfers will fail to start (send or receive) if you have been connected to yahoo for ~24 hours without logging off/on again. (Might not take the full 24 hours of being connected to break the file transfers, but its easy to duplicate after 24 hours. Bug has existed since before Miranda 10.16 and may be an issue with prolonged Yahoo server connectivity.)

Fix: Logging off and then back on again will allow file transfers to function, can both send and receive files after reconnecting.

**Comment by aunsane** [comment]
Yahoo protocol was depricated b0f3e30460fc26ef4fe59bc161b0fddd8eeb9a08.
