### ISSUE TITLE
CurrencyRates: не работает текст всплывающих окон

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3834]
Настройки CurrencyRates → Дополнительные настройки → Настройки всплывающих окон

Кнопка "Тест" ничего не делает.

И, честно говоря, этот диалог с цветами попапов я бы перенес в настройки попапов.

**Comment by georgehazan** [comment]
> И, честно говоря, этот диалог с цветами попапов я бы перенес в настройки попапов.

Оно там как-то привязано к потрохам предыдущего окна, вряд ли получится вынести это просто так в отдельное окно
