### ISSUE TITLE
MirandaG15: не работает кнопка "Благодарности"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3846]
В разделе "Информация", кроме этой неработающей кнопки что-то должно быть?

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/89ef2f24-b116-421d-b003-1f2533a062ec)

**Comment by georgehazan** [comment]
Оно выводит текст на экран клавиатуры.
Без клавиатуры не пашет
