### ISSUE TITLE
Gmail Multiple Notifier - default browser problem

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#385]
**Reported by Tomaso on 6 Jun 2015 20:31 UTC**
The "Login using default browser" option doesn't work.
It always launches Internet Explorer.

(Tested with latest stable and latest development build)

**Comment by dartraiden** [comment]
Yes, IDC_SYSDEF and IDC_USEIE are equivalent:

```
case WM_COMMAND:
	switch (LOWORD(wParam)) {
		case IDC_SYSDEF:
		case IDC_USEIE:
		case IDC_STARTPRG:
			ShowControl = IsDlgButtonChecked(hwndDlg, IDC_STARTPRG) ? SW_SHOW : SW_HIDE;
			ShowWindow(GetDlgItem(hwndDlg, IDC_PRG), ShowControl);
			ShowWindow(GetDlgItem(hwndDlg, IDC_PRGBROWSE), ShowControl);
			SendMessage(GetParent(hwndDlg), PSM_CHANGED, 0, 0);
			break;
```

**Comment by Robyer** [comment]
@dartraiden This part of code handles only enabling of "Apply" button in options window. So this is actually correct, but there should be some other method, that handles the opening of links (I can't look into code right now).

**Comment by dartraiden** [comment]
@Robyer, yes you are right.

options.rc:
`CONTROL         "Login using default browser",IDC_SYSDEF,"Button",BS_AUTORADIOBUTTON,82,123,206,10`

options.cpp:
```
if (IsDlgButtonChecked(hwndDlg, IDC_SYSDEF) == BST_CHECKED)
	opt.OpenUsePrg = 0;
```

utility.cpp:
```
else if (opt.OpenUsePrg == 0)
	strKey = strDefault;
```

`char strDefault[] = "https\\shell\\open\\command";`
```

	// Open the registry
	if (RegOpenKeyExA(HKEY_CLASSES_ROOT, strKey, 0, KEY_READ, &hKey) == ERROR_SUCCESS) {
		// Data size
		DWORD cbData = 0;
		// Get the default value
		if (RegQueryValueExA(hKey, NULL, NULL, NULL, NULL, &cbData) == ERROR_SUCCESS && cbData > 0) {
			if (RegQueryValueExA(hKey, NULL, NULL, NULL, (LPBYTE)str, &cbData) == ERROR_SUCCESS) {
				if ((strKey = strstr(str, "%1")) != NULL)
					*(strKey--) = '\0';
				if ((strKey = strstr(str, "-")) != NULL)
					*(strKey--) = '\0';
				RegCloseKey(hKey);
				return TRUE;
			}
		}
	}
	return FALSE;
```

**Comment by Robyer** [comment]
I'm closing this as topic is so old and it works for dartraiden.
