### ISSUE TITLE
SecureIM: тоже перевод не помещается.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#3853]
![2023-11-06 18_24_42-Issues · miranda-ng_miranda-ng — Mozilla Firefox](https://github.com/miranda-ng/miranda-ng/assets/34127439/783122dc-9589-4267-8c18-54d49071d472)
![2023-11-06 18_25_45-Issues · miranda-ng_miranda-ng — Mozilla Firefox](https://github.com/miranda-ng/miranda-ng/assets/34127439/f49299e8-37c5-4534-a5cc-360464f953c0)

**Comment by dartraiden** [comment]
https://github.com/miranda-ng/miranda-ng/issues/3859
там больше
