### ISSUE TITLE
SendSS: пропал перевод у кнопки

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3864]
Внизу окна кнопка с галкой

"Fill description textbox."

**Comment by georgehazan** [comment]
Такой строки нет в ланге, потому что в ресурсе оно с & спереди

**Comment by georgehazan** [comment]
ланг надо будет подкрутить

**Comment by dartraiden** [comment]
В ленге она как и в ресурсе с амперсандом

[&Fill description textbox.]
&Заполнить строки описания.
