### ISSUE TITLE
SkypeStatusChange: сделать нормальные чекбоксы

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3868]
А не вот эти чёрные жирные с каким-то волоском в левом верхнем углу

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/f599478f-f62e-4be5-a1cc-8de5727c477f)

**Comment by georgehazan** [comment]
Волосок - убери & из строки

**Comment by dartraiden** [comment]
Теперь чекбоксы вообще пропали

ghazan, 08.11.2023
[21:12] надо стиль включить у контрола - CHECKBOXES
[21:13] в студии в пропертих

**Comment by dartraiden** [comment]
Чекбоксы появились, но

1) при клике по родительскому дочерние пропадают
2) не проставляются галочки в чекбоксах
