### ISSUE TITLE
При смене языка настройки горячих клавиш уезжают в другую секцию

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3876]
Английский. Как видно, у жаббера 4 хоткея, остальные в Main

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/7150d8c4-f1f0-4f20-89c9-de1494038c2f)

Русский. Большая часть уехала в жаббер, в Главный осталось 2 хоткея

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/4d31940a-ec61-4f50-a465-60e0314d7bd2)

**Comment by georgehazan** [comment]
для полноты картины надо затолкать строку Main в перевод ядра
