### ISSUE TITLE
Status messages - кракозябры

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#3879]
Я не уверен, что это баг, но точно знаю, что в неком прошлом тут были русские сообщения при английском лангпаке. Заново можно написать по-русски.
![2023-11-07 20_36_03-Miranda NG options](https://github.com/miranda-ng/miranda-ng/assets/34127439/d858a3aa-2ecc-4b3d-84c4-525a279e28c6)

**Comment by dartraiden** [comment]
Я с этим сталквивался несколько лет назад, но так и не понял, как это стабильно воспроизводить.

**Comment by dartraiden** [comment]
Просто надо убить ветку SRAway в базе, куда записались кракозябры.

**Comment by SM-Sergey** [comment]
Стер, все ОК.
А может добавить кнопку "Reset to default" ?

**Comment by dartraiden** [comment]
Хорошая идея. Пусть стирает этот модуль из базы.
