### ISSUE TITLE
Telegram: при убийстве сессии создаётся второе Избранное

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3881]
В Миранду заведен телеграм, в клисте есть голубенькое Избранное.

Через оф. клиент убиваю сессию.

Миранда при следующем входе запрашивает код подтверждения.

После его ввода в клист въезжает второе Избранное.

**Comment by georgehazan** [comment]
нет, не въезжает.
у меня не повторилось

**Comment by dartraiden** [comment]
Тоже перестало воспроизводиться.

**Comment by dartraiden** [comment]
Удалось воспроизвести.

Телеграм у меня заведён в актуальный ночник. Всё работает корректно. Выключаю ночник.

Параллельно ставлю стаблю, создаю в ней новый профиль и импортом втягиваю все контакты и все сообщения (без настроек) с ночника.

Вывожу в стабле телеграм в онлайн. Он запрашивает код подтверждения. Очевидно, потому что импорт втянул лишь то, что в базе, а td.binlog не втянул. Ввожу код, телеграм влогинивается. Выключаю стаблю.

Теперь снова включаю ночник. Он просит код. Ввожу и вот тут Избранное задваивается.

**Comment by georgehazan** [comment]
> Теперь снова включаю ночник. Он просит код.

А почему, собственно? Зачем ему просить лог, если он уже был заведен.

> Ввожу и вот тут Избранное задваивается.

Нетворк лог можешь сделать? Чтобы в нем было New contact added

**Comment by dartraiden** [comment]
Ненавижу... как только включил нетлог, оно опять перестало глючить.
