### ISSUE TITLE
Telegram: менять имя контакта "Saved messages" при изменении языка в Миранде

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3884]
В официальном клиенте при смене языка контакт  "Saved messages" меняется на "Избранное".

В Миранде нет - с каким языком он создался, на таком языке он и останется.

**Comment by georgehazan** [comment]
Оно в базу записано, как это менять

**Comment by georgehazan** [comment]
Меняется только при старте Миранды
