### ISSUE TITLE
Описания некоторых значков перестали переводиться

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3887]
![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/ff52b62f-b018-471d-8630-77c8450afa17)

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/67997963-d514-4111-abc4-c0097de8486a)

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/bb40bfe7-ed72-4c70-bf02-65da39590372)

**Comment by dartraiden** [comment]
На первом скрине всё поправилось, на втором и третьем так и осталось не переведено.

**Comment by georgehazan** [comment]
хер его знает... в гите в переводах есть эта строка, а в общем ланг паке нету...

**Comment by georgehazan** [comment]
надо английский пак перестроить тоже
