### ISSUE TITLE
Jabber: перестали переводиться значки Открыть, Сохранить и Сервер

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3895]
![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/904a622f-e44a-465b-a488-473b436760f0)

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/a6d2f012-3d38-4924-a07f-46210337b027)

**Comment by georgehazan** [comment]
duplicate of #3901
