### ISSUE TITLE
FB connecting after manual disconnect - global status list.

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#390]
**Reported by borut on 25 Jun 2015 09:08 UTC**
After the manual disconnection of network protocols by the general election network status (screen), FB automatically connects and it should not.

http://vi.miranda-ng.org/detail/borut

![fbconn](https://cloud.githubusercontent.com/assets/5046855/21113879/3d4b54ea-c0bc-11e6-8c6c-accc5ba40f61.png)

**Comment by georgehazan** [comment]
**Modified by borut on 25 Jun 2015 09:09 UTC**

**Comment by georgehazan** [comment]
**Comment by robyer on 27 Jun 2015 19:16 UTC**
I think it will be somehow related to KeepStatus plugin. It works correctly for me (I'm not using KeepStatus).

This problem is affecting only Facebook plugin? Could you try to find out what setting in KeepStatus is causing it?

**Comment by georgehazan** [comment]
**Comment by borut on 27 Jun 2015 21:06 UTC**
I do not know what is the problem. I have set the plug on the "check connection". With GG and Skype protocol does not have this problem.

**Comment by georgehazan** [comment]
**Comment by robyer on 17 Apr 2016 11:25 UTC**
Do you still have this problem? Because I can't reproduce it.

**Comment by georgehazan** [comment]
**Comment by borut on 3 May 2016 18:42 UTC**
Please close. Not Use FB in Miranda NG.

**Comment by georgehazan** [comment]
**Modified by robyer on 3 May 2016 19:18 UTC**

**Comment by georgehazan** [comment]
**Comment by robyer on 8 May 2016 15:31 UTC**
"So I started with everything offline and then changed global to online and when protocols was connecting I changed global to offline. While jabber swithced to offline instantly fb was still trying to connect. After turning to online fb switched to offline like it should but after few seconds started to reconnecting. Log is showing that keepsattus for some reason thought that fb lost connection" (goraf)


Log:
[04C8](14:38:55) KeepStatus: assigning status 40072 to Facebook_1
[04C8](14:38:55) KeepStatus: assigning status 40072 to JABBER_1
[04C8](14:38:57) KeepStatus: assigning status 40071 to Facebook_1
[04C8](14:38:57) KeepStatus: assigning status 40071 to JABBER_1
[31B8](14:38:57) SSL failure recieving data (10053)
[04C8](14:39:01) KeepStatus: assigning status 40072 to Facebook_1
[04C8](14:39:02) KeepStatus: connection lost! (Facebook_1)
[04C8](14:39:12) KeepStatus: assigning status 40072 to Facebook_1
[04C8](14:39:17) KeepStatus: stop checking (success)

**Comment by RozekPoland** [comment]
Hello!
I have encountered this problem as well. KeepStatus, which currently is a part of StatusManager plugin, causes it. All the details for reproduction have been provided by @georgehazan.
KeepStatus reconnects FB plugin when I right-click Miranda icon in tray and select Status/Offline. All the other plugins do as they are supposed to - they go offline, besides FB plugin. However, if I click FB plugin icon in Contacts List and set it to Offline then it works properly and goes offline. It occurs to me that there is an issue with KeepStatus and Status/Offline option that pushes FB plugin to reconnecting.

**Comment by georgehazan** [comment]
@RozekPoland by me? :) that's the very old bug which was imported from our old tracker to GitHub, that's why all comments are marked as mine, but I never had any relation to the bug

**Comment by RozekPoland** [comment]
Ah, now I understand why your posts in this topic look like one-sided conversion :)
Anyway, is there any fix to this bug?

**Comment by dartraiden** [comment]
> Anyway, is there any fix to this bug?

Please test our new FB protocol (landed to stable version yesterday). If this bug still exist?
