### ISSUE TITLE
YAMN: "persistent messafge"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3900]
1) @georgehazan  посмотри, пожалуйста, в коде, что делает эта опция? если бесконечный таймаут попапа, то чем не устраивает значение "0", зачем для это отдельная опция?

2) эта опция не должна засеряться с прочими вместе, если попап отключён?

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/8cad31e9-e48e-450b-89aa-0fa7ee5fd18f)

**Comment by georgehazan** [comment]
// Persistant messgage. This means, when a situation occurs (e.g. new mail) and message is displayed, it is not destroyed when YAMN_ACC_MSG is not set - хрен его знает, что это означает, явно не про длительность попапа.

**Comment by georgehazan** [comment]
засерение поправил
