### ISSUE TITLE
Text in Rename and Delete options for subgroups in context menu

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#3915]
Steps to reproduce:
1. Create group in contact list.
2. Create subgroup.
3. Open context menu for subgroup.

Actual behavior:
1. Options "Rename group" and "Delete group"

Expected behavior:
"Rename subgroup" and "Delete subgroup" or (I like it more) "Rename <(sub)group-name>" and "Delete <(sub)group-name>"

**Comment by georgehazan** [comment]
Subgroups are groups too, I don't see any contradictions
