### ISSUE TITLE
IRC: staggering when (re)join to channels

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#3916]
**Is your feature request related to a problem? Please describe.**
When Miranda rejoins in many channels server stops to accept a requests and returns `Target change too fast. Please wait xx seconds`. User should wait.

**Describe the solution you'd like**
Staggering. IRC OPs told that client sends /join ch1, ch2, ch2... and they suggested /join ch1, /join ch2, /join ch2... Add new settings to set an interval between joining to channels.

**Comment by georgehazan** [comment]
you can write any Perform script in Options - Advanced and disable autojoin for channels

**Comment by JeanPaulLucien** [comment]
Other clients do not require a special knowledge from user, because this feature is built-in.
