### ISSUE TITLE
Убрать чувствительность к регистру в поиске NotesReminders

### ISSUE THREAD

**Issue by C1eriC** [miranda-ng/miranda-ng#3927]
Если возможно, было бы здорово чувствительность к регистру в поиске NotesReminders.

**Comment by georgehazan** [comment]
в каком месте? можно скриншот

**Comment by C1eriC** [comment]
![Безымянный](https://github.com/miranda-ng/miranda-ng/assets/10571305/394a8a0c-1134-4b3e-985c-127f5ee2f62b)
