### ISSUE TITLE
ICQ: Исходящий файл раздвоился, а затем краш.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#3928]
Я отправил файл (не думаю, что это важно, но нажав скрепку в окне сообщений). В журнале и в истории почему-то появилось две записи о нем.
Затем мне прислали спасибо. Затем я сделал скриншот, и одновременно с этим оно упало.
![2023-11-15 15_45_59-Alex (Offline)](https://github.com/miranda-ng/miranda-ng/assets/34127439/5082afcf-0407-46a7-b04b-572f8f54bdf5)
[crash20231115153602.txt](https://github.com/miranda-ng/miranda-ng/files/13364669/crash20231115153602.txt)

**Comment by georgehazan** [comment]
раздвоение не понял, как повторять

**Comment by SM-Sergey** [comment]
Можно сделать Load Server History - вторая его копия приедет и отобразится. Но от этого не крашится.
В тот раз почему-то сервер сам решил прислать ссылку на закачанный мной же файл, я больше так повторить не смог
