### ISSUE TITLE
ICQ: Онлайн файл может не преобразовываться в файл, а оставаться "левой ссылкой".

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#3934]
Что-то видимо пошло не так, и из двух пришедших картинок, присланных мне, пока миранда была в оффлайне, одна отобразилась в виде левой ссылки и не преобразовалась в оффлайн-файл.
Нужен какой-то способ обновить такие неудачные транзакции, с перезапросом файла с сервера. Или не писать их в БД вообще, чтобы они при следующей загрузке оффлайн-сообщений доехали сами, или еще как то.

![2023-11-16 13_26_11-ElectroVoicer (Offline)](https://github.com/miranda-ng/miranda-ng/assets/34127439/d3e1e9a1-895a-478b-b278-dca0317ebe77)

[netlog.txt](https://github.com/miranda-ng/miranda-ng/files/13376384/netlog.txt)

**Comment by georgehazan** [comment]
добавил логов, если оно появится еще раз - нужно новый нетворк лог приаттачить
там сервер что-то такое вернул непонятное

**Comment by SM-Sergey** [comment]
> там сервер что-то такое вернул непонятное

ИМХО, там вообще связь оборвалась после запроса временной ссылки на файл, и до прихода ответа, и сервер ничего не смог вернуть. А потом уже был переконнект кипстатуса.

Я конечно еще понаблюдаю, но на такое совпадение нарваться еще раз - это надо очень-очень умудриться.

**Comment by georgehazan** [comment]
В NewStory появился в логе пункт "Convert into a file transfer" для всех таких событий
