### ISSUE TITLE
Crash in SpellCheck plugin in Miranda NG 0.96.4 build #26371

### ISSUE THREAD

**Issue by de77** [miranda-ng/miranda-ng#3935]
After upgrade of Miranda to last version 0.96.4 build #26371 with all used plugins, such as dbeditorpp, historypp, popupplus, 
seenplugin, spellchecker, tipper and whousesmyfiles i've got crashes of Miranda when double-clocking on contact in contact list.
OS Windows XP SP3.

### Expected behavior
I'm expencting, that message session window will be shown.

### Actual behavior
Message session window is shows and then Miranda is crashes.

### Does it work in stable version?
It was worked on previous stable version 0.96.3.

### Steps to reproduce that behavior
 * Launch Miranda.
 * Double-click on contact.
 * That's is.

I've downgrade Libs\hunspell.mir to version for version 0.96.3 (using Plugins\SpellChecker.dll for 0.96.4) and in such conditions Miranda is working fine.

 * Attach a crash report if you are experiencing crashes (It includes VersionInfo as well).

Symbols mode: stable version without symbols

Miranda Crash Report from 16 Nov 2023 11:58:54. Crash Dumper v.0.2.0.2
Exception: Access Violation at address 121ED92D. Reading from address 00000000.

Stack Trace:
---------------------------------------------------------------
121ED92D (hunspell 121E0000): (filename not available) (0): (function-name not available)

CPU: Intel(R) Core(TM) i3 CPU 540 @ 3.07GHz [x86 Family 6 Model 37 Stepping 2] [DEP Enabled] [4 CPUs]
Installed RAM: 3582 MBytes
Microsoft Windows XP Professional Service Pack 3 (build 2600)
Internet Explorer: 8.0.6001.18702 (build 86001)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian

Miranda NG Version: 0.96.4 build #26371 (8208d3f157)
Build time: 15 Nov 2023 20:23:25
Profile: D:\Program Files\Miranda NG.0.96.4\Profiles\profile\profile.dat
Database driver: SQLite database driver
Language pack: No language pack installed
Service Mode: No
SRMM Log Viewer: built-in

Active Plugins (19):
¤ AVS.dll v.0.98.1.6 [15 Nov 2023 20:23:31] - Avatar service 
¤ CrashDumper.dll v.0.2.0.2 [15 Nov 2023 20:24:09] - Crash dumper 
¤ Db_autobackups.dll v.0.1.0.7 [15 Nov 2023 20:23:47] - Db autobackuper 
¤ DbChecker.dll v.0.96.3.1 [15 Nov 2023 20:25:26] - Database checker 
¤ DbEditorPP.dll v.4.1.0.4 [15 Nov 2023 20:24:08] - Database editor++ 
¤ Dbx_sqlite.dll v.0.96.4.1 [15 Nov 2023 20:25:21] - Miranda NG SQLite database driver 
¤ Dummy.dll v.0.2.0.1 [15 Nov 2023 20:24:54] - Dummy protocol 
¤ historypp.dll v.1.5.1.5 [15 Nov 2023 20:28:16] - History++ 
¤ ICQ.dll v.0.96.4.1 [15 Nov 2023 20:25:33] - ICQ-WIM protocol 
¤ Jabber.dll v.0.95.11.1 [15 Nov 2023 20:23:58] - Jabber protocol 
¤ NewEventNotify.dll v.0.2.2.7 [15 Nov 2023 20:24:05] - NewEventNotify 
¤ PluginUpdater.dll v.0.2.1.7 [15 Nov 2023 20:24:17] - Plugin updater 
¤ PopupPlus.dll v.2.1.3.0 [15 Nov 2023 20:24:05] - Popup plus 
¤ SeenPlugin.dll v.5.0.5.6 [15 Nov 2023 20:23:45] - Last seen 
¤ SpellChecker.dll v.0.2.6.6 [15 Nov 2023 20:24:34] - Spell checker 
¤ StatusManager.dll v.1.2.0.6 [15 Nov 2023 20:25:21] - Status manager 
¤ TabSRMM.dll v.3.6.2.6 [15 Nov 2023 20:23:36] - TabSRMM 
¤ Tipper.dll v.2.1.0.8 [15 Nov 2023 20:23:51] - Tipper 
¤ WhoUsesMyFiles.dll v.0.1.0.4 [15 Nov 2023 20:24:09] - Who Use My Files 

Loaded Modules:
-------------------------------------------------------------------------------
D:\Program Files\Miranda NG.0.96.4\Miranda32.exe  00400000 - 0040C000 v.0.96.4.0 [15 Nov 2023 20:23:25]
C:\WINDOWS\system32\ntdll.dll  7C900000 - 7C9B3000 v.5.1.2600.6055 [9 Dec 2010 17:15:19]
C:\WINDOWS\system32\kernel32.dll  7C800000 - 7C8F8000 v.5.1.2600.5781 [21 Mar 2009 16:09:06]
C:\WINDOWS\system32\USER32.dll  7E360000 - 7E3F1000 v.5.1.2600.5512 [14 Apr 2008 20:40:48]
C:\WINDOWS\system32\GDI32.dll  77F10000 - 77F59000 v.5.1.2600.5698 [23 Oct 2008 14:42:24]
C:\WINDOWS\system32\SHELL32.dll  7C9C0000 - 7D1DB000 v.6.0.2900.6072 [21 Jan 2011 16:44:10]
C:\WINDOWS\system32\ADVAPI32.dll  77DC0000 - 77E6C000 v.5.1.2600.5755 [9 Feb 2009 12:54:17]
C:\WINDOWS\system32\RPCRT4.dll  77E70000 - 77F03000 v.5.1.2600.6022 [16 Aug 2010 10:45:15]
C:\WINDOWS\system32\Secur32.dll  77FE0000 - 77FF1000 v.5.1.2600.5834 [25 Jun 2009 10:27:19]
C:\WINDOWS\system32\msvcrt.dll  77C00000 - 77C58000 v.7.0.2600.5512 [14 Apr 2008 20:40:42]
C:\WINDOWS\system32\SHLWAPI.dll  77F60000 - 77FD6000 v.6.0.2900.5912 [8 Dec 2009 11:25:26]
C:\WINDOWS\system32\IMM32.DLL  76360000 - 7637D000 v.5.1.2600.5512 [14 Apr 2008 20:40:38]
C:\WINDOWS\system32\LPK.DLL  62F00000 - 62F09000 v.5.1.2600.5512 [14 Apr 2008 20:40:40]
C:\WINDOWS\system32\USP10.dll  75540000 - 755AB000 v.1.420.2600.5969 [16 Apr 2010 17:38:40]
C:\WINDOWS\WinSxS\x86_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.2600.6028_x-ww_61e65202\comctl32.dll  773C0000 - 774C3000 v.6.0.2900.6028 [23 Aug 2010 18:12:35]
D:\Program Files\Miranda NG.0.96.4\libs\ucrtbase.dll  10000000 - 10120000 v.10.0.19041.789 [9 Apr 2021 15:49:10]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-errorhandling-l1-1-0.dll  003A0000 - 003A3000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-heap-l1-1-0.dll  003C0000 - 003C3000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-processthreads-l1-1-0.dll  003D0000 - 003D3000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-libraryloader-l1-1-0.dll  003E0000 - 003E3000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-synch-l1-1-0.dll  003F0000 - 003F3000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-debug-l1-1-0.dll  008F0000 - 008F3000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-processenvironment-l1-1-0.dll  00900000 - 00903000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-file-l1-1-0.dll  00910000 - 00914000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-string-l1-1-0.dll  00920000 - 00923000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-localization-l1-2-0.dll  00930000 - 00933000 v.10.0.14393.795 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-datetime-l1-1-0.dll  00940000 - 00943000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-sysinfo-l1-1-0.dll  00950000 - 00953000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-processthreads-l1-1-1.dll  00960000 - 00963000 v.10.0.14393.795 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-console-l1-1-0.dll  00970000 - 00973000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-handle-l1-1-0.dll  00980000 - 00983000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-file-l1-2-0.dll  00990000 - 00993000 v.10.0.14393.795 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-namedpipe-l1-1-0.dll  009A0000 - 009A3000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-timezone-l1-1-0.dll  009B0000 - 009B3000 v.10.0.14393.795 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-file-l2-1-0.dll  009C0000 - 009C3000 v.10.0.14393.795 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-synch-l1-2-0.dll  009D0000 - 009D3000 v.10.0.14393.795 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-profile-l1-1-0.dll  009E0000 - 009E3000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-memory-l1-1-0.dll  009F0000 - 009F3000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-util-l1-1-0.dll  00A00000 - 00A03000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-rtlsupport-l1-1-0.dll  00A10000 - 00A13000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-core-interlocked-l1-1-0.dll  00A20000 - 00A23000 v.10.0.10586.15 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-crt-runtime-l1-1-0.dll  00A30000 - 00A34000 v.10.0.14393.795 [14 May 2021 11:55:56]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-crt-stdio-l1-1-0.dll  00A40000 - 00A44000 v.10.0.14393.795 [14 May 2021 11:55:56]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-crt-locale-l1-1-0.dll  00A50000 - 00A53000 v.10.0.14393.795 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-crt-heap-l1-1-0.dll  00A60000 - 00A63000 v.10.0.14393.795 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\VCRUNTIME140.dll  00A70000 - 00A83000 v.14.16.27033.0 [18 May 2022 0:15:35]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-crt-string-l1-1-0.dll  00A90000 - 00A94000 v.10.0.14393.795 [14 May 2021 11:55:56]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-crt-convert-l1-1-0.dll  00AA0000 - 00AA4000 v.10.0.14393.795 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\mir_app.mir  12C40000 - 12D25000 v.0.96.4.26371 [15 Nov 2023 20:23:24]
D:\Program Files\Miranda NG.0.96.4\libs\libcrypto-1_1.mir  12300000 - 12573000 v.1.1.1.23 [9 Oct 2023 16:34:06]
C:\WINDOWS\system32\WS2_32.dll  71A90000 - 71AA7000 v.5.1.2600.5512 [14 Apr 2008 20:40:48]
C:\WINDOWS\system32\WS2HELP.dll  71A80000 - 71A88000 v.5.1.2600.5512 [14 Apr 2008 20:40:48]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-crt-time-l1-1-0.dll  00AB0000 - 00AB3000 v.10.0.14393.795 [14 May 2021 11:55:56]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-crt-utility-l1-1-0.dll  00AC0000 - 00AC3000 v.10.0.14393.795 [14 May 2021 11:55:56]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-crt-filesystem-l1-1-0.dll  00AD0000 - 00AD3000 v.10.0.14393.795 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-crt-environment-l1-1-0.dll  00AE0000 - 00AE3000 v.10.0.14393.795 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-crt-math-l1-1-0.dll  00AF0000 - 00AF5000 v.10.0.14393.795 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\libssl-1_1.mir  12B00000 - 12B87000 v.1.1.1.23 [9 Oct 2023 16:34:34]
C:\WINDOWS\system32\CRYPT32.dll  77A70000 - 77B06000 v.5.131.2600.6154 [28 Sep 2011 9:06:47]
C:\WINDOWS\system32\MSASN1.dll  77B10000 - 77B22000 v.5.1.2600.5875 [4 Sep 2009 23:04:58]
C:\WINDOWS\system32\WINMM.dll  76B20000 - 76B4E000 v.5.1.2600.6160 [14 Oct 2011 16:47:28]
C:\WINDOWS\system32\UxTheme.dll  5B260000 - 5B298000 v.6.0.2900.5512 [14 Apr 2008 20:40:48]
C:\WINDOWS\system32\COMDLG32.dll  76380000 - 763C9000 v.6.0.2900.5512 [14 Apr 2008 20:40:36]
C:\WINDOWS\system32\ole32.dll  774D0000 - 7760E000 v.5.1.2600.6168 [1 Nov 2011 18:07:12]
D:\Program Files\Miranda NG.0.96.4\libs\FreeImage.mir  12000000 - 120EC000 [15 Nov 2023 20:23:17]
D:\Program Files\Miranda NG.0.96.4\libs\zlib.mir  13000000 - 13019000 v.1.2.13.0 [15 Nov 2023 20:22:57]
D:\Program Files\Miranda NG.0.96.4\libs\MSVCP140.dll  00B00000 - 00B6F000 v.14.16.27033.0 [18 May 2022 0:15:35]
D:\Program Files\Miranda NG.0.96.4\libs\mir_core.mir  12E20000 - 12E4C000 v.0.96.4.26371 [15 Nov 2023 20:22:59]
C:\WINDOWS\system32\WTSAPI32.dll  76F40000 - 76F48000 v.5.1.2600.5512 [14 Apr 2008 20:40:48]
C:\WINDOWS\system32\WINSTA.dll  76330000 - 76340000 v.5.1.2600.5512 [14 Apr 2008 20:40:48]
C:\WINDOWS\system32\NETAPI32.dll  5BD50000 - 5BDA5000 v.5.1.2600.5694 [15 Oct 2008 18:37:44]
D:\Program Files\Miranda NG.0.96.4\libs\api-ms-win-crt-multibyte-l1-1-0.dll  00B70000 - 00B75000 v.10.0.14393.795 [14 May 2021 11:55:55]
D:\Program Files\Miranda NG.0.96.4\libs\libjson.mir  128E0000 - 128ED000 [15 Nov 2023 20:23:29]
C:\WINDOWS\system32\VERSION.dll  77BF0000 - 77BF8000 v.5.1.2600.5512 [14 Apr 2008 20:40:48]
C:\WINDOWS\system32\MSCTF.dll  746E0000 - 7472C000 v.5.1.2600.5512 [14 Apr 2008 20:40:40]
C:\WINDOWS\system32\msctfime.ime  75310000 - 7533E000 v.5.1.2600.5512 [14 Apr 2008 20:39:22]
C:\WINDOWS\system32\CLBCATQ.DLL  76FC0000 - 7703F000 v.2001.12.4414.700 [14 Apr 2008 20:40:36]
C:\WINDOWS\system32\COMRes.dll  77040000 - 77107000 v.2001.12.4414.700 [14 Apr 2008 20:40:36]
C:\WINDOWS\system32\OLEAUT32.dll  77110000 - 7719B000 v.5.1.2600.6058 [20 Dec 2010 19:32:04]
D:\Program Files\Miranda NG.0.96.4\Plugins\CrashDumper.dll  16680000 - 16690000 v.0.2.0.2 [15 Nov 2023 20:24:09]
C:\WINDOWS\system32\dbghelp.dll  59C60000 - 59D01000 v.5.1.2600.5512 [14 Apr 2008 20:40:36]
D:\Program Files\Miranda NG.0.96.4\Plugins\DbChecker.dll  16820000 - 1682B000 v.0.96.3.1 [15 Nov 2023 20:25:26]
D:\Program Files\Miranda NG.0.96.4\Plugins\DbEditorPP.dll  16840000 - 1685E000 v.4.1.0.4 [15 Nov 2023 20:24:08]
D:\Program Files\Miranda NG.0.96.4\Plugins\Dbx_sqlite.dll  168C0000 - 168CD000 v.0.96.4.1 [15 Nov 2023 20:25:21]
D:\Program Files\Miranda NG.0.96.4\libs\sqlite3.mir  12EE0000 - 12F6B000 [15 Nov 2023 20:23:44]
D:\Program Files\Miranda NG.0.96.4\Core\stdcrypt.dll  13060000 - 1306C000 v.0.96.4.26371 [15 Nov 2023 20:23:04]
C:\WINDOWS\system32\rsaenh.dll  68000000 - 68036000 v.5.1.2600.5507 [13 Apr 2008 22:07:58]
C:\WINDOWS\system32\Msftedit.dll  4B460000 - 4B4E6000 v.5.41.15.1515 [14 Apr 2008 20:40:42]
D:\Program Files\Miranda NG.0.96.4\Core\stdclist.dll  13040000 - 1304F000 v.0.96.4.26371 [15 Nov 2023 20:23:02]
D:\Program Files\Miranda NG.0.96.4\Plugins\AVS.dll  161A0000 - 161B3000 v.0.98.1.6 [15 Nov 2023 20:23:31]
D:\Program Files\Miranda NG.0.96.4\Plugins\Db_autobackups.dll  168E0000 - 168EF000 v.0.1.0.7 [15 Nov 2023 20:23:47]
D:\Program Files\Miranda NG.0.96.4\Plugins\Dummy.dll  16900000 - 16908000 v.0.2.0.1 [15 Nov 2023 20:24:54]
D:\Program Files\Miranda NG.0.96.4\Plugins\historypp.dll  16D00000 - 16EEC000 [15 Nov 2023 20:28:16]
C:\WINDOWS\system32\msimg32.dll  76350000 - 76355000 v.5.1.2600.5512 [14 Apr 2008 20:40:42]
C:\WINDOWS\system32\winspool.drv  72FC0000 - 72FE6000 v.5.1.2600.5512 [14 Apr 2008 20:41:18]
C:\WINDOWS\system32\RICHED20.DLL  74DF0000 - 74E5D000 v.5.30.23.1230 [14 Apr 2008 20:40:44]
D:\Program Files\Miranda NG.0.96.4\Plugins\ICQ.dll  17220000 - 1723A000 v.0.96.4.1 [15 Nov 2023 20:25:33]
D:\Program Files\Miranda NG.0.96.4\Plugins\Jabber.dll  173E0000 - 17472000 v.0.95.11.1 [15 Nov 2023 20:23:58]
D:\Program Files\Miranda NG.0.96.4\libs\libsignal.mir  129A0000 - 129D0000 [15 Nov 2023 20:23:35]
C:\WINDOWS\system32\DNSAPI.dll  76F10000 - 76F37000 v.5.1.2600.6089 [3 Mar 2011 8:54:55]
D:\Program Files\Miranda NG.0.96.4\Plugins\NewEventNotify.dll  17A20000 - 17A2B000 v.0.2.2.7 [15 Nov 2023 20:24:05]
D:\Program Files\Miranda NG.0.96.4\Plugins\PluginUpdater.dll  17D60000 - 17D77000 v.0.2.1.7 [15 Nov 2023 20:24:17]
D:\Program Files\Miranda NG.0.96.4\Plugins\PopupPlus.dll  17DC0000 - 17DF8000 v.2.1.3.0 [15 Nov 2023 20:24:05]
C:\WINDOWS\WinSxS\x86_Microsoft.Windows.Gdiplus_6595b64144ccf1df_1.0.6002.22509_x-ww_c7dad023\gdiplus.dll  4EBE0000 - 4ED8B000 v.5.2.6002.22509 [23 Oct 2010 2:47:50]
D:\Program Files\Miranda NG.0.96.4\libs\libTextControl.mir  12C20000 - 12C28000 [15 Nov 2023 20:23:40]
D:\Program Files\Miranda NG.0.96.4\Plugins\SeenPlugin.dll  180C0000 - 180CE000 v.5.0.5.6 [15 Nov 2023 20:23:45]
D:\Program Files\Miranda NG.0.96.4\Plugins\SpellChecker.dll  182E0000 - 182F4000 v.0.2.6.6 [15 Nov 2023 20:24:34]
D:\Program Files\Miranda NG.0.96.4\libs\hunspell.mir  121E0000 - 12270000 v.1.7.1.0 [15 Nov 2023 20:24:07]
D:\Program Files\Miranda NG.0.96.4\Plugins\StatusManager.dll  183A0000 - 183BB000 v.1.2.0.6 [15 Nov 2023 20:25:21]
C:\WINDOWS\system32\WININET.dll  63000000 - 630E6000 v.8.0.6001.18702 [8 Mar 2009 4:34:58]
C:\WINDOWS\system32\Normaliz.dll  01A30000 - 01A39000 v.6.0.5441.0 [7 Jan 2009 18:20:36]
C:\WINDOWS\system32\urlmon.dll  1A400000 - 1A532000 v.8.0.6001.18702 [8 Mar 2009 4:34:56]
C:\WINDOWS\system32\iertutil.dll  5DCA0000 - 5DE88000 v.8.0.6001.18702 [8 Mar 2009 4:32:22]
C:\WINDOWS\system32\IPHLPAPI.DLL  76D50000 - 76D69000 v.5.1.2600.5512 [14 Apr 2008 20:40:40]
D:\Program Files\Miranda NG.0.96.4\Plugins\TabSRMM.dll  184C0000 - 18531000 v.3.6.2.6 [15 Nov 2023 20:23:36]
D:\Program Files\Miranda NG.0.96.4\Plugins\Tipper.dll  19700000 - 19725000 v.2.1.0.8 [15 Nov 2023 20:23:51]
D:\Program Files\Miranda NG.0.96.4\Plugins\WhoUsesMyFiles.dll  19FA0000 - 19FAD000 v.0.1.0.4 [15 Nov 2023 20:24:09]
D:\Program Files\Miranda NG.0.96.4\Core\stduserinfo.dll  13160000 - 1316F000 v.0.96.4.26371 [15 Nov 2023 20:23:03]
D:\Program Files\Miranda NG.0.96.4\Core\stdemail.dll  13080000 - 13086000 v.0.96.4.26371 [15 Nov 2023 20:23:03]
D:\Program Files\Miranda NG.0.96.4\Core\stduseronline.dll  13180000 - 13187000 v.0.96.4.26371 [15 Nov 2023 20:23:03]
D:\Program Files\Miranda NG.0.96.4\Core\stdaway.dll  13020000 - 13029000 v.0.96.4.26371 [15 Nov 2023 20:23:02]
C:\WINDOWS\system32\mswsock.dll  71A30000 - 71A70000 v.5.1.2600.5625 [20 Jun 2008 18:04:16]
C:\WINDOWS\system32\hnetcfg.dll  698B0000 - 69908000 v.5.1.2600.5512 [14 Apr 2008 20:40:38]
C:\WINDOWS\System32\wshtcpip.dll  71A70000 - 71A78000 v.5.1.2600.5512 [14 Apr 2008 20:40:48]
C:\WINDOWS\System32\winrnr.dll  76FA0000 - 76FA8000 v.5.1.2600.5512 [14 Apr 2008 20:40:48]
C:\WINDOWS\system32\WLDAP32.dll  76F50000 - 76F7D000 v.5.1.2600.5512 [14 Apr 2008 20:40:48]
C:\WINDOWS\system32\rasadhlp.dll  76FB0000 - 76FB6000 v.5.1.2600.5512 [14 Apr 2008 20:40:44]

**Comment by georgehazan** [comment]
надо переключиться на репу с символами и повторить
это описано тут - https://wiki.miranda-ng.org/index.php?title=Crash_reports
