### ISSUE TITLE
Разные сообщения при отсутствии ядерных плагинов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3940]
AskAboutIgnoredPlugins = 0 в mirandaboot.ini

Если отключён clist_modern и отсутствует stdclist, то Миранда выдаёт сообщение:
[Unable to start any of the installed contact list plugins, I even ignored your preferences for which contact list couldn't load any.]

Если вообще стёрты все плагины списка контактов:
[Can't find a contact list plugin! You need StdClist or any other contact list plugin.]

Если отключены табсы и отсутствует stdmsg, Миранда выдаёт
[Core plugin '%s' cannot be loaded or missing. Miranda will exit now]

Если вообще стёрты все плагины сообщений:
[Core plugin '%s' cannot be loaded or missing. Miranda will exit now]

Мне кажется, надо привести клистовые сообщения к общему виду (Core plugin '%s' cannot be loaded or missing). У нас же почему-то для клиста прописаны особые сообщения.

**Comment by georgehazan** [comment]
Контакт-лист инициализируется и грузится отдельно, перед всеми другими плагинами, поэтому привести сам плагин к общему виду невозможно, можно только синхронизировать сообщения

**Comment by dartraiden** [comment]
Маленький недочёт: про StdMsg пишется, "Core plugin 'stdmsg' cannot be loaded or missing. Miranda will exit now", а про другие плагины (StdClist, StdPopup) пишется с правильной капитализацией.
