### ISSUE TITLE
Плагины сообщений: скрывать элементы окна в зависимости от типа привата

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3945]
`Скрытие панели ввода текста в зависимости от ситуации, например: я открываю rss канал из NewsAggregator и у меня не будет панели ввода, кнопок форматирования текста, цитирования и отправки файлов, также и при открытии канала в ТГ или при заходе в чат с пользователем ВК, который добавил меня в чс`

**Comment by dartraiden** [comment]
В табсах слишком сильно обрезается панель кнопок

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/b70980f9-7782-4758-8f21-6bab68a8c008)

![Uploading изображение.png…]()

**Comment by georgehazan** [comment]
Всё правильно: кнопка Send message стала невидимой
