### ISSUE TITLE
Прогресс скачивания крупных файлов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3946]
> Окно приёма файла(при отправке оно есть, а при получении его нету), его очень не хватает, приходится постоянно лезть в консоль и смотреть как там скачивание идёт

> Нету, потому что в основном вся мелочь скачивается автоматом. Для файлов, размер которых не пролезает в автомат, можно подумать, да.

**Comment by SM-Sergey** [comment]
> Для файлов, размер которых не пролезает в автомат

А если лимит не установлен, то и для всех поголовно. Очень не хватает, да!

Да и лимит вообще крайне странно устроен и бесполезен. В реальной жизни всякий хлам типа смайликов и прочих подобных дерьмокартинок не надо автоскачивать никогда, а вот текстовые файлы, исходники, документы, архивы, аудио, видео, нормальные немелкие фото, скриншоты, и т.п. полезные вещи - эти качать автоматически в локальное хранилище необходимо всегда. Но вот как это бы сделать, вообще не ясно. Но это риторика....

**Comment by SM-Sergey** [comment]
А почему тут поставили "Telegram"? Мне, например, это нужно для ICQ

**Comment by dartraiden** [comment]
Потому что получилось реализовать лишь в телеге, с аськой номер не пройдёт.

**Comment by SM-Sergey** [comment]
> с аськой номер не пройдёт.

А если не секрет, почему? Ведь до введения оффлайн-файлов это отлично работало в ICQ, а протокол передачи файла с тех времен не менялся.

**Comment by georgehazan** [comment]
Потому что телега умеет рапортовать процесс асинхронной загрузки файла, а аська пока не всосет весь файл в память, то не отвечает, а потом уже поздно.

**Comment by georgehazan** [comment]
Сейчас уже готов механизм, чтобы сделать что-то похожее в нетлибе, посмотрим, может и в аське появится

**Comment by georgehazan** [comment]
@SM-Sergey подвалило в ICQ
как соберется, появится прогресс в NewStory
