### ISSUE TITLE
NewStory: скроллбар в групчатах глючит

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3948]
Достаточно открыть нашу конфу, схватить мышкой скроллбар и потащить до упора вниз. Затем ещё раз. И ещё. Почему-то он каждую чётную попытку отскакивает назад.

**Comment by dartraiden** [comment]
Скинул профиль.

В общем, баг можно сформулировать проще: клик по самому ползунку скроллбара не должен вызывать прокрутку

**Comment by georgehazan** [comment]
Вроде перестало прыгать, попробуй
