### ISSUE TITLE
Telegram+NewStory: отправка нескольких файлов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3954]
Отправляю в телеграм два JPEG через кнопку "отправить файл"

apps.43185.13607400376220902.f9e795d7.jpg и 10_mission_30_08.jpg

Баг 1: первый файл имеет имя, а у второго вместо имени "Изображение (разрешение)"
Баг 2: у первого файла зеленая галка, у второго нет
Баг 3: они не открываются двойным щелчком
Баг 4: если переключиться с NS на встроенный журнал табсов, эти файлы в журнале отображаются почему-то в обратном порядке

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/c525a54a-4a01-4964-9483-81ac6a3fa904)

**Comment by georgehazan** [comment]
Забавнее всего то, что ни один файл в итоге не отослался...

**Comment by dartraiden** [comment]
Все 4 бага исправились. Но добавился новый.

Если удалить из журнала NS любую из картинок, то из журнала удаляются ВСЕ эти картинки пачкой. При этом, у собеседника в оф. клиенте корректно удаляется лишь картинка, которую пытались удалить из NS.

**Comment by dartraiden** [comment]
Ещё баг: картинки отправляются в неправильном порядке.

Есть картинки 1 и 2.

Выбираем на рабстоле мышкой сначала 1, затем 2, тащим в поле ввода. Они улетают в порядке 2,1


Выбираем на рабстоле мышкой сначала 2, затем 1, тащим в поле ввода. Они улетают в порядке 1,2
