### ISSUE TITLE
Telegram: импорт контактов приводит к задваиванию после логина

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3957]
Делаем чистый профиль и туда импортом втягиваем контакты Telegram из другой базы. Выводим в онлайн. Т.к. binlog не импортировался, Миранда запрашивает код подтверждения. Вводим код. В момент выхода в онлайн все чаты, контакты и боты задваиваются.

**Comment by dartraiden** [comment]
Ещё почему-то импорт всем контактам прописывает `MyHandle`.

**Comment by georgehazan** [comment]
а недостаточно для повторения бага просто стереть бинлог в профиле?

**Comment by dartraiden** [comment]
Нет
