### ISSUE TITLE
Telegram: сообщение о новом входе приходят на английском

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3958]
Когда я вхожу с нового устройства, от контакта "Telegram" мне приходит сообщение

```
[b]New login.[/b] Dear username, we detected a login into your account from a new device on 23/11/2023 at 21:53:34 UTC.

Device: blabla
Location: Tver, Russia (IP = x.x.x.x)

If this wasn't you, you can terminate that session in [b]Settings > Devices[/b] (or [b]Privacy & Security > Active Sessions[/b]).

If you think that somebody logged in to your account against your will, you can enable [b]Two-Step Verification[/b] in Privacy and Security settings.
```

Но оно на английском. При этом, параллельно на мобилку оно мне приходит на русском.

**Comment by dartraiden** [comment]
Есть подозрение, что системные сообщения приходят на языке клиента. По какой-то причине Миранда всегда декларирует английский?

**Comment by georgehazan** [comment]
> а при смене на русский дальше уже шли бы на русском.

На лету эта хрень не умеет, только в момент инициализации.
`Changes of value of this option will be applied only after TDLib restart, so it should be set before call to setTdlibParameters.`
