### ISSUE TITLE
NewStory: окно ответа

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3959]
1. Кнопка со скрепкой не работает
2. Разделитель между исходным сообщением и полем ввода стоит сделать перемещаемым
3. В верхнем поле с исходным сообщением у сообщения есть фон, а дальше идёт белая пустота. Пустоту надо красить в "фон сетки", как мы делаем в журнале.
4. У исходного сообщения в верхнем поле можно вызвать меню. Стоит его отключить. Половина пунктов там бесполезна ("выделить всё" - там всегда 1 сообщение, оно и так выделяется кликом, "реплай" и "переслать" - мы уже в окне реплая, зачем вызывать ещё один реплая), а вторая половина ("изменить", удалить") в обычном журнале есть.

<img width="371" alt="mstsc_GSu6FyfEX9" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/fafaea66-44f1-4a75-a03d-b316a67ffbbc">

**Comment by georgehazan** [comment]
это всё не актуально, потому что это окно убивается, будет встраиваться полосочка в обычный редактор
