### ISSUE TITLE
Telegram: не удаётся скачать исходящую картинку, если файл стёрт

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3963]
Отправляю картинку с рабстола. Стираю этот файл с рабстола после отправки.
Допустим, теперь я передумал и хочу вернуть файл, он есть на серваке, значит, я могу его скачать

Результат: двойной клик по файлу в журнале ничего не делает.

**Comment by SM-Sergey** [comment]
Ровно то же и в ICQ.

**Comment by georgehazan** [comment]
> Ровно то же и в ICQ.

С аськой никаких проблем, только что попробовал. Заливается сразу файл повторно, никаких вопросов

**Comment by SM-Sergey** [comment]
> С аськой никаких проблем, только что попробовал.

Починилось сегодняшним апдейтом. Но работает частично - если грохнуть свежеотправленный файл, то работает. Если грохнуть файл, отправленный до апдейта, то не работает. И на файлах до апдейта Copy URL ничего не копирует, вообще ничего не делает, в клипборде оставляет то, что там и было.

**Comment by georgehazan** [comment]
> И на файлах, отправленных до апдейта, Copy URL ничего не копирует, вообще ничего не делает, в клипборде оставляет то, что там и было.

А как оно может копировать, если там в качестве урла сидит строка "boo"

**Comment by SM-Sergey** [comment]
А это можно как-то обойти? Например, грохнув сообщение в NS, и потом втянув его по лоад хистори? Стирание сообщения в NS надеюсь его на сервере не прикончит?

**Comment by georgehazan** [comment]
> А это можно как-то обойти? Например, грохнув сообщение в NS, и потом втянув его по лоад хистори?

Вероятно, да.

> Стирание сообщения в NS надеюсь его на сервере не прикончит?

Непременно прикончит, если в базе Миранды для него есть server_id. Есть ненулевая вероятность, что при скачивании истории существующее событие будет перетерто тем, что придет с сервера, но это не точно

**Comment by SM-Sergey** [comment]
> Есть ненулевая вероятность, что при скачивании истории существующее событие будет перетерто тем, что придет с сервера, но это не точно

Увы, не сработало. А можно как-то прибить сообщение в базе, но не трогать на сервере?

**Comment by georgehazan** [comment]
> Увы, не сработало. А можно как-то прибить сообщение в базе, но не трогать на сервере?

Тикет есть, может быть в понедельник займусь, если работа не задавит
