### ISSUE TITLE
NewStory: не стирать исходящий файл с диска при удалении события

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3965]
Собственно сабж.

Отправил я, скажем, /Windows/System32/drivers/etc/hosts а собеседник, допустим, в телеграме взял и стёр событие у всех, включая меня. Или я сам стёр историю этого контакта. Например, вообще взял и стёр этот контакт из ростера.

В результате, если Миранда запущена от админа, я что, должен без hosts оставаться?

**Comment by georgehazan** [comment]
Там чуть сложнее. Например, если ты сам стер изначальный файл, то Миранда перезакачает его и сложит во временный каталог, и вот такой файл можно и должно стирать.
