### ISSUE TITLE
ICQ: неактуальные поля в юзеринфо

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3968]
Что такое "неактивен с" и "участник с"?

Там у всех контактов пусто. Разве в аське есть неактивность? Там же всего два состояния: "в сети" и "не в сети".

<img width="378" alt="Miranda64_ZzX7r5P6WT" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/8a5eb3de-5cb1-43c2-ad79-0a0303990a64">

**Comment by georgehazan** [comment]
Заодно сделяль, чтобы перевод "Последнее появление" влезал
