### ISSUE TITLE
Newstory:  если доскроллить вверх до первого сообщения, то подгрузить еще сообщений

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#3969]
На форуме это ушло как в черную дыру...

Если доскроллить вверх до первого сообщения, то подгружать еще сообщений из БД, с настройкой, по сколько сообщений подгружать (имхо, хорошим умолчанием будет по 50). Так работают оф. клиенты, и так же хочется видеть и тут.

В первую очередь, это касается встроенного журнала табсов, так как он не болен утечкой объектов GDI типа DC с последующим крэшем. Во вторую, по остаточному принципу, касается и больного NewStory.

**Comment by georgehazan** [comment]
Табсы в принципе не умеют писать в начало текста, этот фокус можно проделать только с NS

**Comment by SM-Sergey** [comment]
> Табсы в принципе не умеют писать в начало текста

А если журнал очистить, и подгрузить историю заново, как при первом открытии окна, но большим количеством сообщений?

**Comment by georgehazan** [comment]
ну т.е. на каждый чих будет туда-сюда мотаться 2-3 метра RTF, с учетом иконок. не, это не вариант

**Comment by SM-Sergey** [comment]
Ну проскроллить 50-100 вновь подгруженных сообщений не такой уж и чих. Хотя конечно вам виднее. Получается, что этот злобный баг с утечкой DC в NS ни на какой козе не объехать...
