### ISSUE TITLE
A change in the data in Skype (info profile), FB (info profile or avatar)

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#397]
**Reported by borut on 13 Jul 2015 13:39 UTC**
There are no options change avatar and information in your account FB
There is no possibility to change profile information Skype

**Comment by georgehazan** [comment]
**Modified by borut on 13 Jul 2015 13:40 UTC**

**Comment by LittleVulpix** [comment]
Avatar for Skype can be changed via the regular avatar services in miranda.
Nickname for skype cannot be changed, but this was logged as #672 

I suggest renaming this ticket to "It is not possible to change user details for FB" (I do not use FB so I cannot verify). The Skype part is already logged in the ticket listed above.

**Comment by Robyer** [comment]
As setting profile pic for FB probably won't be implemented at all, I'm just closing this.
