### ISSUE TITLE
Discord: don't create guild entries in contact list when "Enable guilds" is unmarked

### ISSUE THREAD

**Issue by ghost** [miranda-ng/miranda-ng#3970]
### Expected behavior
Do not to create "guilds" entries in contacts list if "Enable guilds" is disabled in Network/Discord. By guilds I mean discord servers and their channels/sub-channels which clutter contact list.

### Actual behavior
The entries are generated over and over even if get removed.

**Comment by georgehazan** [comment]
The only problem is that's not possible to create a guild contact (server room) if this option is turned off... there're only two places where guilds are passed, and both of them are protected with this option
