### ISSUE TITLE
NewStory: add animated smileys support

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3971]

**Comment by tamr** [comment]
I've checked the SmileyAdd sources and it's pretty obvious it will cause the performance bottleneck and there's no simple solution. Maybe just add an option to "Turn off animation" for smiley selector somewhere in the settings?

**Comment by georgehazan** [comment]
@tamr, no it doesn't lag. It seems that the optimization process had broken the glyph timings somehow
I'm using the classic Kolobok pack, it has more icons that on your screenshot, but there're no problems with them
