### ISSUE TITLE
ICQ: crash while file transfer

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#3974]
Пока отправлял фотку, пытался что-то писать. Результат:
[crash20231128004218.txt](https://github.com/miranda-ng/miranda-ng/files/13480693/crash20231128004218.txt)

UPD: файлтрансер завершился нормально

**Comment by SM-Sergey** [comment]
еще краш
[crash20231128013438.txt](https://github.com/miranda-ng/miranda-ng/files/13481246/crash20231128013438.txt)

**Comment by georgehazan** [comment]
Потому что OpenSSL не умеет многопоточность... если мы перейдем на OpenSSL 3.x, такие вопросы снимутся сами собой
