### ISSUE TITLE
Telegram: невозможно просмотреть файл в канале, где копирование файлов запрещено

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3975]
В настройках канала админ может запретить копирование файлов и текстов.

Оф. клиент в таком случае позволяет лишь просмотреть текст и открыть файл (на выполнение).

Миранда позволяет скопировать текст, а вот файл не может даже просмотреть. Так как файл сначала пытаемся скачать и тут в нетлоге видно, как сервер шлёт нас. Таким образом, Миранда для таких каналов наполовину неюзабельна и уступает оф. клиенту, который позволяет хоть запустить файл.

**Comment by dartraiden** [comment]
Также предлагаю отключать пункты меню копирования текста в журнале, если у канала запрещено копирование текстов.

**Comment by georgehazan** [comment]
Только на клиента эта информация никак не поступает. Вот один из крупных коммерческих каналов, найди там запрещение копировать что-то

```
    permissions = chatPermissions {
      can_send_basic_messages = false
      can_send_audios = false
      can_send_documents = false
      can_send_photos = false
      can_send_videos = false
      can_send_video_notes = false
      can_send_voice_notes = false
      can_send_polls = false
      can_send_other_messages = false
      can_add_web_page_previews = false
      can_change_info = false
      can_invite_users = false
      can_pin_messages = false
      can_manage_topics = false
    }
    has_protected_content = true
    is_translatable = false
    is_marked_as_unread = false
    is_blocked = false
    has_scheduled_messages = false
    can_be_deleted_only_for_self = false
    can_be_deleted_for_all_users = false
    can_be_reported = true
```

**Comment by dartraiden** [comment]
has_protected_content = true
