### ISSUE TITLE
NewStory: показывать пункт "изменить реплику" только для своих сообщений

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3978]
Какой смысл показывать её для чужих?
Ну, т.е. мы можем у себя в базе, конечно, локально изменить чужое. Но это не имеет смысла, ни один протокол такое не поддерживает.

**Comment by georgehazan** [comment]
возможно

**Comment by dartraiden** [comment]
Единственное, мне приходит в голову, что, возможно, есть смысл менять чужие сообщения, когда ты админ.
