### ISSUE TITLE
Telegram: отображение ролей в чате

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3980]
Для наглядности включены текстовые значки ролей.

dartraiden - создатель чата
ghazan и Vulpix - рядовые участники
test - тоже рядовой участник, с него и сделан скриншот

Баг 1: у всех рядовых участников перед ролью ненужный пробел (сравни с Jabber - там никакого пробела нет)
Баг 2: у рядовых участников не должно быть значка @. В других протоколах это значок админа, (в TG админ показывается плюсиком) не стоит его тут использовать просто так.

В идеале должно быть так:
- пробела нет
- "собаки нет" ни у кого

**Comment by georgehazan** [comment]
@ = ник пользователя

**Comment by dartraiden** [comment]
Понятно, но тогда надо @ всем лепить. Иначе, получается бред: у тех, у кого есть статус, отчего-то @ в нике нет.

**Comment by dartraiden** [comment]
Неактуально, значок собаки куда-то пропал после вчерашних-сегодняшних фиксов. В целом, стало ровно и красиво.
