### ISSUE TITLE
Telegram: покинутый чат не стирается сразу, а скрывается и выкидывается из ростера

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3983]
Это приводит к тому, что если в текущей сессии нас снова добавят в этот чат, то он не удалится после перезапуска (т.к. он опять влетел в ростер), но останется скрытым.

Три варианта развития событий:
1) при покидании чата мы сразу его убиваем (при этом убивается история, но раз оф. клиент не парится с сохранением истории покинутого чата, почему должны париться мы?)
2) не выставлять чату Hidden (тогда чат будет болтаться в клисте до перезапуска)
3) если нас затащили обратно в покинутый чат, снимать Hidden

**Comment by SM-Sergey** [comment]
> 1. почему должны париться мы?

Ну, как бы, это чуть ли самая главная фича всей миранды, только ради которой ей многие пользуются, что в ней есть все в базе данных, что происходило раньше в истории. ИМХО, перед удалением чего либо из БД надо открывать яркое окно с предупреждением о том, что "сейчас будет удалено то-то и то-то, вы точно уверены, что хотите это позволить"? И обязательно предлагать делать отдельную резервную копию БД, чтобы, если что, к ней можно было вернуться, и посмотреть, что там было. То есть, в любом случае при покидании чего либо где либо, или всё старое должно храниться в БД, либо должен быть выбор, надо ли мне сохранить эту историю, или не надо. И если надо - всегда иметь возможность ее просмотра. А безусловное удаление это будет огромный шаг назад, можно сказать, что в пропасть, это будет потеря базовой функциональности.

**Comment by dartraiden** [comment]
Всё, что после "имхо" нарушает условия использования API.

**Comment by SM-Sergey** [comment]
А наличие резервных копий, которые, к примеру, у меня раз в сутки делаются, и 30 последних копий всегда лежат, по любому это нарушают, как ни крути. Это первое.
А второе - покидание чата это не требование другой стороны, это "я сам ушел". И ничего не нарушаю, храня все что было.

**Comment by SM-Sergey** [comment]
То есть - принципиальный вопрос тут такой. Это обычная практика - сделали группу, поработали, реализовали проект, и разбежались оттуда, ибо она больше не нужна по факту. Но историю всю храним, так как там было много для всех полезного - алгоритмы разные обсуждали, схемотехнические решения, т.д. Опять же, всякие спорные вопросы могут потом быть, чтобы вернуться и глянуть, что и как было. И это по общему согласию, разумеется.

**Comment by SM-Sergey** [comment]
То есть, отличным решением будет отправлять покинутые чаты (во всех протоколах) в контакты типа dummy со всей историей. А по возвращению в них - оттуда возвращать в протокол.
