### ISSUE TITLE
ICQ: реализовать прием отредактированных сообщений с сервера

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#3990]
- От сервера придет событие "histDlgState", содержащее LastMsgId, patchVersion (новый), и не содержащее никакого сообщения и текста. При этом именно изменение PatchVersion по сравнению с предыдущим для этого контакта - есть признак его редактирования.

- После этого надо отправить запрос getHistory с параметрами "count": -1, "fromMsgId": "-1"", без tillMsgId вообще, с "sn" контакта с изменениями (из предыдущего события), и с "patchVersion": "xxxxx", где "xxxxx" - это последний известный PatchVersion этого контакта до того, что пришел в этом histDlgState. Он известен или из предыдущего histDlgState по этому контакту, или из GetHistory, который делался контакту "на старте".  В ответ придет блок типа "patch", в котором будут указаны MsgId исправленных сообщений (type: update) и стертых (type:delete). И последнее сообщение заодно придет, которое проигнорировать.

- Если type==update, то после этого надо сделать еще один getHistory с уже новым patchVersion, c fromMsgId предыдущего сообщения из истории, которое перед тем, что пришло в блоке "patch" предыдущего запроса, с tillMsgId = lastMsgId с предыдущего запроса и count=1, в ответ на который приедет отредактированное сообщение.

Ну и разумеется не стирать "старое сообщение" физически, тут жеж не телега с его идиотскими запретами, а, например, сделать старое сообщение зачеркнутым, и после него добавить новое, если было update, или не добавлять, если было delete. В общем так, чтобы видеть историю правок.

**Comment by dartraiden** [comment]
> тут жеж не телега

Все клиенты, включая официальный, работают по одним правилам.

**Comment by SM-Sergey** [comment]
Не, ну если для ICQ такой запрет тоже существует в какой-то лицензии или ином документе, то да, вопросов нет. Но, хотя бы в базе данных сохраните всю историю как она есть, а при выводе в журнал-историю можно и не отображать "старое"

**Comment by SM-Sergey** [comment]
А, и да... 
Эти patchVersion видимо стоит хранить в БД, так как при обычном getHistory для отредактированных сообщений прилетает также и updatePatchVersion - что позволит обновлять старые сообщения по "Load Server History", если их updatePatchVersion не соответствует записи в БД. Если сообщение не редактировали, то и updatePatchVersion у них нету вообще.
