### ISSUE TITLE
VK+NewStory: если с открытым окном чата входить в сеть, то порядок событий перепутается

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3993]
В чате ВК у меня такая история

входы
выходы
смена топика

Теперь я пишу в чать "ыть". Получаю:

входы
выходы
смена топика
ыть

Если я перезапущу Миранду и открою окно чата, то всё остаётся как и было

входы
выходы
смена топика
ыть

Но если я при открытом окне чата передёрну протокол -> не в сети -> в сети, то в журнале образуется

входы
выходы
смена топика
ыть
входы
выходы
смена топика

т.е. после "ыть" вклеиваются старые события

**Comment by dartraiden** [comment]
Со встроенным журналом табсов нет проблем. А вот с NewStory есть.

**Comment by ElzorFox** [comment]
А это следствие того, что обычные сообщения хранятся в базе и добавляются через ProtoChainRecvMsg, у них есть нормальный ID, и при перезагрузке истории они как новые не идут, потому что уже в базе есть. А входы-выходы,  смены топика и прочие экшены заходят через старый добрый Chat_Event, туда ID события не идет, потому что его там никто не спрашивает. Событие заходит в любом случае как новое, и NS лепит их в конец лога. Стандартный журнал, видимо, умеет события сортировать хронологически, NS - не умеет.

**Comment by dartraiden** [comment]
Напоминает https://github.com/miranda-ng/miranda-ng/issues/3987

Только там это происходит вне зависимости от журнала.

**Comment by ElzorFox** [comment]
Ну да. Разница, по видимому в том, что стандартный лог более примитивен: все что полетело от протокола (как через ProtoChainRecvMsg, так и через Chat_Event) он лепит в конец лога, даже те сообщения, которые в базе уже есть. NS чуть умнее: он "старые" сообщения (то есть, которые в базе уже есть и теперь добавлены повторно через ProtoChainRecvMsg) заново в лог не добавляет. То есть в лог попадают только события, пришедшие через Chat_Event и про которые нельзя однозначно сказать, старые они или новые. 
Если лог NS после этого закрыть-открыть, то можно увидеть, что такие события хронологически пересортируются, но при этом будут задвоены, а сообщения - только пересортированы.
Как вариант решения - начинать хранить GCEVENT в базе.

**Comment by georgehazan** [comment]
duplicate of #3987
