### ISSUE TITLE
Telegram: new problems after adding to chat 

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#3994]
I'm being added to the chat

1) ~the chat appears in Miranda in Chinese instead of the proper name~
FIXED

2) I download history from the server. A 4th chat participant appears in the nickname list - an unknown contact, and in the history there is an events with the date 1970

**Comment by georgehazan** [comment]
Призрак вульпикса остался, потому что без него вообще движок чатов работать не может
Неизвестный контакт я пофиксил
