### ISSUE TITLE
Уведомление о пришедшем файле глючит

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4000]
Я не знаю, насколько это связано с каким-то именно компонентом, поэтому не указываю.
Протокол ICQ. 
Табсы + встроенный журнал. Включена автозагрузка оффлайн файлов без ограничений.
Окно табсов свернуто. Закладки с этим контактом в нем в нем изначально нет. 

Мне присылают файл.
Начинает мигать иконка уведомления в трее винды, внизу клиста, и около контакта.

Если я кликаю на трей винды, окно с табсами всплывает, но там так и нет закладки с контактом. При прочих равных, если приходит сообщение, а не файл, то закладка появляется.

Если я кликаю дважды по контакту в клисте, около которого мигает уведомление, то окно с табсами всплывает, закладка с контактом появляется, я вижу файл, но уведомление не пропадает, так и мигает.

И только, если я кликаю на уведомление внизу клиста, оно сбрасывается.

Если еще включить уведомления "виндовые" всплывающие, то при клике туда также открывается закладка, но иконка-уведомление в клисте не сбрасывается - то есть как бы "дабл-клик по контакту".

ИМХО, все должно работать одинаково. При клике в трее винды закладка должна появляться одинаково и при приходе файла, и при приходе сообщения. Особенно учитывая, что реально файл == сообщение. При дабл-клике на контакте должно происходить ровно то же, и уведомление сбрасываться. При клике на уведомлении внизу клиста - должно происходить ровно тоже самое.

В каких-то случаях были ситуации, что куда как не кликай, мигающая иконка с файлом не сбрасывается, пока миранду целиком не перезапустишь. Это бесит больше всего, но бывает редко, и непонятно как это повторить.

тут какой-то конгломерат багов, который систематизировать просто так не получается без поллитры...

**Comment by georgehazan** [comment]
> Если я кликаю на трей винды, окно с табсами всплывает, но там так и нет закладки с контактом. При прочих равных, если приходит сообщение, а не файл, то закладка появляется.

Вот такого мне не удалось воспроизвести. давай копию настроек сделаем? Проще всего так:
- делаем копию профиля и заходим в нее
- вычищаем оттуда все учетки, это убивает все контакты и истории
- оставшееся сжимаем (Main menu - Database - Compact), чтобы исключить попадание в профиль старой инфы
- полученный профиль содержит настройки, его можно зазиповать и вклеить сюда

**Comment by georgehazan** [comment]
> Если я кликаю дважды по контакту в клисте, около которого мигает уведомление, то окно с табсами всплывает, закладка с контактом появляется, я вижу файл, но уведомление не пропадает, так и мигает.

Вот это тоже повторить удалось только в NewStory, но там я поправил уже

**Comment by SM-Sergey** [comment]
По поводу второго - ну у меня оно так стабильно. Вот клик сюда как на скрине - закладка появляется, но уведомление не сбрасывается - оно и видно - табсы открылись, а иконка там висит.

![2023-12-05 19_41_49-Miranda NG](https://github.com/miranda-ng/miranda-ng/assets/34127439/e7b005eb-0932-4add-a0d7-761088b088bc)


По поводу первого  - я наверное некорректно выразился. Плохо владею терминологией, видимо. Если сделать дабл-клик в той части трея, где стусованы иконки всяких разных "скрытых" софтов, то все в порядке - уведомление пропадает, закладка появляется. А вот если кликнуть в сам таскбар, в котором существует и окно табсов с иными закладками, и сам клист - то там в списке не будет предложения открыть нужную вкладку - то есть она там сама не создалась, пока табсы были скрыты.

![2023-12-05 19_45_06-Settings](https://github.com/miranda-ng/miranda-ng/assets/34127439/4b2b68d6-0e09-478a-9362-12fb2f96696d)

Настройки попробую так скопировать.

**Comment by SM-Sergey** [comment]
А как зайти в копию профиля? Как забекапить то ясно...

**Comment by georgehazan** [comment]
> А как зайти в копию профиля? Как забекапить то ясно...

сделать копию каталога, назвать каталог test, а профиль - test.dat

**Comment by SM-Sergey** [comment]
Не, а где задать то, что каталог рабочий поменялся? В mirandaboot.ini поменять ProfileDir?

**Comment by dartraiden** [comment]
Посмотреть, куда указывает ProfileDir

В этом каталоге сделать

/каталогсбоевойбазой/боеваябаза.дат
/test/test.dat

при запуске миранда спросит, какую базу открыть

**Comment by SM-Sergey** [comment]
Да. Разобрался сам.
Но после убивания всех учеток и "Compact database" она один черт 162 мбайт занимает, как и до компакте

**Comment by SM-Sergey** [comment]
А может хватит в дбедиторе экспорт all settings ?

**Comment by georgehazan** [comment]
> А может хватит в дбедиторе экспорт all settings ?

Там будут все пароли к учеткам

> Но после убивания всех учеток и "Compact database" она один черт 162 мбайт занимает, как и до компакта

Еще можно системную историю стереть

**Comment by SM-Sergey** [comment]
> Там будут все пароли к учеткам

так учетки-то грохнуты, а перед этим пароли попорчены.

> Еще можно системную историю стереть

Ну это вряд ли. Не она же 162 мбайт занимает в БД. По ходу компакт не компактит ничего - он и выполнился за какие то доли секунды, сказав что все OK.

**Comment by SM-Sergey** [comment]
А вот после check database - она сама и скомпактилась! А еще и 7z архив фиг загрузишь.

[test.tar.gz](https://github.com/miranda-ng/miranda-ng/files/13569252/test.tar.gz)

**Comment by SM-Sergey** [comment]
там были ошибки типа "Orphaned setting ..... with wrong contact ID" - может это причина не компактиться? Ну тогда надо бы сказать, что компакт не сработал из-за ошибок, а не говорить, что все ОК.

**Comment by dartraiden** [comment]
@georgehazan, может, временно сделать скрытую опцию, которая бы выполняла проверку без исправления?

**Comment by SM-Sergey** [comment]
Ну я свои базы сохранил если что, перед тем как их проверять или компактить. Так что, повторить могу если надо. архивная копия базы с этими "орфанными сеттингами" тоже есть.
Исправление этих орфанных сеттингов в "боевой" базе вроде ничего не испортила.
И да, перед проверкой базы с исправлениями ее априори надо бекапить. Или сделать галку - исправлять или только проверять.

**Comment by SM-Sergey** [comment]
не, тикет заводить не выйдет, я раза три пытался тоже сделать из архивных копий баз с этими же ошибками в базе. Ни разу не вышло повторить. Всё компактилось. Это что-то странное было, можно считать что не было.

**Comment by georgehazan** [comment]
> test.tar.gz

На этом профиле у меня всегда поднимается таб с той закладкой, куда я пишу

**Comment by SM-Sergey** [comment]
> На этом профиле у меня всегда поднимается таб с той закладкой, куда я пишу

Если писать, то да, всегда все ОК. Глюки возникают, если именно файл прислать, без сообщений.

**Comment by georgehazan** [comment]
@SM-Sergey погоняй, короче, вроде я всё поправил, а там как пойдет
если что-то вылезет - пиши

**Comment by SM-Sergey** [comment]
Ну пока так. 
Первая часть исправилась - теперь закладка появляется в таскбаре по приходу файла, можно на нее кликнуть, и окно всплывает с нужной закладкой.
А вот вторая часть не исправилась, там ничего вообще не поменялось. Убрать мигающую синюю иконку уведомления о приходе файла ни дабл-кликом на контакт, ни тыком в таскбар нельзя. То есть окно с закладкой-то всплывает, но синяя иконка везде продолжает мигать. Ее убрать, по прежнему, можно только тыком на уведомление внизу клиста, либо дабл-тыком на иконку миранды в области уведомлений таскбара (это где много мелких иконок от всякого разного софта спрятаны). И да, скрывать окно сообщений для этого даже и не надо. Главное, чтобы закладки этого контакта там не было открыто изначально.
Также, заметил еще одно странное поведение. Если окно сообщений открыто, закладка контакта есть, но закладка не в фокусе (общаемся с другим контактом), и в ту закладку прилетает файл, то синяя иконка уведомления о файле появляется только на самом табе, а в клисте и остальных местах - нет. Может оно так и должно быть, никаких вопросов к этому нет, но, просто, к слову.

**Comment by georgehazan** [comment]
> Также, заметил еще одно странное поведение. Если окно сообщений открыто, закладка контакта есть, но закладка не в фокусе (общаемся с другим контактом), и в ту закладку прилетает файл, то синяя иконка уведомления о файле появляется только на самом табе, а в клисте и остальных местах - нет. Может оно так и должно быть, никаких вопросов к этому нет, но, просто, к слову. Но, если закладки до этого не было - то синяя иконка уведомления появляется во всей куче мест. Хотя принципиальной разницы, не было закладки, или была, но не в фокусе, нету вроде.

А что тут странного? Если есть готовый таб для этого контакта, то понятно, что звонить везде не нужно, надо замигать этим самым табом. Вроде в табсах это где-то даже настраивалось, чтобы мигать только им.

**Comment by georgehazan** [comment]
> Убрать из клиста мигающую синюю иконку уведомления о приходе файла ни дабл-кликом на контакт, ни тыком в таскбар нельзя.

NewStory точно убирает мигание, если нажать в любое место, чтобы окно поднялось. Или речь идет о родном логе табсов? Так он про это ни ухом, ни рылом...

**Comment by SM-Sergey** [comment]
да, именно. У меня во всех тестах журнал табсов, а история NS

**Comment by SM-Sergey** [comment]
Суть в другом - если журнал показали, уведомление надо сбросить, и всё равно, NS его отображает, табсы, или еще кто пятый
