### ISSUE TITLE
Big avatars in ICQ

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#401]
**Reported by dartraiden on 2 Aug 2015 13:23 UTC**
 icq.com asks user for 600x600 px avatar (and crop image if it is bigger). Miranda dont't support avatars bigger then 64x64:

- if you set big avatar via icq.com, Miranda loads and store it as 64x64 (%profile%\AvatarCache?\ICQ_1)
- if you set big avatar via Miranda - it cropped to 64x64 (official client doesn't support avatar change) 

We try to change this limit in revision 13432, but it's leads to "Error uploading avatar to server, server refused to accept the image". Seems like protocol does't support setting big avatars. But we must able to load and store already exist big avatars (like official client). If user set big avatar via website Miranda crop avatar and sent it back to the server on next connection.

**Comment by georgehazan** [comment]
**Modified by dartraiden on 2 Aug 2015 13:44 UTC**

**Comment by georgehazan** [comment]
**Modified by dartraiden on 2 Aug 2015 13:45 UTC**

**Comment by georgehazan** [comment]
**Modified by dartraiden on 2 Aug 2015 13:45 UTC**

**Comment by georgehazan** [comment]
**Modified by dartraiden on 5 Aug 2015 22:52 UTC**

**Comment by dartraiden** [comment]
Closed due to #1686
