### ISSUE TITLE
Telegram: покидание чата снова оставляет странный контакт

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4018]
Нас добавляют в чат. Покидаем его из Миранды.

Результат: в клисте появляется контакт с id 1985055038

**Comment by georgehazan** [comment]
нужен нетворк лог после выхода из чата, где была бы строка New contact created

**Comment by dartraiden** [comment]
Дубликат https://github.com/miranda-ng/miranda-ng/issues/4019, по-видимому.
