### ISSUE TITLE
Telegram: изредка имя чата корёжит при добавлении Миранды в чат

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4019]
Миранду добавляют в чат.

Где-то 1 раз из 10 вместо названия чата в клисте абракадабра.

**Comment by dartraiden** [comment]
[netlog.txt](https://github.com/miranda-ng/miranda-ng/files/13550028/netlog.txt)

**Comment by georgehazan** [comment]
в логе нет самого описания чата, только засовывание в него какого-то контакта

**Comment by dartraiden** [comment]
Теперь после добавления чата он создался в клисте с именем "нет".
