### ISSUE TITLE
Temporary contacts not shown

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#402]
**Reported by dartraiden on 2 Aug 2015 17:01 UTC**
If the ICQ or Mail.ru agent contact not added to my permanent contact list - it is invisible in the clist (I'm using clist_modern).

Even if option

[Hide &offline users out here]
Скрыть &отключённых вне группы

is disabled

But it still visible in Settings -> Contacts -> Ignore

Contact adds to db with "Hidden = 0x1" parameter.

**Comment by georgehazan** [comment]
**Modified by dartraiden on 2 Aug 2015 17:26 UTC**

**Comment by georgehazan** [comment]
**Modified by dartraiden on 2 Aug 2015 17:27 UTC**

**Comment by georgehazan** [comment]
**Modified by dartraiden on 2 Aug 2015 17:28 UTC**

**Comment by georgehazan** [comment]
**Modified by dartraiden on 2 Aug 2015 17:28 UTC**

**Comment by georgehazan** [comment]
**Modified by dartraiden on 2 Aug 2015 17:29 UTC**

**Comment by georgehazan** [comment]
**Modified by dartraiden on 2 Aug 2015 17:37 UTC**

**Comment by georgehazan** [comment]
**Modified by dartraiden on 2 Aug 2015 17:39 UTC**

**Comment by georgehazan** [comment]
**Modified by dartraiden on 2 Aug 2015 17:40 UTC**

**Comment by georgehazan** [comment]
**Modified by dartraiden on 2 Aug 2015 17:40 UTC**

**Comment by georgehazan** [comment]
**Modified by dartraiden on 3 Aug 2015 17:16 UTC**

**Comment by georgehazan** [comment]
**Comment by dartraiden on 14 Sep 2015 22:32 UTC**
mir_core.mir!db_set_b(unsigned int hContact=1207, const char * szModule=0x0000000003160fd8, const char * szSetting=0x0000000003160fd0, unsigned char val='\x1') Line 179	C++

ICQ.dll!CIcqProto::setContactHidden(unsigned int hContact=1207, unsigned char bHidden='\x1') Line 139	C++

ICQ.dll!CIcqProto::HContactFromUID(unsigned long dwUin=0, const char * szUid=0x000000000c22f6a0, int * Added=0x000000000c22f678) Line 525	C++

ICQ.dll!CIcqProto::handleRecvAdded(unsigned char * buf=0x0000000008b60f91, unsigned __int64 wLen=0) Line 1450	C++

ICQ.dll!CIcqProto::handleServCListFam(unsigned char * pBuffer=0x0000000008b60f80, unsigned __int64 wBufferLength=17, snac_header * pSnacHeader=0x000000000c22fb08, serverthread_info * info=0x000000000c22fcd0) Line 203	C++

ICQ.dll!CIcqProto::handleDataChannel(unsigned char * pBuffer=0x0000000008b60f80, unsigned __int64 wBufferLength=17, serverthread_info * info=0x000000000c22fcd0) Line 76	C++

ICQ.dll!CIcqProto::handleServerPackets(unsigned char * buf=0x0000000008b60f6e, int len=41, serverthread_info * info=0x000000000c22fcd0) Line 263	C++

ICQ.dll!CIcqProto::ServerThread(serverthread_start_info * infoParam=0x0000000000000000) Line 142	C++

mir_core.mir!forkthreadex_r(void * arg=0x000000000013ea18) Line 154	C++

[ 15 21:07](03) * ghazan: 
[ 15 21:08](03) * ghazan: if (!bIsSyncingCL) {
[ 15 21:08](03) * ghazan:      
[ 15 21:11](03) * ghazan:  
[ 15 21:11](03) * ghazan:  - ,

**Comment by dartraiden** [comment]
Fixed in new ICQ protocol plugin.
