### ISSUE TITLE
При смене языка на лету новые чаты перестают появляться в списке контактов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4028]
Стартуем с русским ленгпаком. Смотрим настройки чатов, там указана группа по умолчанию - "Чаты".
Меняем на английский. 
Смотрим настройки - там по-прежнему указана группа "Чаты"

Затем нас добавляют в чат, например, телеграма.

Результат: чат добавляется в дефолтную группу для английского ленгпака - "Chat rooms". При этом в списке контактов отсутствует и эта группа, и чат.

Баг 1: либо надо менять имя дефолтной группы чатов при смене ленгпака, либо чат должен добавиться в группу, которая в настройках.

Баг 2: Чат не виден в списке контактов.

**Comment by georgehazan** [comment]
если в базе нет вообще такой настройки, то должна создаться группа Chat rooms, куда должен прилететь новый чат. Автоматом переименовывать группу вообще не вариант

**Comment by dartraiden** [comment]
Если в базе нет такой настройки, то

- группа в клисте существующая не должна переименовываться
- в настройках плагина сообщений группа должна переименоваться
- и чат должен влететь в эту группу

сейчас 2 и 3 не происходяит

**Comment by georgehazan** [comment]
> * в настройках плагина сообщений группа должна переименоваться

если в базу записалась настройка, то вариантов нет, она переименовываться не будет
переименовывается на лету только тогда, когда в базе нет настройки, но при первом нажатии Ok она туда запишется

**Comment by dartraiden** [comment]
Если в базе есть настройка, то

* группа в клисте существующая не должна переименовываться
*  в настройках плагина сообщений группа не должна переименоваться
* чат должен влететь в эту группу, а не в англоязычную

**Comment by dartraiden** [comment]
Тогда баг в том, что чат игнорирует настройку и всегда влетает в группу на языке ленгпака, положив на настройку болт.
