### ISSUE TITLE
IRC + Tabsrmm: asks use should Miranda close tabs or not.

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#4031]
### Expected behavior
Miranda asks user should tabs be closed or just leave but stay tabs opened. If user does not want to close tabs, just leave channels and disconnects from server.
Note: using /part command in channels you leave channel with tab saving.

### Actual behavior
Miranda closes tabs.

### Steps to reproduce that behavior
Connect to any IRC server, join to several channels, change Status to Offline for this IRC account.

**Comment by georgehazan** [comment]
open dbeditor++, Settings / TabSRMsg
delete cWarningsL & cWarningsV variables
