### ISSUE TITLE
IRC + Tabsrmm: User details windows is without information for IRC users.

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#4032]
### Expected behavior
User details windows is useful.

### Actual behavior
User details is useless, nickname is there only.

### Does it work in stable version?
I don't know.

### Steps to reproduce that behavior
1. Start conversation with any user in IRC
2. Click User details icon for User details window.

**Comment by georgehazan** [comment]
Open this contact in Dbeditor++ and export its settings to INI file
Attach this file here
