### ISSUE TITLE
IRC + Tabsrmm: create a difference for tabs for channels and users.

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#4033]
Tabs for channels and user are same. It's difficult to find a personal chat.

Text in channel tabs looks so: `#channel`
For user: `Usernick (status)`

Visual difference for type of tabs is required.

**Comment by georgehazan** [comment]
![image](https://github.com/miranda-ng/miranda-ng/assets/4628541/73ec394a-8aab-4a1b-8490-db6ad5886147)
