### ISSUE TITLE
LibraIRC - Event to join a chat room with two number signs # before the name results in Miranda NG joining wrong chatroom.

### ISSUE THREAD

**Issue by eggsgent** [miranda-ng/miranda-ng#4034]
1. Set up network on irc libera.chat
2. Go to Settings > networks > irc > advanced > perform and add event: /join ##testmyroom
3. Save and reopen Miranda NG

Expected result: user should join ##testmyroom automatically
Actual result (bug): user joins #testmyroom

Reference: https://libera.chat/chanreg/ 
"Channels that begin with two or more # characters are for informal channels (e.g. ##chat)."

Miranda NG Version: 0.96.4 build #26377 (f975dd282d) x64
IRC.dll v.0.96.1.4 [8 Dec 2023 12:25:42] - IRC protocol

**Comment by georgehazan** [comment]
![image](https://github.com/miranda-ng/miranda-ng/assets/4628541/a35a208b-3f16-4f54-a9cb-21f090eba5f3)
![image](https://github.com/miranda-ng/miranda-ng/assets/4628541/6be5353c-0af5-42e6-962e-0e7b9a903ab3)
what am I doing wrong?
