### ISSUE TITLE
Offline options for Miranda Statuses to disconnect all or locked accounts only.

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#4036]
https://github.com/miranda-ng/miranda-ng/issues/4035 - about this feature.

**Is your feature request related to a problem? Please describe.**
https://github.com/miranda-ng/miranda-ng/issues/4035 - about this feature. Option Offline in Miranda's Statuses does not disconnect locked accounts.

**Describe the solution you'd like**
I suggest add an option in Status to disconnect:
 all accounts including Locked;
 Locked accounts only.

Make both options without hotkey combinations.

**Describe alternatives you've considered**

**Additional context**

**Comment by georgehazan** [comment]
no, locked accounts are by design aren't involved into any global status change
