### ISSUE TITLE
StatusManager: не помещаются надписи

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4037]
Не влезает "Set after":

<img width="503" alt="Miranda64_A7oOEgEjGO" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/e4cb2d34-49a7-41ed-8d45-362cbbe44563">

Не влезает перевод "Длительность":

<img width="396" alt="Miranda64_b2oIwYnnBs" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/723034d4-fc5a-4d37-8562-75ddad501924">

**Comment by georgehazan** [comment]
сделал место для перевода "Включить через"
