### ISSUE TITLE
IRC + Tabsrmm: Tabsrmm is sure user in channel after kick.

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#4038]
### Expected behavior
Leave char room option is not active and not available to click.

### Actual behavior
Tabsrmm is sure that user still in channel and suggests Leave chat room Option.

### Does it work in stable version?
I don't know.

### Steps to reproduce that behavior
1. You need to be kicked from channel.
2. Then click right mouse button on channel tab to call a menu.
3. Tab menu suggest you Leave chat room.
4. If you click on Leave chat room. Tab will be closed. Maybe it make a call to leave channel also.

**Comment by georgehazan** [comment]
Disable Options - Network - IRC - Account - Rejoin channel if kicked, and Miranda won't return to the channel

**Comment by JeanPaulLucien** [comment]
I mean other situation.
1. Get kick from channel.
2. Internet connection goes away.
3. Internet connection restores.
4. Connect IRC account again.
5. Miranda joins to channel where were kicked.

User was kicked any time ago, but Miranda joins to these channels again.

**Comment by dartraiden** [comment]
Тебя кикнули. Канал при этом остался у тебя в списке контактов. Протокол переподключился. Поскольку у тебя в настройках протокола включено "перезайти при повторном подключении", то Миранда и заходит во все каналы, которые есть в списке контактов.

**Comment by dartraiden** [comment]
@georgehazan возможно, имеет смысл при кике писать в базу какой-то флажок? Допустим, тебя кикнули с канала (без перезахода), в базу записался флажок. Дальше ты вырубил Миранду, потом запустил её, она видит флажок "я был кикнут отсюдова" и туда не заходит.

А если после кика ты перезашёл в канал (автоматически или руками), то флажок стирать.

**Comment by dartraiden** [comment]
Или сделать проще: опцию "удалять канал, если меня кикнули".

**Comment by georgehazan** [comment]
> Или сделать проще: опцию "удалять канал, если меня кикнули".

Не понимаю, в чем трагедия стереть это руками, если тебя вышибли с канала?
Зачем вообще что-то городить

**Comment by dartraiden** [comment]
Допустим, ты не заметил, что тебя вышибли.

Или тебя вышибли, пока ты бы не за компом.
