### ISSUE TITLE
NewStory: Просто открыл "System history". В окне пусто несколько секунд, и крэш.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4045]
крэшдамп (не думаю, что полезен)
[crash20231212214507.txt](https://github.com/miranda-ng/miranda-ng/files/13652134/crash20231212214507.txt)

Недавно выкладывал тут обрезанную БД свою для тестов уведомлений о файлах - на ней нет падения, но глюков вагон и тележка, всё встает не падая.

Короткое исследование показывает очередной упор в 9999 GDI объектов в процессе открытия окна. Никаких смайлов там нет, и неоткуда им там взяться, и вообще SmileyAdd нет. Типы объектов в этот раз не смотрел.

**Comment by georgehazan** [comment]
нуачо, как только GDI заканчивается, оно и падает, либо при делении на 0 (в нормальных условиях это высота окна), либо при использовании нулевого хэндла шрифта. 

заканчивается, как выяснилось, GDI из-за рисования иконок в сообщениях, так что ничего  нового по сравнению с #3781 не появилось

**Comment by SM-Sergey** [comment]
Новое еще как появилось. Если в сообщениях можно посмотреть хотя бы немного истории, включая ее хвост, и постараться успеть что-то поискать, и даже найти за сколько-то итераций с падениями, то системная падает не открывшись.

**Comment by georgehazan** [comment]
> И, если заканчиваются объекты из-за рисования иконок, то почему это объекты типа DC (не метафайловые DC, не битмапы, а обычные контексты рисования)? В чем великий смысл не освободить за собой контекст?

Потому что это не HDC, а именно метафайлы. Если в шаблонах убрать иконки, то можно спокойно просматривать историю любого размера

**Comment by SM-Sergey** [comment]
> Потому что это не HDC, а именно метафайлы.

И GDIView, и Bear считают MF/EMF DC отдельно - они по нулям. Тип объекта по их данным - просто DC, и выходит что это именно HDC. Я в том тикете скриншоты приводил. Какой снифер GDI показывает, что это MF/EMF? То, что это связано с иконками - охотно верю, но вопрос немного другой.

А вообще не должен же ричедит так работать. Должен быть где-то какой-то баг, типа того, к примеру, что в ITextServices не долетают какие-то сообщения. В NewstoryListWndProc, к примеру, не видно форварда всего необработанного туда. Все "лишние" сообщения должны улетать в  ITextServices::TxSendMessage, а если оно вернуло FALSE, то надо выполнить ::DefWindowProc для этого сообщения (иначе - нет). Другим потенциальным багом может быть отсутствие реализации SetTimer/Killtimer в текстхосте - может оно там хочет поосвобождать эти DC по таймеру, типа если давно не пользовались.

**Comment by SM-Sergey** [comment]
АААА! Ужас! С какого-то недавнего коммита в NS вообще любая, достаточно длинная, история перестала открываться и вызывает падения, не только системная. Сейчас вообще нельзя никакую историю посмотреть, и даже ту, которая раньше открывалась, ну кроме совсем коротких

**Comment by SM-Sergey** [comment]
А вот еще вопрос - зачем в CacheIconToEmf возвращается копия метафайла, а не оригинал? Его что, ричедит может сам внутри  себя прибивать что ли по DeleteEnhMetaFile?
