### ISSUE TITLE
Miranda has crashed without crashlog after changing of account name in account title

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#4046]
### Expected behavior
Account name was renamed without issue.

### Actual behavior
Miranda has crashed. It was like I've killed a process in Task manager.

### Does it work in stable version?
I don't know.

### Steps to reproduce that behavior
1. Launch Miranda.
2. 
3. Open Accounts window.
4. Start to rename IRC account.
5. Type something to get a new name.
6. Press Enter.

Some accounts were connected, chats were opened...

**Comment by georgehazan** [comment]
no, without a crash log it's useless
you can download any free debugging tool (like Windows Debugging Tools or Visual Studio 2017 Community Edition) and report the call stack. These matters are described in our Wiki
