### ISSUE TITLE
NewStory: падение при открытии окна

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4049]
https://forum.miranda-ng.org/index.php?topic=6033.msg30998#msg30998

**Comment by SM-Sergey** [comment]
Это свежезакрытый  #4045

**Comment by georgehazan** [comment]
Какая разница?.. ну подергается оно еще миллисекунд 200

**Comment by SM-Sergey** [comment]
> ну подергается оно еще миллисекунд 200

Вы издеваетесь? Несколько дней назад длинная история открывалась, и можно было при помощи "PgUp" покрутить примерно до 7000-8000 сообщений! Можно было поискать текст, до тех пор, пока не покажет столько сообщений. А теперь тупо падает сразу.
