### ISSUE TITLE
NewStory: баг в скроллинге.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4058]
Открываем какую нибудь большую и длинную историю.

1) Жмем PgUp и держим. Скроллбар то пропадает, то появляется. Но все скроллится.

2) Жмем мышью куда нибудь в скроллбар сильно выше и держим (это почти эквивалент нажатого PgUp).  В какой-то момент из скроллбара пропадает движок. После этого перестают работать всё управление окном - крест закрытия, меню окна в левой верхней кнопке. Однако продолжить скроллить можно колесом мыши или теми же PgUp/PgDn. При этом скроллбар пропадет. Сделав кучу PgUp можно таки добиться появления скроллбара, но элементы управления окном так и не заработают. Закрыть окно можно нажатием Esc.

В системной истории это вроде не проявляется.

**Comment by SM-Sergey** [comment]
В системной истории удалось прибить скроллбар если схватить за движок, потянуть вверх (получив #4056 часть 2), и дождавшись окончания тормозов.

**Comment by georgehazan** [comment]
нет больше тормозов. должно исчезнуть вместе с #4059
