### ISSUE TITLE
WhatsApp Registration

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#406]
**Reported by jaktema on 7 Aug 2015 01:59 UTC**
WhatsApp registration:

**Comment by georgehazan** [comment]
**Comment by jaktema on 7 Aug 2015 02:06 UTC**
WhatsApp?

**Comment by georgehazan** [comment]
**Comment by wishmaster on 7 Aug 2015 08:51 UTC**
Please provide a detailed english description. Use the [russian forums](http://forum.miranda-ng.org/index.php#c3) if you don't speak english.

**Comment by dartraiden** [comment]
#558 is more actual
