### ISSUE TITLE
<unknown> in Nickname field for old IRC accounts in Account window

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#4061]
### Expected behavior
Nick field for account is filled, show nick from Nick field in Nickname field.

### Actual behavior
Nick field for account is filled, but text `<unknown>` in Nickname field.

### Does it work in stable version?
I don't know.

### Steps to reproduce that behavior
1. You need an IRC account with filled Nick field which was added before fix for #4025.
2. Open Accounts window.
3. Click left mouse button on IRC account.
4. You will see `Protocol: IRC` and `Nickname: <unknown>`.

**Comment by georgehazan** [comment]
Один раз нажать Ok в форме опций - и готово
