### ISSUE TITLE
IRC: Miranda can't display list of channels if server asks to wait.

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#4063]
### Expected behavior
Miranda waits interval and re-request + displays channels.

### Actual behavior
Channels on server window does nothing with "Please wait..."

### Does it work in stable version?
I don't know.

### Steps to reproduce that behavior
1. Connect to IRC server.
2. Ask list of channel.
3. Receive `You must be connected for at least ... seconds before you can use this command: LIST` message

**Comment by georgehazan** [comment]
Just repeat the command from the protocol menu
there's no AI to parse server messages
