### ISSUE TITLE
IRC: Mode header sorting channel by number of users

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#4065]
### Expected behavior
Sorting by modes

### Actual behavior
Sorting by number of users.

### Does it work in stable version?
I don't know.

### Steps to reproduce that behavior
1. You should get a list of channel in Channels of server window.
2. Click on Mode head.
3. Click on Mode head again.

Update: this was much bugged than I've expected. Use also next step 2 and 3.

2. Click Number of users header.
3. Click Mode header.
4. Click again. 
5. You get a workable sorting by number of users.
And another one:

2. Click Topic header.
3. Click Mode header.
4. Click Mode header again.
5. You get a workable sorting by modes.

**Comment by georgehazan** [comment]
and no, this dialog on no accounts sorts Modes column by number of users
