### ISSUE TITLE
NewStory: еще баг в скроллинге. Но уже мелкий.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4067]
Если открыть историю (эта не особо большая), то история показывается в окне до конца, но движок скроллера находится не в самом низу.

![2023-12-18 21_48_45-Sergey Mrkov (Offline)](https://github.com/miranda-ng/miranda-ng/assets/34127439/43b084e4-18cf-4dcc-a9d2-a5318357472f)

Если движок схватить, и потянуть вниз - то он вниз не дотягивается, отпрыгивает чуть назад, но содержимое окна "встает" как надо для такого положения движка, чуть сдвинувшись.

![2023-12-18 21_49_24-Sergey Mrkov (Offline)](https://github.com/miranda-ng/miranda-ng/assets/34127439/23feedad-e094-406c-8b0f-d40b42aecb27)

Теперь окно можно доскроллить вниз колесом мыши. Но движок все равно вниз до упора не переместится. Если его схватить и потащить вниз, ситуация повторится.
Если же схватить движок, и дотащить его вверх до самого упора, до начала, и потом обратно утащить вниз - то он встанет на свое место в упоре внизу, после чего все начинает работать нормально во всех положениях.

**Comment by georgehazan** [comment]
Там делается интерполяция на средний размер строки для всех незагруженных сообщений, поэтому после отпускания ползунка он может незначительно сдвигаться. Это не страшно

**Comment by SM-Sergey** [comment]
Не, ну как бы крайние положения-то можно сделать всегда крайними? А в средних и ладно.
