### ISSUE TITLE
NewStory: Тормоза в поиске

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4068]
Открываем огромную историю. Запускаем поиск чего нибудь такого, что там точно не найдется. Ну или очень далеко где-то может найдется. Окно встает в "not responding" с  ростом выделенной памяти.  После того, как поиск прошел один раз всю историю по кругу, все работает шустро.

**Comment by georgehazan** [comment]
Ну ессно, оно же для поиска должно загрузить текст всех сообщений в память, именно это и тормозило при открытии окна. Сейчас в память поднимаются только те события, которые должны показываться на экране

**Comment by SM-Sergey** [comment]
Косяк не в загрузке событий, а в том, что они грузятся в оконной функции, а не где-то в параллельном мире. Чем и вызывают нот респондинг.
