### ISSUE TITLE
NewStory: Convert message to a file transfer не всегда обновляет результат своей работы в окне истории

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4069]
Делаем Convert message to a file transfer. 
Оно делается. Пункт меню пропадает с этого сообщения.
Но само сообщение не всегда изменяется (обновляется). Для очень больших историй, если это делается где-то далеко сзади, почти никогда. Для небольших историй - почти всегда все ОК, но не всегда.
Если NS закрыть, потом открыть - то всегда все ОК - видим оффлайн файл.

Как-то это глубже поотлаживать? Как?

**Comment by SM-Sergey** [comment]
При этом параллельно открытое окно с табсами и табс-журналом всегда обновляется во всех случаях.

**Comment by georgehazan** [comment]
там запускается редактирование события, соотв. срабатывает хук ME_DB_EVENT_EDITER, который ловит NewStory, генерирует текст сообщения заново и отрисовывает контрол.

**Comment by SM-Sergey** [comment]
Ну вот не всегда срабатывает там эта система, причем именно не обновляет текст (если поскроллить туда-сюда, или скрыть-восстановить - рисуется старый текст. Причем чаще не срабатывает, чем срабатывает.

**Comment by georgehazan** [comment]
Есть мнение, что после исправления #4070 оно исчезнет
Так не может быть, чтобы оно что-то исправляло, а что-то нет. Вылью - посмотришь
