### ISSUE TITLE
WhatsApp plugin shows "registration failed" all times

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#407]
**Reported by emusic on 9 Aug 2015 09:49 UTC**
Hello!

I'm trying to use WhatsApp protocol in Miranda NG 0.95.4. Have entered a new phone number (not registered in Whatsapp previously) but clicking "Request code" button always shows "Registration failed" message.

Network log:
# 

[1488](15:17:01) [Connection request to v.whatsapp.net:443 (Flags 11)....
[15:17:01 1488](WhatsApp_1]) [(061478D8) Connecting to server v.whatsapp.net:443....
[15:17:01 1488](WhatsApp_1]) [(061478D8) Connecting to ip 184.173.136.86:443 ....
[15:17:02 1488](WhatsApp_1]) [(780) Connected to v.whatsapp.net:443
[15:17:02 1488](WhatsApp_1]) [(780 v.whatsapp.net) Starting SSL negotiation
[15:17:02 1488](WhatsApp_1]) [(780 v.whatsapp.net) SSL negotiation successful
[15:17:02 1488](WhatsApp_1]) [(061478D8:780) Data sent
POST /v2/code?cc=7&in=913xxxxxxx&to=7913xxxxxxx&method=sms&mcc=250&mnc=020&token=8bbfbaa28a7bb7ebc97de7b6ccbc35ab&id=%84%ee%ce%30%9c%2e%8a%f0%bc%18%80%5b%b6%a2%4e%0d%45%96%07%1f&lg=ru&lc=RU HTTP/1.1
User-Agent: WhatsApp/2.12.68 S40Version/14.26 Device/Nokia302
Accept: text/json
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: deflate, gzip
Host: v.whatsapp.net
Connection: Keep-Alive
Proxy-Connection: Keep-Alive
Content-Length: 0

[15:17:02 1488](WhatsApp_1]) [(061478D8:780) Data received
HTTP/1.1 200 OK
[15:17:02 1488](WhatsApp_1]) [(061478D8:780) Data received
Connection: close
Server: Yaws 1.99
Date: Sun, 09 Aug 2015 09:17:02 GMT
Content-Length: 41
Content-Type: text/json ; charset=utf-8

[15:17:02 1488](WhatsApp_1]) [(061478D8:780) Data received
{"status":"fail","reason":"old_version"}
[15:17:02 1488](WhatsApp_1]) [(061478D8:780) Connection closed internal
[15:17:02 1488](WhatsApp_1]) [(061478D8:4294967295) Connection closed
# [15:17:02 1488](WhatsApp_1]) [Server response: {"status":"fail","reason":"old_version"}

BTW, the plugin connects to port 443 regardless of "Use SSL connection" settings.

Version information:
# 

CPU: Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz [Intel64 Family 6 Model 58 Stepping 9](WhatsApp_1]) [Enabled](DEP) [CPUs](8)
Installed RAM: 16276 MBytes
Operating System: Microsoft Windows 7 Professional Edition, 64-bit Service Pack 1 (build 7601)
Internet Explorer: 8.0.7601.17514 (build 87601)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | Russian/Russian
Free disk space on Miranda partition: 311 MBytes

Miranda NG Version: 0.95.4 build #13028 [inside WOW64](running)
Build time: 22 Apr 2015 3:43:29
Profile: C:\icq\22072305\22072305.dat
Profile size: 35651584 Bytes
Profile creation date: 20 Nov 2013 14:17:09
Language pack: No language pack installed
Service Mode: No

Active Plugins (20):
  AdvaImg.dll v.0.11.0.2 [Apr 2015 3:44:51](22) - Miranda image services 
  AdvancedAutoAway.dll v.0.8.1.1 [Apr 2015 3:46:22](22) - Advanced Auto Away 
  AIM.dll v.0.11.0.1 [Apr 2015 3:44:18](22) - AIM protocol 
  AVS.dll v.0.95.3.4 [Apr 2015 3:43:45](22) - Avatar service 
  Clist_modern.dll v.0.9.1.3 [Apr 2015 3:48:13](22) - Modern contact list 
  CrashDumper.dll v.0.0.5.2 [Apr 2015 3:49:16](22) - Crash dumper 
  DbEditorPP.dll v.3.2.0.2 [Apr 2015 3:49:31](22) - Database editor++ 
  Dbx_mmap.dll v.0.95.3.1 [Apr 2015 3:43:53](22) - Miranda NG mmap database driver 
  Facebook.dll v.0.2.10.6 [Apr 2015 3:47:12](22) - Facebook RM 
  GG.dll v.0.11.0.3 [Apr 2015 3:44:45](22) - Gadu-Gadu protocol 
  HistoryPP.dll v.1.5.1.5 [Apr 2015 22:17:44](15) - History++ 
  ICQ.dll v.0.11.3.2 [Apr 2015 3:45:02](22) - IcqOscarJ protocol 
  Import.dll v.0.95.4.2 [Apr 2015 3:43:44](22) - Import contacts and messages 
  IRC.dll v.0.11.0.3 [Apr 2015 3:44:43](22) - IRC protocol 
  Jabber.dll v.0.11.0.4 [Apr 2015 3:45:06](22) - Jabber protocol 
  KeepStatus.dll v.0.9.0.2 [Apr 2015 3:46:25](22) - Keep status 
  MSN.dll v.0.11.1.2 [Apr 2015 3:45:10](22) - MSN protocol 
  TopToolBar.dll v.0.8.0.4 [Apr 2015 3:47:45](22) - TopToolBar 
  WhatsApp.dll v.0.1.2.14 [May 2015 2:33:05](2) - WhatsApp protocol 
  Yahoo.dll v.0.11.0.1 [Apr 2015 3:44:47](22) - Yahoo protocol 

Unloadable Plugins (1):
  DbChecker.dll v.0.0.0.0 [Apr 2015 3:49:50](22) - <unknown> 
## Protocols and Accounts:

ICQ                      1 - Enabled 0 - Disabled  Loaded
WhatsApp                 1 - Enabled 0 - Disabled  Loaded
MetaContacts             1 - Enabled 0 - Disabled  Loaded
## Icon Packs:

 HistoryPP_icons.dll [Apr 2015 3:50:39](22)
 Proto_AIM.dll [Apr 2015 3:47:46](22)
 Proto_Facebook.dll [Apr 2015 3:47:44](22)
 Proto_GG.dll [Apr 2015 3:47:47](22)
 Proto_ICQ.dll [Apr 2015 3:47:48](22)
 Proto_IRC.dll [Apr 2015 3:47:48](22)
 Proto_Jabber.dll [Apr 2015 3:47:49](22)
 Proto_MetaContacts.dll [Apr 2015 3:55:14](22)
 Proto_MSN.dll [Apr 2015 3:47:49](22)
#  Proto_WhatsApp.dll [Apr 2015 3:55:32](22)

Tried to attach log and version information as files but as I click "I have files..." in my Opera 12.17 browser, nothing happens except a tick mark.

**Comment by georgehazan** [comment]
**Modified by emusic on 9 Aug 2015 09:50 UTC**

**Comment by georgehazan** [comment]
**Comment by mikalair on 9 Aug 2015 18:37 UTC**
[http://wiki.miranda-ng.org/index.php?title=Reporting_bugs]

```

Update to the latest development version.
```

**Comment by georgehazan** [comment]
**Comment by emusic on 9 Aug 2015 18:42 UTC**
Should I update plugin DLL only, or entire Miranda tree? Is development version as stable as the release?

**Comment by georgehazan** [comment]
**Comment by mikalair on 10 Aug 2015 11:21 UTC**
http://wiki.miranda-ng.org/index.php?title=Installation_and_update#Updating_Miranda_NG

**Comment by dartraiden** [comment]
#558 is more actual
