### ISSUE TITLE
NewStory: Если окно минимизировать, а потом восстановить - движок скроллера улетает в конец.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4070]
Открываем историю.
Тянем куда нибудь движок скроллера, или скроллим иным способом.
Минимизируем окно.
Достаем его из небытия - можно по Alt-Tab, можно кликом в таскбар, без разницы. Скроллер улетает в конец, как собственно и содержимое окна. А должно быть - где минимизировали, там и остались.

**Comment by georgehazan** [comment]
Нет, во всех окнах лога в Миранде стоит одинаковая реакция - на приход WM_ACTIVATE идет проматывание в конец. Это никак не зависит от NewStory

**Comment by SM-Sergey** [comment]
Но это же косяк - в логах, да, пусть. А в просмотре истории то???? Полгода искал нужное место, посмотрел, скрыл, поделал что-то, восстановил, и всё, искать заново?
