### ISSUE TITLE
NewStory: новые тормоза, и даже креш.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4073]
Опять на очень большой истории начинает все тормозить, клинить, вставать в нот респондинг. Но по-другому, отображает быстро, но потом начинает какие-то действия "в себе", тыкая мышью в сообщения реакция их выделения очень замедленная, тормоза, и нот респондинги. Если потащить скроллбар вверх, то вообще не могу дождаться реакции на нажатие кнопки на сообщении. И в конце концов даже упало. Смайладд отключен на всякий случай.

[crash20231221105724.txt](https://github.com/miranda-ng/miranda-ng/files/13737689/crash20231221105724.txt)

соответственно, #4069 проверить не получается, так как оно все в этой большой истории где-то в середине.

**Comment by georgehazan** [comment]
вариантов особенных нет... ну хорошо, будем грузить всё в текущем потоке с помощью таймера

**Comment by SM-Sergey** [comment]
Ну можно же только поиск запускать впараллель, а без поиска - как работало пусть так и работает. Ведь незачем всё грузить в фоне, пока нет поиска. И Sleep(0) делать на каждый load в поиске. Или даже NtYieldExecution, хотя конечно оно не документировано, но работает (аналог для ZwYieldExecution, который документирован для драйверов в кернел-моде).

**Comment by georgehazan** [comment]
> Ну можно же только поиск запускать впараллель, а без поиска - как работало пусть так и работает

А какой смысл вообще тогда? Поиск и так спокойно работает в лобовую, ему вообще всё это не нужно

**Comment by SM-Sergey** [comment]
Так суть предыдущего тикета, который был "прекурсором" этого, изначально был о том, что поиск на очень большой истории вгоняет миранду в нот респондинг. А если бы поиск искал в фоне, то сразу нет никаких вопросов. И было бы прекрасно, если бы он при этом мигал-крутил чем нибудь около поля ввода текста, показывая, что работает. Но не мешал жить остальной миранде и вести беседы.
А вот зачем с открытия окна грузить всю историю, мне как раз непонятно.
