### ISSUE TITLE
XEP-0480: SASL Upgrade Tasks support

### ISSUE THREAD

**Issue by Neustradamus** [miranda-ng/miranda-ng#4074]
Dear @miranda-ng team,

After jabber.ru MITM, can you add the support of "XEP-0480: SASL Upgrade Tasks" for more security?
- https://xmpp.org/extensions/xep-0480.html

Thanks in advance.

Linked to:
- https://github.com/miranda-ng/miranda-ng/issues/3140
- https://github.com/miranda-ng/miranda-ng/issues/3792
- https://github.com/miranda-ng/miranda-ng/issues/3793
- https://github.com/miranda-ng/miranda-ng/issues/3794
- https://github.com/miranda-ng/miranda-ng/issues/4074
- https://notes.valdikss.org.ru/jabber.ru-mitm/
- https://snikket.org/blog/on-the-jabber-ru-mitm/
- https://www.devever.net/~hl/xmpp-incident
- https://blog.jmp.chat/b/certwatch

**Comment by georgehazan** [comment]
@Neustradamus on which server could I test all that stuff?

**Comment by Neustradamus** [comment]
@georgehazan: ejabberd has not yet the support:
- https://github.com/processone/xmpp/issues/80

The XEP-0480 supports is already in:
- Monal IM: https://github.com/monal-im/Monal/blob/9e189f448b8677533b2b832fa48e08cabc5d7b27/monal.doap#L703

cc: @tmolitor-stud-tu, @prefiks.

**Comment by Neustradamus** [comment]
@georgehazan: Can you look for Miranda NG?

@badlop has talked about XMPP Clients here:
- https://github.com/processone/ejabberd/issues/4301

**Comment by georgehazan** [comment]
> Can you look for Miranda NG?

Is there a public server available? I don't wanna setup ejabberd

**Comment by Neustradamus** [comment]
@weiss, @tmolitor-stud-tu, @prefiks: conversations.im? movim.eu? Others?

**Comment by weiss** [comment]
My dev server is messaging.one, you can [register an account][1] and ask me (`holger@jabber.fu-berlin.de`) to configure whatever you need to test things.

[1]: https://messaging.one/register/new/

**Comment by georgehazan** [comment]
@weiss wrote you an email

**Comment by Neustradamus** [comment]
@georgehazan: Have you seen this important fix from @tmolitor-stud-tu?
- https://github.com/xsf/xeps/pull/1403

It has been updated in ejabberd/xmpp by @weiss.

Linked to:
- https://github.com/processone/xmpp/issues/80#issuecomment-2509482891
- https://github.com/processone/xmpp/commit/f5551549e4ba7c27ba84ac4ba7ee7386644b816a

**Comment by georgehazan** [comment]
> Have you seen this important fix from @tmolitor-stud-tu?

I'm not related to ejabberd, I implement those features and consult with @weiss  if smth goes wrong

**Comment by Neustradamus** [comment]
You have not understood, @tmolitor-stud-tu has done a change in the XEP-0480 (not merged yet by XSF Editor) which solves a problem. Please look the change to have a good support in Miranda NG.

**Comment by georgehazan** [comment]
@Neustradamus for now only SHA256 works with ejabberd, SHA512 always fails, so it remains commented out for now

**Comment by Neustradamus** [comment]
@georgehazan: Thanks for your commit! :)
- https://github.com/miranda-ng/miranda-ng/commit/3813c8e151beafef2f3e790573a59897c654b734

Important: The @tmolitor-stud-tu XEP-0480 fix has been merged!

XEP-0480 0.2.0 is now official:
- https://xmpp.org/extensions/xep-0480.html

Hope that you can find a solution with @weiss for SHA-512.
