### ISSUE TITLE
StdMsg: при скрытии поля ввода оно скрывается навсегда

### ISSUE THREAD

**Issue by Deadooshka** [miranda-ng/miranda-ng#4076]
Приходит уведомление с канала, попап (popup plus), открываешь чат - поля ввода текста нет, и везде пропало. Лечится только заменой базы на бекап.
![Clipboard0](https://github.com/miranda-ng/miranda-ng/assets/3809026/4aac9ba9-6330-4eb6-aae2-141607e21881)

**Comment by dartraiden** [comment]
> открываешь чат - поля ввода текста нет

Это правильно, оно скрывается для каналов, поскольку ответить туда вы не можете.

> и везде пропало

Это как?

**Comment by Deadooshka** [comment]
Во всех протоколах пропадает поле.

**Comment by dartraiden** [comment]
@georgehazan минимальный сетап для воспроизведения

- переключаемся на stdmsg (выгружаем табсы)
- выводим телеграм в онлайн
- открываем какой-нибудь канал, где у нас нет прав писать, поэтому поле ввода скрыто
- закрываем окно stdmsg
- открываем какой-нибудь чат, приват, избранное, что угодно

результат: поле ввода пропало везде

**Comment by dartraiden** [comment]
@Deadooshka вместо отката базы можно через редактор базы стереть `splitterPos` из модуля `[SRMM]`

**Comment by Deadooshka** [comment]
После обновления ничего не изменилось. Открытие телеграм-канала без поля ввода текста оно скрывается для всех протоколов.

**Comment by georgehazan** [comment]
@Deadooshka в каком месте? Я только что попробовал - всё ок, переключаю таб с канала на беседу - поле ввода в норме

**Comment by georgehazan** [comment]
@Deadooshka у меня всё норм, делаю так, как ты сказал - открываю канал, закрываю окно, открываю приват
