### ISSUE TITLE
Сообщения в формате RTF показываются как исходники

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4077]
Раньше, в древности, протокол MRA видимо присылал сообщения в формате RTF. И в то время эти сообщения читались без проблем в миранде-до-ng. Теперь же, если открыть архивную копию БД того времени, после ее преобразования в современный формат видим голый RTF:

![2023-12-26 16_15_39-Игорь Митрохин - history  1465 messages total](https://github.com/miranda-ng/miranda-ng/assets/34127439/79cd47ff-afab-40a7-b83a-084db101c45e)

Если сделать экспорт в json там будет ровно это же, что и на скриншоте. Так ведут себя и встроенный журнал табсов, и ньюстори.

Надо, чтобы оно было хоть как-то читабельно.

**Comment by georgehazan** [comment]
Выгрузи plz пару таких сообщений в JSON, не перебивать же это руками с экрана

**Comment by SM-Sergey** [comment]
Ну вот второе из этих
[msg.json.gz](https://github.com/miranda-ng/miranda-ng/files/13772756/msg.json.gz)

**Comment by SM-Sergey** [comment]
Глядя на код, это надо делать проверку и исправление БД для этого? Верно?

**Comment by georgehazan** [comment]
Да, База данных - проверить и взвести соотв. опцию

**Comment by SM-Sergey** [comment]
Сработало. Нормально так, 9800 событий исправлено. Спасибо!
