### ISSUE TITLE
Сделать меню групп доступнее

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4078]
У нас есть такая штука, как меню групп. Это меню, которое вызывается нажатием пкм по пустому месту в клисте.

<img width="503" alt="Miranda64_eTeZkmvRQ5" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/e0ff701b-7d29-40df-b454-06247fecf83e">

Проблема в том, что у меня такой скин и такие настройки Миранды, что пустого места в клисте просто нет. И мне каждый раз, когда надо, например, создать новую группу (что делается через это меню), приходится лезть в настройки и выключать "автоматическое изменение размера клиста" и "запрет ручного изменения размера". После этого я могу растянуть клист по вертикали, получить, наконец, пустое место и добраться до этого меню. А потом обратно возвращать настройки.

В нашей конфе один из пользователей тоже отметил, что хорошо бы иметь ещё какой-то способ вызвать это меню. Может, я не знаю, в главное меню его встроить в виде подменю...

**Comment by dartraiden** [comment]
Но ты же просто добавил пункт "создать группу" в меню группы. Остальные пункты так и остались недоступными...

**Comment by georgehazan** [comment]
в Миранде для подгрупп вообще не вызывается меню групп
