### ISSUE TITLE
TabSRMM: в опциях для контакта само окно с опциями налезает на закладки, и прочие баги там же.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4079]
Собственно, вот:
![2023-12-27 00_10_23-ICQ - заметки для себя  — Mozilla Firefox](https://github.com/miranda-ng/miranda-ng/assets/34127439/0243c6ea-0d82-4db0-a972-9405f84f84a6)

**Comment by SM-Sergey** [comment]
И там, как минимум, не все работает. Если я "Show avatar in message window" для юзера ставлю "Never show at all" то это и не сохраняется и не работает. Если открыть заново - опять получаем "Use global setting"

**Comment by georgehazan** [comment]
уже не налезает

**Comment by georgehazan** [comment]
> Если я "Show avatar in message window" для юзера ставлю "Never show at all" то это и не сохраняется и не работает. Если открыть заново - опять получаем "Use global setting". C "Always trim message log to" та же петрушка.

Ни малейших проблем с этим у меня
