### ISSUE TITLE
TabSRMM: непонятные проблемы с кодировкой после Load Server History

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4080]
Вот кусок истории, с которым я пытаюсь разобраться с удалением дублей, которое их не удаляет (там на поверку разница в таймстампе на какие-то доли секунды между ними, но они точно дубли, я это априори знаю, одно приходило в ту дату онлайн, другое потом через лоад сервер хистори - но это другое дело)

![2023-12-27 00_42_37-Игорь (Offline)](https://github.com/miranda-ng/miranda-ng/assets/34127439/ef565051-afa1-446c-b571-01f9700037af)

Я делаю Load Server History, и почему-то во встроенном журнале табсов происходит какой-то юникодный косяк. При этом в ньюстори все ОК:
![2023-12-27 00_45_11-Игорь - history  5637 messages total](https://github.com/miranda-ng/miranda-ng/assets/34127439/bffe8ecb-0f31-4ecc-afe9-5ed8cc74e796)

Здравствуй восстановление из резервной копии...

Если сделать экспорт в json - то изначально были все сообщения в обычной 8-битной windows1251, а после лоад сервер хистори стали через одно в юникоде, то есть так "обновились".

PS - протокол ICQ, если это имеет значение.
PPS - из каждой пары первое сообщение с чуть меньшим таймстампом - это из лоад сервер хистори, оно "портится" при очередном лоад сервер хистори, а следующее, с чуть большим таймстампом, это которое в то время приходило в онлайне, оно, понятно почему, не трогается,

**Comment by SM-Sergey** [comment]
Это случается, если текст отредактирован (как минимум, в ICQ). Первое сообщение прилетает норм, а результат редактирования - имеет юникодный глюк в табсах и в json-е тоже

**Comment by georgehazan** [comment]
> Не должно быть такого, что оригинальное сообщение прилетает в нормальной кодировке, а отредактирвоанное в юникоде.

В Миранде нет другой кодировки, кроме юникода. Вот эти все старые заморочки, которые были в старой аське, померли. Дублируется же оно из-за того, что при загрузке истории прописывается серверный номер сообщения, а в старой базе их нет

**Comment by SM-Sergey** [comment]
Ну а как пофиксить-то те сообщения, которые в результате редактирования до этого исправления "оюникодились" в табсах? Они по-прежнему в виде кракозябр отображаются.

**Comment by georgehazan** [comment]
> Ну а как пофиксить-то те сообщения, которые в результате редактирования до этого исправления "оюникодились" в табсах? Они по-прежнему в виде кракозябр отображаются.

Можно попробовать через dbchecker, там есть опции для фиксинга utf8

**Comment by SM-Sergey** [comment]
Ну я чуть выше писал, что они не лечатся этой опцией....
