### ISSUE TITLE
tabSRMM: скрывать вкладку "Журнал" в индивидуальных настройках контакта, если для приватов выбран сторонний журнал

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4081]
Эту страницу нужно скрывать, т.к. это настройки встроенного журнала

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/dc8abe35-d4c7-4ffb-9b58-9991a9f5c0ad)

**Comment by SM-Sergey** [comment]
А почему скрывать? А не менять её содержимое на то, которое соответствует установленному просмотрщику журнала?

**Comment by dartraiden** [comment]
Потому что не существует сторонних журналов, поддерживающих настройки per-contact.
