### ISSUE TITLE
ICQ: при прилёте "Избранного" оно помещается в несуществующую группу

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4082]
После того, как мы реализовали поддержку "Избранного" оно у меня в базу влетело с группой "Conferences". Но такой группы в клисте у меня не было и группа почему-то не создалась. Результат: Избранное невидимо, т.к. находится в несуществующей группе.

Таким образом:
1) нужно расследовать, почему не создаётся группа
2) почему Избранное влетает в Conferences? Может, лучше вообще без группы его втаскивать? Это же не групчат.

**Comment by georgehazan** [comment]
Эта группа всегда создается сервером аськи, туда складываются групчаты
Может, конечно, ты ее стер руками, но у всех прочих такая группа есть

**Comment by dartraiden** [comment]
Ну, групчатов у меня не водится, так что, наверное стёр когда-то.
