### ISSUE TITLE
Options/Contacts - непонятки с группами.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4083]
1) Почему в Options/Contacts/Ignore не показываются группы, в которых нет контактов, а в Options/Contacts/Visibility показываются? По логике должно быть одинаково, и пустые группы показывать надо либо и там, и тут, если в обоих местах предусмотрена работа с изменением структуры групп (создание, переименование, удаление, т.п.), либо ни там, ни тут, а настройку структуры групп надо вынести в отдельную страницу опций, что было бы более логично. А то без поллитры не разберешься, где искать настройку структуры групп, пока случайно ПКМ на группе где-то тут не кликнешь. В любом случае, как ни крути, в обоих этих страницах настроек показ групп должен быть унифицирован и работать одинаково.
На нелогичность этого указывает и то, что если создать пустую группу/подгруппу в Options/Contacts/Ignore, и потом переоткрыть эту страницу, то она из нее пропадет, так как в ней нет контактов.

2) В Options/Contacts/Visibility некоторые непустые группы не имеют рядом с собой информацию о количестве контактов в них.
вот пример:
![2023-12-27 02_03_59-Miranda NG options](https://github.com/miranda-ng/miranda-ng/assets/34127439/4ae4ce0e-cd7c-42df-915f-41e064871dde)
нажимаем на все плюсики, и видим что в двух группах есть по контакту, но рядом с ними это не отмечено:
![2023-12-27 02_04_49-Miranda NG options](https://github.com/miranda-ng/miranda-ng/assets/34127439/a87eb4d0-0579-48a8-b3ce-2e4494b96393)

UPD: к слову, в ICQ контакты с ником "[deleted]" стерты на сервере совершенно условно - из них можно спокойно достать историю по Load Server History или посмотреть ее в оф. клиенте. Не удивлюсь, если они еще и в онлайн выйти могут :)

3) если пустые группы показываются (см. п. 1), то если в них нет ни одного контакта и ни одной подгруппы, то и состояния "плюсик в квадратике" у них быть не должно никогда - там нечему сворачиваться, а значит не должно быть и свернутого состояния в принципе.

4) Я не понял, как создать новую группу. Как подгруппу - да. А как группу - нет. Удалить или переименовать, пожалуйста, а до создания я, как говорится, не допёр.

**Comment by dartraiden** [comment]
> Я не понял, как создать новую группу

https://github.com/miranda-ng/miranda-ng/issues/4078

**Comment by SM-Sergey** [comment]
Во, спасибо! Есть оказывается у меня место в клисте, где это работает. ПКМ на разделителе "-------- Offline -------". Это вообще не то, что без поллитры не найти, а без литра :)

Но, все же, Add Group должно быть и где-то там, о чем я здесь, а не только Add subgroup.

**Comment by SM-Sergey** [comment]
И, вот еще... А зачем вообще разделены Visibility и Ignore на две разные страницы? В чем великий смысл? Можно Visibility вообще убить, сделать одну страницу Ignore/Visibility и добавить туда просто еще один столбец - видимости. Собственно, и по смыслу, невидимость это тоже способ частичного игнора...

**Comment by SM-Sergey** [comment]
В общем, по итогу, моё мнение вот такое:
- Должна быть одна страница настроек Ignore/Visibility, где и то и это вместе. В ней не должно быть никакого управления группами, и никогда не должны показываться пустые группы-подгруппы. И кроме установки-сброса галок игноров и видимости (для контактов и для групп-подгрупп целиком) там ничего другого не должно делаться с контактами.
- Должна быть страница настроек Groups, устроенная внешне подобным образом, но в ней всегда должны отображаться пустые группы, в ней можно создавать группы/подгруппы, переименовывать, удалять, менять порядок, перемещая выше-ниже, на подуровень-из подуровня, и там же можно и контакты по группам перемещать. Но никаких других дел для контактов там быть не должно, так как это спец-страница настроек групп, а не клист.

**Comment by dartraiden** [comment]
В том, что в старые времена невидимость и игнор в протоколах были вообще о
разном. Игнор это когда ты не хочешь общаться с чуваком. А невидимость,
например, когда ты сидишь в инвизе для всех (статус Невидимый), но хочешь,
чтобы, скажем, твоя девушка всегда тебя видела, поэтому добавляешь для нее
исключение.

ср, 27 дек. 2023 г., 03:00 Sergey Markov ***@***.***>:

**Comment by SM-Sergey** [comment]
Старые времена это когда? Я в аське с 2003. Инвиз всегда в те времена использовал для того, чтобы для отдельных особо назойливых быть как бы в оффлайне, а остальные меня видели. То есть, исключение всей толпе, и двум-трем нет исключения. Но, если уж на то пошло, были и дырки-способы проверки, реальный оффлайн у контакта, или он для тебя в инвизе, которые вполне себе работали... Так что это прокатывало только для особо назойливых и туповатых :)

**Comment by SM-Sergey** [comment]
Кстати... А сейчас ICQ-контакту там можно установить "Always invisible" - а что, это сейчас работает?

**Comment by dartraiden** [comment]
Емнип, для WIM мы под невидимостью понимаем серверный игнор.

**Comment by SM-Sergey** [comment]
> тогда это всё можно будет выпилить.

Ну в любом случае я пока не вижу никаких противопоказаний для переноса функциональности целой отдельной страницы в колонку в странице игноров, а в странице с инвизами организовать (оставить, и затем дополнить) только работу с группами, переименовав ее в Groups. И убрать при этом действие настроек показа пустых групп на эти окна.

**Comment by dartraiden** [comment]
Зачем для работы с группами делать отдельную страницу в настройках?
Для этого есть список контактов.

**Comment by SM-Sergey** [comment]
> Зачем для работы с группами делать отдельную страницу в настройках?

Не надо ее делать, она там есть. Там можно группу переименовать, удалить. Там можно создать подгруппу и удалить подгруппу и ее переименовать. То есть там есть ПОЧТИ все, кроме создания группы в корне.
То есть из доделок там - только добавить создание группы в корне, и всё. Малая кровь и красивая функциональность.

**Comment by georgehazan** [comment]
> Да, везде должно зависеть от состояния настройки "Скрыть пустые группы"

Это зависит от крыжика, с которым создается контрол клиста, можно скрывать, а можно не скрывать, как программист захочет

**Comment by georgehazan** [comment]
> В будущем - добавить еще перемещение группы вверх или вниз, на уровень выше (в подгруппу) и на уровень ниже (из группы/подгруппы)

Это зачем? Оно прекрасно таскается мышью куда надо

**Comment by georgehazan** [comment]
п.4 пофикшен, клист контрол в Visibility помер, так что если найдется где-то ещё - продолжим

**Comment by SM-Sergey** [comment]
А как теперь в "игнорах" увидеть пустые группы, чтобы их удалять/редактировать/делать подгруппы?
И п.2 так и остается на повестке.

**Comment by dartraiden** [comment]
Включите показ пустых групп в клисте (пкм по свободному месту в клисте).

> контакты с ником "[deleted]" стерты на сервере 

Они не стёрты на сервере, а заблокированы - в них невозможно влогиниться (известен лишь один случай, когда такой аккаунт по какой-то ошибке ожил).

**Comment by SM-Sergey** [comment]
> Включите показ пустых групп в клисте (пкм по свободному месту в клисте)

Во первых, у меня нет в клисте свободного места, кликать некуда. Во вторых, не нужны они мне в клисте видимые, они мне нужны именно тут, где теперь существует вся инфраструктура для работы с группами, после того, как сюда добавили недавним фиксом пункт "Add Group". 
В общем, пока потеряли функциональность. Чистой воды "regression". Надо сделать и тут "показать пустые группы", наравне с клистом, но отдельно от него, чтобы все те, кто привык работать с группами через вкладку видимости, не потеряли возможность работы с группами здесь без перекореживания клиста. Либо просто всегда безусловно их тут показывать, это ничего не испортит.


> Они не стёрты на сервере, а заблокированы

По факту, контакт превращается в [deleted], когда пользователь сам себя удалил. Это я сам наблюдал лично несколько лет назад "вживую". Дальше, в таком виде он существует у всех, у кого он был в клисте, со всей историей на сервере. Его можно удалить из клиста. И его потом можно обратно добавить в клист по UIN и вся история подтянется с сервера! То есть, удаление "себя" не удаляет историю с сервера. Но его, удаленного, нельзя найти ни по почте, ни по нику, ни каким либо другим способом, только по UIN.  А вот как он может "ожить" - ну вероятно по запросу его хозяина на восстановление, это я не знаю как, наверное через техподдержку.
Но это не по теме.

**Comment by dartraiden** [comment]
> В общем, пока потеряли функциональность. Чистой воды "regression".

https://xkcd.com/1172/

**Comment by dartraiden** [comment]
<img width="503" alt="Miranda64_aHtehA13ax" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/5c1ea3d9-a727-4a4e-bbb0-a478f82167a8">

**Comment by SM-Sergey** [comment]
> более того, эта опция есть и в настройках

Не помогло. В закладке опций с игнорами она не влияет на показ пустых групп. Хотя вроде и не должна была.

> Надо упростить доступ к меню клиста, как я и предлагал, а не управлять группами через ~жопу~игнор.

Управлять группами в клисте это еще большая и более глубокая жопа, чем старый и привычный способ. Мало того, что клист - совершенно нелогичное место для этого, да еще и требует перенастроек клиста перед использованием, и возвращение его настроек потом назад. Клист - это только лицо миранды, а не место для засовывания в него всех мух с котлетами в один фарш. Более того, у меня в клисте группы-подгруппы вообще отключены обычно, так как они используются почти всегда только для группового изменения свойств при работе с игнорами и ранее инвизами.
Сделайте тогда отдельное управление группами, как оно было в визибилити. Как я это сразу просил, вместо тупого убийства этого блока настроек. Хотя - полное управление группами полезно и в игнорах тоже, так как одно с другим непосредственно связано  (занят делом - пустил группу "лишних" в игнор, а коллег оставил, освободился - отключил "лишним" игнор, подтянул историю с сервера, и отвечай всем).

Или это так в планах - минимизировать миранду методом убийства удобных, привычных и нужных вещей, которые кому-то вдруг кажутся лишними? Что следующее на очереди?

-----------------------
Более того. В странице с игнорами имеется групповое выделение контактов через галки, которые можно ставить и снимать группам. Хотелось бы там еще видеть возможность переместить выделенные (помеченные галками) контакты в другую группу, а не только по одному. И иметь возможность сделать "Load Server History" выделенным контактам, чтобы это можно было делать одним действием после снятия игнора группе.

**Comment by georgehazan** [comment]
> Сделайте тогда отдельное управление группами, как оно было в визибилити. Как я это сразу просил, вместо тупого убийства этого блока настроек.

Точно нет. Визибилити прибили за то, что такой сущности в Миранде больше нет.

> Клист - это только лицо миранды, а не место для засовывания в него всех мух с котлетами в один фарш.

Классная логика. Эксплорер - это лицо винды, поэтому оттуда надо убрать всё управление папками. Приехали

> Более того, у меня в клисте группы-подгруппы вообще отключены обычно,

А у меня полторы тысячи контактов, и группы постоянно включены, более того, они трехуровневые. И что теперь?

> Управлять группами в клисте это еще большая и более глубокая жопа, чем старый и привычный способ

Старого и привычного способа, отличного от редактирования групп в клисте, никогда не было. Есть редактор серверных групп, но он не касается клиста вообще

**Comment by SM-Sergey** [comment]
> Старого и привычного способа, отличного от редактирования групп в клисте, никогда не было.

Как это нет? Если он есть. Он работает так, как и раньше работал, в окне настроек игноров. Если на отдельную, аналогичную этому окну, систему настройки групп - "однозначно нет" - то сделайте просто возможность видеть пустые группы в настройках игноров - всё, этого будет достаточно (раньше они были видны в инвизах, и именно окно настройки инвизов было одновременно и окно конфигурирования групп - теперь нет). Пусть там, в игнорах, хотя бы всегда будут видны все пустые группы - и всё, удобное и привычное потерянное управление группами будет восстановлено.

>А у меня

Ну понятно, оставить надо только то, что "а у меня". А то, что работало удобно для толпы других - убить. Так?

**Comment by georgehazan** [comment]
> Как это нет? Если он есть. Он работает так, как и раньше работал, в окне настроек игноров.

Ты удивишься, но в опциях игнора настраивается игнор, а не группы.

> Если на отдельную, аналогичную этому окну, систему настройки групп - "однозначно нет" - то сделайте просто возможность видеть пустые группы в настройках игноров

Зачем, если для настройки игнора это вообще не актуально.

> и именно окно настройки инвизов было одновременно и окно конфигурирования групп - теперь нет)

– В спальне принимать пищу, – заговорил он слегка придушенным голосом, – в смотровой читать, в приёмной одеваться, оперировать в комнате прислуги, а в столовой осматривать. Очень возможно, что Айседора Дункан так и делает. Может быть, она в кабинете обедает, а кроликов режет в ванной. Может быть. Но я не Айседора Дункан!

> Ну понятно, оставить надо только то, что "а у меня". А то, что работало удобно для толпы других - убить. Так?

Надо оставить максимальный вариант, который может быть использован всеми. Никакого урезания не должно быть

**Comment by SM-Sergey** [comment]
> Ты удивишься, но в опциях игнора настраивается игнор, а не группы.

Да??? Там всю жизнь настройка групп была и есть. Именно там в меню по ПКМ всегда было и сейчас есть создание, переименование, удаление групп и подгрупп.  И это единственный привычный и удобный способ работы с группами.

> Зачем, если для настройки игнора это вообще не актуально.

Как раз именно для настройки игнора это очень актуально, так как почти всегда игнор включается и выключается группам, а не отдельным пользователям, в зависимости от текущей загруженности работой, например. И там же надо пересобирать народ по группам игнорирования, в зависимости от того, как меняются рабочие группы по разным проектам.  То есть, это сейчас работает почти хорошо. За исключением:
- не видно пустые группы (раньше было видно в визибилити, теперь нигде)
- нельзя сделать Load Server History сразу всей группе (после того, как с нее снят игнор - надо увидеть, что там все понаписали)
- нельзя несколько выделенных галками контактов перенести одним действием в другую группу.
