### ISSUE TITLE
Удалить настройки невидимости

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4085]
<img width="503" alt="Miranda64_1SSpZxMLQF" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/c1dd665f-78e9-4715-9d56-7ab85b3516ba">

Я отсмотрел добрый десяток протоколов. Даже у протоколов, у которых поддерживается невидимость (жаббер, вк) в этом диалоге ничего не настраивается.

Настраивается только для аськи, но в аське инвиза нет. Мы когда-то вместо инвиза прикрутили тут серверный игнор.

В связи с этим, предлагаю посмотреть по исходникам, умеет ли какой-то ещё протокол в настройки инвиза. Если никто не умеет, то, вероятно, пора их выпилить.

**Comment by SM-Sergey** [comment]
> Если никто не умеет, то, вероятно, пора их выпилить.

Ну не вот прямо выпилить, а серверный игнор перенести в игнор. А тут оставить только всю работу с группами-подгруппами, и переименовать в "Группы". Все таки, работать с группами и подгруппами удобнее здесь, а не в клисте.

**Comment by dartraiden** [comment]
Один тикет - одна задача. Добавление раздела управления группами стоит сделать отдельной задачей, не связанной с удалением игнора.

**Comment by SM-Sergey** [comment]
А что такое ростер? Знаю БД миранды, куда можно добавить контакт. Знаю серверный клист. А ростер, это где?

> не связанной с удалением игнора.

Очень даже связаный - в визибилити на 98% уже сделана вся функциональность управления группами. Я писал, что для начала там нету только создания группы в корне (те самые 2% - один пункт меню) Соответственно, если его "выпилить", то есть убить, то все это придется делать заново. А можно просто аккуратно "подпилить", и сразу будет удобное рабочее управление группами.

> Нет, серверный игнор должен жить в меню протокола 

Но должен быть доступен и список - кто у меня в серверном игноре.

**Comment by georgehazan** [comment]
> В связи с этим, предлагаю посмотреть по исходникам, умеет ли какой-то ещё протокол в настройки инвиза. Если никто не умеет, то, вероятно, пора их выпилить.

В телеге и вацапе (и, возможно, Дискорде) есть возможность заблочить чувака на сервере, но вряд ли это является невидимостью

**Comment by dartraiden** [comment]
Ну, как и в аське. Когда ты блочишь чувака на сервере, он помимо прочего лишается возможности видеть твой статус. Исходя из этого соображения мы прикрутили серверный игнор сюда в ICQ-WIM.

**Comment by dartraiden** [comment]
Если верить сорцам, эта фигня используется в аське (выше выяснили, что зря), в погоде (там она бесполезна, т.к. контакты погоды это не живые люди и скрывать от них наш статус бессмысленно) и в GG (там оно заявлено, но не используется).
