### ISSUE TITLE
Discord: after some last commits only active users are shown in channel nicklist

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4096]
До последних коммитов в никлисте показывались все пользователи. Это было неудобно - невозможно было понять, кто онлайн в чате, а кто нет.

После последних коммитов стало наоборот: в никлисте показываются лишь те, кто онлайн вот прямо сейчас. Это чуток удобнее, но можно сделать лучше.

Предлагаю сделать компромиссный вариант:
- те, кто онлайн сейчас, показываются обычным цветом и перемещаются в верхнюю часть никлиста
- те, кто оффлайн, показываются в никлисте сереньким, как, например, в жаббере показываются отсутствующие

Официальный клиент дискорда примерно так и показывает: вверху списка те, кто сейчас активен, а дальше серенькие те, кто неактивен. При этом, все они отсортированы по алфавиту, т.е.

(активен) A
(активен) X
(неактивен) B
(неактивен) Y

**Comment by georgehazan** [comment]
Конкретно в Дискорде вообще нет такого понятия, как никлист для конкретного канала, список пользователей является общим для всех каналов гильдии и запоминается в текстовом файле по мере того, как проявляются определенные участники (пишут сообщения, например). Соотв. их статус вообще никак не учитывается
