### ISSUE TITLE
MRA: после протухания токена сессии протокол не логинится

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4099]

**Comment by georgehazan** [comment]
К изменениям в нетлибе отношения не имеет

**Comment by dartraiden** [comment]
Настолько не имеет, что при откате на старый билд работает?

**Comment by dartraiden** [comment]
Собственно пруф: я беру профиль из "новой" миранды, которая выдаёт ошибку, кидаю его к "старой" и она входит без проблем.

![mstsc_FtFJgO35ro](https://github.com/miranda-ng/miranda-ng/assets/5046855/cc82e31e-7178-4ddb-943e-2e8147b722a6)
