### ISSUE TITLE
Контакт "Favorites" переименовывается, но переименование не сохраняется.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4105]
Мне необходимо переименовать "Favorites" в себя любимого ("Sergey Markov"). Я делаю ПКМ->Rename, переименовываю. Все работает красиво и хорошо, пока я не перезапущу миранду. После перезапуска миранда теряет информацию о том, что я переименовал этот контакт, и опять появляется этот гадкий и богомерзкий "Favorites". Приходится переименовывать каждый раз после перезапуска миранды. У меня это происходит в ICQ, но я не знаю, как это в других протоколах, поддерживающих отправку заметок самому себе, поэтому метку "ICQ:" не поставил.

Почините пожалуйста сохранение заданного мной вручную имени для этого контакта, чтобы миранда при перезапуске помнила о том, что я вводил новое имя для отображения в клисте.

PS
Проблема только с "самим собой", другой встроенный протокольный контакт, ICQ Official, переименовывается и сохраняется корректно.

**Comment by dartraiden** [comment]
> Почините пожалуйста сохранение

Тогда у всех остальных пользователей он из "Избранного" переименуется в ник.

**Comment by dartraiden** [comment]
В качестве обходного пути можно сделать метаконтакт с единственным субконтактом - Избранным.

**Comment by SM-Sergey** [comment]
> Соответственно, мы перезаписываем MyHandle и ваше переименование пропадает, ведь переименование контакта это просто новое значение MyHandle.

Ну сразу видно два способа:
1) Добавить Myhandle2 для таких переименований от имени миранды, с приоритетом MyHandle над MyHandle2
2) Добавить "MyHandleSource" = 1 , если его создала миранда, и =2, если его создал пользователь. Соответственно, если его создал пользователь, то трогать его может только пользователь. Если его нет, или создала миранда - трогать может и миранда и пользователь.
