### ISSUE TITLE
Расширить работу настроек видимости контактов и групп - ввести видимость групп как отдельную сущность.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4108]
В настройках можно скрыть любой контакт или любую группу из клиста, сняв с них галки видимости:

- Если установить галку видимости группы, то установятся и все галки всех контактов группы. Это хорошо и правильно.
- Если снять галку видимости группы, то снимятся и все галки всех контактов группы. Это тоже хорошо и правильно.
- Если начать снимать галки у контактов внутри группы при установленной галке у группы - то галка группы сама снимается при снятии первой же галки контакта, это неправильно - хочется иметь возможность настройки видимости самой группы отдельно от контактов в ней (зачем - см. ниже). То есть, допустим, сначала снять видимость всей группы, и потом установить внутри нее видимость контактов (вплоть до всех), но не установить видимость группы. Дополнительно - хорошо бы, если при клике с Ctrl на галке группы переключалась только она, а галки контактов не трогались.

Соответственно, если у самой группы (или подгруппы) галка видимости не стоит, она, в смысле строки-разделителя с ее названием, должна быть безусловно всегда скрыта из клиста, несмотря на настройки видимости пустых групп, и несмотря на наличие или отсутствие в ней видимых контактов, а ее содержимое всегда развернуто, если это корневая группа, или наследует развернутость от более верхней группы/подгруппы, если это подгруппа. То есть, скрытая группа перестает быть с точки зрения видимости в клисте группой, и ведет себя так, как будто ее содержимое находится в группе более верхнего уровня. Все это с той целью, чтобы из клиста для удобства можно было убрать лишние разделения (которых "хренова гора"), которые используются только для быстрых настроек игноров по группам, но которые хочется видеть в клисте как единую неразделенную группу. И при этом иметь разделение на другие более глобальные группы по другим признакам.

**Comment by georgehazan** [comment]
1. Не будет никаких настроек групп как таковых, это просто список строк
2. >которые хочется видеть в клисте как единую неразделенную группу
так и спихнуть всё в одну группу
3. >И при этом иметь разделение на другие более глобальные группы по другим признакам.
Когда-нибудь в Миранде появится возможность вставлять контакт в более чем одну группу. Но не прямо сейчас

**Comment by SM-Sergey** [comment]
> так и спихнуть всё в одну группу

так нельзя же, так как они разделены по подгруппам для того, чтобы их игнорить группами, когда "не до них", и так же быстро выводить из игнора. Но я не хочу видеть это деление в клисте - оно там конкретно мешает и раздражает, а видеть только в настройках игнора. Лечится это полным отключением групп в клисте, что и имеет место на данный момент времени. Но это не совсем красиво, потому что другие группы более высоких уровней хотелось бы как раз видеть в клисте. Пока "не видеть" перевешивает над "видеть", поэтому полное отключение групп пока более-менее выход. Но тут ключевое слово "пока".
