### ISSUE TITLE
Прекратить хранение списка групп в базе

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4109]
Это осталось от старой аськи и это дикий анахронизм. Список должен получаться простым сканом контактов.

**Comment by SM-Sergey** [comment]
Простите, а как тогда будут существовать группы временно без контактов в них?

**Comment by georgehazan** [comment]
> Простите, а как тогда будут существовать группы временно без контактов в них?

Никак? А зачем они?

**Comment by SM-Sergey** [comment]
> Вводишь имя новой группы, она прописывается контакту и тут же создаётся. 

Для новой группы - это хорошо и удобно и нужно (только как удобно чтобы создать подгруппу, не ошибившись, вбивая "полный путь"?). А вот для старой группы, которая то пополняется контактами, то опустошается - неудобно. Если я знаю, что эта группа мне будет нужна еще как минимум, допустим, полгода, и в ней то будут контакты, то не будут, то зачем каждый раз после того, как она опустеет, писать заново много букв для ее создания?

Зачем опять убивать удобную и нужную функциональность, которой активно пользуются?

**Comment by georgehazan** [comment]
> Если я знаю, что эта группа мне будет нужна еще как минимум, допустим, полгода

Можно антресоль сделать и туда её закинуть.

**Comment by SM-Sergey** [comment]
В каком смысле? 

Вообще, это нормальное состояние группы, когда в ней неделю 10 контактов, потом месяц пусто, потом неделю 5 контактов, потом опять пусто, ну и так далее раз десять туда-сюда в процессе работы по проекту.

**Comment by georgehazan** [comment]
> Вообще, это нормальное состояние группы, когда в ней неделю 10 контактов, потом месяц пусто, потом неделю 5 контактов, потом опять пусто, ну и так далее раз десять туда-сюда в процессе работы по проекту.

Может workflow как-то по-другому поддерживать? Есть множество отличных решений

**Comment by SM-Sergey** [comment]
А зачем что-то менять, если в миранде это работает "сто лет уже как". Раньше, когда был инвиз - пользовались им, исключая из инвиза нужные группы. Потом стали пользоваться кривоватым игнором, но тоже работает. А если еще и "Mute" когда нибудь появится - то это опять станет совсем-совсем удобно, даже круче инвиза старой аськи. ЗамУтил лишних, потом размУтил и всё увидел.

**Comment by georgehazan** [comment]
> А зачем что-то менять, если в миранде это работает "сто лет уже как"

Потому что:
- нумерованный список групп - это унылое наследие ICQ, где надо было сличать список групп на сервере и на клиенте. Сейчас оно переехало туда, куда и должно было прилететь в самом начале - внутрь Settings/ICQ_1;
-  из-за этого происходит куча проблем, например, можно контакту присвоить произвольную группу, но тогда он просто вылетает из списка контактов, и его больше никто не увидит. 
- если собьется нумерация групп, то оставшиеся группы никто не увидит.
- флажки групп из-за этой ботвы хранятся в первом символе имени группы, что вызывает ужасные мучения.

В общем, надо просто сделать так, чтобы это не хранилось в базе, а текущее состояние групп сливалось бы в какой-нибудь оыщтб откуда бы и грузилось благополучно при старте. Мысль о том, что пустые группы не должны пропадать из этого кэша, я услышал, вопросов нет

**Comment by SM-Sergey** [comment]
А как будет обрабатываться ситуация, для примера, когда на одной миранде попереименовывали группы, и это запомнилось на сервере, потом на другом компе открыли другую миранду? Как она отработает переименованные группы с сервера, если они не будут привязаны к group id? Когда у группы есть ID, все прозрачно - можно переименовывать группу как угодно, а ее ID не меняется, потом другая миранда стащит с сервера новые имена для старых ID-ов, и переименует согласно этому всё что требуется в БД, А если не хранить ID? Как это тогда отследить?

Вообще, с учетом полезных планов на возможность включения контакта в несколько групп, надо как-то отличать те группы, которые серверные, и которые синхронизируются между разных миранд на разных компах, и некие "только локальные", присущие только одной локальной миранде. Соответственно, к примеру, контакт может находиться (и находится) в серверной группе - для этого у контакта хранится ID серверной группы. И может плюс к этому находиться в локальных - для этого у контакта записано просто название его групп как-то типа REG_MULTI_SZ или иначе, но в этом списке нет серверной группы.

Получается, что при образовании (создании) новой группы надо обязательно спрашивать, хранить ли эту группу на сервере со всеми вытекающими удобствами (синхронизация) и неудобствами (только в одной такой группе контакт), или это чисто локальная группа.

> не хранилось в базе, а текущее состояние групп сливалось бы в какой-нибудь JSON

Как по мне, так вообще всё равно, в БД это, или рядом с ней в JSON. Или вообще JSON в БД. Нравится JSON, пусть он и будет. Это вообще не вопрос ни разу, главное как-то хранить,

**Comment by georgehazan** [comment]
> Как она отработает переименованные группы с сервера, если они не будут привязаны к group id?

Они приаязаны к group id в настройках конкретного аккаунта ICQ.

**Comment by SM-Sergey** [comment]
... Может, вообще прибить ко всем чертям хранение групп на сервере, но при этом сделать возможность синхронизировать группы через какой нибудь контакт типа Favorites - отправил их сам себе, а потом на другом компе втянул.

**Comment by georgehazan** [comment]
> так зачем в нем иметь имя этой группы

затем, чтобы движок контакт листа мог корректно засунуть этот контакт в группу
