### ISSUE TITLE
NewStory: падает экспорт в json

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4110]
повторяется стабильно. И не важно, есть в сообщении оффлайн файл, или нету.

крешдамп
[crash20240108162002.txt](https://github.com/miranda-ng/miranda-ng/files/13864638/crash20240108162002.txt)

но толку от него немного, так как и он тоже сломался - не дает нормальных символов при наличии всех pdb

**Comment by dartraiden** [comment]
Экспорт теперь невозможен без плагина Import. Код экспорта уехал в импорт, чтобы не плодить разные версии сохранения в JSON.

**Comment by SM-Sergey** [comment]
> но что-то идёт не так

Возможно тогда потому, что этот плагин у меня есть, но отключен галкой в опциях, чтобы в меню глаза не мозолил. Вообще это некрасиво, делать так, чтобы экспорт из ньюстори требовал плагина импорта, засоряющего меню своими добавками. Уж забросили бы этот код в какую нибудь общую либу...

**Comment by dartraiden** [comment]
Пункт меню убирается через редактор меню.

**Comment by dartraiden** [comment]
```
>	NewStory.dll!CHistoryDlg::onClick_Export(CCtrlButton * __formal=0x000000000367a2c0)Строка 875	C++
 	[Внешний код]	
 	NewStory.dll!CHistoryDlg::DlgProc(unsigned int msg=273, unsigned __int64 wParam=1005, __int64 lParam=1114926)Строка 1110	C++
 	[Внешний код]	
 	Miranda64.exe!wWinMain(HINSTANCE__ * __formal=0x0000000000000001, HINSTANCE__ * __formal=0x000000000014fe70, wchar_t * cmdLine=0x00000000005425dc, int __formal=96)Строка 62	C++
 	[Внешний код]	
```

**Comment by dartraiden** [comment]
Если стартануть со вгруженным импортом, выгрузить его и открыть историю, то падает сразу при открытии окна, не дожидаясь экспорта

**Comment by SM-Sergey** [comment]
А как починили  символы в крешдампе?

**Comment by dartraiden** [comment]
При падеии в экспорте - взял стек из студии, она грузит символы.
При падении в истории дампер нормально их вгрузил.
