### ISSUE TITLE
NewStory: При наличии установленного, но отключенного плагина Import она предлагает его установить

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4112]
Ну а по логике должна бы спросить, "а не хотите ли Вы его включить", и если да, то просто тихо включить.

PS
Ну и по идее это должна быть единая система на все случаи жизни, если плагина нет - спросить установку, если есть, но выключен - спросить/включить.

**Comment by georgehazan** [comment]
Оно умеет только детектить присутствие в памяти соотв. сервиса. Выключен ли плагин или просто отсутствует - оно не знает

**Comment by dartraiden** [comment]
Надо просто выдавать сообщение "требуется загруженный плагин Import"

**Comment by SM-Sergey** [comment]
А я предлагаю, чтобы был некий "ядерный" сервис, который всё знает - есть плагин, нет плагина, или он не загружен, и соответственно ситуации делает то или это. И чтобы им могли пользоваться все, кто пользуется сервисами плагинов.

**Comment by SM-Sergey** [comment]
Никак. Предложить вгрузить плагин, если "да" - попытаться. Не вгрузился - не судьба - ошибка, что плагин несовместим

**Comment by SM-Sergey** [comment]
И кроме диска надо наверное еще лазить в  Settings/PluginDisable, если плагин есть на диске, и если он там задисаблен, то только тогда предлагать вгрузить (убрать disable). А иначе - всегда идти на предложение установки, так как это значит, что или плагина нет, или он кривой.

**Comment by georgehazan** [comment]
Плагин - это точно не ядро, и никуда в PluginDisable он точно не полезет, этого не хватало. Потом в ядре что-то мутирует, и оно сразу сходит под себя, не, это не вариант. Надо просто изменить сообщение, требуется, мол, и всё тут
