### ISSUE TITLE
Jabber: в имени принятого файла иероглифы меняются на подчеркивание

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4114]
Кидаю через HTTP File Upload вот такой файл

[密码.txt](https://github.com/miranda-ng/miranda-ng/files/13874789/default.txt)

На отправляющей стороне его имя (иероглифы) корректно показывается в журнале.

На принимающей стороне имя файла превращается в _____.txt и с таким именем он кладётся на диск.

На дворе 2024 год, юникод шагает по планете, а мы не можем принять иероглифы.

**Comment by georgehazan** [comment]
Сервак на j.ru обосрался с поддержкой HTTP Upload, пока их саппорт ничего вразумительного сказать не смог. На хот чили, например, всё работает, как из пушки

**Comment by georgehazan** [comment]
Поправил то, что нет url_decode при приёме файла, остальное - дело сервера
