### ISSUE TITLE
В Options->Message sessions->Typing notify сделать местную галку "показать группы"

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4117]
Или просто показывать там группы всегда. 
Чтобы отделить мух от котлет - чтобы можно было управлять тут контактами по группам, а не только по одному, при отключенных группах в клисте.

**Comment by SM-Sergey** [comment]
Кстати, а по функциональности это не копия ли "Typing" в Ignore? В чем разница настроек тут и там?

**Comment by georgehazan** [comment]
> Кстати, а по функциональности это не лишняя ли копия "Typing" в Ignore? В чем разница настроек тут и там?

В игноре стоят входящие события, в настройках Message sessions - исходящие
