### ISSUE TITLE
NewStory: не вызывается поиск по Ctrl+F

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4119]
По-моему, мы это реализовывали...
Но сейчас поиск вызывается лишь кнопкой на тулбаре в окне истории.

**Comment by georgehazan** [comment]
Переправил умолчание на Ctrl+F (было Ctrl+S почему-то)
Но работать оно будет только в том случае, если фокус стоит на контроле истории

**Comment by dartraiden** [comment]
Ну и славно. S было, видимо, потому что Search. Но в винде и виндовом софте традиционно используется Ctrl+F.
