### ISSUE TITLE
Discord: второй фактор запрашивается при каждом выходе в онлайн

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4120]

**Comment by georgehazan** [comment]
Так миранда рвет токен при выходе, иначе глупый сервер думает, что миранда постоянно в сети и не рассылает пуши на мобильные устройства. А если сессия порвалась, то надо налаживать снова.

Можно сделать опцию "не рвать сессию при выходе", тогда не будет спрашивать каждый раз авторизацию
