### ISSUE TITLE
Discord: добавить поддержку входа с резервным кодом

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4122]
В число вторых факторов надо добавить ещё и резервный код.

При включении двухфакторной авторизации оф. клиент выдаёт пользователю 10 одноразовых кодов. Если пользователь не имеет доступа ко второму фактору, он может выбрать вариант "ввести резервный код" вместо СМС/приложения/аппаратного ключа.

По сути, это тоже разновидность второго фактора.

**Comment by georgehazan** [comment]
а на какой урлик его отсылать?

**Comment by dartraiden** [comment]
1) нужно выкусывать дефис из резервного кода (при включении MFA юзеру выдают текстовый файл с десятком кодов вида abcd-wxyz)

2) если введен неверный код, стоит как-то оповестить юзера
