### ISSUE TITLE
Пункт меню "показать отключенных в группе" ведёт себя странно

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4128]
Если галка "скрыть отключенных в группе" не взведена, то мы имеем пункты "скрыть отключенных в группе" и "показать..."

<img width="189" alt="sDCBEXD4ia" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/5851bb24-737f-439d-880f-9ee98e5c9733">

Пунт "показать..." в этом случае не имеет смысла, ведь они не скрыты.

Но дальше веселее. Если взведена галка "Скрыть...", то пункта "Показать..." не видно.

<img width="187" alt="CsW6e57Ubc" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/6603c19f-0055-48a1-889e-794473c39fbc">

Давайте определимся:
- либо "скрыть отключенных в группе" работает как сейчас, как галочка, и тогда "показать..." вообще не нужно. Если галка взведена, они скрыты. Если не взведена - они показаны.
- либо "скрыть отключенных в группе" будет работать не как галочка, а как действие. Тогда мы делаем один пункт меню, который будет динамически менять своё название между "скрыть" и "показать". Например, так работает пункт включения и выключения метаконтактов, который меняет свой текст в зависимости от включенности метаконтактов.

Второй вариант мне нравится больше.

**Comment by dartraiden** [comment]
Теперь стало вообще шизофренично.

- если нажать на "скрыть отключенных в группе", то ничего не происходит: отключённые не скрываются, галочка не появляется

- если нажать на "показать отключенных в группе", то:

1) отключенные СКРЫВАЮТСЯ и у "скрыть отключенных в группе" появляется галочка (т.е. мы дёрнули принудительный показ, а сработало принудительное скрытие, лол)

2) пункт "показать отключенных в группе" ПРОПАДАЕТ

3) отменить принудительное скрытие невозможно, т.к. пункт про скрытие не пашет, как уже писалось выше

**Comment by dartraiden** [comment]
Берем Миранду, которая не обновлялась несколько дней, обновляем. Получаем такую картину:

![Безымянный](https://github.com/miranda-ng/miranda-ng/assets/5046855/71117938-c93a-43f1-a2e5-05fac1e79c65)

Как видим, включены пункты "показать отключенных в группе" и "скрыть отключенных в группе", и эти пункты соответственно есть в меню группы.

Но при попытке использовать эти пункты начинается глюкодром:
1) пункт "скрыть отключенных в группе" не включается вообще. Сколько его ни тыкай, у него галочка не появится и отключенные не скрываются. Это баг №1
2) Если пару раз безрезультатно ткнуть "скрыть отключенных в группе", а затем ткнуть "показать отключенных в группе", то пункт "показать отключенных в группе" пропадает нафиг (баг №2), и вот тут пункт "скрыть отключенных в группе" приходит в чувство и включается. Но отключить его уже нельзя, т.к. он не реагирует на клик (как описано в №1)

**Comment by georgehazan** [comment]
3. & означает, что в строке меню эта буква будет подчеркнута и работает как хоткей. Т.к. оно работает только в menu bar, а в popup menu не работает, то можно тупо выкашивать эти & к хреням, никакого ущерба от этого не будет.

**Comment by dartraiden** [comment]
Остался ещё один баг с этими пунктами.

Если включить "Скрыть отключённых в группе", то пункт "показать отключенных в группе пропадает". Это логично.

Но если включить "Показать отключённых в группе", то пункт "Скрыть..." не пропадает. И его можно включить. Что приводит нас к взаимоисключающим параграфам: включён принудительный показ и одновременно включено принудительное скрытые.
