### ISSUE TITLE
Переделать настройку "использовать сторонний просмотрщик журнала в групповых чатах"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4130]
У меня выбран NewStory в качестве просмотрщика в приватах, и включена опция "использовать сторонний просмотрщик в групповых чатах".

Иногда мне нужно протестировать что-то на встроенном журнале tabSRMM. Для этого я выбираю встроенный журнал и он начинает работать и в приватах, и в чатах. И тут возникают две проблемы:

1) Так как галка "использовать сторонний просмотрщик журнала в групповых чатах" все ещё взведена, то вот эти настройки встроенного журнала для чатов скрыты:
![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/11751f6a-f17f-4671-b375-a503ec499d4f)

Хотя, по факту работает-то встроенный журнал. Т.е. мне приходится делать два действия (выбирать встроенный журнал и снимать галку) вместо одного.

2) Название опции вводит в заблуждение

<img width="503" alt="Miranda64_O3nkbBJSli" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/29e14fd3-fffe-4fe8-91e4-5e254121a1fe">

Неискушённый пользователь решит, что просмотрщик для приватов встроенный, а для чатов - сторонний, ведь описание опции гласит "использовать сторонний просмотрщик для чатов" без уточнения, что эта опция работает только если для приватов выбран сторонний просмотрщик.

Предлагаю:
- Переименовать опцию в "использовать **выбранный** просмотрщик в групповых чатах". Это решает проблему №2, устраняя всякую двусмысленность.
- Сделать так, чтобы настройки групчатов (страница настроек на скриншоте) скрывались не при включении опции, а при сочетании условий "включение опции + выбран сторонний журнал". Это решает проблему №1.

**Comment by georgehazan** [comment]
Нормально там всё с именами настроек, надо просто при разрешении форм учитывать эффективные права, а не просто значение этой кнопки
