### ISSUE TITLE
NewStory: если водить мышкой поверх сообщения, которое редактируется, появляются глитчи

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4131]
![Miranda64_BdOLHkw7ZY](https://github.com/miranda-ng/miranda-ng/assets/5046855/8593a130-125e-472b-a604-39fd37423128)

**Comment by georgehazan** [comment]
Не будет прорисовываться текст, фон будет дрыгаться, тем не менее
