### ISSUE TITLE
Discord: если процесс подключения прерван, протокол больше не сможет подключиться в текущей сессии

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4134]
- прописываем для дискорда какой-то несуществующий прокси, чтобы он не смог подключиться
- пытаемся вывести дискорд в онлайн
- пока он крутит спиннер подключения, прерываем этот процесс, уведя его в оффлайн
- убираем прокси и пробуем подключиться

результат: дальнейшие попытки подключения в текущей сессии вообще не происходят, спиннера уже мы не увидим, в нетлоге попытки подключения отсутствуют

**Comment by georgehazan** [comment]
Давай конкретнее, что куда прописывать, потому что у меня миранда при плохо прописанной прокси просто ломится напрямую

**Comment by dartraiden** [comment]
Сеть → Из выпадающего меню выбрать дискорд → прописать прокси.
