### ISSUE TITLE
AvatarHistory: при изменении пути к профилю, плагин воссоздаёт старый путь

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4139]
Устанавливаем AvatarHistory, выбираем последний вариант

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/7cb2b910-caf8-4c5b-9732-bfb743626891)

Выключаем Миранду и переносим профиль в другое место. Например, если Миранда установлена в портативном варианте, переносим её каталог в другое место, соответственно профиль тоже переезжает.

Запускаем Миранду. AvatarHistory на секунду создаёт каталог профиля по старому пути и тут же его стирает. Это баг, смысла создавать каталог и тут же его стирать нет.

**Comment by georgehazan** [comment]
а он вообще ни сном, ни духом про какие-то там фолдеры, скорее всего, это плагин Folders читает из базы старое значение, создает каталог, а потом только понимает, что значение уже новое - и сразу его стирает

**Comment by dartraiden** [comment]
Нет никакого Folders у меня.

**Comment by georgehazan** [comment]
Есть две проблемы с этим тикетом
1. В плагине нет ни одной строки удаления каталогов
2. В плагине есть три места, где создаются каталоги, но ни одно из них не вызывается при старте.

Вопрос с тем, что чинить, остается открытым

**Comment by dartraiden** [comment]
Не удаётся повторить :(
