### ISSUE TITLE
NewStory: удаление отдельных сообщений

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4140]
1) При нажатии ПКМ на сообщение, в контекстном меню отсутствует пункт "Удалить" (удалить сообщение можно лишь кнопкой `Delete`). Надо бы его добавить.

2) При удалении сообщения оно удаляется не только локально, но и на сервере, причём, у собеседника тоже (если протокол это умеет). Мы при очистке всей истории сделали возможность указать, нужно ли удалять с сервера и у собеседника. Надо такой же выбор реализовать и для удаления отдельного сообщения.

**Comment by georgehazan** [comment]
1. Пункт отсутствует для чужих сообщений, ибо нефиг

**Comment by SM-Sergey** [comment]
> Пункт отсутствует для чужих сообщений, ибо нефиг

Это почему? Моя локальная БД - что хочу, то и делаю. Может, мне эти сообщения мешают и я не хочу их видеть? А может я тру эти сообщения, чтобы переподтянуть потом c сервера по лоад хистори?

**Comment by georgehazan** [comment]
> по временно неработоспособной лоад хистори?

может уже хватит? с сервера всё стягивается как есть, локальные файлы при этом не затираются и используются

**Comment by georgehazan** [comment]
> Это почему? Моя локальная БД - что хочу, то и делаю.

Потому что локальная база выстраивается по серверу. Что хочешь можно делать только в сервисном режиме, когда сетевая подсистема вся отключена

**Comment by SM-Sergey** [comment]
> может уже хватит? с сервера всё стягивается как есть

не хватит. 
1) Оффлайн файлы на данный момент просто портятся, преобразуясь в короткие ссылки типа "files.icq.net". Скриншоты до и после я показывал.
2) На сервере в реальности встречаются косяки, когда автор ничего не удалял, а с сервера прилетают удаления сообщений.

Этого более достаточно, чтобы признать лоад хистори совершенно не юзабельной на сегодня.

**Comment by georgehazan** [comment]
> 1. Оффлайн файлы на данный момент просто портятся,

Вчера зацепил, да, поправил. Но нытье об этом идет уже неделю

> На сервере в реальности встречаются косяки, когда автор ничего не удалял, а с сервера прилетают удаления сообщений.

Значит, с той стороны их стерли.

**Comment by SM-Sergey** [comment]
> Вчера зацепил, да, поправил. Но нытье об этом идет уже неделю

Ну так может быть потом еще раз "зацепится" случайно, и приведет к порче БД в сообщениях далекого прошлого? Это вопрос чисто безопасности и надежности, а не "нытьё". Отсюда огромная просьба вести лог того, что лоад сервер хистори натворил, чтобы можно было после этой операции увидеть весь ее результат, и на этом основании предпринять какие-то действия.

> Значит, с той стороны их стерли.

Неа, "та сторона" это мой друг, я его вживую спрашивал - он ничего не стирал. Более того, он связался с техподдержкой - они сказали "а фиг его знает, мы тоже не стирали, но ничего сделать не можем, извините-простите". Как результат - я не могу подтянуть недостающие сообщения, которые почему-то есть, не испортив старые. В итоге приходится, когда это надо, недостающие сообщения смотреть в оф. клиенте, так как нет возможности подтянуть с сервера только отсутствующее в БД, не трогая старое.

Правда кажется придумался обход этого косяка - иметь старую миранду, которая еще не поддерживала редактирование и удаление, и ей сделать лоад хистори. Правда это выглядит костылём (но стоит попробовать).

**Comment by georgehazan** [comment]
> Ну так может быть потом еще раз "зацепится" случайно, и приведет к порче БД в сообщениях далекого прошлого?

Может быть, тогда историю надо будет загрузить заново с сервера.

> Это вопрос чисто безопасности и надежности

Ну да, хранение эталонной копии на сервере - это и есть вопрос надежности. Локальная база - это всего лишь оттиск серверной истории в том виде, как это сейчас понимает нынешняя версия плагина. Может быть концепция еще поменяется, кто знает

**Comment by SM-Sergey** [comment]
> Может быть, тогда историю надо будет загрузить заново с сервера.

Это, если я сразу замечу, и открою тикет с багом. А если я не замечу? А замечу через 10 лет? А через десять лет эта история еще останется на сервере? Для того и нужен лог работы загрузки истории, чтобы сразу заметить вдруг образовавшийся косяк, и написать сюда просьбу его срочно исправить, а на это время восстановиться из бекапа.

> Ну да, хранение эталонной копии на сервере - это и есть вопрос надежности. 

Ну как бы не совсем. У меня доверия к серверу около нуля, а доверие к локальной БД, сидящей на рейд-массиве, около 100%. Вообще, у меня возникла идея сделать драйвер БД "High reliability", который бы писал параллельно основной БД еще БД с логом всех транзакций, с возможностью просмотреть их всех и если надо откатить любую из них. Но я еще не созрел до конца.

**Comment by georgehazan** [comment]
> Это, если я сразу замечу, и открою тикет с багом. А если я не замечу? А замечу через 10 лет?

Тогда, конечно, печалька. Придется переходить на телегу

> Для того и нужен лог работы загрузки истории

Специального лога загрузки истории точно не будет

> доверие к локальной БД, сидящей на рейд-массиве, около 100%

И сидеть при этом на ночнике, угу. Поразительное доверие к моим способностям, спасибо

**Comment by SM-Sergey** [comment]
> Поразительное доверие к моим способностям, спасибо

А я сам разработчик ПО (драйверов, встроенного ПО и самого железа), поэтому не боюсь. И у меня бекапы БД четыре раза в день делаются. Но та старая "стабильная" версия вообще "никакая" по многим фичам в ICQ и NS, поэтому просто нет вариантов, на чем сидеть. И, плюс к этому, надеюсь, что моё тестирование и запросы тоже хоть в чем-то помогают.

> Специального лога загрузки истории точно не будет

Ну в общем задумка сработала. "стабильная версия" без поддержки стирания и редактирования делает лоад хистори корректно и аккуратно, подтягивая только новое и отсутствующее в БД. Так что обход проблемы найден - пользоваться для этого именно той версией, в которой она работает хорошо. А отдельные нераспознанные или отредактированные сообщения, надеюсь, можно будет обновить с сервера по #4146.

> Придется переходить на телегу

А что, есть гарантия, что она будет существовать через 10 лет, и что в ней никогда не будет никаких проблем с лоад хистори?

**Comment by georgehazan** [comment]
> А что, есть гарантия, что она будет существовать через 10 лет, и что в ней никогда не будет никаких проблем с лоад хистори?

Там можно денежку платить, это резко повышает возможности проекта

**Comment by SM-Sergey** [comment]
> Там можно денежку платить, это резко повышает возможности проекта

А на это мне @dartraiden прямо написал, что это не предусмотрено.

**Comment by SM-Sergey** [comment]
Но в целом теперь я соглашусь, что п.1 не критичен, если будет работать #4146
Как и пропадет необходимость в п.2 в полном объеме (удалять с сервера можно всегда, но удалять у собеседника или нет - это да).

**Comment by dartraiden** [comment]
Никто не запрещает за деньги нанять конкретного разработчика для реализации конкретной хотелки.

**Comment by SM-Sergey** [comment]
> Если речь про поддержку чего-либо в Миранде через 10 лет, то никто не запрещает за деньги нанять конкретного разработчика для реализации конкретной хотелки.

Речь не про поддержку чего-либо в Миранде через 10 лет, а про то, что хочется видеть сейчас, чтобы через 10 лет, когда что-то на каком-то сервере сгинет, или сгинет сам сервер, не остаться у разбитого корыта с незамеченными сейчас порченными старыми сообщениями в базе, которые уже не восстановить. А сделать это я и сам могу, но какой смысл, если это идет вразрез с вашим пониманием того, что должно быть, а плагины в современном их понимании не могут существовать отдельно от самой Миранды и должны постоянно пересобираться.

>  оформив премиум. Это повышает её шансы на существование.

Ничего это не повышает. Это даже не капля в море, а молекула. Любой мессенджер может накрыться медным тазом по сотне причин, из которых 99 не лечится подписками и копейками. А если будет IPO у них, как обещали, так их вообще одним щелчком прикроют если надо будет - перспектива совсем не радужная.
А уж сбой на сервере со случайным удалением части сообщений (которые надо сохранить в локальной БД) вообще дело житейское и равновероятное для любого сервера любого протокола.

**Comment by dartraiden** [comment]
> При нажатии ПКМ на сообщение, в контекстном меню отсутствует пункт "Удалить" (удалить сообщение можно лишь кнопкой Delete). Надо бы его добавить.

Так и отсутствует. Даже для своих сообщений.

**Comment by dartraiden** [comment]
При этом, кнопка `Del` всегда работает.

Предлагаю не заморачиваться про свои и чужие. Раз уж `Del` позволяет удалить любое сообщение, то и пункт меню показывать всегда.
