### ISSUE TITLE
ICQ: при удалении своего сообщения нужно сразу же запрашивать новые события у сервера

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4141]
В официальном клиенте когда я удаляю своё сообщение, то вместо него остаётся "сообщение удалено".

В Миранде после удаления своего сообщения ничего сразу не появляется. Но если дёрнуть историю с сервера, то прилетит вот это "сообщение удалено".

Надо сделать так, чтобы оно сразу и прилетало.

**Comment by georgehazan** [comment]
> В официальном клиенте когда я удаляю своё сообщение, то вместо него остаётся "сообщение удалено".

Иногда остается, иногда нет, закономерность пока непонятна

> Надо сделать так, чтобы оно сразу и прилетало.

На каждое удаление дергать запрос истории?.. Может лучше не надо?

**Comment by SM-Sergey** [comment]
> На каждое удаление дергать запрос истории?.. Может лучше не надо?

Может, просто заменить на "Message deleted" локально без дергания сервера? Заодно можно сделать и переводимым на языки.

**Comment by georgehazan** [comment]
Я вот сейчас стер около 20 сообщений, только три из них стали message was deleted. Остальные просто исчезли

**Comment by SM-Sergey** [comment]
У меня было подозрение, что сообщения, идущие подряд, если их все стереть, то они превращаются в одно "Message deleted". Но не уверен.
Это смотря как рассматривать - если это баг в сервере, то надо ли его тянуть и в миранду? А если это какая-то задумка, то надо в ней разобраться...

**Comment by dartraiden** [comment]
Да, как-то странно оф. клиент себя ведёт: сейчас поудалял кучу сообщений из него, и свежих, и старых, и только у себя, и у собеседника. Все стёрлись без следа, не оставив "сообщение удалено".
