### ISSUE TITLE
ICQ: удаление истории у собеседника при удалении контакта

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4143]
Наша реализация протокола умеет удалять свои сообщения не только у себя, но и у собеседника.

Но при удалении контакта галка про удаление у собеседника засерена. Нужно выставить флаг о том, что протокол умеет стирать и у собеседника.

**Comment by georgehazan** [comment]
Аська не понимает таких тонкостей, она всегда сносит историю для обоих

**Comment by dartraiden** [comment]
Тогда галка про снос у собеседника должна быть ВЗВЕДЕНА и засерена.

**Comment by georgehazan** [comment]
g
