### ISSUE TITLE
Невозможно удалить серверную историю при удалении метаконтакта

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4145]
Даже если все субконтакты умеют удалять серверную историю (например, мета состоит из 2 сабов телеграма), галка про удаление серверной истории засерена.

Нужно переделать логику. Если хотя бы один саб умеет удалять серверную историю и историю у собеседника, то у меты эти опции должны быть доступны.

**Comment by georgehazan** [comment]
На самом деле всё в порядке: при удалении меты она просто разваливается сама, высвобождая все сабы (они перестают быть невидимыми), тем самым открывая их для дальнейшего удаления. Но сама метаистория - это чисто виртуальное понятие, которое живет исключительно внутри профиля, где она и дохнет при стирании метаконтакта
