### ISSUE TITLE
Сделать возможность безопасного обновления одного сообщения с сервера.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4146]
Сейчас при удалении сообщения в NS оно безусловно сносится из сервера. Но, по факту, удаление сообщения из истории примерно в 95% случаев использовалось ранее для того, чтобы его заново втянуть по Load Server History, а вовсе не для того, чтобы грохнуть на сервере. Когда будет реализована функция "удалить локально", т.е. грохнуть в БД, но не трогать сервер (как это предлагается в #4140), то это будет на сегодня крайне стрёмным способом обновления сообщения по причине неработоспособности и небезопасности Load Server History (см. обсуждение #4107 - мало того, что она теперь самопроизвольно затрагивает все оффлайн файлы в истории, что есть уже априорное вселенское зло, а еще и местами портит их). Таким образом функция Load Server History из-за введенной принципиальной небезопасности перешла из ряда обычной рутинной операции в самые крайние случаи.

Поэтому прошу сделать:
1) Отдельную функцию "Reload from server"  (наверное в NS по меню ПКМ) - которая просто обновит конкретное выбранное сообщение с сервера, если у него есть server_id.
2) см. п.1 в #4147

**Comment by georgehazan** [comment]
Всё, можно безопасно скачивать всю историю, полностью пофикшено

**Comment by SM-Sergey** [comment]
Ну и как это работает?
- надо выборочно обновить пару десятков сообщений (не оффлайн файлов), разными местами попорченных ранее бывшими глюками, некоторые из которых "заюникодились", некоторые в виде RTF, ну и т.п..
- надо обновить выборочно несколько оффлайн файлов у контактов, у которых в результате сбоя сервера оказались стерты другие старые сообщения с файлами и, соответственно, стираются при обновлении "всего" и в локале.
