### ISSUE TITLE
Load Server History: сделать использование безопасным.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4147]
1) Устранить неотключаемое затрагивание по Load Server History чего либо из того, что уже есть в БД, за исключением случаев, когда по Load History прилетело новое редактирование или удаление сообщения, чтобы данная операция не могла ничего испортить в принципе, что было 10000 или 100000 сообщений назад, и что неочевидно (появилось в работе над #4107) Как вариант, если такая функциональность кому-то необходима, то сделать опцию, разрешающую это затрагивать, по умолчанию выключенную, и с предупреждением при ее включении о потенциальной небезопасности использования - например с предложением сделать бекап базы перед каждым использованием этой функции, если опция затрагивания старых сообщений в БД включена, либо как-то иначе.

2) В случае, если Load Server History изменила что-то старое в БД (не добавила новое, а именно изменила - в т.ч. если прилетали стирания и/или изменения сообщений с сервера), то записывать эти изменения в некий отдельный лог файл в папке миранды с базой, в котором отображать, сообщения какого контакта с какой датой и временем были изменены или удалены (без информации о конкретных изменениях, только о фактах этих изменений). Для каждого Load Server History должен быть отдельный лог, либо новый файл, либо аппендом к старому с каким-то разделителем. И если она изменила что-то старее, чем допустим сутки (хорошо бы опцию, сколько), то чтобы она выводила месседжбокс с предупреждением, на основании которого можно было бы посмотреть лог и решить, что делать дальше (отдельно сохранить бекап, чтобы он никогда не автоудалился, восстановить из него, ну или что то иное предпринять).

**Comment by georgehazan** [comment]
Загрузка истории с сервера как раз и делается затем, чтобы счистить с локала любое дерьмо, которое тут завелось, ибо эталонная копия хранится на сервере. Ручные редактирования событий отправляются на сервер, чтобы эталонная копия была доступна всем клиентам,  поэтому смысла в этом пока не вижу

**Comment by SM-Sergey** [comment]
>Ручные редактирования событий отправляются на сервер

Так а я о чем писал? Ручные редактирвоания и должны делаться, как и удаления сообщений. Но апдейты всех оффлайн файлов на пустом месте, если их никто не редактировал - вот это зло, которое надо или убрать напрочь, или сделать опцией.
