### ISSUE TITLE
Чаты недоступны для открытия, когда протокол не в сети

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4150]
Берём чат, история которого хранится в базе. Например, телеграм.

Если протокол в оффлайне, то чат в клисте серенький и открыть его двойным кликом невозможно.  Что выглядит бредово: история чата вот она, в базе лежит, никаких проблем нет позволить открыть этот чат.

Почему-то, если уже открытый чат уходит в оффлайн, то у него лишь пропадает никлист, но окно открытое остаётся, журнал виден. А вот закрытый оффлайновый чат мы не даём открыть. 

Может, это имеет смысл для чатов, у которых история не в базе, но если история лежит в базе, то никакого смысла запрещать открывать оффлайновый чат нет.

**Comment by georgehazan** [comment]
Ответ простой - в базе хранятся только идентификаторы пользователей, а их ники вычисляются в рантайме (поскольку обычно участники чатов в ростере не хранятся). Поэтому можно открыть окно с историей чата, а вот само окно чата без никлиста поднять в оффлайне не получится
