### ISSUE TITLE
ICQ: Проблемы с цитатами не ушли.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4151]
Было до Load Server History:

![2024-01-27 21_38_14-Issues · miranda-ng_miranda-ng — Mozilla Firefox](https://github.com/miranda-ng/miranda-ng/assets/34127439/5942753a-8231-4a18-9336-2bf92a382ee4)

Стало после.

![2024-01-27 21_38_44-Sergey Mrkov - history  85 messages total](https://github.com/miranda-ng/miranda-ng/assets/34127439/90b02feb-9b67-46ea-a0d4-4d40cf657f8c)

- Одна цитата испорчена напрочь (причем из двух одинаковых соседних).
- Другие цитаты так и не определились, что там есть оффлайн файл ( их жсоны были в #4107 )
- Пропала часть галок о том, что файл загружен (хотя имя файла не менялось, и файл на месте)

И все таки уберите уже наконец этот злобный автоматический перекорёж всех оффлайн файлов во всей истории в угоду будущему ручному "Reload from server".

**Comment by georgehazan** [comment]
> * Одна цитата испорчена напрочь (причем из двух одинаковых соседних).

Это приехал новый формат блобов нечаянно в SQLITE, поправил

> * Другие цитаты так и не определились, что там есть оффлайн файл

То, что было в тех JSON, однозначно раскодируется правильно (ответ картинкой или картинкой с подписью на текстовое сообщение).

> Пропала часть галок о том, что файл загружен (хотя имя файла не менялось, и файл на месте)

Те же блобы, вид сбоку.

**Comment by SM-Sergey** [comment]
> Это приехал новый формат блобов нечаянно в SQLITE, поправил

Увы нет, не исправилось. Ровно то же образуется и там же.

> То, что было в тех JSON, однозначно раскодируется правильно 

Тоже нет. Вот еще третий повтор неопределяемого JSON (аналогичного тому, который там был последний).

{"response":{"statusCode":200, "statusText":"OK", "data":{"pollTime":8548, "ts":1706456289, "fetchBaseURL":"https://u.icq.net/bos/nicq-b002i/aim/fetchEvents?aimsid=105.0943934264.3123344509:300659245&rnd=1706456289.385100&seqNum=102491&oorFromAck=102490&oorToAck=102490", "fetchTimeout":60, "timeToNextFetch":1, "events":[{"type":"histDlgState", "eventData":{"sn":"1011246687", "lastMsgId":7329173953308525035, "patchVersion":"7321338455491871490", "unreadCnt":1, "yours":{"lastRead":7325897460197360270}, "theirs":{"lastDelivered":7329173953308525035, "lastRead":7329173953308525035}, "tail":{"messages":[{"msgId":7329173953308525035, "time":1706456289, "locale":"ru_RU", "text":">Sergey Markov (01/16/2024, 19:48):\n>nnnn\n\nhttps://files.icq.net/get/0qOk70005YN1anOmif5tuB65b674e11bg", "parts":[{"mediaType":"quote","msgId":7324739094632726950,"sn":"300659245","text":"nnnn","time":1705423718},{"mediaType":"text","msgId":0,"sn":"1011246687","text":"https://files.icq.net/get/0qOk70005YN1anOmif5tuB65b674e11bg","time":1706456288}], "mediaType":"text"}], "olderMsgId":7325897460197360270}, "persons":[{"sn":"1011246687", "friendly":"Sergey Mrkov"}, {"sn":"300659245", "friendly":"Sergey Markov", "nick":"300659245"}]}, "seqNum":102490}]}}}


> Те же блобы, вид сбоку.

А это да, исправилось.

**Comment by SM-Sergey** [comment]
А вот тут он вообще что-то странное сотворил.

{"response":{"statusCode":200, "statusText":"OK", "data":{"pollTime":4043, "ts":1706456317, "fetchBaseURL":"https://u.icq.net/bos/nicq-b002i/aim/fetchEvents?aimsid=105.0943934264.3123344509:300659245&rnd=1706456317.112953&seqNum=102511&oorFromAck=102510&oorToAck=102510", "fetchTimeout":60, "timeToNextFetch":1, "events":[{"type":"histDlgState", "eventData":{"sn":"1011246687", "lastMsgId":7329174073567609553, "patchVersion":"7321338455491871490", "unreadCnt":1, "yours":{"lastRead":7329173953308525035}, "theirs":{"lastDelivered":7329174073567609553, "lastRead":7329174073567609553}, "tail":{"messages":[{"msgId":7329174073567609553, "time":1706456317, "locale":"ru_RU", "text":">Sergey Markov (01/10/2024, 21:51):\n>https://files.icq.net/get/0ZZKv000lk5RV2cdHGCYQN659ee74a1be\n\nhttps://files.icq.net/get/0qOk7000rgwPIKdlwh3l5665b674fc1bg https://files.icq.net/get/0ZZKv000lk5RV2cdHGCYQN659ee74a1be ", "parts":[{"captionedContent": {"caption": "", "url": "https://files.icq.net/get/0ZZKv000lk5RV2cdHGCYQN659ee74a1be"}, "mediaType": "quote", "msgId": 7322544349164602173, "sn": "300659245", "text": "https://files.icq.net/get/0ZZKv000lk5RV2cdHGCYQN659ee74a1be https://files.icq.net/get/0ZZKv000lk5RV2cdHGCYQN659ee74a1be ", "time": 1704912714}, {"mediaType": "text", "msgId": 0, "sn": "1011246687", "text": "https://files.icq.net/get/0qOk7000rgwPIKdlwh3l5665b674fc1bg", "time": 1706456315}], "mediaType":"text"}], "olderMsgId":7329173953308525035}, "persons":[{"sn":"1011246687", "friendly":"Sergey Mrkov"}, {"sn":"300659245", "friendly":"Sergey Markov", "nick":"300659245"}]}, "seqNum":102510}]}}}

Во первых, он воспринял картинкой не ту картинку - загрузил оффлайн файлом цитируемую картинку, а не ту, которой я ответил. А во вторых - в журнале табсов картинку открыть можно, а в NS - нет, она всегда улетает на files.icq.net, куда не кликай.

Выглядит так:

![2024-01-28 19_00_48-Sergey Mrkov - history  87 messages total](https://github.com/miranda-ng/miranda-ng/assets/34127439/4b776ad5-1258-4b1c-ac80-1b8305aeab12)

**Comment by georgehazan** [comment]
> Это ответ картинкой у андроидного клиента. А ответ картинкой у эппл-клиента да, работает. У них наоборот идет, у одного сначала цитата, потом картинка, а у другого сначала картинка, потом цитата

Миранде пофиг. Сначала выцепляется файл из mediatype=text, потом пробуется quote, потом reply. Порядок, в котором они идут, не играет роли.

**Comment by SM-Sergey** [comment]
> Порядок, в котором они идут, не играет роли.

Ну мне нет смысла вникать в реализацию, это не тот случай, как было с анимацией смайлов или утечкой объектов, где стояла цель разобраться. Но, факт, что что-то не работает, а что-то глючит.

**Comment by SM-Sergey** [comment]
> Сначала выцепляется файл из mediatype=text

А вот тут, кстати, может быть и корень второго глюка - когда ответ картинкой на картинку, и цитируемая картинка идет вначале, то она оказывается первой в "mediatype=text" - а нужный файл идет вторым после.

**Comment by georgehazan** [comment]
Цитируемая картинка всегда сидит в mediaType="quote", она всегда грузится во вторую или третью очередь

**Comment by SM-Sergey** [comment]
> Цитируемая картинка всегда сидит в mediaType="quote"

Да, увидел. Сорри, был неправ.
Но, тем не менее, во втором жсоне загрузилась именно цитируемая картинка как оффлайн файл.
