### ISSUE TITLE
Пропала опция скрытия в диалоге удаления

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4153]
Раньше при удалении контакта была опция "скрыть, а не удалять". Скрытие полезно, например, для каналов Дискорда, тех из них, которые не нужны. Удалять каналы бесполезно, т.к. они в полном составе вгружаются с сервера при выходе в онлайн.

Конечно, можно скрывать контакты с помощью чекбоксов в Настройки → Игнорировать. Но лучше вернуть в диалог удаления.

Итого: в диалог удаления контакта нужно вернуть чекбокс про скрытие. Причем взведение этого чекбокса должно засерять все прочие чекбоксы (про удаление из серверного ростера и удаление истории), т.к. скрытие является противоположностью удаления.

**Comment by georgehazan** [comment]
Не... попробовал, не понравилось, очень перегруженная форма получается. 
Проще menuEx поставить, там есть отдельным пунктом скрытие из меню контакта
