### ISSUE TITLE
windowlist | steam: crash if steam authorization key window not closed, but steam protocol was disabled "windowlist.cpp (68): WindowList_Remove"

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#416]
**Reported by Corak on 27 Aug 2015 16:32 UTC**
 Креш из-за незакрытого окна авторизации по ключу в Steam, если в это же время попытаться отключить протокол в Учетных Записях и нажать "отмена" при вводе ключа.

[MirandaNG_Crash_20150827_steam_disabled_window.ZIP](https://github.com/miranda-ng/miranda-ng/files/647093/MirandaNG_Crash_20150827_steam_disabled_window.ZIP)

**Comment by georgehazan** [comment]
**Modified by Corak on 27 Aug 2015 17:24 UTC**

**Comment by georgehazan** [comment]
**Modified by Corak on 27 Aug 2015 17:28 UTC**

**Comment by georgehazan** [comment]
**Comment by robyer on 10 Nov 2015 08:05 UTC**
Related to #1028

**Comment by georgehazan** [comment]
**Modified by Corak on 24 Jan 2016 14:35 UTC**

**Comment by Robyer** [comment]
We should keep open only #426 and this close as duplicate.
