### ISSUE TITLE
Миранда не может определить, что база уже открыта с другого компьютера

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4161]
Баг сообщили на форуме.

На сервере в локалке лежит база. На клиенте стоит Миранда, в mirandaboot.ini указан путь к серверу где лежит база.

Запускаем Миранду, она открывает базу.

Запускаем на этом же клиенте вторую копию Миранды, удерживая Ctrl, для открытия менеджера профилей. Миранда видит, что база уже используется и рисует возле неё красный крестик.

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/7c9b0e88-f489-400b-9c64-0e282ab24e56)

Теперь такой же сценарий, но Миранды запущены на двух разных клиентах в локалке. Миранда с клиента1 открывает базу. А Миранда с клиента2 не видит, что база уже используется.

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/63645cb4-cc50-4ead-ae03-e1f09282004d)

И при попытке открыть эту базу выдаёт "База в неподдерживаемом формате", т.к. база уже залочена с клиента1.

**Comment by dartraiden** [comment]
Отсюда два бага:

1) Когда обе Миранды на одном компе, то вторая видит, что база уже используется и рисует крестик. А когда Миранды на разных компах, то вторая не понимает, что база уже используется.

2) Если база залочена, то следует выводить какое-то иное сообщение, а не то, что база в неизвестном формате.

**Comment by dartraiden** [comment]
Я смог это воспроизвести по RDP.

**Comment by georgehazan** [comment]
Разумеется, не видит, потому что "блокировка" профиля достигается созданием семафора в памяти той машины, где запущена миранда. С другой машины этот семафор никак не прощупать.

**Comment by georgehazan** [comment]
> 2\. Если база залочена, то следует выводить какое-то иное сообщение, а не то, что база в неизвестном формате.

Если база на другой машине, то не приходит ошибка SQLITE_BUSY, приходит unknown error
