### ISSUE TITLE
Tabsrmm: an area for Notes of contact.

### ISSUE THREAD

**Issue by JeanPaulLucien** [miranda-ng/miranda-ng#4163]
We can write any text in Notes area in Details for any contact. Add an area in top of window where will be displaying text from Notes area of contact.

**Comment by georgehazan** [comment]
Options - Message sessions - Toolbar, enable "Edit user notes", this button opens users settings

**Comment by JeanPaulLucien** [comment]
No. I mean we added some info in Notes, I ask to see info from Notes in Tabsrmm window when I'm chatting with this contact.
