### ISSUE TITLE
WhatsApp: при отвязывании от мобильного приложения ключи не стираются из базы

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4164]
У меня каким-то образом Миранда отвязалась от приложения (в "связанных устройствах" на телефоне стало пусто). Соответственно Миранда перестала логиниться и стала выдавать попап о том, что связь разорвана и надо спаривать Миранду с телефоном заново. Но кроме попапа ничего более. Логичнее было бы показывать QR-код, раз нужно спарить снова. Но он не показывается, т.к. в базе остаются ключи (3 ключа, не запомнил их имена). После их стирания руками Миранда стала исправно показывать QR.

Нужно стирать ВСЕ ключи из базы, тогда Миранда покажет снова QR для спаривания Миранды с телефоном.

**Comment by dartraiden** [comment]
Похоже баг возникает, когда сам сервер рвёт связь при долгом отсутствии активности. Если порвать руками, всё стирается. Так что, вернёмся к тикету через месяц, когда связь протухнет на тестовом аккаунте.

**Comment by tamr** [comment]
> вернёмся к тикету через месяц, когда связь протухнет

У меня уже недели 3 сообщения из клиента не доставляются, но хотя бы приём работает.

**Comment by dartraiden** [comment]
Отправка сообщений не реализована вообще.

**Comment by dartraiden** [comment]
Последовательность такая:

- проходит N дней неактивности Миранды, сервер на своей стороне рвёт связь

- Миранда логинится (нетлог прикладываю), выдаёт красный попап о том, что связь порвана
[netlog — копия.txt](https://github.com/miranda-ng/miranda-ng/files/14735732/netlog.txt)

- дальше она продолжает пытаться влогиниться, порождая кучу этих попапов

![cli72DF](https://github.com/miranda-ng/miranda-ng/assets/5046855/40fc8fb6-13dc-4e21-ad25-ab27fd6de8f7)

- если увести Миранду в офлайн, а потом вывести в онлайн, только тогда она покажет QR

собственно баг в том, что происходит куча вот этих заведомо бесполезных попыток влогиниться

**Comment by tamr** [comment]
> Отправка сообщений не реализована вообще, так что она не могла работать ни 3 недели назад, ни 3 месяца.
Эдакий казус приключился, пойду проверю, что мы там наобщались. Паралельно с телефона писал, вначале даже не подозревая об этом. Надо было какую-нибудь плашку в настройках повесить, может где-то в вики об этом сказано, но устанавливал через меню компонентов.

**Comment by dartraiden** [comment]
Угу, на странице плагина в вики написано.
