### ISSUE TITLE
msn return , and his message too

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#417]
**Reported by vvvaaagggaaa on 30 Aug 2015 22:11 UTC**
msn plugin return thanks so much. But when i open miranda: historic appear again and again for people talk for tree last week.
Popup windows show when i talk for last and appear all historic.
plugin works better to send messages and conversations , buts he dont remember i finish conversation.
basic history no clear this problem!
stop history no resolved this problem!

**Comment by dartraiden** [comment]
Protocol is deprecated.
