### ISSUE TITLE
NewStory: проблемы индикатора прогресса загрузки файлов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4182]
1) его цвет не настраивается

2) он дёргается

![vmware_doNRC2qbSZ](https://github.com/miranda-ng/miranda-ng/assets/5046855/b7d19b02-0140-4aae-b749-5df637e36641)

**Comment by dartraiden** [comment]
Чем-то напоминает https://github.com/miranda-ng/miranda-ng/issues/4152, только там было про встроенный журнал, а тут NS и конкретно мигает лишь полоска.

**Comment by georgehazan** [comment]
как телега репортит прогресс закачки, так оно и показывается
