### ISSUE TITLE
Miranda NG. Печать из диалогового окна 

### ISSUE THREAD

**Issue by onyxnm** [miranda-ng/miranda-ng#4191]
Здравствуйте. очень большое пожелание если это возможно в будущем в Miranda NG  добавить в контекстное меню диалогового окна сообщений печать на прямую. 

![miranda ng printf](https://github.com/miranda-ng/miranda-ng/assets/159990221/18b02ace-511d-4402-b602-1e91891cd0e2)

**Comment by georgehazan** [comment]
крайне маловероятно.
код печати, если делать по уму, под виндой настолько непрост, что делать это технически никто не будет
если кто-то настрочит патч, я с удовольствием его залью
