### ISSUE TITLE
irc op controls grayed out

### ISSUE THREAD

**Issue by flesti** [miranda-ng/miranda-ng#4192]
<img width="338" alt="irc" src="https://github.com/miranda-ng/miranda-ng/assets/46891542/db93b527-fbca-4572-98be-36e932bd1ef3">

Away nicks do not color dimmed out either.

**Comment by georgehazan** [comment]
you need to be the channel operator to access them
are you sure that you're an op? if yes, attach a network log (IRC + Core) from the very beginning to the rclick on that user

**Comment by flesti** [comment]
![irc](https://github.com/miranda-ng/miranda-ng/assets/46891542/a59a8fb7-b688-4a03-8466-833e372b9c21)
[irc.txt](https://github.com/miranda-ng/miranda-ng/files/14277174/irc.txt)

**Comment by georgehazan** [comment]
> :dim!dim@Rizon-191D8D77.rizonbnc.eu.rizon.net MODE dim :+SWirx
so in your roles I don't see neither q, nor a - thus the Control menu is not available
