### ISSUE TITLE
Пропала служба поиска!

### ISSUE THREAD

**Issue by neexmitos** [miranda-ng/miranda-ng#4194]
Верните настройку службы поиска пожалуйста!
![изображение](https://github.com/miranda-ng/miranda-ng/assets/93185734/db13a375-9ca6-4740-9d74-22b75819f9f6)

**Comment by georgehazan** [comment]
Настройка никуда не делась, она должна находиться в Settings / JABBER_1 / Jud STRING
Для корпоративных установок настройку можно разлить через autoexec_jabber.ini, указав её там

**Comment by neexmitos** [comment]
Благодарю за ответ, разобрался.
