### ISSUE TITLE
Jabber: add ability to specify STUN address

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4195]
Instead of using hardcoded address.

**Comment by a11cf0** [comment]
Maybe I'm doing something wrong but no matter what STUN server I enter, the connection doesn't get established. I enter STUN addresses in the form ‘stun://server:port’ and I'm sure they're operational.

**Comment by georgehazan** [comment]
@a11cf0 just server:port. as usual

**Comment by georgehazan** [comment]
I don't know, this address is simply passed to the library without any change

**Comment by a11cf0** [comment]
It turns out that the only valid address format is actually stun://... With it I can at least see remote client addresses in the netlog, but even all call attempts fail.

**Comment by georgehazan** [comment]
> It turns out that the only valid address format is actually stun://...

yes, and Miranda passes it in this format inside.

**Comment by georgehazan** [comment]
@a11cf0 извини, был неправ, вспылил. Поправил код, чтобы stun:// подставлялся
