### ISSUE TITLE
Быстрый поиск для списка контактов

### ISSUE THREAD

**Issue by opiums9** [miranda-ng/miranda-ng#4196]
Есть большое желание пользоваться быстрым поиском по списку контактов, аналогично старому доброму QIP2012. Сейчас поиск реализован так:
1. Открываем список контактов
2. Начинаем печатать любое слово
3. По совпадению букв видим в списке найденные контакты (напечатанный текст подсвечивается другим цветом)
4. Сбрасываем быстрый поиск через Esc
5. Если все группы были до этого свернуты, то сворачиваем те, в которых было совпадение по поиску, в следствии чего они оказались развернуты

P.S. Прикладываю скриншот реализации в QIP2012.
![image](https://github.com/miranda-ng/miranda-ng/assets/25082773/84dafb23-006e-43c5-9266-d30f15df82e4)

**Comment by georgehazan** [comment]
Settings - Contact list - Common - Search works as filter

**Comment by opiums9** [comment]
Галочки стоят, но поиска такого не вижу. Может нужны какие то определённые плагины?
Можно скриншот увидеть как выглядит? И что должно для этого быть

**Comment by SUGHuser** [comment]
Даже скрывать группы не надо , достаточно поиск с фильтрацией результатов
