### ISSUE TITLE
Move icons, skins and sounds options to Customize

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4197]

**Comment by dartraiden** [comment]
Надо только у старожилов спросить, с какой целью эти разделы когда-то вынесли из Customize в корень настроек.

**Comment by georgehazan** [comment]
За звуки не скажу, а про иконки и скины очевидно - у них есть собственные подразделы, а опции умеют только один уровень вложенности

**Comment by dartraiden** [comment]
Логичное решение: давай научим дерево опций в более чем один уровень вложенности.

**Comment by dartraiden** [comment]
Ну и для начала можно значки уже перенести.

**Comment by georgehazan** [comment]
> Логичное решение: давай научим дерево опций в более чем один уровень вложенности.

Это полностью сломает текущую реализацию, не пошло

**Comment by georgehazan** [comment]
> Ну и для начала можно значки уже перенести.

Ты имел в виду звуки?
