### ISSUE TITLE
Расширить дерево настроек влево, увеличив слегка размер окна настроек

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4198]
`[19:44] панель с деревом можно и расширить - у меня даже database editor++ не умещается, а русский обычно шире английского
`

**Comment by georgehazan** [comment]
![image](https://github.com/miranda-ng/miranda-ng/assets/4628541/fc0e178b-2526-440c-9d02-9530e6788d14)
почему, собственно,   database editor++ не умещается?
