### ISSUE TITLE
SRMM: увеличить лимит подгрузки сообщений в журнал

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4200]
Сейчас там максимум 100. Юзер просит 1000.

**Comment by SM-Sergey** [comment]
Это да, полезно.
Но вроде же делали, чтобы сообщения динамически подгружались, по мере кручение вверх до упора, как в оф. клиентах. Или просто тикет закрыли?

**Comment by georgehazan** [comment]
> Но вроде же делали, чтобы сообщения динамически подгружались, по мере кручение вверх до упора, как в оф. клиентах.

Эта настройка действует не только в NS, но и в обычных логах

**Comment by dartraiden** [comment]
Именно так: динамическую подгрузку умеет только NS, а остальным будет костыль в виде разовой подгрузки большого числа сообщений.

**Comment by SM-Sergey** [comment]
Да, я понял, простите, втупил, что это только NS умеет.

PS - верните #4206 - он как глючил, так и глючит, только сформулирован неточно.
