### ISSUE TITLE
Все группы, кроме последней пропадают после стирания groups.json

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4203]
Воспроизводится на моём боевом профиле, но на тестовом не воспроизводится.

База проверена, сжата. Группы, само собой, давно перенесены из базы в json.

Стираю json. Запускаю Миранду. Результат: видна лишь последняя группа. Только после рестарта становятся видны прочие.

**Comment by georgehazan** [comment]
А онлайновые контакты есть в других группах? Там флажки тоже скидываются ведь

**Comment by dartraiden** [comment]
Во всех группах есть онлайновые контакты.
