### ISSUE TITLE
NewStory: копировать текст вместе с цветом

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4205]
Юзер хочет, чтобы из NewStory в Word текст вставлялся цветным.

**Comment by georgehazan** [comment]
Непонятно, как это без конвертации в HTML можно сделать.

**Comment by SM-Sergey** [comment]
Вроде, в клипборд можно одновременно несколько форматов поместить, в т.ч. и обычный текст, и форматированный. Тогда каждый клиент сам выберет более подходящий формат из имеющихся.

**Comment by georgehazan** [comment]
> Вроде, в клипборд можно одновременно несколько форматов поместить

Можно

> в т.ч. и обычный текст, и форматированный

А вот такого понятия, как "форматированный текст" в списке форматов клипборда нет. Надо делать полноценный документ через вызов COM и размещать полученный объект в клипборд. Не хочется совсем это делать

**Comment by SM-Sergey** [comment]
> А вот есть. Но не у винды в целом, а у ричедит контрола.

CF_RTF = "Rich Text Format"
CF_RTFNOOBJS =  "Rich Text Format Without Objects"
CF_RETEXTOBJ TEXT = "RichEdit Text and Objects"

Их получают через RegisterClipboardFormat. Ну и все, кому надо, их понимают, ричедит контрол само собой, ибо это его, мс ворд и эксель - тоже понимают.
