### ISSUE TITLE
ICQ: сломалась передача нескольких файлов за один раз.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4206]
Жмем скрепку, выбираем несколько файлов, жмем отправить. Отправляется только один.

**Comment by georgehazan** [comment]
duplicate of #3949

**Comment by georgehazan** [comment]
если посмотреть в оф. клиенте, то видно, что долетают обе картинки

**Comment by SM-Sergey** [comment]
В том то и дело, что нет. Раньше долетали, а сейчас там одна

**Comment by SM-Sergey** [comment]
Тот баг я описывал, и я бы не стал на пустом месте новый создавать!

**Comment by georgehazan** [comment]
Ну вот я две картинки из миранды запустил, две картинки в браузере увидел
чяднт?

**Comment by SM-Sergey** [comment]
А у меня стабильно одна приходит и в оф. клиент, и тому, кому слал...

**Comment by SM-Sergey** [comment]
Хм... Нестабильно. Вот как-то получилось и две прошли.  А другой раз вообще полторы...

**Comment by SM-Sergey** [comment]
Во. Теперь "стабильно" полторы... Вот так выглядит пять раз подряд:

![2024-02-16 13_10_10-ICQ — Mozilla Firefox](https://github.com/miranda-ng/miranda-ng/assets/34127439/aa478bda-85fa-452e-abad-8ae03b628ece)

А так если ее одну послать.

![2024-02-16 13_10_32-ICQ — Mozilla Firefox](https://github.com/miranda-ng/miranda-ng/assets/34127439/bf08f449-b5e0-4fc1-9165-a022e880f665)

**Comment by SM-Sergey** [comment]
В общем оно "глючит" и не всегда одинаково. Может и всё послать, а может и не все, может целиком файл не послать, а может и его кусок отправить.

**Comment by SM-Sergey** [comment]
Откройте этот баг обратно! Он есть!
