### ISSUE TITLE
Несколько учёток с одинаковыми именами

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4210]
Мы позволяем пользователю создать учётки с одинаковыми именами (не внутреннними, внутреннее имя обязано быть уникальным)

Но отсюда вытекает проблема: если, например, создать учётку с именем "1" и другую учётку с именем "1", то они сосуществуют мирно ровно до тех пор, пока мы не зайдем в настройки.

<img width="52" alt="vmware_5wzpGgvJdy" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/f4422b12-d750-419f-9b9b-8b4c247c5ad9">

Где учётки отображаются по именам, поэтому доступна лишь первая из одноимённых учёток.

**Comment by dartraiden** [comment]
Нужно либо запретить создавать учётки с одинаковым именем, либо как-то разруливать это в настройках, добавляя какой-нибудь суффикс.

**Comment by georgehazan** [comment]
Проще запретить, конечно
