### ISSUE TITLE
tabSRMM: реализовать переключение вкладок колёсиком мыши

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4215]
В виде опции, так как по умолчанию колесико прокручивает вкладки, когда они не влезают на экран (например, при вертикальном размещении).

Таким образом, те, кто использует вертикальные вкладки, смогут и дальше их прокручивать, а вот пользователи горизонтальных вкладок смогут задействовать колесико, которое сейчас при горизонтальном размещении ничего не делает.

**Comment by georgehazan** [comment]
Выяснилось, что можно переключать табы с помощью Ctrl-Tab
