### ISSUE TITLE
Настройки: При переключении вкладок фокус падает в дерево

### ISSUE THREAD

**Issue by a11cf0** [miranda-ng/miranda-ng#4217]
Было бы удобнее, если бы фокус переходил на новую активную вкладку, а не перескакивал в дерево категорий.

**Comment by a11cf0** [comment]
Одна странность сменилась другою. При переключении вкладок фокус все еще выпрыгивает из панели, но не в дерево, а на первый элемент новой страницы настроек.

**Comment by georgehazan** [comment]
> При переключении вкладок фокус все еще выпрыгивает из панели, но не в дерево, а на первый элемент новой страницы настроек.

Это и есть в переводе "фокус переходил на новую активную вкладку". Любой диалог при попадании на него фокуса переводит фокус на первый элемент

**Comment by a11cf0** [comment]
@georgehazan Неясность вышла. Имелось в виду простое перемещение фокуса внутри панели вкладок вместе с выделением без выхода из нее, как, к примеру, это сделано в диалоге свойств Проводника и еще много где. Впрочем новое поведение все равно логичнее старого.
