### ISSUE TITLE
NewStory не получается скачать файл

### ISSUE THREAD

**Issue by SUGHuser** [miranda-ng/miranda-ng#4218]
Если имеются несколько учёток на ВК и при этом есть вложения , то при попытке открыть вложения из любой учётки при клике на него , выводится окно диалога на ВК , а не скачивание файла. Поэтому , если вы автаризованы на вкладке 0 с учёткой допустим id00000@choto-tam@com , а вам прислали файл в учётку id00001@choto-tam@com , то при получении этого сообщения , вы будете жать на него и попадать в диалог который не досутпен или пуст в вашей учётке.

Отличия TabSRM и NS в следующем , TABSRM видит :

Вложения:
	Документ: что-то.там (https://vk.com/docAAAAAAAAAA_BBBBBBBBB5?hash=l2h3UMmCCCCCCCCCCCCceOn4F6NtYa4WwkC24wPO3gz&dl=ZDFeaDDDDDDDDDgNWUhZuoL5FeEEEEEEEELlMlMDr4AT&api=1&no_preview=1)
Ссылка на сообщение (https://vk.com/im?sel=AAAAAAAAA&msgid=BBBBBB)

при тыкании на длинную ссылку - сохраняется файл , при тыкании на то что называется ссылка на сообщение - открываеится диалог в котоом пусто (это правильно , если диалог в другой учётке)

NewStory работает таким образом что сообщение имеет вид :
Вложения:
	Документ: что-то.там (https://vk.com/docAAAAAAAAAA_BBBBBBB65?hash=zCzHWTdjAXbcN2gMq8gSCCCCCCCCC3e7NKWBqdNJqz&dl=4PXWEzjjiTR6MxDDDDDDDDDr0Q3YKaZ9cdbCdu6JNYo&api=1&no_preview=1)
Ссылка на сообщение (https://vk.com/im?sel=AAAAAAA99&msgid=BBBBBB)

но при тыкании на вернюю ссдлинную ссылку , NewStory упорно открывает не её , а ту которая ссылка на сообщение , редко , в особо редких случиях NewStory всё же открывает то что надо , но закономерность я не нашёл.

При этом , если скопировать длинную ссылку из NewStory и открыть в браузере через Copy Paste - то она работает , то есть NewStory получает ссылку правильно , но реакция её на вернюю ссылку отстуствует и NewStory реагирует только на то что ссылка на сообщение , а ссылку на документ она игнорирует.

**Comment by georgehazan** [comment]
duplicate of #3665
