### ISSUE TITLE
Добавьте возможность скрытия столба людей при наведении 

### ISSUE THREAD

**Issue by SUGHuser** [miranda-ng/miranda-ng#4219]
Пожалуйста , добавьте возможность скрыть отображение списка контактов миранды если окно миранды свёрнуто или не в фокусе. Я считаю , что когда виден весь список закреплённых или открытых контактов  , это всё таки не нормально и не удобно.
![list0](https://github.com/miranda-ng/miranda-ng/assets/160612271/d4ce1de6-4376-4425-88e6-76867a7aaa79)

**Comment by dartraiden** [comment]
Ничего не понятно, что это вообще и где.

Понятно лишь, что это явно не список контактов.

**Comment by SUGHuser** [comment]
> Ничего не понятно, что это вообще и где.
> 
> Понятно лишь, что это явно не список контактов. А это то ли панель задач, то ли ещё что, из описания не понятно, что это и где.

Это то , как выглядят контакты когда они октрыты и наведён курсор мышки на миранду ) 
![Screenshot_2978](https://github.com/miranda-ng/miranda-ng/assets/160612271/4507d4ba-139c-4156-be8b-54c51f3426cc)
и я считаю , что при навдеении курсора мышки на миранду , нельзя показывать весь список вкладок и контактов ) , будет лучше выводить информацию о том что это просто миранда )

**Comment by SUGHuser** [comment]
Ступил
