### ISSUE TITLE
Протокол ВК , баг отображения шрифта

### ISSUE THREAD

**Issue by SUGHuser** [miranda-ng/miranda-ng#4221]
В протоколе ВК  поплыл шрифт за границы написанного
![vkq](https://github.com/miranda-ng/miranda-ng/assets/160612271/f936791a-e168-4076-a407-525ae559db95)

**Comment by dartraiden** [comment]
Никакого отображения шрифта тут нет, обычный случай, когда русский текст длиннее английского и не помещается в отведённое место.

**Comment by georgehazan** [comment]
![image](https://github.com/miranda-ng/miranda-ng/assets/4628541/6cc68286-ab8a-4b13-ae99-3068345338de)
На штатных шрифтах и 100% размере всё ок

**Comment by dartraiden** [comment]
У меня на двух машинах не влезает.

**Comment by SUGHuser** [comment]
Значит просто надо расширить диалоги на +64-+80 пикселей и всё будет помещаться )

**Comment by dartraiden** [comment]
Диалог настройки и так расширен на днях, чтобы дерево влезало, делать его ещё шире не хочется. Надо урезать перевод.

**Comment by SUGHuser** [comment]
А может сделать изменяемую ширину диалогов ? Само окно тоже сделать изменяемой ширны ) по-умолчанию оставить как есть , но дать возможность раздвигать закреплённые таабы , вот эти вот менюхи например ) ведь будешь урезать перевод , станет менее понятно и более запутано ) у людей будет ещё больше вопросов по мелочам )

**Comment by georgehazan** [comment]
> А может сделать изменяемую ширину диалогов ?

Можно, но не для опций

**Comment by SUGHuser** [comment]
А что мешает их просто подвинуть ? Ведь галки же стоят плотно и опции если смотреть левую частиь тоже расположены плотно )
