### ISSUE TITLE
Добавьте возможность задания глобального никнейма

### ISSUE THREAD

**Issue by SUGHuser** [miranda-ng/miranda-ng#4223]
Если использовать редактор базы данных , то в нём можно создать параметр MyHandle с типом Unicode и задать в нём никнейм который будет отображаться в диалогах ) , но это не удобно тем , что данный никнейм надо указывать в КАЖДОЙ учётной записе отдельно... я хотел бы увидеть в миранде возможность задания глобального никнейма причём силами самой миранды без дополнительных плагинов )

**Comment by dartraiden** [comment]
Это лучше добавить в плагин MyDetails

**Comment by SUGHuser** [comment]
Вообще не надо средствами протокола ) только локально )

**Comment by georgehazan** [comment]
> надо дать возможность получать ник от имени профиля миранды транслируя его на все локальные диалоги

100% нет, потому что у каждой учетки ник свой и хранится в поле Nick. Вообще лазить по редактору базы и что-то там менять - это вредно, потому что всё то, что не выведено в интерфейс настроек, Миранда может менять сама как захочет. Поле Nick берется с сервера протокола в том виде, как оно доступно всем, что позволяет различать сабы в метаконтактах

**Comment by SUGHuser** [comment]
Видимо вообще идею не поняли  ,  нет нкиакого смысла отображать разные ники вот допустим есть вы :
у вас учётка georgehazan , допустим у вас епсть пять учётных записей georgehazan@jabber.ru это ваша личная для поговорить , compcorp@jabber.ru это ваша рабочая куда писать заказы , есть compsupport@jabber.ru это то , куда писать вам не по заказам , а по поддержке , есь ещё у вас фейсбук и вы там подписаны как George Hazan , а есть ещё ВК и вы там подписаны как Георгий Хазан ) и , но у вас есть профиль миранды который называется просто ghazan ) и вы не хотите видеть сами себя в окне сообщений и журнале с разными никами ) , что мешает добавить в миранду возможность ОПЦИОНАЛЬНО , никто не говорит что это должно быть принудительно ) чисто опционально настраивать возможность без всяких редакторов баз данных назначать общий ник MyHandle для всех контактов ?

**Comment by georgehazan** [comment]
> нет нкиакого смысла отображать разные ники

Есть вполне реальный и конкретный смысл. Есть много таких людей, которым это нужно.

> что мешает добавить в миранду возможность ОПЦИОНАЛЬНО

Оно и есть опционально, с использованием плагина. Всем это точно не нужно, и в ядро пихать никто не будет, в Миранде для этого есть плагины

**Comment by SUGHuser** [comment]
Так тогда каждую фичу миранды можно вынести в плагины ) а зачем ? Вот я сначала ставил NewStory , а теперь он мне не нужен , просто потому что разобрался как это же сделать стандартным способом ) и если в миранде не будет нужды ставить редактор базы данных , а задавать локальный ник в самой миранде на все учётки - то ещё минус один плагин )
