### ISSUE TITLE
Баг с отображением последний учётки

### ISSUE THREAD

**Issue by SUGHuser** [miranda-ng/miranda-ng#4225]
Когда учётных записей много
![Screenshot_2987](https://github.com/miranda-ng/miranda-ng/assets/160612271/d526508b-e39e-408e-8d07-c898f0527230)
то последняя запись не дописывасется

**Comment by apollo2k4** [comment]
Не обязательно последней. Это привет из 90-х от Microsoft (ограничение Windows). Tipper в помощь.

**Comment by SUGHuser** [comment]
А что за ограничение из 90-ых ? )
