### ISSUE TITLE
Краш миранды если во время активности удалить учётную запись

### ISSUE THREAD

**Issue by SUGHuser** [miranda-ng/miranda-ng#4229]
Имеем
![mirset01](https://github.com/miranda-ng/miranda-ng/assets/160612271/70f483c9-0d61-44a3-a164-88d2bbff1f73)
![mirset02](https://github.com/miranda-ng/miranda-ng/assets/160612271/626533e8-52d0-45f4-a9a8-ec7176db1439)
![mirset03](https://github.com/miranda-ng/miranda-ng/assets/160612271/35d82bdf-652a-4e0f-a5a8-770fbc67a039)
![mirset04](https://github.com/miranda-ng/miranda-ng/assets/160612271/2260614c-b1f3-4f4a-8e0a-a280723c36c1)
![mirset05](https://github.com/miranda-ng/miranda-ng/assets/160612271/bf953467-1371-4f47-b693-2008d65a8dbd)
![mirset06](https://github.com/miranda-ng/miranda-ng/assets/160612271/d4b9cccd-5302-48c3-b646-81274afc716c)
этот баг был и в 0.94 версии

**Comment by SUGHuser** [comment]
Миранда не упадёт , если сначала закрыть вкладки , а уже потом удалить учётки

**Comment by SUGHuser** [comment]
[Crash.zip](https://github.com/miranda-ng/miranda-ng/files/14395866/Crash.zip)
крашрепорт со вложенным файлом на котором это восспроизвести удалось.

**Comment by georgehazan** [comment]
Символы надо подложить, как это сделать - в вики
https://wiki.miranda-ng.org/index.php?title=Crash_reports

**Comment by SUGHuser** [comment]
Не падает , не понимаю что не так

**Comment by georgehazan** [comment]
Печалька. В общем, если рухнет, приложи сюда лог с символами, тогда открою баг заново
