### ISSUE TITLE
ICQ: crash after file transfer

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4230]
Упало после отправки фотки.

[crash20240224233333.txt](https://github.com/miranda-ng/miranda-ng/files/14394394/crash20240224233333.txt)

**Comment by SM-Sergey** [comment]
При этом файл отправился нормально.

**Comment by georgehazan** [comment]
Печалька, значит, OpenSSL 3.1 такое же дерьмо в плане многопоточности, как и 1.1
А так тикет про это уже есть
