### ISSUE TITLE
Надо улучшить работу с полосой контактов

### ISSUE THREAD

**Issue by SUGHuser** [miranda-ng/miranda-ng#4231]
В Миранде при уменьшения ширины окна контакт-листа при большом числе соединений , происходит формирование не пригодного для восприятия вида окна контакт-листа
если места хватает , учётки прижимаются друг к другу и выглядят так 
![miranda-hvataet-mesta-clist](https://github.com/miranda-ng/miranda-ng/assets/160612271/f833d554-3535-48b7-af7d-8955ad29d605)
но когда места не хватает , получается такая каша :
![miranda-nehvatka-mesta-clist](https://github.com/miranda-ng/miranda-ng/assets/160612271/b97261e8-a8b2-4bec-8b84-3b8eea9e5901)
в тоже самое время в QIP это сделано так :
![qip-ves-clist](https://github.com/miranda-ng/miranda-ng/assets/160612271/d70543ae-8542-424e-af9b-88a4b9f54942)
а когда места нет , то это сделано так :
![qip-nehvatka-mesta-clist](https://github.com/miranda-ng/miranda-ng/assets/160612271/7f2a9a9d-eedc-42a2-a2eb-8fa6d3dcf311)
![qip-nehvatka-mesta-clist2](https://github.com/miranda-ng/miranda-ng/assets/160612271/f07d64ce-6441-4fe8-b399-e9fe744c3cff)
в миранде же , как не настраивай :
![miranda-nehvatka-mesta-clist](https://github.com/miranda-ng/miranda-ng/assets/160612271/2af08a70-dfa3-4232-818e-b71d3db92fa9)
и даже когда делаешь так как скаали в конференции:
![miranda-nehvatka-mesta-clist-set](https://github.com/miranda-ng/miranda-ng/assets/160612271/ce8fda97-dce6-4b63-bc19-fc5062a21128)
всё равно получается так :
![miranda-nehvatka-mesta-clist-2](https://github.com/miranda-ng/miranda-ng/assets/160612271/49a6f275-2647-4a0b-92b2-03e18e8055b6)
а когда места всё равно не хватает , то миранда становится такой :
![miranda-nehvatka-mesta-clist-3](https://github.com/miranda-ng/miranda-ng/assets/160612271/60c43ef3-5fbb-4731-8dde-0b36b75a52a6)
боковой же стрелки на открытие учёток не появляется всё равно

**Comment by SUGHuser** [comment]
Я вижу решением создание минимального числа значков подключения например три значака , если сжали так что видно первые три , а соединений 4 / 5 / 6 и более , то ставим такие же две стрелки как в QIP и при нажатии на них выводим остальные учётки в виде листинга )

**Comment by georgehazan** [comment]
вот и славно, зато в миранде можно сделать список учеток в два ряда
настройка в том же окне
