### ISSUE TITLE
Запинивание открытых боковых вкладок

### ISSUE THREAD

**Issue by SUGHuser** [miranda-ng/miranda-ng#4233]
Нужно сделать запинивание открытых боковых табов в Miranda силами самой Miranda без учёта особенностей протоколов
![pintab](https://github.com/miranda-ng/miranda-ng/assets/160612271/0dbb6102-4a67-4a58-bbec-3cab7a74562a)
я считаю , что закрепление и открепление диалогов надо сделать именно на движке Миранды , _без учёта особенностей протокола_ это надо , потому что Telegram например разрешают закреплять 5 диалогов , а за оплату премиума попросту унижают человека предлагая закреплять ещё 5 диалогов за 2000 рублей в год... в MailAgent и QIP можно закреплять неограниченное число диалогов , это там и там сделано силами клиента и я хотел бы чтоб Miranda NG в этом плане была не хуже чем названные клиенты )

**Comment by georgehazan** [comment]
duplicate of #4201
