### ISSUE TITLE
Сделайте понятный поиск контакта как в контакт листе , так и в закреплённых вкладках

### ISSUE THREAD

**Issue by SUGHuser** [miranda-ng/miranda-ng#4234]
В миранде пока что сделан поиск только такой
![miranda_find](https://github.com/miranda-ng/miranda-ng/assets/160612271/993c44de-b392-4c7a-881c-735f81ad4847)
его недостаток состоит в том , что когда вводишь первую букву поиск предлагает по первой букве через стрелки вверх / вниз находить нужного человека , поиск не делает отсеевание людей по введённой букве как сделано в поиске например на смартфоне , там если вводишь букву то вычетаются те контакты в которых эта буква просто ни в одном из слов не встречается. Именно смарфонный способ поиска реализован в QIP
ниже покажу примеры эталонного поиска контактов
![qip](https://github.com/miranda-ng/miranda-ng/assets/160612271/a55d4353-9206-4502-8100-e50c2d38e8d1)
как видим весь клист и весь диалог открыт
![qip_find_clist](https://github.com/miranda-ng/miranda-ng/assets/160612271/0820003a-eb5f-4664-ac59-87b83f6f6196)
но если нам надо найти человека на букву М то мы её вводим и видим уже что все люди где нет буквы М скрылись
![qip_find_dialogs](https://github.com/miranda-ng/miranda-ng/assets/160612271/183e3754-95c2-4732-bddb-2b3238672d9a)
так же видим , что в открытых диалогах если мы ищем кого-то например на букву Б , то скрываются все люди на остальные буквы
И такой алгоритм поиска реализован в QIP , Mail Ru Agent , в Android ) то есть это интуитимно понятный поиск ) и по мере введения имени или ника искомого , список отображаемых контактов сокращается ) я считаю , что миранде стоит перенять эту хорошую практику и внедрить её как в clist так и в список закреплённых вкладок ) , по сути , это плюс по одному окошечку ввода над списком контактов и над списком открытых закреплённых вертикальных вкладок )

**Comment by georgehazan** [comment]
в списке контактов так и работает. подробнее в #4196
поиска по вкладкам скорее всего не будет

**Comment by SUGHuser** [comment]
А почему по-вкладкам не будет ? Поиск же уже есть в списке контактов , по идее тот же код , только не на список контактов , а в окно сообщений ) почему бы не прикрутить ?
