### ISSUE TITLE
History++: удалить поддержку скрытой настройки `ProfileName`

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4238]
https://wiki.miranda-ng.org/index.php?title=Plugin:HistoryPP/ru#Скрытые_настройки

H++ поддерживает скрытую настройку `ProfileName`, позводяющую заменить имя пользователя на указанное (локально, для отображения в истории).

Но не так давно мы сделали такую поддержку во всех журналах. Через создание `MyHandle` в ветке протокола. В том числе это поддерживает и H++. Таким образом, у нас в H++ образовалась дублирующаяся функциональность.

Предлагаю выпилить `ProfileName`, поскольку `MyHandle` гибче (она попротокольная, в отличие от `ProfileName`, и работает со всеми журналами)

**Comment by georgehazan** [comment]
Т.е. получается, что ProfileName - это тот самый глобальный ник, который так хотел один любитель QIP?

**Comment by dartraiden** [comment]
Ага, только любитель QIP пересел на встроенный журнал табсов.
