### ISSUE TITLE
Miranda tray icon don't change

### ISSUE THREAD

**Issue by Vitalley** [miranda-ng/miranda-ng#4239]
Уже как несколько лет появилась регрессия - ещё в оригинальной Минарде можно было менять значёк, в свежих версиях это не работает, хотя в настройках все поменяно.
![mirandaico](https://github.com/miranda-ng/miranda-ng/assets/29605653/739bd94c-da7a-41bf-a898-7d878a823218)

**Comment by georgehazan** [comment]
А оно не тут, оно чуть ниже - в глобальных иконках статуса. Эта иконка используется только для того, чтобы нарисовать значок Миранды в паре мест.
