### ISSUE TITLE
Telegram: при подгрузке истории групчата появляются пустые контакты

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4243]
По-видимому, это как-то связано с рекламой. Надо их давить и не пущать в клист.

**Comment by georgehazan** [comment]
а можешь сделать нетворк лог, где бы было видно New contact added
хоть попробовать понять, что там как

**Comment by dartraiden** [comment]
Второй вопрос, который стоит выяснить: у этих контактов в клисте пусто, т.к. в базу пишется id, и пустые FirstName и LastName. Они пустые, но они есть и поскольку имеют приоритет, они и выводятся в клисте. Зачем в базу пишутся пустые строки?

**Comment by dartraiden** [comment]
[netlog — копия.txt](https://github.com/miranda-ng/miranda-ng/files/14437586/netlog.txt)
