### ISSUE TITLE
Telegram: опция "Группа" влияет только на приваты, но не на чаты

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4244]
Завожу учётку в миранду. Выхожу в онлайн

Приваты телеграма (беседы с контактами и незнакомцами) улетают в группу "Telegram" (группа указана в настройках протокола)

Но чаты и каналы улетают в группу, которая указана в табсах

<img width="528" alt="Miranda64_CR9pzhF3EG" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/258281bc-c891-464f-9258-f8f2fbcfee7d">

**Comment by dartraiden** [comment]
Собственно, тут нужно выбрать одно из двух:

1) либо дописать в настройках протокола, что опция работает только для приватов

2) либо, чтобы чаты игнорировали настройки табсов и улетали в группу из настроек протокола

**Comment by georgehazan** [comment]
добавил логов, после апдейта надо будет сделать лог

**Comment by dartraiden** [comment]
Исправилось, видимо, вместе с фиксом топиков. Теперь чаты влетают в Telegram/Основные
