### ISSUE TITLE
Telegram: в чатах никлист показывает не всех участников

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4245]
Группа на 600 тел, показывает гораздо меньше.

Группа на несколько тысяч тел, показывает только админов.

**Comment by georgehazan** [comment]
если канал помечен как большой, то Миранде не делает попыток скачать список юзеров, лишь добавляя туда всех тех, кто пишет.

**Comment by georgehazan** [comment]
а не, чуть не так - миранда испускает запрос на получение первой сотни пользователей, потому что больше нельзя, а дальше ловит пишущих

**Comment by dartraiden** [comment]
Тогда неясно, почему в чатике по линуксу на несколько тысяч тел показывает лишь пятерых админов.

**Comment by georgehazan** [comment]
можно снести кэш чатиков и  посмотреть в логе, что отдает телега для данного чата в ответ на запрос getSupergroupMembers

**Comment by dartraiden** [comment]
Посмотри сам, группа https://t.me/grouplinux

**Comment by georgehazan** [comment]
Там показывается то, что телега вернула в ответ на запрос "Показать юзеров супергруппы".
Легко проверяется по логу.
