### ISSUE TITLE
Telegram: не показывать собаку перед никами в никлисте и журнале

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4246]
В очередной раз прошу убрать собаку.

Во-первых, получается чехарда: если у участника есть ник, будет собака, если ника нет, а есть ФИО, будет без собаки.

<img width="92" alt="mstsc_5FP6BCjv6g" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/1e0a1438-7789-4e9d-9562-59d6151e835c">

Во-вторых, собака воспринимается как символ админа традиционно в сетевых чатах. А у нас собака выдаётся всем, у кого тупо есть ник.

В-третьих, в других протоколах мы её не показываем, например, в Твиттере.

В-четвертых, даже официальный клиент не показывает собаку, кроме как в юзеринфо, зачем же мы эту собаку пихаем в никлист, в журнал?

**Comment by georgehazan** [comment]
Давай лог делать, у меня нет юзеров без firstName/lastName
Есть мнение, что оно с сервера так с собакой и едет

**Comment by dartraiden** [comment]
В нашем тестовом чатике посмотри. Там я (@dartraiden) и Alex

**Comment by georgehazan** [comment]
> В нашем тестовом чатике посмотри. Там я (@dartraiden) и Alex. У Alex нет ника, поэтому "Alex" без собаки, т.к. это его FirstName. А у меня есть ник, поэтому с собакой.

Это не помогает, потому что ты у меня в контактах. Можешь убрать у Alex firstName?

**Comment by dartraiden** [comment]
Не могу, телега требует, чтобы у человека было либо FirstName, либо LastName, либо ник
