### ISSUE TITLE
Telegram: поддержка веток

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4252]
Пример: https://t.me/pydjango

Думаю, в таком случае надо создавать внутри группы Telegram подгруппу с именем чата и туда вываливать ветки, как отдельные чаты.

**Comment by georgehazan** [comment]
Она уже есть

**Comment by dartraiden** [comment]
Я пришлю лог.

У меня при заходе в упомянутый чат виден просто чат. Один. А в оф.клиенте при заходе сразу видны ветки.
