### ISSUE TITLE
Telegram: учётная запись удаляется лишь со второй попытки

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4255]
Удаляем из Миранды учётку телеги.

Учётка пропадает из списка учёток. Контакты пропадают из клиста. Но при этом учётка как-то выживает и контакты остаются в базе в состоянии "UNLOADED"

После перезапуска Миранды учётка появляется в менеджере учёток в отключенном состоянии. И вот если её замочить второй раз, только тогда ей кранты.

**Comment by dartraiden** [comment]
Иногда удалённая учётка телеги вообще не появляется, но контакты телеги остаются в базе как неизвестные контакты.

**Comment by georgehazan** [comment]
у меня спилилось всё нахрен с первой попытки
воспроизводится?

**Comment by georgehazan** [comment]
Без сети удалить учетку телеги не получится. И я даже не знаю, как выдать об этом ошибку, потому что оно просто уйдет в рабочий поток и там зависнет

**Comment by AlexZenoo** [comment]
>  воспроизводится?
   ну дык. если у меня так было, и у него - значит, воспроизводится. *мрачно*

**Comment by dartraiden** [comment]
Непонятно, что делать, когда нет доступа к интернету.

**Comment by georgehazan** [comment]
По уму надо просто в отсутствие интернета не давать стирать учетку, но такой функционал сейчас вообще в ядро не вписывается

**Comment by dartraiden** [comment]
Я, всё же, склоняюсь к кнопке. Да, нажатие кнопки при отсутствии интернета будет всё так же вызывать проблему. Но зато можно грохать учётку без всяких проблем.
