### ISSUE TITLE
IRC: режимы не отображаются

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4260]
Вроде, у канала есть режимы

![clp-20240301-2058360](https://github.com/miranda-ng/miranda-ng/assets/5046855/9b9606d3-1f72-4229-b88f-aa3205c389f7)

Но в списке каналов libera.chat  у всех 7000 каналов, включая этот, в столбце "Режимы" пустота

**Comment by georgehazan** [comment]
Там и есть пустота, просто сделай нетворк лог и посмотри, что сервер отдает на LIST

**Comment by dartraiden** [comment]
Да, режимы не отдаёт.
