### ISSUE TITLE
Telegram: в чатах не показывается автор реплик, оставленных от имени канала

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4263]
У выделенных сообщений отсутствует автор. Это НЕ сгруппированные сообщения. У них реально отсутствует автор. Сравните с тем же чатом в официальном клиенте

![309589594-2073117e-57a2-4cdd-af85-d9f08f160102](https://github.com/miranda-ng/miranda-ng/assets/5046855/d7fa1f7c-1079-4a1e-80c4-f40bfe46f11a)

![photo_2024-03-04_02-32-56](https://github.com/miranda-ng/miranda-ng/assets/5046855/aee89bba-496c-4a81-8748-18108f36f822)

![photo_2024-03-04_02-33-37](https://github.com/miranda-ng/miranda-ng/assets/5046855/197fb970-527b-450d-a68b-30455aaf0689)

![photo_2024-03-04_02-33-45](https://github.com/miranda-ng/miranda-ng/assets/5046855/53256f7b-9275-4e50-ace7-4296dc160804)

**Comment by dartraiden** [comment]
Все эти сообщения объединяет одно - автор (Белка-Душнилка)

**Comment by dartraiden** [comment]
Кажется, я понял. Когда ты владелец какого-нибудь канала, то оф. клиент позволяет писать в чатиках или от своего имени (юзера), или от имени канала.

<img width="260" alt="Telegram_HQDF3HMfCo" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/d4ef45f6-51a9-49b0-8e8c-3a0f23c3bd11">

То есть, я могу абсолютно в любом групчате писать от имени своего канала. И вот эта Белка-Душнилка это канал, а не человек.

**Comment by dartraiden** [comment]
По какой-то причине это не работает в нашем тестовом чатике.

**Comment by dartraiden** [comment]
Журнал роли не играет. Встроенный журнал табсов вообще не показывает ник.  NS вместо ника показывает имя чата.

**Comment by georgehazan** [comment]
лог нужен с таким сообщением, я не очень понимаю, что там будет в графе автор

**Comment by dartraiden** [comment]
Стало слегка лучше, но не до конца.

Вгружаю историю с сервера. Реплики от имени канала видны, это исправилось.

Но после перезапуска Миранды эти реплики в журнале не видны вообще. Только в истории.
