### ISSUE TITLE
StdUIHistory: очень медленная скорость открытия истории

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4264]
История чатика с миллионом событий.

NS открывает окно истории с задержкой, но терпимо. Меньше минуты. StdUIHistory уже пять минут открывает и до сих пор не открыл.

Если надо, дам базу.

**Comment by georgehazan** [comment]
Ну а как? Это ж надо каждый раз вот этот огромный кусок RTF перевыделять, чтобы запихнуть туда очередное событие. На то и грид, чтобы манипулировать миллионом маленьких кусочков, так значительно легче
