### ISSUE TITLE
Msg_Export: при экспорте чата в поле "Контакт" пишется ник создателя

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4265]
Это экспорт истории супергруппы. Да, её создатель - Vadim Sterkin, но как-то странно, что он указан в поле "Контакт". Логичнее, если бы в поле "Контакт" было имя чата...

```
------------------------------------------------
      История переписки с
Контакт   : Vadim Sterkin
Учётная запись: Telegram_1
ID пользователя: 1077344003
Псевдоним : Инсайдеры Windows 18+
------------------------------------------------
Vadim Sterkin          31.08.2016 12:13:39 📌Welcome! Правила в описании чата 📃

Vadim Sterkin          01.09.2016 11:42:42 Чат открыт официально! Всем приятного общения:)
```

**Comment by georgehazan** [comment]
Судя по всему, там в Nick и сидит этот самый Vadim Sterkin

**Comment by dartraiden** [comment]
Похоже, да, но повторить это не удалось. Я покинул чат, затем перезашёл и снова стянул всю историю с сервера. Теперь вcё в порядке.
