### ISSUE TITLE
Пожалуйста , сделайте запинивание вертикальных табов )

### ISSUE THREAD

**Issue by SUGHuser** [miranda-ng/miranda-ng#4267]
Я хочу чтоб в миранде сделали пинтаб то есть закрепение вертикально открытых табв в алфавитном порядке , прошу это делать силами миранды не операясь на API чтоб не сталкиваться с глппыми лимитами как например телега 5 запиненных табов в обычное и на 5 запиненных табов больше в премиуме

**Comment by georgehazan** [comment]
Больше пяти - только за баксы

**Comment by AlexZenoo** [comment]
"Следует  второй  сюжет: мужик  пришел  к  врачу  с  жалобой  на внутреннюю  болезнь,  а  врач  попросил его принести  анализы. Мужик  же решил, что  с  него  требуют взятку, и  написал  в  прокуратуру.  Однако оказался  рак, врач его успешно оперирует, мужик спасен, но  тут прямо в операционную  приносят  повестку из  прокуратуры...  Снова  восхищение и одобрительные возгласы, один из лейб-гвардейцев плачет от смеха, уткнувшись лицом мне  в плечо." ©

**Comment by dartraiden** [comment]
Дубликат https://github.com/miranda-ng/miranda-ng/issues/4201

**Comment by SUGHuser** [comment]
> Дубликат #4201, где уже запрошена эта возможность для любого размещения вкладок.
> 
> При чём тут алфавит - непонятно, пользователь сам выбирает, какие вкладки и в каком порядке закрепить.

при том , что от обновления к обновлению и от частоты общения с тем или иным контактом порядок закреплённых вкладок меняется и часто допустим идёт так :

1
2
3
4
5
6
7
8
9


обновилася миранда и теперь порядок стал таким

1
2
9
4
3
5
6
7
8

вот хочется , чтоб это не происходило и для этого лучше закреплять по алфавиту )

**Comment by SUGHuser** [comment]
Разобрался ) это оказывается можно сделать ) , правда менять последовность немного муторно )
![dialog1](https://github.com/miranda-ng/miranda-ng/assets/160612271/8cd5b7fe-15f7-40fe-86b5-45f2441cad5e)
крепится как здесь 
![dialog2](https://github.com/miranda-ng/miranda-ng/assets/160612271/43e015b4-5220-444c-9891-75577ffe8b75)
а открепляется так )
для изменения последовности закрепления надо все сохранённе очистить , закрыть всё вкладки , перезапустить MirandaNG и настраивать заново порядок закреплённых контактов )
в общем , всё оказалось ещё удобнее чем я думал )
