### ISSUE TITLE
Шаблон сообщения NewStory

### ISSUE THREAD

**Issue by apollo2k4** [miranda-ng/miranda-ng#4268]
Игнорировать теги перевода строки и всю остальную нечисть которая может попасть туда из RTF, после последнего значимого знака из «легенды».

Чтобы не получалось что пользователь в шаблоне сделал пробел, в предпросмотре его не видно, в базе он есть (%M\r\n), а при копировании из истории мы получаем перевод строки между сообщениями.

Ну или как вариант сделать как в офисных пакетах – не отключаемые «не печатные символы» в предпросмотре шаблона сообщений.

**Comment by georgehazan** [comment]
> а при копировании из истории мы получаем перевод строки между сообщениями.

это вообще тут не при чём. проблема в том, что к копированию из лога NS подключился формат RTF, а там был забыт параграф между сообщениями, я его уже выкинул
