### ISSUE TITLE
Окно личные данные и HiDPI

### ISSUE THREAD

**Issue by apollo2k4** [miranda-ng/miranda-ng#4269]
При DpiAware=1 в mirandaboot.ini выше описанное окно перестаёт иметь жесткие границы, при изменении границ может сузиться вплоть до половины аватара
![screenshot](https://i.imgur.com/Vs4mluZ.png)

**Comment by georgehazan** [comment]
а оно ресайзится же. сделай его такого размера, как тебе удобно, размер запомнится

**Comment by apollo2k4** [comment]
> а оно ресайзится же. сделай его такого размера, как тебе удобно, размер запомнится

Допустим. С отключенным HiDPI окно не позволяет сузиться больше чем нужно.

**Comment by georgehazan** [comment]
> С отключенным HiDPI окно не позволяет сузиться больше чем нужно.

К сожалению, всё гораздо хуже: разные элементы окна масштабируются по-разному, поэтому так или иначе окно перекашивает
