### ISSUE TITLE
Telegram: при загрузке истории с сервера всегда самым свежим событием прилетает некая "тема"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4270]
На скрине в самом низу журнала.

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/9e1aad1e-67e9-466a-84a1-b5b9acd17e68)

Неясно, что это такое. Это точно не закреп. Но у телеграма нет понятия "топик". Совпадает с короткой ссылкой чата: t.me/winsiders

Предлагаю либо не показывать это событие вовсе, либо (если это реально событие "смена короткой ссылки") показывать его с правильным временем.

Сейчас это событие при загрузке истории всегда прилетает с текущим временем. Словно оно только что произошло. В базе появляется ключ Topic.

**Comment by georgehazan** [comment]
Это у basic group поле, называется description. Прилетает оно в 2 событиях: updateBasicGroupFullInfo и messageChatChangeTitle. Оба сообщения не содержат ни даты смены топика, ни автора изменения - легко проверить по нетворк логу.
