### ISSUE TITLE
Журналы сообщений перестают подгружать историю чата после её импорта из файла, сделанного Msg_Export

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4272]
Наш тестовый чатик в Миранде. В базе лежит история. Ну или сгружаем с сервера, если не лежит.

Экспортируем историю этого чатика в JSON с помощью Msg_Export.

Очищаем историю чатика из базы (ПКМ по контакту - очистить историю), не удаляя с сервера, разумеется. Просто локально убиваем.

ПКМ по контакту - втягиваем импортом историю из JSON.

Результат: в окне истории история видна. Но вот в журнал ничего не подгружается (например, если открыть окно сообщений с журналом NS и скроллить, чтобы он подгружал из базы). Совершенно пусто.

**Comment by dartraiden** [comment]
Похоже, баг в Msg_Export.

Если экспорт делать в NS JSON, то после импорта всё подгружается.

Если экспорт делать в Msg_Export JSON, то после импорта не подгружается.

**Comment by dartraiden** [comment]
К слову, у нас Msg_Export и NS генерируют разные JSON.

Может, прекратить этот разврат?

**Comment by georgehazan** [comment]
Подгрузка истории с сервера не должна отображаться в журнале, иначе всё будет адски тормозить, это фича, там все сообщения грузятся как уже прочитанные (а на них журнал не возбуждается)
