### ISSUE TITLE
Унифицировать структуру JSON в Msg_Export и NewStory

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4273]
В процессе изучения https://github.com/miranda-ng/miranda-ng/issues/4272 выяснилось, что Msg_Export и NS генерируют разные JSON. Там структура отличается.

Как минимум, унифицировать, чтобы экспорт совпадал байт в байт. NS работает с JSON через Import, а Msg_Export как-то справляется сам.

Как максимум, выпилить экспорт из NewStory. Если кому-то нужен экспорт, что мешает поставить Msg_Export, который специально для экспорта и предназначен? Наличие экспорта в NS это тупое копирование H++

**Comment by georgehazan** [comment]
В NewStory по определению нет никакого экспорта, он сидит в плагине Import. Выкинуть экспорт из Msg_Export можно, но пока с ходу не получилось, там очень аккуратно надо
