### ISSUE TITLE
StopSpam/StopSpamMod: на сервере копятся запросы авторизации от спамеров и клист дёргается при старте

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4276]
В антиспаме включена блокировка запросов авторизации. На самом деле, там ничего не блокируется, просто запросы от людей, не прошедших антиспам, скрываются. Запросы остаются неотвеченными, в этом проблема.

Каждый день мне пишут спамеры, их запросы скрываются оперативно. Но неотвеченные запросы копятся и копятся. Их всё больше. И когда их становится достаточно много, то при старте миранды в клисте начинается дёрганье. С каждым днём время этого дерганья растет по мере того, как копятся запросы авторизации.

https://github.com/miranda-ng/miranda-ng/assets/5046855/5a3cc6ad-cae8-4c20-bbe5-278f74da69a8

**Comment by georgehazan** [comment]
Мы это обсуждали в каком-то тикете про StopSpam, оно где-то есть уже.
Пока решения для XMPP не найдено

**Comment by georgehazan** [comment]
@dartraiden 
клист же больше не дергается? а в остальном это дубль существующего тикета про StopSpamMod

**Comment by dartraiden** [comment]
Клист не дёргается, хоть при старте и видно, как спамеры влетают и скрываются. Но размер клиста теперь, хотя бы, не меняется.
