### ISSUE TITLE
Msg_Export: некорректно экспортируется история чатов Telegram

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4279]
Пользователь сообщил, что там какие-то странности при экспорте, я посмотрю.

**Comment by georgehazan** [comment]
А что именно некорректно?

**Comment by dartraiden** [comment]
Пока не удаётся проверить из-за https://github.com/miranda-ng/miranda-ng/issues/4300

**Comment by dartraiden** [comment]
Есть проблемы, но не с ветками, а с чатами в целом.

1) При экспорте в TXT все реплики в экспортированной истории идут от имени чата, а не от участников.

```
------------------------------------------------
      История переписки с
Контакт   : Telegram Test Chat
Учётная запись: Telegram_1
ID пользователя: 1985055038
Псевдоним : Telegram Test Chat
------------------------------------------------
Telegram Test Chat  29.11.2023 17:09:23 Something broke in Miranda because of all this

Telegram Test Chat  29.11.2023 17:09:36 I now have two of these in my Miranda
```

Это писал Вульпикс, но всё подаётся от имени чата.

2) Если очистить в базе историю нашего тестового чата, вгрузить историю с сервера и экспортировать в TXT, то экспортируются лишь первые два события. Остальные в txt не попадают.
