### ISSUE TITLE
Tox: crash on "onion_client.c: do_onion_client"

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#428]
**Reported by Corak on 17 Sep 2015 22:47 UTC**

```
Exception: Access Violation at address 13DCAD91. Reading from address 092DA038.

Stack Trace:
---------------------------------------------------------------
13DCAD91 (libtox 13DA0000): ..\toxcore\onion_client.c (1435): do_onion_client
1224C554 (mir_core 12240000): e:\sources\miranda_ng_compilation\src\mir_core\src\threads.cpp (154): forkthreadex_r
78AFC556 (MSVCR100 78AA0000): (filename not available) (0): endthreadex
78AFC600 (MSVCR100 78AA0000): (filename not available) (0): endthreadex
7C80B729 (kernel32 7C800000): (filename not available) (0): GetModuleFileNameA
```

Netlog attached.

[20150918_do_onion_client.zip](https://github.com/miranda-ng/miranda-ng/files/649168/20150918_do_onion_client.zip)

**Comment by georgehazan** [comment]
**Modified by Corak on 17 Sep 2015 22:48 UTC**

**Comment by georgehazan** [comment]
**Modified by Corak on 17 Sep 2015 22:48 UTC**

**Comment by LittleVulpix** [comment]
These tox crashes should be revised, tox protocol has been updated several times since, and I've not experienced any tox crashes in the past ~2 years of heavy tox use. I'll see about asking Corak to comment on them.

**Comment by aunsane** [comment]
Very old rare crash. There no any sense to reproduce and fix it.
