### ISSUE TITLE
 NewStory: скроллбар в режиме редактирования

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4286]
1) если редактируется даже всего одна строка, скроллбар показывается (и он неактивен)

<img width="512" alt="Miranda64_ELyfM5RLxt" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/98361598-ac96-4e8a-99be-3198daba78e8">

предлагаю не показывать скроллбар в режиме редактирования, если всё влезает на экран
именно так скроллбар работает в журнале - он не показывается, если скроллить нечего

2) в NS есть опция для скрытия скроллбара в журнале

<img width="528" alt="Miranda64_Y4WBlsiouD" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/da9ae366-3a96-4a53-bc63-11f2521639c3">

нужно, чтобы она влияла и на режим редактирования

**Comment by georgehazan** [comment]
Есть важный нюанс: если скроллбар выключен, то в поле ввода не работает колесико мыши, так что п.2 не смог
