### ISSUE TITLE
Вопросы о включении отключенного плагина

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4287]
Открываем список установленных плагинов и отключаем какой-нибудь из них. Например, DbEditor.

<img width="528" alt="Miranda64_81uyJIktUa" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/5276aa08-0583-4025-8c3a-152f619b47aa">

Нажимаем ОК, настройки закрываются. Открываем их снова.

Ожидаемое поведение: открываются настройки.

Реальное поведение: Миранда зачем-то спрашивает "а не загрузить ли отключенный плагин?"

<img width="241" alt="Miranda64_EOKHaYNiJU" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/c4b3af29-9da2-4a1f-a73d-9a4ce58c3ee8">

Если отказаться, она спросит ещё раз. И только после повторного отказа откроет настройки.

**Comment by georgehazan** [comment]
Это управляется настройкой в mirandaboot.ini
[PluginLoader]
AskAboutIgnoredPlugins=1

Не знаю, зачем ты ее включил, если выключить, то вопрос пропадет
