### ISSUE TITLE
После обновления 21 03 2024 не передаются файлы. 

### ISSUE THREAD

**Issue by onyxnm** [miranda-ng/miranda-ng#4288]
Здравствуйте. По всей сети после обновления миранды ng перестала работать отправка файлов.
Коллапс на предприятии. Сможете оперативно выпустить исправление?

**Comment by georgehazan** [comment]
1. в папке PluginUpdater/Backup есть все файлы, которые были заменены. Надо просто влить их в каталог с Мирандой, чтобы вернуть всё в предыдущее состояние

2. а каким образом должна происходить передача файлов? напрямую, через http upload? что говорит network log по этому поводу?

**Comment by onyxnm** [comment]
парк из 150 машин. нереально все заново залить вручную. меня уже разрывают.  передача файлов через прямое соединение у всех снята.  при передаче миранда вылетает с критической ошибкой. залейте пожалуйста предыдущую версию.

**Comment by georgehazan** [comment]
> при передаче миранда вылетает с критической ошибкой.

какой ошибкой, например? крашлог есть?

> залейте пожалуйста предыдущую версию.

заливает робот, собирая версию из исходников. отмотать руками на версию 22-дневной давности не очень реально, там может поплыть что угодно.

**Comment by georgehazan** [comment]
отключил на стабильной версии передачу файлов напрямую, файлы улетают и принимаются только так, со встроенным журналом и NewStory. нужен крашлог, постараюсь исправить как можно быстрее

**Comment by onyxnm** [comment]
папка crashlog пуста.  при передачи ошибка internal server error

**Comment by onyxnm** [comment]
[crash20240321114100.txt](https://github.com/miranda-ng/miranda-ng/files/14692274/crash20240321114100.txt)

**Comment by georgehazan** [comment]
сейчас будет фикс, минуту

**Comment by georgehazan** [comment]
отправил робота собирать всё это, через 20-25 минут стабля ляжет на сервер

**Comment by onyxnm** [comment]
Спасибо большое. после обновления все заработало.
