### ISSUE TITLE
NewStory: регрессии после перехода на HTML

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4289]
- [x] не работает настройка цвета событий, у меня настроен серый текст, но он в реальности всегда чёрный

<img width="528" alt="Miranda64_kPx6WaKIoE" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/f0e8fab0-dc33-41ee-956b-ba1217718ec9">

**Comment by dartraiden** [comment]
- [ ]  событие файлтрансфера "смазывается", когда приходят следующие события

<img width="512" alt="Miranda64_3LVp648xLN" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/de789c52-df2b-46f4-80fc-91c8a89a6600">

**Comment by dartraiden** [comment]
- [ ] шрифт сообщений стоит Calibri 11, но используется явно какой-то иной

**Comment by dartraiden** [comment]
- [ ] настройки шаблонов пропали

<img width="528" alt="Miranda64_vJbyBAr7nJ" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/9e0ab3f9-f519-43b7-ac46-bfc798db1f0b">

**Comment by tamr** [comment]
Очень печально.
![3145](https://github.com/miranda-ng/miranda-ng/assets/209513/5cc88a33-323b-4b79-a8b9-5b6e80f171c4)

**Comment by georgehazan** [comment]
> Очень печально. ![3145](https://private-user-images.githubusercontent.com/209513/315877315-5cc88a33-323b-4b79-a8b9-5b6e80f171c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDY0OTAsIm5iZiI6MTcxMTEwNjE5MCwicGF0aCI6Ii8yMDk1MTMvMzE1ODc3MzE1LTVjYzg4YTMzLTMyM2ItNGI3OS1hOGI5LTViNmU4MGYxNzFjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxMTE2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTE3MzA5ZmNmMTkyYjk2ZGZiMDI2ZmU4ZTFlOTNkYTI1Mjg1ZTVlOTMyNTMyODRkNTk2NTY2N2UwODRmYjc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9Ap8ZR-g8tMUwOotBZSl6YsKNbprfr9-XU6fLzVjaLo)

пофиксилось

**Comment by tamr** [comment]
> Включите опцию "заменять лишь смайлы, окружённые пробелами"
Это было не в теле сообщения, а в стоке даты.

> пофиксилось
Теперь отвалилась опция ограничения размера смайликов.
![2024-03-22_142508](https://github.com/miranda-ng/miranda-ng/assets/209513/f012c01d-244e-41ac-a884-d81d2f31a8a1)

**Comment by georgehazan** [comment]
> Теперь отвалилась опция ограничения размера смайликов и анимация.

Анимации некоторое время точно не будет, про размер оно тоже не очень в курсе

**Comment by dartraiden** [comment]
- [ ] если сообщение состоит из одной лишь ссылки, то ссылка не кликабельна

**Comment by georgehazan** [comment]
> **Outgoing name**
> было 8,96,189
> стало 0,0,0

И это правильно. Вовсе необязательно, чтобы каждый кусок картинки имел другой цвет, если по умолчанию выбраны светлые тона фона, то черный цвет заголовка ok. И так оно было задолго до HTML.

> вдобавок, вместо text color настройка переехала в color/background

Как и любая другая настройка цвета. Если бы для ника можно было бы задать собственный шрифт, оно было бы цветом текста.

**Comment by dartraiden** [comment]
![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/1e5f66b4-c995-435a-8c84-1aae39ae930e)

<img width="326" alt="Telegram_IbQyMkqmQA" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/e894793c-ee06-40eb-87a7-4259cbb1848d">

Сломался word wrap.

**Comment by georgehazan** [comment]
Word wrap не поддерживается в litehtml, забил туда тикет
