### ISSUE TITLE
Всплывающее окно об облачном файле появляется даже при активном окне

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4290]
tabSRMM, NS, Toaster.

Открыт приват с контактом. Окно на первом плане, активное.

Мне этот контакт присылает текстовое сообщение. Оно появляется в логе, никаких попапов, моргания в трее и клисте нет, т.к. оно сразу прочитано.

Но если вместо сообщения файл (Jabber, HTTP File Upload), то вылезает попап.

**Comment by dartraiden** [comment]
Второй баг из той же серии: открыт приват, но окно неактивно и перекрыто другими приложениями. Туда приходит текстовое сообщение. Есть моргание в трее, клисте, а попапа нет.

**Comment by dartraiden** [comment]
Таким образом:
- окно активно: попапа на текст нет (правильно), попап на файл есть (неправильно)
- окно неактивно (попапа на текст нет (неправильно), попап на файл есть (правильно)

**Comment by dartraiden** [comment]
Теперь, когда активен приват, то любое входящее событие порождает попап.

**Comment by georgehazan** [comment]
больше не появляется
