### ISSUE TITLE
ICQ: crash - ничто не предвещало

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4299]
Никто никому не писал, был переконнект по неясным причинам, миранда упала.
[crash20240324184201.txt](https://github.com/miranda-ng/miranda-ng/files/14735970/crash20240324184201.txt)
[netlog_last.txt](https://github.com/miranda-ng/miranda-ng/files/14735972/netlog_last.txt)

**Comment by georgehazan** [comment]
память где-то стерло, а потом в случайный момент на нее наступило и упало
увы, тут по крашлогу не понять, где это происходит
