### ISSUE TITLE
NewStory: съедаются пустые строки

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4304]
Пример первый: отправляем такое сообщение (это одно сообщение, не три)
```

https://forum.miranda-ng.org

ололо

https://cs14.pikabu.ru/post_img/big/2024/03/24/8/1711285943118726138.jpg
```

А в журнале первая пустая строка съедается
<img width="373" alt="Miranda64_q8j78YdjuP" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/d831f2d4-0934-42e7-8cf9-589ddb474b3d">

**Comment by dartraiden** [comment]
Пример второй: отправляем сообщение (это одно сообщение)

```
111

222

333
```

В журнале съедаются все пустые строки
<img width="64" alt="Miranda64_UboydhMqlW" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/4e37e7ea-6559-4cc6-b574-36da88d1fea7">

**Comment by dartraiden** [comment]
При этом, если из журнала эти сообщения скопировать, то они копируются корректно, со всеми пустыми строками. Т.е. проблема лишь в отображении пустых строк.

**Comment by tamr** [comment]
Перенос строк тоже сломался.
NewStory.dll v.0.2.0.1 [25 March, 2024 20:11:38]
![2024-03-25_232819](https://github.com/miranda-ng/miranda-ng/assets/209513/f164954f-dc77-4232-a88c-902073fd7e82)

**Comment by dartraiden** [comment]
Баг в litehtml, не наш.
