### ISSUE TITLE
VK: первая попытка просмотреть инфу об участнике чата всегда неудачна

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4307]
ПКМ по кому-нибудь в никлисте чата (по самому себе, например) - смотрим юзеринфо.

Вместо юзеринфо отктрывается пустота. Вторая попытка успешна.

И так для каждого участника: первая попытка фейл, вторая норм.

**Comment by ElzorFox** [comment]
Не могу повторить у себя - нормально с первого раза. На свежей сборке повторяется?

**Comment by dartraiden** [comment]
Да, стабильно и в разных чатах.

**Comment by ElzorFox** [comment]
fixed in e23adc4
