### ISSUE TITLE
Tox: Libtox crash on reconnection on "mutex.c: mutex_ref"

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#431]
**Reported by Corak on 18 Sep 2015 08:32 UTC**

```
Exception: Access Violation at address 13E8A445. Reading from address 020C01CB.

Stack Trace:
---------------------------------------------------------------
13E8A445 (libtox 13DA0000): ..\..\mingw-w64-libraries\winpthreads\src\mutex.c (83): mutex_ref
1224C554 (mir_core 12240000): e:\sources\miranda_ng_compilation\src\mir_core\src\threads.cpp (154): forkthreadex_r
78AFC556 (MSVCR100 78AA0000): (filename not available) (0): endthreadex
78AFC600 (MSVCR100 78AA0000): (filename not available) (0): endthreadex
7C80B729 (kernel32 7C800000): (filename not available) (0): GetModuleFileNameA
```

Netlog attached.

[crash20150918074032_mutex_ref.zip](https://github.com/miranda-ng/miranda-ng/files/649198/crash20150918074032_mutex_ref.zip)

[20150919_tox_mutex_ref_2.zip](https://github.com/miranda-ng/miranda-ng/files/649199/20150919_tox_mutex_ref_2.zip)

[20150920_libtox_mutex_ref.zip](https://github.com/miranda-ng/miranda-ng/files/649201/20150920_libtox_mutex_ref.zip)

**Comment by georgehazan** [comment]
**Modified by Corak on 18 Sep 2015 08:33 UTC**

**Comment by georgehazan** [comment]
**Modified by Corak on 18 Sep 2015 08:42 UTC**

**Comment by georgehazan** [comment]
**Comment by Corak on 20 Sep 2015 12:58 UTC**

```
Exception: Access Violation at address 13E8A445. Reading from address 00000054.

Stack Trace:
---------------------------------------------------------------
13E8A445 (libtox 13DA0000): ..\..\mingw-w64-libraries\winpthreads\src\mutex.c (83): mutex_ref

```

**Comment by aunsane** [comment]
Very old rare crash. There no any sense to reproduce and fix it.
