### ISSUE TITLE
Добавьте функцию выделения всего и сразу в окне сообщений по многоклику

### ISSUE THREAD

**Issue by SUGHuser** [miranda-ng/miranda-ng#4311]
Сколько сравниваю клиенты Miranda NG и QIP 2010 , узнаю что даже QIP не полностью знал , но узнав что есть фича которой не пользовался - хочу её же в миранде )
1) если кликать триплом - выделяется строка вобоих клиентах
2) если кликать триплом и продолжать кликать дальше в QIP выделяется весь диалог , а в миранде ничего не продоисходит
пожалуйста , добавте фичу мноколика для выделения всего содержимого окна сообщений

**Comment by dartraiden** [comment]
В Миранде много разных журналов, так что конкретизируйте, в каком вы это хотите.

**Comment by georgehazan** [comment]
Во встроенном журнале quadruple click и так работает, в NewStory его не будет никогда

**Comment by SUGHuser** [comment]
[georgehazan](https://github.com/georgehazan)
С чего ты взял что он в TABSRMM работает ? Я как раз и написал об этом именно потому , что в этом журнале он не работает ) я пытался делать вадроклик и ничего не делается.  Обновил только что миранду и там тлже ничего не делается.
