### ISSUE TITLE
NewStory: цитирование после того, как выделено всё

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4312]
Проматываем журнал NS, чтобы подгрузились записи и в привате было записей 15-20

ПКМ - Выделить всё - Цитата

Реальное поведение: цитируется несколько последних сообщений, а перед ними вставляется большое число пустых строк

Ожидаемое поведение: честно говоря, не уверен. Как минимум, пустые строки точно вставляются по ошибке. А сколько должно цитироваться... думаю, цитировать вот прям всю историю из базы это перебор, наверное, цитировать надо всё, что подгружено в окно.

**Comment by georgehazan** [comment]
> наверное, цитировать надо всё, что подгружено в окно.

так и сделано сейчас
