### ISSUE TITLE
Jabber: задваивается ростер

### ISSUE THREAD

**Issue by onyxnm** [miranda-ng/miranda-ng#4314]
Работаем по протоколу jabber   в связке с сервером openfier 4.7.5 
Клиентов 170 
Не систематически но периодично у любого клиента  могут задвоиться списки контактов и миранда ng начинает работать с новым списком контактов (дубликатами), история остается в старом списке контактов которые рядом не в сети. каждый раз приходится удалять профиль и создавать заново после делаю импорт истории и контактов и все восстанавливается. 
Из-за чего это происходит непонятно. на miranda im такого не было никогда в связке с этим же сервером.

**Comment by georgehazan** [comment]
Происходит это оттого, что в момент запуска миранды какое-то модальное окно преграждает главный поток, обычно это что-то типа MsgExport.

Лечение состоит, например, в установке плагина MsgPopup, который преобразует модальные вызовы MessageBox в асинхронные попапы.

**Comment by georgehazan** [comment]
> каждый раз приходится удалять профиль и создавать заново после делаю импорт истории и контактов и все восстанавливается.

проще поставить плагин Db_AutoBackup и брать свежий файл. также очень хорошо помогает против битых профилей

**Comment by onyxnm** [comment]
Поставил плагин MsgPopup.  Настройки дополнительные не требуются для того чтобы баг не повторялся?

**Comment by dartraiden** [comment]
У MsgPopup нет настроек.

**Comment by georgehazan** [comment]
> Плагин MsgExport никогда не был установлен.

Ну их считанное количество плагинов, которые выплевывают модальные диалоги прямо на старте... Sessions, MsgExport и еще парочка
