### ISSUE TITLE
Версия в разработке с символами: дублируются каталоги

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4321]
В https://miranda-ng.org/distr/pdb_x32/ и https://miranda-ng.org/distr/pdb_x64/ все каталоги продублированы в разном регистре (plugins/Plugins и так далее).

Нужно понять, кто это создаёт каталоги с маленькой буквы и не создавать их.

В ночнике без символов и в стабильной версии каталоги не дублируются и все начинаются с заглавной.

**Comment by georgehazan** [comment]
ничего там не дублируется, это просто симлинки
нужны для фукцирования апдейтера с Miranda IM

**Comment by dartraiden** [comment]
Исключено, т.к. эти симлинки только в ночнике с PDB.

Стёр их.
