### ISSUE TITLE
После стирания groups.json контакты при запуске не видны до выхода в онлайн

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4325]
Отключаем все учётки, кроме парочки, оставляем, например, жаббер и телеграм. Выключем Миранду. Стираем groups.json и стираем StatusManager, чтобы протоколы сами не выходили в сеть. Запускаем Миранду.

Результат: в клисте виден лишь контакт Избранное телеграма, остальные жабберные и телеграмные контакты не видны. Только если вывести какой-то протокол в онлайн, тогда становятся видны все контакты, как онлайновые, так и оффлайновые.

**Comment by dartraiden** [comment]
Воспроизводится на любых протоколах. Например, можно вообще один жаббер оставить, тогда клист при старте будет пустой до выхода в сеть.

У "Избранного", похоже, какой-то иммунитет к этому багу.

**Comment by georgehazan** [comment]
а не надо стирать groups.json, потому что больше нигде инфа об отсуттвующих группах не хранится
просрался файл - пока учетку не оживить, эти контакты с их группами в распоряжение миранды не попадут
