### ISSUE TITLE
CrashDumper: плагин не может корректно показать дату в Windows XP

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4327]
В крашлоге дата выглядит очень забавно

`Miranda Crash Report from ^ ^. Crash Dumper v.0.2.0.3`

В VI дата выводится квадратиками

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/d4b6b7fc-825d-4a65-ad33-f65552381549)

**Comment by dartraiden** [comment]
Судя по всему, регрессия от https://github.com/miranda-ng/miranda-ng/commit/b2f33c6f47d37635d28b0d754a0b6e499078dd09

**Comment by georgehazan** [comment]
> Судя по всему, регрессия из-за [b2f33c6](https://github.com/miranda-ng/miranda-ng/commit/b2f33c6f47d37635d28b0d754a0b6e499078dd09)

маловероятно, там реально ничего не менялось вообще
