### ISSUE TITLE
CrashDumper: VI не показывает версию Миранды при запуске в сервисном режиме

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4328]
Если запустить дампер в сервисном режиме, то вместо версии Миранды отображается `(null)`

<img width="444" alt="Miranda64_3C4aXYCUzU" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/a1ea37ac-6219-40c1-8c27-fc02d5bf8505">

**Comment by georgehazan** [comment]
в сервисном режиме ядро не инициализируется, нет его сервисов вообще

**Comment by georgehazan** [comment]
я вообще не понимаю, зачем крашдампер запускать в сервисном режиме
