### ISSUE TITLE
Telegram: в реплае вместо ника цифры

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4329]
В чате кто-то делает кому-то (не Мирандовскому аккаунту) реплай. Например, я сижу с Миранды и делаю реплай на реплику georgehazan

<img width="210" alt="mstsc_W8hecSLtf5" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/0727887c-89fb-4738-bf2d-948a24eb7396">

В реплае вместо ника исходного сообщения - цифры

**Comment by georgehazan** [comment]
должно пофикситься, проверь

**Comment by dartraiden** [comment]
Не исправилось.

**Comment by dartraiden** [comment]
Точнее так:
- если кто-то отвечает на МОЁ сообщение, то моё имя в реплае есть
- если же я из Миранды отвечаю на НЕ МОЁ, или кто-то отвечает на НЕ МОЁ, то цифры.
