### ISSUE TITLE
Telegram: не работает автоскачивание файлов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4331]
В настройках миранды включено автоскачивание облачных (оффлайновых) файлов размером менее 2000 килобайт.

В чат кидают картинку весом 100 килобайт.

Результат: она не скачивается автоматически.

**Comment by georgehazan** [comment]
На свои или отосланные файлы автозагрузка не распространяется

**Comment by dartraiden** [comment]
Картинку кидает другой человек.

**Comment by dartraiden** [comment]
ghazan, 07.04.2024
[21:17] оно подавляет скачивание для групчатов
[21:18] не знаю, почему
