### ISSUE TITLE
Telegram: проблема со множественным редактированием сообщений

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4332]
В чат c официального клиента кто-то пишет `1`.
В Миранду прилетает `1`
Автор сообщения редактирует его и дописывает `2`
В Миранду прилетает исправление.
Автор ещё раз редактирует и дописывает `3`
В Миранду это не прилетает.

Только, когда в чате появится какое-то новое событие (например, кто-то напишет сообщение), тогда прилетит исправление `3`

**Comment by georgehazan** [comment]
пиши лог, у меня всё ок

**Comment by dartraiden** [comment]
Пока не воспроизводится.
