### ISSUE TITLE
NewStory: при ответе в исходное сообщение подставляется время ответа

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4334]
В 00:19 было написано `vvvv`. В 1:03 был сделан ответ. Но в ответе 1:03 проставлено и у самого ответа (правильно) и у оригинального сообщения (баг, выделено рамкой)

<img width="261" alt="mstsc_Gzk8n0qWlU" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/64d8eb3e-579d-4cb5-a8c6-8516e12f15df">

**Comment by ElzorFox** [comment]
VK тут причем? При ответе в Telegram такая же картина. Протокол вообще на это никак повлиять не может, это баг NewStory.
