### ISSUE TITLE
Cloudfile Upload not working

### ISSUE THREAD

**Issue by MP36ctrl** [miranda-ng/miranda-ng#4335]
### Expected behavior
What did you expect?
To sign into a cloudstorage service
### Actual behavior
What did you get instead?
![image](https://github.com/miranda-ng/miranda-ng/assets/79648510/b793e9ce-b846-4822-89af-d9b7da83376d)
"Server does not respond
### Does it work in stable version?
If you know in which dev build (or approximate date when) it was broken, it may be much easier to identify and fix the issue.
This is happening in dev and stable (0.96.5 alpha build #26680 (159d132822) x64 & 0.96.4.1 build #26397 (0c1e86d815) x64)
### Steps to reproduce that behavior
 * Provide step-by-step instructions so we can reproduce the issue (We can't fix what we can't reproduce).
 *  try to sign in to a cloud service
 * Attach your VersionInfo.
 * 0.96.5 alpha build #26680 (159d132822) x64 & 0.96.4.1 build #26397 (0c1e86d815) x64
 * Attach a crash report if you are experiencing crashes (It includes VersionInfo as well).
 * Attach a network log captured if you are experiencing connectivity issues.
 * [2024-04-07 09:56:00 1708] [DPLG2018] DPLG2018: Unknown error
 * [2024-04-07 09:56:12 395C] [DPLG2018] DPLG2018: Unknown error
 * (Not rlly helping unfortunately)

 * If Miranda freezes, hangs up or consumes CPU, attach information obtained by Process Explorer tool.

**Comment by dartraiden** [comment]
Which cloud exactly are you using? (Dropbox, Gdrive, etc)
