### ISSUE TITLE
NewStory: Скроллинг при помощи таскания движка скроллера глючит.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4336]
Я не могу формализовать, как это именно происходит, но это сильно зависит от превьюшек, и предыдущего положения движка. Он может отлетать обратно в конец после движения им вверх, может отлетать в другую позицию, может скроллить, а может и не скроллить. После N-ной итерации скроллинга пропадает "конец" - можно перетаскивать движок в конец, но это не конец - движок отпрыгивает вверх, и чтобы добраться до конца, надо несколько раз тащить его в низ до упора.

**Comment by georgehazan** [comment]
Есть такое, да.
