### ISSUE TITLE
NewStory: Пока в окне есть превьюшки, скроллинг колесом мыши неадекватно медленный.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4337]
Всё в теме.
Как только превьюшки уезжают за экран, скорость скроллинга колесом становится адекватной.

**Comment by georgehazan** [comment]
Не подтверждаю. Колесо мыши прокручивает некоторое количество пикселей за раз, ему вообще по барабану.

**Comment by SM-Sergey** [comment]
Видимо, причина не в том, что я указал.
Я только что обновился, и по-прежнему наблюдаю две скорости скроллинга колесом мыши, тормозную и нормальную. И да, это вроде не связано с наличием превьюшек на экране. А вот с чем именно связано, пока не понял.

**Comment by SM-Sergey** [comment]
Проблема ЕСТЬ! Скорость скроллинга зависит не сколько от наличия превьюшек на экране, а скорее от каких-то свойств самой картинки. Легковесные картинки проскролливаются быстрее, а отправленная мной в высоком разрешении медленнее. Могу видео снять, только куда его - не хочу сюда помещать.
