### ISSUE TITLE
NewStory: реплаи используют формат даты из операционной системы

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4338]
Например, у меня в шаблоне NS настроена дата сообщений в виде dd.mm.yy

И когда в чате появляется реплай, то у исходного сообщения дата показывается "как в ОС" ("апреля" текстом), а у самого сообщения - как настроено в шаблоне ("04" цифрами).

<img width="210" alt="mstsc_qd9XU3VXQj" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/7f1977cd-bf03-4b11-9a40-0935c575de03">

**Comment by georgehazan** [comment]
Ответ очевиден - реплай не является шаблоном
