### ISSUE TITLE
Telegram: скачанный облачный файл не удаляется, когда удаление инициировано сервером

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4339]
В чат другой человек или я сам присылает картинку. Она автоматически скачивается.

- если я удаляю это событие, то файл стирается

- если это событие удаляет другой человек (например, он запостил не ту картинку и быстро её стёр), то событие стирается из базы, но файл остаётся

**Comment by SM-Sergey** [comment]
А почему вообще скачанные файлы должны удаляться? Для сравнения, официальные веб-клиенты не удаляют ни одного файла, который был скачан, да и вообще, принципиальная возможность удаления файлов из загрузок браузера (куда падают скачанные файлы с оф. клиентов, если прямо не указано иное) без разрешения пользователя нереальна, и крайне вредна. Одно дело - сообщение в БД, но скачанный файл - дело совсем иное!

**Comment by dartraiden** [comment]
> Для сравнения, официальные веб-клиенты не удаляют ни одного файла, который был скачан

То есть, со временем, папка официального клиента займёт все мои 22 терабайта? Сомневаюсь.

**Comment by dartraiden** [comment]
Ну, собственно, да, разумеется, он там есть

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/7a05cc44-5170-428e-92e3-57882be74d78)

**Comment by SM-Sergey** [comment]
Я не про кеш (который, если есть, то чистить надо), а про файлы, которые загружены - если я загрузил файл, или разрешил автозагрузку - то за чистку папки "Downloads" отвечаю только я сам, и никто не должен ее чистить без моего ведома.

**Comment by dartraiden** [comment]
А тикет про кэш

**Comment by SM-Sergey** [comment]
Получается, что в миранде де-факто нет кеша (логично его иметь на превьюшки, стикеры, и пр. - они в протоколах идут отдельными сущностями - отделив их от оффлайн файлов), а есть только загрузки. А вот загрузки чистить не надо. По крайней мере молча и тихо не надо.

Да и тикет про "загруженный облачный файл" - вроде это вполне ясно, что файл загружен.

Для общего знаменателя логично спросить пользователя - что файл, связанный с этим сообщением, был загружен - стереть и его? Он ведь мог быть загружен и не автозагрузкой, а мной, и я уверен, что он у меня там лежит...

**Comment by georgehazan** [comment]
> * если это событие удаляет другой человек (например, он запостил не ту картинку и быстро её стёр), то событие стирается из базы, но файл остаётся

ничего подобного, всё стирается на раз, хоть из групчата, хоть откуда.
не стирается в 2 случаях:
- файл не закачан на диск
- выключено автоматическое стирание файлов
![image](https://github.com/miranda-ng/miranda-ng/assets/4628541/fb7787cf-2bd4-4fec-9080-b7f087e1cea6)

**Comment by SM-Sergey** [comment]
> не стирается в 2 случаях

Вах. Вот спасибо то. А я упустил, когда эта галка появилась, включенная по умолчанию. Сколько всего полезного потерять можно было...

**Comment by dartraiden** [comment]
Дал профиль, где это воспроизводится

**Comment by dartraiden** [comment]
ghazan, 08.04.2024
[22:05] там проблема в том, что файл после приема не закрывается

**Comment by dartraiden** [comment]
Похоже, файл держит NS, когда делает превью. Если закрыть окно, то файл стирается

**Comment by SM-Sergey** [comment]
> Ешё почему-то файл автоскачивается не всегда 

Это и я замечал, но, похоже, это связано с ошибками передачи и отсутствием повторных попыток докачать/перекачать.
