### ISSUE TITLE
NewStory: после прилёта картинки с предпросмотром, журнал не докручивается до конца

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4342]
![photo_2024-04-08_22-18-28](https://github.com/miranda-ng/miranda-ng/assets/5046855/c2e4fd38-d72d-4571-af6e-2dae14d1fd31)

**Comment by dartraiden** [comment]
На скриншоте: журнал был прокручен до конца. Прилетела картинка с предпросмотром. NS показывает лишь начало картинки, а до конца журнал не докрутил.

**Comment by georgehazan** [comment]
Тут ситуация очень хреновая с этим... получается так: событие добавляется телегой в тот момент, когда файла физически еще нет на диске, поэтому оно рендерится на 35 пикселей или две строчки. Потом файл докачивается, выдается событие редактирования события, оно пересчитывает высоту с учетом картинки, но позиционирование по высоте остается тем же

**Comment by georgehazan** [comment]
Если сделать, чтобы при редактировании события оно отпрыгивало наверх, то будут дикие скачки, если запустить 2-3 картинки, например.

**Comment by dartraiden** [comment]
Однозначно что-то делать надо, т.к. картинку просто не видно, а докручивать каждый раз вручную это маразм.

**Comment by SM-Sergey** [comment]
Ну где нет, там и суда нет. Но в большинстве-то активно используемых все таки есть, и "диких скачек" будет значительно меньше.

**Comment by SM-Sergey** [comment]
И для "остальных" можно зафиксировать высоту каким-то строго фиксированным размером, а ширину делать - ну какая выйдет по факту.
