### ISSUE TITLE
NewStory: табуляция в режиме просмотра съедается, а в режиме редактирования нет

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4348]
Отправляем контакту код

```
	#include <mutex>
	static std::mutex mutex;
	#define lock_guard std::lock_guard<std::mutex> lock(mutex)
```

Открываем сообщение на редактирование.

Результат: при отображении в журнале табуляция съедается. А вот в режиме редактирования табуляция исправно показывается.

Хотелось бы, чтобы табуляция не съедалась.

Например, в оф. клиенте Telegram табуляция тоже съедается, но там можно использовать маркдаун и оформить код как код, чтобы сохранить форматирование. А в миранде нет возможности послать контакту сообщение с сохранением форматирования.

**Comment by georgehazan** [comment]
> Например, в оф. клиенте Telegram табуляция тоже съедается, но там можно использовать маркдаун и оформить код как код, чтобы сохранить форматирование.

там табуляции банально меняются на пробелы, в таком виде оно и приезжает в Миранду.
