### ISSUE TITLE
IEView вкладки в настройках скинов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4350]
![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/9cc7dfa9-1205-484a-ab37-4cd18c5dcfa5)

Если я правильно понимаю, то "журнал" это журнал в приватах, "чаты" - журнал в чатах, а "история" - это при наличии IEHistory

Предлагаю:
- переименовать "журнал" в русской локализации во что-то более понятное (что это приваты)
- при отсутствии IEHistory прятать вкладку "история" или делать все элементы на ней отключёнными и выводить надпись о том, что надо установить IEHistory. Иначе для пользователей это выглядит странным - настройки есть, но никак на окно истории они не влияют.

**Comment by georgehazan** [comment]
Перевод поправь по вкусу. На самом деле нынешний вариант довольно точно отражает ситуацию
