### ISSUE TITLE
Telegram: временные контакты перестают быть временными

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4356]
Мне пишет некто, кто не в контактах.

Он появляется у меня в клисте Миранды как временный (серенький). В базе имеет ключ `NotOnList`.

Передёргиваю протокол в оффлайн и обратно в онлайн.

Контакт из временного превращается в полноценный, у него пропадает ключ `NotOnList` и в базе отрастает ветка ContactPhoto

При этом, он не добавляется в контакты на сервере (если посмотреть через оф. клиент, то контактов нет).

**Comment by dartraiden** [comment]
Вообще, тут довольно спорно.

Вот мне пишет чувак. По логике он должен быть временным до того момента, как я его добавлю, либо он будет стёрт клистом при выходе.

Допустим, я не хочу, чтобы он стёрся. Тогда я должен его в Миранде добавить в постоянный список. Но при этом он добавится в серверый ростер, т.к. в оф. клиенте будет в "Контакты".

**Comment by georgehazan** [comment]
> Контакт из временного превращается в полноценный

Он включается телегой в список активных чатов, а все такие чаты убираются из NotOnList.

> Т.е. в оф. клиенте у нас есть две сущности: чуваки, который в контактах, и чуваки которые не в контактах.

Миранда в телеге вообще не оперирует понятием контакта, тут контактом является каждый отдельный чат
