### ISSUE TITLE
Некорректный перевод контакта на Dummy

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4359]
Создаю учётку `Dummy_1`, указываю в её настройках уникальный идентификатор `id`
Увожу телеграм в оффлайн.
Контакту меняю значение ключика `p` и имя ветки протокола на `Dummy`

Перезапускаю Миранду.

Контакт успешно перевёлся на Dummy, но вместо моего имени в переписке "неизвестный контакт".

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/c03bc19f-7e0f-4573-b5b7-9b982411d78f)

**Comment by georgehazan** [comment]
Логично. А кто будет этому контакту прописывать имя уникального id?

**Comment by dartraiden** [comment]
Баг не зависит от протокола.

**Comment by dartraiden** [comment]
![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/9ba25fc9-4e23-4804-b4d2-8b59ec6e81f5)

**Comment by georgehazan** [comment]
Твоё собственное имя берется из поля Nick в учетке. Если его нет, то будет неизвестный контакт.
