### ISSUE TITLE
NewStory: опция про хранение только превьюшек

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4363]
Насколько я вижу, мы выделили для превьюшек отдельный каталог в профиле.

Юзер хочет видеть превьюшки, но одновременно, чтобы диск не очень забивался файлами, которые в чатиках порой летят тоннами

https://forum.miranda-ng.org/index.php?topic=28.msg31257#msg31257

Мне видится некая опция-костыль

1) механизм работы:
- файл будет автоскачиваться 
- делаться превьюшка и сохраняться в Previews
- файл будет стираться автоматически
- превьюшка будет оставаться
- если юзеру нужен полноценный файл, он может его скачать вторично уже руками, например, 2-кликом на превьюшку

2) эта опция будет опциональной и действовать только при включенном автоскачивании, т.к. если автоскачивание не включено, то смысла во всех этих плясках нет

**Comment by georgehazan** [comment]
Не понял, зачем всё это. Очень много вопросов:
- почему будет стираться файл?
- зачем при этом сохранять превью?
- превью вынесено в отдельный каталог, чтобы стирать их всех чохом при старте миранды, например, из батника
