### ISSUE TITLE
Удаление истории: не взводить по умолчанию опцию про удаление у всех

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4365]
Мы, вроде, где-то договаривались, что опция "удалить у всех" будет по умолчанию выключена, уж больно это разрушительно

Сейчас она включена. К чему это приводит:
- я пообщался с чуваком, мы обкашляли вопросики и больше нам говорить не о чем
- я хочу грохнуть приват с сервера У МЕНЯ (чтобы он не болтался больше ни в Миранде, ни в оф.клиенте)
- я взвожу галку "удалить историю с сервера"

при этом сразу взведена доп. галка "удалить у всех"

- если я проглядел и не снял "удалить у всех", то я снесу приват не только себе, но и чуваку

![323779746-c349e939-beb2-4ce7-bf57-445718734402](https://github.com/miranda-ng/miranda-ng/assets/5046855/b52cd31a-f796-4b7d-b6f8-f1e166b35f1f)

Обведенное красным должно не иметь галки по дефолту. Сейчас оно disabled, но галка взведена

**Comment by georgehazan** [comment]
Если опция удаления с сервера выключена, то содержимое галки снизу игнорируется
