### ISSUE TITLE
Windows 11: Icon strings are displayed twice in the SysTray

### ISSUE THREAD

**Issue by winman3000** [miranda-ng/miranda-ng#4368]
### Describtion

If I go to the SysTray in Windows 11 and navigate between the applications in the background, the Miranda NG icon string is displayed twice. This can most likely only be reproduced with a screen reader.

This duplicate display did not occur under Windows 10. The icons of the other programs, which are also displayed in the SysTray, are displayed normally.

This problem occurs with all previous Miranda NG versions, so it is not a problem for a specific Miranda NG version.

### Steps to reproduce

To reproduce, use any screen reader such as NVDA or the supplied screen reader Narrator.

1. Turn on narrator by pressing CTRL+Windows key+Enter.
1. Now press Windows key+B to access the SysTray.
1. Now use the left and right arrows to navigate through the icons until you have found the Miranda NG icon.

#### Result

The screen reader says something like: "Facebook Offline Facebook Online". So first the outdated status is displayed, then the new status. If someone has logged in, something like "Facebook Offline Example contact online" is displayed.

#### Expected

The Miranda NG icon should only be displayed once, as in previous Windows versions.

**Comment by georgehazan** [comment]
Miranda creates a tray icon for each account and for Miranda itself. You can disable it by choosing "Display global icon only" in Options - Contact list - Tray

**Comment by winman3000** [comment]
@georgehazan: I am aware of this. However, when I restart Miranda NG, the old and new statuses are displayed at the same time, i.e. something like: "Facebook Offline Facebook Online". This does not occur under Windows 10. As I said, visually it doesn't seem to be the case, but for screen readers it is.
