### ISSUE TITLE
NewStory: не работает опция "всегда ограничивать журнал до X событий"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4370]
<img width="528" alt="Miranda64_PzLbMsDHi5" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/54a3d021-2116-4195-8a1b-27e6033e29df">

Как эта опция работает во встроенном журнале:
- указано подгрузить при открытии окна 100 событий из истории,
- тем не менее, при открытии в журнале отображается ровно 5 событий
- при поступлении нового события одно старое прячется и в журнале так и остаётся всегда 5 последних событий

так и должно быть

Как эта опция работает в NewStory:
- никак
- при открытии окна подгружается 100 событий
- при поступлении нового события мы получаем уже 101 событие
- кроме того, NS позволяет подгружать события при проматывании в прошлое

Вывод:
1) эта опция должна быть либо убрана для NS
2) либо эта опция должна всегда ограничивать журнал до указанного числа сообщений и, вероятно, отключать подгрузку из базы при проматывании в прошлое

**Comment by georgehazan** [comment]
Оно вообще не имеет никакого касания к NS, выкинул его из диалога
