### ISSUE TITLE
NewStory: кнопка `Delete` не работает после удаления события

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4373]
Ставлю фокус на событие. Оно выделяется цветом. Нажимаю `Delete`. Событие удаляется. Фокус автоматически встаёт на следующее событие. Нажимаю `Delete`. Ничего не происходит. Нужно зачем-то ещё раз выделить это уже выделенное событие, тогда его можно удалить.

Ещё одно проявление этого бага: включаем опцию "совместимость с H++". Теперь стрелки клавиатуры позволяют перемещать фокус. Удаляем сообщение клавишей `Delete`. Стрелки перестают работать, ничего не делают.

**Comment by georgehazan** [comment]
Винда в любом списке ведет себя точно так же, это обычное поведение для списка с кареткой

**Comment by georgehazan** [comment]
После вызова диалога подтверждения на удаление фокус улетает на какой-то другой контрол в окне, если нажать Tab, то он обратно переместится на журнал, и кнопка Delete заработает вновь

**Comment by dartraiden** [comment]
Да, почему-то после удаления:

1) выделяется следующее сообщение
2) фокус при этом ускакивает в поле ввода

**Comment by georgehazan** [comment]
В общем-то понятно, почему это происходит: поднимается диалог с вопросом, захватывает себе фокус, потом отпускает фокус, окно табсов его ловит и привычно переводит фокус на окно ввода

**Comment by georgehazan** [comment]
case WM_SETFOCUS:
		if (CMimAPI::m_shutDown)
			break;

		UpdateWindowState(WM_SETFOCUS);
		SetFocus(m_message.GetHwnd());
