### ISSUE TITLE
NewStory: клик по списку контактов сбрасывает выделение в активной вкладке журнала

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4374]
Открыто два привата. Выделяю событие в первом привате. Переключаюсь на второй приват. Выделяю там тоже. 

Кликаю в клисте по контакту - выделение в активной вкладке сбрасывается. В неактивной сохраняется.

**Comment by georgehazan** [comment]
ну да, там как бы заново открывается окно. 
повторно окно не создается, а вот его содержимое полностью сбрасывается
