### ISSUE TITLE
TabSRMM toolbar issue

### ISSUE THREAD

**Issue by MP36ctrl** [miranda-ng/miranda-ng#4379]
### Expected behavior
What did you expect?
Toolbar to look normal

### Actual behavior
What did you get instead?
Toolbar buttons are shifted up
Here are some comparisons compared with build v0.96.2(also note how the status bar is also not properly themed):
![tabSRMM aero](https://github.com/miranda-ng/miranda-ng/assets/79648510/79cbeeaf-928c-4360-aea5-5447fb34e260)
![tabSRMM Issue aerobasic](https://github.com/miranda-ng/miranda-ng/assets/79648510/df46fcf6-0b69-479b-9377-e9bb7c374c20)
![tabSRMM Issue Classic theme](https://github.com/miranda-ng/miranda-ng/assets/79648510/bac5c41c-d2dc-4ef4-8337-dd6d5f31fed0)

### Does it work in stable version?
If you know in which dev build (or approximate date when) it was broken, it may be much easier to identify and fix the issue.
This happens on all OSes,  on aero, classic and basic windows themes 

### Steps to reproduce that behavior
 * Provide step-by-step instructions so we can reproduce the issue (We can't fix what we can't reproduce).
 * Attach your VersionInfo.
 * Attach a crash report if you are experiencing crashes (It includes VersionInfo as well).
 * Attach a network log captured if you are experiencing connectivity issues.
 * If Miranda freezes, hangs up or consumes CPU, attach information obtained by Process Explorer tool.
 
[spoiler=VersionInfo][quote]CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz [Intel64 Family 6 Model 158 Stepping 13] [DEP Enabled] [8 CPUs]
Installed RAM: 32686 MBytes
Microsoft Windows 7 Home Premium Edition, 64-bit (build 7600)
Internet Explorer: 9.11.19041.0 (build 919041)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | English/English
Free disk space on Miranda partition: 506831 MBytes

Miranda NG Version: 0.96.5 alpha build #27114 (2aeb7d051e) x64
Build time: Monday, 22 April 2024 19:53:52
Profile: D:\Program Files\Miranda Whatsapp\Miranda 2\Profiles\MirandaWhatsapp\MirandaWhatsapp.dat
Database driver: SQLite database driver
Profile size: 30793728 Bytes
Profile creation date: Thursday, 11 April 2024 23:16:02
Language pack: No language pack installed
Service Mode: No
SRMM Log Viewer: ieview

[b]Active Plugins (40):[/b]
¤ Alarms.dll v.[b]0.4.0.6[/b] [Thursday, 11 April 2024 21:03:32] - Alarms 
¤ AVS.dll v.[b]0.98.1.6[/b] [Sunday, 14 April 2024 14:44:34] - Avatar service 
¤ Clist_modern.dll v.[b]0.9.1.12[/b] [Sunday, 14 April 2024 14:45:44] - Modern contact list 
¤ CloudFile.dll v.[b]0.11.0.6[/b] [Sunday, 14 April 2024 14:47:20] - CloudFile 
¤ CrashDumper.dll v.[b]0.2.0.3[/b] [Sunday, 14 April 2024 14:45:48] - Crash dumper 
¤ CryptoPP.dll v.[b]1.0.4.8[/b] [Sunday, 14 April 2024 14:46:44] - Crypto++ 
¤ Db_autobackups.dll v.[b]0.1.0.7[/b] [Monday, 22 April 2024 19:54:14] - Db autobackuper 
¤ DbChecker.dll v.[b]0.96.4.1[/b] [Monday, 22 April 2024 19:56:30] - Database checker 
¤ Dbx_sqlite.dll v.[b]0.96.4.1[/b] [Monday, 22 April 2024 19:56:24] - Miranda NG SQLite database driver 
¤ Discord.dll v.[b]0.96.5.1[/b] [Sunday, 14 April 2024 14:47:42] - Discord protocol 
¤ Dummy.dll v.[b]0.2.0.1[/b] [Monday, 22 April 2024 19:55:50] - Dummy protocol 
¤ Facebook.dll v.[b]0.1.0.11[/b] [Sunday, 14 April 2024 14:47:32] - Facebook 
¤ historypp.dll v.[b]1.5.1.5[/b] [Thursday, 11 April 2024 21:10:34] - History++ 
¤ ICQ.dll v.[b]0.96.5.1[/b] [Thursday, 18 April 2024 21:56:24] - ICQ-WIM protocol 
¤ IEView.dll v.[b]1.6.0.6[/b] [Sunday, 14 April 2024 14:44:58] - IEView 
¤ Import.dll v.[b]0.96.3.1[/b] [Monday, 22 April 2024 19:54:34] - Import contacts and messages 
¤ IRC.dll v.[b]0.96.1.4[/b] [Sunday, 14 April 2024 14:44:36] - IRC protocol 
¤ Jabber.dll v.[b]0.95.11.1[/b] [Sunday, 14 April 2024 14:45:44] - Jabber protocol 
¤ Jingle.dll v.[b]0.1.0.2[/b] [Sunday, 14 April 2024 14:47:34] - Jingle 
¤ MinecraftDynmap.dll v.[b]0.1.0.1[/b] [Thursday, 11 April 2024 21:05:10] - Minecraft Dynmap protocol 
¤ MsgPopup.dll v.[b]0.1.2.2[/b] [Thursday, 11 April 2024 21:04:24] - Message popup 
¤ NewEventNotify.dll v.[b]0.2.2.7[/b] [Monday, 22 April 2024 19:54:42] - NewEventNotify 
¤ PluginUpdater.dll v.[b]0.2.1.7[/b] [Sunday, 14 April 2024 14:45:58] - Plugin updater 
¤ PopupPlus.dll v.[b]2.1.3.0[/b] [Sunday, 14 April 2024 14:45:46] - Popup plus 
¤ QuickSearch.dll v.[b]1.5.0.4[/b] [Sunday, 14 April 2024 14:47:30] - Quick Search 
¤ Restart.dll v.[b]0.0.6.0[/b] [Thursday, 11 April 2024 21:03:54] - Restart 
¤ SecureIM.dll v.[b]1.0.12.6[/b] [Sunday, 14 April 2024 14:45:00] - SecureIM 
¤ SeenPlugin.dll v.[b]5.0.5.6[/b] [Sunday, 14 April 2024 14:45:00] - Last seen 
¤ SendSS.dll v.[b]0.9.0.2[/b] [Friday, 19 April 2024 19:23:48] - Send ScreenShot+ 
¤ StatusChange.dll v.[b]1.3.0.0[/b] [Thursday, 11 April 2024 21:04:20] - Status change 
¤ StatusManager.dll v.[b]1.2.0.6[/b] [Sunday, 14 April 2024 14:47:28] - Status manager 
¤ TabSRMM.dll v.[b]3.6.2.6[/b] [Monday, 22 April 2024 19:54:08] - TabSRMM 
¤ Telegram.dll v.[b]0.11.0.1[/b] [Friday, 19 April 2024 19:29:26] - Telegram protocol 
¤ Tipper.dll v.[b]2.1.0.8[/b] [Thursday, 11 April 2024 21:03:24] - Tipper 
¤ TopToolBar.dll v.[b]0.8.0.5[/b] [Thursday, 11 April 2024 21:03:32] - TopToolBar 
¤ Tox.dll v.[b]0.96.4.1[/b] [Sunday, 14 April 2024 14:47:52] - Tox protocol 
¤ UInfoEx.dll v.[b]0.9.0.3[/b] [Sunday, 14 April 2024 14:45:38] - User info ext 
¤ VoiceService.dll v.[b]0.1.3.2[/b] [Sunday, 14 April 2024 14:47:32] - Voice Service 
¤ WhatsApp.dll v.[b]0.0.1.1[/b] [Sunday, 14 April 2024 14:47:44] - WhatsApp protocol 
¤ WhenWasIt.dll v.[b]0.4.0.2[/b] [Sunday, 14 April 2024 14:45:06] - Birthday reminder 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
CloudFile/Dropbox        0 - Enabled 1 - Disabled  Loaded
CloudFile/GDrive         1 - Enabled 0 - Disabled  Loaded
Discord                  1 - Enabled 0 - Disabled  Loaded
Dummy                    1 - Enabled 0 - Disabled  Loaded
IRC                      1 - Enabled 0 - Disabled  Loaded
JABBER                   2 - Enabled 1 - Disabled  Loaded
MinecraftDynmap          1 - Enabled 0 - Disabled  Loaded
TOX                      1 - Enabled 0 - Disabled  Loaded
Telegram                 1 - Enabled 0 - Disabled  Loaded
WhatsApp                 1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 AlarmActivated.ico [Saturday, 13 April 2024 13:01:53]
 HistoryPP_icons.dll [Thursday, 11 April 2024 21:10:28]
 Proto_Discord.dll [Sunday, 14 April 2024 14:52:14]
 Proto_Dummy.dll [Monday, 22 April 2024 20:00:38]
 Proto_Facebook.dll [Sunday, 14 April 2024 14:52:14]
 Proto_ICQ.dll [Thursday, 18 April 2024 22:00:50]
 Proto_IRC.dll [Sunday, 14 April 2024 14:52:12]
 Proto_Jabber.dll [Sunday, 14 April 2024 14:52:12]
 Proto_MetaContacts.dll [Monday, 22 April 2024 20:00:38]
 Proto_MinecraftDynmap.dll [Thursday, 11 April 2024 21:10:28]
 Proto_MRA.dll [Thursday, 18 April 2024 22:00:50]
 Proto_Telegram.dll [Friday, 19 April 2024 19:29:38]
 Proto_Tox.dll [Sunday, 14 April 2024 14:52:14]
 Proto_WhatsApp.dll [Thursday, 11 April 2024 21:10:30]
 SecureIM_icons.dll [Sunday, 14 April 2024 14:52:12]
 TabSRMM_icons.dll [Monday, 22 April 2024 20:00:38]
 Toolbar_icons.dll [Sunday, 14 April 2024 14:52:12]
 UInfoEx_icons.dll [Sunday, 14 April 2024 14:52:12]
 xStatus_Jabber.dll [Sunday, 14 April 2024 14:52:12]
[/quote][/spoiler]

**Comment by georgehazan** [comment]
It's senseless to compare group chats & private chats in tabSRMM, because controls in group chats are really located 2 pixels down in comparison with private chats (don't ask me why, let's say due to some historical reasons).

**Comment by MP36ctrl** [comment]
The 2 pixel issue has been fixed, although the only issue left I see is the buttons themselves having a bg issue (non aero is most noticeable)

![tabSRMMbutton bg issue](https://github.com/miranda-ng/miranda-ng/assets/79648510/042e5e65-1a69-4e58-b681-67db8c97400a)

Normally the button bg would not look different from the toolbar bg, as seen here:

![image](https://github.com/miranda-ng/miranda-ng/assets/79648510/3531674d-e407-46ee-ae86-92290cc959d1)
