### ISSUE TITLE
Discord: Groupchat support

### ISSUE THREAD

**Issue by MP36ctrl** [miranda-ng/miranda-ng#4382]
**Is your feature request related to a problem? Please describe.**
There is no proper support for discord groupchats
**Describe the solution you'd like**
Support for Discord groupchats 
**Describe alternatives you've considered**
To wait for a typing notification and then go to official discord client which isnt stable on win xp
**Additional context**
Hopefully its not too difficult

**Comment by georgehazan** [comment]
Right now Discord supports private group chats (out of the Guilds). What's wrong with them now? You don't see them?

**Comment by MP36ctrl** [comment]
They are in the contact list but they are offline so i cant access them

The only thing working from them is typing notification

**Comment by MP36ctrl** [comment]
![Discord](https://github.com/miranda-ng/miranda-ng/assets/79648510/337aa564-18f4-4fc0-8aa5-3b4da0c0a8fa)
This is what i mean by its stuck offline even though the Discord Protocol is online
