### ISSUE TITLE
Discord: проблемы со статусами

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4388]
1) Наш протокол позволяет выставить 

В сети
Отсутствую
Недоступен
Не беспокоить
Невидимый

Официальный клиент позволяет

В сети
Неактивен
Не беспокоить
Невидимый

Таким образом, у нас один из статусов лишний. Экспериментально установлено, что это статус "Не доступен". Остальные статусы корректно мапятся в дискордовские один в один, а "Не доступен" выглядит зелененьким, как "В сети".

2) Я в Миранде выставляю статус "Не беспокоить". При этом Миранда должна выставить сообщение статуса

<img width="528" alt="Miranda64_Xzyxw8HKhR" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/20d73254-2317-4abe-8513-da759f8e1a75">

Но друзья с оф.клиентами не видят сообщение

<img width="175" alt="firefox_UiERS7NWz0" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/c183f093-5a19-4666-87d3-b1988b65d62b">

Но если я параллельно с Мирандой зайду через оф. клиент, тогда друзья начинают видеть моё сообщение.

То есть, Миранда статусное сообщение выставляет, но как бы забывает дать серверу пинок, чтобы сервер сообщение увидел. И только параллельный заход через оф. клиент заставляет сервер наконец увидеть статусное сообщение

**Comment by georgehazan** [comment]
> Но если я параллельно с Мирандой зайду через оф. клиент, тогда друзья начинают видеть моё сообщение.

Круто, потому что Миранда вообще не выставляет стамеску в дискорде.

**Comment by dartraiden** [comment]
Ты выпилил не тот статус. Выпилил "Отсутствую", он корректно работал. Нужно выпилить "Недоступен".

**Comment by dartraiden** [comment]
Баги всё ещё есть:

3) Не работает статус "Невидимый"
В официальном клиенте невидимость означает именно невидимость. Как в списке друзей, так и в каналах. Человек со статусом "Невидимый" везде отображается, словно он не в сети.

В Миранде "невидимый" ничем не отличается от "В сети" - нас видят с зелененьким кружочком.

4) Миранда выставляет стамески вопреки написанному в комментах выше. Но как-то рандомно.
Открой одновременно Миранду и дискорд в браузере. В браузере выстави статус "В сети", а у Миранды пошёлкай "не беспокоить", "Отсутствую" туда-сюда. Иногда она выставляет стамеску

5) Вдогонку: статусы не синхронизируются. У нас в браузере может быть выставлен один статус, а в Миранде другой. Нужно, чтобы статус синхронизировался, наверное. Надо глянуть, как два оф. клиента одновременно это разруливают.
