### ISSUE TITLE
Discord: после успешного логина нужно засерять поля логина и пароля в настройках

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4390]
Я залогинен в Дискорд через Миранду. Меняю в настройках логин и пароль (неважно, в сети протокол или нет, главное, что токен уже получен)

Результат:
1) логин меняется, но после следующего подключения протокола к сети логин возвращается взад
2) пароль меняется и сохраняется, но протокол подключается и с неверным паролем, ведь есть `AccessToken`

Предлагаю после того, как мы разок успешно влогинились и получили токен, засерять  эти поля.

Поля должны быть доступными лишь в 3 случаях
1) пока мы не влогинились и у нас нет токена (например, чтобы пользователь мог исправить опечатку в логине/пароле)
2) при нажатии кнопки "Log out", когда токен стирается
3) если пользователь сменил пароль через сайт. Как  я понимаю, в этом случае все токены сервер сразу инвалидирует и Миранда стирает токен из базы.

Во всех этих случаях токена в базе нет, вот пока его нет, поля учётных данных должны быть доступны. А как только токен в базе есть - засеряем.

**Comment by dartraiden** [comment]
На тестовом профиле засерилось, на боевом - нет.

Могу его дать.

**Comment by georgehazan** [comment]
Теперь вопрос будет в том, почему оно засерялось в другом случае 😁

**Comment by dartraiden** [comment]
Ты будешь смеяться, но теперь оно не засеряется на тестовом профиле, да...
