### ISSUE TITLE
Discord: не работает подгрузка истории чата с сервера

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4392]
Чатик на 3 человек.
Один (Миранда) выходит, стирает чатик из базы.
Владелец чатика добавляет этого мирандовода опять.

В Миранде жмём подгрузку с сервера.

```
61
‹
{"message": "\u041d\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043d\u044b\u0439 \u043a\u0430\u043d\u0430\u043b", "code": 10003}
[1:57:01 3554] [Discord_1] Gateway send: {"op":1,"d":6}
[1:57:01 2E90] [Discord_1] Got packet: buffer = 38, opcode = 1, headerSize = 2, final = 1, masked = 0
[1:57:01 2E90] [Discord_1] JSON received:
{"t":null,"s":null,"op":11,"d":null}
```

Ничего не подгрузилось.

При этом, если этот вновь прибывший сидит не с Миранды, а через оф. клиент, то историю он видит. Так что, проблема в Миранде.

**Comment by georgehazan** [comment]
Нормально там всё, прошлая история грузится с флагом "уже прочитано", так что если крутануть колесико в NewStory, то она исправно вылезет. Ну или поставить при открытии окна показывать не только непрочитанное, а предыдущие 10 событий, например.

**Comment by dartraiden** [comment]
У меня включена подгрузка последних 100. Но её не происходит.

**Comment by dartraiden** [comment]
Более того, история просто не грузится. У чата нет даже пункта меню "История". В базе её нет, она не грузится с сервера.
