### ISSUE TITLE
Discord: показывать, кто пригласил или выгнал участника

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4399]
Участник может попасть в чат сам (по пригласительной ссылке) или его может добавить владелец чата.
Аналогично и с покиданием чата: участник может выйти сам, либо его могут выгнать.

В Миранде это отображается одинаково: "username вышел из chatname" / "username вошёл в chatname". Без указания на то, сам он управился или с ним управился кто-то другой.

В официальном клиенте это отображается по-разному:

dartraiden покидает группу - сам ушёл
htgyoma удаляет dartraiden из группы - выгнали

Аналогично и со входом:

dartraiden вошел по ссылке-приглашению - сам пришёл
htgyoma добавляет dartraiden в группу - добавил владелец

**Comment by dartraiden** [comment]
"dartraiden removed dartraiden from the group"

Ну, технически это правда... но, может писать, что dartraiden ливнул, а не удалил самоё себя?

**Comment by georgehazan** [comment]
Нет, там всё жестко - отдельный код события на когда сам выходишь и когда тебя выносят
Может мы как-то неправильно покидаем комнату, не знаю
