### ISSUE TITLE
Discord: добавление и изгнание других людей из чата

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4400]
Не хватает двух возможностей:

1) чтобы можно было в никлисте щёлкнуть пкм по участнику и выгнать его. Как в Jabber пункт "выкинуть"

2) чтобы в меню канала (пкм по журналу) был пункт "пригласить". Оф. клиент позволяет приглашать лишь друзей. Так что, видимо, надо выводить некое окошко, где можно будет галочками выбрать друзей для приглашения.

**Comment by georgehazan** [comment]
У меня нет этих пунктов в меню
Нужны параметры запросов из веб-клиента
