### ISSUE TITLE
tabSRMM: настройка "добавлять к именам при автозавершении" действует лишь для первого ника

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4401]
<img width="528" alt="Miranda64_QcHVas9gKg" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/1be0fdd6-1f8d-40ed-b147-d0be77dded57">

Выставлено добавление двоеточия к нику. Кликаем дважды по нику в никлисте. Вставляется ник с двоеточием, как и указано. Теперь кликаем по другому нику. А он уже вставляется без двоеточия.

Аналогично и с автодополнением. Начинаем вводить в поле ввода ник, жмем `Tab`, ник автодополняется с двоеточием. Тут же начинаем вводить второй ник, жмем `Tab`, ник автодополняется без двоеточия.

Зачем в одном сообщении два ника? Например, хайлайтнуть двух юзеров разом.

**Comment by georgehazan** [comment]
и? двоеточие вставляется только один раз, по определению
хайлайт работает без двоеточия, ему это не надо
