### ISSUE TITLE
Discord: логин по номеру телефона

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4405]
Оф. клиент позволяет вместо почты в поле логина вводить номер телефона (при условии, что телефон привязан к учётке).

В остальном ничего не меняется: всё так же запрашивается постоянный пароль и 2FA.

**Comment by georgehazan** [comment]
Яннп, а что, в поле логина телефонный номер не канает?

**Comment by georgehazan** [comment]
А как бы запрос выцепить к серверу, который это делает?
