### ISSUE TITLE
Настройки Contacts/Ignore поместить в контекстное меню контактов

### ISSUE THREAD

**Issue by Deadooshka** [miranda-ng/miranda-ng#4413]
Сделать настройки игнорирования контакта и группового чата доступными из контекстного меню контакта и группового чата, чтобы не лазить каждый раз в `Options`. Это же касается всех подобных настроек со списком контактов. Например, Popups -> вкладка Contacts.

**Comment by georgehazan** [comment]
Для этого есть плагин MenuEx, который пихает в меню контакта кучу разного хлама, включая игнор.
