### ISSUE TITLE
Telegram: зависание при покидании канала во время загрузки истории

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4415]
Воспроизводится на тестовом профиле.

Захожу с телефона в канал https://t.me/black_library
Он появляется в Миранде
Вгружаю историю с сервера
Открываю этот канал, в NS потоком летят загружаемые события
ПКМ в журнале -> покинуть канал

Миранда зависает наглухо. Канал, впрочем, покидается (пропадает на телефоне). Но Миранду приходится пристрелить.
Было бы неплохо останавливать загрузку в таком случае (нет смысла продолжать грузить историю, раз пользователь хочет покинуть канал) и покидать канал.

**Comment by georgehazan** [comment]
сделать только загрузку предыдущих 500 событий?
