### ISSUE TITLE
Telegram: не выводятся IP-адреса в списке сессий

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4416]
Почему-то вместо IP пустота

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/bf95c956-9023-4ae5-9976-43b9cd7f91cd)

**Comment by georgehazan** [comment]
Да, больше в списке сессий IP-адрес не приходит, не знаю почему.
Легко проверяется по нетворк логу по ключевому слову sessions_

**Comment by dartraiden** [comment]
Тогда стоит убрать это поле из GUI.
