### ISSUE TITLE
Telegram: Миранда заявляет о поддержке голосовых вызовов и секретных чатов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4417]
В Telegram клиент может как-то заявить серверу о том, что он поддерживает, а что нет.

Например, мобильный клиент декларирует поддержку секретных чатов и звонков. А также позволяет это декларирование отключить крыжиками.

![photo_2024-05-12_22-54-31](https://github.com/miranda-ng/miranda-ng/assets/5046855/63513397-f008-4cb7-9b40-3906021607fb)

А вот сессия десктопного клиента (смотрим список сессий с той же мобилки)

![photo_2024-05-12_22-58-22](https://github.com/miranda-ng/miranda-ng/assets/5046855/5469714e-162f-4c9e-9932-a5294ed756f0)

Видим, что десктопный поддерживает лишь звонки (а секретные чаты он не умеет, это правда)

А теперь смотрим сессию Миранды (смотрим всё с той же мобилки)

![photo_2024-05-12_22-59-47](https://github.com/miranda-ng/miranda-ng/assets/5046855/af4e148e-ed9f-43f1-8b0f-534349ca9db8)

Миранда заявляет о поддержке секретных чатов и звонков. Хотя и не умеет ничего из перечисленного.

**Comment by dartraiden** [comment]
Собственно предлагаю, чтобы Миранда не декларировала поддержку этих вещей до тех пор, пока она реально их не начнёт поддерживать.

**Comment by georgehazan** [comment]
Так TDLIB, видимо, вполне способен это делать. А в настройках эти возможности отсутствуют
https://core.telegram.org/tdlib/options
