### ISSUE TITLE
Updates keep failing

### ISSUE THREAD

**Issue by bilogic** [miranda-ng/miranda-ng#4418]
### Expected behavior
What did you expect?
Updates should just succeed

### Actual behavior
What did you get instead?
![image](https://github.com/miranda-ng/miranda-ng/assets/946010/8d21fe2b-4d00-4277-8594-26040e86bc76)

### Does it work in stable version?
If you know in which dev build (or approximate date when) it was broken, it may be much easier to identify and fix the issue.
No

### Steps to reproduce that behavior
 * Provide step-by-step instructions so we can reproduce the issue (We can't fix what we can't reproduce).
 * Attach your VersionInfo.
 * Attach a crash report if you are experiencing crashes (It includes VersionInfo as well).
 * Attach a network log captured if you are experiencing connectivity issues.
 * If Miranda freezes, hangs up or consumes CPU, attach information obtained by Process Explorer tool.

Click the update, wait for it to fail. Start happening only in the last 6 months and each time it happens, I have to find the download link, download and manually update.

https://miranda-ng.org/distr/stable/

**Comment by georgehazan** [comment]
Error 32 = access violation, means that the files, which should be replaced, are locked by OS / antivirus / whatever
You can use tools like Process Explorer / System Informer to detect a process which holds lock on those files

**Comment by bilogic** [comment]
> Error 32 = access violation, means that the files, which should be replaced, are locked by OS / antivirus / whatever You can use tools like Process Explorer / System Informer to detect a process which holds lock on those files

Thanks,

1. Let's assume something was indeed locking miranda-ng
2. That something was sentient (plausible?) enough to immediately stop locking miranda-ng after I shut it down
3. I say that because I was able to replace the files everytime without any Error 32 stopping me
4. And all these years during the update, miranda-ng *does not shutdown first*
5. So, in my view, the likelihood of OS/antivirus/whatever else seems very low
6. Nonetheless I will dig into what is locking the files next time

**Comment by georgehazan** [comment]
It might be anything, including Windows Indexing service, for example, if you enabled search on that partition

**Comment by bilogic** [comment]
That still does not address why I never face any Error 32 after terminating miranda-ng. And I typically retry a few times before ignoring the update, the error 32 consistently recurs until I find time to implement my workaround. Assuming there is so much locking going on, I have never once encountered Error 32 when implementing my workaround.

Again, everything else seems low on the likelihood ranking. I would be more receptive if there is some reasonable explanation of 2, 3 and 4.
