### ISSUE TITLE
History++: проблема с выгрузкой плагина при открытом окне чата

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4419]
Если открыто окно чата и мы выгружаем плагин журнала, то в окне чата остаётся старый журнал, пока чат не будет переоткрыт. Так делают все журналы.

Но если при открытом окне чата выгрузить H++ (который был журналом), то чат превращается в голубое поле.

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/c4dc55d8-79bb-420e-bd06-1528124fbc23)

**Comment by georgehazan** [comment]
Всё правильно, когда плагин выгружается, то он прибивает все свои окошки, потому что у них оконная процедура смотрит в дельфи.  У встроенных журналов оконная процедура от RICHED50W, она не меняется, поэтому окно можно не убивать.
