### ISSUE TITLE
NewStory: добавить кнопку для удаления выбранных сообщений

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4429]
В окне истории кнопка с крестиком удаляет ВСЮ историю. Что несколько неожиданно.

Предлагаю сделать следующее:
1) крестик будет удалять выбранные сообщения, а не все
2) для удаления истории либо добавить ещё одну кнопку с другим значком, либо чтобы при ПКМ по крестику вылезало меню с пунктом "удалить всю историю".

**Comment by georgehazan** [comment]
Проблема в окне истории состоит в том, что там не сбрасывается выделение никак, потому что некуда отдать фокус. Соотв. стоит один раз воткнуть мышь в контрол - и каюк, удалить всю историю больше не выйдет.

**Comment by dartraiden** [comment]
<img width="583" alt="ZHfGhNeaXm" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/ac66f0e0-586a-4c3d-a14e-0ecf5a68cc24">
