### ISSUE TITLE
ICQ: deprecate support

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4438]
https://tass.ru/ekonomika/20897975

After June 26:

- [x] Remove ICQ-specific code

- [x] Remove ICQ-specific strings from langpack

- [x] Convert existing ICQ accounts to Dummy

**Comment by dartraiden** [comment]
Посмотрим, но, учитывая, что OAuth мы не можем, держать мертвый протокол смысла нет. 
Даже у фейсбука дела лучше: он не работает, но как только мы найдём, у кого подсмотреть код для работы с E2E, мы его заведём. А вот OAuth нет.

**Comment by SM-Sergey** [comment]
В любом случае, если официальный майл агент по телефону входит в некий аккаунт, то это есть штатно. И это способ вернуть ему функциональность как минимум для тех, у кого нету двух разных аккаунтов - миранда будет логиниться ровно туда же, куда и оф. клиент.

**Comment by SM-Sergey** [comment]
Июнь покажет, что будет с аськой. А оф. клиент агента уже прямо сейчас умеет логиниться по телефону и смс!

**Comment by dartraiden** [comment]
Всё верно. Войти по номеру телефона можно лишь в аську.
В MRA можно войти лишь по логину-паролю от почты (OAuth).

**Comment by SM-Sergey** [comment]
А, ну это да. Я то сначала разлогинивался из всех майлру для чистоты эксперимента.

Ну и в MRA можно все таки не только через OAuth, а и через их "самопальный" 2FA с доп-подтверждением с вводом последних цифр телефона, если он имеется в аккаунте, или через капчу, если нет.

**Comment by SM-Sergey** [comment]
Ну вот последняя новость звучит так:

> "Обращаем внимание, что в связи с закрытием ICQ **авторизация по номеру телефона** в сервисе станет недоступна с 26 июня 2024. Для того чтобы сохранить данные из вашего аккаунта Агент Mail.ru, скопируйте переписку и файлы на ваш компьютер. "

Так что, предположительно, авторизация в сервисе через майл.ру/ВК/госуслуги останется живой. Так что, "вскрыть" авторизацию в десктопном агенте (хотя бы 2FA с вводом четырех цифр номера телефона, чтобы не OAuth через ВК/Госуслуги) в аккаунт именно агента остается актуальной задачей.

**Comment by SM-Sergey** [comment]
Ну что. Кранты аське.
А MRA работает, и при этом даже перестала спрашивать 2FA, входит просто с паролем от е-майла.

**Comment by SM-Sergey** [comment]
B MRA стал просить привязаться к номеру телефона, чего раньше не было. Но пока работает и без привязки.
