### ISSUE TITLE
Сделать проверку истории на предмет отсутствующих файлов.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4441]
Это в связи с приближающейся кончиной ICQ.
Крайне нужна функция, которая пробегает по всей истории контакта в БД, анализирует события на то, есть ли в них файл, и, далее:
- если есть исходящий файл, включая "старый файлтрансфер", но отправленного файла нет на диске, то предпринимается попытка скачивания его с сервера, и если удачно, то он преобразуется в оффлайн файл. (неудачи будут из истории до серверного хранения файлов, да и из серверных файлов много совсем старых пропало де-факто)
- если в сообщении есть ссылка типа "http[s]/files.icq.net/xxxxxx", то это сообщение преобразуется в оффлайн файл и он скачивается, если проходит по фильтру автоскачивания.
- если это входящий оффлайн файл, но файла нет на диске, то он перепроверяется по фильтру автоскачивания, и если его проходит, то скачивается.
В некоторых контактах история содерит 200-300 тысяч сообщений, руками это всё не осилить.

И, самое главное, **обязательно**, при этом **не делается "Load Server History"**, чтобы исключить возможность прилетания стираний старых сообщений, чего почему-то по отдельным контактам бывает в достатке, хотя их автор ничего не стирал. Либо, если и делается, то с игнорированием удалений сообщений.

**Comment by SM-Sergey** [comment]
> уже. оно грузит все незагруженные файлы, какие только найдет

Нет! У меня сколько угодно вот таких записей, тысячи!

![2024-05-27 22_07_27-ElectroVoicer - history  212904 messages total](https://github.com/miranda-ng/miranda-ng/assets/34127439/eb18744e-17a3-4d35-b99e-296a9da859b0)

![2024-05-27 22_10_45-ElectroVoicer - history  212904 messages total](https://github.com/miranda-ng/miranda-ng/assets/34127439/b3afb4c2-e70c-40c6-83ba-9dc0c5acfe3b)

![2024-05-27 22_11_23-ElectroVoicer - history  212904 messages total](https://github.com/miranda-ng/miranda-ng/assets/34127439/9c731da5-6626-43f9-99a9-e0729fb6f69c)


Тут видно, что есть сообщения со ссылкой, и есть незагруженные оффлайн файлы (ограничений на автозагрузку у меня не стоит, там ноль)

А Load Server History делать нельзя! Поудаляется несколько тысяч сообщений, якобы удаленных на сервере (но пользователь их там не удалял).

**Comment by georgehazan** [comment]
> А Load Server History делать нельзя! Поудаляется несколько тысяч сообщений, якобы удаленных на сервере 

Ничего там не удаляется, только текст может замениться, если он менялся

**Comment by SM-Sergey** [comment]
Удаляется! С сервера прилетают именно удаления сообщений. Замена текста меня не волнует, таких мало.

**Comment by georgehazan** [comment]
Не удаляется. В коде загрузки истории вообще нет мыслей про удаление сообщений

**Comment by SM-Sergey** [comment]
Ну я не знаю как там в коде, а в истории куча сообщений заменяется на что-то типа "Message was deleted" или как-то так.

**Comment by SM-Sergey** [comment]
Вот так это выглядит после Load Server History сейчас:

![2024-05-27 23_06_33-Игорь - history  614 messages total](https://github.com/miranda-ng/miranda-ng/assets/34127439/ca831fc9-a5c5-4e6a-800f-a6f74c5b912a)

Хочется, чтобы это не происходило, а файлы все докачать / преобразовать из старых ссылок.

**Comment by SM-Sergey** [comment]
Хотя бы так - Load Server History с опцией "обрабатывать только сообщения с файлами".

**Comment by SM-Sergey** [comment]
Ну в общем, не работает. В истории есть много такого:

![2024-05-28 20_18_28-Игорь - history  5691 messages total](https://github.com/miranda-ng/miranda-ng/assets/34127439/d11edadc-6d3b-4fed-83f6-bc9d9b9a7f17)

Файл преобразован в оффлайн, но не загружен. Фильтр по размеру на автозагрузку = 0. Делаю лоад сервер хистори - файл все равно не загружен. Дабл-клик - файл загружается (но сломалась полоска загрузки в NS, и превьюшка не появляется до переоткрытия истории),

**Comment by georgehazan** [comment]
Поправмл, чтобы грузилось даже когда есть старое событие
