### ISSUE TITLE
Incorrect local name in ICQ session

### ISSUE THREAD

**Issue by irwir** [miranda-ng/miranda-ng#4442]
### Expected behavior
In ICQ message session tabSRMM used to show two names - the remote party's name and my local name correspondingly.

### Actual behavior
Both received and sent messages get the name of the remote party.
Colours are correct - bold red and bold grey, so the session is readable.

### Does it work in stable version?
Used to work; cannot tell when it got broken, but it was spotted months ago.
It was expected the bug would be fixed soon, but this never happened.

### Steps to reproduce that behavior
Using the current 64-bit nightly build in Windows 11.

**Comment by dartraiden** [comment]
ICQ will be closed on June 26
https://tass.ru/ekonomika/20897975

**Comment by irwir** [comment]
The bug could be related to other parts of Miranda too.

**Comment by georgehazan** [comment]
which message log plugin do you use? built-in? NewStory? h++?
post here a screenshot of Options - Message sessions - Log vievers

**Comment by irwir** [comment]
Nothing fancy at all, only standard plug-ins: https://snipboard.io/yQLZD4.jpg

**Comment by georgehazan** [comment]
> In ICQ message session tabSRMM used to show two names
so that was really tabSRMM or StdMsg?

**Comment by irwir** [comment]
My mistake. Now tabSRMMit is not even marked in the list:
https://snipboard.io/jJywcA.jpg
Other checkmarks are for avs, clist_modern and icq.

**Comment by georgehazan** [comment]
Yes, and now you need to enable the XMPP account to allow Miranda to cache its contacts
I wonder how can you open StdMsg window without enabling the protocol plugin

**Comment by irwir** [comment]
Sorry, I do not follow.
Jabber was never used and XMPP was unnecessary for ICQ protocol and network, which are enabled.
Nightly executable and plug-ins are updated regularly.

**Comment by irwir** [comment]
It appears that In database my account had nick, first name and last names copied from the remote contact.
More weird was that ICQ site also had changed first and last names, but now it was corrected.
Apparently, not a program bug; and the issue could be closed.
Thanks for the program and your help.
