### ISSUE TITLE
ICQ: Load Server History сломалась напрочь.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4443]
Делаю Load Server History для контакта. Во первых, все новые сообщения прилетают (в журнал) с текущей датой и временем, а не с их реальным. А во вторых не пишутся в БД. Нетлог полон SQLITE Error-ов. В конце концов миранда встает в "нот респондинг", и ее приходится убивать диспетчером задач. 
БД изначально проверена, в ней ошибок чекер не нашел. Сборка миранды на текущее время последняя ночная.

[netlog.zip](https://github.com/miranda-ng/miranda-ng/files/15461784/netlog.zip)

**Comment by SM-Sergey** [comment]
Вот на другом контакте другой нетлог
[netlog1.zip](https://github.com/miranda-ng/miranda-ng/files/15461811/netlog1.zip)

**Comment by SM-Sergey** [comment]
И после этого нельзя запустить миранду, так как после рестарта она уже сама делает Load Server History для этого контакта, и всё повторяется. То есть надо восстанавливать БД из архива.

**Comment by georgehazan** [comment]
При зависании не лог нужен, а снимок стека главного потока, либо с помощью студии, либо через Process Explorer
Это всё расписано тут - https://wiki.miranda-ng.org/index.php?title=Using_Process_Explorer_as_the_debugging_tool

**Comment by SM-Sergey** [comment]
Зависание - не всегда. Только на одном контакте. На других - летят сообщения в журнал с текущим временем, но в БД не пишутся. А перед зависанием, дополнительно, прилетело сообщение в другой контакт (в его журнал), которому Load History не делалось. Посмотреть его нельзя, ибо зависло.

Зависло где-то в смайладд...

[cstack.txt](https://github.com/miranda-ng/miranda-ng/files/15470093/cstack.txt)

Но я не думаю, что это причина бага, это по ходу "еще что-то".

**Comment by SM-Sergey** [comment]
... Так и есть. Отключение смайладд позволяет не зависнуть, но суть бага не меняется, все сообщения прилетают текущей датой и временем, а не их реальными, и нетлог набит теми же SQLITE error 19

**Comment by SM-Sergey** [comment]
В общем зависание фиг с ним, отключить смайладд на время перегрузки историй это логично. А баг критический.

**Comment by georgehazan** [comment]
> и нетлог набит теми же SQLITE error 19

это не ошибка, это duplicate (так работает вставка событий)

**Comment by georgehazan** [comment]
> На других - летят сообщения в журнал с текущим временем, но в БД не пишутся.

потому что они уже есть в базе, и они просто обновляются (но на экран выплевываются). если не открывать окно во время закачки, то она пойдет гораздо быстрее

**Comment by SM-Sergey** [comment]
Ошибка в том, что те события, которых нет, приходят текущей датой и временем, а не реальным серверным.
А в БД не записывалось из-за смайладда, после его отключения всё записывается.

**Comment by SM-Sergey** [comment]
А если историю втягивать с нуля, то все сообщения поголовно оказываются "Today, текущее время"
