### ISSUE TITLE
Some duplicate records were not removed from history

### ISSUE THREAD

**Issue by irwir** [miranda-ng/miranda-ng#4444]
### Expected behavior
When using 'Remove duplicate records" function all duplicate records were expected to be cleared.
That is, the ones with the same time and the same text.

### Actual behavior
Most duplicates were purged long ago, but some still remained.
For example, there are two records with time stamp ` 1527120428` and `Yes.` message text.
DB Browser for SQLite hints that one message is a 4-byte text, and the other is 5-byte (Unicode?) blob.
Blob has an additional null character appended, so it is "Yes.\0".

### Does it work in stable version?
No difference for stable and nightly builds.

### Steps to reproduce that behavior
The database was created for Miranda IM, it survived conversions for Unicode, then conversion for Miranda NG.
Hard to tell how to make this happen again.

**Comment by georgehazan** [comment]
It seems that you have programming skills, so you can execute the following query in you SQLITE Database Browser (or whatever you use):

`update events set data=concat(data, zeroblob(1)) where type=0 and data = rtrim(data);`

**Comment by irwir** [comment]
The condition `data = rtrim(data)` did not work here and had to be changed to
`cast(substr(data, -1, 1) as blob)!=zeroblob(1)`
or
`cast(substr(data, -1, 1) as char)!=char(0)`

Database checker deleted over 1000 records after making all texts null-terminated.
Thanks.
