### ISSUE TITLE
ICQ: некоторые картинки не грузятся

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4447]
Например, приветственное сообщение от сервера в Избранном

В оф. клиенте:

<img width="403" alt="mstsc_Eplk6rbaaa" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/e6b9419c-3473-4a1c-9191-d59d8d53aaa9">

В Миранде картинка осталась в виде нерабочей ссылки

<img width="507" alt="mstsc_lMwu0izVhw" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/63988027-1a4a-4dca-8cad-80063a0e6197">

**Comment by dartraiden** [comment]
Стикеры тоже не грузятся при загрузке истории с сервера

`13:41:53: STK{L8g8g000N4DJJfzLN5rnUh5fd103361ad   https://files.icq.net/get/L8g8g000QJdg7GKiqANGUy5fd103001ad cicq.org/s/happy_new}`

При подгрузке с сервера прилетело такое событие. Насколько понимаю, это должен был быть стикер.

**Comment by dartraiden** [comment]
Некоторые файлы всё ещё не грузятся.

<img width="349" alt="mstsc_5TP5wlzk5e" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/b34b39a0-298a-44a3-938a-97031744560b">

Могу дать профиль, на котором это хорошо отлаживается

**Comment by georgehazan** [comment]
Файлы из середины сообщения точно грузиться не будут, это встречается только в рекламных сообщениях от аськи. Все остальные попытки заслать файл помещают урл с файлом в начало сообщения
