### ISSUE TITLE
ICQ: Облачный файл не скачивается, если на диске уже существует файл с таким именем

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4449]
Вот есть такой файл.

![2024-06-04 15_46_21-ElectroVoicer (Offline)](https://github.com/miranda-ng/miranda-ng/assets/34127439/1aabb749-5467-4033-b2c8-d135fa467a8b)

там не картинка, архив с проектом. Вот на него можно хоть обкликаться, и в NS, и в табсах, и делать Copy URL, и Save As - полное молчание. Файл не грузится, в нетлоге ничего не происходит. При этом оф. клиент его загружает нормально.

**Comment by georgehazan** [comment]
А на диске этот файл есть?

**Comment by SM-Sergey** [comment]
Да, есть, но другого размера и из другого сообщения. А этот должен был переименоваться - стоит опция "If incoming file already exist = Rename (append "(1)", etc)

**Comment by SM-Sergey** [comment]
А зря переименовали то тикет.
Вот мне понаприсылали кучу - ровно так же не скачивается, хоть укликайся, и в нетлоге такой же молчок.

![2024-06-06 00_19_55-ElectroVoicer (Offline)](https://github.com/miranda-ng/miranda-ng/assets/34127439/b05f1b13-565e-41ec-89b3-1141a305b5f1)

**Comment by georgehazan** [comment]
> Я условно подозреваю, что это может быть связано с изменением формата хранения ID-а файла,

К-каким изменением?

**Comment by georgehazan** [comment]
@SM-Sergey щас соберу дев билд, посмотри, если всё ок, то перенесу в стаблю

**Comment by SM-Sergey** [comment]
Вроде ничего не поменялось... Не грузится, Copy URL не работает.

билд такой - там это уже есть?

Miranda NG Version: 0.96.6 alpha build #27275 (5b70baa326) x64
Build time: Thursday, June 6, 2024 16:27:08

**Comment by SM-Sergey** [comment]
Вот пример сообщения, на всякий случай.

[Uploading msg.json…]()

**Comment by georgehazan** [comment]
> Вроде ничего не поменялось... Не грузится, Copy URL не работает.

Для скачанных говносообщений ничего меняться не будет, надо стереть их локально и перезалить историю

**Comment by SM-Sergey** [comment]
А как их все найти-то при неработающих фильтрах в NS? Их же не одна сотня и не две в разных местах истории и в разных контактах.
И как стереть только локально, чтобы они с сервера не удалились?

**Comment by SM-Sergey** [comment]
Ну в общем вроде стертые и перегруженные файлы ОК. Но вопрос, как их всех найти среди многих сотен тысяч сообщений, открыт.

**Comment by SM-Sergey** [comment]
А можно автоматизировать? Если при Load Server History нет файла, но сообщение есть, то обновить сообщение в БД?

Но только что делать, если файл есть с тем же именем, но от более старого сообщения...

**Comment by dartraiden** [comment]
Я предлагал это в https://github.com/miranda-ng/miranda-ng/issues/4439#issuecomment-2132205489
По-видимому, невозможно

**Comment by SM-Sergey** [comment]
Спорно. В #4441 в последнем посте [georgehazan](https://github.com/georgehazan) сказал, что он это поправил, и файлы должны автозагружаться, когда есть событие, но нет файла. Но это также не работает.
