### ISSUE TITLE
Discord: Add Mobile status to Discord users

### ISSUE THREAD

**Issue by MP36ctrl** [miranda-ng/miranda-ng#4450]
A mobile user has a specific icon for when theyre online:
![image](https://github.com/miranda-ng/miranda-ng/assets/79648510/97515a49-293d-4310-978a-0935944438f6)
could this be implemented?

**Comment by georgehazan** [comment]
@MP36ctrl you'd need FingerPrint plugin to view clients' icons, also they are implemented for private channels only, not for guilds
