### ISSUE TITLE
При удалении контакта доступность опции "Удалить историю для всех" не зависит от PF4_DELETEFORALL

### ISSUE THREAD

**Issue by ElzorFox** [miranda-ng/miranda-ng#4453]
При наличии сервиса PS_EMPTY_SRV_HISTORY опция "Удалить историю для всех" активна для выбора, даже если у протокола нет капса PF4_DELETEFORALL.

**Comment by georgehazan** [comment]
У меня галка засерена в обоих диалогах: и очистки истории, и удаления контакта
