### ISSUE TITLE
Msg_Export: плагин использует нестандартную переменную %dbpath%

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4454]
`%dbpath%` раскрывается в путь к профилю. И работает лишь в Msg_Export, т.к. это его специфическая переменная.

Но у нас есть ядерная переменная `%miranda_userdata%`, которая делает ровно то же самое.

При этом, код, связанный с DbPath, непонятно как работает

```
/////////////////////////////////////////////////////////////////////
// Member Function : bReadMirandaDirAndPath
// Type            : Global
// Parameters      : None
// Returns         : void
// Description     : Used to set the internal path.
//                   Handles the reading from the mirandaboot.ini to get the %dbpath%

bool bReadMirandaDirAndPath()
{
	wchar_t szDBPath[MAX_PATH], tmp[MAX_PATH];
	wcsncpy_s(szDBPath, pszDbPathError, _TRUNCATE);
	PathToAbsoluteW(L"miranda32.exe", tmp);
	g_sMirandaPath = tmp;
	g_sMirandaPath.erase(g_sMirandaPath.find_last_of(L"\\"));
	Profile_GetPathW(MAX_PATH, szDBPath);
	g_sDBPath = szDBPath;
	Profile_GetNameW(MAX_PATH, szDBPath);
	g_sDBPath.append(L"\\").append(szDBPath);
	g_sDBPath.erase(g_sDBPath.size() - 4);
	return true;
}
```

А если у нас 64-разрядная инсталляция и никакой miranda32.exe нет?..

Предлагаю:
- выпилить всё из сорцов по слову `dbpath`
- переменную `%dbpath%` в сорцах заменить на `%miranda_userdata%`
- для обратной совместимости сделать alias с  `%dbpath%` на `%miranda_userdata%`

**Comment by dartraiden** [comment]
Можно ещё в диалоге настроек поменять? А то уже минимум один пользователь увидел эту %dbpath%, подумал, что она должна работать по всей миранде и обломался.

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/59788ab6-21a7-438a-bddc-e99bd734bf83)

**Comment by georgehazan** [comment]
MsgExport не оперирует мирандовскими переменными вообще, поэтому заменить это не получится
