### ISSUE TITLE
ICQ: сломалось удаление истории у собсеседника

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4455]
В какой-то момент работало, я так грохнул историю тестового контакта.

Сейчас пользователи возможно захотят подтереть историю перед закрытием сервиса, хотя, учитывая подментованность mail.ru, нет гарантий, что они действительно что-то удаляют.

**Comment by SM-Sergey** [comment]
Это не глюк, а отличная фича.

В их БД на серверах, для сервисов, имеющих право официально работать в России, имеется обязанность хранить всю переписку определенный немалый срок, несмотря на все стирания пользователями. Так что, это они нас, бесправных пользователей, ограничивают в возможности получить копию старой переписки, если ее захочет удалить другая сторона с целью скрыть неудобную для себя информацию, но для целей безопасности они сами смогут прочитать всё что им надо и когда им надо, и лет 5 еще как минимум.

Так что, делаем бэкапы БД, и чаще. А то вдруг еще сам сервис перед закрытием пришлет еще "удалить всё". Вообще, по логике, идеальный мессенджер с локальной БД должен делать так, как гитхаб - хранить всю историю. "Пользователь удалил/изменил сообщение" - и мелкий пунктик - "Просмотреть историю изменений".

**Comment by dartraiden** [comment]
Фича не фича, а пользователи просят перед закрытием возможность потереть историю, особенно с учётом, что многие собеседники давно неактивны/удалены и сами на своей стороне потереть не смогут.

**Comment by dartraiden** [comment]
> Так что, делаем бэкапы БД, и чаще.

Ты не вкурил. У нас потереть могут и трётся прекрасно. А вот мы не можем потереть у других.

**Comment by georgehazan** [comment]
убрал флажочек про стирание истории для всех, чтобы не вводить в заблуждение

**Comment by georgehazan** [comment]
@SM-Sergey щас соберу дев билд, посмотри, если всё ок, то перенесу в стаблю

**Comment by georgehazan** [comment]
там всё сложнее... удаление истории у собеседника работает для отдельных сообщений, но не работает для всей истории. как с этим быть - пока непонятно
