### ISSUE TITLE
ICQ: По следам #4441 - не работает скачивание файлов, для которых есть событие в БД, но нет файла.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4457]
В конце #4441 @georgehazan сказал, что добавил скачивание отсутствующих файлов при Load Server History для таких файлов, которых нет на диске, но есть событие в БД:

> Поправмл, чтобы грузилось даже когда есть старое событие

- Это не работает.
- Надо добавить еще и обновление сообщения в БД для таких случаев, так как оно там может быть криво записано.

**Comment by georgehazan** [comment]
1. это работает
2. если в событие записался мусор, то оживить его уже не удастся. Надо стереть событие у себя в профиле (но не на сервере) и заново перезакачать историю

**Comment by SM-Sergey** [comment]
> это работает

Не работает! В тех же примерах из #4441 ничего не догрузилось после Load server history.

![2024-06-07 13_14_28-Игорь - history  5691 messages total](https://github.com/miranda-ng/miranda-ng/assets/34127439/9b3f5815-ad31-45a7-85d4-fc1528d1ab0e)

После двойного клика по сообщению в NS - файл загрузился. То есть сообщение не поломано было.


> если в событие записался мусор, то оживить его уже не удастся. Надо стереть событие у себя в профиле (но не на сервере) и заново перезакачать историю

Ну вот как это сделать? Если в БД больше миллиона сообщений, а до 26 июня осталось две недели? Подскажите пожалуйста способ поиска их, если невозможно их автообновление.

**Comment by SM-Sergey** [comment]
Ну или в ДБ чекере, что ли, сделайте пожалуйста пришибалку бракованных сообщений с файлами, с формированием списка контактов, которым надо перегрузить историю...
