### ISSUE TITLE
IEView: Template Does not apply to Groupchats

### ISSUE THREAD

**Issue by MP36ctrl** [miranda-ng/miranda-ng#4458]
### Expected behavior
What did you expect?
For IEView Theme to Apply
### Actual behavior
What did you get instead?
The compat mode 
### Does it work in stable version?
![image](https://github.com/miranda-ng/miranda-ng/assets/79648510/e7b9d14a-faa2-43f9-97c7-f2ea8174d454)

**Comment by MP36ctrl** [comment]
Forgot to mention, this bug happens on v0.96.6 alpha build #274304 (004f3d1f49) 
Its been like this for a while

**Comment by georgehazan** [comment]
> What did you get instead?
> The compat mode

Not quite... the settings for group chats are also gotten from the first tab. you can change the theme for a message log, and it will be applied for all group chats either.

**Comment by MP36ctrl** [comment]
Compat mode is not selected anywhere yet it decides to use it anyway
groupchat tab:
![image](https://github.com/miranda-ng/miranda-ng/assets/79648510/4a51141d-ffc9-4aab-8e21-b52193951776)
Message logtab:
![image](https://github.com/miranda-ng/miranda-ng/assets/79648510/8c76df1c-4a64-457f-8120-f79eb63f6374)
![image](https://github.com/miranda-ng/miranda-ng/assets/79648510/48a2c94c-41f7-4dac-9513-163f7e882c85)
