### ISSUE TITLE
PluginUpdater пытается проверить обновления снова и снова

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4460]
Включена проверка обновлений при старте и каждый час. Включены попапы апдейтера про ошибки обновления.

Также на сервере обновления приторможены, возможно, это вызывает описанный ниже баг

Ожидание: при старте Миранды вылезет попап, что обновления приторможены (проверка при старте), затем снова вылезет через час (проверка каждый час).

Реальность: каждую минуту Миранда пытается проверить обновления и вылезает попап.

**Comment by georgehazan** [comment]
даже не знаю, может ты как-то через прокси пытаешься это сгрузить как-то?
давай нетворк лог делать, у меня всё штатно

**Comment by tamr** [comment]
У меня также. В нетлоге ничего странного, просто выдаёт 404 для hashes.zip и саму html страницы перед этим. Отключил пока автопроверку обновлений.
