### ISSUE TITLE
PluginUpdater:Updates are temporarily disabled

### ISSUE THREAD

**Issue by MP36ctrl** [miranda-ng/miranda-ng#4463]
![image](https://github.com/miranda-ng/miranda-ng/assets/79648510/e39d064c-a4c4-48aa-a4e6-df1a8ceceb45)

This will not let me download updates or available plugins
Happening on:
Miranda NG Version: 0.96.6 alpha build #27278 (6ac39390bc) x64

This is happening on multiple miranda clients

**Comment by georgehazan** [comment]
yes, they are temporarily disabled
that was intentional
