### ISSUE TITLE
Telegram: не удаётся загрузить сообщение, удалённое локально

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4469]
Загружаю в Миранду историю нашего тестового чатика.
Удаляю (ПКМ в логе) чьё-то сообщение со снятыми галками

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/d3a79260-979f-4989-8d45-9515db736507)

Таким образом, сообщение стирается из базы, но не с сервера.

Дёргаю загрузку истории с сервера.

Ожидание: должно вгрузиться то удалённое сообщение, ведь в базе его нет, а на сервере есть,

Реальность: оно не вгружается. То есть, если я стёр из базы конкретное сообщение, я его уже не могу вгрузить с сервера.

**Comment by georgehazan** [comment]
> Реальность: оно не вгружается.

Оно реально не вгружается, просто не приходит с сервера (посмотрел в нетворк лог). Не знаю, почему так

**Comment by Bumerangas** [comment]
Same problem very often don`t receiving messages. Message not popup, can see message just if manualy open message box and user showing as online.
