### ISSUE TITLE
ICQ: при создании учётной записи в раздел CList почему-то записывается MyHandle

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4472]
Чистый профиль без учёток

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/51258ef8-f757-4bfe-8cee-e19796f7c5bd)

Добавляем учётку ICQ и выводим её в онлайн

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/7697b3dc-a28d-4629-85fe-f4643b5292d4)

Почему-то в раздел CList добавляются ключи MyHandle и NotOnList.

Такое ощущение, что это ключи для /Контакты/<контакт>/CList, но по ошибке они улетают в глобальный /CList

**Comment by georgehazan** [comment]
нет, это когда парсится Избранное, потому что для него hContact == 0
