### ISSUE TITLE
Discord: Not all channels are loaded

### ISSUE THREAD

**Issue by AndyScull** [miranda-ng/miranda-ng#4476]
Hello,
so the problem I encountered is that after joining a community server I cannot see it's announcement  channels in Miranda. All other channels seems to be OK, but specifically two channels marked as announcement type aren't there in the list.
I just wanted to have these specfic channels to keep track of patch notes and such.

**Comment by dartraiden** [comment]
Check if these groups are available in Options → Contacts → Ignore. If they are there and have the checkboxes on the left unchecked, enable them.

**Comment by georgehazan** [comment]
@AndyScull if I can join this guild, tell me its name or invite url, if not - make a network log of login till the moment when its info is fetched

**Comment by AndyScull** [comment]
The actual server is for Shop Legends, invite link: https://discord.gg/5q9dbYHMbG.
I don't know if direct link is needed, it's https://discord.com/channels/854927823331131402/

I checked first Contacts/Ignore, just in case I missed those channels before, nope, they aren't in there.
Saved network log for discord connection, so far found that there is a mention of these channels.
From URLs I understand that channel's ids are: 'announcements' is 854927823331131404, 'patch-notes' is 867711362247688222, they are both found in network log:
`{"muted":false,"mute_config":null,"message_notifications":0,"flags":4096,"collapsed":false,"channel_id":"854927823331131404"}
{"muted":false,"mute_config":null,"message_notifications":0,"flags":4096,"collapsed":false,"channel_id":"854927823331131404"}
`
[miranda.log](https://github.com/user-attachments/files/15931834/miranda.log)

So I totally don't know why I am not seeing them in contacts list or ignore list, it seems they are fetched from server and then dropped?

**Comment by georgehazan** [comment]
Thanks, I'll look at this problem. Miranda calculates the effective rights for each channel and hides non-available channels, maybe smth went wrong with this algorythm

**Comment by georgehazan** [comment]
Well, what can I say... Discord contradicts to their own documentation, dunno what to do with it

**Comment by georgehazan** [comment]
@AndyScull finally fixed, will be available in the next dev build
