### ISSUE TITLE
ICQ: запретить/остановить автоматическую загрузку истории с сервера

### ISSUE THREAD

**Issue by Abdragiz** [miranda-ng/miranda-ng#4478]
При входе в ICQ сразу начинается автоматическая загрузка истории сообщений с сервера. При этом непонятно как остановить начатую загрузку, как заставить миранду грузить историю выбранного чата.

**Comment by Abdragiz** [comment]
Причем каждый раз история грузится с нуля

**Comment by dartraiden** [comment]
>  При этом непонятно как остановить начатую загрузку

Завершить работу программы

> как заставить миранду грузить историю выбранного чата

ПКМ по чату → Загрузить историю

**Comment by georgehazan** [comment]
> При входе в ICQ сразу начинается автоматическая загрузка истории сообщений с сервера.

Автоматически грузятся пропущенные сообщения для контактов, у которых patchVersion отличается от присланных с сервера. При этом грузится только пропущенная история для сообщений, учитывая всё загруженное ранее (по LastMsgId).

> При этом непонятно как остановить начатую загрузку

Прописать в контакт LastMsgId согласно присланному числу с сервера.

**Comment by dartraiden** [comment]
Вопрос в другом: если эти контакты только что прилетели, их не было в базе, у них LastMsgId  пустой. Раз он пустой, он должен просто присвоится.

**Comment by dartraiden** [comment]
Удалось повторить, но не для приватов, а для групчата.

Иногда, если перетащить чат в другую группу, он вместе этого выбрасывается в корневую группу. Это любимое аськино развлечение: иногда сервер может упереться рогом и отказаться перемещать.

**Comment by georgehazan** [comment]
> Именно в этот момент, когда сервер начал козлить, у чата начинает сливаться история.

За три дня до закрытия протокола никто это фиксить не будет всё равно.
