### ISSUE TITLE
Discord: Guilds option unuseable thanks to alot of servers having to go online

### ISSUE THREAD

**Issue by MP36ctrl** [miranda-ng/miranda-ng#4481]
Miranda will lag thanks to the fact that 700 servers have to go online

**Comment by georgehazan** [comment]
@MP36ctrl which option?

**Comment by MP36ctrl** [comment]
![image](https://github.com/miranda-ng/miranda-ng/assets/79648510/c6d6dbe8-406d-400c-9cbc-edfd2102bb5d)

**Comment by MP36ctrl** [comment]
@georgehazan is there a solution to this?

**Comment by georgehazan** [comment]
Dunno, need some spare time to meditate on this

**Comment by MP36ctrl** [comment]
I think it should be redone with the irc method personally, i posted a concept explaining how it could work

**Comment by georgehazan** [comment]
@MP36ctrl okay, I dropped a look at this problem, if this options is disabled, Miranda doesn't even try to create any channels, so you can freely remove them from your profile, they won't be re-enabled
