### ISSUE TITLE
Telegram messages

### ISSUE THREAD

**Issue by Bumerangas** [miranda-ng/miranda-ng#4485]
Very often don`t receiving messages. Message not popup, can see message just if manualy open message box. Sender showing as online just not popup message box.

**Comment by Bumerangas** [comment]
Do you need screens how i can`t receive message? :) on web i can see new messages but mirranda not showing.

**Comment by georgehazan** [comment]
> Do you need screens how i can`t receive message?

No, Miranda has network logs for this case, core + TG + specify which message is missing
It's described in our Wiki: https://wiki.miranda-ng.org/index.php?title=Network_log
