### ISSUE TITLE
User notes copy problem

### ISSUE THREAD

**Issue by Bumerangas** [miranda-ng/miranda-ng#4486]
If notes have new lines made with CTRL+ENTER, like:

Test

Test2

So now if i select just Test2 and press right mouse button + copy and after paste somethere it paste anyway full note, not just selected part of text(Test2), so i can not copy just selected text.

**Comment by georgehazan** [comment]
а можно еще раз и по-русски? ни хрена не понятно, о чем идет речь, и по возможности со скринами

**Comment by Bumerangas** [comment]
<img width="329" alt="Untitled" src="https://github.com/miranda-ng/miranda-ng/assets/46533189/a3e32c36-b5e3-4966-b5f8-2da55513fafc">
<img width="301" alt="Untitled2" src="https://github.com/miranda-ng/miranda-ng/assets/46533189/73e834be-0236-43b8-849f-037763656d24">

**Comment by dartraiden** [comment]
1) Cannot reproduce, all OK for me...

2) I suggest to remove this feature. There is very strange code there.

Use user info dialog to edit notes (right-click on contact in contact list -> Info -> Note)

**Comment by dartraiden** [comment]
Reproduced sucessfully...

Crtl+C =OK
Mouse = not OK

**Comment by Bumerangas** [comment]
Very good function, better remove lot of notifications and visual options.

**Comment by Bumerangas** [comment]
Very good function, better remove lot of notifications, visual, menu options.

Ofcourse best of all build from 0 new client just to hard i think, you have good developments :)

**Comment by georgehazan** [comment]
> I suggest to remove this feature. There is very strange code there.

Agreed. No notes - no problems

**Comment by dartraiden** [comment]
Technically, notes will not go anywhere, they will just now be accessed through the contact info.
