### ISSUE TITLE
ICQ: проблема Load Server History

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4490]
Остался день... А есть серьезная проблема.
Если оборвалась связь, и произошел переконнект по кипстатусу или вручную, то лоад сервер хистори не работает с записью в логе:

{"status": {"code": 40200, "reason": "tokencheck() failure: 40004[Bad auth]"}, "method": "getUserInfo", "reqId": "667a8083-7047-471b-a425-fe1d77de8658", "results": {}}

Требуется перезапуск всей миранды, после чего лоад хистори опять работает, и опять до срыва соединения.

**Comment by georgehazan** [comment]
отправил на сервер фикс

**Comment by SM-Sergey** [comment]
Да, спасибо, все заработало
