### ISSUE TITLE
NewStory: Опять проклятый скроллинг.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4491]
На больших и очень больших историях:
1) Если нажать PgUp и держать, то в какой-то момент все встает, перестают работать и клики в окно, и иной скроллинг.
2) Если таскать за движок, то возобновились старые глюки - то он куда-то отскакивает сам, а в конце концов все окно переклинивает, и там начинаются проблемы с отображением, или все сообщения пустые, или кракозябры в виде исходных кодов сообщений.

**Comment by georgehazan** [comment]
ну так небось хэндлы улетели в небеса опять? 
посмотри, чему равно количество обычных и GUI handles

**Comment by SM-Sergey** [comment]
Ща, доберусь до компа, проверю.
Но ведь эта вся бодяга с хэндлами была вылечено напрочь, и давно.

**Comment by SM-Sergey** [comment]
Да, так и есть. Опять GDI-объекты. Но с чего бы, если тогда всё вычистили и было всё красиво и работоспособно?

**Comment by SM-Sergey** [comment]
На всякий случай - последний фикс, который прибил утечку объектов гди, был 5fee2a9 - там сделали рисование иконок "вручную" вместо создания объекта для каждой.

**Comment by georgehazan** [comment]
> Но с чего бы, если тогда всё вычистили и было всё красиво и работоспособно?

С тех пор мы перешли на HTML, который с точки зрения утечек вообще никто не тестил

**Comment by SM-Sergey** [comment]
А это... Исправление то будет? Почему закрыли тикет? Ньюстори-то не работает, по сути - только для коротких копаний в мелкоисториях...

**Comment by georgehazan** [comment]
> Исправление то будет?

Непременно, но там надо добить еще пару вещей. Как только я полностью устаканю HTML-модель для NewStory, можно будет почистить всё это
