### ISSUE TITLE
Проблемы с конвертацией не совсем старой БД.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4492]
Беру архив 17 января 2022 (полный, всей папки профиля). Делаю из него профиль "test" с переименовыванием папки в test и БД в test.dat. Миранда запускается, без предварительных вопросов конвертирует БД, после чего умирает, не открывшись, вот так:

![2024-06-25 14_01_49-PID_ 19732 - WinDbg 1 2402 24001 0](https://github.com/miranda-ng/miranda-ng/assets/34127439/ff883d1c-f95d-4239-bdf4-618f298dc735)

Любые дальнейшие запуски приводят к той же смерти.

Если взять архив от 11 января 2020 - никаких проблем, перед конвертацией базы задают вопрос, конвертация проходит успешно, все работает. Но там был не SQLite, а MDBX.

Если взять архив до-NG (2017 года) - там dbx mmap driver - тоже все отлично, сначала спрашивают, что старый формат, потом конвертация, потом всё работает.

**Comment by georgehazan** [comment]
Надо смотреть id события, на котором всё валится, а потом запустить его текст сюда

**Comment by SM-Sergey** [comment]
Хм. А как это физически сделать? Я же не исходник собираю и отлаживаю, я просто из-под windbg краш отловил

**Comment by georgehazan** [comment]
Например, студию применить. Винда же есть со студией? Дальше оно по отладочным символам всё само найдет

**Comment by SM-Sergey** [comment]
Есть, собственно windbg это тот же отладчик. Но ведь для этого надо ставить точку останова в исходнике? Или есть другой способ? Там же только ассемблерный код виден. Я хоть в нем и понимаю, но это сложно, въехать где и когда в каких регистрах ссылка на нужный тект.

**Comment by georgehazan** [comment]
> Но ведь для этого надо ставить точку останова в исходнике?

Оно же крашится? Значит, не надо точку ставить, надо скачать символы для миранды и отмотать по стеку наверх, а там сразу id события будет

**Comment by SM-Sergey** [comment]
ща. я пробую первый способ, но в миранде после вчерашнего обновления несоответствие libjson либы и пдб. Обновлюсь...

**Comment by SM-Sergey** [comment]
Параметры, переданные в InitEvents оно не видит:

![2024-06-26 16_39_33-PID_ 12440 - WinDbg 1 2402 24001 0](https://github.com/miranda-ng/miranda-ng/assets/34127439/148a3c8c-70e1-4ee6-bfcb-799f0ecd4d35)

Зато можно поглядеть на локальные переменные в mir_app!DB::FILE_BLOB::write  :
![2024-06-26 16_44_14-](https://github.com/miranda-ng/miranda-ng/assets/34127439/494b214f-806d-4471-8216-f41bd33ed699)

и в Dbx_sqlite!CDbxSQLite::InitEvents+0x199() :
![2024-06-26 16_46_00-](https://github.com/miranda-ng/miranda-ng/assets/34127439/f09e91a7-a7fa-4cee-adf7-d2b36e3dc8c2)

Это может помочь?

**Comment by SM-Sergey** [comment]
... Вот что в базе. Я так понимаю, на первом же он и упал (hEvent == 0x54ff
![2024-06-26 17_02_48-SQLiteStudio (3 4 4) -  Редактор SQL 1](https://github.com/miranda-ng/miranda-ng/assets/34127439/a2a893aa-f5bd-4112-8921-cb983cfb8b99)

**Comment by SM-Sergey** [comment]
А так было в архивной БД до конвертации

![2024-06-26 17_05_44-SQLiteStudio (3 4 4) -  Редактор SQL 1](https://github.com/miranda-ng/miranda-ng/assets/34127439/47c9275a-5da0-4026-8a0a-9e15e90ac43e)

**Comment by georgehazan** [comment]
ща попробую себе это заколотить, посмотрим

**Comment by SM-Sergey** [comment]
Блоб, если что, вот
00 00 00 00 55 73 65 72 73 5c 56 2e 56 2e 50 2e 
4e 65 74 5c 44 65 73 6b 74 6f 70 5c 6c 61 62 5f 
32 2e 7a 69 70 00 c1 e5 e7 20 ee ef e8 f1 e0 ed 
e8 ff 00 

строка - вот
21759	14	ICQ	1331477044	1002	1028			1

**Comment by georgehazan** [comment]
можно обновиться и пробовать

**Comment by SM-Sergey** [comment]
Всё ОК.
