### ISSUE TITLE
MRA: удалить больше ICQ-специфичного

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4495]
\protocols\ICQ-WIM\proto_icq - иконки ICQ больше не нужно собирать

**Comment by SM-Sergey** [comment]
>  а теперь и официальный тоже прекратил поддержку

не факт. Теперь официальный хочет номер телефона с подтверждением его по смс, но это не работает пока. Так что, вход по телефону может и сохранится, тут надо подождать

**Comment by dartraiden** [comment]
Ok, пусть живёт.
