### ISSUE TITLE
Spamotron: прекратить поддержку или доработать

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4497]
Плагин заточен исключительно под ICQ, другие учётки (в т.ч. MRA) ему не подходят - он специально не позволяет их выбрать.

Поскольку учёток ICQ у нас больше не может быть, плагин бесполезен. Допиливать его чисто под MRA - овчинка выделки не стоит. Либо нужно добавить поддержку всех протоколов, либо в топку.

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/bc3de456-2cb1-4f72-9aa2-947652eab87e)

**Comment by georgehazan** [comment]
Действительно заточен на ICQ, причем на старый ICQ c UIN.
Выбрасываем
