### ISSUE TITLE
Не пишутся сообщения в историю.

### ISSUE THREAD

**Issue by SUGHuser** [miranda-ng/miranda-ng#4502]
Если собеседник использует урезанную версию XMPP клиента , например Connect Messanger , YaxIM или что-то подобное , при этом клиент не соответсвует чётко к XMPP протоколу , то мы видим следующее :

пример  работы QIP 2012 

test@user.com
test@client.com

мы общаемся и ситуация такая 

test@user.com (00:00:00 01/01/2024) 
привет
test@client.com  (00:00:05 01/01/2024) 
привет
test@user.com  (00:00:15 01/01/2024) 
что делаешь ?
test@client.com  (00:00:30 01/01/2024) 
читаю книгу
test@user.com  (00:00:45 01/01/2024) 
какую книгу читаешь ?
test@client.com  (00:01:00 01/01/2024) 
про ремонт компьютеров

при этом , в историй QIP у таких клиентов пишет  следующее :

"Сервисное сообщение (00:00:03 01/01/2024) 
Ошибка доставки сообщения:
Ошибка 403: Запрещено посылать приватные сообщения"

и таких сообщений много... но в истории видно что переписка ведётся и видно что пишем мы и что отвечают нам

теперь точно такой же клиент , только используем миранду... что мы видим :

отправляемое

test@user.com (00:00:00 01/01/2024) 
привет
ещё , отмена , отправить позже
test@client.com  (00:00:05 01/01/2024) 
привет
test@user.com  (00:00:15 01/01/2024) 
что делаешь ?
ещё , отмена , отправить позже
test@client.com  (00:00:30 01/01/2024) 
читаю книгу
test@user.com  (00:00:45 01/01/2024) 
какую книгу читаешь ?
ещё , отмена , отправить позже
test@client.com  (00:01:00 01/01/2024) 
про ремонт компьютеров

в истории

test@client.com  (00:00:05 01/01/2024) 
привет
test@client.com  (00:00:30 01/01/2024) 
читаю книгу
test@client.com  (00:01:00 01/01/2024) 
про ремонт компьютеров

то есть , из-за не полного соответствия клиента протоколу , в истории просто нет сообщений которые мы писали.

**Comment by georgehazan** [comment]
1. Неподтвержденные сообщения и не должны записываться в историю.
2. Если клиент не поддерживает доставку уведомлений, то надо в настройках жабера выключить первую галку в разделе "Advanced" про ХЕР-0184

**Comment by SUGHuser** [comment]
А это тоже не помогает

**Comment by SUGHuser** [comment]
Разобрался ) врооде работает )
