### ISSUE TITLE
Очень хочется изменить логику метаконтактов и добавить метавкладки

### ISSUE THREAD

**Issue by SUGHuser** [miranda-ng/miranda-ng#4503]
Очень хочется чтоб метаконтакты в миранде имели следующий вид

![10000000-1](https://github.com/miranda-ng/miranda-ng/assets/160612271/8a670e56-1691-44cc-9882-b8e0c7f2a4f3)
во вкладке контакт-листа
![10000000-0](https://github.com/miranda-ng/miranda-ng/assets/160612271/8291f667-78b5-4698-a2af-babf2bb4895e)
в окне сообщений

сейчас же , при обьединении метаконтактов и написании им , мы имеем столько вкладок , сколько субконтактов в метаконтакте , это не удобно , пожалуйста , добавьте метавкладки и  как сделано в QIP-е )

**Comment by SUGHuser** [comment]
В миранде пока сделано так :
![Screenshot_3170](https://github.com/miranda-ng/miranda-ng/assets/160612271/821b95bd-4dc6-470b-a562-b845e216b9ab)
а сли мы говорим о окне диалога то так :
![Screenshot_3171](https://github.com/miranda-ng/miranda-ng/assets/160612271/0dc2d4dc-933c-4321-b51f-e6beced461a8)
хочется чтоб это было не в разделе пользователь -> субконтакты , агде нибудь как например  здесь :
![Screenshot_3172](https://github.com/miranda-ng/miranda-ng/assets/160612271/4eddabd1-167e-4dad-9ee8-6425f3102f12)
я думаю это более логичное размещение будет )

**Comment by georgehazan** [comment]
В миранде "метавкладки" появились задолго до появления QIP. 
Сабы контролируются через лампочку в нижнем правом углу

**Comment by SUGHuser** [comment]
Спасибо ) всё удобнее чем я думал ) впрочем , как и с запиниванием табов )
