### ISSUE TITLE
VK: несовместимость TabSRMM  и NewStory

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4504]
Включил галку превьюшек для NewStory в настройках VK. Как результат, в истории я вижу превьюшки.

![2024-06-27 22_01_08-Ева Маркова - history  148 messages total](https://github.com/miranda-ng/miranda-ng/assets/34127439/ac7f8a58-cd61-498e-98ef-c58aa13c6be3)

Но в журнале я перестал видеть всё вообще. Журнал - встроенный табсов. Там даже ссылки нет, которую кликнуть можно.

![2024-06-27 22_00_45-Ева Маркова (Offline)](https://github.com/miranda-ng/miranda-ng/assets/34127439/61cd599d-133e-402d-af91-b0637e0e4d4a)

Нужно, чтобы журнал не конфликтовал с историей, в истории были бы превьюшки, но и в журнале можно было бы кликнуть на ссылку и увидеть содержимое, не открывая историю. И не заставляя пользователя ставить ньюстори  для журнала. Хотя бы, чтобы в журнале была просто ссылка в ВК.

**Comment by SM-Sergey** [comment]
В идеале надо поддержать оффлайн файлы, как это было в ICQ

**Comment by ElzorFox** [comment]
1. Включи логом в TabSMRR NewStory и будет счастье.
2. Есть событие-сообщение в базе, у него одно единственное содержимое для всего. Разные логи обрабатывают и отображают это содержимое по-разному в силу своих возможностей. Технически не сделать так, чтобы одновременно для лога NewStory было одно содержимое, а для лога табсов - другое.
3. Все дальнейшие бантики в вк будут рисоваться только для NS - моя личная принципиальная позиция. Если они по какой-то случайности будут нормально отображаться в других логах - ничего против не имею. Все эти красивости можно отключить в настройках вк-плагина и перегрузить историю. Соответственно оно будет более-менее смотреться в логе табса, но и в логе NS никакой графики не будет.

Закрываю, ибо не баг.

**Comment by SM-Sergey** [comment]
> Включи логом в TabSMRR NewStory и будет счастье.

Он пока плохо работоспособен, в нем утечка GDI-объектов, как минимум. Так что, увы, но включать его журналом пока рано.

**Comment by georgehazan** [comment]
> Он пока плохо работоспособен, в нем утечка GDI-объектов, как минимум.

Ничего, для журнала пойдет
