### ISSUE TITLE
Discord: Fix for guild implementation concept

### ISSUE THREAD

**Issue by MP36ctrl** [miranda-ng/miranda-ng#4505]
Use the IRC Implementation:

![image](https://github.com/miranda-ng/miranda-ng/assets/79648510/965f367b-74ce-4415-8cd6-ed5841094c6a)
This could be used to access the guilds

![image](https://github.com/miranda-ng/miranda-ng/assets/79648510/325bc035-9aab-4ece-91e8-29eb53b7867d)
The channel list can be the same but with the addition of the guild dropdown to switch between guilds

**Comment by georgehazan** [comment]
no, that's not possible due to the nature of Discord channels (they share the user list)
you can hide unused channels or mute them
