### ISSUE TITLE
TabSRMM: поддержать ссылки типа file://

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4506]
Ссылки типа file:// в табсах не показываются как ссылки - их нельзя кликнуть.

![2024-06-27 22_00_45-Ева Маркова (Offline)](https://github.com/miranda-ng/miranda-ng/assets/34127439/4f653783-a239-43bc-b81e-6da2cf9e1895)

Да и обычная ссылка типа https:// почему-то тоже не отобразилась ссылкой.

Хотя, скорее это баг, а не запрос фичи. Похоже, что после "=" без пробела не работает детект ссылок как класс.

Это всё глючит, если в VK включить совместимоть с NS

**Comment by georgehazan** [comment]
В стандартном журнале табсов миранда вообще не принимает участия в разборе ссылок, там стоит ES_URLAUTODETECT в ричедите
