### ISSUE TITLE
Clist_modern: проблемы с перетаскиванием групп

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4513]
Отключаем все учётки, чтобы в клисте не было контактов. Это важно. 
Итого, у нас ~~две шлюхи и старый пи.....~~ ноль контактов и 3 пустые группы

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/90c5d226-c70a-4c7f-b49e-e2a48db88e78)

# Баг 1

Хватаем группу 1 мышкой и пытаемся её перетащить в конец списка, чтобы она стала последней (2-3-1). Ничего не происходит, при отпускании мышки группа никуда не перемещается.

![mstsc_5MOLBAFUAq](https://github.com/miranda-ng/miranda-ng/assets/5046855/41c084b5-0131-45be-87f8-536f886ef5d8)

# Баг 2

Действуем как и раньше, но первую группу перемещаем не после третьей, а внутрь третьей. Результат тот же - первая группа никуда не переместилась.

# Баг 3

Хватаем группу 1 мышкой и пытаемся её перетащить, чтобы она встала после группы 2 (2-1-3).
Результат: она встаёт в самый конец

![mstsc_Nf4Bieyy20](https://github.com/miranda-ng/miranda-ng/assets/5046855/8ca14f04-85f2-423c-b7d7-7b3ef446006b)

# Баг 4
Помещаем третью группу во вторую

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/abcc79e0-1078-4770-9136-73657000f0b2)

Теперь мы хотим эту группу 3 вытащить на уровень выше, чтобы она стала одной из "полноценных" групп, как раньше

1) если мышкой поставить эту подгруппу ПЕРЕД первой группой, то она встанет ПОСЛЕ первой группы

![mstsc_fvpnt8AbP4](https://github.com/miranda-ng/miranda-ng/assets/5046855/573f3cc7-02a2-4554-a3e9-f78bffcf6b13)

2) если мышкой поставить эту подгруппу между первой и второй, то она встанет в конец

3) если мышкой поставить эту подгруппу в конец, то она встанет первой

Т.е. какое-то закольцованное смещение на +1

# Баг 5

Снова три одноуровневые группы, в третьей один контакт

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/69c313e6-6aee-465b-8630-4b73421e0114)

Сворачиваем третью группу (в которой контакт), чтобы все были свернуты. Теперь тащим вторую группу в конец. Результат: две группы вообще пропадают, остаётся та, которую тащили. А остальные испарились.

![mstsc_1GZ8CBvwPi](https://github.com/miranda-ng/miranda-ng/assets/5046855/0a01b681-6aa3-4e36-98ec-b918d517e2e6)

Перезапуск Миранды не помогает, пропавшие группы остаются пропавшими. Только если убить группу 2, тогда пропадашки появятся.

**Comment by Bumerangas** [comment]
not so long ago this bug was made lot of handwork for me to find all contacts again and sort.

**Comment by dartraiden** [comment]
Что я наблюдаю сейчас:

- [ ] невозможно переместить первую группу внутрь третьей. Первую во вторую - не вопрос. Первую после третьей - пожалуйста. А вот первую в последнюю никак
