### ISSUE TITLE
При открытой вкладке входящее сообщение и входящий файл ведут себя по-разному

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4514]
Открыт приват с контактом (жаббер), но активна иная вкладка (дискорд)

В неактивную вкладку (жаббер) прилетает сообщение

Результат:

- мигает значок сообщения в трее
- мигает значок сообщения около контакта в клисте

всё это обведено красной рамкой на скриншоте

<img width="809" alt="WS4f0GHjiA" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/9e5610b7-994a-46ac-8fa2-9376578ec73b">

А теперь всё то же самое, но прилетает не сообщение, а облачный файл с автоскачиванием

<img width="822" alt="6GSipnKUQx" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/c7ca7055-9908-42f3-9f59-1430292eddaa">

Ни в клисте, ни в трее ничего не мигает.

**Comment by dartraiden** [comment]
Полагаю, что надо сделать так, чтобы в клисте и трее мигал значок файлтрансфера

**Comment by dartraiden** [comment]
К слову, если приват, куда прилетает файл/сообщение не открыт вообще, то поведение у файла и сообщения одинаковое.

Баг возникает, когда приват открыт и вкладка не активна.

**Comment by dartraiden** [comment]
Ничего не поменялось.

**Comment by georgehazan** [comment]
> В неактивную вкладку (жаббер) прилетает сообщение
> 
> Результат:
> 
> * мигает значок сообщения в трее
> * мигает значок сообщения около контакта в клисте

Так не может быть по определению. Вот я взял твой архив, распаковал - этого не происходит, по понятным причинам, ничего в клисте и трее не мигает, потому что есть окно, ответственное за этот контакт, оно и подсвечивается типом события в табсах
