### ISSUE TITLE
MRA: окно передачи файла не закрывается автоматически

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4515]
Включена опция про закрытие окна файлтрансферов после окончания передачи.

Если я отправляю файл через Jabber, оно закрывается само, как и положено.

Е:сли я отправляю файл через MRA, оно не закрывается само.

**Comment by georgehazan** [comment]
Если ты об окне менеджера файл трансферов, то оно вообще не воздействуется, потому что с точки зрения миранды нет файл трансфера, просто добавляется оффлайновый файл. Поэтому то окно, которое осталось от жабера, так и останется висеть

**Comment by dartraiden** [comment]
От жаббера и телеграма ничего не остаётся висеть. От мра остаётся.

**Comment by SM-Sergey** [comment]
А можно уточнить? Как это, окно файлтрансферов в MRA не задействуется? У меня оно четко появляется при отправке файлов в MRA, и показывает прогресс отправки, и по нему можно отслеживать зависшие отправки.

![2024-07-12 12_26_24-File transfers](https://github.com/user-attachments/assets/0dee0273-4480-4755-83ad-7709fac1a83c)

Но у меня автозакрытие окна работает.

**Comment by dartraiden** [comment]
Хз, всё прекрасно задействуется и окно закрывается автоматически.
Юзер изменил показания: теперь он утверждает, что оно через N отправок перестаёт закрываться.

**Comment by georgehazan** [comment]
Если у него виснут передачи файлов (см. тикет), то понятно, что окно закрываться не будет, пока не пришло уведомление о законченной передаче
