### ISSUE TITLE
MRA: дублируются исходящие файлы

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4516]
Кидаю в своё Избранное файл через Миранду.
Миранда показывает, что в истории один файл.
А десктопный клиент показывает, что два одинаковых файла в этом сообщении.

**Comment by georgehazan** [comment]
Зашел через веб-морду - один файл (webagent.mail.ru)
Есть мнение, что десктопный клиент у них говно и не обновлялся лет несколько
