### ISSUE TITLE
Jabber: некорректный показ времени и даты в информации о пользователе

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4519]
<img width="369" alt="Miranda64_GuyXQnwjVe" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/3e203f6b-c6c1-4a06-a26b-e7ef17fdbdcc">

Во-первых, похоже обрезается ведущий ноль? Из-за чего время выглядит как 19:4 вместо 19:04

Во-вторых, какая-то проблема с датой. Этот человек совершенно точно был в жаббере вчера, а не в июне.

**Comment by georgehazan** [comment]
формат починил, про то, что туда прилетает, надо смотреть в нетфорк логе на тему jabber:iq:last
