### ISSUE TITLE
Veiw ICQ history in the current version

### ISSUE THREAD

**Issue by irwir** [miranda-ng/miranda-ng#4520]
Tried to find a link in ICQ history, but the current nightly build disabled the network and cleared contacts list.
Installation had to be overwritten with an old version of Miranda-NG (updater turned off); then history could be read.

It would be nice to be able to browse history without additional fuss.

**Comment by georgehazan** [comment]
you need to install the Dummy plugin, it will automatically catch your existing ICQ account and keep its histories

**Comment by irwir** [comment]
Used to keep bare minimum of plugins. After enabling the dummy one all is good with history. Thanks.
