### ISSUE TITLE
MRA: атавизм от ICQ в юзер-деталях. Не баг, не фича, а так...

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4521]
![2024-07-09 19_19_12-Лариса (Ева)_ user details](https://github.com/miranda-ng/miranda-ng/assets/34127439/dda4d079-5d1b-4dbd-8e94-61b9a2de068e)

**Comment by georgehazan** [comment]
"И о мелочах надлежит помнить" (с) Арман Жан дю Плесси дюк де Ришельё
