### ISSUE TITLE
работа с группами глючит по нескольким пунктам.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4523]
Группы в клисте выключены. Включать там мне их не надо от слова совсем, в принципе и почти никогда, так как они используются исключительно для групповых выборов в опциях игнорирования.

- Я хочу переименовать группу. Захожу в Options->Contacts->Ignore, Кликаю на группе ПКМ->Rename group - ничего не происходит, переименовать не дают.

- Я хочу создать группу. Кликаю там же ПКМ->New Group - в результате мне включают группы в клисте. А я не просил этого! Мне надо было только создать группу, и категорически не включать их в клисте, а увидеть созданную группу в Ignore.

- Ну и последнее - в  Options->Contacts->Ignore не видны в списке пустые группы. Неудобно. При этом если я там кликаю на контакте ПКМ->Move to group - то видны все пустые группы. То есть перекинуть контакт в группу я могу, а переименовать пустую группу - не могу.

Соответственно, надо сделать так, чтобы пустые группы тоже показывались в списке, чтобы заработало ПКМ->rename group в окне работы с игнорами, и чтобы создание новой группы не включало в принудительном порядке группы в клисте.

**Comment by georgehazan** [comment]
> * Я хочу переименовать группу. Захожу в Options->Contacts->Ignore, Кликаю на группе ПКМ->Rename group - ничего не происходит, переименовать не дают.

Логично. Из встроенных клистов вообще надо запретить все операции с группами.

> * Я хочу создать группу. Кликаю там же ПКМ->New Group - в результате мне включают группы в клисте. А я не просил этого!

Не совсем так. Включается показ пустых групп, чтобы можно было переименовать новую, и она встала бы в нужное место. Потом они скроются, при следующей перестройке клиста.

> * Ну и последнее - в  Options->Contacts->Ignore не видны в списке пустые группы. Неудобно.

Удобство встроенных клистов вообще делается только для их реальных целей, а не для подобной фигни. Если для работы данного списка контактов не нужны пустые группы, то их там не будет

**Comment by SM-Sergey** [comment]
> Логично. Из встроенных клистов вообще надо запретить все операции с группами.

Что же в этом логичного? Если в основном клисте имеется постоянная необходимость, чтобы они были выключены в обязательном порядке, и их включение мешает, то как тогда добавлять-удалять-переименовывать группы? А они нужны для игноров!

**Comment by georgehazan** [comment]
> Что же в этом логичного?

А что в этом нелогичного? Если нужны группы и операции над ними, то есть основной клист. А поведение групп во встроенных клистах определяется исключительно назначением этих самых клистов, а никак не странной необходимостью управлять группами оттуда.
