### ISSUE TITLE
Перед выливанием ночных сборок на сервер, нужно зачищать содержимое каталогов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4525]
У нас в ночнике лежит то, что депрекейтнуто аж в 2021. И там такого много (Rate и прочее)

<img width="481" alt="DSTBU7Wo96" src="https://github.com/miranda-ng/miranda-ng/assets/5046855/8a3f5c33-e71d-4c94-bcfb-58fa38bfc869">

**Comment by dartraiden** [comment]
В стабле всё ок, а вот во всех ночниках (32/64/32pdb/64pdb) бардак.

**Comment by georgehazan** [comment]
Не уверен, что это надо делать при каждой выкладке, да и тот факт, что где-то что-то лежит, никого особенно не волнует, пока оно в hashes.txt не попадет, апдейтер физически это не видит

**Comment by georgehazan** [comment]
> во всех ночниках (32/64/32pdb/64pdb) бардак.

нет, которые PDB - там порядок, потому что туда копируется всё по hashes.txt

**Comment by georgehazan** [comment]
Стер пока всё лишнее, 8 файлов за 3 года - потерпит
