### ISSUE TITLE
Weather: нет результатов посика при вводе имени города с заглавной буквы

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4528]
В поиске вводим `Tver` - 0 результатов
Если вводить со строчной, то результаты есть

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/2a3e59a4-a217-4fca-8933-720fb039a5db)

**Comment by georgehazan** [comment]
потому что этот конкретный поиск так устроен. 
вводи имя города по-русски, и будет счастье, хоть с большой, хоть с маленькой
