### ISSUE TITLE
Weather: контакт погоды не всегда переходит в онлайн после обновления данных

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4531]
Двойной клик по контакту. Открывается окошко погоды. Жмём Обновить. Всасываются свежие данные.

Иногда после этого контакт погоды становится "онлайн". А иногда не становится.

Например, если он стал онлайн, то тут же дёргаем ещё разок обновление и он становится "офлайн".

**Comment by georgehazan** [comment]
Потому что оно парсит данные и вместо "ясно", "облачно" и т.д. получает строчку "Место положения", соотв. этому и присваивает в статус 40071 - оффлайн. Надо подрихтовать шаблон так, чтобы оно выдирало мысль по делу
