### ISSUE TITLE
Jabber: версия Миранды сообщается некорректно

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4533]
У меня, и у собеседника стоит ночник (0.96.6)

Но в юзеринфо наши с ним Миранды выглядят совсем иначе

![изображение](https://github.com/miranda-ng/miranda-ng/assets/5046855/f74d716f-bf1f-43e8-9ec8-9bdf1b91e64e)

**Comment by dartraiden** [comment]
Есть мнение, что версия закэшировалась в нашем кэше капсов.

**Comment by georgehazan** [comment]
Из кэша капсов оно должно автоматически стираться через сколько-то времени, но суть не в том - в хэш должна входить версия клиента, а не только сами капсы.

**Comment by dartraiden** [comment]
[20:22] а, я понял - там хэшируется список фич
[20:23] поэтому для сервака все миранды одинаковые с момента внедрения jingle

**Comment by dartraiden** [comment]
Я понял, откуда берётся эта версия. Это версия ПЛАГИНА

<img width="528" alt="Miranda64_FvSmbTrInq" src="https://github.com/user-attachments/assets/ef18617f-a8ac-4049-9ac2-5baf99de8728">

**Comment by dartraiden** [comment]
Так что проблема слегка иная:

dartraiden, 17.07.2024
[13:34] в том, что в "Клиент" выводится версия плагина
[13:35] а не версия миранды
[13:35] и это очень неожиданно
[13:35] а версия миранды запрятана в подразделе "информация о по"

**Comment by georgehazan** [comment]
Там внизу кстати всё правильно изложено:
- клиент = Miranda NG Jabber protocol 0.95.11.1
- версия Миранды = 0.96.6.ххххх
