### ISSUE TITLE
MRA: краш после передачи файла 

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4539]
Передача файла успешно завершилась, файл передался, в оф. клиенте тоже виден.

----------------------------------------------------------------------------------------------------------------

Symbols mode: trunk version with symbols

Miranda Crash Report from Monday, July 15, 2024 12:04:34. Crash Dumper v.0.2.0.3

Likely cause of the crash plugin: Miranda NG

Exception: Access Violation at address 000000006C0C26DD. Reading from address 0000000000000050.

Stack Trace:
---------------------------------------------------------------
000000006C0C26DD (libssl-3 000000006C030000): w:\test\openssl\ssl\record\rec_layer_s3.c (521): ossl_tls_handle_rlayer_return
000000006C0C2BB3 (libssl-3 000000006C030000): w:\test\openssl\ssl\record\rec_layer_s3.c (693): ssl3_read_bytes
000000006C042FDC (libssl-3 000000006C030000): w:\test\openssl\ssl\s3_lib.c (4527): ssl3_read_internal
000000006C042F2A (libssl-3 000000006C030000): w:\test\openssl\ssl\s3_lib.c (4552): ssl3_read
000000006C060501 (libssl-3 000000006C030000): w:\test\openssl\ssl\ssl_lib.c (2314): ssl_read_internal
000000006C058407 (libssl-3 000000006C030000): w:\test\openssl\ssl\ssl_lib.c (2334): SSL_read
000000001369290D (mir_app 0000000013620000): c:\work\miranda-build\src\mir_app\src\netlib_ssl.cpp (286): Netlib_SslRead
0000000013691F35 (mir_app 0000000013620000): c:\work\miranda-build\src\mir_app\src\netlib_sock.cpp (67): Netlib_Recv
000000001368B238 (mir_app 0000000013620000): c:\work\miranda-build\src\mir_app\src\netlib_http.cpp (876): NetlibHttpRecvChunkHeader
000000001368AF18 (mir_app 0000000013620000): c:\work\miranda-build\src\mir_app\src\netlib_http.cpp (945): NetlibHttpRecv
000000001368AC8C (mir_app 0000000013620000): c:\work\miranda-build\src\mir_app\src\netlib_http.cpp (1096): HttpTransactionWorker
000000001368CCAF (mir_app 0000000013620000): c:\work\miranda-build\src\mir_app\src\netlib_http.cpp (1129): Netlib_HttpTransaction
00000000177C67F2 (ICQ 00000000177C0000): c:\work\miranda-build\protocols\icq-wim\src\http.cpp (191): CIcqProto::ExecuteRequest
00000000177C6C04 (ICQ 00000000177C0000): c:\work\miranda-build\protocols\icq-wim\src\http.cpp (67): CIcqProto::ServerThread
0000000013863D64 (mir_core 0000000013840000): c:\work\miranda-build\src\mir_core\src\windows\threads.cpp (162): forkthreadex_r
00007FFB5E187374 (KERNEL32 00007FFB5E170000): (filename not available) (0): BaseThreadInitThunk
00007FFB5FFDCC91 (ntdll 00007FFB5FF90000): (filename not available) (0): RtlUserThreadStart

**Comment by SM-Sergey** [comment]
Опять глючная мультитредность в опенссл, и незащищенность вызова критической секцией?

**Comment by georgehazan** [comment]
> Опять глючная мультитредность в опенссл, и незащищенность вызова критической секцией?

Она, да. Критическая секция здесь никак не поможет вообще, потому что если на время Netlib_Recv() залезть в секцию, то любая попытка записать в этот сокет, например, подвесит поток.

Это дубликат какого-то существующего бага, этот я пока прикрою

**Comment by SM-Sergey** [comment]
> потому что если на время Netlib_Recv() залезть в секцию, то любая попытка записать в этот сокет, например, подвесит поток.

А разве такое возможно? Чтобы кто-то что-то писал в сокет, пока он висит в ожидании приема чего-то? Это, как минимум, странно. По идее, для передачи файла и для приема файла надо открывать отдельные соединения к серверу с отдельными сокетами и отдельными локальными портами на прием (но в рамках той же сессии с тем же aimsid). Или я недопонял, о чем речь.

**Comment by georgehazan** [comment]
> Чтобы кто-то что-то писал в сокет, пока он висит в ожидании приема чего-то?

В чем проблема? Сокет - это два буфера (SSL сокет - не исключение), один для записи, один для чтение. Так вот, чтение не блокирует запись в сокет, туда можно нагадить, и оно исправно уедет на сервер.

> И закрывать их по окончанию или обрыву передачи.

Это если сервер пришлет "Connection: close" в ответе, а если соединение можно держать, то зачем его закрывать? Оно потом будет использовано повторно для других запросов

**Comment by SM-Sergey** [comment]
>  Так вот, чтение не блокирует запись в сокет, туда можно нагадить

Можно, но зачем? Это ничего особо не ускорит, если все равно ответа ждать. Вы же не аудио-видеопоток гоните.

> Оно потом будет использовано повторно для других запросов

Ну это да, можно. Только естессно с блокировками, чтобы пока один запрос не закончен полностью, второй не начинать. Именно про такую мультитредную блокировку я и имел в виду - чтобы с одним сокетом мог работать на чтение и на запись только один тред в одно время (или два треда, один на чтение, другой на запись). А если другому треду нужен в это время другой запрос - так в другой сокет, а не в этот.

**Comment by georgehazan** [comment]
> Можно, но зачем?

Вебсокет только так и работает, в общем-то. Где-то поток висит и ждет ответов, а где-то в сокет пишут команды, совершенно не сообразуясь с состоянием чтения. C http pipeline та же самая схема.

> Вы же не аудио-видеопоток гоните, которого туда можно загнать с запасом вперед, и в этом есть смысл.

SSL handshake - это три пакета туда, три обратно. Если пинг до сайта 100 мс, то хэндшейк 300 мс.

> Ну это да, можно. Только естессно с блокировками, чтобы пока один запрос не закончен полностью, второй не начинать. 

Это еще зачем? Команды пуляются одна за одной, потом на них асинхронно прилетают ответы. RTFM HTTP2 pipeline.

>Именно про такую мультитредную блокировку я и имел в виду - чтобы с одним сокетом мог работать на чтение и на запись только один тред в одно время

Так не бывает, да и не нужно.

**Comment by SM-Sergey** [comment]
> Это еще зачем?

Ну исходные такие:
 В openSSL3 нет проблем с мультитредностью между разных сокетов, это проверено и известно. В том числе и у меня самого есть сервис, к примеру, передающий немеренные потоки данных через сокет (не HTTP), там сделано два треда как раз - один шлет в него кучу данных, приостанавливая отправку, если слишком много неподтвержденного туда ушло. Второй принимает от удаленной стороны подтверждения изредка, восстанавливая отправку по мере надобности. Но это риторика. На десятке сокетов впараллель работает годами и ничего.

 Однако, MRA падает. Это значит, что MRA  делает что-то несовместимое с openSSL на одном сокете. 
А это значит, что не надо делать чего-то лишнего на одном сокете. Чего именно - не ясно. И как пример - сделать можно файлтрансферы каждый в своем новом сокете, что на 99.9% решит все проблемы. Возможно, есть и какие-то другие пути, но этот с виду самый простой. Вот такая вот суть, если не отвлекаться от темы на то, что мы друг друга плохо понимаем.
