### ISSUE TITLE
SkypeWeb: Изменено: некий глюк в запросах к серверу.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4541]
Поставил скайпвеб, влогинился.
Почти все контакты втянулись, но не все. Один групчат не добавился. Его ид содержит a034333ae9804ca08ca258b265ed65a4

нетлог:
[netlog.txt](https://github.com/user-attachments/files/16235646/netlog.txt)

там нетлог со старта миранды, и я писал в этот групчат сообщение в родном клиенте, удалив перед этим аналогичное. Это в самом конце нетлога - что прилетало миранде. Стоит обратить внимание на вот такие строки лога - это определенно лажа какая-то.

GET /v1https://azwus1-client-s.gateway.messenger.live.com/v1/users/ME/conversations/19%3Aa034333ae9804ca08ca258b265ed65a4%40thread.skype/messages?startTime=0&pageSize=100&view=msnp24Equivalent&targetType=Passport%7CSkype%7CLync%7CThread HTTP/1.1
.....
{"Message":"No HTTP resource was found that matches the request URI 'https://azwus1-client-s.gateway.messenger.live.com/v1https:/azwus1-client-s.gateway.messenger.live.com/v1/users/ME/conversations/19:a034333ae9804ca08ca258b265ed65a4@thread.skype/messages?startTime=0&pageSize=100&

**Comment by SM-Sergey** [comment]
UPD: 
этот групчат вдруг проявился. Ничего не делал, просто через час-полтора после остальных. Это какой-то странный баг, нестабильный. Но на эти глюки в URL в нетлоге стоит таки обратить внимание, с чего они такие могут появляться.

**Comment by georgehazan** [comment]
Это норм. Там бывает у скайпа, что один запрос встает раком, и описание групчата прилетает сильно позже. Сделал кэширование групчатов, теперь всё гораздо быстрее

**Comment by SM-Sergey** [comment]
кэширование это здорово,  а вот глюк с запросами-то починили? Или это глюк сервера в скайпе, задваивать URL тут:

{"Message":"No HTTP resource was found that matches the request URI 'https:// **azwus1-client-s.gateway.messenger.live.com/v1https:/azwus1-client-s.gateway.messenger.live.com/v1**/users/ME/conversations/19:a034333ae9804ca08ca258b265ed65a4@thread.skype/messages?startTime=0&pageSize=100&

**Comment by georgehazan** [comment]
Историю в скайпе вообще не смотрел пока

**Comment by SM-Sergey** [comment]
Это не про историю, это вот такое в нетлоге было "на ровном месте" - именно по тем контактам, которые долго не появлялись в списке.

**Comment by georgehazan** [comment]
Это запрос на считывание истории, он запускается, если контакт рапортует о том, что lastMessageId не совпадает с закешированным

**Comment by SM-Sergey** [comment]
А, ну может быть. 
Я имею в виду, что я не делал "Load server history".
Но именно это есть баг этого тикета, а не задержка появления контакта. Я ж его переименовал поэтому, сам поняв, что задержка не есть баг.
