### ISSUE TITLE
Dummy: групчаты глючат.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4543]
Групчаты, улетевшие из аськи в думми имеют две проблемы:
1. Дабл-кликом не открывают окно сообщений для просмотра последних N постов.
2. Если ПКМ-History, то в истории (NS) все сообщения идут от имени названия групчата, а не от имен авторов (а в аське показывались имена автороы).

**Comment by dartraiden** [comment]
1. не имеет отношения к думми, это дубликат https://github.com/miranda-ng/miranda-ng/issues/4150

**Comment by SM-Sergey** [comment]
Не верю в те объяснения.
Во первых - открыть даблкликом в окне сообщений никто не мешает от слова совсем. Историю же можно открыть по ПКМ-History.
Во вторых - вот вызвал историю одного чата через ПКМ, сделал экспорт в жсон. Что видим? Экспортируется и список юзеров в чате с никами и юзеридами, и юзериды для каждого сообщения. В чем проблема это сопоставить и вывести?

		"aimId" : {
			"type" : 253,
			"value" : "684483280@chat.agent"
		},
		"m0" : {
			"type" : 253,
			"value" : "{\"nick\":\"Sergey Markov\",\"role\":\"member\",\"sn\":\"300659245\"}"
		},
		"m1" : {
			"type" : 253,
			"value" : "{\"nick\":\"Александр Григорьев\",\"role\":\"member\",\"sn\":\"al@mail.ru\"}"
		},
		"m2" : {
			"type" : 253,
			"value" : "{\"nick\":\"ElectroVoicer\",\"role\":\"admin\",\"sn\":\"49092554\"}"
		}
	},
	"history" : [{
	"type" : 0,
	"timestamp" : 1625056865,
	"isotime" : "2021-06-30T12:41:05Z",
	"flags" : "r",
	"body" : "возможно, это и является причиной выхода из строя уже второй платы, точнее, буст-конвертора",
	"server_id" : "6979566089315287048",
	"user_id" : "49092554"
},{
	"type" : 0,
	"timestamp" : 1625056876,
	"isotime" : "2021-06-30T12:41:16Z",
	"flags" : "r",
	"body" : "при неясных обстоятельствах",
	"server_id" : "6979566136559927305",
	"user_id" : "49092554"
},{
	"type" : 0,
	"timestamp" : 1625057005,
	"isotime" : "2021-06-30T12:43:25Z",
	"flags" : "r",
	"body" : "возможно, однако он сгорел точно не во время работы, я несколько раз запускал, и напряжение не снижалось",
	"server_id" : "6979566690610708490",
	"user_id" : "al@mail.ru"
},{

**Comment by georgehazan** [comment]
Сделал, чтобы двойной клик открывал историю. Монтировать по новой движок чатов для Dummy - это перебор
С ICQ проблема была в том, что аська прописывала в user_id по-честному идентификаторы пользователей, поэтому для пользователей, которых нет в базе, в окне истории показывается имя групчата.

**Comment by SM-Sergey** [comment]
История открывается по дабл-клику, да.
А вот сообщения от имени групчата в истории - по-преждему. При этом пользователи есть в базе, они перекочевали в Dummy вместе со всеми своими ID-ами (проверил через дбедитор). И экспорт в JSON по-прежнему, как и выше было, показывает, что у NS (она же экспортирует) есть информация и о никах, и о их ID-ах..

**Comment by georgehazan** [comment]
> А вот сообщения от имени групчата в истории - по-преждему.

См. выше. Для всех, кто есть в профиле, показываются ники, иначе показывается имя групчата.

**Comment by georgehazan** [comment]
> ... а второй фикс уже выгрузился в доступ апдейтеру? Или он не о том?

Второй фикс - это кто?

**Comment by SM-Sergey** [comment]
> Для всех, кто есть в профиле, показываются ники, иначе показывается имя групчата.

Это так должно быть. А по факту - в профиле есть все, а показывается все равно имя групчата. То есть баг имеет место быть.

Второй фикс это который "more accurate", но вижу уже сам, выгрузился.

**Comment by SM-Sergey** [comment]
Вот, для доказательности.
JSON - см. выше.
внешний вид:
![2024-07-17 15_53_50-Усилитель Элком - history  72 messages total](https://github.com/user-attachments/assets/87e409e4-3597-4a2d-b53b-4f0273125009)

А юзер 49092554 в БД на месте:
![2024-07-17 19_35_12-Database Editor++](https://github.com/user-attachments/assets/c34116c7-2308-4399-93d3-fbcacb899b4d)
