### ISSUE TITLE
SkypeWeb: в групчатах история открывается в нотепаде.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4544]
А должна, по-видимому, в просмотрщике истории (например NS), как и другие групчаты в других протоколах.
И, вероятно с этим связано, нету ПКМ-History в меню.

Ну может это и не баг, а просто старое хранение истории групчатов в текстовых файлах, а не в БД, в таком случае надо этот тикет переделать на фиче-реквест, чтобы скайп хранил историю в БД, как и остальные.

**Comment by georgehazan** [comment]
Нет, должна открываться именно в нотепаде, потому что Skype не создает записи в базе данных для групчатов
