### ISSUE TITLE
DbEditor: не работает множественное выделение элементов дерева

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4545]
В редакторе базы слева, как известно, дерево, а справа непосредственно ключи.

В правой части множественное выделение работает (например, если использовать Shift+стрелку)

А в дереве не работает.

**Comment by georgehazan** [comment]
И правильно не работает, потому что там можно будет выделить элементы разного типа (модули, контакты, списки контактов) - как их обрабатывать потом? спецом ради этого в правом списке выводятся элементы одинакового типа, которые и можно отметить кучей и удалить, если что
