### ISSUE TITLE
NewStory: групчаты глючат.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4549]
Открываем историю любого обычного контакта хоть с 300К сообщений - все норм.

Открываем историю групчата с 6-7К сообщений или больше (хоть думми (ex.ICQ), хоть рабочего онлайнового из MRA, а других с большой историей нету пока - в скайпе они другой системы, текстово-нотепадные, а в VK пока не наработали) - NS сначала долго тормозит при открытии, затем открывается, отожрав за гиг памяти ОЗУ, и уперевшись в GDI-объекты, ну и далее глючит как положено, не по детски, если листать вверх, сообщения не показываются, если по тулбару мышкой водить, там всякие квадраты образуются вместо иконок, ну и т.д.

![2024-07-17 22_28_12-Feeder team Волжанка - history  7498 messages total](https://github.com/user-attachments/assets/01b33ec1-9cea-4dad-b1ab-ad4d27cb1fc8)

![2024-07-17 22_29_47-Оптосенс - history  6123 messages total](https://github.com/user-attachments/assets/a7764690-41d7-4f46-8fc1-74e8376bcdc6)

![2024-07-17 22_56_21-Task Manager](https://github.com/user-attachments/assets/86ae8207-a576-40dc-89d3-e5c83b91684e)

**Comment by georgehazan** [comment]
больше картинок и видео - больше расход GDI
в чем вопрос?

**Comment by SM-Sergey** [comment]
> в чем вопрос?

В том, что в истории "обычного" контакта с под 300К сообщений картинок в 100 раз больше, чем в истории этих групчатов, в которых всего лишь 6-7 К сообщений. Но история обычного контакта вгружается без проблем, и GDI объекты утекают по мере листания, а групчат открывается сразу убитым с 10К гди объектов.

**Comment by georgehazan** [comment]
А есть уверенность, что NS назначен для групчатов тоже? или там встроенный лог табсов старается?

**Comment by georgehazan** [comment]
И почему тогда журнал групчата подтаскивает все сообщения сразу?

**Comment by SM-Sergey** [comment]
Так это про историю...

**Comment by georgehazan** [comment]
> Так это про историю...

И плагином, который отвечает за историю, является именно NS?

> А с групчатами из думми - так их и не открыть в табсах в принципе.

Логично, потому что в Dummy не может быть групчатов по определению - их структура утеряна вместе с протоколом.

**Comment by SM-Sergey** [comment]
> Логично, потому что 

Так я и не спорю с этим. История групчатов в думми после правки ce18ece обрела нормальный вид, показываются юзернеймы вместо имени чата. Все стало нормально.

> И плагином, который отвечает за историю, является именно NS?

А кто же еще, если коммит ce18ece починил отображение имен?

**Comment by SM-Sergey** [comment]
К чему все эти вопросы? У вас что ли не повторяется?

**Comment by georgehazan** [comment]
У меня нет чата с 5000 картинок, это правда

**Comment by SM-Sergey** [comment]
Это много сообщений там. Картинок там конечно же в разы меньше, если сотня есть, то это с запасом. Я сейчас пролистал групчат на 7К сообщений в оф. клиенте MRA - картинки там редкость.  Смайлов - куча, но смайладд отключен.

**Comment by SM-Sergey** [comment]
... Отключил опцию "Show picture preview" - без разницы. Те же злостные тормоза при открытии истории, и тот же улёт объектов GDI в потолок.

**Comment by georgehazan** [comment]
Может там какая-то анимированная гифка вкралась? И GDI+ решил ее полностью подхватить, не знаю, вообще каждая картинка - это три GDI handle

**Comment by SM-Sergey** [comment]
Я же отключил просмотр картинок.

**Comment by SM-Sergey** [comment]
И потом это так во всех групчатах, и думмиевых, и MRA-шных

**Comment by SM-Sergey** [comment]
Это какие-то засекреченные GDI-объекты...
![2024-07-19 13_57_35-GDIView](https://github.com/user-attachments/assets/809ef970-8c54-4dde-8f54-a856e01ee8d1)


Но, в любом случае, надо побороть многосекундное открытие истории больших групчатов, вместе с этим проблема стопудово уйдет.

**Comment by georgehazan** [comment]
> И она явно грузит сразу все эти тыщи сообщений

Нет, конечно же, грузит ровно столько, сколько прописано в настройках. Может вообще ничего не грузить

**Comment by SM-Sergey** [comment]
Еще раз - речь про историю. У нее нет никаких опций, сколько грузить. История - это не журнал

**Comment by georgehazan** [comment]
> Есть какая-то принципиальная разница между открытием истории простого контакта, и истории групчата

Нет.

> Еще раз - речь про историю. У нее нет никаких опций, сколько грузить.

История грузит последний экран сообщений так, чтобы всё показать, остальные сообщения только запоминаются в массиве, очень быстро. По мере проматывания наверх остальные сообщения форматируются так, чтобы показываться на экране.

> Если она не грузит все эти тыщи сообщений, то что она тогда делает, подвисая на 10-15 секунд при открытии, отжирая в это время память и объекты?

Аллах его знает

**Comment by SM-Sergey** [comment]
>История грузит последний экран сообщений так, чтобы всё показать, остальные сообщения только запоминаются в массиве, очень быстро. По мере проматывания наверх остальные сообщения форматируются так, чтобы показываться на экране.

> Аллах его знает


Ну так надо это как-то выяснить! Опять, это так должно быть, как ты говоришь, а по факту разницы явная. Групчаты тормозят и дохнут еще до вывода в окно (висят в состоянии пустого белого окна долго), а обычные истории обычных контактов открываются сразу и живые. Причем я не нашел у себя ни одного обычного контакта, который бы так глючил, и ни одного большого групчата, который бы так не глючил. А на мелких групчатах это и незаметно.

**Comment by SM-Sergey** [comment]
Вот я побрейкал миранду во время зависа, когда она, открывая окно истории групчата тормозит и ест память. Не знаю, поможет ли.
![2024-07-19 16_53_52-PID_ 20940 - WinDbg 1 2402 24001 0](https://github.com/user-attachments/assets/2f7344df-d272-4474-befa-625fb57a3737)
![2024-07-19 16_57_24-PID_ 20940 - WinDbg 1 2402 24001 0](https://github.com/user-attachments/assets/dd342fa7-75d7-49cb-958e-7a2baf640c40)
![2024-07-19 16_58_51-PID_ 20940 - WinDbg 1 2402 24001 0](https://github.com/user-attachments/assets/7cf15872-0eca-4367-bf43-1103c5f91021)

**Comment by SM-Sergey** [comment]
Значит так. Нашел я это вам отладчиком.

Если открывается история обычного контакта, то после загрузки массива истории из БД вызывается paint, он отображает собственно кусок конца истории, далее вызывается NewstoryListData::RecalcScrollBar (строка 809 в history_control.cpp). Он пробегает по всему массиву истории, при этом pItem->m_bLoaded равен нулю для почти всех сообщений, кроме тех, которые в конце. А для тех, которые в конце, и у которых m_bLoaded не равен нулю, у тех pItem->savedHeight != -1, поэтому NewstoryListData::GetItemHeight возвращает его, не заходя в pItem->calcHeight. Все довольны.

Если открывается история групчата, то все немного по-другому. Начало то же, загрузка истории, затем paint, затем отрисовка внутри paint, на этом, как и в предыдущем случае, все ОК. А далее вызывается NewstoryListData::RecalcScrollBar, и вот в нем уже все совсем иначе. Начиная с евента с нулевым индексом, у всех евентов  pItem->m_bLoaded установлен в не ноль (true). Поэтому им всем вызывается NewstoryListData::GetItemHeight. Далее, внутри всех них pItem->savedHeight == -1, поэтому вызывается pItem->calcHeight. Внутри него вызывается setText(), ибо m_doc внутри них тоже null, а внутри сеттекста - litehtml::document::createFromString - каждый вызов которого приводит к утечке трех GDI объектов. 3000 сообщений - утекло 9000 объектов. Всем кирдык.

Таким образом, подвисает и съедает все GDI объекты RecalcScrollBar в первом его вызове при первом paint-е.

Вот и принципиальная разница при открытии истории обычного контакта и групчата. В обычном контакте m_bLoaded не равны нулю только у части последних евентов, а у истории групчата - не равны нулю у всех евентов. Почему - это для меня слишком сложно без знания подробностей внутреннего устройства NS. Это уж вы сами давайте.

И заодно утекалка выявидась - это litehtml::document::createFromString , съедающая по три объекта за вызов, при отключенных картинках и без смайладда. Надо, видимо, прибивать документы для тех евентов, которые сейчас не отображаются в окне, если я верно оцениваю ситуацию (не факт что).

**Comment by SM-Sergey** [comment]
Надеюсь, теперь все вопросы отпали? Или еще поработать над вопросом? Могу и сам починить.

**Comment by SM-Sergey** [comment]
Хм. Хотел там лоад на фетч себе поменять, но миранда не собирается (VS2019, солюшн bin16/mir_full.sln, сборка дебаг/вин64), пачка ошибок, в т.ч. как раз в ньюстори :

![2024-07-20 16_37_53-mir_full - Microsoft Visual Studio](https://github.com/user-attachments/assets/f7872993-7d5b-4076-b2b0-3df8aab93a82)

**Comment by SM-Sergey** [comment]
Подскажите пожалуйста, в чем может быть проблема сборки в VS2019? Я хочу починить #4491, благо теперь знаю как, а эта проблема мне не дает жить совсем, как говорится - блокирующая. 
дифф потом скину.

**Comment by SM-Sergey** [comment]
Замена load на fetch проблему этого тикета решила.

diff --git a/plugins/NewStory/src/history_array.cpp b/plugins/NewStory/src/history_array.cpp
index 959de8c8e1..f83e764288 100644
--- a/plugins/NewStory/src/history_array.cpp
+++ b/plugins/NewStory/src/history_array.cpp
@@ -644,7 +644,7 @@ ItemData& HistoryArray::allocateItem()
 
 void HistoryArray::checkGC(ItemData &p, SESSION_INFO *si)
 {
-	p.load();
+	p.fetch();
 	if (p.dbe.szUserId) {
 		Utf2T wszUser(p.dbe.szUserId);
 		if (auto *pUser = g_chatApi.UM_FindUser(si, wszUser))

**Comment by SM-Sergey** [comment]
И вторая часть марлезонского балета - вот решение для #4491 с LRU кэшем документов. Вроде работает, листать историю с 300К сообщений можно сколько влезет, и с картинками. GDI объекты для каждой открытой истории не вылезают за штук так 400 примерно.
Извиняйте, красоту не наводил, "лишь бы работало". Этот баг для меня самый ужасный был, часто блокирующий использование NS для истории, когда там надо долго копаться и искать.

[newstory_doc_cache_diff.zip](https://github.com/user-attachments/files/16322511/newstory_doc_cache_diff.zip)

**Comment by SM-Sergey** [comment]
Вот так правильнее. Там в кеше не надо reset-ы делать, оно само делается.

[newstory_doc_cache_diff.zip](https://github.com/user-attachments/files/16323440/newstory_doc_cache_diff.zip)

**Comment by georgehazan** [comment]
сейчас внесу, мерси

**Comment by georgehazan** [comment]
> Вот так правильнее. Там в кеше не надо reset-ы делать, оно само делается.
> [newstory_doc_cache_diff.zip](https://github.com/user-attachments/files/16323440/newstory_doc_cache_diff.zip)

W:\miranda-ng>git apply newstory_doc_cache.diff
error: corrupt patch at line 94

**Comment by georgehazan** [comment]
Попробуй сделать pull request, может быть

**Comment by SM-Sergey** [comment]
Хм. Я делал pull прямо перед тем, как делать правки

**Comment by SM-Sergey** [comment]
Вот
[newstory_doc_cache_diff.zip](https://github.com/user-attachments/files/16323570/newstory_doc_cache_diff.zip)

**Comment by SM-Sergey** [comment]
Я понял в чем дело - я делал диффы по git diff, но не коммитил между ними, поэтому второй дифф стал неверным - ссылка не на тот коммит оригинала.

**Comment by georgehazan** [comment]
> Вот

Просто в таком виде оно на практике смысла не очень имеет, имхо. Туда надо загонять только записи с картинками, а простые текстовые записи вообще на GDI не влюют, там рисование идет на шареных иконках.

Я подрихтовал чуток патч, одна переменная там лишняя
[0001.patch](https://github.com/user-attachments/files/16323733/0001.patch)

**Comment by SM-Sergey** [comment]
> простые текстовые записи вообще на GDI не влюют, 

На гди да, а вот этот html document съедает 3 гди хандла на один документ без картинок. ЗАчем - хз, это что-то его внутреннее.

> одна переменная там лишняя

Ну да, этот нюанс я не знал. Да и не старался особо.

**Comment by SM-Sergey** [comment]
Так что, пока, без вариантов - или все документы в кеш без разбора, или litehtml чинить, чтобы GDI объекты не текли на ровном месте. Но второе, имно, муторно, сложно, и перспективы не ясны.
Но, даже если GDI объекты перестанут течь, то память-то потечет, 6К сообщений с ассоциированными html документами = ~1.2 гига ОЗУ. Тоже не дело.

**Comment by georgehazan** [comment]
> Но, даже если GDI объекты перестанут течь, то память-то так и потечет, как сейчас, 6К сообщений с ассоциированными html документами = ~1.2 гига ОЗУ, и никуда это не деть.

То, что уже влилось, обеспечивает показ в групчатах N последних событий, остальное подматывается по требованию. Имхо на первый случай вполне достаточно

**Comment by SM-Sergey** [comment]
> То, что уже влилось, обеспечивает показ в групчатах N последних событий, остальное подматывается по требованию. Имхо на первый случай вполне достаточно

Это то да, так.
Второй патч сюда вообще не относится, обеспечивает "бесконечное" копание в любых историях, хоть с 6К сообщений, хоть с 300К. Это фикс #4491, а к этому тикету вообще не относится. С ним хандлы после открытия истории начинаются примерно с 800, а далее по мере листания истории устаканиваются в районе 1050, и так и остаются. Соответственно, при открытии еще других историй, увеличиваются на примерно 300 (в пике) с каждым окном истории. Уже жить можно - чтобы набрать 10К хандлов, надо копаться в 30 историях одновременно, такой запас на все случаи жизни сгодится.

А лично мне это жизненно необходимо, у меня в таких историях хранятся всякие разные обсуждения решений при проектирвоании электроники...

**Comment by SM-Sergey** [comment]
Сейчас провел эксперимент - открываю одну и ту же историю, и жму на ней 5 раз PgUp. Так вот - с включенными картинками на выходе имеется 915 GDI объектов, если картинки включены, и 1040 объектов, если картинки выключены. По ходу дела, отсутствие картинок только усугубляет проблему #4491, если нет патча. По той причине, что без картинок сообщения более компактные, их влезает больше в те же 5 страниц, и объекты GDI утекают быстрее.
Ну и картинки тут вообще не виноваты. Виноват сам в себе кривой litehtml.
Так что, все таки, хотя бы как временное решение для #4491 патч залить стоит, пока нету более правильного. Или оно уже есть где-то в загашнике?

**Comment by georgehazan** [comment]
завтра посмотрю, что там, возможно, это был background image. 
если это так, то есть шанс его расшарить

**Comment by SM-Sergey** [comment]
>  возможно, это был background image.

Это хорошо, если так, это плюс хороший. Но не лечит всего. Память все равно будет копиться тоннами, грубо по гигу на 5К пролистанных сообщений, если держать в памяти все html-документы на все то, что пролистали, а это не айс совсем.
