### ISSUE TITLE
User details: после переезда ICQ в Dummy нельзя увидеть некоторую важную информацию в юзер деталях.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4550]
После переезда ICQ в Dummy нельзя увидеть важную информацию в юзер деталях. Например - Last seen, что сразу бросилось в глаза, когда хотел это глянуть. В БД оно записано, а в окошке с юзер деталями - недоступна. То, что протокол ICQ закрыли, не причина закрывать доступ к просмотру времени, когда контакт был последний раз замечен в сети (это же видимо во всех протоколах есть, или почти всех, а не чисто ICQ-фича).
И, наверное, это не единственное, что стало недоступно из-за переезда ICQ в Dummy.

**Comment by georgehazan** [comment]
> (это же видимо во всех протоколах есть, или почти всех, а не чисто ICQ-фича).

это чисто фича ICQ, лежит в модуле ICQ и показывалась страничкой из плагина ICQ, соотв. Dummy об этом ни сном, ни духом

> И, наверное, это не единственное, что стало недоступно из-за переезда ICQ в Dummy.

Еще "Online since", вероятно 😉

**Comment by georgehazan** [comment]
можно под это приспособить Tipper, у него должна быть переменная LastSeen типа DateTime

**Comment by SM-Sergey** [comment]
> Еще "Online since", вероятно

 Не, еще Phone number, был у некоторых он. За Tipper спасибо, щас настрою его.
