### ISSUE TITLE
SkypeWeb: не работает отправка и прием файлов.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4551]
Не работает отправка файлов, как минимум в групчаты. Прием тоже.

Отправляю файл - картинку. Окно файлтрансфера открывается, без "бегунка" переходит в completed, а в чат (оф. клиент) прилетает вот такое. Табсы молчат, в них ничего не попадает.
![2024-07-18 11_55_49-Skype](https://github.com/user-attachments/assets/3c22eb0b-77a8-4b9d-b7c1-02fb1a5e4781)

 Затем я удаляю это в оф. клиенте, и отсылаю нужные картинки через оф. клиент. табсы продолжают молчать, как бы ничего не происходит. Через некое время порядка минуты-двух, случается краш не дебагбрейке аж в ядре винды где то.

[crash20240718115649.txt](https://github.com/user-attachments/files/16280706/crash20240718115649.txt)

нетлог последних действий, от перед отправкой файла, и до смерти.

[netlog.txt](https://github.com/user-attachments/files/16280721/netlog.txt)

После перезапуска миранды и лоад сервер хистори в этом чате ничего нового, никаких намеков, что были картинки.

**Comment by SM-Sergey** [comment]
Добавка. Если в групчаты вообще ничего не приходит при входящем файле, то в обычный чат с одним контактом приходят какие-то левые ссылки, ничего не открывающие, вот такого вида:
![2024-07-18 15_22_13-Дима Воробей (Online)](https://github.com/user-attachments/assets/687d64df-570a-4dad-a445-e79a86670b7d)

**Comment by SM-Sergey** [comment]
Собственно, было бы правильно перейти на оффлайн файлы после реализации #4548 , а на этот атавизм забить изначально.

**Comment by georgehazan** [comment]
@SM-Sergey печаль в том, что негде брать описание того, как правильно это делать... 
старый апи не работает, а примеров нового нет, потому что протокол полностью закрытый

**Comment by SM-Sergey** [comment]
У меня веб скайп отлично в файрфоксе сниферится по F12 (дебаггер).
