### ISSUE TITLE
CrashDumper: расширение функциональности.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4552]
Прошу добавить опцию для крешдампера - сохранять последние перед смертью N кбайт нетлога там же, где и сохраняется сам крешдамп. N по умолчанию, думаю, порядка 500К будет нормально. Разумеется, если нетлог включен.

**Comment by georgehazan** [comment]
Зачем? это очень разные сущности, и для краша как правило нетлог вообще не нужен

**Comment by SM-Sergey** [comment]
>  как правило нетлог вообще не нужен

Вот именно - "как правило". А когда оказывается, что нетлог нужен, и крашнулось на обработке чего-то сетевого, нетлог оказывается уже давно с нуля переписан... Я сейчас стараюсь каждый креш руками нетлог копировать туда, "чтобы было".
