### ISSUE TITLE
NewStory: проблема с подсчётом числа событий в истории метаконтакта

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4553]
Делаю метаконтат (Jabber+Discord). В обоих сабах есть история.

Смотрю историю метаконтакта. В заголовке окна истории написано, что событий 0.

**Comment by georgehazan** [comment]
Надо брать профиль и смотреть по обоим сабам и метаконтакту, чему равняется

select count(*) from events_srt where contact_id = XXX;
