### ISSUE TITLE
QuickSearch: настройка нового столбца

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4556]
В настройках QS есть возможность добавить новый столбец. Но что с ним делать дальше? Нет способа его переименовать или настроить то, что там будет выводиться, кроме как менять настройки через редактор базы. Через GUI мы тупо добавляем пустой столбец и всё, ничего больше с ним не сделать.

Предлагаю сделать так, чтобы по двойному клику открывался диалог, где можно было бы изменить название,  модуль и параметр.

![изображение](https://github.com/user-attachments/assets/c9949132-f7dd-49dd-ad6b-72be22b14d8f)

**Comment by georgehazan** [comment]
Надо отжать пимпочку справа, появится форма
