### ISSUE TITLE
Discord: Seems to recognize miranda ng as a "threat"

### ISSUE THREAD

**Issue by MP36ctrl** [miranda-ng/miranda-ng#4557]
It seems like whenever i log in to discord through miranda NG it causes discord to have a panic attack and forces me to reset my password, ive tested it several times as shown here:
![cliDD91](https://github.com/user-attachments/assets/1c442f83-297b-464c-9f9a-0f3115d2afe4)
it will work ok on miranda for a few minutes, then will force log out all my clients (not just miranda), when i try to login without resetting my password i get this error:
![image](https://github.com/user-attachments/assets/5f9bf898-f05e-4f2f-9cf6-4b64ba7744c6)
is there a way to fix this issue?

**Comment by georgehazan** [comment]
I don't think so, that was exactly why Discord was banned in Miranda last time

**Comment by MP36ctrl** [comment]
Alot of 3rd party clients use Tokens from the browser to login, ive tested it with clients that support this and have no issue after the reset, could token login be implemented to miranda ng?

**Comment by georgehazan** [comment]
@MP36ctrl perhaps, if you had Nitro or enabled 2FA, you'd get less such messages

**Comment by MP36ctrl** [comment]
Im using nitro as we speak (Ive had it for a while now), if i enable 2fa, would miranda ng support it?

**Comment by MP36ctrl** [comment]
alright i will try to use 2FA, hopefully this works

**Comment by MP36ctrl** [comment]
![image](https://github.com/user-attachments/assets/f5e3de08-d2b6-47f0-b6a1-4b5f78f1d882)

@georgehazan I am only able to find these, which one is supported?

**Comment by georgehazan** [comment]
Both, the first one is preferred

**Comment by MP36ctrl** [comment]
It seems like it works perfectly for the time being, thanks for your help
