### ISSUE TITLE
У чата в клисте отсутствует пункт контекстного меню "Файл", если история чата не хранится в базе

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4558]
ПКМ по чату дискорда в клисте - есть пункт "Файл"

ПКМ по конфе жаббера - нет пункта.

**Comment by dartraiden** [comment]
При этом, файл отлично отправляется перетаскиванием файла на контакт в клисте

**Comment by SM-Sergey** [comment]
При этом, у MRA чаты хранятся в базе, но пункта File нету. Но файл отлично отправляется нажатием скрепки в табсах.

**Comment by SM-Sergey** [comment]
А у думми контаков есть пункт "Message" (у думми-чатов нету)... Интересно, куда его можно отправить?

**Comment by dartraiden** [comment]
В настройках протокола есть опция, указывающая, разрешать отправку в думми или нет.

**Comment by SM-Sergey** [comment]
В общем, наличие пункта "файл" не зависит от записи в базу, как в заголовке написано. ЗАвисит еще от чего то.
