### ISSUE TITLE
mRadio: визуальные глитчи в настройках

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4559]
Открываем настройки mRadio

![изображение](https://github.com/user-attachments/assets/0673a8f1-0a89-4928-9a77-2e921334ee3f)

Водим мышкой по диалогу

![Безымянный](https://github.com/user-attachments/assets/67c2e336-68b3-4408-a250-411c3d385d36)

Проблемы:
1) отмеченные красным области становятся из серых белыми
у прочих протоколов в настройках мы этот серый фон истребили, он сразу белый
а у мрадио забыли
2) отмеченные синим заголовки должны быть полужирными, и они иногда полужирные, но чаще не полужирные - в общем, они рандомно становятся полужирными

**Comment by georgehazan** [comment]
Вряд ли кто-то полезет в паскальный код всё это править, ты же понимаешь
Проще этот плагин на С++ переписать

**Comment by georgehazan** [comment]
@dartraiden как mRadio на С++ перепишем - переоткрой
