### ISSUE TITLE
Telegram: всплывающие уведомления публичных каналов

### ISSUE THREAD

**Issue by Deadooshka** [miranda-ng/miranda-ng#4561]
Всплывающие уведомления о постах в публичных каналах Телеграма появляются только при открытии этих каналов в официальных клиентах. Как только открываешь канал в десктопном или мобильном Телеграме, то сразу всплывают все уведомления этого канала в Миранде. Речь не идёт о непубличных телеграм-чатах, где уведомления всплывают как надо по прибытию сообщения.

**Comment by georgehazan** [comment]
В телеге уведомления от больших каналов работают немного по-другому: прилетает не новое сообщение, а уведомляшка о том, что в чате есть непрочитанные сообщения. Тогда, при открытии окна с данным чатом, телега зачитывает пропущенную историю и рассылает полученные сообщения на все остальные устройства.

Так что ничего удивительного тут нет.

**Comment by Deadooshka** [comment]
@georgehazan а как сделать, чтобы уведомления публичных каналов появлялись в Миранде сразу после публикации поста? Буквально пару обновлений назад это поведение изменилось, а до этого работало как надо.

**Comment by georgehazan** [comment]
в телеге ничего не менялось месяца два. 
если и менялось, то на сервере

**Comment by georgehazan** [comment]
> @georgehazan а как сделать, чтобы уведомления публичных каналов появлялись в Миранде сразу после публикации поста? Буквально пару обновлений назад это поведение изменилось, а до этого работало как надо.

получать уведомление о том, что в чате появились непрочитанные сообщения, и сразу запрашивать историю, но судя по поведению обычного клиента телеги, они считают это очень плохой идеей
