### ISSUE TITLE
не точное определение клиента Miranda NG по имени 

### ISSUE THREAD

**Issue by lao-mang** [miranda-ng/miranda-ng#4562]
не точное определение клиента Miranda NG по имени. так как упущено ng в названии отображаемом программой. 
Вместо имени Miranda ng отображает просто Miranda и некоторые клиенты из за этого путают миранды им и нг в отображении значков

**Comment by georgehazan** [comment]
Не подтверждаю, всё показывается как надо.
Нужно взять редактор базы и посмотреть, что написано у этого контакта в jabber/MirVer

**Comment by georgehazan** [comment]
PS: и надо понимать, что миранда умеет отдавать в мирвер произвольную строку вообще, никак не сообразуясь ни с чем

**Comment by lao-mang** [comment]
там написано miranda 0.95.11.1 как имя клиента. но само имя miranda-ng не показывается. оно видно лишь после запроса версии клиента.

**Comment by georgehazan** [comment]
У старых миранд была такая тема, что они все отдавали свой хэш версии, как 0.95.11.1, это исправлено месяц назад где-то

**Comment by lao-mang** [comment]
не полностью исправлено. все равно номер версии в имени вместо ng стоит

**Comment by georgehazan** [comment]
для начала надо обновить миранду на том конце провода , и это поможет только в том случае, если там руками не прописана какая-то шняга

**Comment by lao-mang** [comment]
я не могу заставить всех обновиться. но миранда простой клиент. настроек то кот наплакал. нет простого режима все в одном окне даже

**Comment by dartraiden** [comment]
> я не могу заставить всех обновиться.

Значит, они будут сообщать фигню о версии, пока не обновятся.
