### ISSUE TITLE
jabber передача файлов баг. HELP!!! 

### ISSUE THREAD

**Issue by onyxnm** [miranda-ng/miranda-ng#4565]
Частая проблема при передаче файлов по миранде. протокол jabber. 
иногда помогает просто перезапуск, иногда обновление а бывает ни то ни то не помогает, в авторизации меняю имя сервера на неверное перезагружаю снова меняю имя сервера на верное подключаюсь и файлы начинают проходить. Этот баг очень мешает работе.
![изображение_viber_2024-08-01_11-24-06-905](https://github.com/user-attachments/assets/42d25741-f050-45ba-af98-c7fe77a2a246)

**Comment by georgehazan** [comment]
давай с этим на форум, ок? и нетворк лог приложи при отказе от передачи файла

**Comment by onyxnm** [comment]
https://forum.miranda-ng.org/index.php?topic=6679.0
Лог по какому пути хранится? крашлог не формируется в этот момент.

**Comment by georgehazan** [comment]
где в опциях укажешь, там и хранится
https://wiki.miranda-ng.org/index.php?title=Network_log
