### ISSUE TITLE
VK: проблема с отправкой .wav файла

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4566]
Отправляю .wav
результат таков:

![2024-08-05 15_12_13-](https://github.com/user-attachments/assets/356355aa-a541-4e6a-9cd3-6776bf067fa8)

А картинка или текстовый файл отправляется.

**Comment by SM-Sergey** [comment]
И не только .wav - сегодня я не смог одну картинку отправить. А другая улетела только в путь. В общем, что-то нестабильное.

**Comment by ElzorFox** [comment]
Не баг.
Попробуй отправить .wav через сайт - тоже не получится. ВК не считает, что .wav отправлять можно. Конечно, в миранде можно сразу пресекать попытки отправлять файлы этого типа, но это поведение ВК не документировано и может в любой момент измениться, так что держать у себя какой-то список запрещенных к отправке форматов, полученных опытным путем нецелесообразно.
Ну когда-то не получилось разово картинку отправить - ну иногда сервер не принимает. Может тут же следом этот же файл принять, может категорически отказаться принимать именно его.  Какой-то системы не замечено и это опять-таки не баг клиента.
