### ISSUE TITLE
Skypeweb: может впадать в ступор после спячки

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4568]
Комп на ночь вырубается - с утра включаю, все протоколы в оффлайн упали, скайп же в онлайне, при этом в клисте пара групчатов онлайновых, остальные контакты в оффлайне. Кипстатус поднимает все протоколы, а скайп так и висит в этом виде. Дальше вручную его увожу в оффлайн, возвращаю в онлайн - ничего не меняется, скайп в каком-то ступоре. И только полный перезапуск всей миранды решает проблему - скайп оживает, показывает реальные статусы контактов и можно беседовать.

**Comment by SM-Sergey** [comment]
Она не висит в смысле "совсем зависла" - программа крутится своим чередом, выходит по выходу нормально. Но перестает реагировать на события в скайпе, и всех в оффлайн переводит, кроме пары групчатов, и непонятно почему именно их, чем они отличаются.

**Comment by georgehazan** [comment]
Посмотри поток, в котором есть Skype.dll - может он подвис?

**Comment by SM-Sergey** [comment]
ОК, как поймаю опять.
Но обычно подвисший поток подвешивает всю миранду так, что после выхода из нее, надо ее добивать диспетчером задач - этого вот нету.

**Comment by georgehazan** [comment]
Если виснет главный поток, он завешивает весь гуй. Если виснет рабочий поток, то отключится только этот протокол

**Comment by SM-Sergey** [comment]
Там не поток виснет. Там как-то странно. К примеру, "как бы" перестает работать отправка сообщений - сообщение в реальности отправляется (другая сторона видит), но через таймаут выскакивает, что сообщение не отправлено, повторить-отменить.  При этом файлы отправляются нормально.

**Comment by georgehazan** [comment]
> К примеру, "как бы" перестает работать отправка сообщений - сообщение в реальности отправляется (другая сторона видит), но через таймаут выскакивает, что сообщение не отправлено, повторить-отменить.

Это и означает, что рабочий поток, который запросы крутит, на чем-то повис. Если бы его не было, то миранда бы не влогинилась, следовательно, либо повесился какой-то запрос, либо заткнулся рабочий поток. Вариантов-то нет больше

**Comment by SM-Sergey** [comment]
В общем, пока не поймал. Стараюсь, но пока всё мимо.
А еще он часто сам не уходит в оффлайн - то есть с утра комп включаю, все протоколы в оффлайне, а скайп "светится".

**Comment by georgehazan** [comment]
> А еще он часто сам не уходит в оффлайн - то есть с утра комп включаю, все протоколы в оффлайне, а скайп "светится".

Это http-протокол, формально у него нет статуса, пока запросы летают в интернет, то он в онлайне

**Comment by SM-Sergey** [comment]
Но у MRA нет такого поведения, он четко в оффлайн сваливается при пропадании инета (которое случается, ибо после спячки вайфай на время слетел)

**Comment by SM-Sergey** [comment]
Сейчас проверил - срубил инет руками. Все протоколы последовательно ушли в оффлайн, включая и не менее HTTP-шный MRA. Скайп 10 минут - в онлайне. Больше ждать не стал.

Вот как вариант - может, он впадает в ступор потому, что не видел пропадания инета, думает, что все ОК, а на самом деле его с сервера давно вышвырнули? Не?

**Comment by georgehazan** [comment]
Бес его знает, сделай нетворк лог на отрубание интернета, я посмотрю
