### ISSUE TITLE
Skypeweb: Unknown event

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4569]
`Сергей Марков: Unknown event, please send this text for developer: "<URIObject uri="https://api.asm.skype.com/v1/objects/0-weu-d8-bc5158ea43baf6e7db6945daf8f5a8fa" url_thumbnail="https://api.asm.skype.com/v1/objects/0-weu-d8-bc5158ea43baf6e7db6945daf8f5a8fa/views/imgt1_anim" type="Picture.1" doc_id="0-weu-d8-bc5158ea43baf6e7db6945daf8f5a8fa" width="1680" height="1260">To view this shared photo, go to: <a href="https://login.skype.com/login/sso?go=xmmfallback?pic=0-weu-d8-bc5158ea43baf6e7db6945daf8f5a8fa">https://login.skype.com/login/sso?go=xmmfallback?pic=0-weu-d8-bc5158ea43baf6e7db6945daf8f5a8fa</a><OriginalName v="IMG_6519.jpg"></OriginalName><FileSize v="1269724"></FileSize><meta type="photo" originalName="IMG_6519.jpg"></meta></URIObject>"`

На самом деле это картинка, она вот - https://api.asm.skype.com/v1/objects/0-weu-d8-bc5158ea43baf6e7db6945daf8f5a8fa/views/imgpsh_mobile_save_anim
и ее превьюшка - вот - https://api.asm.skype.com/v1/objects/0-weu-d8-bc5158ea43baf6e7db6945daf8f5a8fa/views/imgpsh_thumbnail_sx

**Comment by SM-Sergey** [comment]
да, это в групчате

**Comment by georgehazan** [comment]
Не может быть, дев. версия лопает картинки на ура третий день уже

**Comment by georgehazan** [comment]
![Screenshot_20240810_151814](https://github.com/user-attachments/assets/321590f9-f079-4c3e-9d9e-578f87fac350)
можно и в групчате
