### ISSUE TITLE
Skypeweb: Для каких-то контактов не отображаются ники.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4575]
Для каких-то контактов не отображаются ники, а вместо них какие-то .cid.xxxxx (скрин есть в #4574). Такие контакты существуют и в групчатах, и в клисте. При этом в официальном веб- и десктопном клиентах у них отображаются нормальные ники.

**Comment by georgehazan** [comment]
а в нетворк логе скайпа что про них написано?

**Comment by SM-Sergey** [comment]
А где там это посмотреть? На старте-логине, или где-то потом?

Есть нюанс - этот контакт отсутствует в моем клисте (и в клисте оф.клиента тоже), но есть в групчате. Вебскайп и десктопный клиент отрабатывают такую ситуацию корректно, а миранда нет.

**Comment by georgehazan** [comment]
> А где там это посмотреть? На старте-логине, или где-то потом?

Сразу после логина в каком-то из запросов, можно просто поискать по файлу, проще будет

> Есть нюанс - этот контакт отсутствует в моем клисте (и в клисте оф.клиента тоже), но есть в групчате.

Это без разницы, скайп каждый раз шлет всю инфу об участниках полностью

**Comment by SM-Sergey** [comment]
Этот контакт проскакивает только в ответах на такой запрос:

[09:53:33 0E18] [SKYPE_1] Send request to 
[09:53:33 0E18] [SKYPE_1] Send request to https://azeus1-client-s.gateway.messenger.live.com/v1/users/ME/conversations
[09:53:33 0E18] [SKYPE_1] Connection request to azeus1-client-s.gateway.messenger.live.com:443 (Flags 11)....
[09:53:33 0E18] [SKYPE_1] (00000000075AB6A0) Connecting to server azeus1-client-s.gateway.messenger.live.com:443....
[09:53:33 0E18] [SKYPE_1] (00000000075AB6A0) Connecting to ip 20.185.212.106:443 ....
[09:53:33 0E18] [SKYPE_1] (1736) Connected to azeus1-client-s.gateway.messenger.live.com:443
[09:53:33 0E18] [SKYPE_1] (1736 azeus1-client-s.gateway.messenger.live.com) Starting SSL/TLS negotiation
[09:53:33 0E18] [SKYPE_1] (1736 azeus1-client-s.gateway.messenger.live.com) SSL/TLS negotiation successful
[09:53:33 0E18] [SKYPE_1] (00000000075AB6A0:1736) Data sent
GET /v1/users/ME/conversations?startTime=0&pageSize=100&view=msnp24Equivalent&targetType=Passport%7CSkype%7CLync%7CThread HTTP/1.1
Accept: application/json, text/javascript
Accept-Encoding: deflate, gzip

не буду постить весь длинный ответ - вот так его (cid.420088632a87f4a4) упоминание выглядит. Больше он нигде не упоминается, только тут.

"threadProperties":{"lastjoinat":"1719322973988","topic":"╨ƒ╤Ç╨╛╨╕╨╖╨▓╨╛╨┤╤ü╤é╨▓╨╛ SL","membercount":"3","members":"[\"8:dim-pr\",\"8:live:.cid.c48b282c7e957500\",\"8:live:.cid.420088632a87f4a4\"]","version":"1719323220524","joiningenabled":"true"},"id":"19:51253abdb945481db0440cefd54b90cd@thread.skype","type":"Conversation","version":1723729274998,"properties":{"consumptionhorizonpublished":"9223372036854775807;9223372036854775807;9223372036854775807","consumptionhorizon":"9223372036854775807;9223372036854775807;9223372036854775807","isemptyconversation":"False","isfollowed":"False","lastimreceivedtime":"2024-08-15T11:53:42.126Z"},"lastMessage":{"id":"1723723196243","originalarrivaltime":"2024-08-15T11:59:56.243Z","messagetype":"RichText","version":"1723723196243","composetime":"2024-08-15T11:59:56.243Z","skypeeditedid":"15023887910834409885","conversationLink":"https://azeus1-client-s.gateway.messenger.live.com/


Skype получает никнейм для него запросом типа POST:

URL: https://people.skype.com/v2/profiles
POST DATA: {"mris":["8:live:.cid.420088632a87f4a4"],"locale":"en-US"}
ответ: {"profiles":{"8:live:.cid.420088632a87f4a4":{"status":200,"type":"skype","authorized":false,"profile":{"displayName":"PashaT","gender":"Unspecified","options":[{"name":"ui.color","value":"unknown","isDefault":false}]}}}}

При этом в клист не добавляет.

**Comment by georgehazan** [comment]
Может оно закешировано на какой-то старой версии скайпа? Там в профиле есть такой каталог ChatCache, там по номеру контакта можно посмотреть структуру чата вместе с пользователями. Файл этот можно смело снести, оно потом всё заново всосет

**Comment by SM-Sergey** [comment]
Так я и снес кеш, чтобы увидеть, каким запросом он получит ник. Этот запрос выше.

**Comment by SM-Sergey** [comment]
Если надо повторить - делается просто.
Помощник или второй аккаунт создает чат "на троих" - я, он и третий. У меня в клисте есть только "он" - помощник/второй аккаунт. А тот самый третий, для которого миранда не отображает ник - в моем клисте отсутствует, а в клисте "помощника" есть, он его в чат приглашал.

**Comment by georgehazan** [comment]
И в итоге в кэше помойка?... непорядок

**Comment by SM-Sergey** [comment]
В итоге - миранда не запрашивает ники для участников чата, которых нет в своем клисте, и не показывает, вместо них показывает IDы. А родной скайп запрашивает ники, кеширует и показывает.
