### ISSUE TITLE
VK: новый контакт и чат не появляется в списке при его создании через браузер.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4576]
Начал новый чат с новым контактом в веб браузере (так как через find/add contacts он никаким способом не нашелся). При этом миранда, будучи в онлайне, молчала как партизан. Перезапустил ее - и контакт в клист пришел, и история подтянулась.

**Comment by ElzorFox** [comment]
Нетлог процесса есть?
Синхронизация новых чатов/контактов, добавленных извне, не одномоментная - раз в 1 минуту плюс-минус.

**Comment by SM-Sergey** [comment]
Нетлог помер... Я все время забываю, что он стирается при перезапуске миранды...
А вот насчет "раз в минуту плюс-минус" - это немного неожиданно, в других протоколах новые сообщения прилетают сразу, это я проверю.

**Comment by SM-Sergey** [comment]
А вот отвлеченный вопрос - то, что в VK после ссылки идет - vk.com/xxxxxxx - это что? Это ник или ID? Вот по этому xxxxxx почему-то контакт не находится с целью добавления. Или так и должно быть? Как добавить контакт в миранду, если известен только этот "xxxxxxx" ?

**Comment by ElzorFox** [comment]
Нет, новое сообщение (собственное или чужое - не важно) должно прилететь сразу. Если не прилетело, значит что-то с longpool севисом случилось, тогда интересно знать что,  почему и, что важнее, отчего главный поток его не восстановил. А вот если на сайте кого-то в друзья добавить, то он в список контактов прилетит не сразу, а в течение минуты.

**Comment by ElzorFox** [comment]
> А вот отвлеченный вопрос - то, что в VK после ссылки идет - vk.com/xxxxxxx - это что? Это ник или ID? Вот по этому xxxxxx почему-то контакт не находится с целью добавления. Или так и должно быть? Как добавить контакт в миранду, если известен только этот "xxxxxxx" ?

В терминах протокола, это domain. Он может выглядить как idxxxxxxxxxx, тогда xxxxxxxxxx может быть (а может и не быть в общем-то) ИДом. Сервиса поиска по domain, насколько я знаю, нет. Зная только его, пользователя в друзья добавить нельзя, отправить сообщение - тоже. Понимаю, что странно и нелогично, да.

**Comment by SM-Sergey** [comment]
Тут было так - я через веб браузер написал сообщение этому контакту - в друзья его не добавлял. Просто перешел по ссылке, которую мне дали на него, нажал "написать сообщение", перелетел в веб-мессенджер, и написал. А миранда, находившаяся при этом в онлайне, этого не заметила. Вообще, думаю, что минута должна была пройти, прежде чем я ее перезапустил, но тут не уверен точно.

То есть, сначала нажал сюда на их странице:
![2024-08-16 19_28_19-Сообщество «Печатный салон №1-Все виды печати!» ВКонтакте — публичная страница, ](https://github.com/user-attachments/assets/e4d9ac6c-ae29-465b-9570-491f38db1be5)

Затем сюда:
![2024-08-16 19_29_50-Сообщество «Печатный салон №1-Все виды печати!» ВКонтакте — публичная страница, ](https://github.com/user-attachments/assets/e2ebd741-a2a7-415c-9c91-063043888a81)

В результате перелетел в мессенджер с открытым чатом для этого контакта, и написал сообщение.

**Comment by ElzorFox** [comment]
По описанию - почему-то отвалился longpool. Но понять почему без нетлога не получится.

**Comment by SM-Sergey** [comment]
В какой нибудь следующий раз сделаю вырезку из нетлога... Но сейчас его точно нет.

Эх, сделать бы в миранде при ее запуске переименование предыдущего нетлога в "*.1", а предпредыдущего в "*.2", и удаление третьего по старости...

**Comment by apollo2k4** [comment]
> Эх, сделать бы в миранде при ее запуске переименование предыдущего нетлога в ".1", а предпредыдущего в ".2", и удаление третьего по старости...

А пойти посмотреть настройки – нет?
![изображение](https://github.com/user-attachments/assets/34fddde5-eb63-4d74-b7a4-7a3b02407c7b)
Последние 10 хранятся.

**Comment by ElzorFox** [comment]
Не подтверждено, вероятнее была временная нестабильность на сервере.
