### ISSUE TITLE
Discord: Random DM spam

### ISSUE THREAD

**Issue by MP36ctrl** [miranda-ng/miranda-ng#4577]
![cli4EDC](https://github.com/user-attachments/assets/9b69f4d3-adbd-4cb3-8754-ca0b57359df7)

This keeps happening every time miranda ng connects to discord, it shows old messages from private chat and groupchats with all kinds of errors

this does however happen on one client only,

is there a way to prevent this?

**Comment by dartraiden** [comment]
Perform db check with "Mark messages as read" enabled.

**Comment by MP36ctrl** [comment]
Profile completely died (This is because of the computer crashing constantly on startup so its not mirandas fault)
For now the new profile is managing fine, 
Thanks for the help
