### ISSUE TITLE
Skypeweb: по следам #4575 - ник не везде показывается.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4578]
По следам #4575:
После обновления я прибил кеш, ники втянулись, закешировались.
В истории (NS) - ник отображается.
В журнале (tabsrmm) - ник отображается в списке участников, а в окне чата - нет:
![2024-08-19 19_22_23-File Upload](https://github.com/user-attachments/assets/fa155d2a-d0b7-477b-b1c5-85e2e489bdba)

**Comment by georgehazan** [comment]
То, что залетело на экран до отрабатывания запроса на чтение профиля, так там и останется, пока не откроется и не закроется окно. Полученный rtf статичен, его можно только наращивать

**Comment by SM-Sergey** [comment]
Да, сработало - только странно, закрыть-открыть окно не помогало, а вот перезапуск миранды все вылечил.

И еще хотелось бы, чтобы ники обновлялись без прибивания кеша руками - если в кеше нет ника, а есть контакт с ИД-ом, то стоит попытаться запросить ник. Я то кеш прибью, а у других это может быть сложно. Без прибивания кеша ники не обновлялись.

**Comment by georgehazan** [comment]
> И еще хотелось бы, чтобы ники обновлялись без прибивания кеша руками

для всех новых чатов всё будет норм.
