### ISSUE TITLE
NewXStatusNotify: удалить поддержку xСтатусов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4589]
```
wchar_t* GetStatusTypeAsString(int type, wchar_t *buff)
{
	switch (type) {
	case TYPE_JABBER_MOOD:
		mir_wstrcpy(buff, TranslateT("Mood")); return buff;
	case TYPE_JABBER_ACTIVITY:
		mir_wstrcpy(buff, TranslateT("Activity")); return buff;
	case TYPE_ICQ_XSTATUS:
		mir_wstrcpy(buff, TranslateT("xStatus")); return buff;
	default:
		mir_wstrcpy(buff, TranslateT("<unknown>")); return buff;
	}
}
```

Жабберовские, очевидно, нужно оставить, а вот xСтатусы аськи в топку.

**Comment by dartraiden** [comment]
Ну и там ещё несколько `case TYPE_ICQ_XSTATUS`, если они чисто для аськи, то, видимо, в топку.

**Comment by dartraiden** [comment]
Вообще, xStatus поддерживают только аська (покойная) и жаббер (имеет код, который мимикрирует жабберные mood и activity под xСтатусы). В идеале бы переписать в Миранде всю работу с хСтатусами, чтобы оно напрямую работало с жаббером без всякой эмуляции. А код, который заточен под асечные хСтатусы, вытереть.

**Comment by SM-Sergey** [comment]
А вот это в скайпе, это что? Не xStatus-ы?
![2024-08-21 10_07_31-Skype — Mozilla Firefox](https://github.com/user-attachments/assets/d9e8eae2-7dbb-442c-a2e9-5c6174f97b73)

**Comment by SM-Sergey** [comment]
ИМХО, надо ICQ выпилить, а скайп добавить.
