### ISSUE TITLE
SkypeWeb: Поддержать xStatus

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4592]
В скайпе есть расширенный статус, который подразумевает иконку по выбору и статусное сообщение. Миранда это не умеет. Нужно иметь возможность показывать собственный xStatus, и расширенные статусы других контактов из клиста.

![2024-08-21 18_50_07-Skype — Mozilla Firefox](https://github.com/user-attachments/assets/b920da9e-29d7-4d7c-92b7-0d1e27c87b87)

**Comment by georgehazan** [comment]
он не расширенный, в терминах миранды это просто статусное сообщение со смайликом
ставим типпер, например, включаем в смайлах эмодзи и наслаждаемся

**Comment by georgehazan** [comment]
Вот собственный статус - с ним проблема, пока нет никакой возможности вклеить туда смайлик...

**Comment by SM-Sergey** [comment]
Типпер это хорошо, а можно эту иконку выдать в "Extra icons" в клист?
