### ISSUE TITLE
Skypeweb: Показать расширенную статусную иконку в Extra Icons

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4594]
После обновления, включающего в себя коммит 906a9d5f75f282a1ddd683f29346041c8f73e511 , ожидалось, что можно будет включить показ расширенной статусной иконки в "Extra Icon". Однако, нет. 
Поэтому новый тикет - показать ее в экстра-иконках.

PS - по другой теме - надо возвращать #4580 - теперь все групчаты так заглючили, а не один из. То есть стало хуже.

**Comment by georgehazan** [comment]
> Поэтому новый тикет - показать ее в экстра-иконках.

Это невозможно. Это не иконка, это просто кусок текста

**Comment by SM-Sergey** [comment]
> Это не иконка, это просто кусок текста

Да почему же сразу невозможно? Пусть смайладд ее преобразует в иконку, а иконку уже показать!

**Comment by georgehazan** [comment]
потому что смайлиадд показывает иконки вместо текста, а не занимается распознаванием иконок
