### ISSUE TITLE
Skypeweb: Сделать возможность задания своей дополнительной иконки статуса в статусном сообщении.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4595]
Ну как у оф. клиента.

**Comment by georgehazan** [comment]
Это не иконка, это текст.

**Comment by SM-Sergey** [comment]
Ну и что? В любом сообщении мы вставляем иконки без проблем, которые тоже текст. А тут вдруг нельзя.

**Comment by georgehazan** [comment]
Экстра-иконка - это как раз иконка, и она должна быть зарегана в иколибе, чтобы быть показанной, это вовсе не текст.

**Comment by SM-Sergey** [comment]
Ну и взять ее из смайладда, из набора для скайпа

**Comment by georgehazan** [comment]
Смайлиадд не выдает иконки, он их рисует в виндовых контролах

**Comment by SM-Sergey** [comment]
Ну значит надо как-то доработать, чтобы мог выдавать в виде иконки...

**Comment by georgehazan** [comment]
Зачем? оно и так будет видно в клисте, если показать там статусное сообщение

**Comment by SM-Sergey** [comment]
Так в первую очередь для задания своей иконки кликом по иконке из списка.

**Comment by SM-Sergey** [comment]
Вообще для удобства, эту иконку менять 25 раз на дню. Кликнул куда нибудь в меню задания расширенного статуса, кликнул на иконку - она сменилась.

**Comment by SM-Sergey** [comment]
Кстати, было бы неплохо иметь некий набор своих заранее заготовленных статусов в виде текстового файла...

**Comment by georgehazan** [comment]
> Вообще для удобства, эту иконку менять 25 раз на дню.

Удобство смены по 25 раз на дню и выбор из длиннейшего списка всех возможных эмодзи несовместимы друг с другом. 

> В скайпе удобно - есть список из "готовых" часто нужных статусов с выбором в один клик.

Нет, там такая же простыня из всевозможных эмодзи.

> В аське (старой) это же делалось на раз-два.

В аське было 34 расширенных статуса, в отличие от 3000 эмодзи

**Comment by georgehazan** [comment]
> Кстати, было бы неплохо иметь некий набор своих заранее заготовленных статусов в виде текстового файла.

Плагин QuickStatusMessage в помощь

**Comment by SM-Sergey** [comment]
> Нет, там такая же простыня из всевозможных эмодзи.

Ну чего "нет" то? Вот:
![2024-08-22 18_01_49-Skype — Mozilla Firefox](https://github.com/user-attachments/assets/b4510630-303b-451c-ba30-3d713204bd11)

Вот и сделать текстовый файлик с этими заготовками, и чтобы свои туда можно было добавить. Будет достаточно.

**Comment by SM-Sergey** [comment]
А простыня иконок, это уже если этот список не устраивает.

**Comment by georgehazan** [comment]
> Вот и сделать текстовый файлик с этими заготовками

Не надо текстовый файлик, достаточно забить свои сообщения статуса в миранду, их там примерно столько же.

> Винкейплюс ставить ради этого вообще не вариант,

Чо-чо? Это сама винда умеет, еще и запоминает самые частые. Не надо ничего ставить, если это не XP.

**Comment by SM-Sergey** [comment]
Ну тогда, хотя бы, чтобы в SimpleStatusMessage можно было втыкать иконки из смайладда, и видеть их там. Как раз "рисование в контроле" прокатит.

**Comment by georgehazan** [comment]
Это не иконка, это текст... И в скайп оно уходит как текст, если там будет иконка, будет обсер

**Comment by SM-Sergey** [comment]
Еще раз - как в сообщениях и чатах - в контроле у SimpleStatusMessage  видна иконка (если есть смайладд), а в протокол уходит соответствующий текст.

**Comment by SM-Sergey** [comment]
Даже так... 
А как же тогда ее вставлять через SimpleStatusMessage совсем вручную? Чтобы сделать себе набор статусов с иконками?

**Comment by SM-Sergey** [comment]
А этот "richMood" обязательно передавать?

![2024-08-22 18_28_32-Skype — Mozilla Firefox](https://github.com/user-attachments/assets/0db052a5-469b-4ab0-ad1b-56b0fe391c44)

**Comment by SM-Sergey** [comment]
Ну тогда надо дальше думать, как это реализовать.

**Comment by georgehazan** [comment]
> А как же тогда ее вставлять через SimpleStatusMessage совсем вручную?

Никак, понятное дело. В плагине ставится иконка и, видимо, запоминать последнее статусное сообщение для каждой иконки

**Comment by SM-Sergey** [comment]
> В плагине ставится иконка и, видимо, запоминать последнее статусное сообщение для каждой иконки

Вполне логично.

**Comment by SM-Sergey** [comment]
Только еще может быть отсутствие иконки, но сообщение есть.

**Comment by SM-Sergey** [comment]
Побочный вопрос, но он рядом. А типпер показывает иконки в статусных и последних сообщениях со смайл-паком, который "Tipper smileys" ? Или со смайлпаком от соответствующего контакту протокола? Сокращения-то разные в разных протоколах... Что-то пока не получается скрестить ужа с ежом.

**Comment by georgehazan** [comment]
> А типпер показывает иконки в статусных и последних сообщениях со смайл-паком, который "Tipper smileys" ?

Да, но эмодзи в этот пакет не входят, они одни на всех

**Comment by SM-Sergey** [comment]
Спасибо за подсказку. Но всё равно пока не получается скрестить ужа с ежом.
Если я ставлю на эмодзи пак от VK - работает VK, но скайп со своими сокращениями в скобках - нет.
Если ставлю туда набор от скайпа - скайп работает, но ломается VK.
Если ставлю самый большой доступный набор (вацаповский) - то VK частично ломается, а скайп совсем...
Как это всё разрулить то? Или тикет сделать, чтобы типпер брал иконки от протоколов, когда показывает последнее сообщение и статусное сообщение?

**Comment by georgehazan** [comment]
> Как это всё разрулить то?

В смайлиадд есть настройка - отдельные категории для протоколов, ее надо включить и для каждого протокола указать свой маленький смайлпак

**Comment by SM-Sergey** [comment]
У меня такое ощущение, что типпер ее не подхватывает. В NS работает, а в типпере нет. Ну или я что-то не так сделал
