### ISSUE TITLE
CLIST(clist_modern?): Добавить опцию показа контактов Dummy в конце списка.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4596]
Имеется опция показа оффлайн-юзеров в конце списка. Очень нужная вещь, но её маловато.
Хочется увидеть еще опцию показа контактов под управлением Dummy в самом конце этого списка, а то теперь их куча.

Для чего? Группы используются, как всегда, для группировки контактов для игнорирования (включения-выключения игноров группами). Эта группировка никак не совмещается с желаемым расположением контактов в клисте, а так как группы одни и в игнорах, и в клисте, то группы в клисте получаются неприменимы и отключены, а существуют и используются только в окне настройки игноров.  Поэтому, единственная оставшаяся возможность как-то организовать контакты, это их расположение-сортировка. Хочется видеть сначала контакты, которые в сети, затем оффлайн контакты "живых" протоколов, и затем контакты того, что перешло под управление Dummy. И, желательно, чтобы они были отгорожены по аналогии с оффлайном разделителем "------Dummy-----"

**Comment by georgehazan** [comment]
Надо сделать над собой усилие и начать использовать группы по назначению - управление показом контактов на экране, тогда и проблем не будет
