### ISSUE TITLE
SkypeWeb: Не открывается сессия сообщений и не появляется уведомление о новых сообщениях

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4598]
Если окно сообщений не было открыто ранее, то оно и не открывается само (при включенной соотв. опции), и не появляется уведомление о новых сообщениях, как минимум в групчатах.

**Comment by georgehazan** [comment]
Ничего не понял, если честно :-) можно пошаговую стратегию воспроизведения?

**Comment by SM-Sergey** [comment]
Ну в чат кто-то что-то писал, я комп включаю, в табсах вкладки нет, уведомления о новых сообщениях нет. Даблкликаю на чат - вкладка открывается, здрасьте, там новые сообщения. В опциях стоит галка открывать новые вкладки (Automatically create new message sessions without activate them). Уведомлений тоже нет, что новые сообщения были. 
Потом я закрываю вкладку. Вижу - "кто-то набирает текст". Потом перестает набирать. Потом опять даблкликаю, открываю вкладку - там упс, новых сообщений оказывается есть, и опять ни уведомлений, ни автооткрытия вкладки.

**Comment by georgehazan** [comment]
Когда всасывается история с сервера, она подъезжает как уже прочитанная, а на такие события окно не возбуждается

**Comment by SM-Sergey** [comment]
Как это? В других протоколах нет такого. Всю жизнь было все нормально - с утра включаю комп, поднимаются все протоколы, и создаются все вкладки, где что-то новое произошло, и в ранее созданных и открытых мигают уведомления, если они не активны. И сейчас в ВК так. А в скайпе не работает. Как иначе узнать-то, что что-то где-то за ночь произошло?

И сейчас, когда мне пишут непосредственно в онлайне в скайп (как минимум в групчате), вкладка тоже сама не открывается, если она была закрыта для этого чата. Я вижу, что кто-то набирает текст там, и всё - если упустил, то никаких уведомлений, что там что-то новое написали. Открываешь чат - а там оно есть.

А к загрузке истории по Load Server History этот тикет никакого отношения и не имеет.

**Comment by SM-Sergey** [comment]
В обычных чатах, которые не групчаты, вроде все норм

**Comment by georgehazan** [comment]
> Как это? В других протоколах нет такого.

Это так во всех протоколах.

> Всю жизнь было все нормально - с утра включаю комп, поднимаются все протоколы, и создаются все вкладки, где что-то новое произошло, и в ранее созданных и открытых мигают уведомления, если они не активны. И сейчас в ВК так.

В нормальных протоколах (не путать со скайпом) все непрочитанные сообщения, висящие на сервере, прилетают автоматически, не требуя зачитывания истории отдельным запросом. И прилетают они как онлайновые сообщения.

> А к загрузке истории по Load Server History этот тикет никакого отношения и не имеет.

Это ошибочное суждение.

**Comment by SM-Sergey** [comment]
Значит надо сделать так, чтобы в скайпе зачитывание истории не по Load history, а по приходу в онлайн, открывало окна сессий и давало уведомления, если в БД что-то новое прилетело. Это первое. А то блин все названивать начинают, потому что в чате обсуждения рабочие, а я и не знаю. Ну не дело же это!

А второе - надо чтобы при нормальном приходе новых сообщений в групчаты в онлайне тоже автооткрытия вкладок сессий и уведомления заработали (в приватных чатах вроде работают)

Я просто думал, что у этих двух вещей из одного места ноги растут.

**Comment by georgehazan** [comment]
надо только проверить, что выставлена галочка "авто синхронизация сообщений" в настройках

> А второе - надо чтобы при нормальном приходе новых сообщений в групчаты в онлайне тоже автооткрытия вкладок сессий и уведомления заработали

Там отдельный блок настроек для групчатов

> Я просто думал, что у этих двух вещей из одного места ноги растут.

Не, движок групчатов - это вообще отдельная песня

**Comment by SM-Sergey** [comment]
> Там отдельный блок настроек для групчатов

Ну видимо эта отдельная настройка включена, раз в других протоколах вкладки появляются сами, если кто-то в неоткрытый групчат пишет. Ща обновлюсь, проверится...

**Comment by SM-Sergey** [comment]
Ну да, закладки для групчатов не открываются сами по-прежнему при появлении в чате новых сообщений, и уведомление не выскакивает. Хотя уведомление о том, что туда кто-то печатает текст есть.

Не могу понять, что там недонастроено

**Comment by georgehazan** [comment]
> А что именно это за настройка? Я сходу не нашел

автоматом поднимать закладку для входящих сообщений

**Comment by SM-Sergey** [comment]
Это "Activate tabs or windows for highlight events" ? Я просто не понимаю, что значит highlight. Или я не там ищу?

![2024-08-28 19_17_05-Miranda NG options](https://github.com/user-attachments/assets/b583917c-d370-471a-9c2e-12c2a3c80ce7)

**Comment by georgehazan** [comment]
Для начала надо понять, что после старта миранды около чата с непрочитанными сообщениями появляется желтый кружочек

**Comment by georgehazan** [comment]
> Я просто не понимаю, что значит highlight

Это то, что находится на закладке Highlighting

**Comment by georgehazan** [comment]
групчаты по-другому работают, у них появляется желтый кружочек в списке контактов

**Comment by georgehazan** [comment]
можно еще сделать, чтобы попапы появлялись, и звуи играли

**Comment by SM-Sergey** [comment]
Ну вот ничего нигде не появляется, тишина. Или он столь незаметный, что я его не вижу.

**Comment by georgehazan** [comment]
Options - Contact list - Extra icons

**Comment by SM-Sergey** [comment]
Ага. Нашел.
А главный-то вопрос, как теперь включить, чтобы вкладка сама появлялась с новыми сообщениям? А то все эти звуки и попапы будут успешно профуканы, когда я далеко от компа, как и эта не особо заметная иконка (клист вообще далеко не всегда на экране есть). Или это не предусмотрено в принципе и не планируется?

Хотя, когда у нас были все групчаты в ICQ/MRA, я четко помню, что мигало уведомление о наличии непрочитанных сообщений, и вроде закладка открывалась сама... Но теперь уже не проверить.

**Comment by georgehazan** [comment]
> А главный-то вопрос, как теперь включить, чтобы вкладка сама появлялась с новыми сообщениям?

Сделать, чтобы любое сообщение подпадало под критерий highlight, наверное.

> Или это не предусмотрено в принципе и не планируется?

Для групчатов не предусмотрено, про планируется не знаю, наверное, надо бы, чтобы оно хотя бы мигало в списке контактов, если события падают в базу данных

**Comment by SM-Sergey** [comment]
> Сделать, чтобы любое сообщение подпадало под критерий highlight, наверное.

Поставил там "*" на юзера. Поглядю. Если сработает, то в принципе и ничего пока не надо больше. Ну разве что, может, "highlight" не по юзеру или тексту сообщения, а еще по именам самих чатов, которые всегда безусловно highlight - особо важные. А пока у меня и нет неважных со смертью аськи, с ней весь "хламовый чат" погиб.
