### ISSUE TITLE
групчаты: добавить в признаки для Highlight название чата

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4600]
Просьба в признаки для "highlight" групчатов добавить помимо поиска совпадений в имени юзера и тексте сообщения, еще совпадения по названию самого групчата (как он отображается в клисте с учетом возможного локального переименования). Для чего - для того, чтобы некоторые важные групчаты, нужные например по работе, могли сами открывать вкладки в табсах по приходу новых сообщений, независимо от того, какой юзер там писал и что писал. И при этом можно было оставить highlight по юзерам/тексту в других чатах. Сейчас же единственный вариант так сделать - это внести в список "любой юзер" или "любой текст", но это сработает сразу на все чаты, что может быть излишне.

**Comment by dartraiden** [comment]
Проще в настройки мута чатов добавить новый режим.

**Comment by SM-Sergey** [comment]
Не уведомлять, а именно автоматически открывать закладку чата.

**Comment by dartraiden** [comment]
Открывать или нет, это регулируется иными настройками.

**Comment by SM-Sergey** [comment]
Открывать или нет - есть только для хайлайтнутных сообщений в групчатах, в том и дело. Именно поэтому в тикете стоит просьба уметь их хайлайтить.

**Comment by dartraiden** [comment]
https://github.com/miranda-ng/miranda-ng/issues/4698

Сделал запрос более общей фичи, которая, в том числе, решит и описанную здесь проблему.

**Comment by georgehazan** [comment]
@SM-Sergey всё это еще актуально?

**Comment by SM-Sergey** [comment]
Тут варианты. Можно сделать галку "автоматически открывать окна/вкладки с чатами с новыми сообщениями", ну и чтобы они взлетали, если у чата не установлен мут. И тогда это не надо.
В общем, нужен способ включить автооткрытие вкладок для "почти всех" групчатов, а как это будет выглядеть - через хайлайты по списку/маске названий чатов, или как-то иначе, это не важно.

**Comment by georgehazan** [comment]
> Можно сделать галку "автоматически открывать окна/вкладки с чатами с новыми сообщениями"

Такая галка есть.

> ну и чтобы они взлетали, если у чата не установлен мут. И тогда это не надо.

Т.е. надо запретить работу галки для замученных групчатов? это легко

**Comment by SM-Sergey** [comment]
А где такая галка есть? Залез в опции Message sessions / Group chats, вижу только как раньше - Create tabs or windows for highlight evets. А где галка открытия для всех чатов?

**Comment by georgehazan** [comment]
> А где галка открытия для всех чатов?

Теперь одни и те же опции контейнера по созданию табов работают и для чатов, и для групчатов

**Comment by SM-Sergey** [comment]
А! Ну тогда всё, закрыть этот тикет, ну и чтобы замученные чаты не взлетали (если вдруг взлетают).
