### ISSUE TITLE
tabSRMM: поменять местами настройку подсветки ника и дополнительных слов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4603]
Сейчас описание гласит "оставьте пустым, чтобы подсвечивать свой ник", что неверно. Для подсветки ника (который может меняться) нужно взводить следующую опцию. Если её не взвести и, вдобавок, оставить поле пустым, подсветки вообще не будет.

Нужно опцию про подсветку ника поставить первой, поле с дополнительными словами - вторым, а его описание сделать "дополнительные слова для подсветки (допускаются маски ...)

<img width="580" alt="Miranda64_mMCOfAl9FV" src="https://github.com/user-attachments/assets/f30a2011-f3a2-499c-ac0b-0ecde18c5266">

**Comment by georgehazan** [comment]
зачем менять местами?
