### ISSUE TITLE
Telegram: предпросмотр ссылок не работает, если ссылка отправлена из Миранды

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4604]
Аккаунт телеграма заведён в Миранду и одновременно в клиент на телефоне.

Отправляю ссылку из Миранды в своё избранное. Предпросмотра ссылки нет.

Отправляю ссылку с телефона в своё избранное. В Миранду прилетает с предпросмотром.

Нужно это привести к единому знаменателю.

**Comment by dartraiden** [comment]
![изображение](https://github.com/user-attachments/assets/1fe837f4-6796-460d-b330-cc3628f69f96)

**Comment by georgehazan** [comment]
duplicate of #4746
