### ISSUE TITLE
Telegram: предпросмотр ссылок во встроенных журналах

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4605]
Вот так выглядит предпросмотр телеграмной ссылки во встроенном журнале

```
[url]https://www.linux.org.ru/news/proprietary/17716638[/url]
[url][/url]
[img=C:\Users\user\Desktop\miranda-ng-alpha-latest_x64\Profiles\test\Preview\Telegram_1\{AQADO6gxG6_ZTVBy}.jpg][/img]
Vivaldi – кроссплатформенный веб-браузер, доступный на Linux, Windows, macOS, Android, Android Automotive и iOS, и отличающийся широкими возможностями настройки. Что нового: Переименование вкладок « Теперь вы можете легко переименовать свои вкладки и...
```

Проблемы:
1) Ссылку обернуло в тэг `[url]`, который встроенный журнал не понимает
2) Добавился пустой тэг `[url][/url]`

При этом, из-за https://github.com/miranda-ng/miranda-ng/issues/4601 отключить генерацию этих превьюшек невозможно. Фактически со встроенными журналами превьюшки неюзабельны.

**Comment by georgehazan** [comment]
И чо? Не забывай, у нас еще есть IEView, который это прекрасно лопает
