### ISSUE TITLE
Telegram: отправка файла в чат расценивается как новое сообщение

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4606]
Включаем уведомления миганием о входящих сообщениях в чатах

<img width="580" alt="Miranda64_bEA3cygzJS" src="https://github.com/user-attachments/assets/0e0e36a0-9adb-417d-ae83-30aa507f0962">

Пишем в телеграмный чат текст. Никаких уведомлений не появляется, что совершенно логично - т.к. это исходящее сообщение, а не входящее.

Но если кинуть в телеграмный чат картинку из Миранды, то Миранда сочтёт это входящим сообщением и изобразит мигание. Несмотря на то, что это тоже исходящее сообщение и уведомлять о нём не нужно.

**Comment by georgehazan** [comment]
У меня ничего не мигает, если в наш тестовый чат что-то зарядить

**Comment by dartraiden** [comment]
Для истории: баг срабатывал при отправке перетаскиванием в поле ввода текста. При отправке файла с помощью кнопки тулбара баг не воспроизводился.
