### ISSUE TITLE
WhatsApp: crash in "stayConnectedLoop" on reconnection + DataBase nullified (zero data).

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#461]
**Reported by Corak on 18 Oct 2015 15:44 UTC**
Got crash + my database was killed (all data zeroed)

```
Likely cause of the crash plugin: WhatsApp protocol

Exception: Access Violation at address 7C9109DA. Reading from address 00050011.

Stack Trace:
---------------------------------------------------------------
7C9109DA (ntdll 7C900000): (filename not available) (0): wcsncpy
7C91080B (ntdll 7C900000): (filename not available) (0): wcsncpy
78AB016A (MSVCR100 78AA0000): (filename not available) (0): free
177ECC45 (WhatsApp 177E0000): (filename not available) (0): WASocketConnection::`scalar deleting destructor'
177E4CA9 (WhatsApp 177E0000): e:\sources\miranda_ng_compilation\protocols\whatsapp\src\connection.cpp (46): WhatsAppProto::stayConnectedLoop
1224C554 (mir_core 12240000): e:\sources\miranda_ng_compilation\src\mir_core\src\threads.cpp (154): forkthreadex_r
78AFC556 (MSVCR100 78AA0000): (filename not available) (0): endthreadex
78AFC600 (MSVCR100 78AA0000): (filename not available) (0): endthreadex
7C80B729 (kernel32 7C800000): (filename not available) (0): GetModuleFileNameA
```

[20151018_Whatsapp_stayConnectedLoop.zip](https://github.com/miranda-ng/miranda-ng/files/649404/20151018_Whatsapp_stayConnectedLoop.zip)

[netlog.txt](https://github.com/miranda-ng/miranda-ng/files/649409/netlog.txt)

**Comment by georgehazan** [comment]
**Modified by Corak on 18 Oct 2015 15:51 UTC**

**Comment by georgehazan** [comment]
**Modified by Corak on 18 Oct 2015 15:51 UTC**

**Comment by georgehazan** [comment]
**Comment by Corak on 1 Nov 2015 06:08 UTC**
+ New Crash (without crushin base 'scalar deleting destructor').


Likely cause of the crash plugin: WhatsApp protocol

Exception: Access Violation at address 177E4E9C. Writing to address 00000AB8.

Stack Trace:
---------------------------------------------------------------
177E4E9C (WhatsApp 177E0000): e:\sources\miranda_ng_compilation\protocols\whatsapp\src\connection.cpp (77): WhatsAppProto::stayConnectedLoop
1224C536 (mir_core 12240000): e:\sources\miranda_ng_compilation\src\mir_core\src\threads.cpp (154): forkthreadex_r
78AFC556 (MSVCR100 78AA0000): (filename not available) (0): endthreadex
78AFC600 (MSVCR100 78AA0000): (filename not available) (0): endthreadex
7C80B729 (kernel32 7C800000): (filename not available) (0): GetModuleFileNameA

**Comment by dartraiden** [comment]
WhatsApp is deprecated.
