### ISSUE TITLE
Не работает предпросмотр WebP

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4610]
Собственно сабж. Для WebP-изображений вместо превью просто пустота по размеру изображения.

Это наша копия FreeImage не умеет WebP?

**Comment by georgehazan** [comment]
нет, это GDI+ не умеет, сейчас NewStory пользуется им в связке с LiteHtml

**Comment by dartraiden** [comment]
Стоит узнать у разработчиков LiteHTML, как переключиться на FreeImage.

**Comment by dartraiden** [comment]
Теперь работает.
