### ISSUE TITLE
Telegram: невозможно удалить своё сообщение у других участников чата

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4611]
При удалении своего отдельного сообщения **в групчате** недоступна опция "удалить у всех".

Таким образом, сообщение удаляется лишь из базы локально.

![изображение](https://github.com/user-attachments/assets/d49136de-6f93-436c-89b6-93a1a414d9e0)

То есть, если я случайно отправлю в чат, скажем, дикпик, то из Миранды я не могу это отменить и мой короткоствол увидят все. А вот в приватах всё отлично удаляется.

**Comment by georgehazan** [comment]
А не надо слать дикпики в чатики 🤣🤣🤣

**Comment by dartraiden** [comment]
![Смешные Открытки](https://github.com/user-attachments/assets/f67f62c9-816d-4610-9666-8c2e06876dad)
