### ISSUE TITLE
Skypeweb: Set own mood - не запрещается поле ввода кастомного кода иконки при открытии диалога

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4614]
Открываем диалог, когда уже выставлен mood - например wfh

![2024-09-05 13_30_26-Mozilla Firefox](https://github.com/user-attachments/assets/150169a0-abcb-4041-bd6b-517bf20e727d)

И наблюдаем незасеренное поле ввода для кода иконки.

Ну и все равно оно зело неудобно. Чтобы выставить mood не из списка, надо открыть файл .msl из набора смайладда от скайпа, найти там обозначение иконки, и ее ввести. Все таки хотелось бы иметь возможность выбора иконки тыком в нее, как это устроено при написании сообщения в табсах, а не таким вот череззадом. Ведь такой контрол выбора иконки уже существует.

**Comment by georgehazan** [comment]
> Ну и все равно оно зело неудобно. Чтобы выставить mood не из списка, надо открыть файл .msl из набора смайладда от скайпа, найти там обозначение иконки, и ее ввести.

Да нет же, достаточно нажать Win+. и ввести нужный смайлик.

> Все таки хотелось бы иметь возможность выбора иконки тыком в нее, как это устроено при написании сообщения в табсах, а не таким вот череззадом

Для этого надо долго сидеть и перерисовывать бесконечные глифы из скайпа. Очень лениво, если честно.

**Comment by SM-Sergey** [comment]
> достаточно нажать Win+

Недостаточно - он вставляет не то сокращение, не скайповское в скобках, а какие-то непечатные коды.

**Comment by georgehazan** [comment]
> Зачем???

Затем, чтобы вписывать в код эти самые глифы

> он вставляет не то сокращение, не скайповское в скобках, а какие-то непечатные коды

Две трети глифов - это и есть уникодные суррогаты, в скобках в основном только чисто скайповские смайлы

**Comment by SM-Sergey** [comment]
> в скобках в основном только чисто скайповские смайлы

А в данном случае нужны только они. А всё другое не катит.
