### ISSUE TITLE
Telegram: синхронизация статуса прочитанности некорректно работает для групповых чатов

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4616]
Аккаунт телеграма заведён в Миранду на десктопе. Этот же аккаунт заведён в оф. клиент на телефоне.

Кто-то пишет в групчат. С хайлайтом или просто сообщение, неважно. Если я сначала прочитаю это с телефона, то в клисте Миранды значок нового сообщения возле чата не пропадает.

В приватах всё работает корректно в обе стороны. В чатах работает корректно, если сначала прочитать в Миранде (тогда на телефоне оно пометится прочитанным). А вот если прочитать с телефона, то до Миранды с сервера не доходит мысль, что сообщение прочитано и нужно погасить уведомление.

**Comment by georgehazan** [comment]
Так это проблема телефона, если я правильно понимаю. Вопрос только в том, посылает устройство сообщение о прочтении или нет

**Comment by georgehazan** [comment]
Просто посмотри лог Миранды, возникло там сообщение о прочтении или нет. Если нет, то это можно закрывать

**Comment by dartraiden** [comment]
> Так это проблема телефона, если я правильно понимаю.

Нет, если вместо Миранды десктопный оф. клиент, в нём уведомление пропадает.

**Comment by dartraiden** [comment]
```
[3:06:10 2358] [Telegram_1] ProcessResponse: id=0 (updateChatReadInbox {
  chat_id = -1001985055038
  last_read_inbox_message_id = 502267904
  unread_count = 0
}
)
```
