### ISSUE TITLE
Подсветка (highlight) не срабатывает на ответы (reply)

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4617]
Несмотря на то, что реплай содержит мой ник (в цитируемой части), tabSRMM не расценивает его как хайлайт.

<img width="266" alt="Без имени" src="https://github.com/user-attachments/assets/fc9b034a-5ce1-422c-9025-bd8b43b89cd1">

Это очень неудобно, т.к. я просто пропускаю реплики в чате, адресованные персонально мне, ведь для Миранды они не отличаются от прочих.

**Comment by georgehazan** [comment]
В групчатах поле реплая вообще не фигурирует никак, ни в тексте события, ни в нике

**Comment by dartraiden** [comment]
Надо придумать некий костыль.

**Comment by SM-Sergey** [comment]
Кстати, это явно не всех протоколов касается. В скайпе хайлайтит, если свой ник вписать в хайлайт по тексту сообщения, ибо юзер, кого цитировали, упомянут именно там. То есть для скайпа костыль имеет место быть уже.

```
	"timestamp" : 1724833390,
	"isotime" : "2024-08-28T08:23:10Z",
	"flags" : "r",
	"body" : "[1724832975] Pavel Guryev: У Сергея проблема с инетом, ответит позже.\n\n<<< Павел, а когда примерно можно ждать предыдущий вариант белтпак арены?",
	"server_id" : "9393234217418661193",

```

Так что, этот вопрос протоколозависимый, вероятно относится конкретно к телеге.

**Comment by dartraiden** [comment]
>  В скайпе хайлайтит, 

Там, вроде, вместо реплаев цитаты.

**Comment by SM-Sergey** [comment]
> Там, вроде, вместо реплаев цитаты,

Я проверял именно на реплае.

![2024-09-08 07_49_05-Skype — Mozilla Firefox](https://github.com/user-attachments/assets/f5803aae-5f5e-4ea1-a211-88e7846be64e)

А выглядит он сейчас в NS а-ля цитата.

![2024-09-07 10_22_50-Sergey Markov (Offline)](https://github.com/user-attachments/assets/d91d6466-0d71-46af-9101-03fcc8630b20)
