### ISSUE TITLE
Highlighting: не работает для сообщений, пришедших пока был в оффлайне, и пришедших от себя самого с другого устройства.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4619]
Включаем хайлайт на юзера с именем "*", чтобы всем.
Включаем опцию "Message sessions->Group Chats->Create tabs or windows for highlight events"
Выключаем миранду.
Чего нибудь пишем в групчат (как минимум в скайп).
Включаем миранду. 
Около групчата появляется незаметный кружочек, что там что-то есть, но вкладка не открывается, и я конечно же всё пропускаю, пока мне оттуда не позвонят с укором "а ты где, почему не тут, но как бы читаешь".

Должно быть - включил миранду, и тут же, попав под такие хайлайты, повсплывало всё то, что понаписали, пока меня не было, и я все вижу сразу.

**Comment by SM-Sergey** [comment]
Вот чёрт, а теперь почему-то "не взлетело" и в обычном режиме, когда миранда в онлайне, а писал другой человек. Что-то там поломалось, сколько-то дней назад все "взлетало".

**Comment by georgehazan** [comment]
Пофиг оффлайн или онлайн, мигает как заведенное. Вкладка не подымается, это правда

**Comment by SM-Sergey** [comment]
> Вкладка не подымается, это правда

Ну вот в этом и вся суть.

**Comment by georgehazan** [comment]
> > Вкладка не подымается, это правда
> 
> Ну вот в этом и вся суть.

Нет. Суть в том, что нет хайлайта.
