### ISSUE TITLE
Tipper: last message is not last.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4620]
sys:last_msg показывает не последнее сообщение, а последнее входящее сообщение. Соответственно, надо починить, чтобы sys:last_msg показывал реальное последнее сообщение, если оно было исходящим, то тоже. А если надо, еще добавить какой нибудь sys:last_incoming (сомневаюсь в надобности)

**Comment by georgehazan** [comment]
last_msg + last_msg_out
