### ISSUE TITLE
SkypeWeb: Если я пишу что-то с другого устройства, и потом удаляю, в миранде остаются некие оскропотки от произошедшего.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4621]
Если это происходило при живой миранде в онлайне. Вот, как то так:

![2024-09-06 13_46_44-chat room (3 users)](https://github.com/user-attachments/assets/026d84a9-d35b-446b-ba57-262d685641d9)

Надо сделать, либо "халявно", чтобы ничего не оставалось, либо красиво, удобно и правильно, как в ВК, что "сообщение удалено пользователем", и само сообщение:

![2024-09-06 13_53_03 - history  4027 messages total](https://github.com/user-attachments/assets/b880e6a0-04a4-4164-bd82-5daba3d40e66)

Вот, кстати, реализация этого в ВК - прямой повод теперь туда все беседы отовсюду перетаскивать. Это просто бесценная фича, показ удаленных и отредактированных сообщений с историей редактирования. То, что в богомерзкой телеге это запрещено, не повод распространять этот запрет от самоДурова на всё кругом. Реализация этого везде, где не запрещено, уверен, тут же бы расширило круг пользователей миранды в разы.

**Comment by georgehazan** [comment]
> Это просто бесценная фича, показ удаленных и отредактированных сообщений с историей редактирования.

Миранда пишет в текстовые файлы вообще всё, плагин MsgExport в руки

**Comment by georgehazan** [comment]
А что такое "оскропотки" ?

**Comment by SM-Sergey** [comment]
> А что такое "оскропотки" ?

Ну вот две пустые строки "Сергей Марков:" на скриншоте. Одна от оригинального сообщения, которое было до удаления, вторая от самого евента удаления.

**Comment by SM-Sergey** [comment]
> Миранда пишет в текстовые файлы вообще всё, плагин MsgExport в помощь

Ну вот в ВК это же уже сделано красиво и удобно, и без плагинов. Прямо в NS все сразу видно. Почему бы это не распространить вообще на все протоколы, где не запрещено политикой владельца?

**Comment by SM-Sergey** [comment]
> плагин MsgExport в помощь

ну-ну... Вот результат экспорта.

Дмитрий          29-Aug-24 17:03:26 ок, т.е. предварительно из прогнозных дат должны успеть если не будет накладок. Ждем
Сергей Марков    06-Sep-24 13:16:00 Unknown event type 0, size 0

Никакой полезной информации о том, что сообщение было, и потом оно удалено. Нельзя просмотреть то, что удалилось.

**Comment by georgehazan** [comment]
> Никакой полезной информации о том, что сообщение было, и потом оно удалено. Тут нельзя просмотреть то, что удалилось.

Мы об истории редактирования или где?

**Comment by SM-Sergey** [comment]
> Мы об истории редактирования или где?

Мы и об истории редактирования, в ВК + NS это выглядит так (красиво, удобно):
![2024-09-06 15_22_26-Павел Гурьев - history  4027 messages total](https://github.com/user-attachments/assets/6289a227-d42d-4958-8cf3-c6acb1016045)

И об истории удаления, в ВК+NS - так:
![2024-09-06 15_22_55-Павел Гурьев - history  4027 messages total](https://github.com/user-attachments/assets/770d110a-62a8-42f6-90d5-7257a859bb58)

Если это как-то централизовано распространить на все протоколы, в которых это не запрещено Партией и Правительством (а это, вроде, всё, кроме телеги) - будет шикарно и прекрасно.

**Comment by georgehazan** [comment]
> Если это как-то централизовано распространить на все протоколы, в которых это не запрещено Партией и Правительством (а это, вроде, всё, кроме телеги) - будет шикарно и прекрасно.

Пробовали уже, полное дерьмо. Наоборот, это старательно вынесли отовсюду, где только можно. Надо делать какой-то плагин для управления историей редактирования сообщений, а вот эти портянки в тексте сообщений - это полная лажа

**Comment by SM-Sergey** [comment]
портянки, согласен, лажа. А вот спойлерчик бы с портянкой - было бы неплохо.

**Comment by georgehazan** [comment]
> портянки, согласен, лажа. Но лажа лучше, чем вообще ничего.

Троблема не в этом, проблема в том, что ты видишь совершенно не ту картину, которую видит чел в оф. клиенте. Ты ему говоришь "третье сообщение снизу", а у тебя там сидит запись об удалении - и привет.

**Comment by SM-Sergey** [comment]
Это можно сделать включаемым - надо увидеть, что там кто вытер, когда начинается "а я этого не говорил" - включил галку (хватит только в NS), и вот оно всё. А галку выключил - и "как в оф. клиенте".
