### ISSUE TITLE
Highlighting: в трее ничего не происходит, несмотря на галку о трее в настройках.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4622]
Хайлайт настроен на юзера "*" 
Стоит галка трея на хайлайт евенты.

![2024-09-06 14_34_20-Miranda NG options](https://github.com/user-attachments/assets/df245041-b415-43aa-81e6-8fef23062af3)

Но трей молчит по приходу сообщений.

**Comment by SM-Sergey** [comment]
Закладка в табсах для этого чата разумеется не открыта.

**Comment by georgehazan** [comment]
нормально там всё уже
