### ISSUE TITLE
SkypeWeb: поддержать чат с "самим собой".

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4623]
В оф. клиенте есть "я сам" - "Сергей Марков (You)"

![2024-09-06 17_04_19-Skype — Mozilla Firefox](https://github.com/user-attachments/assets/d1f6dec7-aa4b-464c-9f22-6de2526ece29)

Я туда написал чего-то типа "test". В миранду прилетел некий нонейм:

![2024-09-06 17_02_14-Miranda NG](https://github.com/user-attachments/assets/c900bdc8-ab21-4007-a465-9f2fe7db77d9)

И сообщение туда дошло. Я его как-то с ручным переименовыванием добавил в клист, однако отправить я туда из миранды ничего не могу, ругается! Надо сделать, чтобы такой контакт понимался сам как контакт с именеми <Мой ник (You)> - как в оф. клиенте, и от него можно было писать сообщения и слать файлы самому себе.

**Comment by georgehazan** [comment]
Тихо сам с собою, тихо сам с собою, я веду бесе-е-еду....

**Comment by dartraiden** [comment]
> Ну и видимо заодно и "Copilot",

Про это есть тикет.
