### ISSUE TITLE
Official ReactOS and Wine support

### ISSUE THREAD

**Issue by stokito** [miranda-ng/miranda-ng#4627]
On my Ubuntu 22.04 I installed from MSI package but when to started the CPU load increased but no any window appeared.
The wiki [Miranda under Wine](https://wiki.miranda-ng.org/Miranda_under_Wine) helped but it would be really nice if it can work just out of the box.

The WineHQ has a DB of known applications that has the [compatibility page](https://appdb.winehq.org/objectManager.php?sClass=version&iId=29828). Maybe you can update it?

Additionally I checked if the Miranda works on the ReactOS and it looks like their repo has an [entry for the old original Miranda IM](https://github.com/reactos/rapps-db/blob/master/mirandaim.txt). So maybe you can update it too and test?

**Comment by georgehazan** [comment]
Привет, Миранда 64 бита идеально идет под свежим winehq 9.17, почти без глюков, с NewStory в качестве журнала, но с некоторыми ограничениями (например, не работают глобальные хоткеи). Kubuntu 24.04.

Про ReactOS ничего не знаю, ибо нет никакого интереса это раскапывать.

**Comment by georgehazan** [comment]
Выдал запрос на то, чтобы стать мейнтейнером на https://appdb.winehq.org

**Comment by georgehazan** [comment]
> The wiki [Miranda under Wine](https://wiki.miranda-ng.org/Miranda_under_Wine) helped but it would be really nice if it can work just out of the box.

Вот этот трэш с отдельным профилем я так и не понял. Миранда прекрасно ставится в общий профиль в ~/.wine и работает на ура. Всё ставится из коробки и работает

**Comment by georgehazan** [comment]
> WineHQ и просто wine это одно и тоже?

Wine HeadQuarters - это набор сайтов, поддерживающих Wine. wine - это название программы

> Я так понял нужно поставить их [репозиторий](https://gitlab.winehq.org/wine/wine/-/wikis/Debian-Ubuntu) для более свежей версии.

Под убунтой есть отдельный пакет wine-devel, который ставит самый-самый свежак. Я перелез на него, потому что там реально меньше проблем, ибо реализовано больше костылей для ядра винды 😁

> Но мне не критично, просто хотелось услышать от вас "да, мы хоть немного, но официально поддерживаем такой изврат".

До тех пор, пока у меня на десктопе Линукс, то будем поддерживать 100%

> А пляски с "Initializing Wine profile" ещё нужны? И это работает портабл версия или которую через инсталятор ставить?

Нет, не нужны, надо просто ставить всё в общий профиль Wine в ~/.wine. Wiki поправил

**Comment by georgehazan** [comment]
> Не `winehq-devel` а всё таки `winehq-devel`

А в чём разница?

> нужно прописывать их репозиторий

Вероятно, да. У меня есть их репа в списке apt sources, да и на их сайте рекомендуют.

> иконки чёрные

Я им забил этот баг, но чтобы его пофиксить, им надо целую функцию реализовать.
