### ISSUE TITLE
Skypeweb: не работает удаление сообщения с сервера.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4630]
Чего нибудь пишем кому нибудь. Потом удаляем в NS с галкой "удалить с сервера". Открываем оф. клиент, а оно там есть! И там уже это можно удалить совсем.

**Comment by georgehazan** [comment]
Там раньше сообщения маркировались с неверными id, поэтому удаляться будут только новые сообщения. Если есть групчат, то можно счистить локальную историю и передернуть с сервера, тогда они будут чиститься норм

**Comment by SM-Sergey** [comment]
> то можно счистить локальную историю и передернуть с сервера,

Будет можно, когда #4579 будет решен. А пока - оно втягивает только некоторый последний кусочек общения.
