### ISSUE TITLE
E-mage LAN protocol: missing documentation

### ISSUE THREAD

**Issue by stokito** [miranda-ng/miranda-ng#4631]
I'm trying to understand what is this protocol for. It's wiki page is empty
https://wiki.miranda-ng.org/index.php?title=Plugin:EmLanProto

As far I understood this is not some existing serverless LAN chat but the Miranda only plugin.
It looks like it's too old and it didn't worked.

It also doesn't come with the Miranda installer and needs to be downloaded separately. Maybe you can add all the protocols to an installer for lazy people?

**PS**
Just in case if anyone looking for a LAN chat:
There is a Pidgin that supports a limited XMPP [XEP-0174: Serverless Messaging](https://xmpp.org/extensions/xep-174.html) aka Bonjour that can be used for a basic text only conversation.
The Miranda doesn't support it #4632.

Another option is Friendly Chat which is an old but nice chat for Windows. I made a Pigin plugin for Linux https://github.com/stokito/pidgin-fchat

Jammi and Meshanger are the only two Android apps that can talk over LAN but they still rely on internet for discovery and signaling.

There is also https://github.com/warren-bank/Android-Bonjour-WebRTC Android app that allows device discovery on WLAN (w/ Bonjour) and video calls to be placed between devices on WLAN (w/ WebRTC) without any external server. But I didn't tried it yet.

**Comment by georgehazan** [comment]
Это старый добрый NetBIOS, аналог того, что в винде называется net send
@stokito просьба не использовать баг трекер для вопросов, для этого есть форум
