### ISSUE TITLE
Jabber:  Show a list of a public XMPP servers where a user can register an account

### ISSUE THREAD

**Issue by stokito** [miranda-ng/miranda-ng#4634]
One of the strongest problem for newcomers is to get a Jabber account.
We should simplify this process as much as possible.
The Miranda already supports [XEP-0077: In-Band Registration](https://xmpp.org/extensions/xep-0077.html). One next thing is to help to a user to find a server that allows it.

The Miranda shows the `jabber.org` as a default server. But it currently doesn't allow a registration but they promise to enable it again https://www.jabber.org/faq.html#account.

There is a curated list of such servers https://providers.xmpp.net/.
It has a simple classification were the class A list contains only a dozen of servers.
Basically many of them also requires a CAPTCHA that is not properly supported by the Miranda.
There is only three servers without a CAPTCHA: `jabber.fr`, `xmpp.earth`, `yax.im`.

So as a first step we should show the list of servers to a user. In the simplest form we can just include the list of A-class servers into sources. We may also download the [full list of class-C providers](https://data.xmpp.net/providers/v2/providers-C.json) but honestly from a user perspective it should be enough to pick just one random A server to create his first account.

Please check the list of implementations in other clients: https://invent.kde.org/melvo/xmpp-providers/-/issues/44

**Comment by dartraiden** [comment]
Серверы все разные, у всех разные поддерживаемые фичи.

**Comment by georgehazan** [comment]
> это зря т.к. обычный пользователь не сможет зарегаться вообще а просто бросит это дело.

Если пользователь не знает, на каком сервере ему регистрироваться, то реально проще бросить. Восстановления списка серверов точно не будет
