### ISSUE TITLE
Jabber: simplify account registration

### ISSUE THREAD

**Issue by stokito** [miranda-ng/miranda-ng#4636]
New users must get an account as easily as possible to make it accessible for average users.
Currently in the Miranda this is a complicated process.

Here is a description (WIP) of how the whole process ideally should be implemented https://github.com/modernxmpp/modernxmpp/issues/7

* #4634
* The registration button should be replaced with a wizard
* Add a native support of a CAPTCHA during registration. A good news that we can reuse the jabber_captcha.cpp

**Comment by georgehazan** [comment]
> Currently in the Miranda this is a complicated process.

Вот и хорошо. Вообще эра XMPP в значительной степени прошла еще лет пять назад.
