### ISSUE TITLE
Jabber: avatat file size is not checked

### ISSUE THREAD

**Issue by stokito** [miranda-ng/miranda-ng#4637]
### Using
Using a dev build under wine.

### Expected behavior
In the Jabber code for vCard there is a check that should show an error "Only JPG, GIF, and BMP image files smaller than 40 KB are supported"

https://github.com/miranda-ng/miranda-ng/blob/b06d84eef8004575a874486119cbefc382e94e74/protocols/JabberG/src/jabber_vcard.cpp#L386

I was afraid that I won't be able to set my avatar that is slightly bigger but it worked.
It looks like the check didn't happened.
Interesting that the actual avatar was resized and to a server was sent a small JPEG. The server actually converted the avatar to PNG and from another client I received it as a small plain PNG.

So maybe the size check is not needed at all?
If you think it's needed then anyway it should be extended to 72 KiB.
Please see the Modern XMPP recommendations https://github.com/modernxmpp/modernxmpp/issues/62

**Comment by georgehazan** [comment]
Ну да, это прилетело из каких-то незапамятных времен...
