### ISSUE TITLE
Telegram: "Mute never" сбрасывается при переподключении протокола к сети

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4638]
Выставляем телеграмному чату Mute: Never и уводим протокол в оффлайн. При следующем выходе в сеть мут сбрасывается на Default.

При этом, Mute: Always ведёт себя корректно и не сбрасывается.

**Comment by dartraiden** [comment]
Второй баг из этой же оперы:
- Выставляем чату Mute: Always
- Меняем тут же на Mute: Never

Результат: вместо Never выставляется Default.

**Comment by georgehazan** [comment]
> Выставляем телеграмному чату Mute: Never и уводим протокол в оффлайн. При следующем выходе в сеть мут сбрасывается на Default.

При логине статус mute выставляется по серверу.

**Comment by georgehazan** [comment]
Я тебе больше скажу: фактически в телеге вообще нет такого понятия, как Mute Never

**Comment by georgehazan** [comment]
> Результат: вместо Never выставляется Default.

И это правильно

**Comment by dartraiden** [comment]
По-прежнему Never скидывается при переподключении телеграма к сети.
