### ISSUE TITLE
Telegram: невозможно скорректировать ошибочно введённый номер телефона

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4645]
Завожу учётку в Миранду. Ошибся в одной цифре телефона. Соответственно, код подтверждения улетает либо в чужую сессию (если номер зарегистрирован), либо от сервера возвращается ошибка, что такой учётки нет.

После этого Миранда не позволяет скорректировать номер. Если в настройках поменять номер, то Миранда продолжает долбиться на старый номер. Кнопка "Log out" неактивна, т.к. вход не произведён. Только стирать binlog вручную (о чём неискушённый пользователь не знает) или учётку убивать.

Мы можем при изменении номера телефона в настройках учётки убивать старый binlog?

**Comment by georgehazan** [comment]
> Если в настройках поменять номер, то Миранда продолжает долбиться на старый номер.

Даже после рестарта?

**Comment by dartraiden** [comment]
Даже после.
