### ISSUE TITLE
Telegram: имя чата меняется в Миранде лишь при переподключении

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4646]
Владелец чата меняет имя чата через оф. клиент.

Миранда, сидящая в этом чате,  отображает в журнале это как смену топика, но подтягивает новое имя (переименовывает чат в базе) лишь при переподключении протокола к сети.

Предлагаю переименовывать на лету

**Comment by georgehazan** [comment]
Оно и переименовывается на лету, меняя поле Nick. Если у тебя клист вместо ника показывает что-то еще, то меняться на лету оно не будет

**Comment by dartraiden** [comment]
Поле Nick не меняется на лету.

Хватит закрывать валидные тикеты.
