### ISSUE TITLE
Telegram: настройка "Generate URL Preview" работает некорректно

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4648]
Когда я просил эту опцию, я предполагал, что её отключение будет возвращать нас к поведению, которое было в прошлых версиях, когда протокол не умел в предпросмотр ссылок. Ссылка была тупой ссылкой.

Что мы имеем сейчас:

### Баг 1
если с выключенной опцией  "Generate URL Preview" кинуть в чат URL картинки, то картинка не показывается, но место в журнале под неё резервируется, получается большое пустое пространство

![изображение](https://github.com/user-attachments/assets/a97176b8-d879-4689-9eb8-e12b2e7229e8)

### Баг 2
если с выключенной опцией  "Generate URL Preview" кинуть в чат URL сайта, то кроме пустой превьюшки (это следствие бага 1) ещё отображается title страницы.

**Comment by dartraiden** [comment]
Собственно, хотелось бы, чтобы в обоих случаях (когда оация выключена) ссылки были тупо ссылками.

**Comment by georgehazan** [comment]
Не знаю, почему оно у тебя не показывается, у меня всё прекрасно покзывается даже в отсутствие тегов [url]
![image](https://github.com/user-attachments/assets/eae504ee-e35f-4ec7-9e49-26a4e61a43f1)

> ещё отображается title страницы.

А парсинг урлов в телеге никто не отменял
