### ISSUE TITLE
Steam crash

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#465]
**Reported by mataes on 12 Nov 2015 06:35 UTC**
hi. here is call stack
http://pastebin.com/n5mzPdyT

**Comment by georgehazan** [comment]
**Comment by robyer on 30 Jun 2016 13:40 UTC**
Is this still a problem? Maybe it was related to (already fixed) OpenSSL bug?

**Comment by Robyer** [comment]
I'm closing this as too old and probably fixed. If it still happens, open new issue, please.
