### ISSUE TITLE
Окно сообщений: кнопки форматирования текста работают в приватах, но не в групчатах

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4650]
Получается бредовая ситуация:

- В приватах любого протокола мы разрешаем использовать эти кнопки. Мы не заботимся о том, будет ли кто-то это форматирование обрабатывать на "той стороне"
- В групчатах любого протокола мы не разрешаем это использовать, потому что почему-то заботимся.

Давай уберём эти двойные стандарты. Вариант:

- раз мы не паримся про приват, тупо разрешим юзать их в и групчатах и на этом всё. Не паримся там - не паримся и тут.

- переделаем эти кнопки таким образом, чтобы они в протоколах, умеющих форматирование (Telegram, например), делали форматирование, а в протоколах не умеющих - делали ББКоды (всё лучше, чем ничего, вдруг на той стороне журнал, умеющий ББКоды)

В любом случае это надо привести к единому знаменателю, а то сейчас двойные стандарты в полный рост.

**Comment by georgehazan** [comment]
как ббкоды они приходят, что тут непонятного

**Comment by georgehazan** [comment]
ок, не паримся, так не паримся
