### ISSUE TITLE
NewStory+tabSRMM: Форматирование текста по-разному работает в приватах и чатах

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4651]
Отправляю в приват жаббера текст курсивом (кнопка на тулбаре табсов).
Отправляется простой текст, никакого форматирования и кодов.

Отправляю в чат жаббера текст курсивом
Отправляется `%iтекст%I`

Не знаю, какое поведение корректное, но то, что оно разное в рамках одного протокола, это непорядок.

**Comment by dartraiden** [comment]
Кроме того, это вовсе не ББКоды, как было обещано

**Comment by georgehazan** [comment]
В приват летят ббкоды, если их включить в табсах (general - allow bbcodes).
А вот в групчаты оно летит в формате IRC, потому что до этого было только в ирке

**Comment by dartraiden** [comment]
Давай сделаем в чатах, как в приватах. Или IRC пострадает?

**Comment by georgehazan** [comment]
IRC сдохнет, да. Т.е. система разрешений на уровне протокола вообще не давала вставлять эту помойку, если протокол не поддерживает, но вставляло оно только в формате IRC

**Comment by georgehazan** [comment]
вероятно, надо сделать так, чтобы ббкоды летали везде, а ирка перед отсылкой меняла их на то, что нужно
