### ISSUE TITLE
Scriver: аватар перекорёжило

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4656]
Пользователь столкнулся с тем, что после недавних обновлений в скривере перекорёжило аватар.

Не удаётся повторить на чистом профиле, но на его профиле воспроизводится стабильно, обращайся.

**Comment by georgehazan** [comment]
в каком смысле "перекорежило"? можно скриншот хоть

**Comment by dartraiden** [comment]
Ничего визуально не изменилось.

**Comment by georgehazan** [comment]
> Ничего визуально не изменилось.
> Аватар заставляет смещаться влево панель кнопок, а иногда и журнал.

Изменилось, для этого надо понимать суть проблемы. Тулбар в скривере всегда расположен левее аватара, только раньше он не давал ресайзеру опускать тулбар ниже аватара на высоту тулбара, а теперь дает.

**Comment by dartraiden** [comment]
Не понимаю, я подвигал тулбар до обновления. Обновился. Подвигал после обновления. Ни малейшей разницы.

**Comment by dartraiden** [comment]
Покажи, пожалуйста, как эту разницу увидеть, я ведь не могу написать пользователю "мы сделали изменения, но для вас ничего не изменится"

Вот скривер ДО фикса

![vmware_OevS7xaJv2](https://github.com/user-attachments/assets/274bcaa0-ad3f-4a5e-9da6-747577375d28)

Вот скривер ПОСЛЕ фикса


![vmware_jQBHBDTaoU](https://github.com/user-attachments/assets/52ddc31a-9d26-409d-8bad-91ad266b7300)

**Comment by georgehazan** [comment]
До фикса оно доезжало до верхнего края аватара и вставало.

**Comment by georgehazan** [comment]
> Как после поднятия тулбара аватар зачем-то имел выше себя пустое пространство, которое сдвинуло тулбар вправо - так и есть.

Так всегда и было.
