### ISSUE TITLE
NewStory: не отображается предпросмотр

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4657]
Все настройки утверждают, что предпросмотр должен быть.

Картинка автоскачивается на диск.

Но предпросмотр не виден, словно файл не скачан.

Профиль дам по запросу.

**Comment by dartraiden** [comment]
Не исправлено.

**Comment by georgehazan** [comment]
> Картинка автоскачалась, но в журнале по-прежнему только "Picture"

Вкратце - нет. Если бы она скачалась, там была бы зеленая галочка

**Comment by dartraiden** [comment]
Ну на диске я её вижу.

**Comment by SM-Sergey** [comment]
> была бы зеленая галочка

> Ну на диске я её вижу.

Подобное недавно было в скайпе, когда оно как бы скачалось, но размером меньше, чем было заявлено в протоколе, и поэтому не считалась скачанным. Может, оно же?

**Comment by dartraiden** [comment]
Ещё наблюдение

Прилетает картинка. Автоскачивается Мирандой. Отправитель тут же удаляет событие. Из базы в Миранде оно тоже сразу удаляется.

Но картинка остаётся на диске и в клисте моргает входящий файлтрансфер.

**Comment by dartraiden** [comment]
Да, как и было предсказано Зальцманом (с) гадит режим шифрования базы "Total"

**Comment by SM-Sergey** [comment]
> Но картинка остаётся на диске и в клисте моргает входящий файлтрансфер. Хотя события уже нет, 

А тут то в чем проблема? Скачанный файл не евент - что скачано, то скачано, это желание юзера (в т.ч. и авто), и никак не должно быть удалено иначе, чем этим же юзером лично. Совершенно ожидаемое и правильное поведение! Скачано - уведомлено!

**Comment by dartraiden** [comment]
Проблема в том, что включена опция "стирать файл при удалении события, с которым он связан"

**Comment by SM-Sergey** [comment]
>  Файл это контент, содержащийся в событии.

Это так только пока я его не скачал. Так работают все официальные клиенты во всех браузерах. Пока я его не скачал - он да, часть евента. Как только я его скачал (в т.ч. и автоскачиванием) - это копия этого файла на моем носителе, и никак иначе! И никакой клиент никак не может стереть файл на моем диске, мной скачанный.
