### ISSUE TITLE
tox crash on bootstraping

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#466]
**Reported by mataes on 12 Nov 2015 06:37 UTC**
call stack and parameters values:
http://pastebin.com/UBzCZ45r
http://pastebin.com/wXPYRLU5

i think it crashes coz toxThread is NULL, but why it is NULL and why it not returned at the begining....

**Comment by georgehazan** [comment]
**Comment by mataes on 12 Nov 2015 06:43 UTC**
one more call stack- this is another thread
http://pastebin.com/fUahFedL

I think in this thread tox set toxThread = NULL BUT in main thread tox trys bootstrap it

**Comment by aunsane** [comment]
Very old rare crash. There no any sense to reproduce and fix it.
