### ISSUE TITLE
tabSRMM+NewStory: при выделении сообщения с форматированием пропадают кнопки тулбара

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4667]
В приват прилетает сообщение курсивом.

Выбираем это событие мышкой.

Результат: с тулбара табсов пропадают все кнопки.

**Comment by SM-Sergey** [comment]
Они и иначе пропадают другим образом.  Пока не могу сказать точно, но пару раз пропадали в обычном общении

**Comment by SM-Sergey** [comment]
Дошло - при клике на ссылки тоже самое.
