### ISSUE TITLE
Group chats: хайлайты не работают на свои сообщения.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4669]
Пишу с другого девайса в групчат. Стоит хайлайт на юзера "\*" - я тоже юзер, и попадаю под эту "\*". Но чат "не взлетает" по взведенной галке открытия окна по хайлайтнутому сообщению. Открываю руками - там сообщение есть.

**Comment by georgehazan** [comment]
да, всё так. свои сообщения с других устройств оно молча сглатывает, только в лог пишет
