### ISSUE TITLE
SkypeWeb: при создании нового групчата не обновляется его название в табсах

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4671]
Создаю из оф. клиента новый групчат.
В миранде он появляется.  По правилу хайлайта всего и открытия окон/вкладок для хайлайтнутых сообщений окно с ним "взлетает", но в его заголовке он числится как "ID" из кучи букв и цифр. Потом в клисте он получает нормальное название, но открытая с ним вкладка до ее переоткрытия название не меняет, остается из буквоцифр. А должна бы получить нормальное название.

**Comment by SM-Sergey** [comment]
похоже, это не отдельный глюк, а следствие #4672 - это вообще левая вкладка открывается

**Comment by dartraiden** [comment]
Дубликат https://github.com/miranda-ng/miranda-ng/issues/4658
