### ISSUE TITLE
Highlighting: При автооткрытии вкладки в табсах по обнаружению хайлайтнутых сообщений в групчате открывается не то.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4672]
В табсах открывается вкладка не групчата, а непойми чего с именем из ID-а, вот так выглядит.

![2024-09-13 16_41_57-New Issue · miranda-ng_miranda-ng — Mozilla Firefox](https://github.com/user-attachments/assets/8e93893c-f7df-4a83-b0f2-a9910026d661)

А должно было открыться вот такое, как по дабл-клику на чате

![2024-09-13 16_44_15-New Issue · miranda-ng_miranda-ng — Mozilla Firefox](https://github.com/user-attachments/assets/c41a7465-a0b8-43c0-9d8f-56e2b38f4a5e)

**Comment by SM-Sergey** [comment]
И я ничего не понимаю... Почему-то сообщения, которые мне присылают в этот чат, видны только в этом "левом" окне, а в нормальном окне чата пусто... То есть в БД они есть, а окно чата их не показывает, история, открытая из окна чата - тоже. А история из этого "левого" окна - показывает.

**Comment by SM-Sergey** [comment]
После перезапуска миранды - сообщения в окне чата появились.

**Comment by SM-Sergey** [comment]
Не работает. Всё равно автооткрывается окно привата, но с содержимым групчата, без списка пользователей:

![2024-09-16 11_48_44-TR-806M (DECT) (Online)](https://github.com/user-attachments/assets/b67b9c3d-afae-4c95-8539-cedbbc2ce9c0)

А должно было открыться вот так:

![2024-09-16 11_52_32-Highlighting_ При автооткрытии вкладки в табсах по обнаружению хайлайтнутых сооб](https://github.com/user-attachments/assets/73deb91f-f957-4e4f-b5af-b631329a21e2)

**Comment by georgehazan** [comment]
это пофикшено уже
