### ISSUE TITLE
Telegram: после удаления события новое событие появляется лишь при переоткрытии чата

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4674]
Открываем в Миранде групчат.

Кто-то закидывает в чат сообщение (любое, допустим, текст)

Сообщение тут же отображается в Миранде

Автор сообщения удаляет сообщение и отправляет другое

Результат: в базу это новое сообщение приходит и укладывается, но вот в журнале оно не покажется до переоткрытия окна

**Comment by georgehazan** [comment]
техничное наебалово, даже С++ не помог
