### ISSUE TITLE
Не работают кнопки форматирования в StdMsg/Scriver

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4675]
В этих плагинах нет табсовой опции "разрешить ББКоды в исходящих сообщениях".

Поэтому кнопки форматирования там, похоже, чисто для красоты, они не работают. Может, работают в IRC, не проверял.

В TG и прочих протоколах точно не работают - посылается обычный текст.

**Comment by georgehazan** [comment]
раньше они показывались только в групчатах и только в IRC-каналах, а работали только в табсах
можно вернуть как было раньше - регистрация этих 5 кнопок только в табсах

**Comment by dartraiden** [comment]
В приватах StdMsg/Scriver кнопки пропали. В чатах остались и они не работают по-прежнему.

**Comment by georgehazan** [comment]
> В приватах StdMsg/Scriver кнопки пропали.

Согласно настройкам. Я кстати сделал, что если форматирование в настройках выключено, то кнопки блокируются
