### ISSUE TITLE
Skypeweb: unknown event in groupchat

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4681]
```
19:a034333ae9804ca08ca258b265ed65a4@thread.skype, 17.09.2024, 18:25:
Unknown event, please send this text for developer: "<addmember><eventtime>1726586118988</eventtime><initiator>8:oleg.ryzhoff</initiator><target>8:live:.cid.6ee8c9231c1ee387</target></addmember>"

```

Это вот что:
![2024-09-17 18_30_49-Skype — Mozilla Firefox](https://github.com/user-attachments/assets/24ba07b0-4d97-40ed-87c4-0ba3ec2685a0)

**Comment by SM-Sergey** [comment]
Кстати, этот контакт прилетел в список, но ник для него не запросили с сервера, так и висит как ".cid.6ee8......"

**Comment by georgehazan** [comment]
дубликат #4670
