### ISSUE TITLE
NEN: опция "не показывать вспл. окно, если окно сообщений открыто" не расценивает неактивное или свёрнутое окно как открытое

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4683]
<img width="508" alt="Miranda64_aB3gRRsVsj" src="https://github.com/user-attachments/assets/04700835-e4b8-4fac-b079-704a160c3fb2">

Речь о первой опции.

Раньше, если окно активно, неактивно или свёрнуто, попапов не было. Главное, что оно в принципе есть. Как и гласит текст опции.

После некоего изменения (уже портированного в стаблю) открытое окно считается открытым, только если оно активно

**Comment by SM-Sergey** [comment]
Но по логике это совершенно правильно - если окно "где-то" в заднице мира, а не на переднем плане, то уведомление нужно, так как пользователю не видно, что сообщение пришло.

**Comment by apollo2k4** [comment]
> Но по логике это совершенно правильно - если окно "где-то" в заднице мира, а не на переднем плане, то уведомление нужно, так как пользователю не видно, что сообщение пришло.

Возражаю! Если окно открыто, но свёрнуто или не активно попапы не впились. Я вижу что там что-то произошло, пусть себе мирно симофорит пока я туда не гляну. Если окна нет – пусть покажет.

**Comment by dartraiden** [comment]
Сначала надо вернуть как было. Потому что название опции сейчас не соответствует поведению.

**Comment by SM-Sergey** [comment]
> Если окно открыто, но свёрнуто или не активно попапы не впились.

Если окно открыто, но не активно, то 99.9%, что оно перекрыто другим окном, а это значит, что ничего в нем не видно. За редким исключением двух-трех мониторов.

**Comment by dartraiden** [comment]
```
[21:17] ghazan, 17.09.2024, 21:14:14
#4290

ghazan, 17.09.2024, 21:14:54
вот в процессе фикса этой хрени оно и началось

ghazan, 17.09.2024, 21:15:08
-		if (mwd.hwndWindow != nullptr && (mwd.uState & MSG_WINDOW_STATE_EXISTS))
+		if (mwd.hwndWindow != nullptr && (mwd.uState & MSG_WINDOW_STATE_FOCUS))
```

**Comment by SM-Sergey** [comment]
> #4290

так там же прямо стоит галка - "показывает всплывающее окно, если окно чата не активно" - она ясень пень должна быть приоритетнее.

**Comment by apollo2k4** [comment]
> Если окно открыто, но не активно, то 99.9%, что оно перекрыто другим окном, а это значит, что ничего в нем не видно.

Открыто два окна с разными контактами – я вижу их, активно только одно окно, я получаю попапы из того окна которое и так вижу, там достаточно симофора, окно должно посигналить что там что-то произошло и всё, а не сверкать попапами.

Хотите попапы – не возражаю, но не поведением по умолчанию.

**Comment by SM-Sergey** [comment]
> Хотите попапы – не возражаю, но не поведением по умолчанию.

так, собственно галка есть, и она работает корректно, именно когда окно не активно:

![2024-09-17 21_56_26-Miranda NG options](https://github.com/user-attachments/assets/7aacf046-e044-4b3d-963c-71cc73b134a4)

А та галка видимо к приватам относится, что ли. Но тогда странно, почему для групчатов это сделано удобно, а для приватов урезано.

> Открыто два окна с разными контактами – я вижу их, 

Я так даже не умею, в табсах разумеется.

**Comment by apollo2k4** [comment]
> А та галка видимо к приватам относится, что ли. Но тогда странно, почему для групчатов это сделано удобно, а для приватов урезано.

Эта галка тоже отключена.

> Я так даже не умею, в табсах разумеется.

Исторически сложилось, отключены табы, каждый контакт – отдельное окно.

**Comment by SM-Sergey** [comment]
У меня кстати эта галка работает именно как по описанию - у меня по приходу нового сообщения (приват) автооткрывается окно чата, но остается не активированным (такая галка стоит). И попап не всплывает.

А в групчатах работает та групчатная галка - там для хайлайтнутых сообщениях попап всплывает именно тогда, когда окно не активно, в соответствии с той галкой. Так что я вроде пока проблем не вижу.
