### ISSUE TITLE
Skypeweb: не видит покидание чата пользователем.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4685]
Вчера во время тестов заметил.

Это в официальном - юзер покинул чат, и там 2 пользователя осталось.
![2024-09-19 11_31_10-(1) Skype — Mozilla Firefox](https://github.com/user-attachments/assets/fc4f4626-4c10-4321-bfcd-5b8b0f7b5252)

Миранда не заметила потери бойца от слова совсем.
![2024-09-19 11_32_28-test_ chat room (3 users)](https://github.com/user-attachments/assets/4c7f4e89-dc7e-4248-84b7-fbb8ac069c56)

При этом вчера вроде проскочило сообщение в журнале на "белом фоне" что-то про "kicked", но больше его найти не удалось, ни в журнале, ни в истории чата, ни в системной истории. Скорее всего оно было видно, пока не исправился баг #4672 , и окно всплывало как приват, а не чат. 

Хотелось бы видеть в истории записи о том, кто когда приходил в чат, и когда покидал. А в списке юзеров чтобы юзер, покинувший чат, или скрывался, или около него крест был, типа что он был, а больше его нет

**Comment by georgehazan** [comment]
> При этом вчера вроде проскочило сообщение в журнале на "белом фоне" что-то про "kicked"

Всё так. В Миранде сообщения о том, что кто-то покинул чат являются временными, они живут в памяти до тех пор, пока миранда не выключится. By design, как говорится

**Comment by SM-Sergey** [comment]
Так а почему ушедший пользователь в списке показан? И никак не помечен, что он уже зомби.
