### ISSUE TITLE
TabSRMM: при автооткрытии новой вкладки что-то не то с размерами окна.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4687]
Автооткрытие вкладки привата - мне написали, вкладка открылась. Я в нее тыкаю, активирую - и "галки" файлов находятся за пределами видимости. Из-под скроллбара только их хвостики на пиксел.

![2024-09-19 19_18_21-Mrkov Sergey (Online)](https://github.com/user-attachments/assets/cba09b85-ef7f-4704-987b-4a314968a68b)

Стоит еще чего нибудь с этим окном сделать, изменить размер, или деактивировать-активировать, и все нормализуется..
При не-автооткрытии, либо для групчатов - все ОК.

**Comment by georgehazan** [comment]
Фликер будет... если на каждый ресайз окно перерисовывать

**Comment by SM-Sergey** [comment]
Чего это на каждый? По дабл-клику в клист все же нормально открывается? А почему автооткрытие не?

**Comment by georgehazan** [comment]
> Чего это на каждый?

Открытие таба в контейнере - это 5 или 6 ресайзов. Чтобы окно при этом не дрыгалось, часть из них блокируется, в результате не отрабатывается изменение вьюпорта, когда появляется вертикальный скроллбар (он и скрывает галки)
