### ISSUE TITLE
SkypeWeb: кривое форматирование текста.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4689]
1) почему-то в табсах недоступны кнопки жирного текста, курсива и подчеркивания, но в личке доступно зачеркивание текста и img, а в групчатах даже кнопок таких нет.
 
2) Галка "Use BBCode" в настройках протокола вроде ничего не делает, ну я не заметил. Что с ней, что без, внешне не видать различий. Эта опция должна быть уничтожена.

3) В скайпе используется не BBCode, а другое обрамление, * - жирный, ~ - зачеркивание, ``` - код, и т.д., поэтому, когда табсы отправляют туда зачеркивание, то в скайпе прилетает обрамление тегами ббкодов, которое не поддерживается им, а когда пишут из скайпа - то его обрамление просто пропадает. Надо где-то организовать трансляцию одного в другое и обратно.

![2024-09-20 15_21_36-Сергей Марков (You) (Online)](https://github.com/user-attachments/assets/db31e0e6-5292-4777-8793-8bcfe5d2b704)

![2024-09-20 15_22_03-Skype — Mozilla Firefox](https://github.com/user-attachments/assets/16b43cbd-c571-4ea9-875c-1af668f4b6c2)

**Comment by SM-Sergey** [comment]
там некая пародия на markdown, но немного другой диалект, не как тут в гите. Тут например жирный две звёздочки, а в скайпе - одна.

**Comment by georgehazan** [comment]
> 1. почему-то в табсах недоступны кнопки жирного текста, курсива и подчеркивания, но в личке доступно зачеркивание текста и img, а в групчатах даже кнопок таких нет.

Включается в опциях

> 2. Галка "Use BBCode" в настройках протокола вроде ничего не делает, ну я не заметил. Что с ней, что без, внешне не видать различий. Эта опция должна быть уничтожена.

Эта опция как раз и управлает трансляцией ббкодов, которая описана в п.3.

> 3. В скайпе используется не BBCode, а другое обрамление, * - жирный, ~ - зачеркивание, ``` - код, и т.д., поэтому, когда табсы отправляют туда зачеркивание, то в скайпе прилетает обрамление тегами ббкодов, которое не поддерживается им, а когда пишут из скайпа - то его обрамление просто пропадает. Надо где-то организовать трансляцию одного в другое и обратно.

Оно отвалилось, да. Надо починить
