### ISSUE TITLE
WhatsApp: Memory error crash on "bintreenodereader.cpp (92): BinTreeNodeReader::decodeStream"

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#469]
**Reported by Corak on 19 Nov 2015 01:48 UTC**
```
Likely cause of the crash plugin: WhatsApp protocol

Exception: Access Violation at address 7C9101B3. Writing to address 17805542.
## Stack Trace:

7C9101B3 (ntdll 7C900000): (filename not available) (0): RtlAllocateHeap
78AB0269 (MSVCR100 78AA0000): (filename not available) (0): malloc
78AB233B (MSVCR100 78AA0000): (filename not available) (0): operator new
177ED415 (WhatsApp 177E0000): e:\sources\miranda_ng_compilation\protocols\whatsapp\src\whatsapi++\bintreenodereader.cpp (92): BinTreeNodeReader::decodeStream
177EDCB0 (WhatsApp 177E0000): e:\sources\miranda_ng_compilation\protocols\whatsapp\src\whatsapi++\bintreenodereader.cpp (284): BinTreeNodeReader::getTopLevelStream
177EDCCB (WhatsApp 177E0000): e:\sources\miranda_ng_compilation\protocols\whatsapp\src\whatsapi++\bintreenodereader.cpp (319): BinTreeNodeReader::streamStart
177F8FD8 (WhatsApp 177E0000): e:\sources\miranda_ng_compilation\protocols\whatsapp\src\whatsapi++\walogin.cpp (44): WALogin::login
177E4E6E (WhatsApp 177E0000): e:\sources\miranda_ng_compilation\protocols\whatsapp\src\connection.cpp (76): WhatsAppProto::stayConnectedLoop
1224C536 (mir_core 12240000): e:\sources\miranda_ng_compilation\src\mir_core\src\threads.cpp (159): forkthreadex_r
7C80B729 (kernel32 7C800000): (filename not available) (0): GetModuleFileNameA
```

[20151119_whatsapp_memory_bintreenodereader_decodeStream.zip](https://github.com/miranda-ng/miranda-ng/files/649987/20151119_whatsapp_memory_bintreenodereader_decodeStream.zip)

**Comment by georgehazan** [comment]
**Comment by Corak on 8 Dec 2015 17:07 UTC**
Likely cause of the crash plugin: WhatsApp protocol

Exception: Access Violation at address 174ED430. Reading from address 0000000B.

Stack Trace:
---------------------------------------------------------------
174ED430 (WhatsApp 174E0000): e:\sources\miranda_ng_compilation\protocols\whatsapp\src\whatsapi++\bintreenodereader.cpp (91): BinTreeNodeReader::decodeStream
174EDCD5 (WhatsApp 174E0000): e:\sources\miranda_ng_compilation\protocols\whatsapp\src\whatsapi++\bintreenodereader.cpp (284): BinTreeNodeReader::getTopLevelStream
174F17EA (WhatsApp 174E0000): e:\sources\miranda_ng_compilation\protocols\whatsapp\src\whatsapi++\waconnection.cpp (208): WAConnection::read
174E4F5B (WhatsApp 174E0000): e:\sources\miranda_ng_compilation\protocols\whatsapp\src\connection.cpp (93): WhatsAppProto::stayConnectedLoop
1224C536 (mir_core 12240000): e:\sources\miranda_ng_compilation\src\mir_core\src\threads.cpp (159): forkthreadex_r
7C80B729 (kernel32 7C800000): (filename not available) (0): GetModuleFileNameA

**Comment by dartraiden** [comment]
WhatsApp is deprecated.
