### ISSUE TITLE
NewStory: добавить возможность редактировать событие передачи файла

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4691]
Юзкейс: пользователь хочет скопировать часть сообщения.

В случае с обычным сообщением он двойным кликом или пунктом "Изменить" переходит в режим редактирования и там может выделить нужный фрагмент.

В случае с файлтрансфером или облачным файлом с подписью, пользователь, если он хочет скопировать подпись файла, вынужден копировать всё событие, потому что событие передачи файла нельзя редактировать.

Двойной клик по файлтрансферу запускает файл, но мы хотя бы можем пункт меню "Изменить" добавить.

**Comment by SM-Sergey** [comment]
> Двойной клик по файлтрансферу запускает файл, но мы хотя бы можем пункт меню "Изменить" добавить.

Лучше сделать выделение текста при нажатии ЛКМ и перемещении по тексту, и без редактирования. Ведь драгдропа там нету. Можно с кнопкой "Alt", как это привычно для браузеров, чтобы выделять текст вместо тыкания в ссылки.

**Comment by georgehazan** [comment]
Пока сделал так, что событие переходит в режим только для чтения, открывая полностью свой текст
