### ISSUE TITLE
Проблемы проверки орфографии на современных системах (Windows 10/11)

### ISSUE THREAD

**Issue by apollo2k4** [miranda-ng/miranda-ng#4692]
Так как на современных системах работа Spellchecker оставляет желать лучшего из-за того что MS как-то иначе реализует работу richedit.dll
Возникло два вопроса.
1. Можем ли тиснуть (можем, главное чтобы заработало) у Chromium их реализацию HunSpell (у них как-то работает на 10/11)
2. Если первое невозможно, реализовать плагин который сможет использовать встроенное Windows 10/11 средство проверки орфографии.

Краткий поиск по возможному решению проблемы показал следующее.
1. [HunSpell Chromium](https://chromium.googlesource.com/chromium/src/+/master/third_party/hunspell) и тогда можно бонусом прикрыть #531 но похоже они столкнулись с той же проблемой что и мы и теперь у них гибридная проверка [Spellcheck](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/components/spellcheck/)
2. Я не уверен, но с сайта MS ссылка ведёт на https://github.com/microsoft/Windows-classic-samples/tree/main/Samples/SpellCheckerClient

Возможно у кого-то ещё идеи или предложения?

**Comment by georgehazan** [comment]
@apollo2k4 надо копать, долго. 
есть мнение, что второй вариант будет работать, только если на машине стоит Офис, что не есть факт

**Comment by SM-Sergey** [comment]
>  только если на машине стоит Офис, 
Ну это проверятся - если стоит, пусть работает, не стоит, ну на нет и суда нет.

**Comment by dartraiden** [comment]
@georgehazan виндовый спеллчекер можно дёргать без офиса. в Windows 10 точно.

**Comment by apollo2k4** [comment]
> Таким образом, пользователи актуальных ОС смогут перестать страдать, а некроманты нехай мучаются с Hunspell.

Не вижу ничего плохого в Hunspell он отлично работает в Firefox и LibreOffice но стандартные виндовые контролы у него сломаны.
Можно даже внутри спелчекера сделать ветку которая будет исполняться если версия больше 8-ки. Как временное решение может когда-то сможем вернуться обратно на Hunspell
