### ISSUE TITLE
TabSRMM: сделать иконки форматирования в тулбаре протоколозависимыми

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4694]
Не все протоколы поддерживают всё форматирование. Поэтому, если в табсах разрешена опцией настройки тулбара иконка форматирования, не поддержанная тем протоколом, чья вкладка открыта - ее стоит засерить.
Как пример - скайп не поддерживает подчеркивание, IMG и цвет текста/фона, но табсы разрешают так форматировать и отправить. В результате в клиент собеседника придут неясные теги.

**Comment by dartraiden** [comment]
У собеседника может стоять Миранда с журналом, который понимает BBCode.

**Comment by SM-Sergey** [comment]
На этот случай можно предусмотреть опцию для такого редкого контакта - "там миранда". Но, даже если там и миранда, то она не всегда там, а только на компе, а в мобильнике по любому не миранде
