### ISSUE TITLE
Добавить возможность включать/отключать мигания и попапы для конкретного чата, игнорируя глобальные настройки

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4698]
У нас есть два режима мута: Всегда заглушать и Никогда не заглушать. Они отличаются тем, что "всегда" = короткое мигание, а "никогда" = длинное мигание.

Само же наличие миганий настраивается в фильтрах для всех чатов.

Проблема в том, что нет возможности отключить или включить мигание для конкретного чата. Только продолжительность регулируется початово, а сам факт миганий включается или отключается глобально для всех.

Кейс, когда это нужно:
- у меня много чатов в телеграме, там много трепотни, естественно, я не хочу, чтобы на каждую реплику в чате миранда моргала в трее, клисте и попапами плевалась
- поэтому моргания и попапы про сообщения в групчатах у меня выключены

<img width="580" alt="Miranda64_3FTd08Kb5V" src="https://github.com/user-attachments/assets/de44dedd-61c5-461c-8cbe-6db22c749938">

- есть групчат в телеграме, куда сыпятся критические уведомления
- постороннего шума в этом чате нет, туда валится только критически важное
- я хочу, чтобы миранда меня уведомляла об этом сразу и максимально
- но даже если я сделаю этому чату Mute:Never, то миганий и попапов не будет, ведь они выключены для групчатов в целом

Я вижу решение в том, чтобы создать ещё один режим мута, который будет класть с прибором на глобальные настройки. Что-то типа "Всегда уведомлять"

Второй кейс (уже не мой, но от реального пользователя)
- пользователь хочет иметь мигания и попапы про все сообщения во всех чатах, поэтому он включил их глобально
- но для одного чата он не хочет мигания и попапы

Это зеркальный моему кейс. Тут нужен режим мута "Никогда не уведомлять".

**Comment by dartraiden** [comment]
Либо сделать это не добавлением новых режимов мута, а как-то присобачить к Events and Filters

Заодно это позволит закрыть и https://github.com/miranda-ng/miranda-ng/issues/4600

**Comment by SM-Sergey** [comment]
> там тоже автор хочет список чатов в настройки табсов 

Во первых, там автор (я) хочет не список чатов в настройки упихать, а фильтр по названию чатов, такой же, как по юзерам и по контенту, только третий в добавок к ним.

Во вторых, "там" все это делается только ради **автооткрытия вкладок** для некоторых чатов, и ни для чего более. Если реализовать безусловное автооткрытие вкладок для списка чатов - то 4600 можно убрать.

Это хорошо было бы сделать отдельным окном настроек по аналогии с настройкой игноров - выведя туда клист без приватов, и имея галки "автооткрывать вкладки", "мигать", "попапы", и т.д., и в каждом столбце настройка "по умолчанию", "всегда", "никогда". А не режимами мута.
И тогда там можно было бы, также как и в игнорах, собирать чаты в группы, и менять им настройки сразу группами.

**Comment by SM-Sergey** [comment]
Я бы даже больше предложил - настройки "игноров" превратить в более глобальные настройки, включив туда, кроме игноров, и это, что тут обсуждается. Это бы оставило и классную возможность настройки всего этого группам.
Только переименовать игноры в "индивидуальные настройки контакта", и включить туда кроме игноров еще и всё остальное.

**Comment by C1eriC** [comment]
Добавлю свои предложения («второй кейс» — это про меня).

Предлагаю подумать о режимах Mute для групп. 
У нас есть три состояния: Never, Default, Always. 
Сейчас это значит, соответственно: всегда мигать, 6 миганий, 3 мигания (разница между последними двумя практически отсутствует). 
Разве не логично сделать: всегда, сколько-то (ограниченно), никогда? 
  
Как вариант — можно сделать настройку сколько именно мигать в случае Default, с возможностью поставить туда 0 (мигать 0 раз — т.е. не мигать вовсе). 
Или сделать ещё одну настройку типа Mute-Always-Forever-Permanently-Evermore-«Окончательная бумажка. Фактическая. Настоящая! Броня!» — что бы чат принимал сообщения, но не сигнализировал о них.
