### ISSUE TITLE
MessageState: add SkypeWeb support

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4702]

**Comment by georgehazan** [comment]
а зачем? сейчас в NS добавятся крыжики, надобности в MessageState вообще не будет

**Comment by dartraiden** [comment]
Для тех, кто не пользуется NS.

**Comment by georgehazan** [comment]
не выйдет, потому что в скайпе не поддерживается удаленное прочтение вообще, т.е. две галки не вывести
