### ISSUE TITLE
VKontakte: принудительно активировать и засерить опцию про отправку запроса авторизации в диалоге добавления контакта

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4703]
Протокол VK помещает контакт в скрытые, пока контакт не примет запрос авторизации (на сайте это выглядит как запрос добавления в друзья).

Поэтому опция про отправку запроса авторизации должна быть всегда взведена, я полагаю. Чтобы пользователь не мог её снять (как сделал я) и потом гадать, почему контакт так и не появился.

**Comment by ElzorFox** [comment]
зачем после запроса в друзья скрывать контакт я уже не вспомню, честно говоря. Наверное надо этот момент пересмотреть. А вот взводить и выставлять галку по умолчанию точно не стоит. Добавление в список - это не обязательно добавление во френдлист.

**Comment by ElzorFox** [comment]
Короче, тут не баг. Вернее это был другой баг: контакт оставался скрытым после добавления, если был почему-то скрыт ранее.
