### ISSUE TITLE
VKontakte: контакт остаётся скрытым даже после того, как принял запрос авторизации

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4704]
Протокол при добавлении контакта делает его скрытым, пока контакт не примет запрос авторизации (добавление в друзья).

Я добавил контакт, он улетел в скрытые, ему отправился запрос в друзья. Он принял запрос. На сайте он у меня в друзьях. Но в Миранде даже после перезапуска он остаётся скрытым.

**Comment by ElzorFox** [comment]
Просмотрел сейчас код, протокол НЕ делает контакт при запросе дружбы скрытым, в явном виде такая логика не заложена. Единственное, кого контакт делает скрытым - пользователей группчата. Точно ты не пытался добавить кого-то кто уже был скрытым до этого?

**Comment by dartraiden** [comment]
Я пытался добавить пользователя из  групчата.
