### ISSUE TITLE
tabSRMM: опция встроенного журнала "группировать сообщения" некорректно работает с VK

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4706]
В течение одной минуты произошел обмен репликами в привате

Я: Пыщпыщ
Cобеседник: Ололо
Я: Я водитель НЛО

Но встроенный журнал табсов с опцией "Группировать сообщения" сгруппировал их так

Я: Пыщпыщ
Я водитель НЛО
Собеседник: Ололо

Такое ощущение, что табсы сгруппировали это по логике "два сообщения от одного человека в одну минуту - группируем". 

В других протоколах (проверил в TG) группировка группирует лишь сообщения, отправленные последовательно (т.е. два ПОДРЯД от одного человека будут сгруппированы). А в ВК группируется некорректно.

**Comment by georgehazan** [comment]
потому что встроенный журнал группирует по поиску в тексте, а не по реальному времени. если у тебя отключены секунды, то можно в течение одной минуты устроить вот такое вот.
