### ISSUE TITLE
VK: непонятный глюк с приемом файлов.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4708]
Мне прислали сообщение с картинками. Вот так это в оф. клиенте.

![2024-09-27 18_23_40-Мессенджер — Mozilla Firefox](https://github.com/user-attachments/assets/a6039473-b5c0-4d2b-907c-0f558f9563eb)

А так - в миранде. Вместо картинок, превьюшки непонятно от чего. И ссылки непонятно куда - на какое то видео, доступ к которому ограничен.

![2024-09-27 18_24_27-Лариса Маркова (Online)](https://github.com/user-attachments/assets/cd58a0bc-5c7f-48e8-a26f-6772e4efa10d)

Load server history не помогло. Пришло тоже самое.

**Comment by ElzorFox** [comment]
И, что тут не так? Прислали вложения-видео. Как умеем показывать, так и показали: привью к этим видео и ссылки на эти видео, которые может быть при некоторых условиях (первое из которых - обязательная авторизация в том аккаунте на сайте, которому это видео пришло) может даже открыться.

**Comment by SM-Sergey** [comment]
Не так тут то, первое, что превью непойми от чего - ну нет доступа к превью, не надо его и показывать. Просто "нет превью". Это видео мне месяца два назад присылали, от которого это левое превью.
А второе - клик на ссылку на видео отправляет куда-то, где пишут что "доступ ограничен", а клик на него же в том же браузере, но из оф. веб-мессенджера - всё показывает. 
Да, конечно, я в браузере авторизован в этот же аккаунт, так как все время приходится туда прыгать, когда в миранде что-то не так.

**Comment by ElzorFox** [comment]
ВК в последние годы не утруждает себя документированием изменений, поэтому шанс внезапно получить неработающий функционал, который еще вчера прекрасно работал всегда есть. В это раз они утащили генерацию превьюх для некоторых видео на другой домен, да еще вместо статического объекта-картинки, стали отдавать его динамически, из-за чего локальные сохраненные картинки получали одинаковые имена. Поправил.
Заодно сделал шанс открыться видео из сообщения боле вероятным.
Fixed in 55793991ad8b130f5146c1b72bfa0d126ce13456

**Comment by SM-Sergey** [comment]
Не сработало... Обновился, только что пара видео прилетела, опять левые превьюхи, опять открывается как "доступ ограничен", в общем всё тоже самое.
Можно хотя бы превьюхи вообще убрать, если их не дали, а не показывать "левые"?

**Comment by ElzorFox** [comment]
На что обновился? 
Ночник с этими изменениями никто еще не собирал. Версия плагина в котором это исправлено - 0.1.16.13. 
Если версия именно 0.1.16.13 и не работает, тогда интересно взглянуть на нетлог - может быть еще какой-нибудь экзотический случай.

К слову, в старых сообщениях, поправится только если запустить синхронизацию истории [b]не менее, чем за 30 дней[/b]. Или руками каждое сообщение перегружать.

**Comment by SM-Sergey** [comment]
> На что обновился?
А вот на что апдейтер обновил - смотрю предлагает обновление, и там только vkontakte.dll, подумал что это оно.

... нет, 16.12. Тогда, извините.

**Comment by SM-Sergey** [comment]
Все ОК. Работает.

**Comment by dartraiden** [comment]
> А вот на что апдейтер обновил - смотрю предлагает обновление

Лучше ориентироваться по хэшу коммитов. В эбауте Миранды всегда указан коммит, из которого она собрана.
