### ISSUE TITLE
Сделать хэш коммита в диалоге "О программе" кликабельным

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4711]
По нажатию должен осуществляться переход на `https://github.com/miranda-ng/miranda-ng/commit/хэш`

Как минимум несколько раз возникала необходимость открыть в браузере, приходилось набирать хэш руками

**Comment by apollo2k4** [comment]
Красиво, но бесполезно. Мало кто поймет зачем его «сюда» выкинуло.

**Comment by georgehazan** [comment]
> Красиво, но бесполезно. Мало кто поймет зачем его «сюда» выкинуло.

Провинция-с, не поймут-с (с)
