### ISSUE TITLE
Telegram: оформить предпросмотр ссылки как цитату

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4712]
Поскольку мы теперь умеем оформлять произвольный текст как цитату, то предлагаю сделать предпросмотр ссылок как в оф. клиенте

Вот так предпросмотр выглядит в оф. клиенте - сначала идёт ссылка, а её предпросмотр оформлен как цитата (там снова ссылка + title веб-страницы)

<img width="321" alt="Telegram_S2CS3jCmAR" src="https://github.com/user-attachments/assets/f27c5568-faef-4b52-9bba-c3a5a747e07c">

А у нас получается две почти одинаковые ссылки подряд. Да ещё и сопроводительный текст почему-то неполный, куда-то пропала первая строчка "LINUX.ORG.RU — Русская информация об ОС Linux"

<img width="146" alt="vmware_DCGDE5P1v6" src="https://github.com/user-attachments/assets/b94ebdb7-7c0d-40a2-877e-82a77478d9a0">

**Comment by georgehazan** [comment]
Из-за обновления TDLIB поехало, там теперь черт ногу сломит
