### ISSUE TITLE
E-mage LAN not working

### ISSUE THREAD

**Issue by l0oo** [miranda-ng/miranda-ng#4714]
Hello!
E-mage LAN is not working... ;/ While NET VIEW \\ComputerName command gives good response. Windows 11.
Please help! Need local messenger possibility, thought simplicity of E-mage LAN will be good for my purpose. :)

**Comment by georgehazan** [comment]
you need to enable NetBIOS / LANMAN support, which is deprecated by default in Windows 11

**Comment by georgehazan** [comment]
> NET VIEW \ComputerName command gives good response

what about NET SEND

**Comment by l0oo** [comment]
Thanks! Messenger service was not started! :)
