### ISSUE TITLE
Scriver: при отключённом никлисте справа возникает пустое поле

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4717]
Никлист включён, полный порядок

![изображение](https://github.com/user-attachments/assets/b7b251fc-8339-4e59-8f0b-a81aedd1c48b)

Стоит выключить никлист, как справа появляется какое-то серое поле

![изображение](https://github.com/user-attachments/assets/36230f8f-f9ff-45d3-9abf-63bf1034a03c)

Причем, оно даже чуток залезает за верхний край журнала

<img width="432" alt="paintdotnet_x3saqsUPIQ" src="https://github.com/user-attachments/assets/4a39c927-3015-483c-9b27-5616ae402e8a">

**Comment by dartraiden** [comment]
При даблклике по этому серому вертикальному полю, в любой его точке, окно скривера сворачивается

**Comment by dartraiden** [comment]
Регрессия уже присутствует в последней стабле, в более ранних стаблях этого нет.

**Comment by georgehazan** [comment]
Норм, раньше оно даже не подозревало о наличии аватаров в групчатах

**Comment by dartraiden** [comment]
Теперь аватар чата пропал.

**Comment by georgehazan** [comment]
![image](https://github.com/user-attachments/assets/734d47b5-61d6-4b54-8659-a8a991ecdee9)
ничего не пропало

**Comment by georgehazan** [comment]
> Теперь аватар чата пропал в скривере.

Ничего там не пропало, может быть аватары выключены в настройках? или AVS пропал
