### ISSUE TITLE
Jabber: HTTP File Upload в приватах создаёт облачный файл, а в групчатах - ссылку

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4721]
Кидаем в приват картинку.

Она превращается в облачный файл и NS показывает предпросмотр.

Но при кидании в групчат картинка не превращается в облачный файл.

<img width="899" alt="Miranda64_WWVFEEHjvL" src="https://github.com/user-attachments/assets/72c86035-a32f-4818-ab5b-c7e54cfeb826">

**Comment by georgehazan** [comment]
В случае с жабером всё просто - нет события о приеме файла, которое NS умеет разворачивать в оффлайновый файл. Поэтому в групчат просто выстреливается текстовое сообщение, содержащее ссылку

**Comment by georgehazan** [comment]
duplicate of #4351
