### ISSUE TITLE
NewStory: пропала возможность открыть картинку двойным щелчком

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4722]
Раньше была возможность двойным кликом открыть принятую картинку в полном размере.

Теперь двойной клик вводит журнал в режим редактирования (это сделали, чтобы можно было скопировать описание у картинки)

Стало менее удобно. Открытие картинки в полном размере более востребованная операция, чем копирование описания.

**Comment by georgehazan** [comment]
А как быть?
