### ISSUE TITLE
Jabber: удаление срабатывает со второго клика

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4728]
Добавляю в жаббер почту и телефон.

Переоткрываю своё юзеринфо.

<img width="422" alt="Miranda64_RzE36rtJC5" src="https://github.com/user-attachments/assets/4cc51689-d9d7-4112-a20e-b1d7f756073c">

Клик по крестику возле почты ничего не делает. Только повторный клик удаляет почту.

**Comment by georgehazan** [comment]
Вот такая милая особенность винды - если до клика на иконке фокус был на другом окне, то она даже не пробует передать клик мышкой внутрь контрола со списком. Соотв. первый клик ставит фокус, второй - нажимает на иконку
