### ISSUE TITLE
Telegram: проблемы при обновлении

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4731]
1) В 64-разрядную версию при обновлении заехали 32-битные pwrp_k32.dll и p_s232.dll
Т.е. отгрузили пользователям мусор, который мы даже не можем автоматически стереть (иначе сотрутся файлы у 32-битных пользователей)

Нужно либо паковать 64-битные библиотеки с 64-битным плагином, либо пока добавить проверку, чтобы эти библиотеки вообще не отгружать в 64-бит.

2) В 32-разрядной версии апдейтер не может обновить Telegram, ссылаясь на то, что архив повреждён

3) В 32-разрядной версии апдейтер не может и установить Telegram с нуля. Он делает вид, что всё закачал, но протокол не кладётся в Plugins

**Comment by dartraiden** [comment]
Я отключил обновления до завтра.

**Comment by georgehazan** [comment]
> 1. В 64-разрядную версию при обновлении заехали 32-битные pwrp_k32.dll и p_s232.dll

почему 32-битные? потому что называются *32..dll? это не показатель

> * В 32-разрядной версии апдейтер не может обновить Telegram, ссылаясь на то, что архив повреждён

Никаких проблем с архивом




> 3\. В 32-разрядной версии апдейтер не может и установить Telegram с нуля. Он делает вид, что всё закачал, но протокол не кладётся в Plugins

Уже трое пользователей XP установили это с нуля.

**Comment by georgehazan** [comment]
> Я отключил обновления до тех пор, пока мы не разберёмся со всем этим.

Это, конечно, самое правильное, чтобы даже возможности проверить не было...
