### ISSUE TITLE
Предпросмотр файлов сохраняется в профиль даже у канала, где приём сообщений и файлов заигнорен

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4738]
Пользователь в Миранде для одного телеграмного канала выставил игнор (средствами Миранды) на все события.

При этом, он утверждает, что, хоть в Миранду ничего не приходит с канала (что логично, т.к. полный игнор), но "в папку профиля, сохраняются файлы (картинки-превью с этого канала, типа \Preview\Telegram_1\{AQADYbUxG8MubFBy}.jpg )."

Мне не удаётся это воспроизвести.

**Comment by georgehazan** [comment]
Игнор файлов обязан блокировать эту хрень, в теории прорваться мимо оно может только в том случае, если автор канала поменял описание заметки, и т.о. изменилось превью. Тогда да, оно будет скачано в обход игнора, это правда, но такие случаи по идее должны быть невероятно редкими
