### ISSUE TITLE
"About" dialog in TabSRMM

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#474]
**Reported by dartraiden on 3 Dec 2015 06:25 UTC**
 This dialog just pollutes language packs. All info about plugin (version, authors, wiki link) is already presented on Options — Plugins.

![2015-12-03 09_20_35-about tabsrmm](https://cloud.githubusercontent.com/assets/5046855/21157005/edadf19a-c188-11e6-9586-91fea5906cc4.png)

Maybe someone review this patch.

[tabsrmm_about_elimination.zip](https://github.com/miranda-ng/miranda-ng/files/650002/tabsrmm_about_elimination.zip)

**Comment by georgehazan** [comment]
**Modified by dartraiden on 3 Dec 2015 06:36 UTC**

**Comment by dartraiden** [comment]
Fixed in 28e010c9383d28954e8d345c71a73c1b70efa961
