### ISSUE TITLE
Telegram: сделать библиотеки поддержки Windows XP опциональными

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4742]
Если собирать Миранду из нашей репы, то Telegram не вгрузится, т.к. потребует эти проприетарные библиотеки, нужно что-то менять самостоятельно в исходниках, чтобы не использовать эти библиотеки. Вдобавок, тем, кто не под XP, эти библиотеки вообще не нужны.

Было бы здорово сделать следующее:
- вынести эти библиотеки как отдельный компонент, чтобы апдейтер мог их установить и обновлять
- сделать так, чтобы протокольный плагин запускался в отсутствии этих библиотек
- при запуске в Windows XP с отсутствующими библиотеками выдавать сообщение пользователю "поставь вон тот компонент"

Это позволит убить сразу трёх зайцев:
- менее тесная интеграция с проприетарщиной
- возможность без геморроя собрать протокольный плагин и запустить (не используя проприетарные библиотеки)
- пользователям Windows Vista+ не отгружаются библиотеки, которые им совершенно не нужны

**Comment by georgehazan** [comment]
Очень не хочется это делать. Во-первых, это почти удвоит время сборки, потому что основное время уходит на линковку телеги,  а так придется для каждой конфигурации делать две версии. Во-вторых, линковать их можно только насмерть, потому что они закрывают собой кучу импортов, которых в XP нет.
