### ISSUE TITLE
NewStory: отправка ссылки в приват Telegram создаёт пустое белое событие

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4746]
Отправляю в приват (TG) контакту ссылку
`https://github.com/miranda-ng/miranda-ng/issues/4604`

Результат: вместо сообщения вставляется пустое белое событие. Только переоткрыв окно сообщений я вижу эту отправленную ссылку.

**Comment by georgehazan** [comment]
Вообще никаких проблем
