### ISSUE TITLE
Telegram: не работает опция про создание превью ссылок

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4747]
Включена опция "Generate URL preview"
Кидаю в групчат ссылку.

Выключаю опцию.
Кидаю ещё ссылку.

Никакой разницы. Одинаково: ссылка, заголовок, картинка, текст страницы. А в чём смысл опции тогда?

**Comment by georgehazan** [comment]
Смысл опции в обрамлении ссылки тегом url
