### ISSUE TITLE
Steam: crash on "modules.cpp (543): CallService" and "netlibhttp.cpp (138): NetlibHttpFindHeader"

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#475]
**Reported by Corak on 4 Dec 2015 15:38 UTC**

> Likely cause of the crash plugin: Steam protocol
> 
> Exception: Access Violation at address 78B20F66. Reading from address 7065656B.
> ## Stack Trace:
> 
> 78B20F66 (MSVCR100 78AA0000): (filename not available) (0): stricmp_l
> 78B20FE7 (MSVCR100 78AA0000): (filename not available) (0): stricmp
> 120C14CA (mir_app 120A0000): e:\sources\miranda_ng_compilation\src\mir_app\src\netlibhttp.cpp (138): NetlibHttpFindHeader
> 120C2DBF (mir_app 120A0000): e:\sources\miranda_ng_compilation\src\mir_app\src\netlibhttp.cpp (882): NetlibHttpTransaction
> 1224EADA (mir_core 12240000): e:\sources\miranda_ng_compilation\src\mir_core\src\modules.cpp (543): CallService
> 16B8120A (Steam 16B80000): e:\sources\miranda_ng_compilation\protocols\steam\src\http_request.h (147): HttpRequest::Send
> 16B89A00 (Steam 16B80000): e:\sources\miranda_ng_compilation\protocols\steam\src\request_queue.cpp (75): RequestQueue::Execute
> 16B89AA2 (Steam 16B80000): e:\sources\miranda_ng_compilation\protocols\steam\src\request_queue.cpp (105): RequestQueue::WorkerThread
> 1224C57B (mir_core 12240000): e:\sources\miranda_ng_compilation\src\mir_core\src\threads.cpp (119): forkthread_r
> 7C80B729 (kernel32 7C800000): (filename not available) (0): GetModuleFileNameA

[20151204_Steam_HttpRequest_Send__NetlibHttpFindHeader.zip](https://github.com/miranda-ng/miranda-ng/files/650005/20151204_Steam_HttpRequest_Send__NetlibHttpFindHeader.zip)

**Comment by georgehazan** [comment]
**Comment by robyer on 12 Dec 2015 10:16 UTC**
Does this happen regularly? Is it reproducible? It looks like very strange crash.

**Comment by georgehazan** [comment]
**Comment by Corak on 24 Dec 2015 11:19 UTC**
Replying to [robyer](comment:1):
> Does this happen regularly? Is it reproducible? It looks like very strange crash.

Just repeated with core: memory.cpp (225): mir_vsnprintf
http://trac.miranda-ng.org/ticket/1115

**Comment by georgehazan** [comment]
**Comment by Corak on 31 Dec 2015 18:01 UTC**
Simpilar to:
http://trac.miranda-ng.org/ticket/1129
http://trac.miranda-ng.org/ticket/1115

**Comment by Robyer** [comment]
I'm closing this as too old and probably fixed. If it still happens, open new issue, please.
