### ISSUE TITLE
Переименовать Mute:Always

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4751]
Название этого режима вводит пользователей в заблуждение.
Они полагают, что в этом режиме у чата вырубаются принудительно ВСЕ уведомления.

На самом деле, Mute:Always вырубает лишь звуки и попапы, а мигания не вырубает, делая их короткими

> Always muted — short blinking for all; no sounds and popups

**Comment by georgehazan** [comment]
Так и планировалось.

**Comment by dartraiden** [comment]
Я понимаю, поэтому предлагаю поменять название.

**Comment by georgehazan** [comment]
А менять придется именно механизм
