### ISSUE TITLE
IRC: bb-теги в чате с обрезанными стилями

### ISSUE THREAD

**Issue by Deadooshka** [miranda-ng/miranda-ng#4754]
После обновления в чате появились bb-теги типа `[color=%08X][b]текст[/b][color=%08X]`. IRC-стили обрезаются в настройках.

**Comment by georgehazan** [comment]
а кто выступает смотрелкой журнала в чатах? может там просто разрешить ббкоды?

**Comment by Deadooshka** [comment]
`StdMsg`. Стоит галка `strip colors from messages in the log`, но и она сейчас не действует (при снятии галки цвета не появляются, остаются bb-коды). Нужно вырезать все цвета в чатах IRC, чтобы работала настроенная цветовая схема. @georgehazan

**Comment by georgehazan** [comment]
@Deadooshka а куда надо зайти, чтобы посмотреть? желательно на Libera.chat

**Comment by Deadooshka** [comment]
Где бот какой-нибудь есть, который раскрашивает текст. Например в `#codybot` на `irc.libera.chat` надо ввести команду `!rainbow some text` или `!colorize some text` - должен быть раскрашенный текст, либо без красок при включённом вырезании цвета. А сейчас bb-теги. @georgehazan

**Comment by Deadooshka** [comment]
Не работает галка `group chat -> general -> strip colors from messages in the log`. Цвета вырезаются в любом случае, даже без этой галки. Плюс в чате бывают остатки тегов, типа `[color=000080]` или `[b]`, или пропадает какой-то текст раскрашенный. Это лучше смотреть на IRC-каналах с викторинными чат-ботами. @georgehazan

**Comment by georgehazan** [comment]
> Это лучше смотреть на IRC-каналах с викторинными чат-ботами.

Это где, например?
