### ISSUE TITLE
Discord: Add Secure IM Support

### ISSUE THREAD

**Issue by MP36ctrl** [miranda-ng/miranda-ng#4755]
Currently i try to send a key via the SecureIM status bar but it doesnt send anything

**Comment by georgehazan** [comment]
Secure IM doesn't require the special support from any protocol. The only limitation, afair, is that MirVer of this contact must be "Miranda", because Secure IM is available for Miranda only. If there's no version info available, it won't work, in this case I recommend you to use GPG encryption

**Comment by MP36ctrl** [comment]
How do i install GPG encryption for miranda NG?

**Comment by georgehazan** [comment]
we have New_GPG plugin

**Comment by MP36ctrl** [comment]
Yes, but it asks for a gnuPG binary:
![image](https://github.com/user-attachments/assets/71c44097-7ccb-4274-a6c5-7d28d6ac2e51)
Where can i find this?

**Comment by georgehazan** [comment]
evidently, from their site
https://www.gnupg.org/download/

**Comment by MP36ctrl** [comment]
Ah ok, i found the binary
