### ISSUE TITLE
NewStory: Скроллер, как всегда, глючит.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4759]
Получил длинный пост в ВК с кучей картинок и превьюшек.
После него еще пара сообщений.
Поскроллил вверх колесом, потом схватил скроллер и потянул вниз до упора.
Но попал не в упор... А в начало этого длинного сообщения. Потом колесом можно доскроллить еще вниз.

Хватание движка скроллера и тягание его вниз до упора по любому должно приводить к скроллингу в упор вниз, чтобы внизу окна был конец последнего сообщения, а не куда-то там непойми куда, недоезжая.

**Comment by SM-Sergey** [comment]
Возможно, дубль #4609
А может и нет

**Comment by georgehazan** [comment]
Дубль, да, там неверно рассчитывается суммарная высота контента в окне, когда он не загружен
