### ISSUE TITLE
VK: опять видео-превьюшки глючат.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4760]
Наверное опять что-то попортили в апи. Превьюшки для видео показываются от чего-то древнего старого. При этом я влогинен в ВК и в браузере.
Можно в таком случае не показывать превью вообще, если его нет или не дали?

**Comment by ElzorFox** [comment]
Не наблюдаю у себя. Нетлог нужен.

**Comment by SM-Sergey** [comment]
вот, примерно где-то с 900-й строки, вроде.

[netlog_vk.zip](https://github.com/user-attachments/files/17521564/netlog_vk.zip)

**Comment by SM-Sergey** [comment]
Проблема, похоже, вот

[00:58:11 395C] [VKontakte_1] CVkProto::GetVkFileItem file C:\Users\Larisa\AppData\Roaming\Miranda NG\SM\My received files\1575888--ƒ-¦-¦-¦-+ -ô-â-Ç-î-¦-¦\-30.jpg already exist or connection lost

там зачем-то в пути слэш лишний перед "-30.jpg" - файл такой создать, ясное дело, нельзя.

**Comment by ElzorFox** [comment]
У каталогов в файловой системе порой встречаются странные, неправославные имена. 
Что за переменные ты используешь в настройках каталога для приема, что оно в это разворачивается? Прямо-таки любопытно.

**Comment by SM-Sergey** [comment]
> т.е. ты считаешь, что до этого места всё в порядке с именем файла?

Это в логе не в порядке, а в файловой системе все в порядке. Просто русские буквы из %nick%

Но проблема там была не в слеше, он на месте, это я ошибся. А в том, что файл "-30.jpg" существует, и он как раз та самая старая превьюшка и есть. А автопереименование в (1), (2) и т.д. не работает, хотя включено:

![2024-10-25 19_52_47-Miranda NG options](https://github.com/user-attachments/assets/047b5f49-6aa7-4340-be41-bcae8bfd2a9e)

**Comment by SM-Sergey** [comment]
> Что за переменные ты используешь в настройках каталога для приема, что оно в это разворачивается? Прямо-таки любопытно.

C:\Users\Larisa\AppData\Roaming\Miranda NG\SM\My received files\%userid%-%nick%\
