### ISSUE TITLE
Ability to use third party discord reimplementations

### ISSUE THREAD

**Issue by erkinalp** [miranda-ng/miranda-ng#4761]
**Is your feature request related to a problem? Please describe.**
There are a few IM servers reimplementing the Discord protocol (e.g. Litecord, Spacebar).

**Describe the solution you'd like**
Let us enter the endpoing URL for that server.

**Comment by georgehazan** [comment]
Ok, let's make the hidden setting first, and see how it will work
To connect to another server you need to add SETTINGS - Discord_1/ApiUrl STRING "https://blablabla.com"
In theory, if it works as expected, it will auto-tune all another urls in Miranda (gateway etc)
