### ISSUE TITLE
jabber: message handling refactoring

### ISSUE THREAD

**Issue by sss123next** [miranda-ng/miranda-ng#4765]
to handle various xmpp extensions it is at least wise but may be necessary to put all single message related context into atomic structure/class with ability to execute each part of message/extension handling logic as needed, this will make code more readable, allow to get rid of a lot of copy-pasted code and simplify overall logic.

i currently working on this task in separated branch here : https://github.com/miranda-ng/miranda-ng/tree/xmpp_message_handling_refactoring

as of commit 61b2a7d915663e22bf86f58f7f9bba32755b6816 i need some one to test if jabber still works at all.

**Comment by Neustradamus** [comment]
To follow this XMPP ticket :)

**Comment by georgehazan** [comment]
merged with master

**Comment by Neustradamus** [comment]
Thanks to @sss123next and @georgehazan for your XMPP improvements :)
