### ISSUE TITLE
TabSRMM: глюки по следам галки автооткрытия для групчатов.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4768]
По следам коммита d6c0257fa35c82768c50e215cd688d9d9122a6e3

Это, собственно, известно уже, но тикет создать надо.

Если режим автооткрытия окон без активации, то есть вот такой:

![2024-10-30 21_11_23-Miranda NG options](https://github.com/user-attachments/assets/92b579c2-7295-4525-a6ea-2c231927c3c1)

То при "взлёте" окна групчата окно табсов перекорёживает. Ну например вот так - видно, что как бы и вкладка есть, и для чата с отделом для списка юзеров, но на это что-то каким-то раком наложено.

![2024-09-20 17_17_27-Settings](https://github.com/user-attachments/assets/3f9ef8fe-6bd2-4846-bce7-a875493ad1d8)

При этом с автооткрытием окон для приватов проблем как не было, так и нет.

Да, насколько я помню - в дебаге это не проявляется, только в релизе. После ремонта этого тикета надо восстановить поведение окон, "взлетевших" по галке автовзлёта по хайлайтам в соответствии с общими настройками автооткрытия и активации, в своё время это откатили из-за этого глюка.

**Comment by SM-Sergey** [comment]
Да, обращу внимание - что в этом примере изначально была открыта одна вкладка, то есть, собственно, вкладок и не было. Должна была появиться вторая и вкладки вообще. Но вкладки на скриншоте не появилось. Однако, если водить мышью поверх этого "салата", вкладки промаргиваются - зафиксировать это скриншотом нельзя.

**Comment by georgehazan** [comment]
@SM-Sergey когда будешь пробовать этот фикс, убедись в том, что галка Messaging sessions-> Group chats -> Apply tab creation rules... взведена
