### ISSUE TITLE
Telegram: добавить возможность подключаться к тестовому серверу

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4772]
Сервер не очень любит, например, когда много раз подряд за короткое время рвешь сессию. И может забанить тебя на часы или сутки.

У TG есть тестовый сервер, где можно воровать@убивать и творить непотребства с гусями.

Telegram Web: Login here: https://web.telegram.org/?test=1
Telegram Desktop: Hold Alt+Shift and right click on “Add account”, then choose “Test server”.

В официальном клиенте, если кликать по "Добавить аккаунт" правой кнопкой мыши с зажатым Alt+Shitf, то будет выбор, куда логиниться: на продакшен или на тест.

Хорошо бы в Миранде сделать скрытый ключик в ветке протокола в базе. Например, я завожу в Миранду учётку TG, затем, не выходя в онлайн, создаю ключик в ветке протокола, и после этого при выходе в онлайн я попадаю на тестовый сервер, а не на прод.

**Comment by georgehazan** [comment]
в модуль протокола надо добавить UseTestServer BYTE = 1
