### ISSUE TITLE
Notes & Reminders: добавить больше вариантов повтора напоминания

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4776]
При создании напоминания есть опция "повторять ежедневно"

![изображение](https://github.com/user-attachments/assets/858381d2-f7fd-4717-a16b-bb6801a8d973)

Пользователь просит переделать "ежедневно" в выпадающее меню с вариантами "ежедневно", "еженедельно", "ежемесячно".

**Comment by georgehazan** [comment]
Вот это, конечно, почти без шансов, там ужасы какие-то
