### ISSUE TITLE
Notes & Reminders: невозможно отредактировать напоминание

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4777]
Открываем список напоминаний
Создаём напоминание (дату не меняем, просто вписываем произвольный текст)
Нажимаем "Добавить". Нас возвращает в список напоминаний.

Снимаем фокус с созданного напоминания. Всё, его больше нельзя отредактировать, пункт меню "Редактировать" недоступен.

**Comment by georgehazan** [comment]
нельзя менять напоминание, которое уже горит колокольчиком в трее
