### ISSUE TITLE
tabSRMM: дефолтная горячая клавиша Ctrl+O конфликтует с вызовом диалога настройки контейнера

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4780]
По умолчанию Ctrl+O назначена на открытие настроек комнаты чата

![изображение](https://github.com/user-attachments/assets/94dcc323-7c4d-411f-a8fd-f7fee2aabf53)

И она же по умолчанию назначена на открытие контейнера

![изображение](https://github.com/user-attachments/assets/e8b302a2-3570-496a-b86d-44825ac66b5d)

**Comment by dartraiden** [comment]
Да, пользователь может переназначить. Но из коробки делать хоткей нерабочим как-то странно?

**Comment by georgehazan** [comment]
потому что в стдмсг и скривере нет настроек контейнера, а в табсах было Ctrl+Shift+O
