### ISSUE TITLE
SkypeWeb: Please add error window for "new Terms and Conditions"

### ISSUE THREAD

**Issue by tealkami** [miranda-ng/miranda-ng#4783]
Sometimes Skype doesn't connect, and maaaybe with popup it will show that there is a error, but **I have pop-up disabled**, so it only shows connecting and then offline, while the issue is only that on Skype Website they tell you to _forcefully accept_ their new _Terms and Conditions_ , so solution is to log in `web.skype.com` and accept, and then Skype works again in Miranda .

Could you please add some window which write something like: "go to `web.skype.com` website and accept their things to make it work again" ? 
in the last 14 days there were again  _new Terms and Conditions_  so it should be little bit easier to detect it and test it

**Comment by georgehazan** [comment]
to do that Miranda would need to parse html it receives from Skype, parse & download links from the root page and try to find smth in a scripts linked to this page. Imho, that's not possible

**Comment by tealkami** [comment]
heh, so in the connecting/network log there is no way to identify that it ask for the _new Terms and Conditions_ ? and then you would make a general text window "Go to `web.skype.com` in your web browser to fix this problem"

I am just curious how it is looks in the network logs
