### ISSUE TITLE
Jabber: Can you add support for Riot XMPP ?

### ISSUE THREAD

**Issue by tealkami** [miranda-ng/miranda-ng#4784]
I Found out that Riot never stop using XMPP, they just add more "security" features because of bots (League of Legends is still in the 10top online games in world and their other games  are in the top20, Teamfight Tactics, Legends of Runeterra, Valorant), I did check and log in Miranda is from 2017(till that year XMPP/Jabber client did work without any extra additions), after that you needed to do more coding to make it work.
When I did ask you years ago(before 2017), you did even add the list of the servers.

When I was searching if Riot still use XMPP I did find these sources(links below). There are people who made the work and maybe it would be easier if you copy stuff from them ? Most of them are 2years old, but 1 is pretty up to date.

`https://valapidocs.techchrism.me/endpoint/riot-client-config`
`https://valapidocs.techchrism.me/endpoint/xmpp-connection`
https://github.com/giorgi-o/CrossPlatformPlaying/wiki/Riot-Games
https://github.com/ev3nvy/valorant-xmpp-client
https://github.com/techchrism/insomnia-plugin-valorant
https://github.com/techchrism/valorant-xmpp-logger
https://github.com/ValorantDevelopers/riot-xmpp-mitm
https://github.com/KebsCS/LeagueClientDebugger

for all their games you can use the same free Riot account. League of Legends and Valorant have huge player base, so it would be neat if Miranda would support it :)

**Comment by tealkami** [comment]
> @tealkami what do you mean under "add support"? Add Riot to the list of predefined XMPP servers?

You already did that long time ago, and that list is old now

I did imagine something like  Option=>network=>Jabber account=> Advanced => checkmark: change authentification to Riot

In [this link](https://github.com/giorgi-o/CrossPlatformPlaying/wiki/Riot-Games)  he writes about **"To authenticate with the XMPP server, you will need two tokens, an RSO token and a PAS token."** I don't know if you already support it, or if it is something specific only for Riot

So I am asking: if you could please add the new authentifications and the new server list

**Comment by georgehazan** [comment]
> You already did that long time ago, and that list is old now

No, I did not.

> I did imagine something like Option=>network=>Jabber account=> Advanced => checkmark: change authentification to Riot

That's how the short form of Jabber account works in the Account Manager, you can choose a type of network there.

> I don't know if you already support it, or if it is something specific only for Riot

I've not only never heard about those tokens, I've never heard about Riot itself 😉

> So I am asking: if you could please add the new authentifications and the new server list

Server list is gone, because it was driving people mad, dunno about Riot, I'll try to look at those things, but do not guarantee anything - this form is already overloaded with various stuff

**Comment by tealkami** [comment]
It was most likely in between 2015-2016 on jabber chat room, and you do most jabber stuff, so it was high likely you who did add that "League of Legends (EU Nordic)/League of Legends (EU West)/etc" in that list, or maybe someone else at that time, it is just my guess :D


> Server list is gone, because it was driving people mad, dunno about Riot

Because it was not working from 2017, or all the list in general ?

> I'll try to look at those things, but do not guarantee anything - this form is already overloaded with various stuff

Yea, this ticket is something in the "idea" for the future, and something it would be nice, because it did work until 2017

**Comment by georgehazan** [comment]
> League of Legends (EU Nordic)

there's still a predefined server setting for it in the Account Manager window, but I doubt that support for that Riot is only about server address & port

**Comment by dartraiden** [comment]
> support for that Riot is only about server address & port

Are these settings no longer valid? If so we should remove Riot preset
