### ISSUE TITLE
Miranda NG копирование RTF не полное

### ISSUE THREAD

**Issue by SUGHuser** [miranda-ng/miranda-ng#4797]
В данном варианте Miranda NG копирует RTF , но не копирует его полностью , а точнее 
![Screenshot_3514](https://github.com/user-attachments/assets/e9e369fe-ac08-427c-b745-e810d8ed54c2)
%I %N (%h:%m:%s %d/%o/%y)%n%M
в TABSRMM не копируется содержание тег %I

**Comment by SUGHuser** [comment]
Заем это надо ? Это надо затем чтоб я мог окончательно перейти на MirandaNG  , дело в том , что у меня есть истории переписок с людьми в ICQ / MRA / QIP / MRA-New / QIP / Miranda... проблема в том что например есть человек Анатолий я с ним познакомился во времена ICQ и потом перешли в QIP там идёт определённый стиль ведения диалога с копированием цвета сообщения , с копированием иконок возле сообщений с копированием смайлов в сообщениях и всё такое ) и вот этот anatoly.docx у меня идёт с 2006-го года например сейчас же если его переносить в миранду , это ещё одна папка с историей для конкретно anatoly.docx где уже будет стилистика миранды... а хотелось бы иметь один файл с одним единым оформлением истории )

**Comment by SUGHuser** [comment]
Не такой уж дикий расход памяти как вы думаете )
![qip-mem](https://github.com/user-attachments/assets/fb1bd20f-7f8c-453b-a1d5-45a2e4458d46)
![miranda-mem](https://github.com/user-attachments/assets/442afacc-593e-4774-a015-1d64a1e74dce)
я не вижу принципиальной разницы межлу 11 и 30 мегабайтами потребления в условиях когда на ПК стоят гигабайты памяти.

**Comment by SUGHuser** [comment]
> Иконки оно при всём желании копировать не будет, потому что их в RTF банально нету, они вставляются извне как COM-объекты. Видимо, в QIP оно инлайнилось как картинка, но это дикий расход памяти и GDI handles, миранда так не делает

У вас ответ не совсем правильный ) миранда тоже использует COM , она даже отображает иконки в окне сообщения , но если миранда УЖЕ использует COM , то что такого ей копировать эти элементы ? Они ведь УЖЕ ЕСТЬ )

**Comment by georgehazan** [comment]
> я не вижу принципиальной разницы межлу 11 и 40 мегабайтами

Это скорее всего не та память (винда обычно показывает "Рабочий набор", что бессмысленно сравнивать)

> У вас ответ не совсем правильный ) миранда тоже использует COM , 

Не "миранда **тоже** использует COM", а "именно миранда и использует COM", для одной простой цели - чтобы одна и та же иконка могла показываться на экране 20-30-100 раз, не используя дополнительные ресурсы.

> она даже отображает иконки в окне сообщения , но если миранда УЖЕ использует COM , то что такого ей копировать эти элементы ?

С очевидностью, потому что в этом случае иконки не являются частью RTF

**Comment by SUGHuser** [comment]
Так пусть копирует иконки ) делов-то ? Поймите , не враг миранде ) мне мессенджер полюбился очень и у меня есть немного неудобств... раньше это было прям жёсткие такие неудосбства что не копировалось RTF , а сейчас из неудобств осталось совсем малость ) я хочу в идеале получить две вещи к миранде причём одним из двух споосбов :
1) в ядре
2) в виде плагина
мне нужно : 
1) копировать иконки чтоб я могу спокойно писать исорию в те же файлы что и раньше
2) мне нужно чтоб миранда могла писать txt историю , (пусть тоже плагином и опционально) чтоб можнго было использовать ту же историю что в QIP текстовую ) просто я по сути 18 лет использую привычный мне интерфейс и я хочу чтоб новый мессенджер был для меня известен )
