### ISSUE TITLE
Facebook login

### ISSUE THREAD

**Issue by newsjunkie247** [miranda-ng/miranda-ng#4801]
I know Facebook messaging wasn't really working anymore, but until this week I could log in and still see people's statuses and track them. This week for some reason Facebook ended all my active sessions and while I can log in again everywhere else, I can't log in via Miranda-NG anymore. The logs just say the connection is closed. Is anyone still able to login? Any way to at least reenable login?

**Comment by georgehazan** [comment]
make a network log, please, FB + core. it's save to attach it here
