### ISSUE TITLE
NewStory: выделение нескольких сообщений с клавиатуры сломано

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4802]
Тыкаем мышкой сообщение. Зажимаем Shift+стрелку вверх, чтобы выбрать ещё и несколько сообщений выше.

Результат: выделение перескакивает куда-то далеко.

**Comment by georgehazan** [comment]
Если режим совместимости с h++ выключен, то никакого выделения с клавиатуры быть не может по определению
