### ISSUE TITLE
Telegram не позволяет раскидать контакты по группам

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4803]
![395703934-1a6fe225-78d7-408c-a4ed-97fb8ba99925](https://github.com/user-attachments/assets/f3c90661-520f-417d-b3c8-92cb2d0d4ca5)

В настройках протокола не указана группа, потому что я хочу приваты раскидать по разным группам (Дом, Работа, etc), а групчаты должны автоматически упихиваться в группу чатов, указанную в настройках плагиина сообщений

![изображение](https://github.com/user-attachments/assets/47ac3002-c5c9-4ba0-9154-1b883d460f24)

Ожидаемое поведение: если в настройках протокола группа не указана, то контакты находятся в группах, куда я их закинул мышкой в клисте, а чаты САМИ сваливаются в группу "Чаты", указанную в табсах.

Реальное поведение:
1) Если контакты руками раскидать по группам, после рестарта они уезжают обратно в корень. То есть, отсутствует в принципе возможность телеграмные контакты хранить в разных группах. Они всегда будут или в корне (если в протоколе группа не указана) или в одной группе (указанной в настройках протокола). Это очень неудобно.

2) Групчаты игнорируют настройку из плагина сообщений и ведут себя как и контакты.

**Comment by georgehazan** [comment]
Просто укажи группу для телеги и раскидай всех извне этой группы
