### ISSUE TITLE
VK: сделать возможность открыть оф. мессенджер для контакта во всплывающем меню. И сделать меню контакта.

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4817]
Раньше можно было кликнуть на "Message link" от ближайшего переданного файла, и быстро попасть в ветку. После убийства возможности перехода на конкретное сообщение, это было убито, что и логично. Но нередко бывает надо перейти в оф. клиент в ветку общения с контактом. Это надо как-то вернуть.

Например, сделать это по ПКМ в клисте, наравне с "Report abuse" или "Load messages from vk.com" - "Open thread at vk.com", и соотв. и в меню протокола

**Comment by dartraiden** [comment]
П.2 не имеет отношения к VK, это общий баг.

**Comment by dartraiden** [comment]
П.2: всё в порядке, нужно нажимать на кнопку, а не на стрелочку возле кнопки, про это указано во всплывающей подсказке.

**Comment by SM-Sergey** [comment]
А, да. Спасибо. П.2 отменяется, а п.1 остается.
