### ISSUE TITLE
Оффлайн-контакт в корневой группе невидим

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4818]
После https://github.com/miranda-ng/miranda-ng/commit/015dfdfbd64d6aaa7e28e9c12979501136137a1b поведение стало таким:

- прилетает запрос авторизации
- в момент открытия окна, в котором можно разрешить/запретить/отложить авторизацию, контакт получает ключ Hidden=1
- дальше он таким и остаётся

То есть, чувак запрашивает у меня авторизацию, я разрешаю, а в клисте я его не увижу.

**Comment by georgehazan** [comment]
На поведение это никак не влияет, надо смотреть, что там спаморезка делает

**Comment by dartraiden** [comment]
Стопспам не установлен вообще

**Comment by georgehazan** [comment]
Тогда надо прицепить студию к Миранде, поставить точку останова в mir_app, contacts.cpp, 301 и ждать, кто придет скрывать контакт

**Comment by dartraiden** [comment]
Удалось локализовать проблему. Контакт невидим, если он в корневой группе.

**Comment by dartraiden** [comment]
Удалось локализовать проблему.

Если контакт оффлайн И в корневой группе = он невидим.

**Comment by dartraiden** [comment]
Проблема была в том, что в корневой группе включено "Скрыть пользователей вне группы"
