### ISSUE TITLE
tabSRMM: из меню контакта на тулбаре пропали все пункты

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4819]
<img width="181" alt="mstsc_ZlimNiqysz" src="https://github.com/user-attachments/assets/5ebdd099-3e53-4160-a443-2477654ec1fc" />

На тулбаре есть кнопка с меню контакта. Раньше там были собственно пункты меню контакта.
С какого-то момента пункты меню контакта оттуда пропали напрочь.

**Comment by georgehazan** [comment]
у меня она и сейчас работает как надо. чяднт?

**Comment by dartraiden** [comment]
Да, я затупил. Нужно нажимать на кнопку, а не на стрелочку правее кнопки. Стрелочка открывает настройки окна, как и написано во всплывающей подсказке.
