### ISSUE TITLE
Commit 41589ba сломал XMPP

### ISSUE THREAD

**Issue by iDm1** [miranda-ng/miranda-ng#4820]
После обновления до сборки 41589ba Miranda NG перестает подключаться к ejabberd с ошибкой 
­
```
<stream:stream id="4039477494002596800" version="1.0" xml:lang="en" xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" />
<stream:error>
<invalid-xml xmlns="urn:ietf:params:xml:ns:xmpp-streams" />
<text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-streams">
Bad value of attribute 'from' in tag <stream:stream/> qualified by namespace 'jabber:client'
</text>
</stream:error>
```

Настройки учетной записи JABBER так же ломаются, поле UID становится пустым и неактивным, его нельзя ввести.

При откате на 9a2c63b все снова работает.

**Comment by georgehazan** [comment]
> <stream:stream id="4039477494002596800" version="1.0" xml:lang="en" xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" />

- такой XML миранда чисто технически порождать не может,  хочется более точной цитаты из лога
- не надо отключать опцию "Enable SASL2", если сервер её требует при включенном SASL;
- поле UID засеряется только при включенном логине через домен

**Comment by iDm1** [comment]
- Кто порождает конкретно этот XML, Miranda NG или ejabberd - абсолютно не важно. Это шибка, на которой обрывается подключение.
- Никакие опции не меняются. Обновляем Miranda NG до 41589ba и JABBER ломается в ней полностью
- Поле UID блокируется и очищается само. Если это делается при включении логина через домен, то Miranda NG все равно делает это САМА и не позволяет изменить.
- Я перепроверит несколько раз, сборка 41589ba неработоспособна.

**Comment by dartraiden** [comment]
* без более подробного нетлога невозможно понять, что там происходит
* в новом билде появилась поддержка SASL2, поэтому если у сервера какие-то проблемы с SASL2, то они и препятствуют подключениию, а старая версия игнорировала их

**Comment by georgehazan** [comment]
> Поле UID блокируется и очищается само. Если это делается при включении логина через домен, то Miranda NG все равно делает это САМА и не позволяет изменить.
если отключить логин через домен, то можно будет изменить имя пользователя, с очевидностью

**Comment by georgehazan** [comment]
> Доменный логин до обновления был выключен и его никто не включал.

Чудес же не бывает, правда? Миранда сама эту опцию включить не может, следовательно, её кто-то включил.

> Будто бы с SASL2 Miranda NG всегда пытается использовать доменный логин.

Нет, эти опции совершенно не связаны друг с другом

**Comment by iDm1** [comment]
> Нет, эти опции совершенно не связаны друг с другом

Но ведут себя будто связаны. Возможно конечно это и баг на стороне ejabberd, а не Miranda NG.

**Comment by dartraiden** [comment]
@georgehazan ещё раз просмотрел код и уверяет, что они никак друг с другом не связаны.
