### ISSUE TITLE
Переименовать "Disable SASL authentication (for old servers)" в "Enable SASL"

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#4821]
Для консистентности.
И включить эту галку по умолчанию.
"for old servers" вообще не нужно, те, кто использует SASL и очень старые серверы наверняка и так прекрасно знают такие нюансы

<img width="580" alt="Miranda64_jIUzMVF76w" src="https://github.com/user-attachments/assets/af4cee46-d2ce-4a4c-97e8-1b9f6adfc40e" />

**Comment by georgehazan** [comment]
никак. там именно отключение SASL
