### ISSUE TITLE
NewStory: не работает тег img

### ISSUE THREAD

**Issue by SM-Sergey** [miranda-ng/miranda-ng#4824]
subj. на примере стикера из ВК:

![2024-12-30 20_51_45-Игорь Митрохин (Online)](https://github.com/user-attachments/assets/e5f31218-72b4-4b2f-a1b3-c315af729681)

![2024-12-30 20_52_14-Игорь Митрохин (Offline)](https://github.com/user-attachments/assets/a53bae3a-0425-45ed-9969-dee6b7c8bfb0)

ссылка живая, проверил, по ней прилетает картинка.

**Comment by dartraiden** [comment]
Это не прямая ссылка на файл, поэтому и не работает.

**Comment by dartraiden** [comment]
Это не файлтрансфер и не облачный файл, поэтому и не работает.

**Comment by SM-Sergey** [comment]
> Это не файлтрансфер и не облачный файл.

так ВК никогда и не поддерживал оффлайн файлы ни в каких проявлениях, как и автоскачивание. Однако превьюшки всегда показывает. Если считаете, что это не ваш баг, то пусть тогда он исправляется в рамках протокола ВК, чтобы он корректно показывал стикеры, а не закрывается так вот на халяву.

**Comment by dartraiden** [comment]
В каком-то виде поддерживает, иначе они бы не грузились
8d9d3d3809dd91a14df619e58535c00ad8fc48e7

**Comment by ElzorFox** [comment]
> Вопрос лишь в том, чей это косяк: NS, VK или SmileyAdd ( не знаю насчёт VK, но другим протоколам он необходим для скачивания стикеров)

У ВК  есть режим, когда ему SmileyAdd не нужен, достаточно, чтобы журнал тег img умел. Тут как раз этот режим включен.

Собственно, тут дело в том, что когда я делал поддержку NS, сделал ее не для всех типов вложений, в том числе и для стикеров.
