### ISSUE TITLE
Add support for the '0' value in TabSRMM's Message sessions -> Containers -> Flash containers

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#498]
**Reported by dartraiden on 1 Jan 2016 22:22 UTC**
Just to avoid losing in the conference. Need testing.

[ 15 20:27] \* ultramage: random patch I've been using for many years: https://paste.pfak.org/L7W9DRY2 - add support for the '0' value in tabsrmm's Message sessions -> Containers -> Flash containers
[ 15 20:29] \* ultramage: I forget what exactly it does, but I believe it makes it so that chat windows don't flash everytime a new message is received; they just stay lit up
[ 15 20:30] \* Wishmaster: :D
[ 15 20:31] \* Wishmaster: What exactly does that mean?
[ 15 20:31] \* Wishmaster: Isnt there an option not to flash?
[ 15 20:33] \* ultramage: I don't know; but I like to have the window get highlighted when a new message arrives, I just don't want it blinking at me; I think I did that patch because it was distracting me while I was trying to work on something

**Comment by dartraiden** [comment]
Already merged.
