### ISSUE TITLE
HistoryStats statistics can't be opened through Miranda main menu

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#501]
**Reported by  rmn  on 7 Jan 2016 23:37 UTC**
Steps to reproduce:
1. Create statistics (either through main menu or in HistoryStats settings, doesn't matter)
2. Check if `stats.html` was created in `Miranda NG\Profiles\HistoryStats\` (it is created there with the plugin's default settings)
3. Select ''Main menu -> Statistics -> Show statistics''

What happens:
You get HistoryStats warning
''The statistics can't be found. Either you never created them or the last created statistics were moved to a different location and can't be found anymore.''

**Comment by georgehazan** [comment]
**Modified by _rmn_ on 8 Jan 2016 17:31 UTC**

**Comment by LittleVulpix** [comment]
@georgehazan , this is working and can be closed.
