### ISSUE TITLE
Vk: x64 heap crash on "vk_thread.cpp (501): CVkProto::OnReceiveUserInfo"

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#508]
**Reported by Corak on 11 Jan 2016 17:43 UTC**
Likely cause of the crash plugin: VKontakte protocol

Exception: Access Violation at address 00000000771A3290. Reading from address 00000EF2BB2356A8.
## Stack Trace:

00000000771A3290 (ntdll 0000000077150000): (filename not available) (0): RtlFreeHeap
0000000076F51A4A (kernel32 0000000076F30000): (filename not available) (0): HeapFree
000000005DE88D94 (MSVCR100 000000005DE20000): (filename not available) (0): free
00000000120A7B6F (libjson 00000000120A0000): e:\sources\miranda_ng_compilation\libs\libjson\src\internaljsonnode.cpp (183): internalJSONNode::~internalJSONNode
00000000120A79B2 (libjson 00000000120A0000): e:\sources\miranda_ng_compilation\libs\libjson\src\jsonchildren.cpp (82): jsonChildren::deleteAll
00000000120A7B4F (libjson 00000000120A0000): e:\sources\miranda_ng_compilation\libs\libjson\src\internaljsonnode.cpp (183): internalJSONNode::~internalJSONNode
00000000120A79B2 (libjson 00000000120A0000): e:\sources\miranda_ng_compilation\libs\libjson\src\jsonchildren.cpp (82): jsonChildren::deleteAll
00000000120A7B4F (libjson 00000000120A0000): e:\sources\miranda_ng_compilation\libs\libjson\src\internaljsonnode.cpp (183): internalJSONNode::~internalJSONNode
00000000120A79B2 (libjson 00000000120A0000): e:\sources\miranda_ng_compilation\libs\libjson\src\jsonchildren.cpp (82): jsonChildren::deleteAll
00000000120A7B4F (libjson 00000000120A0000): e:\sources\miranda_ng_compilation\libs\libjson\src\internaljsonnode.cpp (183): internalJSONNode::~internalJSONNode
00000000120A12D3 (libjson 00000000120A0000): e:\sources\miranda_ng_compilation\libs\libjson\src\jsonnode.inl (42): JSONNode::~JSONNode
0000000017BE3F28 (VKontakte 0000000017BE0000): e:\sources\miranda_ng_compilation\protocols\vkontakte\src\vk_thread.cpp (501): CVkProto::OnReceiveUserInfo
0000000017BE65B2 (VKontakte 0000000017BE0000): e:\sources\miranda_ng_compilation\protocols\vkontakte\src\vk_queue.cpp (56): CVkProto::ExecuteRequest
0000000017BE69A7 (VKontakte 0000000017BE0000): e:\sources\miranda_ng_compilation\protocols\vkontakte\src\vk_queue.cpp (147): CVkProto::WorkerThread
0000000012331588 (mir_core 0000000012320000): e:\sources\miranda_ng_compilation\src\mir_core\src\threads.cpp (160): forkthreadex_r
0000000076F459ED (kernel32 0000000076F30000): (filename not available) (0): BaseThreadInitThunk
000000007717C541 (ntdll 0000000077150000): (filename not available) (0): RtlUserThreadStart

**Comment by georgehazan** [comment]
**Modified by Corak on 11 Jan 2016 22:49 UTC**

**Comment by ElzorFox** [comment]
No netlog and I cannot reproduce this.
