### ISSUE TITLE
whatsapp text error, dont appear!

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#516]
**Reported by vaga on 17 Jan 2016 02:20 UTC**
whatsapp receive message text dont appear in windows convesation.
videos and audio link appear in the window of conversation, message text sending is ok , but messages receive from other, dont appear .
in the iphone, message sending to miranda ng for the attach.
iphone wrote a message in "notepad" in the iphone and "attach" windows conversation , this make a receive in my miranda ng a text , in the windows conversation.

**Comment by dartraiden** [comment]
WhatsApp is deprecated.
