### ISSUE TITLE
whatsapp: dont connect

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#522]
**Reported by vaga on 27 Jan 2016 01:07 UTC**
thanks for the solve bug to dont receive text message, but before update ( text receive ok ) , whatsapp dont connect.
thanks miranda team!

[ Intel(R) Pentium(R) 4 CPU 3.00GHz [x86 Family 15 Model 4 Stepping 9](spoiler=VersionInfo][quote]CPU:)
Installed RAM: 496 MBytes
Microsoft Windows XP Professional Service Pack 3 (build 2600)
Internet Explorer: 6.0.2900.5512 (build 62900.5512)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Portuguese/Portuguese | Portuguese/Portuguese
Free disk space on Miranda partition: 65788 MBytes

Miranda NG Version: 0.95.5 alpha build #16171
Build time: 26 Jan 2016 16:07:38
Profile: C:\Documents and Settings\Z\Dados de aplicativos\Miranda NG\ZZZ\ZZZ.dat
Profile size: 393216 Bytes
Profile creation date: 11 Jan 2016 0:09:52
Language pack: No language pack installed
Service Mode: No

[Plugins (17):[/b](b]Active)
 AdvaImg.dll v.[[25 Jan 2016 16:50:36](b]0.11.0.2[/b]) - Miranda image services 
 AIM.dll v.[[25 Jan 2016 16:49:32](b]0.11.0.1[/b]) - AIM protocol 
 AvatarHistory.dll v.[[25 Jan 2016 16:51:56](b]0.1.0.1[/b]) - Avatar history 
 AVS.dll v.[[25 Jan 2016 16:49:26](b]0.95.3.4[/b]) - Avatar service 
 CrashDumper.dll v.[[25 Jan 2016 16:51:06](b]0.0.5.2[/b]) - Crash dumper 
 DbEditorPP.dll v.[[25 Jan 2016 16:51:10](b]4.0.1.1[/b]) - Database editor++ 
 Dbx_mmap.dll v.[[26 Jan 2016 16:03:42](b]0.95.3.1[/b]) - Miranda NG mmap database driver 
 Facebook.dll v.[[25 Jan 2016 16:50:48](b]0.2.11.7[/b]) - Facebook RM 
 GG.dll v.[[25 Jan 2016 16:49:48](b]0.11.0.3[/b]) - Gadu-Gadu protocol 
 ICQ.dll v.[[25 Jan 2016 16:49:44](b]0.11.3.4[/b]) - IcqOscarJ protocol 
 Import.dll v.[[25 Jan 2016 16:49:26](b]0.95.4.2[/b]) - Import contacts and messages 
 IRC.dll v.[[25 Jan 2016 16:49:50](b]0.11.0.3[/b]) - IRC protocol 
 Jabber.dll v.[[25 Jan 2016 16:49:54](b]0.11.0.4[/b]) - Jabber protocol 
 MSN.dll v.[[25 Jan 2016 16:49:58](b]0.12.1.1[/b]) - MSN protocol 
 PluginUpdater.dll v.[[25 Jan 2016 16:51:26](b]0.1.2.5[/b]) - Plugin updater 
 WhatsApp.dll v.[[25 Jan 2016 16:53:08](b]0.1.3.2[/b]) - WhatsApp protocol 
 Yahoo.dll v.[[25 Jan 2016 16:49:40](b]0.11.0.2[/b]) - Yahoo protocol 

[Plugins (1):[/b](b]Unloadable)
 DbChecker.dll v.[[26 Jan 2016 16:05:22](b]0.0.0.0[/b]) - <unknown> 
## [and Accounts:[/b](b]Protocols)

AIM                      0 - Enabled 0 - Disabled  Loaded
Facebook                 0 - Enabled 0 - Disabled  Loaded
GG                       0 - Enabled 0 - Disabled  Loaded
ICQ                      0 - Enabled 0 - Disabled  Loaded
IRC                      0 - Enabled 0 - Disabled  Loaded
JABBER                   0 - Enabled 0 - Disabled  Loaded
MSN                      1 - Enabled 0 - Disabled  Loaded
WhatsApp                 1 - Enabled 0 - Disabled  Loaded
YAHOO                    0 - Enabled 0 - Disabled  Loaded
MetaContacts             1 - Enabled 0 - Disabled  Loaded
## [Packs:[/b](b]Icon)

 Proto_AIM.dll [Jan 2016 16:50:52](25)
 Proto_Facebook.dll [Jan 2016 16:50:50](25)
 Proto_GG.dll [Jan 2016 16:50:52](25)
 Proto_ICQ.dll [Jan 2016 16:50:52](25)
 Proto_IRC.dll [Jan 2016 16:50:52](25)
 Proto_Jabber.dll [Jan 2016 16:50:52](25)
 Proto_MetaContacts.dll [Jan 2016 16:06:52](26)
 Proto_MSN.dll [Jan 2016 16:50:52](25)
 Proto_WhatsApp.dll [Jan 2016 16:52:56](25)
 Proto_Yahoo.dll [Jan 2016 16:50:52](25)
 TabSRMM_icons.dll [Jan 2016 16:51:28](25)
 Toolbar_icons.dll [Jan 2016 16:50:52](25)
 xStatus_ICQ.dll [Jan 2016 16:49:48](25)
 xStatus_Jabber.dll [Jan 2016 16:49:50](25)
[/quote][/spoiler]

**Comment by dartraiden** [comment]
We must implement encryption support, See #558
