### ISSUE TITLE
ICQ cannot connect most of the time

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#523]
**Reported by peci1 on 28 Jan 2016 09:54 UTC**
For a few weeks, ICQ has almost stopped working - it fails to connect most of the time. Approx. once a day it succeeds, but then it loses the connection again and reconnection attempts fail. Even after restarting Miranda.

I connect to the secure server slogin.icq.com .

System: Win7 64bit, Miranda in the development version with all updates applied.

What kind of debugging information do you need from me? (and how do I obtain them?)

[netlog.icq_error.txt](https://github.com/miranda-ng/miranda-ng/files/650163/netlog.icq_error.txt)

[netlog.icq_error2.txt](https://github.com/miranda-ng/miranda-ng/files/650164/netlog.icq_error2.txt)

**Comment by georgehazan** [comment]
**Comment by wishmaster on 28 Jan 2016 10:08 UTC**
Replying to [peci1](ticket:1168):
> What kind of debugging information do you need from me? (and how do I obtain them?)
We would need a network log: http://wiki.miranda-ng.org/index.php?title=Network_log

**Comment by georgehazan** [comment]
**Comment by peci1 on 30 Jan 2016 10:17 UTC**
Okay, here you are.

**Comment by georgehazan** [comment]
**Comment by peci1 on 31 Jan 2016 22:47 UTC**
I found a workaround - turning off UPnP, because I saw some UPnP timeouts in the log. But I suppose that is not the clean solution. 

What could be the culprits? Is it a bug in Miranda, or could it be something with the LAN router?

I attach another log. What is recorded: 
1) I tried to connect as in the first log.
2) I changed the incoming port range for ICQ to 3000-4000 (still no success).
3) I turned off UPnP (finally connected).

The log is cut at the moment the connection succeeded, because I don't want to publicly disclose my list of contacts. I really wonder this kind of information is in a log file Miranda devs suggest to upload publicly. Shouldn't the log have some anonymization?

**Comment by dartraiden** [comment]
Non actual. Old protocol is dead.
