### ISSUE TITLE
whatsapp ,no text receive ,no image. i said: no,no,no

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#525]
**Reported by vaga on 2 Feb 2016 02:19 UTC**
hi miranda team!
whatsapp connect, but now, no receive image.

history bugs:
no receive text , receive image and audio
receive text, die another day.
receive audio, no receive image and text

i attach a dependency walker log.
i run miranda ng into dependency walker , i send text (DLL_THREAD_ATTACH) need to other user send me a text(DLL_THREAD_ATTACH).

**Comment by georgehazan** [comment]
**Comment by wishmaster on 2 Feb 2016 11:41 UTC**
Some problems with WhatsApp are known, see [here](http://forum.miranda-ng.org/index.php?topic=56.msg15876;boardseen#new).

**Comment by dartraiden** [comment]
WhatsApp is deprecated.
