### ISSUE TITLE
whatsapp: windows phone ok

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#526]
**Reported by vaga on 3 Feb 2016 18:30 UTC**
hi guys!
miranda ng receive text, image and audio from windows phone whatsapp.

**Comment by georgehazan** [comment]
**Modified by vaga on 3 Feb 2016 18:39 UTC**

**Comment by LittleVulpix** [comment]
I think this can be closed. It's not a bug, more of a "it works with windows phone" ...
