### ISSUE TITLE
miranda ng goBug

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#527]
**Reported by vaga on 7 Feb 2016 15:01 UTC**
miranda ng crash into gobug.
crash when contact send me a file: audio or image                

GoBug - copyright Jeremy Gordon 1996-2009
Date: sbado, 6 de fevereiro de 2016 Time: 19:45:44
Dump of main logpane
whilst debugging C:\Arquivos de programas\Miranda NG\Miranda32.exe

Running to starting address
Starting address reached
breakpoint caused by int3 found in the code at 7C90E4F3h

**Comment by dartraiden** [comment]
Crashlog really need.
