### ISSUE TITLE
Miranda NG crashes when yahoo contact sends file

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#528]
**Reported by StelardActek on 9 Feb 2016 08:41 UTC**
I have tried this with two different contacts. One of which uses the official Yahoo client v11.5, the other is using Trillian. In both cases, when they attempt to send me a file, Miranda crashes immediately with no indication as to what actually caused it on my end.

Here is my versions info:
[Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz [Intel64 Family 6 Model 63 Stepping 2](spoiler=VersionInfo][quote]CPU:) [Enabled](DEP) [CPUs](12)
Installed RAM: 32594 MBytes
Microsoft Windows 8.1 Professional Edition, 64-bit (build 9600)
Internet Explorer: 9.11.9600.18161 (build 99600)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | English/English
Free disk space on Miranda partition: 4020901 MBytes

Miranda NG Version: 0.95.5 alpha build #16248 [inside WOW64](running)
Build time: 9 Feb 2016 4:04:26
Profile: D:\Applications\Miranda NG\Profiles\Stelard\Stelard.dat
Profile size: 94306304 Bytes
Profile creation date: 1 Jan 2016 10:46:41
Language pack: No language pack installed
Service Mode: No

[Plugins (24):[/b](b]Active)
 AdvaImg.dll v.[[24 Jan 2016 16:47:24](b]0.11.0.2[/b]) - Miranda image services 
 AIM.dll v.[[16 Jan 2016 23:22:35](b]0.11.0.1[/b]) - AIM protocol 
 AVS.dll v.[[2 Feb 2016 18:24:16](b]0.95.3.4[/b]) - Avatar service 
 Clist_modern.dll v.[[2 Feb 2016 18:25:54](b]0.9.1.3[/b]) - Modern contact list 
 CrashDumper.dll v.[[16 Jan 2016 23:23:11](b]0.0.5.2[/b]) - Crash dumper 
 Dbx_mmap.dll v.[[9 Feb 2016 4:00:10](b]0.95.3.1[/b]) - Miranda NG mmap database driver 
 Facebook.dll v.[[2 Feb 2016 18:25:34](b]0.2.11.8[/b]) - Facebook RM 
 HistoryPP.dll v.[[2 Feb 2016 9:31:38](b]1.5.1.5[/b]) - History++ 
 ICQ.dll v.[[2 Feb 2016 18:24:32](b]0.11.3.4[/b]) - IcqOscarJ protocol 
 IEView.dll v.[[2 Feb 2016 18:25:02](b]1.5.0.1[/b]) - IEView 
 Import.dll v.[[16 Jan 2016 23:22:33](b]0.95.4.2[/b]) - Import contacts and messages 
 IRC.dll v.[[2 Feb 2016 18:24:26](b]0.11.0.3[/b]) - IRC protocol 
 Jabber.dll v.[[6 Feb 2016 4:00:40](b]0.11.0.4[/b]) - Jabber protocol 
 MSN.dll v.[[2 Feb 2016 18:24:46](b]0.12.1.1[/b]) - MSN protocol 
 NewXstatusNotify.dll v.[[2 Feb 2016 18:25:00](b]1.4.0.11[/b]) - xStatus notify 
 PluginUpdater.dll v.[[16 Jan 2016 23:23:17](b]0.1.2.5[/b]) - Plugin updater 
 PManagerEx.dll v.[[16 Jan 2016 23:23:17](b]0.0.0.5[/b]) - Miranda NG profile changer 
 SkypeWeb.dll v.[[9 Feb 2016 4:04:08](b]0.12.2.2[/b]) - Skype protocol (Web) 
 StartupStatus.dll v.[[2 Feb 2016 18:25:14](b]0.8.0.48[/b]) - StartupStatus 
 StatusChange.dll v.[[24 Jan 2016 16:49:08](b]1.3.0.0[/b]) - Status change 
 TabSRMM.dll v.[[2 Feb 2016 18:24:28](b]3.4.0.11[/b]) - TabSRMM 
 TopToolBar.dll v.[[16 Jan 2016 23:23:07](b]0.8.0.4[/b]) - TopToolBar 
 Tox.dll v.[[2 Feb 2016 18:28:18](b]0.11.1.19[/b]) - Tox protocol 
 Yahoo.dll v.[[16 Jan 2016 23:22:40](b]0.11.0.2[/b]) - Yahoo protocol 

[Plugins (1):[/b](b]Unloadable)
 DbChecker.dll v.[[9 Feb 2016 4:02:02](b]0.0.0.0[/b]) - <unknown> 

[and Accounts:[/b](b]Protocols)
-------------------------------------------------------------------------------
AIM                      1 - Enabled 0 - Disabled  Loaded
Facebook                 1 - Enabled 0 - Disabled  Loaded
ICQ                      0 - Enabled 1 - Disabled  Loaded
IRC                      0 - Enabled 2 - Disabled  Loaded
JABBER                   1 - Enabled 1 - Disabled  Loaded
MSN                      0 - Enabled 2 - Disabled  Loaded
SKYPE                    1 - Enabled 0 - Disabled  Loaded
TOX                      1 - Enabled 0 - Disabled  Loaded
YAHOO                    1 - Enabled 0 - Disabled  Loaded
MetaContacts             1 - Enabled 0 - Disabled  Loaded

[Packs:[/b](b]Icon)
-------------------------------------------------------------------------------
 HistoryPP_icons.dll [Feb 2016 18:26:20](2)
 Proto_AIM.dll [Jan 2016 23:23:05](16)
 Proto_Facebook.dll [Feb 2016 18:25:40](2)
 Proto_GG.dll [Feb 2016 18:25:42](2)
 Proto_ICQ.dll [Feb 2016 18:25:44](2)
 Proto_IRC.dll [Feb 2016 18:25:44](2)
 Proto_Jabber.dll [Feb 2016 4:01:38](6)
 Proto_MetaContacts.dll [Feb 2016 4:03:40](9)
 Proto_MSN.dll [Feb 2016 18:25:44](2)
 Proto_Skype.dll [Feb 2016 4:03:56](9)
 Proto_Tox.dll [Feb 2016 18:28:08](2)
 Proto_Yahoo.dll [Jan 2016 23:23:05](16)
 TabSRMM_icons.dll [Feb 2016 18:26:34](2)
 Toolbar_icons.dll [Feb 2016 18:25:44](2)
 xStatus_ICQ.dll [Feb 2016 18:24:28](2)
 xStatus_Jabber.dll [Feb 2016 4:00:38](6)
[/quote][/spoiler]

**Comment by georgehazan** [comment]
**Modified by StelardActek on 9 Feb 2016 08:43 UTC**

**Comment by georgehazan** [comment]
**Comment by wishmaster on 9 Feb 2016 11:25 UTC**
Please read [this](http://wiki.miranda-ng.org/index.php?title=Crash_reports) and provide a crash report with debug symbols installed.

**Comment by georgehazan** [comment]
**Comment by ghazan on 30 May 2016 09:21 UTC**
might be already fixed, if the multiple file transfer was chosen.
give it a try with a nightly build after revision #16886

**Comment by aunsane** [comment]
Yahoo protocol was depricated b0f3e30460fc26ef4fe59bc161b0fddd8eeb9a08.
