### ISSUE TITLE
support for OMEMO encryption

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#529]
**Reported by plahh on 10 Feb 2016 15:41 UTC**
as requested in [this](http://forum.miranda-ng.org/index.php?topic=4378.0) thread
here is the ticket :)

http://conversations.im/omemo/ 
https://en.wikipedia.org/wiki/OMEMO_%28encryption%29

gajim already got a plugin. code [here](https://github.com/python-otr/gajim-otr/issues/18)

**Comment by georgehazan** [comment]
**Comment by sss_sss on 8 Sep 2016 20:17 UTC**
i am on it

**Comment by georgehazan** [comment]
**Comment by sss_sss on 24 Sep 2016 06:08 UTC**
  ....

**Comment by LittleVulpix** [comment]
@sss123next , tagging you with this ticket since you said you are now working on it. :)

**Comment by DreamFlasher** [comment]
@georgehazan Is there any status update for us? :)

**Comment by georgehazan** [comment]
doesn't it work?

**Comment by sergeevabc** [comment]
Do you believe current implementation with [the following todo][1] is cooked enough to be used in production?

> TODO: 
> 1. fix AES-128 GCM in 4.5 implementation
> 2. handle prekeys properly (cleanup after first use, create new keys)
> 3. reimplement session initialization  without loosing first message (incomming + outgoing)
> 4. fingerprints/keys management ui
> 5. per-contact encryption settings (enable/disable for one contact)


[1]: https://github.com/miranda-ng/miranda-ng/commit/5ab73a190c76b8d43a19866451f6aaca0895781d

**Comment by georgehazan** [comment]
you better ask @sss123next about it

**Comment by DreamFlasher** [comment]
@georgehazan No it doesn't. I found this thread where he apparently writes updates: http://forum.miranda-ng.org/index.php?topic=4506.30 -- but how exactly am I supposed to retrieve the plugin with his commits? It is said somewhere that it's supposed to be in "dev" Miranda, but there is apparently currently none: http://www.miranda-im.org/development/
I have the latest Miranda, with the latest jabber plugin and I don't see any possibility to use Omemo.

**Comment by LittleVulpix** [comment]
@DreamFlasher That's MirandaIM which is pretty dead. This is miranda NG where the changes are taking place. Get the latest dev version from here: http://www.miranda-ng.org/en/downloads/ , if you want to migrate from IM to NG, there is a nice article on our wiki. Make sure to backup everything beforehand.

**Comment by DreamFlasher** [comment]
@LittleVulpix Ah bummer! I first tried with Miranda NG, but it didn't work there, so then I tried Miranda. I have switched to Miranda NG a while ago, but when I now checked 
http://www.miranda-ng.org/en/downloads/ "17.6.2016    New stable build released, 0.95.5"
http://www.miranda-im.org/ "Miranda IM v0.10.70 Released June 06, 2017"
So I thought Miranda would be more current than Miranda NG again.
But yeah, same with me for Miranda NG: I have the development version from the place you wrote, and Omemo doesn't work. I have a chat with Omemo on conversations/gajim, and I don't get the messages on Miranda, also Miranda doesn't announce itself as Omemo capable. How do I activate it? Is there any manual anywhere?

**Comment by LittleVulpix** [comment]
@DreamFlasher 

Yes, there is a way to toggle it on. As long as you are on the dev version of miranda, go to main miranda options menu, type network into the search box, find the name of the network you want to modify (the internal name you gave it, probably jabber if you haven't changed anything), go into advanced and scroll at the very bottom - there is an option to enable Omemo.

See screencap from my miranda:

![image](https://user-images.githubusercontent.com/8679333/27189981-4d93ba04-51f3-11e7-9436-e614316018a2.png)

**Comment by DreamFlasher** [comment]
@LittleVulpix Thank you very much! I was able to active it (although activating crashed Miranda NG). 
Then I tried do start a conversation with an Omemo contact, it asks to create a new session, but the messages aren't received by the other end. Also new messages aren't received by Miranda NG.

**Comment by LittleVulpix** [comment]
@DreamFlasher Ahh, I don't use Omemo myself, so I never tested it. I guess this is a question for @sss123next since he is developing the omemo plugin. Sorry it didn't work! :(

**Comment by DreamFlasher** [comment]
@LittleVulpix You were very helpful in setting things up, so thank you very much for that!
Maybe @sss123next can take over with the bugs? :)

**Comment by sss123next** [comment]
hmm.
i have tested it with success.
ont thing which is not done properly - is aes128gcm tagging (verification always fail in my case), but actual encryption decryption work fine.
other TODO entries is convenience mostly, not XEP implementation related.
i will recheck it.
crashes are completely unexpected behavior.

**Comment by sss123next** [comment]
i have done quick tests. all looks normal [screenshot](http://imgur.com/a/3MaZ8) . so i need more info. check miranda console, it may have useful readable debug messages, also check xml console, i am also need crashlogs, backtraces e.t.c. in case of crash.

**Comment by wiktor-k** [comment]
I'm getting `Delivery failure: No valid OMEMO session exists` when sending a message to OMEMO-enabled contact. Are there any other options/actions besides Network/Advanced/Use OMEMO?

I'm using stock Miranda NG 0.95.6 64bit.

**Comment by sss123next** [comment]
log from miranda console and xml console will be helpful

**Comment by sss123next** [comment]
i have plan to implement let's say "omemo part 2"
1. do things in TODO.
2. ui and convenience related things (but it depends on not implemented yet core ui wrappers, so i have to wait for ui part to be done in core) :
it will look like new tab for omemo only in settings in jabber section (various info and settings related to own omemo params)
and new tab for omemo options in userinfo (info and settings for each user)
also some switches in per contact menu will be added

**Comment by wiktor-k** [comment]
@sss123next, XML console shows only one `<iq>` packet:

```xml
<iq type="get" id="mir_19" from="x@conversations.im" to="a@conversations.im">
<pubsub xmlns="http://jabber.org/protocol/pubsub">
<items node="eu.siacs.conversations.axolotl.bundles:1775231250" />
</pubsub>
</iq>
­
<iq from="a@conversations.im" to="x@conversations.im/Miranda" id="mir_19" type="result">
<pubsub xmlns="http://jabber.org/protocol/pubsub">
<items node="eu.siacs.conversations.axolotl.bundles:1775231250">
<item id="5D68D16BCF808">
<bundle xmlns="eu.siacs.conversations.axolotl">
<signedPreKeyPublic signedPreKeyId="1">BdNmP78geFV66ql8u8ltLStLuDh8OQojMKiFLUu0cQZ0</signedPreKeyPublic>
<signedPreKeySignature>r5bn8niujaNdHZhpnRGBjXrXiS4uGuJNpZZ4BbdA6uYO/iUlyFyh3+9VbAZDAc9a7OFaigoDi2MBatmofdzRCw==</signedPreKeySignature>
<identityKey>BfV/qBoZwL57/XzEzSq1hfn6Hpzs61CXF9pRBcMzaSE4</identityKey>
<prekeys>
<preKeyPublic preKeyId="92">BWejMJL08vSsroHSv5+z/S4XZG0pSv0SewRPlJdPiA4f</preKeyPublic>
<!--...long list of keys here...-->
</prekeys>
</bundle>
</item>
</items>
<set xmlns="http://jabber.org/protocol/rsm">
<first index="0">modification@001494:577899:852197</first>
<last>modification@001494:577899:852197</last>
<count>1</count>
</set>
</pubsub>
</iq>
```

Where is the Miranda log? I don't see it in the application directory...

**Comment by sss123next** [comment]
you can turn on network log in : options->network -> logging button, or you can use console plugin

xml looks ok

**Comment by wiktor-k** [comment]
> also it is critical to use build from code 2017-05-18 17:37:18 ( 5ab73a1 ) or later, if by stock you mean release - it's most probably too old

Do you publish dev builds somewhere? I'm assuming https://www.miranda-ng.org/en/downloads/ is "too old"? I can test experimental builds but setting up the development infrastructure myself is just too much work (sorry if that sounds bad).

**Comment by sss123next** [comment]
https://www.miranda-ng.org/distr/miranda-ng-alpha-latest_x64.7z - i guess this should be ok

**Comment by wiktor-k** [comment]
I erased entire directory (profile too) and started from scratch, before sending first message it asked me twice if I want to create new OMEMO session (each time with different key, probably for mobile) I said Yes both times. Sadly it still failed.

Here's the network log from the alpha build:

```
[20:54:13 2B18] [JABBER_1] Deflate: Z_OK
[20:54:13 2B18] [JABBER_1] (ZLIB) Data sent
<iq type="get" id="mir_24" from="x@conversations.im" to="a@conversations.im"><pubsub xmlns="http://jabber.org/protocol/pubsub"><items node="eu.siacs.conversations.axolotl.bundles:1775231250"/></pubsub></iq>
===OUT: 221(105) bytes
[20:54:13 2B18] [JABBER_1] Jabber OMEMO: info: OmemoCheckSession: pending session creation encryption/decryption of THIS message will not be done and message WILL be lost
[20:54:13 18B0] [JABBER_1] Inflate: Z_OK
[20:54:13 18B0] [JABBER_1] (ZLIB) Data received
<iq from='a@conversations.im' to='x@conversations.im/Miranda' id='mir_24' type='result'><pubsub xmlns='http://jabber.org/protocol/pubsub'><items node='eu.siacs.conversations.axolotl.bundles:1775231250'><item id='5D68D16BCF808'><bundle xmlns='eu.siacs.conversations.axolotl'><signedPreKeyPublic signedPreKeyId='1'>BdNmP78geFV66ql8u8ltLStLuDh8OQojMKiFLUu0cQZ0
</signedPreKeyPublic><signedPreKeySignature>r5bn8niujaNdHZhpnRGBjXrXiS4uGuJNpZZ4BbdA6uYO/iUlyFyh3+9VbAZDAc9a7OFaigoDi2MB
atmofdzRCw==
</signedPreKeySignature><identityKey>BfV/qBoZwL57/XzEzSq1hfn6Hpzs61CXF9pRBcMzaSE4
</identityKey><prekeys><preKeyPublic preKeyId='92'>BWejMJL08vSsroHSv5+z/S4XZG0pSv0SewRPlJdPiA4f
....prekeys here....
</preKeyPublic></prekeys></bundle></item></items><set xmlns='http://jabber.org/protocol/rsm'><first index='0'>modification@001494:577899:852197</first><last>modification@001494:577899:852197</last><count>1</count></set></pubsub></iq>
===IN: 9622(130) bytes
[20:54:13 18B0] [JABBER_1] recvResult = 9622
[20:54:13 18B0] [JABBER_1] bytesParsed = 9622
[20:54:13 18B0] [JABBER_1] Jabber OMEMO: session_builder_process_pre_key_bundle failure SG_ERR_INVALID_KEY
[20:54:13 18B0] [JABBER_1] Jabber OMEMO: error: omemo::build_session failed
[20:54:13 2B48] [JABBER_1] Broadcast ACK
[20:54:13 2B18] [JABBER_1] Deflate: Z_OK
[20:54:13 2B18] [JABBER_1] (ZLIB) Data sent
<message to="a@conversations.im/phone" type="chat" id="mir_25"><composing xmlns="http://jabber.org/protocol/chatstates"/></message>
===OUT: 137(50) bytes
[20:54:13 2B48] [JABBER_1] Returning from thread
```

**Comment by sss123next** [comment]
thx for info, i will check.

**Comment by sss123next** [comment]
which clients used on other side ?

**Comment by wiktor-k** [comment]
> which clients used on other side ?

Conversations.im and Gajim.

> is it possible to send message from other side to miranda ?

I'll test various scenarios and get back to you.

**Comment by sss123next** [comment]
@wiktor-k  any news ?

i have done most of important things in todo.
now implementation close to "complete" state.
convenience ui is separated topic and enhancement.

for now i want bugreports.

**Comment by sss123next** [comment]
update:
currently we have  this: https://conversations.im/xeps/multi-end.html
and not: https://conversations.im/omemo/xep-omemo.html nor https://xmpp.org/extensions/xep-0384.html

which both looks incompatible on first sight

**Comment by sss123next** [comment]
switched to xep-0384  d8a068a2beeb0056b303a612475e7eaa3188e157

**Comment by dryo** [comment]
I too can't send messages with newest miranda IM x86

This is what I get from network log when trying to send a message, nothing more:


[12:25:50 22C0] [***@***] Jabber OMEMO: error: message does not encrypted for any sessions
[12:25:50 1DE4] [***@***] Broadcast ACK
[12:25:50 1DE4] [***@***] Returning from thread

When sending I get the error message "a message failed to send successfully". Other party uses Conversations 1.20.1. I am not logged in from any other client.


  Miranda NG Version: 0.95.7 alpha build #18734 (42732e3639) [running inside WOW64]
  Build time: 27 Oct 2017 6:00:40

**Active Plugins (25):**
¤ AdvaImg.dll v.[b]0.11.0.2[/b] [27 Oct 2017 6:02:33] - Miranda image services 
¤ AuthState.dll v.[b]0.0.2.1[/b] [19 Sep 2017 22:33:32] - Authorization state 
¤ AVS.dll v.[b]0.95.3.4[/b] [27 Oct 2017 6:00:44] - Avatar service 
¤ Clist_modern.dll v.[b]0.9.1.7[/b] [27 Oct 2017 6:02:50] - Modern contact list 
¤ CrashDumper.dll v.[b]0.0.5.2[/b] [27 Oct 2017 6:03:03] - Crash dumper 
¤ CryptoPP.dll v.[b]1.0.4.8[/b] [19 Sep 2017 22:35:04] - Crypto++ 
¤ DbEditorPP.dll v.[b]4.0.1.1[/b] [19 Sep 2017 22:33:54] - Database editor++ 
¤ Dbx_mmap.dll v.[b]0.95.3.1[/b] [27 Oct 2017 6:00:52] - Miranda NG mmap database driver 
¤ Facebook.dll v.[b]0.3.3.2[/b] [27 Oct 2017 6:02:22] - Facebook RM 
¤ FTPFile.dll v.[b]0.6.0.2[/b] [19 Sep 2017 22:34:32] - FTP File YM 
¤ HistoryPP.dll v.[b]1.5.1.5[/b] [24 Sep 2017 22:15:24] - History++ 
¤ ICQ.dll v.[b]0.11.3.5[/b] [27 Oct 2017 6:01:11] - IcqOscarJ protocol 
¤ IRC.dll v.[b]0.11.0.3[/b] [27 Oct 2017 6:00:54] - IRC protocol 
¤ Jabber.dll v.[b]0.11.0.5[/b] [27 Oct 2017 6:01:25] - Jabber protocol 
¤ MirOTR.dll v.[b]0.14.1.16[/b] [19 Sep 2017 22:34:38] - Miranda OTR 
¤ PluginUpdater.dll v.[b]0.1.2.5[/b] [27 Oct 2017 6:03:34] - Plugin updater 
¤ QuickSearch.dll v.[b]1.4.2.0[/b] [19 Sep 2017 22:35:16] - Quick Search 
¤ SkypeWeb.dll v.[b]0.12.2.4[/b] [19 Sep 2017 22:34:28] - Skype protocol (Web) 
¤ SmileyAdd.dll v.[b]0.2.4.1[/b] [19 Sep 2017 22:33:46] - SmileyAdd 
¤ SpellChecker.dll v.[b]0.2.6.4[/b] [19 Sep 2017 22:34:06] - Spell checker 
¤ StatusManager.dll v.[b]0.11.2.0[/b] [24 Oct 2017 19:45:54] - Status manager 
¤ TabSRMM.dll v.[b]3.5.0.6[/b] [27 Oct 2017 6:01:01] - TabSRMM 
¤ TopToolBar.dll v.[b]0.8.0.4[/b] [27 Oct 2017 6:02:43] - TopToolBar 
¤ Tox.dll v.[b]0.11.1.25[/b] [19 Sep 2017 22:34:26] - Tox protocol 
¤ UInfoEx.dll v.[b]0.8.5.0[/b] [19 Sep 2017 22:33:48] - User info ext

**Comment by wiktor-k** [comment]
@sss123next I downloaded the version from https://www.miranda-ng.org/distr/miranda-ng-alpha-latest_x64.7z

Unfortunately the error still exists (`Delivery failure: No valid OMEMO session exists`). Plugins page shows jabber.dll version 0.11.0.5. Is it possible that this is related to contact using Prosody that does not persist PubSub items (so that keys could be removed after restart)?

Do I need to create new profile from scratch or should the update (overwrite all files) take care of everything?

**Comment by dryo** [comment]
I too have Problems: I'm sending messages but the other party does not receive/see them. When the other party sends me a message I get this: "I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo"

The receiving end uses _conversations_ and I had an OMEMO encrypted session also with _conversations_ with the receiver earlier. The receiver probably did not close the app in the meantime. Maybe this is relevant.

Network log says this when receiving:

```
[14:57:59 1F90] [***@***] Inflate: Z_OK
[14:57:59 1F90] [***@***] (ZLIB) Data received
<message to='***@***/***' from='***@***/mobile' type='chat' id='757eb832-6ec9-4490-9871-c423c84b27ae'><encrypted xmlns='eu.siacs.conversations.axolotl'><header sid='1511459254'><key prekey='true' rid='214083405'>MwhhEiEF3lJUNCjrDBXi3Ghv0goXqOMtET9gISTo6zv9QujIMgUaIQXd3hQ3L/wRegQTlMS3Sj3nPpz+S/8VjYtn7scY33AeXCJiMwohBT5RTQ+yJojmHKzvZPCykiGDZ7hzuoydd6YwYQwL/KVPEAEYACIwVtj2AxqtDdMMD4oY/ehMBqXs7E+vqD0POVkIaD0U89N9Gpz7gFLRWAGhUgHWs4MWWnMNihctiYAotpPc0AUwAQ==</key><iv>DF6SuD6N2G8uJnAC9CmA6w==</iv></header><payload>Zvg8vGSHLo5vUz/XmZudUsoR3WjJHg8f+hbJnmx6twmGf4QguyDHdimJWbt4YQ==</payload></encrypted><markable xmlns='urn:xmpp:chat-markers:0'/><origin-id xmlns='urn:xmpp:sid:0' id='757eb832-6ec9-4490-9871-c423c84b27ae'/><store xmlns='urn:xmpp:hints'/><encryption xmlns='urn:xmpp:eme:0' namespace='eu.siacs.conversations.axolotl' name='OMEMO'/><body>I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.**/omemo</body></message>
===IN: 1022(223) bytes
[14:57:59 1F90] [***@***] recvResult = 1022
[14:57:59 1F90] [***@***] bytesParsed = 1022
[14:58:00 1F90] [***@***] Jabber OMEMO: error: session_cipher_decrypt_pre_key_signal_message failed SG_ERR_INVALID_MESSAGE
[14:58:00 1F90] [***@***] Jabber OMEMO: error: signal_message_deserialize failed with unknown error
[14:58:00 1F90] [***@***] Jabber OMEMO: error: failed to decrypt incomming message
[14:58:00 1F90] [***@***] JabberUpdateMirVer: for jid ***@***
[14:58:00 1F90] [***@***] JabberUpdateMirVer: for rc mobile: http://conversations.im#+wL56uyy89dgaGVTbnJJpkXpkIE=
```

Network log says this when sending:

```
[14:58:24 2030] [***@***] Deflate: Z_OK
[14:58:24 2030] [***@***] (ZLIB) Data sent
<message to="***@***/mobile" id="mir_28"><encrypted xmlns="eu.siacs.conversations.axolotl"><payload>kOapO3NhnifBOhSY</payload><header sid="214083405"><key rid="1511459254">MwjXHRIhBS2BelDPQ2hlaDe0pF2NYtkoE7H17DoGRXpSJxtFYVE7GiEFQqbmCQumd156Dnr7dHYsuqOPJfN8oFlkbmOSmK6gfkEiUjMKIQUWt0mm7Zrsxhj+zvockZZ5GHImMA9Fzrd7axiysD/DAhABGAAiIM3Wd/o69zoLalxhdN3Jj3A6QppAtkoQQm6t7SEhW8VIIvOUDyzr5mgozc6KZjAm</key><iv>9O0GUHl+PRYnnXir</iv></header></encrypted><store xmlns="urn:xmpp:hints"/><active xmlns="http://jabber.org/protocol/chatstates"/></message>
===OUT: 544(115) bytes
[14:58:24 11B4] [***@***] Broadcast ACK
[14:58:24 11B4] [***@***] Returning from thread
```

**Comment by dryo** [comment]
Addition: Also when enabling or disabling OMEMO in settings while being connected miranda crashes. Care for crash reports?

**Comment by sss123next** [comment]
yes.

**Comment by sss123next** [comment]
51e27d7122c871c253b7a183da8ac8720f0f2ea7 - rollback to "updated" https://xmpp.org/extensions/xep-0384.html

this should resolve incompatibility with fresh implementations (also this will broke compatibility with others once more)

**Comment by dartraiden** [comment]
#1215
after start OMEMO enabled in settings, but I receive 

> I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo
from contact

**Comment by sss123next** [comment]
i need logs from xml console.
better from both sides if possible.

**Comment by sss123next** [comment]
look on #1255 for further development

**Comment by sss123next** [comment]
current implementation is incompatible with conversation for some reason.
we constantly have SG_ERR_INVALID_MESSAGE on attempt to session_cipher_decrypt_pre_key_signal_message

and no info on conversations side ( looks like conversations does not have any debugging at all.... )

i have redone tests with miranda<>miranda, it works
i have done all tests with latest libsignal-protocol-c

**Comment by Neustradamus** [comment]
OMEMO 100% works with Miranda NG?

**Comment by OmlineEditor** [comment]
Not 100% implemented OMEMO :-( 
interface not yet finalized.
Is there a graphical menu where you can see and verify the keys?
I do not see the interface for normal operation.

**Comment by RIS2000** [comment]
Still no success Miranda <-> Conversations. But Gajim works pretty well, so i suppose that Miranda have some faulty implementation ((

**Comment by tigexplorer** [comment]
I've no success with Miranda <-> Conersations and Miranda <-> Dino

**Comment by Neustradamus** [comment]
@LittleVulpix, @sergeevabc, @dreamflasher, @wiktor-k, @dryo, @dartraiden, @Duke690, @OmlineEditor, @RIS2000, @tigexplorer, @gjf: Can you test the last upstream code?

@sss123next has done some changes yesterday.

The goal is to have a perfect XEP-0384 0.3.0 version:
- https://github.com/miranda-ng/miranda-ng/issues/2719

**Comment by gjf** [comment]
@Neustradamus OMEMO still does not work with Conversations.
Psi+ does.

**Comment by ageis** [comment]
Will be eagerly tracking this.

**Comment by a11cf0** [comment]
Still doesn't seem to work with Conversations.

**Comment by dreamflasher** [comment]
I switched to beeper, which wowed me from a user experience perspective.

**Comment by Neustradamus** [comment]
@georgehazan, @sss123next: Can you look this problem please?
Thanks in advance.

**Comment by sss123next** [comment]
i will check in few days.

**Comment by OmlineEditor** [comment]
Maranda v0.96.4 #26381 and Conversations on Android v2.12.6 (old version) - OMEMO work OK.
Maranda v0.96.4 #26381 and Conversations on Android v2.13.0 (new version) - OMEMO work OK.
Maranda v0.96.4 #26381 and Blabber.im v3.1.4 (analogue Conversations) - OMEMO work OK.

perhaps the problem is changing the keys in the MEMO and Miranda does not understand well that the keys need to be used by others. I had a similar problem when there were several encryption keys and some of them were not used. for Miranda, you need to hand over the ability to delete and revoke your old keys from the server.

**Comment by Neustradamus** [comment]
@OmlineEditor: For information, there is a problem in Metronome IM but it is not the problem with Miranda NG:
- https://github.com/maranda/metronome/issues/549

Please, can you edit your last message?
Maranda -> Miranda NG
MEMO -> OMEMO

Note there is OMEMO 0.3.0 and the new OMEMO...

**Comment by sss123next** [comment]
![miranda_amema](https://github.com/miranda-ng/miranda-ng/assets/202772/0abb8564-6af4-4a56-a99a-bb02e4c2cc1d)
![miranda_amema2](https://github.com/miranda-ng/miranda-ng/assets/202772/ec0d4bba-7c83-4926-8030-a6220574e61f)

**Comment by Excerion** [comment]
Hello what is the status of this?

**Comment by Neustradamus** [comment]
@Excerion: There are:
- https://github.com/miranda-ng/miranda-ng/issues/5076
- https://github.com/miranda-ng/miranda-ng/issues/5075
- https://github.com/miranda-ng/miranda-ng/issues/4767

cc: @sss123next.
