### ISSUE TITLE
whatsapp : problem no receive text

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#532]
**Reported by vaga on 15 Feb 2016 20:07 UTC**
hi miranda team , read a ticket i read a same defect mine:
#1050 new defect

WhatsApp: no text messages receiving from android / ios apps - crypted messages (axolotl encryption support). 

i dont know , this is the same problem.
thanks

[ Intel(R) Pentium(R) 4 CPU 3.00GHz [x86 Family 15 Model 4 Stepping 9](spoiler=VersionInfo][quote]CPU:)
Installed RAM: 496 MBytes
Microsoft Windows XP Professional Service Pack 3 (build 2600)
Internet Explorer: 6.0.2900.5512 (build 62900.5512)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Portuguese/Portuguese | Portuguese/Portuguese
Free disk space on Miranda partition: 65140 MBytes

Miranda NG Version: 0.95.5 alpha build #16281
Build time: 15 Feb 2016 4:04:20
Profile: C:\Documents and Settings\Z\Dados de aplicativos\Miranda NG\ZZZ\ZZZ.dat
Profile size: 524288 Bytes
Profile creation date: 10 Jan 2016 23:09:52
Language pack: No language pack installed
Service Mode: No

[Plugins (16):[/b](b]Active)
 AdvaImg.dll v.[[9 Feb 2016 15:23:26](b]0.11.0.2[/b]) - Miranda image services 
 AIM.dll v.[[9 Feb 2016 15:22:26](b]0.11.0.1[/b]) - AIM protocol 
 AvatarHistory.dll v.[[9 Feb 2016 15:24:50](b]0.1.0.1[/b]) - Avatar history 
 AVS.dll v.[[9 Feb 2016 15:22:20](b]0.95.3.4[/b]) - Avatar service 
 CrashDumper.dll v.[[9 Feb 2016 15:24:02](b]0.0.5.2[/b]) - Crash dumper 
 Dbx_mmap.dll v.[[15 Feb 2016 4:00:12](b]0.95.3.1[/b]) - Miranda NG mmap database driver 
 Facebook.dll v.[[12 Feb 2016 6:29:34](b]0.2.12.0[/b]) - Facebook RM 
 GG.dll v.[[9 Feb 2016 15:22:40](b]0.11.0.3[/b]) - Gadu-Gadu protocol 
 ICQ.dll v.[[9 Feb 2016 15:22:44](b]0.11.3.4[/b]) - IcqOscarJ protocol 
 Import.dll v.[[9 Feb 2016 15:22:18](b]0.95.4.2[/b]) - Import contacts and messages 
 IRC.dll v.[[9 Feb 2016 15:22:30](b]0.11.0.3[/b]) - IRC protocol 
 Jabber.dll v.[[9 Feb 2016 15:22:48](b]0.11.0.4[/b]) - Jabber protocol 
 MSN.dll v.[[9 Feb 2016 15:22:52](b]0.12.1.1[/b]) - MSN protocol 
 PluginUpdater.dll v.[[9 Feb 2016 15:24:16](b]0.1.2.5[/b]) - Plugin updater 
 WhatsApp.dll v.[[9 Feb 2016 15:26:02](b]0.1.3.3[/b]) - WhatsApp protocol 
 Yahoo.dll v.[[9 Feb 2016 15:22:40](b]0.11.0.2[/b]) - Yahoo protocol 

[Plugins (1):[/b](b]Unloadable)
 DbChecker.dll v.[[15 Feb 2016 4:02:12](b]0.0.0.0[/b]) - <unknown> 
## [and Accounts:[/b](b]Protocols)

AIM                      0 - Enabled 0 - Disabled  Loaded
Facebook                 0 - Enabled 0 - Disabled  Loaded
GG                       0 - Enabled 0 - Disabled  Loaded
ICQ                      0 - Enabled 0 - Disabled  Loaded
IRC                      0 - Enabled 0 - Disabled  Loaded
JABBER                   0 - Enabled 0 - Disabled  Loaded
MSN                      1 - Enabled 0 - Disabled  Loaded
WhatsApp                 1 - Enabled 0 - Disabled  Loaded
YAHOO                    0 - Enabled 0 - Disabled  Loaded
MetaContacts             1 - Enabled 0 - Disabled  Loaded
## [Packs:[/b](b]Icon)

 Proto_AIM.dll [Feb 2016 15:23:46](9)
 Proto_Facebook.dll [Feb 2016 15:23:44](9)
 Proto_GG.dll [Feb 2016 15:23:46](9)
 Proto_ICQ.dll [Feb 2016 15:23:48](9)
 Proto_IRC.dll [Feb 2016 15:23:48](9)
 Proto_Jabber.dll [Feb 2016 15:23:48](9)
 Proto_MetaContacts.dll [Feb 2016 4:03:36](15)
 Proto_MSN.dll [Feb 2016 15:23:48](9)
 Proto_WhatsApp.dll [Feb 2016 15:25:50](9)
 Proto_Yahoo.dll [Feb 2016 15:23:50](9)
 TabSRMM_icons.dll [Feb 2016 15:24:22](9)
 Toolbar_icons.dll [Feb 2016 15:23:50](9)
 xStatus_ICQ.dll [Feb 2016 15:22:46](9)
 xStatus_Jabber.dll [Feb 2016 15:22:46](9)
[/quote][/spoiler]

**Comment by georgehazan** [comment]
**Comment by Hannes on 16 Feb 2016 12:25 UTC**
Same here for more than a week:
Miranda v0.95.5 alpha build #16281
Whatsapp.dll v0.1.3.3

Account gets online ok
Outgoing messages ok
No incoming messages, just a notification the other site is typing text.

**Comment by dartraiden** [comment]
Duplicate of #440
