### ISSUE TITLE
whatsapp crash

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#535]
**Reported by vaga on 18 Feb 2016 17:16 UTC**
Miranda Crash Report from 18 Feb 2016 14:56:02. Crash Dumper v.0.0.5.2

Likely cause of the crash plugin: WhatsApp protocol

Exception: Access Violation at address 174B049B. Reading from address 00000038.
## Stack Trace:

174B049B (WhatsApp 174A0000): (filename not available) (0): (function-name not available)
174AC25D (WhatsApp 174A0000): (filename not available) (0): (function-name not available)
174B453B (WhatsApp 174A0000): (filename not available) (0): (function-name not available)
121D55A2 (mir_app 121C0000): (filename not available) (0): Proto_RegisterModule
121C1905 (mir_app 121C0000): (filename not available) (0): Ordinal30

CPU:  Intel(R) Pentium(R) 4 CPU 3.00GHz [Family 15 Model 4 Stepping 9](x86)
Installed RAM: 496 MBytes
Microsoft Windows XP Professional Service Pack 3 (build 2600)
Internet Explorer: 6.0.2900.5512 (build 62900.5512)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Portuguese/Portuguese | Portuguese/Portuguese

Miranda NG Version: 0.95.5 alpha build #16299
Build time: 17 Feb 2016 19:56:14
Profile: C:\Documents and Settings\Z\Dados de aplicativos\Miranda NG\ZZZ\ZZZ.dat
Language pack: No language pack installed
Service Mode: No

Active Plugins (16):
 AdvaImg.dll v.0.11.0.2 [Feb 2016 16:36:38](16) - Miranda image services 
 AIM.dll v.0.11.0.1 [Feb 2016 16:35:48](16) - AIM protocol 
 AvatarHistory.dll v.0.1.0.1 [Feb 2016 16:38:06](16) - Avatar history 
 AVS.dll v.0.95.3.4 [Feb 2016 16:35:36](16) - Avatar service 
 CrashDumper.dll v.0.0.5.2 [Feb 2016 16:37:24](16) - Crash dumper 
 Dbx_mmap.dll v.0.95.3.1 [Feb 2016 19:51:58](17) - Miranda NG mmap database driver 
 Facebook.dll v.0.2.12.0 [Feb 2016 16:36:58](16) - Facebook RM 
 GG.dll v.0.11.0.3 [Feb 2016 16:35:58](16) - Gadu-Gadu protocol 
 ICQ.dll v.0.11.3.4 [Feb 2016 16:36:02](16) - IcqOscarJ protocol 
 Import.dll v.0.95.4.2 [Feb 2016 16:35:36](16) - Import contacts and messages 
 IRC.dll v.0.11.0.3 [Feb 2016 16:35:48](16) - IRC protocol 
 Jabber.dll v.0.11.0.4 [Feb 2016 16:36:06](16) - Jabber protocol 
 MSN.dll v.0.12.1.1 [Feb 2016 16:36:08](16) - MSN protocol 
 PluginUpdater.dll v.0.1.2.5 [Feb 2016 16:37:34](16) - Plugin updater 
 WhatsApp.dll v.0.1.3.3 [Feb 2016 16:39:14](16) - WhatsApp protocol 
 Yahoo.dll v.0.11.0.2 [Feb 2016 16:35:56](16) - Yahoo protocol 
## Loaded Modules:

C:\Arquivos de programas\Miranda NG\Miranda32.exe  00400000 - 00409000 v.0.95.5.16299 [Feb 2016 19:56:14](17)
C:\WINDOWS\system32\ntdll.dll  7C900000 - 7C9B3000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\kernel32.dll  7C800000 - 7C900000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\USER32.dll  7E360000 - 7E3F1000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\GDI32.dll  77E50000 - 77E99000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\ADVAPI32.dll  77F50000 - 77FFB000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\RPCRT4.dll  77DB0000 - 77E42000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\Secur32.dll  77F20000 - 77F31000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\SHELL32.dll  7C9C0000 - 7D1DE000 v.6.0.2900.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\msvcrt.dll  77BF0000 - 77C48000 v.7.0.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\SHLWAPI.dll  77EA0000 - 77F16000 v.6.0.2900.5512 [Apr 2008 9:00:00](14)
C:\Arquivos de programas\Miranda NG\MSVCR100.dll  78AA0000 - 78B5F000 v.10.0.40219.325 [Jan 2016 11:17:34](23)
C:\WINDOWS\WinSxS\x86_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.2600.5512_x-ww_35d4ce83\comctl32.dll  773B0000 - 774B3000 v.6.0.2900.5512 [Apr 2008 9:00:00](14)
C:\Arquivos de programas\Miranda NG\libs\mir_app.mir  121C0000 - 12283000 v.0.95.5.16299 [Feb 2016 19:52:24](17)
C:\WINDOWS\system32\WINMM.dll  76B20000 - 76B4E000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\WS2_32.dll  71A70000 - 71A87000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\WS2HELP.dll  71A60000 - 71A68000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\UxTheme.dll  5B1C0000 - 5B1F8000 v.6.0.2900.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\COMDLG32.dll  76380000 - 763C8000 v.6.0.2900.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\ole32.dll  774C0000 - 775FD000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\Arquivos de programas\Miranda NG\libs\zlib.mir  123E0000 - 123F7000 v.1.2.8.0 [Feb 2016 19:51:58](17)
C:\Arquivos de programas\Miranda NG\libs\mir_core.mir  12360000 - 1237F000 [Feb 2016 19:51:58](17)
C:\WINDOWS\system32\VERSION.dll  77BE0000 - 77BE8000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\Arquivos de programas\Miranda NG\Plugins\CrashDumper.dll  14920000 - 14930000 v.0.0.5.2 [Feb 2016 16:37:24](16)
C:\WINDOWS\system32\dbghelp.dll  59EA0000 - 59F41000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\Arquivos de programas\Miranda NG\Plugins\Dbx_mmap.dll  14AE0000 - 14AF1000 v.0.95.3.1 [Feb 2016 19:51:58](17)
C:\Arquivos de programas\Miranda NG\Core\stdcrypt.dll  130E0000 - 130EC000 v.0.95.5.16299 [Feb 2016 19:56:12](17)
C:\Arquivos de programas\Miranda NG\Core\stdssl.dll  131C0000 - 131C7000 v.0.95.5.16299 [Feb 2016 19:56:06](17)
C:\WINDOWS\system32\CRYPT32.dll  77A60000 - 77AF6000 v.5.131.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\MSASN1.dll  77B00000 - 77B12000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\Msftedit.dll  4B4B0000 - 4B536000 v.5.41.15.1515 [Apr 2008 9:00:00](14)
C:\Arquivos de programas\Miranda NG\Plugins\AdvaImg.dll  14220000 - 142AF000 v.0.11.0.2 [Feb 2016 16:36:38](16)
C:\Arquivos de programas\Miranda NG\MSVCP100.dll  78050000 - 780B9000 v.10.0.40219.325 [Jan 2016 11:17:34](23)
C:\Arquivos de programas\Miranda NG\Core\stdclist.dll  130C0000 - 130D0000 v.0.95.5.16299 [Feb 2016 19:56:12](17)
C:\Arquivos de programas\Miranda NG\Plugins\AIM.dll  14360000 - 1438A000 v.0.11.0.1 [Feb 2016 16:35:48](16)
C:\Arquivos de programas\Miranda NG\Plugins\AvatarHistory.dll  14480000 - 1448D000 v.0.1.0.1 [Feb 2016 16:38:06](16)
C:\Arquivos de programas\Miranda NG\Plugins\AVS.dll  144A0000 - 144B2000 v.0.95.3.4 [Feb 2016 16:35:36](16)
C:\Arquivos de programas\Miranda NG\Plugins\Facebook.dll  14BE0000 - 14C23000 v.0.2.12.0 [Feb 2016 16:36:58](16)
C:\Arquivos de programas\Miranda NG\libs\libjson.mir  12160000 - 1216C000 [Feb 2016 19:52:00](17)
C:\Arquivos de programas\Miranda NG\Plugins\GG.dll  14F20000 - 14F63000 v.0.11.0.3 [Feb 2016 16:35:58](16)
C:\Arquivos de programas\Miranda NG\Plugins\ICQ.dll  15520000 - 15573000 v.0.11.3.4 [Feb 2016 16:36:02](16)
C:\WINDOWS\system32\OLEAUT32.dll  77100000 - 7718B000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\Arquivos de programas\Miranda NG\Plugins\Import.dll  15680000 - 1568D000 v.0.95.4.2 [Feb 2016 16:35:36](16)
C:\Arquivos de programas\Miranda NG\Plugins\IRC.dll  15760000 - 157AE000 v.0.11.0.3 [Feb 2016 16:35:48](16)
C:\Arquivos de programas\Miranda NG\Plugins\Jabber.dll  15800000 - 1588F000 v.0.11.0.4 [Feb 2016 16:36:06](16)
C:\WINDOWS\system32\DNSAPI.dll  76F00000 - 76F27000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\Arquivos de programas\Miranda NG\Plugins\MSN.dll  15E20000 - 15E5A000 v.0.12.1.1 [Feb 2016 16:36:08](16)
C:\Arquivos de programas\Miranda NG\Plugins\PluginUpdater.dll  162A0000 - 162B3000 v.0.1.2.5 [Feb 2016 16:37:34](16)
C:\Arquivos de programas\Miranda NG\Plugins\WhatsApp.dll  174A0000 - 174D4000 v.0.1.3.3 [Feb 2016 16:39:14](16)
C:\Arquivos de programas\Miranda NG\Plugins\Yahoo.dll  175E0000 - 1760A000 v.0.11.0.2 [Feb 2016 16:35:56](16)
C:\Arquivos de programas\Miranda NG\Core\stduserinfo.dll  13200000 - 1320C000 v.0.95.5.16299 [Feb 2016 19:56:14](17)
C:\Arquivos de programas\Miranda NG\Core\stdemail.dll  13100000 - 13106000 v.0.95.5.16299 [Feb 2016 19:56:12](17)
C:\Arquivos de programas\Miranda NG\Core\stdauth.dll  13000000 - 13007000 v.0.95.5.16299 [Feb 2016 19:56:12](17)
C:\Arquivos de programas\Miranda NG\Core\stdfile.dll  13120000 - 1312F000 v.0.95.5.16299 [Feb 2016 19:56:12](17)
C:\Arquivos de programas\Miranda NG\Core\stdhelp.dll  13140000 - 13146000 v.0.95.5.16299 [Feb 2016 19:56:12](17)
C:\Arquivos de programas\Miranda NG\Core\stduihist.dll  131E0000 - 131E7000 v.0.95.5.16299 [Feb 2016 19:56:12](17)
C:\Arquivos de programas\Miranda NG\Core\stdidle.dll  13160000 - 13167000 v.0.95.5.16299 [Feb 2016 19:56:08](17)
C:\WINDOWS\system32\WTSAPI32.dll  76F30000 - 76F38000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\WINSTA.dll  76330000 - 76340000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\NETAPI32.dll  5BCB0000 - 5BD05000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\Arquivos de programas\Miranda NG\Core\stdautoaway.dll  13020000 - 13026000 v.0.95.5.16299 [Feb 2016 19:56:06](17)
C:\Arquivos de programas\Miranda NG\Core\stduseronline.dll  13220000 - 13226000 v.0.95.5.16299 [Feb 2016 19:56:12](17)
C:\Arquivos de programas\Miranda NG\Core\stdaway.dll  13040000 - 13049000 v.0.95.5.16299 [Feb 2016 19:56:10](17)
C:\Arquivos de programas\Miranda NG\Core\stdchat.dll  13060000 - 13083000 v.0.95.5.16299 [Feb 2016 19:56:12](17)
C:\Arquivos de programas\Miranda NG\Core\stdmsg.dll  13180000 - 13195000 v.0.95.5.16299 [Feb 2016 19:56:10](17)
C:\WINDOWS\System32\mswsock.dll  71A10000 - 71A50000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\rasadhlp.dll  76FA0000 - 76FA6000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\hnetcfg.dll  60B30000 - 60B88000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\System32\wshtcpip.dll  71A50000 - 71A58000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\System32\winrnr.dll  76F90000 - 76F98000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\WLDAP32.dll  76F40000 - 76F6D000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\schannel.dll  767D0000 - 767F7000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\USERENV.dll  769A0000 - 76A55000 v.5.1.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\rsaenh.dll  68000000 - 68036000 v.5.1.2600.5507 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\dssenh.dll  68100000 - 68126000 v.5.1.2600.5507 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\CLBCATQ.DLL  76FB0000 - 7702F000 v.2001.12.4414.700 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\COMRes.dll  77030000 - 770FD000 v.2001.12.4414.700 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\oleacc.dll  74C40000 - 74C6C000 v.4.2.5406.0 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\MSVCP60.dll  76050000 - 760B5000 v.6.2.3104.0 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\USP10.dll  74D50000 - 74DBB000 v.1.420.2600.5512 [Apr 2008 9:00:00](14)
C:\WINDOWS\system32\msls31.dll  74680000 - 746A7000 v.3.10.349.0 [Apr 2008 9:00:00](14)

**Comment by dartraiden** [comment]
Crashlog without symbols is useless.
