### ISSUE TITLE
whatsapp: no receive message, description in phones.

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#536]
**Reported by vaga on 20 Feb 2016 00:18 UTC**
in user of iphone 6 , latest version of whatsapp and ios, to send messages from miranda ng:
I can only send messages by notepad, i need to write in Notepad forward to WhatsApp.

in user of nokia = windows mobile , send messages to miranda ng ok

android not tested!

3 months in this problem!
thanks a miranda team

**Comment by dartraiden** [comment]
WhatsApp is deprecated.
