### ISSUE TITLE
Cyrillic "і" from translations don't show in console

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#541]
**Reported by dartraiden on 3 Mar 2016 20:54 UTC**

> [16:51:41] <RMN> в командной строке не отображается укр. буква "і" из перевода CmdLine
> [16:53:15] <RMN> какие-то чудеса в системной кодировке?
> [16:53:32] <watcher> в CMD-то?
> [16:53:58] <RMN> плагин command line
> [16:55:00] <watcher> а в самом cmd всё в порядке?
> [16:55:18] <watcher> скажем из батника запульнуть строку
> [16:56:03] <ghazan> может все же i с 2 точками?
> [16:56:14] <watcher> оно может в cmd работать в колировке 866
> [16:56:22] <RMN> с двумя точками нормально
> [16:56:42] <RMN> и "є" есть
> [17:00:47] <ghazan> watcher: оно и работает в кодировке 866
> [17:01:02] <ghazan> проблема в другом - буква i должна быть железно везде :)
> [17:03:39] <RMN> что написать в батнике, чтобы "запульнуть строку" ?
> [17:06:22] <watcher> echo "Рiдна Матка Украiна"
> pause
> [17:08:02] <RMN> хм.. полностью кракозябры
> [17:08:16] <watcher> i тоже?
> [17:09:01] <RMN> и правда, і на месте)
> [17:15:47] <RMN> хех.. ну я из чата скопировал, потому и на месте. вот и я думал, может в переводе тоже английскую вместо украинской сделать

**Comment by dartraiden** [comment]
Fixed in 8d127430d057891fbd3ac5989d32090715d7923a
