### ISSUE TITLE
Yahoo file transfer fails in 99% of cases when receiving

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#544]
**Reported by mikeroku on 16 Mar 2016 06:52 UTC**
File transfer fails in 99% of cases, when receiving a file.
I can't tell why, ''it seems'' it fails at the first event like status update of other contact than the one transferring the file from or any chat line...

**Comment by georgehazan** [comment]
**Comment by Ratha on 19 Mar 2016 15:26 UTC**
In 0.95.4, Yahoo file transfers sent to Miranda always fail if you've been logged into Yahoo for too long (more than a few hours.) The workaround seems to be simply to log out of Yahoo and then back in again and you should then be able to receive files again.

I reported this bug back in early 2015, but it was a bug that existed since before the move to Miranda NG, it existed in Miranda IM for awhile as well: http://trac.miranda-ng.org/ticket/928

If you update to Miranda 0.95.5 Dev, receiving a file from yahoo will crash Miranda entirely as reported here: http://trac.miranda-ng.org/ticket/1177 so if file transfers are important to you, upgrading is probably not in your best interest at this time.

**Comment by georgehazan** [comment]
**Comment by mikeroku on 21 Mar 2016 08:27 UTC**
Nope. I know that bug. This is different. It doesn't matters how long and it fails in all the networks I've ever been.

**Comment by aunsane** [comment]
Yahoo protocol was depricated b0f3e30460fc26ef4fe59bc161b0fddd8eeb9a08.
