### ISSUE TITLE
После смены пароля и изменении в программе, сервер не принимает авторизацию

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#548]
#547 **Reported by Metallurg IT on 5 May 2016 15:40 UTC**
После смены пароля и изменении в программе, сервер не принимает авторизацию

**Comment by georgehazan** [comment]
**Comment by dartraiden on 5 May 2016 15:57 UTC**
   20  .    ?

**Comment by dartraiden** [comment]
Если речь об ICQ, см. [примечания к выпуску 0.95.5](http://wiki.miranda-ng.org/index.php?title=%D0%98%D1%81%D1%82%D0%BE%D1%80%D0%B8%D1%8F_%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B9/0.95.5). Если речь о другом протоколе, то лучше открыть новый тикет. Этот я закрываю, невозможно понять, о каком протоколе идёт речь.
