### ISSUE TITLE
Miranda crashes at least once a day - Modern contact list

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#550]
**Reported by cakira on 12 May 2016 16:44 UTC**
The crash happens without apparent reason. Miranda isn't even showing itself in the screen and then crashes, out of nowhere, about once a day. When  the crash happens, it happens in bursts, I mean, sometimes after a crash, I reopen Miranda NG and the crash happens again in a matter of seconds. Sometimes it doesn't happen.

The probable culprit is Modern Contact List.

I'm using a Skin called Malice: http://amaeli.deviantart.com/art/Malice-Tab-Miranda-IM-123525163

[Moder_CList_crash.log.txt](https://github.com/miranda-ng/miranda-ng/files/658094/Moder_CList_crash.log.txt)

**Comment by georgehazan** [comment]
**Comment by cakira on 4 Aug 2016 20:44 UTC**
By trial and error, I found out that the problem was in my profile database.
It contained several repeated instances of some metacontacts. I manually deleted the entry for each metacontact and Miranda NG stopped crashing!  \o/

**Comment by LittleVulpix** [comment]
This can be closed, the issue was in user's database and was resolved by manually removing invalid entries.
