### ISSUE TITLE
OTR: "Conv HTML" field is changed together with "Policy" (incorrectly)

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#553]
**Reported by an809512 on 16 May 2016 23:01 UTC**
OTR: "Conv HTML" field is changed together with "Policy" (incorrectly)

Miranda NG v0.95.5 #16814
MirOTR v0.14.1.16 (the same night build)

Steps to reproduce:
1) Settings -> Services -> OTR
2) Find some contact that have values: Policy = "Default", Conv. HTML = "No".
3) Click on "No" value on this string, now it is changed to "Yes".
4) Then at the bottom of screen change "Current policy" from "Default" to "Opportunistic" (you will see the changes under cursort)
5) Then click "Apply" and "OK"
6) Now again go to: Settings -> Services -> OTR
7) Click on the same string on "Yes" in "Conv HTML" column to change it to "No".
8) Click "OK".
9) Now again go to: Settings -> Services -> OTR

Required behavior:
You will see the state: "Opportunistic" / "No"

Current behavior:
"Never" / "No"

So, OTR is disabled for this contact.

Really, Conv HTML settings changes policy settings by some bug.

---

In addition: previous versions of Miranda/OTR allowed to changed Policy by clicking on value in column (like ConvHTML column). Now it is possible to change only by selecting specified value in bottom combobox.

**Comment by georgehazan** [comment]
**Comment by an809512 on 24 Aug 2016 00:11 UTC**
Will someone fix that? Absolutely correct steps to reproduce. And I'm sure easy to fix it.

**Comment by ghsrcgh** [comment]
Why not to check this bug? I think that there is some mixup with indexes of array or something like that. The easiest bug to reproduce and fix.
