### ISSUE TITLE
SkypeWeb can't sign in with Microsoft ID; JavaScript required

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#554]
**Reported by dreamlayers on 22 May 2016 22:21 UTC**
I recently merged my Skype account with my Microsoft account. I can still log in with SkypeWeb using my Skype username and password, but I cannot log in with my Microsoft account. The Microsoft account uses an @yahoo.ca e-mail address.

Looking at the network log, I see that after the POST which sends login=myname&password=mypassword, the server responds with "JavaScript required to sign in" and redirects to https://login.live.com/jsDisabled.srf?mkt=EN-US&lc=1033

This is on Windows 10 with v0.95.5 alpha build #16859 x64

**Comment by aunsane** [comment]
fixed in 160ecb9.
