### ISSUE TITLE
No online Friends

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#555]
**Reported by Giovanni on 24 May 2016 04:08 UTC**
Since a little more then one week all my friends with the facebook protocol are offline. From one day to the other all are offline, even Mirana NG logged me in. I thought, there is something wrong with the tool, so I deleted everything and reinstalled it. I also deleted my profile and reconfigured Miranda NG from beginning. Same result. All my friends are offline and Miranda shows me that I am logged in. Where is the mistake or did facebook made changed on the chat?

**Comment by Robyer** [comment]
I'm closing this as the issue was already fixed (there were some Facebook changes).
