### ISSUE TITLE
Unable register in WhatsApp

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#558]
**Reported by jawhien on 31 May 2016 16:39 UTC**
Instead of send SMS with code: "Registration failed. Reason: old_version"

**Comment by georgehazan** [comment]
**Comment by dartraiden on 31 May 2016 19:49 UTC**
WhatsApp    ,   .
   ,   .

**Comment by dartraiden** [comment]
WhatsApp is deprecated.
