### ISSUE TITLE
Frequent disconnects on ICQ

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#559]
**Reported by Jojo on 1 Jun 2016 20:36 UTC**
Since about one or two weeks, my connection to the ICQ network seems to be unstable, while Jabber and Skype are okay. At some point, the connection seems to be dropped, but the plugin still appears as online. Only at the moment when I try to send a new message, it realizes that I am actually offline and fails to deliver the message until I reconnect.

**Comment by georgehazan** [comment]
**Comment by Jojo on 19 Jul 2016 16:52 UTC**
It seems like this is fixed by enabling the "keep-alive" option in ICQ settings - even though this is a perfectly stable cable network.

**Comment by dartraiden** [comment]
Protocol was rewritten from scratch, so we can close this. If problem happens again - please, reopen.
