### ISSUE TITLE
Openfire/XMPP: Miranda ignores e-mail updated in roster

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#562]
**Reported by Krizz on 6 Jun 2016 08:06 UTC**
I'm using global roster with user list pulled from AD. Once in a while users change a surname (marriage/divorce) and due to our policy it makes me update their e-mail address to current state (we use firstname.surname@ form). After I do so, Openfire displays new email address just fine, but Miranda ignores it when connecting to Openfire server. On the other hand, Miranda properly updates user's new surname after connecting.

The same applies to user's phone number, and I believe it could also affect other informational fields.

The only way to update user info is to manually remove the user from Miranda user list and reconnect to Openfire server.

**Comment by georgehazan** [comment]
**Comment by Davis on 8 Jun 2016 13:57 UTC**
I suggest to try to delete JABBER_1\LastLoggedServer key in miranda DB.
This will force own VCard updating during next server connection.
It is possible to do this via Action Manager on schedule

**Comment by georgehazan** [comment]
**Comment by Krizz on 10 Jun 2016 11:42 UTC**
How am I supposed to deploy Action Manager on tens of computers with predefined, custom action and schedule? If it's not possible, is there any other way to edit local DB in an unattended manner?

**Comment by georgehazan** [comment]
**Comment by Davis on 12 Jun 2016 13:20 UTC**
Sure you can.
look in mirandaboot.ini http://wiki.miranda-ng.org/index.php?title=Mirandaboot.ini/en
This way you can deploy any settings - export needed section on test system and deploy to others.
You can deploy Action Manager Dll too.
Particularily me do this via GPO login script that checks installed version of app and updates and copies updates and new settings to user's installation

**Comment by georgehazan** [comment]
**Modified by Davis on 12 Jun 2016 15:42 UTC**

**Comment by georgehazan** [comment]
**Comment by Krizz on 13 Jun 2016 06:34 UTC**
Thank you. I'm not sure how to use mirandaboot.ini to deploy database settings yet, but I'll take a look at this in testing environment.

Abstracting from this "workaround", is my submission going to be evaluated? I still don't suppose described behavior is on purpose.

**Comment by georgehazan** [comment]
**Comment by Krizz on 13 Jun 2016 06:58 UTC**
It looks good :) So far I've been deploying profiles via predefined template profile, but deployment via ini file seems to be a much better option. 
Can you tell me if it is possible to remove an ini section via those ini files?

**Comment by georgehazan** [comment]
**Comment by Davis on 13 Jun 2016 08:53 UTC**
Sure, as stated here: http://forum.miranda-ng.org/index.php?topic=262.0

KeyName=l  - key removing
[?BranchName] - section removing

**Comment by georgehazan** [comment]
**Comment by Davis on 13 Jun 2016 08:58 UTC**
>is my submission going to be evaluated?
I'm not a developer, I just use Miranda in my company as part of a local chat system.
But I'm programmer, so I've found that Miranda gets full VCard from server only at first connection to this server(LastLoggedServer) and when user manually opens My Info dialog.
This is by design.
But in case of local chat I need to update own VCard at least daily, so I've found this workaround and I think it is quite fine.

**Comment by georgehazan** [comment]
**Comment by Krizz on 13 Jun 2016 12:14 UTC**
Replying to [Davis](comment:7):
> Sure, as stated here: http://forum.miranda-ng.org/index.php?topic=262.0

I obviously don't know russian, but thank you. This will do.

**Comment by georgehazan** [comment]
**Comment by Davis on 13 Jun 2016 12:33 UTC**
Replying to [Krizz](comment:9):
I translated it for you :)

**Comment by georgehazan** [comment]
**Comment by Davis on 1 Jul 2016 11:26 UTC**
Is problem solved?

**Comment by georgehazan** [comment]
**Comment by Krizz on 1 Jul 2016 13:26 UTC**
Problem is not solved because it relates to Miranda-NG itself. By design, as you say.

I have a problem with your workaround, too - deleting the key JABBER_1\LastLoggedServer doesn't change a thing - after reconnection to Openfire server user is still there with his old email address. I need to remove user himself from database (Contacts) so it makes Miranda re-fetch his profile with correct email address. Is there a way to auto-remove all contacts branches?

**Comment by georgehazan** [comment]
**Comment by Davis on 11 Aug 2016 12:41 UTC**
Replying to [Krizz](comment:12):
I've reread first message...
>Miranda ignores it
Miranda of user whom email you changed?
Or Miranda of all other users?

**Comment by georgehazan** [comment]
**Comment by Krizz on 12 Aug 2016 05:47 UTC**
Everyone have the roster contacts pulled with no update of email address.

**Comment by georgehazan** [comment]
**Comment by Davis on 12 Aug 2016 09:10 UTC**
If we speaking about refreshing info about contacts in roster, then try to use this:
1. install http://wiki.miranda-ng.org/index.php?title=Plugin:WhenWasIt/en plugin
2. Create new action in ActMan (name it #Autostart to run it at every run)
3. Type of action: service call. Service: 
```
WhenWasIt/Birthdays/RefreshDetails
```


After every Miranda start this action force to read VCards from server for all contacts in roster.

**Comment by georgehazan** [comment]
**Comment by Davis on 12 Aug 2016 09:14 UTC**
BTW. I hope you did not use this name
```
JABBER_1\LastLoggedServer?
```
This engine adds question sign. I meant:
```
JABBER_1\LastLoggedServer
```
And JABBER_1 is in my case, you better look in you DB to see your names

**Comment by georgehazan** [comment]
**Comment by Krizz on 16 Aug 2016 06:11 UTC**
It's 
```
JABBER_1\LastLoggedServer
```
Not sure why this question mark appeared there... something with autoparsing by Trac? No matter.
And yes, it's JABBER_1 in my case, too.
Btw. I didn't use Action Manager. I thought it's too much of an unnecessary hassle. I based on ''autoexec'' ini file created by GPO preferences. According to docs it should work the same. This file contains:
```
[JABBER_1]
LastLoggedServer=l
```
among other settings.

**Comment by georgehazan** [comment]
**Comment by Davis on 16 Aug 2016 10:38 UTC**
I've tested manual deletion via DB editer and with ActMan. There is possibility that removing this key via INI file may be too late and thus useless...

**Comment by georgehazan** [comment]
**Comment by Krizz on 16 Aug 2016 11:01 UTC**
Hmm, too bad. But I'm too busy right now for figuring this out. Anyway, thanks, you've pointed me the right direction.

**Comment by dartraiden** [comment]
https://forum.miranda-ng.org/index.php?topic=5831.msg25044#msg25044
