### ISSUE TITLE
Vkontakte: crash on "netliblog.cpp (413): NetlibDumpData" and "vk_queue.cpp (58): CVkProto::ExecuteRequest" and

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#568]
**Reported by Corak on 19 Jun 2016 13:34 UTC**
Likely cause of the crash plugin: VKontakte protocol

Exception: Access Violation at address 120DE20A. Reading from address DDDDDE51.
## Stack Trace:

120DE20A (mir_app 12060000): d:\soft\network\im\miranda\src\trunk\src\mir_app\src\netliblog.cpp (413): NetlibDumpData
120D9F57 (mir_app 12060000): d:\soft\network\im\miranda\src\trunk\src\mir_app\src\netlibhttp.cpp (1134): NetlibHttpRecv
120D9817 (mir_app 12060000): d:\soft\network\im\miranda\src\trunk\src\mir_app\src\netlibhttp.cpp (893): NetlibHttpTransaction
1230F208 (mir_core 12300000): d:\soft\network\im\miranda\src\trunk\src\mir_core\src\modules.cpp (543): CallService
17126A75 (VKontakte 17120000): c:\sources\miranda_ng_compilation\protocols\vkontakte\src\vk_queue.cpp (58): CVkProto::ExecuteRequest
17126DB9 (VKontakte 17120000): c:\sources\miranda_ng_compilation\protocols\vkontakte\src\vk_queue.cpp (168): CVkProto::WorkerThread
12319684 (mir_core 12300000): d:\soft\network\im\miranda\src\trunk\src\mir_core\src\threads.cpp (159): forkthreadex_r
7C80B729 (kernel32 7C800000): (filename not available) (0): GetModuleFileNameA

**Comment by ElzorFox** [comment]
No netlog and I cannot reproduce this.
