### ISSUE TITLE
Copyright problem with Facebook emoticons

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#573]
**Reported by dartraiden on 6 Jul 2016 09:11 UTC**
http://trac.miranda-ng.org/changeset/17059

Some of this images are not simple geometric forms, so it's probably copyright protected. Should we add copyrighted images directly our GPL sources? Usually similar images are distributed separately in smiley packs.

**Comment by georgehazan** [comment]
**Modified by dartraiden on 7 Jul 2016 17:25 UTC**

**Comment by georgehazan** [comment]
**Comment by robyer on 31 Aug 2016 10:17 UTC**
These particular icons for notifications will be downloaded and cached on the fly, so I will remove it from there when implemented. But we still have in code many other icons taken directly from Facebook. And not only facebook, other plugins/protocols too.

So, I'm not sure what should we do. Do we have some graphic designer to prepare all own icons for us?

**Comment by Robyer** [comment]
I think this isn't problem only in Facebook plugin and we should rather discuss some solution on "global scale".
