### ISSUE TITLE
Cannot add new contacts to contact list—ICQ Protocol

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#576]
**Reported by Llewen on 13 Jul 2016 00:51 UTC**
When I try adding a new contact to my contact list in ICQ, nothing happens.  I hit the add contact button, fill in the information, hit search, select the appropriate contact, select my options the add contact window, hit add and nothing happens.  The same thing happens if I try to add the contact directly without searching first.  I've tried disabling all my plugins one at a time, and it makes no difference.

[VersionInfo.txt](https://github.com/miranda-ng/miranda-ng/files/658181/VersionInfo.txt)

**Comment by georgehazan** [comment]
**Comment by dartraiden on 13 Jul 2016 11:22 UTC**
Go to Options  Contacts  Ignore and search this lost contacts here. If they exists, simple check combobox near this contacts.


I think it's bug http://trac.miranda-ng.org/ticket/981
If contacts creates as temporary (for example if you search this first) it wrongly have "Hidden = 0x1" parameter in database.

**Comment by georgehazan** [comment]
**Comment by Llewen on 13 Jul 2016 20:40 UTC**
I did figure out that if I went to my ICQ account settings, the contacts had been added to my list on the server, but I had to manually click on the option to show the contact on my contact list for each one.  I'd say it's a bug.

**Comment by dartraiden** [comment]
Duplicate of #402
