### ISSUE TITLE
XMPP/Jabber: Implement  XEP 280 (Carbon Copies)

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#577]
**Reported by spaetz on 13 Jul 2016 12:43 UTC**
Hey, as multiple clients become more and more important, one extension would be crucial to support: Message Carbons make sure that answers are delivered to all connected devices. Daniel Gultsch, author of the popular "Conversations" xmpp client has written about the mobile state of XMPP here (https://gultsch.de/xmpp_2016.html) and he explicitely referred to XEP 280 as one of the features where XMPP can be better than e.g. whatsapp.

XEP is here: https://xmpp.org/extensions/xep-0280.html

**Comment by himselfv** [comment]
Here's an attempt at implementing carbons https://github.com/himselfv/miranda-ng/commit/722b95c6b8b9d36deba0a0db7103868a775c363d

Opinions? I can work on this if something needs to be done differently.

**Comment by himselfv** [comment]
Sure https://github.com/miranda-ng/miranda-ng/pull/1126

**Comment by himselfv** [comment]
Also this https://github.com/miranda-ng/miranda-ng/pull/1127
