### ISSUE TITLE
Steam - Wrong text when user adds you to their contact list.

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#578]
**Reported by Ratha on 18 Jul 2016 20:20 UTC**
 1: When someone adds you to their Steam friends list, Miranda displays the text "[user] has been removed from your contact list." It should say '[user] has added you to their contact list.' or '[user] sent you a Steam friend invite/request.'

2: When you accept this friend invite through either Steam or Miranda, and then close and re-open Miranda you get the message: "[user] is back in your contact list." (But they shouldnt have left your contact list after you accepted their friend invite? Is something happening between accepting the friend invite and restarting Miranda or is this just a text bug too?)

[VersionInfo.txt](https://github.com/miranda-ng/miranda-ng/files/658184/VersionInfo.txt)

**Comment by georgehazan** [comment]
**Comment by robyer on 19 Sep 2016 18:59 UTC**
It should be just wrong text (wrong "detection" of change). I'll try to fix it when I will have some time.

**Comment by Robyer** [comment]
This should be fixed, but I couldn't test it yet. Let me know if it is still not fixed.

**Comment by LittleVulpix** [comment]
@Robyer This is not fixed... seems to be exactly the same right now.

**Comment by aunsane** [comment]
@LittleVulpix, please check it to next nightly.

**Comment by LittleVulpix** [comment]
@georgehazan this keeps causing me a lot of pain lately, with Steam. It happens at least once a week that I get the "has been removed from your contact list" for all my contacts, and then "is back in your contact list" again on next login. The problem is the modal dialog prevents the actual protocol from working and it usually happens when I'm asleep. Can this be made into just a console log instead of an actual popup alert ?

**Comment by georgehazan** [comment]
It might be just a broken / wrong http-packet which is received as an answer to friends list request, and Miranda somehow treats this response as an empty packet and thus wipes out all contacts from your friends :-) If you could make a network log with that "has been removed" (Steam + core), that would be great (you know how to contact me)

**Comment by georgehazan** [comment]
it now works via standard auth dialog, so there should be no messages like that at all. closing
