### ISSUE TITLE
LeftClientMargin

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#581]
**Reported by Dvorak Stepan on 31 Jul 2016 12:28 UTC**
If LeftClientMargin=b0 ShowDelay not working (ShowDelay is constantly 0).

**Comment by georgehazan** [comment]
**Modified by Dvorak.Stepan on 31 Jul 2016 12:30 UTC**

**Comment by tweimer** [comment]
Duplicate of #618
