### ISSUE TITLE
Список контактов недоступен, будет использоваться локальный

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#589]
**Reported by Destr3 on 30 Aug 2016 13:48 UTC**
Периодически пишет ошибку "Список контактов на сервере недоступен, Miranda будет использовать локальный". При этом все контакты становятся недоступны и статус сменяется на "Не в сети". Приходится вручную переключать его как "в сети". Подключение через SSL и MD5.

**Comment by georgehazan** [comment]
**Comment by dartraiden on 30 Aug 2016 15:35 UTC**
 ,   - (      ).

**Comment by georgehazan** [comment]
**Modified by dartraiden on 30 Aug 2016 15:36 UTC**

**Comment by georgehazan** [comment]
**Comment by apollo2k4 on 30 Aug 2016 17:51 UTC**
Replying to [Destr3](ticket:1301):
>   SSL  MD5.
SSL  MD5      ..     .    MD5       GPU.

**Comment by georgehazan** [comment]
**Comment by apollo2k4 on 30 Aug 2016 17:54 UTC**
Replying to [dartraiden](comment:1):
>  ,   - (      ).
,       ,     -  -      -,       netlog.
     ..      .

**Comment by dartraiden** [comment]
Мы переписали протокол, по идее, больше мусора быть не должно.
