### ISSUE TITLE
ImportTXT utf8 historyplusplus import problem

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#591]
**Reported by erty on 2 Sep 2016 00:22 UTC**
 Can import history++ txt-exported files only if they in "Unicode BOM" encode (but can't import same files with utf8 or utf8sig encode)

Miranda-NG x32 v0.95.5, v0.95.6 b17233

**Comment by georgehazan** [comment]
**Modified by erty on 2 Sep 2016 00:25 UTC**

**Comment by georgehazan** [comment]
**Modified by erty on 2 Sep 2016 00:58 UTC**

**Comment by georgehazan** [comment]
**Modified by erty on 2 Sep 2016 01:00 UTC**

**Comment by dartraiden** [comment]
ImportTXT is deprecated.
