### ISSUE TITLE
ImportTXT message export import problem

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#592]
**Reported by erty on 2 Sep 2016 00:29 UTC**
 ImportTXT (Message export import pattern) can't import messages, which have been exported by msg_export module.
error:
Header not found

Miranda-NG x32 v0.95.5, v0.95.6 b17233

**Comment by georgehazan** [comment]
**Modified by erty on 2 Sep 2016 00:58 UTC**

**Comment by georgehazan** [comment]
**Modified by erty on 2 Sep 2016 01:00 UTC**

**Comment by dartraiden** [comment]
ImportTXT is deprecated.
