### ISSUE TITLE
QuickSearch: Copying contacts into clipboard works incorrect

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#597]
**Reported by wishmaster on 7 Sep 2016 16:26 UTC**
It seems that if you copy contacts from QuickSearch window into the clipboard, it does not copy the columns selected, but it always copies the first colomns in the order in the options dialog.

So if you select 8 columns in tehe options dialog, and you put an unseelected item above a selected item, the unselected one will be choosen instead of the selected.

**Comment by dartraiden** [comment]
@tweimer can you test it on c++ version of QS? :)
