### ISSUE TITLE
FB creates two events on friend request approval

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#598]
**Reported by ghazan on 19 Sep 2016 18:37 UTC**

![29755415206_11d5cbe716](https://cloud.githubusercontent.com/assets/5046855/21319103/e564ea46-c61c-11e6-9e01-a0d44b999fac.jpg)

**Comment by georgehazan** [comment]
dunno, I hadn't received any friend requests for a while

**Comment by Robyer** [comment]
I just approved friend request and it didn't generated no events in Miranda at all. So probably change on Facebook side.
