### ISSUE TITLE
v0.95.6 alpha build #17338 - IRC fails to recognize self status change

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#600]
**Reported by CDB Man on 29 Sep 2016 23:09 UTC**
When on an IRC channel, if I received +o, +h, +v, etc, MirandaNG fails to recognize this.  If I join the channel from a separate client, I can see that the nick signed in with Miranda is in fact op'd as expected.

When  say fail to recognize, it includes the following:

> does not show @ beside my nick in chat lines
> does not show @ beside my nick in the userlist
> cannot access channel manager (ie to change topic, add/remove ban, etc)

**Comment by dartraiden** [comment]
Partially confirmed. Test results:

**If I'm no op** and some give me +o: in nicklist I'm still visible as user. I **can** change topic, room settings bans, but I **can't** give or take o, h, v to others (_"Control"_ menu item is grayed out).

**If I'm op** and some take -o: in nicklist I'm still visible as op.
