### ISSUE TITLE
LastSeen plugin don't work with accounts which use "space" in internal name

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#607]
1) Create account with **internal** name "test 1".
2) Check it on LastSeen options page, press OK.
3) Open LastSeen options page again - account is unchecked. So LastSeen can't work with such account. But it works in Miranda IM.

**Comment by dartraiden** [comment]
Maybe we should block creating accounts with spaces in internal name.
Or just put warning about this in account manager.

**Comment by theultramage** [comment]
It doesn't work because it saves the selected protocols as a space-separated list:
saving:
```
							watchedProtocols.AppendChar(' ');
						watchedProtocols.Append(protocol);

				db_set_s(NULL, S_MOD, "WatchedProtocols", watchedProtocols);
```
loading:
```
	ptrA szProtos(db_get_sa(NULL, S_MOD, "WatchedProtocols"));
	for (char *p = strtok(szProtos, " "); p != NULL; p = strtok(NULL, " "))
		arWatchedProtos.insert(mir_strdup(p));
```

**Comment by White-Tiger** [comment]
I'd suggest an \n as that's impossible to input/save and a "usual" delimiter for a list.
Otherwise ";" would have been a better choice as well.. but the internal name seems to be able to support _any_ character. Tab can be copied and pasted into it for example.. but \n can't... we could also use \1 but that'll not really allow manual edits (if one wants to)

**Comment by theultramage** [comment]
I suggest using (or implementing) a miranda tacility for serializing/unserializing data. One approach I know of is https://github.com/eathena/eathena/blob/master/src/common/strlib.c#L731 sv_escape_c() and sv_unescape_c() which perform C-style escaping. It takes an optional list of extra characters to escape, which get turned into octal representation. Using this on existing data would cause a lookup failure for people who have backslashes in their internal protocol names.
(an alternative solution is to drop the whole protocol selection thing and just watch them all)

**Comment by georgehazan** [comment]
we already have json for lists serialization, why do we need anything else?
and yes, using \n as a delimiter looks much more promising

**Comment by Mataes** [comment]
delimiter changed to "\n" in ff728bb

**Comment by theultramage** [comment]
Btw, not sure, but there doesn't seem to be any backwards compat mechanism. Will this change corrupt the data of all existing users?

**Comment by Robyer** [comment]
@theultramage Thanks for notice, I added commit to fix that.
