### ISSUE TITLE
MRA: error message "Disconnected, socket read error"

### ISSUE THREAD

**Issue by olmor** [miranda-ng/miranda-ng#616]
¤ MRA.dll v.2.1.1.1 [31 Oct 2016 4:01:20] - Mail.ru Agent 

Error message 'MRA: Disconnected, socket read error' is often appeared after turning on (waking up) of Windows tablet. Why such low level error messages are shown to user?
I use toaster plugin for notifications.
OS version is Windows 8.1.

I need the way to suppress such error messages or please move these messages to debug level.

**Comment by dartraiden** [comment]
I think we should replace
`ShowFormattedErrorMessage(L"Disconnected, socket read error", dwRetErrorCode);` in Mra_proto.cpp and MraMRIMProxy.cpp by
debugLogA("Disconnected, socket read error\n");
