### ISSUE TITLE
Протокол vk, при наборе текста сообщения не помечаются прочитанными на сервере.

### ISSUE THREAD

**Issue by voditelnlo** [miranda-ng/miranda-ng#620]
Протокол vk, при наборе текста сообщения не помечаются прочитанными на сервере.

**Comment by apollo2k4** [comment]
В настройках выбран соответствующий параметр?

**Comment by ElzorFox** [comment]
Нужны ВИ и  нетлог.

**Comment by devcline** [comment]
та же проблема.

**Comment by ElzorFox** [comment]
Вероятнее всего, у тех, кто жалуется, вообще отключены уведомления о наборе в настройках *SRMM - без этого прочтение при наборе работать не будет.
В любом случае, лога и ВИ нет и ,судя по всему, не будет, так что тикет закрываю.

**Comment by devcline** [comment]
У меня действительно, отключено уведомление других людей о МОЕМ наборе текста.
что бы это работало, надо свой тоже отправлять "набор текста"

Лог слишком мутный, лишнего не хочу нечего отправить публчино.
![screenshot_2](https://cloud.githubusercontent.com/assets/617020/21776280/13098b40-d69a-11e6-820d-8114f010cafb.png)

**Comment by ElzorFox** [comment]
Да, чтобы работало прочтение при наборе текста, нужно чтобы была включена отправка уведомлений о наборе. Иначе в плагин ВК не попадают эвенты, что вы печатаете.
Вообще нетлоги всегда можно отправить мне на почту, но в данном случае в этом, очевидно, уже нет смысла.

**Comment by devcline** [comment]
Получается не очень удобно в моем случае, я то переживу, но отпишусь.

- При прочтении: когда открываю окно, cам решаю важность ответа, поэтому предпочитаю ответить сразу или позже. 
- При получении: пользователь думает что ты просмотрел сообщение, но тебя нету у компьютера
- Помечать при наборе: только если включить функцию о наборе текста 
- При ответе (это стоит у меня): Если ты не ответил то сообщение не прочитано а значит пользователь думает что ты его не прочитал. приходится кликать каждый раз на "пометить сообщение прочитанным" Как можно засунуть эту кнопку поближе, например в панель кнопок сообщения? Наверное никак:)

Спасибо

**Comment by ElzorFox** [comment]
На это я могу сказать только то, что ни один клиент кроме миранды вообще на этот счет никаких настроек не имеет. Что касается кнопки поближе - возможно (я не проверял и этими плагинами не пользуюсь) это можно сделать через плагин Actman или через плагин MirLua.
