### ISSUE TITLE
SkypeWeb: network communication infinite loop after longer uptime

### ISSUE THREAD

**Issue by theultramage** [miranda-ng/miranda-ng#622]
Whenever I leave Miranda running for some time, it always starts spamming a trouter.io subdomain with the same sequence of http requests, one of them ending with "HTTP/1.1 400 Bad Request". It keeps doing it infinitely with no pause inbetween. This generates several tens of kB/s of wasted traffic. It may be that this bug was there from the start, masked by the [trac#1019](http://trac.miranda-ng.org/ticket/1019) NetlibHttpRecvChunkHeader infinite loop hang (I remember that the domain involved was .drip.trouter.io as well).

Here is a [network and protocol log](https://gist.github.com/theultramage/fe69332d1635d94f8a745f17f5660382) showing several repeats of the loop. I can't tell where the starting point is.

**Comment by LittleVulpix** [comment]
I have a similar issue. SkypeWeb is quite unstable, i.e. it will disconnect every 8-12 hrs +- (maybe more often but this is how often I notice)

**Comment by Robyer** [comment]
Longer log from Fiddler, capturing start of the problems, would be appreciated. (Sent it via e-mail or IM to me, as it might contain private info).

Also, do you use OpenSSL plugin? That in the past caused various problems...

**Comment by theultramage** [comment]
As this for me takes an unknown amount of uptime (7+ days?) to start happening, and there's no visual indication that it is happening, it's hard to catch the exact moment. If there is no further progress on this, I guess I could try setting it up and let it run. OpenSSL is not used, btw.

**Comment by Robyer** [comment]
I'm not familiar with Skype communication, but that sounds like session expires or something. And in code I can see that there is no way of disconnecting plugin when that happens. I'll try to investigate code a bit more and put some condition to disconnect plugin when such situation happens so it won't cycle forever like now...

**Comment by LittleVulpix** [comment]
Hmm, for me, Skype is the only protocol that still disconnects (somewhat often and somewhat randomly). Sometimes it'll run for 2-3 days no problem (then disconnect). Sometimes it won't stay online for more than 2 hours. If what you say is true @Robyer , what is handling the disconnects in my case? :o The plugin does go offline when it happens.

**Comment by Robyer** [comment]
@LittleVulpix There are two different "persistent connection" threads - polling thread and trouter thread. I don't know how they differ and what things they process, but from polling thread there is condition that could setStatus(OFFLINE) and thus disconnect the plugin. But in trouter there is no such condition or way. So that explains your situation and my comment above.

Also there seems to be problem with both polling and trouter. If I understand the code correctly, there is no other way to jump out of repeating the polling/trouter than by exiting whole Miranda. *looking at code a bit more* Aha, it's designed this way, so it creates the threads at account initialization and exits them at Miranda termination. So that's probably not an issue.

**Comment by Robyer** [comment]
I believe my fix will stop this infinite loop and will just disconnect plugin instead. In netlog you will see line ": unexpected termination; switching protocol to offline" beginning with "PollingThread" or "TRouterThread".

@LittleVulpix Also I commited 30aa1e735ee6568f598c0b2a04e0b691d68c6a18 with hope it will improve your often disconnections.

**Comment by LittleVulpix** [comment]
@Robyer for some reason after these changes, whenever skype does fail, I am not able to reconnect anymore. I have to restart miranda and then I can reconnect.

**Comment by Robyer** [comment]
@LittleVulpix Nelog would be helpful. Capturing fail and next attempt(s) to reconnect.

**Comment by LittleVulpix** [comment]
@Robyer poke me on tox or whereever, I still have the netlog from the issue :)

**Comment by Robyer** [comment]
Will do when I have some time. I was sick last week (I still am a bit) so I wasn't doing Miranda much...
