### ISSUE TITLE
Плагин MRA и глюки уведомлений в трее о новой почте

### ISSUE THREAD

**Issue by MonsterNya** [miranda-ng/miranda-ng#624]
Приветствую! Пользуюсь Miranda NG 0.95.5.17337 с плагином MRA.dll v2.1.1.1. Уже довольно продолжительное время (после одного из обновлений) уведомления MRA о почте в трее неадекватно себя ведут, или конверт не мигает (просто отображается) или спамит его кучу раз (т.е. я щелкаю по нему, чтобы открыть почту в браузере, а он не пропадает, пока не откроешь его раз 5). В итоге не отображаются в трее значки нового сообщения, может зависнуть иконка "вышёл в сеть", в том числе в главном окне миранды. 
Пробовал ставить отдельно новую версию и создавать там новый профиль, всё тоже самое.
p.s. в настройках - сеть - mail - соединения, стоят галки "уведомлять о почте, только если счетчик увеличился", "показывать значок в трее при наличии новой почты", "проверить почту щелчком".

**Comment by dartraiden** [comment]
MRA is deprecated.
