### ISSUE TITLE
There are an issues with converting issues from TRAC to GITHUB

### ISSUE THREAD

**Issue by ghsrcgh** [miranda-ng/miranda-ng#625]
There are an issues with converting issues from TRAC to GITHUB:

Original, correct: http://trac.miranda-ng.org/ticket/722
New, damaged: https://github.com/miranda-ng/miranda-ng/issues/311

Original, correct: http://trac.miranda-ng.org/ticket/724
New, damaged: https://github.com/miranda-ng/miranda-ng/issues/312

Original, correct: http://trac.miranda-ng.org/ticket/726
New, damaged: https://github.com/miranda-ng/miranda-ng/issues/313

Please reconvert original tickets that were damaged due conversion process

**Comment by georgehazan** [comment]
done
