### ISSUE TITLE
 GTalk extention stoped working after update 

### ISSUE THREAD

**Issue by mymurkas** [miranda-ng/miranda-ng#628]
I've always used the GTalk extention for email notifications (with Popup plugin). But recently, after the letest Miranda NG update 0.95.5 build #17337, or if it was the pluin it self that updated, it stoped working. Anyone with the same problem?

**Comment by georgehazan** [comment]
well, it has nothing to do with GTalkExp, cause Google physically stopped to send these notifications via XMPP... perhaps there is a solution, but I don't know it

**Comment by mymurkas** [comment]
I see. Thanks for that. I now learned that [Gmail Multiple Notifier](http://wiki.miranda-ng.org/index.php?title=Plugin:GmailNotifier/en) still works.

**Comment by Robyer** [comment]
@georgehazan @watcherhd Is there any other function that GTalkExt provides? Or should we make whole plugin deprecate then?

**Comment by georgehazan** [comment]
there is another plugin, GMail Notifier, that works

**Comment by dartraiden** [comment]
Plugin is deprecated.
