### ISSUE TITLE
диспетчер задач 

### ISSUE THREAD

**Issue by devcline** [miranda-ng/miranda-ng#637]
А есть ли у миранды свой диспетчер задач? Плагин?
В связи с таким количесвом плагинов хотелось бы оптимизировать миранду, но для этого нужно знать какой плагин больше всего жрет памяти или же сколько использует CPU

У хрома такое есть.

**Comment by apollo2k4** [comment]
Нет, такого нет и быть те может. У Google Chrome/Chromium/ext Chomium-like браузеров другая архитектура приложения, там есть разделение на процессы, в миранде все работает в рамках одного процесса.

**Comment by devcline** [comment]
И никаких методов , кроме "метода тыка" как я понял нету? ок спасибо

**Comment by apollo2k4** [comment]
Process Explorer?
