### ISSUE TITLE
skype web

### ISSUE THREAD

**Issue by David1501** [miranda-ng/miranda-ng#639]
Hello,
"it's" on Miranda show up as #it&#x 27;s#(had to put a space between x and 27 otherwise it was not showing up correctly). I suppose the problem here is that it was written in skype but miranda dunno how to translate it...Is there a fix?

THX

David

**Comment by LittleVulpix** [comment]
I can confirm this happens to me as well but generally when I'm receiving messages from the iPhone skype (to miranda). It doesn't happen with the other ones or at least I'm not aware of this.

**Comment by Robyer** [comment]
Should be fixed in next build, but I couldn't test it, so let me know if that works ;-)

**Comment by David1501** [comment]
Ok i will :-)

THX

**Comment by LittleVulpix** [comment]
It's working for me!

**Comment by David1501** [comment]
????? did i miss out on somethin?  Robyer said: Should be fixed in next build...
I did not get any update....!!! today

**Comment by LittleVulpix** [comment]
It is out already. If you have your miranda set to check for updates every launch - or if you check for them manually-forcibly now, you will get it.

**Comment by David1501** [comment]
I have it set like that...but normally it advise me about the update...and today i did not see anything...

**Comment by LittleVulpix** [comment]
Because it was compiled literally ~30 minutes ago :D

**Comment by David1501** [comment]
Ah ok then! :-)

THX

**Comment by David1501** [comment]
OK checked and it's fix! THX !!!!!!
