### ISSUE TITLE
Steam+Skype+OpenSSL

### ISSUE THREAD

**Issue by SmilingSpectre** [miranda-ng/miranda-ng#645]
I am trying to use Miranda NG with Steam and Skype plugins.

At home (with Win10 x64) there is no problems - both protocols works.

At work (WinXP x32) Skype works, but Steam is not. Seems, after last changes they changed also SSL authentication that caused Steam plugin to stop working.

Installing OpenSSL plugin (and correspondent libraries into Windows) fixed the problem with the Steam. Unfortunately, while OpenSSL is active, Skype stops to work! It tries to connect indefinitely.

Is there any way to make both protocols work simultaneously on WinXP?

**Comment by Robyer** [comment]
@georgehazan Is there still that problem with netlib and OpenSSL? I thought you fixed it once with that "cache" or something, but lately more users reported some high CPU usage with OpenSSL and also this problem above with SkypeWeb seems it's not really fixed.

**Comment by LittleVulpix** [comment]
@SmilingSpectre can you re-test it now? Miranda has its own SSL libraries now. Please check and let us know!

**Comment by SmilingSpectre** [comment]
Am I need daily build for that, @LittleVulpix? I'll check it then later.

**Comment by LittleVulpix** [comment]
@SmilingSpectre It's already in since 6days ago https://github.com/miranda-ng/miranda-ng/commit/adc9831eb28ab13ae2d9ce37b82436193d06eacd (assuming you use miranda alpha)

**Comment by dartraiden** [comment]
Closed in favor of #930

**Comment by dartraiden** [comment]
Oops, wrong tab

**Comment by dartraiden** [comment]
OpenSSL plugin is deprecated. If problem is still actual please reopen issue
