### ISSUE TITLE
MSN: unable to connect

### ISSUE THREAD

**Issue by theultramage** [miranda-ng/miranda-ng#647]
For many many months I haven't been able to get the MSN protocol to go online. Others I've asked say it works for them. The protocol log:

[56042061ef0a01367ca90a3797d84454-82528797a65504559dab0849db298395d9a755cf.zip](https://github.com/miranda-ng/miranda-ng/files/912776/56042061ef0a01367ca90a3797d84454-82528797a65504559dab0849db298395d9a755cf.zip)

From what I read there - it goes to s.gateway.messenger.live.com, then requests oauth auth from login.live.com, is given a no-javascript error page where it gets a link to post the auth request, which it does. It gets back a pile of cookies and the connection is closed. Then it tries to connect to skypewebexperience.live.com which is a nonexistent domain, and the process aborts.

**Comment by THEtomaso** [comment]
You're not alone.
I've never been able to log on to MSN, using Miranda NG.

**Comment by theultramage** [comment]
Ah, it used to work, then it didn't, then I update and reset the hostnames and it worked again, and then it stopped. According to LastSeen, the last time alive was 2016-03-18 12:29 UTC.

**Comment by leecher1337** [comment]
Please ensure that you have the OpenSSL library installed correctly, the host that is trying to get contacted is only a (now defunct) alternative login method which was used as a fallback, if OpenSSL is not present.
Ensure, that libeay32.dll from OpenSSL is accessible for Miranda installation.

**Comment by theultramage** [comment]
I disabled the OpenSSL plugin because it caused issues with SkypeWeb. But libeay32.mir is present in Libs/. I see a reference to libeay32.mir in msn.dll, and no mention of libeay32.dll in any miranda binary. Is that good enough?

**Comment by leecher1337** [comment]
Seems like ghazan changed it to openSSL plugin instead of the external openSSL library, found the commit from February.
So it works now, can we close the issue then?

**Comment by theultramage** [comment]
Indeed. Thank you for looking into it.
