### ISSUE TITLE
Cannot connect to MSN - MSVCR120 missing

### ISSUE THREAD

**Issue by sagamusix** [miranda-ng/miranda-ng#648]
First off, I know that I can simply install the VS2013 runtime. However, since this plugin previously worked, I suspect that something in your build process has changed and it is not intentional. After all, why should Miranda users be required to install several different runtime libraries?
When starting Miranda (64-bit), I get two messages that MSVCR120.dll cannot be loaded, followed by a message that OpenSSL is not available. After that, Miranda starts normally but no longer can connect to MSN. Everytime I try to connect to MSN, I get the message about the missing MSVCR120.dll again. This just started about two days ago.

**Comment by dartraiden** [comment]
>message that OpenSSL is not available

Please, [see wiki](http://miranda-ng.org/p/MSN):

> Plugin needs OpenSSL

You should install OpenSSL plugin and OpenSSL dlls as described [here](http://miranda-ng.org/p/OpenSSL).

**Comment by sagamusix** [comment]
Nevermind, I ran Dependency Walker over all the DLLs and it turns out that the OpenSSL DLLs themselves required MSVCR120, not Miranda NG itself, so they could not be  loaded. Sorry for the confusion.

**Comment by dartraiden** [comment]
Thanks for info. We should mention this (OpenSSL require VS2013 runtime) in wiki.

**Comment by sagamusix** [comment]
For what it's worth, using the alternative downloads from https://indy.fulgan.com/SSL/ (which are mentioned on linked the OpenSSL wiki article) eliminates that dependency, since those link against the system-provided MSVCRT.
