### ISSUE TITLE
Editing StdMsg toolbar settings shows no effect

### ISSUE THREAD

**Issue by sagamusix** [miranda-ng/miranda-ng#652]
I noticed that about a week ago or so, the toolbar buttons in my IM windows got rearranged randomly. For example, there is now an OTR button at the rightmost position of the toolbar where the History++ button used to be (which is now placed more to the left). I checked if and how I can rearrange the buttons, and I found that "Message sessions" -> "Toolbar" should do this. However, the button list there still shows the list in exactly the same order as it originally looked like, and trying to modify it results in unpredictable behaviour. For example, just for testing I enabled the "Bold" button for IM sessions, but now I can no longer uncheck it. Sometimes, changing the buttons also does not make the "Apply" button clickable.

**Comment by georgehazan** [comment]
as for me everything works ok, despite the fact that the options dialog incorrectly assigns flags after drag-n-drop operations...

**Comment by sagamusix** [comment]
The order of the icons seems to be no longer swapped in today's update, but trying to hide the "Bold" icon from IM chats does not work - hitting the "Apply" button resets the checkbox.

**Comment by georgehazan** [comment]
Apply button also fixed

**Comment by sagamusix** [comment]
Seems to work as intended now.
