### ISSUE TITLE
 GmailNotifier password length limited to 63 characters

### ISSUE THREAD

**Issue by alabuzhev** [miranda-ng/miranda-ng#659]
[stdafx.h:45](
https://github.com/miranda-ng/miranda-ng/blob/master/plugins/GmailNotifier/src/stdafx.h#L45):
`char pass[64];`

Options dialog **silently** truncates anything longer than 63 characters.

Please at least increase the buffer size.

Error message if name / password doesn't fit would be helpful as well.

**Comment by dartraiden** [comment]
Fixed in https://github.com/miranda-ng/miranda-ng/commit/ea67c083c95a12df46bd7229bd8e4fd4f53b1544
