### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by MirandaJR** [miranda-ng/miranda-ng#660]
Miranda Crash Report from 29 Dec 2016 11:41:20. Crash Dumper v.0.0.5.2

Likely cause of the crash plugin: Facebook RM

Exception: Access Violation at address 6F95D0AC. Reading from address 00000300.

Stack Trace:
---------------------------------------------------------------
6F95D0AC (MSVCR100 6F8E0000): (filename not available) (0): vcwprintf_s
6F947462 (MSVCR100 6F8E0000): (filename not available) (0): vsnprintf_l
6F9474A3 (MSVCR100 6F8E0000): (filename not available) (0): vsnprintf
1219538A (mir_app 12180000): (filename not available) (0): ProtoLogA
12181012 (mir_app 12180000): (filename not available) (0): Ordinal79
03E5966F (Facebook 03E40000): (filename not available) (0): Load
03E5578B (Facebook 03E40000): (filename not available) (0): (function-name not available)
1232CD63 (mir_core 12320000): (filename not available) (0): Thread_Push

CPU: Intel(R) Core(TM) i5 CPU M 560 @ 2.67GHz [Intel64 Family 6 Model 37 Stepping 5] [DEP Enabled] [4 CPUs]
Installed RAM: 3951 MBytes
Microsoft Windows 7 Professional Edition, 64-bit Service Pack 1 (build 7601)
Internet Explorer: 9.11.9600.17843 (build 99600)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : English/English | English/Filipino

Miranda NG Version: 0.95.6 alpha build #17476 [running inside WOW64]
Build time: 28 Dec 2016 4:04:26
Profile: C:\Miranda NG\Profiles\JR\JR.dat (dbx mmap driver)
Language pack: No language pack installed
Service Mode: No

Active Plugins (29):
¤ AdvaImg.dll v.0.11.0.2 [24 Jan 2016 13:38:52] - Miranda image services 
¤ AVS.dll v.0.95.3.4 [27 Nov 2016 20:09:16] - Avatar service 
¤ BasicHistory.dll v.1.0.1.10 [7 Dec 2016 15:26:58] - Basic history 
¤ BASS_interface.dll v.0.0.0.14 [27 Nov 2016 20:11:40] - BASS interface 
¤ Clist_blind.dll v.0.8.1.1 [7 Dec 2016 15:26:48] - BClist 
¤ CrashDumper.dll v.0.0.5.2 [7 Dec 2016 15:26:02] - Crash dumper 
¤ DbEditorPP.dll v.4.0.1.1 [3 Nov 2016 4:01:52] - Database editor++ 
¤ Dbx_mmap.dll v.0.95.3.1 [28 Dec 2016 4:00:16] - Miranda NG mmap database driver 
¤ Exchange.dll v.0.1.3.4 [27 Nov 2016 20:12:12] - Exchange notifier plugin 
¤ Facebook.dll v.0.3.0.3 [19 Dec 2016 12:49:18] - Facebook RM 
¤ GTalkExt.dll v.0.1.1.0 [27 Nov 2016 20:10:20] - GTalk Extension 
¤ HistorySweeperLight.dll v.0.1.0.1 [3 Nov 2016 4:00:56] - History sweeper light 
¤ HwHotKeys.dll v.1.0.0.6 [3 Nov 2016 4:03:46] - Hardware HotKeys 
¤ Import.dll v.0.95.4.3 [19 Sep 2016 4:00:10] - Import contacts and messages 
¤ Jabber.dll v.0.11.0.4 [19 Dec 2016 12:48:22] - Jabber protocol 
¤ Msg_Export.dll v.3.1.1.6 [15 Dec 2016 4:02:08] - Message export 
¤ NewsAggregator.dll v.0.1.0.2 [7 Dec 2016 15:26:32] - News aggregator 
¤ NewXstatusNotify.dll v.1.4.0.11 [27 Nov 2016 20:10:00] - xStatus notify 
¤ PluginUpdater.dll v.0.1.2.5 [7 Dec 2016 15:26:14] - Plugin updater 
¤ QuickSearch.dll v.1.4.2.0 [27 Nov 2016 20:13:32] - Quick Search 
¤ Quotes.dll v.0.1.0.101 [27 Dec 2016 16:51:42] - Quotes 
¤ Rate.dll v.0.0.2.1 [12 Sep 2016 4:01:02] - Contact`s rate 
¤ RecentContacts.dll v.0.0.2.1 [3 Nov 2016 4:01:34] - Recent contacts 
¤ Scriver.dll v.2.12.2.1 [28 Dec 2016 4:00:20] - Scriver 
¤ SkypeWeb.dll v.0.12.2.3 [15 Dec 2016 4:03:50] - Skype protocol (Web) 
¤ SmileyAdd.dll v.0.2.4.1 [11 Dec 2016 10:10:52] - SmileyAdd 
¤ SpellChecker.dll v.0.2.6.4 [15 Dec 2016 4:01:54] - Spell checker 
¤ StopSpamMod.dll v.0.0.2.0 [27 Dec 2016 16:51:20] - StopSpam mod 
¤ XSoundNotify.dll v.1.0.1.2 [15 Dec 2016 4:03:00] - XSoundNotify 

Loaded Modules:
-------------------------------------------------------------------------------
C:\Miranda NG\Miranda32.exe  00400000 - 00409000 v.0.95.6.17476 [28 Dec 2016 4:04:26]
C:\Windows\SysWOW64\ntdll.dll  77790000 - 77910000 v.6.1.7601.18247 [11 Oct 2016 11:44:05]
C:\Windows\syswow64\kernel32.dll  76DC0000 - 76ED0000 v.6.1.7601.18015 [11 Oct 2016 11:44:05]
C:\Windows\syswow64\KERNELBASE.dll  76D70000 - 76DB7000 v.6.1.7601.18015 [11 Oct 2016 11:44:05]
C:\Windows\syswow64\USER32.dll  75960000 - 75A60000 v.6.1.7601.17514 [20 Nov 2010 4:08:58]
C:\Windows\syswow64\GDI32.dll  77220000 - 772B0000 v.6.1.7601.17514 [20 Nov 2010 4:08:52]
C:\Windows\syswow64\LPK.dll  75500000 - 7550A000 v.6.1.7600.16385 [14 Jul 2009 9:11:23]
C:\Windows\syswow64\USP10.dll  772F0000 - 7738D000 v.1.626.7601.17514 [20 Nov 2010 4:21:34]
C:\Windows\syswow64\msvcrt.dll  77080000 - 7712C000 v.7.0.7600.16385 [14 Jul 2009 9:15:50]
C:\Windows\syswow64\ADVAPI32.dll  75A60000 - 75B00000 v.6.1.7601.18247 [11 Oct 2016 11:44:05]
C:\Windows\SysWOW64\sechost.dll  75330000 - 75349000 v.6.1.7600.16385 [14 Jul 2009 9:16:13]
C:\Windows\syswow64\RPCRT4.dll  77130000 - 77220000 v.6.1.7601.17514 [20 Nov 2010 4:08:58]
C:\Windows\syswow64\SspiCli.dll  75120000 - 75180000 v.6.1.7601.17514 [20 Nov 2010 4:08:58]
C:\Windows\syswow64\CRYPTBASE.dll  75110000 - 7511C000 v.6.1.7600.16385 [14 Jul 2009 9:15:07]
C:\Miranda NG\MSVCR100.dll  6F8E0000 - 6F99F000 v.10.0.40219.325 [11 Jun 2011 2:58:52]
C:\Windows\system32\IMM32.DLL  756E0000 - 75740000 v.6.1.7601.17514 [20 Nov 2010 4:08:52]
C:\Windows\syswow64\MSCTF.dll  75D80000 - 75E4C000 v.6.1.7600.16385 [14 Jul 2009 9:15:43]
C:\Miranda NG\libs\mir_app.mir  12180000 - 12244000 v.0.95.6.17476 [28 Dec 2016 4:00:36]
C:\Windows\system32\WINMM.dll  75000000 - 75032000 v.6.1.7601.17514 [20 Nov 2010 4:21:38]
C:\Windows\syswow64\SHLWAPI.dll  75CE0000 - 75D37000 v.6.1.7601.17514 [20 Nov 2010 4:21:20]
C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.17514_none_41e6975e2bd6f2b2\COMCTL32.dll  72A80000 - 72C1E000 v.6.10.7601.17514 [20 Nov 2010 3:55:10]
C:\Windows\syswow64\WS2_32.dll  772B0000 - 772E5000 v.6.1.7601.17514 [20 Nov 2010 4:21:40]
C:\Windows\syswow64\NSI.dll  75CD0000 - 75CD6000 v.6.1.7600.16385 [14 Jul 2009 9:16:11]
C:\Windows\system32\UxTheme.dll  723A0000 - 72420000 v.6.1.7600.16385 [14 Jul 2009 9:11:24]
C:\Windows\syswow64\COMDLG32.dll  752A0000 - 7531B000 v.6.1.7601.17514 [20 Nov 2010 4:18:24]
C:\Windows\syswow64\SHELL32.dll  76120000 - 76D6A000 v.6.1.7601.17514 [20 Nov 2010 4:21:20]
C:\Windows\syswow64\ole32.dll  753A0000 - 754FC000 v.6.1.7601.17514 [20 Nov 2010 4:20:50]
C:\Miranda NG\libs\zlib.mir  123A0000 - 123B7000 v.1.2.8.0 [28 Dec 2016 4:00:14]
C:\Miranda NG\libs\mir_core.mir  12320000 - 12340000 [28 Dec 2016 4:00:18]
C:\Windows\system32\VERSION.dll  74FF0000 - 74FF9000 v.6.1.7600.16385 [14 Jul 2009 9:16:17]
C:\Windows\system32\Secur32.dll  74FA0000 - 74FA8000 v.6.1.7601.17514 [20 Nov 2010 4:21:08]
C:\Program Files\Freedom Scientific\JAWS\13.0\x86\jhook.dll  6FD80000 - 6FE11000 v.13.0.1006.400 [1 Aug 2012 15:09:20]
C:\Windows\syswow64\OLEAUT32.dll  75C40000 - 75CCF000 v.6.1.7601.17514 [20 Nov 2010 4:20:50]
C:\Windows\system32\MSVCP100.dll  70E00000 - 70E69000 v.10.0.40219.325 [11 Jun 2011 1:58:52]
C:\Windows\system32\OLEACC.dll  71210000 - 7124C000 v.7.0.0.0 [14 Jul 2009 9:16:12]
C:\Program Files (x86)\Ruiware\WinPatrol\PATROLPRO.DLL  72140000 - 7214E000 v.1.5.0.0 [21 Jul 2014 9:39:33]
C:\Windows\system32\dwmapi.dll  70FF0000 - 71003000 v.6.1.7600.16385 [14 Jul 2009 9:15:13]
C:\Windows\syswow64\CLBCatQ.DLL  76090000 - 76113000 v.2001.12.8530.16385 [14 Jul 2009 9:15:03]
C:\Windows\system32\explorerframe.dll  6FB80000 - 6FCEF000 v.6.1.7601.17514 [20 Nov 2010 4:19:02]
C:\Windows\system32\DUser.dll  73D70000 - 73D9F000 v.6.1.7600.16385 [14 Jul 2009 9:15:13]
C:\Windows\system32\DUI70.dll  6D2C0000 - 6D372000 v.6.1.7600.16385 [14 Jul 2009 9:15:13]
C:\Windows\system32\msiltcfg.dll  74F90000 - 74F97000 v.5.0.7600.16385 [14 Jul 2009 9:15:44]
C:\Windows\system32\msi.dll  72160000 - 723A0000 v.5.0.7601.17514 [20 Nov 2010 4:19:50]
C:\Windows\SysWOW64\SFC.DLL  74EC0000 - 74EC3000 v.6.1.7600.16385 [14 Jul 2009 9:10:22]
C:\Windows\system32\sfc_os.DLL  74EB0000 - 74EBD000 v.6.1.7600.16385 [14 Jul 2009 9:16:14]
D:\Installer\Other Stuff\tinySpell\tskh1960.DLL  74E50000 - 74E5E000 v.1.9.6.0 [8 Sep 2015 17:31:36]
C:\Program Files (x86)\Freedom Scientific\Shared\UiaHooks\1.0\uiahooks.dll  746C0000 - 746D7000 v.14.0.5420.0 [10 Apr 2014 21:07:18]
C:\Windows\system32\UIAutomationCore.DLL  6FCF0000 - 6FD7C000 v.7.0.0.0 [14 Jul 2009 9:16:17]
C:\Windows\syswow64\PSAPI.DLL  75320000 - 75325000 v.6.1.7600.16385 [14 Jul 2009 9:16:12]
C:\Miranda NG\Plugins\CrashDumper.dll  14980000 - 14990000 v.0.0.5.2 [7 Dec 2016 15:26:02]
C:\Windows\system32\dbghelp.dll  6D520000 - 6D60B000 v.6.1.7601.17514 [20 Nov 2010 4:18:28]
C:\Miranda NG\Plugins\DbEditorPP.dll  14B00000 - 14B1D000 v.4.0.1.1 [3 Nov 2016 4:01:52]
C:\Miranda NG\Plugins\Dbx_mmap.dll  14B20000 - 14B31000 v.0.95.3.1 [28 Dec 2016 4:00:16]
C:\Miranda NG\Plugins\Import.dll  15760000 - 1576D000 v.0.95.4.3 [19 Sep 2016 4:00:10]
C:\Miranda NG\Core\stdcrypt.dll  13080000 - 1308C000 v.0.95.6.17476 [28 Dec 2016 4:04:24]
C:\Miranda NG\Core\stdssl.dll  13180000 - 13187000 v.0.95.6.17476 [28 Dec 2016 4:04:18]
C:\Windows\syswow64\CRYPT32.dll  75B10000 - 75C2D000 v.6.1.7601.17514 [20 Nov 2010 4:18:26]
C:\Windows\syswow64\MSASN1.dll  77760000 - 7776C000 v.6.1.7601.17514 [20 Nov 2010 4:19:46]
C:\Windows\system32\WSOCK32.dll  75040000 - 75047000 v.6.1.7600.16385 [14 Jul 2009 9:16:20]
C:\Windows\system32\Msftedit.dll  6D480000 - 6D514000 v.5.41.21.2510 [20 Nov 2010 4:19:48]
C:\Miranda NG\Plugins\AdvaImg.dll  14220000 - 142AF000 v.0.11.0.2 [24 Jan 2016 13:38:52]
C:\Miranda NG\Plugins\Clist_blind.dll  146C0000 - 146CE000 v.0.8.1.1 [7 Dec 2016 15:26:48]
C:\Miranda NG\Plugins\AVS.dll  14500000 - 14512000 v.0.95.3.4 [27 Nov 2016 20:09:16]
C:\Miranda NG\Plugins\BasicHistory.dll  14540000 - 1457C000 v.1.0.1.10 [7 Dec 2016 15:26:58]
C:\Windows\syswow64\SETUPAPI.dll  75540000 - 756DD000 v.6.1.7601.17514 [20 Nov 2010 4:21:16]
C:\Windows\syswow64\CFGMGR32.dll  75510000 - 75537000 v.6.1.7601.17514 [20 Nov 2010 4:18:14]
C:\Windows\syswow64\DEVOBJ.dll  75350000 - 75362000 v.6.1.7600.16385 [14 Jul 2009 9:15:11]
C:\Windows\system32\propsys.dll  714E0000 - 715D5000 v.7.0.7601.17514 [20 Nov 2010 4:20:58]
C:\Windows\system32\ntmarta.dll  72430000 - 72451000 v.6.1.7600.16385 [14 Jul 2009 9:16:11]
C:\Windows\syswow64\WLDAP32.dll  75240000 - 75285000 v.6.1.7601.17514 [20 Nov 2010 4:21:38]
C:\Windows\system32\apphelp.dll  72F00000 - 72F4C000 v.6.1.7601.17514 [20 Nov 2010 4:18:04]
C:\Users\jr\AppData\Roaming\Dropbox\bin\DropboxExt.3.0.dll  70FB0000 - 70FE8000 v.1.0.3.0 [22 Dec 2016 2:21:10]
C:\Windows\system32\ntshrui.dll  6FB10000 - 6FB80000 v.6.1.7601.17514 [20 Nov 2010 4:20:48]
C:\Windows\system32\srvcli.dll  6FAF0000 - 6FB09000 v.6.1.7601.17514 [20 Nov 2010 4:21:28]
C:\Windows\system32\cscapi.dll  6FAE0000 - 6FAEB000 v.6.1.7601.17514 [20 Nov 2010 4:18:26]
C:\Windows\system32\slc.dll  6FAD0000 - 6FADA000 v.6.1.7600.16385 [14 Jul 2009 9:16:15]
C:\Windows\system32\netutils.dll  74E60000 - 74E69000 v.6.1.7601.17514 [20 Nov 2010 4:20:30]
C:\Windows\syswow64\profapi.dll  75290000 - 7529B000 v.6.1.7600.16385 [14 Jul 2009 9:16:12]
C:\Miranda NG\Plugins\BASS_interface.dll  145C0000 - 145C9000 v.0.0.0.14 [27 Nov 2016 20:11:40]
C:\Miranda NG\Plugins\Exchange.dll  14C40000 - 14C50000 v.0.1.3.4 [27 Nov 2016 20:12:12]
C:\Windows\system32\MAPI32.dll  73DB0000 - 73DC6000 v.1.0.2536.0 [20 Nov 2010 4:19:34]
C:\Miranda NG\Plugins\Facebook.dll  03E40000 - 03E8F000 v.0.3.0.3 [19 Dec 2016 12:49:18]
C:\Miranda NG\libs\libjson.mir  12160000 - 1216C000 [28 Dec 2016 4:00:14]
C:\Windows\system32\CRYPTSP.dll  72DF0000 - 72E06000 v.6.1.7600.16385 [14 Jul 2009 9:15:07]
C:\Miranda NG\Plugins\GTalkExt.dll  15060000 - 15070000 v.0.1.1.0 [27 Nov 2016 20:10:20]
C:\Miranda NG\Plugins\HistorySweeperLight.dll  15540000 - 15548000 v.0.1.0.1 [3 Nov 2016 4:00:56]
C:\Windows\system32\rsaenh.dll  72DB0000 - 72DEB000 v.6.1.7600.16385 [14 Jul 2009 9:17:54]
C:\Miranda NG\Plugins\HwHotKeys.dll  15580000 - 15587000 v.1.0.0.6 [3 Nov 2016 4:03:46]
C:\Windows\system32\RpcRtRemote.dll  73150000 - 7315E000 v.6.1.7601.17514 [20 Nov 2010 4:21:04]
C:\Miranda NG\Plugins\Jabber.dll  15860000 - 158EF000 v.0.11.0.4 [19 Dec 2016 12:48:22]
C:\Windows\system32\DNSAPI.dll  738A0000 - 738E4000 v.6.1.7601.17514 [20 Nov 2010 4:18:34]
C:\Miranda NG\Plugins\Msg_Export.dll  15E40000 - 15E57000 v.3.1.1.6 [15 Dec 2016 4:02:08]
C:\Miranda NG\Plugins\NewsAggregator.dll  15FE0000 - 15FF4000 v.0.1.0.2 [7 Dec 2016 15:26:32]
C:\Miranda NG\Plugins\NewXstatusNotify.dll  16020000 - 16040000 v.1.4.0.11 [27 Nov 2016 20:10:00]
C:\Miranda NG\Plugins\PluginUpdater.dll  16320000 - 16334000 v.0.1.2.5 [7 Dec 2016 15:26:14]
C:\Miranda NG\Plugins\QuickSearch.dll  16460000 - 16492000 [27 Nov 2016 20:13:32]
C:\Miranda NG\Plugins\Quotes.dll  164E0000 - 16527000 v.0.1.0.101 [27 Dec 2016 16:51:42]
C:\Windows\SysWOW64\mshtml.dll  66BA0000 - 67E5C000 v.11.0.9600.17842 [11 Oct 2016 11:53:06]
C:\Windows\syswow64\api-ms-win-downlevel-advapi32-l1-1-0.dll  75390000 - 75395000 v.6.2.9200.16492 [23 Mar 2014 18:28:01]
C:\Windows\syswow64\api-ms-win-downlevel-version-l1-1-0.dll  75750000 - 75754000 v.6.2.9200.16492 [23 Mar 2014 18:28:01]
C:\Windows\syswow64\api-ms-win-downlevel-shlwapi-l1-1-0.dll  75D40000 - 75D44000 v.6.2.9200.16492 [23 Mar 2014 18:28:01]
C:\Windows\syswow64\api-ms-win-downlevel-user32-l1-1-0.dll  75760000 - 75764000 v.6.2.9200.16492 [23 Mar 2014 18:28:01]
C:\Windows\syswow64\iertutil.dll  75E50000 - 76082000 v.11.0.9600.17840 [11 Oct 2016 11:53:10]
C:\Windows\syswow64\api-ms-win-downlevel-normaliz-l1-1-0.dll  75B00000 - 75B03000 v.6.2.9200.16492 [23 Mar 2014 18:28:01]
C:\Windows\syswow64\normaliz.DLL  75740000 - 75743000 v.6.1.7600.16385 [14 Jul 2009 9:09:00]
C:\Windows\syswow64\api-ms-win-downlevel-ole32-l1-1-0.dll  75C30000 - 75C34000 v.6.2.9200.16492 [23 Mar 2014 18:28:01]
C:\Windows\syswow64\urlmon.dll  76ED0000 - 7701A000 v.11.0.9600.17840 [11 Oct 2016 11:53:10]
C:\Windows\syswow64\WININET.dll  75770000 - 75954000 v.11.0.9600.17840 [11 Oct 2016 11:53:11]
C:\Windows\syswow64\USERENV.dll  75370000 - 75387000 v.6.1.7601.17514 [20 Nov 2010 4:21:34]
C:\Miranda NG\Plugins\Rate.dll  165E0000 - 165E7000 v.0.0.2.1 [12 Sep 2016 4:01:02]
C:\Miranda NG\Plugins\RecentContacts.dll  165A0000 - 165A9000 v.0.0.2.1 [3 Nov 2016 4:01:34]
C:\Miranda NG\Plugins\Scriver.dll  16700000 - 16738000 v.2.12.2.1 [28 Dec 2016 4:00:20]
C:\Miranda NG\Plugins\SkypeWeb.dll  16900000 - 16945000 v.0.12.2.3 [15 Dec 2016 4:03:50]
C:\Miranda NG\Plugins\SmileyAdd.dll  169A0000 - 169BE000 v.0.2.4.1 [11 Dec 2016 10:10:52]
C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.0.7601.17514_none_83801b5eed6392d9\gdiplus.dll  68790000 - 68938000 v.5.2.7601.17514 [20 Nov 2010 3:55:06]
C:\Miranda NG\Plugins\SpellChecker.dll  16AA0000 - 16AB6000 v.0.2.6.4 [15 Dec 2016 4:01:54]
C:\Miranda NG\libs\hunspell.mir  12000000 - 12050000 v.1.3.4.0 [15 Dec 2016 4:01:36]
C:\Miranda NG\Plugins\StopSpamMod.dll  16C00000 - 16C41000 v.0.0.2.0 [27 Dec 2016 16:51:20]
C:\Miranda NG\Plugins\XSoundNotify.dll  17620000 - 17628000 v.1.0.1.2 [15 Dec 2016 4:03:00]
C:\Miranda NG\Core\stduserinfo.dll  131C0000 - 131CC000 v.0.95.6.17476 [28 Dec 2016 4:04:26]
C:\Miranda NG\Core\stdemail.dll  130A0000 - 130A6000 v.0.95.6.17476 [28 Dec 2016 4:04:22]
C:\Miranda NG\Core\stdauth.dll  13000000 - 13007000 v.0.95.6.17476 [28 Dec 2016 4:04:24]
C:\Miranda NG\Core\stdfile.dll  130C0000 - 130CF000 v.0.95.6.17476 [28 Dec 2016 4:04:22]
C:\Miranda NG\Core\stdhelp.dll  130E0000 - 130E6000 v.0.95.6.17476 [28 Dec 2016 4:04:24]
C:\Miranda NG\Core\stdidle.dll  13100000 - 13107000 v.0.95.6.17476 [28 Dec 2016 4:04:22]
C:\Windows\system32\WTSAPI32.dll  74FE0000 - 74FED000 v.6.1.7601.17514 [20 Nov 2010 4:21:40]
C:\Miranda NG\Core\stdautoaway.dll  13020000 - 13026000 v.0.95.6.17476 [28 Dec 2016 4:04:24]
C:\Miranda NG\Core\stdaway.dll  13040000 - 13049000 v.0.95.6.17476 [28 Dec 2016 4:04:22]
C:\Miranda NG\Plugins\Bass\bass.dll  73CA0000 - 73CF0000 v.2.4.11.0 [23 Jan 2016 12:17:34]
C:\Windows\system32\MSACM32.dll  6FA60000 - 6FA74000 v.6.1.7600.16385 [14 Jul 2009 9:15:42]
C:\Windows\system32\dsound.DLL  6D400000 - 6D472000 v.6.1.7600.16385 [14 Jul 2009 9:15:13]
C:\Windows\system32\POWRPROF.dll  71310000 - 71335000 v.6.1.7600.16385 [14 Jul 2009 9:16:12]
C:\Windows\System32\MMDevApi.dll  71880000 - 718B9000 v.6.1.7601.17514 [20 Nov 2010 4:19:40]
C:\Windows\system32\AUDIOSES.DLL  71790000 - 717C6000 v.6.1.7601.17514 [20 Nov 2010 4:18:06]
C:\Windows\system32\mswsock.dll  738F0000 - 7392C000 v.6.1.7601.18254 [11 Oct 2016 11:43:11]
C:\Windows\System32\wshtcpip.dll  73850000 - 73855000 v.6.1.7600.16385 [14 Jul 2009 9:16:20]
C:\Windows\System32\wship6.dll  72420000 - 72426000 v.6.1.7600.16385 [14 Jul 2009 9:16:20]
C:\Windows\system32\PrxerNsp.dll  10000000 - 10010000 v.2.60.0.1 [28 Feb 2007 16:56:34]
C:\Windows\system32\IPHLPAPI.DLL  73880000 - 7389C000 v.6.1.7601.17514 [20 Nov 2010 4:19:24]
C:\Windows\system32\WINNSI.DLL  73870000 - 73877000 v.6.1.7600.16385 [14 Jul 2009 9:16:19]
C:\Windows\system32\rasadhlp.dll  71BC0000 - 71BC6000 v.6.1.7600.16385 [14 Jul 2009 9:16:12]
C:\Windows\System32\fwpuclnt.dll  71C70000 - 71CA8000 v.6.1.7601.17514 [20 Nov 2010 4:19:04]
C:\Windows\system32\PrxerDrv.dll  064A0000 - 064B3000 v.2.70.0.1 [25 Sep 2007 15:40:32]
C:\Windows\system32\NLAapi.dll  74FD0000 - 74FE0000 v.6.1.7601.17514 [20 Nov 2010 4:20:32]
C:\Windows\system32\napinsp.dll  74FC0000 - 74FD0000 v.6.1.7600.16385 [14 Jul 2009 9:16:02]
C:\Windows\system32\pnrpnsp.dll  73950000 - 73962000 v.6.1.7600.16385 [14 Jul 2009 9:16:12]
C:\Windows\system32\wshbth.dll  73940000 - 7394D000 v.6.1.7601.17514 [20 Nov 2010 4:21:40]
C:\Windows\System32\winrnr.dll  73930000 - 73938000 v.6.1.7600.16385 [14 Jul 2009 9:16:19]
C:\Windows\system32\schannel.dll  70DC0000 - 70DFA000 v.6.1.7601.17514 [20 Nov 2010 4:21:06]
C:\Windows\system32\credssp.dll  74090000 - 74098000 v.6.1.7601.17514 [20 Nov 2010 4:18:26]
C:\Windows\system32\api-ms-win-downlevel-shlwapi-l2-1-0.dll  74C40000 - 74C44000 v.6.2.9200.16492 [23 Mar 2014 18:28:01]
C:\Windows\system32\ncrypt.dll  718C0000 - 718F8000 v.6.1.7600.16385 [14 Jul 2009 9:16:02]
C:\Windows\system32\bcrypt.dll  71AA0000 - 71AB7000 v.6.1.7600.16385 [14 Jul 2009 9:11:20]
C:\Windows\SysWOW64\bcryptprimitives.dll  71710000 - 7174D000 v.6.1.7600.16385 [14 Jul 2009 9:17:54]
C:\Windows\system32\GPAPI.dll  71770000 - 71786000 v.6.1.7600.16385 [14 Jul 2009 9:15:22]

**Comment by Robyer** [comment]
Make sure you have debug symbols to make useful crash report. See http://wiki.miranda-ng.org/index.php?title=Crash_reports
