### ISSUE TITLE
White background on some options

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#671]
For example:

Options -> Status -> Status manager (first and third options):

![2](https://cloud.githubusercontent.com/assets/5046855/21753412/92ef457c-d5fd-11e6-9132-f5d5ff619c35.png)

Options -> Customize -> Languages:

![3](https://cloud.githubusercontent.com/assets/5046855/21753413/9773c1ae-d5fd-11e6-813b-29705fe56f7b.png)

Another one in Contacts -> Metacontacts

Tested on different machines with Windows 10 x64 and Windows XP x32

**Comment by Robyer** [comment]
Happens for me too.

**Comment by Robyer** [comment]
Works correctly in stable: Miranda NG Version: 0.95.5 build #17337  Build time: 27 Sep 2016 14:44:41

**Comment by watcherhd** [comment]
I see this too.

**Comment by georgehazan** [comment]
dunno how it could affect drawing background, but the whole effect disappeared when I changed resource ids from 1002 to 1090, for example. looks crazy, but it's a matter of fact.

**Comment by Robyer** [comment]
@watcherhd As this is easily reproducible, could you compile various revisions and try when exactly it started happening?

**Comment by dartraiden** [comment]
Bug introduced between 15aec1eb990af0c0f15f42d380d718e458df81d6 (no bug) and (b8e1921d35f930eedb01abfe2af606dbed50a888 (bug exists)

**Comment by dartraiden** [comment]
What is the correct way to revert sources back to specific revision?

**Comment by Robyer** [comment]
@dartraiden I recommend using SmartGit (it's free for open source projects) for working with Git. It is much more user friendly than TortoiseGit or anything else I've ever used.

About source of problem - I think ghazan said that it started happening when he rewritten forms to UI Utils.

Builds on server are built using VS2010 so it's strange it disappeared for you. I think it must be something else - or maybe some wrong configuration of building on server?

**Comment by dartraiden** [comment]
Cannot reproduce this bug anymore.

**Comment by georgehazan** [comment]
on Windows 10 it's here

**Comment by apollo2k4** [comment]
No Windows 7 too

**Comment by georgehazan** [comment]
damned VS :)
