### ISSUE TITLE
Статусы в виде сообщений

### ISSUE THREAD

**Issue by devcline** [miranda-ng/miranda-ng#674]
Status change @ 02:34:21: User was deactivated (deleted)
Status change @ 19:23:00: User restored control over own page

не пользуюсь плагином popup и изза этого всегда вижу статусы кто удаляет страницу в vk а кто нет
как сделать так что бы каждый раз это не приходило в качестве "сообщения"

**Comment by dartraiden** [comment]
Если эти события (удаление/восстановление/блокировка) совсем не нужны, можно воспользоваться [редактором базы](http://wiki.miranda-ng.org/index.php?title=Plugin:DbEditorPP/ru) и изменить значение настройки [ShowVkDeactivateEvents](http://wiki.miranda-ng.org/index.php?title=Plugin:VKontakte/ru)

**Comment by devcline** [comment]
А если они нужны в логах? По другому никак кроме как их пачками получаться сообщениями или попапами? спасибо

**Comment by ElzorFox** [comment]
ShowVkDeactivateEvents = 0 как раз и оставляет в логах события, но не показывает их попапами/мессаджбоксами (вернее сказать, оно кладет эти события в базу уже прочитанными)
