### ISSUE TITLE
Chat window resize incorrect

### ISSUE THREAD

**Issue by pdecrocq** [miranda-ng/miranda-ng#680]
Hello,
Since a few versions I have noticed that when I resize a chat window, the contents doesn't adapt to the new window size (see screenshot). Is this known ? How to fix ? Thanks ! -Pierre
![image 1711](https://cloud.githubusercontent.com/assets/6884208/22141511/abc62e14-def2-11e6-8747-927a7a576497.png)

PS: 
VersionInfo
Quote (selected)

CPU: Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz [Intel64 Family 6 Model 58 Stepping 9] [DEP Enabled] [4 CPUs]
Installed RAM: 8066 MBytes
Microsoft Windows 7 Enterprise Edition, 64-bit Service Pack 1 (build 7601)
Internet Explorer: 9.11.9600.18537 (build 99600)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : French/French | English/French
Free disk space on Miranda partition: 74012 MBytes

Miranda NG Version: 0.95.6 alpha build #17571 x64
Build time: 19 Jan 2017 4:10:22
Profile: D:\Utilisateurs\fr18454\AppData\Roaming\Miranda NG\PDecrocq\PDecrocq.dat (dbx mmap driver)
Profile size: 1638400 Bytes
Profile creation date: 13 Sep 2013 15:57:23
Language pack: No language pack installed
Service Mode: No

Active Plugins (17):
¤ AdvaImg.dll v.0.11.0.2 [3 Jan 2017 4:06:40] - Miranda image services 
¤ AIM.dll v.0.11.0.1 [18 Jan 2017 4:05:46] - AIM protocol 
¤ AVS.dll v.0.95.3.4 [18 Jan 2017 4:05:36] - Avatar service 
¤ CrashDumper.dll v.0.0.5.2 [13 Jan 2017 4:07:18] - Crash dumper 
¤ DbEditorPP.dll v.4.0.1.1 [3 Jan 2017 4:07:16] - Database editor++ 
¤ Dbx_mmap.dll v.0.95.3.1 [19 Jan 2017 4:05:52] - Miranda NG mmap database driver 
¤ Facebook.dll v.0.3.0.3 [18 Jan 2017 4:06:56] - Facebook RM 
¤ GG.dll v.0.11.0.3 [18 Jan 2017 4:06:02] - Gadu-Gadu protocol 
¤ ICQ.dll v.0.11.3.4 [18 Jan 2017 4:05:54] - IcqOscarJ protocol 
¤ Import.dll v.0.95.4.3 [18 Jan 2017 4:05:36] - Import contacts and messages 
¤ IRC.dll v.0.11.0.3 [18 Jan 2017 4:05:52] - IRC protocol 
¤ Jabber.dll v.0.11.0.4 [18 Jan 2017 4:06:06] - Jabber protocol 
¤ MSN.dll v.0.12.1.2 [18 Jan 2017 4:06:04] - MSN protocol 
¤ PluginUpdater.dll v.0.1.2.5 [13 Jan 2017 4:07:40] - Plugin updater 
¤ SkypeWeb.dll v.0.12.2.3 [18 Jan 2017 4:09:32] - Skype protocol (Web) 
¤ TopToolBar.dll v.0.8.0.4 [5 Dec 2016 4:06:56] - TopToolBar 
¤ Twitter.dll v.1.3.0.2 [18 Jan 2017 4:07:06] - Twitter protocol 

Unloadable Plugins (1):
¤ DbChecker.dll v.0.0.0.0 [19 Jan 2017 4:07:50] - <unknown> 

Protocols and Accounts:
-------------------------------------------------------------------------------
AIM                      0 - Enabled 0 - Disabled  Loaded
Facebook                 1 - Enabled 0 - Disabled  Loaded
GG                       0 - Enabled 0 - Disabled  Loaded
ICQ                      0 - Enabled 0 - Disabled  Loaded
IRC                      0 - Enabled 0 - Disabled  Loaded
JABBER                   1 - Enabled 0 - Disabled  Loaded
MSN                      0 - Enabled 0 - Disabled  Loaded
SKYPE                    1 - Enabled 1 - Disabled  Loaded
Twitter                  1 - Enabled 0 - Disabled  Loaded
MetaContacts             1 - Enabled 0 - Disabled  Loaded

Icon Packs:
-------------------------------------------------------------------------------
 Proto_AIM.dll [18 Jan 2017 4:07:02]
 Proto_Facebook.dll [18 Jan 2017 4:07:02]
 Proto_GG.dll [18 Jan 2017 4:07:04]
 Proto_ICQ.dll [18 Jan 2017 4:07:04]
 Proto_IRC.dll [18 Jan 2017 4:07:04]
 Proto_Jabber.dll [18 Jan 2017 4:07:04]
 Proto_MetaContacts.dll [19 Jan 2017 4:09:34]
 Proto_MSN.dll [18 Jan 2017 4:07:04]
 Proto_Skype.dll [18 Jan 2017 4:09:22]
 Proto_Twitter.dll [18 Jan 2017 4:07:02]
 Proto_Yahoo.dll [26 Sep 2016 3:07:00]
 TabSRMM_icons.dll [18 Jan 2017 4:07:46]
 Toolbar_icons.dll [18 Jan 2017 4:07:04]
 xStatus_ICQ.dll [18 Jan 2017 4:05:58]
 xStatus_Jabber.dll [18 Jan 2017 4:06:00]

**Comment by georgehazan** [comment]
try to resize a window, it must solve the problem.
somehow the old values stored in your profile don't match the new screen class

**Comment by pdecrocq** [comment]
It is precisely after a resizing that the above behavior occur.
How to remove stored values ?

**Comment by pdecrocq** [comment]
Hi ! sorry to insist. how to remove the stored values ?

**Comment by Robyer** [comment]
@pdecrocq Does it happen also in clean Miranda? Try to download latest development version, create new empty profile (don't import any settings from previous) and test it there.

**Comment by pdecrocq** [comment]
@Robyer I'm afraid I don't have much time to do this all. I'm already using the development version.
I suspect an issue around window size stored values : any way to reset them ?

**Comment by Robyer** [comment]
I read what ghazan said, but I'd like to verify that by using clean profile - you don't have to set whole Miranda from scratch. You just need to test it on clean profile and then you can go back to your current profile.

**Comment by pdecrocq** [comment]
@Robyer Thanks. How to create a new empty profile, use it, then go back to previous one ?

**Comment by Robyer** [comment]
@pdecrocq Just download latest Miranda NG archive, extract it to some new folder, start it and create new profile, test it there, and when you're done, just delete the whole folder (Miranda is portable by default, you don't need to install/uninstall it) and continue using your current Miranda.

**Comment by Robyer** [comment]
@pdecrocq Is problem still happening?

**Comment by pdecrocq** [comment]
Thanks for follow-up. It seems to be solved recently. Has any change/fix  towards this issue been done ?

**Comment by Robyer** [comment]
I don't know about any related change to that.
So if it's solved, we can close this issue then.

**Comment by leecher1337** [comment]
I'm also facing this issue.
Window resizing is broken. 

1) If I try to expand the window, controls don't adjust:
![01-expand](https://cloud.githubusercontent.com/assets/6495842/23472335/c7aa8ef2-feac-11e6-9596-1f7934341d5d.jpg)
2) If I shrink window afterwards, controls become too large:
![02-shrink](https://cloud.githubusercontent.com/assets/6495842/23472362/d9185b10-feac-11e6-84e7-84abf5440f5f.jpg)
3) If I press escape, only the subwindow closes, not the whole chat window
![03-escape](https://cloud.githubusercontent.com/assets/6495842/23472378/e326f134-feac-11e6-9134-99c92874ca51.jpg)

**Comment by georgehazan** [comment]
to reproduce it one needs to disable the "Display window contents while dragging" option in Windows

**Comment by georgehazan** [comment]
fixed, will be available in the next nightly build
