### ISSUE TITLE
(tabsrmm+ieview) Embedded GIFs behave strangely if posted into multiple chats

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#681]
If you paste an embedded gif (be it animated smiley or just a gif embedded in `[img]` tags,)into an ieview+tabsrmm'd conversation tab, it will only play correctly in the first "tab" where you paste it. In the other tabs, the animation will no longer play - but you can catch different "still-frames" of it if you do any action which causes the ieview window to update (i.e. typing a message or scrolling the chat log).

Similarly, if you close the initial tab where you pasted it and then you paste it there again, it will also not play anymore, and will not play again until you restart miranda. (even if you close all tabs and the container, the behavior will not be fixed).

This only applies if you're pasting the SAME gif (or animated emoticon) into multiple windows. The gif will simply play only in the first window (even if you paste it many times there), but in no other tabs, nor in this one if you close it and then paste the gif again.

If you paste a different gif, it will play just fine. (but again not anymore if you paste it elsewhere..)

**Comment by Robyer** [comment]
Could you try some older versions of Miranda to confirm whether it worked before of not?

**Comment by LittleVulpix** [comment]
Hmm I remember this being a problem for very, very long... but I've been discouraged to post it because there was no github back then. I wonder how old the miranda I need to test should be... and where to get it?

**Comment by Robyer** [comment]
You can try old versions of Miranda NG from here - http://miranda-ng.org/distr/deprecated/
I just wanted to know if it was working someday in NG and then broken or if it never really worked.

**Comment by ikeblaster** [comment]
Win10 (or maybe just IE11)? I had similar problem with animated skype smileys - they "froze" after switching to another tab (chat) or just opening a closed one. I am not sure if it's even related to Miranda, I am afraid it's just some broken power-saving feature from IE engine. Back then I solved it using javascript by appending a random suffix to every image found in chat log. Then it worked as expected.

In .ivt file - message templates looks like this:
```
<p id="newMsg">%text%</p>
<script>msgEvent();</script>
```
and in `<head>` section:
```
<script>
function msgEvent() {
	var $el = document.getElementById("newMsg");
	$el.id = "";

	var imgs = $el.getElementsByTagName("img");
	for(var i=0; i<imgs.length; i++) {
		imgs[i].src = imgs[i].src + "?" + (new Date()).toString();
	}
}
</script>
```

**Comment by LittleVulpix** [comment]
@Robyer I went really far with those versions and the issue happened on all of them. I will try it on an older system with older IE core, see if that makes it work normally.

**Comment by LittleVulpix** [comment]
Seems to be W10 specific because I tried this on W7 with IE 10 and IE 11 (fully updated!) and the issue does not occur there - with the exact same setup as I use on w10.

**Comment by LittleVulpix** [comment]
It is now working correctly - gifs play in all tabs. Not sure since when, but it is working.

W10 x64 Pro, 1703, build 15063.1058. Miranda e0799755b3
