### ISSUE TITLE
MsgExport doesn't know certain events

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#682]
Using the text export of MsgExport sometimes produces the line:

"Unknown event type X, size Y" (where X and Y are integers)

Grepping my entire history for these events produces the table below.

First number on the left is the amount of times such event had occurred.

```
  count line
      2 Unknown event type 10002
      2 Unknown event type 20001
     10 Unknown event type 10004
     13 Unknown event type 10008
     30 Unknown event type 2001
     32 Unknown event type 10003
     94 Unknown event type 10001
    155 Unknown event type 10006
    160 Unknown event type 0
    190 Unknown event type 10005
   1390 Unknown event type 2000
  30882 Unknown event type 9003
  32011 Unknown event type 25368
```

These are things like "changed status from away to online" or "changed avatar" etc. I think it would be nice (and should not be difficult) to make MsgExport recognize these events and list them in the text file correctly.

**Comment by Robyer** [comment]
AFAIK it's hard to list them in text file as their internal format is unknown. Sure it might be known for the status change, but not for custom events in e.g. Skype, where it saves (if I remember) also JSON data strings as part of some event.

We would need to have (or maybe we already have? Idk) better transformation from event data to event text and vice-versa. Probably MsgExport would have to ask the protocol/plugin that created/handles this event type to transform it for him? Or just export it in binary form?

Or you are interested only in the status change events?

**Comment by LittleVulpix** [comment]
I'm interested in all of the events, though it's a minor gripe. When I'm for example checking for duplicates (during db repair) and I see something was truncated, but it says it was an unknown event X size Y after I compare the two exports (pre and post db check), it doesn't really tell me what was truncated. I made a list of what each event means but it'd be nice to have it listed properly already.

Again though, the export speed is a much more important issue to me ( #609 ), so this one can wait.

**Comment by georgehazan** [comment]
these events were generated by the plugins which are missing now. so there are no services that support them, that's why the MsgExport plugin cannot grab their description

**Comment by LittleVulpix** [comment]
Not true, these events do happen still, even now, and I have not changed my plugins in a while.

**Comment by LittleVulpix** [comment]
One of these events is for example a message edit in skypeweb plugin where the actual message is edited (causing the regular message event to become an unknown db event)

**Comment by LittleVulpix** [comment]
I have not seen this happen in the past 3 years. JSON export for MsgExport works fine now. Closing as resolved.
