### ISSUE TITLE
Ah!  it&#x27;s

### ISSUE THREAD

**Issue by David1501** [miranda-ng/miranda-ng#685]
Hello,

it was fixed some time ago....and now the *it&#x27 ;s* problem reappeared....(sorry for the space after the 7!)

**Comment by LittleVulpix** [comment]
I think @ghazan recently rewrote html / chat parsing, so this probably affected it.

**Comment by David1501** [comment]
Guys...is there a way to save my setting with Miranda?

**Comment by LittleVulpix** [comment]
What do you mean, "save my setting" ? Your preferences are stored in your profile (a .dat file generally located in the miranda folder\profiles\<profile name>\<profile name>.dat )

**Comment by David1501** [comment]
LittleVulpix Thank You! that's likely what i wanted to know

**Comment by Robyer** [comment]
@David1501 You're mixing different versions of plugins/core together. You can just copy whole folder to different computer and it will work. (unless that different computer doesn't support 64-bit programs and you copy there 64-bit Miranda)

Also, "it's" problem where? In what plugin? Give me link to previous issue...

**Comment by David1501** [comment]
@ Robyer...

the "it's" problem is on skype (sorry i forgot to mention it...) i do believe we talked a while ago about it...then it was fixed..and yesterday reappeared again...

About the copy thing...ok let me give it a try....

THX

**Comment by LittleVulpix** [comment]
@Robyer , the previous issue was https://github.com/miranda-ng/miranda-ng/issues/639 , but it had gotten fixed before. Apparently broken again now (can't check myself at the moment)

**Comment by Robyer** [comment]
@LittleVulpix Thanks. There was no related change in that code yesterday. Please check it later by yourself.
Maybe @David1501 somehow downgraded to stable a that's also why he is seeing that error message?

**Comment by David1501** [comment]
@Robyer no...:-) :-) something worst than that :-) :-) i used a regular installation file...and then copied profiles...plugin ecc. ecc. from pc 1 :-)

**Comment by LittleVulpix** [comment]
@David1501 Miranda is portable by default. Regardless of whether you installed it or not, you can take the _whole_ miranda folder, copy it to a different PC, launch it there and it will work... assuming you use 32bit miranda. If you use 64bit miranda, the PCs must both run a 64bit OS otherwise you'll have to switch to 32bit to launch it on a non-64bit OS.

**Comment by David1501** [comment]
@LittleVulpix ok THX...i see...anyway...the mess i did with the copy...it was on 2 64bit os...

**Comment by David1501** [comment]
@georgehazan can u please fix the  it&#x27;s issue....that is a bit annoying read msg like that?
:-)

**Comment by Robyer** [comment]
I'm closing this, as there is no problem with it&#x27 ;s, as mentioned on forum.
There might be different problem with missing part of messages in groupchats, but that wouuld be different issue (after @LittleVulpix verify it)...

**Comment by LittleVulpix** [comment]
@Robyer @David1501 

I FOUND IT. I know why this happens now. I did some testing with a friend who uses a mac, and there are 2 scenarios.

1) normal message with an apostrophe (or multiple). For example "I'm a lumberjack" - You will receive this message normally. The text (when you check the netlog) looks completely normal and ' is represented by ' .

2) normal message with an apostrophe BUT ALSO WITH AN EMOTICON. Not the "font" emojis but the standard emoticons like ":o" , for example "I'm a lumberjack :o". In this case, you will receive the message from the beginning of the message up until the first apostrophe, at which point the rest of the message is dropped. So in our case, you will receive just "I"

Upon inspection, in the message stream, you can see that the message arrived as:
`I&#x27;m a lumberjack <ss type=\"surprised\">:o</ss>`

Can you please check this? I have no idea why MAC SKYPE behaves this way, but it does.

**Comment by Robyer** [comment]
So when it is broken, it is received as `"content":"I&#x27;m a lumberjack <ss type=\"surprised\">:o</ss>"`
And when it is ok, it is received as `"content":"I&#x27;m a lumberjack"`
Right? Ok, I'll take a look later.

**Comment by LittleVulpix** [comment]
@Robyer Nop. When there is no smiley, the apostrophe is just `'` Not `&#x27;` Somehow, the mac skype converts apostrophe into the unicode format when a smiley is present as well.

**Comment by Robyer** [comment]
@LittleVulpix I was just looking 15 minutes to that piece of code that is doing the stripping and I can't see any problem. Maybe it will be at some other place in code... I'll check it some other day more thoroughly.

**Comment by Robyer** [comment]
Ohhh, found it I guess. It is stripped because I appended 'NULL' char there. Because I made a typo. Will fix it now :-)

**Comment by LittleVulpix** [comment]
Awesome! Thanks~
