### ISSUE TITLE
Don't load long chat history when opening message log with IEview

### ISSUE THREAD

**Issue by peci1** [miranda-ng/miranda-ng#687]
I have development version of Miranda NG, TabSRMM, IEview and History++. The message log is rendered by IEview.

If I open a chat window of somebody I have long history with, loading the window takes ages - probably because a lot of chat events are displayed. Without a config change from my side, this is a different behavior than before, say, a year ago or so.

I tired to find an IEview option to control the number of loaded events, but haven't succeeded. Where is it hidden (if it's there at all)?

**Comment by watcherhd** [comment]
Run DBchecker with option Mark all events "read".

**Comment by watcherhd** [comment]
Also look here:

https://i.imgur.com/vdGc6I0.png

**Comment by peci1** [comment]
Yes, I was playing with this setting, but regardless of what was set, Miranda loaded hundereds of events.

Your tip with running dbtool helped to resolve the issue. Thanks!

**Comment by LittleVulpix** [comment]
@peci1 , probably skypeweb proto? There is a bug, #608 , which causes this. The only resolution is the dbcheck->mark as read, indeed.

**Comment by peci1** [comment]
@LittleVulpix Yes, I'm using skypeweb, it might be correlated.
