### ISSUE TITLE
MRA: low level error messages shown to user

### ISSUE THREAD

**Issue by olmor** [miranda-ng/miranda-ng#688]
My previous submitted issue #616 was fixed, thanks,
but in MRA there are a lot of similar low level messages that shown to user.

I am working on Windows tablet.
When Internet connection is temporarily off, MRA starts showing these error messages every second:
"Can't connect to MRIM server, error"
"Can't connect to NLB server, error".

All these messages are shown with ShowFormattedErrorMessage call (in source code).

I use toaster plugin for notifications.
OS version is Windows 8.1.
¤ MRA.dll v.2.1.1.1 [20 Jan 2017 4:01:20] - Mail.ru Agent 

I need the way to suppress such error messages or please move all these messages to debug level.

**Comment by dartraiden** [comment]
MRA is deprecated.
