### ISSUE TITLE
Cannot connect to ICQ

### ISSUE THREAD

**Issue by buldogeon** [miranda-ng/miranda-ng#692]
Connection failed
Your ICQ number or password was rejected (5)
password length > 8
Miranda NG Version: 0.95.5 build #17337 x64

**Comment by georgehazan** [comment]
you need to retype your password, because in Miranda only first 8 bytes were stored previously

**Comment by dartraiden** [comment]
See troubleshooting section in [0.95.5 changelog](http://wiki.miranda-ng.org/index.php?title=Changelog/0.95.5).

**Comment by buldogeon** [comment]
oh i see )
it worked out
thanks
