### ISSUE TITLE
Unicode issue in "User added you" dialog

### ISSUE THREAD

**Issue by Robyer** [miranda-ng/miranda-ng#699]
When user has nick in unicode, it is showed as "?????" in the dialog. See screenshot below.

I'm not sure it is issue in ICQ protocol itself, or in the Core.

![miranda icq bug](https://cloud.githubusercontent.com/assets/359173/22627853/2c1ba038-ebca-11e6-98db-a9eaee8f0dca.png)

**Comment by georgehazan** [comment]
that dialog, as well as any clist event, is 100% Unicode. the problem is that how ICQ converted the cyrillic name of your contact into utf8. perhaps he uses an old client like QIP. you can attach a network log, when you click on Update button in this dialog
