### ISSUE TITLE
ICQ: file transfer makes miranda crash

### ISSUE THREAD

**Issue by SpinalBlood** [miranda-ng/miranda-ng#700]
File transfer doesn't work anymore since 17/01/07

Builds before that date were working fine (I have tested some builds provided by Watcher)

Sometimes it crashed after cancelling the not working transfer (happened when both sending or receiving files); other times the transfer worked, but it crashed the user who received the file when it was 100%. Not sure if something has changed in miranda.exe in the meanwhile, but it's definitely not working right now

I can't attach crashlog as it seems (odd) not generated from this kind of crash (actually I must force Miranda to close because it freezes and I must click again to force the crash to end

**Comment by Robyer** [comment]
Commits tried by SpinalBlood:

> WORKS: 		DB_AUTH_BLOB: handy piece of code moved into the core	16.01.2017 16:20	George Hazan 
> WORKS:		- constructor & destructor for NetlibBoundPort - warning fix - randomizer must work even if the s...	17.01.2017 13:56	George Hazan
> WORKS:		code cleaning	17.01.2017 14:08	George Hazan
> **CRASHES:	useless field DBEVENTINFO::cbSize removed	17.01.2017 15:19	George Hazan**

**Comment by Robyer** [comment]
@SpinalBlood Is this still a problem?

**Comment by SpinalBlood** [comment]
Yes, I'm afraid it still happens

**Comment by georgehazan** [comment]
ICQ has no file transfers anymore for about three years... The standard client simply upload a file to the cloud storage and then transmit a link to it. Maybe smth got broken at the server-side

**Comment by Robyer** [comment]
@georgehazan He said it works in older builds. Also see my comment where he tried various builds and it started crashing in the mentioned commit (in bold). So it must be some change in core.

**Comment by georgehazan** [comment]
well, I've just tested it with some people, everything is ok between two Mirandas
@SpinalBlood is that possible to download VS2010 Express (or VS2015 Express for Windows Desktop) and blow Miranda up under it? I can assist you via Team Viewer, for example

**Comment by dartraiden** [comment]
Just tested ICQ transfer between @georgehazan and me, All works correctly (even via double NAT).

**Comment by Robyer** [comment]
@SpinalBlood Ping, do you still have problems? And if so, is it still working in previous Miranda version as you said before?

**Comment by SpinalBlood** [comment]
Sorry for late reply. Sadly I can't really test ICQ since no one of my contacts is using it anymore...

I might test with Robyer if he wants (I remember we were crashing as well in one of our test)

**Comment by Robyer** [comment]
@SpinalBlood We can test it at the weekend.

**Comment by SpinalBlood** [comment]
It crashed again, and again there is no crashlog. This time it crashed without transferring, and we didn't cancel it. The only thing I can say is that right before the freeze a popup appeared telling that the transfer failed because proxy unavailable.

If it's true that icq now doesn't officially support file transfer, shouldn't it be disabled in miranda as well?

**Comment by georgehazan** [comment]
ICQ supports file transfers as a file upload to their server + sending a link to it
though there're no specifications for this

**Comment by Robyer** [comment]
@georgehazan But in Miranda ICQ transfers still work (at least SpinalBlood was able to send me file directly, and without crash). So perhaps they changed the behavior only for new protocol version and kept old working intact?

**Comment by georgehazan** [comment]
@SpinalBlood if you could test various commits one by one, doesn't it mean that you have VS and can compile Miranda yourself? If yes, just attach VS to Miranda and reproduce a crash under debugger

**Comment by SpinalBlood** [comment]
I might test with Robyer or another user, but I am not familiar with the compiling procedure...

**Comment by Robyer** [comment]
@SpinalBlood So how that works now? Anything new?

**Comment by SpinalBlood** [comment]
I have no online users to test it these days...

**Comment by georgehazan** [comment]
@SpinalBlood add me :) 731990
