### ISSUE TITLE
Newsfeed items from Facebook not being pulled/showing in  popups

### ISSUE THREAD

**Issue by newsjunkie247** [miranda-ng/miranda-ng#701]
I have it enabled to get popups for "most recent" items in the newsfeed, but they don't seem to be showing up anymore. Was still working this past week on Thursday as far as I can recall. Ticker items and notifications mostly seem to be working, though maybe slightly less common than before.

**Comment by Robyer** [comment]
Probably change on Facebook website.

I can't modify/fix tickers and notifications - Facebook sends me when he decides.
But newsfeeds I'm requesting and parsing manually, so there must be some change in HTML or something. I will look at that later.

**Comment by Robyer** [comment]
Fixed in 23764bc5bfbe6986a1c9a087510e6eeb2521c330
