### ISSUE TITLE
[ImportTXT] Duplicate message checking must check content as well as timestamp

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#708]
When importing history via ImportTXT, if one checks "check for duplicate messages" checkbox, the plugin only considers timestamps. Sometimes if you type really fast, you can type multiple messages per second. These will get pruned as duplicate even if they contain completely different text. This needs to be reworked, otherwise the duplicate checker more often than not discards valid messages.

**Comment by dartraiden** [comment]
ImportTXT is deprecated.
