### ISSUE TITLE
It is no longer possible to edit the menus

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#709]
Miranda NG options->Customize->Menus

It is not possible to check/uncheck the menus which should be displayed. I remember this functionality working some time last year so this is a **regression**.

**Comment by LittleVulpix** [comment]
Actually, this is a bug with miranda options menu. _sometimes_ it will become stuck - cancel/X/any option will no longer close the options menu and miranda must be restarted. Closing this issue, will open one for the menus.

**Comment by dartraiden** [comment]
Yes, it's well known bug with stucking options dialog.

**Comment by LittleVulpix** [comment]
Yeah. Logged as #710
