### ISSUE TITLE
[Facebook] offline history sync unicode is broken

### ISSUE THREAD

**Issue by watcherhd** [miranda-ng/miranda-ng#711]
![image](https://cloud.githubusercontent.com/assets/6558205/22864783/2bd13e30-f160-11e6-8452-7dca29302593.png)

![image](https://cloud.githubusercontent.com/assets/6558205/22864786/38f3c72c-f160-11e6-8eab-eb51c22f45a2.png)

**Comment by Robyer** [comment]
I can't reproduce. And code for processing unread messages and newly received messages (and attachments) is the same, so I don't know what could happen there or why.

Is it still happening for you? If so, perhaps try it without History++ (with plain TabSRMM log).

**Comment by Robyer** [comment]
Found the problem.

I am cutting long attachments descriptions to about 300 characters. And sometimes it can be cut between utf8 character bytes, so it end up having only first part of that utf8 character.
It is broken for TabSRMM too, but it can recover better than H++.

So I should fix this cutting texts to properly support utf8.
