### ISSUE TITLE
[Send ScreenShot+]: Plugin can not properly create JPG, PNG and BMP files 

### ISSUE THREAD

**Issue by ablazhov** [miranda-ng/miranda-ng#712]
**Expected behaviour:**
Create non-zero bytes image file of the selected type (TIF, GIF, JPG, PNG, BMP) in folder "%profile-name%\Screenshots".

**Actual behavior:**
When selected encoder is PNG or JPG the generated file is zero bytes and with no extension. When selected encoder is BMP the generated file is non-zero bytes, but with no extension. The file cannot be sent and the capturing dialog reappears until canceled.

**Miranda NG version:**
Both stable (0.95.5 build 17337) and development (0.95.6 as of Feb 13. 2017), x32 and x64 bits.

**Plugin version:**
0.8.9.1, stable and development according to Miranda version.

**Operating system:**
Windows 10 Pro x64, November update (build 10586) and Windows XP Pro x32, SP3, fully patched.

**Comment by White-Tiger** [comment]
how are you creating those "screenshots" because it's always been working for me.
Also, what's the full file path?

**Comment by ablazhov** [comment]
> Also, what's the full file path?

OK, I think I found the root cause of this problem:
If there is a **dot** in the name of some of the folders forming the full profile path, then I have the described problem. 
The moment I remove the dot(s) SendSS.dll starts to work just fine capturing images to JPG and PNG files.

The problem is my windows profile folder on a domain-controlled computer contains a dot, so not an easy task to get rid of that particular dot... 

Many thanks to @White-Tiger for pointing me to look at the path of the Miranda profile folder!
