### ISSUE TITLE
Sent messages showed as "old" after opening message window

### ISSUE THREAD

**Issue by Robyer** [miranda-ng/miranda-ng#722]
For maybe few weeks already is happening this problem, as seen on video: 

[miranda bug tabsrmm.zip](https://github.com/miranda-ng/miranda-ng/files/912679/miranda.bug.tabsrmm.zip)

When opening message window and sending message, it is showed as "old" - with same style as old messages that are printed right after msg window is opened.
And each newly sent message is also marked as "old"... UNLESS you wait at least 10 seconds before sending any/next message, as seen on video above.

scenarios:
a) open msg window, wait >10 seconds, then send message -> OK
b) open msg window, send message right away -> WRONG "old" style
b1) send another message right away -> same WRONG "old" style
b2) wait > 10 seconds, then send another message -> OK

It happens at least with TabSRMM and it is reproducible 100 % times.

NOTE: It does happen on Facebook protocol or Steam protocol, but it doesn't on ICQ. Other protocols I haven't tested.

**Comment by LittleVulpix** [comment]
I tried it with steam and a "clean" tabsrmm (internal message view) profile, I can't reproduce it (steam), see gif.

https://imgur.com/iNNx0ow

**Comment by Robyer** [comment]
@LittleVulpix Interesting. Could you try enable "Grouping messages" in TabSRMM log settings?
I'll try to reproduce it myself with different setting later too...

**Comment by Robyer** [comment]
It is happening for me with any settings I tried. Also running DbChecker didn't help either.
I'll try empty profile and comparing settings later...

**Comment by LittleVulpix** [comment]
Let me know! I was not able to reproduce it (sorry for spam on steam lol)

**Comment by Robyer** [comment]
Seems working in current development build.
