### ISSUE TITLE
Can't log anymore through proxy

### ISSUE THREAD

**Issue by glandru** [miranda-ng/miranda-ng#727]
Feb 20th I updated to the last build and can't log anymore (using a proxy)
When reverting to the update I did Feb 10th, I can connect.
In the net log I can see proxy info arriving but I also can read:
```
[07:52:08 05E0] Autoproxy Init 1
[07:52:08 05E0] Autoproxy init failed
```
resulting in direct connection attempts

**Comment by glandru** [comment]
Could anyone have a look on this?
I'm currently stuck on Feb 10th version...

**Comment by Robyer** [comment]
@georgehazan Could you look at this?

**Comment by georgehazan** [comment]
@glandru try next nightly build, it might be fixed
strange, but this bug was introduced five years ago, and you just run into it

**Comment by glandru** [comment]
@georgehazan I confirm issue is fixed, thx!
