### ISSUE TITLE
[Tabsrmm] Icon that opens groupchat logs does nothing

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#728]
Regression.

If logging is enabled for groupchats (Message sessions->Group chats->Log formatting->Enable logging to disk), the logs are still created - but they can no longer be opened from tabsrmm's history button in the container. Previously this button would open notepad to view the appropriate groupchat log.

**Comment by dartraiden** [comment]
Confirmed.

**Comment by watcherhd** [comment]
Confirmed

**Comment by LittleVulpix** [comment]
Praise the sun
