### ISSUE TITLE
[Tabsrmm] "img" insert button no longer works on a toggle

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#729]
Regression ( since a few days ago ).

Pressing the "img" button inserts the `[img]` tag - but pressing it again does not insert the `[/img]` tag.

Highlighting an image and pressing the img button correctly encloses the picture in img tags (with one normal and one with the forward slash), however it causes the button to be stuck in the "toggled mode", and every next click inserts the `[/img]` tag now. When in this stuck state, it is not possible to "untoggle" the img button anymore.

**Comment by georgehazan** [comment]
broken December 1st, 2016 :)

**Comment by LittleVulpix** [comment]
@georgehazan worked up until last week though. :D
