### ISSUE TITLE
Tox crash miranda when network fault

### ISSUE THREAD

**Issue by apollo2k4** [miranda-ng/miranda-ng#736]
Miranda Crash Report from 2017-03-07 14:47:15+0200. Crash Dumper v.0.0.5.2

Likely cause of the crash plugin: Tox protocol

Exception: Access Violation at address 16FADE7B. Reading from address 00000000.

Stack Trace:
---------------------------------------------------------------
16FADE7B (Tox 16FA0000): c:\sources\miranda_ng_compilation\protocols\tox\src\tox_contacts.cpp (73): CToxProto::GetContactPublicKey
16FA85F2 (Tox 16FA0000): c:\sources\miranda_ng_compilation\protocols\tox\src\tox_transfer.cpp (50): CToxProto::OnFriendFile
13D78AF3 (libtox 13D60000): (filename not available) (0): DllMainCRTStartup
13D6E2FF (libtox 13D60000): (filename not available) (0): DllMainCRTStartup
779B5950 (ntdll 77960000): (filename not available) (0): wcsnicmp
779B63E0 (ntdll 77960000): (filename not available) (0): wcsnicmp
779B6416 (ntdll 77960000): (filename not available) (0): wcsnicmp
775198CD (msvcrt 77510000): (filename not available) (0): free
13D83CD1 (libtox 13D60000): (filename not available) (0): DllMainCRTStartup
01D941D8 ((module-name not available) 00000000): (filename not available) (0): (function-name not available)

CPU: AMD C-50 Processor [x86 Family 20 Model 1 Stepping 0] [DEP Enabled] [2 CPUs]
Installed RAM: 1771 MBytes
Microsoft Windows 7 Ultimate Edition, 32-bit Service Pack 1 (build 7601)
Internet Explorer: 9.11.9600.18537 (build 99600)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian

Miranda NG Version: 0.95.6 alpha build #17821
Build time: 2017-03-06 04:04:30+0200
Profile: D:\My Docs\Dropbox\miranda\Profiles\apollo2k4\apollo2k4.dat (dbx mmap driver)
Language pack: Russian (RU) [0419]
Service Mode: No

Active Plugins (30):
¤ AdvaImg.dll v.0.11.0.2 [2017-01-02 04:01:28+0200] - Miranda image services 
¤ AVS.dll v.0.95.3.4 [2017-01-18 04:00:12+0200] - Avatar service 
¤ ChangeKeyboardLayout.dll v.0.0.1.6 [2016-11-27 20:10:36+0200] - Change keyboard layout 
¤ Clist_modern.dll v.0.9.1.5 [2017-01-18 04:01:52+0200] - Modern contact list 
¤ CrashDumper.dll v.0.0.5.2 [2017-01-13 04:01:54+0200] - Crash dumper 
¤ DbEditorPP.dll v.4.0.1.1 [2017-01-02 04:02:06+0200] - Database editor++ 
¤ Dbx_mmap.dll v.0.95.3.1 [2017-03-06 04:00:18+0200] - Miranda NG mmap database driver 
¤ Discord.dll v.0.5.0.1 [2017-03-02 04:04:22+0200] - Discord protocol 
¤ Dropbox.dll v.0.12.2.3 [2017-01-18 04:03:40+0200] - Dropbox 
¤ Facebook.dll v.0.3.2.0 [2017-02-26 04:01:30+0200] - Facebook RM 
¤ Fingerprint.dll v.0.1.0.0 [2017-01-02 04:02:40+0200] - Fingerprint NG 
¤ HistoryPP.dll v.1.5.1.5 [2017-02-09 18:55:12+0200] - History++ 
¤ ICQ.dll v.0.11.3.5 [2017-02-20 04:00:30+0200] - IcqOscarJ protocol 
¤ Import.dll v.0.95.4.3 [2017-01-18 04:00:10+0200] - Import contacts and messages 
¤ IRC.dll v.0.11.0.3 [2017-01-25 04:00:28+0200] - IRC protocol 
¤ Jabber.dll v.0.11.0.4 [2017-03-05 04:01:10+0200] - Jabber protocol 
¤ MessageState.dll v.0.0.1.0 [2017-01-18 04:04:08+0200] - Message state 
¤ MirOTR.dll v.0.14.1.16 [2017-01-18 04:02:54+0200] - Miranda OTR 
¤ NewEventNotify.dll v.0.2.2.3 [2017-01-18 04:01:48+0200] - NewEventNotify 
¤ NewXstatusNotify.dll v.1.4.0.11 [2017-01-18 04:01:00+0200] - xStatus notify 
¤ NotesReminders.dll v.0.1.0.1 [2016-10-31 04:02:20+0200] - Sticky Notes & Reminders 
¤ PluginUpdater.dll v.0.1.2.5 [2017-01-13 04:02:08+0200] - Plugin updater 
¤ Scriver.dll v.3.0.1.3 [2017-03-05 20:12:13+0200] - Scriver 
¤ SkypeWeb.dll v.0.12.2.3 [2017-01-24 04:04:10+0200] - Skype protocol (Web) 
¤ SmileyAdd.dll v.0.2.4.1 [2017-01-13 04:01:12+0200] - SmileyAdd 
¤ SpellChecker.dll v.0.2.6.4 [2016-12-14 04:01:54+0200] - Spell checker 
¤ StatusManager.dll v.0.11.2.0 [2017-02-11 04:04:16+0200] - Status manager 
¤ Tox.dll v.0.11.1.22 [2017-03-03 04:04:10+0200] - Tox protocol 
¤ VKontakte.dll v.0.1.2.13 [2017-03-01 04:03:34+0200] - VKontakte protocol 
¤ YAPP.dll v.0.5.0.12 [2016-11-27 20:10:58+0200] - YAPP 

Loaded Modules:
-------------------------------------------------------------------------------
D:\My Docs\Dropbox\miranda\miranda32.exe  00400000 - 00409000 v.0.95.6.17821 [2017-03-06 04:04:30+0200]
C:\Windows\SYSTEM32\ntdll.dll  77960000 - 77AA2000 v.6.1.7601.23572 [2016-10-11 17:21:52+0200]
C:\Windows\system32\kernel32.dll  77640000 - 77715000 v.6.1.7601.23392 [2016-03-18 00:26:26+0200]
C:\Windows\system32\KERNELBASE.dll  759F0000 - 75A3B000 v.6.1.7601.23392 [2016-03-18 00:26:26+0200]
C:\Windows\system32\USER32.dll  771D0000 - 77299000 v.6.1.7601.23594 [2016-11-10 18:19:39+0200]
C:\Windows\system32\GDI32.dll  76D30000 - 76D7E000 v.6.1.7601.23591 [2016-11-06 18:16:33+0200]
C:\Windows\system32\LPK.dll  773F0000 - 773FA000 v.6.1.7601.23587 [2016-11-02 17:16:17+0200]
C:\Windows\system32\USP10.dll  77350000 - 773ED000 v.1.626.7601.23585 [2016-10-27 17:20:17+0200]
C:\Windows\system32\msvcrt.dll  77510000 - 775BC000 v.7.0.7601.17744 [2011-12-16 09:52:58+0200]
D:\My Docs\Dropbox\miranda\MSVCR100.dll  64900000 - 649BF000 v.10.0.40219.325 [2011-06-11 01:58:52+0200]
C:\Windows\system32\IMM32.DLL  77B00000 - 77B1F000 v.6.1.7601.17514 [2010-11-20 23:29:20+0200]
C:\Windows\system32\MSCTF.dll  75BF0000 - 75CBD000 v.6.1.7601.23572 [2016-10-11 17:18:29+0200]
D:\My Docs\Dropbox\miranda\libs\mir_app.mir  12420000 - 124E4000 v.0.95.6.17821 [2017-03-06 04:00:42+0200]
C:\Windows\system32\WINMM.dll  73DF0000 - 73E22000 v.6.1.7601.17514 [2010-11-20 23:29:18+0200]
C:\Windows\system32\SHLWAPI.dll  774B0000 - 77507000 v.6.1.7601.17514 [2010-11-20 23:29:03+0200]
C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.18837_none_41e855142bd5705d\COMCTL32.dll  749F0000 - 74B8E000 v.6.10.7601.18837 [2015-04-24 19:54:13+0200]
C:\Windows\system32\WS2_32.dll  77AB0000 - 77AE5000 v.6.1.7601.23451 [2016-05-11 17:19:26+0200]
C:\Windows\system32\RPCRT4.dll  772A0000 - 77342000 v.6.1.7601.23642 [2017-01-05 19:43:12+0200]
C:\Windows\system32\NSI.dll  76910000 - 76916000 v.6.1.7600.16385 [2009-07-14 03:16:11+0200]
C:\Windows\system32\UxTheme.dll  74550000 - 74590000 v.6.1.7600.16385 [2009-07-14 03:16:17+0200]
C:\Windows\system32\COMDLG32.dll  775C0000 - 7763B000 v.6.1.7601.17514 [2010-11-20 23:29:04+0200]
C:\Windows\system32\SHELL32.dll  75CC0000 - 7690C000 v.6.1.7601.23537 [2016-08-29 17:12:50+0200]
C:\Windows\system32\ADVAPI32.dll  77400000 - 774A1000 v.6.1.7601.23572 [2016-10-11 17:18:02+0200]
C:\Windows\SYSTEM32\sechost.dll  76980000 - 76999000 v.6.1.7601.18869 [2015-05-25 20:01:39+0200]
C:\Windows\system32\ole32.dll  77070000 - 771CD000 v.6.1.7601.23392 [2016-03-18 00:28:21+0200]
D:\My Docs\Dropbox\miranda\libs\zlib.mir  126E0000 - 126F7000 v.1.2.8.0 [2017-03-06 04:00:12+0200]
D:\My Docs\Dropbox\miranda\libs\mir_core.mir  125C0000 - 125E0000 [2017-03-06 04:00:18+0200]
C:\Windows\system32\VERSION.dll  74BC0000 - 74BC9000 v.6.1.7600.16385 [2009-07-14 03:16:17+0200]
C:\Windows\system32\Secur32.dll  75750000 - 75758000 v.6.1.7601.23642 [2017-01-05 19:43:12+0200]
C:\Windows\system32\SSPICLI.DLL  75770000 - 7578B000 v.6.1.7601.23642 [2017-01-05 19:43:15+0200]
C:\Program Files\Yandex\Punto Switcher\pshook.dll  703C0000 - 703E0000 v.4.3.6.1851 [2017-02-17 11:25:32+0200]
C:\Windows\system32\imagehlp.dll  77B20000 - 77B4B000 v.6.1.7601.18288 [2013-10-19 03:36:59+0200]
C:\Windows\system32\api-ms-win-core-synch-l1-2-0.DLL  6AA90000 - 6AA93000 v.10.0.10586.9 [2015-11-19 16:06:05+0200]
C:\Windows\system32\dwmapi.dll  74220000 - 74233000 v.6.1.7601.18917 [2015-07-09 19:42:54+0200]
C:\Windows\system32\CRYPTBASE.dll  757E0000 - 757EC000 v.6.1.7601.23642 [2017-01-05 19:19:03+0200]
C:\Windows\system32\CLBCatQ.DLL  76CA0000 - 76D23000 v.2001.12.8530.16385 [2009-07-14 03:15:03+0200]
C:\Windows\system32\OLEAUT32.dll  76C00000 - 76C91000 v.6.1.7601.23569 [2016-10-07 17:12:49+0200]
C:\Windows\system32\explorerframe.dll  6D5D0000 - 6D740000 v.6.1.7601.23537 [2016-08-29 17:12:38+0200]
C:\Windows\system32\DUser.dll  742C0000 - 742EF000 v.6.1.7600.16385 [2009-07-14 03:15:13+0200]
C:\Windows\system32\DUI70.dll  742F0000 - 743A2000 v.6.1.7600.16385 [2009-07-14 03:15:13+0200]
D:\My Docs\Dropbox\miranda\Plugins\CrashDumper.dll  14980000 - 14990000 v.0.0.5.2 [2017-01-13 04:01:54+0200]
C:\Windows\system32\dbghelp.dll  71280000 - 7136B000 v.6.1.7601.17514 [2010-11-20 23:29:12+0200]
D:\My Docs\Dropbox\miranda\Plugins\DbEditorPP.dll  14AE0000 - 14AFD000 v.4.0.1.1 [2017-01-02 04:02:06+0200]
D:\My Docs\Dropbox\miranda\Plugins\Dbx_mmap.dll  14B80000 - 14B91000 v.0.95.3.1 [2017-03-06 04:00:18+0200]
D:\My Docs\Dropbox\miranda\Plugins\Import.dll  15740000 - 1574D000 v.0.95.4.3 [2017-01-18 04:00:10+0200]
D:\My Docs\Dropbox\miranda\Core\stdcrypt.dll  13080000 - 1308B000 v.0.95.6.17821 [2017-03-06 04:04:28+0200]
D:\My Docs\Dropbox\miranda\Core\stdssl.dll  13180000 - 13187000 v.0.95.6.17821 [2017-03-06 04:04:24+0200]
C:\Windows\system32\CRYPT32.dll  75A80000 - 75BA1000 v.6.1.7601.23566 [2016-10-04 17:13:00+0200]
C:\Windows\system32\MSASN1.dll  758D0000 - 758DC000 v.6.1.7601.17514 [2010-11-20 23:29:04+0200]
C:\Windows\system32\WSOCK32.dll  6E2C0000 - 6E2C7000 v.6.1.7600.16385 [2009-07-14 03:16:20+0200]
C:\Windows\system32\Msftedit.dll  6A820000 - 6A8B4000 v.5.41.21.2510 [2010-11-20 23:29:12+0200]
D:\My Docs\Dropbox\miranda\Plugins\AdvaImg.dll  14280000 - 1430F000 v.0.11.0.2 [2017-01-02 04:01:28+0200]
D:\My Docs\Dropbox\miranda\MSVCP100.dll  64CF0000 - 64D59000 v.10.0.40219.325 [2011-06-11 01:58:52+0200]
D:\My Docs\Dropbox\miranda\Plugins\Clist_modern.dll  146E0000 - 14752000 v.0.9.1.5 [2017-01-18 04:01:52+0200]
C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.0.7601.23545_none_6cb562a507085282\gdiplus.dll  5E300000 - 5E4A9000 v.5.2.7601.23545 [2016-09-12 22:49:16+0200]
C:\Windows\system32\MSIMG32.dll  750D0000 - 750D5000 v.6.1.7600.16385 [2009-07-14 03:15:44+0200]
D:\My Docs\Dropbox\miranda\Plugins\AVS.dll  14500000 - 14512000 v.0.95.3.4 [2017-01-18 04:00:12+0200]
D:\My Docs\Dropbox\miranda\Plugins\ChangeKeyboardLayout.dll  14680000 - 1468C000 v.0.0.1.6 [2016-11-27 20:10:36+0200]
D:\My Docs\Dropbox\miranda\Plugins\Discord.dll  14C00000 - 14C17000 v.0.5.0.1 [2017-03-02 04:04:22+0200]
D:\My Docs\Dropbox\miranda\libs\libjson.mir  12400000 - 1240C000 [2017-03-06 04:00:20+0200]
D:\My Docs\Dropbox\miranda\Plugins\Dropbox.dll  02030000 - 02043000 v.0.12.2.3 [2017-01-18 04:03:40+0200]
D:\My Docs\Dropbox\miranda\Plugins\Facebook.dll  14CE0000 - 14D30000 v.0.3.2.0 [2017-02-26 04:01:30+0200]
D:\My Docs\Dropbox\miranda\Plugins\Fingerprint.dll  14D40000 - 14D58000 v.0.1.0.0 [2017-01-02 04:02:40+0200]
D:\My Docs\Dropbox\miranda\Plugins\HistoryPP.dll  150C0000 - 152AF000 v.1.5.1.5 [2017-02-09 18:55:12+0200]
C:\Windows\system32\winspool.drv  73E70000 - 73EC1000 v.6.1.7601.17514 [2010-11-20 23:29:12+0200]
C:\Windows\system32\RICHED20.DLL  73360000 - 733D6000 v.5.31.23.1230 [2010-11-20 23:29:20+0200]
D:\My Docs\Dropbox\miranda\Plugins\ICQ.dll  155E0000 - 15633000 v.0.11.3.5 [2017-02-20 04:00:30+0200]
D:\My Docs\Dropbox\miranda\Plugins\IRC.dll  15820000 - 1586E000 v.0.11.0.3 [2017-01-25 04:00:28+0200]
D:\My Docs\Dropbox\miranda\Plugins\Jabber.dll  15900000 - 15990000 v.0.11.0.4 [2017-03-05 04:01:10+0200]
D:\My Docs\Dropbox\miranda\libs\LIBEAY32.mir  615B0000 - 616ED000 v.1.0.2.12 [2017-02-16 16:13:10+0200]
D:\My Docs\Dropbox\miranda\libs\libaxolotl.mir  120A0000 - 120CC000 [2017-03-05 04:00:48+0200]
C:\Windows\system32\DNSAPI.dll  75140000 - 75184000 v.6.1.7601.17570 [2012-01-29 20:04:00+0200]
D:\My Docs\Dropbox\miranda\Plugins\MessageState.dll  15A80000 - 15A87000 v.0.0.1.0 [2017-01-18 04:04:08+0200]
D:\My Docs\Dropbox\miranda\Plugins\MirOTR.dll  15BA0000 - 15C38000 v.0.14.1.16 [2017-01-18 04:02:54+0200]
D:\My Docs\Dropbox\miranda\Plugins\NewEventNotify.dll  16000000 - 1600A000 v.0.2.2.3 [2017-01-18 04:01:48+0200]
D:\My Docs\Dropbox\miranda\Plugins\NewXstatusNotify.dll  16060000 - 16080000 v.1.4.0.11 [2017-01-18 04:01:00+0200]
D:\My Docs\Dropbox\miranda\Plugins\NotesReminders.dll  161A0000 - 161BD000 v.0.1.0.1 [2016-10-31 04:02:20+0200]
D:\My Docs\Dropbox\miranda\Plugins\PluginUpdater.dll  16360000 - 16374000 v.0.1.2.5 [2017-01-13 04:02:08+0200]
D:\My Docs\Dropbox\miranda\Plugins\Scriver.dll  10000000 - 10038000 v.3.0.1.3 [2017-03-05 20:12:13+0200]
D:\My Docs\Dropbox\miranda\Plugins\SkypeWeb.dll  16940000 - 16985000 v.0.12.2.3 [2017-01-24 04:04:10+0200]
D:\My Docs\Dropbox\miranda\Plugins\SmileyAdd.dll  169E0000 - 169FD000 v.0.2.4.1 [2017-01-13 04:01:12+0200]
D:\My Docs\Dropbox\miranda\Plugins\SpellChecker.dll  16AA0000 - 16AB6000 v.0.2.6.4 [2016-12-14 04:01:54+0200]
D:\My Docs\Dropbox\miranda\libs\hunspell.mir  12000000 - 12050000 v.1.3.4.0 [2016-12-14 04:01:36+0200]
D:\My Docs\Dropbox\miranda\Plugins\StatusManager.dll  16BA0000 - 16BBB000 v.0.11.2.0 [2017-02-11 04:04:16+0200]
C:\Windows\system32\WININET.dll  769A0000 - 76BFC000 v.11.0.9600.18538 [2016-11-12 19:05:59+0200]
C:\Windows\system32\api-ms-win-downlevel-user32-l1-1-0.dll  75BD0000 - 75BD4000 v.6.2.9200.16492 [2015-02-12 16:22:02+0200]
C:\Windows\system32\api-ms-win-downlevel-shlwapi-l1-1-0.dll  758F0000 - 758F4000 v.6.2.9200.16492 [2015-02-12 16:22:02+0200]
C:\Windows\system32\api-ms-win-downlevel-version-l1-1-0.dll  75950000 - 75954000 v.6.2.9200.16492 [2015-02-12 16:22:02+0200]
C:\Windows\system32\api-ms-win-downlevel-normaliz-l1-1-0.dll  75A70000 - 75A73000 v.6.2.9200.16492 [2015-02-12 16:22:02+0200]
C:\Windows\system32\normaliz.DLL  77AF0000 - 77AF3000 v.6.1.7600.16385 [2009-07-14 03:09:00+0200]
C:\Windows\system32\iertutil.dll  77720000 - 77954000 v.11.0.9600.18538 [2016-11-12 20:20:21+0200]
C:\Windows\system32\api-ms-win-downlevel-advapi32-l1-1-0.dll  758E0000 - 758E5000 v.6.2.9200.16492 [2015-02-12 16:22:02+0200]
C:\Windows\system32\USERENV.dll  75900000 - 75917000 v.6.1.7601.17514 [2010-11-20 23:29:13+0200]
C:\Windows\system32\profapi.dll  758C0000 - 758CB000 v.6.1.7600.16385 [2009-07-14 03:16:12+0200]
C:\Windows\system32\IPHLPAPI.DLL  73520000 - 7353C000 v.6.1.7601.17514 [2010-11-20 23:29:24+0200]
C:\Windows\system32\WINNSI.DLL  73510000 - 73517000 v.6.1.7600.16385 [2009-07-14 03:16:19+0200]
D:\My Docs\Dropbox\miranda\Plugins\Tox.dll  16FA0000 - 16FCA000 v.0.11.1.22 [2017-03-03 04:04:10+0200]
D:\My Docs\Dropbox\miranda\libs\libtox.dll  13D60000 - 13F42000 [2017-02-24 04:00:06+0200]
D:\My Docs\Dropbox\miranda\Plugins\VKontakte.dll  171A0000 - 171DC000 v.0.1.2.13 [2017-03-01 04:03:34+0200]
D:\My Docs\Dropbox\miranda\Plugins\YAPP.dll  17680000 - 17691000 v.0.5.0.12 [2016-11-27 20:10:58+0200]
D:\My Docs\Dropbox\miranda\Core\stduserinfo.dll  131C0000 - 131CC000 v.0.95.6.17821 [2017-03-06 04:04:30+0200]
D:\My Docs\Dropbox\miranda\Core\stdemail.dll  130A0000 - 130A6000 v.0.95.6.17821 [2017-03-06 04:04:30+0200]
D:\My Docs\Dropbox\miranda\Core\stdauth.dll  13000000 - 13007000 v.0.95.6.17821 [2017-03-06 04:04:32+0200]
D:\My Docs\Dropbox\miranda\Core\stdfile.dll  130C0000 - 130CF000 v.0.95.6.17821 [2017-03-06 04:04:34+0200]
D:\My Docs\Dropbox\miranda\Core\stdhelp.dll  130E0000 - 130E6000 v.0.95.6.17821 [2017-03-06 04:04:28+0200]
D:\My Docs\Dropbox\miranda\Core\stdidle.dll  13100000 - 13107000 v.0.95.6.17821 [2017-03-06 04:04:32+0200]
C:\Windows\system32\WTSAPI32.dll  750E0000 - 750ED000 v.6.1.7601.17514 [2010-11-20 23:29:06+0200]
D:\My Docs\Dropbox\miranda\Core\stdautoaway.dll  13020000 - 13026000 v.0.95.6.17821 [2017-03-06 04:04:28+0200]
D:\My Docs\Dropbox\miranda\Core\stdaway.dll  13040000 - 13049000 v.0.95.6.17821 [2017-03-06 04:04:30+0200]
C:\Windows\system32\oleacc.dll  73E30000 - 73E6C000 v.7.0.0.0 [2012-01-29 20:11:39+0200]
C:\Windows\system32\mswsock.dll  752A0000 - 752DC000 v.6.1.7601.23451 [2016-05-11 17:19:16+0200]
C:\Windows\System32\wshtcpip.dll  74C00000 - 74C05000 v.6.1.7600.16385 [2009-07-14 03:16:20+0200]
C:\Windows\System32\wship6.dll  752F0000 - 752F6000 v.6.1.7600.16385 [2009-07-14 03:16:20+0200]
C:\Windows\system32\rasadhlp.dll  6E2B0000 - 6E2B6000 v.6.1.7600.16385 [2009-07-14 03:16:12+0200]
C:\Windows\System32\fwpuclnt.dll  71BC0000 - 71BF8000 v.6.1.7601.18283 [2013-10-12 04:01:25+0200]
C:\Program Files\WIDCOMM\Bluetooth Software\btmmhook.dll  717C0000 - 717F6000 v.6.5.1.5800 [2014-07-17 18:32:08+0200]
C:\Windows\system32\PSAPI.DLL  77B50000 - 77B55000 v.6.1.7600.16385 [2009-07-14 03:16:12+0200]
C:\Windows\system32\schannel.dll  750F0000 - 75131000 v.6.1.7601.23642 [2017-01-05 19:43:12+0200]
C:\Windows\system32\credssp.dll  74D80000 - 74D88000 v.6.1.7601.23642 [2017-01-05 19:43:01+0200]
C:\Windows\system32\ncrypt.dll  75430000 - 75469000 v.6.1.7601.23642 [2017-01-05 19:43:08+0200]
C:\Windows\system32\bcrypt.dll  75410000 - 75427000 v.6.1.7601.23642 [2017-01-05 19:43:00+0200]
C:\Windows\system32\bcryptprimitives.dll  74F90000 - 74FCD000 v.6.1.7601.23451 [2016-05-12 15:04:55+0200]
C:\Windows\system32\NLAapi.dll  73590000 - 735A0000 v.6.1.7601.17964 [2012-10-03 18:42:26+0200]
C:\Windows\system32\napinsp.dll  6D540000 - 6D550000 v.6.1.7600.16385 [2009-07-14 03:16:02+0200]
C:\Windows\system32\pnrpnsp.dll  6D520000 - 6D532000 v.6.1.7600.16385 [2009-07-14 03:16:12+0200]
C:\Windows\System32\winrnr.dll  6D1F0000 - 6D1F8000 v.6.1.7600.16385 [2009-07-14 03:16:19+0200]
C:\Windows\system32\wshbth.dll  6D1E0000 - 6D1ED000 v.6.1.7601.17514 [2010-11-20 23:29:24+0200]
C:\Windows\system32\dhcpcsvc.DLL  72060000 - 72072000 v.6.1.7600.16385 [2009-07-14 03:15:11+0200]
C:\Windows\system32\CRYPTSP.dll  75300000 - 75317000 v.6.1.7601.23471 [2016-06-14 17:21:20+0200]
C:\Windows\system32\rsaenh.dll  74FD0000 - 7500B000 v.6.1.7600.16385 [2009-07-14 03:17:54+0200]
C:\Program Files\WIDCOMM\Bluetooth Software\btkeyind.dll  71800000 - 71822000 v.6.5.1.5800 [2014-07-17 18:32:04+0200]
C:\Windows\system32\RpcRtRemote.dll  75850000 - 7585E000 v.6.1.7601.17514 [2010-11-20 23:29:12+0200]
C:\Windows\system32\msls31.dll  68D70000 - 68DA1000 v.3.10.349.0 [2015-02-12 16:26:33+0200]
C:\Windows\system32\SXS.DLL  757F0000 - 7584F000 v.6.1.7601.17514 [2010-11-20 23:29:19+0200]
C:\Windows\system32\WindowsCodecs.dll  740B0000 - 741E1000 v.6.2.9200.21830 [2016-04-09 06:20:04+0200]
C:\Windows\system32\apphelp.dll  75790000 - 757DC000 v.6.1.7601.19050 [2015-10-29 19:49:58+0200]
C:\Users\Apollo2k4\AppData\Roaming\Yandex\YandexDisk\YandexDiskOverlays-2398.dll  62D30000 - 62E6D000 v.1.4.15.2398 [2017-02-20 12:58:03+0200]
C:\Program Files\Dropbox\Client\DropboxExt.14.0.dll  61080000 - 610BB000 v.1.0.14.0 [2017-03-03 11:07:48+0200]
C:\Windows\system32\SETUPAPI.dll  76ED0000 - 7706D000 v.6.1.7601.17514 [2010-11-20 23:29:06+0200]
C:\Windows\system32\CFGMGR32.dll  75920000 - 75947000 v.6.1.7601.17514 [2010-11-20 23:29:12+0200]
C:\Windows\system32\DEVOBJ.dll  75BB0000 - 75BC2000 v.6.1.7600.16385 [2009-07-14 03:15:11+0200]
C:\Windows\system32\propsys.dll  74590000 - 74685000 v.7.0.7601.17514 [2010-11-20 23:29:12+0200]
C:\Windows\system32\ntmarta.dll  73890000 - 738B1000 v.6.1.7600.16385 [2009-07-14 03:16:11+0200]
C:\Windows\system32\WLDAP32.dll  77B60000 - 77BA5000 v.6.1.7601.17514 [2010-11-20 23:29:19+0200]
C:\Windows\system32\thumbcache.dll  6D550000 - 6D566000 v.6.1.7601.17514 [2010-11-20 23:29:12+0200]
C:\Windows\system32\PhotoMetadataHandler.dll  6D200000 - 6D252000 v.6.1.7600.16385 [2009-07-14 03:16:12+0200]
C:\Windows\system32\XmlLite.dll  741F0000 - 7421F000 v.1.3.1001.0 [2012-01-29 20:11:19+0200]
C:\Windows\system32\LINKINFO.dll  6D080000 - 6D089000 v.6.1.7600.16385 [2009-07-14 03:15:36+0200]
C:\Windows\System32\StructuredQuery.dll  65630000 - 6568C000 v.7.0.7601.23451 [2016-05-11 17:19:24+0200]
C:\Windows\system32\IconCodecService.dll  6D1D0000 - 6D1D6000 v.6.1.7600.16385 [2009-07-14 03:15:27+0200]
C:\Windows\system32\SHDOCVW.dll  6AD80000 - 6ADAF000 v.6.1.7601.18222 [2013-07-26 03:55:59+0200]
C:\Windows\system32\ieframe.DLL  6B8C0000 - 6C5CB000 v.11.0.9600.18538 [2016-11-12 19:21:32+0200]
C:\Windows\system32\api-ms-win-downlevel-shell32-l1-1-0.dll  6AFB0000 - 6AFB4000 v.6.2.9200.16492 [2015-02-12 16:22:02+0200]
C:\Windows\system32\api-ms-win-downlevel-shlwapi-l2-1-0.dll  6AD70000 - 6AD74000 v.6.2.9200.16492 [2015-02-12 16:22:02+0200]
C:\Windows\system32\ntshrui.dll  69BE0000 - 69C50000 v.6.1.7601.17755 [2012-01-04 10:58:41+0200]
C:\Windows\system32\srvcli.dll  756E0000 - 756F9000 v.6.1.7601.17514 [2010-11-20 23:29:15+0200]
C:\Windows\system32\cscapi.dll  6CD50000 - 6CD5B000 v.6.1.7601.17514 [2010-11-20 23:29:08+0200]
C:\Windows\system32\slc.dll  73570000 - 7357A000 v.6.1.7600.16385 [2009-07-14 03:16:15+0200]
C:\Windows\system32\NetworkExplorer.dll  6A8F0000 - 6AA88000 v.6.1.7601.17514 [2010-11-20 23:29:13+0200]
C:\Windows\system32\actxprxy.dll  6CD60000 - 6CDAE000 v.6.1.7601.17514 [2010-11-20 23:29:07+0200]
C:\Windows\system32\MPR.dll  6FB50000 - 6FB62000 v.6.1.7600.16385 [2009-07-14 03:15:41+0200]
C:\Windows\System32\drprov.dll  70440000 - 70448000 v.6.1.7600.16385 [2009-07-14 03:15:13+0200]
C:\Windows\System32\WINSTA.dll  750A0000 - 750C9000 v.6.1.7601.18540 [2014-07-17 03:40:03+0200]
C:\Windows\System32\ntlanman.dll  70420000 - 70434000 v.6.1.7601.17514 [2010-11-20 23:29:07+0200]
C:\Windows\System32\davclnt.dll  70400000 - 70418000 v.6.1.7601.23542 [2016-09-08 22:34:01+0200]
C:\Windows\System32\DAVHLPR.dll  703E0000 - 703E8000 v.6.1.7600.16385 [2009-07-14 03:15:08+0200]
C:\Windows\system32\wkscli.dll  73D20000 - 73D2F000 v.6.1.7601.17514 [2010-11-20 23:29:06+0200]
C:\Windows\system32\netutils.dll  73D30000 - 73D39000 v.6.1.7601.17514 [2010-11-20 23:29:13+0200]
C:\Windows\system32\PortableDeviceApi.dll  6A1B0000 - 6A239000 v.6.1.7601.17514 [2010-11-20 23:29:41+0200]
C:\Windows\system32\WINTRUST.dll  75A40000 - 75A6F000 v.6.1.7601.23566 [2016-10-04 17:13:15+0200]
C:\Windows\system32\EhStorAPI.dll  6FC80000 - 6FCA2000 v.6.1.7601.17514 [2010-11-20 23:29:11+0200]
C:\Program Files\Internet Explorer\ieproxy.dll  65690000 - 656DA000 v.11.0.9600.18538 [2016-11-12 18:58:11+0200]
C:\Windows\system32\api-ms-win-downlevel-ole32-l1-1-0.dll  75BE0000 - 75BE4000 v.6.2.9200.16492 [2015-02-12 16:22:02+0200]
C:\Windows\system32\samcli.dll  73D10000 - 73D1F000 v.6.1.7601.17514 [2010-11-20 23:29:06+0200]
C:\Windows\system32\SAMLIB.dll  74690000 - 746A2000 v.6.1.7601.23390 [2016-03-16 01:53:30+0200]

**Comment by aunsane** [comment]
Should be fixed in 5de5349.
