### ISSUE TITLE
[Discord] It is not possible to add a new contact

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#743]
It seems that Discord has changed something - when a contact request is made from miranda, the account becomes flagged as unverified (stopping any contact additions). For now it is necessary to add contacts via the website. Not a regression, rather, Discord probably changed something.

**Comment by georgehazan** [comment]
it's smth that happened to your account, perhaps it's unverified or smth like that

**Comment by LittleVulpix** [comment]
@georgehazan Don't close this issue please.

I tried this with a brand new account as well as with mine. Both verified. As soon as a request is made VIA MIRANDA, they become unverified.

**Comment by LittleVulpix** [comment]
New information on this one - the discord account also becomes flagged as unverified if you accept someone else's friend request via miranda (regardless of where they sent it from), so it seems like any kind of friend auth causes this issue.

**Comment by georgehazan** [comment]
fixed, AMDG
