### ISSUE TITLE
Strange code in TabSRMM

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#744]
\TabSRMM\src\container.cpp:
![2017-03-13 17_24_08-d__dev_miranda-ng_plugins_tabsrmm_src_container cpp - notepad administrator](https://cloud.githubusercontent.com/assets/5046855/23858577/ea81bb26-0811-11e7-8407-5e2d686b064f.png)
_then_ and _else_ code blocks are identical. So condition _if (!dat->isChat())_ is useless.

Same problem in msgs.cpp:
![2017-03-13 17_19_11-d__dev_miranda-ng_plugins_tabsrmm_src_msgs cpp - notepad administrator](https://cloud.githubusercontent.com/assets/5046855/23858388/446cc244-0811-11e7-9af6-6fe0a678b333.png)

\TabSRMM\src\chat_main.cpp, line 102:
![2017-03-13 17_12_38-d__dev_miranda-ng_plugins_tabsrmm_src_chat_main cpp - notepad administrator](https://cloud.githubusercontent.com/assets/5046855/23858067/5d00a704-0810-11e7-850a-40b0ad9e5e9f.png)
double _if (si->pDlg)_ is useless.

\TabSRMM\src\themes.cpp:
![2017-03-13 17_22_30-d__dev_miranda-ng_plugins_tabsrmm_src_themes cpp - notepad administrator](https://cloud.githubusercontent.com/assets/5046855/23858499/ae6c16e0-0811-11e7-8684-9d474c034160.png)
no sense to assign _data_ twice

**Comment by georgehazan** [comment]
previously they were different, cause they used different IDC_*
now all control ids are synced & these ifs() lost any sense, you're right
