### ISSUE TITLE
Statusbar ghost in Scriver

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#764]
- disable statusbar in Scriver
- open **miranda-ng** conference
- open **miranda-ng-int** conference and close this tab (via right click menu)

Result: blank statusbar appears at previous (**miranda-ng**) tab

**Comment by Robyer** [comment]
@dartraiden Please add "regression" label for issues which are caused by some recent changes (i.e. it works in stable but is broken in development builds). As I expect all these new tabsrmm/scriver issues are caused by ghazan's recent changes.
