### ISSUE TITLE
Broken colors in TabSRMM niclkist when IRC reconnects

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#769]
Reported by **person**

- enable colored nicks in TabSRMM chats
- join some IRC channel
- drop your Internet connection (in OS) and reenable it
- reconnect to IRC

Colors are broken (see screenshots before and after):

![unspecified](https://cloud.githubusercontent.com/assets/5046855/24081131/ed69bebe-0cbd-11e7-8e61-681c3f1946b1.png)

![unspecified](https://cloud.githubusercontent.com/assets/5046855/24081137/0551b036-0cbe-11e7-8877-675423b4c225.png)

**Comment by LittleVulpix** [comment]
This also affects Discord so I suspect it's related to groupchats in general rather than just irc, @dartraiden

**Comment by watcherhd** [comment]
@LittleVulpix no such behavior in XMPP chats.

**Comment by LittleVulpix** [comment]
Interesting, so discord and IRC then.
