### ISSUE TITLE
[vk][feature] voice messages

### ISSUE THREAD

**Issue by devcline** [miranda-ng/miranda-ng#771]
It is even possible?

**Comment by ElzorFox** [comment]
No. VK api not supported it.

**Comment by MikalaiR** [comment]
It is possible, but it's not a official way.
http://ru.stackoverflow.com/a/609941/210145

**Comment by devcline** [comment]
Its just a simple audio file . 
To start a subject dev: Any way to add a support to listen a audio voice files or songs?
