### ISSUE TITLE
[OpenSSL] Crash while running any 8bit depth/256 colors games [Reproducible but at the same time Heisenbug]

### ISSUE THREAD

**Issue by FIGGERNAGGOT** [miranda-ng/miranda-ng#782]
Affects all miranda-ng versions, from old stable ones up to newest development ones.
Keeps happening only with OpenSLL + libeay32/ssleay/ssleay32/whatever other components are required.
Confirmed affected games [happens in single player, no network component interference at all!] - Age of Empires 2 non-hd, Total Annihilation [any version, retail, demo, steam, GoG], probably all other apps that switch desktop color mode to 256 colors for their running time.
Narrowed it down to being desktop color related crash by having Voobly patch for Age of Empires 2 which allows user to select to run game either in original 256 colors scheme [**always** crashes Miranda with OpenSSL loaded] or in 32bit color directdraw mode [**never** crashes Miranda w/ OpenSSL]

However the issue is - Crash doesn't happen while running development version **with debug symbols**, running same versions without debug symbols does crash it - hence I gave it Heisenbug tag in title.

Currently running OpenSSL 1.0.2 .dll paired with ssleay/ssleay32/libssl32 1.0.2.3 [I believe that is the newest available since 1.1.0+ versions don't use update these libraries at all since OpenSSL team decided to switch focus to new LibSSL-1-1.dll's that are not backwards compatible, just in case I have them in my Miranda's Libs folder as well]
Already tried different OpenSSL precompiled dll's sources - including official ones, the ones that run without MSVC redist dependencies and so on - it keeps crashing regardless.

I am in possession of microsoft crashdumps for miranda - .hdmp and .mdmp files
`EventType : BEX     P1 : miranda32.exe     P2 : 0.95.6.18009     P3 : 58ddd54f
P4 : libeay32.mir     P5 : 1.0.2.12     P6 : 58a5cf97     P7 : 0006b3ef     
P8 : c0000409     P9 : 00000000     `
I can upload these however I'd want first confirmation of any dev that it is safe to drop them here - I am concerned whenever these dumps could contain passwords/credentials for protocols I'm using.
And if so, I could attempt to set up new dummie profile with some useless account for that purpose.

Full version info [https://pastebin.com/h38d8acf](https://pastebin.com/h38d8acf) - I'm pretty sure it happens at win7 sp1 /w OpenSSL plugin as well, since I've got dual boot I can test that as well on request.
Sorry for chaotic report but I'm typing on small screen and Github's gui doesn't scale too well.
Let me know whenever I should add anything to the report or test anything out.

**Comment by dartraiden** [comment]
BTW: development version doesn't need external OpenSSL, it's already merged into the core.

**Comment by FIGGERNAGGOT** [comment]
@dartraiden But I have those already [http://i.imgur.com/c68EDjQ.jpg](http://i.imgur.com/c68EDjQ.jpg)

**Comment by georgehazan** [comment]
1. you need to remove libeay32.dll / ssleay32.dll
be sure that your StdSsl.dll is linked to libeay32.mir / ssleay.mir
2. we need a crash dump made by CrashDumper plugin
3. debug symbols never affect the program execution unless the debugger takes control over it

**Comment by dartraiden** [comment]
Closed in favor of #930
