### ISSUE TITLE
[libtox+OpenSSL] - crash on logon in "emmintrin.h (1268): blockmix_salsa8"

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#783]
[libtox+OpenSSL] - crash on logon in "emmintrin.h (1268): blockmix_salsa8".
Seems crypted tox profile
Crashlog: 
[miranda_libtox_blockmix_salsa8_20170401.zip](https://github.com/miranda-ng/miranda-ng/files/1033890/miranda_libtox_blockmix_salsa8_20170401.zip)

```
Exception: Access Violation at address 13DF2F07. Reading from address FFFFFFFF.

Stack Trace:
---------------------------------------------------------------
13DF2F07 (libtox 13D60000): \usr\lib\gcc\i686-w64-mingw32\4.9-win32\include\emmintrin.h (1268): blockmix_salsa8

```

**Comment by dartraiden** [comment]
Closed in favor of #930
