### ISSUE TITLE
Build 18063: Messaging windows are suddenly tabbed

### ISSUE THREAD

**Issue by sagamusix** [miranda-ng/miranda-ng#795]
I use StdMsg with one window per contact. After upgrading to build 18063, the default window size of the chat window has resized itself to a really tiny size and all contacts end up in the same window, separated into tabs.

**Comment by georgehazan** [comment]
yes, now groupchats share the same container with the private chats. you can disable tabbed interface in Options - Message sessions - Tabs

**Comment by sagamusix** [comment]
Okay. But when upgrading to the new version, it would be good if old settings were translated into new settings so that users don't have to recofingure the application while the application could do it by itself.

**Comment by georgehazan** [comment]
that's precisely what happened. cause tabs existed previously only in StdChat, these settings were imported from the chat engine.
