### ISSUE TITLE
Build 18063: Contact windows no longer flashing

### ISSUE THREAD

**Issue by sagamusix** [miranda-ng/miranda-ng#797]
Here's another one. :)
My StdMsg contact windows no longer flash when a new message arrives, despite the flash count being set to 5.

**Comment by leecher1337** [comment]
Message windows now flash even though they are open and have an active focus, which is quite annoying, as it looks like they are losing and gaining focus again while in window.
Should only flash when in background, I suppose? Never had this annoying flashing before and didn't change anything in my settings.

**Comment by sagamusix** [comment]
In addition, it seems like the window now stops being highlighted after flashing, it returns to normal state.

**Comment by sagamusix** [comment]
Window still remains in non-flashed state after flashing the configured amount of times. It's very easy to miss incoming messages.

**Comment by sagamusix** [comment]
This has been broken for a really long while now. The window always flashes (no matter if window is focussed or not) but then goes back to normal state (not highlighted) afterwards. The related issue #808 also remains broken.

**Comment by georgehazan** [comment]
test it on the next build, it should work

**Comment by sagamusix** [comment]
Confirmed to be finally fixed. Thanks a lot!

**Comment by georgehazan** [comment]
![image](https://user-images.githubusercontent.com/4628541/28069854-977c8e38-6653-11e7-98c2-20dc716f85b9.png)
