### ISSUE TITLE
CloudFile: Dropbox problem

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#806]
After Dropbox uploading blank string goes to chat and to clipboard. Instead of URL.

**Comment by watcherhd** [comment]
watcher, 26/04/2017 11:24:27:
значит так, по клаудфайлу

watcher, 11:24:38:
на аплоуде уандрайва валится

watcher, 11:24:39:
https://pastebin.com/JFUtB1cJ

watcher, 11:25:02:
на аплоуде дропбокса вставляет в лог пустую строку вместо ссылки

watcher, 11:25:18:
в метаконтакт слать не хочет

watcher, 11:25:57:
https://i.imgur.com/6MtEfG7.png

watcher, 11:26:27:
https://i.imgur.com/knFNKcW.png
