### ISSUE TITLE
Facebook: timeout error even when message is sent

### ISSUE THREAD

**Issue by Goraf** [miranda-ng/miranda-ng#807]
from conference room:
>  Ja.Ba.: on facebook , when i write message Miranda pop up a error "it didn't send properly"  but when i check it on website it was send ok 
> before it was rare , now it is much often than before
>  Ja.Ba.: "Timeout when sending message."
>  	Ja.Ba.: yet, on facebook it was send
>  	Ja.Ba.: and it starting to be very annoying , every 3-4. mesage pop up this error

Also described here:
1. http://forum.miranda-ng.org/index.php?topic=192.msg19589#msg19589
2. http://forum.miranda-ng.org/index.php?topic=192.msg19590#msg19590
3. http://forum.miranda-ng.org/index.php?topic=5172.msg19585#msg19585

**Comment by Robyer** [comment]
I really hope it is caused by some recent changes in Core, because otherwise I am completely clueless about what is wrong (because in Miranda it ends up just with "request timeout" - even though it is sent correctly).

So it would be good if someone could check it with older Miranda builds (perhaps last stable should be enough). I'm bit busy these days.

**Comment by Goraf** [comment]
Netlib reports "SSL Server signaled SSL Shutdown" with almost every sent message. Is it ok?
And rarely there is also "SSL failure recieving data (10053)":

> WSAECONNABORTED (10053)
> 
> Translation: Software caused connection abort.
> Description: An established connection was stopped by the software in your host computer, possibly because of a data transmission time-out or protocol error.

**Comment by Robyer** [comment]
I don't think that's ok.
Can you try it in stable if it behave differently? (I'm not even using Miranda lately)
Either it's caused by some change in the core, or it's some change on FB and it might be related to persistent connection that I use in plugin.

**Comment by Goraf** [comment]
The same shutdowns reported in stable. I wasn't lucky enough to catch timeout error in stable ver but in dev it reports no response from server so it's probably in that direction.

**Comment by Robyer** [comment]
So in dev version it shows the problem every few messages, but on stable it has not happened for you yet? Hmm...

**Comment by Goraf** [comment]
Not exactly that. I do not experience timeout error as often as other users mentioned. Sometimes there is one or few of them within hours. So I didn't have opportunity to catch it in stable version. But the "server shutdown" entries happens every few messages in stable and in dev version.

**Comment by Robyer** [comment]
Perhaps this change?
https://github.com/miranda-ng/miranda-ng/commit/b0b0b090cbec03d92e803612d2eced7d85ebf486
