### ISSUE TITLE
[Discord] If a contact removes you from their contact list, miranda silently and deletes all contact data

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#812]
With other protocols (i.e. steam, skype, tox, etc), when a user removes you from their contact list, they will appear offline to you, but you will still see their contact and you can browse the history.

With Discord, miranda **silently (without prompt) deletes all related user data - histories and contact metadata from db**

Miranda should instead keep the user and set them as hidden. Additionally, if possible, Miranda should warn the user that they have been removed (by whom) from their contact list - like it does in Steam protocol.

**Comment by Robyer** [comment]
Note: It's probably here https://github.com/miranda-ng/miranda-ng/blob/master/protocols/Discord/src/dispatch.cpp#L169

**Comment by LittleVulpix** [comment]
@georgehazan this would be really appreciated; I just had to rescue some history because a friend accidentally removed everyone thinking he was just removing shortcuts.

**Comment by LittleVulpix** [comment]
@georgehazan once again... you know? :p please?

**Comment by dartraiden** [comment]
https://github.com/miranda-ng/miranda-ng/issues/2994
