### ISSUE TITLE
[Automatic Backups] Increase maximum number of backups past 100

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#813]
When storage space becomes less important than data it holds, backups should allow the user to specify a higher number of past backup retention.

In the case of Automatic Backups - if set to one hour, then 100 holds only about four days of backup. The user should be able to decide whether or not to store more rather than being limited by an arbitrary integer.

The backup count should be increased significantly and leave it up to the user to decide if that's a good or a bad idea.

8760hrs = 1 year

Should be a simple thing to do, hopefully.

**Comment by LittleVulpix** [comment]
Perhaps https://github.com/miranda-ng/miranda-ng/blob/master/plugins/Db_autobackups/src/options.cpp#L153 ?

**Comment by Mataes** [comment]
max number changed to 9999
