### ISSUE TITLE
Plugin Updater is broken after zlib update

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#818]
"An error occurred while checking for new updates."

**Comment by LittleVulpix** [comment]
@dartraiden I believe @georgehazan removed the update file (hashes.zip) from dist to pause updates until an issue is resolved. The error you are seeing is because of the 404 response that plugin updater does not expect.

**Comment by White-Tiger** [comment]
why didn't he use an older one?
Otherwise, might it be a good idea to implement such an special case? Like outputting an

> Server is currently down for maintenance

in case of an 404. This is likely quite acceptable even if the project goes down at some point.

**Comment by LittleVulpix** [comment]
My first thought was some other issue occurred since I've seen this.

I agree, something like "server is down for maintenance" implementation would be nice to have!

**Comment by dartraiden** [comment]
>> The error you are seeing is because of the 404 response that plugin updater does not expect.

You can try to switch from nightly to stable and see the error. "An error occurred while checking for new updates." is common error regardless of the cause of failure.

**Comment by georgehazan** [comment]
>why didn't he use an older one?
because there's no older one. the goal is to block updates to prevent the broken zlib distribution

**Comment by dartraiden** [comment]
Yes, an older update is overwritten with a newer one on the server.

**Comment by dartraiden** [comment]
Zlib has been reverted.
If you on build 18181 - you need redownload Miranda32/64, Core, Libs and all plugins.
And also кe-enter the passwords of all protocols (I do not know why the zlib rollback turns passwords into "buggy resident".

- вводим заново пароли протоколов (одному богу известно, как они связаны с проблемной библиотекой zlib, но они слетают в базе)
