### ISSUE TITLE
[SteamWeb] Sent messages appear twice

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#819]
A very strange issue. With no miranda restart or change of any kind, steam messages started being sent twice. **I assume some change occurred on steam api side.**

Tested with a clean profile too, happens as well.

The contact actually only sees the message once so it is only a problem on miranda side.

**Comment by LittleVulpix** [comment]
And it's now working normally again. I don't know what happened there... but seems it got fixed.

**Comment by Robyer** [comment]
I think there is already some issue for this (or was it closed already?), that this happens because polling thread somehow starts twice. Perhaps it is triggered by some error or relogin? But this must be fixed and so some issue should exist about this.

**Comment by LittleVulpix** [comment]
@Robyer No, this was different. I tried on different computers and with a completely clean miranda profile as well. It just started on its own during an active conversation without me logging out and ended 3 hours later with nothing else happening. I think it was something over on valve's end.

**Comment by Robyer** [comment]
@LittleVulpix Oh. If that happens again, it would be great to have Fiddler log of that :)
