### ISSUE TITLE
Facebook: Don't show "preview text" for incoming URLs

### ISSUE THREAD

**Issue by culinko** [miranda-ng/miranda-ng#824]
Hello there :) I asked Robyer about this on Twitter the other day and he sent me here, so creating a ticket for it. The issue is following:

Often when I receive a message with URL in Facebook RM, the message has an additional description which looks like some kind of a preview for the link (Facebook adds this there very often). I would like to request an option to strip this additional info from the message and only show the link (and text if user sent text too).

I am not sure if Facebook still divides it to link/photo/sticker, so I am attaching a screenshot for all of them just in case. If it's possible, it would be great if you could strip the additional info from photo/sticker messages as well. I suppose (if implemented) this would work only for the future messages and not the ones I already received, correct?

I am using Facebook RM + TabSRMM, the screenshot below is from History++. I can attach more info later if it will be needed. Here is the screenshot for each of the events in question: http://i.imgur.com/1vHjlEq.png (for some strange reason some contacts have been renamed to "Facebook (website)" as of today, I can create a ticket for that if needed).

**Comment by Robyer** [comment]
> I suppose (if implemented) this would work only for the future messages and not the ones I already received, correct?
Yes. Perhaps I should save more info in DB and give preference to user how to show it - that would be more robust, but will take more space in database (but that shouldn't be a big problem I guess).

> for some strange reason some contacts have been renamed to "Facebook (website)" as of today, I can create a ticket for that if needed
Please check if that works the same in clean profile, because it sounds more like some profile corruption. But if it's really a FB plugin problem, please create new issue.

**Comment by culinko** [comment]
>Please check if that works the same in clean profile, because it sounds more like some profile corruption. But if it's really a FB plugin problem, please create new issue.

Strangely, I tried disconnecting + reconnecting and the issue persisted, but restarting Miranda fixed the issue. I guess it was just some kind of fluke :)

**Comment by dartraiden** [comment]
Seems like this is not actual for new FB protocol...
