### ISSUE TITLE
Перевод пункта "Главное меню"

### ISSUE THREAD

**Issue by jawhien** [miranda-ng/miranda-ng#828]
При использовании плагина clist blind название пункта "главное меню" даже при установленых переводах остаётся на английском языке.

**Comment by dartraiden** [comment]
Если речь о "Главном меню", которое в меню иконки в трее, то на ночнике оно переведено.

**Comment by dartraiden** [comment]
Если речь о каком-то другом меню, то как до него добраться?

**Comment by jawhien** [comment]
Речь об иконке, которая в окне списка контактов. Если необходимо, могу сделать скрин.

**Comment by dartraiden** [comment]
Было бы здорово, потому что в clist blind у меня иконок нет...

**Comment by jawhien** [comment]
Прошу прощение, не было возможности написать ранее. сейчас постараюсь подробно всё описать. всё дело в том, что я пользуюсь программой чтения с экрана, по этому мне сложно сделать нормальный скрин. скорее всего там графическая иконка, однако в свойствах объекта есть текст, который передаётся программе чтения с экрана, текст следующий: "main menu". доступ к этому меню осуществляется с помощью клавиши "ALT" в списке контактов. Вот именно в этом меню есть два пункта: "main menu" и "статус".

**Comment by dartraiden** [comment]
В качестве списка контактов используется clist_blind?

**Comment by dartraiden** [comment]
Да, там в clist_blind было какое-то меню (я его ещё пытался вырезать, а оказалось, что оно нужно). Окей, поищу в ресурсах.

**Comment by dartraiden** [comment]
```
IDR_CLISTMENU MENU 
BEGIN 
	POPUP "&Main menu" 
	BEGIN 
		MENUITEM SEPARATOR 
		MENUITEM "E&xit",                       ID_ICQ_EXIT 
	END 
	POPUP "&Status" 
	BEGIN 
		MENUITEM "&Offline\tCtrl+0",            ID_STATUS_OFFLINE, CHECKED 
		MENUITEM "On&line\tCtrl+1",             ID_STATUS_ONLINE 
		MENUITEM "&Away\tCtrl+2",               ID_STATUS_AWAY 
		MENUITEM "&Not available\tCtrl+3",      ID_STATUS_NA 
		MENUITEM "Occ&upied\tCtrl+4",           ID_STATUS_OCCUPIED 
		MENUITEM "&Do not disturb\tCtrl+5",     ID_STATUS_DND 
		MENUITEM "&Free for chat\tCtrl+6",      ID_STATUS_FREECHAT 
		MENUITEM "&Invisible\tCtrl+7",          ID_STATUS_INVISIBLE 
		MENUITEM "On the &phone\tCtrl+8",       ID_STATUS_ONTHEPHONE 
		MENUITEM "Out to &lunch\tCtrl+9",       ID_STATUS_OUTTOLUNCH 
	END 
END
```

Интересно, что оно переведено, но, получается, перевод не подхватывается

```
[&Main menu]
&Главное меню
[E&xit]
Вы&ход
[&Status]
&Статус
```

**Comment by jawhien** [comment]
Да. именно он. Меню и правда это весьма нужно )))

**Comment by jawhien** [comment]
вот в том и дело, я обратил внимание, что в переводе это есть, и в меню иконки в трее подхватывается нормально, а тут, почему-то нет

**Comment by dartraiden** [comment]
Как вариант, можно эту иконку (типа "гамбургера" из трех полосок) заменить на текст, который уже будет нормально переводиться.

**Comment by jawhien** [comment]
думаю хороший вариант, т.к., всё равно скринридер не читает иконки, а только текст, а контакт лист изначально под программы экранного доступа и делался, что и в названии указано

**Comment by dartraiden** [comment]
Открыл конкретную задачу на английском. Если у кого-то из программистов будет время - посмотрят.

#863
