### ISSUE TITLE
SkypeWeb can't login

### ISSUE THREAD

**Issue by stiv-sigmal** [miranda-ng/miranda-ng#829]
After update from 95.5 stable to build 18181 (I'm lucky to decide update to unsable on this build) and upper SkypeWeb can't login with netlog like
`[21:39:26 095C] [SKYPE_1] (01B495F0:856) Data received`
`{}`
`[21:39:26 095C] [SKYPE_1] (01B495F0:856) Connection closed internal`
`[21:39:26 095C] [SKYPE_1] (01B495F0:4294967295) Connection closed`
Rollback to stable (via PluginUpdater) make SkypeWeb to login normally. Update to latest unstable break it.

In jabber conference on may 16 someone told about same problem.

В общем, на форуме и в конференции пара-тройка подробных нетлогов. И тишина.

**Comment by LittleVulpix** [comment]
Skypeweb is working on the latest unstable; you may have to reset and reenter the passwords as they became corrupted due to this bad build. Check http://www.miranda-ng.org/en/news/Zlib%20has%20been%20reverted.

**Comment by stiv-sigmal** [comment]
Nope. First time I reverted miranda from backup (including profile), and now update and rollback via PU.
And if it would be corrupted, it wouldn't login on rollback to stable, but it do.

**Comment by georgehazan** [comment]
@LittleVulpix the fact that on your installation Skypeweb works ok means actually nothing, because it works over the cached token. this problem rises only when you try to refresh the token

**Comment by Corak667** [comment]
@stiv-sigmal if you had Skype account connected to MSN(Microsoft live mail) - you now should use your Live.com password. They seems disabled skype-only account passwords, replacing it with M$.

**Comment by stiv-sigmal** [comment]
@Corak667, how it depends from version of skypeweb plugin?

**Comment by georgehazan** [comment]
it doesn't depend on a version, MS just published a notice about it at their site, about a week ago

**Comment by stiv-sigmal** [comment]
Просто я описал, что у меня стабильная ветка работает нормально, а ночник нет. Причём, переход от одной ветки к другой **и обратно** делаю плагин-апдейтером, т.е. если что-то портится в профиле, то при возврате оно работать не должно.
А в ответ мне пишут про пароль. Неоднократно, хоть и под разными соусами.
Вот я и спрашиваю, как пароль зависит от версий.

Задумываюсь о том, чтобы заново завести скайповые учётки, но не хочется возиться с историей.

Кстати, плагин-апдейтер при возврате к стабильной забывает удалить что-то из Libs\*.mir, миранда при старте жалуется, что порядковый номер не найден в библиотеке. Я лишний файл вручную удалил.

**Comment by dartraiden** [comment]
Предполагается, что возврат на стабильную целиком на страх и риск пользователя, и он сам разрулит. Бывают случаи, что возврат вообще невозможен (например, поменялся формат базы).
