### ISSUE TITLE
Facebook: Group chats - Names broken / error pop ups upon message receipt

### ISSUE THREAD

**Issue by BlackCatte** [miranda-ng/miranda-ng#833]
Upon receiving every message in a group chat, I get this pop up error:
![img](http://i.imgur.com/gS9sDi6.png)
Members in a group chats don't show in members list (displays 0 users in chat in title bar). Names of users are not displayed either, instead only the string of numbers associated with their FB account is displayed.

**Comment by ThosRTanner** [comment]
I get a similar (ish) issue where the group chats pop up but only with a numeric ID and no members. The actual user names seem to be ok

**Comment by Robyer** [comment]
See my comment here: See my comment here: http://forum.miranda-ng.org/index.php?topic=192.msg19915#msg19915

**Comment by ThosRTanner** [comment]
Must be something new facebook are doing. It started working again today for no apparent reason.

**Comment by Robyer** [comment]
@BlackCatte Do you still have the same problem?

**Comment by BlackCatte** [comment]
@Robyer Yes, the problem never stopped occurring for me, not even briefly

**Comment by Robyer** [comment]
@BlackCatte If you are willing to borrow me your account for debugging, I can look at it tomorrow. You can contact me over Facebook - www.facebook.com/robyer

**Comment by Robyer** [comment]
@BlackCatte - http://forum.miranda-ng.org/index.php?topic=192.msg19931#msg19931

**Comment by georgehazan** [comment]
should have been fixed
