### ISSUE TITLE
MSN+TabsRMM: duplicated Skype chat rooms exit finally causes crash in chat_log.cpp (953): CChatRoomDlg::StreamInEvents"  and "msn_chat.cpp (232): CMsnProto::MSN_GCProcessThreadActivity"

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#843]
When someone calls you in real Skype app, and then adds some people to the call - it autocreates new temporary chat room named as people names/nicks list. If this call process repeated (someone calls and adds the same people) and room had the same people there - the room just re-created and no duplication in Skype, but MSN plugin creates duplicates of room (empty ones) there, and if you exit one (in miranda), you need to restart miranda to exit another duplicates..
  
Also - if you try to remove/delete such chats from contact list - it reports that you database are damaged
 
![470b360469ca](https://user-images.githubusercontent.com/5046855/27731589-52faa102-5d96-11e7-818d-a6044963dc98.png)

And exits miranda.

Also - you cannot disable autoopening dialog windows of MSN/Skype Chats even if it was disabled in Dialogs/Chats "Don't open chat windows on room entering". Please fix it.

Finally it can cause such rare crash when there's only 2 rooms left:

```
Likely cause of the crash plugin: TabSRMM

Exception: Access Violation at address 16E26D9A. Reading from address 00000006.

Stack Trace:
---------------------------------------------------------------
16E26D9A (TabSRMM 16DE0000): c:\sources\miranda_ng_compilation\plugins\tabsrmm\src\chat_log.cpp (953): CChatRoomDlg::StreamInEvents
12432856 (mir_app 12420000): c:\sources\miranda_ng_compilation\src\mir_app\src\srmm_base.cpp (701): CSrmmBaseDialog::AddLog
12472D74 (mir_app 12420000): c:\sources\miranda_ng_compilation\src\mir_app\src\chat_svc.cpp (566): Chat_Event
15FDD407 (MSN 15FC0000): c:\sources\miranda_ng_compilation\protocols\msn\src\msn_chat.cpp (232): CMsnProto::MSN_GCProcessThreadActivity
15FDBB09 (MSN 15FC0000): c:\sources\miranda_ng_compilation\protocols\msn\src\msn_commands.cpp (969): CMsnProto::MSN_HandleCommands
15FC73C3 (MSN 15FC0000): c:\sources\miranda_ng_compilation\protocols\msn\src\msn_threads.cpp (240): CMsnProto::MSNServerThread
15FC6CFB (MSN 15FC0000): c:\sources\miranda_ng_compilation\protocols\msn\src\msn_threads.cpp (459): CMsnProto::ThreadStub
125C7F67 (mir_core 125C0000): c:\sources\miranda_ng_compilation\src\mir_core\src\threads.cpp (159): forkthreadex_r
76B8338A (kernel32 76B70000): (filename not available) (0): BaseThreadInitThunk
77179F72 (ntdll 77140000): (filename not available) (0): RtlInitializeExceptionChain
77179F45 (ntdll 77140000): (filename not available) (0): RtlInitializeExceptionChain
125C7F3E (mir_core 125C0000): c:\sources\miranda_ng_compilation\src\mir_core\src\threads.cpp (284): Thread_Wait
0018F3EC ((module-name not available) 00000000): (filename not available) (0): (function-name not available)

```
Crashlog:
[Miranda_crash_MSN-TabsRMM_chat_dup_20170611.zip](https://github.com/miranda-ng/miranda-ng/files/1066391/Miranda_crash_MSN-TabsRMM_chat_dup_20170611.zip)

**Comment by Corak667** [comment]
Also if there is duplicated chat contacts and it autoopens, and you will press ESC in contact list - all contacts will became invisible, and you cannot search for them (zero list, only folders). Have to restart miranda to get contacts back.

**Comment by dartraiden** [comment]
Protocol is deprecated.
