### ISSUE TITLE
Random crash after "kick" event (Jabber MUC)

### ISSUE THREAD

**Issue by Deadooshka** [miranda-ng/miranda-ng#847]
[crash20170612130525.txt](https://github.com/miranda-ng/miranda-ng/files/1070789/crash20170612130525.txt)

**Comment by Deadooshka** [comment]
some related random crashes after deleting jabber muc rooms:
[crash20170619231105.txt](https://github.com/miranda-ng/miranda-ng/files/1092899/crash20170619231105.txt)
[crash20170619231125.txt](https://github.com/miranda-ng/miranda-ng/files/1092897/crash20170619231125.txt)
[crash20170619202027.txt](https://github.com/miranda-ng/miranda-ng/files/1092898/crash20170619202027.txt)
[crash20170619135312.txt](https://github.com/miranda-ng/miranda-ng/files/1092900/crash20170619135312.txt)
[crash20170621235006.txt](https://github.com/miranda-ng/miranda-ng/files/1092901/crash20170621235006.txt)
[crash20170621231524.txt](https://github.com/miranda-ng/miranda-ng/files/1092902/crash20170621231524.txt)
[crash20170621231553.txt](https://github.com/miranda-ng/miranda-ng/files/1092903/crash20170621231553.txt)
[crash20170621231605.txt](https://github.com/miranda-ng/miranda-ng/files/1092904/crash20170621231605.txt)
[crash20170621231529.txt](https://github.com/miranda-ng/miranda-ng/files/1092905/crash20170621231529.txt)

**Comment by georgehazan** [comment]
when you're kicked or you kick someone?

**Comment by georgehazan** [comment]
crashes with RtlFree() are not related to this problem

**Comment by Deadooshka** [comment]
@georgehazan I get it with multiple action "enter a MUC + kick myself with another account or xmpp-bot". Also sometimes when trying to reopen destroyed muc.

**Comment by Deadooshka** [comment]
@georgehazan 
[crash20171109081647.txt](https://github.com/miranda-ng/miranda-ng/files/1456376/crash20171109081647.txt)
[crash20171109080853.txt](https://github.com/miranda-ng/miranda-ng/files/1456377/crash20171109080853.txt)
you may reproduce it here: testing@conference.jabber.ru. Type "kick" or "пинок" and re-enter the room after the kick. Repeat the procedure until the Miranda crashes.

**Comment by dartraiden** [comment]
Probably fixed. Cannot reproduce even after 20 kicks.
