### ISSUE TITLE
MailRu: периодически при каждой новой авторизации аккаунта - оповещение от Каждого из списка друзей, что он якобы только что добавился

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#848]
MailRu: периодически при каждой новой авторизации аккаунта - оповещение от Каждого из списка друзей, что он якобы только что добавился. Как повторить, не знаю, но уже два раза такой ад. Если очень много друзей в mail.ru контактах - то будет сотня оповещений о добавлении в друзья. Сейчас воспроизвелось - отключил аккаунт в менеджере аккаунтов, потом снова включил

![cmfvxack](https://user-images.githubusercontent.com/5046855/27233115-1a0b2018-52c1-11e7-8620-823c19328937.png)

Оповещение "статус невидимости изменился"

![cmfvxacn](https://user-images.githubusercontent.com/5046855/27233140-250d7074-52c1-11e7-9752-f7612ae025f0.png)

**Comment by dartraiden** [comment]
MRA is deprecated.
