### ISSUE TITLE
Vkontakte: удаленные с сайта или временно забаненные сайтом друзья начинают дублироваться как "неизвестный контакт" и просто дублироваться.

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#849]
При каждой авторизации Vk - иногда может произойти оповещение, что "пользователь удален", а также сами удаленные пользователи дублируются,причем по неколько раз

![cmfvxacl](https://user-images.githubusercontent.com/5046855/27233064-eaccdea4-52c0-11e7-9849-9720b2016adc.png)

![cmfvxacm](https://user-images.githubusercontent.com/5046855/27233071-f0022e38-52c0-11e7-8918-f67509c770bf.png)

Лист снова и снова забивается неизвестными контактами

**Comment by ElzorFox** [comment]
Прогони базу дбчекером в агрессивном режиме.
Если после этого баг повторится, то нужен будет нетлог и скриншоты протокольных веток в дбэдиторе у одного неизвестного контакта и двух контактов-дублей.

**Comment by Corak667** [comment]
@ElzorFox прогонял базу в агрессивном режиме - ошибок не находит вообще. Дубли удалял руками, несколько раз повторялось в тот момент, но сейчас вроде пока нормально.

**Comment by ElzorFox** [comment]
not confirmed and not relevant in the current release
