### ISSUE TITLE
Emoji not displayed

### ISSUE THREAD

**Issue by inuyaksa** [miranda-ng/miranda-ng#852]
I have installed this smiley pack with full list of emojis for Facebook/Hangout:
http://www.miranda-ng.org/distr/addons/Smileys/Facebook/

On Window 10 stop working after creator update (I think), before It works well.

I can use "simple" emojis as :D :) 
other emojis as 😭😤 has not displayed.
It adds emoji into text then is like a "blank" character, It seems correct as I can copy-and-paste, It's a realt utf8 character, but tabsrmm can't display.

I use dev win 10 64bit release.  

```
Microsoft Windows 10 Professional Edition, 64-bit (build 15063)
OS Languages: (UI | Locale (User/System)) : English/English | English/English

Miranda NG Version: 0.95.6 alpha build #18228 (5c191ef54d) x64
Build time: 20 Jun 2017 4:10:24

Active Plugins (23):
¤ AdvaImg.dll v.0.11.0.2 [20 Jun 2017 4:07:04] - Miranda image services 
¤ AIM.dll v.0.11.0.1 [20 Jun 2017 4:06:00] - AIM protocol 
¤ AuthState.dll v.0.0.2.1 [20 Jun 2017 4:06:16] - Authorization state 
¤ AVS.dll v.0.95.3.4 [20 Jun 2017 4:05:46] - Avatar service 
¤ Clist_modern.dll v.0.9.1.5 [20 Jun 2017 4:07:36] - Modern contact list 
¤ CrashDumper.dll v.0.0.5.2 [20 Jun 2017 4:07:44] - Crash dumper 
¤ Dbx_mmap.dll v.0.95.3.1 [20 Jun 2017 4:05:48] - Miranda NG mmap database driver 
¤ Facebook.dll v.0.3.3.2 [20 Jun 2017 4:07:20] - Facebook RM 
¤ Fingerprint.dll v.0.1.0.0 [20 Jun 2017 4:08:20] - Fingerprint NG 
¤ GG.dll v.0.11.0.3 [20 Jun 2017 4:06:14] - Gadu-Gadu protocol 
¤ ICQ.dll v.0.11.3.5 [20 Jun 2017 4:06:08] - IcqOscarJ protocol 
¤ Import.dll v.0.95.4.3 [20 Jun 2017 4:05:46] - Import contacts and messages 
¤ IRC.dll v.0.11.0.3 [20 Jun 2017 4:06:04] - IRC protocol 
¤ Jabber.dll v.0.11.0.4 [20 Jun 2017 4:06:40] - Jabber protocol 
¤ MSN.dll v.0.14.0.1 [20 Jun 2017 4:06:20] - MSN protocol 
¤ PluginUpdater.dll v.0.1.2.5 [20 Jun 2017 4:07:54] - Plugin updater 
¤ Popup.dll v.2.1.1.12 [20 Jun 2017 4:06:48] - Popup plus 
¤ Restart.dll v.0.0.6.0 [27 Sep 2016 16:46:18] - Restart 
¤ SmileyAdd.dll v.0.2.4.1 [20 Jun 2017 4:07:02] - SmileyAdd 
¤ TabSRMM.dll v.3.5.0.4 [20 Jun 2017 4:06:04] - TabSRMM 
¤ TooltipNotify.dll v.0.7.0.1 [20 Jun 2017 4:06:54] - Tooltip notify 
¤ TopToolBar.dll v.0.8.0.4 [20 Jun 2017 4:07:20] - TopToolBar 
¤ UInfoEx.dll v.0.8.5.0 [20 Jun 2017 4:07:08] - User info ext 

Unloadable Plugins (1):
¤ DbChecker.dll v.0.0.0.0 [20 Jun 2017 4:07:48] - <unknown> 

Icon Packs:
-------------------------------------------------------------------------------
 Fp_icons.dll [20 Jun 2017 4:08:18]
 Proto_AIM.dll [20 Jun 2017 4:07:22]
 Proto_Facebook.dll [20 Jun 2017 4:07:20]
 Proto_GG.dll [20 Jun 2017 4:07:22]
 Proto_ICQ.dll [20 Jun 2017 4:07:22]
 Proto_IRC.dll [20 Jun 2017 4:07:22]
 Proto_Jabber.dll [20 Jun 2017 4:07:22]
 Proto_MetaContacts.dll [20 Jun 2017 4:09:32]
 Proto_MSN.dll [20 Jun 2017 4:07:22]
 TabSRMM_icons.dll [20 Jun 2017 4:08:04]
 Toolbar_icons.dll [20 Jun 2017 4:07:22]
 UInfoEx_icons.dll [20 Jun 2017 4:07:08]
 xStatus_ICQ.dll [20 Jun 2017 4:06:06]
 xStatus_Jabber.dll [20 Jun 2017 4:06:10]
```

**Comment by georgehazan** [comment]
add a screenshot of your SmileyAdd options please.

**Comment by inuyaksa** [comment]
![smileyadd](https://user-images.githubusercontent.com/444506/27325486-f3cda8ea-55a8-11e7-8a80-1cf41281f49c.png)

**Comment by georgehazan** [comment]
![image](https://user-images.githubusercontent.com/4628541/27328321-712805f4-55ba-11e7-9d62-a8d4000d7554.png)

**Comment by georgehazan** [comment]
![image](https://user-images.githubusercontent.com/4628541/27329083-f81de018-55bc-11e7-9115-c00310c2b034.png)

**Comment by georgehazan** [comment]
everything looks ok, tabSRMM + Facebook_full smiley set

**Comment by Robyer** [comment]
Mentioned smileys are different... I haven't uploaded the Facebook_full smileypack to the Github yet.

@inuyaksa You can get full pack from here: http://www.miranda-ng.org/distr/addons/Smileys/Facebook/

**Comment by Robyer** [comment]
@inuyaksa Does these work? http://www.miranda-ng.org/distr/addons/Smileys/facebook_emoji.zip

**Comment by inuyaksa** [comment]
I have changed font, nothing changes.
I have installed 32bit and 64bit versions.

From selector box, it works the first (thumb up) and symbols from 🈶 (include flags).

Emojis don't works seems "blank" characters.

When I type emoji (as : ) ) after press space, sequence becomes correct emoji.

I suspect a local problem, but how can I detect issue?

**Comment by inuyaksa** [comment]
@Robyer I installed your pack, it doesn't works.

**Comment by Robyer** [comment]
Confirmed. It doesn't work for me either.
Some smileys are not showed in TabSRMM's internal log (both single conversations and chats are affected). It works in History++ window though.

I'm using Windows 10 Creators Update too.

@georgehazan Could you please check our chat conversation on Facebook (with Robyer, Vadim, you,...) - the smileys I sent there aren't showed for me in TabSRMM window. You can try it with this smileypack, but probably it affects any smileypack http://www.miranda-ng.org/distr/addons/Smileys/facebook_emoji.zip

**Comment by inuyaksa** [comment]
Tested on Win10 1617 (Anniversary) emojis works as expected.

**Comment by seg-on** [comment]
Hi,
I think, I have same or very similar configuration of OS and Miranda at home and at work.
At home it work properly, at work I have same issue as written in this thread.
Evening I'll exactly compare configuration.

**Comment by seg-on** [comment]
Hi,
this is my versioninfo

**Miranda with working emojis:**

> [spoiler=VersionInfo][quote]CPU: Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz [Intel64 Family 6 Model 58 Stepping 9] [DEP Enabled] [4 CPUs]
> Installed RAM: 12174 MBytes
> Microsoft Windows 10 Professional Edition, 64-bit (build 15063)
> Internet Explorer: 9.11.15063.0 (build 915063)
> Administrator privileges: No
> OS Languages: (UI | Locale (User/System)) : English/English | Slovak/English
> Free disk space on Miranda partition: 190430 MBytes
> 
> Miranda NG Version: 0.95.6 alpha build #18246 (1153d92a13) x64
> Build time: 30 Jun 2017 4:10:24
> Profile: C:\Users\tvanc\AppData\Roaming\Miranda NG\segi\segi.dat (dbx mmap driver)
> Profile size: 19726336 Bytes
> Profile creation date: 16 Jun 2017 21:18:29
> Language pack: Czech (CZ) [0405]
> Service Mode: No
> 
> [b]Active Plugins (26):[/b]
> ¤ AdvaImg.dll v.[b]0.11.0.2[/b] [16 Jun 2017 4:06:50] - Miranda image services 
> ¤ AVS.dll v.[b]0.95.3.4[/b] [16 Jun 2017 4:05:44] - Avatar service 
> ¤ Clist_nicer.dll v.[b]0.9.2.4[/b] [16 Jun 2017 4:06:10] - Clist nicer 
> ¤ Cln_skinedit.dll v.[b]0.0.0.4[/b] [16 Jun 2017 4:06:08] - Skin editor for Clist nicer 
> ¤ CrashDumper.dll v.[b]0.0.5.2[/b] [16 Jun 2017 4:07:34] - Crash dumper 
> ¤ DbEditorPP.dll v.[b]4.0.1.1[/b] [16 Jun 2017 4:07:36] - Database editor++ 
> ¤ Dbx_mmap.dll v.[b]0.95.3.1[/b] [30 Jun 2017 4:05:50] - Miranda NG mmap database driver 
> ¤ Facebook.dll v.[b]0.3.3.2[/b] [25 Jun 2017 4:07:26] - Facebook RM 
> ¤ HistoryPP.dll v.[b]1.5.1.5[/b] [28 Jun 2017 14:22:12] - History++ 
> ¤ HistoryStats.dll v.[b]0.2.1.1[/b] [16 Jun 2017 4:09:46] - HistoryStats 
> ¤ ICQ.dll v.[b]0.11.3.5[/b] [16 Jun 2017 4:06:06] - IcqOscarJ protocol 
> ¤ Import.dll v.[b]0.95.4.3[/b] [16 Jun 2017 4:05:42] - Import contacts and messages 
> ¤ Jabber.dll v.[b]0.11.0.4[/b] [16 Jun 2017 4:06:42] - Jabber protocol 
> ¤ PluginUpdater.dll v.[b]0.1.2.5[/b] [16 Jun 2017 4:07:46] - Plugin updater 
> ¤ Popup.dll v.[b]2.1.1.12[/b] [16 Jun 2017 4:06:42] - Popup plus 
> ¤ QuickSearch.dll v.[b]1.4.2.0[/b] [16 Jun 2017 4:10:26] - Quick Search 
> ¤ SeenPlugin.dll v.[b]5.0.5.3[/b] [16 Jun 2017 4:06:42] - Last seen 
> ¤ SkypeWeb.dll v.[b]0.12.2.4[/b] [16 Jun 2017 4:10:00] - Skype protocol (Web) 
> ¤ SmileyAdd.dll v.[b]0.2.4.1[/b] [20 Jun 2017 4:07:02] - SmileyAdd 
> ¤ SpellChecker.dll v.[b]0.2.6.4[/b] [16 Jun 2017 4:07:40] - Spell checker 
> ¤ StatusManager.dll v.[b]0.11.2.0[/b] [16 Jun 2017 4:10:04] - Status manager 
> ¤ TabSRMM.dll v.[b]3.5.0.4[/b] [30 Jun 2017 4:05:58] - TabSRMM 
> ¤ Tipper.dll v.[b]2.1.0.7[/b] [16 Jun 2017 4:06:50] - Tipper 
> ¤ TopToolBar.dll v.[b]0.8.0.4[/b] [16 Jun 2017 4:07:16] - TopToolBar 
> ¤ UInfoEx.dll v.[b]0.8.5.0[/b] [16 Jun 2017 4:07:00] - User info ext 
> ¤ Weather.dll v.[b]0.4.0.3[/b] [16 Jun 2017 4:08:14] - Weather 
> 
> [b]Unloadable Plugins (1):[/b]
> ¤ DbChecker.dll v.[b]0.0.0.0[/b] [30 Jun 2017 4:07:40] - <unknown> 
> 
> 
> [b]Weather ini files:[/b]
> -------------------------------------------------------------------------------
>  gismeteo.ini v.[b]2012.05.03[/b] [11 Oct 2016 16:18:02] - GisMeteo
>  msn.ini v.[b]2014-11-08[/b] [11 Oct 2016 16:18:02] - MSN Weather (New Layout)
>  weatherxml.ini v.[b]0.0.5.3 2009-07-16[/b] [11 Oct 2016 16:18:02] - WeatherXML
>  wundergrnd_intl.ini v.[b]2011/02/13[/b] [11 Oct 2016 16:18:02] - Weather Underground Int'l
>  wundergrnd_xml.ini v.[b]2011/02/13[/b] [11 Oct 2016 16:18:02] - Weather Underground XML
> 
> [b]Protocols and Accounts:[/b]
> -------------------------------------------------------------------------------
> Facebook                 1 - Enabled 0 - Disabled  Loaded
> ICQ                      1 - Enabled 0 - Disabled  Loaded
> JABBER                   2 - Enabled 2 - Disabled  Loaded
> SKYPE                    1 - Enabled 0 - Disabled  Loaded
> MetaContacts             1 - Enabled 0 - Disabled  Loaded
> SkypeClassic             0 - Enabled 1 - Disabled  Not Loaded
> Weather                  1 - Enabled 0 - Disabled  Loaded
> 
> [b]Icon Packs:[/b]
> -------------------------------------------------------------------------------
>  available.ico [27 Sep 2008 7:04:30]
>  Avonlea Light.icl [21 Mar 2012 18:07:18]
>  away.ico [27 Sep 2008 7:04:54]
>  content.ico [27 Sep 2008 7:05:10]
>  enteredtext.ico [27 Sep 2008 7:05:26]
>  Flags_icons.dll [16 Jun 2017 4:08:38]
>  Fp_icons.dll [29 Mar 2017 4:02:42]
>  gtalk-gmailcoloredballs-v2.dll [7 Sep 2005 23:44:30]
>  HistoryPP_icons.dll [30 Jun 2017 4:07:50]
>  idle.ico [27 Sep 2008 7:05:42]
>  invisible.ico [27 Sep 2008 7:06:00]
>  mobile.old.ico [27 Sep 2008 7:06:54]
>  offline.ico [27 Sep 2008 7:07:24]
>  Proto_AIM.dll [25 May 2015 10:24:34]
>  proto_ball1.dll [4 Sep 2005 16:52:06]
>  proto_conn_facebook.dll [5 Mar 2011 21:37:52]
>  Proto_Facebook.dll [25 Jun 2017 4:07:32]
>  Proto_GG.dll [25 May 2015 10:24:34]
>  proto_gtalk.dll [24 Oct 2012 10:12:26]
>  Proto_ICQ.dll [16 Jun 2017 4:07:14]
>  Proto_IRC.dll [25 May 2015 10:24:34]
>  Proto_Jabber.dll [16 Jun 2017 4:07:14]
>  Proto_MetaContacts.dll [30 Jun 2017 4:09:18]
>  Proto_MSN.dll [25 May 2015 10:24:36]
>  Proto_Skype.dll [16 Jun 2017 4:09:46]
>  Proto_Weather.dll [16 Jun 2017 4:08:10]
>  Proto_Yahoo.dll [25 May 2015 10:24:38]
>  SecureIM_icons.dll [16 Jun 2017 4:08:38]
>  TabSRMM_icons.dll [30 Jun 2017 4:07:54]
>  Toolbar_icons.dll [16 Jun 2017 4:07:18]
>  UInfoEx_icons.dll [16 Jun 2017 4:07:00]
>  xStatus_ICQ.dll [16 Jun 2017 4:06:04]
>  xStatus_Jabber.dll [16 Jun 2017 4:06:04]
>  zoho.dll [2 Feb 2017 18:57:19]
> [/quote][/spoiler]

**Miranda there is issue with emojis:**

> [spoiler=VersionInfo][quote]CPU: Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz [Intel64 Family 6 Model 42 Stepping 7] [DEP Enabled] [4 CPUs]
> Installed RAM: 8127 MBytes
> Microsoft Windows 10 Professional Edition, 64-bit (build 15063)
> Internet Explorer: 9.11.15063.0 (build 915063)
> Administrator privileges: No
> OS Languages: (UI | Locale (User/System)) : Slovak/Slovak | Slovak/Slovak
> Free disk space on Miranda partition: 126894 MBytes
> 
> Miranda NG Version: 0.95.6 alpha build #18247 (d266343091) [running inside WOW64]
> Build time: 3 Jul 2017 4:04:48
> Profile: C:\Program Files\Miranda NG\Profiles\segi\segi.dat (dbx mmap driver)
> Profile size: 19333120 Bytes
> Profile creation date: 30 May 2017 10:34:57
> Language pack: Czech (CZ) [0405]
> Service Mode: No
> 
> [b]Active Plugins (28):[/b]
> ¤ AdvaImg.dll v.[b]0.11.0.2[/b] [29 May 2017 4:01:38] - Miranda image services 
> ¤ AVS.dll v.[b]0.95.3.4[/b] [20 Apr 2017 4:00:14] - Avatar service 
> ¤ Clist_nicer.dll v.[b]0.9.2.4[/b] [30 Mar 2017 4:00:40] - Clist nicer 
> ¤ Cln_skinedit.dll v.[b]0.0.0.4[/b] [26 Nov 2015 2:14:04] - Skin editor for Clist nicer 
> ¤ CrashDumper.dll v.[b]0.0.5.2[/b] [17 Jan 2017 5:02:02] - Crash dumper 
> ¤ DbEditorPP.dll v.[b]4.0.1.1[/b] [2 Jan 2017 5:02:06] - Database editor++ 
> ¤ Dbx_mmap.dll v.[b]0.95.3.1[/b] [3 Jul 2017 4:00:26] - Miranda NG mmap database driver 
> ¤ Facebook.dll v.[b]0.3.3.2[/b] [26 Jun 2017 4:01:52] - Facebook RM 
> ¤ Fingerprint.dll v.[b]0.1.0.0[/b] [30 Mar 2017 4:02:40] - Fingerprint NG 
> ¤ HistoryPP.dll v.[b]1.5.1.5[/b] [28 Jun 2017 14:22:12] - History++ 
> ¤ HistoryStats.dll v.[b]0.2.1.1[/b] [19 Jan 2017 5:04:22] - HistoryStats 
> ¤ ICQ.dll v.[b]0.11.3.5[/b] [13 Jun 2017 4:00:44] - IcqOscarJ protocol 
> ¤ Import.dll v.[b]0.95.4.3[/b] [19 Jan 2017 5:00:12] - Import contacts and messages 
> ¤ Jabber.dll v.[b]0.11.0.4[/b] [13 Jun 2017 4:01:20] - Jabber protocol 
> ¤ mTextControl.dll v.[b]0.8.0.1[/b] [3 Jan 2016 9:35:20] - Miranda text control 
> ¤ PluginUpdater.dll v.[b]0.1.2.5[/b] [16 May 2017 4:02:30] - Plugin updater 
> ¤ Popup.dll v.[b]2.1.1.12[/b] [14 Jun 2017 4:01:18] - Popup plus 
> ¤ QuickSearch.dll v.[b]1.4.2.0[/b] [30 Mar 2017 4:04:44] - Quick Search 
> ¤ SeenPlugin.dll v.[b]5.0.5.3[/b] [19 Jun 2017 4:01:22] - Last seen 
> ¤ SkypeWeb.dll v.[b]0.12.2.4[/b] [19 Jun 2017 4:04:24] - Skype protocol (Web) 
> ¤ SmileyAdd.dll v.[b]0.2.4.1[/b] [3 May 2017 4:01:28] - SmileyAdd 
> ¤ SpellChecker.dll v.[b]0.2.6.4[/b] [30 Mar 2017 4:01:58] - Spell checker 
> ¤ StatusManager.dll v.[b]0.11.2.0[/b] [13 Feb 2017 5:04:12] - Status manager 
> ¤ TabSRMM.dll v.[b]3.5.0.4[/b] [30 Jun 2017 4:00:40] - TabSRMM 
> ¤ Tipper.dll v.[b]2.1.0.7[/b] [19 Jan 2017 5:01:24] - Tipper 
> ¤ TopToolBar.dll v.[b]0.8.0.4[/b] [5 Dec 2016 5:01:36] - TopToolBar 
> ¤ UInfoEx.dll v.[b]0.8.5.0[/b] [30 Mar 2017 4:01:30] - User info ext 
> ¤ Weather.dll v.[b]0.4.0.3[/b] [19 Jan 2017 5:02:46] - Weather 
> 
> [b]Unloadable Plugins (1):[/b]
> ¤ DbChecker.dll v.[b]0.0.0.0[/b] [3 Jul 2017 4:02:20] - <unknown> 
> 
> 
> [b]Weather ini files:[/b]
> -------------------------------------------------------------------------------
>  gismeteo.ini v.[b]2012.05.03[/b] [11 Oct 2016 17:18:02] - GisMeteo
>  msn.ini v.[b]2014-11-08[/b] [11 Oct 2016 17:18:02] - MSN Weather (New Layout)
>  weatherxml.ini v.[b]0.0.5.4 2011-12-12[/b] [2 Jun 2016 7:05:34] - WeatherXML
>  wundergrnd_intl.ini v.[b]2011/02/13[/b] [11 Oct 2016 17:18:02] - Weather Underground Int'l
>  wundergrnd_xml.ini v.[b]2011/02/13[/b] [11 Oct 2016 17:18:02] - Weather Underground XML
> 
> [b]Protocols and Accounts:[/b]
> -------------------------------------------------------------------------------
> Facebook                 1 - Enabled 0 - Disabled  Loaded
> ICQ                      1 - Enabled 0 - Disabled  Loaded
> JABBER                   3 - Enabled 1 - Disabled  Loaded
> SKYPE                    1 - Enabled 0 - Disabled  Loaded
> MetaContacts             1 - Enabled 0 - Disabled  Loaded
> SkypeClassic             0 - Enabled 1 - Disabled  Not Loaded
> Weather                  1 - Enabled 0 - Disabled  Loaded
> 
> [b]Icon Packs:[/b]
> -------------------------------------------------------------------------------
>  Avonlea Light.icl [21 Mar 2012 18:07:17]
>  Flags_icons.dll [30 Mar 2017 4:03:02]
>  Fp_icons.dll [30 Mar 2017 4:02:40]
>  gtalk-gmailcoloredballs-v2.dll [7 Sep 2005 23:44:30]
>  HistoryPP_icons.dll [30 Jun 2017 4:02:26]
>  proto_ball1.dll [4 Sep 2005 16:52:06]
>  proto_conn_facebook.dll [5 Mar 2011 21:37:52]
>  Proto_Facebook.dll [26 Jun 2017 4:01:54]
>  proto_gtalk.dll [24 Oct 2012 10:12:26]
>  Proto_ICQ.dll [13 Jun 2017 4:01:54]
>  Proto_Jabber.dll [13 Jun 2017 4:01:54]
>  Proto_MetaContacts.dll [3 Jul 2017 4:04:00]
>  Proto_Skype.dll [19 Jun 2017 4:04:08]
>  Proto_Weather.dll [19 Jan 2017 5:02:46]
>  Proto_WhatsApp.dll [13 Jun 2017 4:03:58]
>  TabSRMM_icons.dll [30 Jun 2017 4:02:26]
>  Toolbar_icons.dll [20 Apr 2017 4:01:44]
>  UInfoEx_icons.dll [30 Mar 2017 4:01:32]
>  xStatus_ICQ.dll [13 Jun 2017 4:00:42]
>  xStatus_Jabber.dll [13 Jun 2017 4:00:48]
>  zoho.dll [2 Feb 2017 18:57:19]
> [/quote][/spoiler]

**Comment by ikeblaster** [comment]
It's due to changes in RichEdit50W (msftedit.dll) since Creators Update (Rich Edit v8.5, if I am not mistaken). They are adding some emoji support and it looks like it's incompatible with Miranda's way of replacing smileys/characters with images. I am afraid there are more bugs with this new version, I have encoutered problems with "collapsed" words after pasting some text in message field (where you write). Screenshot attached. Sent message was fine. Also restarting Miranda fixed it.

Temporal solution (or permanent?) is placing older msftedit.dll into Miranda NG folder (next to Miranda32.exe). I am attaching 32bit version from Windows 10 1511, Rich Edit v7.5. You can check for example using [Process Hacker](http://processhacker.sourceforge.net/) which DLL Miranda uses (it will just load system default DLL when it fails to load local DLL). Emojis then work as expected.

[msftedit_v75_32bit.zip](https://github.com/miranda-ng/miranda-ng/files/1202731/msftedit_v75_32bit.zip)

![Collapsed words](https://user-images.githubusercontent.com/6796369/28999291-751ef7de-7a41-11e7-8560-bd0798c537f3.png)

**Comment by Robyer** [comment]
@ikeblaster Interesting finding. I wonder if using this dll will work correctly even on older platforms like Vista or XP?
Also @georgehazan What do you think about this issue/solution? Or can you fix compatibility in Miranda code?

**Comment by ikeblaster** [comment]
@Robyer Tested on XP SP3 and sadly it's not usable. It shows 2 errors messages during start (missing entry point for memcpy_s in msvcrt.dll, something like that). Miranda then however works normally.

I've tested that it works the other way round - copying `msftedit.dll` (v4.1) from XP SP3 into Miranda's folder on Windows 10 1703. It has issues - spellcheck then uses yellow for underlining errors (instead of red). So personally I will continue using that v7.5 DLL.

[msftedit_v41_32bit_xpsp3.zip](https://github.com/miranda-ng/miranda-ng/files/1203125/msftedit_v41_32bit_xpsp3.zip)

**Comment by georgehazan** [comment]
@ikeblaster you cannot simply use modules from Win10 under XP, evidently, because you also need to port all dlls it uses

**Comment by ikeblaster** [comment]
@georgehazan Well @Robyer asked and it was worth the try. :) I didn't have high hopes for that.

**Comment by georgehazan** [comment]
@Robyer I still have no problems on recently updated Win10
![image](https://user-images.githubusercontent.com/4628541/29004021-b8c1de74-7ac9-11e7-84ad-3ddd98080407.png)

**Comment by ikeblaster** [comment]
Hmm, it can be related to Windows language. See @seg-on logs, he has english Windows on one PC, where it works, and slovak Windows on other, where it doesn't. I have czech Windows and have those problems. Also mine DLL have different size than your (but I don't know which one are you trying, that in `system32` or `SysWOW64`?). So maybe a bug in Windows. I have no idea how to solve that.

**Comment by ikeblaster** [comment]
![image](https://user-images.githubusercontent.com/6796369/29004092-5d1efbb2-7ac2-11e7-9038-4eeda3ff2430.png)

**Comment by Robyer** [comment]
Good point it could be related to system locale. I use czech too and it's broken for me.

But as I see @georgehazan has much older version of the library than us. I have same version (10.0.15063.483) as ikeblaster.

**Comment by georgehazan** [comment]
I have Windows 10 English Professional build 14393 with Russian system locale

**Comment by georgehazan** [comment]
okay, after installing that Creator Update nothing works, as you described :-) interesting

**Comment by georgehazan** [comment]
well...everything is ok, but RTF control simply doesn't draw these smileys :-( 
there's no difference between old good smileys that get drawn and those that aren't

**Comment by ikeblaster** [comment]
@georgehazan How does the smileys emplacement work? Is it simple "search string, replace with image"? My guess is there must be some processing of those unicode characters on the RTF control side even before "our" processing. 

It would be best to discard the possibility that it depends on OS language.

@seg-on Would you please send us `C:\Windows\System32\msftedit.dll` (it must be zipped for github) from the system where emojis work?

**Comment by georgehazan** [comment]
@ikeblaster smiley replacement works perfectly. the plugin creates a bunch of IViewObject2 objects and inserts them to RTF control, but only old ones gets drawn.

**Comment by ikeblaster** [comment]
@georgehazan I know, I am just curious how does it exactly work. So it finds for example `:)`, removes it from text, creates new `IViewObject2` with corresponding image and places it into RTF control. Is that right?

**Comment by georgehazan** [comment]
yes, it creates a ITextRange with text and replaces it with an image object

**Comment by seg-on** [comment]
Hi,
@ikeblaster here are all msftedit.dll from both languages systems and 32bit, 64bit version
https://1fichier.com/?dgqlbo3yy9
But i made comparison of those files and they are identical.

**Comment by georgehazan** [comment]
@seg-on there's no such thing like a "language system". all dlls are identical, they simply use different language resource dlls from ru-RU, en-GB etc folders inside %SystemRoot%\System32

**Comment by ikeblaster** [comment]
@georgehazan That is sadly not true. Each Windows distribution with different "base" language has it's own set of DLLs. There are those MUI resources, but the original DLL is not the same for every language.
![image](https://user-images.githubusercontent.com/6796369/29456994-6513ff48-8418-11e7-85d7-4d60140c4df1.png)

**Comment by georgehazan** [comment]
this information covers only version resource which could be present on various languages. also those resources can be replaced on the fly using Resource Editor, for example :) but the binary segments remain the same

**Comment by ikeblaster** [comment]
Hmm, you may be right, I am just looking at it. Sorry for my mistake.

**Comment by dartraiden** [comment]
Can someone test this on 1709?

**Comment by dartraiden** [comment]
Tested, bug still exists.

**Comment by seg-on** [comment]
for me too :/

**Comment by ThosRTanner** [comment]
has someone raised this with microsoft? and couldn't you work round it by adding a space or something?

**Comment by dartraiden** [comment]
I report this via Windows Insider feedback. No reaction.

**Comment by ThosRTanner** [comment]
I'm guessing this is why this: 🍀 when put in a facebook chat doesn't actually appear (it's a unicode character) and can't be copy/pasted (though I can see it in the log)

**Comment by georgehazan** [comment]
Since 0.96.4 Miranda can use the smile pack for emoji, so it doesn't depend on OS version & fonts
