### ISSUE TITLE
Miranda нашла повреждения в вашей базе

### ISSUE THREAD

**Issue by devcline** [miranda-ng/miranda-ng#853]
![image](https://user-images.githubusercontent.com/617020/27382157-faac3496-5685-11e7-99cc-42764f467c0b.png)

DBchecker не помогает
Плагин не запускается так как сама миранда не запускается.. В чем прикол?

Latest nightly build.

**Comment by georgehazan** [comment]
это очень редкая и древняя зараза, но поймать ее не получается
помогает восстановление из бэкапа, потому что оно портит заголовок файла

**Comment by georgehazan** [comment]
рекомендую плагин db_autobackup

**Comment by devcline** [comment]
Есть ли способы что бы вытащить хоть что либо из .dat ?

**Comment by georgehazan** [comment]
можно восстановить, да, если заголовок поврежден частично, а не полностью
