### ISSUE TITLE
Facebook: doesn't work load unread msg 

### ISSUE THREAD

**Issue by seg-on** [miranda-ng/miranda-ng#854]
Feature that load unread msg received between connected times, stop working.

**Comment by Robyer** [comment]
See my comment here: http://forum.miranda-ng.org/index.php?topic=192.msg19915#msg19915

**Comment by Robyer** [comment]
People are reporting it works again, so perhaps a Facebook change back and forth. I'm closing this, but if you still have the same issue, feel free to reopen this.
