### ISSUE TITLE
Окно беседы выводится на передний план

### ISSUE THREAD

**Issue by jawhien** [miranda-ng/miranda-ng#865]
### Expected behavior
В настройках бесед, установлена галочка, чтобы окно новой беседы открывалось в фоне.

### Actual behavior
За редкими исключениями, окно беседы появляется на переднем плане и становится активным. Возможно это связано с использованием программы чтения с экрана, однако какое-то время назад этой проблемы не было.

**Comment by dartraiden** [comment]
Какой плагин чатов используется? TabSRMM?

**Comment by dartraiden** [comment]
Кроме того, у бесед и групповых чатов в TabSRMM разные настройки, поэтому стоит убедиться, что баг воспроизводится именно с беседами.

**Comment by jawhien** [comment]
ПРошу прощение, что сразу не указал. StdMsg, Scriver и TabSRMM выключены.

**Comment by dartraiden** [comment]
Такого не может быть, если выключены Scriver и TabSRMM, то автоматически запускается StdMsg.

**Comment by jawhien** [comment]
ой. StdMsg используется. я это и имел ввиду. опечатался.
