### ISSUE TITLE
MSN: User details do not show username anywhere

### ISSUE THREAD

**Issue by sagamusix** [miranda-ng/miranda-ng#870]
When opening the user details for an MSN contact, there is no way to find out which MSN username they have. For most contacts their MSN address seems to be filled into the "E-mail" field of the contact info, but apparently I have at least contact where this field is empty. Maybe the MSN address that is used to identify the contact should be put in the window title or some other suitable place.

**Comment by dartraiden** [comment]
Protocol is deprecated.
