### ISSUE TITLE
MSN: Users show up outside of their original groups

### ISSUE THREAD

**Issue by sagamusix** [miranda-ng/miranda-ng#871]
Today, MSN users that I have sorted into groups years ago started showing up outside of those groups, and no longer use the custom names I provided. I don't see any recent MSN changes in Miranda so something might have changed on Microsoft's side.

**Comment by sagamusix** [comment]
Actually it seems like those users exist twice - once in their original groups, with the custom names I gave them, and once outside those groups, with their original MSN nickname.

**Comment by Robyer** [comment]
You can look at them via Database Editor++ and compare how (if) they differ in some identifier/e-mail...

**Comment by georgehazan** [comment]
perhaps that's a problem with Skype users recognition, they all might be stored now using their skype names instead of emails

**Comment by sagamusix** [comment]
Is there anything that could be done about that from Miranda's side? I tried deleting one of them but the contact re-appeared when I restarted Miranda.

**Comment by georgehazan** [comment]
MSN does not store groups at the server, so when a contact is deleted, it reappears outside groups

**Comment by dartraiden** [comment]
Protocol is deprecated.
