### ISSUE TITLE
TabSRMM, звук набора текста воспроизводится когда я набираю текст.

### ISSUE THREAD

**Issue by jawhien** [miranda-ng/miranda-ng#877]
Если включить в TabSRMM звук набора текста, он воспроизводится, только когда я кому-либо набираю текст, но когда мой контакт мне пишет, звука как раз и нету.

**Comment by georgehazan** [comment]
работает на ура. возможно, у контакта отключена пересылка уведомлений о наборе текста

**Comment by jawhien** [comment]
не отключена, при использовании scriver или StdMSG всё в порядке. да и в TabSRMM вижу в окне беседы, что набирает текст, и в трее вижу, а звук упорно звучит когда именно я печатаю.

**Comment by georgehazan** [comment]
у меня табсы издает звук и тогда, когда в него прилетает набор текста. т.е. само по себе оно работает, возможно, надо что-то поправить в настройках.

**Comment by jawhien** [comment]
Только вопрос что именно? что не делаю, без результата. Какие вообще настройки могут на это повлиять? Попробовал и без Clist blind, и без bass_interface, всё как в шутке про лыжи....:)
