### ISSUE TITLE
crash miranda в окне настроек с плагином LinkList.

### ISSUE THREAD

**Issue by jawhien** [miranda-ng/miranda-ng#878]
В настройках, при выборе пункта "История ссылок", плагина LinkList, почти всегда происходит crash приложения.
При работе используется программа экранного доступа, возможно, это имеет значение.
Прикрепляю CrashLog.

[crash20170806204622.txt](https://github.com/miranda-ng/miranda-ng/files/1203303/crash20170806204622.txt)

**Comment by dartraiden** [comment]
Лог, к сожалению, бесполезен, поскольку сделан без отладочных символов.

**Comment by jawhien** [comment]
Значит скринридер тут ни при чём. вот лог, сделал как надо.

[crash20170807232902.txt](https://github.com/miranda-ng/miranda-ng/files/1206088/crash20170807232902.txt)

**Comment by georgehazan** [comment]
жуть какая... проблема в том, что оно не может там падать физически :) 
попробую повторить
