### ISSUE TITLE
"xStatus notify" does not save 'removed extra status' template

### ISSUE THREAD

**Issue by Hezkore** [miranda-ng/miranda-ng#879]
### Expected behavior
Changing template text for:
_Popups > Status Notify > Extra status > Notify when contact removes extra status_
Is supposed to be saved, even when Miranda NG is restarted.
Just like all of the other options in the same plug-in.

### Actual behavior
Changing template text for:
_Popups > Status Notify > Extra status  > Notify when contact removes extra status_
Is not saved, and will reset back to "_removed %n_" when Miranda NG is restarted.

### Steps to reproduce that behavior
 * Get and Enable plug-in "_newxstatusnotify.dll_" version 1.4.0.11
 * Go to Miranda NG _Options > Popups > Status Notify > Extra status_
 * Enable Template for "_Notify when contact removes extra status_"
 * Change Template text
 * Restart Miranda NG
 * Notice Template text has reset back to "_removed %n_"

Here's a GIF of the issue:
![2017-08-08_16-32-05](https://user-images.githubusercontent.com/1727541/29076954-41cd549e-7c57-11e7-9606-9cf208881b30.gif)

**Comment by Mataes** [comment]
fixed in 5bed820
