### ISSUE TITLE
IRC dims all rooms after leaving one

### ISSUE THREAD

**Issue by Hezkore** [miranda-ng/miranda-ng#880]
### Expected behavior
When selecting "_Leave chat_" from the right click menu, I expect to leave that chat room only.

### Actual behavior
Miranda NG instead dims all IRC chat rooms, as if I were offline, but IRC is still connected.

### Steps to reproduce that behavior
 * Connect to IRC
 * Join a few chat rooms
 * Right click one and select "_Leave chat_"
 * Notice all rooms now appear dimmed
 * Notice IRC is still actually connected

Here's a GIF of the issue:
![2017-08-08_16-42-49](https://user-images.githubusercontent.com/1727541/29077554-a619756c-7c58-11e7-9d04-a26d7c2a7f7b.gif)

**Comment by Robyer** [comment]
Can you try if it works in stable version?
