### ISSUE TITLE
Facebook Newsfeed popup issue? 

### ISSUE THREAD

**Issue by newsjunkie247** [miranda-ng/miranda-ng#882]
Hi,
I think there might be an issue with the Facebook newsfeed appearing again? The ticker seems to working at times, but I'm not seeing any newsfeed items appear in the popups today.

**Comment by Robyer** [comment]
Could be. Facebook is often changing format of the newsfeed's HTML. I'll look at it later.

**Comment by newsjunkie247** [comment]
Thanks for fixing this. Is there any way to get the new dll version or when will it be available?

**Comment by Robyer** [comment]
It should be ready in build from today. But as I just checked it, loading Memories are fixed, but it didn't show any wall posts for me. But as memories works I expect wall posts should work too (as it uses same format).
