### ISSUE TITLE
Group chat does not start at the bottom

### ISSUE THREAD

**Issue by Hezkore** [miranda-ng/miranda-ng#886]
### Expected behavior
When opening up an IRC chat room, or any other group conversation, I expect to see the newest (bottom) line of text.

### Actual behavior
Opening up a group conversation instead starts the conversation somewhere above the newest (bottom) line and gets worse over time.
Sometimes it scrolls back multiple hours.

This makes me miss a lot of new messages.

### Steps to reproduce that behavior
 * Enter group conversation with a lot of text
 * Close group conversation
 * Open group conversation
 * Notice group chat is not scrolled to the bottom

Here's a GIF showing a very mild case of the issue, only missing a line or two:
![2017-08-15_03-37-43](https://user-images.githubusercontent.com/1727541/29299006-061602ce-816c-11e7-935e-e314ec128fce.gif)

**Comment by georgehazan** [comment]
which SRMM plugin is used for chats? StdMsg?

**Comment by LittleVulpix** [comment]
There is a long discussion on this issue from before as well, on the forums.

See https://forum.miranda-ng.org/index.php?topic=4388

**Comment by Hezkore** [comment]
I'm using Scriver
