### ISSUE TITLE
TabSRMM глотает слова после неразрывного пробела

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#89]
**Reported by v derckach on 30 Sep 2012 19:17 UTC**
 в TabSRMM есть неприятный баг: если отправить реплику, содержащую неразрывный пробел, то глотается этот пробел и слово, стоящее за ним. Что очень часто меняет смысл фразы аж на противоположный.

Типа
«Эта реплика — не подходит.»
превращается в
«Эта реплика —подходит.»

Баг тянется ещё из IM из незапамятных времён.

(Использую программу TypeItEasy, которая помогает легко вставлять всяческие типографские красивости — кавычки-ёлочки, длинные тире и так далее. Вот из-за неё после длинного тире часто оказывается не пробел, а неразрывный пробел.)

Tabsrmm lose space and next followed word if unbreaking space used (Alt+0160)

**Comment by georgehazan** [comment]
**Modified by wishmaster on 3 Jan 2013 10:01 UTC**

**Comment by dartraiden** [comment]
Changed 4 years ago by apollo2k4
Resolution set to wontfix

Microsoft richedit bugs
