### ISSUE TITLE
clist_modern status bar height is not adjusted for icon borders

### ISSUE THREAD

**Issue by AnrDaemon** [miranda-ng/miranda-ng#899]
### Expected behavior
I fully expect borders height to add up to the icon size.

### Actual behavior
The borders are subtracted from icon height.

### Does it work in stable version?
Nop.

### Steps to reproduce that behavior
 *  Install clist_modern
 * CList -> Window -> [x] Disable skin engine
 * Status bar -> Borders -> Add some border width.

![2017-08-21-131317](https://user-images.githubusercontent.com/6532485/29515531-744f9a12-8675-11e7-920e-381be9010057.png)
![2017-08-21-131257](https://user-images.githubusercontent.com/6532485/29515530-744e4ad6-8675-11e7-9039-2780a3d53d16.png)

**Comment by dartraiden** [comment]
What about stable? It's regression or not?

**Comment by Robyer** [comment]
@dartraiden He wrote it doesn't work in stable, so no regression.

**Comment by georgehazan** [comment]
this behavior lasts from the very beginning (i.e. since 2001, when Clist Modern was introduced), and is not a bug, that's how it was written originally

**Comment by AnrDaemon** [comment]
Ok, you may call it an "undesired behavior".

**Comment by georgehazan** [comment]
dunno, imho this behavior is designed :) you can change the frame's height by toggling the Floating checkbox in Frames menu, then adjust the frame's size and toggle Floating back, so these borders should really work inside the frame, not from the outside
