### ISSUE TITLE
Database corruption

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#901]
### Steps to reproduce
- Someone writes me a private message in Jabber conference
- Temporary contact appears in my clist
- When I try to delete them, a message appeared - "Miranda has detected corruption in your database. This corruption may be fixed by DbChecker plugin. Please download it from https://miranda-ng.org/p/DbChecker/. Miranda will now shut down."

DbChecker doesn't help. 100% reproducible.

**Comment by georgehazan** [comment]
could you fix a stack that leads to this message?
you can set a breakpoint to db3x_mmap, database.cpp, line 90

**Comment by Robyer** [comment]
@georgehazan I saw the fix, but shouldn't it be fixed (also) inside dbx driver? It shouldn't let corrupt the database in any case.

**Comment by georgehazan** [comment]
there is no corruption in the database, just the wrong diagnostics during recursive contact deletion
