### ISSUE TITLE
Auto connect/reconnect not working anymoce

### ISSUE THREAD

**Issue by makedir** [miranda-ng/miranda-ng#906]
Miranda-ng updater called for an update in the next days, and since then it doesnt connect automatically anymore when you start it, nor does it reconnect after sleep or disconnect.

**Comment by Robyer** [comment]
KeepStatus, StartupStatus and AdvancedAutoAway were merged into single plugin: Status Manager - https://wiki.miranda-ng.org/index.php?title=Plugin:StatusManager/en

Make sure you have it installed and configured properly.
