### ISSUE TITLE
Wartack: dont tranlate "Check unknow formats". Tab wiht format and players.

### ISSUE THREAD

**Issue by MrMyth** [miranda-ng/miranda-ng#907]
Wartack: dont tranlate "Check unknown formats". Tab with format and players. Very old bug.

Fix for rus:

[Check unknown formats]
Проверять неизвестные форматы

**Comment by dartraiden** [comment]
Ага, это один из плагинов, написанных на паскале, поэтому автоматически "выдёргивать" непереведённые строки из него невозможно. Нужно как-нибудь сесть, перебрать все такие плагины вручную, строчку за строчкой, чтобы составить список непереведённых строк. та ещё работёнка.

**Comment by MrMyth** [comment]
А много таких? Можно выловить иначе: повесить просьбу к пользователям на форуме. Но как я понял плагин очень древний?

**Comment by dartraiden** [comment]
[Шесть](https://wiki.miranda-ng.org/index.php?title=Langpacks/ru#.D0.A1.D1.82.D1.80.D1.83.D0.BA.D1.82.D1.83.D1.80.D0.B0_.D0.BF.D0.B5.D1.80.D0.B5.D0.B2.D0.BE.D0.B4.D0.B0_Miranda_NG). Пять за вычетом уже проделанной работы. Берётся плагин, устанавливается и справа налево сверху вниз все-все строки из интерфейса переносятся в ленгпак по порядку. Трудность в том, что приходится нажимать все кнопки и т.п., чтобы выловить абсолютно все строки.
