### ISSUE TITLE
Close / Minimize the message window on send not closing / minimizing

### ISSUE THREAD

**Issue by minstrel** [miranda-ng/miranda-ng#909]
### Expected behavior
When the boxes 'Close the message window on send' or 'Minimize the message window on send' are checked off, message windows should close or minimize after typing and pressing 'enter' to send.

### Actual behavior
Message windows stay open and not minimized after typing and pressing 'enter' to send.

### Does it work in stable version?
This is the stable version (0.95.6, build 18429).  Unable to provide further version info because clicking 'Available Components List' to install CrashDumper is bringing up 'An error occurred while checking for new updates'.

### Steps to reproduce that behavior
* Open options menu / Message Sessions / Messaging.
* Check off either 'Close the message window on send' or 'Minimize the message window on send'.
* Send a message (window fails to close or minimize).

**Comment by georgehazan** [comment]
which SRMM plugin are you talking about? stdmsg, scriver, tabsrmm?

**Comment by georgehazan** [comment]
also 'check off' usually means that you leave a check box empty. 
do you really expect an option to work when it's disabled?

**Comment by georgehazan** [comment]
if you use StdMsg, be sure that you disabled the tabbed interface first

**Comment by minstrel** [comment]
Disabling tabbed interface did it, thanks!

A bit strange because I haven't touched the settings menu in months and auto-close was working fine before this last update.  I'm not sure if tabbed interface somehow got enabled in the latest update, or if it always was but didn't block the auto-close behavior previously.  Either way working now and thanks again.

**Comment by dartraiden** [comment]
OK, close this.
