### ISSUE TITLE
jabber group chats closed by pressing ESC-key

### ISSUE THREAD

**Issue by de77** [miranda-ng/miranda-ng#910]
### Expected behavior
Minimize the window to the task bar, as selected in "Message sessions -> Tabs and Layouts -> Miscellaneous options -> ESC key behavior"

### Actual behavior
Tab of group chats is closed. If set active other tab (i.e. personal chat - not group), then ESC works as expected.

### Does it work in stable version?
Sorry, I don't use dev versions. In previous stable version 0.95.5 all works fine.

### Steps to reproduce that behavior
1) Open jabber group chat in tabsrrm
2) press ESC-key.

### VersionInfo.
CPU: Intel(R) Core(TM) i3 CPU 540 @ 3.07GHz [x86 Family 6 Model 37 Stepping 2] [DEP Enabled] [4 CPUs]
Installed RAM: 3582 MBytes
Microsoft Windows XP Professional Service Pack 3 (build 2600)
Internet Explorer: 6.0.2900.5512 (build 62900.5512)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian
Free disk space on Miranda partition: 5248 MBytes

Miranda NG Version: 0.95.6 build #18429 (d94f9da99d)
Build time: 25 Aug 2017 19:16:20
Profile: D:\Program Files\Miranda NG\Profiles\profile\profile.dat (dbx mmap driver)
Profile size: 32768000 Bytes
Profile creation date: 16 Sep 2013 15:49:26
Language pack: No language pack installed
Service Mode: No

Active Plugins (12):
¤ AdvaImg.dll v.0.11.0.2 [25 Aug 2017 19:14:50] - Miranda image services 
¤ AVS.dll v.0.95.3.4 [25 Aug 2017 19:14:00] - Avatar service 
¤ CrashDumper.dll v.0.0.5.2 [25 Aug 2017 19:14:55] - Crash dumper 
¤ DbEditorPP.dll v.4.0.1.1 [25 Aug 2017 19:14:56] - Database editor++ 
¤ Dbx_mmap.dll v.0.95.3.1 [25 Aug 2017 19:14:02] - Miranda NG mmap database driver 
¤ HistoryPP.dll v.1.5.1.5 [28 Jun 2017 17:18:28] - History++ 
¤ ICQ.dll v.0.11.3.5 [25 Aug 2017 19:14:12] - IcqOscarJ protocol 
¤ Jabber.dll v.0.11.0.5 [25 Aug 2017 19:14:41] - Jabber protocol 
¤ PluginUpdater.dll v.0.1.2.5 [25 Aug 2017 19:15:01] - Plugin updater 
¤ SpellChecker.dll v.0.2.6.4 [25 Aug 2017 19:15:06] - Spell checker 
¤ TabSRMM.dll v.3.5.0.5 [25 Aug 2017 19:14:09] - TabSRMM 
¤ Tipper.dll v.2.1.0.7 [25 Aug 2017 19:14:32] - Tipper 

Unloadable Plugins (1):
¤ DbChecker.dll v.0.0.0.0 [25 Aug 2017 19:14:59] - <unknown> 

Protocols and Accounts:
-------------------------------------------------------------------------------
ICQ                      1 - Enabled 0 - Disabled  Loaded
JABBER                   3 - Enabled 2 - Disabled  Loaded
MetaContacts             1 - Enabled 0 - Disabled  Loaded

Icon Packs:
-------------------------------------------------------------------------------
 Flags_icons.dll [25 Aug 2017 19:15:18]
 HistoryPP_icons.dll [25 Aug 2017 19:15:00]
 Proto_AIM.dll [25 Aug 2017 19:14:46]
 Proto_Facebook.dll [25 Aug 2017 19:14:43]
 Proto_GG.dll [25 Aug 2017 19:14:46]
 Proto_ICQ.dll [25 Aug 2017 19:14:47]
 Proto_IRC.dll [25 Aug 2017 19:14:48]
 Proto_Jabber.dll [25 Aug 2017 19:14:48]
 Proto_MetaContacts.dll [25 Aug 2017 19:15:37]
 Proto_MSN.dll [25 Aug 2017 19:14:48]
 Proto_Yahoo.dll [24 Jun 2016 22:01:47]
 TabSRMM_icons.dll [25 Aug 2017 19:15:01]
 Toolbar_icons.dll [25 Aug 2017 19:14:48]
 xStatus_ICQ.dll [25 Aug 2017 19:14:03]
 xStatus_Jabber.dll [25 Aug 2017 19:14:03]

**Comment by de77** [comment]
If cursor is placed in log area of group chat, then ESC also works as expected, but if cursor placed in edit area, then tab is closed.

**Comment by georgehazan** [comment]
confirmed
