### ISSUE TITLE
TabSRMM loading all history of contact regardless of settings, crashes miranda on big logs

### ISSUE THREAD

**Issue by hethhhhh** [miranda-ng/miranda-ng#911]
the settings under Message Sessions > Message Log > Load history events, it just loads the whole log, then filters the messages to that setting. And for example shows last 10 or 50. 
If there is a big log with the contact the tab freezes and loads after 30 seconds sometimes, sometimes crashes miranda altogether. Please make it load only the number of entries specified in Load history events, thank you.

**Comment by Robyer** [comment]
You have issue in your *.dat profile. Run DbChecker and make sure to check "Mark all events as read" in it's options.

**Comment by hethhhhh** [comment]
thanks, that fixed it, although the DBchecker didn't say it did anything (only skipping).

**Comment by Robyer** [comment]
Yes, just to clarify, DbChecker reads all data and copy them to new (clean) file. So skipping means it ignored some duplicit or invalid data and didn't copy them to new file.
