### ISSUE TITLE
Miranda-ng crashes when PC wakes up from sleep

### ISSUE THREAD

**Issue by makedir** [miranda-ng/miranda-ng#912]
Since you updated it last week, Miranda always crashes when PC returns from sleep.

**Comment by georgehazan** [comment]
is a crash log available?

**Comment by makedir** [comment]
`Miranda Crash Report from 30 Aug 2017 2:13:41. Crash Dumper v.0.0.5.2

Likely cause of the crash plugin: Modern contact list

Exception: Access Violation at address 147708CC. Reading from address 06C1C340.

Stack Trace:
---------------------------------------------------------------
147708CC (Clist_modern 14740000): (filename not available) (0): (function-name not available)
14772F0E (Clist_modern 14740000): (filename not available) (0): (function-name not available)
77002B5B (USER32 76FD0000): (filename not available) (0): AddClipboardFormatListener
76FF50F3 (USER32 76FD0000): (filename not available) (0): DispatchMessageW
76FE0BEC (USER32 76FD0000): (filename not available) (0): SendMessageW
76FE090F (USER32 76FD0000): (filename not available) (0): SendMessageW
125C5973 (mir_core 125C0000): (filename not available) (0): WindowList_Broadcast
1246D1C4 (mir_app 12420000): (filename not available) (0): Clist_Broadcast

CPU: Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz [Intel64 Family 6 Model 58 Stepping 9] [DEP Enabled] [4 CPUs]
Installed RAM: 3918 MBytes
Microsoft Windows 10 , 64-bit (build 15063)
Internet Explorer: 9.11.15063.0 (build 915063)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : German/German | German/German

Miranda NG Version: 0.95.6 build #18429 (d94f9da99d) [running inside WOW64]
Build time: 25 Aug 2017 19:16:22
Profile: C:\Users\mkdr\AppData\Roaming\Miranda NG\mkdr\mkdr.dat (dbx mmap driver)
Language pack: No language pack installed
Service Mode: No

Active Plugins (21):
¤ AdvaImg.dll v.0.11.0.2 [25 Aug 2017 19:14:52] - Miranda image services 
¤ AIM.dll v.0.11.0.1 [25 Aug 2017 19:14:04] - AIM protocol 
¤ AVS.dll v.0.95.3.4 [25 Aug 2017 19:14:02] - Avatar service 
¤ Clist_modern.dll v.0.9.1.5 [25 Aug 2017 19:14:56] - Modern contact list 
¤ CrashDumper.dll v.0.0.5.2 [25 Aug 2017 19:14:56] - Crash dumper 
¤ Dbx_mmap.dll v.0.95.3.1 [25 Aug 2017 19:14:04] - Miranda NG mmap database driver 
¤ Facebook.dll v.0.3.3.2 [25 Aug 2017 19:14:48] - Facebook RM 
¤ GG.dll v.0.11.0.3 [25 Aug 2017 19:14:12] - Gadu-Gadu protocol 
¤ HistoryPP.dll v.1.5.1.5 [28 Jun 2017 17:18:30] - History++ 
¤ ICQ.dll v.0.11.3.5 [25 Aug 2017 19:14:14] - IcqOscarJ protocol 
¤ Import.dll v.0.95.4.3 [25 Aug 2017 19:14:02] - Import contacts and messages 
¤ IRC.dll v.0.11.0.3 [25 Aug 2017 19:14:08] - IRC protocol 
¤ Jabber.dll v.0.11.0.5 [25 Aug 2017 19:14:42] - Jabber protocol 
¤ MSN.dll v.0.14.0.1 [25 Aug 2017 19:14:16] - MSN protocol 
¤ mTextControl.dll v.0.8.0.1 [25 Aug 2017 19:14:26] - Miranda text control 
¤ NewEventNotify.dll v.0.2.2.3 [25 Aug 2017 19:14:52] - NewEventNotify 
¤ PluginUpdater.dll v.0.1.2.5 [25 Aug 2017 19:15:02] - Plugin updater 
¤ Popup.dll v.2.1.1.12 [25 Aug 2017 19:14:30] - Popup plus 
¤ Scriver.dll v.3.0.1.7 [25 Aug 2017 19:14:04] - Scriver 
¤ StatusManager.dll v.0.11.2.0 [25 Aug 2017 18:16:02] - Status manager 
¤ TopToolBar.dll v.0.8.0.4 [25 Aug 2017 19:14:48] - TopToolBar 

Loaded Modules:
-------------------------------------------------------------------------------
C:\Program Files (x86)\Miranda NG\Miranda32.exe  00400000 - 00409000 v.0.95.6.18429 [25 Aug 2017 19:16:22]
C:\WINDOWS\SYSTEM32\ntdll.dll  77670000 - 777FE000 v.10.0.15063.447 [20 Jun 2017 7:15:11]
C:\WINDOWS\System32\KERNEL32.DLL  76E10000 - 76EE0000 v.10.0.15063.296 [28 Apr 2017 3:16:18]
C:\Program Files (x86)\AVG\Antivirus\aswhookx.dll  65890000 - 658BF000 v.17.5.3.9168 [19 Jul 2017 13:37:26]
C:\WINDOWS\System32\KERNELBASE.dll  748D0000 - 74A92000 v.10.0.15063.502 [28 Jul 2017 6:48:20]
C:\WINDOWS\System32\USER32.dll  76FD0000 - 7710C000 v.10.0.15063.0 [18 Mar 2017 22:59:00]
C:\WINDOWS\System32\win32u.dll  74AB0000 - 74AC6000 v.10.0.15063.0 [18 Mar 2017 22:58:59]
C:\WINDOWS\System32\GDI32.dll  77640000 - 77661000 v.10.0.15063.483 [7 Jul 2017 8:31:24]
C:\WINDOWS\System32\gdi32full.dll  74E50000 - 74FA8000 v.10.0.15063.413 [3 Jun 2017 11:59:17]
C:\WINDOWS\System32\msvcp_win.dll  74850000 - 748C9000 v.10.0.15063.0 [18 Mar 2017 22:58:44]
C:\WINDOWS\System32\ucrtbase.dll  77440000 - 77558000 v.10.0.15063.447 [20 Jun 2017 7:14:59]
C:\WINDOWS\SYSTEM32\MSVCR100.dll  61F50000 - 6200F000 v.10.0.40219.325 [11 Jun 2011 1:58:52]
C:\WINDOWS\System32\IMM32.DLL  74E10000 - 74E35000 v.10.0.15063.0 [18 Mar 2017 22:59:00]
C:\Program Files (x86)\Miranda NG\libs\mir_app.mir  12420000 - 124E6000 v.0.95.6.18429 [25 Aug 2017 19:14:24]
C:\WINDOWS\System32\SHLWAPI.dll  754A0000 - 754E5000 v.10.0.15063.502 [28 Jul 2017 6:35:32]
C:\WINDOWS\System32\msvcrt.dll  77570000 - 7762D000 v.7.0.15063.0 [18 Mar 2017 22:58:44]
C:\WINDOWS\System32\combase.dll  77200000 - 77438000 v.10.0.15063.447 [20 Jun 2017 7:04:39]
C:\WINDOWS\System32\RPCRT4.dll  75020000 - 750E0000 v.10.0.15063.447 [20 Jun 2017 7:13:24]
C:\WINDOWS\System32\SspiCli.dll  74140000 - 74160000 v.10.0.15063.0 [18 Mar 2017 22:58:44]
C:\WINDOWS\System32\CRYPTBASE.dll  74130000 - 7413A000 v.10.0.15063.0 [18 Mar 2017 22:58:44]
C:\WINDOWS\System32\bcryptPrimitives.dll  741C0000 - 74217000 v.10.0.15063.138 [1 Apr 2017 2:28:16]
C:\WINDOWS\System32\sechost.dll  750F0000 - 75131000 v.10.0.15063.0 [18 Mar 2017 22:58:44]
C:\WINDOWS\System32\WS2_32.dll  74FB0000 - 75017000 v.10.0.15063.0 [18 Mar 2017 22:58:44]
C:\WINDOWS\System32\COMDLG32.dll  74C20000 - 74D0F000 v.10.0.15063.502 [28 Jul 2017 6:12:00]
C:\WINDOWS\System32\shcore.dll  74300000 - 7438C000 v.10.0.15063.0 [18 Mar 2017 22:58:54]
C:\WINDOWS\System32\SHELL32.dll  75AC0000 - 76E08000 v.10.0.15063.502 [28 Jul 2017 6:36:21]
C:\WINDOWS\System32\cfgmgr32.dll  754F0000 - 75529000 v.10.0.15063.0 [18 Mar 2017 22:58:49]
C:\WINDOWS\System32\windows.storage.dll  75530000 - 75AB4000 v.10.0.15063.502 [28 Jul 2017 6:40:18]
C:\WINDOWS\System32\advapi32.dll  74280000 - 742F7000 v.10.0.15063.0 [18 Mar 2017 22:58:39]
C:\WINDOWS\System32\kernel.appcore.dll  77630000 - 7763E000 v.10.0.15063.0 [18 Mar 2017 22:58:46]
C:\WINDOWS\System32\powrprof.dll  752B0000 - 752F5000 v.10.0.15063.0 [18 Mar 2017 22:58:48]
C:\WINDOWS\System32\profapi.dll  74E40000 - 74E50000 v.10.0.15063.0 [18 Mar 2017 22:58:44]
C:\WINDOWS\System32\ole32.dll  74D10000 - 74E03000 v.10.0.15063.502 [28 Jul 2017 6:35:56]
C:\WINDOWS\SYSTEM32\WINMM.dll  65850000 - 65874000 v.10.0.15063.0 [18 Mar 2017 22:58:45]
C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.15063.483_none_6dad63fefc436da8\COMCTL32.dll  658D0000 - 65ADE000 v.6.10.15063.0 [18 Mar 2017 22:58:58]
C:\WINDOWS\SYSTEM32\UxTheme.dll  657A0000 - 65818000 v.10.0.15063.0 [18 Mar 2017 22:58:57]
C:\Program Files (x86)\Miranda NG\libs\zlib.mir  126E0000 - 126F8000 v.1.2.11.0 [25 Aug 2017 19:14:02]
C:\Program Files (x86)\Miranda NG\libs\mir_core.mir  125C0000 - 125E0000 [25 Aug 2017 19:14:06]
C:\WINDOWS\SYSTEM32\VERSION.dll  73970000 - 73978000 v.10.0.15063.0 [18 Mar 2017 22:58:58]
C:\WINDOWS\SYSTEM32\Secur32.dll  6BA90000 - 6BA9A000 v.10.0.15063.0 [18 Mar 2017 22:58:50]
C:\WINDOWS\SYSTEM32\WINMMBASE.dll  65820000 - 65843000 v.10.0.15063.0 [18 Mar 2017 22:58:45]
C:\WINDOWS\System32\MSCTF.dll  74AD0000 - 74C16000 v.10.0.15063.332 [20 May 2017 11:13:30]
C:\WINDOWS\System32\OLEAUT32.dll  747B0000 - 74846000 v.10.0.15063.332 [20 May 2017 10:55:12]
C:\WINDOWS\SYSTEM32\dwmapi.dll  65770000 - 65793000 v.10.0.15063.483 [7 Jul 2017 8:57:23]
C:\WINDOWS\System32\clbcatq.dll  77170000 - 771F3000 v.2001.12.10941.16384 [18 Mar 2017 22:58:41]
C:\WINDOWS\system32\explorerframe.dll  51950000 - 51D8A000 v.10.0.15063.502 [28 Jul 2017 6:08:12]
C:\Program Files (x86)\Miranda NG\Plugins\CrashDumper.dll  14A40000 - 14A50000 v.0.0.5.2 [25 Aug 2017 19:14:56]
C:\WINDOWS\SYSTEM32\dbghelp.dll  73360000 - 734BD000 v.10.0.15063.447 [20 Jun 2017 6:38:28]
C:\WINDOWS\SYSTEM32\dbgcore.DLL  73330000 - 73355000 v.10.0.15063.0 [18 Mar 2017 22:58:49]
C:\Program Files (x86)\Miranda NG\Plugins\Dbx_mmap.dll  14C00000 - 14C11000 v.0.95.3.1 [25 Aug 2017 19:14:04]
C:\Program Files (x86)\Miranda NG\Plugins\Import.dll  157E0000 - 157ED000 v.0.95.4.3 [25 Aug 2017 19:14:02]
C:\Program Files (x86)\Miranda NG\Core\stdcrypt.dll  13080000 - 1308B000 v.0.95.6.18429 [25 Aug 2017 19:16:22]
C:\Program Files (x86)\Miranda NG\Core\stdssl.dll  13180000 - 13187000 v.0.95.6.18429 [25 Aug 2017 19:16:20]
C:\WINDOWS\System32\CRYPT32.dll  75300000 - 7547D000 v.10.0.15063.296 [28 Apr 2017 3:09:42]
C:\WINDOWS\System32\MSASN1.dll  77560000 - 7756E000 v.10.0.15063.447 [20 Jun 2017 7:04:50]
C:\WINDOWS\SYSTEM32\WSOCK32.dll  73D70000 - 73D78000 v.10.0.15063.0 [18 Mar 2017 22:58:48]
C:\WINDOWS\SYSTEM32\Msftedit.dll  5DCB0000 - 5DF5D000 v.10.0.15063.483 [7 Jul 2017 7:58:40]
C:\Program Files (x86)\Miranda NG\Plugins\AdvaImg.dll  142E0000 - 14370000 v.0.11.0.2 [25 Aug 2017 19:14:52]
C:\WINDOWS\SYSTEM32\MSVCP100.dll  62300000 - 62369000 v.10.0.40219.325 [11 Jun 2011 1:58:52]
C:\Program Files (x86)\Miranda NG\Plugins\Clist_modern.dll  14740000 - 147B0000 v.0.9.1.5 [25 Aug 2017 19:14:56]
C:\WINDOWS\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.0.15063.483_none_af46e7ffbdd00dcf\gdiplus.dll  5DB40000 - 5DCA6000 v.10.0.15063.483 [7 Jul 2017 8:14:30]
C:\WINDOWS\SYSTEM32\MSIMG32.dll  63A50000 - 63A56000 v.10.0.15063.0 [18 Mar 2017 22:58:59]
C:\Program Files (x86)\Miranda NG\Plugins\AIM.dll  14400000 - 1442A000 v.0.11.0.1 [25 Aug 2017 19:14:04]
C:\Program Files (x86)\Miranda NG\Plugins\AVS.dll  14560000 - 14572000 v.0.95.3.4 [25 Aug 2017 19:14:02]
C:\Program Files (x86)\Miranda NG\Plugins\Facebook.dll  14D60000 - 14DAF000 v.0.3.3.2 [25 Aug 2017 19:14:48]
C:\Program Files (x86)\Miranda NG\libs\libjson.mir  12400000 - 1240C000 [25 Aug 2017 19:14:02]
C:\Program Files (x86)\Miranda NG\Plugins\GG.dll  150A0000 - 150E3000 v.0.11.0.3 [25 Aug 2017 19:14:12]
C:\Program Files (x86)\Miranda NG\Plugins\HistoryPP.dll  15160000 - 1534F000 v.1.5.1.5 [28 Jun 2017 17:18:30]
C:\WINDOWS\SYSTEM32\winspool.drv  71B00000 - 71B6E000 v.10.0.15063.138 [1 Apr 2017 2:01:36]
C:\WINDOWS\SYSTEM32\bcrypt.dll  73210000 - 73228000 v.10.0.15063.0 [18 Mar 2017 22:58:47]
C:\WINDOWS\SYSTEM32\RICHED20.DLL  5DAC0000 - 5DB3D000 v.5.31.23.1231 [18 Mar 2017 22:58:59]
C:\WINDOWS\SYSTEM32\USP10.dll  625E0000 - 625F7000 v.10.0.15063.0 [18 Mar 2017 22:58:59]
C:\WINDOWS\SYSTEM32\msls31.dll  622C0000 - 622F2000 v.3.10.349.0 [18 Mar 2017 22:58:52]
C:\Program Files (x86)\Miranda NG\Plugins\ICQ.dll  15680000 - 156D2000 v.0.11.3.5 [25 Aug 2017 19:14:14]
C:\Program Files (x86)\Miranda NG\Plugins\IRC.dll  158C0000 - 1590E000 v.0.11.0.3 [25 Aug 2017 19:14:08]
C:\Program Files (x86)\Miranda NG\Plugins\Jabber.dll  15960000 - 15A04000 v.0.11.0.5 [25 Aug 2017 19:14:42]
C:\Program Files (x86)\Miranda NG\libs\LIBEAY32.mir  5D980000 - 5DABD000 v.1.0.2.12 [16 Feb 2017 18:13:10]
C:\Program Files (x86)\Miranda NG\libs\libaxolotl.mir  120A0000 - 120D0000 [25 Aug 2017 19:14:22]
C:\WINDOWS\SYSTEM32\DNSAPI.dll  73570000 - 735EF000 v.10.0.15063.0 [18 Mar 2017 22:58:44]
C:\WINDOWS\System32\NSI.dll  74AA0000 - 74AA7000 v.10.0.15063.0 [18 Mar 2017 22:57:35]
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL  73540000 - 7356F000 v.10.0.15063.0 [18 Mar 2017 22:58:44]
C:\Program Files (x86)\Miranda NG\Plugins\MSN.dll  15F60000 - 15F9E000 v.0.14.0.1 [25 Aug 2017 19:14:16]
C:\Program Files (x86)\Miranda NG\Plugins\mTextControl.dll  15FE0000 - 15FE9000 v.0.8.0.1 [25 Aug 2017 19:14:26]
C:\Program Files (x86)\Miranda NG\Plugins\NewEventNotify.dll  160A0000 - 160AA000 v.0.2.2.3 [25 Aug 2017 19:14:52]
C:\Program Files (x86)\Miranda NG\Plugins\PluginUpdater.dll  16400000 - 16414000 v.0.1.2.5 [25 Aug 2017 19:15:02]
C:\Program Files (x86)\Miranda NG\Plugins\Popup.dll  16460000 - 1649A000 v.2.1.1.12 [25 Aug 2017 19:14:30]
C:\Program Files (x86)\Miranda NG\Plugins\Scriver.dll  167E0000 - 16813000 v.3.0.1.7 [25 Aug 2017 19:14:04]
C:\Program Files (x86)\Miranda NG\Plugins\StatusManager.dll  16C40000 - 16C5B000 v.0.11.2.0 [25 Aug 2017 18:16:02]
C:\WINDOWS\SYSTEM32\WININET.dll  736A0000 - 73961000 v.11.0.15063.483 [7 Jul 2017 8:01:50]
C:\Program Files (x86)\Miranda NG\Plugins\TopToolBar.dll  16FC0000 - 16FCD000 v.0.8.0.4 [25 Aug 2017 19:14:48]
C:\Program Files (x86)\Miranda NG\Core\stduserinfo.dll  131C0000 - 131CC000 v.0.95.6.18429 [25 Aug 2017 19:16:24]
C:\Program Files (x86)\Miranda NG\Core\stdemail.dll  130A0000 - 130A6000 v.0.95.6.18429 [25 Aug 2017 19:16:24]
C:\Program Files (x86)\Miranda NG\Core\stdauth.dll  13000000 - 13007000 v.0.95.6.18429 [25 Aug 2017 19:16:22]
C:\Program Files (x86)\Miranda NG\Core\stdfile.dll  130C0000 - 130CF000 v.0.95.6.18429 [25 Aug 2017 19:16:24]
C:\Program Files (x86)\Miranda NG\Core\stdhelp.dll  130E0000 - 130E6000 v.0.95.6.18429 [25 Aug 2017 19:16:20]
C:\Program Files (x86)\Miranda NG\Core\stdidle.dll  13100000 - 13107000 v.0.95.6.18429 [25 Aug 2017 19:16:20]
C:\WINDOWS\SYSTEM32\WTSAPI32.dll  73EE0000 - 73EEF000 v.10.0.15063.0 [18 Mar 2017 22:58:58]
C:\Program Files (x86)\Miranda NG\Core\stdautoaway.dll  13020000 - 13026000 v.0.95.6.18429 [25 Aug 2017 19:16:24]
C:\Program Files (x86)\Miranda NG\Core\stduseronline.dll  131E0000 - 131E6000 v.0.95.6.18429 [25 Aug 2017 19:16:22]
C:\Program Files (x86)\Miranda NG\Core\stdaway.dll  13040000 - 13048000 v.0.95.6.18429 [25 Aug 2017 19:16:20]
C:\WINDOWS\system32\dataexchange.dll  59D20000 - 59D63000 v.10.0.15063.0 [18 Mar 2017 22:58:54]
C:\WINDOWS\system32\d3d11.dll  59AC0000 - 59D12000 v.10.0.15063.0 [18 Mar 2017 22:58:52]
C:\WINDOWS\system32\dcomp.dll  599D0000 - 59ABB000 v.10.0.15063.483 [7 Jul 2017 8:30:55]
C:\WINDOWS\system32\dxgi.dll  59940000 - 599CA000 v.10.0.15063.502 [28 Jul 2017 6:40:44]
C:\WINDOWS\system32\twinapi.appcore.dll  5CA60000 - 5CB96000 v.10.0.15063.332 [20 May 2017 10:46:58]
C:\WINDOWS\System32\TextInputFramework.dll  5A210000 - 5A277000 v.10.0.15063.502 [28 Jul 2017 6:33:06]
C:\WINDOWS\System32\CoreUIComponents.dll  50D70000 - 50F97000 v.10.0.15063.502 [28 Jul 2017 6:47:10]
C:\WINDOWS\System32\CoreMessaging.dll  5A0D0000 - 5A15F000 v.10.0.15063.502 [28 Jul 2017 6:33:17]
C:\WINDOWS\SYSTEM32\ntmarta.dll  6E4C0000 - 6E4E8000 v.10.0.15063.0 [18 Mar 2017 22:58:50]
C:\WINDOWS\SYSTEM32\wintypes.dll  632F0000 - 633C1000 v.10.0.15063.0 [18 Mar 2017 22:58:48]
C:\WINDOWS\SYSTEM32\usermgrcli.dll  59DC0000 - 59DD0000 v.10.0.15063.0 [18 Mar 2017 22:58:48]
C:\Windows\System32\oleacc.dll  71AA0000 - 71AF6000 v.7.2.15063.447 [20 Jun 2017 6:49:36]
C:\WINDOWS\system32\mswsock.dll  71040000 - 7108E000 v.10.0.15063.0 [18 Mar 2017 22:58:44]
C:\Windows\System32\rasadhlp.dll  6F990000 - 6F998000 v.10.0.15063.0 [18 Mar 2017 22:58:45]
C:\WINDOWS\System32\fwpuclnt.dll  6EC50000 - 6EC9A000 v.10.0.15063.0 [18 Mar 2017 22:58:48]
C:\WINDOWS\SYSTEM32\schannel.dll  63520000 - 63586000 v.10.0.15063.0 [18 Mar 2017 22:58:49]
C:\WINDOWS\SYSTEM32\mskeyprotect.dll  63B90000 - 63BA0000 v.10.0.15063.0 [18 Mar 2017 22:58:47]
C:\WINDOWS\SYSTEM32\ncrypt.dll  63B70000 - 63B90000 v.10.0.15063.0 [18 Mar 2017 22:58:48]
C:\WINDOWS\SYSTEM32\NTASN1.dll  634D0000 - 634FC000 v.10.0.15063.0 [18 Mar 2017 22:58:47]
C:\WINDOWS\system32\ncryptsslp.dll  634B0000 - 634CB000 v.10.0.15063.0 [18 Mar 2017 22:58:46]
C:\WINDOWS\SYSTEM32\iertutil.dll  71090000 - 712A2000 v.11.0.15063.540 [1 Aug 2017 4:36:19]
C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll  6FC60000 - 6FC75000 v.10.0.15063.0 [18 Mar 2017 22:58:54]
C:\WINDOWS\SYSTEM32\winhttp.dll  735F0000 - 7369D000 v.10.0.15063.0 [18 Mar 2017 22:58:49]
C:\WINDOWS\SYSTEM32\WINNSI.DLL  71B70000 - 71B78000 v.10.0.15063.0 [18 Mar 2017 22:57:35]
C:\Windows\System32\Windows.Globalization.dll  51FB0000 - 520E2000 v.10.0.15063.0 [18 Mar 2017 22:58:52]
C:\Windows\System32\Bcp47Langs.dll  5A080000 - 5A0D0000 v.10.0.15063.0 [18 Mar 2017 22:58:47]
C:\WINDOWS\SYSTEM32\globinputhost.dll  5A050000 - 5A074000 v.10.0.15063.0 [18 Mar 2017 22:58:49]
C:\WINDOWS\System32\coml2.dll  74160000 - 741BE000 v.10.0.15063.0 [18 Mar 2017 22:58:54]
C:\WINDOWS\SYSTEM32\edputil.dll  61F10000 - 61F4C000 v.10.0.15063.447 [20 Jun 2017 6:40:06]
C:\WINDOWS\SYSTEM32\PROPSYS.dll  6F7E0000 - 6F944000 v.7.0.15063.0 [18 Mar 2017 22:58:51]
C:\Windows\System32\OneCoreUAPCommonProxyStub.dll  77D80000 - 77FF8000 v.10.0.15063.0 [18 Mar 2017 22:58:54]
C:\WINDOWS\SYSTEM32\urlmon.dll  606E0000 - 6087C000 v.11.0.15063.540 [1 Aug 2017 4:03:26]
C:\Windows\System32\Windows.Shell.ServiceHostBuilder.dll  0FD60000 - 0FD74000 v.10.0.15063.0 [18 Mar 2017 22:58:52]
C:\WINDOWS\SYSTEM32\MLANG.dll  5EE40000 - 5EE74000 v.10.0.15063.0 [18 Mar 2017 22:58:47]
C:\WINDOWS\system32\apphelp.dll  74090000 - 74123000 v.10.0.15063.447 [20 Jun 2017 6:28:14]
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL  6FC40000 - 6FC53000 v.10.0.15063.0 [18 Mar 2017 22:58:44]
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL  6FC20000 - 6FC34000 v.10.0.15063.0 [18 Mar 2017 22:58:44]
`

**Comment by georgehazan** [comment]
switch, please, to development version with symbols
(Options - Plugin Updater - third option)
and remake a log. without debug info it's pretty useless

**Comment by georgehazan** [comment]
@makedir knock-knock

**Comment by makedir** [comment]
@georgehazan I havent got the crash anymore since two or three weeks. Not sure if it is fixed because there was a Miranda-ng update during that time, or it's just random chance.

**Comment by georgehazan** [comment]
okay. keep this email and reopen this bug when you have the appropriate crash log
