### ISSUE TITLE
"Updates found" despite switching to stable update path

### ISSUE THREAD

**Issue by sagamusix** [miranda-ng/miranda-ng#913]
I have used the previous development versions but now that there finally is a new stable version, I wanted to switch back to that.

### Expected behavior
After downloading and installing Miranda NG 0.95.6 stable and setting the updater settings to "stable", it should currently not find any updates.

### Actual behavior
I am getting daily update notifications about new builds.

### Does it work in stable version?
No!

**Comment by georgehazan** [comment]
the stable build is reassembled quite often now because of bugfixes
plugin updater works pretty good :)
