### ISSUE TITLE
Miranda NG is crashing as I open the Chat Window

### ISSUE THREAD

**Issue by winman3000** [miranda-ng/miranda-ng#917]
# Expected behavior
When I open the Chat Window, I should see the history and I should be able to write anything.

# Actual behavior
As I open the Chat Window, Miranda NG crashes (error log is atached).

# Does it work in stable version?
As I could see, this is broken in the current builds only.

# Steps to reproduce that behavior
 * Be sure that you are using StdMsg for chats.
 * Select the contact you want to chat with and press enter.
## Result
Miranda is crashes with an error report.

## Crash Report
Miranda Crash Report from 5 Sep 2017 13:58:55. Crash Dumper v.0.0.5.2
Exception: Access Violation at address 00000000126BAADA. Reading from address 0000000000000034.

Stack Trace:
---------------------------------------------------------------
00000000126BAADA (mir_app 00000000126A0000): (filename not available) (0): Ordinal439
00000000126B88A1 (mir_app 00000000126A0000): (filename not available) (0): Ordinal447
000000001288AA35 (mir_core 0000000012880000): (filename not available) (0): mir_forkthread
00000000773F9BBD (USER32 00000000773E0000): (filename not available) (0): TranslateMessageEx
00000000773F729B (USER32 00000000773E0000): (filename not available) (0): SetWindowTextW
00000000773F67E9 (USER32 00000000773E0000): (filename not available) (0): IsDialogMessageW
000000007764BC65 (ntdll 0000000077600000): (filename not available) (0): KiUserCallbackDispatcher
00000000773F6E2A (USER32 00000000773E0000): (filename not available) (0): BeginPaint
00000000773F6E3C (USER32 00000000773E0000): (filename not available) (0): BeginPaint
00000000773F6782 (USER32 00000000773E0000): (filename not available) (0): IsDialogMessageW
00000000126D413A (mir_app 00000000126A0000): (filename not available) (0): mir_main
00000001400019C5 (Miranda64 0000000140000000): (filename not available) (0): (function-name not available)
00000001400011FE (Miranda64 0000000140000000): (filename not available) (0): (function-name not available)
00000000774F59CD (kernel32 00000000774E0000): (filename not available) (0): BaseThreadInitThunk
000000007762A561 (ntdll 0000000077600000): (filename not available) (0): RtlUserThreadStart

CPU: Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz [Intel64 Family 6 Model 60 Stepping 3] [DEP Enabled] [4 CPUs]
Installed RAM: 7907 MBytes
Microsoft Windows 7 Professional Edition, 64-bit Service Pack 1 (build 7601)
Internet Explorer: 9.11.9600.18762 (build 99600)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : German/German | German/German

Miranda NG Version: 0.95.7 alpha build #18482 (2bf6c99) x64
Build time: 5 Sep 2017 14:27:08
Profile: C:\Users\asa\AppData\Roaming\Miranda NG\Ali\Ali.dat (dbx mmap driver)
Language pack: German (DE) [0407]
Service Mode: No

Active Plugins (15):
¤ AdvaImg.dll v.0.11.0.2 [5 Sep 2017 14:27:58] - Miranda image services 
¤ AIM.dll v.0.11.0.1 [7 Aug 2017 4:25:46] - AIM protocol 
¤ AVS.dll v.0.95.3.4 [7 Aug 2017 4:25:12] - Avatar service 
¤ Clist_blind.dll v.0.8.1.1 [7 Aug 2017 4:32:20] - BClist 
¤ CrashDumper.dll v.0.0.5.2 [7 Aug 2017 4:30:56] - Crash dumper 
¤ Dbx_mmap.dll v.0.95.3.1 [5 Sep 2017 14:27:12] - Miranda NG mmap database driver 
¤ Facebook.dll v.0.3.3.2 [5 Sep 2017 14:27:36] - Facebook RM 
¤ GG.dll v.0.11.0.3 [5 Sep 2017 14:27:20] - Gadu-Gadu protocol 
¤ ICQ.dll v.0.11.3.5 [5 Sep 2017 14:27:14] - IcqOscarJ protocol 
¤ Import.dll v.0.95.4.3 [7 Aug 2017 4:25:16] - Import contacts and messages 
¤ IRC.dll v.0.11.0.3 [5 Sep 2017 14:27:12] - IRC protocol 
¤ Jabber.dll v.0.11.0.5 [5 Sep 2017 14:27:32] - Jabber protocol 
¤ MSN.dll v.0.14.0.1 [5 Sep 2017 14:27:22] - MSN protocol 
¤ PluginUpdater.dll v.0.1.2.5 [5 Sep 2017 14:27:38] - Plugin updater 
¤ StdMsg.dll v.0.95.6.18214 [6 Jun 2017 4:10:14] - Send/Receive Messages 

Loaded Modules:
-------------------------------------------------------------------------------
C:\Program Files\Miranda NG\Miranda64.exe  0000000140000000 - 000000014000A000 v.0.95.7.18482 [5 Sep 2017 14:27:08]
C:\Windows\SYSTEM32\ntdll.dll  0000000077600000 - 00000000777AA000 v.6.1.7601.23864 [7 Jul 2017 17:31:14]
C:\Windows\system32\kernel32.dll  00000000774E0000 - 00000000775FF000 v.6.1.7601.23864 [7 Jul 2017 17:29:33]
C:\Windows\system32\KERNELBASE.dll  000007FEFD3B0000 - 000007FEFD41A000 v.6.1.7601.23864 [7 Jul 2017 17:29:33]
C:\Windows\system32\USER32.dll  00000000773E0000 - 00000000774DA000 v.6.1.7601.23594 [10 Nov 2016 18:32:41]
C:\Windows\system32\GDI32.dll  000007FEFD6B0000 - 000007FEFD717000 v.6.1.7601.23807 [12 May 2017 20:22:32]
C:\Windows\system32\LPK.dll  000007FEFD790000 - 000007FEFD79E000 v.6.1.7601.23807 [12 May 2017 20:22:33]
C:\Windows\system32\USP10.dll  000007FEFDEF0000 - 000007FEFDFBB000 v.1.626.7601.23807 [12 May 2017 20:22:44]
C:\Windows\system32\msvcrt.dll  000007FEFE0E0000 - 000007FEFE17F000 v.7.0.7601.17744 [16 Dec 2011 10:46:06]
C:\Windows\system32\MSVCR100.dll  0000000073580000 - 0000000073652000 v.10.0.40219.325 [11 Jun 2011 1:15:38]
C:\Windows\system32\IMM32.DLL  000007FEFF800000 - 000007FEFF82E000 v.6.1.7600.16385 [14 Jul 2009 3:41:09]
C:\Windows\system32\MSCTF.dll  000007FEFE180000 - 000007FEFE289000 v.6.1.7601.23572 [11 Oct 2016 17:31:58]
C:\Program Files\Miranda NG\libs\mir_app.mir  00000000126A0000 - 000000001278F000 v.0.95.7.18482 [5 Sep 2017 14:27:08]
C:\Windows\system32\WINMM.dll  000007FEFA7F0000 - 000007FEFA82B000 v.6.1.7600.16385 [14 Jul 2009 3:41:56]
C:\Windows\system32\SHLWAPI.dll  000007FEFE060000 - 000007FEFE0D1000 v.6.1.7601.17514 [21 Nov 2010 5:24:22]
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.18837_none_fa3b1e3d17594757\COMCTL32.dll  000007FEFB780000 - 000007FEFB974000 v.6.10.7601.18837 [24 Apr 2015 20:12:05]
C:\Windows\system32\WS2_32.dll  000007FEFD740000 - 000007FEFD78D000 v.6.1.7601.23451 [11 May 2016 19:02:50]
C:\Windows\system32\RPCRT4.dll  000007FEFE750000 - 000007FEFE87D000 v.6.1.7601.23864 [7 Jul 2017 17:29:39]
C:\Windows\system32\NSI.dll  000007FEFE740000 - 000007FEFE748000 v.6.1.7600.16385 [14 Jul 2009 3:41:53]
C:\Windows\system32\UxTheme.dll  000007FEFB0E0000 - 000007FEFB136000 v.6.1.7600.16385 [14 Jul 2009 3:41:56]
C:\Windows\system32\COMDLG32.dll  000007FEFDFC0000 - 000007FEFE057000 v.6.1.7601.17514 [21 Nov 2010 5:24:22]
C:\Windows\system32\SHELL32.dll  000007FEFE880000 - 000007FEFF60B000 v.6.1.7601.23806 [10 May 2017 17:29:53]
C:\Windows\system32\ADVAPI32.dll  000007FEFE660000 - 000007FEFE73B000 v.6.1.7601.23864 [7 Jul 2017 17:29:28]
C:\Windows\SYSTEM32\sechost.dll  000007FEFE290000 - 000007FEFE2AF000 v.6.1.7601.18869 [25 May 2015 20:19:09]
C:\Windows\system32\ole32.dll  000007FEFD840000 - 000007FEFDA3C000 v.6.1.7601.23775 [17 Apr 2017 17:37:29]
C:\Program Files\Miranda NG\libs\zlib.mir  00000000129E0000 - 00000000129FD000 v.1.2.11.0 [5 Sep 2017 14:26:58]
C:\Program Files\Miranda NG\libs\mir_core.mir  0000000012880000 - 00000000128AD000 [5 Sep 2017 14:27:00]
C:\Windows\system32\VERSION.dll  000007FEFC3A0000 - 000007FEFC3AC000 v.6.1.7600.16385 [14 Jul 2009 3:41:56]
C:\Windows\system32\Secur32.dll  000007FEFCF30000 - 000007FEFCF3B000 v.6.1.7601.23864 [7 Jul 2017 17:29:39]
C:\Windows\system32\SSPICLI.DLL  000007FEFD100000 - 000007FEFD125000 v.6.1.7601.23864 [7 Jul 2017 17:29:44]
C:\Windows\system32\dwmapi.dll  000007FEFB200000 - 000007FEFB218000 v.6.1.7601.18917 [9 Jul 2015 19:58:26]
C:\Windows\system32\CRYPTBASE.dll  000007FEFD190000 - 000007FEFD19F000 v.6.1.7601.23864 [7 Jul 2017 17:29:30]
C:\Windows\system32\CLBCatQ.DLL  000007FEFD7A0000 - 000007FEFD839000 v.2001.12.8530.16385 [14 Jul 2009 3:40:15]
C:\Windows\system32\OLEAUT32.dll  000007FEFF830000 - 000007FEFF90A000 v.6.1.7601.23775 [17 Apr 2017 17:37:29]
C:\Windows\system32\explorerframe.dll  000007FEEC460000 - 000007FEEC62A000 v.6.1.7601.23836 [6 Jun 2017 17:30:28]
C:\Windows\system32\DUser.dll  000007FEFA760000 - 000007FEFA7A3000 v.6.1.7600.16385 [14 Jul 2009 3:40:34]
C:\Windows\system32\DUI70.dll  000007FEFA830000 - 000007FEFA922000 v.6.1.7600.16385 [14 Jul 2009 3:40:34]
C:\Program Files\Miranda NG\Plugins\CrashDumper.dll  0000000014C00000 - 0000000014C14000 v.0.0.5.2 [7 Aug 2017 4:30:56]
C:\Windows\system32\dbghelp.dll  000007FEFB2D0000 - 000007FEFB3F5000 v.6.1.7601.17514 [21 Nov 2010 5:24:00]
C:\Program Files\Miranda NG\Plugins\Dbx_mmap.dll  00000000154A0000 - 00000000154B6000 v.0.95.3.1 [5 Sep 2017 14:27:12]
C:\Program Files\Miranda NG\Plugins\Import.dll  0000000015E00000 - 0000000015E11000 v.0.95.4.3 [7 Aug 2017 4:25:16]
C:\Program Files\Miranda NG\Core\stdcrypt.dll  00000000130A0000 - 00000000130AD000 v.0.95.7.18482 [5 Sep 2017 14:27:04]
C:\Windows\system32\CRYPTSP.dll  000007FEFCB20000 - 000007FEFCB38000 v.6.1.7601.23471 [14 Jun 2016 19:16:25]
C:\Windows\system32\rsaenh.dll  000007FEFC820000 - 000007FEFC867000 v.6.1.7600.16385 [14 Jul 2009 3:43:15]
C:\Windows\system32\RpcRtRemote.dll  000007FEFD240000 - 000007FEFD254000 v.6.1.7601.17514 [21 Nov 2010 5:24:01]
C:\Windows\system32\actxprxy.dll  000007FEEB000000 - 000007FEEB0EE000 v.6.1.7601.17514 [21 Nov 2010 5:23:48]
C:\Windows\system32\SETUPAPI.dll  000007FEFDD10000 - 000007FEFDEE7000 v.6.1.7601.17514 [21 Nov 2010 5:24:28]
C:\Windows\system32\CFGMGR32.dll  000007FEFD5A0000 - 000007FEFD5D6000 v.6.1.7601.17514 [21 Nov 2010 5:24:00]
C:\Windows\system32\DEVOBJ.dll  000007FEFD690000 - 000007FEFD6AA000 v.6.1.7600.16385 [14 Jul 2009 3:40:28]
C:\Windows\system32\propsys.dll  000007FEFBFA0000 - 000007FEFC0CC000 v.7.0.7601.17514 [21 Nov 2010 5:23:55]
C:\Windows\system32\ntmarta.dll  000007FEFBE30000 - 000007FEFBE5D000 v.6.1.7600.16385 [14 Jul 2009 3:41:53]
C:\Windows\system32\WLDAP32.dll  000007FEFF7A0000 - 000007FEFF7F2000 v.6.1.7601.23840 [10 Jun 2017 17:59:44]
C:\Windows\system32\mssprxy.dll  000007FEE6380000 - 000007FEE639D000 v.7.0.7601.23877 [14 Jul 2017 17:29:04]
C:\Windows\system32\profapi.dll  000007FEFD2F0000 - 000007FEFD2FF000 v.6.1.7600.16385 [14 Jul 2009 3:41:53]
C:\Program Files\Miranda NG\Core\stdssl.dll  00000000131E0000 - 00000000131E9000 v.0.95.7.18482 [5 Sep 2017 14:27:04]
C:\Windows\system32\CRYPT32.dll  000007FEFD430000 - 000007FEFD59D000 v.6.1.7601.23769 [12 Apr 2017 17:32:10]
C:\Windows\system32\MSASN1.dll  000007FEFD300000 - 000007FEFD30F000 v.6.1.7601.17514 [21 Nov 2010 5:24:22]
C:\Windows\system32\WSOCK32.dll  000007FEFB2C0000 - 000007FEFB2C9000 v.6.1.7600.16385 [14 Jul 2009 3:41:58]
C:\Windows\system32\Msftedit.dll  000007FEEE7E0000 - 000007FEEE8A6000 v.5.41.21.2510 [21 Nov 2010 5:24:01]
C:\Program Files\Miranda NG\Plugins\AdvaImg.dll  0000000014940000 - 00000000149F2000 v.0.11.0.2 [5 Sep 2017 14:27:58]
C:\Windows\system32\MSVCP100.dll  00000000734E0000 - 0000000073578000 v.10.0.40219.325 [11 Jun 2011 1:15:38]
C:\Program Files\Miranda NG\Plugins\Clist_blind.dll  0000000014860000 - 0000000014873000 v.0.8.1.1 [7 Aug 2017 4:32:20]
C:\Program Files\Miranda NG\Plugins\AIM.dll  00000000144A0000 - 00000000144D5000 v.0.11.0.1 [7 Aug 2017 4:25:46]
C:\Program Files\Miranda NG\Plugins\AVS.dll  0000000014640000 - 0000000014656000 v.0.95.3.4 [7 Aug 2017 4:25:12]
C:\Program Files\Miranda NG\Plugins\Facebook.dll  0000000015620000 - 000000001568D000 v.0.3.3.2 [5 Sep 2017 14:27:36]
C:\Program Files\Miranda NG\libs\libjson.mir  0000000012660000 - 0000000012673000 [5 Sep 2017 14:27:12]
C:\Program Files\Miranda NG\Plugins\GG.dll  00000000159C0000 - 0000000015A0B000 v.0.11.0.3 [5 Sep 2017 14:27:20]
C:\Program Files\Miranda NG\Plugins\ICQ.dll  0000000016240000 - 00000000162AB000 v.0.11.3.5 [5 Sep 2017 14:27:14]
C:\Program Files\Miranda NG\Plugins\IRC.dll  0000000016440000 - 000000001649A000 v.0.11.0.3 [5 Sep 2017 14:27:12]
C:\Program Files\Miranda NG\Plugins\Jabber.dll  0000000016500000 - 00000000165C9000 v.0.11.0.5 [5 Sep 2017 14:27:32]
C:\Program Files\Miranda NG\libs\LIBEAY32.mir  00000000742A0000 - 00000000744A5000 v.1.0.2.12 [16 Feb 2017 19:26:02]
C:\Program Files\Miranda NG\libs\libaxolotl.mir  00000000120C0000 - 00000000120EF000 [5 Sep 2017 14:27:18]
C:\Windows\system32\DNSAPI.dll  000007FEFC940000 - 000007FEFC99B000 v.6.1.7601.17570 [3 Mar 2011 8:24:15]
C:\Program Files\Miranda NG\Plugins\MSN.dll  0000000016C40000 - 0000000016C8C000 v.0.14.0.1 [5 Sep 2017 14:27:22]
C:\Program Files\Miranda NG\Plugins\PluginUpdater.dll  00000000171E0000 - 00000000171F9000 v.0.1.2.5 [5 Sep 2017 14:27:38]
C:\Program Files\Miranda NG\Plugins\StdMsg.dll  0000000013160000 - 0000000013192000 v.0.95.6.18214 [6 Jun 2017 4:10:14]
C:\Program Files\Miranda NG\Core\stduserinfo.dll  0000000013220000 - 000000001322E000 v.0.95.7.18482 [5 Sep 2017 14:27:04]
C:\Program Files\Miranda NG\Core\stdemail.dll  00000000130C0000 - 00000000130C7000 v.0.95.7.18482 [5 Sep 2017 14:27:02]
C:\Program Files\Miranda NG\Core\stdauth.dll  0000000013000000 - 0000000013009000 v.0.95.7.18482 [5 Sep 2017 14:27:04]
C:\Program Files\Miranda NG\Core\stdfile.dll  00000000130E0000 - 00000000130F3000 v.0.95.7.18482 [5 Sep 2017 14:27:04]
C:\Program Files\Miranda NG\Core\stdhelp.dll  0000000013120000 - 0000000013128000 v.0.95.7.18482 [5 Sep 2017 14:27:02]
C:\Program Files\Miranda NG\Core\stduihist.dll  0000000013200000 - 0000000013209000 v.0.95.7.18482 [5 Sep 2017 14:27:02]
C:\Program Files\Miranda NG\Core\stdidle.dll  0000000013140000 - 0000000013148000 v.0.95.7.18482 [5 Sep 2017 14:27:02]
C:\Windows\system32\WTSAPI32.dll  000007FEFC540000 - 000007FEFC551000 v.6.1.7600.16385 [14 Jul 2009 3:41:58]
C:\Program Files\Miranda NG\Core\stdautoaway.dll  0000000013020000 - 0000000013027000 v.0.95.7.18482 [5 Sep 2017 14:27:02]
C:\Program Files\Miranda NG\Core\stduseronline.dll  0000000013240000 - 0000000013247000 v.0.95.7.18482 [5 Sep 2017 14:27:02]
C:\Program Files\Miranda NG\Core\stdaway.dll  0000000013040000 - 000000001304A000 v.0.95.7.18482 [5 Sep 2017 14:27:04]
C:\Windows\system32\OLEACC.dll  000007FEF9980000 - 000007FEF99D4000 v.7.0.0.0 [27 Aug 2011 7:37:48]
C:\Windows\system32\uiautomationcore.dll  000007FEF2510000 - 000007FEF25CA000 v.7.0.0.0 [14 Jul 2009 3:41:55]
C:\Windows\system32\PSAPI.DLL  00000000777C0000 - 00000000777C7000 v.6.1.7600.16385 [14 Jul 2009 3:41:53]
C:\Windows\system32\mswsock.dll  000007FEFCAC0000 - 000007FEFCB15000 v.6.1.7601.23451 [11 May 2016 19:02:42]
C:\Windows\System32\wshtcpip.dll  000007FEFC470000 - 000007FEFC477000 v.6.1.7600.16385 [14 Jul 2009 3:41:58]
C:\Windows\System32\wship6.dll  000007FEFCAB0000 - 000007FEFCAB7000 v.6.1.7600.16385 [14 Jul 2009 3:41:58]
C:\Windows\system32\IPHLPAPI.DLL  000007FEFB290000 - 000007FEFB2B7000 v.6.1.7601.17514 [21 Nov 2010 5:24:16]
C:\Windows\system32\WINNSI.DLL  000007FEFB280000 - 000007FEFB28B000 v.6.1.7600.16385 [14 Jul 2009 3:41:56]
C:\Windows\system32\rasadhlp.dll  000007FEEF080000 - 000007FEEF088000 v.6.1.7600.16385 [14 Jul 2009 3:41:53]
C:\Windows\System32\fwpuclnt.dll  000007FEF9F10000 - 000007FEF9F63000 v.6.1.7601.18283 [12 Oct 2013 4:29:08]
C:\Windows\system32\schannel.dll  000007FEFC8B0000 - 000007FEFC908000 v.6.1.7601.23864 [7 Jul 2017 17:29:39]
C:\Windows\system32\credssp.dll  000007FEFC6F0000 - 000007FEFC6FA000 v.6.1.7601.23864 [7 Jul 2017 17:29:30]
C:\Windows\system32\ncrypt.dll  000007FEFCCA0000 - 000007FEFCCF0000 v.6.1.7601.23864 [7 Jul 2017 17:29:35]
C:\Windows\system32\bcrypt.dll  000007FEFCC70000 - 000007FEFCC92000 v.6.1.7601.23864 [7 Jul 2017 17:29:29]
C:\Windows\system32\bcryptprimitives.dll  000007FEFC760000 - 000007FEFC7AC000 v.6.1.7601.23451 [12 May 2016 15:05:59]
C:\Windows\system32\NLAapi.dll  000007FEFB9E0000 - 000007FEFB9F5000 v.6.1.7601.17964 [3 Oct 2012 19:44:21]
C:\Windows\system32\napinsp.dll  000007FEEE6A0000 - 000007FEEE6B5000 v.6.1.7600.16385 [14 Jul 2009 3:41:52]
C:\Windows\system32\pnrpnsp.dll  000007FEEE570000 - 000007FEEE589000 v.6.1.7600.16385 [14 Jul 2009 3:41:53]
C:\Windows\System32\winrnr.dll  000007FEEE530000 - 000007FEEE53B000 v.6.1.7600.16385 [14 Jul 2009 3:41:56]
C:\Windows\system32\wshbth.dll  000007FEEE520000 - 000007FEEE530000 v.6.1.7601.17514 [21 Nov 2010 5:24:36]
C:\Windows\system32\MMDevAPI.DLL  000007FEFC0D0000 - 000007FEFC11B000 v.6.1.7600.16385 [14 Jul 2009 3:41:26]
C:\Windows\system32\wdmaud.drv  000007FEFA7B0000 - 000007FEFA7EB000 v.6.1.7601.17514 [21 Nov 2010 5:24:32]
C:\Windows\system32\ksuser.dll  0000000075050000 - 0000000075056000 v.6.1.7601.19091 [8 Dec 2015 21:07:31]
C:\Windows\system32\AVRT.dll  000007FEFBE60000 - 000007FEFBE69000 v.6.1.7600.16385 [14 Jul 2009 3:40:05]
C:\Windows\system32\AUDIOSES.DLL  000007FEFA6D0000 - 000007FEFA71F000 v.6.1.7601.23471 [14 Jun 2016 19:16:23]
C:\Windows\system32\msacm32.drv  000007FEFA680000 - 000007FEFA68A000 v.6.1.7600.16385 [14 Jul 2009 3:38:50]
C:\Windows\system32\MSACM32.dll  000007FEFA660000 - 000007FEFA678000 v.6.1.7600.16385 [14 Jul 2009 3:41:27]
C:\Windows\system32\midimap.dll  000007FEFA650000 - 000007FEFA659000 v.6.1.7600.16385 [14 Jul 2009 3:41:23]
C:\Program Files (x86)\NVDA\lib64\nvdaHelperRemote.dll  000007FEEDB70000 - 000007FEEDC0D000 v.2017.3.0.14335 [24 Aug 2017 13:01:10]
C:\Windows\system32\api-ms-win-core-synch-l1-2-0.DLL  000007FEFB1F0000 - 000007FEFB1F3000 v.10.0.10586.788 [18 Jan 2017 17:36:12]
C:\Program Files (x86)\NVDA\lib64\minhook.dll  000007FEEE7B0000 - 000007FEEE7D6000 v.1.2.2.0 [24 Aug 2017 13:00:50]
C:\Program Files (x86)\NVDA\lib64\IAccessible2Proxy.dll  000007FEEE720000 - 000007FEEE73F000 [24 Aug 2017 13:00:44]
C:\Windows\system32\msls31.dll  000007FEEAAF0000 - 000007FEEAB32000 v.3.10.349.0 [1 Apr 2014 13:04:40]

**Comment by georgehazan** [comment]
switch, please, to development version with symbols
(Options - Plugin Updater - third option)
and remake a crash log. without debug info it's pretty useless

**Comment by winman3000** [comment]
[crash20170905143504.zip](https://github.com/miranda-ng/miranda-ng/files/1277395/crash20170905143504.zip)
Hope this helps more...

**Comment by georgehazan** [comment]
yes, much better now, thanks

**Comment by georgehazan** [comment]
@winman3000 do you enter the private or a group chat?

**Comment by winman3000** [comment]
I entered a private chat.

**Comment by winman3000** [comment]
@georgehazan: Any News about this Bug? I still have this Problem.

**Comment by georgehazan** [comment]
I can't reproduce it :( moreover, I even cannot imagine how this call stack could happen if you enter the private chat

**Comment by georgehazan** [comment]
@winman3000 btw does it happen on any contact or on the concrete contact?

**Comment by winman3000** [comment]
@georgehazan: I'm using a Screen Reader (JAWS and NVDA). Could MSAA or 
any of the accessibility API cause this? If yes, it is a fault of 
Miranda-NG, but I couldn't reproduce in the last weeks.

**Comment by winman3000** [comment]
@georgehazan: it happens with all Facebook contacts.

**Comment by georgehazan** [comment]
just yesterday we discovered that a NVDA module that embeds into any windows program causes crashes inside Miranda. if you could try to disable it somehow and try without it...

**Comment by winman3000** [comment]
@georgehazan: I've tested this without an active Screen Reader and I 
still get the crash. I could sent you my profile, but this is very 
private...

**Comment by georgehazan** [comment]
Well, I have very strong reputation of a man who guarantees absolute privacy of all data sent to me, for years. Yes, if you can email me your profile in a ZIP, it can greatly help me. My email is ghazan@miranda.im

**Comment by georgehazan** [comment]
@winman3000 btw, if you have the dbeditor++ plugin, export please the contact that crashes into a text file and attach it here

**Comment by winman3000** [comment]
@GeorgeHazan: it occurs with all contacts. I’ll sent you my profile tomorrow.

**Comment by georgehazan** [comment]
ok, thanks

**Comment by winman3000** [comment]
@GeorgeHazan: a reinstall solved the Problem. Thank you for your Help. I realy don't know what caused the Problem. All I know is that it didn't work after updating.

**Comment by georgehazan** [comment]
sorry, reinstall of what? Miranda? Windows? smth else? :)
any answer would be valuable, cause if you've met this problem, anyone else will definitely do

**Comment by winman3000** [comment]
@GeorgeHazan <https://github.com/GeorgeHazan>: I've reinstalled Miranda 
IM X64. Perhaps McAfee caused the problem after updating with the plugin 
updater. For now, all is working as expected.


Am 08.09.2017 um 10:16 schrieb George Hazan:

**Comment by Robyer** [comment]
I see that problem was that you had StdMsg.dll plugin in Plugins folder (and it was perhaps some old version too). In clean Miranda is StdMsg.dll in Core/* folder.
