### ISSUE TITLE
Toolbar isn't shown after disabling

### ISSUE THREAD

**Issue by Gynaecologist** [miranda-ng/miranda-ng#919]
### Expected behavior
Enable "Toolbar" frame back after disabling

### Actual behavior
Frame does not become visible, although the checkmark appears

### Does it work in stable version?
no (0.95.6 any buids)

### Steps to reproduce that behavior
unpack miranda-ng-v0.95.6.7z, skip account creation. Click Main menu >> frames >> toolbar >> uncheck toolbar. Now Exit application, run it again. Now, try enable it again.

**Comment by georgehazan** [comment]
confirmed
