### ISSUE TITLE
Problem with animate smileys

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#925]
Reported by @Mataes in the conference.

IEView + [Smileys.zip](https://github.com/miranda-ng/miranda-ng/files/1296834/Smileys.zip)

Animate smileys only in preview, but not in private (with IEView) or group chats (without IEView).
Send smiley, reopen contact window -> show next smiley frame.

> [19:19:47]	MikalaiR: В ieview этот старый баг 
> [19:20:12]	MikalaiR: Смайлики периодически начинают обновляться только при действиях с dom

**Comment by Mataes** [comment]
fixed in bffce5c
