### ISSUE TITLE
After recent updates Miranda keep crashing

### ISSUE THREAD

**Issue by SmilingSpectre** [miranda-ng/miranda-ng#927]
### Expected behavior
Work

### Actual behavior
Crash in random time intervals (once per day, sometimes more often)

### Does it work in stable version?
It's stable version.

### Steps to reproduce that behavior
Crashlog+VersionInfo
[2017.09.14.zip](https://github.com/miranda-ng/miranda-ng/files/1301010/2017.09.14.zip)

**Comment by dartraiden** [comment]
Try to remove OpenSSL plugin (OpenSSL.dll). It needs only on XP and produces crashes on modern Windows.

**Comment by SmilingSpectre** [comment]
Aha. I suspected it after checking my crash logs (OpenSSL appears here too
often, it seems). But there is the nuance. It's here exactly because I need
Miranda in WinXP. And Steam plugin is the reason of it. I tried to remove
OpenSSL yesterday, actually. After that Steam stops working in XP. :(

Well, can I take this answer as "there is no simple solution of my problem"?

Sincerely yours, Oleg Vladimirovych Bobryshev 

  _____

**Comment by georgehazan** [comment]
if you have a roaming profile that should work both under XP & 7+, you can use automatically executed ini files (like autoexec_blablabla.ini). these ini files should contain the only line of the OpenSsl plugin locking/unlocking, so you can easily create a batch file that runs Miranda with or without this plugin.

[autoexec_enable.zip](https://github.com/miranda-ng/miranda-ng/files/1303720/autoexec_enable.zip)

**Comment by SmilingSpectre** [comment]
Well, it crashed on XP too. But at least it can remove problems with Win10.
Thank you!

Sincerely yours, Oleg Vladimirovych Bobryshev 
 

  _____

**Comment by georgehazan** [comment]
well, right now we cannot fix a crash with openssl, it requires a long & thorough investigation, so at least you can easily avoid a problem under Windows 10

**Comment by dartraiden** [comment]
Closed in favor of #930

**Comment by dartraiden** [comment]
Added hint about .ini to [our wiki](https://wiki.miranda-ng.org/index.php?title=Plugin:OpenSSL/en).
