### ISSUE TITLE
Random crashes in conference nicklist after language changed

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#935]
1) Open conference, see info about some member
2) Leave TabSRMM open, change Miranda language (I change from Russian to English)
3) See info about this member again

Sometimes (rarely, but 2 crashes for 20 tries for me) Miranda crashes immediately after right click on conference member on step 3

[crash20170920002409.zip](https://github.com/miranda-ng/miranda-ng/files/1315929/crash20170920002409.zip)

[crash20170920002525.zip](https://github.com/miranda-ng/miranda-ng/files/1315931/crash20170920002525.zip)

**Comment by georgehazan** [comment]
do you have AIM?

**Comment by dartraiden** [comment]
No

https://vi.miranda-ng.org/detail/dartraiden
