### ISSUE TITLE
Crash in service mode

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#939]
* Launch profile manager (ShowProfileMgr=yes in mirandaboot.ini)
 * Try to start Miranda in service mode with CrashDumper, DbEditor or Import.
 
100% crash for me and @Goraf. Crashlog available only if I try to launch CrashDumper. In all other cases, Miranda crashed silently.

Launch via /svc: command line is OK.

[Crashlog](https://pastebin.com/tTWZQyQt)
[VersionInfo](https://vi.miranda-ng.org/detail/dartraiden)

Tested with 32- and 64-bit Miranda on x64 system.

**Comment by dartraiden** [comment]
After the last commits:

- Import and DbEditor  - no crashes.
- CrashDumper now show his window but crashes after this

Also:
- If I run Miranda via Miranda64.exe (ShowProfileMgr=yes in mirandaboot.ini) I cannot launch DbChecker (it's not presented in the menu). But if I run Miranda64.exe" /svc:dbchecker and check "Run Miranda with this profile" option, I can select DbChecker from menu and Miranda silently crashes.

**Comment by georgehazan** [comment]
@dartraiden I can't reproduce it with CrashDumper :(

**Comment by dartraiden** [comment]
Still crashes.
