### ISSUE TITLE
Facebook newsfeed 

### ISSUE THREAD

**Issue by newsjunkie247** [miranda-ng/miranda-ng#940]
Unfortunately I think Facebook newsfeed/ticker have stopped working again in the latest versions.

**Comment by newsjunkie247** [comment]
Actually, Ticker seems to work but Newsfeed isn't at the moment.

**Comment by newsjunkie247** [comment]
I'm sorry you've left @Robyer Any way this can still be fixed?

**Comment by newsjunkie247** [comment]
And also if somebody could please fix this issue as well: https://github.com/miranda-ng/miranda-ng/issues/964 It was temporarily working again a few weeks ago but then stopped again)

**Comment by Robyer** [comment]
Yes, someone will take care of FB plugin. Give it some time (few weeks).

**Comment by dartraiden** [comment]
We need to implement newsfeed support in new FB protocol.
https://github.com/miranda-ng/miranda-ng/issues/2162
