### ISSUE TITLE
TabsRMM: wrong codepage/UTF-8 text string parser in native dialogs log messages (only in %M message string)

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#963]
TabsRMM: wrong codepage/UTF-8 parser in native TabsRMM dialogs log messages (only in %M message string)
In chat all is normal, problem only in dialogs. On Windows XP, dependant on VC2017 plugin compiler. Don't dependant on MSVC lib versions.

![cmfvxl3u 1](https://user-images.githubusercontent.com/7928889/31048640-4a8e2aca-a62a-11e7-9403-41bd5d2d622c.png)

**Comment by dartraiden** [comment]
Same on Windows 7

**Comment by ElzorFox** [comment]
Same on Windows 10.
Send 'лол' for reproducing.

**Comment by dartraiden** [comment]
Yes. Windows 10:

![2017-10-01_15h12_52](https://user-images.githubusercontent.com/5046855/31054435-14f5e812-a6bb-11e7-9332-1d9f79f95108.png)

**Comment by UksusoFF** [comment]
@ElzorFox I can reproduce this with any short message (<4 symbols) without spaces.
![image](https://user-images.githubusercontent.com/1931442/31054930-8893ee2e-a6cd-11e7-9243-9678ba6e006c.png)
![image](https://user-images.githubusercontent.com/1931442/31054934-93b37522-a6cd-11e7-94e3-f97bfe1adde6.png)

**Comment by ghsrcgh** [comment]
Confirming that issue. It depend on some chars of the message. Short/long message is not important. (I have the same issues with long messages, just they have some chars or something).

TabSRMM window - wrong chars
MsgExport - all is ok (with the same message)
History++ - all is ok (with the same message)

Issue occurs after last update.
Current version is: 

[spoiler=VersionInfo][quote]Miranda NG Version: 0.95.7 alpha build #18634 (cd5aa86) x64
Build time: 1 Oct 2017 0:31:42

[b]Active Plugins (21):[/b]
..
¤ HistoryPP.dll v.[b]1.5.1.5[/b] [24 Sep 2017 22:15:30] - History++ 
...
¤ Msg_Export.dll v.[b]3.1.2.1[/b] [1 Oct 2017 0:32:22] - Message export 
...
¤ TabSRMM.dll v.[b]3.5.0.6[/b] [1 Oct 2017 0:31:54] - TabSRMM 
[/quote][/spoiler]

**Comment by Corak667** [comment]
@ghsrcgh in TabSRMM code nothing was changed, the only difference are MSVC2017 compiler used to build.

**Comment by UksusoFF** [comment]
@georgehazan some troubles still here:
![image](https://user-images.githubusercontent.com/1931442/31069158-466e80f0-a76c-11e7-9b0c-970e358c15a3.png)

**Comment by georgehazan** [comment]
I can't even imagine what might that be, Could it be smth VK-dependent? All contacts / chats are working like this one?
