### ISSUE TITLE
Adding a New Client Type to FingerPrint

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#966]
> Is it possible for an end user to add a new Client Type and Icon to be displayed along side a contact in the contact list area of NG?  I use the FingerPrint plugin which I believe is where this would have to take place (but could be wrong).
> 
> I work with a platform called MetaSwitch that has a VoIP / IM soft client called Accession.  The IM portion of their application uses the XMPP protocol which I have a working account in Miranda NG, everything works great I just can't figure out how to get NG to display a custom Client Icon.

https://forum.miranda-ng.org/index.php?topic=5306

**Comment by georgehazan** [comment]
надо перенести в Вики как-то по фингеру... в каталог с профилем надо положить файл с именем fingerprint.json следующего содержания

```
{
   "groups": [
	{"code":3001, "name":"Miranda clients"},
	{"code":3002, "name":"Miranda version overlays"},
	{"code":3003, "name":"Miranda packs overlays"},

	{"code":3004, "name":"multi-protocol clients"},
	{"code":3006, "name":"Gadu-Gadu clients"},
	{"code":3008, "name":"ICQ clients"},
	{"code":3009, "name":"IRC clients"},
	{"code":3010, "name":"Jabber clients"},
	{"code":3014, "name":"RSS clients"},
	{"code":3016, "name":"Weather clients"},
	{"code":3018, "name":"Facebook clients"},
	{"code":3019, "name":"VK clients"},

	{"code":3020, "name":"other protocols"},
	{"code":3021, "name":"other icons"},

	{"code":3022, "name":"resource overlays"},
	{"code":3023, "name":"platforms overlays"},
	{"code":3024, "name":"protocols overlays"},
	{"code":3025, "name":"unicode overlay"},
	{"code":3026, "name":"security overlays"}
   ],

   "masks": [
	{"name": "boo", "descr":"That's a boo", "mask": "Something unusual", "iconFile": "Icons\blablabla.dll", "iconIndex": 126, "group": 3020}
   ]
}

```

**Comment by georgehazan** [comment]
маски можно набивать сколько угодно.
