### ISSUE TITLE
Recent development builds can't start on Windows XP (32 bit)

### ISSUE THREAD

**Issue by Robyer** [miranda-ng/miranda-ng#974]
User reported that after update (to development build) whole Miranda can't start again. It shows system error dialog that application caused error and was terminated (it's my translation from czech error message).

**Comment by georgehazan** [comment]
which dialog? is there a screenshot?

**Comment by georgehazan** [comment]
Miranda requires vs2017 runtime now, it should be packed into miranda32.zip

**Comment by Robyer** [comment]
![22278492_869185916590560_1437305180_n](https://user-images.githubusercontent.com/359173/31247247-3d6fdeda-aa10-11e7-980c-c6c68df3097b.jpg)
![22237193_869185919923893_1008686983_n](https://user-images.githubusercontent.com/359173/31247246-3d6bd5c4-aa10-11e7-9103-27b2284f724e.jpg)

**Comment by Robyer** [comment]
Ok, I'll let him know to try to install vs2017 runtime.

But the update process should be fixed somehow, to automatically install runtime if it's not installed. 

And/or is it possible to show better error dialog than this windows' error dialog? Something to let user know he is missing the vs2017 runtime with link to download it?

**Comment by georgehazan** [comment]
what about crash log? is CrashDumper available?

**Comment by georgehazan** [comment]
runtime is already present inside miranda32.zip

**Comment by Robyer** [comment]
No crashlog it seems. And he is not responding anymore currently.

**Comment by georgehazan** [comment]
maybe there's an old dll... is that possible to remove all older dlls from Plugins folder?

**Comment by Robyer** [comment]
There isn't. I told him to try clean Miranda from website. I understand he downloaded stable version, then switched in PU to development, let it update, and same result. (Also dartraiden posted some other issue #975)

**Comment by dartraiden** [comment]
We have some issues, installer don't install 2010 Runtime.

**Comment by dartraiden** [comment]
@Robyer, ghazan just fixed installer, so all should correct installing and run

**Comment by Robyer** [comment]
Yes, user confirmed it's solved now.
