### ISSUE TITLE
MSN: cannot delete contacts

### ISSUE THREAD

**Issue by theultramage** [miranda-ng/miranda-ng#978]
For a very long time now, deleting a contact (and blocking / removing from address book) does not really delete them from the server. When the protocol reconnects, they appear in the contact list again. The Server List window claims that these contacts are still included in my server list.

**Comment by georgehazan** [comment]
pure MSN account cannot delete contacts associated with Skype accounts, 
you need to remove them from Skype

**Comment by theultramage** [comment]
I'm almost certain that these contacts do not show up in Skype. These were added long ago, before microsoft skype was a thing.

**Comment by georgehazan** [comment]
they don't, because you haven't attached your MSN account to Skype, but they did.
you can create a network log and read an error message there

**Comment by theultramage** [comment]
I will try doing it again and seeing if there's anything useful in the logs. IIRC there will be no errors and the operation will pretend to succeed. Not sure what to do if the servers themselves are broken...
