### ISSUE TITLE
No compatible file transfer mechanism exists

### ISSUE THREAD

**Issue by bol-van** [miranda-ng/miranda-ng#987]
When using jabber protocol
miranda-ng-v0.95.6  cannot send files to older versions (for example miranda-ng-v0.95.4 or miranda classis/not-NG)
Older clients can send files to 0.95.6

Direct peer-to-peer connection is turned off

**Comment by bol-van** [comment]
old version

in function CJabberProto::SendFile
	JabberCapsBits jcb = GetResourceCapabilites(item->jid, TRUE);

jcb = 0x000003526467fcff

in new version

jcb = 0

So its regression in caps detection code

**Comment by georgehazan** [comment]
нужен MirVer того контакта, у которого файл не ходит

**Comment by bol-van** [comment]
Релизная x64 версия с оф сайта
У другого , например, miranda классик

**Comment by georgehazan** [comment]
нужен конкретный MirVer это контакта. его можно посмотреть в dbeditor в базе

**Comment by bol-van** [comment]
Miranda IM Jabber 0.10.24.0
Miranda NG Jabber 0.95.4.0 x64 (SecureIM)

**Comment by georgehazan** [comment]
пофиксил в девелоперской версии, если оно там заработает, перенесу в стаблю

**Comment by yardstudio** [comment]
I have this trouble too. Can´t send files to Google Hangouts contact
![2018-10-26_14-10-47](https://user-images.githubusercontent.com/25852179/47565714-b64a2880-d929-11e8-8102-84425d973461.png)

[spoiler=VersionInfo][quote]CPU: Intel(R) Xeon(R) CPU E3-1220 v3 @ 3.10GHz [Intel64 Family 6 Model 60 Stepping 3] [DEP Enabled] [4 CPUs]
Installed RAM: 16301 MBytes
Microsoft Windows 7 Professional Edition, 64-bit Service Pack 1 (build 7601)
Internet Explorer: 9.11.9600.19129 (build 99600)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : English/English | Slovak/Slovak
Free disk space on Miranda partition: 22982 MBytes

Miranda NG Version: 0.95.9.1 build #20741 (f6ac44d1b1) [running inside WOW64]
Build time: 10 Oct 2018 13:49:42
Profile: I:\PortableAPPS\Miranda_Im_Portable_ROBYER\Profiles\profile\profile.dat
Profile size: 100663296 Bytes
Profile creation date: 8 Oct 2018 14:31:21
Language pack: Czech (CZ) [0405]
Service Mode: No

[b]Active Plugins (33):[/b]
¤ AVS.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:57:46] - Avatar service 
¤ Clist_modern.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:58:16] - Modern contact list 
¤ CrashDumper.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:58:14] - Crash dumper 
¤ Db_autobackups.dll v.[b]0.95.9.0[/b] [10 Oct 2018 13:49:54] - Db autobackuper 
¤ DbEditorPP.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:58:16] - Database editor++ 
¤ Dbx_mdbx.dll v.[b]0.95.9.0[/b] [10 Oct 2018 13:51:22] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.[b]0.95.9.0[/b] [10 Oct 2018 13:49:46] - Miranda NG mmap database driver 
¤ Dummy.dll v.[b]0.95.9.0[/b] [10 Oct 2018 13:50:48] - Dummy protocol 
¤ Facebook.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:58:20] - Facebook 
¤ Folders.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:57:52] - Custom profile folders 
¤ historypp.dll v.[b]1.5.1.5[/b] [8 Oct 2018 19:59:22] - History++ 
¤ HistoryStats.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:59:06] - HistoryStats 
¤ ICQ.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:57:52] - IcqOscarJ protocol 
¤ Jabber.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:58:24] - Jabber protocol 
¤ MenuEx.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:57:56] - Menu item ext 
¤ MobileState.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:58:22] - Mobile state 
¤ MSN.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:58:18] - MSN protocol 
¤ mTextControl.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:57:56] - Miranda text control 
¤ MyDetails.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:58:18] - My details 
¤ NewXstatusNotify.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:57:58] - xStatus notify 
¤ PluginUpdater.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:58:24] - Plugin updater 
¤ PManagerEx.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:58:18] - Miranda NG profile changer 
¤ QuickSearch.dll v.[b]1.4.2.0[/b] [8 Oct 2018 19:59:20] - Quick Search 
¤ SeenPlugin.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:57:58] - Last seen 
¤ Sessions.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:58:00] - Sessions 
¤ SimpleStatusMsg.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:58:08] - Simple status message 
¤ Spamotron.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:58:36] - Spam-o-tron 
¤ StartPosition.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:58:30] - Start position 
¤ StatusManager.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:58:56] - Status manager 
¤ TabSRMM.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:57:54] - TabSRMM 
¤ TopToolBar.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:58:08] - TopToolBar 
¤ UInfoEx.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:58:08] - User info ext 
¤ Variables.dll v.[b]0.95.9.0[/b] [8 Oct 2018 19:58:20] - Variables 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
Facebook                 1 - Enabled 0 - Disabled  Loaded
ICQ                      1 - Enabled 0 - Disabled  Loaded
JABBER                   1 - Enabled 1 - Disabled  Loaded
MSN                      0 - Enabled 1 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 2.ico [8 Jun 2010 18:37:33]
 3.ico [8 Jun 2010 18:37:33]
 4.ico [8 Jun 2010 18:37:33]
 5.ico [8 Jun 2010 18:37:33]
 Fp_icons.dll [8 Oct 2018 19:59:18]
 HistoryPP_icons.dll [8 Oct 2018 19:59:16]
 Proto_AIM.dll [12 Dec 2017 5:06:28]
 proto_conn_facebook.dll [5 Mar 2011 20:37:51]
 proto_conn_icq.dll [31 May 2010 23:26:04]
 proto_conn_irc.dll [27 Aug 2007 9:43:50]
 proto_conn_jabber.dll [18 Jul 2008 14:09:44]
 proto_conn_msn.dll [27 Aug 2007 9:43:52]
 Proto_Dummy.dll [10 Oct 2018 13:51:44]
 Proto_Facebook.dll [8 Oct 2018 19:59:16]
 Proto_GG.dll [8 Oct 2018 19:59:16]
 proto_global_.dll [6 Jun 2010 18:47:16]
 Proto_ICQ.dll [8 Oct 2018 19:59:16]
 Proto_IRC.dll [8 Oct 2018 19:59:16]
 Proto_Jabber.dll [8 Oct 2018 19:59:16]
 Proto_MetaContacts.dll [10 Oct 2018 13:51:44]
 Proto_mRadio.dll [8 Oct 2018 19:59:18]
 Proto_MSN.dll [8 Oct 2018 19:59:16]
 proto_mtv.dll [6 Sep 2010 1:14:18]
 Proto_Omegle.dll [8 Oct 2018 19:59:16]
 Proto_Weather.dll [8 Oct 2018 19:59:18]
 Proto_Yahoo.dll [24 Sep 2016 4:01:40]
 TabSRMM_icons.dll [8 Oct 2018 19:59:18]
 Toolbar_icons.dll [8 Oct 2018 19:59:16]
 UInfoEx_icons.dll [8 Oct 2018 19:59:16]
 Watrack_buttons.dll [8 Oct 2018 19:59:20]
 Watrack_icons.dll [8 Oct 2018 19:59:20]
 xStatus_ICQ.dll [8 Oct 2018 19:59:16]
 xStatus_Jabber.dll [8 Oct 2018 19:59:16]
[/quote][/spoiler]
