### ISSUE TITLE
[Facebook] losing connection repeatedly

### ISSUE THREAD

**Issue by seg-on** [miranda-ng/miranda-ng#989]
After latest development update, facebook protocol is losing connection very quickly (in 2-3 minutes).

```
CPU: Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz [Intel64 Family 6 Model 42 Stepping 7] [DEP Enabled] [4 CPUs]
Installed RAM: 8127 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 15063)
Internet Explorer: 9.11.15063.0 (build 915063)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : Slovak/Slovak | Slovak/Slovak
Free disk space on Miranda partition: 100612 MBytes

Miranda NG Version: 0.95.7 alpha build #18678 (0100ad63ea) [running inside WOW64]
Build time: 12 Oct 2017 4:04:02
Profile: C:\Program Files\Miranda NG\Profiles\segi\segi.dat (dbx mmap driver)
Profile size: 20119552 Bytes
Profile creation date: 30 May 2017 10:34:57
Language pack: Czech (CZ) [0405]
Service Mode: No

Active Plugins (29):
¤ AdvaImg.dll v.0.11.0.2 [11 Oct 2017 4:12:48] - Miranda image services 
¤ AVS.dll v.0.95.3.4 [11 Oct 2017 4:05:30] - Avatar service 
¤ Clist_nicer.dll v.0.9.2.4 [11 Oct 2017 4:06:34] - Clist nicer 
¤ Cln_skinedit.dll v.0.0.0.4 [11 Oct 2017 4:06:26] - Skin editor for Clist nicer 
¤ CrashDumper.dll v.0.0.5.2 [11 Oct 2017 4:10:32] - Crash dumper 
¤ DbEditorPP.dll v.4.0.1.1 [11 Oct 2017 4:10:32] - Database editor++ 
¤ Dbx_mmap.dll v.0.95.3.1 [12 Oct 2017 4:06:36] - Miranda NG mmap database driver 
¤ Facebook.dll v.0.3.3.2 [11 Oct 2017 4:12:26] - Facebook RM 
¤ Fingerprint.dll v.0.1.0.0 [11 Oct 2017 4:13:18] - Fingerprint NG 
¤ HistoryPP.dll v.1.5.1.5 [24 Sep 2017 22:15:24] - History++ 
¤ HistoryStats.dll v.0.2.1.1 [11 Oct 2017 4:15:44] - HistoryStats 
¤ ICQ.dll v.0.11.3.5 [11 Oct 2017 4:06:10] - IcqOscarJ protocol 
¤ Import.dll v.0.95.4.3 [11 Oct 2017 4:05:32] - Import contacts and messages 
¤ Jabber.dll v.0.11.0.5 [11 Oct 2017 4:06:36] - Jabber protocol 
¤ mTextControl.dll v.0.8.0.1 [11 Oct 2017 4:07:20] - Miranda text control 
¤ PluginUpdater.dll v.0.1.2.5 [11 Oct 2017 4:12:30] - Plugin updater 
¤ Popup.dll v.2.1.1.12 [11 Oct 2017 4:07:30] - Popup plus 
¤ QuickSearch.dll v.1.4.2.0 [24 Sep 2017 23:04:32] - Quick Search 
¤ SeenPlugin.dll v.5.0.5.3 [11 Oct 2017 4:07:34] - Last seen 
¤ SkypeWeb.dll v.0.12.2.4 [11 Oct 2017 4:16:08] - Skype protocol (Web) 
¤ SmileyAdd.dll v.0.2.4.1 [11 Oct 2017 4:07:42] - SmileyAdd 
¤ SpellChecker.dll v.0.2.6.4 [11 Oct 2017 4:09:28] - Spell checker 
¤ StatusManager.dll v.0.11.2.1 [11 Oct 2017 4:17:46] - Status manager 
¤ TabSRMM.dll v.3.5.0.6 [11 Oct 2017 4:06:26] - TabSRMM 
¤ Tipper.dll v.2.1.0.7 [11 Oct 2017 4:07:46] - Tipper 
¤ TopToolBar.dll v.0.8.0.4 [11 Oct 2017 4:08:42] - TopToolBar 
¤ UInfoEx.dll v.0.8.5.0 [11 Oct 2017 4:07:56] - User info ext 
¤ Weather.dll v.0.4.0.3 [11 Oct 2017 4:13:22] - Weather 
¤ WhatsApp.dll v.0.1.3.3 [11 Oct 2017 4:16:02] - WhatsApp protocol 

Unloadable Plugins (1):
¤ DbChecker.dll v.0.0.0.0 [12 Oct 2017 4:11:56] - <unknown> 


Weather ini files:
-------------------------------------------------------------------------------
 gismeteo.ini v.2012.05.03 [11 Oct 2016 16:18:02] - GisMeteo
 msn.ini v.2014-11-08 [11 Oct 2016 16:18:02] - MSN Weather (New Layout)
 weatherxml.ini v.0.0.5.3 2009-07-16 [11 Oct 2016 16:18:02] - WeatherXML
 wundergrnd_intl.ini v.2011/02/13 [11 Oct 2016 16:18:02] - Weather Underground Int'l
 wundergrnd_xml.ini v.2011/02/13 [11 Oct 2016 16:18:02] - Weather Underground XML

Protocols and Accounts:
-------------------------------------------------------------------------------
Facebook                 1 - Enabled 0 - Disabled  Loaded
ICQ                      1 - Enabled 0 - Disabled  Loaded
JABBER                   4 - Enabled 1 - Disabled  Loaded
SKYPE                    1 - Enabled 0 - Disabled  Loaded
WhatsApp                 0 - Enabled 1 - Disabled  Loaded
MetaContacts             1 - Enabled 0 - Disabled  Loaded
SkypeClassic             0 - Enabled 1 - Disabled  Not Loaded
Weather                  1 - Enabled 0 - Disabled  Loaded

Icon Packs:
-------------------------------------------------------------------------------
 Avonlea Light.icl [21 Mar 2012 18:07:17]
 Flags_icons.dll [11 Oct 2017 4:17:48]
 Fp_icons.dll [11 Oct 2017 4:17:50]
 gtalk-gmailcoloredballs-v2.dll [7 Sep 2005 23:44:30]
 HistoryPP_icons.dll [11 Oct 2017 4:17:50]
 proto_ball1.dll [4 Sep 2005 16:52:06]
 proto_conn_facebook.dll [5 Mar 2011 21:37:52]
 Proto_Facebook.dll [11 Oct 2017 4:17:48]
 proto_gtalk.dll [24 Oct 2012 10:12:26]
 Proto_ICQ.dll [11 Oct 2017 4:17:48]
 Proto_Jabber.dll [11 Oct 2017 4:17:48]
 Proto_MetaContacts.dll [12 Oct 2017 4:28:42]
 Proto_Skype.dll [11 Oct 2017 4:17:52]
 Proto_Weather.dll [11 Oct 2017 4:17:50]
 Proto_WhatsApp.dll [11 Oct 2017 4:17:50]
 TabSRMM_icons.dll [11 Oct 2017 4:17:50]
 Toolbar_icons.dll [11 Oct 2017 4:17:48]
 UInfoEx_icons.dll [11 Oct 2017 4:17:48]
 xStatus_ICQ.dll [11 Oct 2017 4:17:50]
 xStatus_Jabber.dll [11 Oct 2017 4:17:50]
 zoho.dll [2 Feb 2017 18:57:19]
```

**Comment by Robyer** [comment]
@georgehazan Any idea what was changed? In netlog it shows "src\netlibhttp.cpp 523: HttpPeekFirstResponseLine Failed (1460 10)" errors.

**Comment by georgehazan** [comment]
W:\>net helpmsg 1460
This operation returned because the timeout period expired.

**Comment by georgehazan** [comment]
looks like social networks are physically disabled in his network

**Comment by seg-on** [comment]
What you mean? We don't have any restriction to internet on our network and I think that provider have no restriction too.

**Comment by georgehazan** [comment]
I meant that the http request was rejected with timeout error.

**Comment by Goraf** [comment]
Turned off FB protocol for a while, and now I don't see those entries anymore

**Comment by seg-on** [comment]
At home I dosen't apply the last updates and looks that all works properly.
Tomorrow I can try revert last update changes from update backup and see if it will work or not.

Miranda at home:
[spoiler=VersionInfo][quote]CPU: Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz [Intel64 Family 6 Model 58 Stepping 9] [DEP Enabled] [4 CPUs]
Installed RAM: 12174 MBytes
Microsoft Windows 10 Professional Edition, 64-bit (build 15063)
Internet Explorer: 9.11.15063.0 (build 915063)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | Slovak/English
Free disk space on Miranda partition: 176258 MBytes

Miranda NG Version: 0.95.7 alpha build #18664 (819f67e) x64
Build time: 8 Oct 2017 10:23:00
Profile: C:\Users\tvanc\AppData\Roaming\Miranda NG\segi\segi.dat (dbx mmap driver)
Profile size: 20512768 Bytes
Profile creation date: 16 Jun 2017 21:18:29
Language pack: Czech (CZ) [0405]
Service Mode: No

[b]Active Plugins (26):[/b]
¤ AdvaImg.dll v.[b]0.11.0.2[/b] [5 Oct 2017 16:11:48] - Miranda image services 
¤ AVS.dll v.[b]0.95.3.4[/b] [5 Oct 2017 16:10:22] - Avatar service 
¤ Clist_nicer.dll v.[b]0.9.2.4[/b] [5 Oct 2017 16:10:30] - Clist nicer 
¤ Cln_skinedit.dll v.[b]0.0.0.4[/b] [5 Oct 2017 16:10:22] - Skin editor for Clist nicer 
¤ CrashDumper.dll v.[b]0.0.5.2[/b] [5 Oct 2017 16:10:56] - Crash dumper 
¤ DbEditorPP.dll v.[b]4.0.1.1[/b] [5 Oct 2017 16:10:52] - Database editor++ 
¤ Dbx_mmap.dll v.[b]0.95.3.1[/b] [8 Oct 2017 10:23:04] - Miranda NG mmap database driver 
¤ Facebook.dll v.[b]0.3.3.2[/b] [5 Oct 2017 16:10:58] - Facebook RM 
																		  
¤ HistoryPP.dll v.[b]1.5.1.5[/b] [24 Sep 2017 22:15:30] - History++ 
¤ HistoryStats.dll v.[b]0.2.1.1[/b] [5 Oct 2017 16:11:54] - HistoryStats 
¤ ICQ.dll v.[b]0.11.3.5[/b] [5 Oct 2017 16:10:30] - IcqOscarJ protocol 
¤ Import.dll v.[b]0.95.4.3[/b] [5 Oct 2017 16:10:22] - Import contacts and messages 
¤ Jabber.dll v.[b]0.11.0.5[/b] [5 Oct 2017 16:10:54] - Jabber protocol 
																				 
¤ PluginUpdater.dll v.[b]0.1.2.5[/b] [8 Oct 2017 10:23:46] - Plugin updater 
¤ Popup.dll v.[b]2.1.1.12[/b] [5 Oct 2017 16:10:36] - Popup plus 
¤ QuickSearch.dll v.[b]1.4.2.0[/b] [25 Sep 2017 18:01:42] - Quick Search 
¤ SeenPlugin.dll v.[b]5.0.5.3[/b] [5 Oct 2017 16:10:34] - Last seen 
¤ SkypeWeb.dll v.[b]0.12.2.4[/b] [5 Oct 2017 16:11:40] - Skype protocol (Web) 
¤ SmileyAdd.dll v.[b]0.2.4.1[/b] [5 Oct 2017 16:10:42] - SmileyAdd 
¤ SpellChecker.dll v.[b]0.2.6.4[/b] [5 Oct 2017 16:11:24] - Spell checker 
¤ StatusManager.dll v.[b]0.11.2.0[/b] [5 Oct 2017 16:11:42] - Status manager 
¤ TabSRMM.dll v.[b]3.5.0.6[/b] [5 Oct 2017 16:10:32] - TabSRMM 
¤ Tipper.dll v.[b]2.1.0.7[/b] [5 Oct 2017 16:10:38] - Tipper 
¤ TopToolBar.dll v.[b]0.8.0.4[/b] [5 Oct 2017 16:10:44] - TopToolBar 
¤ UInfoEx.dll v.[b]0.8.5.0[/b] [5 Oct 2017 16:10:46] - User info ext 
¤ Weather.dll v.[b]0.4.0.3[/b] [5 Oct 2017 16:11:06] - Weather 
																		  

[b]Unloadable Plugins (1):[/b]
¤ DbChecker.dll v.[b]0.0.0.0[/b] [8 Oct 2017 10:23:46] - <unknown> 

						 

[b]Weather ini files:[/b]
-------------------------------------------------------------------------------
 gismeteo.ini v.[b]2012.05.03[/b] [12 Aug 2017 11:23:46] - GisMeteo
 msn.ini v.[b]2014-11-08[/b] [12 Aug 2017 11:23:46] - MSN Weather (New Layout)
 weatherxml.ini v.[b]0.0.5.3 2009-07-16[/b] [12 Aug 2017 11:23:46] - WeatherXML
 wundergrnd_intl.ini v.[b]2011/02/13[/b] [12 Aug 2017 11:23:46] - Weather Underground Int'l
 wundergrnd_xml.ini v.[b]2011/02/13[/b] [12 Aug 2017 11:23:46] - Weather Underground XML

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
Facebook                 1 - Enabled 0 - Disabled  Loaded
ICQ                      1 - Enabled 0 - Disabled  Loaded
JABBER                   3 - Enabled 2 - Disabled  Loaded
SKYPE                    1 - Enabled 0 - Disabled  Loaded
										
MetaContacts             1 - Enabled 0 - Disabled  Loaded
SkypeClassic             0 - Enabled 1 - Disabled  Not Loaded
Weather                  1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 available.ico [27 Sep 2008 7:04:30]
 Avonlea Light.icl [21 Mar 2012 18:07:18]
 away.ico [27 Sep 2008 7:04:54]
 content.ico [27 Sep 2008 7:05:10]
 enteredtext.ico [27 Sep 2008 7:05:26]
 Flags_icons.dll [5 Oct 2017 16:12:44]
 Fp_icons.dll [5 Oct 2017 16:12:46]
 gtalk-gmailcoloredballs-v2.dll [7 Sep 2005 23:44:30]
 HistoryPP_icons.dll [5 Oct 2017 16:12:46]
 idle.ico [27 Sep 2008 7:05:42]
 invisible.ico [27 Sep 2008 7:06:00]
 mobile.old.ico [27 Sep 2008 7:06:54]
 offline.ico [27 Sep 2008 7:07:24]
 Proto_AIM.dll [5 Oct 2017 16:12:44]
 proto_ball1.dll [4 Sep 2005 16:52:06]
 proto_conn_facebook.dll [5 Mar 2011 21:37:52]
 Proto_Facebook.dll [5 Oct 2017 16:12:44]
 Proto_GG.dll [5 Oct 2017 16:12:46]
 proto_gtalk.dll [24 Oct 2012 10:12:26]
 Proto_ICQ.dll [5 Oct 2017 16:12:44]
 Proto_IRC.dll [5 Oct 2017 16:12:44]
 Proto_Jabber.dll [5 Oct 2017 16:12:44]
 Proto_MetaContacts.dll [8 Oct 2017 10:25:36]
 Proto_MSN.dll [5 Oct 2017 16:12:46]
 Proto_Skype.dll [5 Oct 2017 16:12:46]
 Proto_Weather.dll [5 Oct 2017 16:12:46]
 Proto_Yahoo.dll [25 May 2015 10:24:38]
 SecureIM_icons.dll [5 Oct 2017 16:12:44]
 TabSRMM_icons.dll [5 Oct 2017 16:12:46]
 Toolbar_icons.dll [5 Oct 2017 16:12:46]
 UInfoEx_icons.dll [5 Oct 2017 16:12:44]
 xStatus_ICQ.dll [5 Oct 2017 16:12:46]
 xStatus_Jabber.dll [5 Oct 2017 16:12:46]
 zoho.dll [2 Feb 2017 18:57:19]
[/quote][/spoiler]

**Comment by seg-on** [comment]
I'm copy facebook.dll from updater backup (there was difference in size approximately 500B) and looks that works fine.
I'm looking on commits for facebook plugin on github but there is latest changes only in text for about.
Here is the working file: www.segi.wz.cz/tmp/Facebook.dll

**Comment by Robyer** [comment]
@georgehazan As it works with previous version, it must be some change in core. I was fixing similar issue in Core before: https://github.com/miranda-ng/miranda-ng/commit/f631072b6932918a4ee19ff64532cd4494f8e9e4#diff-25d902c24283ab8cfbac54dfa101ad31

**Comment by dartraiden** [comment]
@Robyer But how reverting only Facebook.dll can solve a problem with core?

**Comment by Robyer** [comment]
@dartraiden Hmm, good point. Is anyone else having same issues like OP?

@seg-on Can you verify how it works in completely clean Miranda (freshly downloaded from website)? And for both stable version + development version.

**Comment by seg-on** [comment]
@Robyer I download  zip for 64bit stable and alpha version. Have run all Miranda's. My actual install, latest stable and latest alpha and looks like that all works. It is possible that simultaneous run can have effect to stability?

**Comment by Robyer** [comment]
@seg-on I don't know. Anything new with your issue?

**Comment by seg-on** [comment]
I install full clean latest alpha version, migrate contact and history, but not plugins configuration. Plugins setup manually. Now it looks it's working good.
I don't know if it can was in updating or very old miranda configuration.
