### ISSUE TITLE
Icons in message log missing (TabSRMM)

### ISSUE THREAD

**Issue by Huhnmann** [miranda-ng/miranda-ng#995]
### Expected behavior
Icons being shown in message log.

### Actual behavior
A dot is displayed where the icon should be.

![jzkexew](https://user-images.githubusercontent.com/32650705/31548254-8e11c964-b02a-11e7-8099-f612331c4e45.png)

### Does it work in stable version?
Nope. I can't remember the last time it worked. Could be before switching to NG, actually.

### Steps to reproduce that behavior
Adding icons to message log, I guess.

### Version

v0.95.6 #18511, updater shows no new updates.

**Comment by Robyer** [comment]
@georgehazan I think we discussed this already, but now it's interesting that in Preview is icon showed correctly. Can you compare what's different there?

**Comment by Huhnmann** [comment]
It seems to have stopped working after installing Win 10 Anniversary Update.

**Comment by georgehazan** [comment]
@Robyer yes, that bug was definitely reported before, moreover, SRMM revolution began because of it :) but I can't find it here...

**Comment by Robyer** [comment]
@georgehazan I mentioned this because you said that RichEdit doesn't show the icon for some unknown reason. But here in Preview window it seems to correctly show the icon - can you compare source code of Preview window vs. Message log to perhaps see the issue what is done differently in Message log?

**Comment by georgehazan** [comment]
well. I know the commit that introduced this problem - 3.5 years ago :) migration from richedit20 to msftedit. I also compared the rtf code that gets passed to both controls - it is identical. Dunno what else might that be, cause 3.5 yrs ago there were no UI classes etc

**Comment by dartraiden** [comment]
Accidentally fixed as a result of recent major changes
