### ISSUE TITLE
Facebook: false loading full chathistory

### ISSUE THREAD

**Issue by facled** [miranda-ng/miranda-ng#998]
i have a problem with manually loading full chathistory from facebook
i delete history and than it should loading full history from facebook but it saves only the last 2 days.
and how you can see on screenshot with multiple doubles messages.
i restarted miranda but same problem

[Versioninfo.txt](https://github.com/miranda-ng/miranda-ng/files/1385339/Versioninfo.txt)

![fb2](https://user-images.githubusercontent.com/23004217/31583896-83b1145a-b1a3-11e7-9f1e-e251d87c2a7f.png)

**Comment by zemiacsik** [comment]
This should be fixed atm. #1095 
Although not exactly all messages from the past are loaded - it stops at some point, e.g. I know I have history with someone since 2013 but it loaded only since the July of 2014, I will investigate this later.. if they don't exist anymore or what.

**Comment by zemiacsik** [comment]
Missing messages are fixed in current version.
